### ISSUE TITLE
How do I switch cores? (GBA bios issue)

### ISSUE THREAD

**Issue by FraserMcGovern** [OpenEmu/OpenEmu#1002]
Whenever I try to play a GBA game, I get an error message telling me that I need a "Game Boy Advance BiOS". I've tried downloading it and dragging it into OpenEmu, but it doesn't seem to pick it up. 

From what I can gather, GBA games aren't playing because the core that is being used (higan) needs this bios file. I think that if I use the VisualBoyAdvance core it will work, but I don't know how to switch. I've installed all cores in the "Preferences>Cores" menu.

I'm sure I'm missing something. Any help would be appreciated! Thanks.

**Comment by an0nny** [comment]
I typed the command and played the game. But it crashed

**Comment by LelouchvBrutania** [comment]
I was playing pokemon light platinum (rom hack) and was playing on wrong core (mGBA) and didn't know until i evolved pokemon and then my game just got a black screen same thing with trading and i need to switch to Visual Boy Advanced without losing save files could you please help.

**Comment by LelouchvBrutania** [comment]
I was playing pokemon light platinum (rom hack) and was playing on wrong core (mGBA) and didn't know until i evolved pokemon and then my game just got a black screen same thing with trading and i need to switch to Visual Boy Advanced without losing save files could you please help.
