### ISSUE TITLE
Space to Quickview (enlarge cover art) instead of open

### ISSUE THREAD

**Issue by aristidesfl** [OpenEmu/OpenEmu#1012]
I've opened games many times by pressing space when I really wanted to have a better look at the cover art.

Being the cover art one of the killer features of OpenEmu (imho), is there a good reason for this ubiquitous behaviour to work differently inside OpenEmu?

**Comment by ron-wolf** [comment]
This actually seems fairly practical—there’s even a decent [QuickLook API doc](https://developer.apple.com/library/mac/documentation/UserExperience/Reference/Quicklook_Framework_Reference).

**Comment by clobber** [comment]
Nah, this isn't useful. You can just use coverflow or the slider to zoom in. We already decided long ago that 'spacebar' plays, kinda like iTunes.
