### ISSUE TITLE
Multiple save states?

### ISSUE THREAD

**Issue by cheeseandpepper** [OpenEmu/OpenEmu#1023]
It might be a good idea to have multiple save states or a save history.  My last save state was during a screen transition and now when I load it, the sound plays but the UI is frozen.  If only I could revert to my last save... I fear all my progress is now gone.

**Comment by em** [comment]
Same happened to me. Hours of gameplay lost. Pleeease make quicksave append to a FILO list instead of overwriting a single save file every time.
