### ISSUE TITLE
Nintendo DS, have screens Side by Side instead of Top and Bottom?

### ISSUE THREAD

**Issue by whatproblems** [OpenEmu/OpenEmu#1024]
Am I missing the setting for this? I downloaded another Emulator (sorry) to play the DS games because it's so much easier to play and on my eyes for them to be Side by Side. Is there any future plans on this? It's a GREAT thing to do. Uses most of my laptops screen, compared to maybe 1/3 of it before.

Upon downloading that other Emulator, I've got even more respect for OpenEmu and it's ease of use, speed, and lower overall CPU/GPU usage on my computer.

**Comment by robsonpeixoto** [comment]
Hi @clobber. It was implemented? If yes, how to configure it?
