### ISSUE TITLE
Cloning OpenEmu to other Mac not working correctly?

### ISSUE THREAD

**Issue by Denus01** [OpenEmu/OpenEmu#1029]
I have OpenEmu v.1.01 and a nice collection of roms.
The artwork is made by myself (screenshots of the startscreen).

Now: when I try to clone the whole installation from my iMac to my Mac Mini, the screenshots are shown correctly, but the roms are not found and cannot be started, despite the new path set correctly via preferences.

I made a copy of the folder (~/Emulation on both computers) where the roms are installed, and the OpenEmu folder from the Library folder.

When I try to correct this by dropping the roms again in OpenEmu, the roms are working but the screenshots are replaced by the online cover arts or the "testscreen" pic when nothing has been found.

What could be the issue here?

**Comment by cyco** [comment]
#1490
