### ISSUE TITLE
PSP choppy audio?

### ISSUE THREAD

**Issue by jasjeet86** [OpenEmu/OpenEmu#1036]
I have tried psp emulation with few iso's and it seems to be little slow and behind on audio and slow.Anyone else having that issue?

**Comment by teonimesic** [comment]
I also encountered this problem, but it doesn't seems to be the issue of emulation compatibility, as I've tried the same ISO on both OpenEmu and PPSSPP, and it performed way better in regards to choppy sound and slowdowns on the PPSSPP app. I uploaded two videos to demonstrate the issue:

* https://youtu.be/sQR0o1jr0zM (Choopy OpenEmu version), issue visible at 0:26
* https://youtu.be/AMBpQNPAJls (PPSSPP version)

My spec are:
* macOS 10.11.6
* MacBook Pro (Retina, 15-inch, Mid 2014)
* Nvidia GeForce GT 750M
* 15.4-inch (2880 x 1800)
* OpenEmu v2.0.4
* PPSSPP Core v1.3
* Filter applied was Pixellate. Also tried Nearest Neighbor, but both had the same issue
* And the PPSSPP App version used for comparison was v1.3-190-g4a78098

**Comment by mrvacbob** [comment]
The app and OpenEmu might have different JIT settings. Also, there might be something inaccurate about OE's audio timing/samplerate… wait… didn't we fix something like that in ppsspp?

**Comment by TempSpas** [comment]
Specs:

- macOS 10.12.5
- Macbook Pro (Retina, 13-inch, Early 2015)
- Intel Iris Graphics 6100 1536 MB
- OpenEmu v2.0.5
- Filter used is Nearest Neighbor. Tried Pixellate, same issue.
- PPSSPP version tested was v1.4.2-266-g2d5e7c834

The bug occurs on both **Final Fantasy Tactics: War of the Lions** and **Final Fantasy IV: The Complete Collection**, though it is much more severe on Lions. As such, that was the only one I tested on the standalone PPSSPP, and as I said it ran without issue. I didn't touch any settings, I just downloaded it and ran it and it worked fine.

**Comment by TempSpas** [comment]
The issue persists on macOS 10.12.6.

**Comment by danilobytes** [comment]
Same here. Same specs as @TempSpas.

**Comment by clobber** [comment]
https://github.com/OpenEmu/PPSSPP-Core/compare/c39fde54efbb...a7dce0b6fdbf

This should now be fixed the best it can be (for now, there seems to be some slight crackling in Final Fantasy Tactics that we believe is an upstream bug with PPSSPP: https://github.com/hrydgard/ppsspp/issues/9956). When the game drops framerate, especially in the battle animations, it doesn't appear to be returning a correct number of samples.

Restart the app and an updated PPSSPP core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for PPSSPP 1.4.2.

**Comment by nikolas** [comment]
There is stuttering audio during battles in Tactics Ogre: Let Us Cling Together, on OpenEMU 2.2.1, PPSSPP 1.9.3.1. I haven't tried standalone PPSSPP yet, but I'm about to, since it would be great if I could get this working better. I'm on macOS 10.15.5.

**Comment by nikolas** [comment]
So, this issue is fixed when running the latest git version of standalone PPSSPP (ba06c87a7dd953ff8f376fd6a5f811d29e1bdc6a).

So, I'm not sure yet if this is an OpenEMU configuration issue, or if it will solve itself automatically when OpenEMU updates its version of PPSSPP.
