### ISSUE TITLE
Chinese knockoff dualshock 3 no wireless recognition over bluetooth

### ISSUE THREAD

**Issue by cryass** [OpenEmu/OpenEmu#1041]
I borrowed a friends older sixaxis to see how compatible it would be with openemu and within a few minutes everything worked! Seemless and more importantly wireless. Convinced of this magic, I purchased a brand new dualshock 3 (different controller build but essentially indentical function). Now, connecting via bluetooth works, but openemu doesnt see the controller unless it's plugged in. Same OS(mavericks), same openemu version, restarts, reinstalls including core files in Library. can't figure this out...

**Comment by blindjudge** [comment]
The fi.sh script has worked for me unchanged in Yosemite. (PANHAI)

I just never bothered opening up preferences, just did everything from the status bar.

After applying the fix, it works until I plug the usb back in, which appears to overwrite the cache. Running the script again (with Bluetooth off) seams to fix it. Is it possible that this is the expected behaviour? Apple only want devices that they have configuration option for to appear in settings? While third party devices will still work, but only appear in the status bar?

**Comment by uniy64** [comment]
I'll give it a try without opening the preference panel later today. Good to hear from you! Happy new year!

**Comment by torrentlord** [comment]
Firstly wanted to say thank-you for all the work getting these hinges controllers to work!. I have been using both the manual version of editing the plist and also fi.sh but after restarting the settings are lost. Has anyone figured out to keep the edited plist or fi.sh after a restart on Yosemite?

**Comment by schroef** [comment]
Wow! this is really great guys... i bought a controller this weekend for way to much money :( About $50 yes i know, i live on caribbean island so everything needs to be imported. After checking i found out it was spelled "PLAYSTATION(3)Conteroller-PANHAI" and so thus a fake. It works over USB but i really wanted the bluetooth to work. After searching i think hours i found this thread and tried it on Yosemite 10.10.3 It works perfect!

thanks again!!!

**Comment by schroef** [comment]
Do any of you guys can see more info in the bluetooth menu like battery status?
I only see its connected, in the preferences>bluetooth it doesn't show up still.

**Comment by Hoffa** [comment]
Patiently waiting for El Capitan, hopefully they've changed some Bluetooth-related things since I haven't been able to get my crappy controllers to work since Mavericks. Will try and get these things to work then. I've been playing around with settings and testing stuff but nothing so far. Mines don't even work through USB (it is recognized though).

**Comment by DevcubeDevelopment** [comment]
MrRocketman's post https://github.com/OpenEmu/OpenEmu/issues/1041#issuecomment-39808894 did it for me on Yosemite! Thank you very much :-D

**Comment by schroef** [comment]
On el capitan none of this needed any more :) All seems to work just fine

**Comment by RedMaineiac** [comment]
Hello,
I just purchased the exact same Chinese knockoff controller mentioned early on and tried working through MrRocketman's tutorial.  I ran into several problems though and was hoping someone may be able to help.  Schroef says that none of this is needed in el capitan anymore, but I'm still having the problem that started this thread (controller connects briefly but then doesn't stay connected) so I'm wondering if I'm doing something wrong or if he's using a real Sony controller? ...  I'm running 10.11.2 and when I go into the preferences directory I don't have a com.apple.bluetooth.plist file.  I do, however, see a similar file in a "ByHost" folder that's also in Preferences.  When I go into that directory, I see a com.apple.bluetooth.XXXXX.plist file (with a long string of characters in place of the XXXXX).  I tried to perform the steps MrRocketman gave using this plist file in the ByHost folder, but the file wasn't quite the same.  It had my device ID but there wasn't an arrow to drop down additional information.  So I tried adding the fields and copying in the data and class of device, but that didn't seem to work.  Has anyone had success using these cheaper controllers in 10.11.2? Any thoughts on why my plist files are different from what is described above and if there's a way I can modify it to allow my controller to work?  Thanks so much.

**Comment by schroef** [comment]
Hi no im really using a chinese knock off, the PANHAI. I havent looked into this for a while cause it simply works. There's one game, METRO LAST NIGHT, which doesnt seem to go well some how. All others work and the controller stays connecting without the need to logg in or off and replace the file

**Comment by RedMaineiac** [comment]
Thanks for the response, Schroef.  Maybe the issue is with my specific controller which is the "ghic" version.  I can't get it to work and it's odd that my bluetooth preferences aren't the same as those described by MrRocketman.

**Comment by schroef** [comment]
I got different Numbers as well. I got 1344 where we need to change the number. I'm not sure if this was the same, can't remember.   Have tried a search with name?

**Comment by RedMaineiac** [comment]
Yes, I've done some extensive searching on this subject and this is the most promising series of posts that I've come across.  I have two similar "ghic" controllers and one of them I've actually managed to get to the pop up screen where it prompts you to enter a code.  I try '0000' (like I've seen mentioned) and it never connects and the prompt just keeps popping up.  Bluetooth works great for a couple of other devices that I use frequently, so that's not the problem.  This issue with the controllers is really confounding me because they're decent controllers for the price.  I hate to spend a bunch more money on an authentic Dualshock 3 just to play OpenEmu...

**Comment by schroef** [comment]
Do they actually work when the cable is plugged in?

**Comment by schroef** [comment]
PS did you find this post? http://apple.stackexchange.com/questions/75889/anyone-able-to-connect-gioteck-vx-1-ps3-controller-via-bluetooth

It is with a older system though

**Comment by RedMaineiac** [comment]
Thanks, I did see that post but I was hesitant to go to all that trouble since it was for an older OS... Yes, I have tried the controller with the USB cable plugged in, and OpenEmu shows it as an option, but it doesn't work to play games or map buttons.  I have two controllers and both show up in OpenEmu but neither work.

**Comment by RedMaineiac** [comment]
Update on this issue...  I tried a friend's authentic Dualshock 3 controller and it works great.  I still cannot get my generic, "ghic conterollers" to connect or even work when connected via USB.  The way the cheap controllers connect is definitely different than the authentic Dualshock 3.  The cheap ones continue to lose connection every so often (the dashes over the bluetooth symbol in the menu bar disappear every so often, which leads me to believe the controller isn't actually paired) while the authentic Dualshock 3 remains constantly connected (steady dashes over the bluetooth icon; like my bluetooth mouse or speaker).  Unless there are some other thoughts on how to fix this issue, I may have to just give up on these Chinese controllers.

**Comment by schroef** [comment]
@RedMaineiac Well mine is also a chinese nockoff but does work over the cable and now perfect under el capitan over bluetooth. Actually the link i posted earlier has the same work method as earlier in this thread. Have you never tried this?

**Comment by RedMaineiac** [comment]
Thanks, @schroef .  I did try to work through the steps outlined by @MrRocketman but the only bluetooth plist file that I was able to find was in the "ByHost" folder in Preferences and when I opened it up to edit, it wasn't the same as described in the tutorial.  It had my device ID but there wasn't an arrow to drop down additional information. So I tried adding the fields and copying in the data and class of device, but that didn't seem to work.

**Comment by schroef** [comment]
try this address, /library/preferences/com.bluetooth.plist use command+shift+G this is the main preferences folder. ByHost is each item separate i believe.

what OS version are you on

**Comment by schroef** [comment]
Never mind, i see your running 10.11.2 as well like me.

**Comment by RedMaineiac** [comment]
Thanks for the tip, but when I enter that address it just says the folder can't be found.

**Comment by schroef** [comment]
aha, go to GO in the file menu on the top while hovering press option, the library folder will apear than. Ive got a app running which always makes sure the library folder is showing.

Now you most be apple to go to the correct preferences folder.

**Comment by schroef** [comment]
you can also follow these tips on permanently showing the library folder

**Comment by RedMaineiac** [comment]
@schroef Actually, I just tried it again and added the "apple" into the plist file name (com.apple.bluetooth.plist) and it did locate a file that I had not seen previously.  Odd.  This seems to be a different Preferences folder than I had been in before.  Are there multiple Libraries?  I had been using the option key on the Go menu to show the library and that was the folder that wasn't showing the bluetooth.plist.  This is strange.

**Comment by schroef** [comment]
Yes sorry, i think i forgot to put apple there :) Yes each user and the main admin has a own preferences folder. Now you should be able to check the file. Still wondering why my fake does work

**Comment by schroef** [comment]
PS you should try joystick mapper. Works flawless, needs some key bindings but you can add all kinds of presets

**Comment by nickmodernized** [comment]
Hi guys,

I'm having the same issue as RedMaineiac with a PANHAI controller.  Exactly the same.  I can see that after I run the fix the plist looks fine, but then I reconnect the controller and the controller ID turns back into 1,344.

I too can see the Gamepad in OpenEmu when it is plugged in to USB, but none of the buttons work.  The controller also has no response when I use the application recommended previously by clobber for testing gamepads and the system.

I'm a programmer, and although XCode isn't my specialty, I'm happy to dig however would be best to hopefully help solve the problem since I can replicate...

**Comment by nickmodernized** [comment]
In fact...looks like the whole entry from the "fi.sh" program, or the MrRocketman fix, disappears:

![image](https://cloud.githubusercontent.com/assets/10522648/12527964/dacfcae8-c144-11e5-9b5f-6501a24915b5.png)

**Comment by schroef** [comment]
What OS are you on?
Did also do the logout login part and the load sequence with keeping it in the memory

**Comment by nickmodernized** [comment]
El Capitan. 10.11.2.

Yes.  I've also tried this process here:

http://apple.stackexchange.com/questions/75889/anyone-able-to-connect-gioteck-vx-1-ps3-controller-via-bluetooth

As I had previously connected an authentic Sony PS3 controller to this machine, I had all the values.

So far, no matter what I do, the entry in the /Library/Preferences/com.apple.bluetooth.plist keeps getting overwritten when I press the P3 button on the controller.  I am pretty sure if I can somehow get that to stop happening that I'd be golden...

**Comment by nickmodernized** [comment]
Even following this:

http://stackoverflow.com/questions/20553957/how-can-i-clear-the-corebluetooth-cache-on-macos

and restarting...the com.apple.Bluetooth.plist file persists until I hit the "P3" button in the center of my controller.  Then it overwrites with the wrong values again. :(

**Comment by nickmodernized** [comment]
WAIT A MINUTE!  IT WORKED!  With the following settings...

...

![image](https://cloud.githubusercontent.com/assets/10522648/12528291/360a227e-c14e-11e5-8aab-95644164e948.png)


Wtfing it now...

So here's what I did:

1) Overwrote the com.apple.Bluetooth.plist file as RocketMan suggests.
2) Before turning BlueTooth back on, I deleted the ~/Library/Preferences/ByHost/com.Bluetooth.BIGOLEGUID.plist file (this is apparently new to El Capitan).
3) Did the "defaults read /Library/Preferences/com.apple.Bluetooth.plist" command.
4) Rebooted entirely.
5) Then turned on Bluetooth.
6) Then clicked the P3 button.

And the screenshot above is apparently good enough for it to work!

I'll see if it still works after turning off and on again or summat...but I'm playing Twisted Metal III with my cheap PANHAI controller on OpenEmu on El Capitan! :)

**Comment by schroef** [comment]
One of the crucial parts is to red it into the memory I believe. I remember doing this on my old MacBook with Mavericks and sometimes I need to do this 2-3 times. 

Can't remember do I needed to this on El Capitan. 

Hopefully it will keep it like now for you

**Comment by jesscheung** [comment]
First of all, thanks to all that have contributing and explaining all the steps in this thread. I've been following it for the past week trying to make my own knockoff controller work. I've got a genuine PS3 controller that works like a charm - no problems there - but still having issues with the knockoff. 

Deleting the cache in the User ByHost folder was the trick in making the file keep the changes and now my com.apple.Bluetooth.plist file looks exactly the same as nickmodernized. But I still can't get the controller to stay connected to Bluetooth for longer than ~30 seconds. And OpenEmu doesn't register any buttons pressed during the 'connected' period. 

Any thoughts on what could be happening here?

Thanks all.

**Comment by schroef** [comment]
Your looking in the wrong folder. You need show the main library folder. Go to the file menu>go then press alt and library will show. Then go into preferences and find the Bluetooth file

**Comment by RedMaineiac** [comment]
Update:  I finally had some time to go back and try this again with the correct .plist file and I've gotten it to work!  It took 3 times working through @MrRocketman's steps above, but it finally took and my controller is working perfectly now.  I did not have to delete the bluetooth.plist file in the ByHost folder like @nickmodernized.  I was going to give that a try if my third attempt at MrRocketman's steps wasn't successful.  My biggest lesson from this is to make sure you have the correct .plist file (the one in the main library, not the individual user library).  Now I'm going to try and get my second Chinese controller to work as well by again modifying the .plist file.  Thanks, @schroef for your responses and help, and of course thanks to @MrRocketman  for the hack!

**Comment by RedMaineiac** [comment]
Update 2:  So, despite working for a bit after the attempt I described above, my controller stopped working the following day and the .plist went back to its original state.  So, I tried deleting the .plist file in the MyHost folder as suggested by @nickmodernized and that appears to have done the trick for good.  Knock on wood, but my controller has been working great for several days now with several restarts in between.  Just wanted to post and clarify for future readers that it appears deleting the MyHost bluetooth .plist file is an important step in El Capitan.  Thanks to @nickmodernized for the tip.

**Comment by Rikcancode** [comment]
Hi, maybe it's a stupid question but where should I find the "ByHost" folder?

**Comment by schroef** [comment]
Your in the wrong folder Rikcancode. You need to go into the root>the admin library folder. See a couple posts back how to get there

**Comment by takumidaniel** [comment]
Thanks everybody, I purchased the same ps3 controller, but I was not able to run it, I am running 10.11.3 OS X El Capitan. I was not able to locate MyHost folder, also every time I swap the Bluetooth folder back, when I try to reconnect, It automatically changed it self back before the changes.

**Comment by schroef** [comment]
You dont need to look in the ByHost folder. You need to go in the main preferences folder of the root. This library isnt shown by default. Check a couple posts back where i explain how to show this folder

**Comment by takumidaniel** [comment]
Ah... got it, thank you @schroef  it works flawlessly.
Except one small issue if anyone experienced. the lights on my controller keeps flashing after it is connected and working with Steam.

**Comment by schroef** [comment]
Yes, i got that as well. I dont think its supported just like the vibration

**Comment by tdrobinson91** [comment]
So I'm unable to find my com.apple.Bluetooth.plist under preferences... I can only find the one in my byhost folder. I think I might have deleted it in the past to reset my bluetooth settings, but I assumed it would recreate itself. Any suggestions?

**Comment by schroef** [comment]
Okay, 3rd time ;)

Check a couple posts back to see how ii explain how to view and find the correct one.

https://github.com/OpenEmu/OpenEmu/issues/1041#issuecomment-174382193

**Comment by tdrobinson91** [comment]
I had a feeling you were going to say that. I followed the file, menu, go (alt) guidelines you gave. I have some experience with getting there in the past. I'm baffled as to why it isn't there anymore.

**Comment by schroef** [comment]
Cause is see you in the user folder, you need to go to the root of the HD and the
<img width="217" alt="screen shot 2016-03-03 at 6 00 44 pm" src="https://cloud.githubusercontent.com/assets/6923008/13511060/f9fd7538-e169-11e5-85f8-a089a4c5ab8a.png">
<img width="491" alt="screen shot 2016-03-03 at 5 57 54 pm" src="https://cloud.githubusercontent.com/assets/6923008/13511059/f9fcc110-e169-11e5-9181-f01a07c10e62.png"> 

n library. You can go there by using alt when check the "GO' menu in the top menu. When you press [ALT] the library appears.

If you want it to always show, then right click it>view options>show libary folder

**Comment by tdrobinson91** [comment]
Sorry, that was an oversight and a half! I even had the always show setting already up. Thanks for your patience. I'll be seeing if everything worked when I get home later.

**Comment by schroef** [comment]
okay, thats alright

**Comment by terreb** [comment]
@jesscheung I have the same issue as you do. Have you found any solution? My controller is Gasia PS(R) Controller.

**Comment by pjpalomaki** [comment]
Ok, I've tried it all.. I have a PANHAI version of PS3 controller. This is what I've done:

1. Replaced com.apple.bluetooth.plist in HD/Library/Preferences/ with correct settings (inc. ClassOfDevice set to 1288)
2. Deleted the com.apple.bluetooth.somehexuuidstuff.plist in ~/Library/Preferences/ByHost/
3. Read the new .plist into memory ~x8 times
4. Restart

As soon as I hit the P3 button on the remote, it reverts the ClassOfDevice back from 1288 to 1344. It just won't stick! The lights on the controller blinks for 30 seconds and then turns off, disconnecting from my MacBook. Any suggestions at all? I'm on 10.11.4.

Just to note that Enjoyable ([https://yukkurigames.com/enjoyable/](https://yukkurigames.com/enjoyable/)) sees the device for those 30 seconds but doesn't recognise any button presses.

Thanks.

**Comment by terreb** [comment]
I might find a solution to make it work. For me it also rewrites ClassOfDevice back, but this is not a problem. I found that when I start RetroArch the controller start working no matter connected or via bluetooth. After that I can exit RetroArch and open any game or OpenEmu and it keeps working. Hope this helps others.

**Comment by nickmodernized** [comment]
If I remember right, mine also kept changing back.  The key seemed to be if
that long string of stuff actually stuck around.  If it did, then OpenEmu
worked.

Is RetroArch open source?  If so, I wonder if we could see if there's
something in that code that has a handler for this controller to improve
the Open Emu project?

Nick

**Comment by pjpalomaki** [comment]
Yeah the string sticks but neither OpenEmu or Enjoyable works with bluetooth, and it disconnects after 30 secs. Could someone confirm what your SupportedFeatures are in your .plist? Mine is:
83781F987A8DFFFF (.x..z.ÿÿ) - I think I saw the Mrrocketman's original screenshot was different?

**Comment by schroef** [comment]
ive got a panhai and still works in 10.11.4
When i got to 10.11.1 i never need to adjust any file and it would pair with any issue

**Comment by pjpalomaki** [comment]
@schroef could you post a screenshot of your .plist (panhai section)? Also, had you ever have genuine PS3 paired with the mac before the panhai?

**Comment by schroef** [comment]
Ive not linked a origanl controller
Here a the screens of the controller, i skipped the part with the long code as its not of use
<img width="662" alt="screen shot 2016-05-10 at 5 21 45 pm" src="https://cloud.githubusercontent.com/assets/6923008/15162946/c1fe519e-16d3-11e6-887f-cb4a722ca2ae.png">
<img width="545" alt="screen shot 2016-05-10 at 5 21 39 pm" src="https://cloud.githubusercontent.com/assets/6923008/15162947/c1fe76ba-16d3-11e6-8aa1-234103cc8a75.png">

**Comment by schroef** [comment]
With Mountain Lion i did need to the change and had some funky outcomes, sometimes it would work and other times it didnt. With El Capitan it just works straight after the update

**Comment by pjpalomaki** [comment]
Thanks @schroef, your SupportedFeatures seem different to mine, could you confirm that your HEX value is: 67 33 67 66 6d 48 71 4e 2f 2f 38 3d ? (At least that's what I get when I convert the string to hex)

Seems a bit long compared to other posts?

**Comment by schroef** [comment]
what you ean by HEX value??

**Comment by schroef** [comment]
673367666d48714e2f2f383d i got it i think, i checked a couple strings and used the last data string. Its the same as yours

**Comment by clobber** [comment]
# FYI to everyone that pops into this thread with issues editing a plist file

Since OS X 10.9 Mavericks, you **cannot** simply delete a plist or edit values and expect them to save. For performance reasons, Mavericks implemented **preference caching** which is managed via the **cfprefsd** process. All manual changes to a plist must be done via the `defaults` command in Terminal.

Alternatively, you can try this GUI: http://apps.tempel.org/PrefsEditor/

**Comment by schroef** [comment]
what i dont understand why i dont seem to have any issues now with El Capitan, prior i need to do that save trick with copy paste and logging out and back in

**Comment by pjpalomaki** [comment]
@schroef I mean your SupportedFeatures data value is represented in ASCII (g3gfmHqN//8=) but that seems like too many characters. To get the HEX value, you must open the .prefs file with Xcode or something like [PrefSetter](http://www.nightproductions.net/prefsetter.html) and find the value there. I'd appreciate it.. about to throw two PANHAI controllers in the bin...

**Comment by pjpalomaki** [comment]
@clobber just a FYI, I tried PrefsEditor and it won't allow editing com.apple.bluetooth.plist as it only allows editing

> actual application preferences, not general plist files (to edit plist files, use Xcode or Pref Setter or PrefEdit).

**Comment by schroef** [comment]
@pjpalomaki I did find the correct data string, didn't you see my post?

**Comment by bcrescimanno** [comment]
Wondering if anyone is still around here watching this thread. 

I've recently gone through the steps suggested by @MrRocketman and @nickmodernized and my knockoff Ps3 controller will now stay connected via bluetooth consistently and without any issues. Unfortunately, neither OpenEmu nor two gamepad testing tools (Controllers Lite and Joystick Doctor) register any button presses.  Wondering if anyone else had this happen and has a solution.

**Comment by schroef** [comment]
i got joystick mapper and works perfect under osx 10.11.6

**Comment by bcrescimanno** [comment]
Yup; I'm on 10.11.6 and I am able to have both of the controllers connect via bluetooth by following the directions; the instructions worked perfectly. But nothing detects any button presses on the controllers. :(

**Comment by schroef** [comment]
okay, but are you also using joystick mapper? With this app you can make presets per game, this is a bit of a pain to set. Also it feels sort of like a mouse with movement, but its better than keyboard and mouse

**Comment by bcrescimanno** [comment]
I'd be happy to use a tool like Joystick Mapper if I actually believed my controllers were working at all. Being able to map the buttons to something else is cool; but, the buttons would have to work in the first place.

**Comment by bcrescimanno** [comment]
Very interesting!

I just tried the suggestion from @terreb and downloaded RetroArch. Despite OpenEmu, Joystick Doctor, Controllers Lite, and Enjoyable all refusing to acknowledge button presses, the moment I fired up RetroArch, my gamepad was working perfectly. And, as suggested, it immediately worked in OpenEmu as well. I could turn off RetroArch at that point and it continued to work in OpenEmu.

Hey @clobber - I know this isn't a priority for you or the project; but, there's definitely something to this. The facts: I was able to get two of these knockoff controllers to connect steadily via bluetooth following the steps here. Despite being connected, nothing would recognize their button presses. The instant I started RetroArch, the controllers were recognized by literally every other tool that had been failing to recognize their button presses. Something in their system is connecting that last mile.

**Comment by schroef** [comment]
But are you able to map buttons from the keyboard now, would be sort of useless. Many games dont support gamepads. But when your able to map the keys you can still use it

**Comment by bcrescimanno** [comment]
@schroef The only thing I'm trying to set up at this point is OpenEmu; so, controller support there is what matters to me.

**Comment by terreb** [comment]
@bcrescimanno Hi there. My solution with RetroArch works for mapping keys too. I'm using ControllerMate for that, but the basic mappers should work too. I tested with a few in the past, don't remember their names though. Would be great if OpenEmu guys could extract that functionality from RetroArch that makes those Chinese gamepads work out of the box and embed to OpenEmu. This is a bit of annoying to start RetroArch every time:)

**Comment by bcrescimanno** [comment]
Well, there's a part of me that's leaning a bit towards using RetroArch for now anyway (despite strongly preferring OpenEmu from a UI perspective): I can completely control the UI with my controller. My setup is such that my emulators run on a mac mini connected to a TV that doesn't have a keyboard or mouse connected to it. It's nice to be able to use the controller for the browse UI. 

That said, if OpenEmu added whatever RetroArch is using for supporting these third-party game pads (easier said than done, I'm sure!) I'd be back to OpenEmu really quickly.

**Comment by clobber** [comment]
I can assure you, there is no magic from one application that suddenly makes that device work in another. Since this rolling thread has gone on for a couple years with dozen of participants, and there is no OpenEmu issue here, I'm going to lock. It's kind of spam at this point when someone stumbles upon it trying to get bluetooth working with OS X.
