### ISSUE TITLE
DS microphone input can't be sustained

### ISSUE THREAD

**Issue by palmerar** [OpenEmu/OpenEmu#1047]
Hi there,

Many DS games (e.g. Zelda Spirit Tracks) require you to keep blowing into the microphone, but OpenEmu only registers the first 'puff' when you hit the keyboard key and doesn't register when you keep the key held down for a sustained 'blow'.  This makes some aspects of games impossible to do with a keyboard eg.  the bits in Zelda where you need to play along.

Thanks,
AP

**Comment by tomas0721xd** [comment]
Note: I did NOT make these, credit goes to the gbatemp guys.

Fake Mic Blow (L Button)
94000130+FDFF0000
220B5308+0000005F
D2000000+00000000

Fake Mic Blow (R Button)
94000130+FEFF0000
220B5308+0000005F
D2000000+00000000

that should do it, add as a cheat

**Comment by LinkLuver** [comment]
That code is SUPER helpful! Though if you are in spirit tracks, when you are fighting the forest temple boss, the fake blowing doesn't work, so you will just have to set another button for the mic. Luckily this boss is easy so with the sucky mic button it is still easily possible!

**Comment by tomas0721xd** [comment]
I found it cause I wanted to play spirit tracks, for the forest temple boss you can use both, the cheat and the mic button due to not having to blow steadily

**Comment by icepackboy** [comment]
I'm playing The Legend of Zelda: Spirit Tracks on OpenEmu version 2.0.4 and I'm having the same trouble with the mic. It won't be sustained. I've tried all sorts of variations of the cheat codes posted by tomas0721xd but they wouldn't work. Could it be the version of the game that I am using? If anyone who has fixed this problem for this particular game, could you please explain specifically what you did to make the cheat codes work? I would be extremely grateful. I've spent quite a few hours now just looking for answers on the internet but nothing has worked so far. Please help.

**Comment by guybrushthreepwoodmightypirate** [comment]
@icepackboy Yes, I believe so. For me, the code didn't work with the EU version, but it did with the US version.

**Comment by bhnb78** [comment]
Ok newbie here, where do I put the code? I am using OpenEmu for Phantom Hourglass @tomas0721xd

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes
