### ISSUE TITLE
PAL Playstation ROMs doesn't seem to work.

### ISSUE THREAD

**Issue by Jahuya** [OpenEmu/OpenEmu#1048]
I was testing my playstation games, and some were working and others weren't. After a while I noticed a pattern. None of the PAL versions of the games were working. 

I tried different different versions of the same games from different sources to be sure that it wasn't a problem with a specific iso.

I also used different european bios, from different sources.

After all the testing about 40 games, I can say that not even one PAL game worked.

The good news are that all the NTSC ones work fine.

Hope I helped! :)

Thank you for doing this app!

**Comment by finsceal232** [comment]
hey, i become to use openEmu to my mac. After many test, i remarque i can't play only PAL version of the same game, but us and japan work. i try to change my bios but its a same probleme. thanks if you can help me
