### ISSUE TITLE
Not all Gameplay Buttons for SNES RetroPort and RetroPad are able to be assigned in Preferences > Controls

### ISSUE THREAD

**Issue by kylebradshaw** [OpenEmu/OpenEmu#1051]
I have some old SNES remotes and I purchased a RetroPort: http://www.retrousb.com/product_info.php?cPath=22&products_id=31

I also have some older nintendo gamepads that were converted to usb devices years ago. They are recognized as `RetroPad` and `SNES RetroPort` in the input: dropdown on the Preferences > Controls screen. Both are having the same issue.

I cannot assign the buttons. The directional pads get assigned fine. As soon as I attempt to assign the `Select` button it will jump down 3 fields and assign it a button, it's not recognizing a single keypress. I've used them with other emulators and have not had a problem so I know they work.

Any idea?

**Comment by rhestilow** [comment]
I experienced the same issue with an SNES RetroPort today, on the latest version. I just tried wiping my Default.oebindings file and that did not fix the issue. I would be happy to try additional fixes and report back if you have any suggestions.
