### ISSUE TITLE
No cover art will download

### ISSUE THREAD

**Issue by lieder1987** [OpenEmu/OpenEmu#1055]
The cover art for none of my games will download. I have tried right clicking and going to download cover art, but it dose not change from the rainbow lines.

Any suggestions?

**Comment by mathiasbynens** [comment]
@Mitchismo It would be helpful to post the answer to your own question (where are these files stored) instead of just saying you found them.

**Comment by Mitchismo** [comment]
I can't even remember what I asked. Outlook? What is that? It must have been a typo, so I retracted my question. It was from 10 months ago anyhow.

Next time, however, I'll answer my own question. I just don't remember what I asked. Or what the answer was.
