### ISSUE TITLE
Should console region be forced to match localisation settings with 'world' ROMs?

### ISSUE THREAD

**Issue by okdana** [OpenEmu/OpenEmu#1059]
I don't know if this is ever an issue for any other game/system, but there's a curiosity i noticed with the 32X game _Cosmic Carnage_ / _Cyber Brawl_.

The NTSC version of this game is actually multi-region, and the game itself changes based on the console it's booted from. If the console is North American, the game experience reflects that — the title screen displays _Cosmic Carnage_ and many of the characters are altered. If the console is Japanese, the title screen displays _Cyber Brawl_ and contains the original characters.

Despite having my localisation set to Japanese, running this game results in the North American _Cosmic Carnage_ experience.

Is it worthwhile to make OE force the region to match the localisation when it detects a game that is multi- or all-region? Is that even possible?

**Comment by clobber** [comment]
Somewhat implemented for Mega Drive/Genesis https://github.com/OpenEmu/GenesisPlus-Core/commit/c43bcd75af7512bfc2e416219bd86d3440006809

32X will be more comprehensive.
