### ISSUE TITLE
Feature Request: NEO GEO Console Menu and AES vs MVS Selection

### ISSUE THREAD

**Issue by capeman29** [OpenEmu/OpenEmu#1069]
Neo Geo would benefit from having it's own slot on the list of available consoles to separate it from "Arcade" - mainly to allow it's own set of controls, since the neogeo button layout doesn't match other arcade fighting games, you have to keep switching back and fourth between button layouts manually as of now.

Other issue would be to enable switching between MVS mode (arcade settings - insert coin) and AES mode (home console setting - lives, continues, pause button). The universal bios apparently support this selection in Mame, would be a great addition to the neogeo console options (could be added on the controller layout screen).

*\* Also found a neogeo bug: Every neo geo game i open pulls an error popup caused by the automatic continue with save state. When turned off, no error.

**Comment by Danger2010** [comment]
Help me, when i try to play Metamorphic force in openemu, the coin button don`t works :( any idea????
