### ISSUE TITLE
Can't play any game

### ISSUE THREAD

**Issue by ducanhheli** [OpenEmu/OpenEmu#1070]
I added roms to GBA or Sega, but when i click to play, nothing happen.

**Comment by jaypotvin** [comment]
@clobber I am having exactly the same problem. I have deleted all the cores and reinstalled them. I have tried everything that was in these forums everything besides NES does not load. I click on sega, snes, turbografx16 and none of them load, no error messages, nothing happens at all. I am running 10.7.5 on a macbook pro2.4 ghz icore i5, 4gb ram w/ bezel screen. what do you feel may be the problem and is there any other info you need?

**Comment by clobber** [comment]
@jaypotvin No, you are not having the same problem. You bumped an issue from 2014 that is unrelated to your own. 1.x is unsupported and you cannot use the core plugins meant for 2.x with 1.x, which is happening now as you use 1.x. You will need to upgrade to 10.11 and get v2 of OpenEmu.
