### ISSUE TITLE
N64 Plugin no way to choose video plugin

### ISSUE THREAD

**Issue by tlangs** [OpenEmu/OpenEmu#1094]
Some roms run better with Rice, and some work better with Glide64. There is currently no way to choose which plugin to use.

**Comment by EriolGaurhoth** [comment]
Any progress on this front?  With N64 being a part of the new "official" release and no longer just experimental, many great games can't be emulated properly because Rice fails :(

**Comment by josheverett** [comment]
Is there an issue tracking Glide support anywhere where I can voice support?

(I just hit the point in Ocarina of Time where I can't progress due to the Lens of Truth not working and Google brought me here.)

**Comment by mrvacbob** [comment]
Rather than support, some developers would be helpful.

**Comment by josheverett** [comment]
I'll take that as a "no" then.
