### ISSUE TITLE
Additional System Wishlist - DOSBox/Boxer

### ISSUE THREAD

**Issue by The-Pezman** [OpenEmu/OpenEmu#1096]
There is a page listing the "wishlist" of cores to port to OpenEmu (https://github.com/OpenEmu/OpenEmu/wiki/Console---Core-Plugin-Status-&-Wishlist). I am enthused by the idea of including PCSX2, Dolphin, and ScummVM - that could help make the Mac ports of those emulators a lot more manageable. However, I was surprised to not see DOSBox on the list, since there is an actively developed Mac frontend called Boxer (http://boxer.washboardabs.net). In fact, Boxer's dev blog is how I first learned of OpenEmu back in the day, and I know there were talks of collaboration at one point or another. What happened?

**Comment by wraybowling** [comment]
I was curious about Scumm today, and this answered my question. After reading Boxer's blog for a few minutes I can see why it's smart to keep OpenEmu and Boxer separate. Frankly, I'm very impressed with how many features it has.

**Comment by trollworkout** [comment]
this is such a bullshit thing that you can support all these platforms except for dos. unless you support dos i will never use this software . boycotting

**Comment by Solarstrike** [comment]
@trollworkout guess that's why your username is like that.
