### ISSUE TITLE
Implement mouse support

### ISSUE THREAD

**Issue by donmotumbo** [OpenEmu/OpenEmu#1108]
Hi, I'm asking you if you can implement mouse support for playing games, especially in the MAME core, because the current input implementation in this core is only digital input emulation, making some games like Chiller and other point and shoot arcade games impossible to play, because the current implementation only allows to aim to the edges of the screen.

Thanks in advance.

**Comment by clobber** [comment]
This is enabled for as many systems as we can support, except Arcade. Available in next release.

**Comment by lede1243** [comment]
I am trying to use the mouse as an "aim, then click to fire" control scheme for the hook shot in Ocarina of time, but I cannot figure out how to do it. Is it possible?
