### ISSUE TITLE
XBOX1 controller almost works :)

### ISSUE THREAD

**Issue by olind** [OpenEmu/OpenEmu#1111]
I'm trying to use two XBOX1 controllers attached to a MacBookPro (10.9.1) via a Super Joy Box 11.

I installed the XBOX HID Driver (http://macman860.wordpress.com/2013/05/03/xbox-driver-for-mac-os-x-lion/) Launched the preference pane and all buttons works there.
![xboxhidprefs](https://f.cloud.github.com/assets/122699/1993714/01a2bff8-84df-11e3-8b7c-6bd1923d4078.png)

I launched OpenEMU and configured the first controller. I launched super mario kart and it worked perfectly.
![controller1](https://f.cloud.github.com/assets/122699/1993727/4bab0812-84df-11e3-91e6-f191a31db1fb.png)

I restarted OpenEMU, connected controller two and configured it. The configuration for this looks a bit strange but all buttons except the triggers worked fine.
![controller2](https://f.cloud.github.com/assets/122699/1993876/896cd15a-84e2-11e3-9957-3517c913bfb3.png)

Is there any (easy) chance to get this to work or should I buy 2 new standard usb controllers instead?

Thanks a lot!

**Comment by cyco** [comment]
Closing in favor of the more active #1810.

**Comment by olind** [comment]
I'm not sure if this is the same issue. I'm using the oldschool Xbox controller from the first Xbox. In issue #1810 they are talking about the Xbox One released last year.
