### ISSUE TITLE
DS Blackout

### ISSUE THREAD

**Issue by roger1762** [OpenEmu/OpenEmu#1112]
So I was playing Pokemon Soulsilver on DS, and when I re-opened Openemu and loaded the saved file, the top screen just blacks out. I tried loading other saved file as well, but they black out as well. Any solutions?
![screen-capture-2](https://f.cloud.github.com/assets/6492542/1995644/5c32e4ce-8508-11e3-92a8-559474507f56.png)

**Comment by al1290** [comment]
not sure if this will help but it worked for me click save game in the actual game then in controls restart emulator and it should restart the game and pick back up where you last saved

**Comment by Helplugin** [comment]
That actually worked al1290 thanks! :dart:

**Comment by Tomikaze12209** [comment]
al1290 saved my many hours on Heart Gold. Thanks!

**Comment by zorroaster** [comment]
this might be a bit late but how to you restart the emulator from the controls? it doesnt appear to give me an option to..

**Comment by Austria88** [comment]
You have to restart the game and load the savefile in-game not directly from the emulator.

**Comment by yessirk** [comment]
Every time i restart or reset the game it takes me to the tutorial again

**Comment by rahrahraichu** [comment]
@Fluxxed This just means save the game through the in-game menu (the same way you would if you were playing on a DS - click "save" on the bottom screen). Don't save through the emulator itself by going to File > Save. 

I have a question regarding the black screen error. Is it safe to save the game after the screen goes black? Will loading that save fix the error or will I just end up loading the game to a black screen and ending up stuck? So far I've just been saving frequently and when I encounter the error, just restarting and loading my previous save.

**Comment by RiceBall888** [comment]
Um... I've been having the same problem and I'm kinda upset about losing my progress. I've read through everything I can find, and it seems like there is nothing I can do about this issue. The save/restart trick did not work for me. Am I right that there is nothing I can do about this?

**Comment by clobber** [comment]
Yes, that is correct.

In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
