### ISSUE TITLE
Sega Genesis needs 3-button controller option

### ISSUE THREAD

**Issue by aratuk** [OpenEmu/OpenEmu#1120]
Certain Genesis games won't work with a 6-button controller "attached" (Sega came out with this controller scheme later in the life of the console), and this is something that's supposed to be taken care of by emulation of the "mode" button, but I haven't been able to get it to work in OpenEmu.

For instance, the game "Forgotten Worlds" will jump to "game over" as soon as the player starts a new game unless they hold down the "mode" button when the console is turned on. In OpenEmu, I have tried assigning the mode button to different keys, but I haven't been able to approximate this response (and so haven't been able to get the game to work). Here is a thread discussing the issue: http://www.sega-16.com/forum/showthread.php?4398-Forgotten-Worlds-giving-you-GAME-OVER-immediately-Fix-inside

Because there are only a handful of early Genesis games that have this issue, I suggest hard-coding exceptions into OpenEmu's handling of these particular titles, so that, for them, only 3-button controllers are emulated, and from the user's perspective they will simply work, rather than the user having to go figure it out.

**Comment by clobber** [comment]
Implemented in https://github.com/OpenEmu/GenesisPlus-Core/commit/074c0207a151d3f7bed14aa40d10be5a9f5f4f25
