### ISSUE TITLE
Mame Core Error on Rom Load

### ISSUE THREAD

**Issue by capeman29** [OpenEmu/OpenEmu#1124]
The second (third, fourth, etc.) time a mame game is run, receiving a standard error message box when the game is loaded. Does not interfere with emulation after it is dismissed.

This problem goes away if "auto resume" function is turned off globally. Likely caused by this function. More of an annoyance than a problem. If this is not a known issue, let me know and I will post my console readout. 

"Some shit about the game" HA!

**Comment by clobber** [comment]
https://github.com/OpenEmu/UME-Core/commit/7ad25f60338d96c7ac474898ac5ee486dbf19a0c
