### ISSUE TITLE
SNES Multiplayer 3 Player(Multitap) not possible? (game: Secret of Mana)

### ISSUE THREAD

**Issue by davidrichter** [OpenEmu/OpenEmu#1149]
Hello,

is there a way to play Multitap Snes-Games with more than 2 Players? 
The game Secret of Mana for example supports 3 Players, but this doesn´t work with openemu.

**Comment by zevlag** [comment]
I'm commenting here just to +1 say this would be nice if it worked.

**Comment by harrislapiroff** [comment]
+1 for this

**Comment by clobber** [comment]
Added in commit https://github.com/OpenEmu/SNES9x-Core/commit/c1636483fa7663c1e25cb76009b44dd8945853af. Will be available in next OpenEmu release.

**Comment by rennerarruda** [comment]
When this update will be avaible? =]
