### ISSUE TITLE
PSX game won't start

### ISSUE THREAD

**Issue by yoddledooddle** [OpenEmu/OpenEmu#1182]
OpenEmu seems to have a problem with PSX ROMs.

The ROM I have is a .7z file that was successfully scanned, but displayed the following message whenever I tried to play the game:

"The operation could not be completed.
No other information is available about the problem."

A subsequent message window then pops up informing me that OpenEmu is also unable to load the helper application.

**Comment by afatjo** [comment]
I have a similar problem. I double click the added game but openemu simply won't run it, no error,  no crash it simply does nothing. The rom works with PCSXR though.
Any idea?
