### ISSUE TITLE
Unable to save certain games [VBA, 128k Flash needed]

### ISSUE THREAD

**Issue by timbru31** [OpenEmu/OpenEmu#1196]
Hey,

I'm having issues to save games.
E.g. a patched Pokémon version (Ultra Violet) tells me that
`"The 1M sub-circuit board is not installed"`

If I try to save now a "Save Error" appears.

The original VBA had a toggle to increase the memory to 128k.
I'm missing this option in OpenEmu...
Option in VBA:
`Options > Emulator > Save Type`

Is there any possibility to add this feature?
Or at least a way I can mod the VBA Core with this setting?

Cheers

(this is a copy of https://github.com/OpenEmu/VisualBoyAdvance-Core/issues/2)

**Comment by Vristan** [comment]
I have same problem with timbru31, but I don't get it to fixed it. When I play Fire Red is okay, but I want to tried pokemon Advantures Red Chapter and I got same problem like timbru31. Can you help me to fix it?
I'm using Openemu VBA too

**Comment by God1212** [comment]
HI

Could you make a video of you solving this problem ? 
I don't understand how you fixed it .


Thanks guys

**Comment by timbru31** [comment]
@God1212 use e.g. Hex-Editor MX, open the file search for **PUVV** and replace it with **BPRE**, save the file & play :smile:

**Comment by God1212** [comment]
I am sorry man but still not working (probably something I do wrong though)
If I send you the file do you think you could it ? 
I have tried all day, and now I am just pissed at my computer ;)


The game is in this link: https://www.dropbox.com/s/9gfwlex76ml84i7/Dragon%20Ball%20Z-Team%20Training.gba?dl=0

Thanks man

**Comment by robotoad** [comment]
@God1212 Please don't share links to ROM downloads.

**Comment by timbru31** [comment]
@God1212 sorry, you have to figure it out yourself.

**Comment by God1212** [comment]
Yeah I guess I have


Thanks anyway
