### ISSUE TITLE
N64 (Mupen64 Core) Super Mario Moon Jump Cheat Bug.

### ISSUE THREAD

**Issue by theravensrequiem** [OpenEmu/OpenEmu#1202]
Both variations of the Moon Jump Code don't seem to be playing nice with either the Mupen64 Core or OpenEmu. As soon as you check the cheat, the "Hold L button" one [D033AFA1 0020+8133B1BC 4220+D033B1BD 0020+8133B17C 0300+D033B1BD 0020+8133B17E 0880] seems to be locking and Mario just endlessly flies up as if the button is stuck. The "A button" one where you tap to Moon Jump [D133AFA0 8000+8133AFA0 0500+D133AFA2 8000+8133B1BC 4220+D133AFA1 8000+8133B17C AAAA+D133AFA0 8000+8133B17E 0880] just isn't working at all.

Also I would like to note a few things for the official release of OpenEmu that has the Mupen64 Core. First, make sure the cheats you add to the list are saving for later play, because currently they don't. Second, A new form has to be designed so that you can effectively see the list of multiple inputs. The current design is fine for adding one or two string cheat codes but when the cheat has 3+ inputs it's more difficult to keep track. Finally, give the options to edit the cheats. If I made a mistake, I should be able to go back and troubleshoot.

**Comment by rediakik** [comment]
> Ah... sorry. I accidentally built that against the new SDK which won't work until 1.0.2
> 
> Here's another version to try that should work: https://www.dropbox.com/s/uwz79iyucz6fdvb/Mupen64Plus-fix.zip

can it be fixed nowdays running on retroarch ?
