### ISSUE TITLE
Disable Hotkeys?

### ISSUE THREAD

**Issue by Philo-Wintercoat** [OpenEmu/OpenEmu#1204]
Using the NES, SNES and GBA emulators, I've run into an issue.
I always use the L-Command key as my B button and that hasn't been a problem until my volume started changing seemingly at random during gameplay.
Then I discovered the cause: the Command-UpArrow, Command-DownArrow volume adjust shortcuts in the emulator.
I have yet to find a way to disable these shortcuts and am wondering if it can even be done without altering the program itself.
Help and/or constructive suggestions are appreciated.

φ_

**Comment by cyco** [comment]
Same as #350.

**Comment by 35o125** [comment]
> 

any updates on this? :)

**Comment by 35o125** [comment]
> Hi, can I second this? I've used a lot of different emulators on the Mac over the last decade, and using the apple/command key as an action button in games was always a popular and common practice for me. With the current release of OpenEmu the application menu hotkeys take precedence over assigned control keys, which doesn't seem like a practical and/or sensible UI/UX design choice. Thanks for your consideration.

any updates on this? :)
