### ISSUE TITLE
Changing the Game Library Folder Location crash

### ISSUE THREAD

**Issue by iFredOS** [OpenEmu/OpenEmu#1211]
Changing the Game Library Folder Location crashed it:
https://www.dropbox.com/s/2mqda00ww9g3233/OpenEmu%20Crash.txt

I tried 3 times and it crashed each time randomly. A good thing, it seems to resume where it was left off. Maybe your app don't like to have to transfer an "Artwork" folder of 6,75GB. :P

**Comment by gphilipp** [comment]
FWIW, it freezes in 1.04 until it crashes.
