### ISSUE TITLE
PS Game controls stop working when switching to analog

### ISSUE THREAD

**Issue by gvasco** [OpenEmu/OpenEmu#1238]
Playstation game stops reacting to controls after using analog, that is, they work fine using D-pad and buttons but as soon as the analog button is pressed or analog stick (or whatever is mapped to it) is pressed the game stops reacting to any button that is pressed. This was observed when controls where mapped to computer keyboard as well as to a PS3 remote, on OSX 10.9.

**Comment by fnky** [comment]
This is still an issue for me. I have installed the latest experimental version (v2.0.1 – `407-g415a4a6-Release`). If I turn on analog mode, the controller (DualShock 3) wont respond, until I turn it off again, using the **Home** key.

The PSX Core is _0.9.38.7_ and does not have any update buttons.

> _I apologize for the bump, but I found it unnecessary to duplicate this issue._
