### ISSUE TITLE
PPSSPP: How to change advanced settings? > turn off "buffered rendering"

### ISSUE THREAD

**Issue by openemuquestions** [OpenEmu/OpenEmu#1263]
Does anyone know how to change a setting for PPSSPP within OpenEmu? I'd like to turn off "buffered rendering" which is found under 'options' when running PPSSPP alone (or pressing F5 I think.) If there's no way to toggle this control within OpenEmu, would there be a way to do this permanently, such as changing the PPSSPP core file? Turning off buffered rendering seems to fix a glow issue in the WipEout games: http://forums.ppsspp.org/showthread.php?tid=297

**Comment by sonique6784** [comment]
I've compiled PPSSPP-Core with 1.8 in these resolutions:
 * 2x ~ 960x544
 * 3x ~ HD 1440x816
 * 4x ~ FullHD 1920x1088

You can find the binaries here: https://github.com/sonique6784/PPSSPP-Core/releases/tag/multi-resolution

to install, copy/replace PPSSPP.oecoreplugin
in Finder, menu "Go" -> "Go to Folder..." (or Command-Cap-G)a
~/Library/Application Support/OpenEmu/Cores

PS.: you need to have only ONE PPSSPP plugin at a time.

**Comment by clobber** [comment]
@sonique6784 Please don't share binaries here. Instead, use the new `-changeDisplayWithMode` OEGameCore API and add display options that can be changed live. Then open a Pull Request to have them merged.

Example: https://github.com/OpenEmu/Gambatte-Core/commit/4cc81aa4ac394f83d48b12ea943079086310496c
