### ISSUE TITLE
Couldn't find ~/ Library/Application Support/OpenEmu

### ISSUE THREAD

**Issue by AncientSongline** [OpenEmu/OpenEmu#1283]
Hi there! Just as i said in the title i am not able to see or locate this folder. 
I need the /DeSmuME/Battery Saves folder because i have to use a different .dsv file, but it can't be found in its default location. In the "application support" folder there is no "OpenEmu" folder. 
Somebody can help me?

**Comment by john553311** [comment]
same problem. i can run the program but just curious to know why this happens. is it considered as a "hidden folder"?
