### ISSUE TITLE
transporting save states?

### ISSUE THREAD

**Issue by Radawan** [OpenEmu/OpenEmu#1292]
I have been trying to move some save files of my pokemon platinum game to my DeSmuMe. whenever i save though on open emu, it has .oesavestate. how do i make it into a file to where i can move the save over to desmume?
![screen-capture-1](https://cloud.githubusercontent.com/assets/7103606/2559799/58bb882a-b78d-11e3-895b-e00b79b752fc.png) thats in the library-application support-openemu-save states-pokemon platinum.
![screen-capture-2](https://cloud.githubusercontent.com/assets/7103606/2559809/e7c689ca-b78d-11e3-847f-4228f4280767.png) thats in library-application support-desmume-0.9.10-states
the reason why i ask this, is because of pokegen not compatible with openemu.

**Comment by happyian2233** [comment]
sim ply add (.dst) to the state file. So it would look like this ( State.dst and there would be a new "icon")

**Comment by carbi** [comment]
So once I already changed the file name to (.dst). The icon appeared. What do I do next? how do I open de rom in desmume emulator?
