### ISSUE TITLE
Use stored analog deadzone/peaks per-controller in the database

### ISSUE THREAD

**Issue by clobber** [OpenEmu/OpenEmu#1303]
For example https://github.com/mupen64plus/mupen64plus-input-sdl/blob/master/data/InputAutoCfg.ini#L723

**Comment by Surlevif** [comment]
Same here. I'm using an original N64 controller and precision aim is almost unusable in GoldenEye and Perfect Dark. 
I thought the issue might come from the controller, or the adapter , but when I tried Perfect Dark with the SixtyForce emulator, the analog joystick was very responsive and I could very accurately aim.

**Comment by birkag** [comment]
I am struggling where to add the InputAutoCfg.ini file.  I tried adding it to the /Resources/ under OpenEmu and I also tried adding it to the /Resources/ within the /Plugins/System/N64. Neither seemed to work.  Any help would be greatly appreciated.

**Comment by cbarrick** [comment]
Since this is an open issue, does that mean this is not yet implemented?

I tried putting that file in `~/Library/ Application Support/OpenEmu/Mupen64Plus` and saw no difference in my controller's deadzone (Wii U Pro controller). I didn't mess with it to much though.

**Comment by clobber** [comment]
All: You cannot add this file; that's not how it works. I was merely linking to an example of deadzone configurations.

**Comment by clobber** [comment]
This is unnecessary as of OpenEmu 2.2 with automatic analog axis calibration.
