### ISSUE TITLE
controls stopped working

### ISSUE THREAD

**Issue by jbcrimson** [OpenEmu/OpenEmu#1332]
openemu has been working perfectly fine for me all day, but now for some reason the keyboard input has just stopped working. restarted, tried different games, no idea what the problem is or why it suddenly stopped working in the last 15 minutes

**Comment by FullForceGamer** [comment]
Everything, I've looked at everything, and my keyboard still doesn't work. Not with open emu, not with dolphin, nestopia, DeSmuME, or Snes9x. I've tried so much. keyboard still does not respond, and i cant even change the controls. cant do anything within any emulator. I've tried the solutions given in every other problem and none of them worked. I am running os x Yosemite 10.10.2 MacBook Pro (Retina, 13-inch, Late 2013). PLEASE HELP!
