### ISSUE TITLE
When will Sega CD + N64 + Playstation + PSP be included in OpenEmu?

### ISSUE THREAD

**Issue by giterdone420** [OpenEmu/OpenEmu#1335]
I downloaded the experimental version and still can't play Sega CD games. I have all the BIOS files which I threw into the Game Library folder and Sega CD folder but still nothing. I normally use Fusion352i on my Mac running OSX Mavericks and it runs Sega CD just fine. Also, when I dragged my Sega CD roms into OpenEmu, it put all but 1 of them into Sony PSP for some reason...?? 

I was excited at the notion of finally being able to include Playstation, PSP, Sega CD, and N64 into OpenEmu as my "one program fits all" solution instead of running 4 separate emus in addition to OpenEmu.

My point is this....if we have all these extra emus that work fine on their own with Mavericks, why aren't they being incorporated into the NON-EXPERIMENTAL version of OpenEmu?

I think OpenEmu is the best think to ever happen to emulation. The idea of putting everything together, including artwork, game saves, cheats, wireless controller compatibility, etc... is genius. I just wish these additional cores would be easier to install/download for everyone running Mavericks.

**Comment by Solarstrike** [comment]
From the future, they're integrated now.
