### ISSUE TITLE
Realistic Filters

### ISSUE THREAD

**Issue by ron-wolf** [OpenEmu/OpenEmu#1337]
Meaning a way to see the game overlayed on the actual console (as shown in the Controls tab in Preferences) when the console has a built-in screen. It would be interesting to see whether it is possible to emulate how pixels are displayed onscreen.

**Comment by acuozzo** [comment]
Is there any way (currently) to do piped filters? I'd like to have NTSC(blargg) | CRT.

**Comment by astrange** [comment]
There's support for such a thing in the Cg format, and I think you can hand edit them.

**Comment by ron-wolf** [comment]
(piratehearts.com/blog/2014/03/28/crt-simulation)

**Comment by clobber** [comment]
There are many high quality CRT (and other) shaders that one can find in the common-shaders repo.

Anyway, closing this issue since it really doesn't have much to do with our application. One can create their own Cg or GLSL shaders for use.
