### ISSUE TITLE
Saving Cover Art in lossless formats

### ISSUE THREAD

**Issue by ron-wolf** [OpenEmu/OpenEmu#1353]
5ce42bf saves Cover Art as JPEG. There should be a Secrets Preference Panel selector for image filetype. At least include PNG. It’s one of the best lossless image formats out there, and JPEG results for lower-resolution Cover Art is unacceptably low in quality in some cases.

**Comment by cyco** [comment]
defaults write org.openemu.OpenEmu artworkFormat x
    x := { TIFF = 0
	   BMP  = 1
	   GIF  = 2
	   JPG  = 3
	   PNG  = 4
	   JPG2000 = 5
	 }
and 
`defaults write org.openemu.OpenEmu artworkProperties -dict key1 value1 key2 value2`
with keys and values from https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSBitmapImageRep_Class/index.html#//apple_ref/doc/constant_group/Bitmap_image_properties

I'll add some UI for that to the secret preferences eventually.
