### ISSUE TITLE
Wireless XBox 360 Controller loses button functionality if it reconnects while OpenEmu is running

### ISSUE THREAD

**Issue by andhadley** [OpenEmu/OpenEmu#1360]
Ran into a weird problem that I've experienced multiple times and can easily reproduce. Basically, if the XBox 360 controller goes to sleep (because it hasn't been used in 5 mins) while OpenEmu is running and you reconnect it, most of the buttons work fine but you lose the ability to use the toggles on the back of the controller. Unconnecting / reconnecting the wireless receiver does not fix this issue either. Only fully exiting OpenEmu and loading it again restores the use of the toggles. This leads me to believe it is an OpenEmu issue and not a driver issue. The preference panel for the XBox Controller continues to register the toggles even when OpenEmu does not.

Hardware: Microsoft Xbox 360 Wireless Controller for Windows
Tattiebogle Driver: v0.12
OpenEmu: v1.0.2

Probably low priority since it is easy to work around but it is an interesting problem. I may look into it myself if I have time this weekend.

**Comment by clobber** [comment]
This is probably not happening as of OpenEmu 2.2.
