### ISSUE TITLE
unable to locate MAME sound samples folder

### ISSUE THREAD

**Issue by SladeExulis** [OpenEmu/OpenEmu#1374]
I'm trying to play Zaxxon and my ROM is working fine but there's no sound.  I googled around and found that I need to place a set of sounds samples in MAME's sound sample folder.  However I am unable to locate this folder.  I've searched through my OpenEmu's library files and such but no luck.

**Comment by gerardvanschip** [comment]
> You'd have to compile from source using the "Build All + Experimental" scheme https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide
> 
> ```
> git clone --recursive https://github.com/OpenEmu/OpenEmu.git
> cd OpenEmu
> xcodebuild -workspace OpenEmu.xcworkspace -scheme "Build All + Experimental" -configuration Release
> ```
Hi, its now 2019 and there is an experimental build available for download but samples dont seem to work for me. Do I still need to compile?
