### ISSUE TITLE
Sega Team Player multitap support for Genesis/Mega Drive

### ISSUE THREAD

**Issue by SiO2y** [OpenEmu/OpenEmu#1392]
I would like to see support for the Sega Team Player multitap in OpenEmu.
As I understand it, Sega games could only use the Sega Team Player adapter and EA games could only use the EA multitap, they were not interchangeable.

I am interested in playing The Lost Vikings in three player mode which was made available only on the Genesis/Mega Drive version of the game.

As per the forum post at http://www.nintendolife.com/forums/retro/lost_vikings_3_player

**Comment by clobber** [comment]
Implemented in https://github.com/OpenEmu/GenesisPlus-Core/commit/074c0207a151d3f7bed14aa40d10be5a9f5f4f25
