### ISSUE TITLE
Mupen64Plus Texture Packs

### ISSUE THREAD

**Issue by wigga** [OpenEmu/OpenEmu#1394]
I'm trying to add some texture packs for Zelda - Ocarina of Time to the Mupen64Plus integrated into OpenEmu, but I can't get it work somehow. I'm trying to do it like it is explained on this page:
https://github.com/OpenEmu/Mupen64Plus-Core/blob/master/mupen64plus-video-rice/README
I can't find the "~/.config/mupen64plus/" and the /home/<username>/.local/share/
mupen64plus/hires_texture folders...
I think it has something to do with the implementation of Mupen64Plus into OpenEmu. I tried to search for these folders within the openemu.app, but couldn't find them so i created them by myself... e.g. Users/Name/Library/Application Support/OpenEmu/Cores/Mupen64Plus.oecoreplugin/Contents/Resources/highres_texture It didn't worked either. I also can't find the LoadHiResTextures entry in the Mupen64Plus.cfg (/Users/Name/Library/Application Support/OpenEmu/Mupen64Plus/)

Does anybody got some texture packs working with mupen64plus within open emu? 

best regards,
wigga

**Comment by andychase** [comment]
Note that without `Version = 1` in the `[Video-Rice]` section the configuration won't be run. 

This is from https://github.com/OpenEmu/Mupen64Plus-Core/blob/bde1ea33eb6f8456595d0dd18e82d0fbfaffaa8e/mupen64plus-video-rice/src/Config.cpp#L309

So the start of your configuration section should look like this:

```[Video-Rice]

Version = 1
```

Add `Version = 1` if its not already there (it's not included in the gif). The settings will now be applied.
