### ISSUE TITLE
Support FLAC in Cue Sheets

### ISSUE THREAD

**Issue by pathawks** [OpenEmu/OpenEmu#1410]
I should be able to compress the audio tracks of a Playstation disc to FLAC, but this causes the game to not launch at all.

```
FILE "example.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "example.flac" WAVE
  TRACK 02 AUDIO
    INDEX 01 00:00:00
...
```

Everything works great if I keep the audio in a separate file as uncompressed PCM instead.
```
FILE "example.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "example.pcm" BINARY
  TRACK 02 AUDIO
    INDEX 01 00:00:00
...
```

I believe Mednafen supports loading FLAC files from cue sheets in this way, so I'm not sure what the problem could be.

**Comment by clobber** [comment]
https://github.com/OpenEmu/Mednafen-Core/commit/3c3a7bf3f5f601b319501db0672a72dcd41c04b8

**Comment by pathawks** [comment]
:+1:
