### ISSUE TITLE
OpenEmu hangs with certain NeoGeo Pocket game

### ISSUE THREAD

**Issue by Zwitscherer** [OpenEmu/OpenEmu#1411]
Hello!

I noticed that OpenEmu hangs when playing the NeoGeo Pocket game Gals Fighters.

This is interesting to me, since I remember many years ago having the same problem with this game and NeoPop on my computer and the port NeoPopX on my hacked Xbox.

The problem back those days was the same, when doing certain special attacks with certain characters the game would slow down and freeze.

With an update of NeoPop at one time (probably around 2002) this problem was fixed and also with a later released update based on that core of NeoPopX the game finally became playable.

I found some old changelogs where Gals Fighters is mentioned from 2002, I hope this helps to reproduce and fix the issue in OpenEmu too. The NGP didn't have that many games but Gals Fighters is for sure one of the best and generally maybe the most humorous fighting game ever, would love to play that in OpenEmu :-)

Kernel v0.70
- Fixed "Fighters" Gals problems. They were of lightning damage
  Due to excessive data EEPROM emulation discrete simple.
  To solve the problem completely, you must delete the existing
  Flash file - in the battery.
  All movements should work now ... I cross my fingers!

07 SEP 2002 - neopop_uk
- Made the direct EEPROM access more secure by requiring an EEPROM
  command to be issued before every write. This isn't perfect, but it
  should stop "Gals Fighters" from writing all over itself.

**Comment by clobber** [comment]
Hey, I didn't forget about you! Neopop's NGP emulation is really broken compared to Mednafen's NGP module, so we've added NGP support through Mednafen. You should be able to finally enjoy Gals Fighters.

This is available in OpenEmu 2.0.3 and the Mednafen 0.9.39.2 core plugin.

**Comment by Zwitscherer** [comment]
Awesome, thanks for not forgetting, I will give this a try this coming weekend and if the games work fine now maybe an extensive long testing and report back here :-)

**Comment by Zwitscherer** [comment]
Hello,

was a little busy over the last weeks but finally had some time for gaming again this weekend and also was looking forward to playing Gals Fighters on my Mac, however for whatever reason also using the Mednafen core still lets the game freeze all the time, which is very strange since I played it a long time back then with Mednafen on Windows without any such issues.

I made a quick and short video recording with Quicktime of Gals Fighters under OpenEmu where you can see it freeze two times, I hope this is useful:

https://youtu.be/wJDw9G_eeIw

**Comment by clobber** [comment]
Hrm okay, you will need to try it on standalone Mednafen 0.9.39.2 to see if you can replicate the same crash. Our core plugin of Mednafen is unmodified, so if the crash happens in our port I'm curious if it happens with standalone too. If so, we can let the author (Ryphecha) know about the it.

**Comment by clobber** [comment]
> -- 1.22.2: --
> April 13, 2019:
	NGP: Fixed a sequence point rule violation that could cause "Gals' Fighters" to malfunction when Mednafen was compiled with clang, per tip from stellarporter.

Was just looking over Mednafen's changelog. This appears to have been fixed back in version 1.22.2.
