### ISSUE TITLE
MAME Core NEO-GEO support

### ISSUE THREAD

**Issue by retrohex** [OpenEmu/OpenEmu#1415]
Can someone please explain how this works? I have my NEO-GEO bios rom loaded and it doesn't seem to be working. I'm quite sure it's the correct version. I've read elsewhere about people getting NEO-GEO rome to work... what am I doing wrong?

**Comment by ld** [comment]
Try to run `/Applications/OpenEmu.app/Contents/MacOS/OpenEmu YOU_ROM` from the Terminal to see what the console says.
