### ISSUE TITLE
"The operation couldn’t be completed. OpenEmu could not find a Core to launch the game"

### ISSUE THREAD

**Issue by arthurzqhu** [OpenEmu/OpenEmu#1471]
Every time I wanna launch a game, which I believed was playable, it just popped up a window and told me: "The operation couldn’t be completed. OpenEmu could not find a Core to launch the game. Make sure your internet connection is active and download a suitable core."

I'm not sure if it has anything to do with the Yosemite beta 2. And there is nothing in the "Cores" list in preferences.

Hope someone can help me out, thanks in advance!

**Comment by sineld** [comment]
Remove all versions of application from mac. Restart machine and re download the experimental.
This worked for me.

**Comment by NateTGM** [comment]
The same message pops up and i really need help.

**Comment by clobber** [comment]
@NateTGM Stop posting in years old issues that have nothing to do with your problem.
