### ISSUE TITLE
Keyboard options for "start" and "select" don't work for Nintendo DS

### ISSUE THREAD

**Issue by L-R-Ryan** [OpenEmu/OpenEmu#1474]
I am using a MacBook Air, Version 10.9.2.  OpenEmu is v1.0.1 and it also says: 829-gfe1aabc-Release

I know nothing about coding, so I don't think I have made many modifications.  

So, basically I can't access game versions of save.  I have tried putting start and select on different keyboard settings (currently on enter and right shift respectively), but that hasn't worked.  I only want to be able to access the game versions of the save to take advantage of some glitches, otherwise I would just save with the emulator.  Help?

**Comment by Mkone32** [comment]
I am having the same problem except on pokemon black and that does have a menu. I tried using a control and changing the key bindings but nothing seems to be working.

**Comment by LeAzul** [comment]
hi Mkone32, I am now experiencing these problems right now, have you fixed the issue? if so could you help me to select the start button in Pokemon black as when I click the return key nothing happens
Thanks

**Comment by MKsomething** [comment]
Please if anyone can help with this, I have this problem with pokemon white
I've clicked every assigned button but nothing seems to work
can't get past the "click start" on the select screen

I hope someone knows what it is :D

**Comment by MKsomething** [comment]
> hi Mkone32, I am now experiencing these problems right now, have you fixed the issue? if so could you help me to select the start button in Pokemon black as when I click the return key nothing happens
> Thanks

I found a fix, download DeSmuME again, open the dmg and take the DeSmuME and drop it on top of the Nintendo DS page from OpenEmu, if it doesn't work the first time just try again, worked for me after the 2nd time (probably didn't give it time to load it) also don't select continue from last time just to be sure

DeSmuME download: http://desmume.org/download
