### ISSUE TITLE
Keyboard control: "Num 4" is always detected as "Num 1"

### ISSUE THREAD

**Issue by brevilo** [OpenEmu/OpenEmu#1482]
Using version 1.0.3 and Apple full-size international keyboard:

trying to set "Num 4" in keyboard controls doesn't work because "Num 1" is always detected instead. All other keys seem to be detected as usual, even "Num 1" itself.

**Comment by cyco** [comment]
Fixed in 5c6b0d754c30f27c41f0f39a9164e038e4d4c090
