### ISSUE TITLE
Automatic creation of .cue sheets

### ISSUE THREAD

**Issue by Diskutant** [OpenEmu/OpenEmu#1485]
Wouldn't it be possible to create the standard .cue sheet when the user adds a .img or .iso or .bin file when there are no audio (.wav) files next to the image file?

Also, when there are audio files, but no .cue sheet, it would be nice if OpenEmu tells the user that the audio files will not get imported and a .cue sheet is needed, with a link to some more explanation.

**Comment by i-c** [comment]
It'd probably be a good idea to give some kind of warning or info box when using a "default" cue. Maybe something like the current "pick a system" screen, where you have to check off each iso you want to have a default cue file added for? That way the user is discreetly reminded that it may not work if they have an ISO that's not just one data track.

**Comment by clobber** [comment]
Was an interesting idea but this isn't possible. A cue sheet is like a table of contents for a binary disc image and it is impossible to properly recreate after the fact. The solution here is to download a better rip.
