### ISSUE TITLE
why the graphics on the ps1 emulator is so cheesy?

### ISSUE THREAD

**Issue by Razor96** [OpenEmu/OpenEmu#1497]
here's some screens the first is from open emu the other is from another emulator

http://imgur.com/DQuWlC0

http://imgur.com/7QNeoRn

**Comment by sirsmeghead** [comment]
Is there no support in Mednafen for actually rendering in higher resolution?
The whole point to me using emulators is that I can actually run the games in higher resolutions + filters to make them look better than the original games.
