### ISSUE TITLE
"An error occurred during persistent store migration"

### ISSUE THREAD

**Issue by TashaLee** [OpenEmu/OpenEmu#1512]
Hi every time I try to open 'openEmu' an error message comes up "An error occurred during persistent store migration", before closing. I've restarted my computer and tried a few things but can't get it to open. before this it was opening to a complete black screen but now it won't open at all. I'm unsure of what version it is but i did recently update it. 

I'm on an iMac 
Processor  2.9 GHz Intel Core i5
Graphics  NVIDIA GeForce GT 750M 1024 MB
Software  OS X 10.9.4 (13E28)

**Comment by gustabob** [comment]
Em I need help with the same problem but is worst, because openemu don't start in any case so, can anyone help me please ?
