### ISSUE TITLE
SNES RetroPort Adapter Only Maps 4 Buttons

### ISSUE THREAD

**Issue by ChristopherHale** [OpenEmu/OpenEmu#1522]
I'm having an issue where I try to assign my SNES controller's buttons in the Control section of preferences but the buttons only map 4 of the 8. The rest duplicate. Here's the mapping I get for the Super Nintendo Controller mapping.

![screen shot 2014-07-27 at 8 03 47 am](https://cloud.githubusercontent.com/assets/8281945/3714278/3d542432-159f-11e4-97c4-7af785c74f85.PNG)

D-Pad works.
Select: Button 3
Start: Button 4
A: Button 2
B: Button 2
X: Button 1
Y: Button 1
L: Button 3
R: Button 4

To work around this issue I'm currently using a controller to keyboard mapper to access all the buttons. I've no issues using the controller in games such as FEZ or Cave Story without the keyboard mapper. Is there anything I can try to get my buttons to show up as 1 though 8?

![screen shot 2014-07-27 at 8 05 44 am](https://cloud.githubusercontent.com/assets/8281945/3714280/8438215a-159f-11e4-93e0-ff5349175df3.PNG)

**Comment by NeoTeo** [comment]
bump

**Comment by ChristopherHale** [comment]
Sorry, I stopped using this program because of this issue.
