### ISSUE TITLE
DS Multiple Button Input Problems

### ISSUE THREAD

**Issue by Axellae** [OpenEmu/OpenEmu#1523]
While playing there are moments where I'm required to hold certain buttons down together to activate things (for example L and R trigger + A). But for some reason it doesn't seem to be registering properly? Any thoughts?

Running v1.03 on OSX 10.7.5

**Comment by clobber** [comment]
Right, this is not a bug. Keyboards (sometimes depending on model too) are limited on the number of keys they will register at once, especially depending on row. You could remap your L + R + A binds momentarily to 1, 2 and 3 on the keyboard and those should probably register.

**Comment by palmerj3** [comment]
I know this ticket is old but I found it on google so I'm sure others will too. Remapping L to 1 and R to 2 on my keyboard worked and allowed me to get past the area that required it in Chronotrigger. Nice tip!
