### ISSUE TITLE
Add generic gamepad/joystick controller artwork

### ISSUE THREAD

**Issue by pokebyte** [OpenEmu/OpenEmu#1534]
It would be great if some generic controller artwork was available. It would go a long way to getting blueMSX-Core out of "experimental" status.

**Comment by clobber** [comment]
Old, but we're focusing on only doing real artwork. Computer systems that were merely just keyboards probably won't get any. Eventually we'll do a release that focuses all on computer systems (Atari 8-bit, C64, MSX, ZX Speccy, etc) which will be cool.
