### ISSUE TITLE
Shaders and Filters

### ISSUE THREAD

**Issue by TRIFORCE89** [OpenEmu/OpenEmu#1544]
I'm able to drag .cg files into the main OpenEmu window, but I'm not having success with .cgp files.

Noticed in the plugins/filters directory that NTSC (Blargg) is a .cgp, and it seems I can edit that somewhat (I changed the ntsc_filter to rgb). But I'm unable to add more .cgp's here.

If possible, in a future release can the following be included?

- CRT-Geom-Flat shader + Blargg's NTSC RGB filter
- Harlequin's Game Boy Shader variations

Thanks,

**Comment by clobber** [comment]
.cgp and assets that accompany those will need to be manually imported. That shader spec can get a little out of control in terms of includes and we don't (and won't) parse any of those on import. In the future we'll be migrating back to GLSL anyway.
