### ISSUE TITLE
Can't download box art for ROMs known to work

### ISSUE THREAD

**Issue by razi0** [OpenEmu/OpenEmu#1547]
I recently deleted all of the support files and reinstalled OpenEmu (I got into some mess switching from the regular to the experimental version). For some reason, the only box art that will now download is for Actraiser for SNES. No other box art will download. These are all no-intro ROMs from the Internet Archive whose box art previously downloaded perfectly, so I have no reason to believe it is an issue with the ROMs.

**Comment by vinnyp** [comment]
I'm not able to download any box art for my games. I'm running v2.0.1. This is a clean install and the first time I'm running OpenEmu. If there's no issue with the box art server, I'm guessing it's the file metadata. 

Is there a guide published on file name conventions / metadata that needs to be present in order for it to find the box art?

**Comment by vafan** [comment]
Hello. I have the same problem with cover art / box art not downloading. Running the latest experimental release.

Another question - when/if it´s working - are there any images for Mame-arcade-games aswell?

If the database is offline, where can i verify if it´s offline or online?
