### ISSUE TITLE
Can't Open ROMs - "Couldn’t communicate with a helper application."

### ISSUE THREAD

**Issue by TinyOrange** [OpenEmu/OpenEmu#1554]
Whenever I open a ROM for the gba I always get a popup saying: "Couldn’t communicate with a helper application." My game file is a .gba file. The console message:
![screen shot 2014-08-19 at 10 57 44 pm](https://cloud.githubusercontent.com/assets/5943858/3975967/dfa96d9a-2815-11e4-88a6-b4de4eceb475.png)

**Comment by Thingii** [comment]
Hey, having the same kinda problem with the "couldn't communicate with helper..." and i dont quite seem to get this right. Is it still the same way to fix this?? pls help
