### ISSUE TITLE
Action to rescan drives for rom files

### ISSUE THREAD

**Issue by cyco** [OpenEmu/OpenEmu#1560]
As requested by @corysimmons in #486 we could add an action to run setup assistant's import step again. To keep the interface clean this could be hidden away under File->Library->Scan Drive for roms and use game scanner to show import progress. We should pre-select files to import using spotlight.

**Comment by greggman** [comment]
Unfortunately I just spent 30 mins importing 1000s of files and then OpenEMU crashed. All the files appear in the library folder but none of them appear in OpenEMU which suggests this option really is needed.
