### ISSUE TITLE
Import .ccd/.img CD images

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/OpenEmu#1569]
Popular PSX CD format on Windows.

There's a converter to CUE here:
http://www.gnu.org/software/ccd2cue/

(Linux only)

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu-SDK/commit/2bd7a1365e020c561e4ea7826b3d312b735a8173
https://github.com/OpenEmu/OpenEmu/commit/606f950d0f7aba5a33bd7819aaf693cf9ff0fb45
https://github.com/OpenEmu/OpenEmu/commit/4e6f8b5d849e54e4f5cb51dc9fab4746a5714fec
