### ISSUE TITLE
Support physical CD games

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/OpenEmu#1573]
1. Allow playing games with the real CD/DVD, on cores that support this.

2. For the sake of archival, possibly provide a way to create CD images in the library. Disk Utility will do .iso ripping, but not bin/cue creation which many PSX games would need.

**Comment by clobber** [comment]
As of version 0.9.38, Mednafen removed support for physical CD's. As for ripping, we should just provide a link to Redump's guide: http://wiki.redump.org/index.php?title=Dumping-Guides
