### ISSUE TITLE
Run filters at their designed output size only

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/OpenEmu#1576]
Filters like HQ4X etc. only work properly if the output image is exactly 4x the size of the input image. 

Instead of merely drawing the filter at the current size of the window, do another render pass to each filter's design size and then draw that to the window size.

Related:
- allow filters to either be upsized or downsized directly from their output factor if they're designed that way. It might be fine to upsize with Linear filtering for instance.
- use the output factor to upgrade 2x filters to 4x version on retina display?

**Comment by stuartcarnie** [comment]
This will be fixed when remote-layer and Metal support merges

**Comment by mrvacbob** [comment]
It sure will.
