### ISSUE TITLE
Try to make Cg framework optional

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/OpenEmu#1578]
NVidia Cg framework is deprecated: https://developer.nvidia.com/cg-toolkit

It will never be updated for GL 3.2 core profile. That means we can't use core profile GL contexts to draw the game layer.

I guess we can't stop people from writing shaders as cgp/cg bytecode, but we could avoid it and then have a purer core profile drawing path… in case that's faster or something.

**Comment by Armada651** [comment]
OpenEmu should definitely switch to GLSL, there's no reason to use the CG Framework if you only support an OpenGL backend. Retroarch has quite a good compiler script to convert existing CG shaders to GLSL shaders.

As for my HQx shader I already provide GLSL sources, though I don't believe they're multi-pass yet, but that's easily fixed.
