### ISSUE TITLE
Reevaluate possibility of a PS2 / Playstation 2 core due to recent PCSX2 progress

### ISSUE THREAD

**Issue by drcreek** [OpenEmu/OpenEmu#1584]
I've been following the progress of the PCSX2 emulator and very recently a lot of progress has been made in bringing it back to OS X. 

I THINK it now builds and runs on OS X or it is incredibly close to being able to do so.

Might be worth at least taking a look and begin planning on how to implement it? 

They seem to be stuck on one or two issues also so they might need a little help finishing it off?

**Comment by franklinyu** [comment]
[Play!](http://purei.org/) as a possible alternative?
