### ISSUE TITLE
MAME games not opening

### ISSUE THREAD

**Issue by ileftmyattackbootsinchina** [OpenEmu/OpenEmu#1588]
I downloaded the punisher arcade rom, put the files in a zip, added the zip to open emu, the game is there but when i click it nothing happens, the mouse curser disappears but the game doesn't open. what am i missing? 

i'll provide some images
![screen shot 2014-09-04 at 8 27 49 pm](https://cloud.githubusercontent.com/assets/8476535/4147947/acf61d66-341e-11e4-87f3-fd6781cf9915.png)
![screen shot 2014-09-04 at 8 28 14 pm](https://cloud.githubusercontent.com/assets/8476535/4147948/ad003314-341e-11e4-9284-9eea25f7a114.png)
![screen shot 2014-09-04 at 8 28 48 pm](https://cloud.githubusercontent.com/assets/8476535/4147945/acf0967a-341e-11e4-9cca-a2f2724f1fa2.png)
![screen shot 2014-09-04 at 8 29 00 pm](https://cloud.githubusercontent.com/assets/8476535/4147946/acf523ac-341e-11e4-8688-f44c66ebb9bb.png)

**Comment by pawelkrupinski** [comment]
On Mac, start OpenEmu, go to "Arcade" section right-click on any rom there, click "Show in Finder". Copy qsound.zip to the same location.
