### ISSUE TITLE
Unable to detect Snes games

### ISSUE THREAD

**Issue by sohojohn84** [OpenEmu/OpenEmu#1597]
Hello, 

I have a collection of Snes games. However OpenEmu only detects the .sfc roms, whereas other emulators also detect the .smc roms.

Could you help me solve this issue? Is there a plugin I should get? Snes games can come in 3 to 4 different .file formats, however, I noticed that openemu only recognizes the .smc ones...

Thanks!
Jon

**Comment by jlandrum** [comment]
I'm having this issue myself - it's listing SMC files as Arcade and they won't launch.

**Comment by Zarrindast** [comment]
> Actually they do. You are doing something horribly wrong and aren't being clear enough.

There's no need to be sarcastic and rude to someone-- mimicking their speech?
