### ISSUE TITLE
Controller Issue - GC/N64 to USB, v2

### ISSUE THREAD

**Issue by x3digital** [OpenEmu/OpenEmu#1604]
I am able to select the GC/N64 to USB, v2 controller in the controller preferences, but it freezes when I try to map the analog joystick. I am able to close and reopen open emu and map the rest of the buttons, but seem to only be able to set 'Up' to trigger y and 'Left' to trigger x. I had thought these would be treated like an axis with a x, -x, y, -y. How can I get these to map correctly?

**Comment by khanh** [comment]
having the same issue

**Comment by clobber** [comment]
Issues using adapters should be resolved as of OpenEmu 2.2.
