### ISSUE TITLE
Integrate MAMEHub

### ISSUE THREAD

**Issue by MisterTea** [OpenEmu/OpenEmu#1618]
Hey guys,

I'm the solo developer of MAMEHub ( www.mamehub.info and https://github.com/MisterTea/MAMEHub ).  It's a netplay-enabled version of UME and comes with its own frontend & chat.  I want to focus on making the netplay better and I don't have time to work on the frontend, so it would be great if we could use your frontend.  Check out mamehub and let me know if you want to work together.

**Comment by astrange** [comment]
Hope this was dealt with offline, but the wiki is the best place to track things:
https://github.com/OpenEmu/OpenEmu/wiki/Console---Core-Plugin-Status-&-Wishlist
