### ISSUE TITLE
Wrong aspect ratio in NES/SNES

### ISSUE THREAD

**Issue by ghost** [OpenEmu/OpenEmu#1638]
The original NES/SNES screen resolution was 256 × 224 pixels and it don't have exactly 4:3 ratio. The correct NES/SNES aspect ratio is 8:7 rather than 4:3.

**Comment by threenator** [comment]
> No. We automatically correct all console systems to 4:3, which is what you would have seen on a television. 8:7 was its _internal_ aspect ratio.

But what about Super Metroid, in which the ball looks stretched on 4:3?
