### ISSUE TITLE
An error occurred during persistent store migration

### ISSUE THREAD

**Issue by AntonFagerberg** [OpenEmu/OpenEmu#1654]
Just updated to 1.0.4 and I can no longer start the program because of "An error occurred during persistent store migration".

If I copy the entire OpenEmu-folder from ~/Library/blabla to another machine using the previous version, the library opens fine. If I once again chose to update OpenEmu to the latest version on that machine, the same error occurs on that machine as well.

**Comment by astrange** [comment]
Old issue.
