### ISSUE TITLE
Gamecube

### ISSUE THREAD

**Issue by ghost** [OpenEmu/OpenEmu#1656]
Hello. I have Openemu with a GameCube core (pictured) but there seems to be a problem. I have some iso's of super mario sunshine, mario kart double dash!!, and some other Nintendo games. Here's the problem, whenever I try to drag the iso's where it says drag 'n drop games, the emulator always quits, but when I load them manually, the app doesn't quit, but the games don't load. Any help would be much appreciated. If some additional information is needed please let me know.
![screen shot 2014-10-19 at 6 20 53 pm](https://cloud.githubusercontent.com/assets/9310611/4695183/dc286b0a-57e8-11e4-85ed-0fcb4c0db80a.png)

**Comment by SEGADREAM** [comment]
Where did you get the system plugin and core from?
