### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by JuganDyso** [OpenEmu/OpenEmu#1666]
OpenEmu hasn't let me use my keyboard since the most recent update, I can no longer play any games in it without my keyboard.

**Comment by sliverado** [comment]
I'm having the same issue and even after I deleted the file it still isn't working. this has to be a openemu issue because it is happing with all cores

**Comment by FullForceGamer** [comment]
It's happening, not just with open emu, but with other emulators like dolphin

**Comment by Fletch28** [comment]
When i delete the bindings then re open OpenEmu the bindings comeback
