### ISSUE TITLE
Crashes when using AirPlay

### ISSUE THREAD

**Issue by MattzOnFIre** [OpenEmu/OpenEmu#1667]
![screen shot 2014-10-24 at 3 28 32 pm](https://cloud.githubusercontent.com/assets/9387475/4777271/3278c45e-5bcd-11e4-98d5-d8791aefc387.png)

I've been running OS Yosemite with OpenEMU for a while and never had an issue.
Recently, I updated to the newest build for OpenEMU and ever since then, OpenEMU crashes when AirPlay is turned on.

**Comment by astrange** [comment]
Well, that log should be enough!

Closing since this is old.
