### ISSUE TITLE
"Black screen" when switching consoles in library view.

### ISSUE THREAD

**Issue by peterb12** [OpenEmu/OpenEmu#1675]
This is a bit vague, and I'm sorry.

I'm setting up a new OpenEmu install on a retina IMac, running 10.10.  After importing many files at once, during the art lookup, I would occasionally click on another device.  The main view (with the rom list) turned completely black, and the app became seemingly unresponsive.

Only seems to happen intermittently.  I tried to reproduce it just now to take a screen capture and couldn't, but I DID see a black flash, rarely, when switching library views.  This makes me wonder if there's a race somewhere.

**Comment by clobber** [comment]
Thanks. Going to dupe this with #1818 (I know, yours is the older ticket).
