### ISSUE TITLE
Can not option Region For PSP.

### ISSUE THREAD

**Issue by gdgoldlion** [OpenEmu/OpenEmu#1686]
I want useing language is Chinese,HongKong & TaiWan.
Because I have some ios for those Region.
I can't play game by those language.
plz help me.

**Comment by worldedite** [comment]
> I find a Solution for this issue.
> We can use UltralISO software to fix .iso file.
> Just delete english language package in .iso and rename other language package that you need to “english”，then it work ok.
> Haha,very easy!

emmm  能具体一点吗
