### ISSUE TITLE
pokemon black 2 blackscreen durring game

### ISSUE THREAD

**Issue by JuganDyso** [OpenEmu/OpenEmu#1691]
I've been playing a pokemon black 2 rom but when i try to go to certain places the emulator blackscreens(i've been fine with it so far because it wasnt hindering but now it's happening at one of the main storyline areas so i can't finish the game), i think it's my rom but i'm curious what others might have to say.

**Comment by vlisa** [comment]
I know this post is really old but JuganDyso I am having the same problem. Were you able to load your saved OpenEmu file in DesMuMe or did you have to start from the beginning again?

**Comment by JuganDyso** [comment]
Unfortunately yes i had to start over

**Comment by JuganDyso** [comment]
But the black screen does not occur ever when you use DesMuMe

**Comment by clobber** [comment]
We have mentioned in other issues related to this that there are bugs in the JIT dynarec which is enabled in our core port but **not** enabled in the standalone. This could also be related to the save file bug that was present in Desmume's previous release or a general AP patch (or lack of) issue.

Sorry, nothing we can do about this. I recommend using their standalone app.
