### ISSUE TITLE
PS3 Dualshock 3 Sixaxis Button Mapping Not Responding

### ISSUE THREAD

**Issue by theschlaepfer** [OpenEmu/OpenEmu#1699]
So as I play different games on a controller, I've realized that some button layouts work better than others. However, when I go to change the mapping assigned to my Dualshock 3, I can't map anything. Basically, the preferences won't respond to any input from my controller. It works fine in-game. I'm using the N64 core.

**Comment by kirslz** [comment]
I've used a Game controller plugged into my Wiimote Controller (just like a Nunchuck but I'ts a controller http://i2.listal.com/image/2241830/600full-xenoblade-chronicles-media.jpg) and after I did that, the menue wouldn't respond either. So I plugged the Nunchuck/Controller out and now all my Wiimote Controlles aren't responding to the set up menue.

Even my USB Dual Analog Rumble Pad from Saitek doesn't work.

I need help!
