### ISSUE TITLE
Playstation Won't run.  BIOS showing up as games in Atari 2600.  Duplicate in Odyssey

### ISSUE THREAD

**Issue by ZimMan2** [OpenEmu/OpenEmu#1702]
So I just installed the experimental pack, tried running a game, (Spider-Man, for reference), and it simpy won't open.  I created a BIOS folder in the Library like was said by multiple sources, added the BIOS into it, and now those BIOS show up in-app as games under Atari 2600.  In addition, a duplicate of the game is showing up in the Odyssey 2 library.  

An earlier thread I found on Google said that I needed to go into the app bundle for Atari, but I have no clue to find such a thing.  The Library only shows me Bindings Configurations, BIOS, Cores, Game Library, Mednafen, and Save States.

**Comment by beastwork** [comment]
@clobber I may be wrong but it feels like you're dismissing this issue as a user error or @ZimMan2 's inability to follow the documented instructions.  I had the same issues (and more) while getting the Playstation emulator up and running.  In my case, when the app was installed the BIOS folder was not created.  So whenever I dragged the bios into the GUI I got the same import errors as above.  I manually created the BIOS folder, dropped in the correct BIOS files and everything was sorted out.

**Comment by clobber** [comment]
@beastwork I dismissed the issue on there being a bug with BIOS folders not getting created in 1.0.3 and also not following documented instructions. If the problem happened to you in 1.0.4, it would be user error.

**Comment by beastwork** [comment]
@clobber Well I'm at a loss my friend.  It's pretty hard to mess up drag and drop functionality.  The emulator works great now.  I'm running this on Yosemite.  Perhaps that is causing some of the issue. Oh well....

**Comment by clobber** [comment]
> It's pretty hard to mess up drag and drop functionality

That's right. Which is why when you drag and drop in the **correct and unzipped** SCPH5500.BIN, it'll automatically end up where it needs to go.

**Comment by ngude** [comment]
i dragged and dropped 5500,01,02 into open emu and watched as they went to the correct BIOS folder, but attempting to launch any psx games results in nothing. no black screen, just nothing.

any ideas? even though the bios files were taken without error by openemu, i doublechecked their md5 and everything matches up.

**Comment by electrikdave** [comment]
I am having the exact same problem on v1.0.4. 

I am prompted for the 5500,5501,5502 bios files. 
![screen shot 2015-10-13 at 11 56 06 am](https://cloud.githubusercontent.com/assets/15109666/10460250/8313c310-71a1-11e5-95fb-50069ee30091.png)

I have checked the MD5 in Terminal and they match the MD5 on this guide: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

![screen shot 2015-10-13 at 11 54 51 am](https://cloud.githubusercontent.com/assets/15109666/10460264/8b660780-71a1-11e5-9445-d17235dd265d.png)
![screen shot 2015-10-13 at 11 55 06 am](https://cloud.githubusercontent.com/assets/15109666/10460263/8b5f906c-71a1-11e5-870e-c615073ab180.png)

When I drag them in, the Game Scanner pops up and says "Resolve 3 Issues."
![screen shot 2015-10-13 at 11 57 46 am](https://cloud.githubusercontent.com/assets/15109666/10460294/a5ccf656-71a1-11e5-9247-6dbdac1099d3.png)

When I click the arrow to proceed and resolve, the same options appear for Atari, Odyssey, Sega, etc. 
![screen shot 2015-10-13 at 11 56 31 am](https://cloud.githubusercontent.com/assets/15109666/10460317/bcedc9be-71a1-11e5-8dbd-233151580d71.png)


I tried manually creating a BIOS folder in ~/Library/Application Support/OpenEmu and also in ~/Library/Application Support/OpenEmu/Playstation, and it will not load either placing the .BIN files manually, nor importing via the UI. 

What would you recommend confirming or trying next?

**Comment by electrikdave** [comment]
I figured it out. The filenames were incorrect. I had the files named "PSX - SCPH5501.BIN" instead of "SCPH5501.BIN."

**Comment by Arthasu** [comment]
You can download the 3 BIOS files from here https://kat.cr/openemu-psx-bios-t11556957.html

**Comment by clobber** [comment]
@Arthasu Don't post that here again.
