### ISSUE TITLE
Can't add scph5501.bin or scph5502.bin bios files to Playstation emulator.

### ISSUE THREAD

**Issue by agentmith** [OpenEmu/OpenEmu#1704]
At first I thought it was case-sensitive, as the bios files were showing up as unsortable games. I matched the case of the file in the error (lowercase), and now when dropping the bios files on the emulator nothing happens at all. I've tried several versions of them, and renaming scph7502.bin to 5501 or 5502 as a test, and nothing works. Maybe provide a way to map bios files manually instead of automatically sorting them? It's fairly picky in recognizing the bios files in general, and I'd like to have the freedom to choose different ones (not necessarily 5501 for US games, for example).

All relevant cores are downloaded and installed, and up to date as of 11-11-2014.

OpenEmu version 554-gf588330-Release
MacBook Pro Retina 2014
OSX Yosemite

**Comment by MauricioA** [comment]
All the SCPH5502.bin files I find have a different md5 than the one in the user guide, so I can't get any PSX game to work anymore.
The bad thing about it is that it used to work perfectly fine on a previous version (at least with US games), but it started requiring 5502 when I updated OpenEmu.

**Comment by MauricioA** [comment]
Nevermind, found one with the correct md5 by googling scph5502 psxdev.

**Comment by oller** [comment]
:+1: for the google query @MauricioA

**Comment by TheEnigmaSoul5** [comment]
I can't find the NA version BIOS no matter WHAT I DO. I want to play Rival Schools, but I can't do it because of one.........stupid...........BIOS FILE. I already have the other two, why is the NA version such a pain to find.

**Comment by TheEnigmaSoul5** [comment]
Never mind. Just renamed 7003...........I feel dumb now.....

**Comment by nguyenthanhvy105** [comment]
https://www.youtube.com/watch?v=i52AIZuEM5w
