### ISSUE TITLE
Multiple quit dialog boxes

### ISSUE THREAD

**Issue by jetibbetts** [OpenEmu/OpenEmu#1711]
If you hit "Quit OpenEmu" more than once, multiple confirmation dialogs pop up.

![screen shot 2014-11-14 at 2 59 13 pm](https://cloud.githubusercontent.com/assets/3586227/5053341/ed80fac2-6c0e-11e4-9d21-25b38a041be0.png)

**Comment by cyco** [comment]
6db9e39e0b46f61a66005eb46b593d9803b2a587
