### ISSUE TITLE
Mednafen initially fine, next day extreme lag.

### ISSUE THREAD

**Issue by Jakeysp** [OpenEmu/OpenEmu#1713]
Hiya,

So I grabbed experimental 1.0.4 on Friday, installed the latest Mednafen (0.9.34.1 apparently) and loaded in my scph5500.bin, scph5501.bin and scph5502.bin BIOS files with correct hashes. Over the last few days I've been loading all of my PS1 games in (All .bin/.cue, mostly PAL) and performance has been absolutely perfect.
This afternoon, I played a game for a bit, then decided to load a new game in to try out. I opened it but discovered performance was horrible. The game seemed to speed up and slow down like the computer cannot regulate speed. That's fine, can't win them all. However, now ALL the games including those that were fine not ten minutes prior perform equally as badly. Even the BIOS (White Sony and Black Playstation splashes) have skipping audio and lines through them.
I tried restarting my Mac, uninstalling OpenEmu, deleting the library directory and application support directories and recreating everything fresh but the problem persists on all games, they are now totally unplayable where yesterday they were flawless. I googled the issue and there was some suggestion from clobber to try nearest neighbour or pixellate filters, nearest neighbour was already selected. Changing to some of the other filters does make it worse but none of them solve the problem. I checked my console and noticed while the game runs I get the following errors frequently:

17/11/2014 9:06:24.161 pm OpenEmuHelperApp[2138]: parent application is: OpenEmu
17/11/2014 9:06:24.178 pm OpenEmuHelperApp[2138]: Some shit about the game.
17/11/2014 9:06:24.216 pm OpenEmuHelperApp[2138]: Setting up emulation
17/11/2014 9:06:24.222 pm OpenEmu[2132]: SETUP DONE.
17/11/2014 9:06:24.259 pm OpenEmuHelperApp[2138]: Begin separate thread
17/11/2014 9:06:24.260 pm OpenEmuHelperApp[2138]: RT policy: 0.007000s (limit 0.030000s) every 0.032985s
17/11/2014 9:06:24.413 pm WindowServer[125]: WSGetSurfaceInWindow : Invalid surface 1619828100 for window 1073
17/11/2014 9:06:24.413 pm WindowServer[125]: WSGetSurfaceInWindow : Invalid surface 1619828100 for window 1073
17/11/2014 9:06:24.413 pm WindowServer[125]: WSGetSurfaceInWindow : Invalid surface 1619828100 for window 1073
17/11/2014 9:06:58.543 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00023 seconds behind
17/11/2014 9:07:05.129 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00268 seconds behind
17/11/2014 9:07:13.604 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00383 seconds behind
17/11/2014 9:07:23.964 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00023 seconds behind
17/11/2014 9:07:24.250 pm com.apple.xpc.launchd[1]: (com.apple.imfoundation.IMRemoteURLConnectionAgent) The _DirtyJetsamMemoryLimit key is not available on this platform.
17/11/2014 9:07:28.692 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00071 seconds behind
17/11/2014 9:07:33.245 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00957 seconds behind
17/11/2014 9:07:54.980 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00839 seconds behind
17/11/2014 9:07:59.200 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.01148 seconds behind
17/11/2014 9:08:04.593 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.01344 seconds behind
17/11/2014 9:08:19.444 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.01162 seconds behind
17/11/2014 9:08:23.600 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.013 seconds behind
17/11/2014 9:08:29.491 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.01097 seconds behind
17/11/2014 9:08:34.712 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00825 seconds behind
17/11/2014 9:08:59.398 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00219 seconds behind
17/11/2014 9:09:02.693 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00522 seconds behind
17/11/2014 9:09:05.708 pm OpenEmuHelperApp[2138]: Synchronizing because we are 1.00907 seconds behind
17/11/2014 9:09:23.200 pm OpenEmu[2132]: Could not create save state file at url: AE264142-983B-4E9E-858D-E0E19B9F451F -- file:///var/folders/4d/znqvxk9s7td4k9l23r5dsz080000gn/T/
17/11/2014 9:09:23.208 pm OpenEmuHelperApp[2138]: Did finish separate thread
17/11/2014 9:09:23.247 pm OpenEmu[2132]: Deallocating proxy: <OEThreadProxy 0x610000449ed0, target: <OEGameDocument 0x6000001b7e60, ROM: 'Spyro the Dragon', System: 'openemu.system.psx', Core: 'org.openemu.Mednafen'>>
17/11/2014 9:09:24.218 pm WindowServer[125]: disable_update_timeout: UI updates were forcibly disabled by application "OpenEmu" for over 1.00 seconds. Server has re-enabled them.
17/11/2014 9:09:24.282 pm WindowServer[125]: WSGetSurfaceInWindow : Invalid surface 1620006726 for window 1073
17/11/2014 9:09:24.282 pm WindowServer[125]: common_reenable_update: UI updates were finally reenabled by application "OpenEmu" after 1.06 seconds (server forcibly re-enabled them after 1.00 seconds)
17/11/2014 9:09:24.283 pm OpenEmu[2132]: OE_removeStateWatcher

I am running Yosemite 10.10 on a 3.4Ghz Core i7 with 16GB memory and an AMD Radeon HD 6970M 2GB. Any advice is appreciated!

**Comment by swillion** [comment]
Having the same problem. Works for awhile until slow down occurs and Mednafen has to be deleted/reinstalled through the GUI.

Any update on the issue? Or any solution as how to manually install Mednafen versions? They can be inputted and recognized in the Core Prefs but OpenEmu doesn't seem to support versions other than what it downloads/installs. (Either does nothing or gives error.)
