### ISSUE TITLE
Adding Tetris 3.smc (SNES) to library causes crash. OpenEmu v1.0.4 and previous

### ISSUE THREAD

**Issue by Sweek9** [OpenEmu/OpenEmu#1727]
If you need the specific file for testing I can send it to you.

**Comment by astrange** [comment]
Please post the crash log. You can find it in ~/Library/Logs/DiagnosticReports/ in a file starting with OpenEmu.

**Comment by Sweek9** [comment]
I thought I did but that was ages ago, my computer broke months ago. If I ever get it working and recover my hdd I'll do that. 

           Sincerely,
                 -Pål Hart
