### ISSUE TITLE
Wiimote connection issues on 10.10 yosemite.

### ISSUE THREAD

**Issue by RyanD** [OpenEmu/OpenEmu#1740]
Hey all,

Trying to use a Wiimote.. having some trouble.  Never vibrates.. bluetooth menu item shows a device momentarily connected and then drops.  A device is left in my bluetooth prefs: Nintendo RVL-CNT-01-TR.

Tried a black wiimote plus and a white old school wiimote.

Any clues? Running experimental release.
Macbook pro (late 2011) running yosemite (10.10.1, 14B25). Tried removing all bluetooth plists.

Here is log file: 

Dec  9 02:25:33 Hudson.local OpenEmu[572]: Attempting pair
Dec  9 02:25:33 Hudson.local OpenEmu[572]: IOBluetoothDevicePair BluetoothHCIPINCodeRequestReply success!
Dec  9 02:25:34 Hudson.local OpenEmu[572]: Pairing finished <IOBluetoothDevicePair: 0x610000c4c9c0>: 0
Dec  9 02:29:43 Hudson.local OpenEmu[572]: Attempting pair
Dec  9 02:29:43 Hudson.local OpenEmu[572]: IOBluetoothDevicePair BluetoothHCIPINCodeRequestReply success!
Dec  9 02:29:43 Hudson.local OpenEmu[572]: Pairing failed, attempting inverse
Dec  9 02:29:44 Hudson.local OpenEmu[572]: Pairing finished <IOBluetoothDevicePair: 0x610000253800>: 5
Dec  9 02:29:45 Hudson.local OpenEmu[572]: Attempting pair
Dec  9 02:29:45 Hudson.local OpenEmu[572]: IOBluetoothDevicePair BluetoothHCIPINCodeRequestReply success!
Dec  9 02:29:45 Hudson.local OpenEmu[572]: Couldn't pair, what gives?
Dec  9 02:29:45 Hudson.local OpenEmu[572]: Pairing finished <IOBluetoothDevicePair: 0x6180008416e0>: 5
Dec  9 02:31:44 Hudson.local OpenEmu[572]: Attempting pair
Dec  9 02:31:44 Hudson.local OpenEmu[572]: IOBluetoothDevicePair BluetoothHCIPINCodeRequestReply success!
Dec  9 02:31:44 Hudson.local OpenEmu[572]: Pairing finished <IOBluetoothDevicePair: 0x6100006553f0>: 0

**Comment by MarcoMenu** [comment]
Thanks, uninstalling USB overdrive worked for me too: https://github.com/OpenEmu/OpenEmu/issues/2154

Hope it will be reported on the guide:  https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing
