### ISSUE TITLE
Wii U Pro Controllers don't output 100% of analog stick range

### ISSUE THREAD

**Issue by spacecowgoesmoo** [OpenEmu/OpenEmu#1748]
Second source: https://code.google.com/p/wjoy/issues/detail?id=30

I've owned two Wii U Pro controllers, and they both have the same issue - Wii U Pro Controllers don't output 100% of analog stick range. The effects of this depend on how the game is programmed to interpret analog input; Mario 64 is perfectly playable, FF7 Crisis Core is noticeable but not game breaking, and Ratchet+Clank PSP is impossible. There are also slight variations of this on every analog stick; you can test this by playing an affected game, finding the deadzone, and then switching control to the other analog stick. Other Wii U Pro controllers will have completely different deadzones. You can also test this by disassembling the controller; the analog stick will be able to output 100% in all directions without the plastic circle blocking it.

A non-intrusive solution could be to set OpenEmu to interpret 80% (just a guess) analog range as 100% when using a Wii U Pro controller. You could also add a Calibrate Joystick feature, but that would be more complicated and probably goes against your UI vision.

**Comment by clobber** [comment]
If you have a Wii U Pro controller handy, please see https://github.com/OpenEmu/OpenEmu/issues/3102#issuecomment-345170009
