### ISSUE TITLE
SABR filter fullscreen glitches

### ISSUE THREAD

**Issue by kokokurak** [OpenEmu/OpenEmu#1749]
Hi :) I'm having problems with SABR filter, which is my favorite on, on fullscreen. It renders line artifacts.

I have MacBook Air mid 2013. Tested on GameBoy, GameBoy Color and GameBoy Advanced roms.

Windowed, no artifacts:
![good](https://cloud.githubusercontent.com/assets/8510621/5428323/edf18ed2-83be-11e4-9c2a-ce9b7eddfb64.png)

Fullscreen, artifacts visible:
![bad](https://cloud.githubusercontent.com/assets/8510621/5428322/edea1300-83be-11e4-93e2-d95a78f1f5df.png)

**Comment by cyco** [comment]
Should be fixed in de531193178559677829757e1f8f037aad4f1621. Thanks @Armada651!

**Comment by Armada651** [comment]
@cyco Did you confirm that it really is fixed? Because I'm still about doubtful about it.

**Comment by cyco** [comment]
Nope, i trusted you on this one :P

**Comment by Armada651** [comment]
Hey, I just said "hopefully", since the issue seemed to be similar. xD
