### ISSUE TITLE
Crash when dragging game window between monitors on Yosemite

### ISSUE THREAD

**Issue by adaugherity** [OpenEmu/OpenEmu#1753]
OpenEmu 1.0.4, OS X 10.10.1

When dragging a game window (not the library) between monitors, as soon as the mouse pointer crosses to the target monitor, OpenEmu instantly crashes.  This did not happen under Mavericks.

It does not matter which monitor I start from, nor does changing the "Displays have separate spaces" setting.

Crash dump: https://gist.github.com/adaugherity/8b3236195f9b823a209d

**Comment by astrange** [comment]
Thread 1: -[OEGameView viewDidChangeBackingProperties] + 100
Thread 10: -[OEGameView render] + 2101

Need a lock on the game view.

**Comment by cyco** [comment]
You mean a lock on the context, right?

**Comment by astrange** [comment]
If it's going to call anything in the view in two threads at once, I think it's safest to lock the whole object, but you can go finer-grained if you're careful.

**Comment by cyco** [comment]
I couldn't reproduce the issue, so i won't know if i'm on the right track.

**Comment by adaugherity** [comment]
I built from git HEAD (38e601f) and it is now fixed.  Thanks!

**Comment by cyco** [comment]
Great. Thanks for confirming the fix.
