### ISSUE TITLE
Cover art missing after 1.0.4 database migration

### ISSUE THREAD

**Issue by ZachNyhus** [OpenEmu/OpenEmu#1759]
Hello:

I have a late-2010 Mac Mini, running Yosemite.

I used to play games on OpenEmu *all the time*, but I hadn't actually opened it in many months until this evening. The program opened just fine, and I saw my entire library right there. Within a few moments, the little pop-up window appeared, prompting me to update and install version 1.0.4. Naturally, I did this.

Now, the program appears to be completely borked. All the cover art disappeared for all the games (although the image files still reside in their proper folder), and when I try to play a game, it doesn't work right at all. When I double click a game, it will switch over to a completely garbled, jumbled mess of a screen. The audio usually sounds right, and the little control panel on the bottom is there alright, but the visual output of the game is completely jumbled.

I have tried deleting and reinstalling the game, which does't help. I've also tried installing older versions of the program, but those won't even open up at all. (I don't remember the error message I got, but it was definitely something I didn't understand...) Can you please advise me on what steps I should take to correct this issue? I would be very grateful for your help.

Thank you!

Zach

![screen shot 2014-12-23 at 12 44 14 am](https://cloud.githubusercontent.com/assets/10277471/5535370/df2ec880-8a42-11e4-8a6e-dfd0a93e59db.png)

![screen shot 2014-12-23 at 12 49 10 am](https://cloud.githubusercontent.com/assets/10277471/5535372/ee12638e-8a42-11e4-9e45-1ad833ac04b4.png)

**Comment by cyco** [comment]
Hey @ZachNyhus,

I took a look at your library. And somehow all cover entries in your database got cleared out. I don't think it can be fixed automatically.

![screen shot 2015-01-08 at 19 39 48](https://cloud.githubusercontent.com/assets/697021/5668198/2246bf32-976e-11e4-868d-9c149ae69134.png)

Do you remember which version you were using before installing the update? This sort of problem might occur if you skip a version of OpenEmu.

**Comment by ZachNyhus** [comment]
Hello:

Thank you for your response! I appreciate your assistance. I think it is
very likely that I skipped an update version. Not to worry, I have already
cleared out the cover art folder and manually replaced all the cover art,
so my problem is totally resolved now. Thanks for following up!

Best regards,

**Comment by Shouse7** [comment]
How do you have cover art? Mine is all still missing.

**Comment by ZachNyhus** [comment]
Hello,

I just cleared it all out the folder, and manually replaced it with new
image files from the internet. My library isn't huge, so this only took me
a few minutes.

Best wishes,

Zach

**Comment by Shouse7** [comment]
i did that, but now the art is not the same size as the "container square."

you see a semitransparent square that is 1/4 the size of the overall art square. the overall art box should fit 100% inside the semitransparent square. you having the same problem?

**Comment by ZachNyhus** [comment]
Nope, sorry, mine looks right.
