### ISSUE TITLE
N64 steelseries stratus xl - dpad not recognized

### ISSUE THREAD

**Issue by maxxst** [OpenEmu/OpenEmu#1765]
Hey there,
I was trying to set up my Stratus XL but I couldn't get the D-Pad set up. When I press any direction on it - it wouldn't do anything

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu-SDK/commit/565527c931964aa70a2707b0383765df2209f990

Will be available next release.
