### ISSUE TITLE
Can not open roms, do not get it!!!!!!!

### ISSUE THREAD

**Issue by ajt9589** [OpenEmu/OpenEmu#1766]
i downloaded the roms, dragged them into the "drag and drop games here" box, and then when i try to open a game, i get the error "Couldn't communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again."  seriously frustrating. I'm no programmer or whatever but i'm also not tech illiterate. I at least know my way around my mac. but when i right click "show in finder" on one of the games, it takes me to a folder that i can not find. "get info" on the file itself directs me to /Users/Baped/Library/Application Support/OpenEmu/Game Library/ but i can not search for this path or manually access it. i don't know whats going on here. tried utilizing some of the previously raised issues that seemed to be similar such as https://github.com/OpenEmu/OpenEmu/issues/925 to no avail. please. someone help.

**Comment by nielssorensen** [comment]
I'm pretty sure I shouldn't engage in this but... here goes.
Firstly, if you do know your way around a Mac, you'd know that the 'Library' directory is not shown by default in Finder but can be accessed via Terminal. (If you know how to use it.)
To change the default in Finder, you can go to View -> Show Options (command + j) and check "Show Library Folder"
Or you can read this. http://osxdaily.com/2011/07/04/show-library-directory-in-mac-os-x-lion/
However, I don't believe that traversing this directory is your actual problem.  Are you still experiencing this issue?

**Comment by ajt9589** [comment]
Thank you for helping! no one else will for whatever reason? I just felt
that maybe manually inserting the roms into the actual game library folder
would help or something but you're right, actually being able to access the
game library folder is not helping with anything. still can not open any
roms. same error message comes up when i click one...

**Comment by joshvickerson** [comment]
Sounds like you're missing a core? Try going to OpenEmu > Preferences > Cores and make sure the cores have been installed for the system you're trying to emulate.

**Comment by clobber** [comment]
Could be permissions or quarantine problem. You either need a restart, repair permissions, an upgrade of your OS, or you need to switch to using the alternative helper app to run the cores in. See #1580

Try them in that order.
