### ISSUE TITLE
Investigate switching to mGBA for Game Boy Advance emulation

### ISSUE THREAD

**Issue by mathiasbynens** [OpenEmu/OpenEmu#1768]
https://endrift.com/mgba/
https://endrift.com/mgba/about.html
https://github.com/mgba-emu/mgba

The author (@mgba-emu) did a lot of interesting research, such as <https://endrift.com/mgba/2014/12/28/classic-nes/>.

**Comment by mathiasbynens** [comment]
cc @mgba-emu

https://github.com/mgba-emu/mgba

**Comment by joshvickerson** [comment]
At first glance it looks great. I'd like to see the option of using it supported, but maybe wait a little longer for the emulator to be fleshed out before making it the default?

**Comment by clobber** [comment]
It's not ready yet. If you checked the author's readme you'd see an OE port is planned in the future https://github.com/mgba-emu/mgba#planned-features

**Comment by mathiasbynens** [comment]
https://endrift.com/mgba/bugs/show_bug.cgi?id=86
