### ISSUE TITLE
TrackPad touch to click not work properly when playing DS games

### ISSUE THREAD

**Issue by cdanyl** [OpenEmu/OpenEmu#1769]
In many DS games, the touch to click feature for a trackpad in my MacBook Pro don't behave correctly. I need to click to perform a DS touch screen !

**Comment by clobber** [comment]
Could you better describe this?

**Comment by cdanyl** [comment]
Using the TrackPad "Tap To Click" feature, many DS games don't react to the "Tap" when playing a game. Unlike, the "Click" (mean when i press the trackpad to simulate for example a right mouse click) it work perfectly.

**Comment by clobber** [comment]
#1266

Please search for duplicate or related issues before opening a new one.

**Comment by cdanyl** [comment]
Oh! sorry for that.
