### ISSUE TITLE
Crash When Opening Services Menu

### ISSUE THREAD

**Issue by joshvickerson** [OpenEmu/OpenEmu#1770]
While emulating, going to OpenEmu > Services crashes the program, at least on Yosemite.

Here's part of the crash report, if it helps:
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007fff54ba7ff0

VM Regions Near 0x7fff54ba7ff0:
    MALLOC_SMALL           00007fcf8b000000-00007fcf8d000000 [ 32.0M] rw-/rwx SM=PRV  
--> STACK GUARD            00007fff513a8000-00007fff54ba8000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0
    Stack                  00007fff54ba8000-00007fff553a8000 [ 8192K] rw-/rwx SM=COW  thread 0

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff8f4d764d lookUpImpOrForward + 24
1   libobjc.A.dylib               	0x00007fff8f4d7617 lookUpImpOrNil + 20
2   libobjc.A.dylib               	0x00007fff8f4d1ae3 class_respondsToSelector_inst + 35
3   libobjc.A.dylib               	0x00007fff8f4c9dcd -[NSObject respondsToSelector:] + 47
4   org.openemu.OpenEmu           	0x000000010a8d00f0 -[OEHUDWindowDelegateProxy forwardingTargetForSelector:] + 40
5   com.apple.CoreFoundation      	0x00007fff852f372c ___forwarding___ + 140
6   com.apple.CoreFoundation      	0x00007fff852f3618 _CF_forwarding_prep_0 + 120
7   com.apple.AppKit              	0x00007fff845d3242 -[NSWindow validRequestorForSendType:returnType:] + 145

**Comment by clobber** [comment]
Only happens while using the popout window on 10.9 for me. Same case for you? If so, sounds like #469 is back.

**Comment by joshvickerson** [comment]
Yes, it's only when using the popout menu.
