### ISSUE TITLE
NES Controller Config

### ISSUE THREAD

**Issue by Kyrie415** [OpenEmu/OpenEmu#1772]
I bought an NES controller (non-USB) and the adapter to go with it and the button I can use is the right D-Pad. What type of controllers will work for NES?

**Comment by AnalogSurfer** [comment]
The easiest solution is to use a Playstation DS3 or DS4 controller since they are commonly available/wireless/compatible, but they do also sell USB versions of most controllers - including the NES. Always check for OS X compatibility.

**Comment by clobber** [comment]
Any HID-compliant USB device ought to work (usually), but the ones devices we fully support and recommend are listed here: https://github.com/OpenEmu/OpenEmu/wiki#supported-controllers
