### ISSUE TITLE
Advance Wars Dual Strike -- 3D Rendering Issue

### ISSUE THREAD

**Issue by ztdent** [OpenEmu/OpenEmu#1774]
Hello,

Advance Wars Dual Strike needs 3D Rendering in order to function well. Is it possible to alter 3D Rendering through OpenEmu for this game? I've tried and looked everywhere, but I can't do it. 

Certain graphics (and very important ones!) in this game are not visible without adjusting the 3D Rendering in Desmume, which is not an available option in OpenEmu. Specifically, the game's cursor on the map is invisible, as are the arrow pathways that the units can take.

I do have the native emulator through Desmume, but there are two problems. 1) OpenEmu's emulator and sound are both fast and accurate in comparison with Desmume by itself, so I would rather play the rom in OpenEmu. 2) OpenEmu offers wireless controller support, whereas Desmume doesn't.

Is it possible for you to fix this?

**Comment by maxc22** [comment]
hi I'm trying to play advance wars dual strike on open emu on my mac, i downloaded the rom but it won't show up in open emu , can you help?

**Comment by clobber** [comment]
The OpenEmu core port of Desmume, which is available upstream in their source code, doesn't yet support this.
