### ISSUE TITLE
Could you add rotate capability?

### ISSUE THREAD

**Issue by Nathaniel-Wu** [OpenEmu/OpenEmu#1775]
You know, there're some games on GBA, NDS or other portable consoles,  you need to rotate the screen right or left to play it.
However, you can't rotate the screen of your MacBook or Mac, right? It's also very uncomfortable if you twist your neck (I don't know how to express it precisely, but I think you can get the idea).

**Comment by verysofttoiletpaper** [comment]
This is also useful for vertical shmups.
In the mean while, you can do it with the system, it just isn't very convenient: http://www.mactip.net/tip-how-to-rotate-screen-on-mac/

+1

**Comment by Nathaniel-Wu** [comment]
Any one having the same issue, be **CAREFUL** the method mentioned by @verysofttoiletpaper.

I actually tried that, with OS X 10.10.2, and it turns out that screen stayed black when rotate 90 or 270 degrees until restart my Mac, and it went even worse when I tried 180 degree out of curiosity, which is upside down, I cannot rotate the screen back! What the hell?! There was something wrong with Display Preference, it just wouldn't open any more. This must be some sort of glitch of OS X 10.10.

It took me several hours to figure out how to get it right: **ERASE** and reinstall OS X, you can use Time Machine backups that are built before everything went wrong. The whole reinstallation took me about 3 hours or so, I wish that there're any other methods.

**Comment by verysofttoiletpaper** [comment]
Never tried it on Yosemite, and now I don't think I will.
Please, https://bugreport.apple.com/

**Comment by Nathaniel-Wu** [comment]
@verysofttoiletpaper That requires a developer account, which I don't have.

**Comment by astrange** [comment]
You do have one. Sign into developer.apple.com with your Apple ID.

**Comment by rhysforyou** [comment]
This would be very helpful for playing WonderSwan games, since that system could be played in a vertical configuration.

**Comment by marvbloke** [comment]
Bear in mind that not only did the screen rotate, but the controls did too. So even if they supported screen rotation, your mappings to your controllers might be wrong when playing vertical games.

**Comment by clobber** [comment]
Screen rotation for NDS games is available as of OpenEmu 2.2 using the DeSmuME 0.9.11.3 core plugin.
