### ISSUE TITLE
Screen Tearing/Vsync Disabled?

### ISSUE THREAD

**Issue by flx1210** [OpenEmu/OpenEmu#1777]
Hi OpenEmu devs,

Firstly, would like to say thanks for this amazing software for the Mac - It's a great achievement :).

I have noticed that I am getting screen tearing every 1-2 seconds (regardless of which core i'm using). I have checked the correct region is set, and my display refresh rate is correct (60hz). 

I have launched other emulators natively outside of OpenEmu (e.g. Kega Fusion, Higan) and have noticed there is a complete vsync and no screen tearing occurs.

Is this something that could be investigated in the future - perhaps a global vsync switch could be made available in preferences? 

Many Thanks!

**Comment by clobber** [comment]
VSync is already enabled. Your issue is probably GPU related to GL_UNPACK_CLIENT_STORAGE_APPLE but you haven't given us any information about your machine.

**Comment by flx1210** [comment]
Mac Mini (Late 2012)
Processor: 2.5 GHz Intel Core i5
Memory: 4 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 4000 1024 MB
Storage: 500GB
OS: Yosemite 10.10.1 (14B25)
OpenEmu 1.0.4 (Experimental)

**Comment by cyco** [comment]
As clobber said vsync is enabled by default. We're planing to rework some of the OpenGL rendering magic. Hopefully this problem will be fixed along the way.

**Comment by clobber** [comment]
Yeah, and also check to see if the problem persists by using just the Pixellate or Nearest Neighbor filters. I'm not aware of any issues on the HD4000. Previous and newer Intel integrated GPUs are working fine.
