### ISSUE TITLE
unable to use more than one xbox controller

### ISSUE THREAD

**Issue by dnnyb** [OpenEmu/OpenEmu#1782]

**Comment by dnnyb** [comment]
I am able to successfully use a standard xbox 360 controller, Xbox One controller with USB, and a Razer brand xbox controller without issue. Each are recognized as options to set up in the settings menu, but plugging in any more beyond the first won't yield any functionality. It shows another microsoft controller has been plugged in, but still only takes input from the first. 

Which one that is plugged in first isn't important, and only has issues with whatever controller is plugged in after the first. 
Any ideas?

**Comment by jclauffer** [comment]
Hi, I ran into the same issue: I have 2 Xbox One controllers, plugged successfully via bluetooth. Each one works perfectly with Openemu, but when I plug both controllers at the same time, only the first one works (I can see both controllers in the configuration window but I can't configure the buttons). Any idea? Thank you!

**Comment by irishmapping** [comment]
Personally i say it’s because the xbox controllers don’t have great support for that. Chances are it’s microsoft’s issue. Ask them first.

**Comment by clobber** [comment]
This sounds like something that is fixed in OpenEmu 2.2.
