### ISSUE TITLE
MAME Roms utilising .chd files

### ISSUE THREAD

**Issue by mharmeston** [OpenEmu/OpenEmu#1783]
I've had huge success with nearly all MAME roms by using nealy every BIOS pack I could find. Ive come across roms requiring .chd files is that pushing too far? Drag and dropping files worked but only for one of the two required.
![screen shot 2015-01-14 at 9 29 01 pm](https://cloud.githubusercontent.com/assets/8800990/5752959/00b3b1f6-9c35-11e4-9890-4a1b10771cca.png)
![screen shot 2015-01-14 at 9 29 12 pm](https://cloud.githubusercontent.com/assets/8800990/5752961/00b52dba-9c35-11e4-81ab-856aab521635.png)
![screen shot 2015-01-14 at 9 29 23 pm](https://cloud.githubusercontent.com/assets/8800990/5752960/00b4ed00-9c35-11e4-8e4e-f8238a92638a.png)
![screen shot 2015-01-14 at 9 29 32 pm](https://cloud.githubusercontent.com/assets/8800990/5752962/00b5bc12-9c35-11e4-894a-7e465a196c61.png)

**Comment by clobber** [comment]
First of all, you need to be using files from a 0.149 romset. You may also want the NO CD version of this game to bypass the loading that is simulated on first run.
