### ISSUE TITLE
Nintendo ds roms not downloading.

### ISSUE THREAD

**Issue by Joaffle** [OpenEmu/OpenEmu#1784]
Both pokemon gold and soul silver are not being added to the library when I drag the files but my when i add new gameboy games they are perfectly fine.

**Comment by clobber** [comment]
Extract the files from their archives and simply drag and drop in the .NDS ROMs.

**Comment by Joaffle** [comment]
i did still doesn't work before the latest update i had kingdom 358 days.

**Comment by Joaffle** [comment]
also just to add i use mac
