### ISSUE TITLE
Ordering of HID devices is inconsistent between launches

### ISSUE THREAD

**Issue by egradman** [OpenEmu/OpenEmu#1787]
Attached is a screenshot of the Controllers preference between two subsequent launches of OpenEmu.  The ordering of the devices has changed, and the player has bound to the wrong controller!

![screenshot 2015-01-17 16 56 24](https://cloud.githubusercontent.com/assets/103129/5791002/5dfe242c-9e6a-11e4-9d3e-67c7136c1227.png)
![screenshot 2015-01-17 16 57 14](https://cloud.githubusercontent.com/assets/103129/5791004/634a7e4e-9e6a-11e4-997c-ad79a2c203e1.png)

**Comment by cyco** [comment]
I sorted the list by name just so it looks nicer.
I believe the actual bug of identical controllers switching players can't be fixed, especially since osculator hid devices do not have a unique serial number.

**Comment by egradman** [comment]
I dug through the code, and the display list is sorted by deviceIdentifier which is assigned incrementally based on the order in which HIDManager enumerates the device.  I changed the code to assign device identifiers by hashing the [[device description] name] which DID fix the display order.  But the assignment was still random.  It was worth a try!

Is it correct to say that the device to player binding is stored on the basis of device serial number, then?  If so, I'll go bug the OSCulator developer instead of you :)

**Comment by cyco** [comment]
I just checked the code again and noticed that we don't even keep track of which controller is assigned to which player. Maybe i can work on that later this week.

**Comment by egradman** [comment]
Oh man, that would be amazing.  Thank you.

**Comment by cyco** [comment]
I didn't forget you, just been very busy.

**Comment by egradman** [comment]
​Oh man, I very much appreciate it!​

On Tue, Feb 17, 2015 at 2:52 PM, Christoph Leimbrock <
notifications@github.com> wrote:

> I didn't forget you, just been very busy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenEmu/OpenEmu/issues/1787#issuecomment-74772628>.
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by cyco** [comment]
Hey there, i spent some time on this today and decided that we won't fix the problem in OpenEmu. The way our device handling is set up right now makes it hard to implement this nicely.
However, i implemented the necessary changes here https://gist.github.com/cyco/b72d381a089c24d53351 and suggest you fork openemu and merge those in.
Let me know if you need any help with that.

**Comment by egradman** [comment]
Alright, I’ll give it a shot.  Thanks for the diff!

On Sun, Mar 1, 2015 at 9:05 AM, Christoph Leimbrock <
notifications@github.com> wrote:

> Closed #1787 <https://github.com/OpenEmu/OpenEmu/issues/1787>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenEmu/OpenEmu/issues/1787#event-243988002>.
>



-- 
*Eric Gradman*
CTO & Mad Inventor
*P:* 213-268-6253 | *W:* twobitcircus.com <http://www.twobitcircus.com/>
*TW:* @egradman <http://www.twitter.com/egradman>

*TWO BIT CIRCUS*
Engineering Entertainment

Inventors | Developers | Performers

**Comment by magnifymobile** [comment]
I am having this problem too and I suppose the changes you referenced will fix it?  I would like to try it.  I compiled the latest from source in Mac OS through Terminal.  But I don't know how to apply the change you reference.  Can you tell me how to apply this?

https://gist.github.com/cyco/b72d381a089c24d53351

**Comment by magnifymobile** [comment]
I have two NES controllers, 2 SNES controllers and 2 N64 controllers.  So basically each pair of controllers are identical, for instance the two NES controllers have the same name, both SNES same name and both N64 same name.  As far as I am concerned I am not worried if the player 1 and player 2 order are not remembered on restart.  I just want the controller mappings to be remembered on restart, that way I don't have to go back in and remap the controls every time.
