### ISSUE TITLE
Logitech Rumblepad 2

### ISSUE THREAD

**Issue by Xaarai** [OpenEmu/OpenEmu#1788]
I have noticed that the Rumblepad 2 is in your list of supported controllers. However, Mine is not is the drop down input list and isn't being read. Can you please assist?

Thanks.

**Comment by cyco** [comment]
Does the controller work with other apps? It's hard to tell what could be wrong here.

**Comment by cyco** [comment]
Apparently there's some kind of switch on the back of the device. I also hear that our wiki https://github.com/OpenEmu/OpenEmu/wiki has a link to some further information https://web.archive.org/web/20130815061741/http://www.macgamepads.com/gamepads/f710/index.html
(original link is down). I think the important line is "Put the controller into DirectInput mode using switch on front of controller."

Hope that helps.
