### ISSUE TITLE
Crash When using a USB display adapter.

### ISSUE THREAD

**Issue by chellini** [OpenEmu/OpenEmu#1789]
Openemu crashes when attempting to launch the guy. This only occurs when my Sabrent USB-DH88 usb display adapter is attached. If i unplug it and reboot my system it will work again.
Crash report at the following link
https://gist.github.com/chellini/0fd1cf22777175e1b1d0#file-openemu-crash1

**Comment by chellini** [comment]
Also to note that if I plug in the usb adapter after openemu is running it will work.

**Comment by cyco** [comment]
Hey @chellini, i think the issue is fixed now. However i couldn't really test it. Can you see if this version works for you: https://www.dropbox.com/s/8odk1nbvn4qf5sa/OpenEmu%20%28%231789%29.7z
