### ISSUE TITLE
Snow Leopard

### ISSUE THREAD

**Issue by asoksevil** [OpenEmu/OpenEmu#1791]
Hey guys,

Thanks for the emulators, they are great! I'm just wondering why the team decided to drop the support for Snow Leopard when it was compatible on the beta version but not on the stable one...

Is there any "work around" to make it Snow Leopard compatible?

Thanks!

**Comment by clobber** [comment]
Wasn't compatible on any beta versions that were pre-1.0 with the new UI. No work around, we use newer API's and features that aren't available on 10.6 so it isn't possible to support it. We'll likely drop 10.7 soon as well. It's really time to move on so I'd suggest upgrading to the latest your machine can support.

**Comment by asoksevil** [comment]
Thanks for the fast reply!

Would it be possible to play using a pre-1.0 version?

**Comment by clobber** [comment]
No. If I were you I'd upgrade as far as you can. 10.6 doesn't even receive security updates anymore.
