### ISSUE TITLE
3DO Core 

### ISSUE THREAD

**Issue by stardm** [OpenEmu/OpenEmu#1793]
First posting here and not finding my answer so forgive if it is already posted. But I cannot seem to find the core for 3DO, I am told that if the core is not on the OpenEmu it will ask automatically if I want to download the core, but it does not.  
I am not versed in coding so unsure as to how I can go about getting this core, it is the only real reason I want the OpenEmu at all really. Any help would be greatly appreciated.

**Comment by cyco** [comment]
Try downloading the experimental package to get access to additional cores https://github.com/OpenEmu/OpenEmu/releases/download/v1.0.4/OpenEmu_1.0.4-experimental.zip.

**Comment by clobber** [comment]
Also, one would have to build from source since I don't include it in the 'experimental' appcast yet. It's not really ready yet.

**Comment by stardm** [comment]
Thanks for getting back to me,
I have in fact downloaded the experimental package, it shows 3DO but 
says no core available, same for PSX.
Is there no method for me to add the core subsequent to download?
3DO is really why I wanted the emu.

Thanks

**Comment by cyco** [comment]
hey @stardm, you can download the core from this link http://cl.ly/050U442O2l10, unzip it and put the file in ~/Library/Application Support/OpenEmu/Cores/

Keep in mind that 3do is still experimental.

**Comment by stardm** [comment]
Cool,
Is that in the OpenEmu that i add it to? (Library/App etc)?
Seems it is greyed out

**Comment by cyco** [comment]
No, you have to use the finder to navigate to the directory and then place the file in there. Your user library is hidden by default http://support.apple.com/kb/PH18928?viewlocale=en_US

**Comment by stardm** [comment]
disregard that last email, i didn't have my glasses on nor my brain in 
my skull!
Thanks again

**Comment by stardm** [comment]
This is what I am getting now, is this a result of it being experimental 
or am I just missing a file?
FYI I used to work for Apple and have lots of 'swag' around the house 
(giant acrylic apple from my store, iPad posters etc) if you're interested.
Thanks again

**Comment by stardm** [comment]
Forgot the screenshot

**Comment by cyco** [comment]
still no screenshot :P

**Comment by stardm** [comment]
Still didn't come through?

**Comment by cyco** [comment]
Nah, i don't see anything. Try posting it directly on https://github.com/OpenEmu/OpenEmu/issues/1793

**Comment by stardm** [comment]
The on screen message reads

To run this core you need the following:
Panasonic REAL 3DO Interactive Multiplayer FZ-10
v1.59.1.1
   "panafz10.bin"
Drag and drop the required file(s) onto the game library window and try 
again.

**Comment by cyco** [comment]
Oh yeah, looks like you'll need a bios file. Take a look at this guide https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

**Comment by stardm** [comment]
Yuck
This is where i would pull my hair out.......if I had any. Okay, I will try not to kill my mac, I saw this page earlier today and was hoping there would be a way around it.
Thanks for your help, hopefully I will be gaming soon.

**Comment by stardm** [comment]
I think I may be confused, so do I need to go into Terminal ? It says just drop the BIOS file but I don't see an actual file there, just code.

**Comment by cyco** [comment]
The guide only tells you which file you need and how you can verify that you got the correct one. Contents of the file are probably protected by some copyright laws, so i won't help you acquire it.

**Comment by stardm** [comment]
Understood
Thanks

**Comment by stardm** [comment]
Final question then, where would the file be inserted?
Directly into the Openemu 3DO?

**Comment by cyco** [comment]
Yep just import it like you would import a game.

**Comment by stardm** [comment]
Any idea why I get notifications of email from Nude Dating site when i 
get emails from this site? My girlfriend is getting nosey as hayl!

**Comment by stardm** [comment]
Not seeing a core listed, how would I go about inserting that, as I am 
assuming the BIOS will not work when the core itself is missing?

**Comment by Di9** [comment]
Thx guys for files, everything is working! Somebody know why this method doesn't work on new v2 openemu?
