### ISSUE TITLE
Multi screen Mame game support.

### ISSUE THREAD

**Issue by Locke141** [OpenEmu/OpenEmu#1795]
Yosemite 10.10.1 

For games that used more then one screen, like 6 player x-men, there is no screen number options so you only get one screen for these games. You can set a screen number in mame to allow for these games.

Could this be added to the a pull down menu?

**Comment by rodaguilera** [comment]
I had the same issue with Darius game. It would be really nice to add the option to enable multi screens or to resize them to a single monitor.

**Comment by clobber** [comment]
Please search for duplicate issues before opening new ones. Multi-screen games are not yet supported in our MAME implementation.
