### ISSUE TITLE
Add a keybinding for Stop Emulation

### ISSUE THREAD

**Issue by djfjeff** [OpenEmu/OpenEmu#1796]
Hi,

I would like to have a keybinding for the Stop Emulation action (like we have one for Quick Save and Quick Load).

The reason is that I use my Harmony remote to control OpenEmu (to simulate keyboard key). I can browse, launch rom, save, load saved game and quit OpenEmu. The only thing that is missing is to stop a rom to launch another one.

Thank you!

**Comment by cyco** [comment]
Fixed in 7ef1b9cac30dc075d992db8a8cab3cbc6eb523a9.
