### ISSUE TITLE
Playstation crashes with 3 or 4 controllers 

### ISSUE THREAD

**Issue by vanguardista** [OpenEmu/OpenEmu#1798]
The emulator works fine for 1 or 2 players, but when I try to play with 3 or 4 controllers, the screen freezes, I get the error "Couldn’t communicate with a helper application" and I have to close OpenEmu. I tested with different multiplayer games, but had no luck. The same thing happens over and over again.

(I want to clarify that I can play N64 or SNES without problems with 3 or 4 controllers).

Anybody experiences the same problem? Is there any way to solve it? 

Thanks a lot.

**Comment by cyco** [comment]
Hey, 
i can see that the code won't allow for 3 or more controllers. I'll see what we can do about it.

For reference this is the problem: https://github.com/OpenEmu/Mednafen-Core/blob/master/MednafenGameCore.mm#L58

**Comment by clobber** [comment]
PSX Multitap now Just Works as of https://github.com/OpenEmu/Mednafen-Core/commit/8a5229f70d7f6d7a631c8cfcd3aa1231a0a1b079

Will be available in OpenEmu's next release.

**Comment by dvestaloyne** [comment]
I'm having a similar problem, but with one controller. Any time I use the analog sticks (intentionally or otherwise) I get the "Couldn’t communicate with a helper application" and often 2-4 times. I've tried to turn off the analog, but that doesn't seem to work. Any help would be greatly appreciated.

**Comment by dvestaloyne** [comment]
Update: Analog works fine on N64 and I avoided setting up the sticks in controllers, allowing excellent gameplay for anything which does not require them, (most ps1 games.) It would be nice if they worked, but I view it as a pretty minor issue. Thank you OE team for your continued dedication. You guys are awesome.
