### ISSUE TITLE
[REQUEST] Change default save file location

### ISSUE THREAD

**Issue by kurisubrooks** [OpenEmu/OpenEmu#1799]
I'd really like to change where my save files save to, example: Dropbox, so I can play the same games and save files on my iMac, aswell as my Laptop.

**Comment by loicloic** [comment]
Not sure it will be added to the UI however you can achieve this with a symbolic link.

Move your Save States folder to your DropBox, then in the Terminal:

ln -s ~/DropBox/Save\ States ~/Library/Application\ Support/OpenEmu/

Hope this help

**Comment by kurisubrooks** [comment]
Done that now, thanks so much :)I really hope it does get added though, it would be very useful for a lot more people than just me. 


—
Kurisu Brookshttp://kurisubrooks.com/

**Comment by cyco** [comment]
I don't no where to put the button for this. For now i prefer not to add more clutter to the preferences.
