### ISSUE TITLE
Emulators are looking weird

### ISSUE THREAD

**Issue by EasyBoy90** [OpenEmu/OpenEmu#1801]
Hi. I noticed this a while ago but only now it has been going onto my nerves, So basically the emulators are looking different to what they are meant to be. For example

This is what I see on the screen

![screen shot 2015-01-28 at 19 29 26](https://cloud.githubusercontent.com/assets/10746677/5945295/5128de68-a725-11e4-981b-d0b214cdd84f.png)

This is what I should be seeing:

![image](https://cloud.githubusercontent.com/assets/10746677/5945332/85816d88-a725-11e4-905e-3e7ffe2a3e1c.png)

Can anyone help?

Im noob at this by the way so i might not understand what your saying

**Comment by astrange** [comment]
Those are called filters. You can change to a different one!

**Comment by EasyBoy90** [comment]
could you tell me the best one please?
