### ISSUE TITLE
Connectivity game boy advance

### ISSUE THREAD

**Issue by oscarsalvador24** [OpenEmu/OpenEmu#1802]
Hi everyone! I recently stared using OpenEmu with a friend, and we would want to connect both games to exchange info (as, for example, trade pokemon). We cannot do it till now. Someone could help us? Thank you

**Comment by clobber** [comment]
This is unsupported. You could instead use cheats which work fine https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Cheat-codes
