### ISSUE TITLE
Final Fantasy VIII PAL doesn't start

### ISSUE THREAD

**Issue by alec4** [OpenEmu/OpenEmu#1805]
I have a problem with Final Fantasy VIII PAL Version [SLES-02082], when i start the game i can see the Play Station startscreen and then is the screen black.
Other PAL Games work without Problems, so I think its not a wrong BIOS file or something.

By the way a question, can i load the savegames from disc 1 when I start disc 2, or have i to copy somefiles in the OpenEmu directory to load the savegames?

**Comment by clobber** [comment]
PAL version of this game was, I believe, broken in older versions of Mednafen and the one we currently have pushed out via the experimental app (0.9.34.1). You will have to wait until we push out the newer version sometime in the near future.

**Comment by giofrancescu** [comment]
Please do something, we are are start waiting long time ago this new version
