### ISSUE TITLE
MAME unable to fast forward

### ISSUE THREAD

**Issue by digamejh** [OpenEmu/OpenEmu#1806]
It seems like no matter which arcade game I run on MAME, or which key I map it to, the Fast Forward feature is unresponsive.
On OS X "Yosemite" 10.10.1, mid-2014 MacBook Pro

**Comment by clobber** [comment]
MAME will need further work to support this feature, due to threading.

I'll make note of this but closing this ticket because I want to keep the number of open tickets down and also MAME has its own repo/issues page, so this doesn't really belong here.
