### ISSUE TITLE
Request: xBRZ filter

### ISSUE THREAD

**Issue by cwscws** [OpenEmu/OpenEmu#1808]
Would be nice to have the latest xBRZ filter available and all other picture enhancement technologies e. g. ppsspp uses to get an even better picture.

**Comment by clobber** [comment]
Add your own shader: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Filters

**Comment by cwscws** [comment]
Is xbr the same as xbrz? The picture quality for psp games in ppsspp is much better than in OpenEmu. Or does this have something to do with the additional features like fxaa or render resolution?

**Comment by astrange** [comment]
Probably 3D rendering resolution.

**Comment by cwscws** [comment]
OK, thanx. Maybe the developers could check this because I prefer OpenEmu over ppsspp. But because of the picture quality I'm using ppsspp at the moment.

**Comment by bjoernhohe** [comment]
I compared the OpenEmu and PPSSPP - and PPSSPP looks much better. Is there a way to adjust rendering settings?

**Comment by mrvacbob** [comment]
Can you attach some screenshots? Rather than change settings we'd prefer to always be right.

**Comment by cwmoriarty** [comment]
Get the files here: https://github.com/libretro/common-shaders/tree/master/xbrz
