### ISSUE TITLE
SNES In-game saves disappearing

### ISSUE THREAD

**Issue by jglag** [OpenEmu/OpenEmu#1809]
Hi there,
Recently, on two separate occasions, my in-game saves on two different SNES games were deleted. Not save states, but actual saves within the original game. They were both very late game saves of Chrono Tigger and Final Fantasy VI, which took many many hours to achieve, and I'm pretty upset about this.  I never used save states or whatever the built-in save function is in OpenEmu, so there should have been no issue there.

Can someone please help? What could cause this? Is there any way to recover these saved game? A lot of hours went into the gameplay.

I should add that I own both games legally and my original SNES console simply no longer works.

Please, any help would be greatly appreciated. Thanks!

-Jglag

**Comment by Phosphor303** [comment]
If you use Time Machine you can look up the old uncorrupted save states in recent backups of ~/Library/Application Support/OpenEmu/SNES9x/Battery Saves

If you used the Higan core for gameplay, go to: ~/Library/Application Support/OpenEmu/Higan/Super Famicom

**Comment by clobber** [comment]
Isn't possible for battery saves to just vanish, so I'd wager you are using save states in some way. Restoring autosaves each time you load the game perhaps?

**Comment by jglag** [comment]
I wasn't using save states in any way. I was unable to recover the saves...I had to find them online and download them. Since then I've been making a copy of the .sav file every time I close the OpenEmu, just in case. A few minutes ago I clicked "restart console" and when I got to the load screen, it took me back to the previous save, not the most recent one that I had just saved in. Perhaps the "restart console" reverts to the saves when it was last turned on? Bizarre to say the least.

Luckily FF6 is a marvelous game (this is my first play through) and so repeating some of the adventure is still rewarding. However, losing a large amount of progress is extremely frustrating. 

Please anyone, feel free to add things you've noticed op this topic or ways you've gotten around the saving issues. Thanks!

-Jglag

**Comment by astrange** [comment]
Do you have a Time Machine backup?

**Comment by clobber** [comment]
@jglag Did you, by chance, change which SNES emulator core you were using. For example, if you were playing games in SNES9x but then played another game and switched to Higan, then all other games you launched would be running in Higan. Battery saves are not shared between the two emulator cores, so that means your saves would appear gone until you switched back to the emulator core you had originally made them in.

If one is avoiding use of save states and not using autosave restore, then this is a likely problem.

**Comment by clobber** [comment]
Closing since no update on this.
