### ISSUE TITLE
new Xbox One controller driver just needs mappings

### ISSUE THREAD

**Issue by lloeki** [OpenEmu/OpenEmu#1810]
Hi folks!

I just released a native [Xbox One gamepad driver](https://github.com/lloeki/xbox_one_controller) for OS X. Everything already works in OpenEmu, and all it takes to make it an "out of the box" experience in OpenEmu is button mappings!

**Comment by lloeki** [comment]
For reference, here are the button mappings:

Button 1: "Pair" (wireless)
Button 3: "Menu" (start)
Button 4: "Window" (select)
Button 5: A
Button 6: B
Button 7: X
Button 8: Y
Button 9: d-pad up
Button 10: d-pad down
Button 11: d-pad left
Button 12: d-pad right
Button 13: LB (shoulder left)
Button 14: RB (shoulder right)
Button 15: left stick click
Button 16: right stick click
Button 17: Xbox button

Axes are mapped the same as DualShock 4:

Axis 1: LS left-right
Axis 2: LS up-down
Axis 3: RS left-right
Axis 6: RS up-down
Axis 4: left trigger
Axis 5: right trigger

**Comment by lloeki** [comment]
I don't know how you make a match but here goes:

Vendor ID and Product ID are 0x02d1:0x045e. Vendor name and Product name are "Microsoft" and "Xbox One Controller".

**Comment by clobber** [comment]
Thanks. Someone had offered to add built-in support for the Xbox One controller therefore not needing a driver/kext, but that never materialized (https://github.com/JRHeaton/XboxOneControllerDev/issues/1). If somebody wants to add support for that I'd appreciate it as I'd much rather have the built-in support.

**Comment by lloeki** [comment]
Doesn't X360 require TattieBogle's driver?

**Comment by clobber** [comment]
Yes, but we're talking about XBOne here and not X360. As seen with TattieBogle, projects get abandoned and users have to deal with kernel panics, lack of future support for newer OSX, kext hacks and driver signing. I'd much prefer support of the controller baked into our application.

**Comment by lloeki** [comment]
I understand your approach, as I received similar responses from other software vendors and game developers.

I'm contemplating having the driver built with a default set of button mappings to achieve a sensible level of out of the box compatibility across applications and games. What is OpenEmu expecting from an unknown controller (such as d-pad as hat)? Would you be kind enough to express me such a "unknown controller default mapping" in terms of button number to physical locations (using terminology from a well known controller such as PS3/PS4 or Xbox 360/One) ?
