### ISSUE TITLE
keyboard imput

### ISSUE THREAD

**Issue by sliverado** [OpenEmu/OpenEmu#1811]
The Keyboard is not responding to any of the programs. I have tried all the things on here and none of it has worked, restarting my mac,deleting  and reinstalling everything, even deleting the ~/Library/Application Support/OpenEmu/Bindings Configurations file. Nothing has worked

**Comment by clobber** [comment]
Your issue is with another open application conflicting with OpenEmu. Sometimes it's Chrome or things like iTerm2. You'll have to narrow it down. Start by closing running apps.

Also please search the issues first next time. This particular problem has come up several times.

**Comment by sliverado** [comment]
this is not the solution  issue, I have ended every program/app on my computer and this issue still persists. this is happing with not just openemu, but other emulators. I have looked this up and tried to kix it every way you have told us but the issue is still occurring

**Comment by clobber** [comment]
>happing with not just openemu, but other emulators

Sorry, but this is clearly not our problem and definitely an issue on your end.
