### ISSUE TITLE
Pilotwings / Mario Kart wont play

### ISSUE THREAD

**Issue by Leadingman** [OpenEmu/OpenEmu#1812]
I am loving the program but am baffled as to why Pilotwings and Mario Kart refuse to play on the SNES. Any advice will be greatly appreciated.

Mario Kart won't play beyond the Nintendo logo.

Pilotwings lets me start but as soon as I choose a mission, the screen goes black.

**Comment by clobber** [comment]
You're using BSNES/Higan which require special chip dumps: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files#snes-chip-dumps-for-higan

Find then or instead use SNES9x for those games.
