### ISSUE TITLE
My PS3 controller is not working on OpenEmu! HELP!

### ISSUE THREAD

**Issue by jeng0312** [OpenEmu/OpenEmu#1813]
Im using MacBook Pro 13" and I've connected my PS3 controller via bluethooth on my Mac. 
But when I go to OpenEmu 'input' , I can't find the PS3 controller. 
So I connect my controller with the USB cable. And it appear "Sony PS3 Sixaxis Wireless" in OpenEmu.
But the controller is still not functioning. When I plug-off the cable, I can't find my PS3 controller on OpenEmu again. What should I do? :( (Sorry that my english is bad.lol.)

**Comment by clobber** [comment]
If using the USB cable, you must first press the 'PS Home' button before buttons will work.

There are a few bluetooth pairing guides here: https://gist.github.com/3172711 and http://bit.ly/W26q2k
