### ISSUE TITLE
Track release date of games for sorting purposes

### ISSUE THREAD

**Issue by deltakurshiva** [OpenEmu/OpenEmu#1814]
Feature request: It would be neat if OpenEmu's internal database would include game's release dates (OpenVGDB already has this data). Browsing games in order they came out seems very helpful. UI-wise, this would be simple to implement in list view - having a method to select game order in the other views would be great as well, but that's a different and larger issue.

**Comment by clobber** [comment]
Please search for duplicates before opening a new issue.

#664
