### ISSUE TITLE
Accidentally moved game to trash

### ISSUE THREAD

**Issue by BryanMagnaye** [OpenEmu/OpenEmu#1815]
I accidentally moved a game to trash, is there anyway I can recover the save states so I don't have to restart the whole game?

**Comment by ZeldaRooster** [comment]
Yes, your computer should have made a folder somewhere called OpenEmu Library. This folder should contain all your roms. Redownload OpenEmu from the site and you should be good to go! 

Kind Regards, ZRoosty

**Comment by clobber** [comment]
@BryanMagnaye 

1) Add the game back to your library.
2) Navigate to ~/Library/Application Support/OpenEmu/Save States and find the .oesavestate file for your game.
3) Double click the file. It will open the game and load the save while also adding it back to the database.
