### ISSUE TITLE
Flickering screen

### ISSUE THREAD

**Issue by ZeldaRooster** [OpenEmu/OpenEmu#1816]
Hi!

I've been having this problem since the last update to 1.0.4 in the expiremental version (The one with the extra consoles ^_^) Everytime I try to open a game OpenEmu asks me if I want to start where I last left of (Normal so far) I click yes, the music starts playing of the game.... and that is it. All I get is a flickering screen of my open emu liberary, I can't play, al I can do is look at my wonderfull flickering open emu library . When I click on "No, I don't want to continue where I left of" the music of the game doesn't even start playing, and I still have the wondefull flickering open emu library :( I'm running mid 2012 macbook with Yosemite with 4 gigs of ram. Help :)

ZRoosty, From The Netherlands

**Comment by clobber** [comment]
Switch to pixellate or nearest neighbor filters.

**Comment by ZeldaRooster** [comment]
Thanks :) that solved it ^_^
