### ISSUE TITLE
Games not working at all

### ISSUE THREAD

**Issue by SupahBawz1009** [OpenEmu/OpenEmu#1817]
I started Pokemon White 2 today, and some glitch happened to my game as the game was loading.
The game crashed, to instinctively, I reset the system. Now, all my screens are black, no sound is playing, and nothing I do helps.
I tried the 
defaults write org.openemu.OpenEmu OEGameCoreManagerModePreference OEDOGameCoreManager

command in terminal, and that does nothing. I re-downloaded the ROM and OpenEmu, and that doesn't work also. And to top it all off, I have to  force quit the application to stop it.
Can anyone help?

**Comment by cyco** [comment]
Which version of os x are you using?

Downloading a fresh copy of OpenEmu can't help with any problems if you're already using the latest version. You'd have to remove all preferences and other files first to make sure they don't interfere. To do that type 
```defaults delete org.openemu.OpenEmu```
into Terminal.app and delete the directory at ~/Library/Application Support/OpenEmu. Keep in mind that all your roms, artwork and save files are stored in that location by default. So you might want to keep a backup of the folder.

**Comment by SupahBawz1009** [comment]
I'm using Mac OS X Yosemite, AKA OS 10.10, so there's that.
Also, I tried deleting everything but the save files and roms, but it STILL doesn't work.
It just goes black, the menu doesn't do anything, and before I force quit it, it says "could not communicate to helper program" or something of the sorts.

**Comment by clobber** [comment]
@SupahBawz1009 Desmume has a problem with these Pokemon games at certain points in the game and they will crash (noted several times if one searches the issues here). Nothing we can do about it, so we cannot help you with this.
