### ISSUE TITLE
GUI not updating after importing large number of games and changing libraries

### ISSUE THREAD

**Issue by Xeon3D** [OpenEmu/OpenEmu#1818]
When adding a significant number of games and while it is requesting \ downloading cover images for them, if you switch to another system and try let's say renaming a game by right clicking it the following happens:

* The renaming options stays selected and the menu doesn't disappear (nor does it allow it to rename anything)
* You can switch systems on the list to your right, and it'll show you the games for the selected system as normal, but the system won't be highlighted as if it was normally selected.
![image 2015-02-10 at 7 38 16 pm](https://cloud.githubusercontent.com/assets/596627/6134902/760b7c22-b15c-11e4-88cb-7b65b6bc7865.png)

Here you can see that Wonderswan is the "selected" system (I added complete romset to it and it was grabbing cover art), then I went to another system and right clicked a game to rename it, then I selected the N64 system (but the wonderswan is still selected.)

**Comment by lavadrop** [comment]
The issue is more general, the GUI simply fails to update to any actions when right clicking and selecting anything.

**Comment by clobber** [comment]
Video here of related problem https://github.com/OpenEmu/OpenEmu/issues/1675#issuecomment-60876482

**Comment by cyco** [comment]
@Xeon3D, @lavadrop can one of you check if that change solved the problem? I can't reproduce it consistently.

**Comment by lavadrop** [comment]
It's working so far, UI is responsive again.
Cheers!
