### ISSUE TITLE
AppleScript & OpenEmu

### ISSUE THREAD

**Issue by Xeon3D** [OpenEmu/OpenEmu#1819]
I'd love that OpenEmu gets support to be AppleScripted.

Not only does it make it more "connectable" (I know it's not the proper term, but my English is failing me at this late hours, so sorry, I hope you get my point), but it'd allow for cool nice things like a IRC script showing your collection, or most played game, or similar.

**Comment by cyco** [comment]
I don't think we'll get to this any time soon, sorry.

**Comment by clobber** [comment]
Yeah, kind of outside the scope and not worth the effort.
