### ISSUE TITLE
Add a Select All checkbox to the Game Scanner Issues Window

### ISSUE THREAD

**Issue by Xeon3D** [OpenEmu/OpenEmu#1820]
When adding loads of games (with a not so nice extension let me add) the game scanner issues window pops up letting us add the selected games to a specific library, but.. when there is a gazillion games being loaded we have to pick one by one to select them all before adding them to the wanted library.

A select all checkbox would do wonders there.

**Comment by cyco** [comment]
You can right / control-click on any item to select / deselect all.
