### ISSUE TITLE
SNES section only shows import games/limited amount of games

### ISSUE THREAD

**Issue by superblaq** [OpenEmu/OpenEmu#1821]
The SNES section only shows a few games and all of them are Japanese. I've tried adding to library a few times, deleting and reinstalling OpenEmu but nothing works. Any advice?

**Comment by clobber** [comment]
What does "shows a few games" mean? Imports a few games or are you talking about cover art?

If import:
You need to unzip whatever you're trying to import first. It's likely you have multiple files per zip or other junk data in them. Just import .sfc or .smc files for SNES.

If cover art:
Your games need to not contain the 512 byte copier header that some .smc have. Try .sfc roms instead.

**Comment by superblaq** [comment]
Hey’ 

What I meant by show a few games is that when I import/add to library, all the games are not imported. It worked fine before and every other system still imports the entire game folder of which ever folder I import/add to library (Genesis, Turbo16, Sega Master).

Super Nintendo only imports a few games and they’re all Japanese titles only. It never did this before and I’ve been using the same version. The only thing I can think of that’s different for me here is that I reinstalled Yosemite. That’s it. 


Either way I appreciate your time and I wish I was skilled at the inner workings of computers to be of some sort of help but I’m not and I’m sorry. I hope this program is still being worked on and continues to grow. 


Sincerely’
