### ISSUE TITLE
Small lag every ~5s

### ISSUE THREAD

**Issue by xaviershay** [OpenEmu/OpenEmu#1822]
I'm running OpenEmu 1.0.4 554-gf588330-Release on OSX Yosemite, running on a mid-2010 MBP. In any game I play (tested: megaman x, yoshi's island, chronotrigger) I get a short lag every 5s, which results in an audio glitch and a visual stutter. Games are still relatively playable, it's just really annoying.

I've watched activity monitor, and I'm not swapping nor are my CPUs at capacity. I have closed all other processes, and tried rebooting my computer.

Are there any further diagnostics I can run? I'm able to successfully compile and run different builds in XCode, and am able to add extra logging if you point me in the right direction.

_Sorry for the terrible bug report, I'm not sure what else to include..._

**Comment by clobber** [comment]
I need to know your GPU as this could be related to a GL_UNPACK_CLIENT_STORAGE_APPLE problem. If not, it'll be sync-related or part of out-of-process latency we're tracking in #953

**Comment by clobber** [comment]
Oh, and are you using any filters/shaders your machine cannot handle besides the default Pixellate or Nearest Neighbor?

**Comment by xaviershay** [comment]
GPU is `NVIDIA GeForce 320M 256 MB`

I'm using standard pixellate shader.

**Comment by xaviershay** [comment]
Don't know how relevant this is, but:

![screen shot 2015-02-13 at 5 43 21 pm](https://cloud.githubusercontent.com/assets/1714/6198216/8da97e28-b3ab-11e4-84ee-1e895fb6457a.png)

Also turns out since I upgraded to Yosemite I can't compile anymore (ARC related errors, looks like).

**Comment by astrange** [comment]
You might have an older Xcode installed, or one of those pesky submodules is out of date. ('git reset --hard && git submodule update --init --recursive' would do it).

Would you mind watching the CPU % again, but just see if WindowServer is hitting 100% cpu?

**Comment by xaviershay** [comment]
WindowServer sits at around 10%.
