### ISSUE TITLE
BlueBooth, Any Suggestions?

### ISSUE THREAD

**Issue by Bonifacio4** [OpenEmu/OpenEmu#1823]
Is there any way to use bluetooth from one emulator to another

For Pokémon, I want to transfer from my iPod (GBA4iOS) to Mac (OpenEmu)
Is that possible?

**Comment by cyco** [comment]
Pkm can't be transferred over bluetooth, try a link cable.

Seriously though, we'd have to implement link cable support first before even thinking about connecting different emulators.
