### ISSUE TITLE
CRT Lottes has some sort of incompatibility in 1080p. 

### ISSUE THREAD

**Issue by ghost** [OpenEmu/OpenEmu#1824]
Hi everyone.
I am having an issue and would like to ask if someone could help me to understand what's happening.
I'm going straight to the point, the shader crt-lottes has some sort of incompatibility in 1080p except when it's running PSP games. Using Street Fighter Alpha 3 as an example, on the PSP the shader works beautifully while in CPS2 the screen is filled with vertical lines. When using the "Best for Retina" resolution the shader works great, the issue is only for 1080p and other "lower" resolutions. 

Below it's a link to a dropbox folder with 6 images, the first 2 shows the shader running PSP SFA3 in 1080p, the next 2 images shows CPS2 SFA3 in 1080p and the last 2 images CPS SFA3 in "Best for Retina" resolution. Inside there's also the .cg filter that i am using.
I tried to edit the shader and the only option to remove the lines was removing the shadow mask which is pointless since the emulation of SM is the objetive of the shader.

https://www.dropbox.com/sh/cl2wuc0tj5h5ax7/AADhpmFKNW1ubRdqt3hN7raLa?dl=0

I'm using a rMBP mid 2012 and OSX Yosemite.
Oh and... is CRT-Royale compatible with OpenEmu ? I tried to make it work without success.
: )

**Comment by astrange** [comment]
It probably depends on the input size of the image, or the input size:output size being a certain ratio. 

https://github.com/OpenEmu/OpenEmu/issues/1576

**Comment by astrange** [comment]
Test for compatibility and then close.
