### ISSUE TITLE
Keybindings not working

### ISSUE THREAD

**Issue by Nutzchannel** [OpenEmu/OpenEmu#1826]
I'm using the emulator, and I'm unable to change the keybindings and when the respective keys are pressed, nothing is inputted.
I just downloaded, am I doing something wrong?

**Comment by clobber** [comment]
Your issue is with another open application conflicting with OpenEmu. Sometimes it's Chrome or things like iTerm2. You'll have to narrow it down. Start by closing running apps and try a restart.

Hope that helps.

**Comment by Nutzchannel** [comment]
I tried both, they dont work. I deleted the keybinding file, still wont even let me change the keys.

**Comment by clobber** [comment]
Something you have running is interfering, assuming you're just using a built-in keyboard and not one connected to a USB hub. Like I said, it could be a browser running, third party input app, etc. Start closing apps and find which one.

**Comment by Nutzchannel** [comment]
Ah, it was just my antivirus haha
