### ISSUE TITLE
there is not the OpenEmu folder in "Application Support"

### ISSUE THREAD

**Issue by seight33** [OpenEmu/OpenEmu#1827]
sorry to bother you but i've been trying for an hour to find it and i couldn't

i have to reach the saved games since i need to rename the saved game of disc1 in order to make disc2 work but as the title says there is no OpenEmu folder in "Application Support"
i'm not so sure this is foult of the app but i don't know what to do
(i can load the saved games so they must be somewhere)

thx in advance, bye ^^

**Comment by seight33** [comment]
found it! found it! found it! you can close, thx ^^

**Comment by nakk0** [comment]
can you tell me how you found it pleas? i'm having the same problem and would like to solve it
