### ISSUE TITLE
Dragon Quest VI blacks out

### ISSUE THREAD

**Issue by olundegun** [OpenEmu/OpenEmu#1829]
In DQ VI, at the Moonmirror tower, after I push the last purple sphere there a short animation, then game blacks out. There's no sound or anything, and if I try to load the game, save it, restart it, or quit, openemu quits and says "couldn’t communicate with a helper application."

I'm using a Mac OS X 10. 9 5 and the DeSuME core 0.9.10.2

**Comment by clobber** [comment]
DeSuME bug, probably JIT related. We can't help you with this.

**Comment by clobber** [comment]
Update: This problem has been fixed and will be available in the next DeSmuME release http://sourceforge.net/p/desmume/bugs/1450/
