### ISSUE TITLE
Option to change core's without opening game

### ISSUE THREAD

**Issue by OstoVargas** [OpenEmu/OpenEmu#1830]
Changing cores while an emulator is running is a bit of a problem. I accidentally made Higan my core for the NES and it would crash every time. There was no way to change the core because I had to run a game first to access changing the core. But a game wouldn't run because the Higan core seems to not work right on my iMac. I think it would be helpful to add a drop down menu to the emulator icons to which a change of core option is available if something goes terribly wrong, instead of tracking down the core plugin and deleting it.

**Comment by clobber** [comment]
We talked about this before but may or may not do it...not sure yet. Higan's beta modules are going away in the next release, so it won't be exposed anymore for GB/GBA/NES thus pretty much doing away with the need for this feature.

To solve your current problem though, run the following command in Terminal.app:
`defaults write org.openemu.OpenEmu defaultCore.openemu.system.nes org.openemu.Nestopia`

Closing for now.

**Comment by cyco** [comment]
@clobber i was thinking we could add this to the sidebar context menu. When you richt-click on a system you'd get an extra option where you can pick the core..

**Comment by OstoVargas** [comment]
Yeah I guess avoiding the whole issue helps, but besides, it would be a really nice feature. But I couldn't agree more, at least make a set default core feature like @cyco mentions. It won't nudge less technical people into the terminal environment. UI should be there to make things "clicky" and easy. It's shouldn't merit immediate attention but this would be a thumbs up improvement.

**Comment by clobber** [comment]
@OstoVargas the feature was already added. Check cyco's commit referenced in this issue.

**Comment by OstoVargas** [comment]
@clobber Ah! Okay, I apologize, this is my first time on GitHub. Thanks guys.

**Comment by IpourimRobzs** [comment]
@clobber I was wondering if you could provide a terminal code for the GBA one. I was having the same problem with Higan and I need to switch back to VBA. PLEASE HELP! Thanks.

**Comment by clobber** [comment]
@IpourimRobzs 

Run the following in Terminal.app:
defaults write org.openemu.OpenEmu defaultCore.openemu.system.gba org.openemu.VisualBoyAdvance

**Comment by cyco** [comment]
@clobber did we add that to the sidebar context menu already?

**Comment by cyco** [comment]
lol nvm, https://github.com/OpenEmu/OpenEmu/issues/1830#ref-commit-fa5a8fd
