### ISSUE TITLE
Compile with Syphon

### ISSUE THREAD

**Issue by LordHDL** [OpenEmu/OpenEmu#1831]
Seems since 7287afd Syphon output has to be configured now.  How is this done (suggest adding to wiki)?

**Comment by cyco** [comment]
Good idea to add a wiki entry. Syphon support is enabled by default using a preprocessor macro. To change that you go to OpenEmu Build Settings, search for macro, and remove SYPHON_SUPPORT from the list.

![screen shot 2015-02-18 at 18 35 45](https://cloud.githubusercontent.com/assets/697021/6252794/1782054e-b79d-11e4-967e-619379d6d516.png)

ps: I forgot to enable syphon for release builds. Should be fixed now.
