### ISSUE TITLE
Syphon aspect ratio

### ISSUE THREAD

**Issue by LordHDL** [OpenEmu/OpenEmu#1833]
I read in some older issues that you want to ensure 4:3 ratio for games designed for older TVs.  Syphon output doesn't adhere to this, however.  For example, Genesis games will output at 320x224 instead of 240, SNES at 256x224, etc.

**Comment by clobber** [comment]
I think this is by design.

Syphon, as implemented in OpenEmu, just takes the raw video output and doesn't capture any of the post processing like shaders or our aspect ratio correction.
