### ISSUE TITLE
Help with cd based games? (Saturn/psx)

### ISSUE THREAD

**Issue by MechaPlatypus82** [OpenEmu/OpenEmu#1835]
I've been trying to figure out how to get a Saturn game to run in openemu. I've drag and dropped it over into the library and it does nothing. The PSX folder looks the same, but won't load either. Everywhere I look sends me to the cue sheet link here, but how do I work with the .cue? Here are the contents of the decompressed folder.
![screen shot 2015-02-19 at 8 37 11 pm](https://cloud.githubusercontent.com/assets/11083899/6280226/ac81631c-b877-11e4-824a-458758f61cb6.png)

**Comment by danfiscus** [comment]
Where did you get the game files from? If it's a website, please provide a link.

**Comment by clobber** [comment]
@MechaPlatypus82 Guide here: https://github.com/OpenEmu/OpenEmu/wiki/User-guide%3A-Cue-sheets-%E2%80%94%C2%A0loading-CD-based-games

Sorry, .ogg isn't supported in the emulators AFAIK, so you'll need different rips.

@danfiscus Please don't ask for those here.

**Comment by MechaPlatypus82** [comment]
![screen shot 2015-02-19 at 9 33 32 pm](https://cloud.githubusercontent.com/assets/11083899/6280646/0d01c978-b87f-11e4-9b25-8f5b536015ce.png)
The PSX folder is basically the same, but includes ape files. My question I suppose is do I need to compile these extra files to make a .bin for the game to run?

**Comment by astrange** [comment]
CDDA audio tracks must be .wav files. The .7z must be decompressed into the .bin file. I don't think handling this is in the scope of OE.
