### ISSUE TITLE
Can't use diagonal movements on Super Nintendo

### ISSUE THREAD

**Issue by aquinotad** [OpenEmu/OpenEmu#1836]
Hi, i'm currently trying to play FF3 on the OpenEmu SNES emulator, but it seems to not be able to perform diagonal codes, as 1 character needs such diagonal movements to use many of his abilities, currently i cannot do so.

Is there any way to do this? Am i doing something wrong?

**Comment by clobber** [comment]
Keyboard? Gamepad? or what?

Diagonal (directional) works fine here with the arrow keys via keyboard and d-pad on a gamepad. Are you actually talking about three-button moves or something else?

**Comment by aquinotad** [comment]
Keyboard. Using the regular Macbook keyboard.. I'm talking two-button moves, didn't work with the arrow keys, also tried to change the movement to different keys other than the arrow keys, still doesn't work.

**Comment by aquinotad** [comment]
Seems to be working now, i just need to hold more the Down key before i hit the Left/Right one, it seems to be fine. I'm sorry to bother, and thank you for your help
