### ISSUE TITLE
Multiple monitors lags performance on SNES

### ISSUE THREAD

**Issue by macfan406** [OpenEmu/OpenEmu#1843]
Regardless of the core I'm using, OpenEmu lags like crazy, chopping sound when playing SNES games. I'm fairly sure it's not the computer since its a 2010 Mac Pro with a 3 GHz Quad Core Xeon and 10 GB of RAM. It's OpenEmu 1.0.4 on Yosemite 10.10.2

**Comment by astrange** [comment]
Does Activity Monitor show anything using 100% CPU?

**Comment by macfan406** [comment]
No. I had Wirecast running but the issue persisted when I quit it...

**Comment by astrange** [comment]
Some kind of graphics driver issue, maybe.

Please run "sudo spindump" in Terminal while it's having issues, then link the output here.

**Comment by macfan406** [comment]
I have the spindump.txt file, but I can't submit it here. Tried pastebin but nogo as well.. Can I link to a Google Drive URL?

**Comment by astrange** [comment]
Sure, or use gist.github.com.

**Comment by macfan406** [comment]
https://gist.githubusercontent.com/macfan406/817344413597d9d505f0/raw/spindump.txt

**Comment by astrange** [comment]
- Emulator thread is spending lots of time stuck in a synchronous wait inside the GPU driver. May be able to avoid this work with direct iosurface rendering, but it's really a driver bug.

- You're running Higan (bsnes) instead of SNES9X, which is known to be really slow, so maybe switching cores would help?

- The spindump shows something working WindowServer by recording the screen, presumably Wirecast. Maybe quitting and reopening OE after stopping recording would help.

**Comment by macfan406** [comment]
I tried with Snes9x. Same issue. Not sure how to do direct iosurface rendering. 

John N. MacKay
Independent Arranger, Copyist, Orchestrator
Freelance Conductor, Brass Musician

**Comment by clobber** [comment]
Out of curiosity, which filters are you using and what happens if you switch to just using "Nearest Neighbor"?

**Comment by macfan406** [comment]
I have been using Nearest Neighbor

**Comment by mrvacbob** [comment]
It sounds like we'll have to make code changes for it.

**Comment by clobber** [comment]
@macfan406 I'll send you a test build to try in a few days to see if it changes anything. Just an experiment so I don't know if it'll have an effect.

**Comment by macfan406** [comment]
THank you. I would try building myself, but I cannot get XCode to work for the life of me...

**Comment by clobber** [comment]
Okay, can you try with this build of the app and see if the problem persists?

https://transfer.sh/pVz8d/openemu-1.0.4-no-clientstorage.zip

**Comment by clobber** [comment]
Any change?

**Comment by johnmackay13** [comment]
I didn't catch this. I'll check when I boot into Yosemite. No issues on
Mountain Lion.

On Mon, Mar 23, 2015 at 2:09 AM, clobber <notifications@github.com> wrote:

> Any change?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenEmu/OpenEmu/issues/1843#issuecomment-84826906>.
>



-- 
John N. MacKay
*Independent Arranger, Copyist, Orchestrator*
*Freelance Conductor, Brass Musician*

**Comment by clobber** [comment]
Any update on Yosemite with the newer build I posted?

**Comment by clobber** [comment]
Closing, no additional info.
