### ISSUE TITLE
What license is the code for OpenEmu under?

### ISSUE THREAD

**Issue by JamesMcMahon** [OpenEmu/OpenEmu#1844]
Please forgive me if I am missing it but I don't see any license information for OpenEmu in the repo. Can you a license file with a license of the maintainer's choosing?

**Comment by cyco** [comment]
The main app (this repo) is published under a BSD 3-clause license (see file headers).

**Comment by omouse** [comment]
can you please include a copy of the LICENSE with the code? thx
