### ISSUE TITLE
Openemu PSX Quick Load Not Working

### ISSUE THREAD

**Issue by estcourt21** [OpenEmu/OpenEmu#1845]
Hi guys

Recently installed openemu experimental to use the psx emulator. Had a lot of fun trying to set up the bios, but we won't go there!

I've got my PS3 controller and keyboard set up to quick save and load, however the load won't work on either. Quick save works as I see the disk in the top left corner when I press it.

Any ideas why?

**Comment by cyco** [comment]
I just tested quick load and it works on my machine. Can you see which version of Mednafen is installed (go to Preferences, then Cores).

**Comment by estcourt21** [comment]
I have 0.9.34.1

Is this the old version? I can't see how to update it if I'm running an old version. Apologies if I'm being stupid

**Comment by cyco** [comment]
Looks like that's the latest version we released ^^
and it doesn't support save states yet.

**Comment by estcourt21** [comment]
Any ideas why my quick load won't work? With the extensive information I've provided I'm sure you'll be able I've been very helpful - running OS X Yosemite 10.10.2 (if that's of any use). 

Or by 'doesn't support save states yet' means no support on this front? Sorry, new to this forum.

Thanks for your help either way

**Comment by cyco** [comment]
Extract this https://transfer.sh/16qv6p/mednafen.oecoreplugin.7z to ~/Library/Application Support/OpenEmu/Cores/ . That's the latest developer version of the core you need.
I wonder why you see the disk in the top left corner even though save sates are disabled. You might want  to make sure you're using OpenEmu 1.0.4 (https://github.com/OpenEmu/OpenEmu/releases/download/v1.0.4/OpenEmu_1.0.4-experimental.zip).

**Comment by estcourt21** [comment]
Thanks will try that. Just double checked and I am using 1.0.4. 

Under Macintosh HD ▸ Users ▸ JPENTERPRISES ▸ Library ▸ Application Support ▸ OpenEmu ▸ Mednafen I have a battery saves folder which has my ps1 saves I've made?!

No folder for playstation however in the save states folder

**Comment by estcourt21** [comment]
Interesting, games won't play now. I double click them and nothing. Right click, play game - also nothing.

Tried adding another game into the library. Game imported fine but same issue

Just double checked the core and is running on 0.9.38.2. Doubled checked the BIOS and the 3 scph files are there.

Sorry to be a pain!

**Comment by cyco** [comment]
Might be a problem with permissions. In your system settings go to Security & Privacy and make sure that "Allow apps downloaded from:" is set to anywhere. Also try opening the core from finder by right licking it and then choosing 'Open' :D

**Comment by estcourt21** [comment]
Still the same problem. Made the security changes, extracted the file again and tried the right click open option and no joy. Tried opening the unextracted file with openemu, prompted me to install MAME. Again no luck

I've open a can of worms ever since I've tried to get to emulate playstation games! Just double checked and the other roms i have installed work fine on the other emulators

**Comment by clobber** [comment]
@estcourt21 Please wait until we've officially released a version of the Mednafen core plugin that supports save states. There is no help for 'experimental' cores and features. OpenEmu will support these things in a future release.

**Comment by estcourt21** [comment]
Thanks for your help
