### ISSUE TITLE
Alert sound from invalid keyboard entry when game is launched from Finder

### ISSUE THREAD

**Issue by differenceclouds** [OpenEmu/OpenEmu#1849]
When launching a game from Finder, instead of the game browser, using the keyboard to play a game makes an error sound every time you hit a key, in the same way it does when typing on the keyboard when the left panel of the game browser is focused instead of the main browser panel. I launch things from spotlight frequently, so this is a big issue for me.

**Comment by clobber** [comment]
Please search for duplicate issues. #1741

**Comment by differenceclouds** [comment]
rude
