### ISSUE TITLE
Trouble With MAME

### ISSUE THREAD

**Issue by hsien-ko** [OpenEmu/OpenEmu#1850]
Hi, I'm trying to use MAME with openemu.  However, when I try to run Night Warriors: Darkstalkers Revenge, a game that works on homebuilt MAME as well as GGPO and FightCade, it doesn't load or crashes the program.  I was advised to look on console for an error message, and I got VMware Fusion Start Menu[283]: assertion failed: 14C109: libxpc.dylib + 40320 [876216DC-D5D3-381E-8AF9-49AE464E5107]: 0x13.  I was wondering if was a problem with the emulator or some error on my end.

**Comment by clobber** [comment]
VMware? Not sure I can help you there.

This might help though: https://github.com/OpenEmu/OpenEmu/issues/1588
