### ISSUE TITLE
Unable to launch openemu on OS X 10.10.2 (Yosemite)

### ISSUE THREAD

**Issue by digablesamples** [OpenEmu/OpenEmu#1855]
I'm trying to run the app (version 1.0.4). Upon clicking, I'm met with this prompt:

"The application "openemu" can't be opened."

I've lifted the restriction that gatekeeper places on apps with unrecognized developers in my system preferences; that option is set to allow apps downloaded from 'anywhere'. 
I've also tried to run both normal and experimental versions. 
No beans. 
I'm currently trying to compile it. But for a person unfamiliar with coding and things of that nature, it's a bit of a tedious task. I just want to play, man. Lol.
I'm running OS X 10.10.2, what's wrong?

**Comment by clobber** [comment]
Those messages are usually followed by an error code. Anyway, the problem is on your end and you definitely do not need to compile the app to resolve this.

First steps for you should be to repair permissions and restart your machine. Then see if the problem still persists.

**Comment by clobber** [comment]
And uhhh after all that, try right clicking on the icon and selecting open if you hadn't done that before lifting gatekeeper.

**Comment by digablesamples** [comment]
The right clicking returned the same result. 
However, the unarchiving utility I was using was "breaking" the app. I deleted that application and used the native archiving utility app and it launched! Totally working now. 
Thank you for your time and for your help. This ish is dope. Now to find a way to beat Ken and Dhalsim.

**Comment by clobber** [comment]
Okay, so whichever utility was creating a corrupt binary. Thanks for the update.
