### ISSUE TITLE
Mame advanced features

### ISSUE THREAD

**Issue by edgb** [OpenEmu/OpenEmu#1860]
Hello!, 
I was trying to setting up the mame core, I´ve seen that the core is the SDLMame, so I installed the original one trying to been able to have cheats, dip switches working, .ini file and everything went just fine, since both are using the same core I just was wandering if it is possible to do that with the mame core of openEmu, 
I´ve already seen that in open emu it´s a pluging so I suppose It´s been compiled in different way. 
I just wanted to know what did you think about it, 
I was too wandering if I could help in this way for the community, so any advice will be helpful, I´ve searched but found nothing on this subject. 
With this done I think name already would be finished since every important thing would be covered.

Greetings and thanks for your time! :D

**Comment by clobber** [comment]
Sorry, no. The only thing that is available is the 'service' button (check Arcade input prefs) which will open the service menu in most arcade games revealing some settings and DIP switches.
