### ISSUE TITLE
OpenEmu Crashing Yosemite 10.10.3

### ISSUE THREAD

**Issue by javajoe666** [OpenEmu/OpenEmu#1862]
Several weeks ago I switched to the experimental version, after a day or so I got a blue screen on my macbook pro while playing. System was unable to reboot, had to visit apple store and they determined that I was having OS issues. Reinstalled entire OS, I went back to the regular version of OpenEmu and I continue to have the same issue everytime I use it. Any word on this issue?

**Comment by clobber** [comment]
Well you're running on a beta/pre-release of an OSX update, so, could be anything. Not much to go by since you haven't supplied any crash logs. You can find those in Console.app

**Comment by clobber** [comment]
Closing, no additional info.
