### ISSUE TITLE
Huge collection of roms but only certain ones are being imported and I can't find out why.

### ISSUE THREAD

**Issue by freeosin** [OpenEmu/OpenEmu#1866]
I have a huge collection of roms and want to bring them into OpenEmu. They are .7z format. Some import and others don't. I have no idea why. I have tried to drag and drop roms as well as just go to 'add to library' and they don't get added. I have attached a few screenshots but not sure if they will be helpful or not. One collection of roms is for sega and the other is snes. Anything I could try? Attached is my SNES example.
![screen shot 2015-03-17 at 12 14 33 am](https://cloud.githubusercontent.com/assets/4520481/6681317/d0118fd8-cc3a-11e4-9ab7-bdac69cfd158.png)
![screen shot 2015-03-17 at 12 14 55 am](https://cloud.githubusercontent.com/assets/4520481/6681318/d0126bec-cc3a-11e4-9d1d-5df2e10cb40b.png)
![screen shot 2015-03-17 at 12 15 34 am](https://cloud.githubusercontent.com/assets/4520481/6681319/d0142a40-cc3a-11e4-8d81-f47fcbf19bf3.png)

**Comment by freeosin** [comment]
So I just downloaded the experimental version to see if that would fix it and it imported everything but put them in the 'arcade' section. Now when I try and open them they do nothing. So weird. Some are considered SNES and others ARCADE with the same extensions. The ones that got put in the ARCADE section don't do anything. I did install the MAME after it asked me to do so, but that didn't fix them because they are obviously built for SNES.
![screen shot 2015-03-17 at 12 35 28 am](https://cloud.githubusercontent.com/assets/4520481/6681488/9fbe33ce-cc3d-11e4-9d81-0a7978e09294.png)

**Comment by clobber** [comment]
Experimental doesn't mean experimental OE, it just means additional emulator cores. It's the exact same codebase as the standard build.

Anyway, you need to extract all of those files first. Only single games per zip will import and they cannot contain other junk files.
