### ISSUE TITLE
The 1M sub-circuit board is not installed.

### ISSUE THREAD

**Issue by zborowa** [OpenEmu/OpenEmu#1870]
Hey,

I noticed that there were already issue posts about the 128K flash saves. Right now I'm trying to play the Pokemon Ultra Violet (hack rom) but I'm unable to save the game (save states work fine).
In one of the issues the solution was as follows "What you'd want to do is add an entry for this game to the core (assuming it has its own unique ID you can reference) like so " ... proceeded by a link that does not work anymore.
Can someone help me with explaining this solution to me? What does he exactly mean by core and where can I find that rom ID?

![pokemon ultra violet](https://cloud.githubusercontent.com/assets/2786784/6767931/aaecb76e-d09a-11e4-88c1-f68b6eb5914c.png)

**Comment by clobber** [comment]
We've recently updated the VBA port but it is not yet distributed over the in-app updater. You either need to open the ROM in a hex editor and change the ID at offset 0xAC to a proper Pokemon one that will enable the 128KB/1Mbit FLASH saves (I don't know why ROM hackers continually screw with these) or add an entry to vba-over.ini https://github.com/OpenEmu/VisualBoyAdvance-Core/blob/master/src/vba-over.ini and recompile the core from source.

We don't, and probably won't, have a way to manually turn on that save type with an option.
