### ISSUE TITLE
Low performance on full screen and 24Hz/30Hz

### ISSUE THREAD

**Issue by dawiinci** [OpenEmu/OpenEmu#1872]
If I run my Mac Mini (2011) on 1080p 24Hz I get very poor performance on full screen. It is like slow motion combined with a stuttering audio. It is not happening in windows mode and it also works immediatley if I make the menu bar at the top visible. It also works on 60Hz.

This is tested under NES and Gameboy.

**Comment by clobber** [comment]
That isn't possible to run these at 24Hz. These consoles run at around 60fps and need your monitor to match, running at 60Hz.

**Comment by dawiinci** [comment]
What can I do if I have to stick with 2160p at 30Hz?

**Comment by dawiinci** [comment]
Also it works when not in Full Screen.

**Comment by clobber** [comment]
>What can I do if I have to stick with 2160p at 30Hz?

Get out your checkbook.

>Also it works when not in Full Screen.

Not running at 60Hz then and whatever game you're running at with whichever filter is too much for your GPU.

**Comment by dawiinci** [comment]
Sorry but I don't believe that.

If I just put my mouse pointer to the top and the menu bar appears it runs as smooth as it gets even in full screen. I don't know why but it works as a workaround. 

Right now there is no Mac Mini available that can send 60Hz, therefore I don't have many choices. And no a Mac Pro is not an alternative. ;)
