### ISSUE TITLE
(10.7) Can't delete save states.

### ISSUE THREAD

**Issue by RoastyMcToasty** [OpenEmu/OpenEmu#1873]
Hi,
I have many save states on the SNES emulator, the game is Final Fantasy VI, and I wanted to delete them. I went to the Github page and tried it but it didn't work, the save states menu also didn't disappear even when I closed OE. I also have a bug where the menu when right clicking a game is on the other side of the app whereas before it was normal. Here is a SS of the menu problem, <img src=http://i.imgur.com/e8s8ccc.png> As you can see Final Fantasy VI (top right) is highlighted and I right-clicked and the menu is bottom left. The Save state problem, <img src=http://i.imgur.com/Gb9UTda.png> <img src=http://i.imgur.com/DtMVIFy.png> <img src=http://i.imgur.com/bVufEu3.png> Top is in-game, middle is after I close the game but it is still there and bottom is with Openemu closed, I have to quit OE so it disappears. This is when I click on the save state and it freezes.

**Comment by clobber** [comment]
It's important that we know which version of OpenEmu and which version of OS X you're running.

**Comment by RoastyMcToasty** [comment]
Openemu 1.0.4 and OS X 10.7.5

**Comment by clobber** [comment]
I've seen this a few times and I think it's a 10.7 issue. We cannot keep supporting versions of OS X this old, especially ones we cannot test on. I'd recommend upgrading to the latest OS X for numerous reasons including fixes to graphic drivers and security updates.

**Comment by RoastyMcToasty** [comment]
Okay, thanks.

**Comment by clobber** [comment]
Dupe #1639

**Comment by RoastyMcToasty** [comment]
Just found out.
