### ISSUE TITLE
320M: Choppy Video and Audio Lag

### ISSUE THREAD

**Issue by macosxsupreme** [OpenEmu/OpenEmu#1875]
I am running Openemu on my macbook and the playback of any ROM file is choppy. I have attempted to utilize different settings but nothing seems to correct the issue. My machine is:

  Model Name:	MacBook
  Model Identifier:	MacBook7,1
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	3 MB
  Memory:	8 GB
  Bus Speed:	1.07 GHz

Mac OS 10.10.3

Openemu version 1.0.4

I much enjoy the idea of this program but at the moment its unusable.

**Comment by clobber** [comment]
Can you search the various open and closed tickets first to see if any of those situations or solutions apply first?

**Comment by clobber** [comment]
Your GPU is the 320M so that is a good keyword to search first.

**Comment by clobber** [comment]
#1853
