### ISSUE TITLE
MAME Bioses

### ISSUE THREAD

**Issue by raccoonmario3** [OpenEmu/OpenEmu#1877]
How am I supposed to install bioses on MAME through Openemu? I wanted to play Galaga, so I found the files 51xx.bin and 54xx.bin on a rom site, and dragged them into Openemu. Whenever I would do this, I would get an import issue, and have to choose between Atari 2600 and Odyssey 2. After modifying the core plugins .plist file to not recognize .bin files, and modifying the MAME core plugin .plist file to recognize .bin files, I was finally able to drag the bioses into Openemu, into the correct category (Arcade). However, when I try to load Galaga, I still get the same error:

3/26/15 11:53:16.688 PM OpenEmuHelperApp[2385]: MAME: Audit failed with output:
galaga      : 51xx.bin (1024 bytes) - NOT FOUND (namco51)
galaga      : 54xx.bin (1024 bytes) - NOT FOUND (namco54)

I made sure to use the 0.149 version of the rom. The two bios files are in the Arcade game library. What am I doing wrong? Where is Openemu looking for the bioses for this game? Is it looking somewhere else? Is there some other way to install a bios onto MAME?

**Comment by clobber** [comment]
You need both namco51.zip and namco54.zip. Simply copy those zip files (do not extract them, never extract MAME zips) to your Arcade game library folder, which if you picked the default would be `~/Library/Application Support/OpenEmu/Game Library/roms/Arcade` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
