### ISSUE TITLE
Still cannot import ColecoVision Roms

### ISSUE THREAD

**Issue by Everett1954** [OpenEmu/OpenEmu#1878]
Hi, I am using Version 1.0.4, I cannot import the .rom file.  I read that they must renamed to .col

But do rename the .rom or the zip file to get them to import properly?

Thanks

**Comment by clobber** [comment]
ColecoVision can be either .col or .rom. Extract the file from your zip and make sure its one of those. To rename a file extension, in Finder you right click the file, select "Get Info" and then rename it under the "Name & Extension" heading.

**Comment by clobber** [comment]
Whoops, I just noticed the fix for importing CV .rom's isn't in 1.0.4. So yeah, for now rename to .col. The fix will be in the next version.
