### ISSUE TITLE
Are there turbo buttons?

### ISSUE THREAD

**Issue by bbwlover** [OpenEmu/OpenEmu#1879]
All the controller setups for each console use the most basic design. Is it possible to add in turbo buttons, like you would see with the NES Max?

**Comment by clobber** [comment]
Dupe #946

**Comment by bbwlover** [comment]
What I meant was turbo buttons for the controllers. I understand that you can speed up the emulation, but I'm curious to know if you can have turbo buttons that simulate rapidly pressing the buttons.

**Comment by kylewlacy** [comment]
It *is* a dupe of #933, though
