### ISSUE TITLE
PS1 Games No Longer Working, Build Fails due to Mednafen errors, 

### ISSUE THREAD

**Issue by hanshillen** [OpenEmu/OpenEmu#1880]
In the past (January 2015) I've been able to successfully do a "Build All + Experimental" using the excellent instructions provided on provided https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide. I particularly wanted a custom build to get save state support for PS1 games, and it worked great. 

A few days ago (March 2015) I pulled the latest updates to build a newer version, after seeing some references to Gamecube support in the commit descriptions. 
I used the "git pull" and "git submodule update --recursive --init" commands to update the code, followed by the xcode build steps described in the instructions linked to above.

Unfortunately, after replacing the old build with the new one, my PS1 games have stopped working. Double clicking on them does nothing. The console does not provide enough information (for me) to determine what the problem is:
```
3/31/15 19:35:35.909 OpenEmuHelperApp[33160]: parent application is: OpenEmu
3/31/15 19:35:35.931 OpenEmuHelperApp[33160]: Some shit about the game.
3/31/15 19:35:35.941 OpenEmuHelperApp[33160]: ROM did not load.
3/31/15 19:35:35.941 OpenEmuHelperApp[33160]: Deallocating proxy: <OEThreadProxy 0x7f845b5935d0, target: <MednafenGameCore: 0x7f845b592e40>>
```
I've tried changing the "Run Games Using" value in the secret menu from Distributed Objects to the other two values, with no effect (except that Open Emu will crash every time a PS1 game is started when the "Background Thread" value is chosen). 

I just noticed that there is in fact one game in my Library does still work: Policenauts (English Translation). This is also the only game where I normally don't see the "Video Standard Mismatch" text during the PS1 opening animation, so I'm wondering whether this is something related to the game's region (I also tried changing the "region" setting in the Secret settings menu, no effect.

I tried replacing the new app file with my older one, but now starting PS1 games would show an alert about a missing module (if I remember correctly), so I went back to the build process. I figured maybe there's something wrong with my build, and checked out a clean copy of everything. Now when I do a "Build All" or "Build All + Experimental", the build fails with the following errors:

```
Ld /Users/hanshillen/Library/Developer/Xcode/DerivedData/OpenEmu-eslrbhxajxfwgrahepcpifshtbmf/Build/Products/Release/Mednafen.oecoreplugin/Contents/MacOS/Mednafen normal x86_64
    cd "/Users/hanshillen/Documents/Dev/Misc/Openemu Redo/OpenEmu/Mednafen"
    export MACOSX_DEPLOYMENT_TARGET=10.7
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -L/Users/hanshillen/Library/Developer/Xcode/DerivedData/OpenEmu-eslrbhxajxfwgrahepcpifshtbmf/Build/Products/Release -L/Users/hanshillen/Documents/Dev/Misc/Openemu\ Redo/OpenEmu/Mednafen/libsndfile -F/Users/hanshillen/Library/Developer/Xcode/DerivedData/OpenEmu-eslrbhxajxfwgrahepcpifshtbmf/Build/Products/Release -filelist /Users/hanshillen/Library/Developer/Xcode/DerivedData/OpenEmu-eslrbhxajxfwgrahepcpifshtbmf/Build/Intermediates/Mednafen.build/Release/Mednafen.build/Objects-normal/x86_64/Mednafen.LinkFileList -mmacosx-version-min=10.7 -dead_strip -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -lsndfile -lFLAC -lvorbis -lvorbisenc -liconv -framework Cocoa -lz -framework OpenEmuBase -Xlinker -object_path_lto -Xlinker /Users/hanshillen/Library/Developer/Xcode/DerivedData/OpenEmu-eslrbhxajxfwgrahepcpifshtbmf/Build/Intermediates/Mednafen.build/Release/Mednafen.build/Objects-normal/x86_64/Mednafen.lto_temporary.o -Xlinker -dependency_info -Xlinker /Users/hanshillen/Library/Developer/Xcode/DerivedData/OpenEmu-eslrbhxajxfwgrahepcpifshtbmf/Build/Intermediates/Mednafen.build/Release/Mednafen.build/Objects-normal/x86_64/Mednafen_dependency_info.dat -o /Users/hanshillen/Library/Developer/Xcode/DerivedData/OpenEmu-eslrbhxajxfwgrahepcpifshtbmf/Build/Products/Release/Mednafen.oecoreplugin/Contents/MacOS/Mednafen

Undefined symbols for architecture x86_64:
  "_FLAC__metadata_object_vorbiscomment_find_entry_from", referenced from:
      _sf_flac_meta_callback in libsndfile.a(flac.o)
  "_FLAC__metadata_object_new", referenced from:
      _flac_write_header in libsndfile.a(flac.o)
  "_FLAC__metadata_object_vorbiscomment_entry_from_name_value_pair", referenced from:
      _flac_write_header in libsndfile.a(flac.o)
  "_FLAC__metadata_object_delete", referenced from:
      _flac_close in libsndfile.a(flac.o)
  "_FLAC__metadata_object_vorbiscomment_append_comment", referenced from:
      _flac_write_header in libsndfile.a(flac.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I don't understand enough of the build process to know what this means or how to resolve it, is there anybody here who does can help me out or point me in the right direction?

**Comment by clobber** [comment]
If games for only a certain region load and others don't, that means you have incorrect BIOS files and forced wrong ones into your folder instead of through drag and drop and instructions via the guide in the wiki.

If you get linker errors for Mednafen, you need to clean build. You must also be sure to build for profiling/release and not debug.

Don't run the games in anything besides XPC; those other options are for debugging. The region setting in that menu has nothing to do with your problem either. You're making many assumptions that aren't helping you.

**Comment by hanshillen** [comment]
Thanks for the quick response. Getting proper BIOS files with the right Md5 hash solved the problem and PS1 games are loading again. The clean build did not resolve the build errors, but that's less important now.
