### ISSUE TITLE
Can't open DS Roms, Help?

### ISSUE THREAD

**Issue by gigiman12** [OpenEmu/OpenEmu#1883]
Everytim I try to open a DS Rom I get the following message. "Couldn’t communicate with a helper application." Before, I was able to open the file but got a black screen. After deleting and reinstalling this is the message that I get.

**Comment by clobber** [comment]
Help us help you? You've given zero information to go on. Need OS X version, your OpenEmu version, Desmume version in core prefs, your system specs, crash logs, how and what exactly you're trying to load with steps to reproduce the problem.

**Comment by gigiman12** [comment]
Lol sorry I don't know how to find that a lot of that info but I do know I have OS X 10.9.5 and OpenEmu 1.0.4. How can I find the rest of the information?

**Comment by clobber** [comment]
You can't tell me how you're trying to load a game, what it is and exact steps to reproduce the problem? You can find the Desmume version in Core Preferences inside the application.

As for the rest...
https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting%3A-Console-and-crash-reports

First things first, try a restart of your machine and then open the app and try again with nothing else running.

**Comment by gigiman12** [comment]
Im trying to load the nds file for Heart Gold I downloaded here: http://www.emuparadise.me/Nintendo_DS_ROMs/Pokemon_-_HeartGold_Version_%28U%29/50858
I dragged the file into OpenEmu and all I get is a black screen with the game music however. I've tried games on the gba emulator and the snes emulator and they work perfectly fine. Here's the report from console which doesn't seem to show that anything is wrong:
![screen shot 2015-04-01 at 2 26 29 am](https://cloud.githubusercontent.com/assets/11749407/6938260/ea941dfc-d816-11e4-8304-319344691f56.png)

The only other info I really do know is that I have a retina display. Sorry for my incompetence haha

**Comment by clobber** [comment]
All the pokemon games have issues in Desmume beyond our control.

They could be:
* AP patch (or lack of) issue: http://wiki.desmume.org/index.php?title=Faq#The_main_game_graphics_are_missing.21_The_screen_is_black.21
* Save file bug in 0.9.10
* JIT bug

Officially, pokemon games are unsupported in Desmume most like due to the built-in AP (Anti Piracy) measures. Sorry, nothing we can do for you.

Also, please search the issues next time. This has come up many times.

Dupe: #1112
