### ISSUE TITLE
After update to v1.0.4,roms run, but screen is black

### ISSUE THREAD

**Issue by Daeorus** [OpenEmu/OpenEmu#1884]
When I try and open my roms, the screen remains black, but I can hear the game running. Pressing buttons even triggers the sound they would if the rom was functioning normally. If I had known that updating would make my games unplayable, I would not have updated.

**Comment by clobber** [comment]
>If I had known that updating would make my games unplayable, I would not have updated.

Ah yes, because we intentionally shipped an update that would break something on *your* machine.

Please search the issues since this has come up more than once.

Dupe: #1681

**Comment by Daeorus** [comment]
Thanks, and sorry for the last bit founding so rude and ungrateful, I didn't mean it that way but now that I reread it it totally is. You guys rock, sorry for being so mean.
