### ISSUE TITLE
a usb adapter that follow open emu. 

### ISSUE THREAD

**Issue by ulao** [OpenEmu/OpenEmu#1886]
Hey team, I just wanted to let you know Bliss-box is a huge supporter of OpenEmu. We have regularly checked in with the latest version of the Mac and OpenEmu, so that all Bliss-Box fans can use the any controller they want. 

Up till this point we only made hand crafted adapters but we are not running a KS.
https://www.kickstarter.com/projects/544088930/bliss-box-4-play-one-adapter-for-many-controllers-0

Love what you do..

**Comment by clobber** [comment]
Please stop. GitHub issues is not a place to generate interest or revenue for your kickstarter campaign.
