### ISSUE TITLE
Pokemon Advanced Adventure: OpenEmu Crashes in Mac 10.10 

### ISSUE THREAD

**Issue by Salax7** [OpenEmu/OpenEmu#1887]
Hi, 

I'm using mac 10.10 and just downloaded OpenEmu. Whenever I start playing Pokemon Advanced Adventure, OpenEmu crashes.

Please help!

**Comment by clobber** [comment]
Well this is a ROM hack so it could be the hack itself. I loaded it and it didn't crash. Is it crashing at a certain point or always? Can you post the crash log for OpenEmuHelperApp found in Console.app?
