### ISSUE TITLE
Savestate Transfer

### ISSUE THREAD

**Issue by npd200** [OpenEmu/OpenEmu#1892]
I have an englished-patched Fire Emblem game that has a known freezing bug by other users. The solution seems to be moving and renaming the file in the original Japanese rom. How do I transfer the savestate from one rom to another?

**Comment by npd200** [comment]
Any insight? @clobber

**Comment by kylewlacy** [comment]
@npd200 What emulator core are you using to play the game? There's no official way to transfer saves in OpenEmu, but it's sort of possible by copying some files around. The process will differ depending on the system and emulator, though.

**Comment by npd200** [comment]
I'm using a visual boy advance 1.8.0.1231 core. The problem seems to be
just getting the save file to move into another rom. If it helps, I'm on a
mac book pro.

On Thu, Apr 23, 2015 at 2:10 PM, Kyle Lacy <notifications@github.com> wrote:

> @npd200 <https://github.com/npd200> What emulator core are you using to
> play the game? There's no official way to transfer saves in OpenEmu, but
> it's sort of possible by copying some files around. The process will differ
> depending on the system and emulator, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenEmu/OpenEmu/issues/1892#issuecomment-95674121>.
>



-- 
- Nick Davini

**Comment by clobber** [comment]
#1890
