### ISSUE TITLE
Custom fonts for system button names can crash OpenEmu.

### ISSUE THREAD

**Issue by torque** [OpenEmu/OpenEmu#1895]
Introduced in b1140d1ff2a8e47d3e2edf9bd3a787a492d83d31. Specifically [OEControlsKeyLabelCell.m L59-L61](https://github.com/OpenEmu/OpenEmu/blob/master/OpenEmu/OEControlsKeyLabelCell.m#L59-L61). The problem is that there is no fallback in case the font corresponding to the provided `fontName` does not exist, so the `NSTextCell`'s font property will be overwritten with `nil`, which causes a crash in [OEControlsButtonSetupView.m L289](https://github.com/OpenEmu/OpenEmu/blob/master/OpenEmu/OEControlsButtonSetupView.m#L289) in the dictionary constructor (it throws an exception which doesn't get handled).

At the minimum, there should be a fallback if the font does not exist. Lucida Grande is already assumed to exist, so maybe that's good enough?

**Comment by cyco** [comment]
Thanks for point that out.
