### ISSUE TITLE
OpenEmu Mac cheats problem

### ISSUE THREAD

**Issue by CasualKnight** [OpenEmu/OpenEmu#1896]
So basically this is for all my games, in the wheel icon in the hud, there is supposed to be a select cheat option, and I don't have it.

**Comment by clobber** [comment]
Why are you using a package of OpenEmu that you did not get from our website? Can you tell me where you downloaded yours?

**Comment by CasualKnight** [comment]
I downloaded mine off of emuparadise.

**Comment by CasualKnight** [comment]
It looks exactly the same as it should, theres just no cheats option.

**Comment by cyco** [comment]
Try the official version from openemu.org and let me know if the wheel shows up there.

**Comment by CasualKnight** [comment]
Ok I got it. It works. Thanks

**Comment by cyco** [comment]
Great

**Comment by henhen1** [comment]
hello,so i already downloaded the app from openemu.org but still cant find cheat code icon in the hud for sony playstation ..help please
