### ISSUE TITLE
Wario Ware: Touched! Start screen

### ISSUE THREAD

**Issue by GB-CG** [OpenEmu/OpenEmu#1899]
Using the trackpad, I can't get past the title screen, the touch screen is not functioning. before that, the touch screen let me skipped the opening cut-scene. I also used a mouse but that didn't solve the issue.

Tried on v1.0.4, with OSX 10.9.5 and 10.10.2

**Comment by clobber** [comment]
Checked and it appears to be an issue in Desmume 0.9.10 itself, not our implementation. Maybe related to the save file "bug" that they let sit for over a year without a fix.

The good news is it seems to be working in Desmume 0.9.11, which we'll push an update out for soon.

**Comment by GB-CG** [comment]
That's odd, It worked for me on the actual Desmume 0.9.10. Guess I have to play Touched! on Desmume in the meantime. Thanks for checking it out. :)

**Comment by Phalaric** [comment]
This still happens on the latest version of OpenEmu (2.0.1) with the Desmume core updated to 0.9.11. I'm running on El Capitan 10.11.3.

**Comment by AsrielMemeurr413** [comment]
I have the latest verion (2.0.5), but it still won't start. Should i just get Desmume in the meantime?

**Comment by Oatmeal88** [comment]
It's been 6 years since this issue was documented, I'm running OpenEmu 2.3.3 and I can't start the game
