### ISSUE TITLE
Issue with Open Emu

### ISSUE THREAD

**Issue by chesterboy** [OpenEmu/OpenEmu#1904]
I have an issue with OpenEmu. The program opens okay and allows me to pick a game (i only use GBA really) however upon the game loading the keyboard controls become unresponsive to the game thus meaning I cannot play! does anyone know how to fix this, I have no clue on technical methods either!

**Comment by clobber** [comment]
Keyboard not working usually means another app is interfering with input (like google chrome, some third party input apps or a terminal, etc). Close apps until you find the problem. Reboot your machine and don't open anything but OpenEmu.

Also, please search for related issues before opening a new one. This has come up several times.

#798
