### ISSUE TITLE
open emu issue w/ ps1 games

### ISSUE THREAD

**Issue by deedeedaadaadoo** [OpenEmu/OpenEmu#1907]
so I've downloaded the experimental version, made sure the bios files are correct and have been put in the correct folder. however when i click on my PS1 game in the library nothing happens. no error messages, no black screen, no title screen just nothing. all other games i have play fine i.e. n64, gba, gbc, snes, etc.

please help me ={ i want to play some jrpgs lol

**Comment by deedeedaadaadoo** [comment]
4/23/15 10:37:03.332 AM OpenEmuHelperApp[573]: parent application is: OpenEmu
4/23/15 10:37:03.354 AM OpenEmuHelperApp[573]: Some shit about the game.
4/23/15 10:37:03.356 AM OpenEmuHelperApp[573]: ROM did not load.
4/23/15 10:37:03.357 AM OpenEmuHelperApp[573]: Deallocating proxy: <OEThreadProxy 0x7fed11e76e70, target: <MednafenGameCore: 0x7fed11e75ec0>>
4/23/15 10:37:03.357 AM OpenEmu[499]: Deallocating proxy: <OEThreadProxy 0x60000084b400, target: <OEGameDocument 0x6000001ba860, ROM: 'Spyro the Dragon', System: 'openemu.system.psx', Core: 'org.openemu.Mednafen'>>

**Comment by clobber** [comment]
Mednafen is still 'experimental' and people need to better understand how to use the BIOS files and load in games with cue sheets. The next version of OpenEmu will address this but for now all I can do is link you to these guides:

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cue-sheets-%E2%80%94%C2%A0loading-CD-based-games
