### ISSUE TITLE
suitable core...again

### ISSUE THREAD

**Issue by grande123** [OpenEmu/OpenEmu#1908]
Ya so basically I tried uninstalling and reinstalling openemu.  It didn't work. The sony playstation tab is on the left but I looked in preferences and I don't think I have the suitable core (at least thats what it tells me on the error message...).  Basically i need help getting the sony playstation core.  Also, I tried downloading the correct BIOS but it won't let me download the sony playstation bios package on theisozone.com for some reason it doesn't do anything or start downloading anything when i click on download file.

**Comment by kylewlacy** [comment]
Are you using the [experimental version](https://github.com/OpenEmu/OpenEmu/releases/download/v1.0.4/OpenEmu_1.0.4-experimental.zip) of OpenEmu? Mednafen (the PS1 core) is only available in the experimental releases for now.

**Comment by clobber** [comment]
#1905

**Comment by grande123** [comment]
yes i am using the experimental version.
