### ISSUE TITLE
"Stop Emulation" Doesn't Stop, and Can't Access Settings

### ISSUE THREAD

**Issue by Ragnarok345** [OpenEmu/OpenEmu#1909]
Ok, so two things. When I quit a game, no matter how I do it, it doesn't really exit the game. I've done all kinds of things. I've closed it with Cmd+W, the power button, Stop Emulation, Cmd+Q, and more. But the music keeps playing when I start a new game or close and re-open the window, or even the full application. It's incredibly annoying. It even happens-cross platform. And the other thing is that I can't hit the settings gear in the little toolbar at the bottom of the game window. I click on the gear, and it flashes up for a single instant, then vanishes. Doesn't let me insert Action Replay codes, or anything. Suggestions?

**Comment by clobber** [comment]
Please search for new issues before opening a new one.

#1676

**Comment by clobber** [comment]
Oh, and if you cannot access the HUD bar, sounds like you might be on 10.7 maybe? We won't be supporting that version of OS X anymore. Can you upgrade, if so?

**Comment by Ragnarok345** [comment]
Thank you, but I did search. Only found one other person that had this problem, and the suggested solution was stuff I'd done. And no, I'm the last person who would ever let my OS fall behind. I'm on 10.10.3.
