### ISSUE TITLE
Experimental, Playstation BIOS still needed even though they are in the BIOS folder

### ISSUE THREAD

**Issue by Dragonessa** [OpenEmu/OpenEmu#1912]
I have tried a million damn times to get this to work.
I did the whole thing where you get the BIOS for the Playstation and manually put them in the OpenEmu folder located in Application Support in a newly created BIOS folder. 
I have the Mednafen core installed. 
I still cannot open the game I am trying to play (Gex specifically) and it still says I need the three required bios (5001, 5002, etc). I have grabbed and renamed file after file, downloaded new BIOS... nothing. Nothing works. Please make a step by step process on how the hell to do this properly because clearly I'm doing something wrong.

**Comment by clobber** [comment]
> manually put them in the OpenEmu folder located in Application Support in a newly created BIOS folder

Who told you to do this? Not us. That is exactly what you **should not** do. The on-screen directions specifically say **"Drag and drop the required file(s) onto the game library window"**.

Mednafen/PSX emulation is still 'experimental' and people need to better understand how to use the BIOS files and load in games with cue sheets. The next version of OpenEmu will address this but for now all I can do is link you to these guides:

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cue-sheets-%E2%80%94%C2%A0loading-CD-based-games

**Comment by clobber** [comment]
Oh and there's also a thread here on our subreddit: http://www.reddit.com/r/OpenEmu/comments/2xfqc4/cant_run_psx_games/

**Comment by Dragonessa** [comment]
i followed a tutorial video on Youtube that said you had to rename certain files and drop them into the BIOS folder in the OpenEmu folder in app support. I did what the video said and I got the Medafen core to install and the Gex game shows up in the library. However I still get the errror popup that the bios files are needed when they are already there.

**Comment by clobber** [comment]
I can assure you that if you thoroughly read everything I've given you, that will resolve your problem. That is all the help I can offer you.

**Comment by Dragonessa** [comment]
I have read those things. I tried to drag and drop the BIOS files after getting rid of the BIOS folder and making a new empty one. Nothing happened even when I dragged + dropped. Could you please break down the process mentioned in those links because I am having trouble understanding it.

**Comment by Dragonessa** [comment]
As in, I tried to drag + drop the BIOS files into OpenEmu and nothing happened.

**Comment by clobber** [comment]
@Dragonessa knock it off with opening new tickets; you're not entitled to special 1-on-1 help here.

I suggested you read the guides, the reddit link I provided and also the on-screen directions. Either that, or you wait until the next version is released.

**Comment by Dragonessa** [comment]
@clobber I am only asking for help here. I do not appreciate being spoken to so rudely. I have read the BIOS guide, all it is is a list of hashes required for the specific BIOS files.  I read the reddit link and directions and followed them. It is still not working for me. Clearly whatever I am doing isn't working so that is why I am reaching out for assistance and asked for some steps on how to properly do this.

**Comment by clobber** [comment]
@Dragonessa Rude? Sorry, you definitely aren't getting any further help.
