### ISSUE TITLE
Experimental, Game still says Playstation BIOS files are needed for play even after drag and drop into OpenEMU

### ISSUE THREAD

**Issue by Dragonessa** [OpenEmu/OpenEmu#1913]
I have followed instructions given by Clobber in my prior ticket and I still cannot play Playstation games through OpenEMU. I renamed the required file and followed the instructions and even researched provided links from the subreddit. Nothing works. I even tried trashing and re-scanning the game to see if that was the issue and the pop-up saying the 5501, 5502, and 5500 bin files were required for gameplay appeared even after I dragged and dropped the BIOS files into OpenEMU. What is going on here? Can someone please do a step-by-step breakdown on how to get this to work because I am definitely missing something here.

**Comment by clobber** [comment]
#1912

**Comment by Dragonessa** [comment]
All I ask is for some help, and what you have provided for me helped only enough to get the core to install and the game I want to play to show up in the library. No matter how many times I've dragged the BIOS files into OpenEMU (after renaming the 7003.bin to the proper name) nothing ever happens and I get the popup saying the BIOS files are still needed. So obviously dragging and dropping isn't enough to get it to work.

**Comment by Dragonessa** [comment]
Actually nevermind, I got it to work on my own. Turns out I had to change the case of .bin from upper to lower and the PSX emulator of OpenEmu now works. I suggest making a note of that in the BIOS guide perhaps?

**Comment by cyco** [comment]
I added a little note to the guide.

**Comment by clobber** [comment]
@Dragonessa You have incredibly poor reading comprehension; your problems are your own.

Not only did you fail to read the guides, you didn't read a thing I told you. I noted that BIOS handling was still experimental and that these issues (such as file names) were addressed in the upcoming version.

**Comment by clobber** [comment]
Hell, if you had read the subreddit thread I linked (oooh but you swore you *did* read it!!! honest!), you would have even seen the note about lowercase filenames! Absolutely incredible.

**Comment by clobber** [comment]
Also I went back and checked version 1.0.4, because I thought this sounded fishy and verified it will import *any* legit BIOS file regardless of case:
* scph5500.BIN
* SCPH5501.bin
* SCPH5502.BIN

All import. On a case-insensitive file system (default on OS X), Mednafen will load the files in any case as well. So we don't need a note about cases; you've further exposed you just didn't want to read the help that was given you and expected somebody to hold your hand.

**Comment by cyco** [comment]
removed the note https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files/_history
