### ISSUE TITLE
Immediate crash on launch (newly installed)

### ISSUE THREAD

**Issue by Daniol71** [OpenEmu/OpenEmu#1914]
I just installed the latest version of OpenEmu (downloaded, opened with iZip and copied to Applications). When I try to open it, it crashes instantly, what could be the cause? I'm on Yosemite 10.10.3.

https://gist.github.com/71e9f68f99e3a4fa9382

I've provided the latest crash report and the log of OpenEmu events from Console. The Console log might not be of much use since I've tried some experimental versions of OpenEmu etc. to see if they would work, with no success. But the latest crash report is from the latest official version of OpenEmu available on the website.

I hope there is an easy solution,
Thanks, Daniel

**Comment by clobber** [comment]
Your application, iZip, is creating a corrupt binary. You need to extract with Archive Utility (built-in on OS X) or the defacto standard for other archive types, The Unarchiver (free on the mac app store https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12).
