### ISSUE TITLE
"An error occurred during persistent store migration"

### ISSUE THREAD

**Issue by afromagic918** [OpenEmu/OpenEmu#1915]
I re-downloaded OpenEmu as part of a project for school, and when I did, this message appeared. I've looked around for help regarding the issue and can't find anything satisfying or simple enough to follow. I have restarted and re-re-downloaded the program numerous times. Please help me, I was on the last dungeon of Zelda and now I'm pissed because I can't finish.

**Comment by cyco** [comment]
Hey, that message is related to the database openemu uses to keep track of your games. Do you remember which version you were using before download the app again?

The easiest way to fix the issue is to remove the OpenEmu directory in you Library's Application Support folder. Make sure to keep a backup! All your save games are in there!

**Comment by afromagic918** [comment]
Hey Chris!

I do not remember which version I was Singh, unfortunately. I downloaded it pretty close to the launch. 

And I'm sorry, but I'm not sure how to do that! I've seen these instructions before, but I don't know how to go about doing that!

**Comment by cyco** [comment]
Alright, here we go :)

First, activate Finder, open the go menu from the top menu bar and press the option button on you keyboard (looks like this http://upload.wikimedia.org/wikipedia/commons/5/51/Option-key.jpg). A wild menu item called 'Library' will appear, click it.

![library menu item](https://cloud.githubusercontent.com/assets/697021/7375039/2beca18c-edd6-11e4-997b-4080f8f0c457.png)
 
A new finder window opens. In that window double click the 'Application Support' folder to open it. Now look for a folder called 'OpenEmu' and drag it to your Desktop.
That's it. The next time you start OpenEmu it will create new Library and you can import your games and save states again by dragging the whole OpenEmu folder from you desktop onto OpenEmu's main window.

Let me know if this works for you.

**Comment by afromagic918** [comment]
Thanks Chris!!!

Bad news though, there is no OpenEmu folder in the App Support folder. This night be because I've deleted and redownloaded Emu a few times now.

**Comment by verysofttoiletpaper** [comment]
.

**Comment by SamJayne1974** [comment]
Hi- I'm having the same problem, I have a new version of the OpenEmu, have tried both the newest version and Experimental and same error. I had an older version but there is no OpenEmu in the Application Support folder. I have a file of roms that I've moved off the desktop, in case there would be a pathway issue. Why is the newest version giving me this error? any clues? I'm installing newest OS and restarting.

**Comment by 3297** [comment]
Hello - I've been having the same problem too! I think so at least... 

I have the newest version of OpenEmu, and I've checked the file in the OpenEmu. The Problem is though, that I may have accidentally deleted the entire folder of OpenEmu in the Apllication Support folder. Yeahhh.... please help, that would be great.

**Comment by 3297** [comment]
Here's a bit of an update- I got the folder back via my Time Capsule so now I'm at the same stage as the others ^

**Comment by clobber** [comment]
@3297 Cannot help you if you broke your install. Wipe everything and reinstall the application fresh.

**Comment by SamJayne1974** [comment]
i had to use an app cleaner to wipe all the files

On Sunday, February 14, 2016, clobber <notifications@github.com> wrote:

> Closed #1915 <https://github.com/OpenEmu/OpenEmu/issues/1915>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenEmu/OpenEmu/issues/1915#event-549984789>.
>


-- 
Music Party
Sam Jayne / LAL / Lync / etc
New Tracks Of Quality Website - www.tracksofquality.com
Sound Cloud - http://soundcloud.com/love-as-laughter
Love As Laughter bandcamp!  http://loveaslaughter.bandcamp.com/
