### ISSUE TITLE
Feature request: Able to change fast forward speed or slow normal speed down with button trigger

### ISSUE THREAD

**Issue by strashy** [OpenEmu/OpenEmu#1916]
I was so happy with fast forward function, until I realize that sometime, In my case, need to slow the normal speed down to be able to handle ridiculous hard games such as.

1. Final Fantasy IX: Jumping rope 1000 times (probably only few on Earth can make it to that crazy number)
2. Chrono Trigger: Three identical men - Biggs, Wedge, & Piette - come out on stage. They then walk around back and forth, mixing themselves up. Afterward, you will be asked to find one of the three at random. - this is a description from wikia (In this case, slow the game's speed down should be great)

Probably there'll be many more cases the slow down function proves useful.

**Comment by clobber** [comment]
#803
