### ISSUE TITLE
Using USB SNES controllers

### ISSUE THREAD

**Issue by Riley88** [OpenEmu/OpenEmu#1917]
Hi guys i've just recently downloaded openemu and am so happy to have this app to play some of the greatest games ever. Only issue is i cant use my usb snes controller as it doesnt map any of the buttons. I assume you have already answered this in previous posts but is there a way you could update this or is there a way around it? Thanks in advance

**Comment by sinkswim** [comment]
Can you provide more information of the controller you are using?
