### ISSUE TITLE
white 2 crash with open emu at drained house.

### ISSUE THREAD

**Issue by willkornreich** [OpenEmu/OpenEmu#1919]
every time i try to enter drained house my game crashes

**Comment by Judelaw22** [comment]
I am also stuck here and after a little searching there is supposedly no help.

**Comment by mrvacbob** [comment]
This is a DeSMuME issue, unless it doesn't occur there.

**Comment by willkornreich** [comment]
it doesn't bruh why would you close this

**Comment by clobber** [comment]
This is closed because its not our problem and it **does** happen in standalone Desmume with the JIT enabled. We have JIT enabled by default; standalone does not.

Sorry, nothing we can do about it.

**Comment by clobber** [comment]
Oh, and officially, Pokemon games are not supported in Desmume anyway according to their own FAQ/Policy: http://wiki.desmume.org/index.php?title=Faq#Why_can.27t_I_play_Pokemon_Diamond_.2F_Pearl_.2F_HeartGold_.2F_SoulSilver_.2F_Black_.2F_White_.3F_Why_aren.27t_they_supported.3F
