### ISSUE TITLE
New GLideN64 plugin for Mupen64Plus

### ISSUE THREAD

**Issue by andybrito** [OpenEmu/OpenEmu#1921]
I'm no expert in anything, but the new plugin released for the Mupen64Plus seems to be a significant improvement over what was being used previously :D 
Is there any chance of an update of the OE core anytime soon ? 

http://gliden64.blogspot.ru/2015/05/public-release-1.html

**Comment by clobber** [comment]
No, not soon. It will take significant work supporting that new plugin, if if we can, due to newer GL being used.

Closing because we're aware of it.
