### ISSUE TITLE
PSX Emulator launching BIOS main menu, not the actual game

### ISSUE THREAD

**Issue by OkazakiTheOtaku** [OpenEmu/OpenEmu#1923]
When loading a game in the PSX core, the emulator defaults to the BIOS's main menu, and there is no way to actually launch the game.

**Comment by clobber** [comment]
You have a bad dump of your game, nothing else I can tell you. PSX/CD system support will be more complete in our next release along with a troubleshooting guide that should cover most situations.

**Comment by OkazakiTheOtaku** [comment]
Alright, thank you for the reply.
