### ISSUE TITLE
OpenEmu support for X-arcade Tankstick?

### ISSUE THREAD

**Issue by miketatum** [OpenEmu/OpenEmu#1924]
The X-Arcade Tankstick is recognized as a keyboard, but not as a joystick. Any plans to add the tankstick as a default input?

**Comment by cyco** [comment]
Did you get it to work?

**Comment by miketatum** [comment]
Kind of. I was able to change the keyboard defaults, but still unable to get the trackball/paddles to work. But that appears to be a known issue, unless I missed a way to fix that somewhere.
