### ISSUE TITLE
I can't play using 3 controllers or more

### ISSUE THREAD

**Issue by rennerarruda** [OpenEmu/OpenEmu#1927]
I have 5 PS3 DualShock3 Controllers, and I sync them with my mac using bluetooth. So, I open the controller options in OpenEmu, changed the input of each Player with a Dualshock controller, and configured each controller to play Snes.

I tried to play Super Bomberman 3, 4, 5, and Tiny Toons Wacky Sports, but only 2 controllers are working in game. I couldn't activate the 3rd controller in game...

Anyone can help me?

Thanks!

**Comment by clobber** [comment]
#1149

**Comment by rennerarruda** [comment]
Ok. There is a release date of the next OpenEmu release?? Thanks!
