### ISSUE TITLE
Two PS3 controllers show up

### ISSUE THREAD

**Issue by ballo** [OpenEmu/OpenEmu#1928]
Hi. For some reason two ps3 controllers are available even though I only have one. Only the second controller works. Another SDL app, Mupen64 has the same issue. 

I'm not sure if this is a bug in the OS or SDL.

**Comment by clobber** [comment]
You're saying it happens with other applications so it appears to be a problem on your end. Our application doesn't use SDL, by the way.

**Comment by ballo** [comment]
I don't know what you mean by "my end". The only end which is mine are my thumbs. Maybe another ps3 controller user can chime in

**Comment by clobber** [comment]
Funny, but "your end" means your device, your machine, your configuration - and nothing to do with our application.

**Comment by ballo** [comment]
OK, I finally figured out the secret sauce, although it's still more Apple's end than mine.

If you disconnect the ps3 controller from USB and pair, only one controller device shows up. If you connect it to the USB port, a second non-functioning device with the exact same name shows up.

The solution I guess is to run the app before connecting the USB.
