### ISSUE TITLE
5200.rom Issue

### ISSUE THREAD

**Issue by juppaluri** [OpenEmu/OpenEmu#1933]
I am trying to play Pac-Man for the Atari 5200.  I found the dump and renamed it 5200.rom.  I dragged it on to the 5200 library window and nothing happened.  I still cannot play Pac-Man.  Can anyone help me?

**Comment by juppaluri** [comment]
Never mind I solved it myself.

**Comment by elpico99** [comment]
so what do you do i can't see my game there and i like to play oil's well
