### ISSUE TITLE
FDS Issue

### ISSUE THREAD

**Issue by juppaluri** [OpenEmu/OpenEmu#1934]
I was trying to play an FDS game called yume kojou doki doki panic (the game that Super mario bros 2 was based off of), and after the opening it says that I must switch to side B and then it take me back to the title screen and if I press start it does the cutscene again.  Does anyone know how this can be solved?

**Comment by clobber** [comment]
Check FDS control preferences for a key called 'Change Disk Side'. Press it when the game asks you to.
