### ISSUE TITLE
snes core issue

### ISSUE THREAD

**Issue by sunfoode** [OpenEmu/OpenEmu#1935]
After i upgrated openemu snes core, an issue occurred,  Fire Emblem menu  no longer displayed so perfect   
 as before,  it became very unclear ,  i regret so much, is there any way i can get the old snes9x 1.43 core back?
My English is poor, sorry!
![Uploading 27A792B3-3BC0-4D22-85A9-8A4466B60D7A.png…]()

**Comment by sunfoode** [comment]
![27a792b3-3bc0-4d22-85a9-8a4466b60d7a](https://cloud.githubusercontent.com/assets/10395368/7825472/d1980b4c-043f-11e5-973e-df8ad407aa55.png)

**Comment by clobber** [comment]
I'm not aware of any core changes to an SNES9x update we pushed out that would affect games. Our available core ports are from the same code they've always been.

**Comment by clobber** [comment]
For more accurate SNES emulation I would suggest using Higan instead.

**Comment by sunfoode** [comment]
Problem solved! I found the old version of snes9x core on the page about Snes9x-core Releases, downloaded the snes9x 1.53 oecoreplugin and replaced the core. It worked. Now i can  play fire emblem again. Thank you for keeping it available. And thank you for you kindness. By the way, I'm from China.

**Comment by clobber** [comment]
Okay...whatever you say. I'm telling you that SNES9x version is the exact same *core* code as whichever one you were previously using, unless you built from source. I'm assuming you had the one labeled "1.53.3"? The version bumps up until then were all related to fixing audio problems and enabling cheat support, so there cannot be any SNES9x *core* code that was affecting this. Something else was going on but I don't think we'll get to investigate.
