### ISSUE TITLE
Can't save PS1 games

### ISSUE THREAD

**Issue by gmt6bh** [OpenEmu/OpenEmu#1938]
I have been trying to save my file while playing Xenogears recently but had no luck. I have attempted to read up on how to get around this but considering it is a multiple disc game I am genuinely confused as I am not very tech savvy. I am using OpenEmu v1.0.4 experimental build and Mac OS X Yosemite v10.10.2 and have loaded all the BIOS files, so I can run the game just fine. I have checked the Library-application support-openemu-save files folder and can't find the PS1 folder as others have previously stated. I don't quite understand if the compiling multi-disc games option is currently available or not, if it is I would love to have that explained as well. I just want to be able to save my xenogears file so I can actually start playing it. Thanks.

**Comment by clobber** [comment]
I don't know anything about this particular game, but if you are talking about memory card saves, you just have to save in-game whenever a save opportunity presents itself - be it from a menu or save point, etc. If you are talking about save states, those are not yet supported until our next release.
