### ISSUE TITLE
Play Supermario kart on super nintendo in a public venue ?

### ISSUE THREAD

**Issue by jeremielondon** [OpenEmu/OpenEmu#1939]
Hello guys we would like to run a Super mario kart tournament in a bar. We would like to use open emu, do you know if you have to pay some liscencing ?

Best,

**Comment by clobber** [comment]
For OpenEmu? No.

For Mario Kart? I don't know, but I would suggest using a real SNES as a bar sounds like a bad place for a Mac to end up.
