### ISSUE TITLE
GBA wont play any games

### ISSUE THREAD

**Issue by jmufan97** [OpenEmu/OpenEmu#1945]
I have tried deleting my cores and reinstalling them and leaving out Higan, my roms are in .gba files, I've tried using an unzip app but when I try to play those zipped roms it makes the .gba files again. 
Macbook Air Mid 2013
OS X Yosemite
Version 10.10.3
Processor: 1.7 GHz Inter Core i7
Memory: 8 GB 1600 MHz DDR3
Here is a picture of my console app after trying to load games and it will not work. The Screen is just black and on occasion when I try to stop emulation the whole app will freeze and I need to force quit. 
![screen shot 2015-06-06 at 5 08 48 pm](https://cloud.githubusercontent.com/assets/12778908/8021497/ec8d37dc-0c6f-11e5-9c18-c8cc8b007b2f.png)

Just wondering if anybody else has any other solutions that I could use. I have looked through past cases of this happening and have tried some of those but nothing is seeming to work. Thank You

**Comment by clobber** [comment]
Not sure I'm clear on what's going on. Could you run through all of these steps first to sort of 'clean up' and then report back? https://github.com/OpenEmu/OpenEmu/issues/1460#issuecomment-46348553

**Comment by jmufan97** [comment]
I just deleted and reinstalled all my cores, restarted openemu, then went to play a GBA game and the screen is just black. 
![screen shot 2015-06-07 at 10 06 19 am](https://cloud.githubusercontent.com/assets/12778908/8024308/1de894c4-0cfd-11e5-8114-d40f45763925.png)

If you have any future steps for me to take to help please do.

**Comment by clobber** [comment]
I'm not sure you followed all the steps I linked you to. So if not, please do so.

Also try changing your filter in use to Nearest Neighbor.

**Comment by jmufan97** [comment]
Changing the filter worked. Thank you so much clobber!
