### ISSUE TITLE
Robocop vs Terminator textures disappear randomly on SNES Higan core.

### ISSUE THREAD

**Issue by aronkihui** [OpenEmu/OpenEmu#1946]
Well, with this core the game go much better than SNES9X which has sound issues. The problem is some block of textures disappear randomly and infrequently.

**Comment by aronkihui** [comment]
![robocop vs terminator](https://cloud.githubusercontent.com/assets/5703696/8021673/37621df4-0c7f-11e5-807c-e60c2d9018d2.png)
Here we have an example.

**Comment by mrvacbob** [comment]
OpenEmu won't be able to help you unless the problem doesn't occur in other Higan wrappers.

**Comment by clobber** [comment]
Yeah def SNES9x issue so we can't help you here. Just use Higan instead since it's more accurate.

**Comment by aronkihui** [comment]
In the title says "Robocop vs Termi..... SNES Higan core" XD so this issue happens running the HIGAN core no SNES9x.

**Comment by clobber** [comment]
Oh, right. We use the 'performance' profile for BSNES/Higan which has its own set of accuracy edge cases. Few examples with glitches or other problems being A.S.P. Air Strike Patrol, Mega Man X2/X3, Tetris Attack, some others. Looks like you found another. Either way, nothing can be done about this.
