### ISSUE TITLE
Keyboard will not work at all. 

### ISSUE THREAD

**Issue by joanagj** [OpenEmu/OpenEmu#1949]
No matter what I do, my keyboard will not work. I've tried reinstalling the program, deleting the games and reinstalling. Closing chrome. Nothing. None of my emulators work.

**Comment by clobber** [comment]
Keyboard not working usually means another app is interfering with input (like google chrome, some third party input apps or a terminal, etc). Close apps until you find the problem. Reboot your machine and don't open anything but OpenEmu.

Also, please search for related issues before opening a new one. This has come up a dozen times.

#798

**Comment by joanagj** [comment]
I did search for it and looked at the answers on other sites as well as this. Nothing is working, whatsoever. I have tried the deleting file method, as well as closing all applications and even suspending nearly everything on my activity monitor. Still no response. I've also had my ds emulator on openemu glitch and show the gba content as it glitch. I think there may be a problem with the emulator.
