### ISSUE TITLE
Unable to update/download cores

### ISSUE THREAD

**Issue by lfdmotta** [OpenEmu/OpenEmu#1950]
Hi,

I just downloaded OpenEmu, but I can't download any cores. When I try to update, it gives an error message: "An error occurred in retrieving update information.".

I found an old topic about a GitHub certificate problem, but I don't have such issue: no certificate is expired.

I added OpenEmu to Mac OS X firewall to allow all incoming connections. 

Any help?

Running OpenEmu v1.0.4 
Mac OS 10.10.3.

Thanks

**Comment by clobber** [comment]
This is a problem on your end. This error means that the updater cannot connect to where it needs to (GitHub) to check for updates and download cores. 

I'd suggest first deleting everything in your Cores folder ~/Library/Application Support/OpenEmu/Cores, if anything exists there, and then definitely wiping out your certs for GitHub even though you've said they are not expired.

That's all we can do for you.
