### ISSUE TITLE
Game preview / trailers

### ISSUE THREAD

**Issue by keniobats** [OpenEmu/OpenEmu#1951]
Hello, 

First of all, awesome work!, today I found this project and I'm so excited!.

I've been playing around a little with HyperSpin and something that I find really useful is the video game preview for some reasons:

* There's a lot of games(mostly from NES) that I love but can't recall due that I was a kid at that time.
* There's some games that would have more chances to be played only if people would be able to see what's about and that can be accomplished with a short preview video.
* It's just awesome :)

So the first thing that comes in mind is to create a youtube or vines(?) channel where collaborative video upload is allowed and start creating collections of videos for each platform.
That way users could click/select a game and automatically start the video preview from an online channel.

It's just a thought but I would love to see something like that!

Cheers! :)

**Comment by clobber** [comment]
This is far outside the scope of this project, so very unlikely.
