### ISSUE TITLE
Crash in control binding with Playstation 4 (PS4) controller

### ISSUE THREAD

**Issue by mipstian** [OpenEmu/OpenEmu#1953]
OpenEmu crashes whenever I try to bind anything to L2 or R2 in the Preferences window. The triggers work fine during emulation.

Here are the relevant (imo) log lines.

At launch:
````
2015-06-24 03:17:33.354 OpenEmu[13358:2706416] WARNING: There are 2 button elements unaccounted for.
````

And here's the crash:
````
2015-06-24 03:17:44.335 OpenEmu[13358:2706416] *** Assertion failure in -[OESystemBindings OE_playerBindings:didSetDeviceEvent:forKey:], /Users/.../OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemBindings.m:720
2015-06-24 03:17:44.336 OpenEmu[13358:2706416] Controller type 'OEControllerSonyPS4Dualshock4' does not recognize the event '<OEHIDEvent 0x608000067f80 pad=0x600000486e00 type=Button number=8 state=On 'Button 8' cookie=9>', when attempting to set the key with name: 'OENESButtonB'.
````

I've done some digging and it looks like the event received is for a button, but a trigger is (correctly) expected:
````
expected: <OEHIDEvent 0x608000862180 pad=0x0 type=Trigger axis=Ry direction=Pos value=0.000000 'Trigger Ry' cookie=22>
actual: <OEHIDEvent 0x60000086d080 pad=0x60000029d0b0 type=Button number=8 state=On 'Button 8' cookie=9>
````

This happens with both the current (1.0.4) release and a version built from source from master, checked out today.

I'm running 10.11 "El Capitan", so it might be a problem with Apple's driver sending bad events. Let me know if I'm reading this right, and I'll file a radar.

I don't have a Yosemite Mac available to test right now, but from the looks of it it should always crash there too, unless the problem is OS X itself.

**Comment by clobber** [comment]
There's been a strange problem with the DualShock 4 L2/R2 triggers where we had to make SystemBindings think its both a button and a trigger. Interesting that it now hits the assert on 10.11 though.

Can you try this? https://github.com/OpenEmu/OpenEmu/issues/867#issuecomment-84522301

**Comment by mipstian** [comment]
Yup, that did it!

Would that change hurt in cases where this bug doesn't happen? (wondering why that version isn't in master :)

**Comment by clobber** [comment]
Wanted to investigate it more since that doesn't make a lot of sense. Anyway, it's there now.

https://github.com/OpenEmu/OpenEmu/commit/f5d5f41f6584440a68857e0a9a3747cdfcf68a91

**Comment by mipstian** [comment]
Agreed, funky.

Happy to report that everything else works properly under 10.11!

Thanks!
