### ISSUE TITLE
Cannot clone due to submodules of picodrive not found. 

### ISSUE THREAD

**Issue by primalmotion** [OpenEmu/OpenEmu#1957]
The submodules contained in the `picodrive` submodule are pointing to unreachable repos.

I guess notaz has already moved his code to here: https://github.com/notaz.

It would be nice to update OpenEmu references to these repositories.

Thanks,

**Comment by clobber** [comment]
Nothing for us to "update". He has off-site submodule references, if you take a look: https://github.com/notaz/picodrive/tree/master/platform

His site hosting the repos may be down or he has moved them and yet to update his own submodule references. Not our problem though.

**Comment by primalmotion** [comment]
well I've built OpenEmu like 2 or 3 months ago, I had this issue. I tried again today, and I got the same issue. As of today it is not possible to do a git clone --recursive correctly. 

I had to do:

```diff
 [submodule "platform/libpicofe"]
        path = platform/libpicofe
-       url = git://notaz.gp2x.de/~notaz/libpicofe.git
+       url = https://github.com/notaz/libpicofe.git
 [submodule "cpu/cyclone"]
        path = cpu/cyclone
-       url = git://notaz.gp2x.de/~notaz/cyclone68000.git
+       url = https://github.com/notaz/cyclone68000.git
```

in the .gitmodules of picodrive. otherwise I just got some 404 errors

**Comment by primalmotion** [comment]
btw, awesome soft guys! thanks for it

**Comment by clobber** [comment]
Right, this should be reported upstream so notaz can fix it.
