### ISSUE TITLE
Save state profiles

### ISSUE THREAD

**Issue by wraybowling** [OpenEmu/OpenEmu#1958]
I'd like to suggest a way to put save states in "profiles" similar to the way NetFlix allows multiple profiles. One of the pains of console games throughout my entire life has been games that only have one "slot" to save the game on. My brother and I couldn't "pass over" a game until the other was finished. Those days have long passed, but they're being presented again with my girlfriend and I, and my brother and his son. Does anyone else yearn for this feature?

**Comment by clobber** [comment]
If one is using OpenEmu on the same machine and login, as many save states can be created as you want (HUD bar > Disk icon > Save Current Game) - with an enhanced Save State Manager coming in the next release. However, to have multiple 'profiles' for OpenEmu is really outside the scope of the project. Sorry.

**Comment by wraybowling** [comment]
Thanks for taking the time to write a response, @clobber. I'm a few months behind on initiatives with this project, so I didn't know about the save state manager coming. I'm all for solutions that don't solve for just one person's ailments. So I'll look forward to that. Again, thanks for writing back. I'll catch up on progress and see how I can help out with future releases. :)
