### ISSUE TITLE
m3u will not import into openemu sony playstation 

### ISSUE THREAD

**Issue by krazykamikaziee21** [OpenEmu/OpenEmu#1959]
Im trying to compile all cue sheet into a m3u for multi disc game for sony playstation core is mednafen 0.9.38.3. Ive reviewed all previous issues concerning multi disc issues and user guides for this and still when trying to add to openemu's library it won't scan the file and will not showup. All cue sheets done in plain text one sheet per line cue files load fine individually as well. Im not sure if maybe a certain encoding is needed or if i missed a step somewhere or maybe i have to disable a setting in openemu first. Im using Textmate for my editor any help would be much appreciated.
![Uploading Screen Shot 2015-06-27 at 10.53.17 PM.png…]()

**Comment by clobber** [comment]
The new CD guide was a little preemptive.The features for multi-disc support will be available in OpenEmu's next release, or one can check them out now if they compile everything from source.
