### ISSUE TITLE
Arcade games don't work 

### ISSUE THREAD

**Issue by bshizzle** [OpenEmu/OpenEmu#1960]
Other consoles seem to work fine. Just arcade (Capcom) I'm having trouble with. I'll double click and nothing will happen (no pop up, nothing):

6/29/15 12:22:42.641 AM OpenEmuHelperApp[11034]: parent application is: OpenEmu
6/29/15 12:22:42.689 AM OpenEmuHelperApp[11034]: Some shit about the game.
6/29/15 12:22:42.697 AM OpenEmuHelperApp[11034]: ROM did not load.
6/29/15 12:22:42.697 AM OpenEmuHelperApp[11034]: Deallocating proxy: < OEThreadProxy 0x7fb803e0db10, target: < MAMEGameCore: 0x7fb803e0d180>>
6/29/15 12:22:42.697 AM OpenEmu[10812]: Deallocating proxy: < OEThreadProxy 0x6080002551e0, target: < OEGameDocument 0x6100001acbe0, ROM: 'Marvel Vs Capcom', System: 'openemu.system.arcade', Core: 'org.openemu.MAME'>>

Any help much appreciated

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/1445#issuecomment-46265285
