### ISSUE TITLE
Montezuma's Revenge doesn't work

### ISSUE THREAD

**Issue by ddbehsnilian** [OpenEmu/OpenEmu#1961]
Hi, I'm running the latest experimental build v1.0.4 (554-gf588330-Release) with some colecovision roms. They all run flawlessly, except Montezuma's Revenge which, for some reason, can't get past the title screen. I know the rom works because I tested it with other emulators. Are there any other Colecovision cores that I can try with?

**Comment by clobber** [comment]
We aren't responsible for games not working correctly because we don't develop the emulators. This bug has been fixed upstream in the emulator we use for ColecoVision games, CrabEmu, and will be pushed out in a core update for the next release of OpenEmu.

**Comment by ddbehsnilian** [comment]
Thank you for the quick reply! I realize you're not responsible for the actual emulators, and I do appreciate the work you are doing. So much so that I would like to donate some money to your team if you accept donations. OpenEmu has taken me back to my childhood years and in an great Apple-esque way. I am an Apple Certified Trainer, so I find that part awesome, how the library is organized and managed. I enjoy the filters very much and would love to see more options in the future. Also is there a place for feature requests? Sorry I am a Github noob. I'd love to suggest creating smart albums and setting the library location without actually moving anything (I keep mine synced via Dropbox). Thanks again!
