### ISSUE TITLE
Sega cd bios giving me trouble in Open Emu

### ISSUE THREAD

**Issue by Therealmadkong** [OpenEmu/OpenEmu#1964]
I have been going at this for over an hour and am almost done, but something went wrong with downloading the bios.  I downloaded the bios for Japan, Usa, and Europe from Emuparadise.  I wrote them into the .bin format like stated in the guide https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files.  It started to work, but went to issue section asking how to import.  I just check them and said import, but it only said for Atari 2600, Genesis, and another section that was not Sega CD.  So when the bios were downloaded they were put in the Atari 2600 section.  I clicked on the Bios of all three and they all gave me the sega cd start up screen for when you have no disc in the system.  The Bios did not have the right md5 when I checked, but no site I say had right md5.  I download the Bios from 9 websites and all gave me the same md5 that is different from the one stated in the guide.  The only site I have not looked at is romhustler, this is the recommended on by youtube guides, because it will not download to Mac OS X 1.75 version and needs Mac OS X 1.80.  So what should I do the fix this, I am really confused and the game I am trying to play Snatcher as the .cue file type and game cover, so it should work.  It keeps giving me this message though.  
![image](https://cloud.githubusercontent.com/assets/13167865/8501997/f6b70c92-215f-11e5-9d46-97488ebafcc9.png)

**Comment by clobber** [comment]
> The Bios did not have the right md5 when I checked, but no site I say had right md5

Sorry, you will need to find the correct ones or wait until next release when our bios/system file handling is improved.

I really don't follow what you are doing, but you need to actually **unzip** these files if you haven't first. Once extracted, you should also properly rename them by right clicking on the file and selecting Get Info, then going to "Name & Extension" and change the name to match what OpenEmu is looking for. Only then can you import them correctly by drag and drop.

Also, please stop mentioning the sites you have downloaded these files from. We cannot help you find these.
