### ISSUE TITLE
Saturn bin/cue not importing. saturn support?

### ISSUE THREAD

**Issue by ngude** [OpenEmu/OpenEmu#1965]
I'm currently trying to import a bin/cue of Shining Force III for Saturn that simply won't import. the cue is correct and file names/extensions match (triple checked), saturn core installed and active.

i looked at https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games and don't see any mention of saturn under the 'supported formats'

i'm presently a version of the experimental build that @clobber graciously uploaded here: https://github.com/OpenEmu/OpenEmu/issues/1952#issuecomment-113843998

i've also switched back to the website release of the experimental build to see if that had anything to do with it, but no success. currently back on the version linked above.

also just tried loading a different CD based game (playstation) just to see if cue importing still works and it does. seems to be isolated to saturn.

thanks and happy 4th of july!

also: can i import mdf/mds format? or do i need to make a cue pointing to the mdf file?

**Comment by clobber** [comment]
cue+bin imports just fine for that system. How are you sure the cue sheet is correct? Did you open it up in a plain text editor to verify? Paste the contents and all the filenames for your game back here.

mdf+mds importing not supported, yet.

**Comment by ngude** [comment]
here are contents of cue file as copied from textedit in plain text mode:

FILE "Shining Force III (U)(Saturn).bin” BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 23:14:14

file names are as follows:
Shining Force III (U)(Saturn).bin
Shining Force III (U)(Saturn).cue

with regards to mdf+mds, how do you recommend i convert them into a format that openemu is happy with?

**Comment by ngude** [comment]
update: i managed to find another image of a different saturn game that was packaged bin/cue

it seems many of these are mdf+mds.

anyway, the other game (die hard arcade) imported just fine!

so there must be something wrong with this dump of shining force. feel free to close this! thanks again for the quick reply.

**Comment by clobber** [comment]
That appears to be a bad dump of the game, it doesn't contain the disc header it is supposed to have so OpenEmu cannot identify it. Example of the header here: http://redump.org/disc/20315/

![screen shot 2015-07-04 at 1 44 05 pm](https://cloud.githubusercontent.com/assets/1303132/8509062/dd26b072-2252-11e5-8afc-df02534a69a3.png)

Using a hex editor (such as Hex Fiend) you could maybe place the correct header in there where the empty bytes are just find another dump of the game.

As for mdf+mds, I don't have a solution for you but I plan to add support for importing those at some point.

**Comment by ngude** [comment]
helpful as always, thanks @clobber

**Comment by feanvilo** [comment]
you can rename .mdf to .iso and you only need the cuesheet for the game
