### ISSUE TITLE
Organizational Concerns

### ISSUE THREAD

**Issue by johnnyyy29** [OpenEmu/OpenEmu#1968]
I'm not sure what this website is but I just made an account to hopefully get an  developer to implement some things.

OpenEmu is amazing and gotten me back into roms. It's obviously inspired by iTunes which allows us to have a library of neat and organized music. I think that OpenEmu should take two key things from the way iTunes work to smoothen out some edges.

1. When you attach artwork to a music file in iTunes, the artwork actually attaches DIRECTLY to the file in your system. This is true regarding the latest update I've made to my artwork. Therefore, if I deleted my file and decided to drag it back into iTunes at a later time, it would have the very last artwork I've attached to it. After inspecting the internal files of OpenEmu, I've noticed the artwork is kept in a separate folder and when I look at a rom's file, all I see for the thumbnail is a "black exec" icon or a "blank white document". I suggest you make it like iTunes to where if I looked at the internal file for Star Fox, I see a thumbnail of the artwork I attached in OpenEmu. Possible?

2. It seems like sometimes OpenEmu doesn't sort my new rom's until I've restarted it. Then when I do, they are sorted alphabetically. I just feel like there should be sorting options for any major organizational app. Name, Date, Publisher, etc. Then again, I guess we need a way to add dates and publishers first lol

Awesome...app? Whatever it's called I'm in love with it.

**Comment by clobber** [comment]
1. No.

2. This really falls under another ticket, so please search for related issues before opening a new one.

#664
