### ISSUE TITLE
Automatic Save State Regeneration

### ISSUE THREAD

**Issue by johnnyyy29** [OpenEmu/OpenEmu#1969]
When I manually delete an automatic save state from the internal folders and I restart OpenEmu and click that game, it crashes if I select “yes, start from where I left off”. However if I click no and start, I expect it to create a new automatic save state since the other one is deleted. It does not do this.

Easy to replicate and understand what I'm talking about...easy to fix? I just want to be able to manually delete my save files at any time without troubles.

**Comment by clobber** [comment]
> I just want to be able to manually delete my save files at any time without troubles.

That isn't possible. Next version contains a proper save state manager. In the mean time, you can hold option over the save state in the HUD bar menu to delete it.

You're getting deep into the internal folders and there is no reason for you to be in there to 'manage' files.
