### ISSUE TITLE
OpenEmu not installing cores

### ISSUE THREAD

**Issue by samburhan** [OpenEmu/OpenEmu#1972]
yesterday i deleted all of the files for OpenEmu i could find on my mac in order to reinstall it (because i was getting an error and thought it would fix it). i reinstalled it but when i tried to play a game another error "The operation couldn’t be completed. OpenEmu could not find a Core to launch the game" started happening. i tried to reinstall the cores but it just wont work. does anyone know how to fix this? thanks!

**Comment by clobber** [comment]
Seems your machine is rejecting GitHub's SSL certificate. See here:
http://superuser.com/questions/605900/why-wont-os-x-trust-githubs-ssl-certificate (or perhaps here https://blog.digicert.com/expired-intermediate-certificate/)
