### ISSUE TITLE
save (not save sate) directory

### ISSUE THREAD

**Issue by yuliywalsh** [OpenEmu/OpenEmu#1973]
Is it possible to change a save file directory? I am using gba4ios and I would like to change from default save file directory to the same as my gba4ios is using (dropbox). I want all my save data to be synchronised throughout all my devices. .oesavestate is obviously only recognisable by OpenEmu, where as .sav can be used in any other emulators on any other device. Any help please?

**Comment by cyco** [comment]
Sorry, at the moment there's no way to change the battery save directory. We'd also have to change some other things to enable syncing battery saves between emulators as openemu loads up auto save states by default and those don't load in-game saves from the directory.
