### ISSUE TITLE
i don't have any cores in OpenEmu

### ISSUE THREAD

**Issue by half0321** [OpenEmu/OpenEmu#1974]
I check the Preference>Cores and there were nothing. Also if I try to play some games it say "The operation couldn't be completed. OpenEmu could not find a Core to launch the game make sure your internet connection is active and download a suitable core." What's wrong with me? How can i fix this

**Comment by clobber** [comment]
Seems your machine is rejecting GitHub's SSL certificate. See here:
http://superuser.com/questions/605900/why-wont-os-x-trust-githubs-ssl-certificate (or perhaps here https://blog.digicert.com/expired-intermediate-certificate/)
