### ISSUE TITLE
Vectrex games report "null" error

### ISSUE THREAD

**Issue by wraybowling** [OpenEmu/OpenEmu#1975]
Imediately after importing a vectrex rom, a dialog "Do you want to run the game" appears. If "yes" is clicked, the following dialog appears.

"The game '(null)' could not be started because a rom file could not be found. Do you want to locate it?"

![screen shot 2015-07-10 at 11 19 34 am](https://cloud.githubusercontent.com/assets/1120619/8621837/cd419f58-26f5-11e5-949e-d5fbbfd08d47.png)

Running the roms without the dialog after import yields nothing.

There is a vectrex bios floating around out there, but it's not listed on the BIOS documentation page as required https://github.com/OpenEmu/OpenEmu/wiki/User-guide%3A-BIOS-files

The same roms are loading fine in VecX

**Comment by clobber** [comment]
I think this is an import bug in 1.0.4 with importing games from double clicking in Finder. Should already be fixed in source, so it'll be available in the next release.

You should just import games by drag and dropping the ROMs into the library window.
