### ISSUE TITLE
PS2 emulator Play!

### ISSUE THREAD

**Issue by bellinger61** [OpenEmu/OpenEmu#1976]
Not so much an issue but a question. PCSX2 seems to have stagnated with it's OSX development. Play! on the other hand seems to be making steady progress for all platforms OSX included. What if any chance in the new future would there be to create a PS2 core utilizing play?

**Comment by clobber** [comment]
PS2 is already on the 'wish list' and core ports are not planned.

**Comment by bellinger61** [comment]
Thank you for taking the time to reply. Hopefully we'll see PS2 as part of openemu in the future!!
