### ISSUE TITLE
Odd font colour on Yosemite

### ISSUE THREAD

**Issue by IngwiePhoenix** [OpenEmu/OpenEmu#1979]
In the latest release, 1.0.4, I have a rather odd-looking font. It should be white, but it is black instead?

https://www.dropbox.com/s/mibf5ra5sd8zx5g/Screenshot%202015-07-16%2016.01.57.png?dl=0

I see that there are a lot of recent commits. Wouldnt a new release be a good idea since the last one is from 2014?

**Comment by cyco** [comment]
We messed up when we released 1.0.4. The sidebar is supposed to show some nice icons and proper fonts but the translated versions of some files are corrupted. We've fixed this long ago and yes, a new version should be released soonish.

**Comment by IngwiePhoenix** [comment]
Nice!

For the meantime, can you give me a rough hint on how to compile it on my own? When I navigated into the OpenEmu folder and ran xcodebuild, it halted at an error. Something tells me I need some dependencies first. Can you tell me which ones - or, what I do need in general to compile it over here?

**Comment by IngwiePhoenix** [comment]
Nevermind - i oversaw the XCode Workspace. I am building off that now. I...really rarely use XCode. But could you maybe tell me how to make it do a Release build instead of Debug?

**Comment by clobber** [comment]
@IngwiePhoenix You could either wait until next release, or you could search the issues and find a couple solutions in #1636

**Comment by IngwiePhoenix** [comment]
Thanks. I am just trying to get the PPSSPP core to work. Whilst anything else is an `.oesystemplugin`, that one is a `.oecoreplugin`. And it turns out it has barely any similarities to the other bundle's structure. Oh well. Looks like I have to use PPSSPP separately still for a while.

**Comment by mrvacbob** [comment]
There's a "system plugin" for PSP and a "core plugin" for PPSSPP specifically. 'xcodebuild -scheme "Build All + Experimental" -configuration Release' or something like that ought to do it.

**Comment by IngwiePhoenix** [comment]
Using "Build All" or "Build All + Experimental" results in an error of 33 duplicate symbols, all being prefixed with `vorbis_`. I have tried that already, but sadly to no avail...
