### ISSUE TITLE
Support for Retroachievements

### ISSUE THREAD

**Issue by antoniordo** [OpenEmu/OpenEmu#1980]
Is possible to support for Retroachievements via http://retroachievements.org?

**Comment by clobber** [comment]
No, sorry.

**Comment by CokeGuitarist** [comment]
@clobber , why don't you want to support retroachievements? This feature is just great and many people love it as it makes replaying old games much more valuable. Technically it should be possible to integrate it in the systems. Just take a look at recalboxOS for example. An integration like that would be just awesome and I'm speaking for many many people I guess. 
Besides that openemu is a great project. Please keep on improving it ;)

**Comment by drcreek** [comment]
While I love the idea, I can see why not. I'm guessing it would require ripping out and rebuilding some cores from scratch. If not that, it would still be a massive undertaking for a relatively niche feature. Would be neat though.
