### ISSUE TITLE
Error building Openemu. No cores

### ISSUE THREAD

**Issue by tatundria** [OpenEmu/OpenEmu#1981]
When I try to build OpenEmu with xcode I get "build failed". After I clone Openemu on desktop with github, there are no files in the cores folders. I mean, every core folder is empty and I think that is the main reason of the failure.  Any fix for this?

**Comment by clobber** [comment]
Follow the guide. All the submodules must be cloned.

https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide
