### ISSUE TITLE
keyboard doesnt work with quitting every app

### ISSUE THREAD

**Issue by guenney** [OpenEmu/OpenEmu#1982]
hello, keyboard input of open emu doesnt work, i'm running with mac os x yosemite and after quitting every application, keyboard doesnt work either, can someone help me? 
also can't find default.oebindings folder, because no openemu folder in my application support.
please help me, thanks a lot

**Comment by clobber** [comment]
This comes up from time to time. You will find help by going through some of the older related issues: 

https://github.com/OpenEmu/OpenEmu/search?q=keyboard+not+working&type=Issues&utf8=%E2%9C%93

**Comment by guenney** [comment]
sorry, my fault - had the yosemite beta version running ..... SORRY
