### ISSUE TITLE
How do I add .cg shaders to the compile?

### ISSUE THREAD

**Issue by superrune** [OpenEmu/OpenEmu#1983]
Sorry for the probably amateur question, but how can I add .cg shaders to openEmu? Can I just dump them into the folder, and then build a new version, or do they have to be referenced in from somewhere in the code? There are some amazing new viewport shaders being dicussed here: http://filthypants.blogspot.no/2015/04/more-crt-shaders.html that I would love to see in openEmu!

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Filters

Not all shaders from that spec are supported with OpenEmu.

**Comment by superrune** [comment]
Cool, thanks! I'll play around and see what happens. Are shaders with textures supported?
