### ISSUE TITLE
How can i change disk on playstation emu

### ISSUE THREAD

**Issue by erobles396010** [OpenEmu/OpenEmu#1984]
I am curently playing metal gear solid 1 on the ps1 emulator but when it ask me to put in disk 2 idk how to change it can anybody help

**Comment by katanagari7c1** [comment]
I've had the same problem with the same game. :)
Multi disk games will be supported in the next release. Until then you can compile the latest version  available from the sources.

See ticket #1068 for a longer discussion about this.

**Comment by erobles396010** [comment]
i went to ticket #1068 and it says to make a m3u file and then that will make the game work but im not sure how to do that i create one but it does not copy to open emu
