### ISSUE TITLE
Codes/Cheats do not work on NDS

### ISSUE THREAD

**Issue by guenney** [OpenEmu/OpenEmu#1985]
I tried any variation of using codes on NDS.
Seemed to do nothing at all. But I know they worked, because I used them a long time ago...
What's the problem? I don't know...
Thanks for help..

**Comment by cyco** [comment]
Hey there,
did you take a look at the user guide? Maybe it helps https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes
Let me know if this works for you.

**Comment by guenney** [comment]
Yes, looked up for that, also didn't work at all..
Maybe I'm doing something wrong, but I checked every thing I think, do not find the problem...

**Comment by guenney** [comment]
So I tried many Codes now, no one works. I tried it on different games, nothing happened. Tried it on Desmume itself, didn't work. Is there a problem with yosemite? I'm running with MacBook Pro Retina End 2013, Yosemite 10.10.5.
