### ISSUE TITLE
github "Clone in desktop" not downloading cores

### ISSUE THREAD

**Issue by tatundria** [OpenEmu/OpenEmu#1989]
Why is github not downloading cores after selecting "clone in desktop"? core folders are empty. I've tried this several times...

**Comment by clobber** [comment]
It's almost like you've refused to read the guide linked from your last issue you opened.

#1981

**Comment by tatundria** [comment]
I did not clone OpenEmu from the command line. Do I still have to clone every core even when I use the github app?

Thanks in advance!
