### ISSUE TITLE
Githube submodules

### ISSUE THREAD

**Issue by tatundria** [OpenEmu/OpenEmu#1990]
Please I need help. I have already read the guide but I can't find a solution. How can I configure github for mac to clone the whole Openemu git with all the submodules? Because everytime I clone it I find that the core folders are empty. Please help me! Thanks!

**Comment by clobber** [comment]
Please **stop** opening up new issues for this. The issues are for bug reports with the application, not your inability to clone some git repos. This is not your personal help center for using git.

There is a wiki guide with multiple methods and if you cannot follow them, then sorry but it seems that compiling from source is just not possible for you

Thanks!

#1981
