### ISSUE TITLE
Psx games with Subchannel data

### ISSUE THREAD

**Issue by Anubix88** [OpenEmu/OpenEmu#1991]
Hello,
I've imported some psx games in the experimental version and noticed that games like Dino Crisis and Resident Evil 3 stucks on the "gore and violence" screen. In another emulator everithing works well because I think it does "reads" the subchannel data. I have cue/img/ccd/sub disc and it seems that openemu ignore the ".sub" file... will this be solved in the next update?
Also, I had problem importing ccd games, since OpenEmu just ignore them, I had to make a .cue file for each .img and still have some trouble.

Thank You and keep up the great work! (y)

**Comment by clobber** [comment]
Yes, ccd can be used in the next update.
