### ISSUE TITLE
Pokémon SoulSilver white screen (top and bottom) | "Couldn't communicate with a helper application"

### ISSUE THREAD

**Issue by annytheturtle** [OpenEmu/OpenEmu#1992]
My Pokémon SoulSilver game was working just fine but when I pressed the power button on the HUD to return to my games and then later on went back to it, the game wouldn't load and I'd be left with a white screen both on the top and bottom "screens".

When I close the window an error message pops up saying "Couldn't communicate with a helper application." I've tried restarting my computer and Openemu but the white screen won't go away.

I've opened the other games I have in my library and they all work fine, it's only SoulSilver that has this problem. I JUST caught a legendary and I'm annoyed (and angry) that this is happening, does anyone know how to fix this? Thanks.

**Comment by clobber** [comment]
This is a bug with Desmume using the JIT. Sorry, nothing can be done about it. I'd recommend using standalone Desmume which has the JIT off by default.
