### ISSUE TITLE
CCD+IMG+SUB Not Importing

### ISSUE THREAD

**Issue by AugDaug** [OpenEmu/OpenEmu#1994]
Hi Guys--

I'm running v1.0.4 on a 2009 Yosemite Mac Pro. OpenEMU is (obviously) freaking awesome, and I've never had any issues with any of the older 8bit/16bit consoles-- but I decided to try some CD-based PS1 (Playstation) games. I got the BIOS thing sorted out, and games with a CUE file work just fine, but I can't get the ones with CCD (a CCD+IMG+SUB bundle) to work. According to this OpenEMU help doc:

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games

They should work, but when I drag/drop nothing happens. When I try to open a CCD file from the app, it's just grayed out. Any Suggestions?

Thanks for creating such an AWESOME app!

PS:
The above has been my test environment, but I'd eventually like to get OpenEMU running PS1 games on my living room 2009 MountainLion Mac Mini.. I'm assuming there would be no diff between these environments for OpenEMU, but just thought I'd mention it.

**Comment by clobber** [comment]
CCD importing will be in the next release.

**Comment by AugDaug** [comment]
Wow, thanks for the quick response, clobber!

Is there any ETA on the next release?

Thanks again =)
