### ISSUE TITLE
Keyboard refuses to work

### ISSUE THREAD

**Issue by thecubanguyy** [OpenEmu/OpenEmu#1999]
The keyboard refuses to work. I cant play any of the games and I cant change the joystick settings in the preferences. I looked through all the forums about this same issue that came up through google search and non of them worked out the issue. 

Im running a brand new Macbook Pro 15" if it matters to state that

**Comment by clobber** [comment]
All of the other closed issues with this same problem are relevant to yours: another application is interfering with input. Close everything down and restart your machine until you find the one. I've run OpenEmu on "brand new" hardware and clean installs of OS X without issue.

That's all we can do for you.
