### ISSUE TITLE
(10.11 beta) Crash on create or change library

### ISSUE THREAD

**Issue by cedwardsmedia** [OpenEmu/OpenEmu#2000]
When attempting to create a new library or change to an existing library on OS X 10.11 El Capitan, a segmentation fault occurs, terminating the process and rendering OpenEMU unusable with a library anywhere except the default location. This is a problem for users like myself who store their libraries on the network rather than the local machine. This setup worked on Yosemite without problem and should work on El Capitan without problem - once this segfault is corrected. I have posted a copy of the crash report to [this gist](https://gist.github.com/cedwardsmedia/4640623dea7812270fd6).

**Comment by loicloic** [comment]
Like #1993, I confirm this does happen under the latest El Capitan DP with OpenEmu 1.0.4 as well, it does not crash with a build of the current repo version (912-g476ae22-Release, no change, built against 10.10 SDK).

As such I'm closing this issue as it is more than likely to be fixed in OpenEmu 1.0.5

**Comment by DenimTornado** [comment]
When is 1.0.5? For some reason i can't build app from repo.

**Comment by cedwardsmedia** [comment]
@DenimTornado have you followed the directions at https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide ? Specifically, did you initialize the submodules via ```git submodule update --recursive --init```? If not, you will definitely get compile errors because the required files will not be found. I suggest doing another pull of the repo to ensure you're up-to-date, then run ```git submodule update --recursive``` to make sure the submodules are up-to-date as well. Then try building again.

I had the same problem once before and that was why. The main repo was up-to-date but the submodules were not, so files were missing and the compiler chewed me out. :D

**Comment by DenimTornado** [comment]
@cedwardsmedia yeah! Thank you very much! I built it with your advice! Happy like an elephant.

**Comment by cedwardsmedia** [comment]
Glad it worked. Happy to help. I had the same issue and finally figured it out so I assumed that was your issue too. :)

**Comment by jurassicjordan** [comment]
Freezes every time I try to relocate my library! Please fix before Christmas
