### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by dylanmerte** [OpenEmu/OpenEmu#2002]
I downloaded OpenEmu version 1.0.3 and was playing games for about an hour with no problems, then updated to 1.0.4, and had no sound at all from that point on.

How can I fix this?? I already tried to reinstall it, I deleted all files and started from scratch, and still did not fix the problem.

**Comment by clobber** [comment]
That sounds rather incredible to me. Did you try checking if the volume in-app is turned down or muted via the HUD bar?

**Comment by dylanmerte** [comment]
Yeah I made sure all volume levels are definitely up.

**Comment by dylanmerte** [comment]
Send problem fixed itself after doing a computer restart, still don't know why I completely lost sound in the first place though, might want to look into that bug.
