### ISSUE TITLE
Consider adding cover art for independently-made games

### ISSUE THREAD

**Issue by alexchandel** [OpenEmu/OpenEmu#2003]
For example the infamous Kaizo Mario World 1/2/3. Even when loading a no-intro ROM, where OpenEmu finds cover art for the original no-intro SMW ROM, the Kaizos aren't given any art. This might involve choosing images from the games, if no-one has made cover art for them (not my knowledge), or applying someone's artistic talents to make cover art.

**Comment by clobber** [comment]
Nah. The database in use only tracks retail games - not ROM hacks or anything else like that.

**Comment by alexchandel** [comment]
I know. I'm proposing to expand on it.

**Comment by clobber** [comment]
Yep, and I said that isn't happening.

**Comment by alexchandel** [comment]
why not? this is a legitimate issue.

**Comment by clobber** [comment]
> legitimate issue.

No, it isn't.
