### ISSUE TITLE
SABR Filter Frame Drop On Fullscreen PSX

### ISSUE THREAD

**Issue by asoksevil** [OpenEmu/OpenEmu#2006]
I get a massive frame drop with SABR filter when playing fullscreen as opposed as having on 3x Windowed mode. Is this normal? My specs: 2010 MacBook Air Intel Core 2 Duo 1.86 GHz, 4 GB RAM, 128 GB SSD.

PSP games with SABR filter works flawlessly but PSX games don´t...

Any other way to speed up/optimize the emulator?
Thanks!

**Comment by clobber** [comment]
> Any other way to speed up/optimize the emulator

Nope. The emulator (and shader) is very resource intensive so I'd suggest not using that shader when playing PSX games.

**Comment by asoksevil** [comment]
Thanks for the fast reply @clobber 

I remember using SABR once without getting any frame drop at all... how is it that I can actually play it on a Windowed mode at full speed but it becomes unplayable on fullscreen?

Also, I do not experience this using the PSP emulator, could it be a matter of the emulators themselves?

**Comment by mrvacbob** [comment]
The PSP core is more efficient than the PSX core.

I wouldn't expect windowed to be faster than fullscreen though, that could be some system issue (like the game core rendering being deprioritized because it's not "the fullscreen app"). If you can figure out how to collect a spindump with a fullscreen app running, that would be helpful.

**Comment by asoksevil** [comment]
@mrvacbob 

Thanks the help!

I am not too savvy regarding this could you please walk me through it?

I went ahead and tried this with different games and it seems that it´s the emulator itself, not the games (I thought Xenogears could be very resource hungry).

I swear I saw it working flawlessly fullscreen.

**Comment by asoksevil** [comment]
@mrvacbob 

Got the spin dump files here.

This is windowed: https://paste.ee/r/J0XDb
Fullscreen: https://paste.ee/r/6eyLU

I have also made some discoveries... it seems that when you are gaming on a separate window, you get a better performance as opposed as having it embedded with the main window. (I have managed to let it run lag-free but it isn´t working now).
