### ISSUE TITLE
No games will run. Period

### ISSUE THREAD

**Issue by someonekillme** [OpenEmu/OpenEmu#2007]
I'm running 1.0.4 on 10.10.4  New style mac Pro.  Tried all sorts of stuff from reinstalling and deleting everything to changing the location of the files.  Nothing.  When i start a game nothing happens.  A process names OpenEmuHelperApp starts but does nothing.  Please Help.
![screen shot 2015-08-03 at 10 13 12 pm](https://cloud.githubusercontent.com/assets/8240759/9051742/f38f492c-3a2c-11e5-8f32-0307789f33f5.png)

**Comment by mrvacbob** [comment]
Please attach the output from Console.app.

**Comment by clobber** [comment]
Closing, no additional info. Probably a permissions thing with the XPC helper app.
