### ISSUE TITLE
Feature request: Big Picture Mode or mapping Restart System to a button.

### ISSUE THREAD

**Issue by ddbehsnilian** [OpenEmu/OpenEmu#2009]
Hi, I've been enjoying OE with a PS4 gamepad, but I find it awkward to switch back and forth between mouse and gamepad. It would be awesome if the whole UI could be controlled with the gamepad, similarly to what Steam does with Big Picture Mode.

Since this is a lot to ask, as a Plan B, I would like to request something simpler, the ability to map the Restart System command to a button on the gamepad. I imagine this could be done in the controller configuration preferences.

Thank you for all your continued hard work!

**Comment by clobber** [comment]
Please search for related issues before opening a new one.

#401

#1443

**Comment by ddbehsnilian** [comment]
Thanks, I did search, apparently not thoroughly enough
