### ISSUE TITLE
f.lux: OpenEmu crash

### ISSUE THREAD

**Issue by JakeJet** [OpenEmu/OpenEmu#2011]
Hey I've been trying to play some games lately and OpenEmu has been crashing pretty consistently. I couldn't figure out the issue and thought I would ask for help here. Thank you in advance. 
Here is the Crash Report
http://pastebin.com/XA8D90ra

**Comment by ryanorendorff** [comment]
I am also experiencing this problem while running the DS core. I have not experienced it with another core yet, although those games were also shorter (less than four hours).

**Comment by mrvacbob** [comment]
Thread 0 and 13 have both entered OpenGL from OEGameView. It seems very plausible there's a race here.

**Comment by clobber** [comment]
@JakeJet gonna need better details than that - such as what were you doing when it happened. Is it a certain game and core/system? Also note its in your best interests to update to the latest OS X point release, 10.10.4, but not that this has anything to do with your problem.

@ryanorendorff Desmume has bugs in the JIT that will crash certain games under various conditions. Sorry, nothing we can do about it. I would suggest playing NDS games in Desmume standalone which comes with the dynarec off by default.

**Comment by JakeJet** [comment]
Sorry for the lack for information. I was using the GBA core specifically to test if it was working, but the SNES core was giving me the same problem.  The games I were testing were Advance Wars and Super Mario World respectively. I'll update the OSX. Thank You.

**Comment by maki-chan** [comment]
Just a little assumption here: Are you using programs like f.lux or applications with similar features? Whenever f.lux was changing the color temperature for my Macbook Pro 15" (Late 2011), OpenEmu crashed when I started a core. Disabling f.lux for OpenEmu solved the problem in my case.

**Comment by mrvacbob** [comment]
Post crash logs if you've got them!

**Comment by maki-chan** [comment]
I don't have them anymore unfortunately, compiled a new OpenEmu version today from latest git commit (because I needed PSX multi-disc support which isn't included in the latest 1.0.4-experimental)

But I try to trigger another crash and post the logs when it crashes

**Comment by JakeJet** [comment]
f.lux was the culprit thank you!

**Comment by mrvacbob** [comment]
You should be able to find old logs in ~/Library/Logs/DiagnosticReports/ - I don't think they get deleted for more than a month after a crash.

Sounds like the report in the OP is the same issue, though!

**Comment by maki-chan** [comment]
I got all crash logs I could get from OpenEmu 1.0.4 (I am pretty sure it was the non-experimental version at that time) and zipped them for download at my university's site: http://students.fim.uni-passau.de/~armbrust/openemu-crashlogs.zip

In my current self-compiled build 959-gd84688c-Release is no problem at all with f.lux for now. I tried to make OpenEmu crash today again, but it ran just fine.
