### ISSUE TITLE
Nintendo 3DS support

### ISSUE THREAD

**Issue by OldBunny2800** [OpenEmu/OpenEmu#2019]
There is no current or planned emulator for 3ds games, and I need an emulator for it! Can you make one?

**Comment by OldBunny2800** [comment]
Why did you close it?

**Comment by cyco** [comment]
He expects pepole to do a search before posting.

https://github.com/OpenEmu/OpenEmu/search?q=nintendo+3ds&type=Issues&utf8=✓
