### ISSUE TITLE
HUD none-clickable

### ISSUE THREAD

**Issue by Allycat123** [OpenEmu/OpenEmu#2020]
Whenever I load up a game it's all working find and good, except that I cannot click and have it remain the HUD options. So I click to select filter, and I cant get further than just seeing it in the menu for a split second.
Anything to do with a menu inside the HUD I cannot click.
Help greatly appreciated.

**Comment by clobber** [comment]
Guessing 10.7 or 10.8, right? Those versions of OS X are no longer supported.

**Comment by Allycat123** [comment]
Sorry nope. 10.10.

**Comment by clobber** [comment]
Sorry, cannot replicate. HUD and menus work here as expected.

**Comment by cyco** [comment]
Is there anything unusual about your setup? Multiple monitors, touch input device, anything like that?

**Comment by Allycat123** [comment]
Nothing that I can think of. I mean I am using a laptop, with the track pad.(internal) But I have changed all the setting to default and still it is not clickable.

**Comment by clobber** [comment]
Closing; cannot replicate. Likely fixed already.
