### ISSUE TITLE
Sega Saturn

### ISSUE THREAD

**Issue by johnnyyy29** [OpenEmu/OpenEmu#2023]
For some reason, a lot of game for Sega Saturn won't appear in my library. I drag it in and nothing happens or it'll say it's reading the game image for a few seconds before it stops, never showing up. And yes, each time I have a cue and a bin. I drag the cue, and some games appear fine, but other games simply will not. I've never had this problem with playstation cues and bins...

**Comment by clobber** [comment]
Luckily, there is a detailed guide for you: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games

...or, you've run into this issue: https://github.com/OpenEmu/OpenEmu/issues/1965#issuecomment-118542238
