### ISSUE TITLE
Mayflash Dolphinbar crashes OpenEmu on launch

### ISSUE THREAD

**Issue by Wabewalker** [OpenEmu/OpenEmu#2024]
OpenEmu launches properly if I unplug Dolphinbar first.

I've tried deleting config bindings. No change.

I'm running OS X on 10.10.4 (Hackintosh)

Crash log:

https://gist.github.com/Wabewalker/995cb5d623a8e2e3ac88#file-oecrash-txt

**Comment by clobber** [comment]
The input system generally does not favor adapters/hubs so we say they're unsupported. Also can't rule out weird issues with a 'Hackintosh' install so we don't really debug those either.
