### ISSUE TITLE
Sega Saturn Multi-Disc Issue

### ISSUE THREAD

**Issue by johnnyyy29** [OpenEmu/OpenEmu#2025]
So I figured out the issue with Sega Saturn games opening up in your library...if it does not, it's an issue with the file...you just have to know where to look. However I tried to play a multi-disc game and it seems like creating an M3U makes the file appear in the PlayStation list...does this mean you can't play multi-disc games for systems other than PlayStation yet or is there a way around this?

**Comment by clobber** [comment]
The disc switching API + m3u file is only supported by Mednafen/PS1 right now. I don't know if Yabause has an API for switching discs while the game is running.

Yabause/Saturn support is experimental so these features won't be around soon anyway.
