### ISSUE TITLE
Can't add Famicom Disk System games

### ISSUE THREAD

**Issue by superstitions** [OpenEmu/OpenEmu#2026]
I have tried dragging them and dropping them into the window but nothing happens. I have also tried Add to Library. I have several copies of the FDS rom (disksys.rom) but that doesn't seem to make any difference. I have tried putting those into a BIOS folder in the application support folder. I have tried dragging them and dropping. I have tried switching cores.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

FDS games need to have the extension: .fds
