### ISSUE TITLE
"Couldn’t communicate with a helper application." possible solution

### ISSUE THREAD

**Issue by DaGangstaPanda** [OpenEmu/OpenEmu#2027]
I've been playing Final Fantasy Chronicles Ring of Fates for 5 hours or so, everything was fine and the game played smoothly (the latest version of openEmu on OSX 10.10.4). Suddenly, after a cutscene where the screen went blank, it stayed so, and finally the application crashed, warning me that it "Couldn’t communicate with a helper application.". 
Pissed off, I copied the battery save file from OpenEmu to Desmume, loaded it from the GAME's menu on Desmume, played through the cutscene (without any freeze problems), and saved right after it. Then I copied the battery save file from desmume back to openEmu, so that I'm already past the cutscene. Now I can keep playing on OpenEmu (which runs much more smooth and faster).
Just wanted to let you guys know, if it can help developing and also help other people stuck with this annoying problem.
Btw, you devs of OpenEmu are awesome, keep up the good work :)

**Comment by clobber** [comment]
This is another one of those JIT (dynarec) bugs where our port has JIT **on** by default and Desmume standalone has it **off** by default, which is why it works in standalone. Sorry, nothing we can do about this so I'd recommend just using the standalone app when an issue like this arises.
