### ISSUE TITLE
Include Travis CI for the repository

### ISSUE THREAD

**Issue by maki-chan** [OpenEmu/OpenEmu#2029]
A feature request for the whole project:

Wouldn't it be great if you could integrate Travis CI to provide automatic builds? It could be use to check if the latest changes to the repo still build and it could also be used to provide automatic builds with the newest features.

**Comment by clobber** [comment]
We routinely break things in source, so I don't want others using bleeding edge unless they know what they're doing. We'll instead focus on providing releases with stable builds as always.
