### ISSUE TITLE
Soft Patching

### ISSUE THREAD

**Issue by TrevorSayre** [OpenEmu/OpenEmu#2030]
Feature Request: Add soft patching so that *.ups and *.ips files can be given the same name as a ROM file and the ROM will be automatically patched when launched. There are emulators such as Visual Boy Advance which have this built-in, but OpenEmu does not currently support this.

**Comment by clobber** [comment]
Kicked the idea around in the past; not something we're looking to do right now because added complexity. Alternative would be to use MultiPatch (http://projects.sappharad.com/tools/multipatch.html)
