### ISSUE TITLE
OpenEmu doesn't want to copy lynxboot.img

### ISSUE THREAD

**Issue by maki-chan** [OpenEmu/OpenEmu#2031]
I have a valid lynxboot.img with the correct md5 checksum, but OpenEmu doesn't want to take it when I drop it over the library window. It still says that I need to get lynxboot.img

Copying it manually into `~/Library/Application Support/OpenEmu/BIOS` **DOES** work

**Comment by clobber** [comment]
It does. If using OpenEmu 1.0.4 (and whatever version of Mednafen we added support for this), the file must be named `lynxboot.img`, have the MD5 of `fcd403db69f54290b51035d82f835e7b` and be **unzipped**.

**Comment by maki-chan** [comment]
It doesn't with the latest git commit d84688cee0aae717b13fab48ac54720e96e24fbc

Shouldn't a bug report be accepted for the source in the repository, too?

**Comment by clobber** [comment]
You should be specifying what you are using.

**Comment by maki-chan** [comment]
Yes, sorry, I forgot to mention the version.
