### ISSUE TITLE
you guys should add xbox consle support

### ISSUE THREAD

**Issue by mgracer48** [OpenEmu/OpenEmu#2036]
the first one

**Comment by cyco** [comment]
Great suggestions, thanks! I'll put it on the todo list.

**Comment by clobber** [comment]
@mgracer48 hey bro you should write an xbox emulator! for the first one

**Comment by mrvacbob** [comment]
https://github.com/espes/xqemu It's coming!

**Comment by clobber** [comment]
>Status

>    * Very little actually works
>    * Most graphics are broken
>    * Everything is slow
>    * No audio
>    * No networking

> Barbie Horse Adventures.png

5 years from now is gonna be siiiick :D

**Comment by mrvacbob** [comment]
I've kept my BK drivethru copy of Sneak King for this very day

**Comment by clobber** [comment]
Awww yeeaahhh

![sneak](https://i.imgur.com/e95r0z8.png)

Definitely was the best game on Xbox
