### ISSUE TITLE
Loading VisualBoyAdvance Save State

### ISSUE THREAD

**Issue by eyeseamore** [OpenEmu/OpenEmu#2037]
Hello,

I've run into a slight issue - I was playing Pokemon: Emerald and decided to shut down the game to fix the audio mute bug, before doing this I created an in-game battery save. Unfortunately through some turn of events I seem to have overwritten my autosave-state with a brand new game. 

I'm now stuck trying to load the battery save I created before restarting OpenEmu and losing my autosave-state.

When I right click on Pokemon:Emerald there are no options under "Play Saved Game".

Currently, the battery save is in the following location: /Users/Seymour/Library/Application Support/OpenEmu/VisualBoyAdvance/Battery Saves

It's named correctly as well - I checked already!

So, how do I open it? Help!

**Comment by clobber** [comment]
Audio mute bug? Turn of events meaning you were messing around and deleted something?

If you loaded a save state after you saved in-game, that battery save will already have been overwritten by having loaded a save state: it's how the emulator works.
