### ISSUE TITLE
320M: All games unplayable due to slowdown

### ISSUE THREAD

**Issue by smorkin** [OpenEmu/OpenEmu#2039]
Using OpenEmu 1.0.4 on a 2.4 GHzCore 2 Duo Mac mini (mid 2010), 6 GB RAM, GeForce 320M 256 MB, all emulators lags and nothing is playable. E.g NES/GB/GBC/GBA/SNES have the same issue, ni matter which core I use and no matter what filter (including "Nearest neighbor"). Console is filled with:

Sep  6 22:10:38 Mac-mini.local OpenEmuHelperApp[20336]: Synchronizing because we are 1.02036 seconds behind
Sep  6 22:10:40 Mac-mini.local OpenEmuHelperApp[20336]: Synchronizing because we are 1.02203 seconds behind
Sep  6 22:10:42 Mac-mini.local OpenEmuHelperApp[20336]: Synchronizing because we are 1.02356 seconds behind
Sep  6 22:10:44 Mac-mini.local OpenEmuHelperApp[20336]: Synchronizing because we are 1.0027 seconds behind
Sep  6 22:10:45 Mac-mini.local OpenEmuHelperApp[20336]: Synchronizing because we are 1.01483 seconds behind
Sep  6 22:10:47 Mac-mini.local OpenEmuHelperApp[20336]: Synchronizing because we are 1.01222 seconds behind

CPU consumption is never large, around 10%, and I have a few GB of free memory out of the 6 GB (nothing else is running). Might be that the computer is simply too slow, but it feels a bit strange since I'd think at least NES/GB would be simple to emulate. So maybe something else is wrong.

What can I do to test more?

**Comment by mrvacbob** [comment]
Watch Activity Monitor. Is OE or anything else using lots of CPU? If OE is stalling without using 100% cpu that's also interesting.

**Comment by smorkin** [comment]
That's the weird thing, cpu usage is negligible overall; circa 15% in total (OpenEmu 10, other small standard system things 5 in total). So nothing is consuming cpu, yet OE is struggling.

**Comment by clobber** [comment]
This is the client storage thing. We patched this already but you'll have to wait until next release...actually i may have a build sitting around for 1.0.4

Here you go https://transfer.sh/9sUAh/openemu-1.0.4-no-clientstorage.zip

**Comment by smorkin** [comment]
Thank you very much, that solved t!

**Comment by clobber** [comment]
#1853

**Comment by luiscypher** [comment]
For some reason that link says "Not Found".

**Comment by clobber** [comment]
@luiscypher Those uploads only last 14 days.

Here is a new one: https://transfer.sh/12mqBa/openemu-1.0.4-no-clientstorage.zip

**Comment by luiscypher** [comment]
You are a saint.  You guys gave me my childhood back.  It's perfect now.
Just out of curiosity, is this fix coming for the experimental app too?
Thanks again for the incredible help! :)

**Comment by clobber** [comment]
Yes, it will be fixed in both build packages for our next release. Were you already running the 'experimental' cores package prior to this?

**Comment by luiscypher** [comment]
Yes.  I was using the experimental app with all cores running.  I
downloaded the experimental because I thought the problem would go away by
using that one instead of the non-experimental app, but the problem
persisted. By the way, every filter works to perfection in the app you just
gave me.

**Comment by Truesyndo** [comment]
Can you upload the file again please, Ive been having this problem for the longest.

**Comment by Truesyndo** [comment]
can you upload the file again please I have been having this problem for the longest
