### ISSUE TITLE
Cannot QuickSave

### ISSUE THREAD

**Issue by jeffreybox** [OpenEmu/OpenEmu#2040]
I compiled OpenEmu (v 1.0.1) from source in order to utilize the .m3u playlist feature for playing multidisc games on the Mednafen core.  Everything is working properly except quicksaving.  When i quicksave, the disc icon appears on the screen (as if it's saving), but when I quickload, this error appears:

"The Save State File Cannot Be Opened

Could not read the file state in /Users/username/Library/Application Support/OpenEmu/Save States/NES/Super Mario Brothers 3/Quick Save State.oesavestate/State."

When I navigate to that folder, there actually isn't a .oesavestate file.  This is happening for every game and every core in OpenEmu.  Any information?

**Comment by clobber** [comment]
1.0.1? 1.0.4 is the latest, especially if you compiled from source. Quick saving and loading works fine here. Sorry, you did something non standard and broke your install so I cannot help you. I suggest using 1.0.4 from the website.

**Comment by jeffreybox** [comment]
Great thank you. I was wondering if it was the latest - I followed an old link from a the issue on switching discs
