### ISSUE TITLE
MFi controller support

### ISSUE THREAD

**Issue by cannyboy** [OpenEmu/OpenEmu#2044]
A previous issue has been closed: https://github.com/OpenEmu/OpenEmu/issues/1113

However, I think MFi may get much more popular with the advent of the new AppleTV:
http://arstechnica.com/gaming/2015/09/apple-steelseries-talk-up-apple-tv-game-controllers-with-actual-buttons/

**Comment by clobber** [comment]
>However, I think MFi may get much more popular 

Perhaps when the day comes and people on the dev team actually have a device to test with? Until then, this is pretty unnecessary to open.

**Comment by dsemaya** [comment]
I have one of these controllers as well.  I bought it to use Provenance on Apple TV but I'd also like to use it with OpenEmu on OS X.

**Comment by elijah** [comment]
I have one that I bought to use for a variety of purposes - including with Steam - and have opened a bug with those folks about the D-pad on my Horipad Ultimate not being recognized  by their software either.  :)

**Comment by clobber** [comment]
SteelSeries Nimbus and SteelSeries Stratus XL 'just work'

Horipad Ultimate for next release.

If there are others that need to be added to the automap database, list them here.

**Comment by michaelaguiar** [comment]
Has support for Horipad Ultimate been released yet?  I get constant crashes while it's connected.

**Comment by clobber** [comment]
@michaelaguiar Yes.

To fix your crash:

1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

**Comment by michaelaguiar** [comment]
Perfect!  Thanks
