### ISSUE TITLE
Super Smash Bros N64 issue

### ISSUE THREAD

**Issue by Jowersman** [OpenEmu/OpenEmu#2045]
Hey guys.  For the Super Smash Bros N64 Rom, does anyone have the white bar on the right side of the screen? Wondering if that could be removed, thanks.

**Comment by clobber** [comment]
Sorry, no. These are bugs in the GPU plugin (Rice) used by our Mupen64Plus implementation. We're not responsible for these sorts of issues. Some day they may be resolved with a speedy software rasterizer. Also please keep in mind we show this warning for N64 for a reason:
![4d66a968-5c93-11e4-97e1-b2dd5b3dd23a](https://cloud.githubusercontent.com/assets/1303132/8178297/3b7d1862-13d2-11e5-8da7-3f1e90d7775c.png)

**Comment by Jowersman** [comment]
Okay great.  Also another question.  Does a Xbox 360 emulator exist? Thanks.

**Comment by mrvacbob** [comment]
It's not ready yet. http://xenia.jp
