### ISSUE TITLE
Controller not seen on El Capitan

### ISSUE THREAD

**Issue by plauclair** [OpenEmu/OpenEmu#2046]
Tried latest stable and experiment builds (1.0.4) and none of them seem compatible with El Capitan.

Just says "No available controller". The controller in question is iBuffalo Classic Controller (SNES). Same controller is working fine in Yosemite.

**Comment by clobber** [comment]
Dupe https://github.com/OpenEmu/OpenEmu/issues/1966#issuecomment-135531610
