### ISSUE TITLE
Openemu not opening DS games

### ISSUE THREAD

**Issue by marcelo0624** [OpenEmu/OpenEmu#2047]
Openemu isn't opening my ds games downloaded from the internet, I firstly downloaded Pokemon Platinum(.7z file) and played it and it worked like a charm, then I downloaded Pokemon Heartgold(.rar file) and tried to open it, it didn't open, Nothing happened after clicking it. I tried again with Soulsilver(.nds file) and it worked. Now I tried with pokemon black 2 and pokemon white 2 (both .7z files) and they didn't do anything after I clicked them. I tried dragging them to where it says " Drag and Drop Here". My Openemu is up to date I checked already. Only Pokemon Platinum is appearing in my games.
<img width="1280" alt="screen shot 2015-09-11 at 4 38 24 pm" src="https://cloud.githubusercontent.com/assets/14242206/9827804/8d573bb6-58a3-11e5-9f31-381f6f4274e9.png">
<img width="1280" alt="screen shot 2015-09-11 at 4 38 56 pm" src="https://cloud.githubusercontent.com/assets/14242206/9827812/9e2cfd86-58a3-11e5-81c9-64c3fda9b611.png">

**Comment by clobber** [comment]
#1992

You should also extract your 7z files. Unzip using The Unarchiver (free on the mac app store https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12)

**Comment by marcelo0624** [comment]
thanks m8
