### ISSUE TITLE
OpenEmu "Unable to communicate with a helper application"

### ISSUE THREAD

**Issue by Haven-1** [OpenEmu/OpenEmu#2049]
I have been playing Avalon Code(US)(XenoPhobia).7z on an OpenEmu v1.0.4 554-gf588330-Release on a Macbook Pro with a 2.5 GHz Intel Core i5 processor running on a OS X Yosemite operating system (10.10.4 version). The game has been running great and I have been very happy with it then suddenly when completing a specific action in the game the whole game freezes. I have tried restarting the game, OpenEmu and the computer. I only have one display, have not been using pop-outs, and have been using the pixellate filter. My graphics processor is Intel HD Graphics 4000 1024 MB. I am not sure if I have a retina display or not but I do not think I do- if this is a important factor I would be happy to do more research on it!! I have to force quit the whole OpenEmu program as it will not respond and then there's a little pop-up that says "Unable to communicate with a helper application".

. I would be so appreciative if anyone could help me with this!! It's driving me crazy and I am very frustrated about losing such a great game. Thanks a ton in advance for taking the time to take a look at this- hoping you can help me work it out!

(PS. If anyone needs more information to try an figure out the problem I would be happy to contribute!)

**Comment by clobber** [comment]
This is another one of those JIT (dynarec) bugs where our port has JIT **on** by default and Desmume standalone has it **off** by default, which is why it works in standalone. Sorry, nothing we can do about this so I'd recommend just using the standalone app when an issue like this arises.

**Comment by Haven-1** [comment]
Thank you for the response! So by "standalone app" you mean you would recommend Desmume?
