### ISSUE TITLE
glitchy gui behaviour

### ISSUE THREAD

**Issue by VJrabauke** [OpenEmu/OpenEmu#2050]
the context menus don't close and they overlap the emulation
![gui-screenshot](https://cloud.githubusercontent.com/assets/14247195/9830965/2a57b6b6-5944-11e5-85e3-5d67ea110b0e.png)

running OS X 10.10.5 (14F27), OpenEmu 1.0.4 (554-gf588330-Release) on a MacBookPro8,3

**Comment by clobber** [comment]
Cannot replicate the problem with the latest so it appears fixed and will be in our next release.
