### ISSUE TITLE
How do you set up a standalone or portable nds emulator for mac?

### ISSUE THREAD

**Issue by Haven-1** [OpenEmu/OpenEmu#2051]
Total newb here but I'm trying to set up a standalone (are portable and standalone the same thing) emulator for my mac and have been unable to find that. Any advice? Thanks!

**Comment by clobber** [comment]
http://lmgtfy.com/?q=desmume

**Comment by Haven-1** [comment]
Thank you clobber! I wasn't sure if that was the right thing.
