### ISSUE TITLE
SNES emulator is very slow

### ISSUE THREAD

**Issue by Ronnybonny** [OpenEmu/OpenEmu#2052]
Hello,
Open EMU is awesome but lately my snes emulator is very slow and constantly glitching. Any ideas?
I run a Mac OSX 10.9.5, 2.53 ghz intel core duo 2 with a 8 gb 1067 DDR3
Open EMU version V1.0.4 with the SNES9X version 1.53.3

Sincerely,

Ronny

**Comment by clobber** [comment]
Luckily, you've shared details about your machine specs, your operating system, your version of OpenEmu and which emulator you are using.

**Comment by Ronnybonny** [comment]
Thanks Clobber for clubbing the shit out of my bad posting...

**Comment by clobber** [comment]
I need to know what your GPU is. Also, I advise upgrading to 10.10 (and 10.11 soon after) as our next release will not support 10.9.

**Comment by Ronnybonny** [comment]
NVIDIA GeForce 9400M 256 MB
Is this what you mean?

Yeah, but i also run composing software and i am afraid (very afraid) that it will outdate some plug-ins i use. But thanks!

**Comment by clobber** [comment]
It is likely you are using a Filter (shader) that your GPU cannot handle. Try switching to "Pixellate" or "Nearest Neighbor"

**Comment by Ronnybonny** [comment]
Thanks, I will try that and keep you updated. Have a nice day.
