### ISSUE TITLE
Open Emu, not able to use controls on gameboy advance

### ISSUE THREAD

**Issue by leeskiiom** [OpenEmu/OpenEmu#2054]
Hi, I'm using OpenEMU v1.0.4. I've been using it to play pokemon fire red for a few days with no issue. I went to save the game and now all of a sudden my keyboard controls are working.

I have reset the emulator but to no avail. The game continues to run, i.e. other characters in the game are still moving about etc.

Any help greatly appreciated.

**Comment by clobber** [comment]
This has come up several times in the past, usually related to some other open application causing interference. If you search the issues you should be able to find related issues and possibly a solution.
