### ISSUE TITLE
el capitan support

### ISSUE THREAD

**Issue by bears20151** [OpenEmu/OpenEmu#2055]
Updated to mac's new os el capitan last night now my buffalo classic usb gamepad won't work.. Will there be an update soon??

**Comment by cyco** [comment]
We hope to get an update out in the first week after the official launch of the new os.

**Comment by bears20151** [comment]
Alright thank you very much!

**Comment by clobber** [comment]
Duplicate, please search. https://github.com/OpenEmu/OpenEmu/issues/1966#issuecomment-135531610

**Comment by since78** [comment]
Just found this support case. Looking forward to that support update so I can get back into Hyper Metroid.

LOVE this app!
