### ISSUE TITLE
OpenEmuHelper quits when entering the Dreamyard in Pokemon Black

### ISSUE THREAD

**Issue by Ivorforce** [OpenEmu/OpenEmu#2057]
When entering the Dreamyard in Pokemon Black, OpenEmuHelper crashes with this log: https://gist.github.com/Ivorforce/5046495494f22dcbb503

Tried with 2 different ROMs, 100% reproducible on both. The crash results in the game view going black and the main window not responding. 

Version is OpenEmu v1.0.4, 554-gf588330-Release.

**Comment by clobber** [comment]
This has come up I don't know how many times, so search next time.

This is a bug with Desmume using the JIT. Sorry, nothing can be done about it. I'd recommend using standalone Desmume app which has the JIT off by default.
