### ISSUE TITLE
Mame Games doesn't start 

### ISSUE THREAD

**Issue by mmmelih** [OpenEmu/OpenEmu#2058]
Hello,

I have downloaded Open Emu to my Macbook Pro but having some issues on only MAME games. Some roms working perfectly when I dobule click the game name. But some of them doing nothing. Mouse cursor disappear on the screen but game screen not pop up. No error message or anything. Just mouse cursor disappear and when I move mouse its coming back. 

I took a video snap; https://www.dropbox.com/s/bhmw43aisrx4j6y/Untitled.mov?dl=0

Do you have any idea about that ? I am creating an arcade cabinet with open emu and I need to sort out that asap.

My computer details: Macbook Pro Retina 2015 13" (Early 2015)

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/1445#issuecomment-46265285
