### ISSUE TITLE
Cores didn't install

### ISSUE THREAD

**Issue by AheadBlockland** [OpenEmu/OpenEmu#2060]
Hi,
I just installed OpenEmu today by a simple method (copying Contents, put in folder, made .app)
when I got to the core stuff, there was COMPLETELY nothing there.

Help?
![screen shot 2015-09-19 at 3 31 13 pm](https://cloud.githubusercontent.com/assets/14228506/9978440/814ebb46-5ee3-11e5-8076-f56555f55238.png)

**Comment by clobber** [comment]
Wat. I'm not sure I understand but it looks like you did something non-standard and who knows why.

So try again:

1) Delete your OpenEmu install, this includes the application and the "OpenEmu" folder in ~/Library/Application Support.
2) Run the following command in Terminal.app: `defaults delete org.openemu.OpenEmu`
3) Download an official build of OpenEmu from our website: http://openemu.org
