### ISSUE TITLE
Other way to compile other than Xcode?

### ISSUE THREAD

**Issue by RainingJellyfish** [OpenEmu/OpenEmu#2062]
I don't have admin permissions, so Xcode will not install. I was told to try SourceTree, but I have no idea how to go about using it to build (if it can even do that). I need the compiled version for its disc change feature. Please help?

**Comment by cyco** [comment]
I guess you'd use sourcetree to get the source code. But after that you'd still need Xcode to actually build the project. There's no way around that, sorry.

**Comment by RainingJellyfish** [comment]
I was afraid so. I'll ask for someone to build for me then.
