### ISSUE TITLE
Open Emu Battery Save Failure

### ISSUE THREAD

**Issue by nanogram** [OpenEmu/OpenEmu#2066]
I was playing Pokemon Ruby on the GBA emulator. And you know, I gotta catch all the legendaries, so sometimes I would accidentally make it faint, so I would restart the game and try again. All of a sudden, when I reset, the program says there was an error connecting to core. I open up my game again and i am where i was three whole days ago! My question: are battery saves safe or do i mainly rely on save states? can i recover the lost data?

**Comment by clobber** [comment]
To answer your question: Safe, yes. But stick with save states for now.

I found a bug where the battery save would sometimes break in the fork of VBA we were using. I've patched this some time ago and the fix will be available soon with the next release of OpenEmu. Sorry about that.

**Comment by nanogram** [comment]
when should I expect the next update to come out?
