### ISSUE TITLE
New to GitHub - Vectrex Core

### ISSUE THREAD

**Issue by chrissalo** [OpenEmu/OpenEmu#2070]
Please forgive my ignorance, but I am new to github.
I can't seem to find a forum, or a place where sharing on a chat or thread basis happens - or am I just blind?
Anyway, I had a bit of spare time today and fiddled with the vectrex core.
I don't know if they should directly go into the repository, perhaps someone more responsible to coding styles should have a look over :-). Whom can I send the changes to?
What I did?

A couple of years ago, when I still developed the DVE emulator I wrote down:
###
...
Another global constant can be set (though preferable not at the same time
as the above mentioned) ANALOG_CYCLE_PATCH.
I suspect that some control lines are not updated at the same cycle as
VIA. Original emulation had it, that for example BLANK is exactly the
VIA output (control line t6522CB2). I suspect, that the analog hardware
recieves the BLANK impulse some cycles later. I further suspect that
these lines have different 'delays'. With the above option some form
of delay can be enabled for a certain number of analog lines.
####
And I did exactly that within the Vectrex core, entered a delay for a few signals lines.
The outcome ist a cleaner display, mainly visible in Cleansweep,  but also noticable at every startscreen (text is now centered).

Anyway, if anyone is interested - leave me a note where I can drop the source code to.

**Comment by clobber** [comment]
Hey cool, thanks for the interest. If you're just looking to contribute a patch you can open up a "pull request" here for Vecx (https://github.com/OpenEmu/VecXGL-Core/pulls) and we can discuss any changes in that thread. Vectrex emulation isn't really active in the 'scene' these days besides a few homebrew games here and there on AtariAge forums, so we'd love the fix you have in mind. There is also more info here for pull requests on GitHub in general: https://help.github.com/articles/using-pull-requests/

Also, we're on IRC: irc.freenode.net #openemu for chat. #mednafen is another good general emulation channel on that network. Another network, EFnet, still has its active channels such as #messdev (for MAME/MESS), #nesdev, #gbdev, etc.

I'll close this ticket but feel free to still reply.

**Comment by clobber** [comment]
Oh, and I forgot to mention you could always just paste a diff patch on here https://gist.github.com/

**Comment by chrissalo** [comment]
O my.
As said - I am new to Git, and my head is spinning.
I think I understand the concept of git as of now (in opposite to the (for me) well known svn).
I created a fork, made a local clone, added, committed and pushed. All well, but than I discovered, that the Vectrex Core is really just a submodule, and that I did not make a fork of that and that I cannot just straight forward push from my local clone...

Or is there an easy way, that I can push from a submodule of a clone of a fork of an "original" to the  submodule of that said "original" repository?
(Even phrasing that question makes my head spin slightly...)

**Comment by clobber** [comment]
To make it easier on you, just fork the Vecx repo here https://github.com/OpenEmu/VecXGL-Core (you can do this all from within the website, including editing the source, pushing a commit and sending a pull request to the repo you forked). Then when I merge your patch I'll update the submodule reference in our main repo.

If you are an old school SVN guy, there is a sort of git-to-svn conversion guide here: http://git.or.cz/course/svn.html

**Comment by chrissalo** [comment]
Nah...
That ist for babies... I will figure it out...
looking at http://blogs.atlassian.com/2013/03/git-submodules-workflows-tips/ now, seems usefull :-)

**Comment by clobber** [comment]
Sure, that is an example workflow for when you have write access to the submodules. But you on your end still need to fork our VecXGL-Core repo if you want to contribute a patch back upstream.

**Comment by chrissalo** [comment]
Ok.
I did what you proposed - I finally committed all changes thru the web fronted, thats why there are quite a few commits. Is there a way to change multiple files via the web fronted with only one commit? I didn't  find one by just looking at the edit-pages.

**Comment by clobber** [comment]
Thanks. No, cannot edit multiple from the web interface as far as I know. For more control, I suggest you get a git client such as GitHub's (https://desktop.github.com) or SourceTree (https://www.sourcetreeapp.com), otherwise you want to do that all from command line. 

I commented on your pull request here with a guide for you to squash all those small commits down to one: https://github.com/OpenEmu/VecXGL-Core/pull/1#issuecomment-144864969
