### ISSUE TITLE
El Capitan & OpenEmu Experimental

### ISSUE THREAD

**Issue by gberthia** [OpenEmu/OpenEmu#2075]
I Installed "OpenEmu Experimental" to try out MAME on OSX Yosemite and it worked perfectly. I then upgraded to El Capitan the following day and now the "OpenEmu Experimental" looks identical to "OpenEmu" with the "Arcade" section missing. I redownloaded "OpenEmu Experimental" but saw no difference, tried to reinstall/run the rom and it didn't work.

**Comment by clobber** [comment]
Simply upgrading your OS could not have made a change to your library.

If you have OpenEmu 'experimental' package installed, Go to OpenEmu > Preferences > Library, check the box for each missing system under 'Available Libraries' or right click on 'Consoles' in the UI and select each missing system from the context menu.
