### ISSUE TITLE
Openemu arcade Street Fighter 3rd Strike

### ISSUE THREAD

**Issue by PhantomKnight64** [OpenEmu/OpenEmu#2077]
When ever I try to play 3rd strike it says "Memory has not been set necessary for the game. Please try again when the power is turned off."
I tried reinstalling openemu, deleting and getting 3rd strike again and just resetting but it dosen't work
I really want to play 3rd strike again :(

**Comment by clobber** [comment]
This doesn't have anything to do with OpenEmu. I suggest googling the message and seeing what kind of information you find.

**Comment by andybrito** [comment]
Delete both "cfg" and "nvram" files for this game, these files are inside the "MAME" folder in the OpenEmu folder located at the Application Support folder.

**Comment by PhantomKnight64** [comment]
Thanks alot andybrito
