### ISSUE TITLE
Switching from/to game window causes loss of input function.

### ISSUE THREAD

**Issue by armlesshobo** [OpenEmu/OpenEmu#2078]
I noticed that while playing GB or NES games, if I switch to another window, and then come back to the game window, none of the controller buttons work and I can no longer play the game.

* I use a keyboard for game controller input
* I have to completely shutdown OpenEmu and start it up again for functionality to return
* Running OSX 10.11
* I haven't tested this with other game systems so far.

**Comment by clobber** [comment]
Cannot replicate on 10.11 with latest source, so assuming fixed. Will be available next release.
