### ISSUE TITLE
Crashes when adding Cover

### ISSUE THREAD

**Issue by karlbateman** [OpenEmu/OpenEmu#2079]
When trying to load a cover for SNES games OpenEmu crashes.

**Comment by mrvacbob** [comment]
Please find the relevant files in ~/Library/Logs/DiagnosticReports and post them here using gist.github.com.

**Comment by karlbateman** [comment]
There is nothing there :confused:

**Comment by mrvacbob** [comment]
Well, if it's crashing you'll get a window with the crash report in it, so try it again and post that text.

**Comment by karlbateman** [comment]
Thanks, will do.

**Comment by karlbateman** [comment]
Ok so I decided to add a game and had the same issue, OpenEmu crashes. The log file is available here.

[https://gist.github.com/karlbateman/c5804af22e442be0c78a](https://gist.github.com/karlbateman/c5804af22e442be0c78a)

**Comment by cyco** [comment]
Looks like openemu is running into some infinite recursion. I'll try to fix it tomorrow. Thanks for the info.

**Comment by karlbateman** [comment]
​​
Mmmm, no worries. Awesome program by the way. Would be great to see it on
Linux :smile:

**Comment by clobber** [comment]
Um pretty sure this was already fixed

**Comment by clobber** [comment]
Cannot replicate on 10.11 from latest source and this looks a lot like #1993
