### ISSUE TITLE
Multiplayer Super NES

### ISSUE THREAD

**Issue by RayXambeR** [OpenEmu/OpenEmu#2080]
I have a little problem. Even if I have defined the controls for 4 players, I cannot be able to play with a game. I have tried Apocalypse II (an unrealeased Psygnosis game) and, after setting 4 players in options, it appears the following mention: "activate multiplayer adaptor".
And I cannot return to title screen. If I only set to 2 players (or less), there is no problem.

Do exist an option in OpenEmu to pass through by activating multi player adaptor. I suppose Apocalypse II will be ok on a real system, with a multi player adaptor connected to it.

Thanks for any help! Keep up the good work on OpenEmu, it is a great software!

**Comment by clobber** [comment]
Please use the search function before opening new issues.

#1149
