### ISSUE TITLE
Not enough players on some systems (TG-16, Jaguar, Mega Drive, Atari VCS 2600, ...)

### ISSUE THREAD

**Issue by RayXambeR** [OpenEmu/OpenEmu#2081]
OpenEmu is fantastic but, for some systems, there is lack of controls. Not enough players can be set.

For examples, for Nec TurbografX-16 (PC Engine in Japan), this system could accept up to 5 players simultaneously. And OpenEmu only two. The same for TG-16 CD.
The same for Jaguar with only two (with two multitap, up to 8 players)
Atari VCS 2600 for the "rotary" games could have 4 players. OpenEmu just accept 2 players.
Vectrex, only one player on OpenEmu but 2 in reality.
Mega Drive only 2 players instead of up to 4 on the real system
etc.

Is there a possibility to "fix" that? Specially for TG-16 system, please! :) And Mednafen allows to have more than 2 players and the Core used is... mednafen ;)

Thanks!

**Comment by clobber** [comment]
Next version.
