### ISSUE TITLE
oecoreplugin or oesystemplugin ?

### ISSUE THREAD

**Issue by RayXambeR** [OpenEmu/OpenEmu#2082]
I have tried to have some core in my OpenEmu version but, the extension is different.
After OpenEmu's installation, I have several files with oesystemplugin termination.
But, the other Cores I have added (crabemu, mednafen, neopop) have oecoreplugin extension.
I have tried to rename them with oesystemplugin extension but OpenEmu crashes and refuses to launch.

If I let this extension, it doesn't change anything for me in OpenEmu. So, how can I use theses "new" cores?

Thanks for any help.

**Comment by clobber** [comment]
What you are doing doesn't make sense and isn't possible. Wait until release of next version.
