### ISSUE TITLE
Game Pad not Working with El Capitan

### ISSUE THREAD

**Issue by austin00** [OpenEmu/OpenEmu#2083]
I've been using OpenEmu v1.0.4 for months with an SNES style USB gamepad. It's always worked fine until I updated to OS X El Capitan. The controller isn't recognized when I'm in the settings. I'm convinced this is a software issue, not a hardware issue, as the controller hasn't changed.

**Comment by clobber** [comment]
Guessing an "iBuffalo" right? C'mon dude, use the search.

#1966
