### ISSUE TITLE
Openemu 1.0.4 Problems on MAC OS X El Capitan

### ISSUE THREAD

**Issue by powerhousepr** [OpenEmu/OpenEmu#2084]
So far the Application runs SNES games and gameboy games without any problems.

Now when playing Mario 64 DS, the app freezes after 15 or 20 minutes. This doesnt happen with the other DS games but i dk about the other games i dont have.

Also when trying to change the library of the App, it freezes every time and i have to force quit.

**Comment by arturoimaz** [comment]
Same for me, it freezes when changing the library, any solutions?

**Comment by clobber** [comment]
Our last release is almost a year old now and we have a new release planned soon to fix up outstanding bugs. Only thing you can do right now is wait.

**Comment by jurassicjordan** [comment]
Please fix this soon, by the holidays preferably
