### ISSUE TITLE
OpenEmu-SDK is missing when downloading source as zip file

### ISSUE THREAD

**Issue by maurymarkowitz** [OpenEmu/OpenEmu#2085]
After a brief period of confusion, I noticed that downloading the zip version of the source produces an empty OpenEmu-SDK inside the OpenEmu folder. I was able to download it separately and presto, it compiled with only 20 warnings.

Likely just a flag somewhere here in GitHub, hope it's easy to fix.

**Comment by clobber** [comment]
Of course it's missing, it's in a submodule so it won't be in the zip file.

**Comment by maurymarkowitz** [comment]
Ok well given that it won't build without it, maybe a little hint text somewhere wouldn't be too much to ask?

**Comment by clobber** [comment]
How about a wiki guide? https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide
