### ISSUE TITLE
Feature Request: Tagging

### ISSUE THREAD

**Issue by pipwerks** [OpenEmu/OpenEmu#2087]
Hello

Thanks for your work on this, it's a great system.

I just have a quick suggestion: It would be great if the user could tag games and filter the view based on the tags. For example, tagging a game as a first-person shooter, a puzzle game, or a sports game. It would make it much easier to quickly jump to a particular style of game.

**Comment by clobber** [comment]
Something we may or may not do in the future.

This falls under #664 and #811

**Comment by pipwerks** [comment]
I saw #664 and #811, they didn't specifically list tagging, hence a new request. 

Is this something the team would be open to as pull request? I don't see anything in the wiki about the team's preferences or code standards for pull requests. 

Thanks again

**Comment by clobber** [comment]
It's the same thing, you are essentially talking about "smart collections"

No, not something we're looking to add right now.
