### ISSUE TITLE
Error when "build all + Experimental"

### ISSUE THREAD

**Issue by Talintid** [OpenEmu/OpenEmu#2088]
![screen shot 2015-10-09 at 9 23 10 am](https://cloud.githubusercontent.com/assets/15041586/10394797/6be6940c-6e67-11e5-86a5-f361b37382d7.png)

**Comment by joey-astrologo** [comment]
I get the same error too

**Comment by clobber** [comment]
Me three

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu/commit/b18060f032cfb49b3df67949e1380b834fc2872c

Please report if other submodules are affected.
