### ISSUE TITLE
Affected sub routine in Genesis plus Core When "Build all + Experiemental" Post CrabEmu Fix**

### ISSUE THREAD

**Issue by Talintid** [OpenEmu/OpenEmu#2089]
![screen shot 2015-10-09 at 12 26 07 pm](https://cloud.githubusercontent.com/assets/15041586/10399600/98083864-6e81-11e5-9ba1-6097e0c6644b.png)

**Comment by Talintid** [comment]
also Picodrive.... If it not a prob.... Im just going to run a diag on all the subs for latency and ill post my findings here on this thread
![screen shot 2015-10-09 at 12 49 07 pm](https://cloud.githubusercontent.com/assets/15041586/10400035/73421d12-6e84-11e5-9040-cb0967d44db2.png)

**Comment by Talintid** [comment]
and lastly there is an error during the compile in the oddessy gamecore. all other routines seem to have built seamlessly when excluding these 3 cores 
![screen shot 2015-10-09 at 1 31 47 pm](https://cloud.githubusercontent.com/assets/15041586/10401043/71eccd12-6e8a-11e5-964c-b033fa5809f3.png)

**Comment by clobber** [comment]
Thanks for checking that out, I'll patch in a bit. In the meantime you can fix locally on your end if you make the same change to the affected project files like CrabEmu.

**Comment by Talintid** [comment]
will do.... thanks

**Comment by Talintid** [comment]
by the way, how do i build a singular core without building the entire .app.... unfortunately, im stuck. and the Mednafen core that was compiled with OpenEmu seem to not be working correctly. and i dont want to feel obligated to compile the entire emulator for just 1 or 2 core diags.... any help is oblidged.... 
![screen shot 2015-10-09 at 4 26 09 pm](https://cloud.githubusercontent.com/assets/15041586/10404725/7d14e838-6ea2-11e5-89ca-b76cf70b0296.png)

**Comment by clobber** [comment]
Fixed here https://github.com/OpenEmu/OpenEmu/commit/b8fccf661818b0a55edc68b2f098bcff414271db

@Talintid You cannot use most of the new cores with the old OpenEmu app.

**Comment by Talintid** [comment]
@clobber so does that mean that i have to update to the latest osx? cause i would rather not...

**Comment by clobber** [comment]
Yes.
