### ISSUE TITLE
Minor bug: "The operation could not be completed" on opening any game – except, the game opens!

### ISSUE THREAD

**Issue by bluesdance** [OpenEmu/OpenEmu#2090]
Whenever I open a MAME game lately, the game opens, but on top of the game there is this dialog box, to which I have to click OK.

I call this a minor bug because the game loads perfectly and everything works!

It's not a big deal to just click "OK," but I thought the programmers should know that this is happening.

Thanks

![dialog box](http://i.imgur.com/TIL2TAB.png)

**Comment by clobber** [comment]
This was fixed back in https://github.com/OpenEmu/UME-Core/commit/7ad25f60338d96c7ac474898ac5ee486dbf19a0c

A new version will be pushed out for next OpenEmu release.
