### ISSUE TITLE
Can't add cover art from file

### ISSUE THREAD

**Issue by g1cbr** [OpenEmu/OpenEmu#2091]
Hi I only just started using OpenEmu today, it's understandable that download cover art doesn't always work, but when I tried to add cover art from file, it just becomes unresponsive. I am using El Capitan, so I don't know if it's a compatibility issue with the OS or just an existing bug. Any help please, thanks in advance

**Comment by clobber** [comment]
Been fixed. Wait until next release (soon) for the patch.

#1993
