### ISSUE TITLE
Deployment Platform osx 10.11?

### ISSUE THREAD

**Issue by Talintid** [OpenEmu/OpenEmu#2094]
is this compile only for osx 10.11 or is it backwards compatible? i see from the markup that most of the plugins are compatible with !0.7 but the OE.sdk and OE itself are only for 10.11. how i get around this because i dont feel comfortable updating to the latest osx as of yet

**Comment by clobber** [comment]
Sorry, no. Only the latest OSX is supported. 10.11 is perfectly fine to upgrade to.
