### ISSUE TITLE
MAME / Defender ROM: "Press advance to step through test"

### ISSUE THREAD

**Issue by bluesdance** [OpenEmu/OpenEmu#2096]
Dear OpenEmu team,
Trying to play "Defender" on OpenEmu. The game says: "Press advance to step through test," but there is no mappable "Advance" button. Please implement this.

**THANK YOU**

**Comment by clobber** [comment]
Defender (Red label) version is fine to boot, it's the one I've used. Arcade/MAME is experimental and not a focus right now but in the future we'll re-think input.
