### ISSUE TITLE
OpenEmu just crash on each start

### ISSUE THREAD

**Issue by rvb3n** [OpenEmu/OpenEmu#2098]
Hi,

I've compiled OpenEmu with Xcode 7.0.1 on El Capitan but when I try to start the app, it crash on each opening.

I tried to build the base version and the Experimental but the result it's the same.

The version I download from the official webpage works just fine.

The error I get from the crash report is:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[NSNib _initWithNibNamed:bundle:options:] could not load the nibName: NSTitlebarAccessoryViewController in bundle (null).'
terminating with uncaught exception of type NSException
abort() called

Can you help me?

**Comment by cyco** [comment]
When was the last time you updated the source code? Did you try a clean build?

**Comment by rvb3n** [comment]
I've just installed El Capitan on a new SSD and I've download Xcode and OpenEmu from Git today: I had the same problem on Yosemite and I thought I would have better luck on a fresh installation..

**Comment by cyco** [comment]
I'm not sure what's happening here, either your xibs get corrupted or something is wrong with the build settings.

Try cleaning out your ~/Library/Developer/Xcode/DerivedData/ directory and then build OpenEmu again, also make sure that the base SDK is set to latest and shows OS X 10.11 in parentheses ;)

**Comment by rvb3n** [comment]
Thx I'll try to clean the folder, but what do you mean by setting the SDK? I just followed the instruction on the guide, I don't have much experience with Xcode..

P.S. Is it normal that after cloning OpenEmu and opening the project, Xcode lights up like a Christmas tree (I got hundreds of warning on the side bar)?

**Comment by cyco** [comment]
Yes, warnings are 'normal', as long as you don't see any red errors everything should be fine. If you click on the project in the sidebar and select OpenEmu (under 'Targets') you'll get an option to inspect the 'Build Settings'. Those should contain a line saying Base SDK: Latest OS X (10.11). (see screenshot)

![sdk](https://cloud.githubusercontent.com/assets/697021/10463493/42b6765c-71e5-11e5-98df-14273538817c.png)

**Comment by rvb3n** [comment]
I've just checked and I got the same settings! :/

**Comment by rvb3n** [comment]
By the way here is the full crash log:

https://dl.dropboxusercontent.com/u/3737004/CrashLog.txt

**Comment by cyco** [comment]
could you try this version? https://transfer.sh/f55Jg/openemu.zip
i'm still trying to figure out whether you're building it wrong or if your system is weird :D

**Comment by rvb3n** [comment]
No luck! Crash on start even with your version!

**Comment by cyco** [comment]
Alright, i think i figured it out. You're probably running a non-english version of os x. Localization are broken as we're currently re-designing the app.
The quick fix is to right-click the app, choose 'Show Package Contents' from the context menu and then remove you're language from Contents/Resources/ (just delete the .lproj directory, e.g. de.lproj).

Let me know if this works for you so i can close the issue.

**Comment by rvb3n** [comment]
It works! Thanks a lot!

**Comment by cyco** [comment]
Great. Have fun, but remember that you're running a development version that probably has a lot of bugs not worth reporting.
