### ISSUE TITLE
Occasionally - messy, nasty crash that requires hard power down!

### ISSUE THREAD

**Issue by bluesdance** [OpenEmu/OpenEmu#2099]
Every once in a while, OpenEmu crashes in such a way that it's impossible to get it out of memory. I try using Force Quit but the app just says loaded.
Weirdly, even though OpenEmu shows up in the FQA window and gets in the way of logout/shutdown, I can't find any trace of it in Activity Monitor.
The only way to resolve the problem is to hold down on my MacBook's power button!

![screenshot 2015-10-13 14 53 58](https://cloud.githubusercontent.com/assets/373713/10464953/66df338c-71ba-11e5-8da2-cac6adfe4145.png)
![screenshot 2015-10-13 14 54 00](https://cloud.githubusercontent.com/assets/373713/10464952/66dece1a-71ba-11e5-8f1d-01a7e643ed6e.png)
![screenshot 2015-10-13 14 54 04](https://cloud.githubusercontent.com/assets/373713/10464954/66df72b6-71ba-11e5-9aea-51ed50dc9d59.png)

**Comment by clobber** [comment]
This doesn't tell us anything. Crash logs? Is it with a certain system and game? As I've said before, the current release of OpenEmu is about a year old and things are broken but fixed in source now so you'll really have to wait until next release. Closing unless we get additional information.

**Comment by mrvacbob** [comment]
This is a bug in OS X, I think I've heard of it before.
