### ISSUE TITLE
Mavericks Support for Next Release

### ISSUE THREAD

**Issue by asoksevil** [OpenEmu/OpenEmu#2100]
I just stumbled across this closed issue:https://github.com/OpenEmu/OpenEmu/issues/2052 where @clobber states that 10.9 (Mavericks) won´t be supported in the next major release leaving it only to El Capitan (and perhaps Yosemite).

If possible, I would like to get a better understanding about why it won't be supported as Mavericks still receives safety updates from Apple, there are quite a lot to apps that have not been updated to El Capitan yet and at least from me it has been working great, even better than the buggy Yosemite.

Thanks!

Edit. So here´s the commit: https://github.com/OpenEmu/OpenEmu/commit/7b18c2f7487ea1f4af3369547f5ccf373ab085e1 and it seems that only 10.11 will be supported unfortunately. I understand El Capitan brings some performance improvement over Yosemite but I am not sure how this will affect OpenEmu.

**Comment by mrvacbob** [comment]
10.11 is a free upgrade with very few bugs; incompatible apps might even just be written to put up an error if they don't see "10.10" somewhere!

The new UI font and Metal for OS X are both very important things that make development for an earlier OS more difficult, because we'd need to support both and test both. Multi OS testing needs a lot of changes if you're just working on your personal computers.

**Comment by clobber** [comment]
Ditto everything above, update your OS dude.

**Comment by asoksevil** [comment]
@clobber 

I have apps that haven´t been updated to El Cap yet...

Anyway, does that mean that previous versions will be removed? I am okay with the current one as I can still play all my favorite games...

**Comment by robotoad** [comment]
@asoksevil 

By remaining with OpenEmu 1.0.4, you will be missing out on major new features. 10.11 has the same system requirements as 10.10 and 10.9, and it is a recommended update.

**Comment by asoksevil** [comment]
@robotoad

Thank you for your suggestion. I will certainly update to El Cal as soon as my other apps and my projects are done. I really don't want to screw it up in the middle of it. Regarding  to my previous questions will you guys leave the 1.0.4 version for the people using 10.9 and older?

Thanks!
