### ISSUE TITLE
Graphic card switching on Macbook Pro

### ISSUE THREAD

**Issue by capeman29** [OpenEmu/OpenEmu#2101]
When you start Openemu on the high end Macbook Pro with automatic graphic card switching, the graphics card stays on the integrated processor when browsing the games menu, then switches to the discrete graphics card when an emulator is started. Seems fine up to this point.

The problem is, when an emulator is quit, and you return to the openemu menu, the graphics card does not switch back to integrated until openemu is quit, even if no emulator is running, potentially causing a strain on battery life to those who don't monitor which card their MBP is using at the time. 

It would be best to switch back to integrated when the emulator is quit and you return to the browsing menu.

**Comment by clobber** [comment]
#375
