### ISSUE TITLE
Application stops responding when I try to change Game Library Folder Location

### ISSUE THREAD

**Issue by loganhuskins** [OpenEmu/OpenEmu#2107]
I am using a fresh installation of OpenEmu 1.0.4 on OS X 10.11. I have not loaded any ROMs or changed any settings yet. When I try to change my Game Library Folder Location the application locks up and takes ~99% of my CPU.

**Comment by cyco** [comment]
Yep, this will be fixed in the next release.

**Comment by clobber** [comment]
#2000
