### ISSUE TITLE
Mednafen Core Issue

### ISSUE THREAD

**Issue by woodlandtech** [OpenEmu/OpenEmu#2108]
(Quick preface, this is my first time in years compiling any applications, so I may not be 100% up to speed on terminology)

I went ahead and compiled a build of the experimental software this morning so that I could get save states and disc changing working for Playstation games. However, when I go to launch a Playstation game, it pops up an error saying "Couldn't communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again."

<img width="422" alt="screen shot 2015-10-18 at 4 09 04 pm" src="https://cloud.githubusercontent.com/assets/15165689/10564624/c214f15a-75b2-11e5-8118-4ddf2383e4b2.png">

Relaunching the application like it recommends doesn't help anything. t've managed to trace that back to the core file: if I replace the Mednafen core with the one from the downloadable experimental build, the games launch fine, albeit without the added functionality.

I'm running El Capitan and the latest version of Xcode. Is there a possibility for a compatibility issue? Or is there something simple I'm just plain missing?

Thanks!

**Comment by clobber** [comment]
New builds of Mednafen require the latest OpenEmu which is currently in a state of chaos because we are redesigning the UI, so things are broken. No one should be compiling this right now.

Just wait until next release, it'll be out soon.

**Comment by woodlandtech** [comment]
Sounds good, thanks for the clarification!
