### ISSUE TITLE
Application hangs when trying to add local cover art

### ISSUE THREAD

**Issue by Techmaster37** [OpenEmu/OpenEmu#2109]
There may be something more to this as many of my .smc roms (no worries, legal) failed to download cover art, including Super Mario World which I would think to be a no brainer in the cover art database.

**Comment by clobber** [comment]
Been fixed. Wait until next release (soon) for the patch.

#1993

**Comment by clobber** [comment]
Oh, also

> .smc roms (no worries, legal) failed to download cover art

You obviously didn't dump them yourself :)

Cover art not downloading for .smc ROMs is a dead giveaway for the 512 byte copier header on very old sets. Try .sfc ROMs instead or [remove the copier header](https://github.com/OpenEmu/OpenEmu/issues/1146#issuecomment-74404878) yourself:

Alternatively, you can drag and drop art files directly onto the games in the library.

**Comment by Techmaster37** [comment]
Thank you for the information and the speedy response!
