### ISSUE TITLE
CANT SAVE IN GAME - POKEMON PLATINUM - OPENEMU

### ISSUE THREAD

**Issue by frankzane42** [OpenEmu/OpenEmu#2110]
Since i started the game, I only saved by using the native resource in game, like, 3 times, and then I just saved by the emulator resource, and now Im at some part that I need to save in game to continue, but everytime that a tried the game crashes. And when I start the game, it starts at the last time that a saved in game, and then I need to load the emulator save.

Please, help me, and sorry about the english, I cant speak very well :/

**Comment by clobber** [comment]
Pokemon games with Desmume are officially unsupported as stated by their own dev team.

Anyway, this is a bug with Desmume using the JIT. Sorry, nothing can be done about it. I'd recommend using standalone Desmume app which has the JIT off by default and the game may work properly.

**Comment by frankzane42** [comment]
so, is it impossible to convert the OpenEMU save to DeSmuME save(.dsv)?
because when I load the .dsv save I can save normally. The problem that im
having its only with the openemu save...

2015-10-19 21:31 GMT-03:00 clobber <notifications@github.com>:
