### ISSUE TITLE
choppy graphics, 2014 rMBP yosemite

### ISSUE THREAD

**Issue by psik** [OpenEmu/OpenEmu#2111]
I havea  2014 retina macbook pro runing Yosemtie 10.10.5 and latest versino of open emu, I have the Intel Iris graphic card in the retina macbook pro, some games the graphics are a bit choppy like parts the bodies of the enemies appearing/disappearing very briefly, or just choppiness sometimes, it varie,s i have tried several different filters. So far I have only tried NES games. I am trying to attach spindump as wel lbut i first require permission. Thanks.

**Comment by clobber** [comment]
NES games? Um, you are describing a [hardware limitation](http://wiki.nesdev.com/w/index.php/Limitations) when there are too many sprites on screen so they flicker.

**Comment by psik** [comment]
Yes, I see, so this has to do with the weaknesso f the graphic card itself essentially, right? Fair to say almost any mac suffers from this problem? Or doe the 15" macs handle it fine cause of their strogner graphics?

**Comment by psik** [comment]
NEver mind i see this is inherent to the genre/system itself (i.e. NES). Sorry got it. thnaks.
