### ISSUE TITLE
Unable to open compiled OpenEmu

### ISSUE THREAD

**Issue by djLarrikin** [OpenEmu/OpenEmu#2115]
After a successful build using "sudo xcodebuild -workspace OpenEmu.xcworkspace -scheme "Build All + Experimental" -configuration Release" I am getting a "You can’t open the application “OpenEmu.app” because it may be damaged or incomplete." error when I try to open the app.

I am running El Capitan which I suspect may be part of the problem.

**Comment by clobber** [comment]
>I am running El Capitan which I suspect may be part of the problem.

Nope.

Try a clean build and do it again. Everything compiles (and launches) here fine.

**Comment by mrvacbob** [comment]
The OE project doesn't code sign the app, so it can't be "damaged". Make sure you're running the copy you think you are, then check the output of:
'''
> codesign -dvvv       DerivedData/OpenEmu/Build/Products/Debug/OpenEmu.app/Contents/MacOS/OpenEmu 
DerivedData/OpenEmu/Build/Products/Debug/OpenEmu.app/Contents/MacOS/OpenEmu: code object is not signed at all
> spctl --assess -v DerivedData/OpenEmu/Build/Products/Debug/OpenEmu.app
DerivedData/OpenEmu/Build/Products/Debug/OpenEmu.app: rejected
source=no usable signature
'''

Also, maybe your system is set to high security (System Prefs -> Security -> General -> Allow apps from: Mac App Store only)?

**Comment by djLarrikin** [comment]
Is there also supposed to be an OpenEmu.app in the Debug folder as well as there is nothing in that directory but there is in my release directory? 
There was no OpenEmu folder in the `DerivedData/OpenEmu-ebghdzwpmhxwzaanepocnoqkweab/Build/Products/Release/OpenEmu.app/Contents/MacOS` folder. Running the second command resulted in 
`$ spctl --assess -v Build/Products/Release/OpenEmu.app
Build/Products/Release/OpenEmu.app: accepted
source=no usable signature
override=security disabled`

**Comment by mrvacbob** [comment]
As long as it's the one you're running it doesn't matter what the path is. I don't understand how you could get an error if spctl says "accepted" / "no signature", though.
