### ISSUE TITLE
How to play Dreamcast games with the new core Reicast

### ISSUE THREAD

**Issue by igarikoitz** [OpenEmu/OpenEmu#2116]
I compiled the last code of OpenEmu and I have a new core named Reicast (Dreamcast emulator). How can I play a game? I have the files dc_boot.bin and dc_flash.bin, but i don´t know where is the right place to put them.

**Comment by rochev22** [comment]
Same question! 

P.S. It's very cool guys that you have added this core to play Dreamcast games!!! Many thanks!!!

**Comment by drewthatgamer** [comment]
@igarikoitz You should put them in User->Library->Application Support->OpenEmu->BIOS

**Comment by rochev22** [comment]
https://github.com/drewthatgamer Not work! A message appears - "The operation couldn’t be completed. OpenEmu could not find a Core to launch the game". Help!

**Comment by drewthatgamer** [comment]
@rochev22 Oh, you're having THAT problem. You need to go into your Preferences and download the Core.

**Comment by rochev22** [comment]
@drewthatgamer How? I go to preferences and there is no dreamcast or reicast in CORE section.

**Comment by drewthatgamer** [comment]
@rochev22 Hmm, it may be because there is no official core for it just yet. You may need to wait for the next stable OpenEmu to be released.

**Comment by rochev22** [comment]
@drewthatgamer OK, thanks for help!

@igarikoitz Do you have Reicast core in CORE section in Preferences?

**Comment by igarikoitz** [comment]
@rochev22 If you compile the last github code of OpenEmu with Xcode, you will have the Reicast core.
Thank you @drewthatgamer, now I have Dreamcast running on OS X El capitan!

**Comment by rochev22** [comment]
@igarikoitz ok, i'll try! Thanks!

**Comment by drewthatgamer** [comment]
Since you guys built the newest version, I was wondering if you could answer my question. #2117

**Comment by igarikoitz** [comment]
Thanks OpenEmu developers!
![new openemu screenshot](https://cloud.githubusercontent.com/assets/4145129/10711965/fb84273e-7a8b-11e5-9d05-c0ac781655df.png)

**Comment by drewthatgamer** [comment]
@igarikoitz can u get that to work if ur not on 10.10? My school computer doesn't let me update.

**Comment by clobber** [comment]
We *just* added this as a new core experiment, so it's far from ready yet guys.

Please, no issues opened about this.
