### ISSUE TITLE
Unable to build latest OpenEmu

### ISSUE THREAD

**Issue by drewthatgamer** [OpenEmu/OpenEmu#2118]
Anyone know how to fix this problem? I can't seem to fix it.
![60fcd733e144aa595077bf40980de015](https://cloud.githubusercontent.com/assets/5677214/10713020/eb5e3f68-7a7a-11e5-82d7-674140e477d0.png)

**Comment by mrvacbob** [comment]
Did you actually build it? There will be some false errors if you just open the workspace.

**Comment by drewthatgamer** [comment]
@mrvacbob it tells me the build failed, so I don't think so.

**Comment by mrvacbob** [comment]
What's it look like after that? Your screenshot can't be from after a build, since there would be a lot of warnings from the different cores showing up.

**Comment by drewthatgamer** [comment]
@mcvacbob That's it. That's all it shows me.

**Comment by clobber** [comment]
Yeah, I mean you either didn't pull down the submodules (cause SDK is missing) or that is a temp Xcode glitch. Check the compile guide in the wiki and also try doing a clean build.
