### ISSUE TITLE
JJBA Not Opening At All

### ISSUE THREAD

**Issue by SupahBawz1009** [OpenEmu/OpenEmu#2120]
I've downloaded a rom of a certain game, JoJo's Bizarre Adventure. I try and open item but nothing happens, at all. No error message, no black screen, nothing. This is a Playstation game. Here's the thing. It's nothing with my computer, since it can run another Playstation game, Mega Man X4. It's not the rom, since my friend downloaded the same .BIN file on the same site as mine, only on windows, and his works. When I put in the code that has been used before for other cases like this, the game loads, but it's a black screen, and I have to force quit the app. I load up the console, and this is what it says:
10/26/15 6:15:15.713 PM OpenEmuHelperApp[6677]: parent application is: OpenEmu
10/26/15 6:15:16.324 PM OpenEmuHelperApp[6677]: Some shit about the game.
10/26/15 6:15:16.370 PM OpenEmuHelperApp[6677]: ROM did not load.
10/26/15 6:15:16.371 PM OpenEmuHelperApp[6677]: Deallocating proxy: <OEThreadProxy 0x7feac3db1980, target: <MednafenGameCore: 0x7feac3c81600>>
I can't find any way around this.
Can anyone provide me advice on how to play the game?

**Comment by clobber** [comment]
This comes down to either wrong BIOS files or something bad with your disc rip, so check our wiki for guides on both subjects.
