### ISSUE TITLE
Allow all users access to ROMS?

### ISSUE THREAD

**Issue by i621148** [OpenEmu/OpenEmu#2121]
I have installed many ROMS available to me under my Mac OS X user name but I want to be able to let my son play under his user name without reinstalling all the ROMS.

Is there a way to allow a shared folder as the storage point of the ROMS?

**Comment by i621148** [comment]
This issue can be closed.  I just opened a terminal and cp -r /Users/xxx/Library/Application\ Support/OpenEmu/ //Users/Shared/
Then under Preferences>LIbrary>Game Library Folder Location I set the location to:
//Users/Shared/OpenEmu
for myself and also my son.

**Comment by i621148** [comment]
After logging in with the other user name then I was not able to add the shared location as the library location without deleting it.

**Comment by clobber** [comment]
If you checked library preferences, you'd find you can change your game library location.

**Comment by drcreek** [comment]
I'd just like to add I set my game library as a folder in iCloud Drive. Now library syncs with all my computers. This library option is great.
