### ISSUE TITLE
Changing library location crashes OpenEmu?

### ISSUE THREAD

**Issue by JesseLeite** [OpenEmu/OpenEmu#2124]
Changing library location crashes OpenEmu.  It hangs, and I have to Force Quit.

![screen shot 2015-10-28 at 2 55 24 pm](https://cloud.githubusercontent.com/assets/5187394/10799588/fe6b4a7c-7d83-11e5-8fbe-90c81c44a23c.png)

I'm on a fresh install of El Capitan.

**Comment by clobber** [comment]
Fixed for next release.

#2000

**Comment by JesseLeite** [comment]
Oh awesome, thank you :)

Also, if I wanted to sync a library and game save states between two machines, would it be bad idea to have library in iCloud drive or Dropbox?  Any downsides to this?
