### ISSUE TITLE
D-Pad of SteelSeries Nimbus not recognized

### ISSUE THREAD

**Issue by ddribin** [OpenEmu/OpenEmu#2127]
I got a SteelSeries Nimbus for my Apple TV, but it also works on OS X:

https://steelseries.com/gaming-controllers/nimbus

Unfortunately, the D-Pad is not recognized. The button presses are ignored when trying to set it up as an NES controller.

**Comment by clobber** [comment]
Heya. Anytime someone has had a weird issue with input we usually give them a [modified](https://github.com/OpenEmu/OEHIDBrowser) version of your old HIDBrowser app that can export a plist of the device's profile and elements so we can take a look: http://cl.ly/2K1K400t0H3p - you can attach that or a screenshot would be fine I think.

Also, if you enable [debug prefs](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Secrets) there is an option to enable logging for HID events which may or may not spit anything out in console when you press that D-Pad. Maybe button presses are getting mapped as something other than `kHIDPage_Button`? Code for HID lives over in our SDK if you want to poke around: https://github.com/OpenEmu/OpenEmu-SDK

It looks like earlier in the year, someone reported that the D-Pad on the SteelSeries Stratus XL was also not working with our app, so it sounds like something weird is going on there.

**Comment by kremer-io** [comment]
same issue here

![hidbrowser_nimbus](https://cloud.githubusercontent.com/assets/1693067/10864035/96de46e8-7fe0-11e5-98d7-0d92dbf56dff.png)

**Comment by ddribin** [comment]
Nice to see HIDBrowser still alive and kicking! ;-) Here's my screen shot, too:

![screen shot 2015-10-31 at 9 41 19 am](https://cloud.githubusercontent.com/assets/20428/10864187/90de8596-7fb3-11e5-8999-1b48c1de0782.png)

From a quick look at `OEHIDEventTypeFromIOHIDElement()`, it's not handling `kHIDPage_GenericDesktop` + `kHIDUsage_GD_DPadUp/Down/Right/Left`.

**Comment by ddribin** [comment]
I can get it working by putting this at the end of the `case kHIDPage_GenericDesktop` + `switch(usage)`:

```objc
                case kHIDUsage_GD_DPadUp :
                case kHIDUsage_GD_DPadDown :
                case kHIDUsage_GD_DPadRight :
                case kHIDUsage_GD_DPadLeft :
                    return OEHIDEventTypeButton;
```

But then they show up as  Button 144 - 146.

It seems like there ought to be a an `OEHIDEventTypeDPad` or something. I tried going down that rabbit hole, but couldn't get it working easily, so I stopped. ;-)

**Comment by ddribin** [comment]
And I'm curious, does the modified HIDBrowser use the new HID API or still use DDHidLib?

**Comment by clobber** [comment]
Hrm `kHIDPage_GenericDesktop`, reminds me of a PR where someone was having issues like this. See if what he was working on is any use to you getting it working further: https://github.com/OpenEmu/OpenEmu-SDK/pull/6#issuecomment-150851589

Modified HIDBrowser is still using DDHidLib.

**Comment by clobber** [comment]
@ddribin Okay, so we're looking at the additional `kHIDPage_GenericDesktop` buttons including Start and Select. From your screenshot, am I right in assuming the D-pad is actually analogic? I see the min/max values are 0 - 255 instead of being a 0 or 1. We'll fix this in time for next release (coming soon!), just want to make sure we're handling all situations.

Also, they showed up as button 144, etc, probably because 0x90 == 144 which is the value of `kHIDUsage_GD_DPadUp`.

**Comment by gio-dude** [comment]
so i had same issue with [HORIPAD ULTIMATE](http://www.apple.com/shop/product/HJ172ZM/A/horipad-ultimate-wireless-game-controller?fnode=a1b44f6f46baf1fd122713a8c94afd997d353dda6af79828673a463ad18642c1e9a74bd7de3e7b1e40cb56662f84883186abf673371b327dc3c5aa80b2018972baffe797556b7c1647c205cec9f265ef700085e447a23bab992b33302947e259) dpad didn't work all other button did. I loaded up steam to see if it was just open emu same issue no dpad. 

don't know if this helps

**Comment by ddribin** [comment]
@clobber By analogic, I assume you mean unpressed reports 0 while pressed reports 255? I won't have the device available until this weekend to try out, but I'll post an update when I can.

**Comment by clobber** [comment]
Thanks! For analogic I mean 0 when it's off and 255 when it's at the maximum, but may be possible to have multiple states likes a 'trigger' depending on how much pressure. I don't know if the d-pad on that device is pressure sensitive or not (never heard of that for a d-pad before), but the 0 - 255 values made me curious.

**Comment by clobber** [comment]
Alright I just fixed this here https://github.com/OpenEmu/OpenEmu-SDK/commit/565527c931964aa70a2707b0383765df2209f990

Will be able next release! Thanks for reporting.

**Comment by clobber** [comment]
Oh, and since this device might get popular due to the new ATV I'll probably add it to our automap database so one doesn't have to bind controls.

**Comment by ygbr** [comment]
@clobber I can confirm that the DPad is indeed pressure sensitive. I have tested with the HIDBrowser watching events on the DPad buttons and the values increase with more pressure on the dpad buttons.
It would be really awesome to have this controller automapped ;) thank you for the quick fix.

**Comment by Hakuhatsuboi** [comment]
@clobber For some that doesn't know any code, how difficult is it  to fix the DPad not working? I really like the controller and OpenEmu, but the DPad not picking up is less than ideal.

**Comment by dlutsch** [comment]
I've also been trying to get this working with no luck. Would love to know how to get the DPad working

**Comment by ddribin** [comment]
@clobber I can confirm that the D-Pad is analog. And I can confirm that this fix works. Thanks!

**Comment by clobber** [comment]
@ddribin Thanks for confirming.

By the way, could someone do me a huge favor and use this app https://transfer.sh/1fGPA5/joystick-and-gamepad-tester.dmg to generate some output for the device e.g. Button A = HID button 5, etc, etc?

Here is an example from someone that did it for their Stratus XL, which I'm betting is just like the Nimbus: http://pastie.org/10646225

I'm going to set up automapping for this device so if someone can do this ASAP, I need it for Tuesday. Sorry about the short notice :\

**Comment by ddribin** [comment]
Attached. Note that the D-Pad does not show up there at all.

[Nimbus.txt](https://github.com/OpenEmu/OpenEmu/files/69301/Nimbus.txt)

**Comment by nickmodernized** [comment]
Hey all,

I've opened a new issue that may be just me...would like some confirmation and testing from some of you other Nimbus owners out there:

https://github.com/OpenEmu/OpenEmu/issues/2277

TIA!

**Comment by ddribin** [comment]
FWIW, I can use R1 in both HID Browser and OpenEmu v2.0.1.
