### ISSUE TITLE
Import of multi-disc PSX via m3u file doesn't copy bin/cue files along with m3u file

### ISSUE THREAD

**Issue by DarwinAwardWinner** [OpenEmu/OpenEmu#2130]
With the current master (0460901683a89d67848beecfa10dc2c3bdb2c4c8), I tried to import a multi-disc PSX game by creating the proper m3u file and dragging it into OpenEmu. It imported, but it only copied the m3u file into the appropriate folder, and attempting to launch the game did nothing. After I manually copied the bin and cue files into the same filter that OpenEmu had put the m3u file in, the game launched normally with proper multi-disc support. So it seems that OpenEmu is forgetting to copy the supporting files for multi-disc games in m3u format.

**Comment by Headrush69** [comment]
I don't think that functionality is included.
At least according to https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games it would seem copying the individual cue sheets first is the normal procedure.

**Comment by clobber** [comment]
Right.
