### ISSUE TITLE
Add UI to control screen features of Nintendo DS core

### ISSUE THREAD

**Issue by gingerbeardman** [OpenEmu/OpenEmu#2131]
A year on and I'm still hungry for UI to control screen features of the Nintendo DS core.

Most notable rotated display aka "side by side" screens.

> 2014-11-19 01:49:25
> rogerman
> I discussed the issue with clobber on IRC, and there was a misunderstanding on how the NDS screen features were implemented. He now understands that the NDS screen features are implemented purely within the frontends, and that the DeSmuME backend doesn't handle the NDS screen features at all. Keep in mind that DeSmuME's OpenEmu plug-in only contains the backend code. There is no frontend code present in the plug-in. OpenEmu exists to provide that frontend for DeSmuME.
So I want to state for the record that it's not that I'm withholding these features from the plug-in -- it's just that I can't add them there. The NDS screen transformation code doesn't exist in the DeSmuME backend code, and it wouldn't be appropriate to put it there. As zeromus has already posted, these features are supposed to be handled by the frontons.

Also see:
"Support rotate display feature of DeSmuME" https://github.com/OpenEmu/OpenEmu/issues/1714
"Allow real-time video configuration changes whilst emulator core is running" https://github.com/OpenEmu/OpenEmu/issues/721
"Show DS screens side by side" https://github.com/OpenEmu/OpenEmu/issues/597

And:
"Closing, since this is an issue related to the OpenEmu UI, not with DeSmuME."
http://sourceforge.net/p/desmume/feature-requests/141/

**Comment by clobber** [comment]
Pull requests welcome 8)
