### ISSUE TITLE
Desmume x432r

### ISSUE THREAD

**Issue by RubixCraft** [OpenEmu/OpenEmu#2132]
Desmume x432r is mod for desmume. It's windows only, but I think it'd be AWESOME if you would be able to put it into OpenEmu as a filter or source. here's a link to (what I think is) the original post http://shikaver01.webcrow.jp/

**Comment by clobber** [comment]
No, that would be a mess to integrate. We'll wait for high res texture support from official Desmume.

**Comment by RubixCraft** [comment]
Okay, I understand.
