### ISSUE TITLE
Freezes on Library selection

### ISSUE THREAD

**Issue by Juice805** [OpenEmu/OpenEmu#2134]
When I try and select a new library, either by holding alt while opening the app or going through preferences, the program freezes until force quit. It never brings up any finder selector, it freezes after the button is pushed and remains highlighted. 
On El Capitan. 

Is there anyway in the meantime I can directly edit the location of the library? I modified the Plist in ~/Library/Preferences but it is overwritten on launch

**Comment by clobber** [comment]
#2000

**Comment by Juice805** [comment]
Whoops, didn't see the closed section. Thanks
