### ISSUE TITLE
GUI Lockup

### ISSUE THREAD

**Issue by bronzedragon** [OpenEmu/OpenEmu#2137]
GUI lockup when trying to add games to library or update Box art.

Date/Time:       2015-11-05 22:20:06 -0500
OS Version:      Mac OS X 10.11.1 (Build 15B42)
Architecture:    x86_64
Report Version:  22

Command:         OpenEmu
Path:            /Applications/OpenEmu.app/Contents/MacOS/OpenEmu
Version:         ??? (1.0.4)
Parent:          launchd [1]
PID:             20899

Event:           hang
Duration:        1.00s (process was unresponsive for 89 seconds before sampling)
Steps:           10 (100ms sampling interval)

Hardware model:  MacPro3,1
Active cpus:     8

Fan speed:       607 rpm

**Comment by clobber** [comment]
*Please* search, we have been getting dupe issues for this a lot. Fixed for next release

#1993

#2000

**Comment by bronzedragon** [comment]
Thanks.
