### ISSUE TITLE
cheats on psp and ps1

### ISSUE THREAD

**Issue by guilliano111** [OpenEmu/OpenEmu#2138]
Help i can't use cheats on ps1 and psp why is that??????

**Comment by clobber** [comment]
Sorry, cheats are unavailable for both of those systems. If they were available, you would see the menu item enabled for them.

**Comment by brianmcdoogle** [comment]
Congrats on the 2.0 release! 
Sorry for responding in this closed thread, but is there a reason why cheats are disabled for them? I thought cheat codes were available in Mednafen and PPSSPP? Or is it just not yet ready for prime time?

**Comment by Miail** [comment]
Sorry for  commenting on this closed thread.  The issue you are refering  to refers back to the same issue.. this one. PPSSPP does support cheat, but the option has be enabled outside the game, and not inside the game..

**Comment by Mohammed6155** [comment]
> Sorry, cheats are unavailable for both of those systems.
I know RetroArch has it.
