### ISSUE TITLE
how can I change the SENS core to SNES9x 1.50 or earlier version

### ISSUE THREAD

**Issue by memere** [OpenEmu/OpenEmu#2139]
Em... I know it's a strange demand.

cause there are bugs (game menu display) when I play Fire Emblem: Genealogy of the Holy War(Chinesize version) on OpenEmu, and someone said: 
>the Chinesize ROM displayed well in SNES9x 1.51 or earlier versions.

Another way is: converted the
`BlockInvalidVRAMAccess`  into  `FALSE`

Begging for help!

**Comment by mrvacbob** [comment]
Can you try Higan?

**Comment by memere** [comment]
you mean play it on another emulation?

**Comment by clobber** [comment]
Not possible.
