### ISSUE TITLE
OpenEmuSystem/OpenEmuSystem.h is missing

### ISSUE THREAD

**Issue by hstriepe** [OpenEmu/OpenEmu#2140]
Does not currently build: "OpenEmuSystem/OpenEmuSystem.h" is missing...

**Comment by clobber** [comment]
Please actually search the issues and please use the compile guide in the wiki.

**Comment by hstriepe** [comment]
Well, I know how to follow instructions and know a fair bit of building product myself...

$ git clone --recursive https://github.com/OpenEmu/OpenEmu.git
Cloning into 'OpenEmu'...
... blah-blah - looks like some stuff is locked for normal mortals:
Cloning into '4DO'...
warning: templates not found /usr/local/share/git-core/templates
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:OpenEmu/4DO-Core.git' into submodule path '4DO' failed

$ cd OpenEmu
$  xcodebuild -workspace OpenEmu.xcworkspace -scheme "Build All" -configuration Release
...blah-blah

Then the first fatal error at OEPMSystemResponder.h:27:9: fatal error: 
      'OpenEmuSystem/OpenEmuSystem.h' file not found

Result: In file included from /Volumes/Yosemite/git/OpenEmu/OpenEmu/Pokemon mini/OEPMSystemResponder.m:27:
Path to .. /git/OpenEmu/OpenEmu/Pokemon mini/OEPMSystemResponder.h:27:9: fatal error: 
      'OpenEmuSystem/OpenEmuSystem.h' file not found

Same issue I had wild catting on my own. Cloning from git and running Xcode projects are not brain surgery :-)

Please, enlighten me.

**Comment by clobber** [comment]
Not brain surgery yet you are still refusing to read the guide. Even that 'publickey' error is explained right there for you. How much more of my time are you planning on wasting?
