### ISSUE TITLE
Updating a compiled from source version

### ISSUE THREAD

**Issue by JPaquim** [OpenEmu/OpenEmu#2141]
Hello everyone, I don't know if this should go here, but here it goes:

I'm not really familiar with git, nor the Xcode build process, but I thought I could just keep my local version synced to the remote repository by just doing a git pull origin master, and then re-running the xcode build commands. However, when doing this, the build fails midway through, with an error. What is the correct way of telling Xcode to rebuild after pulling from the master repo?

**Comment by cyco** [comment]
After updating the main repositories you have to update the submodules as well. Try this git command 
git submodule update --init --recursive

If it still doesn't work you can try to run a clean all (cmd + shift + k in Xcode, not sure how it's done using xcodebuild).
