### ISSUE TITLE
SNES Emulator Sound Stutter

### ISSUE THREAD

**Issue by la1248** [OpenEmu/OpenEmu#2142]
Hello, I began playing older games on OpenEMU again after about a year hiatus.  I've noticed a stutter or glitch about every 5-15 seconds when playing games using the SNES emulator (noticed with all games so far: Chrono Trigger, Illusion of Gaia, Final Fantasy II).  

I have tried the following after searching previous issues however the sound glitch still occurs:
- Switching the core from SNES9X (1.53.3) to Higan (0.93.1)
- Switching the filter from Nearest Neighbor to Pixellate

OpenEMU Info:
- OpenEMU v1.0.4
- ![screen shot 2015-11-08 at 12 25 07 pm](https://cloud.githubusercontent.com/assets/15718225/11021828/ae2a06dc-8613-11e5-8ca0-58dac7004fd8.png)

Computer Info:
- MacBook Pro (2010)
- OSX 10.10.4
- 2.4 GHz Intel Core 2 Duo
- 4 GB 1067 MHz DDR3

Let me know if you need any additional information.

**Comment by clobber** [comment]
Already fixed for next release, due out soonish.
