### ISSUE TITLE
gzip support

### ISSUE THREAD

**Issue by qmr** [OpenEmu/OpenEmu#2144]
I cannot add gzip'd files to OpenEmu.  Files add without issue after uncompressing.

**Comment by cyco** [comment]
Can you give us some more info on those files? What's the file extension, how many games are inside, can you extract them using other tools, etc

**Comment by qmr** [comment]
1 file per game.  

Example file:  macbook:USA qmr$ file Legend\ of\ Zelda\,\ The\ -\ A\ Link\ to\ the\ Past\ \(U\)\ \[\!\].smc.gz
Legend of Zelda, The - A Link to the Past (U) [!].smc.gz: gzip compressed data, was "Legend of Zelda, The - A Link t", from Unix, last modified: Thu Sep  2 15:51:35 2004, max compression
macbook:USA qmr$

**Comment by jschrab** [comment]
I believe this is still an issue with 2.0.1. Specifically, for a Coleco CrabEmu core game, only uncompressed files work. File name is of the format <gamename>.rom.gz
