### ISSUE TITLE
Import Battery Saves to self-build application

### ISSUE THREAD

**Issue by MathGrelck** [OpenEmu/OpenEmu#2145]
Hi All

Thank you for creating such an amazing emulator! But I'm thursty for all the new features, so I decided to do a build my self of the latet release here.
After building the OpenEmu Experimental, the app cannot seem to recognize any of my old battery saves located in  
```
~/Library/"Application Support"/OpenEmu/"Save States"/Mednafen/"Battery Saves"/
```
Simple drag&drop of the .mcr files doesn't work either.
How can I do this? 
Thanks in advance!

// Mathias

**Comment by clobber** [comment]
Sorry, please wait for next release which should be soon.
