### ISSUE TITLE
OpenEMU forgets controller mapping on exit

### ISSUE THREAD

**Issue by magnifymobile** [OpenEmu/OpenEmu#2149]
I am running OpenEMU experimental version, I also had the same problem with the regular version as well.  So far I have 2 NES, 2 SNES and 2 N64 controllers connected.  After I map my controllers and exit the controllers no longer work.  It's as if the program is forgetting which controller is which.  So I have to open up preferences and select them again (always returns to keyboard).  I have tried everything to make sure things are consistent as possible.  I always leave the controllers plugged in, the same ports all the time.  Once I select them they all work, two player modes, etc. I've tried searching and cannot find any kind of fix for this.

**Comment by clobber** [comment]
OpenEmu remembers mappings. There may be a problem with your particular setup but you haven't provided any details on your devices.

**Comment by magnifymobile** [comment]
Running Yosemite 10.10.5
2 SNES Controllers connected via mayflash usb converter
2 N64 Controllers connected via Mayflash usb converter
2 NES USB controllers (not real NES, these are actual USB controllers)

Not sure what other details I should provide.

**Comment by magnifymobile** [comment]
I did the following:

1. Updated to El Capitan
2. Compiled the latest source + experimental

Still won't remember the mappings.  I set up all of the controls for NES, SNES and N64, they all work fine (both 1st and 2nd player).  After exiting and coming back in they are all forgotten and have to be remapped.  Also I noticed some funny behavior when I am mapping.  For instance I selected SNES, player 1, then selected USB Gamepad 1 (which is my SNES player 1 controller).  When I press a button it automatically jumps to player 5.  Others will jump to player 3 or something weird.

**Comment by clobber** [comment]
Sorry, I won't be able to troubleshoot this for you -  I don't have any of those devices. Mayflash-type adapters and USB hubs have always had problems. Input works best when you are using a USB HID-compliant device plugged directly into your machine.

**Comment by magnifymobile** [comment]
They are HID compliant.  I think the issue might be that perhaps OpenEMU does not utilize the USB Location ID.  If they were to incorporate this into the code, where the location ID would be used as a part of differentiating the different controls then this would most likely clear up any issues such as this.  For me it seems more like an issue where the settings are not being saved.  After the controllers are mapped they all work, so no issue there.  But after reload the settings have cleared.

**Comment by clobber** [comment]
Are you sure your issue isn't related to #1787?

**Comment by clobber** [comment]
Also, in my previous reply I meant that actual gamepads plugged in directly work best, not ones through multi-port adapters and/or hubs such as your situation. Keeping track of the port location doesn't make a lot of sense because the front end should be able to recognize a regular gamepad plugged into any port.

**Comment by magnifymobile** [comment]
I just looked at issue #1787 and yes I believe that is on the right track. Now that I think about it I have noticed that many times I have noticed that the order of devices will change on restarts.  I noticed that someone indicated that this issue will not be fixed, but that he made the necessary changes and he references this link: https://gist.github.com/cyco/b72d381a089c24d53351

So is he saying that he did fix this issue, but the fix won't be released, only at the above link.  I already compiled the source on my machine, so I suppose I am halfway here. Is the above link something that I would incorporate into the source and recompile?  Is that something you can walk me through if so?

**Comment by magnifymobile** [comment]
bump

**Comment by clobber** [comment]
#1787

**Comment by clobber** [comment]
You are going to want to google how to apply a diff patch. That's all the assistance we can provide.
