### ISSUE TITLE
after trying to compile Openemu

### ISSUE THREAD

**Issue by Thundar73** [OpenEmu/OpenEmu#2150]
I deleted everything I tried to compile.  Then I went on the experimental Openemu & tried to play a few games...but some of the consoles don't work now.  Sega CD, Genesis, Master System, & TG-16 games do not work now...every other console works.   It says this if I double click on a game from one of those 3 consoles

"Couldn't communicate with a helper application....Try your operation again...etc."

Did I delete something with all the compile work I did that I shouldn't have?

Thank you for your time.

p.s. when I try to go to Preferences-Library, & click the change button, it stalls.  I've deleted the app & tried again, but the same things happen.   Do I have to delete the whole Openemu folder (minus rooms) in Application Support & start over fresh?

**Comment by mrvacbob** [comment]
'Couldn't communicate with a helper application' means a crash. Look for crash logs in ~/Library/Logs/DiagnosticReports/ and post them here.

Also, yes, maybe you do need to.

**Comment by Thundar73** [comment]
I tried everything, still gives me "Couldn't Communicate...." thing.  I deleted Xcode, everything relating to OpenEmu.  Now all the games don't work...but I tried them on Kega Fusion (the Sega ones) & they work, so I'll just use these stand alone emulators I think.

**Comment by mrvacbob** [comment]
Can't help you without the crash log files.

**Comment by Thundar73** [comment]
closed this?  your so much help ty P
