### ISSUE TITLE
MAME hangs up when trying to resume games

### ISSUE THREAD

**Issue by ckpopenemu** [OpenEmu/OpenEmu#2152]
openemu 1.0.4
mac osx 10.11

if i ever choose to continue a game where i left off, openemu hangs indefinitely and i have to force kill the process.

i am just using MAME games/roms

**Comment by clobber** [comment]
Gotta use the search.

Already fixed for next release. #1124

**Comment by ckpopenemu** [comment]
Awesome. Any idea about when we can expect the next release?
