### ISSUE TITLE
pal park 

### ISSUE THREAD

**Issue by guilliano111** [OpenEmu/OpenEmu#2153]
how can i use pal park on openemu??

**Comment by clobber** [comment]
Sorry but I have no idea what you are talking about.

**Comment by takeshineale128** [comment]
PalPark is where you get Pokemon Transferred from Ruby, Sapphire, Emerald, FireRed & LeafGreen. I don't think is posable.

**Comment by clobber** [comment]
Considering there is no transfer or link cable support, it should be obvious this is not possible unless you use cheat codes. Sounds like cheats is your best bet.
