### ISSUE TITLE
Can't pair with Wiimote on OSX El Capitan

### ISSUE THREAD

**Issue by MarcoMenu** [OpenEmu/OpenEmu#2154]
Openemu (1.0.4) can't pair with Wiimote on OSX El Capitan.
Can you patch it please?

**Comment by clobber** [comment]
Can you follow the guide please? https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing

**Comment by MarcoMenu** [comment]
Hi Clobber,

obviously I followed that guide first with no results.
I'm able to pair the Wiimote with my MB Pro, but Openemu does not recognize it.

**Comment by clobber** [comment]
I closed the issue because there isn't a problem on our end as I am able to pair a Wiimote on 10.11 by following our guide. I posted a suggestion in your subreddit thread that you also opened.

**Comment by MarcoMenu** [comment]
Ok, can we discuss it there? --> https://www.reddit.com/r/OpenEmu/comments/3swwi3/wiimote_now_working_on_el_capitan/

**Comment by MarcoMenu** [comment]
Fixed uninstalling USB Overdrive: https://github.com/OpenEmu/OpenEmu/issues/1740

Please report this incompatibility on the guide --> https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing

**Comment by clobber** [comment]
Um, so it turns out you have trouble reading after all because the guide already lists "USB Overdrive" as something you need to uninstall. I mean, it's the **4th bullet point** right there in the guide. I cannot make it more clear than that and I do not know how to make people that refuse to read actually read. Perhaps some remedial education?

**Comment by MarcoMenu** [comment]
Sorry, I've read wrong cause text wrapping.
Your rudeness speaks for itself.

The page can be formatted better.

Keep calm and live in peace.

**Comment by clobber** [comment]
Ohhhh now you want to save face by claiming it was a hard to read when you didn't read it in the first place. Your idiocy speaks for itself.

Now, if you don't mind...
![1400985439735](https://cloud.githubusercontent.com/assets/1303132/11179388/905db3c8-8c18-11e5-9c1d-2dd3310da51f.jpg)
