### ISSUE TITLE
Won't Recognize 8BitDo SNES30 Gamepad

### ISSUE THREAD

**Issue by TinyOrange** [OpenEmu/OpenEmu#2155]
Hi- 
I recently purchased the SNES30 gamepad, and when I went to set the controls, OpenEmu didn't recognize the controller. I'm playing over bluetooth, and I know it's connected because pressing down on the pad will scroll my pages down.

Thanks in advance!

edit: it does work with the USB plugged in

**Comment by clobber** [comment]
https://www.reddit.com/r/OpenEmu/comments/3siy1o/nes30_pro_problems_el_capitan/ ???
