### ISSUE TITLE
Unable to add Playstation Games

### ISSUE THREAD

**Issue by hstriepe** [OpenEmu/OpenEmu#2156]
I am using the current dev build and have also tried the "experimental" release from the home page.

Playstation BIOS files have been added manually to the ~/Library/Application Support/OpenEmu/BIOS/ folder, drag did not work. I have carefully checked that the MD5s are correct.

Playstation has been enabled in Preferences.

When I drop a CUE/BIN file combo, there is a busy sign for a moment, but files are not copied. Manually copying files into the ~/Library/Application Support/OpenEmu/Game Library/roms/Sony Playstation/ folder also has no impact. I carefully checked for matching file names and cue path content.

There is no entry in console.

**Comment by hstriepe** [comment]
Did a DEBUG compile, but there were no console messages. The scanning dialog popped for short while on the first attempt.

I did notice it placed the BIN file into the Atari 5200 folder!

**Comment by clobber** [comment]
Please follow the guide otherwise using CD systems is going to be quite painful https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games

**Comment by hstriepe** [comment]
Thanks for your patience. I thought, it was following the guide, but discovered another issue I overlooked.

Should the cue sheets be Linux LF or is Windows CRLF ok? This is not in the guide.

Console logging might be useful for debugging issues, even (or especially) if caused by ignorance.

**Comment by clobber** [comment]
The guide states to simply import the cue sheet and nothing else. I cannot make it more clear than that.

If one files the guide to the letter, they will have no problems importing. Additional debug logging will not be added nor useful to cover every possible case where somebody could screw up by not reading.

**Comment by hstriepe** [comment]
Thanks. Got it working. The guide talks about generating cue sheets. Both formats work.
