### ISSUE TITLE
Links to the Higan emulator website need to be updated

### ISSUE THREAD

**Issue by tvler** [OpenEmu/OpenEmu#2157]
It looks like the URL for the Higan emulator has been changed from
http://byuu.org/higan/
to http://byuu.org/emulation/higan/

The link is found in the "Core Provided By..." list that appears when opening an empty game console library that uses the emulator.

<img width="517" alt="screen shot 2015-11-15 at 1 31 32 pm" src="https://cloud.githubusercontent.com/assets/4934193/11171163/e3fe9b8a-8b9d-11e5-8afe-a09295d93bfb.png">

Thank you for making OpenEmu! : )

**Comment by clobber** [comment]
Got it, thanks.
