### ISSUE TITLE
Emu can't see my Ds4 - Bluetooth connected

### ISSUE THREAD

**Issue by Symfox** [OpenEmu/OpenEmu#2158]
Hello everyone,
I'm kinda new to OsX and this forum.
So my Ds4 can only be seen while connected through Usb. And not when connected by Bluetooth.

Hope anyone can help me out.

**Comment by clobber** [comment]
Works for others with official DS4's by following this guide https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-DualShock-Controller-Pairing
