### ISSUE TITLE
iBuffalo/Padix Co. USB SNES controller not recognized after El Capitan

### ISSUE THREAD

**Issue by TehVulpes** [OpenEmu/OpenEmu#2159]
I have an iBuffalo branded USB SNES controller that isn't recognized in the controller settings. It hasn't worked since I've upgraded to El Capitan, but it worked fine in Yosemite. It also still works in other programs.

Don't know if it helps, but running `system_profiler SPUSBDataType` shows this for the controller.
```
Composite Device:
  Product ID: 0x2060
  Vendor ID: 0x0583  (Padix Co., Ltd.)
  Version: 1.00
  Speed: Up to 1.5 Mb/sec
  Location ID: 0x14120000 / 15
  Current Available (mA): 1000
  Current Required (mA): 100
  Extra Operating Current (mA): 0
```

**Comment by clobber** [comment]
Please search before opening a new issue.

#1966

**Comment by TehVulpes** [comment]
Ah, sorry, I only searched open issues. Thank you for your reply.

**Comment by shaneambers** [comment]
the issue hasn't been resolved, so... why are you closing it ?
