### ISSUE TITLE
Hang on changing library location with 1.0.4 on OS X 10.11.1

### ISSUE THREAD

**Issue by AaronMT** [OpenEmu/OpenEmu#2160]
* Downloaded 1.0.4
* Opened `Preferences`
* Clicked change library location
* Hang

Never see the Finder dialog, application requires a force quit.

Nuked all cache, preferences, and application support files related to OpenEmu. Re-downloaded and tried again and still reproduces.

**Comment by clobber** [comment]
*Please* search before opening a new issue. Fixed for next release.

#2000
