### ISSUE TITLE
Issue with Changing Game Library Location

### ISSUE THREAD

**Issue by bkmintie** [OpenEmu/OpenEmu#2161]
Running a fresh install of v1.0.4 on Mac OS X 10.11.1.

When attempting to change the Game Library Folder Location from the application preferences, the OpenEmu will hang.

Application must be force quitted to close.

![screenshot_2015-11-19_21_38_44](https://cloud.githubusercontent.com/assets/1494953/11292702/8f9f5bc6-8f06-11e5-9c8b-61e7e0f77fb7.png)

**Comment by clobber** [comment]
*Please* search before opening a new issue. Fixed for next release.

#2000
