### ISSUE TITLE
Feature Suggestion: Create Game Shortcut in .app form to enable Valve In-Home Streaming

### ISSUE THREAD

**Issue by drcreek** [OpenEmu/OpenEmu#2162]
With .app shortcuts that open a specific game fullscreen, and assuming the Steam Controller is compatible with OpenEmu. This would allow you to stream games to your TV in 1080p60 with minimal delay. Which would be pretty darn sweet.

**Comment by clobber** [comment]
#401

**Comment by drcreek** [comment]
Not quite the same but a better idea. This would only serve as a band aid solution at best. Thanks. 

Skickat från min iPhone
