### ISSUE TITLE
Icons in the row beneath the game screen are just square white icons now

### ISSUE THREAD

**Issue by ReggieMeme** [OpenEmu/OpenEmu#2163]
OpenEmu v1.0.4, running on a MacBook Pro which is running OS 10.10.4
Using the Pixellate filter
I haven't modified anything in OpenEmu. All I've done is used it to run Final Fantasy 4, The 4 Heroes of Light, and Dragon Quest 9, all of which I got from [removed]. It's worked fine up until today. I've been using OpenEmu for about three weeks. 
This is what the problem looks like on the main screen:
![screen shot 2015-11-20 at 1 31 13 pm](https://cloud.githubusercontent.com/assets/15946054/11308242/12a8e6ac-8f8b-11e5-8ab4-1970e5061a47.png)
And this is what it looks like while playing a game:
![d](https://cloud.githubusercontent.com/assets/15946054/11308322/84aa0cd6-8f8b-11e5-9ba1-cd3eaad16089.png)
It happens when running any game.Clicking on the icons does not do anything. Everything else about the emulator and the games runs fine.

**Comment by clobber** [comment]
Already fixed for next release. You also need to upgrade to OSX 10.11.
