### ISSUE TITLE
Can't add new games, and app crashes when I try to add a game from the File menu

### ISSUE THREAD

**Issue by venkata1994** [OpenEmu/OpenEmu#2164]
I'm sorry if this issue seems very vague, but I've never posted an issue before. I'd be more than happy to post any more information that would help in fixing this problem. I'm running OSX El Capitan. Every time I drag and drop a ROM into the window the app doesn't recognize nor do anything. When I try to add the ROM from the File menu the app just freezes(I've added a screenshot).
![screen shot 2015-11-20 at 22 34 13](https://cloud.githubusercontent.com/assets/12499907/11312523/de7d0c5e-8fd6-11e5-9caf-cb475fdbc098.png)

I came across another issue where it was suggested that programs like f.lux could interfere with the functioning with the app. I have tried closing the app, and it seems to have no effect.

**Comment by clobber** [comment]
Describe what exactly you are drag and dropping into the window. It cannot be a large archive containing multiple ROMs and other files.

As for the file menu dialog hang, that is fixed for next release.

**Comment by venkata1994** [comment]
I have a single game ROM in .7z format. It's around 8 MB.

**Comment by SupahBawz1009** [comment]
You can't drag .7z files into OpenEmu. You need to use an extracted like The Unarchiver to extract the files, and drag the ROM file from the extraction into OpenEmu.

**Comment by clobber** [comment]
They can be 7zipped, they just need to be a single file and nothing else inside the archive.

**Comment by venkata1994** [comment]
Just to clarify, what format is a ROM file supposed to be in? I've only found archives, and the archives contain many game files of a single game.

**Comment by clobber** [comment]
It depends on the system. You have a 7z file presumably containing multiple files. You need to extract it using [The Unarchiver](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) and then drag and drop the ROM file into the OpenEmu window to import it. They could be .nds (Nintendo DS games), .nes (NES games), etc.

**Comment by venkata1994** [comment]
Thanks a ton guys!
