### ISSUE TITLE
Crash on Change Game Library Folder Location

### ISSUE THREAD

**Issue by Reinfeldx** [OpenEmu/OpenEmu#2166]
Hangs as soon as I press the Change button on 1.0.4.

[OpenEmu_2015-11-22-102708.txt](https://github.com/OpenEmu/OpenEmu/files/41087/OpenEmu_2015-11-22-102708.txt)

**Comment by clobber** [comment]
*Please* search before opening a new issue. Fixed for next release.

#2000

**Comment by Reinfeldx** [comment]
My fault. I searched but apparently not good enough.
