### ISSUE TITLE
Core compatibility voting

### ISSUE THREAD

**Issue by drcreek** [OpenEmu/OpenEmu#2167]
I was struggling with Arkanoid for NES this morning. The mouse controls was behaving badly. It was slightly off so the mouse would move more to the side than the paddle would and it was a mind f''k for controlling it accurately.

But then I swapped NES cores. Worked perfectly with Nestopia.

Maybe integrating some kind of voting system for certain games (via OpenVGDB?) for which people had best compatibility with each game and then for new users it automatically uses the core with the most votes?

Might be best to hide the one switch behind the contra code though?

(P.S Before building from source, are there any settings for individual cores I can tweak? Graphic settings and the like or is it best for an amateur not to touch it...?)

**Comment by clobber** [comment]
mmmm...no. The solution would be to resolve whatever input issues were in FCEUX. Nestopia is already the default NES core.

To answer your question: no, there are no core settings to tweak.

**Comment by drcreek** [comment]
Thanks, you make a good point. The inspiration was the settings system from Dolphin. But I guess it makes sense for settings in a single emulator, but not a multi-system emulator like this. Thanks very much!
