### ISSUE TITLE
El Capitan

### ISSUE THREAD

**Issue by gameglaux** [OpenEmu/OpenEmu#2168]
Since upgrading OSX to El Cap, openemu beachballs when showing an expanded file chooser dialogue. I can no longer choose an existing library or create a new one on startup since both options open the said dialogue. Is there any way to remove the dialogue preference or manually add the library path in openemu?

**Comment by diotro** [comment]
I too noticed this happening, specifically in my case when I use the menubar to "Add to Library" while OpenEmu is in FullScreen mode. Just chiming in to see if that has anything to do with it.

**Comment by clobber** [comment]
*Please* search before opening a new issue. Fixed for next release.

#2000
