### ISSUE TITLE
5-player support for TG-16/PCEngine

### ISSUE THREAD

**Issue by rskm1** [OpenEmu/OpenEmu#2171]
The Mednafen core supports the "TurboTap" and has 5 gamepad inputs enabled by default.

But OpenEmu only has TWO players selectable in the controller dropdown.

**Comment by clobber** [comment]
Please search before opening a new issue, this is already fixed for next release.

**Comment by rskm1** [comment]
Whoops, sorry, I read the titles on all 5 pages of existing issues... but I guess those are just OPEN issues.  Thanks!!
