### ISSUE TITLE
10.11.1 iBuffalo Classic USB Gamepad unrecognized

### ISSUE THREAD

**Issue by shaneambers** [OpenEmu/OpenEmu#2172]
worked in previous versions... 

OpenEMU version: 1.0.4
Mac OS X: El Capitan 10.11.1

**Comment by clobber** [comment]
I'm guessing you aren't too bright, which is why you are also posting in other closed issues that link to the original issue with the resolution.

**Comment by shaneambers** [comment]
I'm guessing you have no sense of humor.

**Comment by clobber** [comment]
Being an annoying retard is supposed to be funny?
