### ISSUE TITLE
Suggestion: Replace HUD with toolbar buttons

### ISSUE THREAD

**Issue by romulof** [OpenEmu/OpenEmu#2173]
![Toolbar example](http://i.imgur.com/cvWiU3r.png)
Remove the floating HUD and put the controls on the toolbar/navbar. Benefits:
* Floating controls doesn't interfere with Nintendo DS touchscreen;
* Less code: I don't code for OS X, but I've seen several apps using this feature, so I guess there's an API for that. Oh wait, OpenEmu main window already uses it;
* Controls get hidden in fullscreen until user puts the mouse on top of the screen;

**Comment by robotoad** [comment]
It's a logical suggestion. Currently, there are no codified plans to change the controls bar in time for the next release. My initial reaction is that it might be seen as a drawback for users to have to slide the mouse to the top of the screen in fullscreen mode to access the controls. Additionally, new features may be added to the controls bar that could cramp the titlebar or be infeasible for other reasons. These and other concerns will need to be taken into account when the time comes to evaluate new interface changes.

**Comment by clobber** [comment]
> Floating controls doesn't interfere with Nintendo DS touchscreen;

There is already a menu option to turn off the HUD. Did you see it?

> Controls get hidden in fullscreen until user puts the mouse on top of the screen;

This is by default. Mouse movement triggers the HUD.

Anyway, we can't ditch the HUD because the popout window relies on it.

**Comment by romulof** [comment]
I agree with you, @robotoad. Stuffing things on the title bar is harder. But with little tweaks is possible. For exemple Parallels has done a great work:
![Imgur](http://i.imgur.com/t6DERXB.png)
My real problem is with Nintendo DS games that you have to click on the screen. Then you start moving the mouse the HUD comes over the "touch" part of screen making it hard to click. Ok, that you can hide the HUD, but then you loose save state controls.

**Comment by clobber** [comment]
> Ok, that you can hide the HUD, but then you loose save state controls.

No you don't. There are hot keys for quick saves and also bindable keys for showing the regular save state dialog in control prefs under "Special Keys". There isn't any problem with using NDS games and the HUD that hasn't already been solved.

**Comment by robotoad** [comment]
@romulof Personally, I think that window looks cluttered and off-balance. More to the point, Parallels has different requirements, and a transient HUD is a better fit for OpenEmu's purposes.
