### ISSUE TITLE
OpenEmu (v. 1.4) 'CVDisplayLink' Crash

### ISSUE THREAD

**Issue by jeffpees** [OpenEmu/OpenEmu#2175]
Hey there,

OpenEmu (v 1.4) seems to have crashed and removed a sizable portion of saves from a game that I was playing. This has happened in the past with regards to crashing with the same CVDisplayLink crashed thread. I've included a link to the gist below. 

https://gist.github.com/anonymous/3c5f572166a0bdef43c7

Thanks, Jeff

**Comment by clobber** [comment]
The log is pretty much useless to see what's going on, but likely an issue we've already solved for next release. 

Update to 10.11 (required for next release) and sit tight.
