### ISSUE TITLE
Crashes every time I try to open it

### ISSUE THREAD

**Issue by shaleema** [OpenEmu/OpenEmu#2177]
OpenEmu freezes every time I try to open it. Then I have to force quit it. Please help me. Here is crash report
https://gist.github.com/39c26545d2fcb0f19f9c.git

**Comment by shaleema** [comment]
https://gist.github.com/shaleema/39c26545d2fcb0f19f9c

**Comment by clobber** [comment]
This was already fixed for next release, but you will need to be using OSX 10.11 so I'd advise upgrading.
