### ISSUE TITLE
Open Emu / Mac El Capitain does not recognize Controller 

### ISSUE THREAD

**Issue by MrsDi** [OpenEmu/OpenEmu#2178]
Hi, 
I used to play N64 games on my Mac without any problem. 
Then I made a break, put out the controller and in the meantime I updated from Yosemite to El Capitain. Now I wanted to play again but the controller is not listed and I can not use it. I tried to restart Open Emu, tried an other game, but nothing happens.
What can I do?
Thanks!

**Comment by clobber** [comment]
I am guessing it is an iBuffalo device?

**Comment by MrsDi** [comment]
To be honest I don't know what an i Buffalo device is!
I use an N64 Controller Adapter from "May Flash" (bought it from Amazon) and an original N64 controller. By the way, I live in Germany.

**Comment by clobber** [comment]
Okay, I think I know what the problem was (and it has already been fixed), though you will have to wait until next OpenEmu release or OSX 10.11.2 (whichever comes first). Sorry about that.

**Comment by MrsDi** [comment]
Alright, thank you for your quick reply!

**Comment by Orestisc** [comment]
Hi clobber,
I had trouble with iBuffalo controller and followed the other thread about it.
Now, having updated to 10.11.2, things actually seem to be worst, since it no longer recognizes my Logitech controller either. Is there a solution for it?

**Comment by clobber** [comment]
@Orestisc Not enough information to go on. Does the iBuffalo controller now work on 10.11.2?

Which Logitech controller? Is it the type that has a direct input/xinput switch on the back? Is there any output in console.app when you have it connected and load OpenEmu and go to control prefs?

**Comment by muadibbles** [comment]
fwiw, my iBuffalo controller doesn't work on 10.11.2.

**Comment by Orestisc** [comment]
Hi clobber, thanks for the reply.
The iBuffalo is still not working.
About the Logitech (Dual Action model), I may have jumped the gun on that one, because after restarting to make sure it is now recognized.
So I'm back to the state prior to 10.11.2, where only the iBuffalo is not recognized. Unfortunately that doesn't seem to have been fixed.

**Comment by clobber** [comment]
Looks guys, help me help you. I asked for output that should be found in Console.app when you have your iBuffalo controller connected after launching OpenEmu and opening control preferences. Grab that output and paste it back here.

As for the original issue being fixed in 10.11.2, I have no idea. It was my understanding that it was slated to be fixed so I don't know what's going on. However, the iBuffalo controller **will work** with OpenEmu in our next release regardless.

**Comment by muadibbles** [comment]
Here's my console output from after I loaded openemu. Let me know if you need anything else.

12/12/15 7:22:11.755 AM launchservicesd[91]: SecTaskLoadEntitlements failed error=22
12/12/15 7:22:11.768 AM launchservicesd[91]: SecTaskLoadEntitlements failed error=22
12/12/15 7:22:12.043 AM sharedfilelistd[339]: SecTaskLoadEntitlements failed error=22
12/12/15 7:22:12.047 AM appleeventsd[62]: SecTaskLoadEntitlements failed error=22
12/12/15 7:22:12.070 AM OpenEmu[4217]: OELibraryDatabase loadFromURL: 'file:///Users/Simon1/Library/Application%20Support/OpenEmu/Game%20Library/'
12/12/15 7:22:12.072 AM OpenEmu[4217]: CoreData: Failed to load optimized model at path '/Applications/OpenEmu.app/Contents/Resources/OEDatabase.momd/OEDatabase 1.3.omo'
12/12/15 7:22:12.258 AM OpenEmu[4217]: Apple Internal Keyboard / Trackpad
12/12/15 7:22:12.550 AM OpenEmu[4217]: Device is already being handled
12/12/15 7:22:12.550 AM OpenEmu[4217]: (null)
12/12/15 7:22:12.550 AM OpenEmu[4217]: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
12/12/15 7:22:12.551 AM OpenEmu[4217]: (
	0   CoreFoundation                      0x00007fff88547ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff91928f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8842761e -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 318
	3   CoreFoundation                      0x00007fff8843c66b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	4   OpenEmuSystem                       0x00000001083dae07 -[OEControllerDescription OE_initWithVendorID:productID:name:] + 501
	5   OpenEmuSystem                       0x00000001083da68e +[OEControllerDescription OE_deviceDescriptionForVendorID:productID:product:] + 287
	6   OpenEmuSystem                       0x00000001083d2b18 -[OEHIDDeviceParser OE_parseIOHIDDevice:] + 40
	7   OpenEmuSystem                       0x00000001083d2868 -[OEHIDDeviceParser deviceHandlerForIOHIDDevice:] + 93
	8   OpenEmuSystem                       0x00000001083cd8f2 -[OEDeviceManager OE_addDeviceHandlerForDeviceRef:] + 287
	9   IOKit                               0x00007fff89becc21 __IOHIDManagerDeviceApplier + 153
	10  CoreFoundation                      0x00007fff88436372 __CFSetApplyFunction_block_invoke + 18
	11  CoreFoundation                      0x00007fff8841af80 CFBasicHashApply + 128
	12  CoreFoundation                      0x00007fff8843630a CFSetApplyFunction + 186
	13  IOKit                               0x00007fff89bede86 __IOHIDManagerInitialEnumCallback + 58
	14  CoreFoundation                      0x00007fff884575c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	15  CoreFoundation                      0x00007fff8844941c __CFRunLoopDoSources0 + 556
	16  CoreFoundation                      0x00007fff8844893f __CFRunLoopRun + 927
	17  CoreFoundation                      0x00007fff88448338 CFRunLoopRunSpecific + 296
	18  HIToolbox                           0x00007fff8fa5d935 RunCurrentEventLoopInMode + 235
	19  HIToolbox                           0x00007fff8fa5d76f ReceiveNextEventCommon + 432
	20  HIToolbox                           0x00007fff8fa5d5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	21  AppKit                              0x00007fff939660ee _DPSNextEvent + 1067
	22  AppKit                              0x00007fff93d32943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	23  AppKit                              0x00007fff9395bfc8 -[NSApplication run] + 682
	24  AppKit                              0x00007fff938de520 NSApplicationMain + 1176
	25  OpenEmu                             0x0000000108025f44 start + 52
	26  ???                                 0x0000000000000001 0x0 + 1
)
12/12/15 7:22:15.997 AM WindowServer[189]: send_datagram_available_ping: pid 518 failed to act on a ping it dequeued before timing out.
12/12/15 7:22:16.857 AM launchservicesd[91]: SecTaskLoadEntitlements failed error=22
12/12/15 7:22:16.858 AM launchservicesd[91]: SecTaskLoadEntitlements failed error=22

**Comment by clobber** [comment]
It's the same original bug. Apple has not fixed it, it seems.

**Comment by Orestisc** [comment]
Thanks for taking a look and my bad for not providing the console data earlier. Too bad that bug isn't fixed yet...

**Comment by MrsDi** [comment]
Hi, 6months later and I still have the same problem with my not ibuffalo controller - it is still not recognized by open emu, although I have updated to the latest version now. Is there anything I can do to go on playing? Thanks.
