### ISSUE TITLE
OpenEmu blocks with dialogs with El Capitan

### ISSUE THREAD

**Issue by Marcounet** [OpenEmu/OpenEmu#2180]
Hi!
When I use an system (El Capitan) open dialog in OpenEmu this one blocks and don't open the windows. The only solution is to quit (normally quit) application and restart it. I need the dialog to change the path of the library of roms.

**Comment by clobber** [comment]
*Please* search before opening a new issue. Fixed for next release.

#2000

**Comment by gphilipp** [comment]
@clobber when is the next release due ?
