### ISSUE TITLE
Played yesterday, today doesn't work

### ISSUE THREAD

**Issue by shaleema** [OpenEmu/OpenEmu#2182]
Hello,
yesterday I played an snes game without any problems. started up today, asks me whether I want to resume where I left off. And no matter if I choose yes or no, nothing happens...
Frustrating

**Comment by clobber** [comment]
You need to provide actual details such as which game, which emulator core you think you might be using as well as possible crash logs for OpenEmu and OpenEmuHelperApp in Console.app
