### ISSUE TITLE
support for virtual gamepads

### ISSUE THREAD

**Issue by tristan-k** [OpenEmu/OpenEmu#2183]
On iOS there is [joypad legacy](http://getjoypad.com/legacy/) and on Android there is [node-virtual-gamepads](https://github.com/miroof/node-virtual-gamepads).

Support for joypad legacy is provided through [JoypadConnect](http://getjoypad.com/joypadconnect/JoypadConnect-1.5.2.dmg), but node-virtual-gamepads need the uinput kernel module. Maybe it is possible to integrate node-virtual-gamepads into OpenEmu with a different approach?

**Comment by clobber** [comment]
#924

**Comment by tristan-k** [comment]
This issue also adresses integrating node-virtual-gamepads into OpenEmu. Why it is closed?
