### ISSUE TITLE
Missed icons

### ISSUE THREAD

**Issue by rodsvart** [OpenEmu/OpenEmu#2185]
![2015-12-04 13 53 20](https://cloud.githubusercontent.com/assets/16150456/11588006/8c828006-9a8e-11e5-97d8-adabd024c0a6.png)
![2015-12-04 13 53 39](https://cloud.githubusercontent.com/assets/16150456/11588007/8f9f0dea-9a8e-11e5-8e10-6bff0890aa5d.png)
Somehow the icons of consoles are missed in the main window and the icons in the top part of settings window are moved to the left. Reinstalling doesn't help. I use 1.0.4 version.

**Comment by PlutoX86** [comment]
What might help: Open the Openemu package, go to contents > resources and delete every language folder, except "en.lproj"

**Comment by rodsvart** [comment]
Yep, it helped somehow.

**Comment by clobber** [comment]
#1636
