### ISSUE TITLE
Boxart gloss, black controller mask buttons & cover art sizes

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/OpenEmu#2186]
* Boxart gloss - I don't know why that's gone (for now?), but it should be optional again. -> [Example](https://cloud.githubusercontent.com/assets/10595183/11750978/d474d9b0-a036-11e5-92da-bf7f21f0ae36.png). 

I think it still looks good with your new OE design! ;)

* Button configuration - The controller masks have no transparency. -> [Example](https://cloud.githubusercontent.com/assets/10595183/11667421/e9d2eeec-9df1-11e5-9774-966620c43b16.png). 

I'm not sure why it's there in the first place, because when you exchange it with a transparent placeholder .png before compiling, button configuration looks normal.

* Cover art sizes - Having different sizes/zoom-ins for different consoles would be nice, too. Especially when you only have 2 NES games and 40 Atari5200 ones.. 

* Macros (for Arcade Games) - While it's great to have 'Special Keys' for 'Pause', 'Quick Save', 'Rewind', etc., sometimes i wish i could press all three punch buttons with "L2" (PS3 Pad) for an easier Shin-Shoryuken experience. At least some temporary "Press Button 1-3" & "Press Button 4-6" kind of 'Special Key' (or "Button 1+2, 2+3, 3+4" for Neo-Geo folks), would be nice. 

I'm not sure how hard this is to implement, but i guess it would make a lot of people even happier. ;)

**Comment by clobber** [comment]
1. No :P

2. Cannot replicate here. Please verify this is still an issue with the latest source and provide more details if so.

3. Have that on the list but not sure if we will add that back in.

4. Sorry, not planned right now. Would really complicate the input system.

**Comment by PlutoX86** [comment]
Haha, it's ok. thanks for answering anyway. :) Love your stuff

**Comment by cyco** [comment]
Number 2 looks like a debugging option. Make sure this is unchecked

<img width="535" alt="screen shot 2015-12-11 at 21 14 18" src="https://cloud.githubusercontent.com/assets/697021/11754540/46e94368-a04c-11e5-983a-fa390e6c1a43.png">

**Comment by PlutoX86** [comment]
Thanks cyco!!
