### ISSUE TITLE
No Icon File Images

### ISSUE THREAD

**Issue by glitchninja2000** [OpenEmu/OpenEmu#2189]
Although recognizes ROM files and will run them, it does not assign them default icons. I have made my own custom icons for the OpenEmu emulators I do use (plus Dolphin, since I use it often and am waiting for the core). I'd love to see some nice icons, or maybe a guide on how to add support for it through it's Info.plist (I've visited multiple websites and look at the file myself, but it is formatted differently than I'm used to).
Examples:
![snes file](https://cloud.githubusercontent.com/assets/14809991/11620785/cb02b1a6-9c6a-11e5-8219-d5dc0d0787ab.png)
![snes folder](https://cloud.githubusercontent.com/assets/14809991/11620787/d4622eca-9c6a-11e5-8048-577da6b99063.png)
![snes icon](https://cloud.githubusercontent.com/assets/14809991/11620801/e7533b1e-9c6a-11e5-9361-186ff2c6b1f0.png)

[OpenEmucons.zip](https://github.com/OpenEmu/OpenEmu/files/53538/OpenEmucons.zip)

**Comment by clobber** [comment]
Thanks, but we already have some of these made and have decided not to use them for now.
