### ISSUE TITLE
Cores Missing Icons

### ISSUE THREAD

**Issue by glitchninja2000** [OpenEmu/OpenEmu#2190]
I've noticed some developmental cores don't have there own icons. Instead, they are using the Arcade one. I very easily added icons to most of them, taking maybe 5 minutes for making a good icon,  15 seconds to add it. I'd like to request that they all have there own, and I've even included my icons in .png and .tiff format if anyone wants to use them.
[Core-Icons.zip](https://github.com/OpenEmu/OpenEmu/files/53541/Core-Icons.zip)

Add them by navigating to Library/Application Support/OpenEmu/Cores
Select the core you wish to add an icon to
Right click, Show Package Contents
Go to Contents/Resources, find the icon, replace

**Comment by clobber** [comment]
?

All our systems that need icons already have them in source, coming in next release.
