### ISSUE TITLE
⚑ Feature Request: Add Other Emulators

### ISSUE THREAD

**Issue by glitchninja2000** [OpenEmu/OpenEmu#2191]
I love **OpenEmu**. It's the main emulator I use, and it preforms amazingly. Sadly, it doesn't support everything. I currently am also using [Dolphin](https://dolphin-emu.org/) for my **GameCube** and **Wii** games, and [PCSX2](http://pcsx2.net/download/releases/mac/viewcategory/5-mac.html) for my **PS2** games. I'd love to be able to easily configure **OpenEmu** to run the ROMs through these emulators, maybe even still have added controller support.
I know this is for emulation, but, similarly to [Steam](http://store.steampowered.com/), I'd also like the possibility to run other games, like [Mari0](http://stabyourself.net/mari0/) and [Not Pacman](http://stabyourself.net/notpacman/) off **OpenEmu** too.
![Steam Library](http://i64.tinypic.com/2s9oniq.png)
*Source of Steam Banners from [Booru Banners](http://steambanners.booru.org/index.php).*

**Comment by clobber** [comment]
Knock it off.
