### ISSUE TITLE
NSScroller Styling

### ISSUE THREAD

**Issue by DaveTheOne** [OpenEmu/OpenEmu#2192]
NSScroller in console selection Scrollview is not styled at all. Plain Style. XIB shows two(?) NSScroller objects. I have not found any Outlet connection nor anything regarding Style.

**Comment by robotoad** [comment]
The two scrollers are the horizontal and vertical scrollers of the scroll view. Currently, visual artifacts may manifest if the scroll view inherits a vibrant dark appearance.

**Comment by DaveTheOne** [comment]
Yes, after a closer look I have seen some styling (wood_knob...). Currently I have disabled those Scrollers but main problem remains. And another one is that the initial scanner sometimes misplaces the LibraryScrollView during animation.

**Comment by robotoad** [comment]
Can you post a screenshot of the issue you're describing?

**Comment by DaveTheOne** [comment]
NSScroller behavior seems to be normal.

http://stackoverflow.com/questions/11253949/scroller-background-not-transparent-in-nsscrollview
