### ISSUE TITLE
Adding artwork from file hangs the app

### ISSUE THREAD

**Issue by lavadrop** [OpenEmu/OpenEmu#2195]
Hi.

I just reinstalled El Cap (10.11.2). I deleted an old Sengoku 3 rom I had and replaced it wit a newer copy. I had custom artwork for it before. Now I tried adding it manually and the app just hangs. This are the logs:
[OpenEmu_2015-12-09-001756_Molly.hang.zip](https://github.com/OpenEmu/OpenEmu/files/56424/OpenEmu_2015-12-09-001756_Molly.hang.zip)
[OpenEmu_2015-12-09-002437_Molly.cpu_resource.diag.zip](https://github.com/OpenEmu/OpenEmu/files/56428/OpenEmu_2015-12-09-002437_Molly.cpu_resource.diag.zip)

**Comment by clobber** [comment]
*Please* search, we have been getting dupe issues for this a lot. Fixed for next release

#1993
