### ISSUE TITLE
MAME: allow for different core versions?

### ISSUE THREAD

**Issue by HiPhish** [OpenEmu/OpenEmu#2196]
Hello OpenEmu team,

I just purchased the NeoGeo bundle from Humble Bundle and the game work fine in OpenEmu, but not in standalone MAME. The problem appears to be that ROMs need to be ripped for a particular version of MAME and the standalone version installed via Homebrew is at version 0.168, whereas the OpenEmu core is at version 0.149.
http://wiki.mamedev.org/index.php/FAQ:ROMs

I'm sure the core will be updated eventually, at which point my ROMs won't be able to be played anymore. So the question is, what to do? Not update the MAME core? Update it anyway? Or allow different versions of the MAME core to be installed?

Ideally MAME would have some sort of compatibility bridge for such cases, but I doubt they would do that. Any ideas how to solve this situation?

**Comment by clobber** [comment]
The solution is to just download the NeoGeo games from a MAME 0.149 or compatible romset, pretty easy to find.

**Comment by HiPhish** [comment]
You misunderstood me, the games do work fine *for now*, I was talking about the future. I have been looking for MAME ROMs, but I could never find any site the would list the version of MAME they were dumped for. I have been searching for ROMs compatible with 0.168 but it has been a complete shot in the dark whether a ROM would run (it didn't, and yes I did place the NeoGeo ROM along with it)

**Comment by clobber** [comment]
I think you are misunderstanding. It wouldn't be on us to maintain any sort of compatibility with MAME romsets, those change with the wind and are entirely up to MAMEdev. The paradigm with MAME is to always have the correct romset for the version of MAME you are using. So what you are suggesting is not possible.

**Comment by HiPhish** [comment]
So it is not possible to offer multiple versions of the core as if they were separate cores? I will accept the decision of the OpenEmu team, although I am not looking forward to future updates if that's the case. With other cores it's really simple, just download the latest version and you're good to go.

This is slightly off-topic, but are there any other NeoGeo emulators then that could be made into cores instead?

**Comment by clobber** [comment]
>future updates

You are implying the experimental MAME core plugin will ever be updated and make it out of the 'experimental' cores bundle phase any time soon.

>With other cores

MAME has a complex design and is often complicated to use. MAME also has a lot of users and they all deal with using the latest romsets just fine and somehow manage to acquire those files. They even make cataloging tools to manage and auditing their sets. Look, your particular reservations about versions of MAME really doesn't matter here - we wouldn't be maintaining multiple versions of a core plugin; that's backwards.

To answer your question: no, none that we would be using.
