### ISSUE TITLE
why i cant put the PSX bios in the Game library 

### ISSUE THREAD

**Issue by Swagatron2000** [OpenEmu/OpenEmu#2197]
I try to put the psx bios in the BIOS folder but openemu keeps putting up the same message.

" you need to put the scph 5500,scph 5501, and the scph 5502 in the game library windo

**Comment by clobber** [comment]
We don't tell you to place files directly in the folder. Please [follow the guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files) to import the **correct** files and on-screen directions.

**Comment by Swagatron2000** [comment]
thx
