### ISSUE TITLE
MFi Controller D-Pad not recognized

### ISSUE THREAD

**Issue by gymnastboatman** [OpenEmu/OpenEmu#2198]
With the Steelseries Nimbus and Horipad Ultimate supporting Mac, it's time to fully support MFi controllers. I want my Ultimate to play SNES games and by golly the joystick isn't natural. I need the D-Pad to play, and since these two controllers don't have bowl D-Pads but have Plus ones, They're actually really nice.

**Comment by clobber** [comment]
Same issue as #2127, already fixed for next release.
