### ISSUE TITLE
Steelseries Stratus XL: D-pad not being mapped

### ISSUE THREAD

**Issue by deemee20** [OpenEmu/OpenEmu#2201]
Hi,

Having problems mapping a Steelseries Stratus controller. Client recognises the controller but when I try to map the d-pad nothing happens. All other keys work.
El Capitan v. 10.11.1
<img width="741" alt="screen shot 2015-12-11 at 21 50 09" src="https://cloud.githubusercontent.com/assets/16260613/11755237/346dec3e-a051-11e5-89b1-d4955fe77ba1.png">

**Comment by clobber** [comment]
Please search before opening a new issue. This is already fixed for next release.

#1765

**Comment by deemee20** [comment]
apologies and thank you
