### ISSUE TITLE
Hackintosh OS X Lion with OpenEmu

### ISSUE THREAD

**Issue by lda4life** [OpenEmu/OpenEmu#2202]
Hello,

I apologize if this is an issue that has been rectified but i could not find any info and could appreciate any help available. OpenEmu crashes with version 1.0.4 both regular and experimental whenever I click on the screen to choose and emulator or game. All versions of 1.0.1 & 1.0.3 wont open. Version 1.0.2 retrieves all game roms perfectly, doesn't crash but no games will play. If any one can steer me in the right direction I'd greatly appreciate it.

**Comment by clobber** [comment]
Sorry, it's impossible to support non-apple hardware. Also, the next version of OpenEmu requires 10.11.
