### ISSUE TITLE
Pokémon Platinum Save State rolled back my in-game save

### ISSUE THREAD

**Issue by xXxMountainJewritos42069xXx** [OpenEmu/OpenEmu#2203]
Hello, I have encountered an issue with save states on OpenEmu. When I went to restart the rom, I accidentally loaded a save state. Panicking, I turned the rom off and back on, tried to load my save, and sadly, I was rolled back to a previous save from maybe a few days ago, at Valley Windworks. I could load my latest save state where I was capturing a Drifloon, but that's as far back as I could return to. I didn't get too far from that point anyway, but this could be a problem if you're at the end of the game and your last save state was from, say, the 4th gym leader.

I don't know if this can be fixed, and I doubt it. In that case, please let this be a PSA: be careful with your save states in games like Pokémon.

**Comment by clobber** [comment]
>When I went to restart the rom, I accidentally loaded a save state. Panicking, I turned the rom off and back on, tried to load my save, and sadly, I was rolled back to a previous save

That is exactly how save states work on any emulator. It completely restores everything that was in memory including the state of the battery.
