### ISSUE TITLE
PSP games appear to cause OpenEmu to become unresponsive

### ISSUE THREAD

**Issue by eyelasers** [OpenEmu/OpenEmu#2205]
Metal Gear Acid and Metal Gear Acid 2 both seem to cause OpenEmu to become unresponsive when I try to play them. I'm new to OSX, apologies if I blew something up compiling OpenEmu myself or missed something. Both games are listed as playable on the PPSSPP compatibility list. Everything else works great! Thanks for all of the hard work.

HelperApp crash log:
https://gist.github.com/eyelasers/c86b1057cf39dbd21e78

I'm using a mid 2013 MacBook Air, El Capitan 10.11.2, OpenEmu v1.0.4 337-gc3e64b4-Release

**Comment by eyelasers** [comment]
These two entries in the console appeared above the crash log, I don't know if they are relevant or not:

2015-12-14 12:08:03.519 AM OpenEmu[5262]: 
Deallocating proxy: <OEThreadProxy 0x7f9845e8a260, target: <OEGameDocument 0x7f98459505a0, ROM: 'Metal Gear Ac!d', System: 'openemu.system.psp', Core: 'org.openemu.PPSSPP'>>

2015-12-14 12:08:03.537 AM com.apple.xpc.launchd[1]: 
(com.apple.ReportCrash[5269]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash

**Comment by clobber** [comment]
This game crashes in the 1.0/1.0.1 standalone version which is the same version as our current core plugin.

It appears to run in 1.1.1 so you will have to wait until our port is upgraded.

**Comment by eyelasers** [comment]
Great, thank you.
