### ISSUE TITLE
Hangs on "Open" dialog

### ISSUE THREAD

**Issue by Adrian232** [OpenEmu/OpenEmu#2207]
Any time the app would activate an "Open" dialog box (e.g. "Launch Game...", "Add to Library...", "Add Cover Art From File...", etc) the application goes into an infinite loop, where it appears to be slowly allocating memory ad infinitum. I get a beachball icon over the app, and the only way to stop it is to force quit.

I have tried this in both the stable version and the "experimental" version with the same results.

I am running OS X El Capitan, with Little Snitch and Sophos (in case that makes a difference; though disabling these seems to have no effect). I have not had this problem with any other apps except OpenEmu.

**Comment by Adrian232** [comment]
[OpenEmu_2015-12-18-052313_Omega.hang.txt](https://github.com/OpenEmu/OpenEmu/files/66477/OpenEmu_2015-12-18-052313_Omega.hang.txt)

Here is a hang file I found from Console.app, in case this helps

**Comment by clobber** [comment]
Please search before opening a new issue.

#1993
#2000
