### ISSUE TITLE
Save/Load Menu

### ISSUE THREAD

**Issue by Adrian232** [OpenEmu/OpenEmu#2208]
I like the ease of use of the save/load game menu while running a game, compared to other emulators. However, it would be nice if the menu incorporated a screenshot of the game at that save point. Many other emulators make use of this, and it helps to figure out when exactly the save was made.

~~It would also be nice to be able to delete saves from the menu when I no longer need them in order to reduce clutter,~~ and also to be able to rename them.

Edit: Aaand, I just noticed you can delete the save with option-click. Nice hidden feature.

**Comment by clobber** [comment]
Next release.
