### ISSUE TITLE
Just Downloaded -- "Application Not Responding" If I Click "Create New Library" or "Open Existing Library

### ISSUE THREAD

**Issue by Jobles** [OpenEmu/OpenEmu#2210]
I've downloaded OpenEmu previously and uninstalled it. I am redownloading it now and when I open it, it says "The OpenEmu Library could not be found." I am then redirected to a screen that says "Quit" "Create Library..." or "Choose Library..." If I click "Quit" it just stops. If I click either of the other two, it just freezes and then the spinning wheel shows up on my mouse. 

Help?

**Comment by clobber** [comment]
Please search before opening a new issue?

#1993
#2000

**Comment by Jobles** [comment]
I did search and all it said was that it will "most likely be fixed" with the next patch. Is there a time frame for this? Or any quick fix until that point?
