### ISSUE TITLE
Games freezing when touching trackpad

### ISSUE THREAD

**Issue by lwears** [OpenEmu/OpenEmu#2211]
When playing games on both SNES and SEGA MegaDrive. After starting the game working with the iBuffalo USB controller works fine. However once i touch the trackpad the whole game freezes and a force quit is required. Problem is not replicated when playing on SEGA MasterSystem.

MacBook Pro (Retina, 13-inch, Early 2015)
10.11.2 (15C50)
Intel Iris Graphics 6100 1536 MB

346-g729a832-Release
Compiled from source in order to get iBuffalo SNES USB controller working

No modifications
single display (macbook screen)
Pixellate filter

Changed no folder locations

https://gist.github.com/anonymous/679e9e157f18241e7c64

**Comment by clobber** [comment]
You compiled the application but you did not build the cores which have some changes. I believe that is the issue here.
