### ISSUE TITLE
openemu-1.0.4-no-clientstorage.zip

### ISSUE THREAD

**Issue by Truesyndo** [OpenEmu/OpenEmu#2212]
Can somebody upload this version of openemu for me please I cant use openemu anymore due to the lag issues.

**Comment by clobber** [comment]
Sorry, no. You will have to wait until next release for the fix, which is coming soon.

**Comment by Truesyndo** [comment]
Can you please reupload the file just once more, I was in the middle of playing a very sentimental rpg to me and by the time the fix is released il already be out of the story and feeling, I am very depressed and this is one of the only things that helps me

**Comment by clobber** [comment]
Sorry, but I no longer have that build and we are in the middle of preparing a new release. We've stated before that next release is coming so just sit tight man.
