### ISSUE TITLE
NEOGEO Support - Time to add a dedicated core just for NEOGEO

### ISSUE THREAD

**Issue by PatrickRoanhouse** [OpenEmu/OpenEmu#2213]
I'm trying for the life of me to figure out where to place the neogeo.zip bios file i have. I have downloaded the universal bios version 30 and 31 and placed them all in the bios folder. I have placed copies in the arcade rom folder and i still can't get roms that are neogeo from the 1.49 mame romset to work.

All i get is this exact same error message in the OSX Console on every NeoGeo game I try

`Dec 21 11:08:40 rMBP15 OpenEmuHelperApp[19774]: parent application is: OpenEmu`
`Dec 21 11:08:40 rMBP15 OpenEmuHelperApp[19774]: Some shit about the game.`
`Dec 21 11:08:41 rMBP15 OpenEmuHelperApp[19774]: MAME: Audit failed with output:`
`Dec 21 11:08:41 rMBP15 OpenEmuHelperApp[19774]: ROM did not load.`
`Dec 21 11:08:41 rMBP15 OpenEmuHelperApp[19774]: Deallocating proxy: <OEThreadProxy 0x7fa9f4829b20, target: <MAMEGameCore: 0x7fa9f4829fc0>>`
`Dec 21 11:08:41 rMBP15 OpenEmu[19666]: Deallocating proxy: <OEThreadProxy 0x7f9fa344f0d0, target: <OEGameViewController: 0x7f9fa6cc06a0>>`

**Comment by clobber** [comment]
Here's what to do:

* Remove whatever you have added into your library for neogeo.
* Locate a MAME 0.149 romset.
* Download neogeo.zip and simply drag and drop it into the window so that it imports into the Arcade library just like any other game.

That's it.
