### ISSUE TITLE
ARCADE & NeoGeo issues it is more than just romset and bios

### ISSUE THREAD

**Issue by PatrickRoanhouse** [OpenEmu/OpenEmu#2214]
I only have 1.49 rom set roms. I have a bios sets for both universal and just a stock neogeo.zip which is a 1.7 mb file. But I keep getting this EXACT error messages in the console when i try to load an arcade rom or neogeo rom from the 1.49 set with the bios in the rom folder and in the bios folder just incase

`Dec 21 15:28:51 rMBP15 OpenEmuHelperApp[21793]: parent application is: OpenEmu`
`Dec 21 15:28:51 rMBP15 OpenEmuHelperApp[21793]: Some shit about the game.`
`Dec 21 15:28:51 rMBP15 OpenEmuHelperApp[21793]: MAME: Audit failed with output:`
`Dec 21 15:28:51 rMBP15 OpenEmuHelperApp[21793]: ROM did not load.`
`Dec 21 15:28:51 rMBP15 OpenEmuHelperApp[21793]: Deallocating proxy: <OEThreadProxy 0x7fd621c18a30, target: <MAMEGameCore: 0x7fd621c18220>>`
`Dec 21 15:28:51 rMBP15 OpenEmu[20064]: Deallocating proxy: <OEThreadProxy 0x7fcd68c31460, target: <OEGameViewController: 0x7fcd664b6140>> `

**Comment by PlutoX86** [comment]
There are lot's of neogeo.zip files out there. Eventually one will work. ;) Try the 1.4 mb one!

**Comment by clobber** [comment]
@PatrickRoanhouse there is no need to open a new ticket. You need the files from a 0.149.

If this doesn't work for you, you have done something wrong.

**Comment by clobber** [comment]
#2213

**Comment by clobber** [comment]
And you keep pasting console out, such as `MAME: Audit failed with output:` but you don't even include the full line!

**Comment by PatrickRoanhouse** [comment]
'Dec 21 16:54:01 rMBP15 OpenEmuHelperApp[22417]: Some shit about the game.'
'Dec 21 16:54:02 rMBP15 OpenEmuHelperApp[22417]: MAME: Audit failed with output:'
'	mslug6      : bios.ic23_l (65536 bytes) - NOT FOUND (awbios)'
'	mslug6      : ax3001f01.bin (4 bytes) - NOT FOUND'
'Dec 21 16:54:02 rMBP15 OpenEmuHelperApp[22417]: ROM did not load.'
'Dec 21 16:54:02 rMBP15 OpenEmuHelperApp[22417]: Deallocating proxy: <OEThreadProxy 0x7fbddb68c280, target: <MAMEGameCore: 0x7fbddb68c470>>'
'Dec 21 16:54:02 rMBP15 OpenEmu[21854]: Deallocating proxy: <OEThreadProxy 0x7f9cb8d07440, target: <OEGameDocument 0x7f9cc0280490, ROM: 'Metal Slug 6', System: 'openemu.system.arcade', Core: 'org.openemu.MAME'>>'

**Comment by clobber** [comment]
Um, first of all. Metal Slug 6 isn't a Neo Geo game, and MAME cannot run Metal Slug 6 in the first place.

**Comment by PatrickRoanhouse** [comment]
Hey first sorry for coming across dickish. I know you guys put a lot of work into openemu.

I'm just trying to get the arcade part to work well. Now I found joust and that works but I tried final fight 1, 2, last blade 1, 2, King of Monsters, Spin Masters, King of Fighters and Metal Slug 1 and I still get the same . similar error log.

Here is what i get for metal slug 1

Dec 22 00:59:03 rMBP15 appleeventsd[60]: SecTaskLoadEntitlements failed error=22
Dec 22 00:59:03 rMBP15 OpenEmuHelperApp[22606]: parent application is: OpenEmu
Dec 22 00:59:03 rMBP15 OpenEmuHelperApp[22606]: Some shit about the game.
Dec 22 00:59:03 rMBP15 OpenEmuHelperApp[22606]: MAME: Audit failed with output:
	mslug       : uni-bios_3_0.rom (131072 bytes) - NOT FOUND (neogeo)
Dec 22 00:59:03 rMBP15 OpenEmuHelperApp[22606]: ROM did not load.
Dec 22 00:59:03 rMBP15 OpenEmuHelperApp[22606]: Deallocating proxy: <OEThreadProxy 0x7f9150701df0, target: <MAMEGameCore: 0x7f91528009c0>>

**Comment by clobber** [comment]
>uni-bios_3_0.rom 

**Please read** what I have told you as you are now wearing down my patience. I'm not lying when I said that you need files from a **MAME 0.149 romset**.

`uni-bios_3_0.rom` exists inside of the `neogeo.zip` from a proper MAME 0.149 romset. Now enough with this already.

**Comment by PatrickRoanhouse** [comment]
got it to work finally.

**Comment by Xerox-Prime** [comment]
> a stock neogeo.zip which is a 1.7 mb file
PatrickRoanhouse, I am looking for this neogeo.zip 1.7 mb file and I couldn't find it. Please, give the link for this file or attach it in your reply that will also do.
