### ISSUE TITLE
Blurry images on non-retina screens

### ISSUE THREAD

**Issue by J-rg** [OpenEmu/OpenEmu#2215]
Ever since moving all images into an asset catalog, the retina assets for interface graphics defined in Theme.plist are also displayed on non-retina displays, where they look slightly blurred.

Two examples (both are APNGs):
http://cl.ly/2A1I14442f0f
http://cl.ly/3w0f0M251q2c

**Comment by clobber** [comment]
Thanks for reporting, I'm noticing this now but not sure of the cause. Will definitely have to fix in the next day for release! Also cc'ing @cyco on this so he has a chance to take a look.

**Comment by clobber** [comment]
@J-rg Just to clarify, did you pinpoint this to the image assets pull request (https://github.com/OpenEmu/OpenEmu/pull/2102) by @MaddTheSane ? Wanting to make sure we know when this happened.

Also posting some other example images from the issue:

1.0.4
![screen shot 2015-12-21 at 11 08 13 pm](https://cloud.githubusercontent.com/assets/1303132/11949099/da634032-a838-11e5-99f4-d4c8a654a36c.png)

2.0
![screen shot 2015-12-21 at 11 09 20 pm](https://cloud.githubusercontent.com/assets/1303132/11949102/e6f9b4f2-a838-11e5-8a4b-dcfedaa9100d.png)

So there is a definite issue there. Interestingly, the tab icons and sidebar icons seem unaffected. @MaddTheSane do you have any idea about this?

**Comment by J-rg** [comment]
>@J-rg Just to clarify, did you pinpoint this to the image assets pull request (#2102) by @MaddTheSane ? Wanting to make sure we know when this happened.

962245b still has sharp images, 60a175f onwards is blurry. (You'll have to put noise.png back to Interface Graphics before building 60a175f, otherwise the app will crash.)

**Comment by cyco** [comment]
@J-rg can you test this? I have a retina macbook with an external screen so i can't be sure it works in a non-retina only setting.
