### ISSUE TITLE
Launching DS games causes org.openemu.GameCore.ErrorDomain -6

### ISSUE THREAD

**Issue by mipstian** [OpenEmu/OpenEmu#2218]
I've build from source a few weeks ago and everything was fine.
Today I've built from source (pulled master a few hours ago), following the guide.
When I first tried launching a DS game, it asked me to download the core, I said yes. Core downloaded fine and games run.
However, at launch, I get an error box that says `The operation couldn’t be completed. (org.openemu.GameCore.ErrorDomain error -6.)`, which seems to mean `OEGameCoreDoesNotSupportSaveStatesError`.
I can't find a recent commit which might have caused this.
(all other systems work as expected, including save states)
What could this be?

**Comment by clobber** [comment]
There was an API change. I'll be pushing a Desmume update hopefully later today.

**Comment by mipstian** [comment]
Thanks! Out of curiosity, why is desmume not a submodule?

**Comment by clobber** [comment]
We have our API upstream, so didn't have a need yet.

Anyway, the update is now out, along with 2.0 :D

**Comment by mipstian** [comment]
I saw, congrats on the release! I can confirm this issue is fixed on 2.0.
