### ISSUE TITLE
Save-Games moved to .Trash after upgrading to OpenEmu 2.0

### ISSUE THREAD

**Issue by jeffbonhag** [OpenEmu/OpenEmu#2219]
Hi,
After upgrading to OpenEmu 2.0 (402-g7465b44-Release), it seems like my saved games were moved to the Trash; could this be related to the upgrade?  I went the "Automatically Upgrade/Install and Relaunch" route.

After dropping the .oesavestate files back into OpenEmu (I can see the screenshot of where my game left off), when I try to load the file I get an error that says "Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again."

**Comment by clobber** [comment]
Sorry, yeah, all Genesis/Mega Drive states had to be trashed due to unfixable incompatibilities from the emulator core which would crash the whole thing.

No possible way to recover them for use with the new GenesisPlus core.

**Comment by clobber** [comment]
Also adding a line about this in the release notes because I totally forgot. Thanks for reporting.

**Comment by jeffbonhag** [comment]
Thanks for making the emulator, it's really nice!  And congratulations on the new release.
