### ISSUE TITLE
IGN Rating - Feature Request

### ISSUE THREAD

**Issue by panzander** [OpenEmu/OpenEmu#2220]
It would be fantastic for larger libraries if there were two options, one where the user can rate and score his games, but a separate mode that pulled all game scores (maybe from a ign or another famous ranking site)  and ranked them on the 5 star bases. It would make searching and discovering games much more fun. Also if they pulled a bit about it, like a short description and some in game shots I would be non stop on openemu. Thanks for all the amazing work so far.

**Comment by clobber** [comment]
No plans for this, at least no right now. Though we do have extra metadata in our database that we may eventually expose.
