### ISSUE TITLE
App having problem when adding atari bin files

### ISSUE THREAD

**Issue by michaelmon1203** [OpenEmu/OpenEmu#2222]
Why cancel the chosen "atari 2600" when having problem adding atari bin files? 

If i can fix the issue by choosing "atari 2600" and clicking the APPLY button, then why don't you let the software fix it automatically?

**Comment by clobber** [comment]
If you are referring to the import issue resolver, .bin is ambiguous and supported by many systems, hence why you have to select which one during import.

**Comment by Gerst20051** [comment]
<img width="334" alt="screenshot 2016-07-03 02 08 10" src="https://cloud.githubusercontent.com/assets/235372/16544023/081a2bbc-40c3-11e6-8f53-a529ecbd59cd.png">

**Comment by zackria** [comment]
It works
