### ISSUE TITLE
"Couldn't communicate with a helper application" when closing an Arcade game.

### ISSUE THREAD

**Issue by andybrito** [OpenEmu/OpenEmu#2223]
First of all, congrats on the new release, the new gui is amazing.
It's impossible to stop emulation of any arcade game, the screen goes black and the error message mentioned on the title appears, the only solution is force quit the app.
The games are running fine, the issue is just when trying to stop the emulation and return to the app.

<img width="1440" alt="screen shot 2015-12-24 at 10 00 21 am" src="https://cloud.githubusercontent.com/assets/8280492/11994911/145dc2c8-aa26-11e5-81c0-e919d11273b3.png">

**Comment by clobber** [comment]
Cannot replicate this problem. Please ensure that your version of MAME in Cores Preferences is 0.149.1
