### ISSUE TITLE
v2 consoles missing after upgrading from v1

### ISSUE THREAD

**Issue by Demasterpl** [OpenEmu/OpenEmu#2225]
After upgrading from v1.0.4 to v2.0.0, no new consoles are loaded:

<img width="562" alt="screen shot 2015-12-24 at 12 26 36 pm" src="https://cloud.githubusercontent.com/assets/4109695/11996825/9a341538-aa39-11e5-9145-493168e565ee.png">
<img width="861" alt="screen shot 2015-12-24 at 12 00 51 pm" src="https://cloud.githubusercontent.com/assets/4109695/11996813/7fa6e682-aa39-11e5-89ef-93ed618603b5.png">
<img width="861" alt="screen shot 2015-12-24 at 12 01 05 pm" src="https://cloud.githubusercontent.com/assets/4109695/11996815/7fb4eb10-aa39-11e5-8447-27988ad65f81.png">
<img width="1095" alt="screen shot 2015-12-24 at 12 05 11 pm" src="https://cloud.githubusercontent.com/assets/4109695/11996814/7fadfde6-aa39-11e5-992e-73fd9d67afad.png">

After performing a clean install of v2.0, everything appears okay. Pointing the game library to my old one then resets the console lists everywhere to appear as v1. The only mention of v2 consoles is on the Preferences -> Cores. Attaching my 3 Library.storedata files as everything else in my Games Library folder is Artwork or ROMS.

[Game Folder Libraries.zip](https://github.com/OpenEmu/OpenEmu/files/71849/Game.Folder.Libraries.zip)

**Comment by anderbubble** [comment]
I have this same issue. What I tried:

* importing (drag-and-drop) wonderswan roms; these were scanned, but not added to the library
* regenerating (by deleting) org.openemu.*; I got the initial setup wizard, but still no new systems
* installing the new cores in the cores menu (where the new systems *are* listed)

**Comment by clobber** [comment]
Fixed for 2.0.1, out now.
