### ISSUE TITLE
PSP audio now choppy when upgrading to 2.0

### ISSUE THREAD

**Issue by kevputer** [OpenEmu/OpenEmu#2228]
I've been play Metal Gear Solid: Portable Ops and Portable Ops Plus recently with no problems. After updating today there is now choppiness in the audio and only for the PSP core. I'm on an E2015 base model 13" with PS4 controller Bluetooth'd.

I wanted to downgrade back to 1.04 experimental but now when downloading the cores I guess it gets your new ones and just crashes before launching any game for any console. I used AppDelete to try and clear everything out sans save states/game library (backed them up and then moved them back in newly generated one) to no avail. That being said, mostly raising the point of 2.0's PSP acting funky now, if there's a way I can go back to 1.04 experimental and the old core let me know.

**Comment by kevputer** [comment]
I just noticed you've added real-time rewinding. Perhaps the computer is not powerful enough to do that constantly at the same time. Is there a way to disable that and test?

**Comment by clobber** [comment]
This would be a bug in PPSSPP itself not related to OpenEmu or rewind (PPSSPP doesn't have rewind enabled).

I'd suggest just using an older standalone version of PPSSPP to work around the issue.

**Comment by clobber** [comment]
#1036
