### ISSUE TITLE
Controller prefs: Overshoot clips cord

### ISSUE THREAD

**Issue by RickyRomero** [OpenEmu/OpenEmu#2229]
When switching systems in the controller config, we have an animation where the old controller bounces out and the new one bounces in.  To account for this, we added 50pts of extra space above each controller graphic.

![Overshoot illustrated]
(http://i.imgur.com/cM8Ukxp.png)

The overshoot was rendered correctly in a previous version, but in 2.0.1 it's cropped off during the animation.

![Bug]
(http://i.imgur.com/Vzsfv3t.png)

**Comment by clobber** [comment]
Is this 2x only? I don't think it's happening for me on 1x.

**Comment by RickyRomero** [comment]
I'm seeing this issue at 1x on a 2013 MacBook Air.

**Comment by robotoad** [comment]
I'm not seeing this on a 1x external display. Only the 2x screen.

**Comment by clobber** [comment]
Man that is odd. I don't get it on my 1x display.

**Comment by RickyRomero** [comment]
Couple of long shots... Both of you have extended desktops, yeah? What happens if you change your primary display?  I'm only using the one built-in display in this system.

What about integrated vs. discrete graphics?

**Comment by robotoad** [comment]
With the external display disconnected, the issue goes away on my 2x screen. I think we're going to remove the bounce so it's not an issue regardless.

**Comment by clobber** [comment]
Oh I should have mentioned I'm using the regular 1280x800 display on my old MBP.

**Comment by robotoad** [comment]
Fixed in <a href="https://github.com/OpenEmu/OpenEmu/commit/2fde96882c5153cf1e92b7b4cc7d1ad216a1d512">2fde968</a>.
