### ISSUE TITLE
v2.0 killed all my Sega Genesis save states 

### ISSUE THREAD

**Issue by sonicmouse** [OpenEmu/OpenEmu#2231]
I had 30+ games that I saved using only save-states. I didn't use in-game saves.

I installed openemu version 2.0, and OpenEmu moved all my save-states to the trash -- luckily i caught that and saved them.

I uninstalled version 2.0 using "App Cleaner" and re-installed v1.3 of OpenEmu -- I ran it and it still doesn't work with my save-states (gives me the "Helper Application not found" error.)

I am assuming you guys updated the SegaGenesis core and didn't make it backwards compatible with the core that was distributed with 1.3.  I am assuming that openemu 1.3 is grabbing the new core instead of the old one.

Can you please give me a link to the old segagenesis core that was distributed with version 1.3?

If i can't get this to work, it's going to suck -- I will lose months of game saves for tons of games.

**Comment by sonicmouse** [comment]
[save_state_crash.zip](https://github.com/OpenEmu/OpenEmu/files/72048/save_state_crash.zip)
I attached the one of the ROMs along with the save state i am trying to load.

**Comment by clobber** [comment]
Did you check the release notes?

>I am assuming you guys updated the SegaGenesis core and didn't make it backwards compatible

Not us, the author of the emulator.

Sorry but there is no way to recover those state files for use with the latest OpenEmu. Also, please search before opening a new issue.

#2231

**Comment by clobber** [comment]
Also, 1.0.4 is now unsupported but if it is an absolute must that you need that old version and the older GenesisPlus, you can find a build in its repo: https://github.com/OpenEmu/GenesisPlus-Core

**Comment by sonicmouse** [comment]
Thanks -- I found the older genesisPlus core and replaced the new one with that and all my save games are back.

Sorry about not searching first -- I panicked.

**Comment by clobber** [comment]
Sure, one other thing to consider: very few Genesis games had save files, where most had a password system or level select cheat codes that you can use to get back to where you left off. Figured I'd mention that as an alternative so you can still use OpenEmu 2.0 and the latest GenesisPlus core.
