### ISSUE TITLE
Grid View not sorting games by System anymore ver. 2.0

### ISSUE THREAD

**Issue by powerhousepr** [OpenEmu/OpenEmu#2233]
Hi guys, great update... I notice that when selecting ALL GAMES on "Grid view" the games are now sorted in alphabetic order and there is no way to change it by system/console order. You can only do that on "List view".

I remember being able to do that on "Grid View" before the last update.

Anyways hope you guys can bring that back when working on other updates... :)

**Comment by clobber** [comment]
No, we never allowed 'sorting' in grid view. That may have been possible in the old 'cover flow' view but that is no longer available.
