### ISSUE TITLE
Older OpenEmu version that has mupen64plus core (n64) and works with 10.7.5?

### ISSUE THREAD

**Issue by jewelryjelly** [OpenEmu/OpenEmu#2235]
Recently my friend gave me two retrolink controllers I am really excited to use for my n64 roms. After realizing sixtyforce would not work with the retrolink 64 controller, I have been hunting for hours for a new emu and found OE. I was able to find an older version of it that worked for my 10.7.5 (v1.0.4) however n64 is not an option.

Is it possible to ask if I could access a previous OE version that allows n64 and can run on 10.7.5? If not, there is a way for me to put the mupen64plus core in v1.0.4? I have been hunting around but am having trouble finding old versions of OE.

Thank you so much!

**Comment by clobber** [comment]
Sorry, there isn't a version of the Mupen64Plus core port that ever ran on 10.7. I strongly advise upgrading your machine to the latest OS X if at all possible though.

**Comment by GB-CG** [comment]
@jewelryjelly Pardon me for butting in, You could try project64 with winebottler if you having problems. ~~I've made a basic video tutorial of how to do that. I may not cover Lion, but~~ you should be ok.

**Comment by jewelryjelly** [comment]
@GB-CG That would be fantastic if you could link me to the tutorial! I am pretty new to messing around with more complex things regarding EMUs (as opposed to just get and go haha) so that would be a huge help!

**Comment by jewelryjelly** [comment]
@clobber Thank you for letting me know! Okay got it, and I will try to update however I need more memory before doing so sadly!

**Comment by GB-CG** [comment]
@jewelryjelly Just click on the link on my github profile.

**Comment by Pwnz0rserver2009** [comment]
> Sorry, there isn't a version of the Mupen64Plus core port that ever ran on 10.7.

<img width="1178" height="630" alt="Image" src="https://github.com/user-attachments/assets/b84b1aea-6c42-450d-a2ec-095a08d4aa36" />
Wrong... It works when using the experimental version of 1.0.4
