### ISSUE TITLE
v2.0.1, SNES (higan 0.95) save states not loading after upgrade?

### ISSUE THREAD

**Issue by returnal** [OpenEmu/OpenEmu#2236]
hey, i upgraded from whatever the last major version was (1.4?) to 2.0.1 today, and been having the same issue with all my save states. upon opening an SNES (via higan) game and any of its save states, i get a dialog box along the lines of:
"The save state data could not be read
Could not read the file state in /Library/Application Support/OpenEmu/Save States/SuperNES/Earthbound/Auto Save State.oesavestate/State."
(fwiw, battery saves aren't affected, but my save states are more recent)
the save state files are all still there in the /Library/Application Support/OpenEmu/Save States/SuperNES folder. what could the issue be? are save states made w/ previous versions of higan not compatible? albeit, googling hasn't brought up anything along those lines...
i apologize if i've missed something glaringly obvious. thanks for your assistance!

**Comment by clobber** [comment]
Sorry, byuu, the author of Higan doesn't keep save state compatibility between versions of his emulator. One of the reasons it's now our default SNES 'core'.

**Comment by clobber** [comment]
whoops, now = not.

**Comment by returnal** [comment]
ah, dang. are past Higan.oecoreplugin files available?
ty!

**Comment by returnal** [comment]
ah, actually I can just get it via one of my hard drive backups
