### ISSUE TITLE
Black Frozen Screen After 2.0.1 update

### ISSUE THREAD

**Issue by oysterbank** [OpenEmu/OpenEmu#2239]
After installing the 2.0.1 update on my Macbook Pro running 10.11.2, anytime I try to open a game or save state, all I see is a black screen. The game itself does not load, and from there, it is impossible to close the window or shut down the program without Force Quitting the application.

**Comment by clobber** [comment]
Need to describe exactly what is going on. Which system? Which game? Switch the filter to something else, such as Pixellate or Nearest Neighbor. Let us know how that goes. If there are crash logs, post those too.

**Comment by oysterbank** [comment]
Okay, I've determined that the issue was that the save states I made in version 1.0.4 must have gotten corrupted during the upgrade to 2.0.1 (or moved?...but I don't think the system would hang if that were the case). When I started the games without any save state, they worked fine, and I was able to create new, perfectly functional save states. This happened with Gameboy/Color games, I'm not sure if it happened with other systems because that was the only one I was using.

**Comment by clobber** [comment]
Okay, we had someone else with the same problem where their files were found to be corrupted. I'd urge backing up all your files to a new hard disk and replacing the old as soon as possible, because it sounds as if your drive may be going bad.
