### ISSUE TITLE
Games do not respondg to MFi controller; UI does respond

### ISSUE THREAD

**Issue by gingerbeardman** [OpenEmu/OpenEmu#2240]
i had to AppClean OpenEmu away and then download and setup again in order to get the games to react to my MFi controller at all… I have a Time Machine backup of my old config if it’s of any help?

**Comment by clobber** [comment]
That has to be interference from other applications like I think we may have discussed.

**Comment by gingerbeardman** [comment]
OK, I will keep an eye on it!

**Comment by clobber** [comment]
Yeah, not something we can diagnose easily since it looks like a well-known issue with other apps. Btw, it wasn't clear to me earlier, but are the automaps now working for your device with that file I gave you?

**Comment by gingerbeardman** [comment]
Yes they are, so thanks for that!

**Comment by clobber** [comment]
Great! Happy to help.
