### ISSUE TITLE
How to restore old SNES9x core plugin after accidentally updating on OS X 10.8.5?

### ISSUE THREAD

**Issue by monergist** [OpenEmu/OpenEmu#2243]
I'm still running OpenEmu 1.0.4 on OS X 10.8.5. Today I accidentally updated SNES9x on the Cores tab in Preferences, not knowing that SNES9x 1.53.4 apparently does not run with my configuration. How can I restore the old SNES9x.oecoreplugin? Surely I can download it somewhere?

**Comment by clobber** [comment]
Check the other repos in our org, you'll find the one for Snes9x.

**Comment by monergist** [comment]
Can you supply a URL? I've looked and can't seem to find the repos.
