### ISSUE TITLE
Can't Uncheck these cores in 2.0.1 Experimental

### ISSUE THREAD

**Issue by wraybowling** [OpenEmu/OpenEmu#2244]
I am delighted to see a set-up guide in 2.x! Very nice. So I tried out unchecking all the cores to make sure. Yep. Found a bug. The following cores cannot be unchecked:

- Gambatte / Gameboy
- Nestopia / NES
- Snes9X / Super NES
- Visual Boy Advance / Gameboy Advance

![screen shot 2015-12-25 at 9 37 17 pm](https://cloud.githubusercontent.com/assets/1120619/12004923/c363f15a-ab4f-11e5-89e3-a571160e7b29.png)

**Comment by clobber** [comment]
Not a bug, we made it so emulator cores marked as default in the application could not be unchecked, to get around some older issues.
