### ISSUE TITLE
Running Arcade Games

### ISSUE THREAD

**Issue by brettallica** [OpenEmu/OpenEmu#2245]
Hi,

New user, longtime browser. OpenEmu is by far and away the coolest way to play vintage games on a Mac that I have used, and I've been doing this stuff on a Mac for probably 10 years or so now. I've only been using OpenEmu for a few days now, which originally started after searching for a better way than what I had been doing. Because of finding and now using OpenEmu quite a bit, I have had a revival of my interest in running MAME on Mac. I gave up on running MAME on a Mac several years ago, but when stumbling upon OpenEmu and reading through all these comments it looks like running MAME (or something similar) is quite possible.

I know I'm probably going to have my you-know-what handed to me for not searching, but believe me I have searched a great deal, and for the life of me I cannot figure out how to get these vintage arcade games running in OpenEmu. Is there some type of tutorial where I can review a walkthrough to ensure that I'm doing everything correctly? I have already downloaded the MAME 0.149 ROMs file, which contains 28,510 files in the directory — 28,509 are zipped files which I'm sure are mostly games. I also have higher revisions of directories for the ROMs, but for this exercise I am using the 0.149 version to be consistent with what is being recommended on this site. I have tried dragging and dropping single games, multiple games, adding games to the library through the "File -> Add to Library..." menu, the neogeo.zip file by itself, and on and on. I've even cleared/renamed the folders in the Applications Support folder, reinstalled the application itself, and run the Terminal command to reset the OpenEmu preferences. I have been able to run MAME (mame64) outside of OpenEmu by opening Terminal and typing in some commands, but the interface that appears in this is pretty rudimentary at best. I'd love to see the integration with OpenEmu on my systems. 

I'm pretty generally a technically savvy guy, but this one has gotten the better of me and I don't know how to go on without asking for help in this way. I can see that this is a pretty common source of irritation, so I don't want to be a bother. If someone can just point me in the right direction I am sure I can get it figured out. Any support is appreciated.

Let me know if anything I am typing here is uncouth or if I am required to add information and I will gladly oblige.

**Comment by gingerbeardman** [comment]
Is Arcade listed in your Consoles list down the left side of the main window?

**Comment by clobber** [comment]
Right, "experimental" cores package is what is needed to get at the Arcade system and MAME core plugin. I think this guide here (http://agreeordie.com/how-to-emulate-retro-video-games/) has helped people with using Arcade in the past, but beyond that we cannot offer any other assistance.

**Comment by brettallica** [comment]
@gingerbeardman Thanks! I did not have the "Arcade" system in my list of consoles, so I was running the standard version and not the experimental version, as you mentioned. I'm giving this a whirl right now and we'll see what happens. During the ROM import process I am noticing a ton of issues, as the OpenEmu GUI is telling me "Resolve ### Issues" and the number just keeps going up. For example I am only in the "J" section and we're up to 700+ issues already. See screenshot:

![lots of issues](https://cloud.githubusercontent.com/assets/16442162/12008392/37c88406-abec-11e5-8b20-a52e0ca41cf3.png)

When I click on the arrow to go to the "Fix Import Issues" page of the interface, it just lists a bunch of ROM files and I don't really know what the proper next step is. Are these ROMs with missing bios files or what? What do I need to get those all to work? 

@clobber Thank you for your help and support with this project in general. I see that you contribute a lot and it is appreciated. Hopefully you get more praise than complaints.

**Comment by clobber** [comment]
Whoa, that isn't right. Basically you should be able to import a single Arcade .zip file and it will end up right in the Arcade system **unless** the zip file has other files in it that are being picked up by other systems, I'm guessing .bin files.

So sounds like I need to add .bin to the Arcade's list of supported file types in order to allow you to import all those other zips. I didn't expect someone would import the *entire* MAME 0.149 rom set :P

Do me a favor and unzip the first file in that list there to verify its contents. I think that is whats going on here though.

**Comment by brettallica** [comment]
Hi, @clobber — Thanks! Have a look at the screen captures. Hopefully this helps/makes sense:

![first two files](https://cloud.githubusercontent.com/assets/16442162/12008418/9dc0fa0c-abee-11e5-9709-3a4719e0fffc.png)
![first two files unzipped](https://cloud.githubusercontent.com/assets/16442162/12008427/da781b24-abee-11e5-88e5-fdb60f9b4e14.png)

Please let me know if you need anything else. Thanks again.

**Comment by clobber** [comment]
You honestly do not need to import the entire MAME 0.149 set into your library, as MAME doesn't actually run *all* of those games due to various compatibility issues. It's much better to just import the games you really want to play and their associated bios/system file zips (e.g. mslug.zip for Metal Slug and neogeo.zip for the required Neo Geo system files).

Anyway, a temp fix so you can get those MAME zips that contain a .bin file into your Arcade library.

Download this https://transfer.sh/X4QHR/arcade.oesystemplugin-bin.zip, unzip and place inside your OpenEmu app bundle:
* Right-click on OpenEmu.app and 'Show Package Contents', navigating to OpenEmu.app/Contents/PlugIns/Systems
* Relaunch the app
* Now when those files end up in the Import Issue Resolver, you should be able to select "Arcade" from the dropdown menu and send them there.

Protip: Control+Click on the first 'checkbox' in order to select them all in the list.

**Comment by brettallica** [comment]
@clobber — Thanks. I have downloaded the file and installed into the app bundle as directed. This worked and offered me an "Arcade" option in the drop-down of the "Fix Import Issues" screen.

You're probably right about not importing the entire library; there's no way I truly need all of those ROMs. I guess I was just seeking the most complete library of titles that I could get so I'm trying to get them all in there.

I have a couple follow-up questions that are related to OpenEmu running MAME, and basically just OpenEmu in general.

1) If I re-import the same game, will it add a duplicate entry or will OpenEmu "know" that it's already in there and just skip the import? The reason I ask is that I have more titles and am thinking about bringing them in, but comparing both lists could be pretty time-consuming (although I am certain there are folder-comparing programs out there that could assist with this process). 

2) Can I have "OpenEmu 2" (which is the "experimental" version) and "OpenEmu" both installed on my computer at the same time? I was thinking of keeping OpenEmu 2 around for MAME only, and then using the standard version of OpenEmu for all my other emulation needs, as I get the impression that the standard OpenEmu gets more attention, and a large portion of my emulation gaming is with the home consoles anyway. I'm wondering if there will be any sorts of conflicts or shared files that might make one or the other not work well if both are installed. 

Thank you, once again, for all your efforts.

**Comment by clobber** [comment]
1) Duplicates won't be imported.

2) Just use the "Experimental" package. All that means is it includes two additional system plugins, Arcade and Sega Saturn, so you can use the MAME and Yabause core plugins. That is the only difference between the two packages.

**Comment by brettallica** [comment]
Awesome. Thanks, @clobber. I've got OpenEmu 2 running now and all seems to be well. Do you (or anyone else) think it would be worthwhile to download a "BIOS ROM pack" such as this one (http://www.emuparadise.me/biosfiles/MAMEBIOS.rar)? If so, I'm assuming that those BIOS ROMS go in the same folder as the Arcade ROM files (Library -> Application Support -> OpenEmu -> Game Library -> rooms -> Arcade). Is that correct? Thoughts and suggestions about this are welcomed.

**Comment by clobber** [comment]
Depends if it is for MAME 0.149 or not, but yeah, the BIOS and system files for MAME need to be imported just like any other game. Drag and drop them into the library or, as you suggested, you may copy them directly.

**Comment by brettallica** [comment]
Thank, @clobber. I will give that a shot. I am now in a perpetual state of unable to download cover art for not only the arcade games, but all the NES games I have since imported as well. They've all got that revolving animated "in progress" icon going. Is this a known issue with the experimental version or did I muck something up somewhere? I wouldn't be surprised if it was due to me importing ALL of the arcade ROMs and slowing down the application.

**Comment by clobber** [comment]
Arcade is still "experimental" and definitely does not have cover art yet. I really do not recommend doing a massive import like that all at once -- just import the games you want to play!

NES games pull down cover art as long as they are the retail "good" dumps of the games, so no translations, overdumps, hacks, betas -- that sort of thing.

**Comment by brettallica** [comment]
Noted and thank you! I think I will greatly pare-down my MAME/Arcade library. When I had the non-experimental version running — before I ventured in the MAME/Arcade side of things and was using the standard version — just about all of the cover art images appeared for the NES ROMs. I haven't had the same luck with the experimental version with the very same NES ROMs, though.

**Comment by grayskyclouds** [comment]
Hi @clobber, I think I might have the same issue about the Import Issue Resolver. All the files that are supposed to be in 'Arcade' are all showing at there. 

I tried your link; https://transfer.sh/X4QHR/arcade.oesystemplugin-bin.zip

but it doesn't work anymore. help?

**Comment by fredfontes** [comment]
Same here!
