### ISSUE TITLE
Controller only navigation -  Feature Request

### ISSUE THREAD

**Issue by panzander** [OpenEmu/OpenEmu#2246]
I thought I read this once a while back, but I've just read through all of the feature request and I don't see it. Request: a slightly altered controller only interface. When you connect to a tv and are a ways back have a mode to be able to navigate and control openemu with just a controller. This would include
-selecting games
-entering/exiting games
-rating
-settings and preferences + editing controller configurations
-playlists

**Comment by clobber** [comment]
Please search before opening a new issue.

#401
