### ISSUE TITLE
Rogue Squadron N64 not working

### ISSUE THREAD

**Issue by jaimemf1983** [OpenEmu/OpenEmu#2247]
The screen freezes at the begging...

**Comment by clobber** [comment]
Notoriously hard N64 game to emulated. Also please keep in mind this is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
