### ISSUE TITLE
PSX BIOS SCPH5502.bin not being sceen.

### ISSUE THREAD

**Issue by WCARDude** [OpenEmu/OpenEmu#2248]
Every time I try to load a PS1 game, OpenEmu throws up an error saying SCPH5502.bin is missing. I keep copying it, but it removes it. Using 2.0.1.

**Comment by gingerbeardman** [comment]
Does the file have the correct MD5 hash?

```Playstation (EU)	Mednafen	scph5502.bin	32736f17079d0b2b7024407c39bd3050```

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

**Comment by WCARDude** [comment]
It doesn't.  Could I change the incorrect MD5 to this one, or do I need to find bios with the correct hash?

**Comment by gingerbeardman** [comment]
You need a new file with the correct MD5 hash

**Comment by WCARDude** [comment]
I can't seem to find the correct MD5 in multiple files. Hmmm.

**Comment by blakespot** [comment]
I am stuck here also.

**Comment by clobber** [comment]
You will need to follow the guide and search online for the correct files.

**Comment by RowdyFOXYT** [comment]
omg made it work!!!!!!!!!!!!!!!!!!!!

swap the md5 for scph5501 and scph5502 in the info.plast file in the Mednafen contents. 😎🕹😆
