### ISSUE TITLE
Same game, different ROMS, Crashes at same moment ?

### ISSUE THREAD

**Issue by Nokomis** [OpenEmu/OpenEmu#2249]
Hi guys :)

Thanks for reading this message. I'm quite desperate now and I don't know what to do anymore. As a Pokémon fan I got a Pokemon White ROM for OpenEmu and I'd never had a problem with a rom on the app before. But when I launched the game, I was able to run it for about 30min when it crashed at a specific moment of the game. I restarted it several times trying to figure out what it was, then eventually I deleted the rom to find another one of the same game. 

But same thing happened. I thought maybe I'd got the same ROM but from a different website so I downloaded another one in a foreign language I'm fluent in, just to be sure. Same thing happened. I tried like 4 different ROMs of the Patch White Pokémon version and it kept crashing at that very specific moment in the game. I really don't know what to do, nor do I know where the problem is. Does that sound familiar to one of you guys ? Did it happen to you, or do you know what I can try to do to fix this ? 

Thank you in advance !

**Comment by clobber** [comment]
Pokemon games are not well supported by Desmume. I'd recommend using standalone Desmume app which has the JIT dynarec off by default. Not anything we can do about an emulator bug.

**Comment by Nokomis** [comment]
Helo clobber, 
Thank you so much for answering ! I'll download the Desmume app to run the game on it alone then. Thank you again ! :)
