### ISSUE TITLE
Unify Libraries and Cores into unified tab

### ISSUE THREAD

**Issue by wraybowling** [OpenEmu/OpenEmu#2250]
There's some dissonance in the preference panels the way cores and libraries are separated. I'd like to propose that we unify the enabling/disabling and installation of cores/consoles into one tab. I realize that the vocabulary of "Cores" and "Libraries" is different, but from a pure UX perspective, there are consoles, and they are either "not plugged in" or "plugged in" and "on" or "off". There are a number of reasons.
 1. There are a lot of libraries to choose from and the section to enable/disable them is getting pretty cramped. 
 2. There is a warning badge next to libraries "[have] no corresponding core installed." Letting a user view that information graphically in a table is better.
 3. Not all enabled consoles are installed. Not all installed cores are enabled libraries. All the more reason to unify.

Less emphasis on what this tab would be called. Maybe it's still called "Cores" Maybe it's called "Consoles." More emphasis on what it is: unified.

<img width="535" alt="open-emu-unified-consoles" src="https://cloud.githubusercontent.com/assets/1120619/12006980/71daaf64-abbc-11e5-9318-7fe9a4f9e6a6.png">

**Comment by clobber** [comment]
Interesting but won't really work out, there are multiple cores for systems.

**Comment by wraybowling** [comment]
Oh, I think you mean the reverse. Some cores handle more than one console. You're right; that would suggest a totally different layout.
