### ISSUE TITLE
N64 core freezes after saving game state

### ISSUE THREAD

**Issue by Headrush69** [OpenEmu/OpenEmu#2252]
Steps to reproduce:

1) Create a new user account in OS X to remove possibility of issues with previous versions.
2) Download and install OpenEmu Experimental 2.0.1
3) Add any N64 game
4) Start any N64 game
5) Using OpenEmu toolbar, create a save game.

At this point, emulation is frozen. If I click outside of OpenEmu window, than click back in OpenEmu window, emulation continues to run.

(Happens in fullscreen and windowed mode)

Nothing in Console related to OpenEmu either.

[OpenEmu Video Sample.zip](https://github.com/OpenEmu/OpenEmu/files/72491/OpenEmu.Video.Sample.zip)

or here if you have Flash support: http://tinypic.com/r/23magbr/9

**Comment by buchanancate** [comment]
I have the same problem; ovvasionally (read as 2out of about 20 saves) it will not freeze.

**Comment by Headrush69** [comment]
Appears fixed with 2.0.2 release.

**Comment by clobber** [comment]
Great. Thanks for the follow up.
