### ISSUE TITLE
CD-based systems try to copy tracks from different games into same directory

### ISSUE THREAD

**Issue by rejemy** [OpenEmu/OpenEmu#2253]
Upon trying to add my second TurboGrafx-CD game, I realized that OpenEmu is trying to copy all the tracks from the second game into the same directory as the first, which is failing because they both have identically named track files (Track1.wav, Track2.wav, Track3.wav ...)

It seems like I can probably work around this by renaming all the files involved to make sure they're unique across all games and editing the cue files to match, but a much nicer solution would be to have OpenEMU make a new folder in the library for each CD-based game to avoid having their files co-mingling in the library.

**Comment by clobber** [comment]
Interesting problem. Yeah, as you suggest you need to uniquely name those track files, we don't alter the cue sheets or filenames, but sounds like something we may take a look at. Closing for now, as I want to keep the number of open issues down but I will add this to my notes.

**Comment by rejemy** [comment]
You shouldn't need to alter the cue sheet or filenames if you put each in its own folder. You'd just need to have each CD game in the database have a pathname to the cue sheet in the proper subdirectory. Seems the easiest fix.

**Comment by clobber** [comment]
Yep, that is definitely an easier solution. Thank you.
