### ISSUE TITLE
No pix BIOS recognized...

### ISSUE THREAD

**Issue by fildzntus** [OpenEmu/OpenEmu#2254]
I followed the guide to a T. I finally have a game ready to play, but when I go to launch it pretends like I've done none of the BIOS work. I try dragging and dropping the BIOS files again, and it shows all three need to have issues resolved and the only action to take is not to import the files. I have copied them directly to the BIOS folder, but to no avail.  Please help

**Comment by MDJCM** [comment]
I'm having the same problem, tried 4 different BIOS packages and no luck.

I've no idea why it's so difficult to find the only BIOS package that makes this software work.

It reminds me that this is all still very BETA, I'm fairly technical and a non-technical person would have no chance.

**Comment by robotoad** [comment]
The 2.0.1. release notes say: "Note: If BIOS files were not importing correctly after a new core install, please remove the imported files, restart the app and import your BIOS files again."

Does that workaround resolve your issue?

**Comment by fildzntus** [comment]
Yeah, I solved it. I went into the library folder, deleted the BIOS folded, then the import worked without a hiccup. Try deleting the BIOS folder and then drag and drop the files again

**Comment by MDJCM** [comment]
@fildzntus  I tried this and finally found the BIOS folder, but the import is still being rejected. Any chance you can contact me with the right BIOS files? Twitter: @mdjcm

**Comment by clobber** [comment]
You do not need to place files directly into the folder, if you add the wrong ones the application will still remove them. Follow the BIOS guide (https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files) and search Google to get the correct ones.
