### ISSUE TITLE
8Bitdo Controller no longer working properly

### ISSUE THREAD

**Issue by cmdshft** [OpenEmu/OpenEmu#2255]
v2 brought back support for the 8Bitdo F30 Pro controller I have. v2.0.1 seems to have broken that support again.

The issue is that the d-pad controls are not working according to their maps I set. This issue was not present in v2.0

**Comment by clobber** [comment]
> v2.0.1 seems to have broken that support again.

Not possible, we didn't change anything input-related in that point release. What I believe is going on is interference from another application. When this happens, you need to start closing down other running applications until you find the culprit. Sometimes this is Chrome, sometimes 3rd party terminal apps, etc. Also give it a reboot and then only launch OpenEmu.

**Comment by cmdshft** [comment]
Restarting the machine did seem to fix it. I had to go and remap the buttons again.

Is there a reason this happened?

**Comment by clobber** [comment]
I don't know about the buttons remapping, but I am aware of the other applications causing interference. Or maybe something weird going on with hardware and bluetooth.

**Comment by ph0rn** [comment]
I seem to be having this issue, however rebooting and closing every 3rd party app possible doesn't affect it. As soon as I remap, on relaunch of Openemu the d-dap directions are mixed up again and I have to remap. Any other suggestions?

**Comment by clobber** [comment]
#2395
