### ISSUE TITLE
OpenEmu 2.0 unexpectedly slower (likely because of discrete/integrated GPU switching)

### ISSUE THREAD

**Issue by aktau** [OpenEmu/OpenEmu#2256]
Thanks for the wonderful new release.

I tried playing a PSP game I had played earlier in fullscreen mode and noticed that it was choppy with 2.0, while it wasn't with 1.0.4. I thought it might have to do with the transition from PPSSPP 1.0.0 to 1.1.1, but then I thought of another thing:

I'm usually running gfxCardStatus and noticed that OpenEmu 1.0.4 switched to the discrete graphics card. OpenEmu 2.0 doesn't. Forcing the discrete card with gfxCardStatus "fixes" the issue.

I imagine automatic switching was disabled for power saving reasons, which is commendable. In fact, when running games in windowed mode, or PSX games, this works perfectly well and saves a lot of battery.

Perhaps something else can be thought of? I don't know whether the communication between OpenEmu and the cores carries enough information to deduce the FPS and whether that signal (a low FPS or big FPS oscillations) is a strong enough signal to switch GPUs.

Alternately, if there is a way to detect the load on a GPU, perhaps that could be used (near to 100% -> try to switch). I can't imagine that Apple has a nice API for that, though.

**Comment by clobber** [comment]
Thanks for bringing this up.

Not a lot we can do about the GPU switching there, as that works directly against the API and we already disabled switching, as you noticed, for power-saving reasons.

Sure, PPSSPP issues are another possibility as well. 

So just thinking the best solution is for us to add a note in the guides, release notes, etc as a suggestion for those on dual-GPU machines to try gfxCardStatus.

**Comment by aktau** [comment]
I agree it's a sticky issue. I can't recall whether 1.0.4 already switched to discrete graphics on the main menu, which would definitely be an unnecessary power drain. I wish there was a good way to discern which games needed the extra boost.

**Comment by clobber** [comment]
2.0 is when the change to integrated first began. So, just to close this out I went ahead and added a line about it (and another issue) to the release notes so at least it can be known. Will also add to various wiki guides.

http://openemu.org/rnotes/2.0.1.html
