### ISSUE TITLE
Connection problems between Openemu and Joypad

### ISSUE THREAD

**Issue by michel-passos** [OpenEmu/OpenEmu#2257]
Hello everybody, someone can give me a light to solve my problem regarding connection the openemu with the joypad, I'm using Macbook Pro, Openemu v 2.0.1 and joypad v1.5.2, when I connect my iPhone to Joypad it works the way programmed, but when I start the ROM in Openemu he does not obey any command, someone has been there or no idea of what can be ?? Please help me!

**Comment by clobber** [comment]
Looks related to this issue #924

Closing since it seems duplicate and will have to troubleshoot it when we get around to it. Honestly, I recommend a real gamepad though.
