### ISSUE TITLE
Trying to run  super mario world 1 but nothing seems to work

### ISSUE THREAD

**Issue by ferlicio** [OpenEmu/OpenEmu#2258]
i've been Trying to run super mario world 1 but nothing seems to work, i tried downloading it three times, but got nothing different, still got a black screen with nothing, not even an error message. i tried seeing other threads and i saw one of the answers was deleting the cores and reinstalling them, but actually i didn't even had a library folder named OpenEmu with the app files

**Comment by clobber** [comment]
Which version of OpenEmu?
