### ISSUE TITLE
PSX Crashing When Opened? 

### ISSUE THREAD

**Issue by JsQuestion** [OpenEmu/OpenEmu#2259]
Just downloaded Version 2.0.1 on my Macbook Pro and finally figured out how to successfully get multi disk titles in the library. I have added the correct BIOS, and everything seems to be working okay. However, whenever I attempt to start the game, I get stuck on a black screen. OpenEmu then proceeds to crash. The game artwork itself also seems to be bugged. Other systems continue to be working properly, any suggestions for the Playstation though?

**Comment by clobber** [comment]
Can't replicate any issues there. Sounds like a bad rip of the game to me, assuming you imported everything correctly. Check the guide again to verify you have done that and let me know how that goes.

Also, .m3u files won't pull down any artwork. Only the individual games.

**Comment by JsQuestion** [comment]
Now that you mention it, the cue sheets I've created don't seem able to be received by the library. I'll keep playing around with it, this is definitely tougher then I imagined it being. Thanks.

**Comment by clobber** [comment]
If that is the case, do follow the guide and read it very closely otherwise you won't be able to get those games running. Import the individual games first (cue sheets), then create an m3u file and import that.

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games
