### ISSUE TITLE
airplay on apple tv

### ISSUE THREAD

**Issue by balyesh** [OpenEmu/OpenEmu#2263]
Is it possible to have an airplay function directly from the emulator so that the computer isnt playing the game as well as the apple tv. 
it can be done where only the apple tv shows the game and the computer is just pushing it to the apple tv rather then mirroring the game.
there other apps that have this function and i think it would be a huge benefit when airplaying the emulator to apple tv.
i can give you examples of apps, pm me for them.

**Comment by clobber** [comment]
> directly from the emulator

Nope.

**Comment by balyesh** [comment]
any chance you can build it out? or look into it?

Ben Alyeshmerni
516-220-0257

**Comment by clobber** [comment]
Sorry, no. It's outside the scope of this project.
