### ISSUE TITLE
Keyboard not working??

### ISSUE THREAD

**Issue by ep007** [OpenEmu/OpenEmu#2265]
So i just installed the latest OpenEmu to play gba games on my brand new Macbook air latest version. When i load the game the controls don't work at all, not even to change the default controls. I read other posts and OpenEmu is not in my ApplicationSupport folder so I don't know what to do about that, and I have google chrome but i made sure it was fully quit before getting on OpenEmu. Everything but OpenEmu was closed at the time. Can anyone help me? I was looking forward to play some GBA games. Thanks!

**Comment by clobber** [comment]
Restart your computer, then only launch OpenEmu and then we'll go from there. Usually some other application causing interference.

**Comment by ep007** [comment]
Unfortunately still an issue. The same thing with the keyboard happened. I don't know if it is something i did but ive uninstalled and reinstalled the program twice already. Also thanks for replying.

**Comment by clobber** [comment]
>same thing with the keyboard happened

Did you mean gamepad or was the original issue the gamepad?

**Comment by ep007** [comment]
well im trying to change the gamepad controls and my keyboard doesnt work. like I can't type anything. Or when im trying to press A for example nothing happens

**Comment by clobber** [comment]
This is just about always some other app interfering. Things such as Chrome and 3rd party terminals and input apps have all be culprits in the past. Start closing other apps down to see if you can find the issue. Sometimes even a restart works.

**Comment by Fibrodysplasia** [comment]
I am having the same issue (wasn't sure if I should open a new ticket). When I go to settings>edit game controls the emulator recognizes input from the keyboard to edit/create keybindings but when I try to actually play a game I'm unable to do anything. 

After restarting my Mac it worked for ~2minutes and then stopped again. No new applications opened during that time

**Comment by Fibrodysplasia** [comment]
Wish I had waited before posting: Problem Solved. Upon shutting down Webroot it works perfectly, no restart required. Open Webfoot back up: Problem returns immediately.

**Comment by sapDevAcct** [comment]
Same issue for me...I briefly used the Nintendo NES USB gamepad successfully, but when I unplug that and try to use the keyboard for other emulators, it doesn't register any keys being pressed. I tried Atari, Coleco, etc., but I can't use the keyboard at all. I quit all processes that could be conflicting, but still no dice. Any other advice?

**Comment by clobber** [comment]
@sapDevAcct Refer to the guide here https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by Fibrodysplasia** [comment]
I solved my issue by disabling secure keyboard entry in Webroot

**Comment by RoryHall2408** [comment]
I have a different problem for some reason I can't press any button on the keyboard and i can't change the game controls for openemu it wants me to press start on the game but I have pressed every key on my keyboard nothing works i have figured out how to delete a key-bind by pressing ESC but I can't add one in its place. Any advice?
