### ISSUE TITLE
Minor bug: Screenshots in games with a forward slash in the title

### ISSUE THREAD

**Issue by bluesdance** [OpenEmu/OpenEmu#2267]
Using OpenEmu 2.01, any attempt to take a screenshot in a game with a forward slash in the title silently fails.

Just thought you'd like to know!

Thanks!!!

**Comment by robotoad** [comment]
Thanks for reporting this. Fixed in <a href="https://github.com/OpenEmu/OpenEmu/commit/3ab4fef3dbf0b5ab6750a2399ac3a19dc3829ee5">3ab4fef</a>.
