### ISSUE TITLE
Minor/medium bug: Loss of aspect ratio… sometimes

### ISSUE THREAD

**Issue by bluesdance** [OpenEmu/OpenEmu#2268]
In OpenEmu 2.01, I opened up 1942, a vertical shmup, in MAME. It started out in the proper aspect ratio, then I hit restart, then I resized the window left-to-right. At this point the width of the game clipped to the shape of the window, which made the game look very "fat."

Restarting the game again, or exiting back out to the menu and going back into the game, fixes the problem and re-achieves the desired behavior, which is the game retaining its proper aspect ratio despite the width of the window.

(★ ★ ★ THANK YOU FOR PUSHING OUT THE NEW VERSION!!! There are so many wonderful improvements / fixes that I have been waiting on!!! My favorite fixes are the "retain full screen when exiting a game" fix, the generic joypad fix, and the MAME save state fix!!!! Viva la OpenEmu!!!!!!!)

**Comment by clobber** [comment]
Doesn't appear to be a problem as of OpenEmu 2.1.1 and the MAME 0.215.1 core plugin.
