### ISSUE TITLE
Indexer / Cover Art grabber does not recognize any "No-Intro" Atari Lynx games

### ISSUE THREAD

**Issue by cabel** [OpenEmu/OpenEmu#2269]
**Summary:** When I import Atari Lynx games from "Goodsets" collection, they are properly recognized and the cover art downloads. But when I import the same Atari Lynx roms from the "No-Intro" collection, this is not the case.

**Solution:** Obviously don't import the No-Intro roms. :) But I'm still curious what would cause this, as I didn't encounter it with any systems when using No-Intro…

_(Can I attach two roms here for comparison? Let me know.)_

**Comment by clobber** [comment]
The "No-Intro" ones, on some websites, are missing the proper headers so they are not being recognized and will also not run in the emulator. Someone with this issue will need to download them elsewhere.
