### ISSUE TITLE
Support OS X 10.10

### ISSUE THREAD

**Issue by cpacejo** [OpenEmu/OpenEmu#2271]
Hi, the new requirement of OS X 10.11 has rendered OpenEmu completely unusable to me (well, slightly more unusable than due to bug #1773).  10.11 has only been out two months, and some users are not yet able or willing to upgrade.  (For me, corporate IT hasn't vetted 10.11 with our stuff yet.)

What feature caused the 10.11 requirement?  Any chance to allow running on 10.10, perhaps with that feature disabled?

**Comment by clobber** [comment]
Nope.

>some users are not yet able or willing to upgrade

Not our problem.

See a detailed explanation: https://github.com/OpenEmu/OpenEmu/issues/2241#issuecomment-167281578
