### ISSUE TITLE
Unprofessional deployment

### ISSUE THREAD

**Issue by cpacejo** [OpenEmu/OpenEmu#2272]
Wow.  I really liked this project, but if you guys (a) can't be bothered to support anyone with an OS more than 3 months old, because *shiny* (#2241), and (b) can't be bothered to even check in the installer if the current OS is supported before *breaking a working installation* (#2271), why should I bother supporting *you*?

Totally unprofessional.

See y'all later.

**Comment by clobber** [comment]
Nope.

**Comment by robotoad** [comment]
@cpacejo 

Responding to this for future reference.

This project is worked on by a very small group of volunteers in our spare time. We don't have the time or means to test compatibility on many previous versions of OS X. Combined with the fact that this was a major version update that was breaking backwards compatibility anyway, we had good reasons to start fresh with 10.11.

A contributing factor in the decision was the fact that OS X updates are not only free but that their system requirements haven't increased in several releases. Someone running Mavericks is capable of running El Capitan, so it's not as if we're expecting large numbers of people to pay for new hardware. Our version requirement follows other applications, including commercial ones, that are moving up their requirements as time goes on--something they have always done.

10.11 dependencies are scattered throughout, including various Foundation initializers, system font APIs, behavior changes like NSNotificationCenter's zeroing weak references for observers, and implicit behavioral dependencies by virtue of the fact the project has been developed and tested with the assumption of 10.11 for a while now. Had there been more time, the dependencies would have been even greater, and I expect to see their use in the near future (e.g., NSCollectionView). Thus, the 10.11 requirement isn't just for 2.0 but is a nod toward future plans.

Assuming Apple's annual update schedule holds, another OS X update will be unveiled a mere six months from now. I can't speak about future backwards compatibility--such decisions would depend on the characteristics of each OS X release--but I do think the extreme level of backwards compatibility seen prior to 2.0 is a policy that has been permanently abandoned. It added a substantial burden to the project.

If you'd rather dismiss all this as "shiny", you're welcome to, but I don't feel a sense of loss over your departure from whatever it is you did for us. I resent your suggestion that we're lazy or don't care. We spent the holiday doing tech support and emergency bug fixes. We love working on the project, and I'm very happy and proud of the release. It's unfortunate that not everybody gets to use it, but that will never not be the case in software development.

In the future, a better method of advocacy would be respectfully communicating with us in the IRC channel and making a persuasive case--even better if you can contribute code to support what you want. This isn't a paid job; none of us are obligated to be professional to you. What you've written here only makes me want to tell you to piss off.
