### ISSUE TITLE
Joypad Connect not working

### ISSUE THREAD

**Issue by arppl** [OpenEmu/OpenEmu#2273]
Hi,

I've tried to use the iPhone with the Joypad Legacy App as a controller for OpenEmu 2.0.1. So after connecting etc. I can see the inputs I make on the iPhone on my Mac without any problems (OSX 10.11.2). I can also edit the controls in the OpenEmu preferences using the iPhone, i.e. the gameplay buttons are being recognized correctly from the iPhone input.

However, if I start a game, no input is going through... Also, if I have the debug window open in Joypad Connect, no input is being logged. If I close the game window in OpenEmu, the input works fine again.

**Comment by clobber** [comment]
Duplicate of #924
