### ISSUE TITLE
SteelSeries Nimbus R1 button not recognized

### ISSUE THREAD

**Issue by nickmodernized** [OpenEmu/OpenEmu#2277]
Hi all,

Great work on getting the DPad for the SteelSeries Nimbus recognized in the latest experimental release.

It could be just me...but the R1 button on the SteelSeries Nimbus does not seem to be recognized in the latest OpenEmu Experimental build.  I've tried to map it in both SNES controls and Sony Playstation controls.

Can anyone confirm?

**Comment by clobber** [comment]
Might just be you? As far as I know, others that tested this out had no issue and I don't see any problem from looking at the mappings.

**Comment by nickmodernized** [comment]
Hmm...I have tried unpairing/repairing, restarting OpenEmu...does anyone else have this controller that you know of on the thread that can confirm or differentiate?

Happy to close the bug if we can get some confirm on it...every button works but R1.

I imagine that the code mapping it is here, yes?

https://github.com/OpenEmu/OpenEmu/blob/2f59701685c3cb5dd98b225e82864ca80d3e29e6/OpenEmu/Controller-Database.plist

I actually have some programming background...is there some way for me to catch the input using another program to test?

As another oddity...the "Up" and "Down" analog sticks seem to be switched on my controller input as well...again, happy to test or see if I have a different version or summat...

**Comment by nickmodernized** [comment]
As an additional note...I manually went into Default.oebindings and made this change:

    <key>OEPSXButtonR1</key>
    <string>OEControllerSteelSeriesWirelessButtonR1</string>

This causes OpenEmu to display "R1" when SteelSeries Nimbus is selected...but the game still refuses to recognize it.

Previous version of OpenEmu did work outside the directional pad...including this button.

**Comment by clobber** [comment]
Analog directions might be switched, those did not get tested.

To log input events in Console.app, run the following in Terminal, `defaults write org.openemu.OpenEmu logsHIDEvents -bool YES`, and button presses should show up there.

When done, disable logging with `defaults delete org.openemu.OpenEmu logsHIDEvents`

**Comment by nickmodernized** [comment]
It logged every single other button, but when pressing the R1 on my Nimbus nothing happened.

It looks like, if I'm reading the code right that we would expect 'Button 6' to log when R1 is pressed...

Is there an external app or something I can test with to look at those codes?  Any other Nimbus owners out there than can replicate?

If it's worthwhile, Here's the dump (of the successful button presses):

12/27/15 9:01:22.021 PM OpenEmu[64116]: Nimbus
12/27/15 9:01:22.021 PM OpenEmuHelperApp[64118]: Nimbus
12/27/15 9:01:28.558 PM OpenEmu[64116]: <OEHIDEvent 0x7fada24ef7f0 pad=0x7fada5ba55f0 type=Button number=8 state=On 'Button 8' cookie=20>
12/27/15 9:01:28.678 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5e0fc70 pad=0x7fada5ba55f0 type=Button number=8 state=Off 'Button 8' cookie=20>
12/27/15 9:01:31.168 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05df8c0 pad=0x7fada5ba55f0 type=Button number=7 state=On 'Button 7' cookie=19>
12/27/15 9:01:31.333 PM OpenEmu[64116]: <OEHIDEvent 0x7fada24ef7f0 pad=0x7fada5ba55f0 type=Button number=7 state=Off 'Button 7' cookie=19>
12/27/15 9:01:32.413 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5cae9a0 pad=0x7fada5ba55f0 type=Button number=5 state=On 'Button 5' cookie=17>
12/27/15 9:01:32.608 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0407e10 pad=0x7fada5ba55f0 type=Button number=5 state=Off 'Button 5' cookie=17>
12/27/15 9:01:33.733 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05d3b60 pad=0x7fada5ba55f0 type=Button number=1 state=On 'Button 1' cookie=13>
12/27/15 9:01:33.853 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0491d10 pad=0x7fada5ba55f0 type=Button number=1 state=Off 'Button 1' cookie=13>
12/27/15 9:01:34.858 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5cae9a0 pad=0x7fada5ba55f0 type=Button number=2 state=On 'Button 2' cookie=14>
12/27/15 9:01:34.978 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05d3b60 pad=0x7fada5ba55f0 type=Button number=2 state=Off 'Button 2' cookie=14>
12/27/15 9:01:36.043 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5d1e320 pad=0x7fada5ba55f0 type=Button number=3 state=On 'Button 3' cookie=15>
12/27/15 9:01:36.148 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05d3c20 pad=0x7fada5ba55f0 type=Button number=3 state=Off 'Button 3' cookie=15>
12/27/15 9:01:37.123 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05df8c0 pad=0x7fada5ba55f0 type=Button number=4 state=On 'Button 4' cookie=16>
12/27/15 9:01:37.228 PM OpenEmu[64116]: <OEHIDEvent 0x7fada25d01a0 pad=0x7fada5ba55f0 type=Button number=4 state=Off 'Button 4' cookie=16>
12/27/15 9:01:38.248 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05df8c0 pad=0x7fada5ba55f0 type=Button number=144 state=On 'D-pad Up' cookie=9>
12/27/15 9:01:38.398 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5d1e320 pad=0x7fada5ba55f0 type=Button number=144 state=Off 'D-pad Up' cookie=9>
12/27/15 9:01:39.343 PM OpenEmu[64116]: <OEHIDEvent 0x7fada041ace0 pad=0x7fada5ba55f0 type=Button number=145 state=On 'D-pad Down' cookie=11>
12/27/15 9:01:39.508 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5cae9a0 pad=0x7fada5ba55f0 type=Button number=145 state=Off 'D-pad Down' cookie=11>
12/27/15 9:01:40.333 PM OpenEmu[64116]: <OEHIDEvent 0x7fada2105bf0 pad=0x7fada5ba55f0 type=Button number=147 state=On 'D-pad Left' cookie=12>
12/27/15 9:01:40.483 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5cc3d50 pad=0x7fada5ba55f0 type=Button number=147 state=Off 'D-pad Left' cookie=12>
12/27/15 9:01:41.428 PM OpenEmu[64116]: <OEHIDEvent 0x7fada246e030 pad=0x7fada5ba55f0 type=Button number=146 state=On 'D-pad Right' cookie=10>
12/27/15 9:01:41.608 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0715590 pad=0x7fada5ba55f0 type=Button number=146 state=Off 'D-pad Right' cookie=10>
12/27/15 9:01:51.373 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05e44d0 pad=0x7fada5ba55f0 type=Button number=5 state=On 'Button 5' cookie=17>
12/27/15 9:01:52.379 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05f43a0 pad=0x7fada5ba55f0 type=Button number=5 state=Off 'Button 5' cookie=17>
12/27/15 9:01:53.113 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0407e10 pad=0x7fada5ba55f0 type=Button number=5 state=On 'Button 5' cookie=17>
12/27/15 9:01:54.103 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05f43a0 pad=0x7fada5ba55f0 type=Button number=5 state=Off 'Button 5' cookie=17>
12/27/15 9:01:57.913 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05a15b0 pad=0x7fada5ba55f0 type=Axis axis=Y direction=Pos value=0.582677 'Y+' cookie=22>
12/27/15 9:01:57.913 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05f4420 pad=0x7fada5ba55f0 type=Axis axis=X direction=Pos value=0.354331 'X+' cookie=21>
12/27/15 9:01:57.943 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c84ad0 pad=0x7fada5ba55f0 type=Axis axis=Y direction=Pos value=1.000000 'Y+' cookie=22>
12/27/15 9:01:57.944 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Pos value=0.464567 'X+' cookie=21>
12/27/15 9:01:57.988 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5cac680 pad=0x7fada5ba55f0 type=Axis axis=X direction=Pos value=0.307087 'X+' cookie=21>
12/27/15 9:01:58.003 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Pos value=0.204724 'X+' cookie=21>
12/27/15 9:01:58.078 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0407e10 pad=0x7fada5ba55f0 type=Axis axis=Y direction=Pos value=0.976378 'Y+' cookie=22>
12/27/15 9:01:58.093 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05f4420 pad=0x7fada5ba55f0 type=Axis axis=Y direction=Pos value=0.653543 'Y+' cookie=22>
12/27/15 9:01:58.094 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05a15b0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Pos value=0.236220 'X+' cookie=21>
12/27/15 9:01:58.108 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5b9ffa0 pad=0x7fada5ba55f0 type=Axis axis=Y direction=Nul value=0.000000 'Y=' cookie=22>
12/27/15 9:01:58.108 PM OpenEmu[64116]: <OEHIDEvent 0x7fada256e9f0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Nul value=0.000000 'X=' cookie=21>
12/27/15 9:01:59.083 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05a15b0 pad=0x7fada5ba55f0 type=Axis axis=Y direction=Neg value=-0.614173 'Y-' cookie=22>
12/27/15 9:01:59.098 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05f4420 pad=0x7fada5ba55f0 type=Axis axis=Y direction=Neg value=-1.000000 'Y-' cookie=22>
12/27/15 9:01:59.248 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0407e10 pad=0x7fada5ba55f0 type=Axis axis=Y direction=Neg value=-0.669291 'Y-' cookie=22>
12/27/15 9:01:59.263 PM OpenEmu[64116]: <OEHIDEvent 0x7fada04547f0 pad=0x7fada5ba55f0 type=Axis axis=Y direction=Nul value=0.000000 'Y=' cookie=22>
12/27/15 9:02:00.133 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Neg value=-0.842520 'X-' cookie=21>
12/27/15 9:02:00.148 PM OpenEmu[64116]: <OEHIDEvent 0x7fada256e9f0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Neg value=-1.000000 'X-' cookie=21>
12/27/15 9:02:00.298 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5b9ffa0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Neg value=-0.677165 'X-' cookie=21>
12/27/15 9:02:00.313 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Nul value=0.000000 'X=' cookie=21>
12/27/15 9:02:01.108 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c84ad0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Pos value=0.330709 'X+' cookie=21>
12/27/15 9:02:01.123 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05f4420 pad=0x7fada5ba55f0 type=Axis axis=X direction=Pos value=1.000000 'X+' cookie=21>
12/27/15 9:02:01.288 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c84ad0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Pos value=0.960630 'X+' cookie=21>
12/27/15 9:02:01.303 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05f4420 pad=0x7fada5ba55f0 type=Axis axis=X direction=Pos value=0.228346 'X+' cookie=21>
12/27/15 9:02:01.318 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c84ad0 pad=0x7fada5ba55f0 type=Axis axis=X direction=Nul value=0.000000 'X=' cookie=21>
12/27/15 9:02:02.053 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5b9ffa0 pad=0x7fada5ba55f0 type=Axis axis=Z direction=Pos value=0.519685 'Z+' cookie=23>
12/27/15 9:02:02.068 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0407e10 pad=0x7fada5ba55f0 type=Axis axis=Z direction=Pos value=1.000000 'Z+' cookie=23>
12/27/15 9:02:02.083 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5b9ffa0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.220472 'Rz+' cookie=24>
12/27/15 9:02:02.113 PM OpenEmu[64116]: <OEHIDEvent 0x7fada046ad70 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.346457 'Rz+' cookie=24>
12/27/15 9:02:02.128 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5d24700 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.401575 'Rz+' cookie=24>
12/27/15 9:02:02.143 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05f4420 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.409449 'Rz+' cookie=24>
12/27/15 9:02:02.158 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05a15b0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.417323 'Rz+' cookie=24>
12/27/15 9:02:02.173 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5d24700 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.425197 'Rz+' cookie=24>
12/27/15 9:02:02.188 PM OpenEmu[64116]: <OEHIDEvent 0x7fada046ad70 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.433071 'Rz+' cookie=24>
12/27/15 9:02:02.218 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.425197 'Rz+' cookie=24>
12/27/15 9:02:02.233 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5cac680 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.259843 'Rz+' cookie=24>
12/27/15 9:02:02.233 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=Z direction=Pos value=0.488189 'Z+' cookie=23>
12/27/15 9:02:02.248 PM OpenEmu[64116]: <OEHIDEvent 0x7fada07239f0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Nul value=0.000000 'Rz=' cookie=24>
12/27/15 9:02:02.248 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5cac680 pad=0x7fada5ba55f0 type=Axis axis=Z direction=Nul value=0.000000 'Z=' cookie=23>
12/27/15 9:02:02.908 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=Z direction=Neg value=-0.275591 'Z-' cookie=23>
12/27/15 9:02:02.923 PM OpenEmu[64116]: <OEHIDEvent 0x7fada04917a0 pad=0x7fada5ba55f0 type=Axis axis=Z direction=Neg value=-1.000000 'Z-' cookie=23>
12/27/15 9:02:03.058 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0407e10 pad=0x7fada5ba55f0 type=Axis axis=Z direction=Neg value=-0.779528 'Z-' cookie=23>
12/27/15 9:02:03.073 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0605090 pad=0x7fada5ba55f0 type=Axis axis=Z direction=Nul value=0.000000 'Z=' cookie=23>
12/27/15 9:02:03.763 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Neg value=-0.834646 'Rz-' cookie=24>
12/27/15 9:02:03.778 PM OpenEmu[64116]: <OEHIDEvent 0x7fada2105bf0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Neg value=-1.000000 'Rz-' cookie=24>
12/27/15 9:02:03.928 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Nul value=0.000000 'Rz=' cookie=24>
12/27/15 9:02:04.543 PM OpenEmu[64116]: <OEHIDEvent 0x7fada07239f0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.456693 'Rz+' cookie=24>
12/27/15 9:02:04.558 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.984252 'Rz+' cookie=24>
12/27/15 9:02:04.573 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5b9ffa0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=1.000000 'Rz+' cookie=24>
12/27/15 9:02:04.693 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5b45b30 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Pos value=0.960630 'Rz+' cookie=24>
12/27/15 9:02:04.708 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5b9ffa0 pad=0x7fada5ba55f0 type=Axis axis=Rz direction=Nul value=0.000000 'Rz=' cookie=24>
12/27/15 9:02:05.563 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5c9eca0 pad=0x7fada5ba55f0 type=Button number=147 state=On 'D-pad Left' cookie=12>
12/27/15 9:02:05.000 PM syslogd[45]: ASL Sender Statistics
12/27/15 9:02:05.698 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5b45b30 pad=0x7fada5ba55f0 type=Button number=147 state=Off 'D-pad Left' cookie=12>
12/27/15 9:02:07.618 PM OpenEmu[64116]: <OEHIDEvent 0x7fada256e9f0 pad=0x7fada5ba55f0 type=Button number=146 state=On 'D-pad Right' cookie=10>
12/27/15 9:02:07.738 PM OpenEmu[64116]: <OEHIDEvent 0x7fada0407e10 pad=0x7fada5ba55f0 type=Button number=146 state=Off 'D-pad Right' cookie=10>
12/27/15 9:02:08.923 PM OpenEmu[64116]: <OEHIDEvent 0x7fada04917a0 pad=0x7fada5ba55f0 type=Button number=145 state=On 'D-pad Down' cookie=11>
12/27/15 9:02:09.073 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05a15b0 pad=0x7fada5ba55f0 type=Button number=145 state=Off 'D-pad Down' cookie=11>
12/27/15 9:02:10.048 PM OpenEmu[64116]: <OEHIDEvent 0x7fada05f4420 pad=0x7fada5ba55f0 type=Button number=144 state=On 'D-pad Up' cookie=9>
12/27/15 9:02:10.198 PM OpenEmu[64116]: <OEHIDEvent 0x7fada2105bf0 pad=0x7fada5ba55f0 type=Button number=144 state=Off 'D-pad Up' cookie=9>
12/27/15 9:02:11.818 PM OpenEmu[64116]: <OEHIDEvent 0x7fada04917a0 pad=0x7fada5ba55f0 type=Button number=547 state=On 'Button 547' cookie=4>
12/27/15 9:02:11.998 PM OpenEmu[64116]: <OEHIDEvent 0x7fada5cae9a0 pad=0x7fada5ba55f0 type=Button number=547 state=Off 'Button 547' cookie=4>

**Comment by nickmodernized** [comment]
Am I allowed to ask some of the folks on this thread to test with the rules of this community?

https://github.com/OpenEmu/OpenEmu/issues/2127

I downloaded the app mentioned on that thread and I got feedback for every single button but R1...which seems to be different than what the other user (ddribin) on that thread had.

It really seems like it must be my controller based on what I'm seeing here...it would seem weird that "Button 6" just doesn't register, but I'd love to confirm with one of the other people on that thread or another Nimbus owner before heading to the Apple Store.

**Comment by clobber** [comment]
I reached out to a few people to see if they are experiencing the same problem, but go for it.

**Comment by nickmodernized** [comment]
Done and done -- we'll see if it's replicatable by others...

**Comment by gingerbeardman** [comment]
How does it look if you use a joystick tester? I use Joystick Show ($0.99 paid) https://itunes.apple.com/gb/app/joystick-show/id515886877?mt=12 

but there are others such as the free HIDbrowser: http://cl.ly/2K1K400t0H3p

I have a Horipad Ultimate, which maps the same as other recent MFi controllers like SteelSeries Nimbus, and the R1 button works fine. 

![screen shot 2015-12-28 at 23 59 38](https://cloud.githubusercontent.com/assets/49612/12027489/18491710-adbf-11e5-84ae-ce6c763ff01e.png)

![screen shot 2015-12-29 at 00 01 40](https://cloud.githubusercontent.com/assets/49612/12027508/5fe14ac0-adbf-11e5-8d01-3b801d46d2b0.png)

(aside: I had an issue where OpenEmu would not recognise any inout - keyboard or controller - so I had to trash my whole config with AppCleaner and reinstall)

**Comment by clobber** [comment]
> (aside: I once had an issue where OpenEmu would not recognise any input - keyboard or controller - so I had to trash my whole OpenEmu install using AppCleaner, and then reinstall)

Just a note: that probably wasn't the best solution and trashing your entire install isn't really conclusive as a fix. There's not any settings data stored that can touch input besides ~/Library/Application Support/OpenEmu/Bindings/Default.oebindings, so more likely, there was a case of another application snagging input and causing interference, which has been quite common in the past with Chrome, sometimes 3rd party terminal and input apps, sometimes a restart is required to work things out. Just saying, before they go and wipe out their whole install as a last resort.

**Comment by gingerbeardman** [comment]
Noted! Thanks

**Comment by ddribin** [comment]
FWIW, I can use R1 in both HID Browser and OpenEmu v2.0.1.

**Comment by clobber** [comment]
Okay @nickmodernized, seems to be a problem with your hardware then, perhaps a faulty button.

**Comment by zanona** [comment]
@nickmodernized by any chance did you find any workaround the R1 button issue? I am having the same thing and was almost sure it was a hardware defect?

**Comment by nickmodernized** [comment]
I did not.  I also left a ticket on the SteelSeries Nimbus support and have
yet to hear a response. :(

Nick

**Comment by danielmcq** [comment]
@nickmodernized
I know this is late, but just so you know that you're not crazy, I have issues with the R1 button as well on my SteelSeries Nimbus. I have only played SNES games on OpenEmu so I didn't worry when I couldn't map that button before. But recently I've been trying to use the controller with other games and I found out that R1 doesn't work at all. I did some dumping of the raw output from the controller and I get the same result: all buttons and sticks produce data except for R1. 

Is there a way I can +1 your ticket with SteelSeries support?

**Comment by zanona** [comment]
@danielmcq just so you know I had to replace the controller :/ it was the most difficult replacement order I had to go through with those guys. But it was a faulty controller unfortunately.

**Comment by nickmodernized** [comment]
I also replaced the controller with the Apple store where I bought it -
even though the warranty and return period was expired, they replaced it
free of charge anyway.

As far as the Nimbus support guys, I think they auto-closed my ticket with
no response. :(
