### ISSUE TITLE
Ongoing issue: Developers don't get enough credit.

### ISSUE THREAD

**Issue by drcreek** [OpenEmu/OpenEmu#2278]
Thank you so much for your hard work and passion and for asking for nothing in return. 

Thanks for bringing us such an awesome project to enjoy and I actually think it's a pretty exciting one to follow. To see new features being discussed and built and watching the devs work together.  I also have to admit a guilty pleasure in watching people come in and complain about pissing little entitlement issues and watching the devs act ENTIRELY "professional" about it. 

But seriously, thanks.

Keep up the good work and don't let the bastards grind you down.

If anyone has anything else to add to this issue. Please do.

**Comment by joshvickerson** [comment]
I completely agree. While I don't have the expertise or time to contribute to this project as much as I would like to, I am watching the project and peek at most of the conversation happening here. All too often I see a very demanding attitude from people who report issues, and it's really unfortunate.

I love OpenEmu so much, v2 especially! Thank you to everyone who dedicates so much time to this incredible piece of software.

**Comment by vgturtle127** [comment]
@drcreek I'm not sure a GitHub issue is the most appropriate place for this, but I understand what you're trying to say. Maybe a more direct public announcement would be more appropriate?

**Comment by nickmodernized** [comment]
Hear hear!  Great job guys!

**Comment by drcreek** [comment]
@vgturtle127

Spoken as a true developer. ;)

I know, but I for the sake of balancing the Kama, I thought it appropriate. Also, as a project issue. I think it's a real problem. I'm not sure what the solution is. But maybe a few more replies will find a way to solve this. I believe this is part of a wider issue but I don't want to bring the good vibes down or start a philosophy argument.

Thanks again to everyone who has contributed their personal time to the benefit of this project.

**Comment by vgturtle127** [comment]
@drcreek I assume you meant karma, not kama. :laughing: 

When you say "developers" you are talking about the OpenEmu developers, right? Not the developers of the original emulators?

I'm not sure how this will be "solved", I think the OpenEmu developers like being humble, although I am just speculating.

I hope I'm not misinterpreting what you are saying when you say "the devs don't get enough credit".

Also, the fact that OpenEmu is Mac-only at the moment might have some part in this issue...
