### ISSUE TITLE
Hasn't worked ever since 2.0.1; please fix it!

### ISSUE THREAD

**Issue by sethh-thomas-1001** [OpenEmu/OpenEmu#2279]
I have a perfectly functional Mac and the emulator was working fine until v2.0.1 came out. When I try to launch a game, nothing happens. None of my games launch, from the Atari 2600 to the SNES. They don't crash, but all methods of trying to launch them always get the same result: they don't work. Occasionally when I try to launch a game the little window will pop up saying, "do you want to continue playing where you left off?", but whether I select "yes" or "no", the same thing happens: nothing. This is by far the greatest and most convenient emulator I've ever used, so please fix it so it can stay that way!

**Comment by clobber** [comment]
Seems this was somehow resolved in our IRC channel earlier by reinstalling or updating the emulator cores.

**Comment by sethh-thomas-1001** [comment]
Thanks. I reinstalled it and everything is now running smoothly. All my games were even saved!
