### ISSUE TITLE
"System Files" prefs panel does not auto-refresh when new BIOSes are installed

### ISSUE THREAD

**Issue by cabel** [OpenEmu/OpenEmu#2281]
**Expected:** As I dragged BIOS files into OpenEMU, the "System Files" panel would automatically refresh with green checkboxes as the proper BIOSes are installed.

**Actual:** The window does not automatically refresh. This was leading me to believe I was loading incorrect BIOSes. Quitting and restarting the app showed the correct state of the BIOS files. (They were fine.)

**Comment by clobber** [comment]
Thanks, planning to redo the "UX" a bit for BIOS handling. You can actually drag and drop the files right into the "BIOS" prefs tab and they do refresh, but should also refresh when dragged into the library as you noted.

**Comment by cyco** [comment]
Fixed in cf7cd1ee214bfd6db8fe10c3f7116ebe0d67fa78, dc15f60051e585da19863f4668cd4bd55d069485 and 5cf0eaca6fb7e2e879c537e936750c730d33c474.
