### ISSUE TITLE
Super Action Controller Buttons Missing in Colecovision Control Panel

### ISSUE THREAD

**Issue by VonMagnum** [OpenEmu/OpenEmu#2283]
You cannot properly play a Colecovision Super Action Controller game because there is no way to assign the extra two buttons (e.g. to aim and grenade in the game Frontline) the controller has for those games.  I would imagine a similar problem exists for playing steering wheel games (i.e. Turbo, Destructor and Dukes of Hazard) relative to the steering wheel controller.  It would be nice if these could be mapped to appropriate controllers and/or buttons.

**Comment by clobber** [comment]
Unfortunately, the emulator in use doesn't support those peripherals yet. Once they do, I will add them.

Though I will probably look at using BlueMSX as the default ColecoVision core plugin instead.
