### ISSUE TITLE
Sega Mega CD multi-disc-games are imported as PSX games

### ISSUE THREAD

**Issue by Phosphor303** [OpenEmu/OpenEmu#2284]
Congratulations on your newest major release!

I find that the wiki entry for CD based games should mention that multi-disc games are only supported for Mednafen right now.

Trying the m3u trick with Sega Mega CD games results in OpenEmu mistaking them for PSX games. Maybe an error message would be a more appropriate behavior of OpenEmu when a user tries to do that.

**Comment by clobber** [comment]
Multi-disc (m3u) is not yet supported for that system and emulator so I will add a note to the wiki.
