### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by erobles396010** [OpenEmu/OpenEmu#2285]
When i updated the emu to version 2.0.1 all my sega genesis save states deleted please help how can i get them back i noticed the all appeared  in my trash folder PLEASE HELP!!!!!!!!!!! and also when are you guys gonna release the 3do aka 4do emulator thanks and please respond

**Comment by robotoad** [comment]
This is explained in the <a href="http://openemu.org/rnotes/2.0.1.html">release notes</a>:

"Previous Sega Genesis/Mega Drive save states have been removed due to unresolvable incompatibilities with the Genesis Plus GX emulator."
