### ISSUE TITLE
controllers mismatch

### ISSUE THREAD

**Issue by chinsta** [OpenEmu/OpenEmu#2288]
Although my controller, 8bitdo NES30 pro, is not in the list of support controllers, everytime i plug in, it can be correctly detected and auto matched every buttons, except the cross button. the emulator can detect my 'up' as 'north', but match as 'west'. and 'down' as 'east', 'left' as 'north', right as 'south'. The confusion is, every time when set it correctly and quit the app, then it is still mismatched as before and it seems like never save my match settings. So i wonder if there anywhere in the code causes this problem. THX!

**Comment by clobber** [comment]
Sounds just like this issue here: #2255

**Comment by clobber** [comment]
#2395
