### ISSUE TITLE
Xenogears lost save

### ISSUE THREAD

**Issue by Jesse525** [OpenEmu/OpenEmu#2292]
i was playing Xenogears today and was about 8 hours in. an the game randomly restarted an i lost my save spot. i was doing the memory card save and save state. The Save state i have is only like 4 hours in. So anyone have an idea of were that save could be on the system, it can't be completely gone.........right?

**Comment by clobber** [comment]
You have to be real careful with save states. When you load one, it completely restores everything that was in memory including the state of the memory card. If your memory card has already been overwritten, which it sounds like it has, there is no way to recover it.

It is best to either rely only on the memory card (in-game saves) or saves states; pick one but try not to mix the use of either.
