### ISSUE TITLE
Minor bug: Renaming collections after starting OE

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/OpenEmu#2294]
Kinda non-important, but when i rename a collection after a fresh start of OE, the "enter new name"-area becomes blue-ish. Afterwards it looks/behaves completly normal.

![bildschirmfoto 2015-12-30 um 15 07 04](https://cloud.githubusercontent.com/assets/10595183/12051747/d020cc40-af07-11e5-9c59-d2e027d345da.png)

(PS: Love your new release, but i still dig the bigger shadows and the more individual bg style. :P

Selfishly altered & compiled latest version)

**Comment by robotoad** [comment]
I've seen this before but couldn't replicate it 100% of the time. As I recall, clicking or typing makes the blue bar disappear, so it's a visual artifact that doesn't affect renaming functionality. Will investigate further.

**Comment by PlutoX86** [comment]
![bildschirmfoto 2017-11-26 um 22 56 13](https://user-images.githubusercontent.com/10595183/33244747-27e6824c-d2fd-11e7-94c1-63f85a1cc1dd.png)

Almost! xD j/k

**Comment by clobber** [comment]
Appears fixed for next release, probably from commit 0931b66eb7bbc33bfdbd6e3c0cf28147dbeeddfd
