### ISSUE TITLE
New emulator and Old updates to new update?

### ISSUE THREAD

**Issue by azoreseuropa** [OpenEmu/OpenEmu#2295]
Are you going to update old Mame version to MAME 0.169?

What about PCSX2 ?

Which PSX emulator do you use ? Mednafen or PCSXR? I like PCSXR. 

What about mGBA emulator ? Its accurate and brand new emulator for MAC OS X. Its very excellent emulator. Check this out: https://mgba.io

Thanks.

**Comment by clobber** [comment]
1) Some day

2) Not sure

3) Mednafen

4) We're aware and may port it eventually.

**Comment by azoreseuropa** [comment]
Thanks.

Why are you not sure about PCSX2 ? :(

Are you going to add PCSX-Reloaded 1.9.93? Its great emulator. Here:

https://pcsxr.codeplex.com
