### ISSUE TITLE
Arcade not working

### ISSUE THREAD

**Issue by geoffbuck** [OpenEmu/OpenEmu#2296]
Hi,

I'm having an issue with playing arcade/MAME games on Openemu.
I have some MAME roms in .zip format that I placed in Openemu.
The games appear in the arcade section just fine (although they do not have their cover downloaded).
But when I try to play them I just get a black screen. I do not get any error message or anything. Just a black screen and nothing happens.
I cannot find any topic regarding this kind of problem. When I look at tutorials on how to play MAME games, people just place the games in Openemu and it just works.
I though I could be missing a BIOS file but I don't know which one. I have placed a bunch of BIOS files for arcade games that I found on Internet but nothing changes.
I even deleted and reinstalled Openemu without any success.

Could anyone help me please ?

Thanks.

**Comment by azoreseuropa** [comment]
Same here. Just a black screen and nothing happens. So, I have to exit it but it won't let me at all.

**Comment by PlutoX86** [comment]
Just a quick help, for cps games (street fighter alpha 3, etc) & neogeo games (kof96, etc) you need a qsound.zip & neogeo.zip in your "game library/roms/arcade" folder). For covers, just make a ingame screenshot and drag'n'drop them into your games in 'grid view'.

**Comment by geoffbuck** [comment]
@azoreseuropa 
How do you get the warning to tell you what's the missing file ?

@PlutoX86 
Thanks. I added sound.zip and neogeo.zip and I managed to make some games work. But the ones that are not neogeo are still displaying a black screen. I added a pack of zip called "BIOSMame" in the folder but it didn't change anything.

**Comment by PhantomKnight64** [comment]
I think if you open console from spotlight and keep it open while starting a game it will say what files are missing in the audit section(press arrow facing right so it will face down and show the list)

**Comment by PlutoX86** [comment]
Yeah.. just google something like "complete mame 0.149 bioses", drag them in your arcade folder and delete ones you don't need afterwards. ;)

**Comment by geoffbuck** [comment]
@PlutoX86 
I found a full MAME 0.149 BIOS pack and placed it in the arcade folder but it didn't change anything.

Looks like more games are working with this pack of bios.
Some aren't but I guess not all of them are compatible.

Thanks for your help.
