### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by azoreseuropa** [OpenEmu/OpenEmu#2299]
Thanks.

Why are you not sure about PCSX2 ? :(

Are you going to add PCSX-Reloaded 1.9.93? Its great emulator. Here:

https://pcsxr.codeplex.com

**Comment by clobber** [comment]
PCSX2 is not possible for us to port until it has x86_64 compatibility, so probably never.

PCSX-R is not a great emulator. It relies on hacks and inaccurate GPU plugins for emulation and has tons of compatibility issues.
