### ISSUE TITLE
Is it possible to disable the sound completely?

### ISSUE THREAD

**Issue by erythrocytes** [OpenEmu/OpenEmu#2300]
It's a bit of an odd question, but is it possible to disable the sound completely in the emulator? I'm asking because I'm usually playing with sound muted while listening to music. But more importantly, I noticed that whenever a game is running in the emulator, there's a constant high-pitched hum of sorts coming from the speakers, even with sound muted (at least in Neo Geo games). Of course it's not that big of a big deal for me but it's a little irritating to my ears, I wish I could turn it off.

**Comment by clobber** [comment]
There is a volume slider right there on the HUD bar

**Comment by erythrocytes** [comment]
I know that. I mean not muting, but maybe disabling sound emulation altogether. So if I open a new game, I don't have to mute it again, and the volume slider won't work.

**Comment by clobber** [comment]
No, there is no way to disable sound emulation.

**Comment by erythrocytes** [comment]
OK, thanks for clarifying this.
