### ISSUE TITLE
Can't quit OpenEmu 2.01 (MacOSx El Capitan 10.11.3)

### ISSUE THREAD

**Issue by Ariken** [OpenEmu/OpenEmu#2301]
Everything works perfectly, but as I try to quit openemu, it doesn't. Keeps running as I don't press quit.
The only way to quit OpenEmu is Force Quit with Activity Monitor.

Any help?

Thanks

**Comment by clobber** [comment]
Need more details here as it sounds like an emulator core has crashed. Which system? Which game?

**Comment by Ariken** [comment]
It happens with every single game (waiamu GBA, all Atari 2600 roms, homebrew, etc. etc.). I'm running under Osx El Capitan 10.11.3 (latest beta) iMac retina 27, using OpenEmu v2.0.1 (407-g415a4a6-Release). 
Every single close action I try (Exit from menu, top left red button, Exit from dock) results in NOTHING. The game keeps running and I can still play. The only way to quit OpenEmu is Force Quit with Activity Monitor
Please tell me if I can give you any more hints.

Thanks

**Comment by ryanproud** [comment]
Away from my Mac right now, but I had a similar issue yesterday.  These are just possible steps to reproduce.
* Imported an incorrect M3U file (filenames were incorrect).
* Tried running the M3U and got a black screen.
* Was unable to quit the application and needed to Force Quit.

**Comment by MScoutsDCI** [comment]
I can confirm the previous post, had the same experience with slightly different specifics.

The "unquitable" black screen, for me, resulted from trying to run MAME games without having the correct BIOS file.  I did this a few times in order to look at the console to determine what I needed.  Each time I could not close out of the black screen without force quitting.

**Comment by Ariken** [comment]
Just deleted ALL OpenEmu files (using AppCleaner) and reinstalled and it quits now.
Thanks

**Comment by robwired** [comment]
This happens if you attempt to run a game and don't have the correct bios/rom files. You then have to force quit OpenEmu and restart. It's pretty consistent. If this is still an issue please let me know and I'll give exact roms and steps to reproduce.

**Comment by clobber** [comment]
#2670
