### ISSUE TITLE
OpenEmu v2.0.1 Not Accepting BIOS scph5502.bin

### ISSUE THREAD

**Issue by derekluciani** [OpenEmu/OpenEmu#2303]
First of all, thanks for delivering the latest version of OpenEmu! Super excited to play the recently added consoles.

I'm having an issue importing the BIOS scph5502.bin file for the Playstation Console. When I drag the .bin file to the window, I get a prompt to resolve an issue. Basically, it won't let me import the file. I also tried to manually place the .bin file in the BIOS folder of the OpenEmu package file and it disappears once I try to load a PSX game. Anyone else having this issue?

<img width="592" alt="screen shot 2015-12-31 at 2 26 12 pm" src="https://cloud.githubusercontent.com/assets/16504121/12067628/2cef63f0-afcb-11e5-98a7-58d15e638df7.png">

<img width="423" alt="screen shot 2015-12-31 at 2 22 31 pm" src="https://cloud.githubusercontent.com/assets/16504121/12067572/ef84f42c-afc9-11e5-8241-fa13515ea993.png">

**Comment by takeshineale128** [comment]
Your S is a capital letter not lower case.

**Comment by derekluciani** [comment]
I noticed that early on but made no difference when I changed it to lowercase.

**Comment by clobber** [comment]
Search the internet, read the guide https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files
