### ISSUE TITLE
OE hangs when trying to start a PS1 game where the bin file is missing

### ISSUE THREAD

**Issue by birphborph** [OpenEmu/OpenEmu#2305]
I had the issue, that a cue file was missing a bin but it was displayed in the OE game browser.
When I try to start this game, the emulation starts but nothing happens (of course)... Black screen, no error message and you cannot quit the emulator or OE itself. You have to Force-Quit OE.

**Comment by clobber** [comment]
Not a lot we can do about this...import all the correct files and the emulator core won't crash.
