### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by azoreseuropa** [OpenEmu/OpenEmu#2307]
How do I get a screenshot ? What key am I looking for on my keyboard ?

**Comment by clobber** [comment]
C'mon, at least check the application out first... It's in the menu bar, Controls > Take Screenshot which happens to be Cmd+T.

**Comment by azoreseuropa** [comment]
Sorry about that but I am looking for... an example: SNES emulator.. when I
take a screenshot. The screenshot is too big. I am trying to make this
resolution to 256X240 or 256X224 if you know what i mean.

**Comment by PlutoX86** [comment]
I think the photoshop core comes with the next release. Or you could try to move away from your mac till the size fits. :)

**Comment by azoreseuropa** [comment]
Great. I will wait for the next release instead. Keep up the good work! By
the way, did you know there is new PS2 emulator in the working ? Yes, its
called Play! Emulator. It is still in development and the compatibility is
very low. You can take a look at this one: http://purei.org
