### ISSUE TITLE
PSX audio choppy, distorted

### ISSUE THREAD

**Issue by limitlesslimits** [OpenEmu/OpenEmu#2309]
Just installed all the SCPH files needed for Mednafen to run PSX games, but when I started the game the boot screen cut itself a bit short near the end of the PS logo's appearance.
***
Afterwards, I started the game, and the BGM sounded very weird and distorted along with the game itself lagging a bit more than usual.

* Is it a problem with Mednafen?
* Did I install the wrong variant of one of the SCPH files?

***
Any information as to what is probably causing this is greatly appreciated. I'll look into what may be causing the problem as well.

Thanks for your time.

**Comment by clobber** [comment]
No, not a BIOS file related issue. Could be any of the following:

* Emulator bug with that certain game (though not so likely).
* Filter you are using is too much for your GPU to handle, try switching to Nearest Neighbor
* Your CPU isn't powerful enough. PSX emulation is completely CPU-bound and requires a decent CPU to run full speed. Some of the Macs, especially the MacBook Air's have lower-end CPU's
* Something else you have running is using a lot of your machine's resources, so try closing other applications.
