### ISSUE TITLE
Playstation Cheats?

### ISSUE THREAD

**Issue by bobmason2991** [OpenEmu/OpenEmu#2310]
Is it possible to use gameshark codes for playstation games on the emulator? Sorry if this has been asked before, I looked around and didn't see it.

**Comment by clobber** [comment]
No, not yet. In a future Mednafen core plugin update once it is easier to hook that up.

**Comment by reddrag0n** [comment]
I found a way to use cheats with PSX games. Takes a bit of work, but it involves adding a gameshark game and editing an m3u file (mine was FF7)

**Comment by cloroxxxx** [comment]
@reddrag0n Hey how did you edit your m3u file?

**Comment by reddrag0n** [comment]
once i get home from work, ill explain everything i did

**Comment by reddrag0n** [comment]
this pic might show you what i was doing. i got the game shark cd and put it with the regular games. then from there, any game i wanted cheats for, i added the info to the game m3u file. now whenever i open a game, it opens the gameshark cd first, then when it asks to load the disk, i then select the regular cd in the opener cd witch menu. for me it works.

**Comment by cloroxxxx** [comment]
@reddrag0n I don't see them pic, can we chat through email? spamme424@gmail.com

**Comment by thiago1805** [comment]
@reddrag0n can you send me the pic and the way to to m3u file?

**Comment by clobber** [comment]
Figure it out and make your own: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game
