### ISSUE TITLE
Couldn’t communicate with a helper application.

### ISSUE THREAD

**Issue by Yungtang** [OpenEmu/OpenEmu#2311]
Hi,

Since I updated OpenEmu I can't play to any of my games (I only use VBA), I tried to delete the core and re download it but it didn't worked and reinstalling OpenEmu didn't worked too...
Is there someone that could help me ? 

Btw Happy New Year :)

And sorry for my bad english !

**Comment by Yungtang** [comment]
I'm running the app on a macbook air with el Capitan 10.11.2

**Comment by clobber** [comment]
Which version of OpenEmu? Which version of VisualBoyAdvance? Go into Preference > Cores to verify you have the latest installed.

**Comment by joshvickerson** [comment]
I'm experiencing this problem while testing the new mgba core under development by @endrift. It appears to have installed correctly and it appears in the core list in the preferences pane, but when I try to open a game with it I get that error message. What can I provide that will give you more information? Not sure what you need to look into this further.
![screen shot 2016-01-03 at 12 57 38 pm](https://cloud.githubusercontent.com/assets/2325487/12080236/0e47edf4-b21a-11e5-9c91-d07177e53cb3.png)

**Comment by clobber** [comment]
@joshvickerson That is still unsupported, WIP and not related to this issue.

**Comment by endrift** [comment]
fwiw, that happens when the core crashes, so it's entirely likely that it's a bug in the mGBA core.
