### ISSUE TITLE
Issue importing SNES9x files to OpenEmu

### ISSUE THREAD

**Issue by strawberrymilk** [OpenEmu/OpenEmu#2312]
I started playing Chrono Trigger again about a month ago using Snes9x and recently decided to start utilizing OpenEmu since it proved to be a better platform all around. I was glad to find that the file transfer would be compatible after reading several other repositories and conversations here and on other forums, so I started the following process:

1. Add Chrono Trigger to my Game Library in OpenEmu, then close.
2. Open ~/Library/Application Support/OpenEmu/SNES9x/Battery Saves in one Finder window, open ~/Library/Application Support/SNES9x/SRAMs in another.
3. Copy the save files from SNES9x's SRAMs directly into OpenEmu's Battery Saves as they are. (i.e., Chrono Trigger (USA).srm).
4. Launch OpenEmu.

Then I looked in Save States and found nothing. I also tried launching the game itself and I was taken straight back to the screen for a brand new game. I really don't want to lose all of the progress I've made. Have I missed a step?

Thanks!

**Comment by clobber** [comment]
You need to:
* Right click on `Chrono Trigger (USA).srm` and select Get Info, then under "Name & Extension" change the file extension from srm to sav
* Launch OpenEmu, go to OpenEmu > Preferences > Library, click "Reset warnings" and when you launch your game click "No" when prompted to "Continue where you left off"

**Comment by strawberrymilk** [comment]
After resetting warnings and launching the game I wasn't prompted with "Continue where you left off." Do I delete the file from SNES9x completely or just copy it over?

**Comment by strawberrymilk** [comment]
Update: I launched the game, played a little, then closed it. I went back into Library > Preferences > Reset warnings, and was then prompted with "Continue where you left off." I still do not have the SNES9x save.

**Comment by clobber** [comment]
Importing an in-game save (battery save) is not a "Save State" and will not make anything appear under "Save States"

You need to save your progress in-game on snes9x and then import that battery save file to OpenEmu following those guidelines you have listed above.

**Comment by strawberrymilk** [comment]
Okay thank you.

When I import the battery save file, do I completely eradicate it from snes9x in the transfer process or do I just copy and paste it? Would it make a difference if I later choose to uninstall snes9x?

**Comment by clobber** [comment]
I don't see any reason to delete it. Might as well keep it if you want a backup, but you can copy and paste the file over.

**Comment by strawberrymilk** [comment]
I opened snes9x and saved the game again, copied the Chrono Trigger (USA).srm file from SNES9x/SRAMs to SNES9x/Battery Saves, then changed the file name to .sav

I launched OpenEmu and after resetting warnings and being prompted with continuing the game to say "No", I still do not come up with my save. I'm really hating the idea that I'll have to start the game over.

**Comment by spurll** [comment]
I was having a similar issue loading in my saves from BSNES for OS X. The saves claimed to be SRM files, but I noticed that they weren't 8 kB (most were much smaller) and I couldn't find any information about BSNES save formats anywhere. Obviously they were compressed in some way, and on a hunch, I renamed them to .ZIP and they extracted just fine. After extracting they loaded into OpenEmu with no problem.

I know that this comment is only tangentially related to this issue, but perhaps it will help someone with a similar problem somewhere.

**Comment by Jefferson227** [comment]
Just passing by to inform that it worked for me (in 2023) by doing as @clobber mentioned at first place:

- Right click on Chrono Trigger (USA).srm and select Get Info, then under "Name & Extension" change the file extension from srm to sav
- Launch OpenEmu, go to OpenEmu > Preferences > Library, click "Reset warnings" and when you launch your game click "No" when prompted to "Continue where you left off"
