### ISSUE TITLE
NDS: OpenEmu freezes upon loading QuickSaves

### ISSUE THREAD

**Issue by ntvngo** [OpenEmu/OpenEmu#2314]
On OpenEmu v. 2.0.1, "407-g415a4a6-Release", when playing a DS game via DeSmuME, loading a QuickSave intermittently results in a hang of the game - sprites freeze and game music stops, although the emulator still shows the game as "playing" as opposed to "paused" on the HUD bar. Attempting to further interact causes the emulator to switch the game state to "paused" and then the rest of the application becomes unresponsive. Trying to stop emulation, close OpenEmu, or interact in any way is unsuccessful.

**Comment by pucksaint** [comment]
I'm having exactly the same issue. Here's a screenshot of the core im using because I've seen other similar issues be due to the core being used, hope this gets addressed!
<img width="402" alt="screen shot 2016-01-15 at 5 47 15 pm" src="https://cloud.githubusercontent.com/assets/16726682/12367553/e96c600a-bbb0-11e5-90bf-09799b81a095.png">

**Comment by clobber** [comment]
@pucksaint, No you aren't having the same issue. 1.x is unsupported and you cannot use the core plugins meant for 2.x with 1.x

**Comment by intrepidsg** [comment]
I'm also having quick-load issues, DeSmuMe 0.9.11, OpenEmu v2.0.3 579-gf929d38-Release (as well as previous versions).

Intermittently when I load my quick-save the app will lock up. Game is in 'play' mode but it is frozen, and when the emulator enters this frozen state there is no way to reset or power-off the emulator. There is also no way to quit the app, as it is unresponsive to my dialogue selections. Force-quit is the only way out.

Previously I had this issue and somehow it fixed itself, but I am unable to reproduce.

**Comment by clobber** [comment]
Thanks for pinging this, I forgot to address it earlier. So what's going on is an issue with Desmume's JIT dynarec that is outside our control.

NDS games can be timing-sensitive, especially ones that had AP measures built-in. The OpenEmu core plugin of Desmume ships with the JIT dynarec **turned on** for speed and power savings. This has the unfortunate side effect of introducing compatibility and other glitches in some games. The standalone version of Desmume has the dynarec **off** by default, but will run slower and consume much more CPU time -- the upside being improved compatibility. Furthermore, some games (especially Pokemon, first-party or big studio releases) require patches to circumvent built-in AP measures which can also affect compatibility.

Recommend to use the standalone version of Desmume when running into problems, until they have addressed bugs with the dynarec.

**Comment by intrepidsg** [comment]
Thanks, Clobber; you guys really know your stuff.

I found that if I just leave the app open and running for a while it will
eventually correct itself, but I'll keep your advice in mind.

Cheers!

**Comment by Anonymous20475** [comment]
How long did you leave it on for because i am facing a similar problem
