### ISSUE TITLE
analog game pad reponds as off/on instead of giving full dynamic range

### ISSUE THREAD

**Issue by jeffdoll-wf** [OpenEmu/OpenEmu#2315]
I'm attempting to use a Logitech F310 for N64 games. When I attempt to use the joypad, the game responds as you would expect when using a dpad instead of the analog joystick. The game responds with an on/off behavior for the direction activated on the controller.

**Comment by clobber** [comment]
This was fixed in https://github.com/OpenEmu/Mupen64Plus-Core/commit/44dd073396e104c32d8dd5768b427ec9c93fe775 and the core update will go out alongside OpenEmu 2.0.5 or before then.
