### ISSUE TITLE
Can't install cores

### ISSUE THREAD

**Issue by pacmac34** [OpenEmu/OpenEmu#2316]
Hello,

if I launch a ROM, it tries to download it's core, but tells me that there should be an internet connection problem. If I go through preferences -> cores and press install button, nothing happens. There are no significant info in the Mac OS X Console log. I am running El Capitan 10.11.2 version and OpenEmu latest and experimental (OpenEmu 2) versions with same result. I have tried launching it with sudo too and to delete all my SSL certs at keychain app (lock is in green colour at all my browsers).

logs here:

http://pastebin.com/0dUznuA1

Thank you so much.

**Comment by clobber** [comment]
It's a problem on your end with your machine and internet connection, not a lot we can do.

Usually it has to do with your machine rejecting connections to GitHub and their SSL cert so you can try these methods to fix:

* http://superuser.com/questions/605900/why-wont-os-x-trust-githubs-ssl-certificate
* https://blog.digicert.com/expired-intermediate-certificate/

That's really all the help we can offer.

**Comment by pacmac34** [comment]
lol my SSL cert isn't expired
