### ISSUE TITLE
Unable to open SNES Higan sav file in SNES9x

### ISSUE THREAD

**Issue by plughie** [OpenEmu/OpenEmu#2317]
I copied a Higan .ram file to the SNES9x folder and renamed to [GAME NAME].sav, but trying to load the game. Am I barking up the wrong tree here? Is there any way to transfer a Higan core battery save to the SNES9x core?

**Comment by clobber** [comment]
You need to make sure you are not also restoring an autosave state when you load the game.

Launch OpenEmu, go to OpenEmu > Preferences > Library, click "Reset warnings" and when you launch your game click "No" if prompted to "Continue where you left off"

Also double check the file extension is actually .sav by right clicking on your save file and select Get Info, then look under "Name & Extension"
