### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by apostols** [OpenEmu/OpenEmu#2319]
Hi,
I'm trying to compile OpenEmu the following instructions:

git clone --recursive https://github.com/OpenEmu/OpenEmu.git
cd OpenEmu
and show the following errors:

.
.
.

CompileC /Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/Objects-normal/x86_64/OESystemController.o OpenEmuSystem/OESystemController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/juan/src/OpenEmu/OpenEmu-SDK
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=80 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/juan/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/juan/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Xclang -fmodule-implementation-of -Xclang OpenEmuSystem -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.11 -g -Wno-sign-conversion -iquote /Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/OpenEmuSystem-generated-files.hmap -I/Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/OpenEmuSystem-own-target-headers.hmap -I/Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/OpenEmuSystem-all-non-framework-target-headers.hmap -ivfsoverlay /Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/all-product-headers.yaml -iquote /Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/OpenEmuSystem-project-headers.hmap -I/Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Products/Release/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/DerivedSources/x86_64 -I/Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/DerivedSources -F/Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Products/Release -include /Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OpenEmuSystem-Prefix.pch -MMD -MT dependencies -MF /Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/Objects-normal/x86_64/OESystemController.d --serialize-diagnostics /Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/Objects-normal/x86_64/OESystemController.dia -c /Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.m -o /Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/Objects-normal/x86_64/OESystemController.o
In file included from /Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.m:27:
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:115:26: error: 
      expected '>'
+ (NSDictionary<NSString *, OEGlobalKeyBindingDescription *> *)globalKey...
                         ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:115:27: error: 
      expected ')'
+ (NSDictionary<NSString *, OEGlobalKeyBindingDescription *> *)globalKey...
                          ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:115:3: note: 
      to match this '('
+ (NSDictionary<NSString *, OEGlobalKeyBindingDescription *> *)globalKey...
  ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:116:43: error: 
      expected '>'
@property(readonly) NSDictionary<NSString *, OEGlobalKeyBindingDescripti...
                                          ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:116:44: error: 
      expected member name or ';' after declaration specifiers
@property(readonly) NSDictionary<NSString *, OEGlobalKeyBindingDescripti...
                    ~~~~~~~~~~~~           ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:116:1: error: 
      property requires fields to be named
@property(readonly) NSDictionary<NSString *, OEGlobalKeyBindingDescripti...
^                   ~~~~~~~~~~~~~~~~~~~~~~~
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:116:46: error: 
      interface type cannot be statically allocated
@property(readonly) NSDictionary<NSString *, OEGlobalKeyBindingDescripti...
                                             ^
                                *
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:116:75: error: 
      expected ';' at end of declaration list
  ...NSDictionary<NSString *, OEGlobalKeyBindingDescription *> *globalKeyBind...
                                                           ^
                                                           ;
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:116:77: error: 
      expected identifier or '('
  ...NSDictionary<NSString *, OEGlobalKeyBindingDescription *> *globalKeyBind...
                                                             ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:120:43: error: 
      expected '>'
@property(readonly) NSDictionary<NSString *, OEKeyBindingDescription *> ...
                                          ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:120:44: error: 
      expected member name or ';' after declaration specifiers
@property(readonly) NSDictionary<NSString *, OEKeyBindingDescription *> ...
                    ~~~~~~~~~~~~           ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:120:1: error: 
      property requires fields to be named
@property(readonly) NSDictionary<NSString *, OEKeyBindingDescription *> ...
^                   ~~~~~~~~~~~~~~~~~~~~~~~
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:120:46: error: 
      interface type cannot be statically allocated
@property(readonly) NSDictionary<NSString *, OEKeyBindingDescription *> ...
                                             ^
                                *
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:120:69: error: 
      expected ';' at end of declaration list
  ...NSDictionary<NSString *, OEKeyBindingDescription *> *allKeyBindingsDescr...
                                                     ^
                                                     ;
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:120:71: error: 
      expected identifier or '('
  ...NSDictionary<NSString *, OEKeyBindingDescription *> *allKeyBindingsDescr...
                                                       ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:121:43: error: 
      expected '>'
@property(readonly) NSDictionary<NSString *, OEKeyBindingDescription *> ...
                                          ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:121:44: error: 
      expected member name or ';' after declaration specifiers
@property(readonly) NSDictionary<NSString *, OEKeyBindingDescription *> ...
                    ~~~~~~~~~~~~           ^
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:121:1: error: 
      property requires fields to be named
@property(readonly) NSDictionary<NSString *, OEKeyBindingDescription *> ...
^                   ~~~~~~~~~~~~~~~~~~~~~~~
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:121:46: error: 
      interface type cannot be statically allocated
@property(readonly) NSDictionary<NSString *, OEKeyBindingDescription *> ...
                                             ^
                                *
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:121:46: error: 
      property has a previous declaration
/Users/juan/src/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemController.h:120:46: note: 
      property declared here
@property(readonly) NSDictionary<NSString *, OEKeyBindingDescription *> ...
                                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/juan/Library/Developer/Xcode/DerivedData/OpenEmu-flfnbmorkxmzcwbkvvolgnaeslwo/Build/Intermediates/OpenEmu-SDK.build/Release/OpenEmuSystem.build/Objects-normal/x86_64/OESystemController.o OpenEmuSystem/OESystemController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

I have:

$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.10.3 (14D136)
      Kernel Version: Darwin 14.3.0
      Boot Volume: Principal
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      Time since boot: 5:33

$ xcodebuild -version
Xcode 6.3.1
Build version 6D1002

Thanks you!

**Comment by clobber** [comment]
> 10.10.3

> Xcode 6.3.1

??

You need to be using the latest Xcode as well as OS X 10.11
