### ISSUE TITLE
SNES games on OpenEmu not launching

### ISSUE THREAD

**Issue by ThBerenguier** [OpenEmu/OpenEmu#2322]
Hi,
I've recently downloaded OpenEmu, and I've installed NES and SNES roms. All NES roms run good, but when I try to launch SNES roms, nothing happened.

I run OpenEmu 1.0.4 on OSX 10.7.5. 
The SNES cores are Higan 0.95 and SNES9x 1.53.4

Thank's for your help !! And congrats for this great work !

**Comment by clobber** [comment]
Well OpenEmu 1.x is unsupported now. You need to update to OS X 10.11 and OpenEmu 2.0

#2243

**Comment by ThBerenguier** [comment]
Thank you for that quick answer.
The problem is I can't update to 10.11 (nor 10.9 and 10.10) cause some of my softwares can't run on it.
Could you just tell me if it's possible or not for me to play SNES roms with OE 1.0.4 with my settings, to know if spending time to fix it is valuable.

Thank's again =]
