### ISSUE TITLE
Star Wars Pod Racer 1/2 screen only

### ISSUE THREAD

**Issue by ruben8448** [OpenEmu/OpenEmu#2324]
When i try to play star wars pod racer i am only able to see half the screen.  The entire game seems shifted. I am on the newest version of openemu. I've attached an image
<img width="1440" alt="screen shot 2016-01-03 at 11 45 21 pm" src="https://cloud.githubusercontent.com/assets/16534527/12084675/1ff6d5c4-b274-11e5-9be2-430fca6778ff.png">

**Comment by clobber** [comment]
A general N64 emulation and GPU plugin bug.  Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
