### ISSUE TITLE
Problem loading new Playstation games

### ISSUE THREAD

**Issue by Dannyboy289** [OpenEmu/OpenEmu#2328]
Hello, I'm a novice when it comes to this sort of thing, can generally get things to work ok but this has me stumped. I've had a few ROMs for Playstation for a while now and used PSX ok. I was delighted to see OpenEmu now supported Playstation and I've enjoyed playing my games on there. The problem is when I've come to load a new game into the system it just doesn't recognise it. When I've unpacked the 7z file I saw there was now .cue file so created one in line with the instructions provided but when I drag both files to the library it just doesn't do anything. Can anyone tell me what I'm doing wrong please.

**Comment by clobber** [comment]
I'm guessing either the cue sheet was made incorrecly (really need to make sure you followed the guide closely) or it's a bad rip of the game, in which you'll need to find another.
