### ISSUE TITLE
PPSSPP on OpenEmu 

### ISSUE THREAD

**Issue by pretochines** [OpenEmu/OpenEmu#2329]
Is there a way of installing the PPSSPP on OpenEmu 1.0.4. (OS X Yosemite)? I have PPSSPP 1.0. running on my Macbook Pro. Just wondering if there is a plugin file that I can copy to the OpenEmu folder since I noticed that all the emulators are labeled as plugins and put in that folder. When I searched the PPSSPP's contents and folders I did not find any plugin file so I'm guessing it's an app or some software that does this job. Am I wrong?

**Comment by clobber** [comment]
1.x is unsupported and PPSSPP requires v2. I'd suggest just using the standalone PPSSPP from their website.

**Comment by pretochines** [comment]
yeah thanks, that's what i am doing
