### ISSUE TITLE
Can not import BIOS file (for PlayStation emu)

### ISSUE THREAD

**Issue by qwwwpp** [OpenEmu/OpenEmu#2330]
Every time I try to drag and drop "scph5500.bin" (PlayStation), there will always be an import issue. It looks like this.
<img width="180" alt="2016-01-05 9 58 09" src="https://cloud.githubusercontent.com/assets/11554486/12116816/77dd11c0-b3f7-11e5-9435-d5de4a3597e2.png">

click "resolve 1 issue"
<img width="822" alt="2016-01-05 10 01 20" src="https://cloud.githubusercontent.com/assets/11554486/12116893/eecbc1e6-b3f7-11e5-87ae-ee4019d3eb31.png">

BTW, the md5 is correct.

**Comment by cyco** [comment]
Try importing it in the preferences. Go to 'System Files' and drag your bios into the view there.

**Comment by clobber** [comment]
Fixed in acb865afd0a4211f4ae8a509a02d9fbfbc3b2c9d for next release.

**Comment by clobber** [comment]
In the mean time, if BIOS files were not importing correctly after a new core install, please remove the imported files, restart the app and import your BIOS files again -- as the release notes state.

**Comment by Solarstrike** [comment]
No mean to revive a dead issue, but I am suffering similar problems with 5502.
I have tried every measure possible, but the BIOS will not import properly.

**Comment by Solarstrike** [comment]
Nevermind, MD5 sum was incorrect.
