### ISSUE TITLE
Control latency with PPSSPP core

### ISSUE THREAD

**Issue by lorenzobulfone** [OpenEmu/OpenEmu#2335]
Started playing Patapon (rhythm-based game) using the PPSSPP 1.1.1 core and noticed a delay in my controls input. At first I thought I was just bad at the game (the delay is not very high but definitely noticeable in a rhythm game), but then I installed PPSSPP via Homebrew, and now the game works great, so it's not me being terrible at it or PSPSPP's fault.

Running both openEmu and PPSSPP on a early 2014 rMBP (2,6 GHz i5, 8GB RAM, Intel HD Graphics 4000 1536MB, 256GB SSD) with OS X 10.11.2. Controller is an original Sony PS4 controller, used wired.

At first I thought this was related to issue #1281 but even with PPSSPP (via Homebrew) settings set to default the game runs great. Didn't try other cores so not sure if this only happens on PSP.

Very possibly related to issue #953.

**Comment by clobber** [comment]
This should be better now as of OpenEmu 2.0.3 and PPSSPP 1.2.2+, although we still have video-side latency work to do via the remote-layer branch.
