### ISSUE TITLE
BIOS files not working

### ISSUE THREAD

**Issue by tantacles** [OpenEmu/OpenEmu#2336]
Hey there. Like many, I've been trying to get PSX games to work. I followed an online tutorial, and I manually found the correct BIOS files from emuparadise and renamed them (correctly, all lower case, as seen in the following picture: ![screen shot 2016-01-08 at 3 11 42 pm](https://cloud.githubusercontent.com/assets/16615650/12209638/5eaff870-b622-11e5-9306-876132ad449a.png)
). When I drag and drop them into the PSX game library, it tries to import them as games for other systems. 

When I try to drag and drop them into system preferences, they bounce back. 

Any reason I'm not able to import these files? How do I get this to work?

**Comment by tantacles** [comment]
Oh, and I'm running el capitan 10.11.2

**Comment by clobber** [comment]
Please search before opening a new issue.

#2330

**Comment by tantacles** [comment]
I searched extensively before opening this new issue, and I am unable to find an answer to my question. I've read the bios guide, and it does not definitively explain why I am getting this error.
