### ISSUE TITLE
Black screen after launching SNES and GameBoy Games

### ISSUE THREAD

**Issue by thefergs** [OpenEmu/OpenEmu#2338]
I just installed a clean version of OpenEmu 1.0.4 onto my new MacBook Pro running 10.10.5.  The NES roms load just fine but when I try and launch any SNES or GameBoy games the screen just goes black and the program seems to freeze or crash.  A few times a dialogue box popped up saying it couldn't communicate with the helper program.  Any ideas as to what might be my problem?

**Comment by clobber** [comment]
Well OpenEmu 1.x is unsupported now. You need to update to OS X 10.11 and OpenEmu 2.0

#2243
