### ISSUE TITLE
Backgrounds layers on/off for SNES games?

### ISSUE THREAD

**Issue by RayXambeR** [OpenEmu/OpenEmu#2340]
It exists an ability, in the old ZSNES for example: I can switch off the different background layers, in order to only have sprites visible, or only background, etc.

Do exist such a possibility in OpenEmu or, at least, will it be planned for future upgrades?

Thanks and keep up the good work with OpenEmu!

**Comment by clobber** [comment]
No, not possible and not really something we'd add.
