### ISSUE TITLE
Issues with Save States

### ISSUE THREAD

**Issue by CaptainBignose** [OpenEmu/OpenEmu#2341]
Using save states, either through Quick Save and Quick Load hotkeys or manually pressing the "Save Current Game" button on the toolbar, fails to work. It won't allow me to start a ROM where I left off. This is only an issue for Nintendo DS games, and using save starts works fine on Gameboy Advance.

Attached are screencaps of the console after trying to load from a save state and the cores I have installed.

This was never an issue before, and I don't think there have been any significant changes to my system

Thanks!
Edit: Tried states with a fresh ROM, and they can't even be created
![cores](https://cloud.githubusercontent.com/assets/16629090/12219356/261de3b8-b70e-11e5-8894-508f8bd4e175.png)
![error](https://cloud.githubusercontent.com/assets/16629090/12219358/26cbaf0c-b70e-11e5-83cc-2eb6dc6736d5.png)
![console log](https://cloud.githubusercontent.com/assets/16629090/12219359/26de4932-b70e-11e5-8e8f-eb9b7912d988.png)

**Comment by clobber** [comment]
Can't replicate.
