### ISSUE TITLE
Games crash OpenEmu version 2.0.1

### ISSUE THREAD

**Issue by Gameboi64** [OpenEmu/OpenEmu#2342]
[Untitled 2.docx](https://github.com/OpenEmu/OpenEmu/files/83946/Untitled.2.docx)
[Untitled.docx](https://github.com/OpenEmu/OpenEmu/files/83947/Untitled.docx)
(This is some information I grabbed from the console)

I got the newest version of OpenEmu 2.0.1 around the start of the new year, when it was released. i like what you have done with it, including the newer looking interface, the homebrew section and more things.

But once I upgraded, I got some strange results, that being only one.

I can't play anything now!
Whenever I launch a game, the whole app crashes. I have all of the bios, all of the cores, including deleting old cores and redownloading them, and that did nothing. I have though kept the crash information for it.
[openemu crash information.docx](https://github.com/OpenEmu/OpenEmu/files/83933/openemu.crash.information.docx)

**Comment by cyco** [comment]
Can you please upload the info to pastebin.com or gist.github.com and post the links here. No one wants to open docx files.

**Comment by Gameboi64** [comment]
http://pastebin.com/wU7u8KZX
crash information
http://pastebin.com/BSMx88J2
console information
http://pastebin.com/7r8WUftR
console information 2

**Comment by clobber** [comment]
Follow the steps here https://github.com/OpenEmu/OpenEmu/issues/2226#issuecomment-167277759 and please search before opening a new issue.
