### ISSUE TITLE
Tomee nes to usb adapter not working

### ISSUE THREAD

**Issue by amusser** [OpenEmu/OpenEmu#2344]
I got a Tomee NES to USB adapter and plugged my old NES controller into it and OpenEmu sees it as NES PC Gamepad but when I select it and try to use it nothing happens.  I have it directly plugged into my laptop and not through a hub and I do not have any 3rd party USB apps or drivers installed.  Is there something I'm missing?

**Comment by clobber** [comment]
Issues using adapters should be resolved as of OpenEmu 2.2.
