### ISSUE TITLE
Apple Remote Desktop and/or Screen Sharing issue with OpenEmu

### ISSUE THREAD

**Issue by popoption** [OpenEmu/OpenEmu#2346]
Hi all! I have a mac mini hooked up to my TV and OpenEmu works great. The issue happens when I try to connect to the machine with Screen Sharing or ARD while a game is running. The connection is dropped and the Screen Sharing or ARD app freezes on my my laptop. If I have ARD connected before I launch a game, everything is fine. The second I launch a game, it freezes ARD.

Any thoughts?

Thanks!

**Comment by mrvacbob** [comment]
Are there any crash logs?

**Comment by clobber** [comment]
Closing for lack of info.
