### ISSUE TITLE
Sega Cd Bios

### ISSUE THREAD

**Issue by zippyjake** [OpenEmu/OpenEmu#2347]
When I configured the bios for sega cd it said I was missing the the Japanese one which I di configure. What should I do?

**Comment by clobber** [comment]
Follow the BIOS guide so you can determine the exact one that is required: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

**Comment by zippyjake** [comment]
"I did drag the bios on

**Comment by zippyjake** [comment]
It still didnt work
