### ISSUE TITLE
where can I edit deadzones etc for controllers in openemu?

### ISSUE THREAD

**Issue by dorschinger** [OpenEmu/OpenEmu#2350]
The post  "Use stored analog deadzone/peaks per-controller in the database #1303" does not help since I don't find the "InputAutoCfg.ini" on my harddrive. Openemu's newest update is installed and everything works perfectly, I just can't control the aiming etc with my PS4 Controller in Goldeneye properly since the deadzones are crappy.
Is there a way to solve this? where can I find the ini to edit?
Thanks in advance!

**Comment by clobber** [comment]
If you read the rest of that issue, you'd learn that there is no way to edit deadzones/peaks per-controller, which is why that issue is open in the first place.
