### ISSUE TITLE
First game after installation

### ISSUE THREAD

**Issue by heliason** [OpenEmu/OpenEmu#2351]
I tried adding and plaing Zelda Oracle ROM after installing OpenEmu and the ROM wasn't responding. I tried ejecting the ROM and it wouldn't respond. Now I can't shut down OpenEmu and it won't let me shut down my computer.

**Comment by clobber** [comment]
Pretty confused what you mean here. Ejecting?

Provided you are using OpenEmu v2 (1.x is unsupported and I have a hunch that is what you are using), you should be able to simply drag and drop in a Game Boy/Game Boy Color ROM (.gb or .gbc) into the library, have it import and then double click the game to play.

Feel free to reply if that is not the case.

**Comment by heliason** [comment]
You know when you eject a disk its shuts down a program. I was trying to
stop or shut down the ROM because it wasn't responding. Now OpenEmu won't
do anything and it won't let me exit the program or shut down my MAC to
exit.

**Comment by clobber** [comment]
I still don't know what you're talking about, but I assume you can go to the Apple menu > Force Quit, up in the menu bar, to quit whatever apps are still running.

**Comment by heliason** [comment]
Ok I'll lay it out for you.

1. I downloaded Open Emu
2. I downloaded a Nitendo64 ROM
3. I dragged and dropped the ROM onto Open Emu
4. Open Emu opened the game
5. Game was not responding. No start up, music, nothing
6. I tried to exit the game but it wouldn't do anything
7. I tried to exit Open Emu and it didn't do anything
8. I tried to shut down my computer and an error popped up saying that Open
Emu needed to shut down first, but wouldn't. Nothing worked

How do I close the dumb program?

**Comment by heliason** [comment]
I tried force quit. It didn't work!

**Comment by robotoad** [comment]
It's difficult to diagnose the problem based on the available information, but you can force your computer to turn off by pressing and holding the power button.

**Comment by heliason** [comment]
I did that, but the OpenEMu will not allow my computer to shut down. An
error pops up saying the OpenEmu is still open and need to be closed before
the computer can shut down. So I try closing the program, which doesn't
work!!

**Comment by robotoad** [comment]
You need to hold the power button for at least five seconds. This forces the computer to turn off, so you will lose any unsaved documents.

**Comment by heliason** [comment]
I fixed the problem! Thank you

**Comment by heliason** [comment]
I have a question! How to you fix controls on the game?
