### ISSUE TITLE
No games are loading successfully

### ISSUE THREAD

**Issue by macaddict4life** [OpenEmu/OpenEmu#2354]
I just installed OpenEmu last night. I added cores for the systems I have games for (NES, SNES, Genesis, GameGear, GameBoy, Virtual Boy), and added my rather extensive game library. A handful of Genesis games could not be imported (it said they were invalid), but that wasn't a big deal, and I tossed those files.

However no games will actually load. When I double click a game for any system I just gent a blank screen, with no sound. This happens regardless of whether a controller is connected. 

Sometimes, I also cannot close this window (and return to the library) or quit the application without force quitting.

Did I miss a critical step or something? MacBook Pro, 10.11.2, and OpenEmu is up to date.

**Comment by macaddict4life** [comment]
Just a follow-up. I tried again, and watch the Console. I'm getting similar errors no matter what game or system I try on.

However I also tested this file in Nestopia, and no problem. Other files I've tried I know I've previously played using various emulators (in many cases, the one that provides the core used in OpenEmu).

1/16/16 12:49:19.193 AM OpenEmuHelperApp[9106]: Invalid file.
1/16/16 12:49:19.193 AM OpenEmuHelperApp[9106]: ROM did not load.
1/16/16 12:49:19.193 AM OpenEmuHelperApp[9106]: Deallocating proxy: <OEThreadProxy 0x7fa71a908740, target: <NESGameCore: 0x7fa719639d00>>
1/16/16 12:49:19.194 AM OpenEmuHelperApp[9106]: Setting up emulation
1/16/16 12:49:19.000 AM kernel[0]: IOSurface: buffer allocation size is zero
1/16/16 12:49:19.204 AM OpenEmuHelperApp[9106]: Error creating IOSurface texture: invalid numerical value & 0
1/16/16 12:49:19.205 AM OpenEmuHelperApp[9106]: Cannot create FBO, OpenGL error 8CD6
1/16/16 12:49:19.205 AM OpenEmuHelperApp[9106]: createNewTexture, after creating tex: OpenGL error 0500
1/16/16 12:49:19.211 AM OpenEmu[9103]: SETUP DONE.
1/16/16 12:49:19.255 AM OpenEmu[9103]: failed to make complete framebuffer object 8cd6
1/16/16 12:49:19.310 AM OpenEmu[9103]: Display's nominal refresh rate is 59.99 Hz

**Comment by clobber** [comment]
>OpenEmuHelperApp[9106]: Invalid file.
>OpenEmuHelperApp[9106]: ROM did not load.

Looks like a problem of whatever files you are trying to load in. Just try running some games from the Homebrew library. If those load fine, that means you have a problem with your other ROMs. Also make sure your Filter in use is set to Pixellate or Nearest Neighbor.
