### ISSUE TITLE
OpenEmu lag after updating to 2.0.1 and El Capitan 10.11.2

### ISSUE THREAD

**Issue by Rakun44** [OpenEmu/OpenEmu#2356]
No matter what system I try there is a constant lag at the same rate through all the systems. OpenEmu worked perfectly for SNES and a lot of the N64 games before this update, please help. BTW great program, and thank you for your time.

**Comment by clobber** [comment]
We've done nothing to introduce latency, only lessen it. You haven't provided any details about your setup, so not much we can do to troubleshoot here. I suggest setting your filter to Nearest Neighbor or Pixellate if they aren't already and closing any other running programs, especially f.lux if you use that.

**Comment by Rakun44** [comment]
Thank you very much! This worked...Changed it from SABR to one of the ones you recommended.

**Comment by empire76** [comment]
i am having a severe lag issue as well, very similar to the video posted. I have openemu (experimental build) running on a mid 2011 Mac Mini, running OS X El Capitan, 2.3 Ghz intel core i5, with 8 gb of ram and an intel hd graphics 3000 512 mb. Games work fine for a few minutes and then the lag kicks in, both video and audio, it has made all games unplayable. I have the filters set for nearest neighbor, and am lost for a fix.

**Comment by clobber** [comment]
@empire76 Please stop posting the same thing in unrelated issues. That isn't helpful
