### ISSUE TITLE
PPSSPP Core 1.1.1 not working on 1.0.4

### ISSUE THREAD

**Issue by asoksevil** [OpenEmu/OpenEmu#2358]
The latest core doesn't work on 1.0.4, but core 1.0 does (the core is automatically downloaded so you have to manually download the 1.0 one)

Also, any way to manually add or change settings like in this thread? 
http://forums.ppsspp.org/showthread.php?tid=940&page=3

**Comment by clobber** [comment]
It requires 2.0. No way to change settings.

**Comment by asoksevil** [comment]
I understand 1.1.1 requires 2.0 but it doesn't make sense for people who have 1.0.4 to download automatically the 1.1.1 core when it doesn't work. Maybe changing it to 1.0 would be better as some less tech savvy people might not know the issue is with the core.

**Comment by Solarstrike** [comment]
Upgrade to 2.0. Don't bother wasting his time.

**Comment by asoksevil** [comment]
Thanks for the suggestion Solarstrike, I will upgrade if I could but can't due to app incompatibility, hence why I am here.

I am just staying this because people who previously had 1.0.4 or are under 10.11 will find the PSP emulator not working with no reason.

**Comment by Solarstrike** [comment]
The 1.x versions are unsupported.
