### ISSUE TITLE
Super Game Boy Support

### ISSUE THREAD

**Issue by ghost** [OpenEmu/OpenEmu#236]
Hi,

I haven't actually used OpenEmu. I just stumbled across the home page and then eventually made my way here. I read the list of supported emulators and I have a suggestion. First, I'm assuming VisualBoyAdvance won't be used for GB and GBC games because the readme.md just states support for GBA games.

So, based on that assumption, can you add KiGB as a potential emulator? (http://kigb.emuunlim.com/ http://bannister.org/software/kigb.htm) I like that Gambatte is included as it enables the DMG palettes for specific games like Metroid II (which KiGB does not do, at least on Mac).

But KiGB does have support for game-specific Super Game Boy palettes (like for Donkey Kong '94, which I prefer over the GBC look), as well as border areas.

By the way, will there be something that can be set in the preferences to identify situation-based Game Boy palette scenarios? For instance, my ideal setup would be:
- If it has a SGB palette, use it. If not, use the GBC DMG palette if it has it. If not, default to black & white (like the Game Boy Pocket)
- If it has an SGB border, use it. If not, don't display one or take up space with a black border. But, also set independently of if a SGB palette is used or not (so SGB border but GBC palette combinations would be possible)

Again, sorry if any of this has been addressed before. Haven't actually used OpenEmu. Only just came across it. Saw Gambatte support and the message for VisualBoyAdvance, so jumped this conclusion about Super Game Boy Support.

Thanks,

**Comment by NaaChill** [comment]
Hey! This is a feature I'd really like to see in OpenEmu, as I'd like to play SGB-enhanced GameBoy games. Not many games use it, but for those that do it is quite a nice treat.

I've actually gotten this to work using the steps listed below.

Files needed: **sgb.rom**, **Super Game Boy (World).sfc**, and the **Higan core 0.93** (https://github.com/OpenEmu/Higan-Core/releases/tag/v0.93.1).

- Place **sgb.rom** and **Super Game Boy (World).sfc** into the BIOS directory located at _~/Library/Application Support/OpenEmu/BIOS_
- Extract the Higan core and rename to Higan-SGB.oecoreplugin and place in the Cores folder located at _~/Library/Application Support/OpenEmu/Cores_
- Open a SGB-Enhanced game such as Pokémon Red & Blue or Megaman V. Now switch your Core from the Gear menu to Higan.

Eureka! The game now plays in SGB mode. It would be cool to see some official support for this feature.
