### ISSUE TITLE
GameCube controller support

### ISSUE THREAD

**Issue by racemus** [OpenEmu/OpenEmu#2360]
Hi.

What about support for Nintendo GameCube Controller Adapter for Wii U?
This one https://store.nintendo.com/ng3/browse/productDetailColorSizePicker.jsp?productId=prod500101

**Comment by clobber** [comment]
What is your question in particular? This adapter looks like it needs a driver and nobody on the dev team has this thing.

**Comment by racemus** [comment]
My question: will it be supported? I understood. I hope it will be some day, because GameCube controller is most comfortable I ever used.

**Comment by clobber** [comment]
The GameCube controller is one of the worst controllers in general for retro gaming. As for supported, I'm still not clear on what you mean. I assume if there is a HID driver, then it should 'just work'. Otherwise, we won't be going out of our way to get it working.

**Comment by leosampaio** [comment]
> The GameCube controller is one of the worst controllers in general for retro gaming.
🤷‍♂️ Uhm, why would one of the best controllers ever made be considered one of the worst for retro gaming? Besides, what about Gamecube emulation, can you recommend a controller that better recreates my childhood experience?
