### ISSUE TITLE
Disable Players or Controllers for Multiplayer

### ISSUE THREAD

**Issue by nicholas-jon** [OpenEmu/OpenEmu#2361]
I am trying to play Starfox64 on multiplayer mode. There are only two of us playing, but I can't find an option to deselect players 3 and 4. Is this possible? I have done some searching online and under other issues but haven't found an answer yet. Sorry if this is an old issue or actually an issue with the Mupen64 and not OpenEmu.

**Comment by clobber** [comment]
Currently not possible to do this. You would have to bind keys for that controller and then deselect it in-game.
