### ISSUE TITLE
IOS / tvOS support

### ISSUE THREAD

**Issue by paulgeorges** [OpenEmu/OpenEmu#2365]
Hey folks,

I recently tried OpenEmu over the holidays and it's just absolutely fantastic. I haven't looked at the source much, but how much work do you guys reckon it would take to port the application to iOS and tvOS? I know it's really hard to estimate this stuff given that all the app flow and input will have to be redone to say the least.

Cheers,

Paul

**Comment by clobber** [comment]
Can search the issues for previous responses. In short, a ton and not likely.
