### ISSUE TITLE
Importing PCSX .mcr files into OpenEmu

### ISSUE THREAD

**Issue by toastercult** [OpenEmu/OpenEmu#2366]
Hey!  I'm new to the whole emulation thing, and I was using PCSX to play some PSX games until I discovered OpenEmu.  I was wondering if there was a way to import my saved game files (.mcr) into OpenEmu?  Not sure how to do that so any help would be appreciated.  Thanks!

**Comment by clobber** [comment]
The path to the save files is: ~/Library/Application Support/OpenEmu/Mednafen/Battery Saves

They need to be named whatever Mednafen wants the game to be named, so run the game in Mednafen first, then import your file.

**Comment by CarlosFF262** [comment]
is there a way to import .gme files?
