### ISSUE TITLE
Multiple disc issue with PS1

### ISSUE THREAD

**Issue by dsilwadi** [OpenEmu/OpenEmu#2367]
I got to the end of Disc 1 of FFVIII and when I loaded Disc 2, my saved game wasn't there. I came across the m3u fix and it successfully starts, but again, no saved game. I'm assuming it's because the battery save was on my original Disc 1 game. Is there anything I can do about this, or am I going to have to start the game from scratch on the m3u? I tried what someone else had suggested: renaming the Disc 1 saved game to the one created by the m3u in my Battery Saves folder, but it didn't work.

**Comment by dsilwadi** [comment]
I just thought of renaming the battery saves AND then deleting the previous Disc 1s altogether, and it worked!

**Comment by clobber** [comment]
https://www.reddit.com/r/OpenEmu/comments/3ynqpx/no_saves_found_when_changed_disc/cyf9lo0
