### ISSUE TITLE
Game scans, but only for a couple of moments and does not go into the Library.

### ISSUE THREAD

**Issue by snoprooo** [OpenEmu/OpenEmu#2368]
I've already successfully played one game through OpenEmu, but when uploading others, it will either scan for around 3 seconds and quit, or not scan at all. I've tried dragging from desktop, as well as "Launch Game..." as well. Not to mention, I have also tried downloading other types of ROMs of different devices and the same problem occurred. 

Thanks in advance.

**Comment by clobber** [comment]
That means it wasn't detected, sounds like it was a CD-based game. You need to specify.

**Comment by snoprooo** [comment]
It's a Nintendo DS ROM that I'm trying to use, and I've already downloaded Desmume as well. I've tried both .zip and .nds files. Does that help or did I need to elaborate on anything else in particular?

**Comment by clobber** [comment]
The zip of your DS game probably contains other files so it's not being picked up. Only single games per zips are supported. So, simply extract the zip file and import the .nds file.

**Comment by snoprooo** [comment]
Not too sure if I've made it unclear or I've made a mistake, but I previously did state that I did, in fact, try importing the .nds file. And yes, this .nds file comes directly from the .zip file. I've also tried "The Unarchiver" application which gave me the exact same .nds file I've been trying to use all along. Is this still a problem with extraction? Sorry for all this confusion!
