### ISSUE TITLE
3DO Controller GUI

### ISSUE THREAD

**Issue by davideverly** [OpenEmu/OpenEmu#2369]
OpenEmu Team,

I've attached a zip with 3DO controller graphics below. Let me know if anything needs to be tweaked before including a future build. 

D

[controller_3do.zip](https://github.com/OpenEmu/OpenEmu/files/101956/controller_3do.zip)

**Comment by clobber** [comment]
Hey there, thank you for the graphic! We need both the standard and HiDPI/Retina versions in PNG format -- Xcode does the work of combining both 1x and 2x resolution assets. Also cc'ing both @memorynoise and @RickyRomero to see if they have any feedback for you.

**Comment by RickyRomero** [comment]
It isn't a problem to extract PNG versions out of the TIFF - I can take care of that in the next hour or so. Good job on the artwork!

**Comment by RickyRomero** [comment]
Here are PNG versions with @1x sizes.  I created them by shrinking the @2x with bilinear resampling, which I've found gives the cleanest result. @davideverly, if you have bespoke @1x versions, we can definitely use those instead.

![controller_3do_mask](https://cloud.githubusercontent.com/assets/233891/12588747/00fa6f12-c40f-11e5-9b84-563e17cf81e3.png)
![controller_3do_mask 2x](https://cloud.githubusercontent.com/assets/233891/12588749/0119fcb0-c40f-11e5-97c5-234f3b5dfa17.png)
![controller_3do](https://cloud.githubusercontent.com/assets/233891/12588750/011c227e-c40f-11e5-8ed7-2a33cf3e84ae.png)
![controller_3do 2x](https://cloud.githubusercontent.com/assets/233891/12588748/0112eb78-c40f-11e5-8203-5810255ffab4.png)

**Comment by davideverly** [comment]
Just a quick design update from the original source files. I've included the 1x and 2x versions in the zip attached. Let me know if there is anything else needed.

Dave

[controller_3do_20160201.zip](https://github.com/OpenEmu/OpenEmu/files/113256/controller_3do_20160201.zip)
