### ISSUE TITLE
Raphnet GC adapter does not work

### ISSUE THREAD

**Issue by coral** [OpenEmu/OpenEmu#2370]
Hello!

Tried to use my Raphnet GC adapter with Open EMU but it does only detect the Y axis on the main joystick and no other buttons. Adapter works fine in Dolphin.

**Comment by kunaakos** [comment]
I have the same issue with a Raphnet 4nes4snes and another controller based on raphnet firmware (usb snes) - what can I post to help?

**Comment by clobber** [comment]
Issues using adapters should be resolved as of OpenEmu 2.2.

**Comment by kunaakos** [comment]
Thank you so much for fixing this! 😊
