### ISSUE TITLE
OpenEmu quit unexpectedly

### ISSUE THREAD

**Issue by jmufan97** [OpenEmu/OpenEmu#2373]
I have a MacBook Air
OS X El Capitan Version 10.11.2
OpenEmu v2.0.1 407-g415a4a6-Release

When I opened OpenEmu it told me it required an update, so I did the update and restarted the app. Then when I tried playing a game I got an error message that states OpenEmu quit unexpectedly, and then a lot of computer speak that I do not understand. I went through all the trouble shooting on the OpenEmu page and non of that work. Thank you in advance for any help you can offer

**Comment by jmufan97** [comment]
I just updated my mac to El Capitan Version 10.11.3 and it still is doing the same thing

**Comment by clobber** [comment]
You need to elaborate. Is this with all games or a certain one? Also post the crash log.

**Comment by jmufan97** [comment]
It is with everygame I have tried. I have tried gameboy color, gameboy, and DS which are the only systems i play.
Is the crash log the thing that pops up when it quits out?

**Comment by clobber** [comment]
Follow the steps here to fix your problem: https://github.com/OpenEmu/OpenEmu/issues/2226#issuecomment-167277759

**Comment by jmufan97** [comment]
Thank you so much! that was very weird solution but worked perfectly!
