### ISSUE TITLE
Snes game have noticeable latency and frame rate drop

### ISSUE THREAD

**Issue by TheGrantula21** [OpenEmu/OpenEmu#2377]
I haven't played in a while but when i got back on to play some snes games i noticed that all of the games i played had a latency issue and the game would run at a low frame rate. I have played through many games on this laptop and never had this issue. Help would be much appreciated. Thanks!

**Comment by clobber** [comment]
We've done nothing to introduce latency, only lessen it. You haven't provided any details about your setup, so not much we can do to troubleshoot here. I suggest setting your filter to Nearest Neighbor or Pixellate if they aren't already and closing any other running programs, especially f.lux if you use that.
