### ISSUE TITLE
Xbox One Controller Problems.

### ISSUE THREAD

**Issue by ButterflyCubed** [OpenEmu/OpenEmu#2379]
I use a Xbox One controller to play all my games but a few updates ago my controller stopped working for OpenEmu. It works every now and then, it comes up that the controller is connect and if a press a button it has the controller bindings though it won't change or work when emulating. I've tried deleting the Bindings folder and restarting OpenEmu but nothing helps the chance of it working.

**Comment by clobber** [comment]
Xbox One controller requires a driver, so there is probably something weird going on there which means we can't do anything about it. Other than that, could be another application you have installed or running that is interfering with input.

**Comment by ButterflyCubed** [comment]
Oh, the driver is fine. Everything else works with it except OpenEmu. And I'm sure it's compatible with OpenEmu because it used to work fine.
