### ISSUE TITLE
Open Emu Battery Save

### ISSUE THREAD

**Issue by lexy001** [OpenEmu/OpenEmu#2383]
I am playing a game from Game Boy Advanced on OpenEmu. I saved the game within the game; not on the OpenEmu screen. It looks like the automatic "save state" wiped out whatever saved game I had, even though I properly saved within the game itself.

After reading some of these notes, I found a file called "Battery Saves" which is what I think I was looking for. There, I found two files that say ".sav.old" and ".sav2". I believe one of these was my old saved game file I was looking for. How do I find the REAL one OR how do I reactivate the old saved file in my game? I'm not computer savvy to the ninth degree, so please, any step by step process you can show me, any Youtube link you can send me, anything to help me out would be incredibly helpful.

-lex

**Comment by nashullo** [comment]
Today it happened the same to me. I upload from Mountain Lion to El Capitan and I keep playing the game in Game Boy Advanced without any problems and suddenly OpenEmu closed with a message that i don't remember. But when I opened it again it came back to another save file. The automatic "save "state" of the game changed from the last one, but the other files didn't, so I lost a lot of progress on my game. If there's a solution, please let us know! Im f*****g dying!

**Comment by clobber** [comment]
Loading a save state restores the contents of everything in memory at the time the save state was created, which means the in-game battery save is also overwritten if you close the game having just loaded a save state. There is nothing you can do to recover the in-game save.

**Comment by twaddington** [comment]
> Loading a save state restores the contents of everything in memory at the time the save state was created, which means the in-game battery save is also overwritten if you close the game having just loaded a save state.

This is a terrible default experience. The default dialog "Would you like to continue your last game?" contains no warning that your battery saves will be overwritten and unrecoverable. I just lost dozens hours from a Breath of Fire IV playthrough that I'll have to repeat because the auto save state didn't take and I lost my memory card saves.
