### ISSUE TITLE
Saves + WiFi

### ISSUE THREAD

**Issue by Fedefio** [OpenEmu/OpenEmu#2386]
Hello,
1) how do I put the bailouts of OpenEmu, because some games I've finished on the NDS and PSP, but I can at inseririli.

2) How do I connect to WiFi OpenEmu like to play Pokemon in WiFi connection?

Thank you

P.S = if the message is poorly written because I used google translator

**Comment by clobber** [comment]
1) Sorry I wasn't able to understand that. Sounds like maybe you want to copy save files or something?

2) Wi-Fi is not supported in Desmume.
