### ISSUE TITLE
About Box background not rendering @2x

### ISSUE THREAD

**Issue by RickyRomero** [OpenEmu/OpenEmu#2387]
![screen shot 2016-01-29 at 11 59 49 pm](https://cloud.githubusercontent.com/assets/233891/12694478/838be230-c6e4-11e5-8ad5-404ed585e5f9.png)

The About Box isn't rendering at 2x, despite there being an asset for it:
https://github.com/OpenEmu/OpenEmu/blob/ce823221c412217f51cbf77a04644576afcfe837/OpenEmu/Graphics.xcassets/about_background.imageset/about_background%402x.jpg

**Comment by robotoad** [comment]
Fixed in <a href=https://github.com/OpenEmu/OpenEmu/commit/c7f6d2ea21997505533aebbded5a9b4e5275dc1d>c7f6d2e</a>.

**Comment by RickyRomero** [comment]
:+1: Thanks!
