### ISSUE TITLE
Change/Switch Memory Cards (PSX)

### ISSUE THREAD

**Issue by Bag-Head** [OpenEmu/OpenEmu#2388]
I have .mcr files I used in other PSX emulators and I would like to use them with OpenEmu, but I cannot find a way to change what .mcr file a game loads, it will create it's own. Is there a way to configure memory cards for the emulator or a way to move saves over to the new .mcr each game creates?

**Comment by clobber** [comment]
Please search before opening a new issue. Try this thread here https://www.reddit.com/r/OpenEmu/comments/3ynqpx/no_saves_found_when_changed_disc/cyf9lo0

**Comment by Bag-Head** [comment]
Though that is a "Solution" it's incredibly tedious and doesn't actually fix my issue. This requires me to boot up a game, get the .mcr file names for it, create a copy of my original .mcr file and rename it, and I'd have to do this separately for every single game.

I asked for a way to change what .mcr file a game loads, what if I want multiple games to point to the same memory card? Also this does not answer how to get to a memory card editor (say boot PSX in BIOS mode). Is there a solution for this specifically?

*(Also I did search, Github nor Google showed me anything useful under the search term "memory card", likely because the thread you linked doesn't exactly apply to my problem)

**Comment by clobber** [comment]
>I asked for a way to change what .mcr file a game loads, what if I want multiple games to point to the same memory card? 

Mednafen, the emulator in use, generates a unique mem card save per game. So no, there is no "solution"

**Comment by Bag-Head** [comment]
Fair enough, thanks for the help regardless :)

**Comment by Elihime** [comment]
Not to necro an old post but I'm new here, and found your post, Bag-Head. I think I have a solution although, while I'm not completely tech savvy, it worked for me. I'm currently emulating Spur the Dragon on PS1. I started with ePSXe, however there were nigh unplayable amounts of random slowdown that I couldn't. Undeterred, I switched to pSX emulator (from emuparadise), and copied the save file from ePSXe's save folder to pSX's, renamed it a .bin, and set the path to that mem card vs the one I created originally. I then loaded up my game and voila~ I could play my game, with no slowdown, and nothing lost. I can also save over that file, and load easily.

**Comment by Bag-Head** [comment]
No sorry, I was specifically asking how to set custom paths for saves, so I could swap out memory cards or have saves from other games on the same card.
I don't remember why I needed this but as clobber said, the emulator doesn't have the feature I was asking for, thanks anyway
