### ISSUE TITLE
Can't open safari download!

### ISSUE THREAD

**Issue by marthao19** [OpenEmu/OpenEmu#2389]
![screen shot 2016-01-31 at 4 52 21 am](https://cloud.githubusercontent.com/assets/16985410/12701958/874dd0a2-c7d6-11e5-85f9-68bfe8d64ad4.png)
Trying to download OpenEmu on my Mac and I keep getting an error. I downloaded the installer ZIP file and when I attempt to open it I get n error stating: "Safari can’t open the file “OpenEmu-2” because no available application can open it."

My OS X system is up to date and I can't seem to find anyone else anywhere online that's having this issue.

**Comment by clobber** [comment]
This is a problem on your end...

**Comment by MonicaJeanne** [comment]
I'm currently having this issue, any chance you figured out the cause?
