### ISSUE TITLE
SNES not working on mac

### ISSUE THREAD

**Issue by Okoyos** [OpenEmu/OpenEmu#2390]
When trying to play snes games (I've tried Chrono Trigger & Link's Awakening (from emuparadise)), the screen fades out to black and stays there...forever. No sound; just a black screen with controls. When trying to exit, it doesn't let me (only works by cmd-q). When trying a filter, it crashes. When saving, it crashes. When rebooting, it reboots with same problems. Completely freezes when going full-screen (not even allowing me to cmd-q or move the window), forcing me to force quit by activity monitor.

Model: 2015 Macbook Pro 13" (i5, iris pro 6100)
OS X version: 10.10.3
OpenEmu Version: 1.0.4
Core: SNES9x

**Comment by clobber** [comment]
Please search before opening a new issue. OpenEmu 1.x is unsupported now so you would need to update to OS X 10.11 and OpenEmu 2.0

#2243
