### ISSUE TITLE
open emu wont play any game / black screen

### ISSUE THREAD

**Issue by Darwinthecat** [OpenEmu/OpenEmu#2391]
i just downloaded open emu, installed it and downloaded some roms to play.  it wont open any roms.  when i add the game to the library it changes the name of the game from the name of the zip file to the name of the game.  when i go to open the game a black screen pops up but no game play.  when i go to close the screen i cant and have to force quit.  any help would be appreciated

**Comment by ctrain77** [comment]
Are you getting a message similar to this in your console?

1/30/16 8:33:52.358 PM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.user.domain.501.100007.Aqua) Caller specified a plist with bad ownership/permissions: path = /Users/jeff/Library/Application Support/org.openemu.OEXPCCAgent.Agents/org.openemu.OEXPCCAgent.0080BC7C-235C-42B9-AF45-5B58ACFC0DA1.plist, caller = launchctl.439

**Comment by clobber** [comment]
@Darwinthecat OpenEmu version 1.x is unsupported. You will need OS X 10.11 and OpenEmu v2.

**Comment by Darwinthecat** [comment]
thanks for the help.  i figured it out.  it was the ROMS i was downloading.  i got the ones i own on console with a different program and they work fine.  CoolROM didnt work at all
