### ISSUE TITLE
Rewind dosen't work on some consoles

### ISSUE THREAD

**Issue by TCAtrevor** [OpenEmu/OpenEmu#2393]
## Rewind doesn't work on some consoles
I'm playing a GBA game and the rewind feature doesn't work. I have the right keys set up and it doesn't work. But when I'm playing an NES game it works just fine. **PLEASE FIX**
It works with:
**NES**
**SNES** (_but buggy_)
**GB**
**Famicom Disk System**
**Sega Genesis**
**Sega 32X**
and probably a few others
_DOESN'T_ work with:
**N64**
**GBA**
**NDS**
Definately more.
Like I said before: **PLEASE FIX**

**Comment by clobber** [comment]
Not all systems can support rewind. GBA is fixed for next version.

N64, nope. NDS, we'll see.
