### ISSUE TITLE
No Gameboy Support with Higan since 2.x upgrade

### ISSUE THREAD

**Issue by wilk-polarny** [OpenEmu/OpenEmu#2396]
Hello,

I used to play Gameboy games using the Higan Core (because the other one did not have that authentic green tint and crashed). Today I have upgraded to version 2.0.1 and I'm not able to play Gameboy games using the Higan Core anymore. The screen just stays black and nothing happens. I can't even close the window because it won't disappear after the confirmation dialog (I have to SIGKILL the process).

Anyways, only Gambatte seems to work - but the big problem is: I can't use the save-games I made using Higan. Is there any way to make Higan support the Gameboy again?

Or: Can I downgrade to an old version of Higan somehow?

Things I already tried:

- Deleting all cores in the user library and re-downloading them

**Comment by clobber** [comment]
Game Boy support is through Gambatte, not Higan. The Higan plugin should have never shipped with Game Boy support in the first place.

You can copy your battery save files located in ~/Library/Application Support/OpenEmu

**Comment by wilk-polarny** [comment]
...but it did ship with game-boy support. I can't use the save-states nor any saves as OpenEmu will tell me they have been created using another core.

Is there a way to work around this, or are all of my states gone now? (which would really suck).
