### ISSUE TITLE
Save File handling is absolutely broken

### ISSUE THREAD

**Issue by Spinalfields** [OpenEmu/OpenEmu#2397]
Twice now I have been trying to back up my save file just in case something happens, which I have experienced several times now in Pokemon games. (Clicking load instead of save f.ex, which is dumb but easy to do) The "Auto save" works fine, if you leave it alone. But, I tried to back it up by going to Finder, duplicate and archive somewhere else. It seemed like a no brainer,  but once I tried the game now I got an error message saying "The operation could not be completed. _No other information is available about the problem."_ and reset my save. I thought, OK, at least I have my backup, but the same thing happened. I even created an own save state just minutes before this, and guess what, same message. So, that is 2 broken Pokemon save files, each costing me over 20+hours in gameplay. The emulator is splendid at everything else, just a bummer with this.

**Comment by mrvacbob** [comment]
Could you check Console.app for anything printed when this happens?

**Comment by clobber** [comment]
We don't know which version of OpenEmu, what game or emulator core. Closing for lack of info.
