### ISSUE TITLE
MAME - Namco games not working

### ISSUE THREAD

**Issue by ffxsam** [OpenEmu/OpenEmu#2398]
Hi there,

For some reason, Namco games are not working. I can drag the namco zips into OpenEmu and it wants me to resolve them by choosing where to put them. The options are Atari 2600, Atari 5200, Intellivision, and Odyssey2. MAME is not on the list. All ROMs are 0.149.

**Comment by PlutoX86** [comment]
Is "Arcade" on the list?

**Comment by ffxsam** [comment]
Nope, just the ones I mentioned.

**Comment by PlutoX86** [comment]
You're sure you're using Open Emu 'Experimental'? Just testet the manual import with Tekken 3 (Namco Arcade). Works just fine.. 

![bildschirmfoto 2016-02-03 um 22 12 27](https://cloud.githubusercontent.com/assets/10595183/12797501/94976a84-cac4-11e5-9146-23016b79b971.png)
![bildschirmfoto 2016-02-03 um 22 21 36](https://cloud.githubusercontent.com/assets/10595183/12797504/9b6b2382-cac4-11e5-9bc5-6dbb4b68a7de.png)

**Comment by ffxsam** [comment]
No, I mean I can't run any Namco MAME games because they require the namco ROMs. But when I import the namco ROMs, OpenEmu doesn't know what to do with them.

![all_messages](https://cloud.githubusercontent.com/assets/12532733/12797749/5baafe24-ca7a-11e5-9c36-523033ec2f02.png)

![screen_shot_2016-02-03_at_1_29_29_pm](https://cloud.githubusercontent.com/assets/12532733/12797751/5e6a7702-ca7a-11e5-89ae-d5b628114524.png)

**Comment by PlutoX86** [comment]
Looks like collections to me.. You should probably unzip them first.

**Comment by ffxsam** [comment]
You're not supposed to unzip ROMs or related engine files. But I tried unzipping them and dragging the bin files in, that doesn't work either.

**Comment by clobber** [comment]
Zips that won't automatically import into Arcade should be manually copies to the /Users/[YOUR NAME]/Library/Application Support/OpenEmu/Game Library/roms/Arcade folder.
