### ISSUE TITLE
I don't have the select cheats option...

### ISSUE THREAD

**Issue by alexistam** [OpenEmu/OpenEmu#2399]
So I just got the openemu emulator (I'm not sure which version I have) and for some reason on my HUD bar, when I click on the gear options it doesn't give me the option to select cheats. I play Pokemon Platinum and I want to level up my pokemon but I can't because I can't input any cheats. It worked for my brother but some reason didn't work for me. Could you help me out with this? Thanks.

**Comment by clobber** [comment]
You need OpenEmu v2 running on OS X 10.11
