### ISSUE TITLE
Save files from a disc 1 file to multidisc

### ISSUE THREAD

**Issue by QEnergee** [OpenEmu/OpenEmu#2403]
Hey guys

Is it possible to transfer the save file from a disc 1 to the multidisc game?, i ended up reading how to put them all in 1 after i started the game

**Comment by clobber** [comment]
Please search before opening a new issue. Try this thread here https://www.reddit.com/r/OpenEmu/comments/3ynqpx/no_saves_found_when_changed_disc/cyf9lo0
