### ISSUE TITLE
Replace "LCD3x.cg" filter with "lcd-grid.cg"

### ISSUE THREAD

**Issue by KelseyHigham** [OpenEmu/OpenEmu#2404]
`LCD3x` looks weird at any size other than non-Retina 3x:

<img width="169" alt="screen shot 2016-02-05 at 12 19 46 pm 2" src="https://cloud.githubusercontent.com/assets/286211/13231882/2130727e-d961-11e5-9d9a-43779e0a0f01.png">

Because it blurs the rainbow LCD overlay, but doesn't blur the pixels themselves.

**[`lcd-grid.cg`](https://github.com/libretro/common-shaders/blob/master/handheld/lcd_cgwg/lcd-grid.cg)** looks fine at any size, including on Retina displays, and including in fullscreen:

<img width="169" alt="screen shot 2016-02-05 at 12 19 46 pm 3" src="https://cloud.githubusercontent.com/assets/286211/13231894/351b1050-d961-11e5-97f9-a3d11feaa97e.png">

It's still blurry, but it's _consistently_ blurry, and it actually looks like an LCD screen, even at fullscreen, which is nice. So I propose **[`lcd-grid.cg`](https://github.com/libretro/common-shaders/blob/master/handheld/lcd_cgwg/lcd-grid.cg)** be adopted in the meantime.

<img width="1440" alt="screen shot 2016-02-05 at 12 19 55 pm" src="https://cloud.githubusercontent.com/assets/286211/12858218/95c5e38c-cc03-11e5-85d9-289949e009d8.png">
_`LCD3x`_

<img width="1440" alt="screen shot 2016-02-05 at 12 19 46 pm" src="https://cloud.githubusercontent.com/assets/286211/12864442/2a99dd5c-cc3f-11e5-959e-62a2bea67854.png">
_**[`lcd-grid.cg`](https://github.com/libretro/common-shaders/blob/master/handheld/lcd_cgwg/lcd-grid.cg)**_

**Comment by mrvacbob** [comment]
I think we should apply filters in multiple passes, so that "3x" filters would always get rendered exactly 3x bigger, then scaled up/down to the screen size. The math in the filters probably never works out otherwise - especially since we can't keep supporting complex Cg files, which Nvidia has deprecated.

But that's no reason not to improve filters in the meantime.

**Comment by KelseyHigham** [comment]
Yeah, this is just a stopgap. `lcd-grid.cg` already exists in RetroArch and works in OpenEmu, so it's a simple file swap.

**Comment by mrvacbob** [comment]
This is fixed in our new Metal renderer.

**Comment by StrikerXL** [comment]
How do I added this lcd3x shader to OpenEmu?
Thanks!
