### ISSUE TITLE
Suggestion: Realistic LCD pixel grid

### ISSUE THREAD

**Issue by KelseyHigham** [OpenEmu/OpenEmu#2405]
Because a single Game Boy pixel can be like 12 Retina pixels tall now, we have enough resolution to show what LCD screens actually look like.

For example, we can use a shader that renders three subpixels and a black border, to accurately reflect the gap between pixels:

![emulator pixel grid](https://cloud.githubusercontent.com/assets/286211/12864503/9154d4a0-cc41-11e5-8c15-3d4907fe44c6.png)

The first one there looks like this:

<img src="https://cloud.githubusercontent.com/assets/286211/12864716/ce1809f4-cc49-11e5-94e8-eb4c499c127a.png" width="480" height="320">
(sized for Retina; click for non-Retina)

Or we can run game pixels through a bitmap mask created from a [known pixel grid](http://ignorethecode.net/blog/2012/03/16/ipad_screen_microscope/):

![nintendo_3ds](https://cloud.githubusercontent.com/assets/286211/12864510/bfefc8e2-cc41-11e5-868b-57b4a0d99937.jpg)

Apply some halation, and you can get a physically realistic appearance for every individual system's LCD screen.

**Comment by clobber** [comment]
We don't write the shaders. Cg won't be supported much longer as we go back to GLSL, but feel free to write one.
