### ISSUE TITLE
Severe Lag After File/ROM Migration From Backups [VIDEO ATTACHED]

### ISSUE THREAD

**Issue by larsonjamesr** [OpenEmu/OpenEmu#2406]
Hi all,

Just wanted to start by saying how great it is seeing this project and community grow over time. OpenEmu has been a great way to take a break from personal projects.

Unfortunately I have been unable to use OpenEmu since downgrading back to OS X Yosemite and then creating a separate boot containing Mavericks due to the lack of developer support for mainstream apps on El Capitan. 

I reinstalled Yosemite and downloaded the previous version (1.0.4) and started reimporting the ROM files I had in my old library. Prior to the downgrade to Yosemite and subsequently Mavericks I noticed a troubling amount of lag after reimporting the ROMs and using some trial and error to troubleshoot these issues. 

After importing the ROM files to both the Yosemite and Mavericks partitions (not run from the backup hard drive) I still had a considerable amount of lag that was not present before the downgrade.  

I decided to use Space Harrier as an example to show the glaring amount of lag not present prior to all the data migration. The YouTube link is below:

https://www.youtube.com/watch?v=UrFSE0W80fg

I have tried deleting/reinstalling OpenEmu with no luck, trying both the 1.0.4 stable and experimental releases but this issue has still persisted. I currently have a Core2Duo 3.06 ghz iMac with 4 GB RAM and 256 mb VRAM so the hardware should not be the problem especially since I could multitask with several apps in the background and still have OpenEmu run smoothly. 

Does anybody have any idea where this issue is coming from?

[UPDATE]

Started messing with the filter settings and it seems the video filter setting was the issue. I had to set it to Pixellate though NTSC set as its default is apparently more resource intensive. I am not sure if ongoing support will continue for earlier systems for this issue since it is inherently the video filter settings.

**Comment by empire76** [comment]
i am having a severe lag issue as well, very similar to the video posted.  I have openemu (experimental build) running on a mid 2011 Mac Mini, 2.3 Ghz intel core i5, with 8 gb of ram and an intel hd graphics 3000 512 mb.  Games work fine for a few minutes and then the lag kicks in, both video and audio, it has made all games unplayable. I have the filters set for nearest neighbor, and am lost for a fix.

**Comment by clobber** [comment]
>Started messing with the filter settings and it seems the video filter setting was the issue.

Yes, some shaders/filters are very GPU intensive. NTSC, especially.
