### ISSUE TITLE
game not acknowledging keyboard commands splashtop/teamviewer

### ISSUE THREAD

**Issue by bellinger61** [OpenEmu/OpenEmu#2407]
I'm experiencing a strange issue where when trying to stream games from openemu that I am able to update the keyboard bindings appropriately use the bound keys for movement in the openemu gui to select a game but once the game launches the game itself doesnt recognize the input. I have tried it with all installed cores and also remapped once the game was in progress with the same result. I have also confirmed that other applications receive the input as well. Since there is no error per say I didn't know what sort of log file to include.

**Comment by bellinger61** [comment]
Ive also tried all other keyboard input troubleshooting measures listed in other issue tickets.

**Comment by kylepohsib** [comment]
I am having the same issue as you when I remote in to my home PC via TeamViewer. I am running open emu 2.0.1 on my iMac 10.11.4 with TeamViewer 11.0.55321. Please can someone resolve this as I like to play games on my lunch break at work and am not allowed to install games on the work computer.

**Comment by clobber** [comment]
Remote Desktop apps are not compatible.
