### ISSUE TITLE
OpenEmu Cheat system

### ISSUE THREAD

**Issue by banderz** [OpenEmu/OpenEmu#2409]
I dont mind doing plus signs but can they actaully work. Or go back to tried and true methods of the classic format of gameshark, codebreaker ext. layouts

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes

**Comment by clobber** [comment]
+ signs are only used to join multi-line/multi-cheat codes. Read the guide.
