### ISSUE TITLE
Sparkle updater vulnerable?

### ISSUE THREAD

**Issue by Hypedoc** [OpenEmu/OpenEmu#2412]
According to this the framework is dangerous if not up to date: http://www.macrumors.com/2016/02/09/sparkle-hijacking-vulnerability/

> Apps that use a vulnerable version of Sparkle and an unencrypted HTTP channel for server updates are at risk of being hijacked to transmit malicious code to end users. The Sparkle framework is used by apps outside of the Mac App Store to facilitate automatic software updates.

**Comment by clobber** [comment]
Please search before opening a new issue. #2401
