### ISSUE TITLE
Overheat Issues While playing

### ISSUE THREAD

**Issue by jrojas14** [OpenEmu/OpenEmu#2413]
Hello,  I have a Macbook pro 13, OS 10.11.3 and the OpenEmu emulator is working fine, however is the only app I have that makes my macbook overheat, i´ve tried closing every other app but my computer overheats  anyway, can someone help me with this, or have experienced the same issue

thanks in advance

**Comment by clobber** [comment]
I am not sure what you mean by "overheat" (the fan turns on?) but some of the emulator core plugins, depending on the system emulated, have high CPU usage; this is normal. There is nothing to be done about this and is not "overheating".

**Comment by jrojas14** [comment]
I just touch the computed and it is extremely hot

**Comment by clobber** [comment]
Higher usage on the CPU and GPU equals more heat - that's just the nature of electronics. While your MacBook is a compact computer, it does it's best to dissipate heat with an aluminum body, heat sinks, fans and vents for airflow, but can still get warm enough to be mildly uncomfortable. The machine has sensors and safeguards in place so it cannot get to the point of actually burning you though, so I don't know what you might qualify as "extremely hot". If you are curious about thermal management in general you can read more here: https://support.apple.com/en-us/HT202179

**Comment by jrojas14** [comment]
That answer my question, thank you very much

**Comment by BorisPizza** [comment]
Glad to see it's not just me. **Has there ever been a fix for this?** 

I wonder why SNES emulation heats up MacBook Pros far more than video rendering.. 
As awesome as OpenEmu is, it is a little annoying to play games when the fans blast at full power after 10 - 20 minutes.

**Comment by clobber** [comment]
Read through this and the referenced issues. There is no “fix” because nothing is wrong.
