### ISSUE TITLE
DeSmuME Multiple windows/ file > New Display Window

### ISSUE THREAD

**Issue by Bag-Head** [OpenEmu/OpenEmu#2414]
In DeSmuME you can open multiple windows using this method

http://embed.gyazo.com/28543a83b296cf1a72c7d553e87b79e4.png

This there a way to do this within OpenEmu? Or Support for this feature would be nice in the future

**Comment by clobber** [comment]
No, not possible.

**Comment by Bag-Head** [comment]
Is there a way to request new features? I don't wanna come of as demanding but it would be nice to suggest stuff like this in a more official way.
