### ISSUE TITLE
Sparkle Framework Update

### ISSUE THREAD

**Issue by velvetman** [OpenEmu/OpenEmu#2415]
After reading about a vulnerability in the Sparkle framework that allows man-in-the-middle attacks during updates, I ran the following command in Terminal to find which apps I have that use Sparkle:

find /Applications -path '*Autoupdate.app/Contents/Info.plist' -exec echo {} \; -exec grep -A1 CFBundleShortVersionString '{}' \; | grep -v CFBundleShortVersionString

It returned the following for OpenEmu:

/Applications/OpenEmu.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/Info.plist
	<string>1.7.1</string>

So it looks like OpenEmu is using Sparkle 1.7.1, but Sparkle's release notes on Git (https://github.com/sparkle-project/Sparkle/releases) state that only versions 1.13.1 and newer are protected against this vulnerability. Will you be updating OpenEmu to use the newest version of Sparkle?

**Comment by Eitot** [comment]
See #2401. The feed URL has been HTTPS, so the vulnerability should not affect OpenEmu. I am interested to know whether Sparkle will be updated though, given that 1.7.1 is already fairly old (July 2014).

**Comment by clobber** [comment]
Please search before opening a new issue. #2401
