### ISSUE TITLE
Please support Xiaomi Bluetooth Gamepad

### ISSUE THREAD

**Issue by middling** [OpenEmu/OpenEmu#2416]
It would be great if support for the [Xiaomi Bluetooth Gamepad](http://www.mi.com/shb/) ([review](http://www.pcadvisor.co.uk/review/mobile-phone-accessories/xiaomi-wireless-bluetooth-gamepad-review-3618460/) (in English)) was added out-of-the-box.  It's a relatively low-cost gamepad with good build quality.

It pairs fine with El Capitan and the controls can be manually mapped in OpenEmu.

I'm attaching 2 plist files exported from HIDBrowser as the Xiaomi Gamepad presents as a game pad and a mouse.

[Xiaomi-gamepad.txt](https://github.com/OpenEmu/OpenEmu/files/128488/Xiaomi-gamepad.txt)
[Xiaomi-mouse.txt](https://github.com/OpenEmu/OpenEmu/files/128489/Xiaomi-mouse.txt)

**Comment by clobber** [comment]
We generally only add more 'well known' or popular devices to the automap database to cut down on the possibly of vendor/product ID conflicts. Plus it's a lot of tedious work.

You are free to add it on your own locally though.

**Comment by inekipelov** [comment]
@clobber but Xiaomi Bluetooth Gamepad - popular gamepad in Asia, Eastern Europe. It popular gamepad like Wi Classic Controller.
