### ISSUE TITLE
An error occurred during persistent store migration.  PLEASE!

### ISSUE THREAD

**Issue by pacoobieta** [OpenEmu/OpenEmu#2417]
ok.. so i download the file .. unzip it , drag it to my app folder and when i open it it says

An error occurred during persistent store migration.

in terminal this is what it says

Last login: Fri Feb 12 21:13:27 on ttys000
Pacos-MacBook-Pro:~ Pako$ /Applications/OpenEmu.app/Contents/MacOS/OpenEmu ; exit;
2016-02-12 21:13:32.866 OpenEmu[1067:83737] OELibraryDatabase loadFromURL: 'file:///Users/Pako/Library/Application%20Support/OpenEmu/Game%20Library/'
2016-02-12 21:13:32.873 OpenEmu[1067:83737] CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///Users/Pako/Library/Application%20Support/OpenEmu/Game%20Library/Library.storedata options:{
    NSInferMappingModelAutomaticallyOption = 0;
    NSMigratePersistentStoresAutomaticallyOption = 0;
} ... returned error Error Domain=NSCocoaErrorDomain Code=134100 "The managed object model version used to open the persistent store is incompatible with the one that was used to create the persistent store." UserInfo={metadata={
    NSPersistenceFrameworkVersion = 641;
    NSStoreModelVersionHashes =     {
        AbstractCollection = <2dfadfde 9f70b27e 16f7b6de 72310bdf 0c52bafe 3bba15ea 509e7dcc eeb8d43a>;
        Collection = <8910c83c cf414724 f6a2bbcb 597f384c c2905c19 a17d09ba de6ec5db 30a757c4>;
        CollectionFolder = <c4dd68ab e96e31fe 321efa43 240bc442 9dd93d11 dd4c51f7 ba6f3f61 e5285d4d>;
        Contributor = <18b1a514 f9441a8e 52084fb8 2af99d1a a4b849f2 4bebf26e 502687c1 85719de4>;
        Credit = <ab0a5381 9c2743ee b749c5cc ec46059e f8234412 51964008 b6f2f8ad 66495539>;
        Game = <6564305f 14ca264e 3a9b8387 1b02fea5 2bf7be49 064561e5 354fe33b 34987388>;
        Genre = <1b01e77d cd8c4d47 f35932db 5eb7a782 ac398147 94520d44 249062cc a2d2a093>;
        Image = <5b6f7286 8e63cf1b a62120dd 0780c3f0 ac3191de b8138b9a 5139599b b31e8489>;
        ImageThumbnail = <c8ab373b e3229404 41ef07fd 9e58a56a 27d33010 98a2c360 2df5f827 c1bbf066>;
        ROM = <d02ba56e b22505f6 71bc28fe d0d3624d b8feeca1 7fa872b0 8caa666f ab437388>;
        SaveState = <4c7b3c71 93eca214 2173588a 4829ffdb 7acc387d 787e488d 4d53bea6 585c3a34>;
        SmartCollection = <6b5924ca e02bf6f6 d8a1204f 5aa2f5e9 9cce66c9 ebddfd14 96faf8dd 4c804ed7>;
        System = <f17fee71 2a779438 bed9e987 82e0ae6b 602f3f47 8e18f18f 51070c70 a1c20228>;
    };
    NSStoreModelVersionHashesVersion = 3;
    NSStoreModelVersionIdentifiers =     (
        "1.0"
    );
    NSStoreType = SQLite;
    NSStoreUUID = "BE545205-DC27-4946-A010-135D3D6F554F";
    "_NSAutoVacuumLevel" = 2;
    romsFolderURL = "./";
}, reason=The model used to open the store is incompatible with the one used to create the store} with userInfo dictionary {
    metadata =     {
        NSPersistenceFrameworkVersion = 641;
        NSStoreModelVersionHashes =         {
            AbstractCollection = <2dfadfde 9f70b27e 16f7b6de 72310bdf 0c52bafe 3bba15ea 509e7dcc eeb8d43a>;
            Collection = <8910c83c cf414724 f6a2bbcb 597f384c c2905c19 a17d09ba de6ec5db 30a757c4>;
            CollectionFolder = <c4dd68ab e96e31fe 321efa43 240bc442 9dd93d11 dd4c51f7 ba6f3f61 e5285d4d>;
            Contributor = <18b1a514 f9441a8e 52084fb8 2af99d1a a4b849f2 4bebf26e 502687c1 85719de4>;
            Credit = <ab0a5381 9c2743ee b749c5cc ec46059e f8234412 51964008 b6f2f8ad 66495539>;
            Game = <6564305f 14ca264e 3a9b8387 1b02fea5 2bf7be49 064561e5 354fe33b 34987388>;
            Genre = <1b01e77d cd8c4d47 f35932db 5eb7a782 ac398147 94520d44 249062cc a2d2a093>;
            Image = <5b6f7286 8e63cf1b a62120dd 0780c3f0 ac3191de b8138b9a 5139599b b31e8489>;
            ImageThumbnail = <c8ab373b e3229404 41ef07fd 9e58a56a 27d33010 98a2c360 2df5f827 c1bbf066>;
            ROM = <d02ba56e b22505f6 71bc28fe d0d3624d b8feeca1 7fa872b0 8caa666f ab437388>;
            SaveState = <4c7b3c71 93eca214 2173588a 4829ffdb 7acc387d 787e488d 4d53bea6 585c3a34>;
            SmartCollection = <6b5924ca e02bf6f6 d8a1204f 5aa2f5e9 9cce66c9 ebddfd14 96faf8dd 4c804ed7>;
            System = <f17fee71 2a779438 bed9e987 82e0ae6b 602f3f47 8e18f18f 51070c70 a1c20228>;
        };
        NSStoreModelVersionHashesVersion = 3;
        NSStoreModelVersionIdentifiers =         (
            "1.0"
        );
        NSStoreType = SQLite;
        NSStoreUUID = "BE545205-DC27-4946-A010-135D3D6F554F";
        "_NSAutoVacuumLevel" = 2;
        romsFolderURL = "./";
    };
    reason = "The model used to open the store is incompatible with the one used to create the store";
}
2016-02-12 21:13:32.874 OpenEmu[1067:83737] destroying LibraryDatabase
2016-02-12 21:13:32.874 OpenEmu[1067:83737] OE_removeStateWatcher
2016-02-12 21:13:32.967 OpenEmu[1067:83740] NSAlert is being used from a background thread, which is not safe.  This is probably going to crash sometimes. Break on void _NSAlertWarnUnsafeBackgroundThreadUsage() to debug.  This will be logged only once.  This may break in the future.

PLEASE HELP!

**Comment by clobber** [comment]
Which version of OSX? Which version of OpenEmu?

**Comment by pacoobieta** [comment]
OpenEmu_2.0.1  on 10.11.3 captain

**Comment by pacoobieta** [comment]
please help ! thanks

**Comment by pacoobieta** [comment]
can someone please helpme !

**Comment by clobber** [comment]
Too late to try to troubleshoot a migration error at this point. Recommend to just remove your game library and reimport your games.
