### ISSUE TITLE
Hide consoles that don't have any games

### ISSUE THREAD

**Issue by nicolasmccurdy** [OpenEmu/OpenEmu#2418]
I have a lot of cores enabled (so I don't have to remember which cores I need to enable when adding games to my library) that are taking up a lot of room on the sidebar of OpenEmu. I would like to have consoles hidden that I don't have any games for (this could be a default or implemented in an option).

**Comment by clobber** [comment]
Simply right click on the sidebar to hide the ones you don't want to see or are empty.

#2276

**Comment by nicolasmccurdy** [comment]
That isn't exactly what I want, but since my issue is a duplicate I'll move discussion to #2276.

**Comment by clobber** [comment]
Doesn't matter if that's not what you want. It's what's available and it works fine.

We're not adding pointless features.
