### ISSUE TITLE
Not storing controller settings properly

### ISSUE THREAD

**Issue by jagalbraith** [OpenEmu/OpenEmu#2420]
I am running version 407-g415a4a6-Release.

Since updating to this version I have been unable to store controller settings. The controller is a Snakebyte SB01426. When I exit OpenEMU and re-launch it, The controller is there, but the mappings are different. DPAD right changes to DPAD down. I have to reconfigure the controller for each emulator after launching OpenEMU every time.

**Comment by inekipelov** [comment]
I repeated this bug

**Comment by clobber** [comment]
Dupe of #2395
