### ISSUE TITLE
How to change discs for Playstation 1 games 

### ISSUE THREAD

**Issue by NicholasGallis** [OpenEmu/OpenEmu#2421]
Recently I was playing Final Fantasy 7, which is a 3 disc game for the PS1. After finishing the first disc, I was prompted to insert the second disc to continue. However, you cannot actually save the game to a memory card like the real ps1, so when you switch to disc its as if its an entirely new game because your game saves are on disc 1. If I cant get passed this, its impossible for me to continue playing the game :(

**Comment by clobber** [comment]
Read the guide. https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game

**Comment by lukeshumard** [comment]
Sorry to bring up old an old and closed (non-)issue, but I recently had this happen to me. I hadn't created the `.m3u` file when I first started playing, but had created it and got it all working after it was time to switch to Disc 2. I didn't have any of my old Save States, but you can easily get them back.

1. In the new playlist-ed game, create a Save State. We'll call this playlist-ed game NewGame.

2. Grab your last Save State from Finder, it has a `.oesavestate` extension. We'll call the game you were playing OldGame. Make a copy of the Save State of OldGame and NewGame.

3. Right click on your Save State from NewGame and click (Show Package Contents). You'll see a file called `Info.plist`. Open this file in a text editor such as Atom, Sublime, or anything that can do plain text.
<img width="423" alt="screen shot 2016-10-22 at 12 54 20" src="https://cloud.githubusercontent.com/assets/472555/19619119/b8d75534-9856-11e6-8441-aba29161e41d.png">


4. Find the value for key `ROM MD5`. This is an identifier for the ROM it belongs to. It will look like this. Copy the `string` containing the md5 hash (ie `94a02344daacc9a18c7746c4135b077b`).
    ```xml
    <key>ROM MD5</key>  
    <string>94a02344daacc9a18c7746c4135b077b</string>
    ```

5. Repeat step 3, but for OldGame. Find the md5 hash value, and replace it with the one you copied from NewGame.

6. Copy your OldGame Save State file that you've modified and paste it into your Save States folder.

7. Open up the new ROM and the Save State should be there!

**Comment by clobber** [comment]
@lukeshumard Not good advice because typically those state files are not going to work when transferred over from a multi-disc game that wasn't using the m3u. Instead, always follow the disc guide.
