### ISSUE TITLE
Don't understand how to import save file in multi-disc games

### ISSUE THREAD

**Issue by dddanial** [OpenEmu/OpenEmu#2422]
I played Final fantasy ix disc 1 and when i had to play disc 2 i had to transfer the save file. I've read a lot of threads about how to import the save files but it doesn't seem to work for me. I've located the battery saves and everything but it doesn't seem to wanna change name to fit with the multi disc game. could anyone help me out step by step with screenshots? I have a mac and i have the newest openemu update 2.0.1

**Comment by Solarstrike** [comment]
Did you make sure to unite the files using the .m3u file creation [page?](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game)

**Comment by dddanial** [comment]
yeah i did

**Comment by clobber** [comment]
Please stop opening new issues regarding this. Sorry but no one is going to give you step by step instructions when the multi-disc guide in the wiki works for everybody else.

As for changing mem card saves, this may help you so please search before opening a new issue https://www.reddit.com/r/OpenEmu/comments/3ynqpx/no_saves_found_when_changed_disc/cyf9lo0
