### ISSUE TITLE
Games Importing to Wrong Systems, Helper Application (1.0.4, OS X Yosemite)

### ISSUE THREAD

**Issue by larsonjamesr** [OpenEmu/OpenEmu#2423]
Hi all, 

I've been finding a few more issues after some heavy file migration and OS partitioning. I am currently on a 3.06 ghz Core2Duo late 2009 iMac running partitions of OS X Yosemite and OS X Mavericks.* I primarily use OpenEmu on the Yosemite partition.

I started re-importing my ROM collection to OpenEmu noticing something peculiar. About 30 ROMS in my Sega Genesis collection had import issues and got re-classified as Atari 2600 ROMS in the Library pane seen below.

![screen shot 2016-02-14 at 8 14 29 am](https://cloud.githubusercontent.com/assets/11397629/13034176/1b4f0ec4-d2f4-11e5-97a4-c2b82aa390cd.png)

When trying to use a Sega Genesis ROM within the Genesis library I've also been noticing the recurring "Helper Application" issue as well. 

![screen shot 2016-02-14 at 8 16 06 am](https://cloud.githubusercontent.com/assets/11397629/13034178/241f65ee-d2f4-11e5-8789-4e096e3df366.png)

However, after reading into the troubleshooting responses put up by Clobber there's been one huge issue— **the OpenEmu Application Support folder does not exist in the Library folder, if at all.**

![screen shot 2016-02-14 at 8 15 10 am](https://cloud.githubusercontent.com/assets/11397629/13034180/29352ca8-d2f4-11e5-8ae9-5acd6c250693.png)

This has still been occurring after deleting and re-installing OpenEmu to no avail. I'm very sure it's not the system itself since OpenEmu would work flawlessly prior to upgrading either given system. Related specs have been put below.

![screen shot 2016-02-14 at 8 32 12 am](https://cloud.githubusercontent.com/assets/11397629/13034236/b7123bfa-d2f5-11e5-8556-a7d55282881e.png)

Any help would be highly appreciated. 

*As I said in a previous open-shut case, I'm still very reluctant to upgrade to El Capitan and run OpenEmu 2.0.x since, after finding out the hard way, several of the applications I use on a daily basis have very limited developer support considering 10.11 is so new.

**Comment by clobber** [comment]
Sorry, 1.0 is unsupported. You will need v2 to solve the import issue.
