### ISSUE TITLE
Severe lag/slow down

### ISSUE THREAD

**Issue by empire76** [OpenEmu/OpenEmu#2424]
Good morning, I am having a severe lag issue that has made enjoying openemu impossible. I have the latest version of openemu (experimental build) running on a mid 2011 Mac Mini, running OS X El Capitan 10.11.1, 2.3 Ghz intel core i5, with 8 gb of ram and an intel hd graphics 3000 1024 mb. Games work fine for a few minutes and then the lag kicks in, both video and audio.

Now I'm not the most technical person in the world, but I have spent several days going thru all of the closed issues trying to perform all of the fixes posted, such as having the filters set for nearest neighbor, deleting the bindings, running first aid with the disk utility, deleting and reinstalling openemu, closing all other programs etc, but to no avail.  I have noticed in Activity Monitor that the "Openemu helper app" will get as high as 107.6 in %CPU.  This happens while using both cores for SNES, and FCEU.  I hope I have provided enough info for you to assist, thanks!!!!

**Comment by empire76** [comment]
It's been 10 days and no response... do you require more information? Is there something else I should be doing to correct the issue??? Can someone please assist me?

**Comment by mrvacbob** [comment]
Please use Activity Monitor to run "spindump" on OpenEmuHelper while this is happening, and then use gist.github.com to post that here!

**Comment by empire76** [comment]
thanks for responding mrvacbob!!!!  Openemuhelperapp CPU was at 107% when i did the spindump

https://gist.github.com/empire76/d4870a18c4c568bbe1c2

**Comment by mrvacbob** [comment]
HelperApp is not executing a core at any point, which is weird (game is paused?)

OpenEmu GUI is spending a lot of time in the GPU driver. So is WindowServer.
Another app might be doing something (like a web browser) or the computer could be overheating. Maybe check the fans?

I don't see an issue directly caused by OE.
