### ISSUE TITLE
PS1 memory card import problems

### ISSUE THREAD

**Issue by ralphred** [OpenEmu/OpenEmu#2426]
I've been trying to import a .mcr file into OpenEmu by renaming it and copying it into the correct directory. Whenever I try to load the save from inside the game, the data is missing. I've done a bit of sleuthing and it looks like OpenEmu is overwriting my .mcr file with a blank memory card whenever I open the game.

**Comment by clobber** [comment]
You need to make sure you are not also restoring an autosave state when you load the game.

Launch OpenEmu, go to OpenEmu > Preferences > Library, click "Reset warnings" and when you launch your game click "No" if prompted to "Continue where you left off"
