### ISSUE TITLE
Problem with controller

### ISSUE THREAD

**Issue by domenicoblanco** [OpenEmu/OpenEmu#2427]
Ho, I've bought an umofficial controllerfor ps3, when I try to set it up with OpenEmu, every button that I press can't be recognized by OpenEmu. I found a little trick to male it works, I set it up with RetroArch and then set up with OpenEmu

**Comment by clobber** [comment]
Sorry, won't be able to help you with ps3 clone/knockoffs. You can search our issues for possible solutions: https://github.com/OpenEmu/OpenEmu/issues?utf8=%E2%9C%93&q=chinese+knockoff
