### ISSUE TITLE
Some Sony PlayStation games not shown in library

### ISSUE THREAD

**Issue by Ryuzaki96** [OpenEmu/OpenEmu#2429]
When I try to import some Sony PlayStation game in library, they're processed but don't appear in library.
As I already said this not happen with all game. Why? How can I fix? I'm on OS X 10.11.3 and OpenEmu 2.0.1

**Comment by PlutoX86** [comment]
This might be helpful: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games

Maybe your game is [still compressed](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-an-ecm-or-ape-file)

**Comment by Ryuzaki96** [comment]
Thank so much PlutoX86, I fix the problem creating manually the .cue file.
