### ISSUE TITLE
scale to fit screen option

### ISSUE THREAD

**Issue by DEM3NTED** [OpenEmu/OpenEmu#2430]
is there a scale to fit option??? I'm not taking full advantage of fullscreen it looks horrible

**Comment by mrvacbob** [comment]
We have no interest in scale-to-fit because it's not the way the games were ever designed to be shown. Mario won't look good if you stretch him from 4:3 to 16:9.

Maybe there could be some kind of decorative border?

**Comment by clobber** [comment]
Yeah ditto.
