### ISSUE TITLE
Ocarina of Time Bug

### ISSUE THREAD

**Issue by ajmartinezm** [OpenEmu/OpenEmu#2433]
Hello, 
I'm using Open Emu N64 to play Zelda Ocarina of time and when i Get to the sense of truth, it docent work. Things that should disappear are not disappearing. Is there a way to fix this. What do I need to do

Thank you very much

AM

**Comment by clobber** [comment]
A general N64 emulation and GPU plugin bug.  Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)

**Comment by ajmartinezm** [comment]
Clobber, I have read about this issue online and apparently there is a way of changing the plugging from Rice to glide64. How do I do this through OpenEmu?

**Comment by Solarstrike** [comment]
@ajmartinezm
Mupen64Plus is the only N64 OE core present in the system, so I suggest a few options: suffer through the sometimes hilarious bugs prevalent, grab M64P standalone, or wine a Windows N64 emulator.

Those are my recommendations.
