### ISSUE TITLE
OpenEMU 1.0.4 O2EM not loading ROMs

### ISSUE THREAD

**Issue by desoto313** [OpenEmu/OpenEmu#2435]
I'm having a few problems with my PSX emulator in openemu. I imported the roms I wanted (i've tried 2 separate roms) and while i noticed that OpenEMU is powered by a mednafen core, it makes me download the O2EM core. Once I do that and add the bios o2rom bios I get a "couldn't communicate with helper application". I've tried deleting the O2EM core but I don't know how to get it to look for or settle for the mednafen core and bios. 
Honestly if this version is supposed to have the mednafen core for psx i can't figure out why it looks for the O2EM core anyway. Any ideas?

**Comment by clobber** [comment]
1.x is unsupported. Update to v2 and OS X 10.11
