### ISSUE TITLE
Can't play a game on openemu

### ISSUE THREAD

**Issue by Sleyar** [OpenEmu/OpenEmu#2436]
So I wanted to play age of empires for the nds. the file name I downloaded is:  0324-Age of Empires - The Age of Kings (U)(WRG).7z
I play on a mac and I'm up to date on the latest emu.

When I drag this file to openemu, it just does nothing! in fact any game i download isn't doing anything. perhaps it has to do with the file. I can only play pokemon black and its an .nds file
Please help

**Comment by Solarstrike** [comment]
Unzip the .7z file.
