### ISSUE TITLE
MAME / arcade games doesn't work

### ISSUE THREAD

**Issue by Bass-N-Roll** [OpenEmu/OpenEmu#2437]
Before the new release 2.0 my favorite arcade game Street Fighter 3 Third Strikes worked pretty well. Since the new version of open emu (witch is wonderfull with PSP and PS1 games support) every arcade games that I try to play doesn't work anymore. Black screen, and I the application doesn't quit.
What's the problem ?

**Comment by Solarstrike** [comment]
MAME is a bit of an oddball when it comes to emulation.

**Comment by clobber** [comment]
Please stop opening issues like this, especially since you did just a week ago.

#2419

**Comment by Solarstrike** [comment]
@clobber Speaking of which, what's with the inactivity with the project recently?

**Comment by Paul-Huntsberry** [comment]
I'm having the same issues with OSX 10.11.4. All Arcade (MAME) games go to black screen only and OpenEMU must be force-quit. I know it worked with certain ROMS previously in the past, so it might be a conflict with an OSX update?
