### ISSUE TITLE
Endless Fastforwarding

### ISSUE THREAD

**Issue by ugothaxxed** [OpenEmu/OpenEmu#2438]
I hope this hasn't been posted about already, as I attempted to look through all the previously posted topics and couldn't find one in relation to this. Anyways, the first time I started playing an N64 game (Paper Mario) I noticed the fast forward feature and used it. I didn't realize that the longer you hold it, the longer it'll fast forward for. I'm unsure how long I held it for, but no matter what N64 game I open as of now it keeps on fast forwarding making games unable to play. Is there a way to undo this? Thank you for this amazing batch of emulators by the way!

**Comment by clobber** [comment]
This affects N64 games; fixed for next release.

#2234
