### ISSUE TITLE
FPS counter and General Settings

### ISSUE THREAD

**Issue by GrompVEVO** [OpenEmu/OpenEmu#2440]
Hello. This isn't really a bug, but more so a couple things I would really like see added in future versions of the emulator. First of all, it'd be really nice to have an FPS counter. I don't know why but I'm really curious about what my FPS count is when I play a game and I feel like this would be a pretty easy fix. It'd also be really nice if I could raise or lower setting like I can with something like the Dolphin emulator. Enabling or disabling fog, raising or lowering the resolution on PS1 or N64 games and adding Anti-Aliasing (just to name a few) would all be some really nice features to see added to the emulator. I would honestly enjoy any of those things a lot more than the couple of "nifty" filters that I can put over my game to make it look special.

**Comment by clobber** [comment]
We generally keep OpenEmu as optionless as possible, and the things you have suggested aren't anything we'd invest time in. The PS1 emulator is software rendering and its resolution cannot be adjusted. Anti-aliasing is already turned on (I believe to the maximum) for N64 games. We may some day add per-core preferences for various things but don't count on it.

**Comment by Solarstrike** [comment]
At least we have SNES Mouse and Light Gun support! ;)

**Comment by clobber** [comment]
@Solarstrike Yes both of those are available. However, I don't see your point of commenting on an issue that has nothing to do with what you've said. This isn't a forum so please stop doing that.

**Comment by vegerot** [comment]
I understand the philosophy of optionless and elegant design, however I think an FPS display is a minimal thing that many people find useful, even if the setting is hidden away in the debug menu.

**Comment by clobber** [comment]
Games run at more than full speed on all the hardware we support. This isn’t a useful feature.
