### ISSUE TITLE
Some PSX files Cannot Loaded :(

### ISSUE THREAD

**Issue by megacharlie159** [OpenEmu/OpenEmu#2441]
I was trying to play Pepsi-Man (honestly the only game I have ever played for the Play Station) And after installing Bios files this happened!!
<img src="https://camo.githubusercontent.com/88bbd3abbcd36f173f39baa80c13ad2e12ac4044/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f353234353233362f313831373331302f35636266653636302d366638652d313165332d393964662d3437626430646663383531652e706e67" alt="screenshot 2013-12-28 14 00 45" data-canonical-src="https://f.cloud.github.com/assets/5245236/1817310/5cbfe660-6f8e-11e3-99df-47bd0dfc851e.png" style="max-width:100%;">

I have tried quite a lot of different things but I couldn't get it to go away. Also I am pretty sure this isn't a BIOS Error. but yeah. 

I am on 10.9.5 btw.

                  

 
Thanks for the help!

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to v2 and OS X 10.11.
