### ISSUE TITLE
Incorrect name with Arcade Core and set roms in 7zip format

### ISSUE THREAD

**Issue by vicmarto** [OpenEmu/OpenEmu#2447]
Hello.

In the Arcade core (MAME), OpenEmu displays the correct game name when the set roms are in zip format, but incorrect when they are in 7zip.

For example:
avsp.zip ---> NAME in OpenEmu: Alien vs. Predator (Euro 940520)
avsp.7z ---> NAME in OpenEmu: **avsp**

The rest of cores works as expected with rom sets in 7zip format.

Thanks.

**Comment by Solarstrike** [comment]
So, why can't you just unzip the .7z file?
OE doesn't support that format...

**Comment by clobber** [comment]
@vicmarto Thanks, known issue with how we do lookups in the db for Arcade games.

Yes 7zip is supported.

**Comment by Solarstrike** [comment]
Well, deja vu, eh @clobber?

**Comment by vicmarto** [comment]
Thanks for answer @clobber.

Excellent work in OpenEmu, just love it.

**Comment by clobber** [comment]
This is resolved in OpenEmu 2.2.
