### ISSUE TITLE
Can't download cores, stays on "Downloading and Installing Core..." with no progress

### ISSUE THREAD

**Issue by boztalay** [OpenEmu/OpenEmu#2449]
Hey,

I just got the latest official release from the website and ran OpenEmu for the first time. When I tried to play an NES game, I got a popup telling me that I needed to install the Nestopia core, so I proceeded. Now, it's just hanging in the downloading screen, not making any progress. I've tried leaving it for an hour or so and nothing happens.

<img width="455" alt="screen shot 2016-02-27 at 8 36 20 pm" src="https://cloud.githubusercontent.com/assets/1679999/13376786/c6654c36-dd91-11e5-9319-b5e7dee9801f.png">

This seems a bit different than the other "can't install cores" issues I read, where there was an error message about the connection. In this case, OpenEmu seems perfectly happy to wait here forever.

**Comment by clobber** [comment]
It's a problem on your end with your machine and internet connection, not a lot we can do.

Usually it has to do with your machine rejecting connections to GitHub and their SSL cert so you can try these methods to fix:

* http://superuser.com/questions/605900/why-wont-os-x-trust-githubs-ssl-certificate
* https://blog.digicert.com/expired-intermediate-certificate/

That's really all the help we can offer. Also please search next time as this issue has come up several times.

**Comment by boztalay** [comment]
Well, all that seems to be in order. I went into https://raw.githubusercontent.com/OpenEmu/OpenEmu-Update/master/nestopia_appcast.xml and just downloaded the core from https://github.com/OpenEmu/Nestopia-Core/releases/download/v1.42.5/Nestopia_1.42.5.zip using Safari and that seems to work fine, so I don't think it's a certs issue.

**Comment by clobber** [comment]
Nope, not anything to do with our application. Perhaps another application on your machine blocking downloads by OpenEmu.

LittleSnitch, HandsOff, firewall tools, etc all come to mind.

**Comment by boztalay** [comment]
I don't have anything like that installed, and I don't have any firewalls active (on my computer or network). I just replicated this with the SNES core. I have all of my security settings turned down to make sure that's not it either.

**Comment by notzeist** [comment]
I have exactly this same issue with the mgba core. El Cap 10.11.5.

Downloads in Safari or using cURL work fine but OpenEmu just gets stuck.

**Comment by jjm340** [comment]
I had the same exact issue with the n64 core.  Even if this is an issue with configuration on our individual machines, the application should show a friendly error message and give the user some indication of what to do, just hanging there forever is bad UX.

**Comment by shaun2121** [comment]
I'm getting the same issue and have tried the same solution that clobber posts everywhere this subject comes up. My comp is brand new so idk what could be stopping it.

**Comment by shaun2121** [comment]
You guys, idk what browser you're using but I just reinstalled with safari and now it works. Idk what the difference is.

**Comment by jjm340** [comment]
Mine fixed itself after a couple restarts, IDK either.

**Comment by eobet** [comment]
I'm having the same issue, and this is on a new Mac Mini. I don't have LittleSnitch or any firewalls, just stock OS X.

So, if your implementation is affecting a lot of users, blaming them is strange. Shouldn't you consider changing your implementation?

Also, the app did update itself without any issue (transfered it from an old machine, and hadn't tried it in a year or two).

**Comment by iology** [comment]
After clicking "cancel", I found that it started to put the downloaded files into the Cores directory, and the game runs well.

**Comment by salvarez2000** [comment]
PSP CORE NOT RUNNING GAMES! Hey guys, I'm pretty new to openemu and have just updated the app and all of the cores and I'm not able to play any games on the PSP. It gives me a window that says the game may either glitch or not play at all due to the core. Please help!
