### ISSUE TITLE
3rd Party Playstation 3 Controller in OpenEmu N64?

### ISSUE THREAD

**Issue by sami10007** [OpenEmu/OpenEmu#2450]
I have PowerA Mini Pro (Playstation 3 3rd party controller). I would like to use it in OpenEmu. I have not managed to activate it in no emulators. I am testing mainly N64 with many games. 

How can you enable 3rd party Plastation controller in OpenEmu?

**Comment by clobber** [comment]
Sorry, won't be able to help you with ps3 clone/knockoffs. If it is not HID-compliant than it may never work at all. You can search our issues for possible solutions: https://github.com/OpenEmu/OpenEmu/issues?utf8=%E2%9C%93&q=chinese+knockoff
