### ISSUE TITLE
Original Wiimote with third party Classic Pro Controller

### ISSUE THREAD

**Issue by PeppeWH** [OpenEmu/OpenEmu#2451]
Hi,
I have an original wiimote with connected a third party classic pro Controller.
The wiimote can regularly connect to OpenEmu and works well, even with the Original Nunchuck connected, but if i try to connect the Classic pro Controller i can't map the keys and it can only map the up arrow (wrongly recognizes as "Z")
How can I get this controller to work?
Thanks

**Comment by clobber** [comment]
Similar to #2371

There is no fix for this as of now.

**Comment by sjenx02** [comment]
I have the same problem btw, there should totally be a fix soon, especially considering I have a PDP Samus Fight Pad that works fine.
