### ISSUE TITLE
Possible to move game saves from single disk PSX to multi disk PSX .m3u?

### ISSUE THREAD

**Issue by corneydj** [OpenEmu/OpenEmu#2452]
So I recently finished FF9 disk 1 & found out about the whole .m3u multi-disk work around when disk 2 didn't have my save file.

Now I have a functioning multi disk .m3u file in my library, but I still can't continue my game - it says there is no save data when I hit continue. So my question is, is there any way to grab my save file from the single disk 1 and move it over to the multi disk pack? I really don't want to have to repeat all of the first disk.

I tried copy and pasting my save file in the battery save and save state folders in Library/Application Support but with no luck, but I also don't really know what I'm doing. Anyone know a work around?

**Comment by clobber** [comment]
Please search before opening a new issue. Try this thread here https://www.reddit.com/r/OpenEmu/comments/3ynqpx/no_saves_found_when_changed_disc/cyf9lo0
