### ISSUE TITLE
Pokémon Diamond .duc save on OpenEmu

### ISSUE THREAD

**Issue by melvyn2** [OpenEmu/OpenEmu#2453]
I recently got into NDS emulation, and openemu was my first choice. I have a .duc save from Pokémon Diamond, and used wine on mac to run the file in the link. I chose the DeSmuMe output format and got a .dsv file. I tried putting it in ~/Library/Application Support/OpenEmu/DeSmuME/Battery Saves/, and starting the emulation, but i was directed to the start first adventure screen. Can somene help me??

[Offline NDS Save 6.zip](https://github.com/OpenEmu/OpenEmu/files/150137/Offline.NDS.Save.6.zip)

**Comment by melvyn2** [comment]
By the way, battery saves is where pokémon stored my adventure save, and i sure of it.

**Comment by clobber** [comment]
Two things:
* The filename of your save needs to match the filename of your ROM file e.g. My Game.nds = My Game.dsv
* Launch OpenEmu, go to OpenEmu > Preferences > Library, click "Reset warnings" and when you launch your game click "No" when prompted to "Continue where you left off"

**Comment by melvyn2** [comment]
I know, I did that.

**Comment by melvyn2** [comment]
can you reopen this post please?

**Comment by melvyn2** [comment]
REOPEN!!!!!!
