### ISSUE TITLE
Bios issues 

### ISSUE THREAD

**Issue by UncertaintyLich525** [OpenEmu/OpenEmu#2455]
Hey, so I'm trying to play Rondo of Blood on PC Engine, and every time I drag the syscard3.pce bios into the library, it ends up in Turbografx-16 instead of Turbografx-CD.

**Comment by UncertaintyLich525** [comment]
I've tried downloading it from multiple sources, and there seems to be a Japanese syscard that's different than the US one. I don't know if that affects anything.

**Comment by clobber** [comment]
* If BIOS files were not importing correctly after a new core install, please remove the imported files, restart the app and import your BIOS files again.

* Follow the BIOS guide to be sure you have the correct file: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files
