### ISSUE TITLE
All games stopped launching

### ISSUE THREAD

**Issue by chameshausting** [OpenEmu/OpenEmu#2456]
I was running every game perfectly fine until last night. Tried opening a .gb and then it wouldn't launch. I tried to fix the problem but only made it worse because then everything else that was running fine suddenly stopped launching. Below is where i think the problem is after trying to replicate it, it's not loading something. Can anyone help?

2/28/16 5:59:58.023 PM OpenEmuHelperApp: Error loading /Users/ChamesHausting/Library/Application Support/OpenEmu/Cores/VisualBoyAdvance.oecoreplugin/Contents/MacOS/VisualBoyAdvance:  dlopen(/Users/ChamesHausting/Library/Application Support/OpenEmu/Cores/VisualBoyAdvance.oecoreplugin/Contents/MacOS/VisualBoyAdvance, 265): Symbol not found: _OBJC_METACLASS_$_NSObject
  Referenced from: /Users/ChamesHausting/Library/Application Support/OpenEmu/Cores/VisualBoyAdvance.oecoreplugin/Contents/MacOS/VisualBoyAdvance
  Expected in: /usr/lib/libobjc.A.dylib
 in /Users/ChamesHausting/Library/Application Support/OpenEmu/Cores/VisualBoyAdvance.oecoreplugin/Contents/MacOS/VisualBoyAdvance

**Comment by clobber** [comment]
* Be using OpenEmu v2 and OS X 10.11
* Go to the folder /Users/ChamesHausting/Library/Application Support/OpenEmu/Cores and delete "VisualBoyAdvance.oecoreplugin"
* Reopen OE and go to Preferences > Cores, click "Install" for VisualBoyAdvance
