### ISSUE TITLE
Why Doesn't My OpenEMU Nintendo 64 Core Work

### ISSUE THREAD

**Issue by DaKewlDood** [OpenEmu/OpenEmu#2457]
On my OpenEMU the Nintendo 64 Core won't play any games on it. I don't know why but anytime I try to load Legend of Zelda Ocarina of Time or Majora's Mask it pops up with the following message WARNING 
The Mupen64Plus core s compatibility issues and some games may contain glitches or not play at all.

Please do not report any problams as we are not responsible for the development of Mupen64Plus.

When I click okay it goes to the game and the screen is black and I have to force quit the whole system to get out of it. 

What do I do? Can Someone please help ME!?!?

It's worth noting that my OpenEMU is the 1.0.4 Version if that would impact the significance of the problem at all.

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to v2 and OS X 10.11.

**Comment by lukeevans2712** [comment]
clobber what is v2
