### ISSUE TITLE
Question About Compiling (sorry if this isn't in the correct place) 

### ISSUE THREAD

**Issue by hullstar242** [OpenEmu/OpenEmu#2458]
I'm trying to compile the newest version of OpenEmu so I can play Paper Mario without the bugs of 2.0.1 and 2.0 among other things.  Before I follow the directions I noticed a section that says "Cleaning Up Previous Versions" and I wasn't sure if that only meant for people who had 1.x before or if that's if you have any version that precedes the latest version of OpenEmu.  I currently have 2.0.1,  would I have to "Clean Up" my version before I compile the newest version?  Thanks for the help and excuse my ignorance.  Also excuse this possibly not being in the right place.

**Comment by mrvacbob** [comment]
You're good.

But yes, this isn't a forum. It's a bug tracker.

**Comment by hullstar242** [comment]
Wait but where do I go for help 😓

**Comment by mrvacbob** [comment]
reddit, probably.

**Comment by PlutoX86** [comment]
@hullstar242, you don't need to compile OE yourself. The EU version of Paper Mario works just fine with the 2.0.1 release. However, the US version runs too fast on 2.0.1 AND the latest compiled OE version

**Comment by hullstar242** [comment]
I'm running Paper Mario no problem with the newest compiled version and I live in the US :)

**Comment by mrvacbob** [comment]
Paper Mario US should be fixed in git.

**Comment by PlutoX86** [comment]
I'm sorry, you're totally right. ^^"
