### ISSUE TITLE
Updated to El Capitan, now no ROMs load

### ISSUE THREAD

**Issue by chameshausting** [OpenEmu/OpenEmu#2464]
I was running the app fine on Lion, then it stopped working all of a sudden. I posted an issue and it was suggested I update to El Capitan and download the latest version of OE. But now nothing will even load, after double-clicking to try to run something it shuts the whole program down in an instant.

**Comment by clobber** [comment]
You haven't posted any crash logs, but I'm guessing the following will solve your issue: https://github.com/OpenEmu/OpenEmu/issues/2226#issuecomment-167277759
