### ISSUE TITLE
Using OpenEmu with Icade controller

### ISSUE THREAD

**Issue by mameplayer** [OpenEmu/OpenEmu#2465]
I would like to  connect icade Core to a Mac computer in order to use it as a game controller for Openemu. 
Icade core is paired with the Mac and I have a controllermate script that is running correctly. The output box of controllermate shows the modified output when using the icade core stick and buttons so the script works perfectly and it has assigned the letters used for controlling games from a keyboard.
However I have not been able of using Icade with MAME games in Openemu. But I have been able to play connecting a bluetooth keyboard as well as with a normal one. So, in theory, as Icade behaves as a keyboard too it should work using the controllermate script and Openemu. You can find the script I am talking about at http://forums.toucharcade.com/showthread.php?p=3374181

Do you know what I am doing wrong when trying to use iCade as a controller for MAME games in Openemu?
Thanks in advance for your help.

**Comment by clobber** [comment]
iCade as well as ControllerMate are not compatible with the app.

#514
