### ISSUE TITLE
Cant open ROMS on VBA message "unrecognized selector sent to instance 0x7fff71e79780" 

### ISSUE THREAD

**Issue by NeoDralion** [OpenEmu/OpenEmu#2468]
I'm on OS X El Capitan... Can you help me? :(

**Comment by mrvacbob** [comment]
Try this: https://github.com/OpenEmu/OpenEmu/issues/1460#issuecomment-46348553

**Comment by NeoDralion** [comment]
I completely follow those steps to the letter, then instead of doing nothing, OpenEmu closes unexpectedly

**Comment by NeoDralion** [comment]
![captura de pantalla 2016-03-08 a las 9 26 08 p m](https://cloud.githubusercontent.com/assets/17734013/13624511/712b1b3e-e574-11e5-949e-d43a41f14e3b.png) that's my console messages

**Comment by mrvacbob** [comment]
Click on the paperclip icon and paste the whole file you get to gist.github.com, and we can check it out.

**Comment by mrvacbob** [comment]
This has been fixed in https://github.com/OpenEmu/OpenEmu/commit/be91ed8fd26c1e10dfc37c7f833feb426703086f

As a workaround, change "Distributed Objects" to "XPC" in the preferences if you see that.
