### ISSUE TITLE
"Star Wars Episode I – Battle for Naboo" makes OpenEmu uncloseable

### ISSUE THREAD

**Issue by Phosphor303** [OpenEmu/OpenEmu#2469]
Steps to reproduce the bug:
	1.	Load "Star Wars Episode I – Battle for Naboo" into OpenEmu.
	2.	Start the game.
	3.	Wait for about 10 seconds after the first text is printed on screen.
	4.	Try to stop the game / close OpenEmu.

Expected behavior: The game stops. / OpenEmu closes.
Actual behavior: The game does not stop. / OpenEmu does not close and must be forced to quit.

OS X 10.11.3
OpenEmu 2.0.1
Mupen64Plus core 2.5

**Comment by clobber** [comment]
This game is unsupported/unemulated and is thus crashing the emulator (Mupen64Plus). Nothing we can do about this short of just blocking loading of this game and others such as Rogue Squadron and Indiana Jones.
