### ISSUE TITLE
SegaCD M3U Files

### ISSUE THREAD

**Issue by bjaudon** [OpenEmu/OpenEmu#2471]
Created a m3u playlist of CUE files for a multi-disc SegaCD 32X title Night Trap. Tried to import the files in. Discs 1 & 2 show up in SegaCD correctly and launch, but the M3U shows up under PlayStation. The M3U file is also stored in the PlayStation ROM folder. 

OpenEmu 2.0.1 407-g415a4a6-Release, OSX 10.11.3

**Comment by clobber** [comment]
Multi-disc (m3u) is not yet supported for that system and emulator so I will add a note to the wiki.
