### ISSUE TITLE
ROMs Running Speedy Without Use of Fast Forward Function

### ISSUE THREAD

**Issue by GreenBarnacle** [OpenEmu/OpenEmu#2473]
I am playing Banjo-Kazooie on OpenEmu, and the game is running speedy, and I'm not using the fast forward key. I am on Mac OS X El Capitan and OpenEmu 2.0.1, is anything going through any bugs or am I doing something wrong?

**Comment by clobber** [comment]
Please search before opening a new issue.

#2234
