### ISSUE TITLE
PSP games won't add into my library. (v2.0.1)

### ISSUE THREAD

**Issue by SmugglerX9** [OpenEmu/OpenEmu#2477]
I'm fairly new with this emulator. I haven't had any trouble with any other cores so far. But when I drag my PSP ROMs where OpenEmu says "Drag & Drop Games Here" I get the notification that it's "Scanning Game" but then it just goes away and the game doesn't appear. I have also tried added the games through browsing to the ROMs instead of the drag and drop option and it still happened.

I guessed it may have just been a bad ROM I got, but I now have tried many different ones and am having the same problem. Anyone have any idea or tips to help?

**Comment by clobber** [comment]
PSP rips will be in .iso format and you need to first unzip if the file is compressed (say, .7z, .rar, .zip, etc).

**Comment by SmugglerX9** [comment]
I don't know why you CLOSED this. You did not fix it. I have multiple .iso files now. Putting the whole file of .iso's into OpenEmu doesn't work so what do I do now?

**Comment by macrohard** [comment]
I encountered the same problem, the iso file cannot be imported into the OpenEmu library. But the same iso file works completely correctly under the ppsspp emulator on the windows platform
