### ISSUE TITLE
Take screenshots at 1:1 pixel size

### ISSUE THREAD

**Issue by dpk** [OpenEmu/OpenEmu#2478]
Taking a screenshot results in a picture at the size of the window. It also includes the black letterboxing around the game if the window isn't the exact aspect ratio of the game being played. [e.g.](https://i.imgur.com/S1xVFhG.png)

It should be more like [this](https://upload.wikimedia.org/wikipedia/en/1/1e/Supermarioworld_map.PNG) imo. That is, 1 game pixel is one screenshot pixel, and there are no borders.

**Comment by clobber** [comment]
Check our wiki, there is a way to do this via the hidden preferences pane labeled 'Secrets'
