### ISSUE TITLE
Black screen/lockup

### ISSUE THREAD

**Issue by thebonnfire** [OpenEmu/OpenEmu#2481]
So I had been playing Pokemon Blue on a .gb file just perfectly fine, and I had to go and screw it up. I was annoyed with the green color, and I saw on here if you updated the core and switched to Gambatte (from Higan) it would fix the color. I did so, updating all the cores, and I received the "couldn't communicate with a helper application" error. I ended up needing to update OpenEmu altogether.

After the update, attempting to load my game now gives me just a completely black screen and locks up the game, requiring me to force quit and restart to get the library back. If I delete the game and re-drag it in, it runs fine, but any attempt to load my prior save states from before the update brings me back to the black screen. I would very much like to recover my old save states and continue from where I left off.

**Comment by thebonnfire** [comment]
Well, now, the game has decided to crash OpenEmu every time I try to open it, even the new one without an old save state. Sigh. All this because I wanted to get rid of the green color. Opened a huge can of worms.

**Comment by clobber** [comment]
Sounds like the save states you are trying to load want to be loaded in old Higan's GB/GBC core, which is not available in OpenEmu v2 (and was only available in prior versions of OpenEmu by mistake; Gambatte has always been the 'default' GB/GBC core plugin so there will be very few users affected by this).

Only thing you can do is switch back to OpenEmu v1, manually download the **old** Higan core plugin (https://github.com/OpenEmu/Higan-Core/releases), place it in the Cores folder in Application Support/OpenEmu, load your game save in Higan, do a in-game battery save, copy that save file to the Gambatte Battery save folder in Application Support/OpenEmu, making sure it matches the filename Gambatte is looking for (yourfilename.sav), switch back to OpenEmu v2, make sure all the cores are up-to-date, reset warnings by going to OpenEmu > Preferences > Library and clicking the 'Reset Warnings' button, load Pokemon Blue and make sure to click 'No' if it asks you to 'Continue your last game'.

This is all the help we can offer.

**Comment by thebonnfire** [comment]
Thank you! This at least helped me get the game back in v1. I followed everything up until the point where you say to save the file in the Gambatte Battery save folder. I don't see anything for Gambatte.
![screen shot 2016-03-25 at 12 46 17 am](https://cloud.githubusercontent.com/assets/18063442/14038144/0984f84a-f223-11e5-8d9d-3602c9c010b6.png)

**Comment by clobber** [comment]
No folder there because you haven't run a game in Gambatte that has created a save yet. You can create a folder there called Gambatte and then a sub folder called Battery Saves
