### ISSUE TITLE
Repeatable Tactics Ogre freeze (PPSSPP 1.1.1)

### ISSUE THREAD

**Issue by chaseychasem** [OpenEmu/OpenEmu#2483]
I've been noticing that the PSP game Tactics Ogre always freezes when the spell "Boon of Swiftness" is cast in battle from about chapter three onward. The same issue has been reported here:

http://www.reacttant.com/r/OpenEmu/comments/4bxbi3/tactics_ogre_on_psp_freezes_when_spell_quickened

This is the most 3D game I've played in OpenEmu-PSP emulation, so I don't know whether it's related to a more general bug, but I'd be interested to find out. Thanks!

**Comment by clobber** [comment]
Well we don't develop the emulators. If there are compatibility issues in PPSSPP that is up to the emulator developers to correct. Also,

![screen shot 2015-12-29 at 7 27 07 pm](https://cloud.githubusercontent.com/assets/1303132/12045507/46add534-ae62-11e5-9a4d-9108a89767dc.png)
