### ISSUE TITLE
Cant get roms into Openemu

### ISSUE THREAD

**Issue by Deakstre** [OpenEmu/OpenEmu#2484]
I download a zip file off of wherever but when i try double clicking it, it just wont open in openemu, I've tried dragging and dropping it and opening it straight from openemu itself but nothing works, any sggestions?

**Comment by clobber** [comment]
No idea what game or for what system, since you didn't specify, but you could right click on the zip and select Open With > Archive Utility and them drag and drop in the extracted ROM file.

**Comment by Deakstre** [comment]
Its a GBA rom and i tried that but all it does is make a new folder and inside there is a .ups file that cant be played
