### ISSUE TITLE
Having trouble on multi disk games on ps emulator

### ISSUE THREAD

**Issue by erobles396010** [OpenEmu/OpenEmu#2485]
ive been trying to put resident evil 2 multi disk on open emu but when i drag the .cue file into textmate it comes with a track 1 and track 2 file for each disk i do everything you guys said like delete everything and change the .bin to .cue and save it with m3u extension then drag onto openemu but when i try to open it it just stays on a black screen it worked on metal gear solid just fine but mgs only had one file when i dragged it onto textmate example no track 1 and 2 like the resident evil i hope you guys understand what im trying to say please let me know thanks

**Comment by clobber** [comment]
> drag the .cue file into textmate

> delete everything

> change the .bin to .cue and save it with m3u extension

Wat. Read the directions closer, it sounds like you aren't following our steps at all. That's all we can do to help.

**Comment by erobles396010** [comment]
I did that but when i drag the.cue file there is a track 1 and track 2 so when i do the .m3u and drag it on openemu and open the screen stays black

**Comment by WeirdAhmad** [comment]
Hi did you find a solution for this problem ? if you did, plz help me

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game
