### ISSUE TITLE
m3u disc swapping issue

### ISSUE THREAD

**Issue by nickness126** [OpenEmu/OpenEmu#2487]
i am having an issue setting up disc swapping. i followed all the instructions on the info page, but when i try to open the .m3u in the OpenEmu library page, it opens onto a black screen.

the hud menu shows up and is functional but the disc switch option is greyed out. also, it pretty much crashes the software every time. it gets stuck on that screen and i have to force quit.

am i doing this correctly, or am i supposed to open the individual discs or what? help would be greatly appreciated.

**Comment by PlutoX86** [comment]
Both discs are already in your game library? Let's say you have "Street Fighter Collection - CD1.bin", "Street Fighter Collection - CD1.cue", "Street Fighter Collection - CD2.bin" and "Street Fighter Collection - CD2.cue" already imported, it should be possible to start them individually. 

Just open textedit then, change the format to "plain text". In my case, it's:

```
Street Fighter Collection - CD1.cue
Street Fighter Collection - CD2.cue
```
Save it as "Street Fighter Collection.m3u" and drag the file onto OpenEmu. 

The new "Game" has now both discs included. I usually delete the single games (without moving them  trash of course) and voila, just add the cover manually. ;) Once the game is loaded, you can change discs and hit the "reset" button if neccessary.

**Comment by clobber** [comment]
>i followed all the instructions on the info page

No you didn't, not if it is opening to a black screen. Sounds like you didn't save your m3u file as plaintext or the cue files are not named correctly.

Let's not open issues for this sort of stuff please.
