### ISSUE TITLE
Can't reset/restart

### ISSUE THREAD

**Issue by KimCheeWarrior** [OpenEmu/OpenEmu#2488]
Can't reset or restart the game without quitting out of the game and even then the game will start from the autosaved position when quitting. No matter which way I do it, whether it be by menu option, button in the bar at the bottom, keyboard shortcut, or pausing and then trying to reset in combination with all previous ways I've tried, I cannot reset the game. On a side note I also cannot find the option to turn off auto save states upon quitting a game. After reading various other issues people are having, this is the one and only issue that I've had with the numerous hours I've spent with this emulator so far and I'm surprised that no one else has this problem. If it helps, I'm using Mac OS 10.11.3 El Capitan. Thanks in advance.

**Comment by clobber** [comment]
>I cannot reset the game.

Which game and system? It is important to clarify.

>On a side note I also cannot find the option to turn off auto save states upon quitting a game.

OpenEmu > Preferences > Library and click the 'Reset Warnings' button

>I'm surprised that no one else has this problem

If this was a widespread issue affecting everyone then there would obviously be mention of it, so sounds like a specific problem to a game/system.

**Comment by KimCheeWarrior** [comment]
If it were system specific, I would've mentioned it.

**Comment by clobber** [comment]
Okay. Seems you don't want to provide further details, so nothing I can do to help you here. Sorry, this isn't happening for anyone else.

**Comment by KimCheeWarrior** [comment]
Are you being serious? I gave you all the details that I could think of. Wow. Thanks for that. Great emulator but you guys really need to work on your people skills.

**Comment by clobber** [comment]
#2670
