### ISSUE TITLE
DeSmuME emulator not working for some games in openemu

### ISSUE THREAD

**Issue by idontknow970** [OpenEmu/OpenEmu#2493]
I am trying to download games like pokemon pearl and pokemon heartgold and play them on DesmuME emulator in openemu. I have used [redacted] to download the games and whenever I try to open them with openemu the games don't load into the emulator. I have downloaded pokemon platinum and it is working just fine. I can't seem to figure out what is going on. Is there a solution to my problem?

**Comment by clobber** [comment]
Search next time as this has come up several times.

In general, Desmume doesn't support Pokemon games very well. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility.

**Comment by newroser** [comment]
Thanks clobber
