### ISSUE TITLE
Feature Request: Batch Cover Art Handling.

### ISSUE THREAD

**Issue by metaColin** [OpenEmu/OpenEmu#2494]
I have a bunch of Hyperspin sets that have coverart & roms with matching names. I can't manually drag and drop images for thousands of ROMs. Can we add in a method of matching cover art based on rom name in addition to hash identity?

**Comment by clobber** [comment]
Been discussed before but not worth the effort / not enough interest in implementing, as this is kind of an 'extreme' use case.
