### ISSUE TITLE
NES, SNES and N64 games load black screen

### ISSUE THREAD

**Issue by mfrizzell** [OpenEmu/OpenEmu#2496]
I've run into an issue where all the ROMs I've loaded for NES, SNES and N64 are loading to a black screen. I'm running current versions of OpenEmu and El Cap. I've tried replacing the bios files, cored and completely removing OpenEmu and reinstalling. Also tried the experimental version - no change. Any ideas?

**Comment by clobber** [comment]
Switch your Filter to Nearest Neighbor or Pixellate.

**Comment by mfrizzell** [comment]
Thanks - I tried but no luck there either. Additionally, I have tried opening the ROMs in their respective emulators outside of OpenEmu, they work fine there. Odd considering they're using the same cores.

**Comment by clobber** [comment]
Load an NES game and paste the output from Console.app back here.

**Comment by mfrizzell** [comment]
4/12/16 7:37:04.672 PM launchservicesd[81]: SecTaskLoadEntitlements failed error=22
4/12/16 7:37:04.675 PM launchservicesd[81]: SecTaskLoadEntitlements failed error=22
4/12/16 7:37:04.677 PM launchservicesd[81]: SecTaskLoadEntitlements failed error=22
4/12/16 7:37:04.681 PM appleeventsd[53]: SecTaskLoadEntitlements failed error=22
4/12/16 7:37:04.686 PM OpenEmuHelperApp[771]: parent application is: OpenEmu
4/12/16 7:37:04.689 PM OpenEmuHelperApp[771]: Apple Keyboard
4/12/16 7:37:04.770 PM OpenEmuHelperApp[771]: Fds: BIOS ROM ok
4/12/16 7:37:04.771 PM OpenEmuHelperApp[771]: Invalid file.
4/12/16 7:37:04.771 PM OpenEmuHelperApp[771]: ROM did not load.
4/12/16 7:37:04.771 PM OpenEmuHelperApp[771]: Deallocating proxy: <OEThreadProxy 0x7f8c11e2ec60, target: <NESGameCore: 0x7f8c11c553f0>>
4/12/16 7:37:04.771 PM OpenEmuHelperApp[771]: Setting up emulation
4/12/16 7:37:04.000 PM kernel[0]: IOSurface: buffer allocation size is zero
4/12/16 7:37:04.778 PM OpenEmuHelperApp[771]: Error creating IOSurface texture: invalid numerical value & 0
4/12/16 7:37:04.783 PM OpenEmuHelperApp[771]: Cannot create FBO, OpenGL error 8CD6
4/12/16 7:37:04.783 PM OpenEmuHelperApp[771]: createNewTexture, after creating tex: OpenGL error 0500
4/12/16 7:37:04.785 PM OpenEmu[763]: SETUP DONE.
4/12/16 7:37:04.837 PM OpenEmu[763]: failed to make complete framebuffer object 8cd6
4/12/16 7:37:04.854 PM OpenEmu[763]: Display's nominal refresh rate is 59.95 Hz
4/12/16 7:37:07.023 PM launchservicesd[81]: SecTaskLoadEntitlements failed error=22
4/12/16 7:37:12.000 PM kernel[0]: ignored is_io_service_close(0x1000004cd,IOHIDParamUserClient)

**Comment by mfrizzell** [comment]
so, 'Invalid file' - seems like just a lot of bad dumps.  I'm not sure why Nestopia will open them if OpenEmu won't, but replacing the ROM files seems to be correcting the problem.  Strange.  Thank you for taking a look, clobber!

**Comment by fredericopdg** [comment]
Hi @mfrizzell ! How exactly did you solve this issue? I'm having the same error on my console...What files did you replace? Same OS, same game...Thanks in advance

**Comment by mfrizzell** [comment]
I don't know what caused it, but I think I actually replaced the ROMs to correct it

**Comment by fredericopdg** [comment]
Ok thanks! I think i solved my problem too...by opening the console app, i can see what files are missing from the games and then i just have to find them and add to my game folder...it works for almost all games...still cant play others though

**Comment by clobber** [comment]
@fredericopdg You are clearly talking about Arcade which is not at all the same problem as the original poster. That system is experimental, unsupported and you should search other relevant issues for help -- not post in unrelated ones. Although, it seems like you learned you need to check Console, you can also find a guide that may or may not be helpful: http://agreeordie.com/how-to-emulate-retro-video-games/
