### ISSUE TITLE
Always Hide Controls option is grayed out

### ISSUE THREAD

**Issue by danny2004de** [OpenEmu/OpenEmu#2498]
I see the Always Hide Controls option in the Controls menu, but it's grayed out. Cmd-Shft-H doesn't work either. It's really annoying to have the controls bar always there when I'm playing. Why isn't it working?
I'm using version 1.0.4 experimental

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to v2 and OS X 10.11.
