### ISSUE TITLE
DS games not working in openemu

### ISSUE THREAD

**Issue by sonix5909** [OpenEmu/OpenEmu#2502]
when i drag a DS game into openemu it doesn't show up sometimes, only scribblenauts works and when it finished it was a zip file but other games i download are not. i have compressed the files and tried but it still doesn't work, please help

**Comment by sonix5909** [comment]
btw i've tried the archive utility thing but it didn't help

**Comment by clobber** [comment]
Decompress the file, whether it's .zip, .7z, .rar, ... etc using The Unarchiver (free on the mac app store https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) 

Import the .nds file (the actual NDS game ROM) into OpenEmu.

**Comment by sonix5909** [comment]
thx
