### ISSUE TITLE
Circle button not working on PSP Dante's Inferno

### ISSUE THREAD

**Issue by bhbr** [OpenEmu/OpenEmu#2503]
Hi, I've been playing Dante's Inferno (OE's PPSSPP 1.1.1). But the circle button does not work. It does not matter which key it gets mapped it onto. This makes the game unplayable after the first boss. The controls works on other PSP games.

OE version 2.0.1
OS X El Capitan 10.11.4

**Comment by bhbr** [comment]
I downloaded the rom from here:
http://www.emuparadise.me/PSP_ISOs/Dante's_Inferno_(Europe)/158247-download

**Comment by bhbr** [comment]
i just tried out a different rom (http://romhustler.net/rom/psp/dantes-inferno-e-nrp). Same result.

**Comment by clobber** [comment]
The 'circle' button is indeed wired up and works in other games. Either a PPSSPP core bug or the button is not mapped on your end. Also, please do not link to game downloads.

**Comment by bhbr** [comment]
Sorry about that. The issue is apparently in the game itself, and has been resolved. Still I wouldn't have posted this if I hadn't become desperate. Sorry about that.
