### ISSUE TITLE
Cant load Psp roms

### ISSUE THREAD

**Issue by GrimReaper1214** [OpenEmu/OpenEmu#2504]
When I go to drop Psp .Iso in to OpenEmu the seam to be added but i can't find them anywhere in OpenEmu

**Comment by clobber** [comment]
PSP games are imported into the PSP library. Do you have an example of a specific game that does not import?

**Comment by GrimReaper1214** [comment]
i have tried Need for Speed ProStreet, Need for Speed Most wanted, Need for Speed Undercover, And Ratchet and Clank. i used .rar files and .Iso files

**Comment by clobber** [comment]
These games import just fine provided they are good rips of the game. They must be uncompressed and you can only import the .iso file.

So, decompress the file, whether it's .zip, .7z, .rar, ... etc using The Unarchiver (free on the mac app store https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12). Then import the resulting .iso file.
