### ISSUE TITLE
DualShock 4 Analog Stick Problem

### ISSUE THREAD

**Issue by 1davi** [OpenEmu/OpenEmu#2505]
If I use the analog stick while holding a button, sometimes the movement is not registered properly, as if it got stuck to a single direction. That happens in Crash Team Racing, especially when drifting.

**Comment by caw742** [comment]
I'm also having this problem playing crash 3 for PSX with a dualshock 3 controller. The analog stick gets stuck in one direction and I have to wiggle the stick to get it unstuck

**Comment by jacielmelnik** [comment]
Same issue here while playing Harvest Moon: Back to Nature in PSX with version v2.0.2.

If you hold the circle button (to run) while doing a fast half-circle with the left analog it's easy to reproduce this bug.

**Comment by jacielmelnik** [comment]
I'm pretty sure this is a "release button event" bug, because the only way to unstuck the character's movement in HM:BTN is by moving the analog stick to the same direction it is stuck.

**Comment by dyeinafyre** [comment]
How is #2601 the same as this? This is a "release button event bug". #2601 is an annoying iussue in, i.e. goldeneye -- which makes the game unplayable, where when you move the analog stick down the cursor goes up.

**Comment by jacielmelnik** [comment]
@dyeinafyre Actually I mentioned this as a release button event because it might occur due to a missing release. But the issue is nearly the same. The character on this games also move to another directions, actually, as I mentioned, it stick to a direction until you move the analog to the same direction your character is stuck.

**Comment by clobber** [comment]
This should be okay as of https://github.com/OpenEmu/Mednafen-Core/commit/3247fcf46efb6a9c7f7f71bb1697c4ebc7bf2d65

**Comment by Jesse17072000** [comment]
i'm having this issue
