### ISSUE TITLE
Psp Roms = Black Screen

### ISSUE THREAD

**Issue by GrimReaper1214** [OpenEmu/OpenEmu#2507]
When i start a psp rom all i get is a black screen
and when i go to exit the rom it won't (have to force close app)

(Did have issue with adding Psp roms (was solved with help))

**Comment by GrimReaper1214** [comment]
Note Did wait about 30min for rom to work

**Comment by clobber** [comment]
Please be more specific. Which version of OpenEmu? What game?

PSP games run fine in OpenEmu v2. You are likely running into a compatibility issue with the PPSSPP  emulator core and whatever game.

**Comment by GrimReaper1214** [comment]
Im running OpenEmu v2.0.1 and i want to play ratchet and clank or Any of the need for speed game

**Comment by clobber** [comment]
These games work. I've just tried Ratchet & Clank: Size Matters (USA) ISO

![screen shot 2016-04-22 at 3 16 47 pm](https://cloud.githubusercontent.com/assets/1303132/14753811/490f6fe6-089d-11e6-82a5-ef24f36add2f.png)

**Comment by GrimReaper1214** [comment]
ok well i don't mean to be rude but i can't get any pop roms to open
All i get is a black screen and when i go to leave the rom i have to force close OpenEmu
don't get me wrong i love OpenEmu but if at all possible  would love to get this fixed

![open emu psp black screen](https://cloud.githubusercontent.com/assets/18587288/14754020/a4db9bfc-088d-11e6-8caf-4182895404b8.jpeg)

**Comment by clobber** [comment]
Load a PSP game and paste the output from Console.app back here.

**Comment by GrimReaper1214** [comment]
4/22/16 5:29:06.367 PM OpenEmuHelperApp[989]: Setting up emulation
4/22/16 5:29:06.379 PM OpenEmu[986]: SETUP DONE.
4/22/16 5:29:06.408 PM OpenEmuHelperApp[989]: Begin separate thread
4/22/16 5:29:06.432 PM OpenEmuHelperApp[989]: ERROR: RAR file detected (Require UnRAR)
4/22/16 5:29:06.441 PM coreaudiod[184]: SecTaskLoadEntitlements failed error=22
4/22/16 5:29:06.456 PM OpenEmu[986]: Display's nominal refresh rate is 59.99 Hz
4/22/16 5:29:08.060 PM launchservicesd[77]: SecTaskLoadEntitlements failed error=22
4/22/16 5:29:08.061 PM launchservicesd[77]: SecTaskLoadEntitlements failed error=22

**Comment by clobber** [comment]
> 4/22/16 5:29:06.432 PM OpenEmuHelperApp[989]: ERROR: RAR file detected (Require UnRAR)

Sounds to me that you are still having trouble decompressing those files or using bad dumps of the games. Go back to this issue and read closer: https://github.com/OpenEmu/OpenEmu/issues/2504#issuecomment-213223809

**Comment by GrimReaper1214** [comment]
ok well i don't know if I'm decompressing them right cause when i do decompress them i get a folder full of other .rar files, one .nfo file and one .sfv file 
![psp game decompresed](https://cloud.githubusercontent.com/assets/18587288/14758752/3d0a0612-08bf-11e6-8e4f-d39a4700a23c.jpeg)

**Comment by clobber** [comment]
Yes, you decompressed them right. These are just split rar's (rar's inside of a rar file) if that makes sense and is common for PSP dumps.

When this happens there is usually a main .rar, .part1.rar or .001 that you need to decompress which will begin decompressing all of the other files with it and end up with a big .iso file.

If decompressing that main file doesn't work (sometimes it will not) then you can try this:

1) Open up Terminal.app and install Homebrew: http://brew.sh/
2) Type `brew install unrar` and press enter to install the unrar package.
3) Type `cd ` (cd including a space at the end) and drag and drop the folder where your .rar files are into the Terminal window and press enter.
4) Type `unrar x ` (unrar x including a space at the end of the x) and drag and drop the first part of your split rar file, .part1.rar, .001 whatever it is, into the Terminal window and press enter.

Alternatively, you may follow these directions but they are essentially the same: http://www.barbatricks.com/en/mac-en/open-split-r00-part1-rar-001-rar-mac/

You will end up with a .iso file and you can then import that into OpenEmu. Don't forget to delete your previously imported game first.

**Comment by GrimReaper1214** [comment]
Thank you so much i have just one more question is there a faster way or do i have to do this for all of the roms?

**Comment by clobber** [comment]
You need to do this for all of the games that happen to be rar'd.

**Comment by ian0523** [comment]
I had the same problem , and here's the solution .https://www.youtube.com/watch?v=tkyU2mWj5e8
