### ISSUE TITLE
Fake Wii U Pro Controller will not connect

### ISSUE THREAD

**Issue by Dimikosta** [OpenEmu/OpenEmu#2508]
Bought a cheap Wii U Pro Controller off of eBay for using it with emulators and what not, only to find it doesn't work at all. I haven't tried wJoy yet because Openemu recommends against using it. I see theres a workaround for knockoff PS3 controllers, maybe theres someway to change the ID of the fake controller to a real one?

Using a 13inch Macbook Pro mid 2009 on OSX 10.11.3

**Comment by clobber** [comment]
Sorry, no workaround that I'm aware of for this. The app only supports the official Wii U Pro controller.
