### ISSUE TITLE
Ports and how to add them to OpenEmud

### ISSUE THREAD

**Issue by ejtheslaya** [OpenEmu/OpenEmu#2509]
![screen shot 2016-04-23 at 4 49 19 pm](https://cloud.githubusercontent.com/assets/18637728/14765217/6649a5de-0a1b-11e6-983d-e4f9d07a69ca.png)
![screen shot 2016-04-23 at 4 49 00 pm](https://cloud.githubusercontent.com/assets/18637728/14765218/67bec96c-0a1b-11e6-8a56-47a8bbc9b209.png)

I, while looking for OpenEmu updates, stumbled across this. It says 'feel free to port these', but I have no idea how to port anything. Could anyone show me how to?

**Comment by clobber** [comment]
Not something that can be walked through. If you are a programmer you can look at implementations of the other emulator cores and possibly figure out how to port one.
