### ISSUE TITLE
Play SBI required games with PSX

### ISSUE THREAD

**Issue by racer21** [OpenEmu/OpenEmu#2510]
Some games require this SBI files to play LibCrypt protected videogames on the PSX, with ePSXe you can do it, putting it on the "patches" folder, but in OpenEmu there isn't that option.
How I can patch those games?

**Comment by clobber** [comment]
Mednafen requires the .sbi files to just be in the same location as the disc binaries, so ~/Library/Application Support/OpenEmu/Game Library/roms/Sony PlayStation

I'll be sure to add that extension to the system plugin so those can be drag and dropped.

**Comment by clobber** [comment]
Also noting that the file obviously needs to be named the same as the disc binary and SBI files can be found at redump's site e.g. http://redump.org/disc/28260/ "SBI subchannels" at the top.

**Comment by racer21** [comment]
Obviously, everything is downloaded from there, and has the same name, but the SBI file cannot be imported into OpenEmu, I think the problem is that it needs to be developed a Patches function just like the ePXEe emulator.

**Comment by racer21** [comment]
Sorry, I didn’t read the first answer, and yes, it does work. Thanks :’)

**Comment by balabambuz** [comment]
doesn't work anyway with final fantasy IX
