### ISSUE TITLE
Atari 7800 Pole Position ii not working correctly

### ISSUE THREAD

**Issue by Hardies1** [OpenEmu/OpenEmu#2513]
There is an issue with the game Pole Position II on Atari 7800 in this emulator. The issue is that you can only access the 2 tracks on the right hand side of the track select screen and not the 2 on the left hand side of the track select screen. I know the Rom file is fine because I have tried it in another emulator called emu7800 and it works perfectly(can access all 4 tracks). Please correct this issue as the one track that I really like to run is on the left had side of the track select screen and I can't play it on here. Thank You.

**Comment by clobber** [comment]
You need to press the 'Select' key in order to choose the other tracks on screen which, in control prefs for Atari 7800, is bound to 'Enter/Return' by default. I don't know why this is - could be an emulator or implementation error with the joystick - I have no idea how the game functions on real hardware. The emulator in use here is an updated version of ProSystem based on the Wii port.

**Comment by clobber** [comment]
Checked a changelog for EMU7800:

>Moved VBLANK OFF up by four scanlines, making the track selection screen in Pole Position II work with the joystick (thanks to Tom Hafner for the hardware report)

Also just verified in MAME/MESS, since it is known to have accurate 7800 emulation and it works with the joystick as well. So, guess we have a ProSystem bug here.

**Comment by clobber** [comment]
I've found that reducing the NTSC scanline count in ProSystem by four to 258 fixes the joystick on the track selection screen, but I don't know if this i the correct fix or if any other games break. Something to look into more.

https://github.com/OpenEmu/ProSystem-Core/blob/1660bd3992cfa016c86f33a5a26485e6db88ee65/core/Region.cpp#L32

**Comment by Hardies1** [comment]
Is this a change I can make myself or would an update to OpenEmu be released with this change in place?

 

-Jeff

**Comment by clobber** [comment]
A core update would need to be released with the fix. Just use the 'SELECT' key to choose tracks for now...
