### ISSUE TITLE
How to do a backup and restore

### ISSUE THREAD

**Issue by julesstrangelove** [OpenEmu/OpenEmu#2514]
I need to rebuild my system. 

Is there documentation on how to backup and restore all the configuration information for my library, save games, etc?   I can't find any procedures for it.

Thanks!

**Comment by clobber** [comment]
Basically you want ~/Library/Application Support/OpenEmu (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)

**Comment by julesstrangelove** [comment]
That doesn't just work. Here's what I did.  

Install OpenEmu, open it, then close it.
Copy that folder into position.
Reopen OpenEmu
Nothing shows up -- it's like it's a default install still.

**Comment by julesstrangelove** [comment]
Is it closed and now no one sees it? clobber, that didn't fix my problem....

**Comment by clobber** [comment]
Um yes closed tickets can be read, not necessary to open a new one. No offense, but you aren't exactly having an OpenEmu problem and whatever you're trying to do is unsupported.

The only help we can offer provided you are using OpenEmu v2, you need:
* ~/Library/Application Support/OpenEmu
* and possibly but not totally necessary: ~/Library/Preferences/org.openemu.OpenEmu.plist

If you still can't get it working then just reimport your files.

**Comment by julesstrangelove** [comment]
Clobber:

So how about the "backup" and "restore" features?   Is there documentation on how that works?    In the "File" menu, there's clearly a Library / backup function -- but greyed out in the image from the old machine (I have a bootable copy).

Is it unsupported to move a library from one machine to another?  If so, how come there is a backup option?

**Comment by clobber** [comment]
There is no built-in feature. Those are greyed out, meaning non-functional. They were added there a long time ago but functionality was never implemented and the menu items were accidentally left in.
