### ISSUE TITLE
SNES won't work... mac everything updated... 

### ISSUE THREAD

**Issue by fondooo** [OpenEmu/OpenEmu#2518]
i have a mac with 10.11.4, using open emu v2.0 and i can't get my snes to work.  i tried many websites but when i get a rom.  i goto drag into open emu and nothing happens???  every other system works.  Please help... i want my snes to work.

**Comment by clobber** [comment]
[Unzip](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) the file and then make sure you are importing the .sfc or .smc file.
