### ISSUE TITLE
Diddy Kong Racing split screen doesn't work

### ISSUE THREAD

**Issue by llamatamer** [OpenEmu/OpenEmu#2519]
Hey so I've been having issues with the Diddy Kong Racing splitscreen, mainly the second player's screen is blacked out. Everything else works fine, both controllers and graphics are responsive in the main menus. Just the gameplay this happens.

**Comment by clobber** [comment]
A general N64 emulation and GPU plugin bug.  Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
