### ISSUE TITLE
Closed issue #2514 isn't closed

### ISSUE THREAD

**Issue by julesstrangelove** [OpenEmu/OpenEmu#2524]
Sorry guys.. .clobber, you closed my issue but your fix didn't actually fix it.  Can you look at the comments I put in there?

**Comment by PlutoX86** [comment]
He actually did! You just need to copy/paste ~/Library/Application Support/**OpenEmu** to any external drive. Make sure your roms are stored in the **Game Library** folder though! 

After your system rebuild, just copy **OpenEmu** back to ~/Library/Application Support/ ... download OpenEmu again (or back that up, too) and everything should be fine.
