### ISSUE TITLE
OpenEmu (v2.0.1) not accepting scph5502.bin

### ISSUE THREAD

**Issue by jjonginamo** [OpenEmu/OpenEmu#2525]
Hi! I just downloaded OpenEmu and want to play PlayStation 1 games. It asked me to add scph5500, scph5501, and scph5502. I was able to drag and drop the first 2 in the game library but scph5502 wouldn't get identified. I also tried manually adding it to the bios folder but it just disappears whenever i try to load a PS game. Please help! Thank you :)
![screen shot 2016-04-29 at 2 43 33 am](https://cloud.githubusercontent.com/assets/18725648/14897477/afa40bce-0db4-11e6-8a0e-94f6b021f9ac.png)
![screen shot 2016-04-29 at 2 46 36 am](https://cloud.githubusercontent.com/assets/18725648/14897478/afff5272-0db4-11e6-8b72-95727298cc2d.png)

**Comment by clobber** [comment]
Follow the BIOS guide to be sure you have the correct file: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

You don't, which is why it will not import. A lot of bad and mislabeled dumps out there, so you will have to find another.
