### ISSUE TITLE
Advance Wars Dual Strike Bug

### ISSUE THREAD

**Issue by jromano89** [OpenEmu/OpenEmu#2528]
Cursor does not display
Looks like this was fixed in DeSmuME r5191, can this be ported to OpenEmu?

https://sourceforge.net/p/desmume/bugs/1494/

**Comment by clobber** [comment]
No, we only release core ports from their stable releases. Will have to wait until 0.9.12 or use their official standalone app with the workaround.

**Comment by HiroiSekai** [comment]
Hi, just wanted to shoot an update for this. DeSmuMe has a Mac-specific stable release link for 0.9.12 on their Downloads page of their website here: http://desmume.org/download/

I just downloaded the standalone app to my Mac and tested Advance Wars Dual Strike, and the cursor issue is resolved. Can this be implemented into a core update for OpenEmu? Thank you!

**Comment by phoenixeliot** [comment]
@clobber Any chance of an update on this issue? It looks like from the above comment a year ago, this may be fixed in the stable release by now.

**Comment by clobber** [comment]
>in the stable release by now.

There is no new stable release yet.

https://github.com/TASVideos/desmume
