### ISSUE TITLE
Moving MSX past experimental status?

### ISSUE THREAD

**Issue by pokebyte** [OpenEmu/OpenEmu#2530]
I'm not sure where else to bring it up, but I figured this would be a good place.

The only issue that I recall keeping blueMSX-Core in experimental status was an issue with video corruption on reset and the lack of graphical assets. 

Looks like there's already a computer icon, which is great - 1/3
With regard to video, I assumed (though didn't get a chance to confirm) that it was caused by a rendering sync problem between the helper app and the main window. I just tested the core now, and I'm no longer seeing that issue - 2/3?
There's no generic controller artwork, so no 3/3 :(

Given that ROM files are the primary way MSX games are played, I don't see lack of CAS and DSK support as a blocker for a release. 

So my question is, can we get some generic 2-button controller artwork and move the MSX plugin out of the experimental stage? Does anyone see any other issues that I'm not aware of?

UPDATE: Just saw #1534, so I'm wondering whether there's any point in continuing work on the plugin?

**Comment by clobber** [comment]
> I'm wondering whether there's any point in continuing work on the plugin?

Huh? Re-read that thread.

> Eventually we'll do a release that focuses all on computer systems (Atari 8-bit, C64, MSX, ZX Speccy, etc) which will be cool.

So yes, it will be available in a future release!

**Comment by pokebyte** [comment]
OK cool. Is the plan for arcade emulation similar?
