### ISSUE TITLE
My Save Game is Frozen?

### ISSUE THREAD

**Issue by EWZeiger77** [OpenEmu/OpenEmu#2533]
Im not sure what happened, but Im on my macbook air playing Pokemon, as you do. I was fighting a legendary Pokemon and accidentally killed him. So I went into my controller settings ( I am using a Playstation 3 Dual-shock Controller) And tried to bind L2 to Rewind. It wasn't really working and I was getting pissed off. But I restarted the game after creating a save file to where I was after I killed the Legendary. When I came back I couldnt move at all. At first I thought it was a controller issue, So I tried switching to the keyboard to control my character, and still nothing. So I found the troubleshooting on your website and did everything, but nothing worked. Thats when I realized maybe my save game file was corrupted. I went into different games and my controller worked fine. I even went into a different save game inside Pokemon Black and it worked just fine. I would just start playing from this other save game that I had, but It was from gym leader 2 and I was already fighting the Elite 4. If I had to start back from that point then I might as well give-up on the game. Last thing I tried was creating a new save game from the point where I was frozen, and it did the same thing to me, I was just Frozen. Will you Please Help Me? I was thinking that maybe there is a different place where OpenEMU kept more save game files because I have the PS3 button bound to save the game, where it puts a saving Icon in the top left corner, but it doesn't show me those saves in the bar at the bottom of the screen. Thats all I've really thought about doing with the problem. I would be really grateful I you guys could help me, although I know you are very busy. Thanks though If you do decide to help me!

**Comment by msikma** [comment]
If your save game is frozen, it's almost certainly a bug in whatever core you were using. So if you were playing a DS game then it would be a DeSmuME bug.

Is it possible you hit the pause button and then saved the game? Have you tried hitting the pause button again to unpause the game after loading?

> I was thinking that maybe there is a different place where OpenEMU kept more save game files because I have the PS3 button bound to save the game, where it puts a saving Icon in the top left corner, but it doesn't show me those saves in the bar at the bottom of the screen.

Do you mean the quick save/load buttons? They're in `~/Library/Application Support/OpenEmu/Save States/<system name>/<game name>/`. But you won't find any more.

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility.
