### ISSUE TITLE
PS1 serial regex pattern not matching all cases

### ISSUE THREAD

**Issue by aktau** [OpenEmu/OpenEmu#2534]
This started happening a while ago, unfortunately I can't give an exact date.

- Recently, for Rayman (PSX) I had to click "Download Covert Art" a couple of times before it "resolved". The cover art it downloaded is not of the usual dimensions, it's taller than it is wide (I don't know whether that's meant to be this way, but it's different from all other titles in the same category).
- For Chrono Cross (USA) (disc 1), it just doesn't resolve at all, while I think it would resolve (information below).

To avoid questioning whether Chrono Cross was contained in OpenVGDB found it at all, I checked manually:

```bash
$ sqlite3 -header "/Users/aktau/Library/Application Support/OpenEmu/openvgdb.sqlite" "SELECT romID, systemID, romHashCRC, romHashMD5, romHashSHA1, romSize, romFileName, romSerial FROM ROMs WHERE romExtensionlessFileName LIKE 'Chrono Cross (USA) (Disc 1)';" | column -t -s'|'
romID  systemID  romHashCRC  romHashMD5                        romHashSHA1                               romSize  romFileName                      romSerial
64167  38        005354C2    1563ECC3A2AAEF7D7B5BBE64C564818E  14CEBDEAF5A9B1192E589E912F6D0E310645811F  93       Chrono Cross (USA) (Disc 1).cue  SLUS-01041
```

Let's see if the hashes match with the files I have:

```bash
$ parallel -k "{1} {2} | sed 's/^/{1}: '/" ::: du md5 shasum crc32 ::: "Chrono\ Cross\ \(USA\)\ \(Disc\ 1\).bin" "Chrono\ Cross\ \(USA\)\ \(Disc\ 1\).cue" | column -t -s:
du       1438776	Chrono Cross (USA) (Disc 1).bin
du       8	Chrono Cross (USA) (Disc 1).cue
md5      MD5 (Chrono Cross (USA) (Disc 1).bin) = 3b29ee931df29f51ecf0817f30e103d7
md5      MD5 (Chrono Cross (USA) (Disc 1).cue) = 1563ecc3a2aaef7d7b5bbe64c564818e
shasum   91ce7726d264111c068a0bee89784f6ebd42ac54  Chrono Cross (USA) (Disc 1).bin
shasum   14cebdeaf5a9b1192e589e912f6d0e310645811f  Chrono Cross (USA) (Disc 1).cue
crc32    a07898cc
crc32    005354c2
```

So the filesize `du` doesn't really seem to match (perhaps I'm interpreting that openvgdb field wrongly), but the MD5/SHA1/CRC32 of the `.cue` file all match.

I tried using `dtruss(1)` to see which websites OpenEmu was trying to contact to get the cover art, but no luck so far. I haven't been able to find anything by grepping in the code either, which is somewhat weird.

**Comment by clobber** [comment]
Disc-based games are not identified by the checksum of their cuesheets, but by the serial number or header in the actual dump. In your case, the following happens for PS1: https://github.com/OpenEmu/OpenEmu/blob/master/OpenEmu/PlayStation/OEPSXSystemController.m#L82

Regarding Rayman: That is the cover art. Nothing wrong there.

Most likely, if you are having temporary issues where the cover art did not download but later does, it is network related i.e. the website in which it snags the cover could not be resolved. So I wouldn't worry too much about this. As for other possible reasons covers might not download:

1. Your IP is blocked from the source.
2. Cover art did not exist at the source (gamefaqs).
3. The game matched but the particular game didn't have a URL for cover art added yet (incomplete).
4. The system for those games has no cover art added yet (incomplete).
5. The game was not matched in the database at all.

**For Chrono Cross (USA)**, there appear to be a case with that game where we are not parsing the string correctly, which should return `SLUS-01041` as you can see:

```
5/5/16 10:13:05.101 AM OpenEmu[15184]: RegEx pattern could not match serial. Full string:
BOOT	= cdrom:\SLUS_010.41;1
TCB		= 4
EVENT	= 16
STACK	= 801fe000
```

So you found a bug with the regular expression in which we parse the PS1 serials. Thanks for reporting!

**Comment by aktau** [comment]
Alright, thanks for the explanation!

Just one more thing:

> 1. Your IP is blocked from the source.
> 2. Cover art did not exist at the source (gamefaqs).

Could be, though I doubt it. What's the source? Is it only gamefaqs?

> 3. The game matched but the particular game didn't have a URL for cover
>    art added yet (incomplete).

Is this URL hardcoded somewhere? Or built up out of pieces?

> 4. The system for those games has no cover art added yet (incomplete).

Could be, depends on the source.

> 5. The game was not matched in the database at all.

If you're referring to the openvgdb, then at least they do seem to exist (I *think* remember having this problem with Metal Gear Solid lately, too).
