### ISSUE TITLE
Why does NES have only 2 buttons A and B?

### ISSUE THREAD

**Issue by ProgrammingLife** [OpenEmu/OpenEmu#2535]
Famicom and Nintendo NES has only 2 buttons: A and B on the joypad but in my early 90's we had 4 buttons in the joypad. Look here: http://skrebnyov.narod.ru/index.files/pristavka.gif
Why? :)

**Comment by clobber** [comment]
Those are turbo buttons and on a Dendy machine. Technically not a Famicom/NES.

**Comment by meller713** [comment]
What do you meen technically not nintendo/NES? We play same NES files on emulator (not on yours, ofcource) but you just delete this two buttons even though you're using nestopia's work. In Russia we didn't  have nintendo and had only Dandy. Looks like you just don't like Russians as you didn't add this buttons during 3 years. Some of our games you just won't walk through without this buttons, and some of them just loose their charm. You don't need to impose your opinion, just let people choose "use turbo or not to use". it just looks not too tolerant.
