### ISSUE TITLE
please add "glide64" video plugin for the mupen64plus core

### ISSUE THREAD

**Issue by soraythus** [OpenEmu/OpenEmu#2536]
some games like star wars: shadow of the empire can't be played with the rice-plugin really, there's just to much blinking/flickering. it would be really awesome if the user could choose which video plugin should be used. i know this means a lot of work and i don't expect a fix in the near future, just wanted to let you know what could be optimized from my point of view... thx!

**Comment by clobber** [comment]
https://github.com/OpenEmu/Mupen64Plus-Core/issues/5
