### ISSUE TITLE
Library empty after update

### ISSUE THREAD

**Issue by benb1** [OpenEmu/OpenEmu#2537]
Hello everybody.
First of all OpenEmu is fabulous! benn searching for this for years. I use it since 2013, but i have a small issue. When i update the software, my library is not recovered. Everything is empty ( games, saves ). All the files are still in library/application support/ open emu, but OpenEmu doesn't seem to see them. Have you seen this somewhere? thanks a lot

**Comment by mattrstokes** [comment]
Exact same thing happened to me.

**Comment by benb1** [comment]
however i can re import my saves from application support folder, and it works like this. a bit long if you have a lots of files :)

**Comment by clobber** [comment]
Seems like you worked around this and we won't be able to troubleshoot it then.
