### ISSUE TITLE
Sony Playstation Issues !

### ISSUE THREAD

**Issue by azk404** [OpenEmu/OpenEmu#2540]
Hi there,

Yesterday I tried adding the PSX BIOS to open emu with no luck at all.

I checked the hash codes, which all checked out but every time I drag the 3 .bin files into the Sony PlayStation Library it just says in the bottom left corner 'resolve 3 issues'.

If I click on the resolve issues the list shows the 3 files and next to the apply button in the drop down box it has 3 options:

Atari 2600
Don’t import selected
Video Pac+

I also tried changing the file names to the other version listed on the tutorial area, I.e. 5501 to 7003.

Nothing else I can really do it seems.

If I try to add PlayStation rom folder it adds the game but doesn't show in the PlayStation library. In the 'all games' collection if I click 'show in finder' it shows the game in the Video Pac + folder.

I am running Mavericks and v1.0.4 of open emu.

I googled it but couldn't find any answer just a few more people that have similar problems! Any help would be great :)

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to v2 and OS X 10.11.

**Comment by azk404** [comment]
Updating to El Capitan something I don't want to do so damn !

**Comment by asoksevil** [comment]
There are some 1.0.4 versions floating around that work perfectly. I might be able to get one of those, but not sure if I can publish it here.
