### ISSUE TITLE
[Feature Request] Turbo mode 

### ISSUE THREAD

**Issue by thejamespinto** [OpenEmu/OpenEmu#2543]
#832 is a feature request made a while ago. 
Can we talk about maybe implementing it?
Some games are too slow by default and I like mostly play them while holding the turbo button.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/832#issuecomment-31184674

**Comment by thejamespinto** [comment]
@clobber I'm sorry I wasn't specific enough, I was tired last night.

I mostly play whole holding the turbo button (key configured for fast-forward).
But I don't want to hold that button.
I would prefer to press the button once, then it is always fast-forward.

What do you think?

**Comment by thejamespinto** [comment]
@xyz123jasdh 832#issuecomment-38485869

**Comment by thejamespinto** [comment]
@xyz123jasdh you might be interested in this because of  https://github.com/OpenEmu/OpenEmu/issues/832#issuecomment-38485869
