### ISSUE TITLE
Some Games crash on OpenEmu (PSP MODE)

### ISSUE THREAD

**Issue by Jerry2396** [OpenEmu/OpenEmu#2544]
Hello Guys,

I discovered OpenEmu today and I was really surprised positively! I would love it, if it would work :/ most of my favorite Game is Kingdom Hearts. I tried Birth by Sleep for PSP and it crashes at the beginning every time. ( After the third beginning scene) 
I wonder why.. I tried different roms but it doesn't work... But not only this Game, also other Games like Dragonball or Yu-Gi-Oh doesn't work 100%... 
Can you tell me why? 

Thank you!

**Comment by Jerry2396** [comment]
Ah I forgot to tell I use a Mac.. Is this maybe the reason?

**Comment by clobber** [comment]
Well we don't develop the emulators. If there are compatibility issues in PPSSPP that is up to the emulator developers to correct. Also please keep in mind the reason we display this message in the app:

![screen shot 2015-12-29 at 7 27 07 pm](https://cloud.githubusercontent.com/assets/1303132/12045507/46add534-ae62-11e5-9a4d-9108a89767dc.png)
