### ISSUE TITLE
Adding DSP1b to OpenEmu

### ISSUE THREAD

**Issue by nestornaz92** [OpenEmu/OpenEmu#2545]
I've downloaded a DSP1b.zip file to start playing Super Mario Kart. It says to just drag the file into the game library. That did not work. So I unzipped the file and tried dragging the folder. That didn't work either. Then I tried to drag the two individual files from the folder (dsp1b.data.rom and dsp1b.program.rom), both together and separately.... nothing. I've restarted OpenEmu, restarted my computer, redownloaded the file, and nothing seems to work. Please advise.

MacBook Air Early 2015, OSX 10.11.4, OpenEmu V2.0.1 407-g415a4a6-Release.

**Comment by clobber** [comment]
It needs to be the correct file. See the md5 checksum in the BIOS guide for more information: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files#snes-chip-dumps-for-higan

That is all the help we can offer for this.

**Comment by bloodstrike** [comment]
I see that this is closed, but there is a problem with Higan's core currently. Even with a correct md5 checksum-ed dsp1b.rom, Higan is trying to load dsp1b.program.rom and dsp1.data.rom on load:

```
5/19/16 3:54:00.979 PM OpenEmuHelperApp[29203]: Loading file "manifest.bml"
5/19/16 3:54:00.979 PM OpenEmuHelperApp[29203]: Loading file "program.rom"
5/19/16 3:54:00.980 PM OpenEmuHelperApp[29203]: Loading file "save.ram"
5/19/16 3:54:00.980 PM OpenEmuHelperApp[29203]: Loading file "dsp1b.program.rom"
5/19/16 3:54:00.980 PM OpenEmuHelperApp[29203]: Higan: Wasn't able to load file "dsp1b.program.rom"
5/19/16 3:54:00.981 PM OpenEmuHelperApp[29203]: Loading file "dsp1b.data.rom"
5/19/16 3:54:00.981 PM OpenEmuHelperApp[29203]: Higan: Wasn't able to load file "dsp1b.data.rom"
5/19/16 3:54:00.985 PM OpenEmuHelperApp[29203]: Loading file "manifest.bml"
5/19/16 3:54:00.985 PM OpenEmuHelperApp[29203]: Loading file "ipl.rom"

```

From what I've been able to find out, dsp1b.program.rom and dsp1b.data.rom and literally dsp1b.rom split into two files and loaded separately:
http://www.neogaf.com/forum/showpost.php?p=73698723&postcount=155

But Higan won't load/find these files from OpenEmu's BIOS directory. If both files are put in Application Support/OpenEmu/Higan/Super Famicom/<rom name>/, the game will load correctly, but on closing the rom, dsp1.program.rom is deleted and the game won't open again.

Not sure if any of this can/will help, just thought I'd share the information I was able to gather.

**Comment by clobber** [comment]
Looks like this broke with the v095 update.
