### ISSUE TITLE
Window title should fade out in-game

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/OpenEmu#2547]
Why doesn't the titlebar go away! (It needs to come back if the mouse is over the window too.)

http://stackoverflow.com/questions/28371381/nswindow-animate-show-hide-titlebar

**Comment by robotoad** [comment]
The examples of this effect that I'm aware of, specifically Quicktime Player, have titlebars that overlap the  window's content and reappear on mouse input. The downside here would be that games which use the mouse, such as DS games, would repeatedly make the titlebar reappear, obscuring content.

**Comment by mrvacbob** [comment]
True, but the HUD/controls bar at the bottom already does that, doesn't it?

**Comment by robotoad** [comment]
It does, but you can drag it outside the window.

**Comment by clobber** [comment]
Oh they don't even have to do that. Just hit Shift+Cmd+H to 'Always Hide HID'
