### ISSUE TITLE
Open Emu Failing To Work (doesn't work, at all...)

### ISSUE THREAD

**Issue by ZerR0Sound** [OpenEmu/OpenEmu#2548]
# !! URGENT HELP !!

~ Running OS X El Capitan 10.11.4 ~

For some reason no roms load onto the application and when trying to play a homebrew game the application crashes (since this is the only way to try and get a game to run). Is there any fix to this reoccurring problem??

(Yes I have been on the forum and completed all the steps using Terminal with no success)

**Comment by mrvacbob** [comment]
Please post the crash log.

**Comment by robotoad** [comment]
Closing for lack of info.
