### ISSUE TITLE
NDS Issues

### ISSUE THREAD

**Issue by GiveMeAnthony** [OpenEmu/OpenEmu#2551]
These are a few issues with the NDS emulator.

1. Microphone button has poor response.
2. No option to use microphone input.
3. Can't put DS in side-by-side layout.

Regarding issue (1), the key to simulate a blow has a very weak response. Some in-game items require a sustained blow which cannot be simulated by holding down the microphone button. Instead, my current workaround is to repeatedly tap on the mic button. Obviously, this isn't ideal. Therefore, I suggest that the microphone button be made repeatable. I'd imagine that there's some kind of internal tone generator to simulate blowing into the mic.

Regarding issue (2), real microphone input ought to be supported. I think every macbook comes with a webcam, so it's natural that Mac users would think this is the default control. It's much more interactive and entertaining to use a legitimate microphone.

Regarding issue (3), some games require that the user turn the DS on its side. An example of such a game is [Love Plus](https://www.youtube.com/watch?v=TQrFXJlyacE). This should be incorporated into the display mode key, because that seems most logical.

P.S. How would I go about contributing to this project or its cores? I'm happy to help where I can.
P.P.S. I know points (1) and (2) are often referenced to issue #1047 but that doesn't tell me anything about the current progress of these points.

**Comment by clobber** [comment]
Hi, these have pretty much been covered in other issues:

1 & 2: https://github.com/OpenEmu/OpenEmu/issues/1047
3: Covered in several. Will need a change to both the front end and the Desmume plugin. When we get to it.

Thanks. As far as contributions, you could consider a donation. See details in our Twitter bio: https://twitter.com/openemu
