### ISSUE TITLE
DS Z-Fighting

### ISSUE THREAD

**Issue by GiveMeAnthony** [OpenEmu/OpenEmu#2552]
I had forgotten to mention another problem when opening up #2551. There appears to be Z-Fighting on the NDS core. Recorded a quick clip to demonstrate the issue: [OpenEmu NDS Z-Fighting](https://www.youtube.com/watch?v=vNLWTzdwV2c)

**Comment by clobber** [comment]
Oh, that's going to be a Desmume bug and not OpenEmu related. We use the latest stable of Desmume NDS emulation.
