### ISSUE TITLE
Yoshi's story bug

### ISSUE THREAD

**Issue by dris695** [OpenEmu/OpenEmu#2555]
Hello, it's the first time i use OpenEmu, it's amazing ! But i have some bugs when i'm playing Yoshi's story on N64, there is some lag on the screen.

I'm not an expert, please can you help me to fix this bug.

Thank you

**Comment by clobber** [comment]
A Mupen64Plus GPU plugin bug.  Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
