### ISSUE TITLE
Won't let me map classic controller + WiiMote

### ISSUE THREAD

**Issue by hullstar242** [OpenEmu/OpenEmu#2556]
I can map every other controller just fine including a plain wiimote but once I plug in the classic controller every controller gets stuck in what's already been mapped and I have to close out of OpenEmu in order to be able to map again.  I didn't have this problem before im not really sure why this started to happen.  Im running the most recent build including the N64 speed up fix.

**Comment by braco** [comment]
Related? #1607

**Comment by clobber** [comment]
Similar enough to #2371

There is no fix for this as of now.
