### ISSUE TITLE
Scroll bars bugged

### ISSUE THREAD

**Issue by oraichu** [OpenEmu/OpenEmu#2560]
Hi

For quite a long time I have been annoying myself over the bugged side scrolling bars I have in my OpenEmu. This is the only application I'm seeing this in, they seem to be fitting the style of an older OS X program, not the thinner ones that would fade out.. which was in OpenEmu before. Sadly I can't recall exactly when these appeared. 

Any clue how to fix this? 

Screenshot attached to show what I mean:
![image](https://cloud.githubusercontent.com/assets/8253068/15455373/208441de-208d-11e6-8a2b-3b9c918c58d0.png)

**Comment by robotoad** [comment]
OpenEmu uses the system scroller style, which changes based on the input devices connected to your computer. You can force a particular scroller style in the General pane in System Preferences.
