### ISSUE TITLE
Japanese PSX titles not adding to library

### ISSUE THREAD

**Issue by FelixAC** [OpenEmu/OpenEmu#2561]
Hello! I'm relatively new to OpenEmu, but it's definitely the best experience I've had with any emulator. Super well laid out, works great and looks great.
The only problem I've had so far is with the PSX; most titles add to the library fine when I drag and drop them, however, when I drag in Japanese releases, the Game Scanner will pop up in the bottom left as usual with a loading bar saying "Game x of x", but when it finishes no title is added to the library. If I check the roms folder in application support, the files have not been added there either, and adding them manually doesn't work.

I've tried replacing the Japan BIOS file and I've md5 checked it each time, and I've tried with about 7 different game titles. I'm running v.2.0.1 on El Capitan. Thank you in advance for any help you can provide!

**Comment by clobber** [comment]
Probably not an issue with OpenEmu but an issue with whatever dump you are trying to import. Give me an example of a Japanese release and it's files (cue, bin, whatever).

**Comment by FelixAC** [comment]
Hey Clobber, thanks for the speedy reply. Here's a few of the releases I've tried:

Pepsiman (cue, iso)
Shaman King- Spirit of Shamans (bin, cue)
Marl Oukoku no Ningyou Hime - The Adventure of Puppet Princess (cue, bin.ecm)

**Comment by clobber** [comment]
I have Pepsiman imported fine, but I am aware of bad dumps floating around.

>Marl Oukoku no Ningyou Hime - The Adventure of Puppet Princess (cue, **bin.ecm**) 

Please see the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for how to load games, especially dealing with .ecm files.

This is the best I can do to help you out, since this is an issue with the dumps you are importing.

**Comment by FelixAC** [comment]
No worries, thanks for your help!
