### ISSUE TITLE
Looking for help using analog stick with Openemu

### ISSUE THREAD

**Issue by Owleater0** [OpenEmu/OpenEmu#2563]
I'm trying to use an Atari 5200 controller with Openemu.
 I acquired an adapter to USB the 5200-dapter from Hafner Enterprises.
 All the buttons configure perfectly except the directional controls. When I go left, it will stay going left until I go right. then it'll go right without stopping. Tom Hafner who made the adapter said this, 
" I am suspect this has something to do with the 5200 controllers being analog. It outputs a varying value that corresponds to how far off center it is. Also, there is *no* center detent on the controller, so you have no way of knowing when the joystick is centered. Thus while you think you have it at center, it is probably always a little bit off, and thus always giving a slight left or right, or up or down. I'm guessing Open Emu is then taking *any* amount off center to be a move in that direction.
Look in the Open Emu settings for something like centering dead band or threshold and increase it. This would be a setting to ignore any small move of the joystick."
   However, there is no option to center the dead band or increase the threshold that I found in Openemu.
 Is there anyway to fix this? Tom from Hafner Enterprises also said to feel free to contact him in regards to this. his email is: contact_2600adaptor@yahoo.com
please help me understand how to get this thing to work. Thank You!
-Joe

**Comment by clobber** [comment]
The 5200 controller was **terrible**, if not the worst controller ever made, because the joystick was not self-centering. So if you moved it left it would be stuck in that direction. In short, there is no easy way to get your controller working the way you want with OpenEmu. Not short of modification that may not be worth the effort and possibly something like #1303. 

Sorry, I'd recommend any other device as an alternative.

**Comment by Owleater0** [comment]
Thanks clobber. That sucks! Does it often stay stuck in that direction when being played on an actual Atari 5200 console? Whatever modification info you sent me is like a foreign language to me so I guess I'm stuck. Thanks though.

**Comment by clobber** [comment]
By design, the 5200 controller joystick would stay stuck in any direction - yes, even on real hardware - making twitchy games like Pacman unplayable. It's a notoriously bad controller. Honestly, use any other controller besides that for playing games and you'll be much happier.

**Comment by Owleater0** [comment]
Okay, my final inquiry.
I'll probably just heed your advice and use a different controller.
 Would the problem I'm having in Openemu with my controllers happen if I plugged those same controllers into the 5200 console? Or do you think it's happening because I'm using them on Openemu and not a console? I've noticed that the left movement is actually okay and the character will stop when not moving the stick left. It's mainly the right movement that will not end. 
Might it be possible for me to get lucky and get a 5200 controller that happens to be perfectly centered and actually work? Or, do you feel with Openemu, I will ALWAYS get that same reoccurring problem regardless of whatever 5200 controller I use? There must have at least been some 5200 controllers out there that worked correctly right? If you feel you've had enough of this conversation and don't want to respond I understand. I'm just having a hard time letting go of getting a 5200 controller to work on Openemu because I went through the trouble of getting the adapter and the controller and everything. But "that's life" I guess as they say. I just wish there would have been a bit more explanation about the trickiness of getting the 5200 controller to work on emulators when I initially bought that adapter.Thanks again for your help.

**Comment by clobber** [comment]
**Please** re-read what I am telling you:

> By design, the 5200 controller joystick would stay stuck in any direction - yes, even on real hardware - making twitchy games like Pacman unplayable. It's a notoriously bad controller.

Buy an actual good, modern gamepad. A lot on the market to choose from:

* SteelSeries Nimbus

* PlayStation 4 DualShock 4

* Logitech series (Dual Action, Rumblepad 2, Gamepad F310/F510/F710)

* etc
