### ISSUE TITLE
Moving mouse freezes games 

### ISSUE THREAD

**Issue by doggobroggo** [OpenEmu/OpenEmu#2567]
Lately I've been trying to play Megaman X and MegaMan 2 (SNES/NES) and every time I even slightly touch the trackpad the game freezes entirely, and I have to force-quit OpenEmu. 

I don't have this problem on the N64, however.

**Comment by clobber** [comment]
Which version of OpenEmu?

**Comment by clobber** [comment]
Pretty sure it's 1.x which is unsupported while using a newer, incompatible core plugin. Update to v2 and OS X 10.11.
