### ISSUE TITLE
8Bitdo NES30 Pro controllers

### ISSUE THREAD

**Issue by heyuimintojsus** [OpenEmu/OpenEmu#2568]
Hi, sorry if this is in the wrong place - I have looked to no avail and was told to post in one of these forums. Is it possible to use two 8Bitdo NES30 Pro controllers at the same time for the two-player games, etc? Are you able to use two of the same of any kind, or both must be different? If both have to be different, what is the best to use? I mainly play the NES, SNES, Sega Genesis and N64 games. I have tried Yobo, but the d-pad doesn't move right. Thanks.

**Comment by clobber** [comment]
Yes, it should be possible unless there is a bug with multiple duplicate devices. Otherwise, different ones will work.

As for best to use, I'd probably recommend the SteelSeries Nimbus at this point.

**Comment by heyuimintojsus** [comment]
But the Nimbus doesn't have enough buttons, for like start and select?

**Comment by clobber** [comment]
This is an entirely subjective matter and one where you want to do your own research, but the Nimbus has more than enough buttons (both face and shoulder/trigger) to accommodate NES, SNES and Genesis games. The least used console buttons are simply bound to other buttons on the controller, such as 'Start' and 'Select' for the triggers or shoulders.

**Comment by heyuimintojsus** [comment]
Thanks. Last question. Is this the one you are referring to? I ask bc I didn't see the computer/laptop being on the compatible list.
http://www.apple.com/shop/product/HJ162ZM/A/steelseries-nimbus-wireless-gaming-controller?rdt=redirectionFromReviewsPage

**Comment by clobber** [comment]
Yeah, that's the one. It works (I have one myself) and is the reason we have it in the list of supported automapped devices on the website.
