### ISSUE TITLE
The hudbar is gone for open emu

### ISSUE THREAD

**Issue by joeker3412** [OpenEmu/OpenEmu#2569]
when i just downloaded open emu again because this was a new laptop when playing Pokemon for the first time on the laptop it doesn't appear  because i wanted to add cheats but i couldn't find it like even if i moved the mouse it didn't move can some one please tell me how to fix this and get the hud bar up 
or if there is another way to add cheats

**Comment by clobber** [comment]
* Be using OpenEmu v2
* Menubar > Controls > Always Hide HUD (shift+cmd+H)
