### ISSUE TITLE
Turbo buttons missing for NES

### ISSUE THREAD

**Issue by nitinsurana** [OpenEmu/OpenEmu#2570]
Can't find a way to associate keyboard buttons corresponding to turbo A & B buttons for NES emulator/core. FYI - I am trying to play BattleCity on Mac.

**Comment by clobber** [comment]
I think you are meaning rapid fire. Please use the search. 

#933

**Comment by nitinsurana** [comment]
Found it earlier, but it's locked, can't 👍

**Comment by alvarocastro** [comment]
Everyone links to that thread, but it's like 3-4 years old.

Any news about this? Are the turbo buttons comming? It would be great tbh
