### ISSUE TITLE
Won't let me access menu. 

### ISSUE THREAD

**Issue by KevTheDansa** [OpenEmu/OpenEmu#2571]
So, openemu works, the only issue i'm having with it is the fact that the window that pops up displaying the game won't let me access the menu. It also wont let me minimize or hide the window. Idk what caused this, when I first downloaded the emulator and game, I didn't have this issue. Please help.

**Comment by clobber** [comment]
Which version of OpemEmu? Are you talking about the HUD bar not displaying, where you need to do Menubar > Controls > Always Hide HUD (shift+cmd+H) ?

**Comment by KevTheDansa** [comment]
The version I'm using is Openemu 2.

**Comment by KevTheDansa** [comment]
How do I access the menu bar?

**Comment by clobber** [comment]
The same as any other application on the Mac... https://support.apple.com/kb/PH21890?locale=en_US

**Comment by KevTheDansa** [comment]
Not to be disrespectful

**Comment by KevTheDansa** [comment]
But do you own this site? And I apologize, I didn't realize you replied to this.

**Comment by clobber** [comment]
Actually **read** above what I am telling you and stop opening new issues.

**Comment by KevTheDansa** [comment]
Thats my point, I must've closed the issue without refreshing the page, so I didn't actually SEE your response until I just came back, hence, my apology.

**Comment by KevTheDansa** [comment]
Wasn't trying to be annoying, I was just being a little impatient.

**Comment by KevTheDansa** [comment]
Its not working, btw.

**Comment by clobber** [comment]
Sorry, don't know what to tell you. You need to better describe the problem with possible steps to repeat it. Perhaps the core helper process crashed and you need to force quit the app?

**Comment by KevTheDansa** [comment]
I'll try to describe it the best I can. Y'know those 3 little tri-colored dots that pop up on any window you open on a mac? The red, yellow, and green ones, that let you close, minimize, or hide a window. Yeah, so when I open openemu and click on the game, the window would pop up displaying the game, along with the dots at the top. I had an issue where the HUD menu wouldn't pop up upon looking for it, even waving the mouse across the screen wasn't working, so, I found a glitch; by going fullscreen, then minimizing the screen back to normal size, the menu would pop up with enough time for me to pause the game and use the menus function. Now, the only thing that pops up is the option to close the menu, the little x in the circle, and the menu wont pop up at all. Thats literally the best way I could describe it, I'm honestly terrible with computers.

**Comment by robotoad** [comment]
> Now, the only thing that pops up is the option to close the game, the little x in the circle, and the menu wont pop up at all.

If you're only seeing a close button at the top, that is the popout gameplay window, which displays the game in a second window with the main library window remaining in the background. You can change this behavior in Preferences->Gameplay by unchecking "Always use popout gameplay window." Doing so will cause games to be played in the main window instead.

If the gameplay HUD isn't appearing when you move the mouse, go to the Controls menu at the top of the screen and make sure "Always Hide HUD" is unchecked, or press Shift-Command-H.

**Comment by KevTheDansa** [comment]
THANK YOU!!!!  IT WORKED!
