### ISSUE TITLE
RTC not enabled

### ISSUE THREAD

**Issue by adelgirl** [OpenEmu/OpenEmu#2575]
One of the games I wanted to play requires that the RTC (Real Time Clock) be enabled, but I cannot find where to do that. I am trying to play a hack of pokemon fire red that implemented a time system, but since the game did not have a time system to begin with the emulator will not acknowledge the time system, it makes me unable to finish the story, because some of the events can only happen at night.

Is there a possible way to turn the RTC on for the emulator, or do I need to find a different emulator?

**Comment by clobber** [comment]
I'd suggest this thread here: #1541

**Comment by adelgirl** [comment]
I already checked that one, and when i tried to patch the game after doing that it did not work

**Comment by clobber** [comment]
Hex editing the Game ID to an appropriate RTC supported ID works fine provided that you are not restoring a previous save state from before you made the change. This would mean you do:

* OpenEmu > Preferences > Library and click the 'Reset Warnings' button

* Load the game and make sure to click 'No' if it asks you to 'Continue your last game'.

**Comment by adelgirl** [comment]
The actual patch software will not patch the game if I change the game id with hex editor. I get this error- Input file (the file you're applying the patch to) size and/or CRC32 invalid. This means you picked the wrong file.

**Comment by clobber** [comment]
Obviously, you need to be changing the ID of the game **after** you have patched the original ROM.

**Comment by adelgirl** [comment]
Well, the version after patching it does not use the fire red code at all, it uses the ruby codes, yet the time still won't work

**Comment by clobber** [comment]
It works fine, provided that you have replaced the Game ID with an RTC supported one after patching (if it does not already use one) and that you have followed the steps above to not restore an autosave or save state on launch. Sorry that's all I can do.
