### ISSUE TITLE
PSP Issues : Some games crashes when video 

### ISSUE THREAD

**Issue by Barbadak** [OpenEmu/OpenEmu#2576]
Hi
I played Ace combat Joint Forces when my game crash. I don't know why. But some players said it's because the video are not supported by the PPSSPP core. 
They said to disable “Media Engine” but Openemu has no option for that. Can I fix this problem ? How can I fix it ? I don't know how to code ... so please, explain to me.
Thank

**Comment by clobber** [comment]
PPSSPP bug. There is no way to toggle extra per-core options for compatibility hacks like this. I'd recommend using PPSSPP standalone to work around the issue.
