### ISSUE TITLE
Drag and drop doesn't work

### ISSUE THREAD

**Issue by ahmadsyarbini** [OpenEmu/OpenEmu#2578]
Running El Capitan 10.11.5. The drag and drop doesn't work for Sega Genesis ROM and SEGA CD BIOS All region.

**Comment by clobber** [comment]
Works for both. Here is a guide relating to the BIOS: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

If a legit Sega Genesis game is not being picked up, it could be a 'bad' dump that doesn't contain a proper header (which is what we use to ID games). If you have a game that is compressed, try unzipping it and make sure the file you are importing is .smd/.md/.gen/.bin
