### ISSUE TITLE
Emulator Deleted Backup ROM of Game

### ISSUE THREAD

**Issue by SkaaRidley** [OpenEmu/OpenEmu#2579]
I'm not exactly sure of what happened, but while I was playing Golden Sun: The Lost Age, I reset the console. However, rather than do that, the window froze. The message "Failed to communicate with helper application" appeared, and the window closed itself. When I tried to reopen the game, I discover that all my progress is gone. More recent, as I try to play again, I discovered that apparently, something else is missing, as the game itself brings up the message "Unable to detect backup memory."

**Comment by clobber** [comment]
What version of OpenEmu are you using?

**Comment by SkaaRidley** [comment]
OpenEmu v1.0.3.

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to v2 and OS X 10.11.
