### ISSUE TITLE
Controller Compatibility Issues

### ISSUE THREAD

**Issue by PiratePake** [OpenEmu/OpenEmu#2581]
Hi I just picked up a Gravis Eliminator Aftershock controller with USB port at a yard sale for $2. I was going to use it with Open Emu on my Macbook. While OE recognizes the controller, I can't configure any of the buttons for gameplay. Help?!

**Comment by clobber** [comment]
Which version of OpenEmu? Did you verify that your $2 gamepad from a yard sale is even functional in the first place? Do you have additional 3rd party input software installed that could be causing interference?

**Comment by PiratePake** [comment]
I'm currently using 1.0.4 of open emu, on OSX 10.9.5. I'm not sure if its fully functional, the mom was selling it for her son. How would I check to see if I had 3rd party input software installed that would cause problems? Or do I need to download any software to use it? Also thanks for replying!

**Comment by clobber** [comment]
You could google some input apps designed to test devices. Anyway, this doesn't solve your issue but sorry, OpenEmu 1.x is unsupported. Update to v2 and OS X 10.11.
