### ISSUE TITLE
OpenEmu wont detect analog sticks from wireless 360 Controller

### ISSUE THREAD

**Issue by DavidEscalante** [OpenEmu/OpenEmu#2582]
As title says, OpenEmu is not using the analog sticks for any game from any platform, while OpenEmu detects and maps the inputs:
https://dl.dropboxusercontent.com/u/67104790/screenshots/openemu_github/github1.jpg

The game it self only uses the D-Pad, it wont use any of the analog sticks in the 360 controller.

Im using the recommended driver listed in the webpage:
https://dl.dropboxusercontent.com/u/67104790/screenshots/openemu_github/github2.png

**Comment by clobber** [comment]
Analog sticks are only going to work in supported games/systems. In some PS1 games, for example, you may need to first press the 'Analog Mode' key.
