### ISSUE TITLE
"select" not working in NDS

### ISSUE THREAD

**Issue by Mochino1104** [OpenEmu/OpenEmu#2583]
the "select" key i set is "space" however its not working and i tried changing another key its still not working. Other keys i set worked perfectly. what should i do?

**Comment by clobber** [comment]
Works here. Which version of OpenEmu?

**Comment by Mochino1104** [comment]
v2.0.1

**Comment by Mochino1104** [comment]
oh i got it, that game use another key to select instead of "select"...thanks
