### ISSUE TITLE
8bitdo zero

### ISSUE THREAD

**Issue by sanilraut** [OpenEmu/OpenEmu#2584]
Hi,

I recently purchased the 8bitdo Zero  gamepad. When I went tried to map 8bitdo with the controls of GBA, I could setup the direction keys but all the assigned keys go blank when I try to setup start key and every key after start key.

**Comment by clobber** [comment]
Which version of OpenEmu?

**Comment by sanilraut** [comment]
2.0.1

**Comment by clobber** [comment]
Most 8bitdo devices are known to work, assuming they have the latest firmware and are in the correct mode: http://www.8bitdo.com/zero/Manual.html

If you have done all of this, you could try recording a video of your issue so we can better see what is going on.

**Comment by clobber** [comment]
Should have been fixed in OpenEmu 2.0.2
