### ISSUE TITLE
NeoPop 

### ISSUE THREAD

**Issue by azoreseuropa** [OpenEmu/OpenEmu#2585]
I found a new one called lr-beetle-ngp and it is a Neo Geo Pocket  Emulator. Standalone port of Mednafen NGP to the libretro API, itself a fork of Neopop.

Here:

https://github.com/RetroPie/RetroPie-Setup/wiki/Neo-Geo-Pocket
https://github.com/libretro/beetle-ngp-libretro

**Comment by clobber** [comment]
We already use Mednafen, so we could potentially switch to its NGP module some day.
