### ISSUE TITLE
M.A.M.E. Core: Dipswitch menu

### ISSUE THREAD

**Issue by Janichsan** [OpenEmu/OpenEmu#2587]
Stand-alone M.A.M.E. allows setting a game's dip switches via the on-screen menu. For many older games, this is the only way to set certain game options (e.g. difficulty, credits per coin, control options). A way to access this menu in OpenEmu would be appreciated.

**Comment by clobber** [comment]
#1860

**Comment by jeansebastienbg** [comment]
A workaround for that, if you have access to a PC, is to run the same ROM on MAME, access the Dip Switches menu pressing TAB while the game is running, set the switches and save that Machine Configuration. Then, you go to the cfg folder in your MAME pc version and copy the game's cfg file to the same folder in openemu *USER\Libray\Application Support\OpenEmu\MAME\Cfg . I switched a couple games to a four player mode that way.
