### ISSUE TITLE
Disable Auto Save States

### ISSUE THREAD

**Issue by pqhf5kd** [OpenEmu/OpenEmu#2589]
Is there an option to disable auto save states?

**Comment by clobber** [comment]
OpenEmu > Preferences > Library and click the 'Reset Warnings' button

Load a game and make sure to tick the 'Do not ask me again' checkbox and click 'No' if it asks you to 'Continue your last game'.

**Comment by pqhf5kd** [comment]
That doesn't disable the auto saves, plus I would like to 'Continue your last game' message to pop up if I manually created a saved state.

**Comment by clobber** [comment]
Yes, it does disable autosave states from being reloaded at launch. The "continue your last game" option is only related to autosaves, so you may have a misunderstanding as to how these work.

**Comment by udance4ever** [comment]
@clobber I feel disabling auto save states in a valid feature request.

While I realize it's a convenience for others, I do not need to be overwhelmed by the number of auto save states in the `Save States` tab.  I want this tab only to contain a very **small** number of save states of the games I'm currently working on.  The large majority of auto save states is clutter (I am constantly deleting them which gets old fast) and unnecessary.

Please consider reopening this issue.
