### ISSUE TITLE
OpenEmu crashes after removal of joystick

### ISSUE THREAD

**Issue by bartgrantham** [OpenEmu/OpenEmu#2592]
I have a PS3 Sixaxis joystick that is currently not connected to my machine, but it was the last controller I used with OpenEmu.  Now I have a new controller attached (8bitdo NES30 Pro), and OpenEmu starts to UI but no emulation can run.  Worse, _I can't open the Preferences to tell OpenEmu to ignore the SixAxis and use the other controller instead_.

Is there a plain-text config where I could erase the SixAxis reference?  In the absence of that I'm going to try having both joysticks attached so that I can switch.

Top few lines of crash log:

```
Application Specific Information:
Performing @selector(showPreferencesWindow:) from sender NSMenuItem 0x7f9cf253e160
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unknown control value for identifier: 'OEControllerSonyPS3SixaxisButtonHome' associated with key name: 'OE5200ButtonReset''
terminating with uncaught exception of type NSException
abort() called
```

**Comment by bartgrantham** [comment]
Reattaching the SixAxis did not help.  Neither did blowing away ~/Library/Preferences/org.openemu.OpenEmu.LSSharedFileList.plist and ~/Library/Preferences/org.openemu.OpenEmu.plist.

More info: unlike the other similar reported bug, I am using an OEM SixAxis.  I've attached the HIDExplorer properties export for both the SixAxis and the NES30 Pro.

[8Bitdo NES30 Pro.plist.zip](https://github.com/OpenEmu/OpenEmu/files/326795/8Bitdo.NES30.Pro.plist.zip)
[PLAYSTATION(R)3 Controller.plist.zip](https://github.com/OpenEmu/OpenEmu/files/326794/PLAYSTATION.R.3.Controller.plist.zip)

**Comment by mrvacbob** [comment]
Could you attach the entire crash log?

Deleting this file might fix it:
~/Library/Application\ Support/OpenEmu/Bindings\ Configurations/Default.oebindings

**Comment by bartgrantham** [comment]
Deleting ~/Library/Application Support/OpenEmu/Bindings Configurations/Default.oebindings did not fix it.  It got me farther, though.  I could open the Preferences, but when I hit the "controls" icon it crashed.  Here's the full crash log.

[OpenEmu-crash.txt](https://github.com/OpenEmu/OpenEmu/files/326801/OpenEmu-crash.txt)

**Comment by clobber** [comment]
Try ~/Library/Application Support/OpenEmu/Bindings/Default.oebindings instead, not 'Bindings Configurations', since the folder location changed in 2.0

**Comment by bartgrantham** [comment]
That did not make a difference, but disconnecting (bluetooth) the NES30 Pro did.  Reconnected the NES30 Pro (bluetooth) and it's crashing again.  However, if I connect it via USB it works, which is progress.  I am deleting the Bindings/Default.oebindings prior to each attempt.

AFAICT, this appears to be an incompatibility with this controller over bluetooth.  I am running the newest firmware on the NES30 Pro (v1.69), which is supposed to work perfectly (and does work perfectly in other applications).

**Comment by ZeroT3K** [comment]
Running into this issue as well running v2.00 firmware in Mode 1 on the controller. See attached crash log.


[OpenEmu_2017-04-05-152728.txt](https://github.com/OpenEmu/OpenEmu/files/900602/OpenEmu_2017-04-05-152728.txt)

**Comment by clobber** [comment]
This crash can no longer happen as of OpenEmu 2.0.7.

For the record: 8bitdo devices should be using the [latest firmware](http://support.8bitdo.com/) powered on with START and **not** START+A - do not use that mode as it attempts to mimic a Dualshock 4 and incorrectly at that.
