### ISSUE TITLE
Having troubles with loading games

### ISSUE THREAD

**Issue by Dawnll** [OpenEmu/OpenEmu#2593]
Hi I am having trouble with playing a game. I would request assistance to resolve this issue. I just downloaded a game, I used the unarchiver to unzip the file, clicked on the game folder, and this is what I got (see attachment).
![screen shot 2016-06-23 at 7 33 16 am](https://cloud.githubusercontent.com/assets/20109083/16301697/c85317b0-3914-11e6-9eb3-ef49f5fc874b.png)

**Comment by msikma** [comment]
The game is still compressed. You need to find the `psy-mgspw.rar` file and extract that too.

**Comment by clobber** [comment]
Spit rar's, not an OpenEmu issue. @Dawnll see this comment for a solution: https://github.com/OpenEmu/OpenEmu/issues/2507#issuecomment-213666458
