### ISSUE TITLE
Every time I click on something, OpenEmu Loads forever

### ISSUE THREAD

**Issue by yandrewy0** [OpenEmu/OpenEmu#2594]
Every time I try to open a game or click on another game system, the spinning loading wheel spins and doest stop. I waited for hours, but it didn't respond. I had to force quit from the app. How to I stop the wheel from spinning? It keeps on loading, preventing me from playing the games.

**Comment by clobber** [comment]
Which version of OpenEmu?

**Comment by yandrewy0** [comment]
version 2.0.1

**Comment by robotoad** [comment]
Is this issue still occurring with version 2.0.2?

**Comment by clobber** [comment]
Closing for lack of info.
