### ISSUE TITLE
SNES emulation uneven and jerky.

### ISSUE THREAD

**Issue by forzaroo** [OpenEmu/OpenEmu#2596]
I've tried running my ROMs through both snes9x and Higan cores, but it hasn't made a difference. Ever since the upgrade to El Capitan (and hence, the update to OpenEmu 2.0.1), gameplay has lacked the smoothness that was in preceding versions.

My Mac is a late-2011 13 MacBook pro w/ 6GB of RAM and a 512GB SSD.

**Comment by clobber** [comment]
There wasn't a change in OpenEmu v2 that should have negatively impacted video performance compared to v1. Do you have any programs running such as f.lux and/or have you tried setting the filter in OpenEmu to Nearest Neighbor?

**Comment by forzaroo** [comment]
It seems to be helping. Thanks! :D I'll play through a few games to make sure.

**Comment by clobber** [comment]
Okay, great.

The GPU in your machine (Intel HD 3000) can't handle all of the filters/shaders, so best to stick with Nearest Neighbor or Pixellate.
