### ISSUE TITLE
Trouble running Densha de Go n64 on OpenEmu - Black Screen, No Sound

### ISSUE THREAD

**Issue by bauhausfanatic** [OpenEmu/OpenEmu#2597]
Thanks for stopping by.

I am trying to run Densha de Go on OpenEmu, but I am unable to get past a black screen without any sound. I am running an updated Mac, and just downloaded the application today so it should be up to date.
Any suggestions?

OpenEmu 2.0.1 is currently the newest version available.
OSX EL CAPITIAN. Version 10.11.15

**Comment by clobber** [comment]
This game appears incompatible with Mupen64Plus and the Rice GPU plugin. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
