### ISSUE TITLE
Do not associate RAR and 7z files with OpenEMU by default

### ISSUE THREAD

**Issue by ben174** [OpenEmu/OpenEmu#2598]
RAR and 7z files are incredibly common and in normal use it's incredibly uncommon for those to be a rom which OpenEMU supports. It seems presumptuous to have OpenEmu grab associations of all these files by default.

**Comment by joshbgosh10592** [comment]
I'd also like OpenEmu to not associate rar and 7z files to it, as I am constantly using tar files that have nothing to do with ROMs.
