### ISSUE TITLE
Dualshock 3 Analog Stick bug

### ISSUE THREAD

**Issue by Bdkrpg7** [OpenEmu/OpenEmu#2601]
Whenever I move my Analog stick down, OpenEmu registers it as the stick moving up. This is a problem with many games, including PSX and N64 games. It is really annoying as I can't find a way to fix that.

**Comment by clobber** [comment]
Which version of OpenEmu?

**Comment by clobber** [comment]
Looks like #2505

Please search before opening a new issue.

**Comment by Bdkrpg7** [comment]
Silly me, I forgot to update.
