### ISSUE TITLE
Bowser's Inside Story Crash 

### ISSUE THREAD

**Issue by FierySeas** [OpenEmu/OpenEmu#2602]
I've been playing through "Bowser's Inside Story" rom, but the game crashes at the beginning Midbus fight, when previous fights provided no problems. I researched this subject and found that switching  Synchronous to Dual SPU Synch/Async. in sound settings will fix it, but the settings were in DeSsuMe, which I believe is the core that OpenEmu uses for the emulator of the game. I'm new to the OpenEmu program, so I'm not entirely sure where the settings are or if they even exist. Someone said just to use the "standalone port of desmume since it has the JIT dynarec *off* by default. as well as options for game hacks."

**Comment by clobber** [comment]
Right, as discussed on IRC you should do exactly that: use the standalone version of Desmume. We don't have per-core settings right now, maybe some day.

**Comment by AnthonyCastillo24** [comment]
My bowser inside story keeps freezing on the first boss battle, how do I fix this?

**Comment by ericrileyjackson** [comment]
Here's my solution. I installed a walk through walls cheat to skip this portion of the game.
Here it is.
923398a0 00000003+94000130 000001df+d9000000 02336558+d4000000 fffffe00+d6000000 02336558+d2000000 00000000+923398a0 00000003+94000130 000001ef+d9000000 02336558+d4000000 00000200+d6000000 02336558+d2000000 00000000+923398a0 00000003+94000130 000001bf+d9000000 02336560+d4000000 fffffe00+d6000000 02336560+d2000000 00000000+923398a0 00000003+94000130 0000017f+d9000000 02336560+d4000000 00000200+d6000000 02336560+d2000000 00000000

Plug that in and hold L to walk through walls and skip that section.
