### ISSUE TITLE
Transfer of save datas

### ISSUE THREAD

**Issue by defining** [OpenEmu/OpenEmu#2603]
Hi,

I've played a disc (Sony Playstation) then I've had the probleme with the multiple disc. I've done the .m3u file to play with multiple disc but I did not manage how to recover the "memory card" from the game when I have played solo. I did not find the right way to recover it. And when I would like to copy the save state of the machine (which is different from the "memory card" of the Sony Playstation!), it is impossible to copy the .oaevstate file in the right folder (it is automatically deleted and replaced in the origin folder..)

Is there any solution to not start from the begining the game?

**Comment by defining** [comment]
If you have the solution, please be clear because the "Loading" parts of the guides does not work :(

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2489#issuecomment-213987713

**Comment by defining** [comment]
I thought it was an openemu issue since the "Loading part" does not work..
