### ISSUE TITLE
ROMS not loading El Capitan 

### ISSUE THREAD

**Issue by newdusk00** [OpenEmu/OpenEmu#2604]
Using OPENEMU experimental v.2.02, MAC OSX El Capitan 10.11.5

I tried the fix through the terminal and renaming the folder in the Library. Does anyone else have this problem and have a solution.

**Comment by clobber** [comment]
>I tried the fix through the terminal and renaming the folder in the Library


Please provide exact details, because this is probably related to a certain game/system.

**Comment by aheckmann** [comment]
N64 worked for a bit, now it freezes. 
OpenEmu gets confused and will not respect pressing the red "power button", instead, the game will play for a second, then freeze. Force quitting is required to exit a game.
Restarting my MacBook Air does not help.
Downgrade seems best for me for now - what's the best way to do so without losing game progress?

**Comment by aheckmann** [comment]
I'll open a new ticket since my issue sound separate.

**Comment by newdusk00** [comment]
Hi Clobber, this issue is for ROMS that I already have downloaded, I am trying to drag and drop from my old OpenEMU ROMS folder to the new OpenEMU Build.

I did a test download of some NES ROMS and they loaded just fine. I'm not sure what the issue but for now I have a workaround.

**Comment by clobber** [comment]
@newdusk00 Okay, it's still unclear to me what you did to get that point - perhaps something you did on your end - but sounds like you have it sorted now.
