### ISSUE TITLE
N64 Problems

### ISSUE THREAD

**Issue by MichaelRampage** [OpenEmu/OpenEmu#2607]
Ever since OpenEmu 2.0.2 I've experienced new glitches within the N64 games that weren't there before. The console also refuses to quit emulation and I need to force quit to exit. Also, the console sometimes has problems recognizing my dualshock 4, which wasn't a problem before. Anyone else experiencing problems with other consoles? I don't know if this is an N64 exclusive problem. Almost feel like I shouldn't of upgraded versions. :(

**Comment by clobber** [comment]
Please search before opening a new issue. #2606 is exactly like yours.

**Comment by MichaelRampage** [comment]
I did, and the posts aren't "exactly" the same. But that's fine, it doesn't seem you are able to remedy the problem regardless.
