### ISSUE TITLE
OpenEmu 2.0.2 - Save States not working in Arcade

### ISSUE THREAD

**Issue by igarikoitz** [OpenEmu/OpenEmu#2609]
Every time I finish playing an arcade game, OpenEmu automatically saves state. When I go to the Save State section and I try to load the saved game, the screen goes black and the application no respond.

**Comment by clobber** [comment]
Using which gamepad?

**Comment by clobber** [comment]
Forgot to mention - some Arcade games/systems in MAME don't save states properly, and aren't really supported.

**Comment by clobber** [comment]
Closing due to that and the 'experimental' status of MAME support.

**Comment by clobber** [comment]
This was a duplicate of #2615 and has been fixed.
