### ISSUE TITLE
Black screen on DS pokemon soul silver

### ISSUE THREAD

**Issue by Charlesyoshi** [OpenEmu/OpenEmu#2612]
![capture d ecran 2016-07-04 a 18 30 49](https://cloud.githubusercontent.com/assets/20286074/16566516/80112b04-4215-11e6-827a-29fd92c1fcaa.png)
Hello i got a problem with openemu. When i start my game the up screen be black, but just the background. The down screen have no problem i dont understand... Can you help me please ?

**Comment by clobber** [comment]
Search next time as this has come up several times.

In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
