### ISSUE TITLE
Sound Glitches with PPSSPP core

### ISSUE THREAD

**Issue by thibo1138** [OpenEmu/OpenEmu#2613]
Hello 

I tried different psp games on openemu and each time there is a lot of sound glitches during game
the worst was with musical games where the song became distorted 

I tried it on PPSSPP 1.1.1 directly and there i found less glitches (there was some but less)
after some test I found deactivating audio resampling decrease the quantity of audio glitches a lot too 

Is the problem known?

I hope it can help
(and sorry for my approximate english)

**Comment by clobber** [comment]
Our core port is PPSSPP 1.2.2 and should perform about the same as PPSSPP standalone with the default settings. Nothing we can really do here; their resampler is supposedly not very performant and PPSSPP can be very CPU intensive.

**Comment by thibo1138** [comment]
I Do not agree the CPU aren't overloaded by openemu during emulation (i checked) and there is still glitches during the check
So for me it's something else and openemu is currently doing worse than ppsspp (with high res settings)

that's why i  think there is a problem

**Comment by clobber** [comment]
I don't agree you are doing a fair comparison.

Compare the same game and same version of our PPSSPP 1.2.2 to PPSSPP 1.2.2 standalone with default settings. You're welcome to look over our settings and implementation here: https://github.com/OpenEmu/PPSSPP-Core/blob/71b876e73d212732bf01ebed12f7ad98743f01f6/PPSSPPGameCore.mm

Also, in OpenEmu ensure you are running the game using the Nearest Neighbor filter.

**Comment by clobber** [comment]
#1036
