### ISSUE TITLE
PowerEmu.icn question and Vertical mode for WonderSwan ?

### ISSUE THREAD

**Issue by azoreseuropa** [OpenEmu/OpenEmu#2614]
1st: I can't do the Vertical mode for Klonoa Moonlight Museum. I tried Display Mode and use spacebar but nothing's happening at all. Help ? 

2nd: Can I change PowerEmu.icn to my favorite icn file ?

**Comment by clobber** [comment]
1) We still need rotation support and are tracking that in another issue.

2) No idea - I guess that's up to you.

**Comment by azoreseuropa** [comment]
1. What another issue ? Can I see it ?

2. Alright, thanks.

**Comment by azoreseuropa** [comment]
Hello ? I am asking the number 1 question, please ?
