### ISSUE TITLE
Ability to filter roms to only see ones with a cover art image.

### ISSUE THREAD

**Issue by Gerst20051** [OpenEmu/OpenEmu#2616]
I would love to have the ability to filter the roms to only see ones with a cover art image. Can anyone point me in the right direction.

**Comment by Gerst20051** [comment]
Also requested by @diotro in https://github.com/OpenEmu/OpenEmu/issues/2270

**Comment by clobber** [comment]
Don't need another issue open for this, probably not something we'll add right now.

**Comment by Gerst20051** [comment]
@clobber What I meant by "point me in the right direction" is that I was hoping you could tell me what file(s) you would add this feature so that I can implement it myself.
