### ISSUE TITLE
Ability to purge roms that reference a rom that no longer exists.

### ISSUE THREAD

**Issue by Gerst20051** [OpenEmu/OpenEmu#2617]
I would love the ability to purge roms that reference a rom that no longer exists. Can anyone point me in the right direction.

**Comment by clobber** [comment]
> Can anyone point me in the right direction.

You can try debug prefs (info in the wiki) to do a database check. Probably won't be adding a feature to automatically do this, though.

**Comment by Gerst20051** [comment]
Thanks!
