### ISSUE TITLE
N64 not working at all for 2.0.2

### ISSUE THREAD

**Issue by hullstar242** [OpenEmu/OpenEmu#2619]
All of the games I had that worked on 2.0.1 and the build I compiled in between .1 and .2 that fixed the N64 speed up problem no longer work on 2.0.2.  The game opens into the window but it's just black and I have to force quit the app to exit.  I hope there is a small fix because I would really like to play these games but if I revert back to 2.0.1 I'll revert back to N64 speed ups.  Thanks :)

**Comment by clobber** [comment]
To resolve:

* OpenEmu > Preferences > Library and click the 'Reset Warnings' button

* Load the game and make sure to click 'No' if it asks you to 'Continue your last game'.

**Comment by hullstar242** [comment]
Is their anyway I can make it only ask me for MAME and have it pick up where i left off for other cores?  If not is that a possible feature that could be added?

**Comment by clobber** [comment]
Nope and probably not. Keep in mind Arcade/MAME is 'experimental' and officially unsupported.
