### ISSUE TITLE
OpenEmu freezes PSP game

### ISSUE THREAD

**Issue by dropedrops** [OpenEmu/OpenEmu#2621]
Hello, clobber!

Today I was playing PSP's Lunar: Silver Star Harmony on OpenEmu, but the game freezes right at the first battle. I know that OpenEmu just uses PPSSPP's core, but I tried it on PPSSPP latest version (1.2.2) directly and the game worked fine in default settings, without any freezes.

As the OpenEmu and PPSSPP standalone uses the same core, why the game just freezes on the OpenEmu? I've tried the Lunar's USA and Japan Version, but the outcome was the same. 

Could you help me or try this game on your mac? :)
Thanks.

**Comment by clobber** [comment]
Suffered through JRPG exposition, but I could replicate the crash. I cannot compare it to PPSSPP 1.2.2 standalone, because there is no build available for OS X.

My guess is this is just a regression in PPSSPP 1.2.2 - these happen a lot.

**Comment by unknownbrackets** [comment]
It should be pretty easy to build PPSSPP from git if you want to test v1.2.2 (assuming you have Xcode.)

By the way, I noticed you have an old fbo.cpp:
https://github.com/OpenEmu/PPSSPP-Core/blob/71b876e73d212732bf01ebed12f7ad98743f01f6/gfx_es2/fbo.cpp

It may be worth noting that we've stopped using an external fbo.cpp, and are now using GPU/GLES/FBO.cpp.  If that fbo.cpp override is important in some way, it could be related to the crash.

-[Unknown]

**Comment by clobber** [comment]
Haven't looked at it in a while but pretty sure our fbo.cpp is just about the same as the one upstream in 1.2.2.

**Comment by clobber** [comment]
cc: @duckey77 on this. You last updated the PPSSPP core plugin, can you check if our fbo implementation matches up with upstreams?

**Comment by duckey77** [comment]
I will take a look; however, my macbook died so it may take me a little bit.

**Comment by clobber** [comment]
Recording duckey77's findings so far:

* In the OpenEmu PPSSPP core plugin, both regions of the game terminate on line `glDrawArrays(glprim[prim], 0, vertexCount)`; in `TransformDrawEngine::DoFlush()`.
* Using the same game, cannot replicate the crash in PPSSPP 1.2.2 standalone using same settings as our core plugin, including SAS and IO on separate threads and CPU/GPU on one thread -- but that doesn't completely rule out us missing a setting or implementation problem.
* Appears unrelated to the use of GLEW in PPSSPP standalone and our modifications to fbo.cpp, which simply serves to work around OpenGL limitations in OS X and set the OpenEmu fbo as the render fbo.
* Moved the GLES/FBO.cpp and FBO.h code into the OpenEmu core plugin fbo.cpp and fbo.h, making them essentially the same now -- still crashes.
* Looked through the fbo.cpp to see if missing a bindframebuffer that is going to 0 and not our define framebuffer.

The issue could possibly be in the frontend? https://github.com/OpenEmu/OpenEmu/blob/master/OpenEmu/OEOpenGL2GameRenderer.m

**Comment by unknownbrackets** [comment]
Do you use VAOs/VBOs?  We currently only support the compatibility profile (limited to OpenGL 2 on Mac typically), although there's been some work on using a core profile - hrydgard/ppsspp#8277.

Otherwise it seems like the main reason glDrawArrays would crash is if there are enabled vertex arrays that PPSSPP doesn't expect.

-[Unknown]

**Comment by clobber** [comment]
No VAO/VBO's for our OGL2.1 renderer. We have a GL 3.2+ core profile renderer available, but it's not being used with the PPSSPP core plugin here.

**Comment by mrvacbob** [comment]
It might be worth trying removing the glPopAttrib / glPushAttrib calls. Thinking about it, those should be around OE's rendering code, not the core's. They could be corrupting the core's expected GL state by resetting it every frame.

**Comment by mrvacbob** [comment]
But there should be no VAO set. Only a 2D core would use that.

**Comment by clobber** [comment]
Yep that fixed it. I removed the glPopAttrib / glPushAttrib calls in -willExecuteFrame and -didExecuteFrame and now we're good to go. Thanks!

**Comment by clobber** [comment]
Sorry, I take that back. If I try to attack in that first battle, then the game freezes. :(

**Comment by mrvacbob** [comment]
I mean, it probably still needs them, just not there :/

**Comment by clobber** [comment]
Doh okay, someone is going to have to take a look later then. Here's the crash log with the calls removed, at least:

https://gist.github.com/anonymous/e41aaba0fdd90a8605ff978ef77dc1dd

**Comment by mrvacbob** [comment]
This looks like a PPSSPP bug. CheckGLExtensions() is never called so it doesn't set up VAOs, etc, even though they're in GL2.1 here. So that's probably going down an untested path or something.

Also there's a crash with AddressSanitizer on + vertex decoder JIT that I can't debug since... it's in the JIT.

Anyway, it works if we call CheckGLExtensions() and it uses VAOs. And it's faster!

**Comment by mrvacbob** [comment]
Oh it doesn't use VAOs, that was me hacking it.

The actual problem seemed to be memory corruption caused by allocing too small a sound buffer.

**Comment by clobber** [comment]
Update is live. Restart the app and an updated PPSSPP core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for PPSSPP 1.2.2.1.
