### ISSUE TITLE
Game that runs on DeSmuMe won't open on OpenEmu

### ISSUE THREAD

**Issue by McBeckon** [OpenEmu/OpenEmu#2623]
I'm trying to play a ROM hack of Pokemon Platinum called Pokemon Platinum NTEVO. I can open and run the game just fine on DeSmuMe, but when I try to open it on OpenEmu I get a message saying "Couldn't communicate with a helper application." I know OpenEmu uses DeSmuMe for its DS core, so I feel like there should be an easy fix for this. I would love to be able to keep all my emulation together in OpenEmu and not have to switch back and forth between apps. Thanks!

**Comment by clobber** [comment]
Sounds like a Desmume issue with the JIT dynarec enabled. You will have to use Desmume standalone which has the JIT dynarec off by default which may improve compatibility.
