### ISSUE TITLE
Dandy(NES) Game Controller Turbo A/B Buttons is missing.

### ISSUE THREAD

**Issue by JulyIGHOR** [OpenEmu/OpenEmu#2625]
Hello. I have just tried OpenEmu and I want to say it best app for emulator games.
Any way I have found missing Turbo A/B buttons in Nintendo(NES) emulator.
I know developers ignoring it and don't want to add and they think it not supposed to be there, but I'm going to explain why it should be added.

Everyone know Nintendo(NES) that was very popular in USA.
But no one could buy it in Europe that time, so Chinese vendors started to create copy of device with support of its cartridges.
Devices looks different, each vendor added many labels and different sizes, but most popular "copy" of Nintendo was "Dendy".
Any almost all copies of Chinese devices had Game controller with additional Turbo A and Turbo B buttons.
It just hardware addition that was constantly repeat pressing of A or B buttons while you hold Turbo A or Turbo B.
You can find how it looks like here https://google.com/search?q=dendy+game+gamepad by switching to Images mode.
I'm sure there is millions of users who played games via pirated copies of device, and they use Nestopia, Nester, Fceux UI etc emulators on Windows, each of them supports of "Turbo A" and "Turbo B" buttons, but not OpenEMU, they just don't know about OpenEMU yet.

Look at my gameplay https://www.youtube.com/playlist?list=PL2Gch16j761FFu_ytGTkYROhU0tDogl77 
It would be not possible to play like this without Turbo A and Turbo B buttons.
I know developers may don't understand me because in original Nintendo there was no Turbo buttons.
But it not means it not supposed to be there. Many of gamers will be happy to play old games exactly like they played it many years ago, but without Turbo buttons it become awful feeling.

I hope developers will add Turbo buttons to Nintendo in future, or add new game console "Dandy" with different game controller that have Turbo buttons.

**Comment by clobber** [comment]
Probably not adding these. #2535

**Comment by JulyIGHOR** [comment]
Than please add feature to set multiple keys as single button.

**Comment by clobber** [comment]
Sorry, not adding that either as it would really complicate the way we currently handle input assignment.
