### ISSUE TITLE
Distorted noise accompanying the audio for some GBA games

### ISSUE THREAD

**Issue by hullstar242** [OpenEmu/OpenEmu#2626]
The one that I experienced was Beyblade V Fusion.  Im not sure if this is a problem with anyone else.  Im using the most current version 2.0.2 with visualboyadvance as that has my saves.  Is it just the game?

**Comment by clobber** [comment]
We don't develop the emulators. Could be:

* How the game was
* VisualBoyAdvance emulator bug

Try using the mGBA core plugin instead.

**Comment by clobber** [comment]
Yes, unless you open a game while restoring an autosave, which it will then switch to the correct core plugin associated with that save. Opening save states while in-game will also automatically switch it to the correct core.

**Comment by clobber** [comment]
For reference, the audio problem is a timing-related emulation bug. When it's fixed in a future mGBA release I will post an update here.
