### ISSUE TITLE
Opening Vectrex games results in a blank screen

### ISSUE THREAD

**Issue by TuxOtaku** [OpenEmu/OpenEmu#2628]
Vectrex ROMs don't seem to play properly. Whenever I start one, the screen just stays blank, and I have to Force Quit OpenEmu.

**Comment by clobber** [comment]
Have an example? I just loaded Pole Position (1982).vec (MD5 = f94173910549038d4d8f329413a5aa54), so maybe you have a bad dump?

**Comment by TuxOtaku** [comment]
I have that exact same ROM in my collection (verified the MD5 vs. the one you posted). Still just loads a black screen. OpenEMU UI controls all function normally, but the game won't stop when I hit the power button on the pop up menu.

**Comment by clobber** [comment]
> Could this be an issue with the Emulator itself?

Doubt it.

Anything in Console? Tried switching Filters to Nearest Neighbor? Do games load for other systems? Computer need a restart or is some weird permission issue blocking the OpenEmuHelperApp process from running?

**Comment by TuxOtaku** [comment]
This is what I get back from running in a terminal:

`2016-07-08 20:45:50.090 OpenEmu[36562:4768633] Error loading /Users/ryandraga/Library/Application Support/OpenEmu/Cores/VecXGL.oecoreplugin/Contents/MacOS/VecXGL:  dlopen(/Users/ryandraga/Library/Application Support/OpenEmu/Cores/VecXGL.oecoreplugin/Contents/MacOS/VecXGL, 265): Symbol not found: _OBJC_IVAR_$_OEGameCore.isRunning
  Referenced from: /Users/ryandraga/Library/Application Support/OpenEmu/Cores/VecXGL.oecoreplugin/Contents/MacOS/VecXGL
  Expected in: /Applications/OpenEmu.app/Contents/MacOS/./../Frameworks/OpenEmuBase.framework/Versions/A/OpenEmuBase
 in /Users/ryandraga/Library/Application Support/OpenEmu/Cores/VecXGL.oecoreplugin/Contents/MacOS/VecXGL
2016-07-08 20:45:50.250 OpenEmu[36562:4768633] SETUP DONE.
2016-07-08 20:45:50.310 OpenEmu[36562:4768633] failed to make complete framebuffer object 8cd6
2016-07-08 20:45:50.344 OpenEmu[36562:4768633] Display's nominal refresh rate is 60.14 Hz`

**Comment by clobber** [comment]
Ah, I see. There was an API change and an update for VecXGL hadn't been pushed.

This has now been corrected. Restart the app and an updated VecXGL core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for VecXGL 1.2.2. Thanks for reporting.
