### ISSUE TITLE
Retrolink SNES USB Adapter problem

### ISSUE THREAD

**Issue by veke** [OpenEmu/OpenEmu#2630]
I have exactly same problem. Any ideas?
https://www.reddit.com/r/OpenEmu/comments/4gwtwd/unable_to_use_retrolink_snes_adapter/

USB Adapter:
http://www.innexinc.com/product-detail.php?prod_id=RB-PC-1114
or https://www.amazon.com/Retro-Link-SNES-Controller-Adapter-Dual/dp/B00BYH9Q4Y

Some machine details:
MacBook Pro (15-inch, Early 2011)
OS X 10.11.5
OpenEmu 2.0.2 (535-gc11c17e-Release)

**Comment by teroqim** [comment]
Still having this problem @veke?

I experienced this issue on OpenEmu 2.0.3. Plugged a controller into the player 1 port on the retrolink (with no controller in the player 2 port) and could map each button, but no response when entering a game. I tried removing the controller from the retrolink and plugging it into the player 2 port and.... it worked!
I don't have 2 SNES controllers so couldn't experiment a lot, but it seems I can map the controller in OpenEmu from each port on the retrolink, but when in a game only the player 2 port responds.

**Comment by toromei** [comment]
This is so stupid it might just work for you. After fiddling with this for hours of frustration, I was able to get it working simply by unplugging the adapter from my Mac's USB port and plug it back in. Seriously, I think we might just be trying to outsmart OpenEMU by manually configuring the controllers right off the bat. After reconnecting only the USB plug, both controllers worked flawlessly with no setup. I hope this works for others too! :)

**Comment by teroqim** [comment]
I've noticed that as well! It usually works if you unplug+plug back once or twice. Sometimes I need to switch to another USB port.

**Comment by clobber** [comment]
Issues using adapters should be resolved as of OpenEmu 2.2.
