### ISSUE TITLE
How to change speed up speed?

### ISSUE THREAD

**Issue by megamazeman** [OpenEmu/OpenEmu#2632]
I've been looking around the web for a little bit but I haven't found anything to help. I've been playing some DS games and the speed up button isn't speeding it up all that much, so I was wondering if there was any way to speed up the emulator by x5, or x10 instead of x2.

Thanks!

**Comment by clobber** [comment]
It is not adjustable, and should be 5x by default.

**Comment by Reverendhero** [comment]
Mine only seems to be 2-3x

**Comment by Reverendhero** [comment]
And when I put it in fullscreen or any bigger than the smallest window size it doesn't allow me to fast forward
