### ISSUE TITLE
[feature request] Allow Png Images with Transparent Backgrounds for Cover Art

### ISSUE THREAD

**Issue by hullstar242** [OpenEmu/OpenEmu#2633]
for instance: I wanted to use these rom icons i found from http://scissorhands7.deviantart.com/art/SNES-Icons-Pack-V-1-0-137689551 but when i try and make it the cover, a white background is created under the image.  like this https://postimg.org/image/g6ryh7ppt/ Having a large library can sometimes be confusing if all of the artworks are close to the same shape.  It makes it a bit easier to distinguish consoles with these cool cartridge images.  I will be making my own for the consoles i cannot find.

**Comment by clobber** [comment]
Cool idea. When the grid view is rewritten to use the new NSCollectionView, this will just work but not before then.
