### ISSUE TITLE
Sega Saturn not working on my mac, black screen

### ISSUE THREAD

**Issue by andybrito** [OpenEmu/OpenEmu#2634]
I've played Sega Saturn on past versions of OpenEmu and it always worked well, the issue was only the controller glitch which made give up until the bug was fixes, which happened in the last version. 
Yesterday i was visiting a friend which uses the same OS and same OE versions and we were testing SS games, everything was working wonderfully in his Mac. 
For some reason unknown, since yesterday i am trying to play SS games but i am always getting a black screen for every game (i am using the same dumps as my friend), even tried reinstall OE completely, everything from scratch and only 1 SS game added, same thing. 
The whole thing seems to be related with something outside OE, something in my OS, IDK. 

Need guidance from the masters of OE. My mac is on 10.11.5

**Comment by azoreseuropa** [comment]
I have MAC. What game did you try ? I can test it for you.

**Comment by andybrito** [comment]
Thanks for your help, i've tried many games including Astal and Guardian Heroes, the thing is they are all running in my friend's mac, which is almost the same config, same OS etc. I would like someone to point me what could be the cause of black screens, i know the core doesn't need bios but i've tried to use too and while in retroarch i can see the bios startup and play the games, in openemu i am only getting a black screen with or without bios.
In previous versions of openemu i was running Saturn games, i did give up of play because of the controller glitch which was fixed recently and now the games are not working anymore. I am still trying to figure out what's wrong with my system.

**Comment by azoreseuropa** [comment]
I tested Astal and you are right. Its not playable either. Maybe this emulator is still mature. Rockman 8/Megaman 8 is playable, thought.

**Comment by clobber** [comment]
Saturn via Yabause is still experimental, low compatibility and unsupported.
