### ISSUE TITLE
Couldn’t communicate with a helper application on Sega Gensis/PSX

### ISSUE THREAD

**Issue by gogolox** [OpenEmu/OpenEmu#2635]
Hey all.  I've tried playing games on both systems and I always get "Couldn’t communicate with a helper application".  I've done different things like delete the cores and reinstall after restarting the computer and even used older versions of the Mednafen core, but nothing.  Any ideas on what I can do to help it? I'm running OS X 10.10.5 and am on OpenEmu 1.04.  Can't really update my mac because doing so will cause issues with projects I'm working on.  Thanks.

**Comment by clobber** [comment]
Sorry, 1.x is unsupported.
