### ISSUE TITLE
NDS Touchscreen Unresponsive with OpenEmu

### ISSUE THREAD

**Issue by demraldes** [OpenEmu/OpenEmu#2638]
I'm having a problem using the touchscreen with DeSmuMe via OpenEmu, where the touchscreen works fine when I use the DeSmuMe standalone but doesn't respond to input when I use OpenEmu.  The DeSmuMe standalone quite frankly sucks on my system and for whatever reason doesn't run as well as OpenEmu's emulation.

It would appear that the problem has something to do with touch controls being unassigned by default, since I had to map my mouse with DeSmuMe to get touch controls working in the standalone, yet there's no way for me to assign input to the touchscreen in OpenEmu.  Otherwise I'm pretty much baffled as to why I can use the touch controls with the standalone but not with OpenEmu, which uses DeSmuMe for DS emulation anyway.

This is a completely new install of OpenEmu; newest version installed on a 2011 MBP unibody with OSX 10.11.1

**Comment by clobber** [comment]
>The DeSmuMe standalone quite frankly sucks on my system and for whatever reason doesn't run as well as OpenEmu's emulation.

The OpenEmu core plugin has the Dynamic Recompiler enabled by default, which means it runs faster, especially on low end CPU's.

>yet there's no way for me to assign input to the touchscreen in OpenEmu

It is not necessary to assign mouse controls, it should Just Work with a trackpad or mouse.

>2011 MBP unibody with OSX 10.11.1 

You should probably update to the latest point release, which is 10.11.5.

I need more information about your problem.

* Is this only with certain games?
* Have an example game where the mouse does not work?
* Any more details about your setup you can provide, e.g. are you just using your trackpad or another mouse? With the trackpad, tap-to-click will not work - you must physically press the trackpad.
* Have any weird 3rd party input apps installed or running?
* Tried restarting your machine and just running OpenEmu with nothing else open?

**Comment by demraldes** [comment]
> Is this only with certain games? / Have an example game where the mouse does not work?

So far I've only tried Kirby Squeak Squad and Pkmn Black, neither of which worked with the click to touch controls.  Seems unlikely that it's a problem with the ROMs themselves since they work with the DeSmuMe on its own.

> Any more details about your setup you can provide

Tried using the trackpad and also a Logitech mouse.  Otherwise I'm using a Sony DualShock4 controller for input.

> Have any weird 3rd party input apps installed or running? / Tried restarting your machine and just running OpenEmu with nothing else open?

No, and I'll try a restart and see what happens.  I usually don't have anything else running with OpenEmu.

**Comment by clobber** [comment]
> Seems unlikely that it's a problem with the ROMs themselves since they work with the DeSmuMe on its own.

Some games have issues due to bugs with the Dynamic Recompiler, notably WarioWario: Touched, however the two you mentioned are not ones.

> Otherwise I'm using a Sony DualShock4 controller for input.

Ding ding ding, think we found the problem! I was able to replicate mouse input not working when a DualShock 4 is connected (paired or via usb). Now we will have to find out what changed in 2.0.2 to cause this.

**Comment by clobber** [comment]
Duplicating this with #2636
