### ISSUE TITLE
Intellivision Roms - Update (not working)

### ISSUE THREAD

**Issue by ZillaRush** [OpenEmu/OpenEmu#2640]
Hello!  Updated to the recent version of Open Emu v 2.0.2 and all game systems work except for Intellivision ROM's.   I just get a black screen for all roms.   Anything I can do to get them back up?   Thanks!

**Comment by clobber** [comment]
Thanks for reporting, I can replicate the issue.

It appears to have broke in commit https://github.com/OpenEmu/OpenEmu/commit/c5b3fa754292bc2576e6ffb69db7fc4f7b3d4e0c but it could now be a [Bliss-Core](https://github.com/OpenEmu/Bliss-Core/blob/master/BlissGameCore.mm) implementation bug.

**Comment by ZillaRush** [comment]
Thanks...love OpenEmu!   Play Intellivision all the time on it during my travels.   hope you can fix it soon.

**Comment by clobber** [comment]
There was an API change in 2.0.2 that exposed a bug in the Bliss implementation.

This has now been corrected. Restart the app and an updated Bliss core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for Bliss 2.1.2. Thanks for reporting.
