### ISSUE TITLE
OpenEmu.app is not registered to Apple, does not support GateKeeper

### ISSUE THREAD

**Issue by nekoniaow** [OpenEmu/OpenEmu#2643]
Upon launching the app, one immediately gets the following message:

“OpenEmu.app” can’t be opened because it is from an unidentified developer."

As you must know, the only way to open and use the app is then to explicitly instruct the system to open the app despite:
- it being not identified clearly being from the OpenEmu team
- having no guarantees that the app will be removed if any malware is associated with it

Registration has been made free for quite some time now so there are very few reasons why the OpenEmu team would not pursue it. This would give additional guarantees to users that the app is going to be well behaved and has not been tampered by any malware (or at least if it was, that it will be disabled).

Cf Apple's own docs:
https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

**Comment by clobber** [comment]
Yes, we are well aware that our app is not code signed. Please search before opening a new issue. 

And no, it is not "free" -- to code sign a Mac app, one requires a Developer Certificate from the Mac Developer Program, in which one must be enrolled (annual fee of 99 USD).

#816

**Comment by nekoniaow** [comment]
I did search for "certified" and "registered", none of which returned any useful result, in hindsight I should probably have searched for "Gatekeeper". My apologies for being human.

About the fee I guess that is another mistake of mine. I recalled reading that policy having changed but after checking on Apple's site you are indeed right.
Once again, my apologies.
