### ISSUE TITLE
I am lost on how to enable High resolution texture packs

### ISSUE THREAD

**Issue by Nanito559** [OpenEmu/OpenEmu#2644]
Hi, i am new to coding and I've been trying to add high resolution texture packs to my "The Legend of Zelda: Ocarina of Time". I tried to follow the instructions set up but i don't know where to find the config giles. Please get back to me

**Comment by mrvacbob** [comment]
Either:
~/Library/Application Support/OpenEmu/Mupen64Plus/

or ~/.rice/ or wherever it would put it on Linux.

We don't consider N64 stable enough to work on extra features like this yet.

**Comment by Nanito559** [comment]
I am on the mac though so i am still lost. So there is no way to access mupen64plus on the OpenEmu? I thought Openemu mupen64 runs a rice plugin?

**Comment by mrvacbob** [comment]
I promise I just answered your question.
