### ISSUE TITLE
How do I remove a cheat from openemu

### ISSUE THREAD

**Issue by lede1243** [OpenEmu/OpenEmu#2645]
How do I remove a cheat from ocarina of time openemu? I turned the game off and back on, closed the software, but the cheat is still in effect although it's not in the cheat box in settings. I need to keep the memory, but take away the cheat. Please help

**Comment by clobber** [comment]
This is not yet possible. You could only have disabled it when you originally added it, by clicking the menu item for it.

**Comment by clobber** [comment]
Also, known issue. Please search before opening one. #782
