### ISSUE TITLE
Upgraded version Open EMU 2.0.2v too many issues

### ISSUE THREAD

**Issue by ratedsc** [OpenEmu/OpenEmu#2646]
At first my n64 emulator no longer worked so I upgraded to 2.0.2 and problem solved. Also Golden Eye and Banjo Kazooie works perfectly fine. But this brought up new issues.

- Powerbutton not functional. I have to Force Quit to close it out to play a new game.
- Unable to save any game clicking the disk logo. It used to on the previous version but not anymore.
-It will not continue where you left off. 

Thats about it for now. I've collected a few puzzle pieces on Banjo Kazooie however it didn't save when I went back to it.

**Comment by ratedsc** [comment]
Update: I discovered that it only does these issues to Nintendo 64 emulator. All other systems are working fine in regards to saving and continuing where I left off and clicking the Power Button to switch games. Only N64 has the issues.

**Comment by clobber** [comment]
Are you using a DualShock 4 gamepad?

**Comment by ratedsc** [comment]
Yes I'm using a PS4 controller. Thank you for responding. Is it related?

**Comment by clobber** [comment]
>Is it related? 

Yes. Please search before opening a new issue.

Dupe #2606
