### ISSUE TITLE
Pairing 2 ps4 controllers using open emu

### ISSUE THREAD

**Issue by danfred82** [OpenEmu/OpenEmu#2647]
Hi, I am currently using open emu perfectly with one ps4 controller. However, in trying to use a second controller it appears I cannot because it disconnects/ freaks out when I do so. Please if anyone else is doing this what did you have to do. Thanks in advance!All the Best!!

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu/commit/3032021828c473dbfdd444f04eb72da2bb6d5433 for next release.
