### ISSUE TITLE
OpenEMU not loading

### ISSUE THREAD

**Issue by adobson66** [OpenEmu/OpenEmu#2649]
I get a message that says "An error occurred during persistent store migration." whenever I try to open OpenEmu. It was working just a few minutes ago, I don't know what happened or why.
![screen shot 2016-07-16 at 9 25 34 pm](https://cloud.githubusercontent.com/assets/20496724/16898373/fc33fe6a-4b9c-11e6-836c-7baeffc599b0.png)

**Comment by clobber** [comment]
Which version of OpenEmu and OS X?

**Comment by adobson66** [comment]
Most recent version of OpenEmu. I am currently running OS X El Capitan Version 10.11.5

**Comment by clobber** [comment]
Any info in Console? If an automatic migration failed from a previous version, it is unlikely we can solve this for you. It may be best to delete your library and reimport all the games.

**Comment by adobson66** [comment]
I've tried that. I deleted everything, downloaded the latest version, and it still gives me this error message.

**Comment by adobson66** [comment]
are there any hidden files I'm perhaps missing when I delete the app? Some lingering presence of code that could be interfering?

**Comment by clobber** [comment]
Well there is the actual Game Library in Application Support.

Navigate to the folder `~/Library/Application Support/OpenEmu` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/).

You will want to rename the "Game Library" folder, relaunch the app and then reimport your games that you find in there.

**Comment by adobson66** [comment]
I deleted that folder along with the app. No such file or folder exists on my computer in that location.

**Comment by clobber** [comment]
You cannot still get the error if the Game Library is gone - it has nothing to migrate. Are you absolutely sure you went into the correct Application Support folder as per the article I linked? There are two of them: root and user home folder. You want the home folder location.

To delete left over preferences, you can run the following command in Terminal.app:
`defaults delete org.openemu.OpenEmu`

**Comment by adobson66** [comment]
the terminal prompt seems to have done it! Thank you very much!
