### ISSUE TITLE
Cannot compile with 4dO

### ISSUE THREAD

**Issue by scottdcrompton** [OpenEmu/OpenEmu#2651]
I cloned the repo locally and receive this error:

Subproject commit a8e3ef0dc8feef932cb336317ac3868378d07aeb under 4do.

I can compile with everything except 4DO.

**Comment by clobber** [comment]
That doesn't look like an error to me. Are you talking about a compile error or a problem cloning all the subprojects?

**Comment by scottdcrompton** [comment]
As soon as I clone from the repo (on several computers), I immediately see that 4DO is removed with an uncommitted change.

**Comment by clobber** [comment]
That submodule points to https://github.com/OpenEmu/4DO-Core/tree/a8e3ef0dc8feef932cb336317ac3868378d07aeb which happens to be the latest commit in that submodule. There is no issue there.

Might want to check if you are properly cloning the submodules as you clone the entire project.
