### ISSUE TITLE
Logitech f310 only mapping a few buttons, not working.

### ISSUE THREAD

**Issue by romanibga** [OpenEmu/OpenEmu#2653]
Hi!

I recently purchased a Logitech f310 controller to use on my Macbook Pro.
I've followed all the Mac instructions (switch to D on the back, plug afterwards) and the controller is being recognized by the mapping system, but when I actually press the buttons to map them, it behaves weird, basically, it will only map some buttons on the controller, like D-pad, left trigger and select. 
When I press any of the other buttons absolutely nothing happens.
Its very frustrating, hope you can help me

Thanks

**Comment by clobber** [comment]
That gamepad is known to just work, provided you first switch to the 'D' before plugging it in.

Is your problem related to anything here? https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by clobber** [comment]
I cannot replicate any problem when using the Logitech F310 alone, with the 'D' switch set before plugging it in, using OpenEmu 2.0.3.
