### ISSUE TITLE
A Cheat wont stop working!

### ISSUE THREAD

**Issue by lede1243** [OpenEmu/OpenEmu#2654]
So I have 2 issues, and either one being resolved would fix my entire problem. Here's my situation. I am playing Legend of Zelda: Ocarina of Time on OpenEmu emulator on my macbook pro. I am in the Water temple and I have completed everything EXCEPT for getting the Boss Key and defeating the boss. I know exactly how to get the Boss Key as well: I shoot the eye button on the second water level, and shoot the grey target circle with my hookshot to go past the gate on time. The problem is that because I am playing on my computer, I am using the arrow keys as directional controls. These arrow keys are not fluid enough to allow me to hit the circle with the hookshot. I can aim just above or just below the grey target. 
So I tried using a walk through barriers cheat to rectify the problem. I tried about 3 different ones, and none of them seemed to work, so I stopped trying. The next day, I went onto Ocarina of Time to see if I missed anything, and a cheat was working! i am not sure which one worked, but I am able to walk through gates, blocks, etc. not walls. It worked, but here is a different problem. Whatever cheat code worked is not listed in the list of codes. It says my list of cheat codes is empty (as this was my first time using any in openemu). So I am unable to turn the cheat off. turning off openemu doesn't work, but what does technically turn off the cheat is going to a previous save state before I put in the cheat. But that just leaves me outside the gate again with no way to get the key. Also, sources say that openemu is unable to save cheats when you turn off the openemu system, but somehow one stayed in and won't leave, so I guess it's a bug. 
So my question is, how do I get rid of the cheat while still being inside of the gate? in my most recent save state? If I can't do that, then how do I rectify the controls problem? is there a way to control the hookshot aim with the mouse and click to shoot? because I am unable to figure that out.

**Comment by clobber** [comment]
>I am using the arrow keys as directional controls

You really need a gamepad with analogs.

>Whatever cheat code worked is not listed in the list of codes. It says my list of cheat codes is empty (as this was my first time using any in openemu). So I am unable to turn the cheat off.

Sorry we can't fix this. Cheats are supposed to be deactivated from the UI during the same session you were using them. Sounds to me that whatever it changed in memory, was saved along in the save state as well.

**Comment by clobber** [comment]
And you also opened an issue just like this the other day...

#2645
