### ISSUE TITLE
Change disc function not working

### ISSUE THREAD

**Issue by danilobytes** [OpenEmu/OpenEmu#2655]
Hi guys! Changing discs for multi-cd PS1 games used to work for me but it has stopped since yesterday. I don't know if it has to do with Apple recent update or the latest OpenEmu one. The screen doesn't change and when I stop the game OpenEmu throws an error. I had a look on it and there is the following Application Specific Information:

`Assertion failed: (MDFNGameInfo), function MDFNI_SetMedia, file /Users/clobber/Code/OpenEmu/Mednafen/mednafen/mednafen.cpp, line 2033.`

I guess it is related to @clobber. I already reinstalled Mednafen core, but the same happens. If you need something else please let me know. Thanks for your time.

**Comment by clobber** [comment]
Disc switching works fine here for me. Is this only with a particular game?

My guess is there is a problem with your m3u file, maybe the filenames don't match, some files didn't get imported or something else is wrong.

**Comment by danilobytes** [comment]
Uhm, that's odd... It works now. Before opening this issue I've checked everything you said (different games; checking m3u files) and by changing nothing it came back to work. Anyways, let's hope it doesn't crash again. Thank you very much.

**Comment by danilobytes** [comment]
Oh, wait. Maybe I figured it out. Testing now with my PS3 controller (generic) plugged in doesn't work. Going back to only keyboard works fine. That's really odd...

**Comment by clobber** [comment]
Okay, thanks for the update. I know why this is happening -- also related to issues #2606 and #2636 -- and we're working on a fix for next release.

So, essentially some gamepads with analog sticks (e.g. DualShock 4, Matricom G-Pad EX, your generic PS3 controller, possibly the 8bitdo) are spamming input events even while no axes are being moved, leaving little time for frontend functions for input and core plugin callbacks to get through our runloop. This was revealed with an optimization made in OpenEmu 2.0.2 designed to lower input latency, but having the unforeseen side effect of breaking things in the frontend with these devices.

For now while using your device, if you need to use mouse or keyboard input or use something like disc changing in PS1 games, unplug your gamepad before doing so.

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu/commit/3032021828c473dbfdd444f04eb72da2bb6d5433 for next release.
