### ISSUE TITLE
OpenEmu freezes upon launching SOME arcade games, which used to work fine

### ISSUE THREAD

**Issue by bluesdance** [OpenEmu/OpenEmu#2656]
I have OpenEmu 2.0.2 and a lot of MAME games in my Library.

Up until recently, **they all worked fine**. Recently some of them stopped working so I migrated everything to a fresh Library -- at this point they worked again for a few days, until they stopped working.

When they don’t work, NOTHING is written in the console. The “remote control” box appears but none of the buttons do anything. There’s no way to move forward except with a force quit.

Some of the games that cause this behavior:
The entire “19” series: 1941, 1942, etc.
Aero Fighters 2
Armed Formation
Armed Police Batrider
Batsugun
Guwange
Turtles In Time

Some of the games that work:
Aqua Rush
Aero Fighters 3
Aero Fighters Special
ASO, Armored Scrum Object
Bang Bead
Battle Bakraid
Battle Chopper
Battle Circuit
Block Hole
Caveman Ninja
Crime Fighters
Puzz Loop 2

In the case of Armored Warriors: It worked LAST NIGHT, and today it’s NOT working!!!

I tried clearing out the CFGs and Save States in the Application Support folder, but this did not solve the problem.

OpenEmu posts a warning to the Console on launch about “Guitar Rig 5.component“ in my Audio Plug-Ins. I don’t know why OpenEmu is worried about this file... What does it have to do with playing games?

Thank you very much!!!

**Comment by bluesdance** [comment]
Update: I tried moving the Guitar Rig file to my desktop. This did not fix the problem.

Also, when OpenEmu crashes, I see a note in Console saying it is “causing excessive wakeups”

Thanks

**Comment by clobber** [comment]
Dupe #2615
