### ISSUE TITLE
Start Button doesn't work

### ISSUE THREAD

**Issue by matteoblonde** [OpenEmu/OpenEmu#2658]
Hi everyone, i hope you can help me with my problem.
I was playing Pokemon White when i tried to open the menu and the start button didn't work!!
I tried to assign it to an other keyboard button, or to use my ps4 Dualshock, but nothing! It doesn't work, and this is a problem because i need to open the menu!
Can anyone help me with my problem, please?

**Comment by clobber** [comment]
Desmume has problems with Pokemon games in general, but in OpenEmu 2.0.2 there is an issue with inputs while using the DualShock 4.

Try unplugging your DualShock 4 and see if it fixes the issue.

**Comment by matteoblonde** [comment]
Oh yes, thanks so much, i put an other DualShock and now all the function works correctly! I love you, Good Job!

**Comment by clobber** [comment]
>i put an other DualShock and now all the function works correctly

Does that mean a device other than a DS4? Perhaps a DS3?

**Comment by matteoblonde** [comment]
Nono, i put DS4, but an other one.

**Comment by clobber** [comment]
Okay...that's the opposite of what I said to try.
