### ISSUE TITLE
Classic Controller Analog Thumbsticks Pro is not optimized for PlayStation game

### ISSUE THREAD

**Issue by Murmursixtyfour** [OpenEmu/OpenEmu#2663]
I tried using my Classic Controller Pro on a German version of Medal of Honor 1 and it wasn't so successful because I can't command full thumbstick pull so the soldier end up walking at least two times slower than supposed. But it works properly Super Mario 64 though.

**Comment by clobber** [comment]
We need deadzone/peaks support some day. #1303
