### ISSUE TITLE
Keyboard not working (OpenEmu 2.0.2. & Mac OS X 10.11.4)

### ISSUE THREAD

**Issue by duksi1993** [OpenEmu/OpenEmu#2664]
Today I have installed OpenEmu 2.0.2, and I cannot get keyboard working in it.
Keyboard doesn't respond when trying to setup controls in Settings, nor in game.

I've seen issue #798 and #659 . Tried these steps, but none of them helped:
- Close Chrome and restart OpenEmu after that. (Tried both quiting, and killall from terminal)
(I don't have iTerm2 installed)
- Delete ~/Library/Application Support/OpenEmu/Bindings Configurations/Default.oebindings
- Delete whole ~/Library/Application Support/OpenEmu/*
- Reinstalling OpenEmu, by compiling latest version from GitHub (followed complete process including "Cleaning previous versions" part) - after running it, I got first run menu, which means that Cleaning part was successful.
- Rebooting computer and trying to run OpenEmu before any other program.

More ideas? :(

**Comment by clobber** [comment]
Did you look through here? https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by duksi1993** [comment]
Yes I did. I'm not using any keyboard modifier, neither antivirus.
Only Chrome, but as I said, even reboot and running OpenEmu first didn't helped.
As for USB, I don't have anything but external HDD and mouse plugged in.

Are PS2 keyboards supported by OpenEmu? (I am using one)

**Comment by clobber** [comment]
>Are PS2 keyboards supported by OpenEmu? (I am using one)

Doesn't sound like it, if that is all you have connected. Are you running on non-Apple hardware or something?

**Comment by duksi1993** [comment]
Yes, hackintosh with MacPro3,1 SMBIOS.

**Comment by clobber** [comment]
Sorry, those are unsupported. You should know better than to report issues without mentioning using non-Apple hardware.
