### ISSUE TITLE
PSP Emulator not accepting any input whatsoever, not even keyboard ones

### ISSUE THREAD

**Issue by DeepCoreLive** [OpenEmu/OpenEmu#2665]
Recently I tried to play a PSP game with a Twin USB Joystick and right about when I started to configure my controller, OpenEmu didn't read any of my inputs (Even keyboard ones). So I tried to test on other games from other consoles, like PS1 and SNES ones and it all went normally. 
I just wanna play KH Birth by Sleep =( 
Currently running the 2.0.2 version

**Comment by DeepCoreLive** [comment]
Apparently the Twin USB Joystick needs to be connected on Port1 to work, if input at a different port than Port1 it just doesn't work (Still don't know what was the keyboard input bug though)

**Comment by clobber** [comment]
Sounds like you sorted this out.
