### ISSUE TITLE
My Pokemon platinum game lost progress.

### ISSUE THREAD

**Issue by zachurchill** [OpenEmu/OpenEmu#2666]
I looked up from my game for a second and may have pressed some keys, but when I looked down my game had lost progress. I can't find any save states or automatic save states to get back to where I was. Is there any way to get back to where I was???????? I have no idea how this happened and It is really annoying.

**Comment by clobber** [comment]
> I can't find any save states or automatic save states to get back to where I was. Is there any way to get back to where I was????????

No, doesn't sound like it.

> I have no idea how this happened and It is really annoying.

Would be useless to speculate. Sorry, nothing we can do.
