### ISSUE TITLE
Improvement suggestions.

### ISSUE THREAD

**Issue by briannyeko** [OpenEmu/OpenEmu#2667]
When will you add:
Netplay through(Airplay,LAN or Wi-fi)?
Dreamcast & PS2 emulator

**Comment by clobber** [comment]
1. Netplay feature request is already tracked in another issue; please search before opening a new issue.

2. The question to be asking is: when will emulators for those systems get high enough compatibility and portability that we can use them as core plugins? As it stands now they are alpha and beta status. We don't develop the emulators so it should be clear that is outside our control.

**Comment by mrvacbob** [comment]
I can write instructions for building the test Dreamcast and PS2 cores (Reicast and Play!) if you want, but they are really really not compatible. Play only boots one game I have and making sound work is beyond even us so far.

**Comment by diogo-lins** [comment]
Hello, the Netplay feature is already in OpenEmu ?
