### ISSUE TITLE
Backup / Restore Games and Saves - Feature Request

### ISSUE THREAD

**Issue by jagalbraith** [OpenEmu/OpenEmu#2668]
Please create a process to backup and restore the games and saves so updating the version is not so painful. Also,  backing up controller configs would be lovely too.

**Comment by clobber** [comment]
>updating the version is not so painful

There isn't anything changed during updates that would call for a backup/restore process.

**Comment by jagalbraith** [comment]
Really? You have to restore all the games, re set up all the controllers, re-establish collections and re add games to them. Game saves are all lost. Any custom controllers you created are gone. How is that not painful to you? I’ll write a backup process myself in Python and distribute it on my own channel. 

-- 
John Galbraith
Information Security Analyst
Cell: 727-[[[RECIPIENT NOT IN ADDRESS BOOK]]]
Blog: https://tech55i.com

**Comment by clobber** [comment]
What the hell are you talking about?

**Comment by jagalbraith** [comment]
Here is a quick timeline of events to give you a good idea of what happened. 

I have an OpenEmu instance with Every NES, SNES, N64, Sega Genesis, and GBA game. Thousands of games right? I created a Custom collection for the games I frequent out of all of those. I set up the controller for each console type.

1. I plugged in my controller and opened OpenEmu to play a game. 
2. I immediately got a notification that there is a newer version of the game. I opted to update it. 
3. When I got back into OpenEmu, all the games, controller settings, and collection I added were gone. 


This is why I wanted to back up these settings. I imagine these are just files that got sent to the trash bin when I updated right? 

The bug here is that games and settings are not persistent through the update process. 

-- 
John Galbraith
Information Security Analyst
Cell: 727-[[[RECIPIENT NOT IN ADDRESS BOOK]]]
Blog: https://tech55i.com

**Comment by clobber** [comment]
> I immediately got a notification that there is a newer version of the game. I opted to update it. 

From which version?

>  When I got back into OpenEmu, all the games, controller settings, and collection I added were gone.

That isn't normal and I don't believe that actually happened.

> The bug here is that games and settings are not persistent through the update process. 

Yes, of course they are otherwise we'd have complaints about this all the time. We wouldn't ship updated that do that.

**Comment by jagalbraith** [comment]
I think I figured it out. I have to add a rule for AppTrap to not grab the plist for OpenEmu when it gets replaced. Sorry for the confusion.




-- 
John Galbraith
Information Security Analyst
Cell: 727-[[[RECIPIENT NOT IN ADDRESS BOOK]]]
Blog: https://tech55i.com
