### ISSUE TITLE
Missing game title in the popout gameplay window

### ISSUE THREAD

**Issue by ghost** [OpenEmu/OpenEmu#267]
**Visual Review 22 Oct 2012, item 18**

Popout gameplay window is missing the Game Title in its header bar.

**Comment by LordHDL** [comment]
This can still be done with another method.

To reproduce, you first trigger another oddity: changing the game title name to OpenEmu instead.
![screen shot 2015-02-15 at 11 13 20 am](https://cloud.githubusercontent.com/assets/5182602/6203861/54312dd0-b504-11e4-8f71-a7f228de8162.png)
Play in a popout window, enter full screen, then exit back to windowed mode.  The title changes to OpenEmu, and you can remove the title by pressing ⌘` (command + grave accent) to switch the window to the game library, then switching back to the game window.  It will give you this:
![screen shot 2015-02-15 at 11 16 24 am](https://cloud.githubusercontent.com/assets/5182602/6203855/30bb76d0-b504-11e4-9c98-67162ca96b0e.png)
