### ISSUE TITLE
I cannot close the window of any running gmaing

### ISSUE THREAD

**Issue by emulover521** [OpenEmu/OpenEmu#2670]
I just tried OpenEmu few days ago and always had fun with it. But I currently cannot close the window of any running games because the close button/red power button doesn't work at all. I guess the last time I closed the game, I probably clicked the "cancel" button to resume the game but at the meantime I somehow checked "don't show this dialog again " or something so that OpenEmu seemed to record like that users would like to resume rather than close the game as long as they click the close button/red power button...

Now please tell me how to reset the OpenEmu/discard the wrong records asap. Thanks a bunch!

**Comment by emulover521** [comment]
btw, do you guys know which kind of joystick the best compatible with OpenEmu is? I have DS3 and how about xbox360 joystick?

**Comment by clobber** [comment]
Which version of OpenEmu?

**Comment by emulover521** [comment]
should be the latest one, running on the v2.0.2 535-gc11c17e-Release

**Comment by emulover521** [comment]
I just tried once again with Final Fantasy NDS - game started running normally, all buttons seemed to be working but close button & power button, so I gotta force quit the whole application to stop the game

**Comment by emulover521** [comment]
Clobber, for god's sake I finally found out that OpenEmu itself just had the feature of resetting warnings right in the preference's description(go menu bar - go OpenEmu - go Preferences - go library - click "reset warnings" then done resetting!) Now I am able to close the game normally, thanks for your time!

**Comment by clobber** [comment]
Ah, nice find. So the bug is checking the suppression checkbox and clicking cancel.
