### ISSUE TITLE
Wiimote Connects to mac but leds don't appear.

### ISSUE THREAD

**Issue by cemre2002** [OpenEmu/OpenEmu#2672]
I read the tutorial, I did everything. 
I know the leds shouldn't appear. But the wiimote seems to not be working at all. 
I can't map controlls.

Please help

Gr. Cemre

**Comment by clobber** [comment]
Try again. Make sure you hit the red button on the back of the device to put it in discovery mode. To pair while OpenEmu is running, you should be able to hold the 1 + 2 buttons.

Using OpenEmu 2.0.2, I was able to connect two different Wiimotes so I know it is working. We have two guides available but that is all the help we can offer:

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
