### ISSUE TITLE
Keyboard, Mouse will not work at all. 

### ISSUE THREAD

**Issue by Sirin424** [OpenEmu/OpenEmu#2673]
I have tried to shut down my laptop, turn it on. Restart it, and open nothing besides OpenEmu, all of the threads that I have read do not work. I have tried deleting ~/Library/Application Support/OpenEmu/Bindings Configurations/Default.oebindings, only for it to not work.

I don't know what is going on, there is no third party software that I know of interfering with OpenEmu, I turned on Force Quit Applications, but it only shows OpenEmu, Safari, and Finder.
I am playing Pokemon black, and I am near chargestone cave, my Archen fainted, I had to switch it out, then on the screen that says "Battle using which Pokemon?" It freezed, neither my keyboard, or mouse work at all. 

The things that I have noticed are that the animations are still up, like the animation for my opposing Emolga is still moving, and all my pokemon in my team are still moving. I also can't hear any sound. Here is a video.

http://sendvid.com/cg4gxsmf

**Comment by clobber** [comment]
You're confusing the problem with something else; that isn't an input issue, that is a glitch with Desmume.

In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
