### ISSUE TITLE
mame games not working

### ISSUE THREAD

**Issue by iandonegan8** [OpenEmu/OpenEmu#2674]

**Comment by iandonegan8** [comment]
Some of my name game don not work and I have the new updated version for opener experimental pack. Is there any way to fix it. Its not a big deal because I don't really play arcade games on a emulator but when I tried they all failed. Please respond but take your time because like I said its not really a big deal. Thx

**Comment by clobber** [comment]
Dupe #2615

**Comment by iandonegan8** [comment]
thx
