### ISSUE TITLE
Can't open Openemu. Has worked previously

### ISSUE THREAD

**Issue by DEATHAHRURA** [OpenEmu/OpenEmu#2676]
Trying to open openemu but gives me the message "The operation could not be completed. No other information is available about the problem.".
**Openemu has worked for me previously, but stopped working after i:**
1. Deleted newest version of openemu.
2. Downloaded openemu 1.0
3. Installed an older version of Pokemon fire red (so i could use the cheats).
4. It would not let me open the game, i tried updating openemu then to just play normally.
5. Wouldn't let me update.
6. Tried opening and closing openemu, but then the problem started.

**What i've tried to do:**
1. Update my pc system.
2. Reinstall openemu.
3. Update openemu

Please help anyone? All i want right now is to get openemu to working again, but if anyone has an idea on how i can use the cheats please also help with that.

My computer is a macbook pro running the OS X. 10.11.6

**Comment by clobber** [comment]
OpenEmu 1.x is unsupported. Use v2

**Comment by DEATHAHRURA** [comment]
Didn't work? I already tried uninstalling openemu and then installing the newest version

**Comment by clobber** [comment]
>Confused emjoi

Actually, I'm confused why you would switch back to 1.x when the core plugins are not compatible and cheats work just fine in 2.x while using the VisualBoyAdvance plugin.

It seems you took a sledgehammer to a problem that you didn't understand and now have completely broken your install.

My advice to you is to wipe everything and start over.

**Comment by DEATHAHRURA** [comment]
Yeah i'm really silly haha.
I did try to delete all version of openemu i had on my pc, and remove them from the thrash before downloading the newest version. That didn't work.. So i should also delete the games?

By the way.. Thanks for the fast respones, really means a lot to get help :)

**Comment by clobber** [comment]
I don't know what you mean by "didn't work"

* You should wipe your OpenEmu install, removing the OpenEmu folder in Application Support (Navigate to your ~/Library/Application Support/OpenEmu ...see the [guide here](http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/) if you don't know this).
* Run the following command in Terminal.app: `defaults delete org.openemu.OpenEmu` to remove old preferences.
* Install OpenEmu 2.0.2
* Stop breaking your install. Do not mess with it.

**Comment by DEATHAHRURA** [comment]
IT WORKED!!!
Thanks a lot man!
