### ISSUE TITLE
cheats won't work for openemu

### ISSUE THREAD

**Issue by DEATHAHRURA** [OpenEmu/OpenEmu#2677]
my core is visualboyadvance, i'm using the correct codes 100%.
I followed guides and i remembered to use the master code, wild pokemon code and add the pokemon number i wanted.
i know 100% i wrote the codes right, but it won't work..
I'm using the newest version of openemu, and was told that it should still work.
Any ideas?

**Comment by clobber** [comment]
>i'm using the correct codes 100%.

I doubt that. Check the guide here: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes#gba-cheats

**Comment by DEATHAHRURA** [comment]
Still can't seem to work..
Like if i wanted to find a wild abra. i went to the link you gave me, found my game in the same country version as i play and as an example - abra, i tried to find that.
I made sure the code was correctly entered from this:
[http://prntscr.com/bxx3ew](url)
Into openemu likes this:
[http://prntscr.com/bxx35o](url)
I then made sure the cheat was checkmarked as enabled/on and then i tried going into the bushes, but as you see in 2nd link i found a ratata, not an abra..
Am i doing something wrong here?

Thanks for reply!

**Comment by DEATHAHRURA** [comment]
Can you help? I've even tried using codes only for v1, v2 which should be my game

**Comment by clobber** [comment]
I can't speak for the authenticity or usage of the cheat codes, but that appears to be a 2-line cheat, not 4-line, in which you would want to enter it as:

E1D22EE0 CED8+239BFA53 9D67

**Comment by DEATHAHRURA** [comment]
And that is the only code i would need? Like no master code or anything? If not i'll try one from the site you gave me

**Comment by clobber** [comment]
I think you generally need the "Master Code" too. For some reason, I could only get certain cheats from that website to work and I was curious, so I looked around and found others to do this:

**First enter and enable the "Master Code"**
000014D1 000A+1003DAE6 0007

**Then enter and enable the "encounter in the wild" Pokemon Modifier code for Abra**
83007CEE 003F

That will make you encounter Abra in the wild every time. After you catch it, be sure to disable those cheats before you quit and shut down the game, otherwise you will be encountering it forever.

Cheats found on: http://pokemonfireredcheats.com/codebreaker-codes

**Comment by clobber** [comment]
Yeah, the above won't work with Revision 1 of the game which you appear to be using, based on your screenshot. This is why you have to pay close attention to the guide which mentions versions of games. So you were also looking at the wrong set of codes, you need them for Revision 1:

http://gamehacking.org/game/5632

**Comment by DEATHAHRURA** [comment]
I went over to gamehacking.org and went to my version of the game which is:
"Pokemon - Fire Red Version (U) (V1.1)".
I tried entering the master codes as decrypted (is that correct)? http://prntscr.com/byytbl
and then wrote it in as "DE0FC72E 00008422" Then i tried doing the wild pokemon code but then it was unable to provide more information about the code..
http://prntscr.com/byytx1
I got pretty confused as to how i should write that in, but i tried writing it like:
59F09908+11E58618+DDEFF53A+EC57A23F (i guess this is wrong because it's not separate codes? But how can it be so long then?) By the way this wasn't just this pokemon, it was with all it said the system didn't recognize the code.

Hope to hear from you, thanks :)

**Comment by clobber** [comment]
As the guide states: for multi-line codes, use a plus (+) to separate each line. So if you have 4 lines, you do CODE+CODE+CODE+CODE - pretty self-explanatory.

Anyway, sorry I can't do anything else for you here; you are not having an OpenEmu problem. I suggest using the other version of the game where the cheats are known to work via the link I posted, or try to find another site that has working cheats for your version of the game.

**Comment by DEATHAHRURA** [comment]
You know what, i'll make sure to do that.. Can you relink me the other game version as i'm unsure as to which link you're referring to?
Also I would like to thank you a lot for the help, really been nice you spend time searching for me, even tho i'm a random 👍

**Comment by clobber** [comment]
I was referring to the comment above...
https://github.com/OpenEmu/OpenEmu/issues/2677#issuecomment-236082206
