### ISSUE TITLE
Help with Rom

### ISSUE THREAD

**Issue by Mariobro456** [OpenEmu/OpenEmu#2678]
I try to download a rom and when I drag it the rom doesn't show anyone know how to fix it

**Comment by robotoad** [comment]
What game and for which system? Where are you dragging the file to?

**Comment by Mariobro456** [comment]
It is Pokemon diamond from emu paradise and when I drag it to open emu it doesn't show up I'm on Mac OS X 10.11.14

**Comment by clobber** [comment]
* [Unzip](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) the .7z file.

* Import the .nds file
