### ISSUE TITLE
Nintendo DS Rom's don't work.

### ISSUE THREAD

**Issue by AlamarPike** [OpenEmu/OpenEmu#2681]
So every time i download a DS game onto my mac, in this case Pokemon Platinum, it downloads as a .7z file instead of a zip file. Im at a loss for what to do. Any help would be much appreciated.

**Comment by clobber** [comment]
* [Unzip](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) the .7z file.

* Import the .nds file

**Comment by simplyandy** [comment]
im on a mac... the file is unzipped
