### ISSUE TITLE
N64 doesn't let me play on open emu

### ISSUE THREAD

**Issue by Mariobro456** [OpenEmu/OpenEmu#2682]
I click on smash bros 64 and it doesn't open but it was working on me last week anyone know how to fix it I'm on Mac OS X 10.11.14

**Comment by Mariobro456** [comment]
And I am in OpenEmu 2.0.1

**Comment by clobber** [comment]
Use OpenEmu 2.0.2.

**Comment by Mariobro456** [comment]
Do I re download it or update it

**Comment by clobber** [comment]
Updating it in-app is just fine.
