### ISSUE TITLE
Hard crash when launching GBA rom

### ISSUE THREAD

**Issue by ShaneKilkelly** [OpenEmu/OpenEmu#2686]
Error as seen in crash reporter:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: OENDSButtonMicrophone)'
terminating with uncaught exception of type NSException
abort() called
```

OSX El Capitan 10.11.5, MacBook Pro (Retina, 13-inch, Mid 2014)

Same crash when opening the 'controls' section of preferences.

**Comment by clobber** [comment]
A possible fix is to do the following:

1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app and try a GBA game again.

Should be okay.
