### ISSUE TITLE
Errors compiling from source 

### ISSUE THREAD

**Issue by tdrobinson91** [OpenEmu/OpenEmu#2687]
I've tried this a few times with no luck. Followed the guide and even cleaned up as suggested in other threads. Any suggestions?
![screen shot 2016-07-30 at 11 13 39 am](https://cloud.githubusercontent.com/assets/17621973/17271337/e0e87942-5646-11e6-850d-4d9f235675f9.png)

**Comment by clobber** [comment]
Can't replicate, but maybe that only occurs under certain circumstances while compiling for Debug, which you seem to be doing -- that's incorrect if you are trying to follow the guide. 

Do you have a legitimate reason to be compiling the application + all core plugins from source when pre-compiled builds are available and we recently had a new release?

**Comment by tdrobinson91** [comment]
I see. I did not realize I was compiling for Debug. I was just following the instructions as well as possible. 

Yes, I am compiling with the addition of Dolphin 5.0 using this core: https://github.com/duckey77/Dolphin-Core

**Comment by clobber** [comment]
Okay, well that's unsupported.
