### ISSUE TITLE
Once deleted rom won't re-add

### ISSUE THREAD

**Issue by dinpappa** [OpenEmu/OpenEmu#2688]
I added Vandal Hearts rom to PS1 library in open-emu. I accidentally deleted it from library and the aftermath have caused more problems then i initially thought. Later when i tried to re-load it to the library it "loads" but won't show. I have tried to download new copies with different origins aswell. Is this a known glitch? Hope to get some assistance!

**Comment by clobber** [comment]
>Is this a known glitch?

Nope.

Navigate to the folder:
 `~/Library/Application Support/OpenEmu/Game Library/roms/Sony PlayStation` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)

Delete the game if it still exists (cue + bin's), then reimport your new game.

**Comment by dinpappa** [comment]
Thanks a bunch for the help, t'was a easy fix with your guidance!
