### ISSUE TITLE
Can't run OpenEmu on OS X Mountain Lion

### ISSUE THREAD

**Issue by cmonteiro188** [OpenEmu/OpenEmu#2690]
Hello,

I used to have OpenEmu 1.0.1 working fine on my mac since installation day, back in 2014. Then, last week, I had to restore my computer to factory settings and do a clean install of Mountain Lion (tried to update to El Captain but it got too slow). Now I just can't run any of your releases compatible with Mountain Lion anymore, getting different errors/messages when I try to launch a game:

1.0.4: no message, OpenEmu just closes itself
1.0.3: "The operation could not be completed"
1.0.2 and older ones: "Couldn't communicate with a helper application"

The same goes with the experimental releases. Is there anything I can do (besides upgrading to El Captain, which is not possible)?

Thank you.

**Comment by clobber** [comment]
Sorry, OpenEmu 1.x is unsupported.

https://github.com/OpenEmu/OpenEmu/issues/2238#issuecomment-167251788

**Comment by cmonteiro188** [comment]
I see. It's sad that 1.0.1 was fine until last week and now, after being reinstalled, it simply doesn't. Though you would have a clue on why...

Anyway, you said something about dowloading older cores on issue #2238. Do you think this would work for me? If so, could you please explain me how to do it?

Thanks again.
