### ISSUE TITLE
Can't Close game windows

### ISSUE THREAD

**Issue by HappyQuQu** [OpenEmu/OpenEmu#2692]
when i play the game
then want to close it 
but it can't close...
i must use 'FORCE QUIT' to close the game

**Comment by onehotelfoxtrot** [comment]
Same here

**Comment by clobber** [comment]
If you are using OpenEmu v2, go menu bar - go OpenEmu - go Preferences - go library - click "reset warnings" -- report back if that doesn't fix it.

**Comment by clobber** [comment]
Also disconnect any gamepad you might have connected. There is an issue with certain analog gamepads right now, that has been resolved for next version.

**Comment by onehotelfoxtrot** [comment]
I did the reset warnings and that worked for a bit and then it went back to doing the same thing. I tried to click reset warnings again but this time had no affect.

**Comment by clobber** [comment]
Read the rest of the thread regarding gamepads if applicable.

**Comment by HappyQuQu** [comment]
Reinstall can fix it ...
