### ISSUE TITLE
2.0.2 Not functioning 

### ISSUE THREAD

**Issue by onehotelfoxtrot** [OpenEmu/OpenEmu#2694]
Ever since the upgrade to 2.0.2 it has not been functioning correctly at all, at least for me. When I start the emulator I can play a game fine but if I try to load another state it just freezes everything up. I also am unable to stop the emulation or close out of OpenEmu all together unless I force quit. Help! Last version worked great, I love your program!

**Comment by clobber** [comment]
Solutions to both problems in here: https://github.com/OpenEmu/OpenEmu/issues/2692

**Comment by clobber** [comment]
Try actually providing more details, like you know, which system and game ???

Are you using a gamepad ???

**Comment by onehotelfoxtrot** [comment]
Gameboy: Pokemon Silver, Pokemon Yellow

No game pad
