### ISSUE TITLE
Using two PS4 controllers causes issues

### ISSUE THREAD

**Issue by darthbodacious** [OpenEmu/OpenEmu#2695]
I have two DualShock4 controllers connected to my late 2013 13" rMBP.

When I tried connecting both wirelessly via Bluetooth, I noticed that every few minutes one of them (or both) would cut out and stop receiving new input (usually resulting in the game "holding" the last input button down). I originally tried this on version 2.02 (535-gc11c17e-Release). Each controller experienced the same issue consistently, but not predictably.

I updated and built the most recent release (554-g59f5374-Release) and still encountered the problem.

I then tried pairing only one controller over Bluetooth and wiring the other via USB, but when I did this OpenEmu didn't recognize the wireless controller as an option for Players 1 or 2 in the Preferences menu (it only recognized the USB connected controller). If I wired *both* controllers via USB, OpenEmu recognized both of them in the Preferences menu, but the Player 2 controller input did not work in games. 

I could only get both controllers selected in the Preferences menu *and* accepting input in games when both controllers were connected via Bluetooth (however, my occasional connectivity issue kept cutting out across both). The controllers were the only Bluetooth devices that were connected to my computer at the time (I disconnected my wireless mouse and keyboard to test).

To better describe the connectivity issue: it was most obvious when playing 2 player Tetris. All of a sudden the input would either stop completely, or blocks would start stacking in the center because the game was acting as though the down direction was being pressed and held (when it was not). The connectivity would drop for a short time (usually about 1-5 seconds) and then return. It was usually one controller at a time, but both were generally affected in a given 3 minute match.

I wonder if perhaps it is a similar problem to https://github.com/OpenEmu/OpenEmu/issues/2647?

In any case, I'm happy to keep testing out different configurations (and so, so happy with OpenEmu, overall). Thanks for all the work that goes into this!

**Comment by clobber** [comment]
Try the most recent build from source, as we just fixed an issue with certain devices like the DualShock 4 that spam input events. The build will include commit 3032021828c473dbfdd444f04eb72da2bb6d5433 and I see the last you tried was the build just before that commit.

**Comment by clobber** [comment]
*Bump* can you try out the latest source to see if the issue is resolved?

**Comment by darthbodacious** [comment]
Finally got to try it today and two wireless PS4 controllers worked perfectly!

I didn't bring my micro-USB cords to test to see if the issues regarding one wired and one wireless or both wired was resolved... but both playing wirelessly worked perfectly.

Thank you!

**Comment by clobber** [comment]
Dupe #2647
