### ISSUE TITLE
Problems still with 2.0.2 after clicking reset warnings

### ISSUE THREAD

**Issue by onehotelfoxtrot** [OpenEmu/OpenEmu#2697]
My last issue was closed even though it was still in process of being worked on, not sure why? I clicked the reset warnings and it allowed me to close my rom like normal. Then when I reloaded it, it would not let me load another state nor would it let me close it without force quitting. I clicked the reset warning again but this time it had no affect.

**Comment by clobber** [comment]
Don't open new issues, post in the old one #2694
