### ISSUE TITLE
Custom paths for mame roms

### ISSUE THREAD

**Issue by menelkir** [OpenEmu/OpenEmu#2700]
An option for customizing directory path for MAME roms. For example, I have a macbook air and I have my mame set on my external hdd, of course it's nearly impossible to get rom dependencies to put individually in directory (or even drag and drop), also I can't have a mame set inside my main disk so customizing the path should help a lot, specially if you have a big set.

**Comment by clobber** [comment]
Either Preferences > Library > Change Game Library Folder Location or symbolic links.
