### ISSUE TITLE
Trouble mapping some n64 controller buttons

### ISSUE THREAD

**Issue by gak7** [OpenEmu/OpenEmu#2702]
Hey,

I've been trying to get an official n64 controller and a usb adapter (https://www.amazon.co.uk/gp/product/B003D61Y30/) to work in open emu. However, when I try to map certain buttons (the analog stick and A,B) it isn't registering in the mapping. Has anyone got any advice? Thanks.

**Comment by clobber** [comment]
Using OpenEmu 2.0.2? Anything here relevant to your problem? https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by guitman444** [comment]
Have same issue with same adapter. I understand it says on the Input Problems page "Adapters" are "generally unsupported", so we may be out of luck. However, it _almost_ works. OpenEmu recognizes the controllers connected to the adapter, I can map buttons and everything in the OpenEmu settings. It's just that games don't respond to the controller after the buttons are mapped. 

Any hope for us adapter users?

**Comment by clobber** [comment]
Issues using Mayflash adapters have been addressed in OpenEmu 2.2.
