### ISSUE TITLE
Can't Run OpenEmu on OS X 10.11.6

### ISSUE THREAD

**Issue by throwout** [OpenEmu/OpenEmu#2703]
Hello,

I am running OS X 10.11.6 (El Capitan) on a Macbook. When I try to install or run OpenEmu, I get the following message:

Check with the developer to make sure OpenEmu works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.

I have tried reinstalling OpenEmu, but it still does not work. Any ideas? Thanks.

**Comment by clobber** [comment]
Maybe the binary was corrupted in some way from your decompression software.

Download OpenEmu again and extract the zip file with Archive Utility (built-in on OS X, right click Open With > Archive Utility) or the defacto standard for other archive types, [The Unarchiver](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) (free on the mac app store).

**Comment by throwout** [comment]
Thanks, that worked!
