### ISSUE TITLE
black screen, won't quit

### ISSUE THREAD

**Issue by andrezweers** [OpenEmu/OpenEmu#2704]
in the mame/arcade emu open-emu crashes, black screen, no quitting possible if i try to open certain  mame roms, notably 'zerowing' , it plays fine w QMc2/sdlmame and my moms are .176.

so i end up force quitting it a lot...

i guess its still 'experimental'?

:)

love the app!!!! (donated)

**Comment by clobber** [comment]
Dupe #2615
