### ISSUE TITLE
OpenEmu 2.0.2 Manual save state not working on OS X 10.11.6

### ISSUE THREAD

**Issue by penmarkercys** [OpenEmu/OpenEmu#2705]
Hello,

I installed OpenEmu 2.0.2 recently on my mac (El Capitan 10.11.6), The auto save works fine but the manual save is not working when I move the mouse and try to click the floppy a balloontip is saying "save in progress", (in french : Sauvegarder la partie en cours) and nothing appears, I tried with several games and several emulators NES, SNES and MegaDrive, still not working.
I did not understand why because the auto save is working, and not the manual save.
Thanks for your help!
Have a nice day.

**Comment by clobber** [comment]
Which gamepad are you using?

**Comment by penmarkercys** [comment]
Mostly a wired Xbox360 controller or the keyboard.

**Comment by clobber** [comment]
A problem in OpenEmu 2.0.2 with select analog gamepads. Fixed in https://github.com/OpenEmu/OpenEmu/commit/3032021828c473dbfdd444f04eb72da2bb6d5433 for next release.
