### ISSUE TITLE
Lost Data 

### ISSUE THREAD

**Issue by logancowan7** [OpenEmu/OpenEmu#2706]
I lost all of my data while I was playing Pokemon Fire Red and I want to know how to get it back. I put a lot of time into the game and I'm definitely not starting over. I hit save when I got to a rare Pokemon and when I saved it, I moved over one spot and I went back into the game to see if it would take me to my previous place and it didn't so I exited and when it asked me again if I wanted to continue where I left off I said no but then it erased all of my data. Please do something to help!

**Comment by clobber** [comment]
Can't help you here as it sounds like user error. One has to be pretty careful using save states and mixing those with use of in-game battery saves.

So what sometimes happens is people make the mistake of mixing battery saves + save states. As with most of the emulators, battery saves are 'saved' during core shut down, even in the standalone versions. So if you open a save state that occurred before that battery save and you close the game, well you're now overwriting your battery save with that memory when you close.

There isn't much for us to fix here as this is how most function. I suggest you just stick with the autosaves and make regular manual save states as you progress throughout a game. Possibly safer that way if you just ignore the battery completely and only save the battery if you plan on transferring your game save elsewhere.

**Comment by clobber** [comment]
Should also note that you want to be using OpenEmu v2 with the mGBA core plugin, if you aren't already. That's the only version of OpenEmu supported. There is a guide here on transferring battery save files if you were previously using VisualBoyAdvance: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files
