### ISSUE TITLE
Run include-what-you-use

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/OpenEmu#2707]
https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md

Anything that makes the build faster is worth it!

**Comment by PlutoX86** [comment]
As a fan of the project and being a programming noob -> If i don't want to compile the PPSSPP core 'again' (and OE and OE-SDK compile extremely fast anyway), it's actually kinda easy to edit it out it manually.. 

But granted, anyone who reads "... solved in the next update" actually might want to build OE on their own the fastest way possible. BUT which could also bring "Issues" to the next level of frustration..

**Comment by mrvacbob** [comment]
Related: Build All also much faster if we fix PPSSPP/MAME to not rebuild every time
