### ISSUE TITLE
OpenEmu no me funciona, no me deja abrirlo

### ISSUE THREAD

**Issue by rayoaser** [OpenEmu/OpenEmu#2709]
Yo tenía OpenEmu y funcionaba correctamente pero lo desinstalé hace poco y al intentar volverlo a instalar no me deja abrirlo, me pone: No se ha podido completar la operación.
Y debajo de eso pone: No se dispone de más información sobre el problema.
Aclaro que soy de Mac

**Comment by clobber** [comment]
Okay, a core crashed? Have any specific details, in English please?

**Comment by rayoaser** [comment]
No, it only puts that there isn´t information about the problem

**Comment by clobber** [comment]
Details I'm looking for:

* Which version of OpenEmu and OS X?
* Steps to replicate the crash; which game and system.

**Comment by clobber** [comment]
Closing for lack of info.
