### ISSUE TITLE
OpenEmu issues - emulator going way too fast

### ISSUE THREAD

**Issue by prl100** [OpenEmu/OpenEmu#2710]
Hi there

Sorry to trouble you all, but just wondering if anyone could help. I have recently downloaded OpenEmu to emulate SNES and megadrive games, but am finding it doing so far too fast - ruining the gameplay. I have googled this issue and found some very old answers saying to alter the frame rate but I could not figure out how to do that with this software.

I'm running OpenEmu on a 2016 Macbook, 1.2Ghz, 8Gb RAM, OSX 10.11.6 if that helps.

If anyone is able to help it would be much appreciated

Thanks

**Comment by mrvacbob** [comment]
Does this happen with any other kind of games like Gameboy? Maybe you have some key mapped to Fast Forward by accident?

**Comment by prl100** [comment]
I only use it for a couple of NES games and a couple of mega drive games. The mega drive games are both too fast but the NES games seem fine.

**Comment by yashghelani** [comment]
Happens with me in Sonic the Hedgehog (GBA)

**Comment by andrezweers** [comment]
happens on a lot of games

**Comment by clobber** [comment]
Provide exact details. Which Mac? Which system and game?

**Comment by yashghelani** [comment]
MacBook Air (13-inch, Mid 2013) - OS X El Capitan 10.11.6 - Sonic the Hedgehog Genesis

**Comment by clobber** [comment]
I cannot replicate "Sonic the Hedgehog: Genesis" running too fast in the mGBA core plugin -- perhaps an issue on your end? As an aside, that is a really terrible port of the game. I'd recommend the original on the Mega Drive / Genesis :P

**Comment by yashghelani** [comment]
Thanks for that recommendation @clobber :) Turned out that was the game I was actually looking for. The original. Classic!

**Comment by andrezweers** [comment]
iMac late 2013/3.5ghz/32g ram.

i know mame is not officially supported :), a lot of mame games could benefit from a speed throttle DOWN :)

and while we r on the unsupported mame thread :)

are there plans to support the more current .176 roms?

---Donated---

**Comment by GamerLunaBoy** [comment]
It's too fast for me too, the game I played is NBA 2k12 on a PSP emulator known as PPSSPP in openemu, is there any way to fix this?
