### ISSUE TITLE
N64 Emulations Refuse to Stop

### ISSUE THREAD

**Issue by slimjosa** [OpenEmu/OpenEmu#2713]
After updating to version 2.0.2, OpenEmu refuses to shut off N64 games when I click the "stop emulation" button. Instead, it simply speeds up the game for a second and pauses. As a result, I cannot even save my games as force quitting the application after finishing a session only erases the state I created. This doesn't occur with other consoles, only Nintendo 64.

**Comment by clobber** [comment]
Please search before opening a new issue.

Dupe #2606
