### ISSUE TITLE
DS Emulator Doesn't Recognize Touch Input

### ISSUE THREAD

**Issue by slimjosa** [OpenEmu/OpenEmu#2714]
Whenever I try clicking on the touch screen area of the DS emulator, it does nothing. I tried checking to see if my controls were mapped wrong and it appears that there isn't even an option to configure touch input. While the emulation runs smoothly, games like Kirby: Canvas Curse are unplayable as they _only_ use the stylus. Hopefully this will be resolved soon.

**Comment by clobber** [comment]
Please search before opening a new issue.

Dupe #2636
