### ISSUE TITLE
Ability to use bluetooth game pad when OpenEmu isn't the active window

### ISSUE THREAD

**Issue by jasonwoodland** [OpenEmu/OpenEmu#2715]
I'm on macOS with a bluetooth connection to my Dualshock 3 and use OpenEmu on a TV. It'd be cool if someone could play the game using the controller on the TV while I use my Mac on the primary display.

**Comment by clobber** [comment]
Probably won't do anything to support using OpenEmu on TV's or allowing the app to receive inputs while it's not in focus, but we will likely do a tvOS port in the future.
