### ISSUE TITLE
Turbo controller compatibility?

### ISSUE THREAD

**Issue by Ludi64** [OpenEmu/OpenEmu#2717]
I'm currently playing Banjo-Tooie on OpenEmu and I've had issues with joystick sensitivity and the lack of a turbo/rapid fire option in OpenEmu (I've seen the previous threads about these issues, so I'd like to join the many others who want these features in OpenEmu).

Before I buy a turbo controller, I would like to know if the turbo function would even work based on the OpenEmu software's control configurations. In other words, if my hardware (i.e. my controller) can perform the turbo function, will the software (i.e. OpenEmu) implement it in gameplay? 

I've tried button mashing and that still is too slow (hence my concern about how OpenEmu input configuration), so I feel that a turbo controller is my last option to complete the game 100%. Since I'm near the end of the game too, I'm all the more disappointed. If there were a way for me to manually change the controls, I'd do it.

**Comment by clobber** [comment]
Rapid fire doesn't look like something we'd probably add and we don't exactly need another issue opened about it.

>Before I buy a turbo controller, I would like to know if the turbo function would even work

I assume it would, it is simply sending inputs faster.
