### ISSUE TITLE
OpenEmu Select Button Not  

### ISSUE THREAD

**Issue by TheBanditGame** [OpenEmu/OpenEmu#2718]

**Comment by TheBanditGame** [comment]
I have a mac El captain 
I just downloaded Open Emu To Play 
Pokemon White 2 for nintendo ds
I started play but then I could not select the options 
I tried changing The controls but still not working

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
