### ISSUE TITLE
Sidebar resizing resets after quitting and opening the app

### ISSUE THREAD

**Issue by yashghelani** [OpenEmu/OpenEmu#2720]
I resized the sidebar and then quit the app. After opening it, I saw that the sidebar was back to it's default size. I resized it again to my need and then quit the app and opened it again. And again the sidebar had switched back to it's default size.

**Comment by robotoad** [comment]
Can't replicate this. If you're still have this issue, try [enabling the Secrets preferences pane](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Secrets) and clicking the "Reset main window" button, which will reset various main window size preferences including the sidebar width.
