### ISSUE TITLE
2.0.3

### ISSUE THREAD

**Issue by andrezweers** [OpenEmu/OpenEmu#2723]
anyone having the same problem as me:

2.0.3 won't open any game, no matter the emu?

**Comment by andrezweers** [comment]
oops, restart fixed that, some games (Cave) dont open from 'continue from last....', 
open fine from fresh start.
they give the famous black non-responsive screen (force quit) on 'continue'

**Comment by clobber** [comment]
You seem to be talking about Arcade games which are officially unsupported at this time, and you already opened an issue about this before: #2704
