### ISSUE TITLE
disc change on parasite eve

### ISSUE THREAD

**Issue by felipe-dias** [OpenEmu/OpenEmu#2726]
When I reach the end of the first disc on Parasite Eve, I can not play the second.
![captura de tela 2016-08-15 as 12 09 33](https://cloud.githubusercontent.com/assets/21040514/17668824/7c23f142-62e1-11e6-938d-7f97f94287e8.png)

When I play only the second disc, the game run without any problem.

MacBook Pro 13"
OS X El Capitain
OpenEmu v2.0.3

**Comment by clobber** [comment]
You didn't follow the guide: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game

**Comment by felipe-dias** [comment]
I followed the guide, but don't work...

**Comment by felipe-dias** [comment]
Are you I am stupid?

**Comment by clobber** [comment]
Well let's see, you posted a screenshot and said "can not play the second" which doesn't describe what you're doing or what's wrong.

Are you playing the game by loading the m3u file? If so, is the m3u file actually correct? If so, do you have the option to "Select Disc" via the HUD bar?

**Comment by felipe-dias** [comment]
All the files are correct. I have the option "Select Disc".
When I start the second disk, it runs normally. But when I'm in the printed screen, the "Select Disc" option don't work.

**Comment by clobber** [comment]
Which region of the game? Upload your mem card save file ([transfer.sh](https://transfer.sh), dropbox, cloudapp) found in `/Users/[YOUR NAME]/Library/Application Support/OpenEmu/Mednafen/Battery Saves` and link it here.

**Comment by felipe-dias** [comment]
In this game a there is not a save on the exchange screen. I have the savestate. Ok?

https://transfer.sh/mfU5g/insert-disc-2.oesavestate

**Comment by clobber** [comment]
You cannot upload a .oesavestate bundle file directly to that website. The file needs to be zipped in order to transfer it. I also need to know **which region** of the game. I'd also really prefer a mem card save file saved at a point where it's ready for me to switch to Disc 2.

Also, how about showing the contents of your m3u file in which you use to load the game?

**Comment by felipe-dias** [comment]
I have not used memory card

NTSC-U

https://transfer.sh/fpkt8/insert-disc-2.oesavestate.zip

**Comment by clobber** [comment]
Okay, so do this: go into the game and do an in-game save, then provide me with the mem card save file.

**Comment by clobber** [comment]
>Also, how about showing the contents of your m3u file in which you use to load the game?

Still waiting on this too.

**Comment by clobber** [comment]
Okay, I checked out your state file. I don't know if you manually imported that from a previous single-disc save state or what (my hunch is you did, and that won't work), but it will not load the next disc. Playing the game with the m3u file, you are going to have to save in-game and then load that mem card save and get to the point where you can switch discs again. Don't bother with your save state file.

Just to verify that disc switching does work, I tried a [save I found online](http://fantasyanime.com/squaresoft/parasiteeve/pe_saves.htm#day6) that gets me to "Day 6/Final Battle" and sure enough, I can switch to Disc 2 when it prompts me to.

For testing purposes, here are my mem card saves: https://transfer.sh/AhWwE/parasite-eve-day-6.zip
