### ISSUE TITLE
Donkey Kong Pauline roms aren't recognized

### ISSUE THREAD

**Issue by robwired** [OpenEmu/OpenEmu#2727]
Under old versions of Mame it was necessary to patch Donkey Kong Pauline but with newer versions of Mame this hacked rom is now recognized as "dkongpe". I see that Donkey Kong Foundry is recognized by the newest OpenEmu experimental which makes me wonder which underlying version of Mame is OpenEmu using?

**Comment by clobber** [comment]
Says in Cores Preferences that it is based on MAME 0.149.

Our MAME core plugin is 'experimental' an unsupported, and thus probably will not be updated anytime soon.
