### ISSUE TITLE
# Control setting is frozen on my mac. Neither default key would work in game.

### ISSUE THREAD

**Issue by BWbear** [OpenEmu/OpenEmu#2730]
openEMU: 579-gf929d38-Release
MacBook Pro (Retina, 15-inch, Mid 2015)
OS X 10.11.6 (15G31)

As titled, both control setting and default key don't work in openEMU, don't why.

My game works well, but I can not play it.

**Comment by clobber** [comment]
Try here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by BWbear** [comment]
Hi clobber, thanks for your reply. Yes, I'm using ONLY keyboard with macbook.

**Comment by BWbear** [comment]
I will give a shoot with clean restart of my mac.
