### ISSUE TITLE
Option to show status bar

### ISSUE THREAD

**Issue by yashghelani** [OpenEmu/OpenEmu#2731]
Can we have an option to show the status bar (just like the Finder) to show all the details about the window/tab that's open. For eg. number of games, total memory taken by those games, etc.

**Comment by robotoad** [comment]
There's currently not a status bar implemented to display that information, but if you right-click a game and select "Show in Finder," it will open a Finder window for the containing folder.

**Comment by yashghelani** [comment]
What about showing the total number of games in the sidebar? For eg. PSP (4), PS (7), All Games (11), etc.

**Comment by clobber** [comment]
Nah, that's not useful enough information either and ends up being clutter. Just use Finder if you *really* need to know.

**Comment by yashghelani** [comment]
Alright :)
