### ISSUE TITLE
Can we have a column called 'Done' in the All Games section?

### ISSUE THREAD

**Issue by yashghelani** [OpenEmu/OpenEmu#2732]
Just like the 'Rating' column, we should be able to mark the game as done when you've finished playing it.

**Comment by robotoad** [comment]
I'm not convinced this would be used by enough people to warrant it as a feature, but if you're wanting to track completion status, you can create a "Done" playlist and add completed games to it.

**Comment by yashghelani** [comment]
Okay. Seems fair :)
