### ISSUE TITLE
Can't resume OpenEmu game or change keybinds

### ISSUE THREAD

**Issue by BigDTurk** [OpenEmu/OpenEmu#2739]
I've recently been playing a pokemon game on my OpenEmu and everything is frozen and i cant move or anything, its completely frozen and i can't do anything. Plus i have no idea on how to change keybinds.

**Comment by BigDTurk** [comment]
Also just to mention, i'm using the Nintendo DS console

**Comment by BigDTurk** [comment]
Plus i think it might have something to do with the lid keybind but i dont know how to open the lid or resume the game PLEASE HELP ME I LOVE THIS GAME!

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
