### ISSUE TITLE
Screenshots behave inconsistently

### ISSUE THREAD

**Issue by ticky** [OpenEmu/OpenEmu#2740]
In v2.0.3, screenshots taken (of GameBoy Advance games, at least) in pop-out mode on a Retina MacBook Pro appear to be scaled to the main window’s last-used (non-Retina) resolution. Screenshots taken from the pop-out window in this way also appear to ignore any set filter settings when at 1x scale (despite the output scale being dependent on the main window!)

It seems to me that it would be worthwhile providing options for screenshots to either be “as shown” and “at original resolution,” but currently the output appears to provide neither of these.

**Comment by clobber** [comment]
Already available in debug prefs: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Secrets

Maybe something to bring over to one of the other pref tabs, eventually.
