### ISSUE TITLE
Reicast Core (Dreamcast)

### ISSUE THREAD

**Issue by rochev22** [OpenEmu/OpenEmu#2742]
Hi everyone! First of all i'd like to thank Openemu Team for such a quality product like Openemu! Thank you very much! I'm very interested to play Dreamcast games and i was very surprised when you announced Recast Core! Please, guys, share with us status of development of Recast core in openemu. Can we play Dreamcast games in near future?

**Comment by clobber** [comment]
>Can we play Dreamcast games in near future?

No, sorry.
