### ISSUE TITLE
Emulator not working

### ISSUE THREAD

**Issue by Zeliaa** [OpenEmu/OpenEmu#2745]
I have the 1.0.4 experimental version of OpenEmu. I've added the playsation BIOS, And 3 games. I cannot play any because the soft asks me to try again, and reboot the app (that does nothing). the error message is "Couldn’t communicate with a helper application."

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to OpenEmu 2 and OS X 10.11.
