### ISSUE TITLE
Does not work with Virtual Keyboard, node

### ISSUE THREAD

**Issue by JPTeasdale** [OpenEmu/OpenEmu#2747]

**Comment by JPTeasdale** [comment]
I'm trying to build a crowd controlled emulation experiment, but open emu doesn't respond to keypresses generated by nodes robotjs or golangs: github.com/micmonay/keybd_event 

I also noticed the the on screen accessibility keyboard doesn't work.

**Comment by clobber** [comment]
Dupe #2642 

Probably won't be able to fix the other unless you hack around it.

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
