### ISSUE TITLE
OS X is too recent

### ISSUE THREAD

**Issue by bbwlover** [OpenEmu/OpenEmu#2748]
Anyone else have this problem, where OS X needs to be 10.11 or later?

**Comment by clobber** [comment]
Not sure what you mean by this.

**Comment by bbwlover** [comment]
When I try to start OpenEmu, I get this message http://imgur.com/a/Wbp0Q

**Comment by clobber** [comment]
If you are indeed running OS X 10.10.5, that message is clear. The minimum requirement to run OpenEmu is 10.11.

**Comment by bbwlover** [comment]
Fair enough. It's just that I was using OpenEmu without issue, not too long ago.

**Comment by clobber** [comment]
That was for versions 1.x, Version 2 (released December 2015) has always required OS X 10.11.

Update to 10.11, you'll be much happier.

**Comment by bbwlover** [comment]
Thanks
