### ISSUE TITLE
Trying to play PSP games, gives me error, "Couldn’t communicate with a helper application."

### ISSUE THREAD

**Issue by i3DGamer** [OpenEmu/OpenEmu#2749]
I've tried NES games and those work but when i try to play PSP games, it gives me that error. Im currently using 1.0.4 experimental because i cant run 2.0 as it says i have a lower version of OS X as i have 10.10.5 and it needs to use 10.11. I've tried 3 different PSP games now. 
![screen shot 2016-08-24 at 10 04 53 am](https://cloud.githubusercontent.com/assets/21222688/17935822/466fdc70-69e2-11e6-8a3d-3e5c759935ce.png)
I'm not really in a rush but i would like an answer, thanks.

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to OpenEmu 2 and OS X 10.11.

10.11 is a free upgrade in the Mac App Store. http://www.apple.com/osx/how-to-upgrade/
