### ISSUE TITLE
No System Sound

### ISSUE THREAD

**Issue by sensible69** [OpenEmu/OpenEmu#2750]
Unable to pick up system sound when playing Openemu.

I can hear the sound through my headphones and internal speakers on my Macbook Pro respectively but I'm not able to capture the sound when streaming using OBS.

I've installed iShowU Audio Capture and have created a multiple output to my headphones and to iShowU. This is selected as an input device in OBS but still no sound will come through.

Using OS X 10.11.6, had the same issue on 10.11.5. All applications are up to date.

I should note that the first few time I was able to capture the sound but now I am not able to.

**Comment by clobber** [comment]
If I am understanding correctly, you probably need to enable our [debug prefs](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Secrets) and then select "Show audio output device in menu" which will then allow you to select an audio device from the HUD bar while a game is playing.

**Comment by sensible69** [comment]
Hey!

Thanks for your response. I've found the debug prefs and enabled the option to change audio output.

I'm still unable to collect anything as a system sound. 

I have this issue using both OBS and GameShow streaming applications.

The sound will still output to my headphones when I have enabled the multi-output device enabled with iShowU Audio Capture.

This issue doesn't occur with other applications however.

Can you think of anything else it might be?

Thanks,

Darcy

On Aug 25, 2016, at 10:40 AM, clobber <notifications@github.com> wrote:

If I am understanding correctly, you probably need to enable our debug prefs and then select "Show audio output device in menu" which will then allow you to select an audio device from the HUD bar while a game is playing.
