### ISSUE TITLE
'Select' key not working

### ISSUE THREAD

**Issue by PharaohHunter** [OpenEmu/OpenEmu#2751]
Whenever I press 'Right Shift' nothing happens in my game. I have tried restarting my computer many times but the same problem keeps happening in every game I play. I am using OS X El Capitan 10.11.6. Any advice?

**Comment by clobber** [comment]
Which game and system?

**Comment by PharaohHunter** [comment]
It happens on all games, but I'm trying to play Pokémon Gold using a ROM downloaded from the internet. What do you mean by system @clobber ?

**Comment by clobber** [comment]
Works fine for me in OpenEmu 2.0.3, with Pokemon Gold:
![screen shot 2016-08-25 at 3 09 22 pm](https://cloud.githubusercontent.com/assets/1303132/17984266/ff4c49f6-6ad5-11e6-826e-9756c22379ee.png)

Maybe bind 'SELECT' to another key?
