### ISSUE TITLE
OpenEmu Experimental 1.0.4 Will Not Import CCD Files

### ISSUE THREAD

**Issue by Goi-Yaas-Dinn** [OpenEmu/OpenEmu#2752]
Is there a reason this version of OpenEmu simply remains silent when failing to import what I am quite sure is a valid CCD file- no dialog, no warning, no error, no nothing? I have no idea what is wrong because I'm not getting an iota of feedback from the application.

Mountain Lion 10.8.5.
[[HECD4010] [HE100523] [Mixed mode CD] [!-].ccd.zip](https://github.com/OpenEmu/OpenEmu/files/437364/HECD4010.HE100523.Mixed.mode.CD.-.ccd.zip)

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to OpenEmu 2 and OS X 10.11.

**Comment by Goi-Yaas-Dinn** [comment]
I'm not upgrading to El Capitan. Are you telling me you can't even help me with one of your own releases, just because you think no one should use old software?

**Comment by clobber** [comment]
>I'm not upgrading to El Capitan.

That's your own problem.

>Are you telling me you can't even help me with one of your own releases

Yes.
