### ISSUE TITLE
Missing controller graphics for Saturn

### ISSUE THREAD

**Issue by infinitewarp** [OpenEmu/OpenEmu#2756]
It looks like commit https://github.com/OpenEmu/OpenEmu/commit/58bdad288e7d8c6855fc534db52bfce2c53be2d5 destroyed the placeholder graphics and key coordinates for a bunch of controllers. Although most have been replaced since then, Saturn's controller graphics are still blank.

When configuring controller settings, if you don't already know exactly where the buttons are supposed to be on the real-world counterparts, not having a visual aid makes it difficult to input a good, appropriate button map.

**Comment by infinitewarp** [comment]
FWIW, I have opened a pull request that could address this issue: https://github.com/OpenEmu/OpenEmu/pull/2755

**Comment by clobber** [comment]
>for a bunch of controllers

Huh? That old commit doesn't reflect the current state of the controller graphics
