### ISSUE TITLE
mame

### ISSUE THREAD

**Issue by andrezweers** [OpenEmu/OpenEmu#2757]
i know theres no official support for exp cores but i had mame running so nicely for a week or 2

now i get the black screen, sometimes i can quit ,sometime i can't and have to resort to force quit
whats going on?

8/27/16 8:28:20.399 PM launchservicesd[84]: SecTaskLoadEntitlements failed error=22
8/27/16 8:28:20.401 PM launchservicesd[84]: SecTaskLoadEntitlements failed error=22
8/27/16 8:28:20.402 PM launchservicesd[84]: SecTaskLoadEntitlements failed error=22
8/27/16 8:28:20.406 PM appleeventsd[53]: SecTaskLoadEntitlements failed error=22
8/27/16 8:28:20.410 PM OpenEmuHelperApp[2010]: parent application is: OpenEmu
8/27/16 8:28:20.411 PM OpenEmuHelperApp[2010]: Apple Keyboard
8/27/16 8:28:20.413 PM OpenEmuHelperApp[2010]: Macally iShockX Game Controller
8/27/16 8:28:20.418 PM OpenEmuHelperApp[2010]: Device is already being handled
8/27/16 8:28:20.467 PM OpenEmu[2007]: SETUP DONE.
8/27/16 8:28:20.547 PM OpenEmu[2007]: Display's nominal refresh rate is 59.95 Hz
8/27/16 8:28:26.000 PM kernel[0]: process OpenEmuHelperApp[2010] caught causing excessive wakeups. Observed wakeups rate (per sec): 7171; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 46555
8/27/16 8:28:26.883 PM com.apple.xpc.launchd[1]: (com.apple.ReportCrash[2012]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
8/27/16 8:28:26.884 PM ReportCrash[2012]: Invoking spindump for pid=2010 wakeups_rate=7171 duration=7 because of excessive wakeups
8/27/16 8:28:27.127 PM spindump[317]: No microstackshots found

help???

**Comment by clobber** [comment]
déjà vu...

#2704
