### ISSUE TITLE
"No filter" filter

### ISSUE THREAD

**Issue by Tombenpotter** [OpenEmu/OpenEmu#2761]
So, this is not really an issue, and it may sound weird to some people, but I happen to actually dislike filters.

Would it be possible to add an option in the filter list that would be "No filter"? Just so that I'd be able to play the game with the default graphical output, and nothing else.

Thanks for any answer! :D

**Comment by clobber** [comment]
That's what Nearest Neighbor is, though really you are going to want to be using Pixellate (the default).

**Comment by Tombenpotter** [comment]
I'll stick to nearest neighbor, pixellate is a tad too blurry for me. Thanks a lot!
