### ISSUE TITLE
ds white screen

### ISSUE THREAD

**Issue by guilliano111** [OpenEmu/OpenEmu#2762]
i update it to 2.0.3 so i was going to play pokemon then ther was a white screen now i lose my save  files ;-;

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.

**Comment by guilliano111** [comment]
nvw i hust had to restart it sorry of losing your time
