### ISSUE TITLE
UI idea regarding multi-disc games

### ISSUE THREAD

**Issue by msikma** [OpenEmu/OpenEmu#2764]
I think it'd be nice if multi-disc games had a slightly different appearance in the games list, because once you have a multi-disc game the proper way to start it is to click on the playlist item.

Here's the current display, as it is right now in my version (2.0.1):
<img width="835" alt="mock1" src="https://cloud.githubusercontent.com/assets/1507745/18166044/1131e39c-7049-11e6-9d38-748f702afc8a.png">

Here's what it would look like if the individual discs were folded under the main playlist item:
![mock3](https://cloud.githubusercontent.com/assets/1507745/18166077/46b66682-7049-11e6-8711-af2c99f89b93.png)

In case you wanted to see the individual discs, you could click on the arrow next to the playlist item, which would expand the list:
![mock2](https://cloud.githubusercontent.com/assets/1507745/18166087/5b409762-7049-11e6-8ee8-619d9ab48c5e.png)

I think this would be useful for users since (as far as I know) the correct way to start a multi-disc is always to click on the main item, rather than on the individual disc. It would also clean up the list a bit, since right now multi-disc games have n+1 items in the list.

I hope this is useful and fits in with whatever is already planned for this feature.

**Comment by clobber** [comment]
We're improving the import process for m3u files so that it simply imports everything and you won't see the individual discs in the library, since those aren't useful. In the mean time, you can simply remove the individual discs from your library, while still keeping them in your Game Library folder. Also, you should upgrade to 2.0.3
