### ISSUE TITLE
Help with entering md5 hash for BIOS files??

### ISSUE THREAD

**Issue by jdal2700** [OpenEmu/OpenEmu#2765]
Hello, first of all I'd like to point out I'm very new to all this.

I'm currently trying to set up a PS game on OpenEmu. I already extracted the game file, which is now processed properly into the program, which is great.

Afterwards, I installed and extracted the required "scph5500.bin", "scph5501.bin", and scph5502.bin" files in the Unarchiver (I'm running on Mac). Then, I went into Terminal, ensured I was a root user, and drag and dropped each of the required files into the terminal, and typed in their appropriate MD5 hashes into the terminal after.

My problem is that the terminal KEEPS issuing "Access denied", despite me enabling myself as a root user prior. And yes, I have the correct MD5 hashes. 

This might be a minor problem, but is there something I'm doing wrong? Thanks.

**Comment by clobber** [comment]
>And yes, I have the correct MD5 hashes.

I'm confused by what you mean. You found the correct ones from the [BIOS guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files) or you have the correct ones based on checking your files?

There is a guide for [getting the MD5 checksum](https://www.maketecheasier.com/file-checksum-mac/) but other than that, I don't think I can help you. It's not a requirement to get the MD5 checksums.

Best advice is just to drag in all the PS1 BIOS files you have and OpenEmu should automatically import the correct ones, which you can verify in OpenEmu > Preferences > System Files.
