### ISSUE TITLE
Buttons Won't Work in A Few Games

### ISSUE THREAD

**Issue by Kogie13** [OpenEmu/OpenEmu#2772]
I cannot select items in some games. In Mario Kart 64, I cannot select a character in the game. In Super Mario Kart, it will not let me select a mode. In Super Mario World, it will not let me select something to get past the intro screen. Any help? I have all the buttons configured fine

**Comment by clobber** [comment]
Try here https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
