### ISSUE TITLE
Pokemon Pinball Not Running at all on mGBA core

### ISSUE THREAD

**Issue by hullstar242** [OpenEmu/OpenEmu#2775]
MacBook 13 inch 2015
8gb RAM
El Capitan
OpenEmu 2.0.3

Not sure if its a core bug or an OpenEmu bug. close if its not an OpenEmu bug.

**Comment by clobber** [comment]
Problem with your dump of the game? All four versions of "Pokemon Pinball - Ruby & Sapphire" (Europe, Japan, Japan Rev 1, USA) work for me with the mGBA 0.4.1 core plugin.
