### ISSUE TITLE
PS4 Controller recognized and mapped by Openemu but doesn't function

### ISSUE THREAD

**Issue by rwdman** [OpenEmu/OpenEmu#2778]
I successfully connected and mapped a dual shock 4 controller. Upon opening any N64 rom the controller is not functioning within the rom. I can open the menu and confirm it is recognized and mapped and still have no functionality in game.

**Comment by clobber** [comment]
Try here https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
