### ISSUE TITLE
(Request) Will there ever be an option added to export raw .sav files?

### ISSUE THREAD

**Issue by JoshWilsonnn** [OpenEmu/OpenEmu#2779]
I imported my Pokémon Red save, but can't reverse the process now. If not, could you point me in the direction of another utility/app with this capability? Mac or PC - thanks.

**Comment by clobber** [comment]
The process is the exact reverse. First make sure you have saved in-game, close it and then copy your battery save file from:
`/Users/YOURNAME/Library/Application Support/OpenEmu/Gambatte/Battery Saves`

**Comment by JoshWilsonnn** [comment]
I tried this & it will not take because the core of my DSTWO emulator isn't
the same.

**Comment by clobber** [comment]
Sorry, can't help you there. The .sav files are indeed the correct battery save files from the emulator.

**Comment by JoshWilsonnn** [comment]
I know - I copy them to my DSTWO emulator & the exact file to overwrite the original, but I no longer receive the option to continue in-game (Pokémon Red). I'm wondering if something about the file after being booted on OE conflicts with its visibility on GameYob. 🤔
