### ISSUE TITLE
Gamecube support?

### ISSUE THREAD

**Issue by lifeiscontent** [OpenEmu/OpenEmu#2780]
Any chance you guys might add support for Gamecube roms? Dolphin on mac is pretty decent these days, but the mapping for controllers is quiet poor.

Also, is there a place to donate to speed up development by any chance?

**Comment by clobber** [comment]
No, at least, not in the near term. Recommend to use the Dolphin's native Mac app.

If you want to donate to OpenEmu, you can do so here: http://openemu.org/donate/
