### ISSUE TITLE
USB N64 Controller Issue

### ISSUE THREAD

**Issue by bjmort** [OpenEmu/OpenEmu#2781]
So i have got my USB N64 controller working however the anaolgue stick doesn't have varying degrees of direction. For example, if you lightly press on the joystick your character does't slowly move forward. The character just does;t move until the joystick kicks in and then its as iff the joystick has been pushed hard in that direction.

Is this a limitation of my gamepad or of open emu?

**Comment by Compression** [comment]
Openemu. A lot of people have the same issue, I believe it's #1303.
