### ISSUE TITLE
[Mac OS] Crash if you access Services submenu while running a game

### ISSUE THREAD

**Issue by shinji257** [OpenEmu/OpenEmu#2782]
While a game is running (any emulator as far as I can tell, tested on Game Boy as well as SNES -- both cores) if you go to the Application menu then try to open the Services submenu the application will crash.  The system will catch it but if you tell it to continue then input is effectively broken at that point.

Here is a crash log from when I hit Crash on that screen.

https://p.robertpendell.com/raw/UymevhkTOp

**Comment by robotoad** [comment]
I can't replicate this. I notice in the crash log that you were running Sierra public beta 7. Are you still experiencing the issue in the release version of Sierra?

**Comment by robotoad** [comment]
Scratch that last comment. I can replicate it when using the popout gameplay window.
