### ISSUE TITLE
Crash with Bluetooth Controller (2.0.3)

### ISSUE THREAD

**Issue by rowdyreverb** [OpenEmu/OpenEmu#2785]
I've noticed that OpenEmu persistently crashes when I attempt to use my HoriPad Ultimate controller with it. The controller works with mGBA installed separately, so I don't believe it is the issue. The error occurred with 2.0.0 and is still present after updating to 2.0.3

The error occurs when I open Preferences while the bluetooth controller is connected and it causes the app to immediately crash. This error does not occur while the controller is not connected. The error is easily replicable.

Details are as follows:
rocess:               OpenEmu [11550]
Path:                  /Applications/OpenEmu.app/Contents/MacOS/OpenEmu
Identifier:            org.openemu.OpenEmu
Version:               2.0.3 (2.0.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           OpenEmu [11550]
User ID:               501

Date/Time:             2016-09-14 11:03:35.711 -0500
OS Version:            Mac OS X 10.11.6 (15G1004)
Report Version:        11
Anonymous UUID:        4709EF39-3293-81D6-CFA4-392FCEDD9406

Sleep/Wake UUID:       3A4A778C-27BA-4CC4-B984-FD6622878005

Time Awake Since Boot: 16000 seconds
Time Since Wake:       2800 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: org.openemu.system.OEBindingsController

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Performing @selector(showPreferencesWindow:) from sender NSMenuItem 0x7fd90bd754e0
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unknown control value for identifier: 'OEGenericControlButton113' associated with key name: 'OEGenesisButtonA''
terminating with uncaught exception of type NSException
abort() called

My computer is a 2010 MacBook Air with Core 2 Duo and 4GB RAM

**Comment by clobber** [comment]
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.
