### ISSUE TITLE
Autosave before loading save

### ISSUE THREAD

**Issue by davidganster** [OpenEmu/OpenEmu#2789]
Accidentally loading a quicksave discards all progress since the last save. Memory card (in PSX) is reset as well.
Either openEmu should make a savefile before loading, or at least ask to erase all progress.

**Comment by clobber** [comment]
This is how save states work and it doesn't have anything to do with OpenEmu. Loading a state means you are loading everything in memory from that time, including the last contents of the mem card. Can't do anything about this, it's how the emulator(s) work. Best advice is to be more careful.

**Comment by davidganster** [comment]
I'm sorry for my lack of explaining what my actual issue is.
I'm well aware how savestates work - but the way the UI is implemented right now is not a very pleasant user experience. 
If Microsoft Word had a 'Delete document' button right next to the 'Save' button, everything would 'work as intended' as well, but it would without question be a bad design choice.

openEmu tries to deliver a good UX (and succeeds for the most part!), and not losing progress is a huge part of that.
An option to autosave every X minutes, automatic saves before loading a save, or a dialogue if the user hasn't saved in say 10 minutes before loading a save would go a long way towards making the overall experience much more pleasant.
Even just separating the 'load' and 'save' menus into separate buttons would help greatly.
