### ISSUE TITLE
NDS Problems

### ISSUE THREAD

**Issue by carmelo2935** [OpenEmu/OpenEmu#2791]
After working for a while, I am now unable to add new NDS ROM's and the ones that I have, the controls are not working. Also, I am very new to emulators and stuff related to that so I do not know much about the subject.

**Comment by clobber** [comment]
For input problems: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

For adding NDS roms:
* [Unzip](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) the .7z file.

* Import the .nds file
