### ISSUE TITLE
OpenEmu 2.0.3 does not work with synergy

### ISSUE THREAD

**Issue by pimlottc** [OpenEmu/OpenEmu#2792]
I am using synergy to share a keyboard and mouse between my Macbook Pro and my Windows 10 desktop.  The keyboard is attached to the Windows computer, making the Mac the synergy client.

This worked fine with OpenEmu 1.0.4 but since upgrading to OpenEmu 2.0.3, I find it doesn't respond to the Synergy-shared keyboard, only to the Macbook's own keys.

Nightly builds from Synergy are available here for testing: https://symless.com/nightly

**Comment by clobber** [comment]
Our input system is a little more complex and we probably won't be able to easily support that setup. I'll add it to the list here https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by pimlottc** [comment]
Bummer, that's unfortunate.  For me, that means I'll have to stay on 1.0.4.  I'm having problems downgrading, though; I can't seem to re-install the MAME core (progress bar doesn't move) and running Dr Mario on SNES just gives a blank screen, with a "Couldn't communicate with a helper application" error when I try to restart.  Do I need to clean out some settings directory?
