### ISSUE TITLE
Syphon is outputting at 120 FPS

### ISSUE THREAD

**Issue by LordHDL** [OpenEmu/OpenEmu#2795]
Actual game speed is normal, but it seems the emulator and/or its Syphon output may be running at a higher frame rate?

The reason I suspect this is because I regularly use Syphon Recorder to make videos of various games with its frame rate setting at "As Fast As Possible," which records at whatever rate the source video is outputting at.  The result is a video at 60 FPS if the game in question runs at 60, even though I'm technically not capping the rate to 60 in Syphon Recorder.  Such videos have super smooth motion with no visible stutter in them.

When recording OpenEmu this way I get a video at 120 FPS.  The emulator itself (as well as the videos) show a frame stutter that isn't present in other games I record.  Here's my hardware:

MacBook Pro 8,2
AMD Radeon 6750M
i7 quad core
16 GB memory
SATA 3 SSD

I've only tested this with Genesis, SNES, and PS1.  I record at their native resolutions (320x224, 256x224, and 320x240 respectively).  It is most easily seen with objects/sprites that flicker every frame, such as the shield in Sonic 2.

**Comment by vjdobermann** [comment]
little question : how do you send the game on syphon ?

**Comment by mrvacbob** [comment]
Do people still use Syphon? We haven't added back support in the Metal renderer, though we could. @stuartcarnie

**Comment by clobber** [comment]
Syphon support is removed as of OpenEmu 2.1.
