### ISSUE TITLE
OpenEmu won't close

### ISSUE THREAD

**Issue by Plemxn** [OpenEmu/OpenEmu#2797]
I opened OpenEmu like normal but when I tried to open up a game (randomized pokemon soul silver) the screen went to black instead of the normal intro screen. i tried to quit the emulation to restart it but it wont close. i tried to shut OpenEmu off and it will wont close. It wont allow my computer to shut down because the emulation is technically running. I don't know what to do. Please help.

**Comment by robotoad** [comment]
[Read this](https://support.apple.com/en-us/HT201276) on force quitting an application.

**Comment by clobber** [comment]
You may also have to open Activity Monitor (Applications > Utilities) and force quit OpenEmuHelperApp.
