### ISSUE TITLE
ROMs and Artwork won't load

### ISSUE THREAD

**Issue by LuxuryMilk** [OpenEmu/OpenEmu#2798]
Hi all

Hoping someone can help?

Downloaded OpenEmu on Sunday - all working great. Ordered a couple of NES and SNES USB controllers and had a play last night - no problems.

Then things went a bit weird, and the same issues tonight.

All of the art work disappeared and now none of the games will load. The odd game try to load but either gives me a black screen or gets stuck on the loading titles (Nintendo logo for example).

Im running Mac mini (Mid 2010)
El Capitan 10.11.6 (15G1004)
2.4 GHz Intel Core 2 Duo
4 GB 1067 MHz DDR3

**Comment by LuxuryMilk** [comment]
![screen shot 2016-09-20 at 20 10 57](https://cloud.githubusercontent.com/assets/22329631/18685152/c0ca757e-7f6e-11e6-8158-316fce001ed6.png)
![screen shot 2016-09-20 at 20 12 03](https://cloud.githubusercontent.com/assets/22329631/18685155/c10b2b78-7f6e-11e6-83fd-65dab3434f67.png)
![screen shot 2016-09-20 at 20 12 33](https://cloud.githubusercontent.com/assets/22329631/18685153/c0feb9c4-7f6e-11e6-8174-025d34820638.png)
![screen shot 2016-09-20 at 20 13 14](https://cloud.githubusercontent.com/assets/22329631/18685156/c110f288-7f6e-11e6-8430-b4f3aea503c2.png)
![screen shot 2016-09-20 at 20 13 42](https://cloud.githubusercontent.com/assets/22329631/18685154/c105946a-7f6e-11e6-8801-bf2ad8f0ef4e.png)

**Comment by LuxuryMilk** [comment]
Hoping some of those photos help? Looked at a few other threads and followed some of the steps to save people posting the same help over and over

**Comment by clobber** [comment]
Can't think of a way cover art would vanish, so I don't think that is happening unless someone is fiddling around with their install. Keep your game folder on your local drive if you aren't already doing so. You do need an active internet connection to download the artwork. Once you have one, right click on a game and select "Download Cover Art".

As for the black screen on the games, try switching the "Filter" to Nearest Neighbor or Pixellate.

**Comment by clobber** [comment]
Oh, also noticed your display's refresh rate is only 50hz which is no good. If you play a NTSC game or anything on a handheld, they will be running too slow.

And maybe you have bad dumps of games? That output for Super Bomberman (Europe) looked really weird.

**Comment by clobber** [comment]
Lastly, you said you "followed some of the steps" from other threads and that could mean anything, so no telling if you broke your install based on what you read. If nothing above works, you will want to just remove your OE install and start fresh.
