### ISSUE TITLE
Games wont load on Lion

### ISSUE THREAD

**Issue by InochiPM** [OpenEmu/OpenEmu#2799]
I have only recently come across this app because of a search i did to find VirtualBoy Advanced.
so i tried to run some games i had on my external but i couldn't get them to launch at all.  the little icon changes to a spinning wheel icon and nothing happens. there's only one version i can run and thats 1.0.4 for Lion. Since i'm running on OSX 10.7.5 this is the only version that will work. i was hoping that 2.0 would work but its only for 10.11 or higher ^^;; 
I tried to follow some of the fixes on here but none of them seem to work at all. 
Also before anyone says to I can't update to 10.11 since i have a macbook from 2007.

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to OpenEmu 2 and OS X 10.11.

**Comment by InochiPM** [comment]
Why is it unsupported? Also is there anyway to actually fix my problem instead ot telling me to go and spend $1000+ on a new laptop. also if it's unsupported you shouldn't you remove the release from being downloadable instead of telling people to upgrade? I also cannot update at all i'm using an older macbook and i would really like to use it.
