### ISSUE TITLE
Copying Save State to Another Computer/Installation

### ISSUE THREAD

**Issue by brettallica** [OpenEmu/OpenEmu#2803]
I'm still loving OpenEmu, as it's easily the best front end out there! I installed in late-2015 and haven't looked back. 

I am now installing this on another computer in my house, and I would like to bring my saved states for a few specific NES games with me so that I can resume the games where I left off. Really it's only one game that I really really want the save state — Tetris — and it's so I can retain the high scores and have records of them on both/all systems where I play the game. 

I tried looking around in the help forum but couldn't quite find what I was seeking, so I apologize in advance if this is a duplicate topic.

Thanks for all you do.

**Comment by brettallica** [comment]
Looks like I just figured out my own issue! 

The way I did it was launch the game (Tetris) for the first time on the new installation. This creates a save state for the game called "Auto Save State.oesavestate". Right-click on this .oesavestate file/package/bundle and select the "Show Package Contents" option. Once the package contents directory is revealed, you can see the actual files comprising the save state. Keep this window open.

Now (if you haven't already done so), locate the save state from the game whose save state you want to bring into the new installation. Perform the same sequence as mentioned in the previous paragraph until you get to the directory that shows the three save state files. Copy those files from the original game into the new installation of the game. Confirm replace of all three files. This should do it.

Launch the game and see what happens. It seemed to work perfectly for me, as I was able to see my high scores that were achieved on another computer. Yay!

**Comment by marnovo** [comment]
I've ran into a similar issue when moving my library to another disk—save state files still exist on my home folder but OpenEmu doesn't identify them when open a game, as if there was no save state. As there are literally hundreds of ROMs with save states, this approach isn't reasonable.

Is there any other way to do this at scale?

Going even further: why would OpenEmu ignore the existing save state files, given both ROM files (just moved to a different disk) and save state files (not touched) are the same?

Thank you.

**Comment by jhocking** [comment]
It's years later so you probably don't still care, but I just found this thread while moving to OpenEmu on a new computer. While looking at OpenEmu release notes I noticed it referring to double-clicking on save states to open them, so I just tried that and it worked!

https://openemu.org/rnotes/1.0.2.html

So to clarify what I did: I copied the .oesavestate files from Application Support > OpenEmu > etc on my old computer to my new computer, then double-clicked them to and they add back to the list within OpenEmu. I'm not sure if this works at scale with multiple ROMs (haven't tried that yet) but it does work with multiple states in a single game. As in, drag the mouse selection around all the state files in a folder, then double-clicking once adds them all.

**Comment by brettallica** [comment]
> It's years later so you probably don't still care, but I just found this thread while moving to OpenEmu on a new computer. While looking at OpenEmu release notes I noticed it referring to double-clicking on save states to open them, so I just tried that and it worked!
> 
> https://openemu.org/rnotes/1.0.2.html
> 
> So to clarify what I did: I copied the .oesavestate files from jhocking > Library > Application Support > OpenEmu > etc on my old computer to my new computer, then double-clicked them and they add back to the list within OpenEmu. I'm not sure if this works at scale with multiple ROMs (haven't tried that yet) but it does work with multiple states in a single game. As in, drag the mouse selection around all the state files in a folder, then double-clicking once adds them all.

That’s awesome and I always love hearing updates about things. Thank you for sharing. I still use this software regularly to get my retro gaming on.
