### ISSUE TITLE
DS Games Freezing and Crashing

### ISSUE THREAD

**Issue by Caxinuld** [OpenEmu/OpenEmu#2805]
This has never happened with the emulator before. When I updated to v2.0.3, I suddenly began to have major issues with quick saving and loading. Sometimes, if I press the key set to quickload, the emulator will crash and say "couldn't communicate with helper application." However, I've found that it is rare for that error to happen and instead, my game will completely freeze and both the power and reset button will fail to work. If I force quit OpenEmu and click on the game thumbnail, it will start me off where the game froze and I have to force quit the application again or the game will send me back to an earlier point where I played it. E.g. a game crashes on stage 5 and sends me back to the beginning of 4.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2314#issuecomment-247815066
