### ISSUE TITLE
[Feature Request] Genre field and/ or custom fields

### ISSUE THREAD

**Issue by Kerry-Maxwell** [OpenEmu/OpenEmu#2806]
I'd love to be able to enter genre information for sorting purposes. It was also be great to have a notes or comments field. Right now I'm using collections to organize by genre, but more sorting options would be welcome. A release date field would be sweet too.

**Comment by clobber** [comment]
Please search before opening a new issue.

#664 and #811

**Comment by Kerry-Maxwell** [comment]
Thank you.
