### ISSUE TITLE
Key Binding Preset List

### ISSUE THREAD

**Issue by differenceclouds** [OpenEmu/OpenEmu#2807]
I saw a couple requests similar to this, but none this simple. Just the ability to save multiple layouts would be nice. I'm imagining a simple drop down list of saved presets.

I use a controller that acts as a wireless keyboard, but sometimes I like to use a normal keyboard. It's not a huge pain to remap the buttons, but it could be nice. Could also be good for situations like having an alternative more compact layout for two players on one keyboard.

**Comment by clobber** [comment]
> saw a couple requests similar to this

Okay, I'd call this a duplicate then.

**Comment by differenceclouds** [comment]
rude

**Comment by clobber** [comment]
No, rude is opening a duplicate issue when you are aware of others similar to your request. In fact, you could have just posted in them.
