### ISSUE TITLE
same key problem 

### ISSUE THREAD

**Issue by SwordDragon1** [OpenEmu/OpenEmu#2809]
So i'm playing crono trigger on your emulator and there's this part where i have to press 2 keys at the same time. Now this won't work no matter how many times I try, so i was hoping you could fix that by allowing me to assign the same key to be both "L" button and "R" button

**Comment by clobber** [comment]
Keyboards (sometimes depending on model too) are limited on the number of keys they will register at once, especially depending on row. You could remap, for example, your L + R + A binds momentarily to 1, 2 and 3 on the keyboard and those should probably register.
