### ISSUE TITLE
OpenEmu Crashes on Launch

### ISSUE THREAD

**Issue by N0S1GNAL69** [OpenEmu/OpenEmu#2810]
As soon as I launch OpenEmu is closes with no sort of crash log or pop-up. Then it removes the app and its just GONE! I'm using OS X Sierra 10.12 Help?

**Comment by robotoad** [comment]
Open Console in Applications->Utilities and post any OpenEmu error logs you find. Make sure you're running the latest version of OpenEmu, which is currently 2.0.3, and that you downloaded it from the [OpenEmu website](http://openemu.org).

**Comment by robotoad** [comment]
Not enough information to diagnose.
