### ISSUE TITLE
Single Intellivision game with multiple files

### ISSUE THREAD

**Issue by drwhoelse** [OpenEmu/OpenEmu#2812]
AtariAge has a link to home-brew game of Ms Pac-Man for Intellivision website.  I downloaded the zipped file of Ms Pac-Man game from that site.  Unzipped and dumped binary files into OpenEmu on my Mac.  It wouldn't play.  I believe that OpenEmu doesn't process multiple files needed for playing Ms. Pac-Man properly.  In this game's pack, it has three files with different file extensions-- BIN, CFG and ROM.  If there is no solution for this, please consider adding this as a new feature/support.

By the way, I'm able to play this game with three files in my RetroPie Raspberry Pi box.

**Comment by clobber** [comment]
You only need to import the .rom file, in this case "ms.rom," because it already contains the necessary header for the emulator to identify and handle the game.
