### ISSUE TITLE
Playstation Games not Recognized after being moved.

### ISSUE THREAD

**Issue by Zideocraze** [OpenEmu/OpenEmu#2813]
I moved files around to better organize my Folders and such.
Now when I try to drag over the ISO files games that worked initially won't work again.
I've tried deleting OpenEmu to start again but it doesn't seem to change anything.

I've tried everything I can think of. Is there a Reset all Option within OpenEmu that could fix this?

**Comment by clobber** [comment]
You can't move files around that are already imported into your Game Library and expect them to work. ISO files cannot be imported as PS1 games, they have to be loaded through cuesheets as per [CD the guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games).
