### ISSUE TITLE
tvOS Port

### ISSUE THREAD

**Issue by albinousrex** [OpenEmu/OpenEmu#2814]
Hi,

I've looked through past posts and nearly all say tvOS support was pretty much out of the question due to the work needed to be done. 

That being said, there was an issue closed from 5 days ago (#2804) asking if other OS's would be developed, with a response from mrvacbob seemingly stating tvOS would be developed (unless I mis-read). Does this mean it is in development and if so, is there any ETA?

Appreciate the response and all the hard work on the project. Open EMU is an amazing piece of software!

**Comment by robotoad** [comment]
We want to do a tvOS port, but there is no ETA.

**Comment by albinousrex** [comment]
Thanks for the quick reply!
