### ISSUE TITLE
Mupen64Plus: Mapping Z axis on a joystick?

### ISSUE THREAD

**Issue by jeffreybox** [OpenEmu/OpenEmu#2818]
I noticed that there isn't an option to map the z-axis for the joystick - aka diagonal (i even have a n64 usb controller). If I map x & y only, games are almost unplayable...  Any thoughts?

**Comment by clobber** [comment]
With an analog gamepad, you would need to map "Up, Down, Left, Right" under "Analog" in N64 Controls.

**Comment by jeffreybox** [comment]
Fair enough.  I tried a few different controllers - works better with some.  Will just find the best option out there.  Any recommendations?

**Comment by clobber** [comment]
For gamepads with analogs:
* PlayStation 4 DualShock 4
* SteelSeries Nimbus
* 8Bitdo NES30 Pro
