### ISSUE TITLE
converting battery saves?

### ISSUE THREAD

**Issue by disclaim** [OpenEmu/OpenEmu#2819]
Im fairly new to open emu and i made an github account to submit this issue, so please bear with me. I was wondering if there was a way to convert my battery save files from visual boy advance to open emu? I recently switched from Windows to mac, and i was running VBA on windows. I cannot drop the save files from my gameboy color games with either the .SAV or .SGM extension into open emu. Do i need to change the file extension? Usually i would open VBA and select load to load either of these files. Can anyone help? Im sorry if this was answered before and thank you to whoever in advance :)

**Comment by clobber** [comment]
This guide should help you take a battery save file from your VBA Windows install and use it with mGBA (the core plugin you want to be using instead of VBA): https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files

**Comment by franklinyu** [comment]
How about reading `.sgm` files?
