### ISSUE TITLE
Errors with compiling.  

### ISSUE THREAD

**Issue by juppaluri** [OpenEmu/OpenEmu#2821]
When I try to compile OpenEmu Experimental on Xcode, I always get these errors (see screenshot).  I am on an MacBook Air 13 inch mid 2013.  Is there anything I can do?  (I am compiling on experimental because I want an unsupported core (Pokemini))

![screen shot 2016-10-05 at 8 32 35 pm](https://cloud.githubusercontent.com/assets/12588760/19136470/e7baec68-8b3a-11e6-8d78-da19d20e7296.png)

**Comment by clobber** [comment]
Call it an Xcode glitch. Supposed errors pop up while source code files are indexing, which I've noticed ever since we rearranged a bunch of header files. It should build fine if you actually compile.

**Comment by mrvacbob** [comment]
Also, update Xcode… or maybe even macOS. Class properties are a new feature.

**Comment by robotoad** [comment]
@juppaluri Class properties are a feature of Xcode 8. You will need the latest stable version of Xcode to compile the project.
