### ISSUE TITLE
How to show just favorites from all systems?

### ISSUE THREAD

**Issue by ylluminate** [OpenEmu/OpenEmu#2822]
Is there currently a way to show favorites from all systems in one location?  Eg, I might want to see a list of all of my favorite games that are 5 stars in every game system so that I can just conveniently find them vs going into the system and then searching by name.

**Comment by clobber** [comment]
Thumbs up'd your own post?

Anyway, Switch to List view, sort by rating...

**Comment by ylluminate** [comment]
@clobber nope, that's my son who is also a developer.

**Comment by ylluminarious** [comment]
@clobber Yeah, I happened to be having the same problem as @ylluminate so I 👍'd his post. I am indeed a separate person ;)
