### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by LelouchvBrutania** [OpenEmu/OpenEmu#2825]
I was playing pokemon light platinum (rom hack) and was playing on wrong core (mGBA) and didn't know until i evolved pokemon and then my game just got a black screen same thing with trading and i need to switch to Visual Boy Advanced without losing save files could you please help.

**Comment by LelouchvBrutania** [comment]
#1002

**Comment by clobber** [comment]
mGBA is the recommended core plugin to use for GBA games. VisualBoyAdvance is deprecated and will be removed in the future.

I don't know anything about your ROM hack, but I know that link cable trading is not supported in either. Only help we can provide:

https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Default-Cores

https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files

**Comment by LelouchvBrutania** [comment]
I don't know it doesnt let me evolve pokemon on mGBA and when i tried to do it on Visual Boy Advanced it worked and i'm already half way through the game and would not like to restart.

**Comment by theactualadi** [comment]
i am having the same problems but i want to do the game on open emu and every time i evolve the pokemon it goes to a blue screen.
any fixes?
