### ISSUE TITLE
Can't load saves up to a point, and can't create new ones (Mac)

### ISSUE THREAD

**Issue by Josemartinmoya** [OpenEmu/OpenEmu#2829]
I got a Rom version of Persona 3 Portable, I've been playing for days now and today when I tried to load my latest save file today the message "Try your operation again. If that fails, quit and relaunch the application and try again." popped out. I last played 3 days ago without any issues. I tried reinstalling the cores. I updated OpenEmu to 2.0.3 and it still won't work. I can open the game normally and load the in-game saves. Other Psp games open and load just fine. Any suggestions?

**Comment by clobber** [comment]
Sounds like a PPSSPP bug there - I've had some states that fail to load before. You can probably replicate the same behavior in their standalone app.

**Comment by Josemartinmoya** [comment]
So there is a standalone PPSSPP app? Could I move my saves?
