### ISSUE TITLE
Couldn’t communicate with a helper application. Error Message - Help Needed

### ISSUE THREAD

**Issue by AryaLovesParadox** [OpenEmu/OpenEmu#2830]
My current Mac OSX is version 10.9.5 .... I haven't been able to update my OSX due to limited data allowances due to where I live. I downloaded the version of OpenEmu that works with my current OS (v1.0.4), and I added in all the ROMs and downloaded all Cores listed.

But everytime I attempt to use them, I keep getting the error message "Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again."
I've uninstalled, reinstalled, removed the ROMs, readded the ROM's.... 

I have shut down the app, gone into the Cores folder and completely deleted all Cores and then reopened the app, checked for updates, and redownloaded all Cores. 

To no avail. Same error message keeps happening.

**Comment by clobber** [comment]
Sorry, 1.x is unsupported.
