### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by JoshuaPettus** [OpenEmu/OpenEmu#2831]
First off, I doubly made sure that all sub modules were up to date, and then when that failed I cleaned out everything and recloned.  Not ruling out user error mind you, :) but that shouldn't be the problem.
When compiling for "Build All + Experimental" it fails at building 4DO) with these errors.

OE3DOSystemController.m:82:48: error: no visible @interface for 'OECUESheet'
      declares the selector 'initWithPath:'
    OECUESheet *cueSheet = [[OECUESheet alloc] initWithPath:path];

OE3DOSystemController.m:83:37: error: no visible @interface for 'OECUESheet'
      declares the selector 'dataTrackPath'
    NSString *dataTrack = [cueSheet dataTrackPath];

Anything I can do about that?

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu/commit/b45ace17d2988e059de12e16eafe3467b300484b
