### ISSUE TITLE
Rapid Fire Input

### ISSUE THREAD

**Issue by itsgreggreg** [OpenEmu/OpenEmu#2833]
Since the previous issue was locked which means I cannot comment: https://github.com/OpenEmu/OpenEmu/issues/933

I'd just like to reiterate that many people would love a rapid fire checkbox next to each Gameplay Button when configuring Controls.

Not that this is easy to do or a show stopper but it is certainly a feature request of many and I believe it should be treated as such. It's a common feature of many emulators, hardware controllers and software controllers and it would be awesome if external software wasn't necessary to achieve this functionality.

**Comment by clobber** [comment]
We don't need an issue opened for this.
