### ISSUE TITLE
Problem to use cheat codes

### ISSUE THREAD

**Issue by salsififi** [OpenEmu/OpenEmu#2834]
Hello, impossible for me to use cheat codes in Zelda Ocarina of Time (Nintendo64): I tried with several codes doing like specified in the wiki, was carefull with syntax, but no way: each time it didn't work at all.
Can someone help me?

**Comment by clobber** [comment]
Have an example?

**Comment by salsififi** [comment]
I tried these four ones:
D01C84B50020 811DAA9040CB

D01C8675 0020 + 811DAC50 40CB

D01C84B5 0020 + 811DAA90 40CB

D01C8D75 0020 + 811DB350 40CB

(It should allow Link to levitate by pressing L button, but this doesn’t work).

Thank you for your help.

**Comment by clobber** [comment]
The [L Button For Moon Jump](http://gamehacking.org/game/21084/?name=moon+jump&format=original) code entered as `D01C84B5 0020+811DAA90 40CB` works just fine, provided you are using Version 1 of the USA release of the game.

Our [cheat code guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes) states: "be sure that the codes you use are for the proper region and revision of the game you are playing." You will need to find a working codes for your [particular version of the game](http://gamehacking.org/system/n64/ocarina).
