### ISSUE TITLE
I don't the select cheat option.

### ISSUE THREAD

**Issue by thienlan0310** [OpenEmu/OpenEmu#2836]
I just download openemu on openemu.org but for some reason I don't have the select cheat on the hud.

**Comment by clobber** [comment]
Have to be using OpenEmu 2.x with all the latest core plugins. It's not available for every system, see [the guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes).

**Comment by thienlan0310** [comment]
I download OpenEmu from openemu.org. I play the Sony Playstation and they don't have the select cheat option. Is that one doesn't available for cheat?

**Comment by clobber** [comment]
It's self-explanatory. If cheat support were available for that system, you'd see the menu item.
