### ISSUE TITLE
Open app and its the outdated version?

### ISSUE THREAD

**Issue by ninjaskills123** [OpenEmu/OpenEmu#2837]
ive opened downloaded several times and each time im left with a before 2.0 ( so no n64 or other systems added in the 2.0 update) version of the game yesterday it was working fine but no longer does

**Comment by robotoad** [comment]
Are you downloading from the [official website](http://openemu.org)?

**Comment by ninjaskills123** [comment]
yes i have from the official website and from the release notes on github

**Comment by robotoad** [comment]
Go to Preferences, and in the Library tab, make sure the systems you want visible are checked.

**Comment by ninjaskills123** [comment]
That was the problem! thanks
