### ISSUE TITLE
OpenEmu won't open?

### ISSUE THREAD

**Issue by Tempo17** [OpenEmu/OpenEmu#2838]
So I have a Macbook Pro that is on OSX El Capitan and I tried to play some emulator games and i get a weird message saying that it won't open the game. Now it won't even open the program I need help explaining what to do. 
http://imgur.com/a/I5Bet
There is an image of what exactly pops up but in case for whatever reason you cannot access this what is says is "An error occurred during the persistent store migration." What is going on here?

**Comment by clobber** [comment]
Too late to fix a data store migration issue from an old install. To work around this, follow the steps in this issue: #2649
