### ISSUE TITLE
Unable to launch games after attempting to launch a faulty ROM

### ISSUE THREAD

**Issue by bloomingbridges** [OpenEmu/OpenEmu#2841]
Looks like I had a faulty GameBoy ROM in my library. 
Whenever I tried to open it, (after failing silently) I was consequently unable to launch any other game until I quit and reopened the client. The app itself was still responsive and as far as I could tell allowed me to use all the other features just fine. This is probably not intended behaviour?
 
This was on macOS Sierra 10.12 and I tried both, opening them by double-clicking and through the contextual menu.

**Comment by clobber** [comment]
Already fixed in https://github.com/OpenEmu/OpenEmu/commit/21e02f08e1289118a9f28988f767e9f2b24587ce for next release.
