### ISSUE TITLE
Lost save. 

### ISSUE THREAD

**Issue by electrikdave** [OpenEmu/OpenEmu#2842]
130 hours deep in Xenogears when suddenly my Mac comes unplugged. After loading, system asks "Do you want to resume" and I click yes, and am back to a week ago. I saved at in-game save points, but my virtual memory card shows nothing. I have an OE save from long, long ago, and within it there is an old capture of the memory card, but I can't find my progress anywhere. Is there any hope?

**Comment by kardas6** [comment]
Same here with  Pokemon Fire Red. Can anyone help? I still can not save my game..

**Comment by clobber** [comment]
Can't help with lost saves - usually due to inadvertent user error. One needs to be very careful when using save states and in-game battery saves.

**Comment by kardas6** [comment]
Thanks.

**Comment by Knockonwoodathome** [comment]
This happened to me with MHFU. I am currently dying inside.
