### ISSUE TITLE
OpenEmu N64 No Mercy Flickering

### ISSUE THREAD

**Issue by 80xer5antar05** [OpenEmu/OpenEmu#2843]
Hey
When playing N64 No Mercy I the screen flickers badly when a wrestler gets out of the ring, kinda makes it unplayable which is diasspionting. There is also some Issues with the screen art when selecting a wrestler but the flickering is the main issue

Anyone got a fix?

**Comment by clobber** [comment]
A Mupen64Plus GPU plugin bug.  Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
