### ISSUE TITLE
Feature Request:  Implementing a launcher for Dolphin, Cover Art and All

### ISSUE THREAD

**Issue by hullstar242** [OpenEmu/OpenEmu#2844]
I know that implementing the Dolphin core would be a heavy and almost unnecessary task.  However, I believe what is really desired is for OpenEmu to add gamecube to the list of systems.  The isos would behave differently when clicked as they would open in Dolphin when you click a gamecube game.  It just is way more pleasing to click on a GameCube game with its cover art than the small little banner with a bunch of text in the Dolphin Application.  Also having all of your games in one location just makes sense.  If this is not possible lock the thread but i believe at the very least its a useful idea.

**Comment by clobber** [comment]
We don't do launchers, just core plugins.
