### ISSUE TITLE
Most recent update rendered my bluetooth controllers worthless

### ISSUE THREAD

**Issue by saiyantrainer** [OpenEmu/OpenEmu#2848]
I'm using 8bitdo controllers. And NES30 and an FC30 pro. Since I updated, they are totally useless in games. I'm able to update the controller settings and assign buttons just fine, but they will not work during game play. 

I have also tried a USB Logitech gamepad and it works just fine.

**Comment by clobber** [comment]
I have both of those devices and they work just fine in OpenEmu 2.0.3.

**Comment by clobber** [comment]
For 8Bitdo devices:

Get the [latest firmware](http://forum.8bitdo.com/thread-942-1-1.html) and use **Mode 1/Joystick Mode** by holding the START button to power on (or the POWER button on the Pro models).

**Comment by saiyantrainer** [comment]
I tried that on both controllers with no luck.

**Comment by clobber** [comment]
Try completely resetting your mappings:

1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

Also, follow this guide to troubleshoot input problems: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by saiyantrainer** [comment]
Just wanted to respond and let you know that worked. Thanks a bunch for the
help! Love OpenEmu.
