### ISSUE TITLE
Using iPhone as game controller

### ISSUE THREAD

**Issue by jnTracks** [OpenEmu/OpenEmu#2849]
I'm using the Ultimate Control app to use my iPhone as a controller for mac, and it's sooooo close to working.

I have the computer and iPhone talking, and my mac is receiving the keyboard commands when I push buttons on my iPhone as controller.  When I load an emulation in OpenEmu the games play fine and the normal keyboard control works fine.  I can even go to remap the controls and the buttons on the iphone controller are accepted as the new mapping when I push them.  (in other words, when I click on any control in OpenEmu settings, and then push a button on my iPhone, OpenEmu responds and sets that mapping.
But when I return to the game, there is no response to the iPhone button presses.  Mac keyboard still works.

I've tried troubleshooting like making sure other apps aren't running, especially chrome, and doing a reboot to make sure.

Any ideas?

Thanks!

**Comment by cherish520** [comment]
I have the same problem as you!! 
Looking for the answer

**Comment by resistor4u** [comment]
ditto, and i can't seem to get joypad legacy on itunes--every link says it's no longer available on the itunes.

**Comment by jnTracks** [comment]
At some point a person replied to one of my threads saying that there was a known issue with getting it to work with this sort of setup (iPhone acting as keyboard emulations of WiFi) and that it wasn't going to work. Sounded like something they couldn't, or wouldn't, be working around.

I gave up on that and got a Logitech F310 on amazon for less than $15.  It's much better control anyway, and was so cheap.  Works flawlessly with no drivers, etc.
