### ISSUE TITLE
OpenEmu crashes when there is a Touch Bar HID device connected

### ISSUE THREAD

**Issue by shysaur** [OpenEmu/OpenEmu#2851]
### Premise (skip if you want, except if you can't reproduce the bug)
The new MacBook Pros with a Touch Bar are not out yet, but the Touch Bar's implementation is actually present and functional for debugging purposes on all macs which have macOS 10.12.1 build 16B2657 installed. This is a different build than the one that rolled out before the event, which was build 16B2555; the old build does not have Touch Bar support. 

One can open Xcode 8.1 and enable a Touch Bar simulator by choosing "Open Touch Bar" from the Window menu, and then the Touch Bar shows up as a floating window. This floating window seems to work exactly as a real Touch Bar would (it doesn't just work for the app being debugged as someone says, but it is usable and visible from any app on the system).

It turns out that the Touch Bar is driven by two background processes: TouchBarAgent which probably draws the UI, and TouchBarUserDevice, which actually installs a fake HID device which shows up in HID Explorer as having Vendor=1452, ProductID=34304, and advertises itself as a keyboard. This device is used to simulate the keypresses that were previously sent by the physical function key row that the Touch Bar replaces. (This works even in the simulator by the way. That is, when you click the esc key in the Touch Bar simulator the fake HID device's esc key registers, but the physical keyboard's esc key does not register.)

### Why the app crashes
This Touch Bar device does not have a location id, nor a product name, nor a manufacturer name, ... it has no properties except for vendor, product id, and the fact it is a keyboard. When OpenEmu finds this device, it tries to read its location id, and since it has none, it tries to generate one from the product name. But the Touch Bar also has no product name, and thus OpenEmu crashes on a null pointer dereference when trying to read the non-existent string returned as product name.

I don't know if the real Touch Bar will have the same properties, but in my opinion there is a good chance it will; regardless, this bug causes OpenEmu to always crash on launch if you have that build of macOS 10.12.1 installed and you have opened the Touch Bar simulator from Xcode at least once. If you want to make it stop crashing you have to reboot the mac (which can be a major annoyance). Thus, I think this bug warrants being fixed as soon as possible.

I don't have enough knowledge about what properties OpenEmu actually expects HID devices to have, so I'm not sure about what's the best way to fix this bug. The best solution is probably to filter out the Touch Bar from the device list entirely.

### Full crash log
https://gist.github.com/shysaur/ee49a2b86b2b49647cef7252d22cb359
The crash was produced while running the vanilla release version of OpenEmu 2.0.3 thus it has no line number information. It can be reproduced verbatim even with a build from master. The crash happens on line 142 of OEHIDDeviceHandler.m.

**Comment by clobber** [comment]
Thanks for detailing. Someone reported this the other night while testing out the new Xcode and the special 10.12.1 build with Touch Bar support.

So I thought cases like these would already be handled since this commit https://github.com/OpenEmu/OpenEmu-SDK/commit/af8a726282abf3969b27221c7dbfa56b68e325e3 but maybe it's crashing before that point.

**Comment by clobber** [comment]
Should be okay as of https://github.com/OpenEmu/OpenEmu-SDK/commit/3895064628859b2d8531171bb44df70cd4d5f10f

**Comment by shysaur** [comment]
It's fixed indeed.

**Comment by sol33t** [comment]
Is this build on the openemu.org website? I tried downloading the experimental build and it still crashes for me.

**Comment by clobber** [comment]
Just FYI: 2.0.4 update is [now available](http://openemu.org) with the fix and proper support for the Touch Bar.

**Comment by KovuTheHusky** [comment]
Tested 2.0.4-Experimental on a MacBook Pro 15" with Touch Bar and appears to work perfectly fine. Thank you!
