### ISSUE TITLE
DualShock 4 (CUH-ZCT2) not automapping in 2.0.3

### ISSUE THREAD

**Issue by jeffreybox** [OpenEmu/OpenEmu#2853]
I am able to get the PS4 controller to connect wirelessly to my macbook (Sierra 10.12.1), but OpenEmu isn't recognizing it as a PS4 controller.  Manually mapping the buttons is a little problematic due to the +/- functions on the L2 and R2 buttons.  Any thoughts on how to get OpenEmu to automap or recognize the wireless controller as a dualshock 4?

Thanks!

![screen shot 2016-10-30 at 7 05 04 pm](https://cloud.githubusercontent.com/assets/14154735/19840752/f0c1e65c-9ed3-11e6-9540-e9442346186c.png)

**Comment by clobber** [comment]
My thoughts are, you need to be using an official Sony DualShock 4 gamepad. I have one and it works and automaps just fine.

Only two things I can suggest:
* https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-DualShock-Controller-Pairing
* https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by jeffreybox** [comment]
Thanks for the response.  I read both threads, removed the device from my bluetooth preferences, quit all open programs, and restarted the pairing process from scratch.  Unfortunately, OpenEmu is continues to view the controller as "wireless controller" and does not automap.  It is a brand new official DualShock 4 controller.

**Comment by craigerskine** [comment]
There are now 3 different OFFICIAL DS4 controllers. Some have different firmware and work differently. I have 2 of the 3 (the 3rd is the new one that comes with the Slim and Pro models). I found out about the different firmwares because of the RetroPie project. Some controllers work and some don't... the new-ish ones with the newer firmware have problems on the RP.

I wonder if what you are experiencing is because of the different models.

**Comment by clobber** [comment]
@jeffreybox What makes you certain it is "official" and not a clone or knockoff device? As far as I know, all official Sony PS4 DS4's have the vendor ID of 0x054C (1356) and product ID of 0x5C4 (1476) in their HID profiles, which if yours did, OpenEmu would recognize the device as "Sony PS4 Dualshock 4 Wireless" in the app.

You can verify this by:
* With your USB gamepad device plugged in or paired, run this app http://cl.ly/2K1K400t0H3p

* Select your gamepad from the list and then go to File > Export Device Properties and then give us the plist it generates, by uploading to cloudapp, dropbox, transfer.sh, etc.

**Comment by jeffreybox** [comment]
Here is the link to the item I ordered on amazon:  https://www.amazon.com/gp/product/B01LWVX2RG/ref=oh_aui_detailpage_o00_s00?ie=UTF8&th=1

Here is the model number on the back"CUH-ZCT2U Wireless controller" on the back.  

I tried running your HID Browser app, but it will not open - keep crashing.  Any other way to verify?

**Comment by jeffreybox** [comment]
@craigerskine your response is what I'm leaning towards. I bought a new dualshock 4 controller off amazon

**Comment by craigerskine** [comment]
As far as I know it's not possible for any company to make knock off DS4 controllers yet as they would not make a profit. The touchpad and light are too complicated to replicate with cheap components. There might actually be some knock offs out there, but it's highly unlikely at this point in time.

Regardless there are different FW's in Japanese and US DS4 controllers as found out by the RetroPie and Lakka (RetroArch) dev teams.

**Comment by Sperk11** [comment]
I also just recently bought a DS4 controller through the same Amazon link. I am having the same issue as jeffreybox. Here is the Terminal output:

Wireless Controller:
              Address: 1C-66-6D-D4-60-9E
              Major Type: Peripheral
              Minor Type: Peripheral
              Services: Wireless Controller
              Paired: Yes
              Configured: Yes
              Connected: Yes
              Manufacturer: Qualcomm Atheros (0x6, 0x01)
              Firmware Version: 0x0100
              Vendor ID: 0x054C
              Product ID: 0x09CC
              Class of Device: 0x05 0x02 0x2508
              AFH: On
              AFH Map: FFFFFF000FC0FC7F
              RSSI: -45
              Role: Master
              Connection Mode: Active Mode
              Interval: 0 ms
              Host Connectable: No
              EDR Supported: Yes
              eSCO Supported: Yes
              SSP Supported: Yes

**Comment by Sperk11** [comment]
@clobber 

I have the plist file from HIDBrowser. How should I get it to you?

**Comment by clobber** [comment]
Zip it and upload to a service such as cloudapp, dropbox, transfer.sh, etc.

**Comment by Sperk11** [comment]
@clobber 

Ok, I think I did it correctly.

https://dl.dropboxusercontent.com/u/12885617/Wireless%20Controller.plist.zip

**Comment by clobber** [comment]
This is fixed for next release. To try it out now, you could update Controller-Database.plist in the OpenEmu app bundle with the new entry from this latest commit. You will first want to completely reset your mappings by:

1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

**Comment by Sperk11** [comment]
It worked! Thanks!

**Comment by jeffreybox** [comment]
Sorry, I'm still having trouble.  What do I do after following the 4 steps above (OpenEmu is still only recognizing it as "wireless controller")?  Are you saying I need to download/compile a newer version of the app from GitHub?

**Comment by Sperk11** [comment]
Click on the "Code" tab at the top of this page and then click on the OpenEmu folder. Look within that folder for the "controller-database.plist" file. Download it. Then go to your Applications folder. Find OpenEmu, right click, and select show content. Go to the resources folder. Drag the controller-database.plist file you downloaded into this folder. You will be asked to replace the old file. Say yes. Should be good to go from there.

**Comment by jeffreybox** [comment]
@Sperk11 Thanks.  That did the trick.  Works like a charm!  Thanks all
