### ISSUE TITLE
Steam Controller only maps Right Analog as Up-Down

### ISSUE THREAD

**Issue by LibertyBeta** [OpenEmu/OpenEmu#2855]
Version: 2.0.3

Issue: 

Using the most recent OpenEmu and steam drivers, the controller mapping interface only lets you set a right analog stick as up/down, and nothing else. I've seen this behavior with a few other controllers but its the most pronounced with my new steam controller.

**Comment by clobber** [comment]
Works fine for others. I think the proper method for using a Steam controller is as follows:

1) Install Steam and open it.
2) Open Steam Big Picture Mode by clicking the controller icon in the top right of the window.
3) Install controller drivers as necessary from Big Picture mode.
4) Navigate to the configuration gear and enter configuration.
5) Navigate to the controller Configurations button.
6) Select desktop configuration.
7) Search the community for one of many redundant Xbox360 controller presets and choose one.

Once an Xbox360 controller preset is configured, the controller will pretend to be an Xbox controller to most software, so long as Steam is currently running.

Also run through possible issues here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
