### ISSUE TITLE
Probleme PAL version of ps1 game

### ISSUE THREAD

**Issue by finsceal232** [OpenEmu/OpenEmu#2856]
Hey ! i'm new user of OpenEmu, its a really good app.

I have a probleme with pal version of game. i try FF8 FF9 pal and us version, but only pal version don't work. When i start the pal game i can see the Play Station startscreen and then is the screen black. 
i don't know what's happen. Please i need help

**Comment by clobber** [comment]
Assuming you have good dumps of the game that are in bin/cue format, you may also need the SBI subchannel files for certain games. See here https://github.com/OpenEmu/OpenEmu/issues/2510
