### ISSUE TITLE
Wiimote Classic Controler not mapping correctly

### ISSUE THREAD

**Issue by jnTracks** [OpenEmu/OpenEmu#2857]
I'm having good results using a WiiMote as a controller, even added a nunchuck to map the extra buttons to fill out the SNES controller, but I'd rather use a classic controller for better button placement.  
But when I connect the Classic controller to the WiiMote it maps only a few buttons and does them all wrong!

Dpad up sends a Z to openemu
Dpad left sends C
the analog sticks horizontal axis seems to work, 

And that's it; all other buttons on both the classic controller and the wiimote send nothing to OpenEMU when it's connected.  I have to quit and restart OpenEMU and repair the remotes without the Classic Controller connected to get it working the old way again.

Any ideas?  It's not a true nintendo classic controller so is that the issue?  I'll have to go up and test it with my actual Wii to find out if there's something wrong with this hardware...

**Comment by clobber** [comment]
Similar enough to #2371

There is no fix for this as of now.
