### ISSUE TITLE
when will PS2 be possible? and how can I help?

### ISSUE THREAD

**Issue by zzz6519003** [OpenEmu/OpenEmu#2858]

**Comment by clobber** [comment]
No ETA on proposed core ports, if at all. PS2 emulators aren't yet in a good enough state in regards to compatibility and portability.

**Comment by mrvacbob** [comment]
A very experimental Mac emulator can be found here -> http://purei.org

**Comment by AlftheElf** [comment]
5 years on, are we any closer?
