### ISSUE TITLE
OpenEmu 2.0.3 segfaults on start...

### ISSUE THREAD

**Issue by bmironer** [OpenEmu/OpenEmu#2860]
2.0.2 starts fine but 2.0.3 crashes while starting up in  org.openemu.uniqueIdentifiersToDeviceHandlersQueue.

Crashlog attached
[OpenEmu_2016-11-06-193448_hostname.crash.txt](https://github.com/OpenEmu/OpenEmu/files/574037/OpenEmu_2016-11-06-193448_hostname.crash.txt)

**Comment by robotoad** [comment]
2.0.3 is incompatible with 10.12.1 build 16B2657. This issue is fixed in https://github.com/OpenEmu/OpenEmu-SDK/commit/3895064628859b2d8531171bb44df70cd4d5f10f

**Comment by clobber** [comment]
#2851

**Comment by bmironer** [comment]
Thanks! Sorry for the duplicate. I forgot to check the closed issues...
