### ISSUE TITLE
Open Emu Sony Playstation won't recognize

### ISSUE THREAD

**Issue by ratedsc** [OpenEmu/OpenEmu#2862]
I did the bios part and I confirmed that on the Library, Open EMU, Bios folder for all 3 that I needed to drag into. After using Keka to create the Bin and Cue file for Metal Gear Solid, I tried to drag the Cue into the Sony Playstation ,it wants to scan but it ignores it and doesn't pick up the game at all. Not sure why.

**Comment by clobber** [comment]
Possibly a bad dump of the game or incorrect cue sheet. Best we can do is refer you to the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games). You may also want to look for another dump of your game.
