### ISSUE TITLE
Add cover art for ムシャ

### ISSUE THREAD

**Issue by artkiver** [OpenEmu/OpenEmu#2864]
I have looked at the schema for openvgdb.sqlite but that is not really a suitable format for submitting diffs via git, maybe I could give you SQL statements for adding information, but it seems like it is easier to use a tool such as DB Browser to edit table records for most use cases and I don't see much in the way of even a database at https://github.com/OpenVGDB/OpenVGDB and I am not yet familiar enough with your codebase to see where you might update that even though I see there are some redundant, if perhaps unused sets of information under for example megadriv.xml under MAME's sub dependencies.

That said, if you add:

http://reviktra.neocities.org/%E6%AD%A6%E8%80%85%E3%82%A2%E3%83%AC%E3%82%B9%E3%82%BF%20FULL%20METAL%20FIGHTER%20ELLINOR%20Front%20Cover.png for the releaseCoverFront field for releaseID 42950

and 

http://reviktra.neocities.org/%E6%AD%A6%E8%80%85%E3%82%A2%E3%83%AC%E3%82%B9%E3%82%BF%20FULL%20METAL%20FIGHTER%20ELLINOR%20Back%20Cover.png for the same releaseID

and if you want to get really involved:

releaseDescription:

武者ムシャアレスタ ALESTE FULL METAL FIGHTER ELLINOR
Producer: 仁井谷正充 「Masamitsu ”moo" Niitani」https://twitter.com/mooniitani
Composer: 迫田敏明「Toshiaki Sakoda」

releaseDeveloper:

株式会社コンパイル 「Compile Co., Ltd.」

releasePublisher:

東亜プラン株式会社 「Toaplan Co., Ltd.」

releaseGenre:
Action,Shooter,Scrolling,vertical,SHMUP

releaseDate:

 December 21, 1990

Since you only seem to call that information from OEGameInfoHelper.m I am less certain about how to precisely suggest schema changes, but hopefully the cover art will be helpful! If you have other suggestions for how I might be able to improve information in that database I am comfortable with SQL and other building things from source including some of the projects from which you derive code, like mednafen, but am just peering in and don't want to let some suggestions fall through the cracks just because I can't find the precise line of code to diff and submit a pull request.

**Comment by clobber** [comment]
Please open an issue on the OpenVGDB repo since this and that project are definitely separate.
