### ISSUE TITLE
2.0.3 crash on startup - MacOS 10.12.1

### ISSUE THREAD

**Issue by jakemauer** [OpenEmu/OpenEmu#2866]
Hi there! I'm getting crashes on startup.

**Hardware and Software:**
2013 MacBook Pro 15" with nVidia 750M & 16gb ram.
MacOS 10.12.1 
OpenEmu 2.0.3

**General Error**
````
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
````

**Crash Log**
http://hastebin.com/azidofagah.sql

**Attempts to fix**
1. `defaults delete org.openemu.OpenEmu`
2. Deleting `~/Library/Application Support/OpenEmu`
3. Deleting all `openemu` preference files in `~/Library/Preferences`

Still getting immediate crashing on startup with 2.0.3 stable and experimental. Anything else I should try?

**Comment by robotoad** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2851
