### ISSUE TITLE
OpenEmu Crashing on Launch with MacOS 10.12.2 Beta

### ISSUE THREAD

**Issue by Boundarybreaker** [OpenEmu/OpenEmu#2868]
OpenEmu is crashing instantly whenever I try to launch it. The crash log is [here](http://pastebin.com/32yMgGUL). 
Info:
OS: MacOS 10.12.2 (16C41b)

Exception Type:         EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:          EXC_CORPSE_NOTIFY
 
Termination Signal:      Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

It can be replicated by trying to launch OpenEmu and happens every time.

**Comment by robotoad** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2851
