### ISSUE TITLE
Mouse support in Arcade

### ISSUE THREAD

**Issue by cressie176** [OpenEmu/OpenEmu#2869]
First, thanks for OpenEmu, it's an amazing piece of work.

Second, I know that this has been asked [before](https://github.com/OpenEmu/OpenEmu/issues/1108), but don't fully understand your answer

> This is enabled for as many systems as we can support, except Arcade. Available in next release.

Does this mean that 
* Mouse support for Arcade can't be done.
* Mouse support for Arcade will be available in the next release (the answer was posted Jun 2015 so I guess not)
* Mouse support for Arcade is planned, but not available yet.

Thanks.

**Comment by clobber** [comment]
Not available and the Arcade system is generally unsupported.
