### ISSUE TITLE
Inability to resume arcade games since OpenEmu Experimental 2.0.2

### ISSUE THREAD

**Issue by fgimian** [OpenEmu/OpenEmu#2871]
Hi there guys, a problem was introduced in OpenEmu 2.0.2 with arcade games.

I am testing with Mortal Kombat I, II and Ultimate 3.  Simply start the rom, play for a while, close the game and then attempt to resume it.

This worked correctly with OpenEmu 2.0.1, however since 2.0.2 (and also with 2.0.3), a blank screen appears and OpenEmu locks up.  The only way to exit it is to Force Exit at this point.

Any help would be greatly appreciated.  I have reverted to 2.0.1 in the meantime.

Cheers
Fotis

**Comment by clobber** [comment]
#2615
