### ISSUE TITLE
Will OpenEmu support automap Nes Controller?

### ISSUE THREAD

**Issue by nadiamode** [OpenEmu/OpenEmu#2872]
![nes-classic](https://cloud.githubusercontent.com/assets/278774/20243545/aafc7b98-a98f-11e6-889a-d3186992e3ae.jpg)

**Comment by clobber** [comment]
No probably not, since there wouldn't be a way for us to detect it through an adapter. Alternatively, I'd recommend the [8bitdo](http://8bitdo.com/) model which is pretty nice build quality and we can set up automaps for those devices in the next OE release.
