### ISSUE TITLE
"Could not access helper function"

### ISSUE THREAD

**Issue by andrewwang95** [OpenEmu/OpenEmu#2873]
This issue has been resolved with some minor experimentation by myself, but I could not immediately find a similar problem or solution via search, so I thought I'd post it here for reference.

The issue was that, on one instance my computer ran out of memory (MacBook Air Mid-2013, this is a recurring and unrelated issue that I am still trying to figure out) and I was forced to force restart my laptop, as this temporarily resolves the issue. During this time, I was running a game on the PSP core. 

Upon rebooting, I found that I was no longer able to run that specific PSP game, with the error message "Could not access helper function". All other games, including other PSP games, worked fine. 

Upon some investigation I found that somehow the Library.storedata-wal, Library.storedata-shm, and Library.storedata files had become corrupt. Since I wanted to keep my save data, I had initially simply copied over my previous OpenEmu folder found in ~Library/Application Support/OpenEmu after a fresh install, but what is actually needed is to copy everything except for the Library.storedata files. This means that the titles in the Library need to be readded into the UI, even if they already exist in the Application Support folder. 

I suspect that there was a problem communicating between the Application UI and the ISO file, but other than that I cannot offer technical specifications. If anyone actually knows what caused the bug, maybe they can elaborate.

**Comment by clobber** [comment]
This is a core plugin crash, the emulator itself. PPSSPP is still under development and not quite perfect yet, so there will be issues from time to time. Make sure you are using the latest version of OpenEmu (2.0.4 at this time) and the PPSSPP 1.3 core plugin which should now hopefully not have any implementation issues. Beyond that, there is nothing we can do.
