### ISSUE TITLE
OSX Sierra

### ISSUE THREAD

**Issue by BaconWrappedShrimpWithEyes** [OpenEmu/OpenEmu#2876]
I updated my computer to OSX Sierra, or OSX 11, and OpenEmu now repeatedly quits when I try to open it. Is there a way to fix this, or will there be an update coming?

**Comment by robotoad** [comment]
Please post a crash log.

**Comment by BaconWrappedShrimpWithEyes** [comment]
Actually, restarting my computer fixed it, never mind.
