### ISSUE TITLE
Having trouble on multi disk games

### ISSUE THREAD

**Issue by erobles396010** [OpenEmu/OpenEmu#2877]
Im currently trying to add alone in the dark the new nightmare to my library and do the multidisk m3u file but when i drag the .cue file to textmate it comes with 2 tracks so i tried to save them and put the m3u extension and then drag to my library and it does not work any suggestions

**Comment by clobber** [comment]
Make sure to closely follow everything in the disc guide https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game

**Comment by erobles396010** [comment]
i did everything correctly but its not working like the metal gear one for example only had one track this one has 2 what do i do it does not explain that on the guide

**Comment by clobber** [comment]
No, you aren't reading the guide. Tracks have nothing to do with the creation of an m3u file. An m3u file only contains a plain-text listing of all the cuesheets. That is all you need.

**Comment by erobles396010** [comment]
but do i include both track or just use 1 track

**Comment by clobber** [comment]
Again, there are no "tracks" involved. Your m3u file must include a list of ALL the cue's for your multi-disc game. The [directions](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) make this pretty clear.

**Comment by Aeglos711** [comment]
In fact I have exactly the same problem, i provided another game that did not give me 2 tracks and still does not work. 
I did exactly what the guide said, even review tutorial videos and it does not work
