### ISSUE TITLE
Game can't run

### ISSUE THREAD

**Issue by chy9002** [OpenEmu/OpenEmu#2880]
There is error infomation.
/Volumes/Transcend/Home/Library/Application Support/org.openemu.OEXPCCAgent.Agents/org.openemu.OEXPCCAgent.D02308CB-0B7B-4A47-9C4F-A32750707FFB.plist: Path had bad ownership/permissions

**Comment by clobber** [comment]
Saw a few of these in the past. They always turn out to be some sort of permissions or macOS install issue that we have no control over.
