### ISSUE TITLE
DIP Switches

### ISSUE THREAD

**Issue by ApertureSO** [OpenEmu/OpenEmu#2882]
Hi. I'm extremely new to GitHub and have no idea how things work so please excuse me if this doesn't belong here.

I am using the Experimental version of OpenEmu and I see no way to control DIP Switches on arcade games. Can you please implement this?

**Comment by clobber** [comment]
Assuming you are talking about Arcade, the only thing available is the 'Service' menu, details here: #1860

Please keep in mind that Arcade/MAME is 'experimental' and strictly unsupported at this time.

**Comment by jeansebastienbg** [comment]
A workaround for that, if you have access to a PC, is to run the same ROM on MAME, access the Dip Switches menu pressing TAB while the game is running, set the switches and save that Machine Configuration. Then, you go to the cfg folder in your MAME pc version and copy the game's cfg file to the same folder in openemu *USER\Libray\Application Support\OpenEmu\MAME\Cfg . I switched a couple games to a four player mode that way.
