### ISSUE TITLE
'The Emulator Could Not Load ROM'

### ISSUE THREAD

**Issue by AgentPeggyCarter** [OpenEmu/OpenEmu#2883]
I just added a new game, and the game loaded onto the screen, but when I tried to open it, I got the error message 'The emulator could not load ROM.'  It is only happening with games I have loaded recently for the DS, but it's not happening with the GBA games.

![image](https://cloud.githubusercontent.com/assets/23566983/20453173/577539ec-adea-11e6-8605-14c86a764085.png)

**Comment by clobber** [comment]
I am able to load NDS games, including the one selected in your screenshot. Try checking Console.app for messages when you get that error.

**Comment by AgentPeggyCarter** [comment]
What is console.app?

**Comment by clobber** [comment]
https://computers.tutsplus.com/tutorials/how-to-use-console-your-macs-diagnostic-diary--mac-45251

**Comment by AgentPeggyCarter** [comment]
I just checked that, and it said 'ROM did not load'

**Comment by clobber** [comment]
How about restarting your computer and then only launching OpenEmu afterwards and see if you can then run NDS games?

**Comment by AgentPeggyCarter** [comment]
I tried that, but it didn't work.  It's odd that it is only happening with new NDS roms, but it's not happening with new GBA roms.

**Comment by AgentPeggyCarter** [comment]
All of the other NDS games that are on there are working just fine, it's the ones that I've added in the past 3 days that aren't working.

**Comment by clobber** [comment]
Okay, sounds to me like those are bad dumps of the games. Delete the ones that are problems and acquire new copies from another source. Also, if they are compressed (rar, zip, 7z, etc) first extract the files with an application like [The Unarchiver](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) (free on the mac app store) and import just the `.nds` files.

**Comment by Phalaric** [comment]
I've had the same issue. When I import and load new .nds files on 2.0.4 they work, but whenever I try importing and loading the same .nds file compressed as 7z (compressed by myself with 7zX) I get that error. I downgraded to 2.0.3 and now that very same .7z file imports and loads just fine. The strange thing is that all of my previously imported NDS games from before 2.0.4 are compressed as .7z and still load fine on 2.0.4.

**Comment by Rotjochie** [comment]
I have the same problem now, i can't run some pokémon games. It says **Could not load rom**
Hopefully you can help me with this issue.

Sorry for my poor english
Greets Rotjochie
