### ISSUE TITLE
multi disc game issue in mednafen (PS1) openemu 2.0.4

### ISSUE THREAD

**Issue by gh0sti** [OpenEmu/OpenEmu#2885]
Ok I am on 2.0.4 latest version, have followed this guide to a t https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game . And Openemu won't recognize nor import my .m3u files that I have made in plain text and copied over the correct names of the .cue files. Now do I have to have my multi disc games removed from openemu to get it to work otherwise idk how to get multi disc games to import into openemu

**Comment by clobber** [comment]
>Now do I have to have my multi disc games removed from openemu to get it to work 

Yes, games should not be pre-imported. Just create the m3u file and have it in the same folder as your cue sheets and bin files, and OpenEmu will automatically import everything as you drag and drop in the m3u file.

**Comment by gh0sti** [comment]
btw that did fix it thank you I appreciate it
