### ISSUE TITLE
[SUGGESTION] Automatic Switching of "Controls"-Tab during Gameplay

### ISSUE THREAD

**Issue by adrianmkofficial** [OpenEmu/OpenEmu#2886]
During gameplay when the user accesses the "Controls"-Tab in Preferences to switch Controller Mappings, the currently selected / shown controller should automatically switch to the system currently in use.

For example if the user has a NES Emulation running and decides to switch some buttons in his controller mapping, he opens up "Preferences -> Controls" but currently sees the controller that has most recently been mapped. This could happen to incidentally be already the NES controller but it could also be e.g. the GameBoy Controller and thus requiring the user to make an additional step before he can start assigning buttons.

This is really just a small UI-style issue but if it can be fixed within a couple of lines of simple code it'd contribute greatly to the 'It just works' philosophy which the OpenEMU Project shares proudly with the platform it runs on.

**Comment by clobber** [comment]
This already happens as you are running a game and you click the HUD bar cog wheel -> "Edit Game Controls"
