### ISSUE TITLE
All save data deleted upon installing update 2.0.4

### ISSUE THREAD

**Issue by reginleif45** [OpenEmu/OpenEmu#2889]
Um... was this supposed to happen? I don't remember losing everything when I updated previous versions.

**Comment by clobber** [comment]
No, and there wasn't any code in the update that could do that. Any specific details you can provide?

**Comment by reginleif45** [comment]
After the update was added, OpenEmu kept crashing immediately upon opening it, (but that had happened before without problems, so I didn't pay it any mind). When I was finally able to start a game(s), they were all blank. The save states (regular ones, quick, & auto save states), screenshots, etc., hadn't been removed though.

**Comment by clobber** [comment]
Kept crashing? Any crash logs to share? Which games and systems? Be specific.

It sounds like to me that you mixed up save states and in-game saves. Loading a save state will completely restore everything that was in memory at time, including the state of the in-game battery/mem card save and overwrite it.

**Comment by reginleif45** [comment]
Sorry for not being specific enough >< I'm not exactly familiar with this sort of thing so I don't know what information I need to provide...

But I did a second check just to be sure. I do know the difference between the ingame save and the save state; what I meant to say was that I'd lost ingame saves but nothing else. It only affected Game Boy Advance games (Fire Emblem: Binding Blade, Fire Emblem: Blazing Sword, Fire Emblem: The Sacred Stones, if you want the titles).

And yes, I was able to recover a bit of progress by loading save states. I didn't have very many though so it wasn't extremely helpful, especially since the last auto save state (which contained progress from before I updated) was overwritten a few seconds after I opened the blank game.

**Comment by clobber** [comment]
Don't know what else to do for you, but I think there is some confusion regarding save states.There wasn't anything in 2.0.4 that affected battery save files or save states for GBA games.

Whenever you restore an autosave state or manually load a save state, it will overwrite everything in memory including the state of the battery save with the progress from the time of that state. That means if you loaded a state that was made previously to your current progress, your current progress is lost unless you also have a save state of it. Once you go back in time, there is no returning to where you were without save state files to recover that.

Regarding autosaves: If you had previously clicked "Yes" and the "don't ask me again" checkbox on the alert that prompts you to "continue where you left off" when you load a game, it will always restore the last autosave (created at shutdown from the last time you ran the game). If you would like to reset that alert, go to OpenEmu > Preferences > Library and click "Reset warnings."

Also, If you are using the VisualBoyAdvance core plugin, I recommend migrating your battery saves to the mGBA plugin (see the handy [guide here](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files)).
