### ISSUE TITLE
Can't make changes to my controls.

### ISSUE THREAD

**Issue by PokeManiac4459** [OpenEmu/OpenEmu#2892]
Hello OpenEmu, with the recent 2.0.4 openemu out I downloaded it and started using it. Im on OSX Sierra and the controls were changing fine a couple of hours ago. Im not sure what went wrong so i would appreciate the help. Going threw pokemon games without turbo speed is kind of a pain.

**Comment by clobber** [comment]
>were changing fine a couple of hours ago

Not going to be an issue with OpenEmu. Check the [input troubleshooting guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for solution(s)
