### ISSUE TITLE
cheat too long don't know how to adjust it for openemu

### ISSUE THREAD

**Issue by JoJoGlory** [OpenEmu/OpenEmu#2893]
BA5E9E05 D1FAE4A6
BDA65F34 AF5A7B09
BCE1B8B2 F28DD1A0
7F274920 3B7376A3
54DAC339 8C2C1DC4
BE0E7574 0BDF821E
7D802310 055815DE
BDA65F34 AF5A7B09
DB077F87 60FDDD1B
BDA65F34 AF5A7B09
BDA65F34 AF5A7B09
8B6C261F 0F5FC925
BDA65F34 AF5A7B09
35E3FBA6 FB6DC8B4
BDA65F34 AF5A7B09
2985E353 232FAED5
CC6C7A3A D0879B59
BDA65F34 AF5A7B09
BDA65F34 AF5A7B09
8AB0EAB8 5DDAEC6C
can you help me out 
@clobber

**Comment by clobber** [comment]
The [cheat guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes), specifically "For multi-line codes, use a plus (+) to separate each line."

In your case, that means:
`BA5E9E05 D1FAE4A6+BDA65F34 AF5A7B09+...+...`

**Comment by JoJoGlory** [comment]
yeah i tried it, but won't work

**Comment by clobber** [comment]
There's a lot of junk on the web and many mislabeled or just plain wrong cheat codes. Read through the guide and make sure you have the right code for the version and region of the game you are using.
