### ISSUE TITLE
app keeps crashing after 2.0.4 update

### ISSUE THREAD

**Issue by rnailer** [OpenEmu/OpenEmu#2894]
hi,

I have updated to 2.04 and now the app keeps crashing on me when I launch a game or open prefrences.

Attached is the apple error log.

Im running OSx el Capitan ver 10.11.6
[OpenEmu [988].pdf](https://github.com/OpenEmu/OpenEmu/files/603300/OpenEmu.988.pdf)

**Comment by GatecrasherUK** [comment]
Same here.. updated through the emulator page and now can't set up any controllers without crashes, and will crash very randomly between games =( why release an update that isn't 100% usable?? .. great shame because the program is the best out there .. thanks.

**Comment by clobber** [comment]
@rnailer 

To fix your crash:

1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

**Comment by GatecrasherUK** [comment]
Hello Clobber .. can I just show you my error report .. I can probably tell you now, all this is probably my fault, the disappointment shown, is because its so frustrating when such a great program just stops! but like i said, probably due to a fault this end.
[OpenEmu 2.zip](https://github.com/OpenEmu/OpenEmu/files/604501/OpenEmu.2.zip)

**Comment by clobber** [comment]
@GatecrasherUK Follow the exact same steps above to resolve your issue.

**Comment by rnailer** [comment]
@clobber thanks that fixed the issue

**Comment by GatecrasherUK** [comment]
@clobber ..Yes same here! lol .. thanks =)
