### ISSUE TITLE
8Bitdo N64 Gamepad

### ISSUE THREAD

**Issue by DrunkenPilot2** [OpenEmu/OpenEmu#2897]
I am having a hard time connecting two controllers to my mac book air and open emu.  One works great in Mode 2 and one works great in Mode 1.  When turn one on in mode 1 and one on in mode 2 they both don’t want to work in open emu and if I turn them both on in mode 2  it doesn’t work, do you have any suggestions.

**Comment by clobber** [comment]
All 8Bitdo devices should only be used with the [latest firmware](http://support.8bitdo.com/) and in Mode 1/Joystick Mode.
