### ISSUE TITLE
Crashes when starting a new game

### ISSUE THREAD

**Issue by npartlow** [OpenEmu/OpenEmu#2899]
When i closed one of my games in openemu i tried opening another game and the emulator crashed on me. I never had this problem before until 2.0.4 was released so there must be something wrong with the new update.

**Comment by clobber** [comment]
Please provide exact steps to replicate the crash and also paste the crash log here.

**Comment by clobber** [comment]
As well as details about which games/systems you were loading.

**Comment by npartlow** [comment]
it's been happening to all the systems: Mupen64, PPSSPP, PSX, etc., it's the same problem that everyone else is experiencing from Openemu 2.0.3

**Comment by npartlow** [comment]
2.0.4
