### ISSUE TITLE
GBA Crashing

### ISSUE THREAD

**Issue by coolio1028** [OpenEmu/OpenEmu#2902]
I am trying to play Pokemon Emerald after updating to the newest version of openemu. I'm using mGBA as the default core and I have crash report. Please help me figure out what's wrong.

CRASH REPORT: [OpenEmuHelperApp_2016-11-23-132236_ryans-iMac copy.crash.docx](https://github.com/OpenEmu/OpenEmu/files/609717/OpenEmuHelperApp_2016-11-23-132236_ryans-iMac.copy.crash.docx)

**Comment by clobber** [comment]
That crash report says you are using VisualBoyAdvance for that game - crash looks VBA related (now deprecated) so we won't investigate that. See the [Default Cores guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Default-Cores) and the [Save File Transfer guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files) switching to mGBA.

**Comment by coolio1028** [comment]
How do I switch a savestate though.

**Comment by clobber** [comment]
You cannot transfer save states, those are not compatible between emulators. Save in-game and then transfer your battery save.
