### ISSUE TITLE
no logro grabar subir juegos a la biblioteca

### ISSUE THREAD

**Issue by chanketito** [OpenEmu/OpenEmu#2903]
hola buenas soy un poco novato en esto,me descargue openemu y empece a descargar juegos,he descargado unos 5 y no se porque ahora me descargo juegos y los intento pegar en la biblioteca pero no se cargan
que hago???
los juegos de cartuchos hay que descomprimirlos???comprimirlos???
bajo juegos desde [link removed]
agradezco su ayuda
gracias

**Comment by clobber** [comment]
You probably need to unzip them. Get "The Unarchiver" free in the App Store, extract them and then import the ROM files. Keep in mind that disc based games cannot be imported when zipped.
