### ISSUE TITLE
no puedo conectar el mando d ps4 x bluetooh

### ISSUE THREAD

**Issue by chanketito** [OpenEmu/OpenEmu#2904]
hola 
enchufo mi mando de ps4 con cable y va bien pero no encuentro el dispositivo x bluetooh en my imac
que hago?!?!?!

**Comment by clobber** [comment]
Follow the guide, its why we have them: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-DualShock-Controller-Pairing
