### ISSUE TITLE
como puedo grabar juegos de cd en openemu???

### ISSUE THREAD

**Issue by chanketito** [OpenEmu/OpenEmu#2905]
hola 
intento grabar juegos de play1 en open emu pero no me deja
como debo de hacer???
y el final fantasy 7 que es de tres cds??
soy novato x favor me podeis ayudar pero en sencillamente como si hablaseis con alguien que no sabe mucho de esto?
gracias

**Comment by robotoad** [comment]
To play CD-based games, you must follow the [disc import guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games).
