### ISSUE TITLE
USB keyboard won't work

### ISSUE THREAD

**Issue by omegahm** [OpenEmu/OpenEmu#2909]
When I launch a game, my USB keyboard doesn't respond.

I can map the game controller fine with the USB keyboard, however when I try to actually use it in game, nothing happens. I can use the keyboard on my MacBook just fine at the same time. Is there a setting somewhere, that I am missing?

OpenEmu does respond to cmd+q from the USB keyboard

---

I am running OpenEmu 2.0.4 (639-g606b287-Release) on a MacBook Pro (Retina, 13-inch, Early 2015) with macOS Sierra 10.12.1 (16B2555)

**Comment by omegahm** [comment]
It works fine with my bluetooth Apple keyboard.

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
