### ISSUE TITLE
Higan v101 update to OpenEmu ?? 

### ISSUE THREAD

**Issue by azoreseuropa** [OpenEmu/OpenEmu#2910]
They have WonderSwan Color and WonderSwan in Higan v101. Why aren't you updating it to OpenEmu 2.0.4 ? :(

We are waiting for Vertical to work properly in Mednafen so Higan v101 might be our only open for OpenEmu.

**Comment by clobber** [comment]
Higan breaks save state compatibility between releases. Not something we will be keeping up to date with currently.
