### ISSUE TITLE
OpenEmu refuses to launch any game

### ISSUE THREAD

**Issue by ApertureSO** [OpenEmu/OpenEmu#2911]
I am on MacOS sierra and for some reason on both OpenEmu experimental and stable, it refuses to launch any game. I tried restarting with no luck. Could I please have some help? It just happened today.

**Comment by clobber** [comment]
Provide specific details.

**Comment by ApertureSO** [comment]
@clobber When I double click any game, or right click and click Play Game, it simply does nothing.
The only thing that partially works is Homebrew, where I can double click and add it to my library, however when I double click the homebrew game in my library, it doesn't even give me the download window.
I've tried launching save states too.
Nothing works at all.

**Comment by clobber** [comment]
Try a restart.

**Comment by ApertureSO** [comment]
@clobber I've restarted both my macbook and the software.

**Comment by clobber** [comment]
Then provide output from Console.app when the problem happens.

**Comment by ApertureSO** [comment]
@clobber How do I do that?

**Comment by ApertureSO** [comment]
Hold on, I think I found the issue. It seems that it was because of a corrupted ROM.
For some reason restarts work NOW.
Issue fixed, closed.
