### ISSUE TITLE
Arcade joystick sensitivity

### ISSUE THREAD

**Issue by TheDennysODST** [OpenEmu/OpenEmu#2913]
Hi I recently got the arcade fixed in my openemu sidebar and I was playing Jurassic park (shooter on rails) to test it out and i noticed that the joystick sensitivity is really high, like I would barley move the joystick on my wii nunchuck in any direction and the crosshairs would instantly move to the side of the screen. I was wondering if there was anyway to lessen the sensitivity so i would be able to actually aim, or if I would have to wait for a patch. I would also like to note that I really like openemu and it made playing roms and downloading emulators really easy and I would like to thank the developers for their hard work.

**Comment by clobber** [comment]
Arcade/MAME is 'experimental' and thus unsupported at this time. It is also missing support for other input types (such as analog).

#1085

**Comment by TheDennysODST** [comment]
ok Thanks Clobber for the info
