### ISSUE TITLE
Feature suggestion: pop-out menu for filters

### ISSUE THREAD

**Issue by toolsquatch** [OpenEmu/OpenEmu#2914]
Just added all the extra filters from the "common shaders" section, and it'd be great if you could pop out the filter window and navigate all of the filters with arrow keys instead of having to manually go into the filter tab and change over one by one.

**Comment by clobber** [comment]
One of those things that could be "nice to have" but overall not useful enough to warrant spending time adding something like that to the UI. Especially with support for Cg shaders being deprecated.

**Comment by toolsquatch** [comment]
Is there a detailed guide for there filters available anywhere then? Not sure what I'm looking at or what the purpose for some of the filters is supposed to be, it'd make finding the desirable effect I'm looking for easier to find in that exhaustive list (added them all at once so there's hundreds of filters).
