### ISSUE TITLE
Keyboard Mapping for Tron

### ISSUE THREAD

**Issue by robwired** [OpenEmu/OpenEmu#2915]
I was able to get the Tron arcade game working but whether I use a keyboard or a joystick the button mapping doesn't seem to work correctly. For example, in the scene with the spiders if you move left or right Tron's arm will spin 360 degrees. 

Does anyone else have this problem or is it a known issue?

**Comment by clobber** [comment]
Arcade/MAME is 'experimental' and thus unsupported at this time. It is also missing support for other input types (such as analog).

#1085

**Comment by robwired** [comment]
Where can I see a roadmap, for example, when support might be added for analog input, mame roms beyond .57 or just to see what is upcoming? So curious!
