### ISSUE TITLE
Metal Slug Bios

### ISSUE THREAD

**Issue by GatecrasherUK** [OpenEmu/OpenEmu#2916]
@ Clobber!!! ..
Hello .. sorry if this sounds lame to most, but I'd like a few games to add to my OpenEmu library .. but for some reason the Metal Slug series/Samurai Showdown etc I cant get working at all.. can someone help? Thanks =) SimonUK

**Comment by clobber** [comment]
Arcade/MAME is 'experimental' and thus unsupported at this time. I'm sure if you search neogeo and metal slug you can find some information on what is missing.
