### ISSUE TITLE
No Select Cheats Option

### ISSUE THREAD

**Issue by Redfernx** [OpenEmu/OpenEmu#2919]
At first I think I was using version 1.0.4 and the HUD bar was missing - I couldn't find any option to hide or unhide it so I trashed that version and downloaded the newest version from your site.  The HUD bar reappeared, but now there is no cheats option.  I have tried closing and re-opening it, going back to the old version, the new version again, I don't know what to do.  I've used cheats on my DS games before (which is what I'm trying to do now) so I know they work, I just can't get to them anymore.

**Comment by clobber** [comment]
Need to be using the latest version of OpenEmu and have our Desmume 0.9.11 core port (check OpenEmu > Prefs > Cores to confirm).

OpenEmu 1.x is unsupported.
