### ISSUE TITLE
Games showing under incorrect system

### ISSUE THREAD

**Issue by StuMcBill** [OpenEmu/OpenEmu#2920]
I've copied a bunch of games into my OpenEmu library, however, some of the games are showing under the incorrect system.

For example (PSX) Destruction Derby and Advance Wars are showing up under Arcade for me, when this is a PS1 and Game Boy Advance game respectively.

Is there anyway I can force these into the correct system?

Stewart

**Comment by clobber** [comment]
CD-based games cannot be compressed, so unzip your PS1 games and import the cuesheets. For your other game, there are probably multiple files inside the archive so you also need to unzip it and simply import the .gba ROM file.
