### ISSUE TITLE
Migrated game library and preferences to new machine hangs until "defaults delete org.openemu.OpenEmu lastSaveStateEventID"

### ISSUE THREAD

**Issue by clobber** [OpenEmu/OpenEmu#2921]
Something to investigate. I got a new machine and migrated my OpenEmu install, both app support folder and org.openemu.OpenEmu.plist, and when opening the app it would hang until I ran `defaults delete org.openemu.OpenEmu lastSaveStateEventID` in Terminal.

**Comment by SpeakingColors** [comment]
I lost a lot of my games that I cannot put back in Open Emu nor relocate my Game Library by trying to move it to my second hard drive like it always been.
