### ISSUE TITLE
Fullscreen mode causes OpenEmu to freeze

### ISSUE THREAD

**Issue by parasyte** [OpenEmu/OpenEmu#2923]
Version: 2.0.4
macOS: 10.12.1 (16B2555)

Steps to reproduce:

* Start a game
* Enter fullscreen
* Exit fullscreen
* Stop the game
* Start the game again

At the last step, video will not be displayed (black screen) but the game seems otherwise playable. Doing anything else in OpenEmu at this point will cause it to beachball until you force-kill it.

Here's a spindump on the frozen OpenEmu process: https://gist.github.com/parasyte/7dd39bce5819990b669ca0dc8080752a

**Comment by clobber** [comment]
#2888
