### ISSUE TITLE
PSX Games not loading....

### ISSUE THREAD

**Issue by karahartauthor** [OpenEmu/OpenEmu#2926]
Hey there, I downloaded FFVII recently and it came as a .bin file. I created a .CUE file like you said to in the guide and did it in the right manner. Both the bin and the cue file are in a folder together. I then drop the folder into the openemu and it seems to load for a second, but then nothing happens. Nothing at all. How the heck do I get the game to show up? It's really causing me to get annoyed. Please help

**Comment by clobber** [comment]
Probably a bad rip of the game. Just download another copy that also has the cue sheet. Also, that game is multiple discs so you would need to instead follow the [directions for multi-disc games](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game).
