### ISSUE TITLE
Mass relink and find moved roms

### ISSUE THREAD

**Issue by themesser** [OpenEmu/OpenEmu#2927]
I moved my game library to an external hard drive, before cleaning, sorting, and importing missing artwork.
Now all roms are offline. Is there a way to change the global path (or use a relative path) to my roms, so I don't have to restart from scratch ?
I tried edit the opened library with a text editor, but it's not XML or understandable..

**Comment by clobber** [comment]
Try OpenEmu > Preferences > Library > Change...

**Comment by themesser** [comment]
not working, moves the library ut does not automatically relink roms.
Is there a way to change all path from Users/me/Roms to Volumes/ExternalHarddriveDrive/Roms

**Comment by clobber** [comment]
Yes it does work. The procedure to move your Game Library (which *is* your ROMs) to another location, is to go to OpenEmu > Preferences > Library > Change... and OpenEmu will automatically move the Game Library folder (which *does* contain your ROMs) to your new specified location.

If you did it any other way, there is nothing I can do to help you.
