### ISSUE TITLE
Mednafen PSX analogue stick range

### ISSUE THREAD

**Issue by jbwzrd213** [OpenEmu/OpenEmu#2928]
In the Mednafen core, the DS3 and DS4 controllers (and I'm sure a few other ones) have a strange range of movement that causes an issue with Mega Man Legends 2 (PSX). The Mednafen documentation goes more in depth about it here: http://mednafen.fobby.net/documentation/psx.html#Analog+Sticks+Range+Issues

The issue arises when trying to move in a precise diagonal direction (45º, 135º, 225º, and 315º). When doing so, the character (Mega Man) will start walking instead of running.

The Mednafen documentation has a workaround where it suggests increasing the sensitivity of the analogue sticks, but there's no way to do this in the emulator.

**Comment by clobber** [comment]
This sort of falls under #1303 once we get to it, but we can look at a core setting for just Mednafen. I have that game and those gamepads (and various other analogs), so I'll check it out for next release.

Adding the line `MDFNI_SetSetting("psx.input.port1.dualshock.axis_scale", "1.33");` under [mednafen_init](https://github.com/OpenEmu/Mednafen-Core/blob/master/MednafenGameCore.mm#L117) might fix it.

**Comment by clobber** [comment]
Added in https://github.com/OpenEmu/Mednafen-Core/commit/3247fcf46efb6a9c7f7f71bb1697c4ebc7bf2d65
