### ISSUE TITLE
Multi-disc

### ISSUE THREAD

**Issue by karahartauthor** [OpenEmu/OpenEmu#2929]
Hey there, just figured out how to load my game correctly. It's a multi-disc, so I followed your instructions and used Textmate to make a .m3u file with the three .cue's involved. I'm not on disc 2 yet, but how do I know if it worked? Should it give me the option to switch to disc 2 or 3 even though I'm not that far into the game yet? Or will I just have to find out when I get there? Thanks

**Comment by clobber** [comment]
If you imported all your games correctly and have loaded the the m3u, it will work as demonstrated in [the multi disc guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) via the HUD bar.
