### ISSUE TITLE
Update spanish localization

### ISSUE THREAD

**Issue by pulsedrivervstibby** [OpenEmu/OpenEmu#2930]
Hallo Clobber,

I send you a spanish localization update to include.

I send this update to Chris via email but I don't have response from him.

I need you help to finish all localization with these strings:

"A version of this plugin is already loaded" = "A version of this plugin is already loaded";

"Device Disconnected" = "Device Disconnected";

"Device number %lu, %@, has disconnected." = "Device number %1$lu, %2$@, has disconnected.";

"Downloading %@…" = "Downloading %@…";

"Error!" = "Error!";

"Installing Core" = "Installing Core";

"Locate '%@'" = "Locate '%@'";

"New Folder" = "New Folder";

"Resolve Issues" = "Resolve Issues";

"ECM compressed binary detected." = "ECM compressed binary detected."; /**/ // TODO

"ECM compressed binaries cannot be imported. Please read the disc importing guide." = "ECM compressed binaries cannot be imported. Please read the disc importing guide."; /**/ // TODO

Can you send me a screenshots to see these strings on openemu?

I have found the following strings in a localizable.strings that do not appear in source code, can you delete from all localizable strings?

"Couldn't connect to the background process." = "Couldn't connect to the background process.";

"Save to Slot %d" = "Save to Slot %d";/**/

"Slot 1" = "Slot 1";/**/

"The background process couldn't be launched" = "The background process couldn't be launched";/**//*no aparece en el codigo*/

"The root proxy object is nil." = "The root proxy object is nil.";/**//*no aparece en el codigo*/

"Your library was moved sucessfully. OpenEmu must relaunch now!" = "Your library was moved sucessfully. OpenEmu must relaunch now!";/**//*no aparece en el codigo*/

"Always show BIOS preferences" = "Always show BIOS preferences";

I wait your response.

Thank you for all. PvD.

[es.lproj.zip](https://github.com/OpenEmu/OpenEmu/files/629114/es.lproj.zip)

**Comment by clobber** [comment]
Hi, please submit a [pull request](https://github.com/OpenEmu/OpenEmu/pulls) with your changes. You can even edit files right from GitHub now.

**Comment by pulsedrivervstibby** [comment]
Hallo Clobber,

i have problems to create a pull request, can you help me?

Thank you for all.  PvD.

**Comment by clobber** [comment]
Try GitHub's documentation on [Pull Requests](https://help.github.com/articles/creating-a-pull-request/).

**Comment by pulsedrivervstibby** [comment]
Hallo Clobber,

i have forked Openemu/openemu to pulsedrivervstibby/openemu.

uploaded a spanish files into a es.proj

pull request and merged

but I don't see in openemu/openemu my changes.

Can you help me again?

Thank you for all.  PvD.

**Comment by clobber** [comment]
You need to make the changes in your repo and then open a pull request in **our** repo, OpenEmu/OpenEmu, not your repo.
