### ISSUE TITLE
.cue files not being added

### ISSUE THREAD

**Issue by SeanPick07** [OpenEmu/OpenEmu#2931]
I'm running the latest OpenEmu version and I've played FFVIII disc 1 to the end. Problems started when I tried to make the multi-disc system work. I used TextMate to create the .m3u file but I only used the first two discs' files, just to see if it worked.
I then dragged it in the OpenEmu app but nothing happened. From this point I started trying to add the third and fourth disc's .cue files with no results, the game scan bar didn't even show. 
Deleting previously added .cue files and re-adding them didn't work as well.
Completely uninstalling and re-downloading OpenEmu didn't solve the problem which persists just for .cue files.
I've checked the .cue files and they are saved like this:
![schermata 2016-12-04 alle 12 39 55](https://cloud.githubusercontent.com/assets/24368643/20865909/2056a31a-ba1f-11e6-9e45-be1baf8e9a6d.jpg)
What can I do?

**Comment by clobber** [comment]
Follow the [guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game). If a m3u file does not import, then it was either not set up correctly or there are issues with the cue sheet not being formatted correctly or filenames not matching up. It is also possible to have a bad rip of the game in which case you need to download another elsewhere.
