### ISSUE TITLE
Open emu 2.0.4 won't import Sega Saturn games

### ISSUE THREAD

**Issue by Razor96** [OpenEmu/OpenEmu#2933]
tried with Radiant silvergun i have both the .bin and the .cue files and they both work on standalone yabause but for some reasons open emu won't take them tried to drag and drop them nothing it just shows the scanning games bar for a brief second and then nothing, tried to manually copy/paste the 2 files in the sega saturn library folder still nothing i don't know what to do!

**Comment by PlutoX86** [comment]
Same problem here with Resident Evil (U)..

**Comment by PlutoX86** [comment]
Update: I couldn't import Sega Saturn .cue files too,.. even if i enabled "manually choose system on import". I checked the .cue and everything seemed correct.. But it still didn't import the game. 

Then i made my own .cue with 'Cue Sheet Generator', and BÄM! it worked! ;)  

![recue](https://cloud.githubusercontent.com/assets/10595183/20881630/85ccb43c-badd-11e6-87b4-bc9936ea8e9d.png)

**Comment by clobber** [comment]
Please don't open issues for CD import errors. These files import just fine provided you:
1) Have a good dump of the game.
2) Have a properly formatted cue sheet that was included with your dump of the game.
3) Have imported your file via the cue sheet.
4) Have read the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) to understand CD file importing.

@PlutoX86 You cannot simply create a cue sheet for a game if it did not include one. Your cue sheet isn't even correct for that game -- it's missing the Audio track! Just download another copy from somewhere else.

**Comment by PlutoX86** [comment]
I'm sorry to reply again, but as i said, the game runs perfectly fine with that exact cue sheet i made (i.e. cutscenes, sound effects & background music). 

The original one (with the audio track listet), did not work. Maybe it wasn't saved in the correct format. Doesn't matter anyway ;)
