### ISSUE TITLE
OpenEmu 2.0.4 - Multi Disc games can't be added with the .m3u file

### ISSUE THREAD

**Issue by Torty85** [OpenEmu/OpenEmu#2934]
Hello, I wanted to add a multi disc games with the m3u file, but it isn't working. why can i  not longer add multi disc games? Which is the mistake i have done? Or is there an other option to use multi disc games?

Thank you for your Help.
Torty85

Here the pic of my m3u-file.

<img width="504" alt="bildschirmfoto 2016-12-05 um 16 25 08" src="https://cloud.githubusercontent.com/assets/24391609/20890503/6a06990a-bb07-11e6-8145-ca2a78bdcf0f.png">

**Comment by clobber** [comment]
See the updated [guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game). The process changed a bit in OpenEmu 2.0.4.

**Comment by Torty85** [comment]
Hello Cobber,

Thank you for the Link. Unfortunately it does not work for me like its written in the guide you have gave me the link. i have done all exactly how its written. i have create a folder with all the files (have a look on the pic1) and i have create a m3u file with all the filenames of the cue sheets (pic 2) … what is the problem, did i have done a mistake?

Thank you for your help.

Daniel Jordi
