### ISSUE TITLE
The emulator could not load rom

### ISSUE THREAD

**Issue by letdowntown** [OpenEmu/OpenEmu#2937]
I installed MAME core, I downloaded a rom for .149. I dragged it into the OpenEmu window and the name changed from the filename to the name of the game. I clicked on the game and a window popped up that said "The emulator could not load ROM." I looked at the error in Console, and all it said was "ROM did not load." I do not understand what's going on. How can I fix this?

**Comment by clobber** [comment]
Sorry, Arcade/MAME is 'experimental' and unsupported right now. You are properly missing some required files which Console.app may be logging.

I'd recommend using a standalone version of MAME instead.

**Comment by ylluminate** [comment]
Would still love to see MAME supported more robustly. I'm wondering if you can't just lock in a specific version that has proven to be one of the more supported (available) releases vs trying to be a solve all situation. That would at least make a case for testability / reproducibility.
