### ISSUE TITLE
3rd Party Playstation Controller

### ISSUE THREAD

**Issue by toolsquatch** [OpenEmu/OpenEmu#2940]
I know there's a detailed guide on how to set up Dualshock 3 and 4 controllers which explicitly states that 3rd party controllers are unsupported, but is there any chance that that will change? I'm able to get my 3rd party controller to function perfectly with a different Playstation Emulator and all the 3rd party controllers for NES, Genesis, SNES, and N64 get along with the emulators just fine so it's strange that OpenEmu won't play nice with this controller.

**Comment by clobber** [comment]
>any chance that that will change

No, not likely. Especially if it happens to be a knockoff PS3 model.

**Comment by toolsquatch** [comment]
Why are 3rd party Playstation controllers specifically unsupported though?
