### ISSUE TITLE
Downloading NDS Mario Kart ROM

### ISSUE THREAD

**Issue by simplyandy** [OpenEmu/OpenEmu#2941]
I've tried several different versions of the mario kart NDS rom but it simply wont download. I have other DS games saved and as the same format (.7z). They all work fine. I've tried restarting openemu and my mac. Does anyone have it downloaded or have any suggestions?

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2681#issuecomment-235673594
