### ISSUE TITLE
dual shock 4 crashing 

### ISSUE THREAD

**Issue by G8mer82** [OpenEmu/OpenEmu#2942]
open emu is crashing with the use of dual shock 4, it wont register the device under controllers, when I click on any of the games while its connected . it just crashes the application.

please can you help

not sure if this is any uses  and I'm not to familiar with the Mac OS  and reports and what to post

heres a few lines from the apple crash report:

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: org.openemu.system.OEBindingsController

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

hope this few lines are useful.

**Comment by robotoad** [comment]
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.
