### ISSUE TITLE
help with some strings in spanish localization

### ISSUE THREAD

**Issue by pulsedrivervstibby** [OpenEmu/OpenEmu#2943]
Hallo Clobber,

I need your help with the following strings to finish a spanish localization:

"A version of this plugin is already loaded" = "A version of this plugin is already loaded";

"Device Disconnected" = "Device Disconnected";

"Device number %lu, %@, has disconnected." = "Device number %1$lu, %2$@, has disconnected.";

"Resolve Issues" = "Solucionar errores";

"Grid Size" = "Grid Size";

"View Mode" = "View Mode";

"Category" = "Category";

"ECM compressed binary detected." = "ECM compressed binary detected.";

"ECM compressed binaries cannot be imported. Please read the disc importing guide." = "ECM compressed binaries cannot be imported. Please read the disc importing guide.";

I need a screenshots of openemu to see these strings.

And I need a description of an option "Cleanup rom hashes" in a secrets preferences.

I wait your response to finish all spanish localization.

Thank you for all.  PvD.

**Comment by clobber** [comment]
Sorry, I'm not going to go through the app and screenshot these. Some are tooltips and the rest are alerts, so I don't know what other useful context we could provide. Maybe you want to switch your own language to English and then go through the app to find them.

**Comment by mrvacbob** [comment]
Some of those are tooltips for the controls in the browser (the size of game icons and switching list/box view). The rest aren't important.

**Comment by pulsedrivervstibby** [comment]
Hi mrvacbob, when I do a translation I try to do it in the best possible way so I need to see how those strings appear inside the application.

All the strings that are translated I have been able to verify as they appear in the application except the previous strings that I can not generate.

This is the reason because I need help using a screenshot or with an example of how to generate these strings.

Greetings. PvD.
