### ISSUE TITLE
"Recently Added" Collection Timeframe

### ISSUE THREAD

**Issue by digamejh** [OpenEmu/OpenEmu#2944]
Hi, I was just wondering how the "Recently Added" Collection in the sidebar works.  It automatically contains recently-imported games (as the name suggests), but they seem to stay there for months.

Is it possible to customize the timeframe that games appear there, or can that be a future addition?

Thanks!

**Comment by clobber** [comment]
>Is it possible to customize the timeframe that games appear there

No. I think it has a hard limit in which it keeps a number of imported games in there. Not something we would be presenting an option to change. You can create new sidebar "collections" if you would like.
