### ISSUE TITLE
Pokemon Emulator Save Crash 

### ISSUE THREAD

**Issue by mikesavage16** [OpenEmu/OpenEmu#2945]
Hello, I am new to the Openemu community and definitely not as well versed in software as you guys are. I'm asking if anyone can help solve this problem I've been having with Pokemon Platinum, where saving the emulator in the game (not with save states), causes the game to crash, making it unplayable after beating a certain character where you're forced to save. I'm asking for a solution or someone to point me in the direction of someone who can give me the proper advice. Thank you and have a wonderful day.

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
