### ISSUE TITLE
Multi-Disc Support Not Improved.

### ISSUE THREAD

**Issue by MightyTurgoth** [OpenEmu/OpenEmu#2946]
As of downloading version 2.0.4 the .m3u method for multi-disc support no longer works properly. I  created the .m3u file, which in this case encompasses 2 discs, and when I attempt to import the file it doesn't respond. I downloaded the previous version (2.0.3) to test this and the .m3u file imported correctly.

**Comment by clobber** [comment]
It was improved. Have you read the updated guide to make sure you aren't doing something incorrectly? Without details about your setup I can't really help you here.

**Comment by MightyTurgoth** [comment]
Thank you for the reply, and do excuse the title as it was more for the purpose of a swift response. I'll try to be as thorough as I can: MacBook Pro 2015 OS Sierra 10.12.1 Intel Iris Pro 1536MB. Followed the instructions of the guide to the letter. I've also been successful with a separate PSX game in version 2.0.3. Without looking at the source code I can only assume that a small bug may have occurred where .m3u importing is specified. Other than that I very much appreciate this program those who put in the effort to write it. Thanks again for the response and I hope I could be of some small assistance.

**Comment by clobber** [comment]
>and do excuse the title as it was more for the purpose of a swift response.

Don't do that.

>Followed the instructions of the guide to the letter.

Are you sure about that? All your cue/bin files + m3u file all need to be in the folder for the m3u file to automatically import everything in. You have provided no details about your files or the contents of them.

**Comment by MightyTurgoth** [comment]
m3u file name for the example was Chrono Cross (USA).m3u contents were as follows:
Chrono Cross (USA) (Disc 1).cue
Chrono Cross (USA) (Disc 2).cue
I first imported the 2 cue files into the Sony Play Station library. I then created the above file on TextEdit with plain text. I then attempted to drag and drop this file into the library and got no response. Upon inspecting the Application Support folder, I found the cue and bin folders to be in the same Sony Playstation folder but no m3u file. I also attempted manually moving the m3u file into the folder with still no update in the OpenEmu library

Strangely, the only fix that worked was downloading the 2.0.3 version, opening that application, and dragging and dropping the m3u file like normal. This also updated the 2.0.4 version as well, which is why I assume this is an issue with the code for importing vs the multi disc support as a whole.

Apologies for the initial lack of detail and again thank you for your time.

**Comment by clobber** [comment]
Mmm no, you didn't actually read the updated [guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game). The process changed a bit in OpenEmu 2.0.4.

#2885

**Comment by MightyTurgoth** [comment]
You're absolutely right, I was wrong. To clarify for any who may read this issue, I had to place all the cue and bin folders of the associated game as well as the m3u file into the same folder before importing, then drag and drop JUST the m3u file into the OpenEmu library.

He stated this above, but I misunderstood. Thanks again for taking the time to help.

**Comment by GuitarGuy9** [comment]
I'm trying to get driver 2 to work on open emu and i have both files for disc 1 and 2 with their original files and the .m3u that has both cue files in it like in the guide's picture. Still does not want to read the game file, it will read all files but one, and the one file not read I'm assuming is the .m3u how do i fix this

**Comment by dmorel89** [comment]
Well, What worked for me was similar to what MightyTurgoth posted except that I have v2.0.5 and I had to download v2.0.3 just to open that version and add the m3u folder and then open up the v2.0.5 and play the game.

My games are dragon warrior 7 and xenogears.
