### ISSUE TITLE
[FEATURE REQUEST] Rotation on DS

### ISSUE THREAD

**Issue by ApertureSO** [OpenEmu/OpenEmu#2947]
I saw that someone had a Feature Request tag on their issue, if anyone can tell me how they did it I would appreciate that. Also, I would like to suggest rotation on DS, as you likely already know. I've used the original DeSmuME, and there was turning so it shouldn't be that hard to implement in OpenEmu, because it uses DeSmuME as its DS core.

**Comment by clobber** [comment]
Already a request open for this. That functionality is somewhat a frontend feature and doesn't have much to do with it being in Desmume.

**Comment by ApertureSO** [comment]
Can I have the request number?
