### ISSUE TITLE
My Wii U Pro Controller wont sync anymore to OpenEmu

### ISSUE THREAD

**Issue by W0NDERwaffle3** [OpenEmu/OpenEmu#2948]
I followed the steps to Sync my Wii U Pro Control but they didn't work. For some reason after I restarted my computer when I was playing a PS1 game it wouldn't let me resync my control, I'd press the button to select it then the emulator would crash. I restart again then it doesn't detect my controller at all. It always connects to the Bluetooth but it never connects to OpenEmu.

**Comment by clobber** [comment]
The following should fix your crash:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app. 

As for your Wii U Pro gamepad: remove it from Bluetooth completely, reset the device and then go through the [pairing guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing) once again. It can sometimes take a few attempts to pair.
