### ISSUE TITLE
cannot delete save games in library/game view

### ISSUE THREAD

**Issue by sathompson** [OpenEmu/OpenEmu#2950]
OS X 10.11.6
OpenEMU v2.0.4
639-g606b287-Release

I tried following the directions for deleting found in the [User Guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide%3A-Save-states).

Save games do not turn red no matter what modifier key I hold in. Clicking on the save loads the save no matter what modifier key I hold in. I've tried every combination of fn, control, option, and command. This occurs for Game Boy, Nintendo DS, Sony PlayStation, and Sega Genesis games. This occurs in the Library view and when in the game.

I can delete saves in the Save States view by pressing delete or right-clicking and selecting the delete option.

**Comment by clobber** [comment]
They were never delete-able in that view before, only from the HUD menu during gameplay which I believe we removed since adding the Save States library in 2.0. The wiki guide needs to be updated.
