### ISSUE TITLE
Problem with inputs

### ISSUE THREAD

**Issue by Blogbog** [OpenEmu/OpenEmu#2951]
I've tried pretty much all the previous pieces of advice around the keyboard not having any affect on any game despite it running the startup screen. I used to be able to about 2 months ago and have just reopened open emu and it's unresponsive in-game on every console/emulation. The only thing I haven't tried is a recompile which doesn't _**seem**_ necessary and I don't fully know how to do. Any advice/help/sources?

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
