### ISSUE TITLE
Copy save files to disc 2

### ISSUE THREAD

**Issue by karahartauthor** [OpenEmu/OpenEmu#2952]
Hey guys, I just got to disc 2 on final fantasy 7. After, I decided to make a .m3u file to combine the three discs into one thing. Now, I can't access my save files. What exactly do I do? I read that you go to the "combined disc"'s save file and copy its name. Then, you copy that name over your original game's save file name. Is this correct? Because I've been trying and trying and it doesn't do anything at all. Please help

**Comment by clobber** [comment]
As discussed before, you needed to follow the CD guide in the wiki for multi-disc games so that this wouldn't happen. I can't offer any help since playing multi-disc games any other way is unsupported. You can probably google around or find info on the subreddit, as you said you already read something.

**Comment by valencik** [comment]
Hey @karahartauthor just wanted to let you know I was able to accomplish this. Steps were basically:
- install disc 1 and play it for several hours, realize I goofed up
- backup my save states (right-click Saved State, "show in finder", copy to Desktop)
- [create the m3u file for multi-disc games](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game)
- I ended up completely reinstalling OpenEmu as I couldn't install the .m3u game now that I had previously installed a single disc version
- install and play the .m3u version just long enough to make a save state
- right-click Saved State, "show in finder",  replace new "Saved State" with my backup (from Desktop)
