### ISSUE TITLE
Multi-disc Issue (Followed latest instructions)

### ISSUE THREAD

**Issue by metalobster** [OpenEmu/OpenEmu#2953]
I am having trouble importing a multi-disc PSX game using an .m3u file.
I followed the instructions [here](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game).
I have the .m3u file and all ,cue and .bin files in the same folder.  
Then, I just drag the .m3u file into OpenEmu.  Games are not pre-loaded.
Once the import is complete, OpenEmu crashes.
When I reopen the application it automatically crashes again.
I need to delete the Game Library folder in order to stop this.

I am able to load all of the discs successfully as individual games.
The game I am trying to import is Final Fantasy VII International (Japan).
There are 3 discs that contain gameplay material.
I was able to import a different multi-disc game using the .m3u file method.
I am using OpenEmu v2.0.4 and Mednafen core (v.0.9.39.2)

Any help would be much appreciated.

**Comment by clobber** [comment]
This is fixed for next release, coming soon.

#2917

**Comment by metalobster** [comment]
Thanks clobber!
