### ISSUE TITLE
Can't add some PSX games 

### ISSUE THREAD

**Issue by JamesCookies** [OpenEmu/OpenEmu#2955]
Hello ! 

I have an issue when I try to add some games, for example I tried to play Spryo 2, but when I drag&drop it on the window, there's a little bar which's loading and nothing happens.

![capture d ecran 2016-12-18 a 09 41 57](https://cloud.githubusercontent.com/assets/20623996/21292440/413f5544-c506-11e6-86e5-6343d5271c41.png)
 I add some screenshots for you to see what files I tried to drag&drop 

Thanks for helping

**Comment by clobber** [comment]
Please see the CD guide: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-an-ecm-or-ape-file
