### ISSUE TITLE
iOS10.0.2

### ISSUE THREAD

**Issue by 4strings** [OpenEmu/OpenEmu#2957]
Hello!
I am new to the forum, was attempting to add OpenEmu to the iOS10.0.2 environment on an Ipad to run some Roms I have on my PC (mame, NES to be specific). I attempt to open the package with iZIP
and get an error message wen I attempt to unzip the OpenEmu files. The error message is: "Sorry, the file format is not currently supported by Izip."
Anyone know a workaround by chance, or is this IOS10.0.2 just being ever so fantastic?
Any help would be appreciated.
Thanks!!!!!!!

**Comment by clobber** [comment]
This is a macOS app. There is no iOS version of OpenEmu.
