### ISSUE TITLE
Openemu won't add new games. 

### ISSUE THREAD

**Issue by Tempo17** [OpenEmu/OpenEmu#2959]
So I am playing a fanmade fire emblem game and a new patch came out. Normally I would just drag the new rom into the library and then just rename my save file so that I can save my progress. However, now it won't add the new rom. I have no idea what is going on.

**Comment by clobber** [comment]
If the file is zipped and contains other files besides the .GBA ROM, just unzip the file and import the .GBA ROM. If you have a patch file, you may need to use a [patching tool](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Apply-ROM-Patches-(for-fan-made-translations-and-mods)).

**Comment by Tempo17** [comment]
well it is already unzipped, the problem is that it just won't import and I don't know why

**Comment by clobber** [comment]
Show me exactly what you are trying to import and where I can download it.

**Comment by Tempo17** [comment]
http://www.mediafire.com/file/wamu040q5detwz0/FE6+PME+v1.5.zip

**Comment by clobber** [comment]
Unzipped your file and FE6 PME.gba imports to the Game Boy Advance library just fine. The only thing that could prevent that is if you already had the exact same file imported; OpenEmu will not import duplicates.

**Comment by Tempo17** [comment]
is there a way to delete the file while still keeping my current save data?

**Comment by duskymagnolia** [comment]
i have the same problem but it doesn't download as a zip. i can't add it, or anything, i have tried in multiple different ways and nothing. i have even turned the file into a zip, then unzipped it. and it gave this, really weird, unzippable file that i unzipped and it just gave me back the original zip file.  what do i do? also i have tried downloading the same rom multiple times incase something bad just happened in the download, and even tried from different sources, and different versions of the file. nothing changed, it just won't go into open emu. any help?

**Comment by duskymagnolia** [comment]
oh yeah, and i also tried uninstalling and then reinstalling open emu, then trying. nothing changes.

**Comment by clobber** [comment]
You will have to wait for next release. This turned out to be issue #3476
