### ISSUE TITLE
Dual Screen like desmume

### ISSUE THREAD

**Issue by lordhappyface** [OpenEmu/OpenEmu#2961]
I've looked and looked through the other issues about this but I can't find the answer. In some games the top and bottom screen go together. But in OpenEmu they are squashed so a lot of images look as though they are chopped in half. Is there a solution to not having this?
Here are the images:
http://imgur.com/a/e6ipL

**Comment by clobber** [comment]
As long as you are using the latest OpenEmu (2.0.4) with the latest Desmume core plugin, that all looks normal as it would on a real Nintendo DS or while playing with Desmume using the software renderer.
