### ISSUE TITLE
Sega Saturn unable to save in internal memory

### ISSUE THREAD

**Issue by murphytex** [OpenEmu/OpenEmu#2963]
it seems that the yabause core is unable to create a memory file. It's called "memory.ram" if i remember well. I can save during the game (tried with dragon force and shining force III) but i'm unable to load it if i quit.

**Comment by clobber** [comment]
Saturn via Yabause is still experimental, low compatibility and unsupported. That said, use the Mednafen core plugin for Saturn games instead.
