### ISSUE TITLE
Games do not Appear in OpenEmu Library After Install

### ISSUE THREAD

**Issue by forever2sday** [OpenEmu/OpenEmu#2964]
I was attempting to get multiple-disc Playstation games to work properly when I ran into a snag of sorts. I deleted a game (from the library but not the computer) so that I could reinstall it properly to allow for the ability to change discs. When I went to reinstall the game OpenEmu processed the install but did not show the game in my Library. After much effort with  no success, I somehow figured that it would be a good idea to delete the entire library of Playstation games so that I could reinstall them all. After dragging them over to OpenEmu, the program worked through the install only to not show any of the games in the Library. Any help would be greatly appreciated. 

In addition to getting the games back up and running, I would also greatly appreciate help on getting multiple-disc games to work. I read through the OpenEmu instructions and found a tutorial (without verbal instructions for some reason) on Youtube and still couldn't get the damned multiple disc games to allow me to switch between games.

Thanks!

I'm running OpenEmu v2.0.4 in MacOS 10.12.2 on the new MacBook Pro 2016.

**Comment by clobber** [comment]
Follow our guide for [multi disc games](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game), not videos on YouTube. The process recently changed for OpenEmu 2.0.4.

I don't understand your other problem, but maybe you need to read through the whole CD guide.

**Comment by forever2sday** [comment]
After much trial and error I managed to get my library working again. Prior getting it working again I somehow managed to completely break OpenEmu so that it wouldn't allow me to install any games of any kind (SNES, NES, N64, PSX, etc.). To fix it, I deleted the entire application and any (and all) files associated with it with the exception of the folder containing the library of games. After that didn't work, I decided to reinstall OpenEmu and allow the application to set up a new library rather than have it use my existing library. That seemed to do the trick. I still have no clue how to get the multiple disc games to work. I followed the instructions on the guide for multi-disc games to the T with no avail. Perhaps my other issue was complicating the issue. I'm going to give that process another go and I'll report back.

**Comment by forever2sday** [comment]
It seems that if you accidentally install a single disc of a multi-disc game and then try and go back and install the .m3u file instead it all but breaks OpenEmu for some reason. I'm working through very carefully to ensure that I only install the .m3u files. Everything seems to be working now... Fingers crossed all continues to go smoothly...

**Comment by forever2sday** [comment]
So far so good.
In an effort to not screw up my OpenEmu again, could you please provide some assistance with installing games with two tracks? I have Resident Evil 1 with two tracks on a single disc and RE2 with two tracks on each of the two discs. Thanks.

**Comment by clobber** [comment]
Like the CD guide says, you simply drag and drop in the .cue file to import a game. There's nothing special to it; tracks don't matter. OpenEmu will automatically import all referenced files in a cuesheet as long as they exist.

**Comment by forever2sday** [comment]
Thanks for the help! I finally got everything working.
