### ISSUE TITLE
Open Emu Ex not working on new Mac

### ISSUE THREAD

**Issue by lodashtaroth** [OpenEmu/OpenEmu#2968]
So I recently got a secondhand mac. I transferred all my backups from the old to new mac.

Everything worked fine other than open emu. Previously it worked beautifully. On the new computer only certain systems would work.

Ive tried downloading various different version and tried tons of different things with no luck.

Could anyone please help me as I loved my old games library and love this app.

Thanks, Beau

**Comment by ptitgraig** [comment]
2.0.4 does not start. 2.0.3 is running correctly.
MacBook Pro with Mac OS El Captain.

**Comment by SpeakingColors** [comment]
2.0.4 start and was playing fine on my side. But there is a problem with the preferences and game library... I have no idea how to solve that for the moment...

**Comment by clobber** [comment]
@lodashtaroth Please describe in detail what is not working including steps to replicate the problem, as well as any crash logs if you have them. Also post your system specs (macOS/OS X and OpenEmu version).

**Comment by clobber** [comment]
Closing for lack of info.
