### ISSUE TITLE
Retrolink controllers?

### ISSUE THREAD

**Issue by theboyk** [OpenEmu/OpenEmu#2970]
Hey there.

Been using a Retrolink Saturn-like controller with OpenEMU for a few weeks (mapped it for NES ROMs). Loaded a bunch of Sega Genesis ROMs in today and, using the same controller, mapped it for the Genesis ROMs. Once I did this, the controller no longer responds correctly to the mappings I've made (up is now left, down is right, etc.). Can I use the same Retrolink controller for multiple systems (NES, SNES, Genesis, etc.), or can I only use one controller per system?

Either the controller happened to break at the same time I mapped it for the Genesis (while also mapped for the NES) or I'm doing something wrong?

What files do I need to blow-out to reset the mappings and any OpenEMU reference to the Retrolink controller so I can start fresh?

Thanks!

**Comment by clobber** [comment]
They work with the app, but you may have run into a special case so check the [input troubleshooting guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems).

To completely reset mappings:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.
