### ISSUE TITLE
OpenEmu crash or not respond between games

### ISSUE THREAD

**Issue by emilioacosta** [OpenEmu/OpenEmu#2971]
Hello there, im new here on the community, hope someone can help me with this...

I have a MacBook Late 2008 Unibody, and I play with a WiiU Pro Controller. The problem is this:

Im playing any game for a time, and then I turn it off to return to my library, select another game and the game screen goes black but i hear the sound is fine, then i try to close it and openEmu doesn't respond anymore.

I tried playing only with the keyboard thinking this could be a bluetooth issue, but the same problem persists.

Could it be because i have the latest OpenEmu with OS X El Capitan? Because this mac doesn't support OS X Sierra.

thanks

**Comment by robotoad** [comment]
Are you playing in fullscreen?

**Comment by emilioacosta** [comment]
thanks for your reply.

yes indeed, I didnt made tests without full screen.. ive been playing OpenEmu on that macbook 2008 since OpenEmu released...

Since now I have the problem. Maybe is too old now? Because I play on my iMac 2015 and doesnt have an issue.

**Comment by robotoad** [comment]
The next update fixes a freezing issue related to the control bar fullscreen button. Are you clicking that to go to fullscreen? Does the issue still occur if you enter fullscreen using the window titlebar or View menu? If it doesn't, it's very likely the bug we fixed.

**Comment by clobber** [comment]
#2888
