### ISSUE TITLE
m3u Import Doesn't Work for PC-FX Games

### ISSUE THREAD

**Issue by jerrypc2036** [OpenEmu/OpenEmu#2972]
When I tried to drag-n-drop a m3u file for multi-CD PC-FX games into OpenEmu 2.0.4,
nothing happened. OpenEmu seemed not trying to scan the CD images.

I am pretty sure the m3u file has correct format, because it works for PlayStation and Saturn multi-CD games.

**Comment by clobber** [comment]
The PC-FX system plugin does not have 'm3u' in its list of supported file suffixes, which is why it won't take. Can you show me a PC-FX game that does in-game disc swapping? If so, have a save file I can test it with?

I know some PC-FX games have multiple discs, but I don't know if any actually do the swapping at some point in-game.

**Comment by jerrypc2036** [comment]
To be honest, I neither know whether a game asks for in-game CD swapping.

However, I tried to start "Aa! Megami Sama" from Disc 2 from the beginning, and it asked to load the save of Disc 1. Since Mednafen uses game's file name in battery saves, if OpenEmu can't import m3u file, I have to manually change the save file's file name.

**Comment by jerrypc2036** [comment]
I would like to close this issue first, and I found a game that actually asks for CD swapping in-game, I will open another issue.

**Comment by clobber** [comment]
No need to open a new issue for the exact same problem.

**Comment by clobber** [comment]
Just tell me the name of the game and if you have a save file that is currently at a point in-game that is asking you to insert the next disc, upload that somewhere and I will use it to test.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/commit/0175517cbfbaa7314550f8fcb34302d025c376b2
