### ISSUE TITLE
Sega CD Japanese BIOS not work..

### ISSUE THREAD

**Issue by tonykenobi** [OpenEmu/OpenEmu#2973]
I find lot of Sega CD Japanese BIOS(bios_CD_J.bin), But no Bios md5 Hash is "278a9397d192149e84e820ac621a8edd"

Just "bdeb4c47da613946d422d97d98b21cda" is found...

can any one find this md5 Hash "278a9397d192149e84e820ac621a8edd" BIOS file and send to me??

**Comment by clobber** [comment]
Sorry, no one can send you that. Keep searching for "sega cd bios" files I suppose.
