### ISSUE TITLE
OpenEmu Crash after FullScreen 

### ISSUE THREAD

**Issue by nedimonar** [OpenEmu/OpenEmu#2974]
**Hi, 

OpenEmu crashes into fullscreen mode. After the crash, gamepad does not work.

When I enter gamepad settings and exit, gamepad works.**

*Os x Sierra 10.12

Exception Name: NSInvalidArgumentException
Description: -[OEGameViewController touchBar]: unrecognized selector sent to instance 0x6100003409a0
User Info: (null)

0   CoreFoundation                      0x00007fff7d2fe7bb __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff91a6ba2a objc_exception_throw + 48
2   CoreFoundation                      0x00007fff7d37ed84 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
3   CoreFoundation                      0x00007fff7d271fc3 ___forwarding___ + 1059
4   CoreFoundation                      0x00007fff7d271b18 _CF_forwarding_prep_0 + 120
5   OpenEmu                             0x0000000101d94b4e _TFE7OpenEmuCSo20OEGameViewControllerP33_239303EE196DE72FE9C49BC03ADD36B116toggleFullScreenfGSqP__T_ + 110
6   OpenEmu                             0x0000000101d94e7a _TToFE7OpenEmuCSo20OEGameViewControllerP33_239303EE196DE72FE9C49BC03ADD36B123gameplayControlsTouchedfGSqP__T__merged + 90
7   libsystem_trace.dylib               0x00007fff9257903d _os_activity_initiate + 61
8   AppKit                              0x00007fff7b61e4e7 -[NSApplication(NSResponder) sendAction:to:from:] + 456
9   AppKit                              0x00007fff7b16e245 -[NSControl sendAction:to:] + 86
10  AppKit                              0x00007fff7b16e16d __26-[NSCell _sendActionFrom:]_block_invoke + 136
11  libsystem_trace.dylib               0x00007fff9257903d _os_activity_initiate + 61
12  AppKit                              0x00007fff7b16e0c5 -[NSCell _sendActionFrom:] + 128
13  AppKit                              0x00007fff7b1b092a -[NSButtonCell _sendActionFrom:] + 98
14  libsystem_trace.dylib               0x00007fff9257903d _os_activity_initiate + 61
15  AppKit                              0x00007fff7b16ca58 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2481
16  AppKit                              0x00007fff7b1b0667 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 785
17  AppKit                              0x00007fff7b16b4c8 -[NSControl mouseDown:] + 832
18  AppKit                              0x00007fff7b77e73d -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 6341
19  AppKit                              0x00007fff7b77af8c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 1942
20  AppKit                              0x00007fff7b77a42a -[NSWindow(NSEventRouting) sendEvent:] + 541
21  AppKit                              0x00007fff7b61abf5 -[NSApplication(NSEvent) sendEvent:] + 1145
22  OpenEmu                             0x0000000101dbf98d _TTSf4g_n___TFC7OpenEmu18OpenEmuApplication9sendEventfCSo7NSEventT_ + 77
23  OpenEmu                             0x0000000101dbf415 _TToFC7OpenEmu18OpenEmuApplication9sendEventfCSo7NSEventT_ + 37
24  AppKit                              0x00007fff7af01009 -[NSApplication run] + 1002
25  AppKit                              0x00007fff7aecba8a NSApplicationMain + 1237
26  OpenEmu                             0x0000000101d89e59 main + 73
27  libdyld.dylib                       0x00007fff92347255 start + 1

**Comment by nedimonar** [comment]
Adding:

When I use the full screen key at the bottom, it crashes. There is no problem if I do full screen from the window controls at the top.

**Comment by robotoad** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2888
