### ISSUE TITLE
Constant App Crashes after trying to Download Artwork

### ISSUE THREAD

**Issue by OpenEmuBugComplaint** [OpenEmu/OpenEmu#2976]
After selecting Download artwork on a Multi CD PSX game OpenEmu is now in a constant crash cycle. Upon reopening I can see the game has the loading graphic for the artwork and a couple of seconds later crashes.

From the crash logs.
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: gameTitle)'
terminating with uncaught exception of type NSException
abort() called

A reddit thread with the same thing happening. https://www.reddit.com/r/OpenEmu/comments/5jfyhq/set_openemu_to_download_artwork_now_it_wont_stop/?

**Comment by clobber** [comment]
Need to use the search.

Switch back to 2.0.3 for now. This is a bug with importing certain multi disc games in 2.0.4 - already fixed for next release.

#2917
