### ISSUE TITLE
Os X 2 player 2 wiimotes

### ISSUE THREAD

**Issue by vertsub** [OpenEmu/OpenEmu#2977]
I have successfully paired my two wiimotes and they both work as player 1 but I am having trouble using both wiimotes to play 2 player games. 

Using authentic wiimotes with openemu 2.0.4 and osx Sierra 10.12.2.

Any suggestions?

**Comment by clobber** [comment]
Two Wii remotes worked for 2-player games last I tried and they should not both work as player 1. My only suggestion is to take a look at both the [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) and [wii remote pairing](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing) guides to see if anything applies there.

**Comment by vertsub** [comment]
Well it's not that I'm trying to use both wiimotes as player 1, I would like to use player 2 with the second wiimote. I just can't get openemu to recognize both at the same time.

I've been through the troubleshooting and guides and no help there. I can use either remote as player 1 (when selected from the options panel) but I can't use both at the same time with player 1 and 2.

You mentioned that last time you tried it worked; was that version 2.0.4?

Thanks.

**Comment by clobber** [comment]
Remove your controller bindings file by:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

Then pair both of your wii remotes again - maybe completely reset them with the red button on the back. Don't mess with any player settings in Controls prefs. As both are paired, OpenEmu will automatically assign a remote to Player 1 and Player 2.

**Comment by vertsub** [comment]
Well looks like that did it. Works like a charm now! Thanks for all your help :)
