### ISSUE TITLE
The Emulator Could not load rom - Arcade

### ISSUE THREAD

**Issue by JillyT14** [OpenEmu/OpenEmu#2978]
I am getting this error in the arcade version of Punch Out and Pole Position. Punch out worked one time - sort of. Then it locked up and now I am getting the error again. I have looked at the console  - but it just tells me it cannot load load rom. Any ideas on what might be wrong or what else to check. I can't get the thing running again. Thanks.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2615#issuecomment-230357101
