### ISSUE TITLE
No Bluetooth Audio

### ISSUE THREAD

**Issue by dvdshadow** [OpenEmu/OpenEmu#2979]
Good afternoon,

I recently got a new pair of bluetooth headphones and for some reason there is no audio coming through with OpenEMU. It works with everything else on my computer. I'm running MacOS 10.12.2.

**Comment by dvdshadow** [comment]
Interesting update on this. It appears that what's happening is that while I'm running OpenEMU, it is compressing my audio quality for anything and everything. So, when I play music it sounds extremely compressed and quiet coming from my laptop. But again, only while OpenEMU is running. As soon as I quit the application, everything gets restored to normal. Any idea what could be happening here?

**Comment by clobber** [comment]
>So, when I play music it sounds extremely compressed and quiet coming from my laptop.

Only noticed that before when I was connected through HDMI and used a core plugin with 8-bit audio paused in the background, while I played a video with VLC. This might not be an OpenEmu bug, though.

Can you get audio through your BT headphones if you run the following in Terminal:
`defaults write org.openemu.OpenEmu HUDBarShowAudioOutput -bool YES`

Then launch the app and select an audio device from the HUD bar while a game is playing.

**Comment by dvdshadow** [comment]
Nope. I turned that on with the Konami code in the settings. Still can't get sound to go through, and when I play audio from any other app while OpenEMU is running, then it sounds compressed. Which makes me think that OpenEMU is somehow changing the way bluetooth audio is communicated somehow. 

Take note that I have very little coding experience, so pardon my horrible terminology.

**Comment by OJPower** [comment]
I've had the same issue.

**Comment by her** [comment]
Hi guys, 

I'm also having this issue. 

Trying to find a debug mode, any ideas where I can enter something like that? 

Audio works fine when playing through MacBook speakers but just doesn't work with Bluetooth. I tried using this command

> defaults write org.openemu.OpenEmu HUDBarShowAudioOutput -bool YES

but this didn't fix it... and it looks more like some flag for the HUD controls when playing a game.

**Comment by pencilcheck** [comment]
Also can't hear from bluetooth audio, if you need a flag to turn on bluetooth audio, in my opinion that means the code is wrong. I thought OS manages the audio input/output, so it should automatically adjust based on system preference, why do we have to turn on a flag to enable this behavior?

**Comment by pencilcheck** [comment]
Actually I take some word back, because the sound works for PSX emulator, but not in NDS emulator the last time I tried.

I wonder if this is simply is a issue with the plugins?

**Comment by pencilcheck** [comment]
I found out new information, for NDS, it seems like it is accessing microphone, and thus affecting bluetooth sound quality. I also noticed that bluetooth will not transmit sound at all if the microphone input is muted. So I am guessing if openemu is muting microphone by default.

**Comment by pencilcheck** [comment]
Found out one solution:
https://stackoverflow.com/questions/37901761/bluethooth-headphone-music-quality-deteriorates-when-launching-ios-simulator

**Comment by dhoken95** [comment]
Just set the mic to internal speaker and the sound comes out perfectly.

**Comment by mrvacbob** [comment]
If you still see this issue, please try it with Xcode - and report it to Apple with feedback assistant if you see it there too. It doesn't sound like OE can fix it.

**Comment by dgealow** [comment]
It seems like the problem is that the games are for some reason turning on the microphone input, would it be possible to prevent them from doing so?

**Comment by dgealow** [comment]
Here's a workaround/solution:
https://interactivelogic.net/how-to-force-bluetooth-headphones-to-use-internal-microphone-in-macos/
This keeps the internal mic as the default sound input device, even when bluetooth headphones are connected; if you do this, OpenEmu sound will be fine through headphones without needing to manually futz with system preferences every time.
