### ISSUE TITLE
Policenauts English hack .m3u issue

### ISSUE THREAD

**Issue by themesser** [OpenEmu/OpenEmu#2980]
I got the English custom hacked roms for policenauts both for PSX and Saturn.

It is a 3 discs game and requires a m3u to run, but
on PSX, the .m3u won't import, nor individual .cue 
on Saturn, importing the m3u crashes openemu, and corrupts the library, impossible to reopen Openemu without manually editing the "Library.storedata" files
Note that on Saturn, individual disc images import well and run, but can not change the disc when playing the game.

my m3u files are very simple, a list of cue files, so this is not the problem
POLICENAUTS_1.cue
POLICENAUTS_2.cue
POLICENAUTS_3.cue

cue files are formatted like this:
FILE "POLICENAUTS_3-1.ENGLISH.iso" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00
	POSTGAP 00:02:00
FILE "POLICENAUTS_3-2.wav" WAVE
    TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 00:00:00

**Comment by clobber** [comment]
Need to use the search.

Switch back to 2.0.3 for now. This is a bug with importing certain multi disc games in 2.0.4 - already fixed for next release.

#2917
