### ISSUE TITLE
Cannot Re-Download Games I Deleted...

### ISSUE THREAD

**Issue by Bmarks0800** [OpenEmu/OpenEmu#2981]
I Deleted Final Fantasy 8 disc 2, 3, and 4 but i've tried redownloading them but it will not add them to the library. i've also tried downloading them from a different website but it still didn't work.
Please Help!!!

**Comment by clobber** [comment]
Can't help you with downloading games, but to properly import a multi-disc game please see the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games).
