### ISSUE TITLE
(Inconvenience) Roms only open through Finder

### ISSUE THREAD

**Issue by freerainboxbox** [OpenEmu/OpenEmu#2983]
Double clicking a game title doesn't do anything. Selecting "Play game" through menu doesn't do anything.
The only way to play the game is to click on the "Show in Finder" option, then double click on the rom. This only happened right after I added a NDS rom (compressed with zip)
I am running a mid-2010 MBP with macOS Sierra. There is no result in Console.
I can live with this issue, but I think it kinda sucks.

**Comment by kevinchau321** [comment]
Did you figure out how to solve your issue?

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2681#issuecomment-235673594
