### ISSUE TITLE
Customized USB Controller support needed

### ISSUE THREAD

**Issue by JBRPG** [OpenEmu/OpenEmu#2984]
I am a dual player and i like to play games that feature two players on one controller. I have attempted to use the configuration option and it does not support analog sticks for any input, including d-pad. I have also attempted to get around the issue by using another application called Joystick Mapper to allow analog sticks to be used on directional pads, but when I played a game like STG on SNES, it cannot detect the keys used on a USB gamepad using Joystick Mapper, thus rendering the customized joystick controls useless.

Also, the USB joystick support is too small since it only accepts a few brands of joysticks and not generic USB joysticks.

You should find a way to make USB controls more customizable so that analog sticks can be freely used for any input including D-pads.

**Comment by clobber** [comment]
Any HID compliant gamepad will work. The ones that we "support" are simply ones that we automap controls for. For other devices, you have to manually map your controls but mapping analog sticks will work too.

Also see the [input troubleshooting guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) - Keyboard and Gamepad modifier apps will not work.
