### ISSUE TITLE
Save Current Game menu does not open

### ISSUE THREAD

**Issue by grovermind** [OpenEmu/OpenEmu#2985]
I tried to reset the game warnings from preferences, but it did not have any effect. I can save a quick state and the autosave works, but I cannot save with a named state name.

**Comment by clobber** [comment]
Restoring the Save State confirmation dialog works fine here with the 'Reset Warnings' button in Library preferences using OpenEmu 2.0.4. What are you using?

**Comment by grovermind** [comment]
Thank you for the fast reply, clobber. Hmm, I have v2.0.4.

**Comment by grovermind** [comment]
I was able to restore the functionality by going into the secret options and enabling the save related options in the HUD Bar/Gameplay category. Perhaps they are disabled by default, and if so I apologize because I am new using OpenEmu. From my perspective this is no longer an issue, but if they are to be enabled by default, I am certain that I didn't disable them.

**Comment by clobber** [comment]
Saves in the HUD are definitely enabled by default.
