### ISSUE TITLE
PS3 SixAxis control sticks not working in PSX games (OpenEmu)

### ISSUE THREAD

**Issue by Allanbuzzy** [OpenEmu/OpenEmu#2986]
I have configured the sticks on the preferences, but it doesn't seem to work in-game. I do not know why but it doesn't. I am using a PS3 controller using a MicroUSB charger with Bluetooth enabled. I even press Home (the button for analog sticks) and it still doesn't work. Oh and every time I seem to edit it, it always goes to a keyboard mode. Help!

**Comment by clobber** [comment]
Official PS3 DualShock 3 gamepad+analog works here, either via USB or Bluetooth - and OpenEmu will automatically map controls for it. Some games require pressing the 'Analog Mode' button to enable DualShock/Analog in-game - check Controls prefs to see which key/button that is assigned to.

Also make sure you have followed both the [DualShock Controller Pairing](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-DualShock-Controller-Pairing) and [Input Troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) guides to see if anything applies.

**Comment by CreepyHobo** [comment]
I'm having the same issue Allenbuzzy. clobber must not have read the part about already pressing the home button.  I press it as well and the sticks won't work.  It's very frustrating trying to play Tenchu without them.

**Comment by clobber** [comment]
>  It's very frustrating trying to play Tenchu without them.

@CreepyHobo "Tenchu: Stealth Assassins" (the very first game) DOES NOT support analog controls, you fucking idiot. You must not have read that part.
