### ISSUE TITLE
Pokemon Platinum Save Freezing Game

### ISSUE THREAD

**Issue by DenizOlgun** [OpenEmu/OpenEmu#2987]
When I use the ingame save, the game's audio stops and the screen freezes (more like softlock because the game does not actually throw an error, just stops).  Save states work fine, but in game saves crash the game.  Note: this is not the elite 4 glitch, this is much earlier in the game.  The most similar issue I could find is here: http://www.drastic-ds.com/viewtopic.php?f=7&t=818 , but OpenEmu's save states save the in game saves as well, so the method used here does not fix my file.  

OpenEmu Version 1.0.4
Mac OS Version: 10.10.5
Mac Version: MacBook Pro (Retina, 15-inch, Late 2013)
DeSmuMe Version: 0.9.11

My save state is enclosed.
[Save-Game-43 2017-01-02 081634 +0000.oesavestate.zip](https://github.com/OpenEmu/OpenEmu/files/681566/Save-Game-43.2017-01-02.081634.0000.oesavestate.zip)

Last Working Save State:
[Save-Game-34 2017-01-02 061431 +0000.oesavestate.zip](https://github.com/OpenEmu/OpenEmu/files/681573/Save-Game-34.2017-01-02.061431.0000.oesavestate.zip)

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to OpenEmu 2 and OS X 10.12 (it's free and your machine is supported).

**Comment by Walid-R** [comment]
I face the exact same problem, and thus once I beat the League Champion, the game does an auto in-game save, and this freezes OpenEmu. I have the latest version of OpenEmu, and the latest MacOS. A solution would be greatly appreciated.
