### ISSUE TITLE
Issues with Importing MultiDisk game

### ISSUE THREAD

**Issue by Wickedjc** [OpenEmu/OpenEmu#2991]
hello, I imported final fantasy IX disks seperately and ended up playing the whole first disk before I realized I needed to import the disks with the .m3u
the import didn't work with this game with the .m3u so I decided to delete all of the final fantasy IX disks. now none of them won't import over. I tested to see if it was messed up for other games as well but I successfully imported the MD game Chrono Cross with no issues using the .m3u

I think I may have to delete the full library or fully uninstall/reinstall OpenEmu to get the old FF9 files off. please help. I'm running Mac OS Sierra and I don't know how to get off all the openemu files to reimport FF9 or just if you know a better way to get it done, anything will help.
(wasted 8hrs beating the first disk to realize I had to do a MD import QQ)

thanks!

**Comment by Wickedjc** [comment]
*update* I just successfully imported final fantasy 7 as a multi disk game so I know for sure I'm doing the .m3u correctly. Im just having the issue uploading FF9 since Im guessing it has data from the first time I imported the disks separately. any help would be amazing! thanks!

**Comment by clobber** [comment]
Follow the [guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game). Remove the currently imported disc(s) then import them all the correct way.
