### ISSUE TITLE
Display mode for DS where the touch screen is showing, but very small

### ISSUE THREAD

**Issue by bergmayer** [OpenEmu/OpenEmu#2997]
On the DraStic DS Emulator for Android, there's an option where the main screen takes up most of the screen, and the touch screen is small and off to the side, but visible.  This would be a valuable additional display mode for the DS, in addition to both screens being equal size, or just one or the other being displayed.

**Comment by clobber** [comment]
Sorry, this isn't possible in our core plugin of Desmume.
