### ISSUE TITLE
OpenEmu 1.0.4 Crash when loading a roms - 10.8.5

### ISSUE THREAD

**Issue by ELaplume** [OpenEmu/OpenEmu#2998]
Hello there, im new here on the community, hope someone can help me with this...

I just install OpenEmu 1.0.4 on y macbook 2009 10.8.5.

I can open OpenEmu and had new roms but when I launch a game OpenEmu just crash.

There is the report from the console : 

![capture d ecran 2017-01-08 a 20 32 45](https://cloud.githubusercontent.com/assets/24993182/21752919/b31053d0-d5e1-11e6-818f-bb7a23e7a314.png)

If someone have an idea with this ?
Thanks a lot

**Comment by robotoad** [comment]
Sorry, but that version of OpenEmu is unsupported. The latest version is 2.0.4.
