### ISSUE TITLE
Certain MAME games locking up on second launch

### ISSUE THREAD

**Issue by redmagehat** [OpenEmu/OpenEmu#2999]
I know MAME is in OpenEmu's experimental build, but I thought I'd drop this in here just in case. Certain MAME roms work great on the first launch, but subsequent launches of the rom will result in a black screen and necessary force quit of OpenEmu.

I'm on MacOS 10.12.2, iMac 5k.

Magic Sword: Heroic Fantasy is the particular one I was trying this morning. I can paste a console dump if needed.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2615#issuecomment-230357101
