### ISSUE TITLE
Organise/Collate by Country

### ISSUE THREAD

**Issue by kwolk** [OpenEmu/OpenEmu#3000]
As each ROM contains geographic release data (Country info), this significant not only for collectors but also sometimes in the way games play, I'd like to use it as a sorting option under List View.

As this information is already present on most ROMs, and display sorting already implemented, it shouldn't take too much time to include?

As sorting options in box art view are greatly limited compared to List View, I'd suggest that multiple ROMs with different geographic releases be collated in a sort of TimeMachine-esq cover-flow timeline design, expanded on click or mouse hover?

**Comment by clobber** [comment]
#664
