### ISSUE TITLE
Attach PDF game manuals to games

### ISSUE THREAD

**Issue by KelseyHigham** [OpenEmu/OpenEmu#3003]
Playing emulated games on 3DS and Wii U made me appreciate having game manuals available. For older games, like NES and Game Boy games, important information like controls and story were only communicated in the manual.

This amounts to these feature requests:

1. Under the hood, allow a PDF to be attached to a game, in the same way that cover art is attached to a game
2. Allow dragging a PDF onto a game to attach a manual
3. Add a context menu item, menubar item, and keyboard shortcut <kbd>⌘</kbd><kbd>I</kbd> for `Attach Manual…` and `View Manual`
4. If a manual is attached, then add a `View Manual` button to the HUD
5. `View Manual` opens the PDF in Preview

**Comment by clobber** [comment]
I think this is outside the scope of the project for now (not worth implementing), but maybe something we can leverage through OpenVGDB in the future.

**Comment by kevinchau321** [comment]
I would really love to see this feature actually! I hate having to google for game manuals...
What's the progress and development plan for OpenVGDB at the moment?

**Comment by kevinchau321** [comment]
I've added game manuals to openVGDB in this fork: https://github.com/kevinchau321/OpenVGDB
