### ISSUE TITLE
OpenEmu PSP games get stuck while loading , and sometimes l get a black screen

### ISSUE THREAD

**Issue by knightbol** [OpenEmu/OpenEmu#3004]
I downloaded GTA Vice City (European) , and when l launched the game it gets stuck in the loading screen.

**Comment by clobber** [comment]
PPSSPP emulator bug - I've experienced the same. You can sometimes bypass it by not pressing any buttons (or by pressing buttons) during the intro screen. Restart the game without loading an autosave and keep trying until you get it to work.
