### ISSUE TITLE
Unpredictable, repetetive crashes

### ISSUE THREAD

**Issue by claytonrcarter** [OpenEmu/OpenEmu#3006]
OpenEmu (2.0.4) seems to not like something on my system.  When I launch it, it usually crashes repeatedly before working fine:

1. Launch app.
2. It crashes.
3. I get the "shut down unexpected" dialog.
4. Select "Reopen".
5. Repeat steps 2-4 several times.

Sometimes I get a dialog saying that it crashed while trying to reopen windows and asking me if I want to try to reopen them again or not.  The choice I make there seems not to matter. Sometimes this doesn't happen at all.  Sometimes it happens a dozen times.  Sometimes the "reopen windows" dialog never pops up, sometimes it pops up several times.

Sometimes I get get into the app, then it will crash when I launch a game, then repeat the above cycle before working again and then launching a game successfully.

This afternoon, the above crash cycle happened 5 times before the app finally worked.  At that point, it emulated an N64 game perfectly for about an hour.  I have posted all 5 crash logs here: https://gist.github.com/claytonrcarter/5ec059156156f7f10533c6d9d8124588

Thanks.

**Comment by robotoad** [comment]
https://github.com/OpenEmu/OpenEmu/issues/2888
https://github.com/OpenEmu/OpenEmu/issues/2982
