### ISSUE TITLE
Black Screen at launch of PSP games

### ISSUE THREAD

**Issue by maxl716** [OpenEmu/OpenEmu#3010]
When ever I launch a game on psp for openemu a black screen appears and nothing happens. If I select to stop the emulation it doesn't and I have to force quit the application.
EDIT: Something I forgot to add is that I am on a school given computer that has blocked Terminal and I have tried to get it to open but nothing has worked so far, I do have the unarchiver though
![screen shot 2017-01-14 at 5 01 08 pm](https://cloud.githubusercontent.com/assets/25125300/21958385/3b9c25d8-da7b-11e6-90d8-2b38dcebea9f.png)

**Comment by clobber** [comment]
Cannot replicate this with OpenEmu 2.0.5 (the only supported version) and the PPSSPP 1.3 core plugin.

![screen shot 2017-03-25 at 9 31 32 pm](https://cloud.githubusercontent.com/assets/1303132/24327928/912e52d8-11a2-11e7-804c-55029f27e454.png)
