### ISSUE TITLE
Verbose logging anywhere?

### ISSUE THREAD

**Issue by sheykh-sleky** [OpenEmu/OpenEmu#3012]
Top of the morning.  Works great, short of importing PSX games.  I have read the wiki.  Did the checksum validations and tried a couple of different BIOS'.  I ensured I have the CORRECT .cue file as well.

Nada

Nothing in the console either that would lead me to think there is anything wrong.  It looks like it is scanning, then it just vanishes without a trace....  The default logging isn't helping all that much.  So I'm hopeful that there is someway to turn up verbose logging to help pinpoint my issue?  Works great on (assuming) other people's machines, so I'm confident it is user error (heh).  Gonna be irked when/if someone replies "Oh yea, simply do XYZ and badaboombadabing!"  Then again, I'd rather be irked playing God of War vs bothering all you fine people here.  

Time for some coffee!!  Cheers!!

**Comment by sheykh-sleky** [comment]
macOS Sierra 10.12.2
OpenEmu X v2.0.4

Can provide any further information as well (screen shots, logs, woot!)

**Comment by clobber** [comment]
Provide details on exactly what you are trying to import, including filenames and contents of cuesheets.

**Comment by sheykh-sleky** [comment]
GODOFWAR.ISO
GODOFWAR.CUE

`FILE “GODOFWAR.ISO" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00`

Much thanks clobber!

**Comment by clobber** [comment]
Uh, "God of War" is a PSP game, not a PS1 game and thus does not require a cuesheet. Simply import the .iso file.

**Comment by clobber** [comment]
Er, assuming your iso is indeed one of the PSP ports (Chains of Olympus or Ghost of Sparta). If that is the actual PS2 game, that will definitely not import!
