### ISSUE TITLE
Can't play SNES9x on Mac 10.7.5 w OpenEmu 1.0.4

### ISSUE THREAD

**Issue by keithmarino** [OpenEmu/OpenEmu#3014]
Hi, I don't want to upgrade to the new OSX so I downloaded OpenEmu 1.0.4 for since I am on Mac 10.7.5 Lion, the NES emulator works! But for SNES games, I click play and nothing happens, no error, etc, just nothing... here is the error I get in Console:

1/18/17 2:13:08.259 PM OpenEmuHelperApp: Error loading /Users/MountVernon/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x:  dlopen(/Users/MountVernon/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x, 265): Symbol not found: _OBJC_METACLASS_$_NSObject
  Referenced from: /Users/MountVernon/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x
  Expected in: /usr/lib/libobjc.A.dylib
 in /Users/MountVernon/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x

Do I need to get a new SNES9x.oecoreplugin file since maybe that one is only for the newest OSX? Any help would be great

Thanks

**Comment by mrvacbob** [comment]
We can't go back in time far enough to support 10.7. You might be better off with 1.0 or a standalone SNES9X app.
