### ISSUE TITLE
Configuring gamepad, player select switched to Player 2

### ISSUE THREAD

**Issue by martylavender** [OpenEmu/OpenEmu#3015]
I am trying to connect an 8bitdo NESPro 30 gamepad. The controller is paired with my Mac. I see the controller listed twice in OpenEmu as such:

-8Bitdo NESPro 30
8Bitdo NESPro 30

(notice one with a - in front of it)

When I select either one, OpenEmu attempts to map the controls itself. The D-Pad does not seem to work when playing games. All other buttons work. If I attempt to manually map the controls, OpenEmu switches to Player 2 for some reason in the player dropdown menu.

OpenEmu Ver 2.0.4
NESPro 30 FW Ver 1.71

**Comment by clobber** [comment]
First disconnect your NES30 Pro.

Then start with removing your controller bindings file:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

Then pair your NES30 Pro again and use **Mode 1/Joystick Mode** by holding the POWER button to power on. It is important to use Mode 1 and no other.

Lastly, return to Controls preferences and map your controls for Player 1.

**Comment by martylavender** [comment]
Works now! Thanks !!

**Comment by javierjulio** [comment]
I can confirm this solution worked with the SF30 Pro controller and replacing the "Mode 1/Joystick Mode" with just a normal Mac pairing (START + A). Thanks!

**Comment by djlaw90** [comment]
thank you!!!

**Comment by atmb82** [comment]
I followed the instruction carefully, but as of now it doesn't work.
I tried pairing the controller both in Mac Mode (Start + A) and Normal mode (Start), confirmed by the led flashing the appropriate times for each mode.
Mac paired the devices, but Openemu doesn't recognize it at all.

Openemu version: 2.0.9.1 058-g8850505-Release
macOS version: Catalina Beta Beta 10.15 (19A512f)
