### ISSUE TITLE
Left menu area should use the same right padding as it does for the left padding [Design]

### ISSUE THREAD

**Issue by natemcintyre** [OpenEmu/OpenEmu#3017]
This certainly isn't a major change, but the fact that the console text runs right into the border for the left menu navigation area keeps making me twitch. It doesn't help that the software doesn't persist custom resizing of that left menu area.

For specific issue and potential solution/suggestion please see the attached annotated screenshot below.

<img width="1435" alt="openemu" src="https://cloud.githubusercontent.com/assets/742548/22126606/8c23dfae-de55-11e6-988c-1f850f30b816.png">

**Comment by clobber** [comment]
I don't think we will adjust padding in the sidebar (we sort of mirror what iTunes or Photos app does) but it will now remember the width between launches if you adjust it.

#3103
