### ISSUE TITLE
Is it possible to sync OpenEmu Libraries across many computers

### ISSUE THREAD

**Issue by lewisbuttress** [OpenEmu/OpenEmu#3018]
I'd like to use something like iCloud Drive to sync my Game Library folder on all my machines.

**Comment by clobber** [comment]
No, not supported officially but if you search the issues you may be able to find a semi-workable solution using symbolic links and a cloud service.

**Comment by michaelahlers** [comment]
I've found [Resilio Sync](https://www.resilio.com/individuals/) is a great solution, with various `Application Support` folders connected. See the following screenshot.

<img width="979" alt="image" src="https://github.com/OpenEmu/OpenEmu/assets/2034877/7f5f0912-d30c-4294-be96-08a8a1152976">
