### ISSUE TITLE
Is it possible to backup my OpenEmu Library (including ROMs, save states & preferences)? 

### ISSUE THREAD

**Issue by Anaxophus** [OpenEmu/OpenEmu#3019]
Not an issue, more a 'nice to have'.  Recently in switching to a newer computer, I saved my ROMS but lost all of save states and preferences.  An option to completely backup a library (including OpenEmu specifics like prefs, states, etc.) would be awesome!  Thank you!  LOVE the program!

**Comment by clobber** [comment]
Manually in ~/Library/Application Support/OpenEmu
