### ISSUE TITLE
Is it possible to use a BSNES freeze state (created by BSNES) with OpenEmu?

### ISSUE THREAD

**Issue by martylavender** [OpenEmu/OpenEmu#3020]
I have been playing a game in BSNES and have gotten quite far but I rather use OpenEmu to play this game. Is it possible to use the freeze state or saved game that is currently in the ROM with OpenEmu?

**Comment by clobber** [comment]
Not save/freeze states - BSNES/Higan does not maintain compatibility between versions. In-game battery saves, yes. [This guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files) should help you infer how to do it.
