### ISSUE TITLE
Instructions on building core plugins for transferring save states?

### ISSUE THREAD

**Issue by martylavender** [OpenEmu/OpenEmu#3022]
Looking at https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files it talks about opening the ROM in the Higan core plugin. I cloned this repo https://github.com/OpenEmu/Higan-Core and tried compiling it in Xcode. I ran into some missing .h files. Found those in the OpenEmuSDK. Still cannot compile the core plugin. Am I missing something? Sorry for possibly sounding ignorant.

**Comment by clobber** [comment]
Just use the pre-built version of OpenEmu from the [website](http://openemu.org/). Higan and all of other core plugins are already included.

**Comment by martylavender** [comment]
Ok  I went through the steps. When I launch my game, I dont have any save files loading in it. Does BSNES store its battery save in the ROM itself? I guess I am confused as to how OpenEmu is getting the battery save that BSNES created

**Comment by clobber** [comment]
Sorry, I don't think I can help you beyond what you should be able to figure out from the wiki. Higan stores battery save files in `/Users/YOURNAME/Library/Application Support/OpenEmu/Higan/Super Famicom` created on first launch of the game, which you can easily see for yourself.

**Comment by martylavender** [comment]
RIght  I see that    But if I am running the game with the actual BSNES binary and I have a battery save through that process, is there a way to get that battery save from that into OpenEmu?

**Comment by clobber** [comment]
I don't know anything about BSNES - we don't provide support for it. Find out in their documentation where they store battery saves on your machine. Maybe google search.

**Comment by martylavender** [comment]
Yeah  thats what Ive been trying to figure out.  Thanks though :)

**Comment by martylavender** [comment]
Alright  in case anyone runs across this. BSNES drops them here: ~/Library/Application Support/Bannister/BSNES/Battery RAM

It drops .srm files for its battery saves. Tried renaming it exactly as the rom is named and changing the extension to .sav but still nothing. Poop sticks

**Comment by clobber** [comment]
Literally step 4 of the guide:
>4. Rename <ROM name>.sav to save.ram
