### ISSUE TITLE
Intellivision BIOS files don't seem to make a difference...

### ISSUE THREAD

**Issue by Rotgut-X** [OpenEmu/OpenEmu#3025]
I must be doing something wrong.  I have 13 emulators running perfectly via OpenEmu (incredible emu btw, so pain-free it's *shocking*), but Intellivision is giving me a hard time.  I dragged/dropped both BIOS files (exe.bin and grom.bin) into the screen yet no game will boot with these added.  The game box images show up on screen but they do not boot.  Maybe I have the wrong bin files?  Couldn't find much online.

Info: using OpenEmu experimental ver.  Thanks in advance

**Comment by clobber** [comment]
Are you saying the BIOS files you've found for Intellivision will not import, or a game will not run? Which game?

**Comment by Rotgut-X** [comment]
First of all, I want to say thank you for providing such an amazing, 95% pain-free emulator.  I've been into emulation for 20 years (MAME, Stella, Kega Fusion and all the rest) but I have never experienced anything easier, it's kind of a miracle IMO.

So re: this, I attempted it two ways:

1) First, I placed the exec.bin and grom.bin bios files into the drag/drop screen. They showed up as their own "game-like" boxes with the "off the air tv" striping. Go to click a game, i.e.; Baseball and get the same error message that I need the exec.bin and from.bin files. Tried other games like Snafu, same thing happens. The game "box" appears but I get the error message when I click it to run.

2) Then I went and dowloaded a diff set of bin files online (exec and grom), drag/dropped those, prompted to fix "issues", checked off the two boxes and selected "Intellivision" in the dropdown, clicked "Apply."  Game gives me the same error message.

**Comment by clobber** [comment]
You seem to not have the correct required files.

1. First delete all and any currently imported exec.bin and grom.bin files in your Library.
2. Find the correct exec.bin and grom.bin files as per the [BIOS guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files). You will need to google search and find them.
3. Import the correct exec.bin and grom.bin files **unzipped** via the System Files tab in Preferences (just drag and drop them onto the screen) to make sure they have imported.

**Comment by Rotgut-X** [comment]
Guess I had the wrong set or version of those files.  Works now.  Thank you for your help.
