### ISSUE TITLE
Mednefen supports rapid fire for turbo grafx OpenEmu is missing passthrough mapping

### ISSUE THREAD

**Issue by cloudd1** [OpenEmu/OpenEmu#3026]
Mednefen supports rapid fire button mapping in its controller config setup.
Mednefen controller config can be accessed during game play*
Turbo Grafx/ PC Engine  press (Shift+Alt+1) during game emulation

Why does Openemu not allow this to be configured either in OpenEmu controls config or by pressing (Shift+Alt+1) during game emulation?

The original Turbo Grafx came with rapidfire built in. some of the games feel completely broken without rapid fire. 

Please allow pass thru of rapidfire button mapping (2nd buttons that are the rapid version - A/B or I/II) . Its already mappable in Mednefen.

**Comment by clobber** [comment]
#933
