### ISSUE TITLE
Sega Saturn Multi-CD games issue (creating and importing a Plain Text file)

### ISSUE THREAD

**Issue by Rotgut-X** [OpenEmu/OpenEmu#3029]
Hi there!  Spent some time on this before deciding to hassle you.  I did searches, followed this carefully (twice):

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game

Still no luck creating a usable .m3u file for switching CDs.  The option does not show up (even in gray) in the bottom "gear" drop down in OpenEmu.  I first tried TextEdit (even converted it to Plain Text), then that didn't work so I scrapped that file and tried TextMate.  In TextMate, I do not see the option of saving the file as a "Plain Text" file anywhere — or saving as a "m3U" file.  All I see are these options:
**Japanese
Chinese
Unicode—UTF-8
Unicode—UTF-16BE
Unicode—UTF-16LE
Western—ISO Latin 1
Western—Mac OS Roman
Western—Windows**

and a small drop-down next to that:
**LF
CR
CRLF**

More info.  I have 4 CDs for a certain game.  Names:
**Panzer Dragoon Saga (Disc 1 of 4) (USA) (DW0575).cue
Panzer Dragoon Saga (Disc 2 of 4) (USA) (DW0575).cue
Panzer Dragoon Saga (Disc 3 of 4) (USA) (DW0575).cue
Panzer Dragoon Saga (Disc 4 of 4) (USA) (DW0575).cue**

Tried to create a Plain Text file and named it:
**Panzer Dragoon Saga (USA) (DW0575).m3u**

Not sure if that's correct either.

Wanna continue my Panzer Dragoon Saga game lol.  Any help when you get a chance is sincerely appreciated   : )

Jim

**Comment by clobber** [comment]
Sega Saturn is 'experimental' and thus unsupported at this time. It is not yet possible to import and use a m3u (multi disc game) for Saturn games in our currently released Mednafen core plugin. Perhaps in the next update.

**Comment by clobber** [comment]
Just an update: this can now be accomplished with OpenEmu 2.0.5 and the latest Mednafen 0.9.43 core plugin. Still strictly 'unsupported' until Saturn emulation is stable and ready.

**Comment by Rotgut-X** [comment]
No joke, I was telling my friend about this **just this morning**.......  how great OpenEmu is and that I was hoping for an update with Saturn multi-disc memory... I will try this soon!  Thank you so, so much.

**Comment by Rotgut-X** [comment]
I wanted to post again to tell you that it worked -- and also to say thank you for doing what you do. I can finally play Panzer Dragoon Saga without spending $500+... all 4 discs.  You're the best, whoever you are  : )
