### ISSUE TITLE
Mac overheating

### ISSUE THREAD

**Issue by Doolamiester** [OpenEmu/OpenEmu#3030]
Hey,

While I love Openemu<3, running even a snes game causes my macbook pro retina to heat up like crazy! I guess it's not the biggest issue in the world as I just turn on my aircon and aim it at my lap, but just wondering if maybe there was a fix I wasn't aware of to fix this?

Thanks Openemu, 
-Doolamiester

**Comment by clobber** [comment]
No, especially if you are using the Higan core plugin. Also try using basic filters such as Nearest Neighbor or Pixellate if you aren't already.

#2413
