### ISSUE TITLE
HUD menu wont stay open

### ISSUE THREAD

**Issue by antoniovillalon** [OpenEmu/OpenEmu#3031]
Hi. Whenever I press either the save button or the options (gear) button on the HUD, the drop down menu flashes open for a split second then disappears. I cannot access them at all.

Been searching google for a possible solution for the last few days. I'm running the latest openemu (2.0.4), as well as the latest MacOS (10.12.3 (16D32)). So no, it's not the OS. I've found several people with the same issue, all of which were unsolved.

**Comment by robotoad** [comment]
What input devices are you using (trackpad, mouse, etc.)? Does the issue still occur if you have no other applications open?

**Comment by clobber** [comment]
Please test with this temporary test build https://transfer.sh/2UvRn/openemu-pre-2.0.5-experimental.zip (link valid for only 14 days) and see if the issue persists.

**Comment by antoniovillalon** [comment]
Will do, thanks! Apologies as well, I didn’t see the prior email you sent me. I noticed the issue using a trackpad. However I was able to replicate it across different games, with different other applications open, as well as when it was the only application open. Issue also occurred with a mouse. 

Hopefully this test build works out, thanks.

**Comment by clobber** [comment]
This should be fixed as of 2.0.5.
