### ISSUE TITLE
Multi Disk m3u file will not be read on OpenEmu

### ISSUE THREAD

**Issue by GuitarGuy9** [OpenEmu/OpenEmu#3032]
i followed the steps for how to create a multi disk game, the game I'm trying to make work is Driver 2 for the Playstation 1 and i put the plain text code of the two .cue files i needed to make and the original .cue files. Nothing. I then put the .bin files with it, so all the original files from the downloaded game are now included in the folder. Still wont read the .m3u file. OpenEmu begins to scan the files, then once it gets to the .m3u file it will not scan and the game will not be added to the library. How do I fix this?

**Comment by clobber** [comment]
Possible issues:
* You don't actually have the m3u set up correctly (follow the guide closely).
* Your cuesheets are wrong and not referencing the bin files correctly.
* You have a bad rip of the game and will need to find another copy.

Can't offer any more help beyond that.
