### ISSUE TITLE
Openemu Disc Change does not work. Renaming mrc does not work.

### ISSUE THREAD

**Issue by squishymochi** [OpenEmu/OpenEmu#3033]
I just updated to the latest version of Openemu. I tired to import m3u to allow for disc changes it did not work. So I played the game without using the disc change availability that the new openemu has claimed to offer. After the finished the first disc, I went to rename the mrc in the battery saves folder to continue on to disc 2. (I have used this method previously before on the older version of the openemu and it worked) Now every time I load disc 2 a new mrc file is made and will not register the one I renamed. I rename the new one it makes and once again it just makes a new mrc file. Please help this new openemu has been a great inconvience. Thanks.

**Comment by clobber** [comment]
The procedure changed slightly for 2.0.4, so follow the [import guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) very closely.

For save file transfer, try this thread here #2489 or https://www.reddit.com/r/OpenEmu/comments/3ynqpx/no_saves_found_when_changed_disc/cyf9lo0

That's all the help we can offer.
