### ISSUE TITLE
Multi Disc Game

### ISSUE THREAD

**Issue by Bozorgs** [OpenEmu/OpenEmu#3034]
I followed the guide and created a .m3u file for Final Fantasy 7, but nothing happens when i drag and drop it to the library. It works just fine when I drag and drop the .cue file for each individual disk.
![screen shot 2017-01-29 at 1 54 17 am](https://cloud.githubusercontent.com/assets/25412600/22402462/d1cfc23a-e5c5-11e6-92d2-09a3a6578e92.png)

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/3032#issuecomment-275519133
