### ISSUE TITLE
I can't for the life of me figure out how to upload an MCR on Mac

### ISSUE THREAD

**Issue by cjhlambert** [OpenEmu/OpenEmu#3035]
Hey. I'm really new to emulation. I loved being able to use OpenEmu to replay Vanguard Bandits, one of my favorite PS1 games.

I wanted to play Final Fantasy Tactics again, but not go through the grind of the entire game. I was hoping to use one of the saved game files I could find online. I downloaded several, but I'm finding it impossible to use them with OpenEmu. I've been searching and searching but not really finding any real instruction on how to do this. 

Is there any way you can provide an explanation for dummies on how to use save files for the Mac version of OpenEmu? I'd be very appreciative. I tried looking up the Mednafen and Battery Save files, but I'm not seeing anything like that. 

Thank you!

**Comment by clobber** [comment]
Sorry, I'd say try the OpenEmu subreddit for info on importing a PS1 memory card file. Those questions have turned up there before.

**Comment by splrb** [comment]
So... on a similar note, can .smr files be converted without issue to .mcr?

**Comment by splrb** [comment]
I notice that in the battery saves folder within Mednafen, it seems to generate two separate, but all but precisely similarly named files for each game save file (seemingly):

![Screen Shot 2020-11-03 at 9 12 08 PM](https://user-images.githubusercontent.com/73887325/98071768-4f658100-1e19-11eb-9152-e164866eafa3.png)

I have a previous save file I would like to import, but am unsure as to whether I should rename both of these files, per game, etc. The previous save, however, is as a .smr.
