### ISSUE TITLE
How to turn off anti-aliasing in screenshots?

### ISSUE THREAD

**Issue by coolo222** [OpenEmu/OpenEmu#3036]
Hello,
I'm attempting to take a screenshot of a game, and want the individual pixels to be clear in the picture (I seem to remember being able to do this before, but I could be mistaken as I'm not 100% sure). I currently have it set to "Take screenshots in native size", but not matter what I do, the picture is extremely anti-aliased, and I can't seem to figure out how to take a clean screenshot. Is there any way for me to turn anti-aliasing off?

**Comment by clobber** [comment]
Try [debug prefs](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Secrets) screenshot options.

**Comment by coolo222** [comment]
Thanks, appreciate the help.

I can't seem to find an option, that removes the anti-aliasing, though. Been trying just about every visual/screenshot-related setting and can't seem to find anything that gives a clean shot. Am I missing something?

**Comment by clobber** [comment]
There is no "anti-aliasing" but maybe you are referring to a pixel smoothing filter you are using. Switch to Pixellate or Nearest Neighbor and then take your screenshot.

**Comment by coolo222** [comment]
Currently have it set to Nearest Neighbor, but the Openemu screenshot function still has a lot of anti-aliasing and blurry pixels, despite the in-game screen looking normal. I guess the screenshot function compresses the image a lot.

Zoomed in section of picture taken using the screenshot function:
<img width="582" alt="screenshot in openemu" src="https://cloud.githubusercontent.com/assets/25425396/22444463/a86c7e9e-e708-11e6-81e7-641a6bf46b25.png">

Taken using print screen:
<img width="328" alt="print screen of window" src="https://cloud.githubusercontent.com/assets/25425396/22444468/ad98fce4-e708-11e6-913e-1994b02adc18.png">

The reason I'm asking is because I was looking to rip a (rather complicated and large) sprite from a game screenshot, but because of how the emulator displays things at a larger size, the pixel's aspect ratio isn't one-to-one with the actual native resolution of the sprites, so if I resize a print screen of the emulator itself, the sprite gets distorted.

I guess there isn't an option to turn off screenshot compression/anti-aliasing, so I'll have to try and find some other method. I thought I was able to take native-sized screenshots with no compression in Openemu previously, but I may have been mistaken. Thanks for the help, nonetheless!

**Comment by msikma** [comment]
Is there any chance that this could be reopened? I can't find any combination of settings that gives me the output I want.

For an option called "take screenshots in native size", I would expect the screenshot to be the same size as the emulated resolution. So 320x200 in my case on PSX. And I would expect the screenshot to be like that regardless of whether I have an output filter set.

However, even when I set my output to "nearest neighbor", the screenshot ends up not being in the native size.

[Here's my screen](http://i.imgur.com/kWx4crp.png) and [here's the image](http://i.imgur.com/rsuZZ7c.png). Also, disabling aspect ratio correction [makes it a little better](http://i.imgur.com/l25L24d.png), but I think "native size" should also implicitly make screenshots not have aspect ratio correction regardless of what the aspect ratio setting is configured as.

I'm not sure if there's something I don't entirely understand, or if this is a bug. Maybe it has something to do with having a retina display. I'm on OpenEmu v2.0.5 719-g369c3a2-Release. I can open a proper issue with more information if you want.

**Comment by clobber** [comment]
The blurry look you are describing is a bug and will be fixed for next release.

**Comment by msikma** [comment]
Thanks so much for responding swiftly and clearing up my confusion 🙂

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu/commit/59faf0e621f6b895d99035e5b19e296626d8cd37
