### ISSUE TITLE
OpenEmu fails to import Arcade ROMs over a certain size

### ISSUE THREAD

**Issue by selee14** [OpenEmu/OpenEmu#3038]
I am running OpenEmu Experimental Version 2.0.4 on macOS 10.12.2 and I have imported some Neo-Games such as Puzzle Bobble or Metal Slug X, and they load without any problems. However when I try to import Metal Slug 3 rom by drag and drop, literally nothing happens. I tried different roms from all the sources including the 0.149 romsets and other websites, and I also reinstalled OpenEmu and its library.

**Comment by clobber** [comment]
This is a bug that was already fixed in 214f42af8eefae9dab85893bbb416af5f3f398b0 for next version.

Also noting that Arcade/MAME is 'experimental' and not a focus, so it's unsupported at this time. Instead, you may want to use the standalone version of MAME.
