### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by mrkenshiro** [OpenEmu/OpenEmu#3041]
I am using el capitan 10.11.6 whenever i try to open openEMu i get a pop up saying...
![screen shot 2017-02-05 at 6 05 49 pm](https://cloud.githubusercontent.com/assets/25507852/22630803/1891ed16-ebce-11e6-9e04-19f5aa0fd988.png)

**Comment by DRRN** [comment]
Same problem... Running El Capitan 10.11.6.
Was running great... Won't even open now

**Comment by clobber** [comment]
Please test with this temporary test build https://transfer.sh/2UvRn/openemu-pre-2.0.5-experimental.zip (link valid for only 14 days) and see if the issue persists and/or gives you a new error message.

**Comment by tenfolddean** [comment]
I have the same issue after upgrading, and the experimental version above doesn't work either...

**Comment by DRRN** [comment]
I just tried it... Exact same error message.

**Comment by clobber** [comment]
I tried on an install of 10.11.6 and it runs fine.

How exactly are you all opening the zip file? You should right click and open it only using "Archive Utility" or, if you have it installed, [The Unarchiver](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12).

**Comment by mrkenshiro** [comment]
i also still get the same message after using archive utility and the unarchiver. I would love to know how you got it to open

**Comment by DRRN** [comment]
I'm not quite following... the link above takes me to a transfer.sh page and I click the download button that downloads right to the open emu icon which I drag into the applications folder.

I try to open the app and it crashes before it opens.
Really wish I hadn't updated my OS.

**Comment by robotoad** [comment]
Does the application quit immediately after the error message is dismissed?

**Comment by clobber** [comment]
In addition, please check Console for any output when you open OpenEmu. Here are a few guides on how to do so if you don't understand:
* http://www.macworld.com/article/3102847/macs/hands-on-with-macos-sierras-console-now-its-easier-to-get-the-mac-information-you-need.html
* https://support.omnigroup.com/console-osx/

**Comment by DRRN** [comment]
The app crashes as soon as you click on the ok button from the message...
I have no idea if this screenshot will load or help

![screen shot 2017-02-14 at 10 34 50 am](https://cloud.githubusercontent.com/assets/25577068/22941136/8a1aa19c-f2a1-11e6-8e40-5ea6b16ff519.png)

**Comment by robotoad** [comment]
@tenfolddean You mentioned upgrading. Do you mean you recently upgraded OS X or OpenEmu?

To the others, have you performed a recent OS X upgrade or done anything special with the game library?

**Comment by mrkenshiro** [comment]
I first updated the open emu app. Then it would not open at all. After trying many options i then decided to update my mac book. Still wont work

**Comment by clobber** [comment]
This should be fixed as of 2.0.5, or, at least a proper error message should now appear. We can't fix a broken data store so you will have to delete yours in `~/Library/Application Support/OpenEmu/Game Library` and then reimport your games.

**Comment by mrkenshiro** [comment]
thank you for the reply. But does this mean to just delete the entire folder called game library? or should i just go in the game library folder and delete the rom folder?

**Comment by clobber** [comment]
It means delete the Game Library folder or rename it, then reimport your games.
