### ISSUE TITLE
Atari problems on OpenEmu. Please help. 

### ISSUE THREAD

**Issue by SomeEmuUser** [OpenEmu/OpenEmu#3042]
I am having problem with my Atari 2600 5200 7800. I am trying to put different ROMS in there and nothing is working. Other ROMS work just fine ( NES, SNES, N64, etc.) I have tried multiple different sites, different extensions and nothing has worked. Please, any help.

**Comment by clobber** [comment]
Which version of OpenEmu? You simply drag and drop in .a26/a52/a78/bin files to import games for those systems. Try unzipping the files if they are zipped and import just the ROM.
