### ISSUE TITLE
scale of NES screen is wrong

### ISSUE THREAD

**Issue by HawkenKing** [OpenEmu/OpenEmu#3043]
NES games run in most emulators at 256x240

in OpenEmu - as much as I love this software - they run at a pixelated 292x240

What's going on here and can you fix it?

Normal Emulation:
![mario bros 3 nes](https://cloud.githubusercontent.com/assets/5999766/22681945/63f69d70-ed53-11e6-9830-b59debdc1315.png)

OpenEmu emulation
![super mario bros 3 2017-02-07 16 31 26](https://cloud.githubusercontent.com/assets/5999766/22681949/6ac63f02-ed53-11e6-9542-efa1c9200510.png)

**Comment by clobber** [comment]
It's not wrong, it's aspect ratio corrected to look how it would on a real TV. Other emulators that don't aspect ratio correct are doing it wrong.

**Comment by mrvacbob** [comment]
It should be 320x240 though. Maybe.

But yes, NES games were designed to run on 4:3 TVs, the sprites were drawn for 4:3, and so we display them as 4:3.

I will accept a bug that says it shouldn't be pixelated, but try the different scaling methods if you're running Nearest Neighbor or Pixelate.

**Comment by clobber** [comment]
Nope, 292x240. Check here: http://wiki.nesdev.com/w/index.php/Overscan
