### ISSUE TITLE
Use Retroarch Beetle fork of Mednafen PSX core

### ISSUE THREAD

**Issue by axfelix** [OpenEmu/OpenEmu#3045]
I'm not sure how easy this is to support in OpenEmu, so feel free to tell me this is way outside of scope, but Retroarch's fork of the Mednafen PSX core (called "Beetle") has a lot of rendering improvements, including:

- Rendering at very high internal resolutions rather than the PSX native; this was supported by finicky ePSXe plugins ages ago and was never implemented in Mednafen, so it's very nice to have it here
- Really nice dithering
- Fixed warping: https://www.libretro.com/index.php/mednafenbeetle-psx-pgxp-arrives/

This finally drove me to start using Retroarch rather than Mednafen on other platforms, and I'd love to see it here too.

**Comment by clobber** [comment]
It also introduced a lot of regressions. Sorry, we're only going to use vanilla Mednafen in our core port. Much easier to maintain and support.
