### ISSUE TITLE
Transfering Save Data to Snes9xGx (Wii) from OpenEmu

### ISSUE THREAD

**Issue by W0NDERwaffle3** [OpenEmu/OpenEmu#3046]
I want to transfer over my save of Link To The Past from Snes9x on OpenEmu to Snes9xGx on the Wii. How would I transfer over my saves?

**Comment by clobber** [comment]
[This guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files) should help you figure out how to do it, but that's all the help we can offer.
