### ISSUE TITLE
Can anyone help?

### ISSUE THREAD

**Issue by mrkenshiro** [OpenEmu/OpenEmu#3047]
Updated my open emu by mistake and now this is the message i get everytime. Have been searching for weeks how to get around this

![1891ed16-ebce-11e6-9e04-19f5aa0fd988](https://cloud.githubusercontent.com/assets/25507852/22852701/0dd058fe-f010-11e6-9ac4-f0961137796c.png)

**Comment by robotoad** [comment]
What version of macOS and OpenEmu are you running? Does that error display immediately on launch?

**Comment by mrkenshiro** [comment]
Thank you for replying. I am using el capitan 10.11.6 and i have tried download multiple versions of open emu. I still get the same message. And yes it happens immediately on launch

**Comment by clobber** [comment]
No need to open a new issue.

#3041

**Comment by mrkenshiro** [comment]
I can close the other one. No one was helping

**Comment by clobber** [comment]
No, use your original issue you opened.

You have to wait until someone gets to you. You're not entitled to immediate help by opening multiple issues for the same problem; that's just annoying.

**Comment by mrkenshiro** [comment]
Ok i unnderstand. Is there any way you can help me?  It looks like you have helped a lot of people here. It will be appreciated
