### ISSUE TITLE
2x/3x/4x fixed filtering works poorly with free scaling fullscreen

### ISSUE THREAD

**Issue by jewesta** [OpenEmu/OpenEmu#3051]
Hi,

I absolutely love OpenEmu and we are using it quite often to play SNES games on a mac mini hooked up to an HD (1920 x 1080) TV. Thank you very much for all the effort!

Having said that I have one issue with the screen resolution settings. I know that undocking the emulation window allows for setting various multipliers (2x, 3x etc.). Unfortunately that's not possible in full screen mode. Full screen (while preserving the aspect ratio as it should be) always means scaling the picture to however big the screen is. This causes problems when using filters, since those rely on the image being rendered in integer multipliers of the original resolution. I for example love SABR (but it applies to other high quality filters as well). Unfortunately those produce artifacts in full screen mode. The artifacts are thin vertical black lines that appear in the center area of the screen.

I realize this is a bit of a first world problem, but it's there and I guess full screen mode plus some sort of HQ filter is a quite common combination. It would really be nice if one could have full screen mode while having OpenEmu limit resizing to the maximum multiplier possible. Coming back to the combination SNES and HD-TV this would lead to relatively small black bars on the top and bottom area of the screen and filters like SABR wouldn't have a problem.

So why not just use the windowed mode? It's just that it's not very nice looking having to play with all the window border control stuff etc. around the emulation window. After all, that's why there's full screen mode. :-)

Thanks in advance for considering!

Cheers,
Jens

**Comment by mrvacbob** [comment]
You're right, the 4x filters should be applied by filtering 4x bigger and then scaling down to the screen size. The same way "scaled" resolution works on Retina Macs.

**Comment by mrvacbob** [comment]
This is fixed in the remote-layer branch.

**Comment by l008com** [comment]
I'm confused what the last comment in this thread means? But I'm using the current version of OpenEMU in 2023 and I'm having this exact same bug. SABR looks great but in full screen mode, I get those thin horizontal lines. In non-full-screen mode, the game video looks perfect.
