### ISSUE TITLE
Help error 

### ISSUE THREAD

**Issue by engranes** [OpenEmu/OpenEmu#3052]
helpme error in spanish

<img width="426" alt="captura de pantalla 2017-02-14 a las 2 00 11 p m" src="https://cloud.githubusercontent.com/assets/25775355/22940003/3c750a90-f2bf-11e6-906a-1e66dee895b0.png">

<img width="586" alt="captura de pantalla 2017-02-14 a las 2 10 00 p m" src="https://cloud.githubusercontent.com/assets/25775355/22940028/4dd7b9d6-f2bf-11e6-986e-11806b03b7b9.png">

**Comment by clobber** [comment]
That means your game library database didn't properly migrate from whatever previous version of OpenEmu you were using. You haven't provided any details so I can't really help you.

But to work around this, follow the steps in this issue: #2649
