### ISSUE TITLE
PPSSPP emulator freezes at same spot

### ISSUE THREAD

**Issue by pheonixia** [OpenEmu/OpenEmu#3053]
Hello,

I am a Mac (Yosemite) user. I currently have PPSSPP 3.1 on my OpenEmu. It keeps freezing at the same spot for my Final Fantasy Tactics War of the Lions game. I am guessing because the animation is too fast or something. 

These are the options I am looking at:

1) Downgrading to a better PPSSPP version. (How do I do that and which one is better?)

2) Fixing the issue in the current PPSSPP version so it doesn't keep freezing in that frame and then crashing the app. 

3) Converting my .oesavestate file to a save state that works with the PPSSPP emulator that I separately downloaded, since this may be an OpenEmu problem. 

I really want to continue my game :( so your help will be appreciated! And if I have to move to a different emulator I really don't want to start over too.

**Comment by clobber** [comment]
Sorry, 1.x is unsupported. Update to OpenEmu 2 and the latest macOS (OS X).
