### ISSUE TITLE
Chrono Trigger Battle Transition Problem

### ISSUE THREAD

**Issue by freakykokiri** [OpenEmu/OpenEmu#3057]
I started playing Chrono Trigger on OpenEmu. I noticed the screen flashed every time I was starting a battle. Instead of a fluent transition, the screen would stutter shortly right at the start of a battle. Apart from that issue the game seems to work perfectly fine. 

Is there any way to fix this problem?

Greetings from Germany

**Comment by clobber** [comment]
Is this what normally happens on real hardware? Does the same thing happen when running the game in the more-accurate Higan core versus the SNES9x core? See guides here to [switch cores](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide%3A-Default-Cores) and [transfer save files](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide%3A-Transfer-Save-Files).

**Comment by freakykokiri** [comment]
I've switched to Higan core and transferred my save file. It runs flawlessly on Higan. However, before I changed cores I tried running it on a regular SNES9x emulator (version 1.53),too, without any issues.

**Comment by freakykokiri** [comment]
Thank you for your quick response!

**Comment by clobber** [comment]
Okay. Sounds like a regression somewhere. Keep in mind that the standalone version of SNES9x you tried is over 6 years old, and not even the latest version (1.54.1 as of Oct 2016). Our core port deviates a little bit, being much newer than 1.53 but slightly older than the latest.

Anyway, Higan is what you want to use for SNES emulation.
