### ISSUE TITLE
Can't Home Button On Subsonic PS3 Pro Controller, Can't Map Keyboard Key to Analogue Selector

### ISSUE THREAD

**Issue by Nobody1707** [OpenEmu/OpenEmu#3059]
I can't map the home button on this [controller](http://www.subsonic.com/en/for-playstation-3/47-ps3-pro-controller-blackwhite-3760192202145.html?search_query=ps3&results=41), nor can I map a key on the keyboard as the analogue button so in Mednafen I can't actually use my analogue sticks in my Playstation games. Is there any way around this?

**Comment by clobber** [comment]
It looks like by default we have mapped the 'Analog Mode' button to '\' on the keyboard. Does backslash not work for you?

No idea about your gamepad. Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by Nobody1707** [comment]
Backslash works. I didn't expect the keyboard bindings to still be in effect while using the game pad. I thought it was one or the other.

**Comment by clobber** [comment]
Yeah, OpenEmu responds to both keyboard and gamepad input at the same time.
