### ISSUE TITLE
Multi-language ISO images (PPSSPP core)

### ISSUE THREAD

**Issue by antoniokratos** [OpenEmu/OpenEmu#3060]
Hello.

Almost all the videogames in Europe are multi-language (Spanish, French, English, German, Italian...).

Some of them have a language selector inside the game, but some others doesn't, they just auto-select the language in which the PSP is set.

So, for example, I want to play "Daxter" on OpenEmu but I can't select the spanish language because of this and it only works in english.

So, could you give us an option to choose the region of the PPSSPP core?

Thank you so much! Greetings.

**Comment by clobber** [comment]
Dupe #1083
