### ISSUE TITLE
save game problems

### ISSUE THREAD

**Issue by blueyes47** [OpenEmu/OpenEmu#3062]
I was playing Pokemon mystery dungeon explores of darkness and my game just suddenly went back to a previous save all the way at the beginning! NOTE THAT THIS HAPPENED WHILE I WAS PLAYING MY ORIGNIAL SAVE (i don't the save function on the openemu game bar) plz help me!
i just finished the game yesterday as well, and then as i was playing the afterstory, it went back to a place before the first boss and i can't figure out how to get back to where i was

if it helps, i use the i game save feature, and i recently saved using that

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
