### ISSUE TITLE
Nintendo DS Start Button Doesn't Work

### ISSUE THREAD

**Issue by ToxicXplosion** [OpenEmu/OpenEmu#3063]
I have been using the DS Emulator to play my favorite games. It has been working perfectly without any flaws until I needed to use Start. I pressed the button assigned as Start and it didn't work. Then I tried out other buttons and they didn't work.

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
