### ISSUE TITLE
save issues

### ISSUE THREAD

**Issue by blueyes47** [OpenEmu/OpenEmu#3064]
Im using openemu as my emulator

i was playing a pokemon game and i was going through the post game story and i took a step and it started me back at the beginning of the game, al data was gone. this happened while i was playing and i put alot of hours into this game. how can i get it back? my last post on this didn't help
the game was pokemon mystery dungeon explorers of darkness if that helps, i was walking in a dungeon one second and then the next second i was back before the first boss please help!
again im using openemu! not desume!

**Comment by clobber** [comment]
#3062 

>again im using openemu! not desume!

Uh nope, you are using a core plugin of Desmume with OpenEmu.
