### ISSUE TITLE
.m3u file crashes Openemu

### ISSUE THREAD

**Issue by Therealmadkong** [OpenEmu/OpenEmu#3065]
Hello there, I have a translated game for Playstation and I put it in with .bin and .cue.  They work perfectly, but it is a two disc game.  The title of the game files for .bin and .cue has [En by Slowbeef v1.0] in it since it is translated.  Openemu crashed multiple times and didn't transfer or have the game scanner bar come up.  Then one time the game scanner bar came up and everything crashed again.  When I restarted it, the .m3u file transferred once, but didn't have the disc 2 function working.  By that I mean it was there, and I could see Disc 1 and Disc 2 option, but it was not changing when I clicked it when the game was playing.  So I deleted it andI retried.  Now the .m3u file crashes the openemu.
![screen shot 2017-02-19 at 4 27 59 pm](https://cloud.githubusercontent.com/assets/13167865/23108310/74b4425e-f6c0-11e6-96e3-31e9c9075156.png)
Thank you for your time.

**Comment by clobber** [comment]
#2917
