### ISSUE TITLE
Mac keyboard not operating

### ISSUE THREAD

**Issue by rennyverdugo** [OpenEmu/OpenEmu#3067]
I'm having an issue using my MacBook Pro builtin keyboard. OpenEmu is recognizing it and I can map the button configuration but when a game is up it won't operate. I've seen previous boards and have closed out of everything but openemu and deleted the ~/library/applicationsupport/ bindings blah blah and still nothing. What can I do?

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
