### ISSUE TITLE
The Emulator could not load ROM

### ISSUE THREAD

**Issue by pdevans1** [OpenEmu/OpenEmu#3068]
I have downloaded an experimental version of OpenEmu and have the Arcade option. I have downloaded many MAME games and they work perfectly. However I am experiencing problems with some of the games, namely Bubble Bobble and Pole Position. When I drag the zip file into Open Emu and click on the games but it comes up with the following message "The emulator could not load the ROM" I have tried unzipping the file I have tried many different versions from sites such as EmuParadise Rom hustler etc. but to no avail.

Any ideas?

**Comment by clobber** [comment]
#2937
