### ISSUE TITLE
Cheat Options Not Available

### ISSUE THREAD

**Issue by Crisaula** [OpenEmu/OpenEmu#3069]
I was wondering was the Cheat Option completely removed or is there another way to access the Cheat Option?
I downloaded it from http://openemu.org/
I'm trying to use cheats on Playstation Emulator 

and a image of where it isn't

![screen shot 2017-02-23 at 6 49 53 pm](https://cloud.githubusercontent.com/assets/25788878/23287215/48634db2-f9f9-11e6-8685-f40bb12174c0.png)

**Comment by clobber** [comment]
#2811
