### ISSUE TITLE
Audio delay on 2.03 and 2.0.4

### ISSUE THREAD

**Issue by FoxHounderSnake** [OpenEmu/OpenEmu#3072]
Hello everyone,

I use Openemu for almost a year, and i never had this issue until this week.

When i play PS1 or SNES games such Donkey Kong Country or Harry Potter and the sorcerer's stone, i notice a kind of audio delay while im playing, but it seems more noticeable when i go from one stage to another, like the loading screen gets glitched and the sound gets one step after the actions.

I got a MacbookPro mid 2012, 4gb ram, 500 HDD, El Capitan. Im using the HQ4x filter, i've been always using it. It's pretty weird because never happened before.

P.S: For the best experience, i turn off Wifi connections and i close all the others app.

**Comment by clobber** [comment]
Switch to basic filters such as Nearest Neighbor, Linear or Pixellate. It seems your GPU cannot handle the other.

**Comment by FoxHounderSnake** [comment]
It still persist, i tried the other and the same, this began to happen when 2.0.4 was released, i don't know why but with 2.0.4 the app also crashes when i press the exit button.

I'm not sure my GPU is not working fine, i can play fine but the audio delay is annoying to me and i find Openemu the best emulator ever created.

Do you think this could be something related to the fact i don't have OS Sierra installed? Maybe?

**Comment by clobber** [comment]
Don't know, but you should definitely install 10.12 if your machine supports it. Does the problem still occur if using this test build of OpenEmu? https://transfer.sh/iytLH/openemu-pre-2.0.5-experimental.zip (link valid for ~8 days)

**Comment by MScoutsDCI** [comment]
This may not be what's happening here but I've noticed that if I ever use the fast forward function the audio falls out of sync and the only way to get it back is to pause and unpause the emulation (mind you, not in-game pause but the Openemu pause button).

**Comment by clobber** [comment]
@MScoutsDCI @digamejh 
I cannot replicate that behavior with the fast forward function. Tried both SNES9x and Higan cores with Super Mario World (USA) on OpenEmu 2.0.4 (only supported version. if using 1.x, that is unsupported) and using the Pixellate 'filter'. Make sure you are not using a filter that your GPU cannot handle.

I don't think we can go out of sync, and there have been no changes to affect that in 2.0.4.

**Comment by MScoutsDCI** [comment]
I'll have to test when I get home but it's possible I've only experienced that behavior with the Mednafen PSX core. I don't really consider it a problem worth reporting but when I saw this I thought I'd offer my two cents. Sorry for the clutter.

**Comment by FoxHounderSnake** [comment]
@clobber Thank you for giving me the link to the 2.0.5 experimental version, although when i see the about Openemu it says 2.0.4, anyway.

I uninstalled everything, i also lost my savedata but i dont really care, i installe the version you sent me, i only played Harry Potter and the chamber of secrets, during almost the entire game it worked perfectly fine, in the first 6 hours of gameplay (including dinner, watching youtube, texting some people) the game only had the delay issue twice very far from each other. That was yesterday at night.

Today, i just finished the game and it was very pleasurable to play it, just in the final part of the game when you are in the chamber of secrets itself the game began again to have that annoying audio delay, i happened like 5 or 6  times during the "dungeons" and the final battle.

Anyway, thank you very much for helping me.

@MScoutsDCI @digamejh I used to use the fast forward and rewind function but i stoped using it long time ago, and i use the pause button trick to get back the video audio sync, but you know that is a critical way to ruin the gaming experience when you do it every 5 minutes.

**Comment by clobber** [comment]
Mednafen's PS1 emulation is **very** CPU intensive. There are also sequences in some games that could introduce slowdowns if your CPU is already nearly maxed out (90-100%+). In some games, there could also be bugs relating to timing with the emulation itself. Combine that with playing a game fullscreen using a filter your GPU cannot handle and you may be in for a rocky experience.

**Comment by FoxHounderSnake** [comment]
@clobber Is hard to believe but my mac is the same that i bought almost a year ago and never had any problem using openemu, i think it's something with the CPU because Snes games suffer the same and also Nes and GBA. 

I can run the games perfectly, its just the fact the audio suffer that delay, but everything else works fine, no stuck, no video lag, no input lag, no nothing, just the audio delay, i've been all these days trying to find the issue, and it won't be fixed with a new release because the software must not be the problem.

It's really weird, i dowloaded a smcFanController to get cold my CPU, CleanMyMac3 to free some RAM space, not the filters, not any other app, not any other issue, i've read some other people issues from the past and guys with 8 ram intel i7 having worse issues than me, so i can't relate it.

I won't surrender, Openemu will be my number 1 emulator for Snes, nes and gba, for sure.

**Comment by FoxHounderSnake** [comment]
@clobber I kinda fixed my problem.

I deleted all (again), and i dowloaded 2.0.2 (the one i really remember works because i played a lot on OpenEmu those days) and boila ! It worked !!!! Yeah i did but i'm not sure it will last forever... but i did it this way:

-Installed OpenEmu 2.0.2 standard
-Installed the PS1 bios
-Put HQ4x on settings
-Don't save games on library and don't look for any info or cover

Then i tried with A link to the past, and the sound was really good, and then i tried with Klonoa: door to phantomile and pretty good, full screen, HQ4x and NO SOUND DELAY.

I don't know if this affected, but i deleted an anti virus called Sophos that i never used.

P.S: After all this, i updated to 2.0.4 and TROUBLES, then updated to 2.0.5 experimental (the one you sent me) and crashes everywhere.

I think my machine doesn't support more updates for now, i hope it could in the future when i update my RAM from 4 to 16, because i will stay with Mac machines for a loooong time...

Thanks by the way.
