### ISSUE TITLE
Won't Compile on Latest Xcode with latest macOS

### ISSUE THREAD

**Issue by CyberManifest** [OpenEmu/OpenEmu#3073]
I can't get this to compile in Xcode (latest version) with the latest version of macOS on a MacBook Pro Early 2015 edition. I get build errors, even after a clean.

**Comment by robotoad** [comment]
Make sure you've read this: https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide

**Comment by ltcarneiro** [comment]
I have the same issue.... Tried with and without experimental....

**Comment by ltcarneiro** [comment]
And I was following the guide

**Comment by robotoad** [comment]
It's impossible to help without knowing what the build errors are.

**Comment by kevinchau321** [comment]
@CyberManifest what error messages are you getting?

**Comment by mpaladin** [comment]
@CyberManifest are you referring to the following error?
```
<built-in>:16:26: note: expanded from here
#define __ATOMIC_SEQ_CST 5
                         ^
In file included from /Users/ssjenka/peach-jenkins/workspace/CFamily_openemu-HT574ZUVCG6ZH4FZASWFSDGXIJEJWHEP6DRGXCCQ5ZB4NPNKXPDQ/Higan/HiganGameCore.mm:32:
In file included from /Users/ssjenka/peach-jenkins/workspace/CFamily_openemu-HT574ZUVCG6ZH4FZASWFSDGXIJEJWHEP6DRGXCCQ5ZB4NPNKXPDQ/Higan/HiganInterface.h:29:
In file included from /Users/ssjenka/peach-jenkins/workspace/CFamily_openemu-HT574ZUVCG6ZH4FZASWFSDGXIJEJWHEP6DRGXCCQ5ZB4NPNKXPDQ/Higan/higan/emulator/emulator.hpp:4:
In file included from /Users/ssjenka/peach-jenkins/workspace/CFamily_openemu-HT574ZUVCG6ZH4FZASWFSDGXIJEJWHEP6DRGXCCQ5ZB4NPNKXPDQ/Higan/higan/nall/nall.hpp:15:
In file included from /Users/ssjenka/peach-jenkins/workspace/CFamily_openemu-HT574ZUVCG6ZH4FZASWFSDGXIJEJWHEP6DRGXCCQ5ZB4NPNKXPDQ/Higan/higan/nall/platform.hpp:20:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/atomic:1123:1: note: to match this '('
In file included from /Users/ssjenka/peach-jenkins/workspace/CFamily_openemu-HT574ZUVCG6ZH4FZASWFSDGXIJEJWHEP6DRGXCCQ5ZB4NPNKXPDQ/Higan/HiganGameCore.mm:28:
In file included from /Users/ssjenka/Library/Developer/Xcode/DerivedData/OpenEmu-djhrdjnzwxruoobvydudvoktymcf/Build/Products/Release/OpenEmuBase.framework/Headers/OERingBuffer.h:28:
In file included from /Users/ssjenka/Library/Developer/Xcode/DerivedData/OpenEmu-djhrdjnzwxruoobvydudvoktymcf/Build/Products/Release/OpenEmuBase.framework/Headers/TPCircularBuffer.h:46:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include/stdatomic.h:131:57: note: expanded from macro 'atomic_store'
#define atomic_store(object, desired) __c11_atomic_store(object, desired, __ATOMIC_SEQ_CST)
                                                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```
The build of OpenEmu has been failing since 22nd February so I believe it is related to changes of 21st February: https://github.com/OpenEmu/OpenEmu/commit/20418aca0f8c1e79228d107f3a46988fecda90cc or https://github.com/OpenEmu/OpenEmu/commit/30f5c1260b667b436fb19b84f2ea8124bae5a35c.

**Comment by clobber** [comment]
There are no build errors compiling OpenEmu. That is a specific name mangling issue with the Higan core plugin and the OpenEmu SDK, not a build of OpenEmu.

If you want to just build the OpenEmu app, first meet all the requirements (have latest Xcode, have submodules checked out - this also requires reading and understanding [the guide](https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide)) and then select the correct scheme: the "OpenEmu" scheme, **not** the "Build All" scheme.

**Comment by morriswinkler** [comment]
is there a workaround for the atomic include problem?

**Comment by clobber** [comment]
Yes there is...

* Either patch the offending line of code,
* or build the application the proper way as described above https://github.com/OpenEmu/OpenEmu/issues/3073#issuecomment-283987701. There is no reason to build the application + the core plugins when the core plugins are already pre-compiled and distributed over the updater.

**Comment by clobber** [comment]
Addressed in https://github.com/OpenEmu/OpenEmu/commit/410833ff7f2dcc757c71cad297922337bc06cc92
