### ISSUE TITLE
Turbo Feature?

### ISSUE THREAD

**Issue by LordTwann** [OpenEmu/OpenEmu#3076]
This would be a fantastic feature to add.  I know I used to use it on snes9x all the time.  The above also had an autopress feature which was fun, let you set a button to always depressed and then turbo.  Was handy for shooters that had a button that was always depressed during play or constantly smashed.  Also handy for power leveling in FF6.

**Comment by robotoad** [comment]
https://github.com/OpenEmu/OpenEmu/issues/832

**Comment by LordTwann** [comment]
Pardon me but I meant Rapid fire.  Corrected the title.

**Comment by robotoad** [comment]
https://github.com/OpenEmu/OpenEmu/issues/933

**Comment by LordTwann** [comment]
Well then since that thread is locked let me make this a feature request.
