### ISSUE TITLE
Ultimate GamePad (use your phone as gamepad) bug when the game plays

### ISSUE THREAD

**Issue by lippertmaxime** [OpenEmu/OpenEmu#3080]
Hello, 

I downloaded the app Ultimate GamePad and the receiver and it worked on my computer.
However on OpenEmu I still have a problem. OpenEmu recognise it because it allow me to change the controls. 

For example I said to Ultimate Gamepad that “Up” = T on my keyboard and on OpenEmu I said “Up is “click Up on my phone” = and T appears. So OpenEmu recognise my phone as a gamepad 

However when I launch the game, only my keyboard is working. And the game doesn’t answer to the Ultimate Gamepad anymore.
Is there any setting I have to change on Ultimate Gamepad or on my Mac to tell that he should listen to it all the time. Even in this special program ? 

I think I have to check something in the parameters on my mac or Ultimate Gamepad or OpenEmu so it allows it to work with every program all the time.  Is there such a parameter somewhere ? Where can I find it

Thank you in advance for your support.
![screen shot 2017-03-05 at 17 15 05 1](https://cloud.githubusercontent.com/assets/9382414/23589213/4024a6f0-01c9-11e7-80c1-6d95c3791e81.png)

**Comment by clobber** [comment]
These types of apps won't work with OpenEmu. Really best to get a real gamepad.

#2849

**Comment by lippertmaxime** [comment]
Thank you for your quick answer Clobber. 
Indeed, I planned to buy one but I could not wait and I wanted to play with something better than a keyboard for the next days.

I don't get why this gamepad app does'nt work on OpenEmu though...
