### ISSUE TITLE
.ips files

### ISSUE THREAD

**Issue by JoeyHutt** [OpenEmu/OpenEmu#3081]
is it possible to apply .ips files to my roms on openemu

**Comment by digamejh** [comment]
Unfortunately, OpenEmu doesn't support the automatic-applying of IPS patches the way some emulators do.
However, MultiPatch can help you apply it to a separate ROM.  See https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Apply-ROM-Patches-(for-fan-made-translations-and-mods)

**Comment by clobber** [comment]
Please use the search before opening a new issue.

#2030
