### ISSUE TITLE
multi disc issue in openEMU v 2.0.4

### ISSUE THREAD

**Issue by kfarrell1** [OpenEmu/OpenEmu#3082]
I am having an issue importing multi disc ps1 games into open EMU. I have followed the directions exactly to create an .m3u file for several different games. I have not imported the separate disc files. I am running version 2.0.4 on a mac running OS X el Capitan 10.11.6 and have never had problems with 2-disc games. The games I am trying to import are Final Fantasy 7 and 8. Any help would be appreciated.

**Comment by clobber** [comment]
Possible issues:
* You don't actually have the m3u set up correctly (follow the guide closely).
* Your cuesheets are wrong and not referencing the bin files correctly.
* You have a bad rip of the game and will need to find another copy.

Can't offer any more help beyond what is in the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game)
