### ISSUE TITLE
Reading CD while emulating

### ISSUE THREAD

**Issue by SunDiego** [OpenEmu/OpenEmu#3083]
Hello

I want to play Monster Rancher 2 on Open Emu.
This game requires to read a CD to create monsters but I have no idea how to accomplish this.
Other emulators seem to have a solution for this by mounting a CD using DAEMON tools.

Is there any way I can try to enjoy this game?

Thank you in advance

**Comment by clobber** [comment]
You want to create a m3u file and add the disc you want to use to 'unlock' to it, then import. Follow the [multi disc guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) to do it. That is the only option here.
