### ISSUE TITLE
Can't run PS1 roms on Mavericks - v1.0.4

### ISSUE THREAD

**Issue by alexandervoid** [OpenEmu/OpenEmu#3084]
Good evening, 
I'm a very happy OpenEmu user, kudos to the developers for the great work. 
I've been playing MAME and NES roms for over a year. Last week I decided to download and try some ps1 games. Downloaded the Core, the right BIOS files, followed the instructions and all, but the **"Couldn’t communicate with a helper application. Try your operation again."** window appears. That's happened with five different games. I've checked some posts with similar issues but unfortunately none of them have helped.

I run Mavericks with OpenEmu 1.0.4 and since I can't upgrade to 2.0 I was wondering if maybe that could be a problem. Thanks in advance.

**Comment by robotoad** [comment]
Older versions of OpenEmu are unsupported.
