### ISSUE TITLE
Automap for Switch Controllers

### ISSUE THREAD

**Issue by kevinchau321** [OpenEmu/OpenEmu#3085]
Mostly a feature request. I think we should have automap for the Switch Pro controller as well as the Joycons.

**Comment by clobber** [comment]
Do those devices pair to bluetooth on macOS without any sort of driver?

**Comment by kevinchau321** [comment]
@clobber they pair with macOS without any problem or need for extra drivers. I was able to use them with OpenEmu just like I use my DualShock4 controller. just had to do a little extra mapping.

**Comment by clobber** [comment]
Okay, I don't have those devices so if you can give me the vendor and product ID's for all or them as well as the **full** HID profile mappings for every single button including analogs, triggers/shoulders, d-pad, face buttons (e.g. HID Button 1 = "X", left analog = X/Y or Rx/Ry, axis directions, etc) I will consider setting up automappings.

This app may also be useful for you for looking at analogs and buttons: http://ysflight.in.coocan.jp/programming/macosx/joystick/e.html

To get a better idea of the information I'm looking for, see the Wii U profile in our Controller-Database.plist: https://github.com/OpenEmu/OpenEmu/blob/master/OpenEmu/Controller-Database.plist#L2628

I'd also like to have a HID profile exported for each so we can take a look:

With your device connected, run this app http://cl.ly/2K1K400t0H3p

Select your gamepad from the list and then go to File > Export Device Properties and then give us the plist it generates, by uploading to cloudapp, dropbox, transfer.sh, etc.

**Comment by zachcoyle** [comment]
Here are the HID profiles:
https://transfer.sh/9J0j1/joy-con-l.plist
https://transfer.sh/swPN9/joy-con-r.plist

**Comment by clobber** [comment]
Thanks. So it looks like the Joy-Cons are going to be a little too complicated and awkward to deal with automapping (plus no d-pad makes them pointless for retro gaming). Plus I don't want to deal with figuring out all the button assignments for the already weird design of these things - it's a hassle. We can do the Switch Pro Controller though.

**Comment by clobber** [comment]
Added in 09b721bf7fa4ebca1a7cc37e567afec35c137d09
