### ISSUE TITLE
Add "Turbo A" and "Turbo B" buttons

### ISSUE THREAD

**Issue by lisgray** [OpenEmu/OpenEmu#3086]
Can you add ability to set "Turbo A" and "Turbo B" as separate buttons with NES cores.
This like quickly the A or B button is pressed.
Like NES emulators and some pirate controllers has:
![e5849076-335f-11e6-8bd7-de387bdc5728](https://cloud.githubusercontent.com/assets/20662641/23747365/0ba934ca-04c8-11e7-8cb9-29601b7f07d7.jpg)
Nestopia for windows has it (Auto-fire A, Auto-fire B);  Thank you.

**Comment by clobber** [comment]
Please use the search before opening a new issue.
