### ISSUE TITLE
scph5502 scph5501 FIXED!  for ps1 (but with another problem)

### ISSUE THREAD

**Issue by RowdyFOXYT** [OpenEmu/OpenEmu#3087]
made it work a little but now it comes up with "the emulator can not load rom"

swap the md5 for scph5501 and scph5502 in the info.plast file in the Mednafen contents.

or

i got the edited file right here ⤵️
just replace it with this one

========================================================================

[Info.plist.zip](https://github.com/OpenEmu/OpenEmu/files/832075/Info.plist.zip)

========================================================================

**Comment by clobber** [comment]
Uh no, that isn't correct. You need to find the files the emulator requires, not edit the file to force it to accept an incorrect one.

Follow the guide: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files
