### ISSUE TITLE
please take a look

### ISSUE THREAD

**Issue by RowdyFOXYT** [OpenEmu/OpenEmu#3088]
<img width="423" alt="bios evidence" src="https://cloud.githubusercontent.com/assets/26282588/23770059/776b862c-0509-11e7-8ce1-7e746244abed.png">
#3087 @clobber

**Comment by RowdyFOXYT** [comment]
look at the three ticks.

You should try compare my version with your file and maybe see the differences.

**Comment by RowdyFOXYT** [comment]
Just saying i want my game to work.

And both Rayman 2 and crash team racing are not working either way whether I'm still using your repetitive method of trying to put the bios in to open emu instead of finding the problem straight a way by switching the md5s IN THE RIGHT ORDER THAT THAY SHOULD BE.

Also sorry if I am using caps.

Am Just trying to make a difference.

**Comment by clobber** [comment]
Sorry, but you are confused and don't know what you're talking about.

Here's the fix:
1) Remove your files.
2) Remove the **incorrect** hack you made to the core plugin.
3) Google for the correct files and import them. https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files

That's all the help I can offer.
