### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by mrkenshiro** [OpenEmu/OpenEmu#3090]
I have posted this issue before and was wondering if anyone has came across this issue. The advice clobber gave me before was no help. I am not trying to flood this message board with the same issue and be annoying. just simply trying to receive some help so i use open emu once again. I am running os x el capitan version 10.11.6   

![1891ed16-ebce-11e6-9e04-19f5aa0fd988](https://cloud.githubusercontent.com/assets/25507852/23805163/c9712694-058a-11e7-9dbf-822a0220c556.png)

**Comment by clobber** [comment]
Sorry, but there just isn't any reason to open a new issue when you already have one that you can post in. In your original issue, you should provide more information.

#3041
