### ISSUE TITLE
7z files won't import

### ISSUE THREAD

**Issue by DemonicGames** [OpenEmu/OpenEmu#3091]
I have 2 7z sega genesis files that the software refuses to import. I got them from [SonicRetro](https://info.sonicretro.org). the zip I got from the same place did have a successful import so it might not be the website. I have sonic spinball and 2 sonic megamix files (one is a zip and the other is a 7z. one of them is the most resent stable version, 3.0). just search them up on the site. you'll find them.

**Comment by clobber** [comment]
>just search them up on the site. you'll find them.
Uh I literally have no idea what you are trying to import. Why not just link me to them?

Anyway, the issue here is that you probably need to extract the files and import the individual ROMs that way, because they might be containing extra junk in the archives.

**Comment by clobber** [comment]
Also forgot to note, if they are romhacks and the files are .bin, they may not have correct header information so they are not being auto-detected. So,

Rename bin's to .md/.smd/.gen

**Comment by DemonicGames** [comment]
[Spinball](http://info.sonicretro.org/Sonic_Spinball_(16-bit_prototype)#Downloads)
[Megamix](http://info.sonicretro.org/Sonic_the_Hedgehog_Megamix)

**Comment by clobber** [comment]
Both Sonic_Spinball_(Beta).7z and Sonic_1_Megamix_v3.0.zip import to the Genesis library just fine here. OpenEmu 2.0.4.
