### ISSUE TITLE
Build Failed (Experimental) from command line

### ISSUE THREAD

**Issue by scottdcrompton** [OpenEmu/OpenEmu#3092]
Following error is received when building via command-line:

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/scottcrompton/Library/Developer/Xcode/DerivedData/OpenEmu-hhdvjldtbhggjmfhqdsffjmozxco/Build/Intermediates/Higan.build/Release/Higan\ (Performance).build/Objects-normal/x86_64/HiganGameCore.o HiganGameCore.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/3073#issuecomment-283987701
