### ISSUE TITLE
Use 2 Switch Joycons for One Player.

### ISSUE THREAD

**Issue by dangnelson** [OpenEmu/OpenEmu#3093]
You can connect Nintendo's new Switch Joycons to your mac using the bluetooth pairing button.
Together, two of them operate well as a great single controller for lots of old systems. 
The issue is, OpenEmu currently only accepts one input per player. 
So for instance, when trying to setup an N64 controller, using 2 Joycons won't work.

**Comment by clobber** [comment]
Not going to be possible here. Since both Joy-Con's pair and communicate separately, we can't make them act as 'one' in our app.

Instead we opted to just automap controls for the Pro controller. #3085

**Comment by lnikkila** [comment]
If you don’t have a pro controller like me, you can work around this by choosing the Keyboard input and mapping the joycons to keys using a separate mapper app like https://vividmachine.com/controllers (paid) or https://github.com/fyhuang/enjoy2 (free).

**Comment by clobber** [comment]
Input modifier apps such as those do not typically work with OpenEmu.

**Comment by lnikkila** [comment]
Well this is embarrassing, I didn’t try them in-game yet and you’re absolutely right :smile:

**Comment by rafalink1996** [comment]
I actually found that you _can_ use two Joy Con for one player. Just connect both Joy Con to your computer. In the controls window, select the input to either Joy Con and assign the buttons that belong to that Joy Con. Then select the input for the other Joy Con and assign the remaining buttons. For example, for PSP (which is the one that I got it to work; haven't tried with others, yet), assign D-Pad, Analog, L1, and Select to the directional buttons, Analog, L and minus buttons respectively on the Left Joy Con. Then assign Triangle, Circle, X, Square, R1 and Start to X, A, B, Y, R, and plus buttons respectively on the Right Joy Con. Close the Controls window and it should be working.

**Comment by lerous** [comment]
when I press the right joy con, it changes to the player2, not for the player1

How can I fix it

**Comment by rafalink1996** [comment]
First, map the buttons for _only_ the Left Joy-Con. Then, without pressing any button on the controllers, change the input to the Joy-Con (R) and map the buttons for _only_ the Right Joy-Con. 

Like I said, it worked for PSP (But the analog stick don't work analog-ly (?)). I've tested it with PS1 and N64. It didn't work; it would only recognize the Joy-Con you left selected in the controls window. But it worked just fine for PSP. It seems it only works for PSP at the moment. It's great for playing Kingdom Hearts: Birth by Sleep.

**Comment by lerous** [comment]
Thanks bro! 

I'm tired of openemu don't want to solve this, so I change other emu and use joystick mapper now.
