### ISSUE TITLE
Is it possible to transfer save states to new roms?

### ISSUE THREAD

**Issue by Masdrion** [OpenEmu/OpenEmu#3095]
I've been playing a Pokemon romhack using OpenEmu, and it recently got a patch. However, the only way to play the new version with my old data seems to be patching a new rom and transferring the old data to that rom. Since OpenEmu doesn't let you move save states to other roms, the save state format isn't compatible with other emulators, and I don't know any other way to access the save data, I'm kinda stuck here. Is there any possible way I could transfer my save data to the other rom, or is it impossible?

**Comment by clobber** [comment]
A save state taken from a previous patch version of a romhack will not be compatible with the newer, and vice versa.

However, you can transfer in-game battery save data, assuming the author of your romhack has maintained compatibility. [This guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files) should help you figure out how to do it.
