### ISSUE TITLE
Games won't start

### ISSUE THREAD

**Issue by herrbeimer** [OpenEmu/OpenEmu#3096]
I just bought an older iMac (Intel Core 2 Duo) running the last possible OSX version 10.8. That means that only OpenEmu 1.04 or lower is working on this machine.

It looks like 1.04 (and all other lower versions) is running well, that means I can click through the starting sequence and enter the main window. It is also possible to load any bios and import/lunch rome. BUT it is not possible to start them: I tired different games on different platforms, but the result is always the same: Nothing happens, not even any error message is coming up.

Anybody who has an idea what's wrong..?

**Comment by robotoad** [comment]
Sorry, but OpenEmu 1.x is unsupported.
