### ISSUE TITLE
Odyssey 2 Voice

### ISSUE THREAD

**Issue by vileperson** [OpenEmu/OpenEmu#3098]
Where do I put the O2EM "voice samples" for use with voice enabled games like KC's Crazy Chase? I have tried placing them in various places, and have yet to get the "voice" to work in . It works with the same rom, and the same samples, under a stand-alone O2EM install, elsewhere, but the OpenEmu folder structure is slightly different.

**Comment by vileperson** [comment]
Anyone? I still am not able to get this to work.

**Comment by WrestleCrapRD** [comment]
I've never heard O2 Voice work on a Mac ever.  Would love to have that!  Killer Bees with Voice is one of my all-time favorite games on any console...

**Comment by clobber** [comment]
Moved to https://github.com/OpenEmu/O2EM-Core/issues/1
