### ISSUE TITLE
A way to handle consoles with multiple names

### ISSUE THREAD

**Issue by StoppingBuck** [OpenEmu/OpenEmu#3099]
Hi! This is just a suggestion, but I think the project ought to have a way of handling the fact that several of the supported consoles were released under different names in different regions of the world.

As an example, I just spent a lot of time looking for the Odyssey2 core before realizing that it was called "Videopac+" (its European name AFAICS). Previously, I've had the same issue with Sega Genesis before realizing that it was called "Sega Mega Drive".

Obviously, I'm not advocating for duplicate cores under different names - but it would be nice to have the different names displayed somewhere in OpenEmu to help people from other regions understand which console they're looking for. Maybe in the 'Available libraries' section (which by the way needs a larger window)?

**Comment by clobber** [comment]
That already happens automatically based on your locale...
