### ISSUE TITLE
Preset scaling when launching a game (feature request)

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/OpenEmu#3101]
I'm not sure how to describe this, but sometimes OE (running a PlayStation game), gives me the option to scale to 1x only, which is i think the original PSX resolution. However, depending on how much i stretched the window myself the last time playing, it sometimes gives me the option to use 2x and 3x too! Though with 3x and fullscreen i have lots of sound glitches (old mac i guess)..

Anyway, is it possible to implement the feature that all games are forced start in 1x (or 2x / 3x / etc.) window-mode with their respective resolution? Optional of course. (Like all games can use "nearest neighbour" first)

**Comment by clobber** [comment]
Depending on your resolution and if your Dock is hidden or not, OpenEmu will launch games in the highest scaling factor possible when in windowed mode. Not going to add any other options for this though.

**Comment by PlutoX86** [comment]
Fair enough, thanks.
