### ISSUE TITLE
Sidebar doesn't remember and restore width between launches

### ISSUE THREAD

**Issue by emilyst** [OpenEmu/OpenEmu#3103]
Most minor issue, I know. But every time I start OpenEmu, I notice that the label for console "Super Nintendo (SNES)" is condensed to fit into the space allotted for it by default.

![capture 2017-03-22 at 19 56 39](https://cloud.githubusercontent.com/assets/528994/24229998/f6884406-0f39-11e7-9d68-123079c2276a.png)

I am then obliged to resize the sidebar to correct this so that it doesn't distract me.

![capture 2017-03-22 at 19 56 50](https://cloud.githubusercontent.com/assets/528994/24230010/08055c96-0f3a-11e7-9aef-e487df8867c1.png)

I figure the easiest fix is just to permanently remember this resizing rather than having to do it every time I open the application.

**Comment by robotoad** [comment]
I can't reproduce this. Is there anything unique about your setup?

**Comment by PlutoX86** [comment]
Same here. Before compiling i set sidebar width to 195.0 ... Much better.

**Comment by emilyst** [comment]
> Is there anything unique about your setup?

Not that I know of. Downloaded the app off the site and ran it. It's the experimental version, but I doubt that matters.

> Also, what version of macOS are you running?

10.12

**Comment by robotoad** [comment]
This bug was hidden from me because window restoration restores the splitter position. If you have "Close windows when quitting an app" enabled in System Preferences, disable it as a workaround.
