### ISSUE TITLE
PSX Games Freezing

### ISSUE THREAD

**Issue by BadgerGhostMan** [OpenEmu/OpenEmu#3104]
Several playstation games I try to play (specifically, Medievil, Crash Team Racing, and Strider 2) freeze the OpenEmu program. I can't even quit after it freezes, I have to force quit it. Any ideas of  what can fix this?

Addendum: It didn't always freeze the games at these times, it just started happening suddenly.

**Comment by clobber** [comment]
Thanks for reporting. I noticed this with a few PS1 games (not the freezing, but states not loading), but it could be due to save state incompatibility issue between some versions - not sure yet.

What happens if you try to load the games without restoring an autosave state on first load?
1) Go to OpenEmu > Preferences > Library, click "Reset warnings"
2) Open your game and click "No" if prompted to "Continue where you left off"

**Comment by BadgerGhostMan** [comment]
It doesn't make a difference. If you want the easiest example to find with the freezing, just boot up Crash Team Racing, and wait for it to get to the copyright screen, it always freezes for me there (and only started to do so recently, possibly after the 2.0.4 update.)

**Comment by clobber** [comment]
Crash Team Racing for which region exactly? PAL?

Are you using OpenEmu 2.0.5 with the Mednafen 0.9.43 core plugin? If not, update to both of those first.

**Comment by BadgerGhostMan** [comment]
North American Region, I'm pretty sure. I'm updated on both of those.

**Comment by clobber** [comment]
> just boot up Crash Team Racing, and wait for it to get to the copyright screen, it always freezes for me there

I cannot replicate that with "CTR - Crash Team Racing (USA)" from just booting the game. I think you have a bad rip of the game. Try getting another copy, of the NTSC version, and see if anything changes.

**Comment by BadgerGhostMan** [comment]
I downloaded a rom of a european version from a different website and had the same problem.

**Comment by clobber** [comment]
I can't replicate that on multiple machines, and if you really had the PAL/European version, the app would have been prompting you to import the required SBI file for Crash Team Racing. Did it?

Try finding other rips of the game; look for "redump".

**Comment by BadgerGhostMan** [comment]
Yes, turns out what I though was a PAL version was mislabeled. I found another one and it prompted me to import the SBI file. I also found what claimed to be a red ump, and it didn't work.

**Comment by micochops** [comment]
Hello @BadgerGhostMan!

I'm also not able to replicate your issue.

Dumps of PSX games following the redump guide are usually made up of two files:
.bin file and .cue file.

Kindly check the md5 hash of the .bin file. According to redump, it should have an md5 hash of:
ab95bfca8a4bb3d90daa6519acf6e944

The .cue file should look EXACTLY like this:

FILE "CTR - Crash Team Racing (USA).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

Note that the name inside the quote marks depend on the filename of the .bin file.
It can change.
Does it match? If not, then it's another bad dump of the game.

**Comment by clobber** [comment]
Definitely want to use what are considered 'good' rips of the games. Look for "redump"
