### ISSUE TITLE
Arcade games requiring bsmt2000.bin won't run

### ISSUE THREAD

**Issue by MScoutsDCI** [OpenEmu/OpenEmu#3105]
So far I've only tried this with Police Trainer and Battletoads.  Both of those games will not load and the console calls out bsmt2000.bin as the missing BIOS file it needs.  That file is included in the complete 0.149 collection so I tried placing it both in the roms/Arcade folder and the BIOS folder in Application Support/Openemu but the console still says it can't be found.

**Comment by clobber** [comment]
Those work. bsmt2000.zip (not unzipped) is required to be in the same folder as the games. They all need to be from a 0.149 romset.

Also, my usual reply about Arcade/MAME: https://github.com/OpenEmu/OpenEmu/issues/2937#issuecomment-265036062
