### ISSUE TITLE
Request feature : add turbo combination

### ISSUE THREAD

**Issue by black-pudding** [OpenEmu/OpenEmu#3106]
It would be cool if "select + a or b or x or y" maintained 2 sec would trigger the turbo on that button .

**Comment by clobber** [comment]
Sounds like you mean "Rapid Fire" but not something we're probably going to add.

#933

Instead you may want something like https://www.amazon.com/Buffalo-Classic-USB-Gamepad-PC/dp/B002B9XB0E or https://www.amazon.com/Elecom-Button-Endurance-million-JC-U3808TWH/dp/B01N7HZM0Q
