### ISSUE TITLE
Logitech Dual Action

### ISSUE THREAD

**Issue by Avorymiller** [OpenEmu/OpenEmu#3109]
I have had a problem with my Logitech Dual Action controller.  The 1, 2, 3, and 4 buttons don't work.  I have tried to remap the buttons but when I press them, nothing happens.

**Comment by clobber** [comment]
If your Logitech controller has a switch on the back, it must be set to DirectInput (D).

Also check here for possible issues: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by Avorymiller** [comment]
I read about the switch, but my controller does not have one.  I have read the link that you included but it was no help.

**Comment by clobber** [comment]
I have this same gamepad and have just tested it: input does work fine.

When it doesn't, it is usually interference from another running application. Go through the guide again and maybe try a restart, then only run OpenEmu and see if it works.
