### ISSUE TITLE
Gamesir G3s will not map controls

### ISSUE THREAD

**Issue by Giggsy13** [OpenEmu/OpenEmu#3110]
I have used this controller before with steam and GOG games and it is connected just fine to the system. When I try to map it to specific controls, nothing shows up as if it is not detecting any interaction with the controller. Is there a trick for this controller?

**Comment by clobber** [comment]
Never heard of it.

Try here first though: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
