### ISSUE TITLE
Transfer Save States

### ISSUE THREAD

**Issue by jalben1** [OpenEmu/OpenEmu#3111]
Hello! 
I'm playing soul silver on Open emu and it has been running great aside from a few screen glitches now and then. 

My problem is I used a randomizer tool to edit the game but in the edited version I have to start from the beginning. Is there a way to transfer or open my save states from the unedited version of the game in the new edited version?

Any help would be appreciated.

**Comment by clobber** [comment]
This guide should help enough for you to figure out how to do it: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files
