### ISSUE TITLE
Openemu decided to completely stop working

### ISSUE THREAD

**Issue by dejanilmic** [OpenEmu/OpenEmu#3113]
OpenEmu is a fantastic emulator application and has been incredibly easy to use since (about) July. I never had any trouble using it, and all my games ran smoothly--up until today. I opened the application and proceeded to click on one of my games and nothing happened. Usually within a second the game will start up. There's not even an error message or a system preferences notification. There's just no reaction to me opening a game. I have tried deleting and reinstalling OpenEmu and restarting my computer. I'm truly the opposite of tech savvy, so any and all help is greatly appreciated.

**Comment by robotoad** [comment]
What version of OpenEmu and macOS are you running?

**Comment by clobber** [comment]
Lack of info; closing.
