### ISSUE TITLE
Mayflash Gamecube Wii U adapter and Wii U pro controller not mappable

### ISSUE THREAD

**Issue by o0willdabeast0o** [OpenEmu/OpenEmu#3114]
The mayflash only shows up if you switch the box into PC mode, which no other application uses. When you try to map the buttons, sometimes nothing is an input, sometimes only the R button is an input, and sometimes it will just rapidly input that you are pressing the R button (when you aren't) and keep mapping subsequent controls to the r button - and + until you reach the bottom.

The Pro controller has similar issues as the last thing mentioned, except it rapidly scrolls through mapping everything as Analog Up and Analog Down. Very strange!

**Comment by clobber** [comment]
This looks like #1773
