### ISSUE TITLE
ARv3 Cheat Codes

### ISSUE THREAD

**Issue by hjurin** [OpenEmu/OpenEmu#3118]
It is not possible to enter ARv3 cheat codes. I know they cannot be differentiated from ARv1 with the length, but the user could just indicate what encryption he wants to use.
It makes all cheat codes that need Anti-DMA not work...

**Comment by clobber** [comment]
We know. https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes#gba-cheats

Waiting on some kind of heuristics in mGBA to automatically detect them.
