### ISSUE TITLE
Xbox One S Bluetooth Controller Support

### ISSUE THREAD

**Issue by Cruplezone** [OpenEmu/OpenEmu#3119]
The new xbox one s controller connects natively over bluetooth to macOS without need for a driver or adapter. However, it is not supported by openemu. Please add support!

Currently it appears as an input device but one the xbox button is registered during binding

**Comment by clobber** [comment]
OpenEmu supports it just fine, it just doesn't automap controls so one would have to map themselves.

As for input issues in prefs, try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by Cruplezone** [comment]
Ugh I don't know what to tell you, but it's not working over here on sierra 10.12.4. It used to work but after the latest mac update looks like not... only the xbox button is being registered as button 547... do you need me to film a video or something?

**Comment by tresni** [comment]
@clobber Is there an easy way to create/submit mappings?
