### ISSUE TITLE
PS3 controller SIXAXIS detection if analogue sticks are used

### ISSUE THREAD

**Issue by timekiller89** [OpenEmu/OpenEmu#3121]
Hi,

If using the analogue sticks on a DualShock 3 SIXAXIS controller (official), to control the game, the emulator seems to sense the SIXAXIS motion sensor, which is highly irritating when trying to control a character in a game. The only fix I found was to use the D-Pad instead of the analogue sticks, which is annoying because games like Street Fighter would work much better on an analogue stick and other games would be flowing better in terms of control with it.

Could either:
* The option to disable SIXAXIS motion be implemented
* The detection of SIXAXIS movement be dropped altogether

I don't have a wired PS3 controller that properly works here, I do have one but pushing the left analogue stick to the left on it doesn't properly work, so have to use a USB-connected wireless one, and my (unofficial) original Xbox controller doesn't work with OpenEmu or macOS either, so can't use that.

I'm on macOS Sierra, using OpenEmu release version 2.0.5 and on a MacBook Air from 2015.

Thanks,
timekiller89

**Comment by clobber** [comment]
Motion controls won't work; there's no way OpenEmu or emulated games could be reading the sensor. I have an official DS3 sixaxis and cannot replicate this. Only thing I can think of is you have some other software or driver installed that is.
