### ISSUE TITLE
Audio stutter on SNES9x

### ISSUE THREAD

**Issue by revmischa** [OpenEmu/OpenEmu#3122]
Running 2.0.5 719-g369c3a2-Release
On my OSX 10.12.4 system, the audio stutters heavily when playing SNES games with the SNES9x core. When beginning emulation or if I switch the device sample rate, it plays smoothly for about a second or two, then begins stuttering.
This does not happen on the Higen core or other systems.

My audio device is a 10-channel PreSonus firewire interface.

**Comment by clobber** [comment]
I don't have your external audio device setup, but I cannot replicate any audio issues using SNES9x and not sure how it could even be affected - OpenEmu drives the emulation loop. Higan is definitely the SNES emulator you want to use though, as it has more accurate audio emulation and timings. That said, our SNES core plugin needs an update from upstream that may improve audio but I don't know if that will relate to your issue.

Your issue could also be a bug with a certain game. Also ensure that you are not using a filter/shader that your GPU cannot handle.

**Comment by revmischa** [comment]
I have tried multiple games and filters and had the same effect

**Comment by clobber** [comment]
Interesting. I'll ping you back here when an SNES9x core update goes out and we'll see if that had any change.

**Comment by clobber** [comment]
The SNES9x core plugin was updated to 1.54.1.

Restart the app and an updated SNES9x core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for SNES9x 1.54.1.

Try launching a SNES game and switching it to the SNES9x core plugin to see if it had any effect on your issue.

**Comment by revmischa** [comment]
I tried restarting but my SNES9x core does not appear to be updating
![screen shot 2017-04-06 at 5 21 08 pm](https://cloud.githubusercontent.com/assets/245131/24781425/849804c8-1af4-11e7-9c1d-bd22659fd8a0.png)

**Comment by clobber** [comment]
That update was just recently removed (today) due to another issue, but I'll ping you back here once it's pushed back out again.

**Comment by clobber** [comment]
Okay, another update was pushed. 1.54.1.1

**Comment by revmischa** [comment]
No dice in 1.54.1.1
