### ISSUE TITLE
(Error de Foundation._GenericObjCError 0.)

### ISSUE THREAD

**Issue by krlos2228** [OpenEmu/OpenEmu#3124]
Greetings openemu team I have a mac os sierra version 10.12.4 I install the application from your website and it gives me the following error:  the operation couldn't be completed (Error of Foundation._GenericObjCError 0.)

Please if anyone knows how to solve this error I appreciate it

**Comment by DRRN** [comment]
Good Luck!  

I had this issue months ago... It never got resolved.
It's a really great program... I hope you get answers!

**Comment by clobber** [comment]
Closing for lack of details. Although this may have to do with using third party software to unzip the file which corrupts the binary. Instead, right click on the zip file and select Open With > Archive Utility (the built-in tool for macOS).

#3044

**Comment by EmuUser0-01** [comment]
I have the same problem too. My openemu was working perfectly until I messed up. Honestly, I'm such an idiot. All I wanted to do was find an openemu compatible with my 32 bit computer for the n64. I downloaded and opened too many openemu and then this error popped up. I know, very stupid of me.

**Comment by EmuUser0-01** [comment]
There's an answer for this but I believe you all figured it out already. I went to the application support and deleted everything in openemu but not my saved files, bios, and games. I downloaded the latest openemu and it worked, everything is back to normal. I got this idea from a very old post, I forgot who post it.
