### ISSUE TITLE
Saturn multi-disc game won't import properly

### ISSUE THREAD

**Issue by xXSlick-JimmyXx** [OpenEmu/OpenEmu#3126]
I recently downloaded the English-translated .bin and .cue files for the Utena game on Sega Saturn, but after following the steps for importing multi-disc games, it did not import properly.  While I realize Saturn is experimental and therefore unsupported, this seems to be an issue with how OpenEmu imports the games themselves and not with Yabause/Mednafen.

Attempting to import the .m3u sheet yields no results.  It will import when the sheet reads the .bin files instead of the .cue files, even getting the boxart and proper name for it in the library, but clicking it yields an error message and stops the game from running.  Curiously, I found the game in the PSX library (without its boxart and real name), but attempting to run it or delete it would crash OpenEmu.

Attempting to import the Disc 1 .cue file by itself does not yield any results whatsoever.

Interestingly, the Disc 2 .cue file can be imported successfully by itself, but OpenEmu recognizes that it is part of a multi-disc game and refuses to run when clicked (it instructs me to import the .m3u file and directs me to the page on how to do that).

I also tried creating pseudo .cue files that read the original ISOs instead of the .bin files, then made a .m3u sheet to read those.  That actually imported correctly, boxart and all, but running it brought me to the Saturn home screen with the message "Disc could not be read" (this happened with both cores, hence my suspicion that this is an OpenEmu problem, not a Yabause/Mednafen problem).

I have the most up-to-date version of OpenEmu (2.0.5).

**Comment by clobber** [comment]
>Attempting to import the Disc 1 .cue file by itself does not yield any results whatsoever.

Sounds like this romhack/translation is missing its proper header, so it cannot be identified. In a hex editor, show me what the beginning of the first binary (disc 1) looks like.

**Comment by clobber** [comment]
I should also note that forcing an import of the m3u by placing bin/iso filenames inside the m3u file instead of cue will not work. Mednafen (as per the guides) absolutely requires these games to be loaded via cue sheets (or clonecd ccd). Also, the Yabause core plugin was deprecated and removed from distribution - so that one won't ever be supported.

**Comment by xXSlick-JimmyXx** [comment]
![screen shot 2017-04-06 at 1 08 46 am](https://cloud.githubusercontent.com/assets/26951161/24738730/a9c1a2c0-1a65-11e7-9d06-c467dfa82062.png)

**Comment by clobber** [comment]
Header appears intact. So,

* Remove all occurrences of the imported discs from your library.

* You may have to manually remove them if they somehow ended up in the wrong library (not sure how that is possible), so check the folder `~/Library/Application Support/Game Library/roms` (~ meaning your Home folder where ~ is your username. [Guide here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) if you don't know this.

* Actually follow the guides and properly import your multi-disc Saturn game. That means your binaries can be cue+bin or cue+iso or whatever, but they **MUST** include a valid cue sheet, and add them to the m3u file. Then import just the m3u file. Don't try to outsmart the importer.
