### ISSUE TITLE
macOS Sierra Update 10.12.4 

### ISSUE THREAD

**Issue by ajarshem** [OpenEmu/OpenEmu#3129]
I just updated to macOS 10.12.4.  I was playing Super Mario World right before the update and everything was working just fine.  After the update, all of my SNES ROMS give an error saying "The emulator could not load ROM" when I try to open them.  My DS files appear to be working fine.

**Comment by enemyboss** [comment]
I have also experienced snes roms recently failing to load.  A work around that worked was unzipping my rom files and adding the .sfc file.   My save states still worked .

**Comment by clobber** [comment]
#3127
