### ISSUE TITLE
Default Core Issue

### ISSUE THREAD

**Issue by ExacjiuOfErea** [OpenEmu/OpenEmu#3138]
I'm trying to find the cores I can use for my platforms. I'm following the user guide for default cores: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Default-Cores , but when I right click the console's name on my console library sidebar I do not see the option to select a different core. Could you help me with this?

**Comment by robotoad** [comment]
You need to have the cores installed first. Go to Preferences->Cores and install the cores you want to use.
