### ISSUE TITLE
Request for a scale to fit aspect ratio option

### ISSUE THREAD

**Issue by clash64** [OpenEmu/OpenEmu#3144]
I know you already said no to this and I understand your reasons. But just the same and I believe others are clamoring for this, I thought I'd still request, if it's not asking too much, can you please include an option where it's possible to stretch the 4:3 video to 16:9? Hope you're okay with this now. Thanks and cheers! Wonderful job on OpenEmu. =)

**Comment by clobber** [comment]
>I know you already said no to this and I understand your reasons.

Then you know the answer. :)

**Comment by clobber** [comment]
#2430
