### ISSUE TITLE
2-player vs game issue

### ISSUE THREAD

**Issue by AugDaug** [OpenEmu/OpenEmu#3145]
Hi - I'm running the latest version of OpenEMU, and I have a problem where a game (like NBA Jam on SNES) won't let me select 2 DIFFERENT teams for a "vs" game (if I want to play against a friend). It will only allow us to play on the SAME team. Any inputs from our two separate controllers (two corded Playstation2 controllers using an adapter going to a single USB port, which works with other multiplayer "vs" games, just not NBA Jam) only controls the SAME team. 
I feel certain this used to work in previous releases of OpenEMU (we used to be able to play against each other in NBA Jam). Perhaps this is only an issue on certain games, where you're able to be on the same team OR vs each other? Anyone else having this issue?

**Comment by clobber** [comment]
This is not an OpenEmu issue, but an issue with the Snes9x multi tap default configuration with this particular game (or game settings? Double check a manual?), and definitely not new. For now switch to playing this game using the Higan core plugin instead. See guide https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Default-Cores

**Comment by AugDaug** [comment]
Thanks clobber - that worked - thx for the swift reply - you guys rock =)
