### ISSUE TITLE
Screen dims when playing games with dark backgrounds like Galaxian, Ms. Pac Man

### ISSUE THREAD

**Issue by clash64** [OpenEmu/OpenEmu#3146]
How do I resolve this? My Mac Mini mid-2011 Core i5 running Sierra has no automatically adjust brightness option in the Display preference pane. And I tried the halfdim disable solution in the Terminal but the problem still persists.

**Comment by clobber** [comment]
Doesn't look like an OpenEmu issue to me. Try Google?

Arcade/MAME is 'experimental' and unsupported right now.
