### ISSUE TITLE
Feature Request: BLE support

### ISSUE THREAD

**Issue by adespoton** [OpenEmu/OpenEmu#3147]
Since Joypad Legacy is no longer available and Ultimate Gamepad is not compatible, why not implement BLE Central in OpenEmu?

http://developer.apple.com/library/mac/#documentation/CoreBluetooth/Reference/CBCentralManager_Class/translated_content/CBCentralManager.html

MFI support would also be nice, but BLE would at least allow for GoBLE from dfrobot.com, as well as other BLE input devices.

**Comment by clobber** [comment]
No, not really interested in this. Instead, someone can debug where those Joypad Legacy type apps stopped working and try to fix it.

Also, [MFi devices](https://afterpad.com/mficontrollers/) already work as long as they can pair with the Mac (stuff like Stratus XL, Nimbus, Horipad, etc).

**Comment by adespoton** [comment]
Understood, but the ticket for the joypad legacy apps was already rejected as 'not interested ' -- which means no support for properly behaving BLE inputs and no support for keyboard emulators; kind of limits the input device field to registered MFI and HID devices, of which iOS devices are neither.

-Andrew

**Comment by clobber** [comment]
No it wasn't, and as I said support for those less-than-ideal input devices used to work. There are at least a few dupes open right now pointing that out. If someone is interested enough in fixing support, then that is the proper course of action. Implementing something new with very little interest compared to HID, isn't. Playing these games by mashing ones fingers against glass is a really lousy experience.
