### ISSUE TITLE
Unable to import .m3u file for game including .ccd, .cue, .img, .sub files 

### ISSUE THREAD

**Issue by shinsukato** [OpenEmu/OpenEmu#3148]
1) Wrote the .m3u file using TextEdit set to PlainText. Contents of the file are:

> Lunar Silver Star Story Complete (Disc 1).cue
> Lunar Silver Star Story Complete (Disc 2).cue

2) Moved to a folder with the game files. Contents of the folder are:

> Lunar Silver Star Story Complete (Disc 1).ccd
> Lunar Silver Star Story Complete (Disc 1).cue
> Lunar Silver Star Story Complete (Disc 1).img
> Lunar Silver Star Story Complete (Disc 1).sub
> Lunar Silver Star Story Complete (Disc 2).ccd
> Lunar Silver Star Story Complete (Disc 2).cue
> Lunar Silver Star Story Complete (Disc 2).img
> Lunar Silver Star Story Complete (Disc 2).sub
> Lunar Silver Star Story Complete.m3u

3) Drag and drop the .m3u file into OpenEmu

No response, no error message. I can import the individual disc files but obviously it then won't run.

**Comment by shinsukato** [comment]
I've also tried changing the .m3U file to list the .ccd or .sub files instead.

**Comment by clobber** [comment]
1.  Make sure those files don't already exist in your Library, i.e. they are not already imported.

2. See if one of the discs will import via just the .cue or .ccd alone.

>.m3U file to list the .ccd or .sub files instead.

Well that isn't going to work, at least, not with .sub files. An M3U can take .ccd files though.

Also, is this the Saturn or PS1 version of that game?

**Comment by clobber** [comment]
Cannot replicate this with a clone cd rip of this game. My M3U contains:
```
Lunar Silver Star Story Complete CD1.ccd
Lunar Silver Star Story Complete CD2.ccd
```

And when drag and dropping the M3U file, OpenEmu successfully imports everything into the PS1 library:
```
Lunar Silver Star Story Complete CD1.ccd
Lunar Silver Star Story Complete CD1.img
Lunar Silver Star Story Complete CD1.sub
Lunar Silver Star Story Complete CD2.ccd
Lunar Silver Star Story Complete CD2.img
Lunar Silver Star Story Complete CD2.sub
Lunar Silver Star Story Complete.m3u
```

My guess is you already had those individual disc files imported before the M3U, and both of our disc guides ([User guide: CD based games](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) & [User Guide: Required m3u file missing](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing) state they must not be, so actually read those first.
