### ISSUE TITLE
Cannot open NDS games such as Pokemon Platinum

### ISSUE THREAD

**Issue by Reliew** [OpenEmu/OpenEmu#3152]
I recently updated OpenEmu to its latest update, I'm on a Mac running 10.11.6, and when I downloaded the roms for Pokemon Soul Silver, Heart Gold, Platinum, Pearl, etc. I get a message saying "The emulator could not load ROM." I've been using EmuParadise to get roms and all of the other games work, including the GBA games and also the later NDS games like Pokemon Black. When I got the message for the game that didn't work I tried downloading different rom versions and going to other sites, but I got the same result every time, so I'm thinking it's an issue with OpenEmu. Any suggestions? 
(p.s. I lost the actual game cartridges that I bought, so I can only get online files)

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
