### ISSUE TITLE
Extra newlines in M3U file crashes importer

### ISSUE THREAD

**Issue by milesheilman** [OpenEmu/OpenEmu#3153]
Hi,

I am on 2.0.5, attempting to import a multi disc game using an .m3u file.  The app crashes immediately after either dragging the m3u file or using the "File>>Add to Library" option.  This is using a Mac mini macOS sierra 10.12.4.

.bin/.cue and .m3u files are all in the same folder.  I am attaching all 3 plus the crash log...
[CrashLog.txt](https://github.com/OpenEmu/OpenEmu/files/925646/CrashLog.txt)

**Comment by milesheilman** [comment]
~/SyphonFilter2]$ more Syphon\ Filter\ 2\ \(USA\).m3u 
Syphon Filter 2 (USA) (Disc 1).cue
Syphon Filter 2 (USA) (Disc 2).cue

_________________

~/SyphonFilter2]$ more "Syphon Filter 2 (USA) (Disc 1).cue"
FILE "Syphon Filter 2 (USA) (Disc 1).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

__________________


~/SyphonFilter2]$ more "Syphon Filter 2 (USA) (Disc 2).cue"
FILE "Syphon Filter 2 (USA) (Disc 2).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

**Comment by clobber** [comment]
I am able to replicate this crash by adding extra new lines/carriage returns at the end, inside my M3U file like so:
```
Syphon Filter 2 (USA) (Disc 1).cue
Syphon Filter 2 (USA) (Disc 2).cue


```

You can work around the crash by removing them from your M3U, and then reimporting.

**Comment by clobber** [comment]
Fixed in commit https://github.com/OpenEmu/OpenEmu/commit/e289a9eec1f7d38f3e473630f26a4d592a077fc0
