### ISSUE TITLE
OpenEmu crashes whenever Switch Pro Controller is connected

### ISSUE THREAD

**Issue by superwiifan** [OpenEmu/OpenEmu#3154]
When I saw that the new update offered Switch Pro controller mapping automatically, I was excited, so I immediately updated, connected my Pro Controller, and tried to start playing a game. However, whenever I went into Preferences, or when I tried to play a game, the app would crash.  However, when I disconnect the Pro Controller, the app works fine.

OS: MacOS 10.12.4
OpenEmu version 2.0.5

**Comment by clobber** [comment]
Gotta use the search.

https://github.com/OpenEmu/OpenEmu/issues/3116#issuecomment-290622500

**Comment by superwiifan** [comment]
Sorry I've never used GitHub b4 :/
