### ISSUE TITLE
Couldn't Play PS2 Game

### ISSUE THREAD

**Issue by abhisoni96** [OpenEmu/OpenEmu#3155]
I have installed Open EMU first time but not able to play any PS2 game. As per documentation I have installed all ROMS and also PS2 BIOS which is showing enabled in preferences window. Once i drag CUE file into window nothing happens.
Console is showing following errors: 
18/04/17 11:12:51.660 PM OpenEmu[35669]: SCD data track: file:///Volumes/Abhishek/Downloads/WWE.iso
18/04/17 11:12:51.660 PM OpenEmu[35669]: ''
18/04/17 11:12:51.660 PM OpenEmu[35669]: ''
18/04/17 11:12:51.660 PM OpenEmu[35669]: Error Domain=OEImportFatalDomain Code=3 "(null)"

Environment Details:
OS X EI Captain - Version 10.11.6
Core i7 16 GB RAM 
Open EMU: 2.0.5
Core Mednafen: 0.9.43

Note: Nitendo(NES) Games are working fine(Mario Bros).

**Comment by clobber** [comment]
PS2 games? No where on our website or wiki does it say we support PlayStation 2 games.

Read the guide here: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games

**Comment by flashboss** [comment]
why ps2 is not supported in OpenEmu?

**Comment by MaddTheSane** [comment]
The Experimental download of OpenEmu should let you play some games using the "Play!" emulator.
Note that support will be spotty because Play! is fairly immature in comparison to PCSX2.

**Comment by flashboss** [comment]
why not include PCSX2 in openemu?

**Comment by FonkinS** [comment]
> why not include PCSX2 in openemu?

Because no-one has bothered implementing it yet? Remember that this is an open-source project. If you really want something to be added, do it yourself
