### ISSUE TITLE
Odyssey2: All keyboard input ignored

### ISSUE THREAD

**Issue by invalidname** [OpenEmu/OpenEmu#3156]
I just updated to OpenEmu 2.0.5 and all keyboard input is completely ignored on Odyssey2. This means I can't start a game (since most Odyssey2 games start by pressing "1" for one player), and saved games are unplayable with keyboard because the arrow keys used for the joystick are also ignored.

Sorry, I don't have ROMs for any other system, so I don't know if this is Odyssey2-specific.

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by invalidname** [comment]
What I'm saying is that keyboard input _had_ been working prior to updating to 2.0.5. Oh well, never mind, I guess.

**Comment by clobber** [comment]
And what I'm implying is, there were no changes in 2.0.5 to affect keyboard input in the app or the core plugin, so the issue is likely on your end which is why I linked the input troubleshooting guide. Oh well, then!

**Comment by bryce13950** [comment]
This is still an issue. I am not sure if it did work at some point, and if it is now no longer working, but none of there is no way to send in inputs from the keyboard that was on the console in the current build. This thus means that you cannot get past the "Select Game" screen that every game boots to.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/6487928/87209478-57516080-c312-11ea-9d04-c580240d4f47.png">
