### ISSUE TITLE
Panzer dragoon 3/saga/azel rpg

### ISSUE THREAD

**Issue by cholvac007** [OpenEmu/OpenEmu#3158]
since Panzer dragoon saga is a mdg i createt an m3u file for it but it shows up in the wrong console (ps1 instead of saturn) and it wont start up. could someone please help me?

**Comment by clobber** [comment]
Mdg? Doesn't sound like a supported format to me. Please read the disc and M3U guides. Cannot help you beyond that.

**Comment by clobber** [comment]
Oh I get it. Mdg meaning "multi disc game." Inventing TLA's...

I don't know how you managed to get it to import to the wrong system (from the code I don't know how that is possible because we ID the files), but your M3U setup has to be very wrong. Without exact details about what you are importing, there is no way to troubleshoot. So maybe you want to provide details?

**Comment by cholvac007** [comment]
yes
panzer dragoon saga disc 1 of 4 (u) (saturn) to panzer dragoon saga disc 4 of 4 (u) (saturn)

**Comment by clobber** [comment]
You're going to have to be more detailed that that dude

**Comment by cholvac007** [comment]
![bildschirmfoto 2017-04-23 um 19 51 54](https://cloud.githubusercontent.com/assets/14243003/25315970/5b91a396-285e-11e7-9450-c8d421f46a0e.png)
i set the cue file in textmate of all 4 discs

**Comment by cholvac007** [comment]
![bildschirmfoto 2017-04-23 um 20 01 15](https://cloud.githubusercontent.com/assets/14243003/25316030/b8472880-285f-11e7-92e0-5c2aa21b4a8a.png) 
so it looks like this before i get the m3u name changed

**Comment by clobber** [comment]
Sorry but this is very confusing. You have one folder with a set of files, then you have a M3U file referencing completely different names. Here's what I need from you:

* Exact steps to replicate the problem.
* All file names and folder locations of your files you are trying to import.
* I also need to see the contents of your cue sheets and the M3U file you tried to import.
* I would also like a link to where you downloaded your set of files so that I can test it out. (Don't worry, I will remove the link after you posted it).

**Comment by cholvac007** [comment]
all right so first of the link: https://www.emuparadise.me/Sega_Saturn_ISOs/Panzer_Dragoon_Saga_Disc_1_of_4_(U)/371

**Comment by cholvac007** [comment]
i download all 4 gamedisc and then i normaly unzip them so that they look like a normal folder. next i open the textmate and put the datas in

**Comment by clobber** [comment]
That's not the information I need.

I need to know what the contents of your M3U and cue sheets are and their locations.

**Comment by cholvac007** [comment]
there is the m3u file opened
![bildschirmfoto 2017-04-23 um 20 57 05](https://cloud.githubusercontent.com/assets/14243003/25316442/7e95ee84-2867-11e7-9670-05c99ebc5500.png)

**Comment by cholvac007** [comment]
and here are the cue files

**Comment by cholvac007** [comment]
![bildschirmfoto 2017-04-23 um 21 01 09](https://cloud.githubusercontent.com/assets/14243003/25316470/1942837a-2868-11e7-860f-2d00deb59290.png)

**Comment by clobber** [comment]
Hä was?! Uhh, can you please explain why your M3U file is referencing:

```
PANZER DRAGOON SAGA DISC 1 OF 4 (US).cue
PANZER DRAGOON SAGA DISC 2 OF 4 (US).cue
PANZER DRAGOON SAGA DISC 3 OF 4 (US).cue
PANZER DRAGOON SAGA DISC 4 OF 4 (US).cue
```
and yet the files you downloaded are named:

`042 Panzer Dragoon Saga Disc 1 of 4 (U).cue`, `042 Panzer Dragoon Saga Disc 2 of 4 (U).cue`, `042 Panzer Dragoon Saga Disc 3 of 4 (U).cue` and `042 Panzer Dragoon Saga Disc 4 of 4 (U).cue`.

What you are trying to do absolutely **does not make sense**. It is clear you have not read the [import guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) so I suggest you read it closely. You don't even have all your files together in the same folder as the guide states! Anyway, I am not going to hold your hand here when our guide is very precise with step-by-step directions.

Even with this broken setup, I cannot replicate the issue of the M3U file being imported into the wrong library.

Another thing, the cuesheets for your games contain invalid hardcoded paths (FILE "C:\SATURN\042 PANZER DRAGOON SAGA DISC 1 OF 4 (U).BIN" BINARY) so you will need to edit those to make them correct, by removing the "C:\SATURN\" portion. That information is also in our [guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-my-cue-sheet-or-ccd-wont-import).

**Comment by clobber** [comment]
One more thing- you also need to be using at least OpenEmu 2.0.5, if you are not already.
