### ISSUE TITLE
Crash when importing .m3u file with blank line

### ISSUE THREAD

**Issue by JoaoPinheiro** [OpenEmu/OpenEmu#3159]
I was having a persistent crash while trying to import a .m3u file for a 3-disc Playstation game until I noticed that the file a blank line. Removing this blank line fixed the problem. I've repeated the process multiple times and the behaviour was consistent.

The crash was on OpenEmu 2.0.5 (719-g369c3a2-Release) on macOS 10.12.1 (16B2555).

I'm attaching a zip file containing the crash log, along with 2 versions of the .m3u file; one which causes a crash and one which doesn't.
[M3U Crash.zip](https://github.com/OpenEmu/OpenEmu/files/949952/M3U.Crash.zip)

**Comment by clobber** [comment]
Have to use the search.

#3153
