### ISSUE TITLE
Client storage slows down some GPUs badly

### ISSUE THREAD

**Issue by clobber** [OpenEmu/OpenEmu#316]
NPOT and client storage GL extensions appear to be causing slowdowns on GPUs such as the 8600GT and the 9800GT (non-apple hardware). These GPU's get high usage of glTexSubImage2D, around 98%.

To test, we forced `isIntel = YES` on line 189 in OpenEmuHelperApp.m and profiled the helper in OpenGL Profiler - comparing mainline build with altered.

Results of the 9600M GT (late 2008 MBP with 9400M/9600M GT) before:
![before](http://i.imgur.com/on3Xg.png)

Results of the 9600M GT after:
![before](http://i.imgur.com/7yo8d.png)

------

Results of the 9800GT (non-apple hardware) before:
![before](http://i.imgur.com/R5wJZ.png)

Results of the 9800GT (non-apple hardware) after:
![after](http://i.imgur.com/XyJcY.png)

------

For a comparison, here is 9400M running on unaltered mainline build:
 ![9400M](http://f.cl.ly/items/2L1V1P042D2o1X162H0S/Screen%20Shot%202012-11-01%20at%2011.50.43%20PM.png)

**Comment by cyco** [comment]
boooring

**Comment by clobber** [comment]
Notes from @mrvacbob regarding our slow client storage issue:
* "the GPU is a lot slower reading back from our own memory during the drawing, 'cause it doesn't want to store images linearly the way we do"
* "we only wanted client storage to avoid a memcpy from our memory into the driver memory, but the memcpy onto the gpu + tile is fine"
* "client storage means "don't store it in VRAM at all", but if you fail the secret requirements it just doesn't try to do it, and doesn't tell you, so really hard to tell what's going on"
* try https://www.opengl.org/wiki/Pixel_Buffer_Object

**Comment by mrvacbob** [comment]
Further note: https://www.opengl.org/registry/specs/APPLE/client_storage.txt basically says it will still copy texture data when we update it, which we do every frame.
