### ISSUE TITLE
Problem emulating Sega CD when 32x is also required

### ISSUE THREAD

**Issue by aratuk** [OpenEmu/OpenEmu#3164]
I'm having an issue trying to run a Sega CD game, "Night Trap," that also uses the Sega 32X attachment for the Mega Drive / Genesis.

I see that OpenEmu uses different cores for Sega CD and 32X emulation. So, I suppose this problem may not be easily solved if the SegaCD core doesn't do 32X emulation, or vice-versa. According to Wikipedia, there are [only six games](https://en.wikipedia.org/wiki/List_of_Sega_32X_games) that require both the Sega CD and the 32X. But, if anyone knows a good solution to this, please let me know.

It looks like there is a Sega-CD-only version of "Night Trap," but it's lower quality than the CD/32X version.

![32x](https://cloud.githubusercontent.com/assets/3944007/25461745/91f7a35c-2a9f-11e7-80ca-655f73b99891.png)

**Comment by clobber** [comment]
#1986
