### ISSUE TITLE
I cannot play multi-disc games

### ISSUE THREAD

**Issue by MrMephilestheDark** [OpenEmu/OpenEmu#3165]
Hello, I'm sure I'm missing something right in front my eyes, but no matter how many times I try I cannot play any multi disc games.   In 2016 I put disk one of FFVll in openemu and it worked perfectly.  Come 2017, a pop up on my computer says that I need the other disks.  I've read the guide, watched tutorials, but I still can't get it to work.  I've pasted all three .cue files of the three disks into TextMate (and yes I changed their names from .bin to .cue), saved it as Final Fantasy Vll.m3u and Final Fantasy Vll (USA).m3u but I still can't get it to work!
Any help you could supply would be greatly appreciated.

**Comment by clobber** [comment]
Possible issues:
* You don't actually have the m3u set up correctly (follow the guide closely).
* Your games are still imported in the library. The guide says they need to be removed and deleted first, so make sure they aren't still in ~/Library/Application Support/OpenEmu/Game Library/roms
* Your cue sheets are wrong and not referencing the bin files correctly.
* You have a bad rip of the game and will need to find another copy.

Can't offer any more help beyond what is in the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game)
