### ISSUE TITLE
Assigning specific controllers to specific systems?

### ISSUE THREAD

**Issue by ferropop** [OpenEmu/OpenEmu#3166]
Hi! I have the following:

1xN64 (8bitdo) Controller
2xSNES (8bitdo) Controller
1xPS3 (original) Controller

Is there any way to map the specific controllers to their respective systems?  I want the SNES core to only use the SNES controllers and never even attempt to use the N64 or PS3 controllers, etc.  Right now the controller trump each other depending on what you've set up as Player 1, 2 etc.

Or am I missing something?  Thanks!

**Comment by clobber** [comment]
You can change which player each controller belongs to in each system, but you cannot only have a controller appear for a certain system. The workaround is to not have all three types of those controllers paired/connected at once.
