### ISSUE TITLE
Help with the save file lost!

### ISSUE THREAD

**Issue by laoertongzhi** [OpenEmu/OpenEmu#3167]
Today I just opened OpenEmu. However, there was an introduction start and it told some basic operation of OpenEmu. I forgot if it would be shown when user opened it for the first time. After that the main interface showed and it said that OpenEmu is scanning my games in the library. However no games were successfully scanned. I went to the directory to check and all my game files and save files were lost. I did nothing before this issue happened and I just normally played games. Why it would suddenly happened and why could my files in library lost? Can I find them back? Please help me! It almost makes me cry. :( :(

**Comment by clobber** [comment]
>I did nothing before this issue happened and I just normally played games.

The issues you are describing are nonsensical. The setup assistant won't just startup on its own, so you had to have done *something*. It also doesn't just start "scanning" for games all by itself, nor would that make games and save files disappear. It sounds like you deleted your org.openemu.OpenEmu preferences in user defaults - that's the *ONLY* way at least some of this behavior could happen, such as the setup assistant reappearing.

As far as finding your files, if they do not exist in `~/Library/Application Support/OpenEmu` (~ meaning your Home folder where ~ is your username. [Guide here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) if you don't know this), then I don't know what to tell you. Sorry, that's all the help we can offer for this.

Next time, don't do whatever you did to break your Library.
