### ISSUE TITLE
Select or use an existing game library?

### ISSUE THREAD

**Issue by alancwoo** [OpenEmu/OpenEmu#3168]
When trying to select an existing Game Library, I am shown the message:

> “Game Library” couldn’t be moved to “Apps” because an item with the same name already exists.
> To save the file, either provide a different name, or move aside or delete the existing file, and try again.

I've managed to work around this by temporarily by:

1. renaming my existing Game Library
2. setting the folder to an appropriate location
3. quit OpenEmu
4. remove the new Game Library
5. rename old Game Library
6. reopen OpenEmu

This seems a bit tedious, and while not a common occurrence, I was wondering if there is a reason you can't just select a Game Library that exists? (And in my case, one I am syncing over Dropbox)

I am using OpenEmu v2.0.5 `719-g369c3a2-Release` on OS X Sierra `10.12.3`

**Comment by clobber** [comment]
There are no plans for an "Import/Export Game Library" functionality. Most users that want some sort of "Dropbox" like compatibility use symbolic links.
