### ISSUE TITLE
MAME Feature requests for OpenEmu

### ISSUE THREAD

**Issue by retrogaminggod** [OpenEmu/OpenEmu#3169]
MAME Feature requests for OpenEmu

These are the 4 most important features needed for a next major release -

- Be able to list and group games by year and manufacturer in grid view
- Play trackball, paddle/spinner, steering wheel, light gun and mouse games using joystick
- Play multiple screen games
- List the hardware specs of each machine when running a ROM

**Comment by clobber** [comment]
Most of these have already been requested before, so please use the search. You also requested one yourself, so please stop opening an issue for MAME-related stuff.

Arcade/MAME is 'experimental' and unsupported right now.
