### ISSUE TITLE
Crashes every time I try to launch a game

### ISSUE THREAD

**Issue by Poetastrophe** [OpenEmu/OpenEmu#3171]
Every time I install the OpenEmu, add a game and then relaunch Openemu, then I will not be able to play that game because OpenEmu crashes. Even though the game can be played just fine before relaunching OpenEmu. The method described here:https://github.com/OpenEmu/OpenEmu/issues/2226 
Does not work.
The crash report is at:https://gist.github.com/Poetastrophe/f1f989b62e48607370088d0745cf36d7

**Comment by clobber** [comment]
Follow the instructions completely: https://github.com/OpenEmu/OpenEmu/issues/2226#issuecomment-167277759

That can be the only way to solve it. If you haven't done all of that, then I don't know what to tell you.
