### ISSUE TITLE
Won't Compile on Latest Xcode with latest macOS

### ISSUE THREAD

**Issue by CyberManifest** [OpenEmu/OpenEmu#3172]
Following this guide: https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide
I can't get this to compile in Xcode (latest version: Version 8.3.2 (8E2002)) with the latest version of macOS (macOS Sierra Version: 10.12.4 (16E195)) on a MacBook Pro Early 2015 edition. I get the following build error, even after a clean. Either the code needs to be corrected/cleaned up/fixed or the guide needs to be updated or temporarily removed to clear up confusion.

`** BUILD FAILED **

The following build commands failed:
	CompileC /Users/ryan/Library/Developer/Xcode/DerivedData/OpenEmu-dogsmafmwcivutdgennkhrpphwik/Build/Intermediates/Higan.build/Release/Higan\ (Performance).build/Objects-normal/x86_64/HiganGameCore.o HiganGameCore.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Ryans-MacBook-Pro:OpenEmu ryan$ `

**Comment by clobber** [comment]
Please don't needlessly open duplicate issues. You already opened #3073

The guide was updated some time ago, which shows the proper way to build the application without having to build all of the core plugins.
