### ISSUE TITLE
Q.) Why does RetroArch have certain working cores for multi platforms and yet OpenEmu doesn't?

### ISSUE THREAD

**Issue by CyberManifest** [OpenEmu/OpenEmu#3173]
Why does RetroArch have certain working cores for multi platforms and yet OpenEmu doesn't? It may be worth looking into. RetroArch on the Mac Platform seems to have working core plugins that OpenEmu on the Mac seems to lack. See: http://buildbot.libretro.com/stable/1.5.0/apple/osx/x86_64/
Is it not possible to take/borrow or use the work already done/accomplished by RetroArch to be implemented into OpenEmu easily? Can the two projects not collaborate with one another to accomplish the best of both worlds?

**Comment by clobber** [comment]
We only support 10.11 and up. We also only ship core plugins that are stable, have reasonably high compatibility and fit well within our "just works, near zero setup required" model.
