### ISSUE TITLE
Crashes trying to start a game, and sometimes navigate the UI

### ISSUE THREAD

**Issue by linuxpng** [OpenEmu/OpenEmu#3174]
I just installed 2.0.5 after a reload of macos 10.12.4 and I get crashes trying to start nes or snes games (I have not tried others) and periodically navigating the preferences.  I have not been successful in starting any game.
[openemu_crash_logs.zip](https://github.com/OpenEmu/OpenEmu/files/970472/openemu_crash_logs.zip)

**Comment by linuxpng** [comment]
Grabbed the 2.0.4 release and works no problem.

**Comment by clobber** [comment]
Gotta use the search.

https://github.com/OpenEmu/OpenEmu/issues/3116#issuecomment-290622500
