### ISSUE TITLE
Screen Tearing With Nintendo DS

### ISSUE THREAD

**Issue by SpreadTheJello** [OpenEmu/OpenEmu#3177]
First of all thank you for making OpenEmu!

I started playing Pokemon Diamond for the Nintendo DS and I noticed I have a lot of screen tearing constantly. I tried changing the screen effect, which changed nothing. I have also tried to redownload the game, which also changed nothing. I tried to install all cores, changed nothing. If you could help me on this that would be much appreciated as I want to record this game very much so.

Specs: MacBook Pro (15-inch, Mid 2010)
Processor: 2.53 GHz Intel Core i5
Memory: 8 GB 1067 MHz DDR3
Graphics: NVIDIA GeForce GT 330M 256 MB
                 Intel HD Graphics 288 MB
Display: 15.4-inch (1440 x 900)

**Comment by clobber** [comment]
Which version of OpenEmu?

**Comment by SpreadTheJello** [comment]
Version is 2.0.5

**Comment by clobber** [comment]
Are you using the Nearest Neighbor or Pixellate filters? I don't see any tearing, so you might want to record what you are seeing so we can check it out. There could be an issue with that specific GPU.

**Comment by SpreadTheJello** [comment]
Yes I am using Nearest Neighbor. https://www.youtube.com/watch?v=zPgIQQJE21c

**Comment by clobber** [comment]
That's going to be a Desmume bug or particular problem with the game (was it like that on real hardware?). Not anything related to OpenEmu there.
