### ISSUE TITLE
How to install older core, or downgrade a core

### ISSUE THREAD

**Issue by hvalcourtSerdy** [OpenEmu/OpenEmu#3178]
Hi,

I reinstall my old imac to give to a kid. It's on 10.8 lion because I cannot upgrade osx after this version on this mac.

I installed OpenEmu 1.0.4, the last compatible version with 10.8. 

It's working, but only for NES core. I think the other core are to new, it's not working.

How can I downgrade a core, or manually install a older / version of a core? I would like to add snes, atari 2600 and sega master system on 1.0.4.

I know it s old, I will understand if you cannot help me.

thanks,

Hugo

**Comment by clobber** [comment]
Sorry, issues regarding OpenEmu 1.x is unsupported. You would have to manually install everything by downloading from individual core plugin repos.

**Comment by hvalcourtSerdy** [comment]
Do you have a list of last supported core for 1.0.4? It could be useful to put this somewhere. A lot of people recycle old computer for retro gaming.

Or It can be cool to made a 1.0.5 with the good core, without update of core, for older computer. Recycling and happy children!!!

Thanks for the reply, I will try older core from repo.

You made a good job with openEmu. I install it on all my computer.

Hugo
