### ISSUE TITLE
Controls don't work at all

### ISSUE THREAD

**Issue by Big-Scheming** [OpenEmu/OpenEmu#3179]
Hi, please forgive me as I am new here and relatively inexperienced.  I downloaded a couple of files from [removed] today and dragged them into the add window of OpenEmu.  They might have been "ROM" or "ISO" or something else.  Two of them didn't show up in "Recently Added," despite having the same file extension as the other three, which worked.  I booted up all three of them without issue, however when I went to press start and begin the game, the game did not respond.  I checked the control customization interface and everything was in order, but the game would not recognize that I was pressing start.  Please explain to me what I'm doing wrong here.  Thank you.
![guy-manuel](https://cloud.githubusercontent.com/assets/28472656/25769929/bcadc926-31f4-11e7-929d-f7595228e188.jpg)

**Comment by clobber** [comment]
Please search before opening a new issue...this comes up a lot.

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
