### ISSUE TITLE
Issue with "Start" & "Select" Buttons on Mac OS X playing NDS games.

### ISSUE THREAD

**Issue by Valoryze** [OpenEmu/OpenEmu#3180]
I have been playing Pokemon and realized that no matter how I map the keyboard or restart my game, the "start" and "select" buttons do not work. Any way of solving this?

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
