### ISSUE TITLE
Playstation one games

### ISSUE THREAD

**Issue by totneschap** [OpenEmu/OpenEmu#3181]
I have Open Emu on my work and home macs and today I downloaded some ps titles (final fantasy 8&9 among others). I created my m3u file and they all uploaded to the software fine and played first time. I put the same game files on to a memory stick and brought it home so I could transfer them to my home mac knowing that they work fine. I transferred the files from the memory stick to my hard drive and openemu scans the files but then no game shows! what am i doing wrong?

**Comment by clobber** [comment]
By trying to import a save file through the UI, you are looking for functionality that doesn't exist. No supported method is available for transferring save files, but you should be able to figure out the gist of it from a section of a guide here: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing#transfer-your-save-data

**Comment by totneschap** [comment]
Hi, sorry there seems to be a misunderstanding, I was talking about about transferring save files but uploading games themselves but I think i know what my problem is. At home I was having trouble with multi disc games but I think that's because I was uploading all the bin files and the m3u at the same time. I just uploaded final fantasy 9 at work by just loading the m3u file! And as your multi disc user guide states, that's all you need to do. Thanks for the reply

**Comment by totneschap** [comment]
I've taken my chrono cross files(bin and cue files) from work and they worked fine on my mac at work but they won't even load on my home mac???
