### ISSUE TITLE
Start and Select Buttons Not Working for Nintendo DS ROMs

### ISSUE THREAD

**Issue by Fuckboysupreme** [OpenEmu/OpenEmu#3183]
Start and Select buttons not working in V 2.0.5. Playing Pokemon Diamond and I've tried remapping the buttons to other keys but still no response. Any solutions?

**Comment by clobber** [comment]
#3180

**Comment by Fuckboysupreme** [comment]
Thank you for the response, is there anyway to transfer save data from openemu to desmume?
