### ISSUE TITLE
Transferring Save Data From OpenEmu to Desmume

### ISSUE THREAD

**Issue by Fuckboysupreme** [OpenEmu/OpenEmu#3184]
Seeing as the select and start buttons are not functional in this version, is there any way to transfer save data from OpenEmu to Desmume?

**Comment by clobber** [comment]
Those buttons are functional here.

As far as transferring your save files, that is not officially supported (this bug tracker is for OpenEmu issues). You would have to poke around in ~/Library/Application Support/OpenEmu for those. That's all the help we can offer for this.

**Comment by clobber** [comment]
#3183
