### ISSUE TITLE
Joycon not working properly 

### ISSUE THREAD

**Issue by shadda** [OpenEmu/OpenEmu#3188]
OpenEmu 2.0.5
Can't get various buttons to map correctly using the JoyCon. When I try to map the directional keys to the joycon (left or right) analog stick, it autofills the mappings for each direction, but in-game the controls do not reflect these mappings (eg, up on the stick = right in game, left = down, up = right)
Further, when I attempt to map each direction individually, I cannot get the down direction to be recognized no matter what. It sits there waiting for a key event but I press down and nothing happens.

**Comment by clobber** [comment]
Sounds like #3093

These are unsupported.

**Comment by shadda** [comment]
Negative, I'm not attempting to use two joycons as one input.

**Comment by clobber** [comment]
Okay, well whatever is going on there doesn't sound like an OpenEmu problem. The device itself probably isn't fully HID compliant, and I don't know if there are certain "modes" they need to be set in to act as sideways or regular. You may also want to check if you have third party software installed causing a conflict: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
