### ISSUE TITLE
Using Wiimote as a gun for NES, SNES, MAME games etc...

### ISSUE THREAD

**Issue by sohojohn84** [OpenEmu/OpenEmu#3189]
Hello, 

I purchased a wiimote and sensor bar. They all work seamlessly for Dolphin, and the wiimote works like a charm on OpenEmu when I play NES games.

I wanted to see there is any chance to pair the wiimote and use is as a Lightgun for NES, SNES, MAME games (or whatever console as a matter of fact...)

Thanks!

**Comment by clobber** [comment]
Nope, that is unsupported. No plans of supporting the sensor bar - not worth the effort.
