### ISSUE TITLE
PSP core language selection

### ISSUE THREAD

**Issue by castledayz** [OpenEmu/OpenEmu#3190]
In Kingdom hearts birth by sleep (playing on Openemu) the language in which you play the game is preselected with no changing option inside the game.
How can I change the PSP core's default language?

**Comment by clobber** [comment]
Dupe: https://github.com/OpenEmu/PPSSPP-Core/issues/5

**Comment by Reygans** [comment]
Same problem somebody can help me, explaining how can I switch the language in italian please ?
