### ISSUE TITLE
Slow performance when playing PlayStation games

### ISSUE THREAD

**Issue by hijackHarry** [OpenEmu/OpenEmu#3192]
Hey guys I am setting up openemu.  Everything is incredible and works well. The only issue is PlayStation 1 games run super slow and the sound stutters.  I know it works because I set it up for my friend where it runs fine.  Could it be a processor or gfx card issue?

**Comment by clobber** [comment]
Mednafen's PS1 emulation is very CPU intensive and will take a fairly fast machine to run games at full speed. Nothing can be done about this. At the very least, try running games windowed and using the 'nearest neighbor' filter.

**Comment by hijackHarry** [comment]
Not sure why you closed this.  I still have questions...  anyone know what the specs to run this properly is?

**Comment by clobber** [comment]
Closed because this is not an OpenEmu issue. Also please do not open additional issues.
