### ISSUE TITLE
PlayStation emu minimum reqs

### ISSUE THREAD

**Issue by hijackHarry** [OpenEmu/OpenEmu#3193]
Anyone have an idea of what minimum specs are for running the PlayStation emulator in openemu?  I have a 2011 Mac mini, 2tb hd, 16gb ram, 2.3ghz i5.

**Comment by clobber** [comment]
You're not having an OpenEmu issue, so you should really google around for this kind of information first. Our issues pages is strictly for bug reporting.

Anyway, according to Mednafen documentation:
>A dual-core Phenom II or Athlon II at 3GHz or higher, or rough equivalent(in terms of single-core IPC), is recommended for running Mednafen's PlayStation 1 emulation on(note that this recommendation does not apply to any unofficial ports or forks, which may have higher CPU requirements). For better performance, the binary should be compiled for a 64-bit target(for example, x86_64) rather than 32-bit, if available.

**Comment by clobber** [comment]
#3192
