### ISSUE TITLE
Saturn Shining Force 3 Scenario 2 - Carrying on using Scenario 1 Save data

### ISSUE THREAD

**Issue by AlvSovereign** [OpenEmu/OpenEmu#3194]
Hi all
I have completed SF3 - SC1 and want to use the save data from that in SC2 to carry on with the progress I have made.

From what I can tell in the Mednafen core, in the battery saves folder, the saves are prefixed by the game and what seems to be a unique identifier.

So naturally, when I boot up SC2, Mednafen loads the saves for that individual game (SC2 in this case) and not (SC1).

I am aware that Saturn emulation in OpenEmu is experimental so I'm not expecting any results, but is there a way of loading SC1 save in Sc2?

Thanks for your time and help.

Alvin

**Comment by clobber** [comment]
Boot the second game so that it writes its initial save file, then close it. Then, rename your old save file to match the new one generated by the second game.

**Comment by AlvSovereign** [comment]
Thank you
