### ISSUE TITLE
Controller Mapping Dysfunction

### ISSUE THREAD

**Issue by ylluminate** [OpenEmu/OpenEmu#3195]
Wanted to just make a note here. I found that keyboard and other controller mapping was not able to be changed. Verified I had the most recent version of the program and upgraded (as it was a few versions behind). After upgrading controller mappings would still not change.

I removed `~/Library/Preferences/*openemu*` and restarted OpenEMU and found that the app would then allow me to make changes to the mappings properly.  I figure there must be something wrong somewhere from an upgrade due to an issue in the previous version, but wanted to document it here in case anyone has a similar issue.

**Comment by clobber** [comment]
None of that sound related. Input issues are usually due to issues noted here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
