### ISSUE TITLE
issues with loading .m3u file for multi-disc games

### ISSUE THREAD

**Issue by igozali** [OpenEmu/OpenEmu#3197]
I'm sorry for potentially being the 100,000th person to report an issue regarding multi-disc imports, but I'm (again) having issues importing an .m3u file for Chrono Cross.

Software Versions: 
* macOS 10.12.4
* OpenEmu v2.0.5 (719-g369c3a2-Release)

My setup:
```
sh-3.2# pwd
/Volumes/HD2/games/psx/Chrono_Cross_USA
sh-3.2# # Renamed the Chrono Cross files to use underscore since I thought spaces were causing the path not found issue.
sh-3.2# ls -l
total 1443812
-rw-r--r-- 1 user staff        56 May 21 18:36 Chrono_Cross_USA.m3u
-rw-r--r-- 1 user staff 736651104 May 21 17:21 Chrono_Cross_USA_Disc_1.bin
-rw-r--r-- 1 user staff        89 May 21 17:52 Chrono_Cross_USA_Disc_1.cue
-rw-r--r-- 1 user staff 741797280 May 21 17:23 Chrono_Cross_USA_Disc_2.bin
-rw-r--r-- 1 user staff        89 May 21 17:52 Chrono_Cross_USA_Disc_2.cue
sh-3.2# tail -n +1 Chrono*.{cue,m3u}
==> Chrono_Cross_USA_Disc_1.cue <==
FILE "Chrono_Cross_USA_Disc_1.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

==> Chrono_Cross_USA_Disc_2.cue <==
FILE "Chrono_Cross_USA_Disc_2.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

==> Chrono_Cross_USA.m3u <==
Chrono_Cross_USA_Disk_1.cue
Chrono_Cross_USA_Disk_2.cue
sh-3.2# $ tree ~/Library/Application\ Support/OpenEmu/Game\ Library/
/Users/user/Library/Application\ Support/OpenEmu/Game\ Library/
├── Artwork
├── Library.storedata
├── Library.storedata-shm
├── Library.storedata-wal
└── roms
    ├── Automatically\ Import
    ├── Sony\ PlayStation
    └── unsorted
sh-3.2# # Got nothing on my Game Library directory.
```

When I try to import the .m3u file (by drag-and-drop), I get the following error message from console, even when I'm very sure that Chrono_Cross_USA_Disk_1.cue exists in the directory shown in the error message. 
```
Error Domain=org.openemu.OECDSheet.ErrorDomain Code=-1 "Missing referenced file" UserInfo={NSUnderlyingError=0x608000a4b250 {Error Domain=NSCocoaErrorDomain Code=260 "The file “Chrono_Cross_USA_Disk_1.cue” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Volumes/HD2/games/psx/Chrono_Cross_USA/Chrono_Cross_USA_Disk_1.cue, NSFilePath=/Volumes/HD2/games/psx/Chrono_Cross_USA/Chrono_Cross_USA_Disk_1.cue, NSUnderlyingError=0x608000c53ec0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}, NSLocalizedDescription=Missing referenced file, NSLocalizedFailureReason=Could not read file at path /Volumes/HD2/games/psx/Chrono_Cross_USA/Chrono_Cross_USA_Disk_1.cue. Make sure the file is at the indicated location and can be read.}
```

Unfortunately I'm not very familiar with Objective-C and Cocoa development on macOS, so I'm not sure what could cause this issue. You might notice that I have renamed the files to use underscores instead of spaces since I thought spaces were causing OpenEmu to not find the files.

Would appreciate any pointers! Also, it might be helpful to surface error messages in the GUI during import errors?

**Comment by clobber** [comment]
The error message is self-explanatory.

You have an M3U playlist file referencing files that don't exist. It cannot import files named Chrono_Cross_USA_Disk_1.cue if your actual files are named Chrono_Cross_USA_Disc_1.cue

**Comment by igozali** [comment]
Wow, can't believe I missed that. 

Thanks for your help, and also thanks a lot for maintaining the project!

**Comment by firath** [comment]
Hello. 

I'm trying to figure this thing out, but i stil can't make my Chrono Cross game works with Open Emu, even after following thoroughly the guide. 
Here a screen :
<img width="959" alt="capture d ecran 2018-08-24 a 02 27 43" src="https://user-images.githubusercontent.com/42660548/44558635-9473d000-a745-11e8-9434-fa980d1a1c48.png">
When i drop the M3U file on Open Emu, nothing happened... OpenEmu tried to load it and then nothing. I did saved the file as a Plain Text, names are matching so..... can't figure it out :( can you help me please?

Btw : 
OpenEmu : v2.0.6.1
iOS : macOS High Sierra, version 10.13.6

Thank you...
