### ISSUE TITLE
trouble with emulating pc engine-CD

### ISSUE THREAD

**Issue by greengamerUSSR** [OpenEmu/OpenEmu#3198]
it's probably a stupid question that already has been answered elsewhere, but i don't know how to install the syscard3.pce BIOS for openemu.

**Comment by clobber** [comment]
Like an other BIOS or system file, you find the correct one as per the [BIOS guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files) and then you drag and drop the file into your library which will then automatically import it.

**Comment by greengamerUSSR** [comment]
yes, but were do i find said files?

**Comment by clobber** [comment]
Ever heard of a search engine? Please don't open issues like this in our bug tracker.
