### ISSUE TITLE
Arcade Emulator: Anyway to save and keep highscores of games without the save states?

### ISSUE THREAD

**Issue by PalmerB** [OpenEmu/OpenEmu#3199]
Trying to build an arcade machine and I would like it so that when you boot up a game it automatically goes into the startup of the game but maintains any highscores or such of that game.

With the saved states it goes directly to where the previous saved version was regardless of if they were in the middle of a game. I know I'm asking for a lot but just wanted to see if I could find a way around this. I read the guide on the sidebar about saved states but am still looking for a way around them if there even is a way.

Thanks for any help!

**Comment by clobber** [comment]
Arcade/MAME is 'experimental' and not a focus, so it's unsupported at this time. Instead, you may want to use the standalone version of MAME. We recommend that.

**Comment by PalmerB** [comment]
Sorry to open it back up.  By using a standalone version of MAME do you mean use one outside of OpenEmu or does OpenEmu offer a MAME only version?  I tried checking their website but do not see a MAME only version.  

Thanks for the help!

**Comment by clobber** [comment]
Standalone version of MAME means an official version of MAME and not OpenEmu.
