### ISSUE TITLE
Unknown DS games are displayed as "Mazes of Fate DS"

### ISSUE THREAD

**Issue by SamusAranX** [OpenEmu/OpenEmu#3200]
I just imported a bunch of demo ROMs (like E3 demo ROMs) and as you can see in the screenshots, something went wrong fetching the metadata. I don't know how this part of OpenEmu works, like whether it depends on embedded IDs or not, but this is definitely not correct.

![OpenEmu's grid view, showing 13 selected copies of "Mazes of Fate DS"](https://cloud.githubusercontent.com/assets/676069/26470582/88795d6e-419e-11e7-82fc-8d893b748060.png)
![A list of 13 selected files in Finder, none of which are "Mazes of Fate DS"](https://cloud.githubusercontent.com/assets/676069/26470586/8a9d9060-419e-11e7-8807-a0810c52ef1e.png)

**Comment by clobber** [comment]
These demos probably all share the same internal ID's, so the importer/database cannot tell them apart. Not really an OpenEmu issue, though, but something to figure out for OpenVGDB.

Anyway, the workaround, if you really want to have these demos imported with their filenames intact, is to turn off "Automatically lookup game information & artwork" in Library preferences and then reimport the files. Afterward, turn that setting back on.
