### ISSUE TITLE
SG-1000 hardware pause not mapped.

### ISSUE THREAD

**Issue by null1024** [OpenEmu/OpenEmu#3203]
Unlike on the SMS, the SG-1000's console pause button isn't mappable.

**Comment by clobber** [comment]
Do any games use this for accessing an in-game menu like the Master System? Otherwise, I'd say hit Command+P or map a key to the "Pause" special key in Preferences > Controls.

**Comment by clobber** [comment]
Added in https://github.com/OpenEmu/OpenEmu/commit/7af924a7c131c9c32dfcf1408855b5d4fcaaeae5
