### ISSUE TITLE
won't open DS emulator

### ISSUE THREAD

**Issue by Shaun1998** [OpenEmu/OpenEmu#3204]
overtime I try to open any DS emulator it comes up with this
![screen shot 2017-05-29 at 9 00 01 pm](https://cloud.githubusercontent.com/assets/22471247/26548278/856ccfea-44b2-11e7-8df0-49d060516cfc.png)

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.
