### ISSUE TITLE
my wiimote wont connect

### ISSUE THREAD

**Issue by DJDAN20xx** [OpenEmu/OpenEmu#3209]

**Comment by clobber** [comment]
When using a Wii input device, always follow [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) and [wii remote pairing](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing) guides to see if anything applies.
