### ISSUE TITLE
My wiimote is having trouble connecting

### ISSUE THREAD

**Issue by pj4242** [OpenEmu/OpenEmu#3210]
I started using OpenEmu around march, and I very much enjoyed using my wii classic controller alongside it. I used to have no problems connecting my wiimote to my computer. However, one day I downloaded dolphin emulator, alongside wjoy. After realizing that this was interfering with my ability to use my wii classic controller on openemu, I uninstalled both wjoy and dolphin, just to be safe. however, my classic controller still doesn't work! I have looked at the list of downloads and applications that cause problems at https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems, and I didn't have any installed (besides google chrome, which I closed down when using openemu, and it still didn't connect), yet I still can't connect my controller. I do have an xbox 360 controller installation called 360controllerinstall, could that possibly be interfering with the connection?

**Comment by pj4242** [comment]
also, I could connect my wiimote before with chrome open, is that normal?

**Comment by clobber** [comment]
When using a Wii input device, always follow [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) and [wii remote pairing](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing) guides to see if anything applies.

Can't help you beyond that.
