### ISSUE TITLE
Game not recognizing a memory card.

### ISSUE THREAD

**Issue by brandontluong** [OpenEmu/OpenEmu#3211]
I'm trying figure out how to get Suikoden II to read the "memory card" on my Mac so that I can get all the benefits/work from the first one. I have the latest version of OpenEmu and I believe I set up my bios and cue correctly. When I check my saved games for Suikoden in my Mac's library, they work fine when I click on it. I tried moving the file to Suikoden II to see if t could read from there, and that didn't work. I was thinking of moving the data to PSX or something similar to see if that works, but would rather keep it all on OpenEmu. Any suggestions?

**Comment by clobber** [comment]
Boot the second game so that it writes its initial save file, then close it. Then, rename your old save file to match the new one generated by the second game.
