### ISSUE TITLE
Loading Playstation multidisk (FFVII) rom onto OpenEmu v2.0.5

### ISSUE THREAD

**Issue by nadong89** [OpenEmu/OpenEmu#3212]
Hello, 

I have the the MacBook Pro, 2016 (version 10.12.5) 

I have been attempting to import the FFVII multi disk rom into open emu and have been having some trouble when inputting the m3u file. I followed the multi-disk import [guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) exactly (at least I think I did): 

Folder with cue, bin, and m3u file:
<img width="767" alt="screen shot 2017-06-06 at 6 37 34 pm" src="https://user-images.githubusercontent.com/29242054/26858619-3d7d799c-4ae7-11e7-972b-a42bb759c779.png">

Library folder with no FFVII in there: 
<img width="908" alt="screen shot 2017-06-06 at 6 38 37 pm" src="https://user-images.githubusercontent.com/29242054/26858653-604ee6d6-4ae7-11e7-8db8-bce09641994c.png">

m3u file:
<img width="768" alt="screen shot 2017-06-06 at 6 39 42 pm" src="https://user-images.githubusercontent.com/29242054/26858706-b83c2bec-4ae7-11e7-8ee8-7134f1eb769e.png">

I imported the m3u file by dragging it into the openemu library. 

Could you help me out?

**Comment by clobber** [comment]
Possible issues:
* You have files lingering in the 'unsorted' folder that got stuck there during a bad import.
* You didn't remove the games from your Library inside the app and only deleted them manually from the folder.
* There is a problem inside the cue sheet files (dunno, you didn't show the inside of them).

**Comment by LordSarius** [comment]
I'm having a similar problem. I'm also trying to import FFVII, and am using OpenEmu version 2.0.3. I did everything as I was told to, but when I try to run the game I get the following error - 
![screen shot 2017-06-07 at 2 04 17 pm](https://user-images.githubusercontent.com/29263419/26901428-b320bc74-4b8a-11e7-866b-596ee65118e5.png)

The "Learn More" button has told me jack-all about what to do. I roughly understand I'm missing files, but understand nothing else. Help would be greatly appreciated.

**Comment by clobber** [comment]
@LordSarius No, you are not having a "similar" problem. You just don't want to follow directions and copy in the required files, which you must google search for.

**Comment by clobber** [comment]
#3163
