### ISSUE TITLE
Some files unintendedly end up in Arcade library

### ISSUE THREAD

**Issue by Pixel0501** [OpenEmu/OpenEmu#3214]
I am using the experimental version of OpenEmu, and sometimes, when I drag a ROM into OpenEmu, it goes straight into Arcade. Anyway to move the roms around manually, because it seems the only way to sort your ROMs into the right console is to do it automatically. I really love this program, and I don't want to stop using it. I should mention I didn't have this problem before, but when I tried to change the location of the OpenEmu library, the problem started and is not going away. Please help right away!

**Comment by clobber** [comment]
>sometimes, when I drag a ROM into OpenEmu, it goes straight into Arcade

Zips that are not automatically detected are assumed to be Arcade games. Sometimes there can be extraneous files inside the zip that will confuse the importer: Garbage In, Garbage Out. The workaround is to unzip your file and import the ROM itself.

**Comment by Pixel0501** [comment]
Thank you 😊

**Comment by Pixel0501** [comment]
Sorry, I just didn't know how to reopen it.

**Comment by Pixel0501** [comment]
I admit I was being rude before, sorry about that.

**Comment by clobber** [comment]
Provide me with **exact** details:

I want the filename you are trying to import and then I want you to unzip the file and provide the names of the file(s) inside the zip file. Copy and paste all of that information back here.
