### ISSUE TITLE
Problem with consoles?

### ISSUE THREAD

**Issue by Pixel0501** [OpenEmu/OpenEmu#3220]
So let's say I drag the Sega Genesis version of RoadBlasters into the Sega Genesis page, and for some reason, it always goes to Arcade. Is there anyway to sort ROMS manually into consoles? Thank you for reading my question.

**Comment by Pixel0501** [comment]
If that doesn't work, is there a way to convert roms into console files like .nes?

**Comment by clobber** [comment]
I can't help you until you start reading what I've told you.

Do not open another duplicate issue regarding your problem. Post in the ORIGINAL you opened. #3214
