### ISSUE TITLE
Adding a new emulator

### ISSUE THREAD

**Issue by stigvp79** [OpenEmu/OpenEmu#3221]
Hello,

This weekend I wrote an emulator for the [CHIP-8](https://en.wikipedia.org/wiki/CHIP-8) system. It is written in C++ and is working as a standalone console application (I tested it with its port of Pong), and now I would like to integrate it with OpenEmu. However, it is not clear to me how to proceed and I would welcome any guidance you may have.

As far as I can see, I need to add a system under System Plugins. I tried this, including a SystemController class. But how does my new system get registered so it appears in OpenEmu's list of consoles? Is it a matter of adding a MacOS custom bundle and setting all the appropriate key-value pairs in a plist?

Once I get the System Plugin to register and configure it, then it appears I need to add a Core Plugin with the actual source code of my emulator. Is that the right sort of idea? 

Many thanks,
Stig

**Comment by clobber** [comment]
Neat. Well this isn't a system we are probably going to support and I cannot walk you through the entire process of setting up a System + Core Plugin, but the best way to figure it out is to open up the Xcode workspace file and look at a current one and how it interfaces with one of the core plugins. You will have to be mindful of the entire build process, in that the system plugin has to also get copied in the OpenEmu app bundle.
