### ISSUE TITLE
SNES Input/Controller Problems

### ISSUE THREAD

**Issue by gethubguy** [OpenEmu/OpenEmu#3222]
So I traditionally use a steelseries controller for my game playing - however, when I load Civilization on the SNES, the controller stops working. The only thing I'm able to do is use the mouse to move the in-game pointer. However, that has it's problems as well. For some reason, I am unable to move the pointer all the way to the righthand side of the screen (which means i can't even get past the enter your name screen). Any idea of what's going on here? Happy to post screen caps if need be.

**Comment by clobber** [comment]
Using the Snes9x core plugin, that game is set to only use the 'SNES Mouse' and might not be perfect. To play that game with gamepad-only, switch the core plugin to Higan (while running the game, go to the HUD menu, click the cog wheel, select Higan).
