### ISSUE TITLE
Cannot access save states on GBA

### ISSUE THREAD

**Issue by AHorseWithNoGame** [OpenEmu/OpenEmu#3224]
Game opens fine if not accessing a save state. But when I try to open a save file, I get the error message: "Couldn't communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again." It was fine yesterday; won't open today.

**Comment by clobber** [comment]
Not nearly enough details to troubleshoot this.

**Comment by clobber** [comment]
Closing for lack of info.
