### ISSUE TITLE
Make Advanced Settings Possible

### ISSUE THREAD

**Issue by mustii82** [OpenEmu/OpenEmu#3225]
We need advanced Settings for the cores in Open Emu.

I can't even play a N64 Game with more Resolution we need more Settings for the Cores to make OpenEmu the best Solution for Emulating Games.

Let us enjoy Retro Games with even more Power than on there Times.

**Comment by clobber** [comment]
Please don't open an issue like this again without first searching.

Advanced core prefs/options. #1281
