### ISSUE TITLE
PSP Only Supports .iso/.cso

### ISSUE THREAD

**Issue by limericky** [OpenEmu/OpenEmu#3226]
I spent several hours today trying to follow https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game for a multi-disc PSP game (The Legend of Heroes: Trails in the Sky SC) to absolutely no avail.  I was creating my m3u file for my bin/cue file which I had ripped from ISO files (this might ultimately be part of my end problem), but could never get it to import.  The ISO files themselves imported without issue, but not my .cues or my .m3u.  Eventually, going through the PSP-Info.plist in the code database, I realised that currently only .iso/.cso is supported.  I tried manually adding the m3u and cue types which did indeed allow me to import my game successfully, but after doing this, the game itself does not load (black screen), so I am guessing something more needs to be done than just adding it to the plist file.

As OpenEmu (as far as I can tell) does not support disc swapping except within confines of the m3u file, this seems to be an issue making this game unplayable.  Am I missing something?

I am aware that the PSP is only in the experimental build, so, I understand if this is beyond the scope of support at this point, but figured either way that it was worth raising.

**Comment by clobber** [comment]
You didn't read the guide close enough - it's only for CD-based games.

For PSP games, you simply only need to drag and drop in the ISO file for it to import. As for multi-umd PSP games, that is still unsupported.
