### ISSUE TITLE
guide to play cd copied games is too complicated

### ISSUE THREAD

**Issue by scrabbl3r** [OpenEmu/OpenEmu#3227]
-i have a file ending .7z. it is a cd file
-i go to click and drag into the Sony Playstation folder on Emu.
-it doesnt recognize it.
-in the guide i read something about a .cue file. but as you can see the game is a .7z

so do i convert it to a .cue file? do i add an extra blank .cue file with it? i dont understand anything..... all i want to do is play this ps1 game but it seems so difficult to set up.

**Comment by Solaire2** [comment]
Download 'The Unarchiver', this will convert it to .cue so you can play. After this if it says there are things missing called SCPH5500 just search them up. I just set mine up yesterday so I thought this would help :)

**Comment by clobber** [comment]
>-i have a file ending .7z. it is a cd file

Uhhh yeah, you might need to unzip that first...
