### ISSUE TITLE
Controls stop working after one game :(

### ISSUE THREAD

**Issue by Solaire2** [OpenEmu/OpenEmu#3228]
When I play a game (only played PS1 games) the my keyboard worked fine controlling the game, played for about an hour no troubles. When I later tried to play again, my keyboard didn't work at all, even when I tried re-mapping the control scheme, it would not enter anything. I plugged a PS3 controller in, and this worked fine, but when I came back later, again, the controls stopped completely. 
I am using a macbook air if that helps anyone figure out a solution, any advice would be helpful :)

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by Solaire2** [comment]
I'm not using any of the things listed, and I have tried closing all applications, unfortunately that did not work. Thanks for the help though, that's definitely a start.
