### ISSUE TITLE
can cgp and glslp filters work?

### ISSUE THREAD

**Issue by rimpydoo** [OpenEmu/OpenEmu#3230]
Im trying to get dithering filters like gdapt, mdapt, or the bilateral blur filter made by sp00kyfox to run on openemu, but it doesn't seem to work at all. bilateral blur is a cg file not cgp.
it seems on other sites people go it it to work, any help?

**Comment by clobber** [comment]
Short answer is no. Most of those other multi-pass shaders rely on unimplemented features that we don't support, as the spec was ever-changing. Cg is deprecated and will be removed in a future release, replaced with GLSL and possibly Metal.
