### ISSUE TITLE
PCE: potful mail cue doesn't work?

### ISSUE THREAD

**Issue by rimpydoo** [OpenEmu/OpenEmu#3231]
Ive no problems with openemu / mednafens emulation. I can emulate other cd games well. but there seems to be a problem with Popful mail. Id drag the cue file into openemu. there will be an error message in game scanner asking me to fix import. so I:ll set it up to pc engine cd. and after that it disappears. game doesn't show up. I drag the iso file and it simply keeps saying error loading rom.

not sure why. I used a text editor to look at the cue file and it looks fine. In fact World Heroes 2 has almost exactly the same thing and it works.

is this a game that doesn't work on the emu? it seems other people who downloaded from the same source didn't have problems

FILE "MAGICAL_FANTASY_ADVENTURE_-_POPFUL_MAIL_(NTSC-J)_[HECD4011].ISO" BINARY
  TRACK 01 AUDIO
    INDEX 01 00:00:00
  TRACK 02 MODE1/2352
    PREGAP 00:03:00
    INDEX 01 00:59:41
  TRACK 03 AUDIO
    PREGAP 00:02:00
    INDEX 01 09:55:33
  TRACK 04 AUDIO
    INDEX 01 11:15:24
  TRACK 05 AUDIO
    INDEX 01 12:14:23
  TRACK 06 AUDIO
    INDEX 01 13:45:25
  TRACK 07 AUDIO
    INDEX 01 15:08:49
  TRACK 08 AUDIO
    INDEX 01 16:21:43
  TRACK 09 AUDIO
    INDEX 01 17:17:30
  TRACK 10 AUDIO
    INDEX 01 18:49:27
  TRACK 11 AUDIO
    INDEX 01 20:10:48
  TRACK 12 AUDIO
    INDEX 01 22:22:40
  TRACK 13 AUDIO
    INDEX 01 23:08:39
  TRACK 14 AUDIO
    INDEX 01 24:36:22
  TRACK 15 AUDIO
    INDEX 01 25:51:33
  TRACK 16 AUDIO
    INDEX 01 27:07:25
  TRACK 17 AUDIO
    INDEX 01 28:23:03
  TRACK 18 AUDIO
    INDEX 01 30:11:33
  TRACK 19 AUDIO
    INDEX 01 32:06:18
  TRACK 20 AUDIO
    INDEX 01 33:05:07
  TRACK 21 AUDIO
    INDEX 01 34:56:49
  TRACK 22 AUDIO
    INDEX 01 36:06:42
  TRACK 23 AUDIO
    INDEX 01 37:24:05
  TRACK 24 AUDIO
    INDEX 01 38:39:45
  TRACK 25 AUDIO
    INDEX 01 41:08:47
  TRACK 26 AUDIO
    INDEX 01 42:54:74
  TRACK 27 AUDIO
    INDEX 01 44:21:56
  TRACK 28 AUDIO
    INDEX 01 45:51:49
  TRACK 29 AUDIO
    INDEX 01 46:35:15
  TRACK 30 AUDIO
    INDEX 01 47:51:49
  TRACK 31 AUDIO
    INDEX 01 49:17:58
  TRACK 32 AUDIO
    INDEX 01 51:27:68
  TRACK 33 AUDIO
    INDEX 01 53:03:00

**Comment by Gankosakae** [comment]
My cue file is imported OK.

FILE "Magical_Fantasy_Adventure_-_Popful_Mail_(NTSC-J)_[HECD4011].ISO" BINARY
  TRACK 01 AUDIO
    INDEX 01 00:00:00
  TRACK 02 MODE1/2352
    PREGAP 00:03:00
    INDEX 01 00:59:41
  TRACK 03 AUDIO
    PREGAP 00:02:00
    INDEX 01 09:55:33
  TRACK 04 AUDIO
    INDEX 01 11:15:24
  TRACK 05 AUDIO
    INDEX 01 12:14:23
  TRACK 06 AUDIO
    INDEX 01 13:45:25
  TRACK 07 AUDIO
    INDEX 01 15:08:49
  TRACK 08 AUDIO
    INDEX 01 16:21:43
  TRACK 09 AUDIO
    INDEX 01 17:17:30
  TRACK 10 AUDIO
    INDEX 01 18:49:27
  TRACK 11 AUDIO
    INDEX 01 20:10:48
  TRACK 12 AUDIO
    INDEX 01 22:22:40
  TRACK 13 AUDIO
    INDEX 01 23:08:39
  TRACK 14 AUDIO
    INDEX 01 24:36:22
  TRACK 15 AUDIO
    INDEX 01 25:51:33
  TRACK 16 AUDIO
    INDEX 01 27:07:25
  TRACK 17 AUDIO
    INDEX 01 28:23:03
  TRACK 18 AUDIO
    INDEX 01 30:11:33
  TRACK 19 AUDIO
    INDEX 01 32:06:18
  TRACK 20 AUDIO
    INDEX 01 33:05:07
  TRACK 21 AUDIO
    INDEX 01 34:56:49
  TRACK 22 AUDIO
    INDEX 01 36:06:42
  TRACK 23 AUDIO
    INDEX 01 37:24:05
  TRACK 24 AUDIO
    INDEX 01 38:39:45
  TRACK 25 AUDIO
    INDEX 01 41:08:47
  TRACK 26 AUDIO
    INDEX 01 42:54:74
  TRACK 27 AUDIO
    INDEX 01 44:21:56
  TRACK 28 AUDIO
    INDEX 01 45:51:49
  TRACK 29 AUDIO
    INDEX 01 46:35:15
  TRACK 30 AUDIO
    INDEX 01 47:51:49
  TRACK 31 AUDIO
    INDEX 01 49:17:58
  TRACK 32 AUDIO
    INDEX 01 51:27:68
  TRACK 33 AUDIO
    INDEX 01 53:03:00

**Comment by clobber** [comment]
I'm not sure I understand all your steps you described. Anyway, to import a CD-based game you simply have to drag and drop in the cue sheet file and it will automatically import to the correct system provided you have the cue sheet and the bin/iso/whatever files all in the same folder. You **do not** need to drag and drop in those other files - **only** the cue sheet. This is in the directions.

I just imported the exact game and set of files you described without a problem, so one has to wonder how you managed to mess it up. I suggest to remove everything you have imported for it now and then simply import the cue sheet file, making sure its iso file is also in the same folder.
