### ISSUE TITLE
OpenEmu crashes (Mac Book Pro Os Sierra)

### ISSUE THREAD

**Issue by lucarav** [OpenEmu/OpenEmu#3235]
Hello, I have a Mac Book Pro 13 inch Mid 2010 with os Sierra. 
I downloaded the roms of Final Fantasy IX (4 disc) and created the .m3u file, but when i try to drag it into the Playstation 1 folder, the app crashes instantly, and it does it every time i try to drag the .m3u file. What's the problem?

p.s. I also downloaded a rom for a Nintendo DS game to see if it does it for every game, but the game seems to run normally, so i think it's a problem connected only with the playstation games.

**Comment by clobber** [comment]
Probably #3153
