### ISSUE TITLE
can not play get past title screen for snes rims

### ISSUE THREAD

**Issue by likeGroovy** [OpenEmu/OpenEmu#3236]
when i start a snes rom all it will do is play the intro and then go to the title screen ( and there is no press start text) i tried to delete openemu and deleted the file with it and reinstalled but the same problem occurred

**Comment by clobber** [comment]
Um is it a game without "press start" text? Which game?

**Comment by likeGroovy** [comment]
it use to work. but now i cant start megaman x 1 2 3 metroid donkeykong (thats all i had at the time)

**Comment by likeGroovy** [comment]
is there another file I can delete to maybe redownload. I only found one in my library

**Comment by likeGroovy** [comment]
i fixed  nvm sry for the bother
