### ISSUE TITLE
Problem with battery save for player 2

### ISSUE THREAD

**Issue by Tanapat1992** [OpenEmu/OpenEmu#3238]
Hey guys there is anyway how to share battery save for another players like player 1 vs player 2 and player 2 also need to load save file (Yu-Gi-Oh battle capsule monster ps1)

Thanks for future

**Comment by clobber** [comment]
Sorry, not really familiar with this series or clear on what you are trying to do, but it doesn't sound like it's possible otherwise it would be obvious.

**Comment by digamejh** [comment]
Are you referring to the two memory cart slots on the PS1?

OpenEmu creates two virtual memory cards for each PS1 game, represented by .mcr files found in ~/Library/ApplicationSupport/OpenEmu/Mednafen/Battery Saves/ (if I remember correctly...).  The file names will start with the game name, followed by a hexadecimal string and ending in ".1" or ".2" for each of the virtual memory cards.

I'm not quite understanding what you are trying to do either, but that should be your starting point.
