### ISSUE TITLE
How can I only use keyboard for the games

### ISSUE THREAD

**Issue by lerous** [OpenEmu/OpenEmu#3239]
I just asked the switch joystick, openemu don't support it for 1 player and close the issue.

and then I try to use a mac app called joystick mapper,  map the keyboard on each joystick, it works fine in any text editor.

But the openemu active the joystick and keyboard at the same time, so I can't map it in the game, how can I only use keyboard for the game, and let the openemu don't active the joystick auto? so that it's a way we can use 2 switch joysticks for 1 player in openemu.

**Comment by clobber** [comment]
Keyboard and gamepad modifier apps are not supported. What you're trying to do isn't going to work. It's not possible.

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
