### ISSUE TITLE
High Sierra beta: Freezes Constantly After Playing for a While

### ISSUE THREAD

**Issue by ZachieBlade** [OpenEmu/OpenEmu#3240]
As title says, I'll play for a little bit (anywhere from 2-5 minutes) but it'll always end up freezing and I have to Force Close.

MacOS High Sierra beta, latest version of the app from the website.

**Comment by clobber** [comment]
Lol you are running on beta macOS, which you obviously shouldn't be doing. The least you could do is provide as much details as possible. You know, example game+system and if there is any output in Console.

**Comment by clobber** [comment]
Closing this for now. We cannot provide support for developer betas of macOS since we don't run it. If it turns out to be a problem on release, then we will address it.
