### ISSUE TITLE
DS Screen placement customization

### ISSUE THREAD

**Issue by Speeris** [OpenEmu/OpenEmu#3243]
I saw an issue of this but it was outdated so I'm curious if any changes have been made concerning the customization of DS screen placement.
I'm m currently a game that does not require equally large screens so I was wondering if I could place the touch screen in like the upper right hand corner or something.
if I'm posting this in the wrong place please tell me, I'm new to this

**Comment by clobber** [comment]
No change from the previous issue. This doesn't need another issue opened.
