### ISSUE TITLE
My OpenEmu stopped working

### ISSUE THREAD

**Issue by alecjameson** [OpenEmu/OpenEmu#3244]
Hello,

I don't know if this is an easy problem to fix, but ever since two days ago whenever I open OpenEmu I just get the circling colour wheel, and the program then promptly stops responding and I have to force quit the program. I tried deleting the program and redownloading it but that didn't fix the problem. 

Does anyone have any advice? I love openemu, but at this point it looks like it might have stopped working forever for me, as it's been two days of the program automatically not responding when I open it.

Thanks for any help.

**Comment by clobber** [comment]
Which version of OpenEmu and macOS? Any output from Console?

**Comment by clobber** [comment]
Closing for lack of info.
