### ISSUE TITLE
Quick question about updates

### ISSUE THREAD

**Issue by heyuimintojsus** [OpenEmu/OpenEmu#3245]
Hi, I was just wondering if someone could tell me if there may be a particular reason why OpenEmu won't load English-translated games from emuparadise or from patching them from romhacking.net for NES/Famicom games? Or if there will be an update in the near future to resolve these? Not sure if this is the place to ask the question, but wasn't sure where else, and I hope it's an OK question. Thank you in advance.

**Comment by clobber** [comment]
Patched games work fine, I have dozens. One needs to first apply the patch to a ROM and then import the new ROM file: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Apply-ROM-Patches-(for-fan-made-translations-and-mods)

That's all the help we can offer with this.

**Comment by heyuimintojsus** [comment]
This is not true because I have several that do not work on openemu.

**Comment by clobber** [comment]
If a NES game doesn't run in the default core plugin (Nestopia) due to bad or unsupported mapper, then switch the default to FCEU instead. It's really that simple.

https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Default-Cores

**Comment by heyuimintojsus** [comment]
I had absolutely no idea about that. That did it for those translations. Thanks so much Clobber for that bit of info. I appreciate it!
