### ISSUE TITLE
Can't add PSX games to library (Experimental edition)

### ISSUE THREAD

**Issue by atomicBRblaster** [OpenEmu/OpenEmu#3246]
Hi there, guys!

I've followed every single step to be able to play PSX games, but never succeeded.

I've tried with regular version and with the Experimental, but none works.

It's important to say that. BIOS and all requirements are correctly set and other platforms works great as SNES, Genesis.

Could anyone help me with that?

**Comment by clobber** [comment]
Sorry, no. Can't offer any more help beyond what is in the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) so follow it closely and make sure you have good rips of games.

**Comment by atomicBRblaster** [comment]
It's not a "good rip". It's the disc itself. An original copy of Final Fantasy IX to be precise.

**Comment by clobber** [comment]
Um, that is not supported. You'd know that if you actually read the guide.
