### ISSUE TITLE
Problems with loading multiple discs .m3u files into OpenEmu (nothing appears)

### ISSUE THREAD

**Issue by dhkdgnldud** [OpenEmu/OpenEmu#3247]
I deeply apologize for being the 100,000th person to report an issue regarding multi-disc imports, but I'm a new OpenEmu user who is having having issues importing an .m3u file for Tales of Destiny II. I have followed the instructions for the new guide exactly as is, from the copying name files to plain text editor and saving it down as .m3u, but when I dragged-and-dropped the .m3u file, I can only see the load bar for a few seconds and then it disappears, leaving the library empty still.

Can anyone please help? Thank you in advance.

**Comment by clobber** [comment]
Possible issues:
* You don't actually have the m3u set up correctly (follow the guide closely).
* Your games are still imported in the library. The guide says they need to be removed and deleted first, so make sure they aren't still in ~/Library/Application Support/OpenEmu/Game Library/roms
* You have files lingering in the 'unsorted' folder that got stuck there during a bad import.
* Your cue sheets are wrong and not referencing the bin files correctly.
* You have a bad rip of the game and will need to find another copy.

Can't offer any more help beyond what is in the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game)
