### ISSUE TITLE
XBox 360 Wireless Controller with Open EMU

### ISSUE THREAD

**Issue by Phihaase** [OpenEmu/OpenEmu#3249]
Hey,

i use 4 XBox 360 Controllers via the Xbox 360 Controller Driver Version 0.16.5 on a macbook pro.
When i try to map my controllers i can perfectly control every driver in the driver settings.
Still in Open Emu mapping doesn't work. Sometimes i cannot map at all since the program doesnt react to my moves on the controller, sometimes i can map 2 controllers, sometimes when i try to map Open Emu automatically jumps to another controller while mapping. I really can find no pattern behind it.

Has anyone got experience with this combination of Xbox 360 wireless controllers on a macbook and open Emu? 

I would be very open to any help.

Thanks very much,

Philipp

**Comment by clobber** [comment]
Issues with input not responding will be related to what is outlined here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

I haven't experienced and cannot replicate the other things you mentioned. You may be getting confused as to which connected gamepad belongs to which 'virtual player #' in the settings.
