### ISSUE TITLE
OpenEmu crashes when i try to open up a game

### ISSUE THREAD

**Issue by Markymoo39** [OpenEmu/OpenEmu#3251]
Whenever I try to open up one of my games, Openemu crashes. Is anyone else experiencing this?

**Comment by clobber** [comment]
Please post a crash log.

**Comment by inakilbss** [comment]
If it's anything like mine, then just delete ~/Library/Application Support/OpenEmu/Bindings/default.oebindings or something like that.

**Comment by clobber** [comment]
Closing for lack of info.
