### ISSUE TITLE
Expose Core Features

### ISSUE THREAD

**Issue by carlsmith** [OpenEmu/OpenEmu#3256]
Support for configuring emulators has not been discussed since 2014, and most of the conversations have been locked down so only contributors can comment there.

If users are required to use some of the emulators outside of OpenEmu to make some games playable, it defeats the purpose of the project.

**Comment by clobber** [comment]
You opened this issue already knowing the current status, having read past discussion, and that really annoys me.

>it defeats the purpose of the project

The purpose of OpenEmu is to play retro games with as zero config as possible.

If a system seriously needs options for games to be playable (which none currently do, in fact, we've went to great lengths to make sure that is unnecessary) then we will work a way for advanced core preferences. Use something else if you feel you are "required" to.
