### ISSUE TITLE
Audio issues in PSP emulation

### ISSUE THREAD

**Issue by TempSpas** [OpenEmu/OpenEmu#3257]
I am having pretty extensive issues with audio when attempting to emulate PSP games. Audio is often choppy and distorted. Here's a video of the issue:

[Choppy audio](https://www.youtube.com/watch?v=sQR0o1jr0zM)

I know that OpenEmu displays a dialog addressing the core compatibility issues, but this does not appear to be the case, because the most recent version of PPSSPP runs the games smoothly and without audio issues. ([Another video link](https://www.youtube.com/watch?v=AMBpQNPAJls); these aren't mine but they illustrate what I'm talking about).

I'm on macOS 10.12.5, running version 2.0.5 of OpenEmu. I was unsure if the issue is because the core OpenEmu uses hasn't yet been updated to the most recent version of PPSSPP, or if it's a different underlying issue. Either way, the bug appears to be with OpenEmu.

**Comment by PhishSkale** [comment]
Have you tried installing different versions of the game to see if the issue is still there?

**Comment by TempSpas** [comment]
I have not tried different versions, but since it's occurring on more than one game, I didn't think that was the issue.

**Comment by TempSpas** [comment]
I just tried a different version of one of the games, and the issue persisted.

**Comment by clobber** [comment]
#1036
