### ISSUE TITLE
Help with multi disk .bin.ecm files

### ISSUE THREAD

**Issue by dhkdgnldud** [OpenEmu/OpenEmu#3258]
I downloaded a ROM for Final Fantasy VII (3 discs) off EmuParadise, it came as a .7z and when I extracted them, the files I got are only 1 .bin.ecm (per discs) and nothing else.

I'm a noob at this so I'm not sure what to do, but so far I've done:
1. Terminal-ed all 3 .bin.ecm to .bin;
2. Created 3 .cue files for each .bin from scratch (because there wasn't any);
3. Created .m3u for all the .cue and imported it to Openemu.

Clearly it's something who doesn't know what to do would do, so of course it didn't work and then I had a pop up that said:

> ECM compressed binary detected.
> ECM compressed binaries cannot be imported. Please read the disc importing guide.
> 

Can anybody help, please? The guides from Openemu are really not helping because I understand almost none of it and I'm not a Terminal user either (and there aren't really a combo-guide for this case). A detailed guide would be appreciated. Thank you in advance.

**Comment by clobber** [comment]
> ECM compressed binaries cannot be imported. Please read the disc importing guide.

Do what the message says and actually read the guide. https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-an-ecm-or-ape-file

> The guides from Openemu are really not helping because I understand almost none of it and I'm not a Terminal user either

Can't help you beyond what is in the guide - they work for everyone else.

>A detailed guide would be appreciated.

The guides are **very** detailed.

If reading and following directions is too hard then I suggest trying to find other copies to download that are not ECM compressed and include proper cue sheets too.
