### ISSUE TITLE
SNES controller not working in game after 2.0.5 update

### ISSUE THREAD

**Issue by PhishSkale** [OpenEmu/OpenEmu#3259]
Trying to play SNES on OpenEmu 2.0.5
macOS Sierra 10.12.6

My MBA installed this macOS update automatically when I plugged the charger in.

It seems like ever since the OpenEmu 2.0.5 update the controls plugged in via USB don't work in the game on first launch. The controls can be mapped, but don't do anything in game.

After restarting the system the controller can still be mapped, but doesn't work in game.
Closing OpenEmu and relaunching after mapping seems to make the controls work. 
Is this how the controls are supposed to work on 2.0.5?

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by PhishSkale** [comment]
![screen shot 2017-07-09 at 8 18 45 am](https://user-images.githubusercontent.com/30014376/27994241-599357f8-647f-11e7-93d6-70055c766b17.png)

I wonder if this app Xone Controller could interfere with OpenEmu as well. 
I'm going to uninstall it; I no longer need it.
