### ISSUE TITLE
Multiple controller configurations

### ISSUE THREAD

**Issue by Sachka** [OpenEmu/OpenEmu#3260]
It would be nice to have an option to save multiple controller configurations. Imagine a situation where you map your Dualshock 4 to play Super Mario 64 (using default config is pretty good), then suppose you want to play Super Smash Bros. , it is nice to be able to jump with "Triangle" so you change your DS4 mapping for N64 again, then imagine you want to play GoldenEye and there we go again... It could be awesome if you associate the mapping to a game so if you only have a Mac and a DS4 you could play N64 according to your mapping without setting up the controller every single time.

**Comment by clobber** [comment]
This has come up a few times (please use the search) and it's not going to happen now because it would really complicate the input system.
