### ISSUE TITLE
Playstation 1 games are restarting

### ISSUE THREAD

**Issue by npartlow** [OpenEmu/OpenEmu#3261]
Whenever I open one of my PS1 games, the emulator is suppose to open up where I left off but sometimes there are cases when a pop up opens up and says:

**The operation could not be completed 
No other information is available about the problem**

and so the game itself resets to the title screen.

please fix it.

**Comment by clobber** [comment]
Go to the Save State manager and delete all autosaves for the game(s). Also go into the folder where the autosaves are and delete any lingering orphaned autosave files in it.
