### ISSUE TITLE
No MSX Support?

### ISSUE THREAD

**Issue by diogoschneider** [OpenEmu/OpenEmu#3264]
In the 80s, the MSX was the main platform for the best games from Konami and several other developers. It is a home computer, but with the addition of gamepads it's no much different from any other videogame from the same era. (Think of the SG-1000 related the Master System) Please, this platform must be added here. Thanks!

**Comment by clobber** [comment]
Please use the search.

https://github.com/OpenEmu/OpenEmu/wiki/Console---Core-Plugin-Status-&-Wishlist
