### ISSUE TITLE
my CRT filter has yellow vertical bars really visible on games 

### ISSUE THREAD

**Issue by WayneStruders** [OpenEmu/OpenEmu#3265]
does anyone else have this issue I have included a picture 
![img_1648](https://user-images.githubusercontent.com/30233996/28267279-47950394-6af1-11e7-89aa-11969e5ae5af.JPG)

**Comment by WayneStruders** [comment]
ITS on the CRT filter

**Comment by WayneStruders** [comment]
any one help or know whats going on 
? also can anyone help with adding more filters ? THANKS GUYS

**Comment by clobber** [comment]
It seems that's how it looks. No, we cannot help with adding additional ones. They are unsupported, aside for the ones we already include with the app.
