### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by distinity** [OpenEmu/OpenEmu#3267]
Hi,

I have been trying to get the controls on any of the games to work I keep changing the controls to see if that helps but it doesn't. I would like to play my favourite franchise, Legend of Zelda, again as I haven't played the originals in a few years. The consoles or "Cores" i have been using are the SNES, NES and Gameboy Advanced emulaters on Open Emu.

Thanks!

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
