### ISSUE TITLE
"Couldn’t communicate with a helper application." after updating to v2.0.5

### ISSUE THREAD

**Issue by planeticus** [OpenEmu/OpenEmu#3268]
Hi,

I updated to v2.0.5 because in the previous version I had (v1.x) I couldn't see the HUD bar.

However, since I updated I cannot load any state saves (both quick or automatic) saved previously; I see them in the Save States tab, but if I click on them or I try to load them in any other way, I get the message "Couldn’t communicate with a helper application."

As for the in-game save states, I see the files in the directory, but the game seems not to see them (if I load it it just lets me start a new game).

I'm using a pokemon rom for gba, for which I tried both vba and mGBA (for which I already copied and renamed the in-game states, following "User Guide: Transfer Save Files" instructions).

Before opening a new issue I read a lot of older threads (that's why I tried mGBA), but most of them seemed to refer to different issues.
The only similar one was #2219, which however referred to a different emulator.

Let me know if you need further information.

Thanks in advance

**Comment by clobber** [comment]
Old VBA save states from OpenEmu v1.x are not going to work. You should follow the transfer guide and copy battery save files, not save states. Then, make sure you are loading your GBA games with mGBA and not VBA (which was deprecated, removed and no longer shipped with OpenEmu 2.x).
