### ISSUE TITLE
N64 Emulator Horipad Unable to Assign Keys

### ISSUE THREAD

**Issue by adventurejosh** [OpenEmu/OpenEmu#3269]
On Player 1 with 2 Bluetooth Horipad controllers connected, it is impossible to assign new keys. As you can see from my screenshot, they are incorrectly configured. Though, player 2 seems to be OK.
![screen shot 2017-07-18 at 3 48 39 pm](https://user-images.githubusercontent.com/30274700/28343200-ff3d4b16-6bd0-11e7-9e4a-745ce7f19c20.png)

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by adventurejosh** [comment]
None of these apply to my situation.

**Comment by clobber** [comment]
You sure? There isn't a reason why input doesn't work with the Horipad besides what is outlined in that guide. That device works the same as all the other MFi devices and none of them have issues.

Alternatively, you can do the following to reset all mappings to default and take it from there:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.
