### ISSUE TITLE
Nintendo Switch Pro Controller causes crash when plugged in

### ISSUE THREAD

**Issue by dunn** [OpenEmu/OpenEmu#3272]
Related to #3116, #3154, #3174, etc., except this persists after running 
```shell
rm ~/Library/Application\ Support/OpenEmu/Bindings/Default.oebindings
```
as @clobber suggests in those issues.

Crash logs before deleting the bindings file:
- https://gist.github.com/anonymous/3bbead76184aaffe2dd58411f4752813
- https://gist.github.com/anonymous/edd44d3d978bef25ed83a3f852611581

Crash log after deleting the bindings file:
- https://gist.github.com/anonymous/01af2b8d2823a96d61f53d29a5f711ae

(OpenEmu 2.0.5)

**Comment by clobber** [comment]
Is it a legitimate Switch controller or is it a clone/generic/knock off?

Also check if you have some third party input software installed or anything else related in this guide: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by dunn** [comment]
> Is it a legitimate Switch controller or is it a clone/generic/knock off?

Yes, unless GameStop scammed me.

> Also check if you have some third party input software installed or anything else related in this guide: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

I had Keybase and iTerm running, but I quit them and still get a crash: https://gist.github.com/anonymous/51b135d0fd310eed31e8166c5970ffa6

**Comment by dunn** [comment]
Tried restarting too, that didn't help.

**Comment by clobber** [comment]
Are you saying you have the device "plugged in" via USB? I didn't know it was connectable to PC via USB and if so, it may be presenting a totally different HID profile than what we expect when it is normally connected via Bluetooth. Try Bluetooth instead and make sure to wipe your Default.oebindings file again.

**Comment by dunn** [comment]
Ah, yeah.  It charges via USB-C so you can plug it in directly to the computer.

**Comment by dunn** [comment]
Linking via Bluetooth works fine.  Should this ticket remain open, since there's apparently a bug with wired linking?

**Comment by clobber** [comment]
>Linking via Bluetooth works fine. Should this ticket remain open, since there's apparently a bug with wired linking?

No I don't think so. As far as I've read, the device does no communication over USB - just charging. It should only be used via Bluetooth for gameplay.
