### ISSUE TITLE
Mame (experimental) and spinner knob controls?

### ISSUE THREAD

**Issue by wolfgangrumpf** [OpenEmu/OpenEmu#3274]
The experimental MAME seems to work pretty well for games with straightforward controls - I tried running startrek (Star Trek Strategic Operations) and while the game worked great (vector graphics looked awesome, the button controls worked fine) the directional controllers (which in the arcade were a spinner knob) were unaccessible - the arrow keys for left/right/up/down didn't map to their spinner equivalents, so there was no way to control direction.

It seems like the solution to a spinner control (a wheel that rotates infinitely either clockwise or counterclockwise) would be to implement a left / right direction that input either clockwise or counter clockwise to the game.....

**Comment by clobber** [comment]
Arcade/MAME is 'experimental' and thus unsupported at this time. It is also missing support for other input types (such as analog).

#1085
