### ISSUE TITLE
Master System (disable YM2413 FM Sound)

### ISSUE THREAD

**Issue by Samberto** [OpenEmu/OpenEmu#3276]
Request to access TwoMbit's option to choose PSG over FM Sound. As Master Systems in the west didn't have FM functionality, the synth tracks don't feel nostalgic like the PSG chip tunes. 

Could an audio toggle be mapped to the "Display Mode" for Master System? Appreciate that feature for turning off the Super Gameboy! 

Love OpenEmu - just signed up on Patreon. 👍

**Comment by clobber** [comment]
Sorry, we don't have a way to do this right now that won't be a headache for us. Try switching cores to CrabEmu or another version of the game which might not detect or have FM sound.

Advanced core prefs/options. #1281

**Comment by Samberto** [comment]
Thanks - CrabEmu is also default to FM unfortunately. Appreciate the reply.
