### ISSUE TITLE
Cores automatic update Incompatible

### ISSUE THREAD

**Issue by YiNicer** [OpenEmu/OpenEmu#3278]
Cores automatic update makes MAME core up to 0.149.1. This version makes a bug with my rom.
When I open Arcade games  in the second time，Emu will be Black Screen，and I cant close this window unless Force Quit.Terminal only show me refresh rate(I think it is normal).Then，I delete this rom，and reload this rom，this rom can be open once. next time ,the bug will be happen.

I use 1.04 version(Core will not be updated automatically) ，MAME 0.149，everything is OK.

So , what should I do if  I don't want to update my core with the  latest version OpenEmu?
Or，support choose update or not update like 1.04 version.

MAC 10.12.6 

Thank you.

**Comment by clobber** [comment]
Why would you still be using OpenEmu 1.0.4 if you are on macOS 10.12.6? 1.x is unsupported.

Update to OpenEmu 2.x (latest version is 2.0.5 as of writing).

As for MAME, see https://github.com/OpenEmu/OpenEmu/issues/2615#issuecomment-230357101

**Comment by YiNicer** [comment]
Thanks@clobber ,Thanks you all for you making this APP.

I tried click no,It works for me in v2.05.

Thanks a lot.
