### ISSUE TITLE
Permission to access repository

### ISSUE THREAD

**Issue by Primus-Wren** [OpenEmu/OpenEmu#3279]
I've been trying to clone this repository to GitHub desktop but every time I get this message. 

![screen shot 2017-07-25 at 6 46 07 pm](https://user-images.githubusercontent.com/30431684/28568757-914be7a4-7169-11e7-8efa-272bb5b44724.png)

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide#command-line-install-guide-advanced-users
