### ISSUE TITLE
Lags and becomes unresponsive

### ISSUE THREAD

**Issue by chijuancito** [OpenEmu/OpenEmu#3280]
Hi, 

I was attempting to use the Openemu app and became aware that it was lagging with the colored circle and becoming unresponsive with the OS system. I wanted to see if anyone could help. Here is the spindump file for the program. 
[Spindump.txt](https://github.com/OpenEmu/OpenEmu/files/1175219/Spindump.txt)

**Comment by clobber** [comment]
Update to the latest version of OpenEmu first. Currently 2.0.5

**Comment by chijuancito** [comment]
Hi, 

I've got your message. Problem is still not solved. Please help!

**Comment by clobber** [comment]
>Please help!

Help me help you. Post exact details, such as what you are doing and how/when the issue occurs, instead of being vague. That's better than playing the guessing game in order to troubleshoot.

**Comment by chijuancito** [comment]
I downloaded the updated version of the game. After that I opened the
program. Once I click on the program it gives me the colored loading
circle. The program becomes irresponsive. I try clicking any function
within the program and it does nothing but stay lagging with the color
cursor. I have given it time, like about 5 to ten minutes and it does the
same. So I am left with no other option but force it to close.
I have recently made an update on the computer's hardware from normal disk
drive to ssd. Everything was recovered through a backup. I dont know if
that would cause it a problem.
Let me know if this works, or if you need more info.
