### ISSUE TITLE
Can't import ROMs

### ISSUE THREAD

**Issue by RobotLimeLtd** [OpenEmu/OpenEmu#3281]
I can no longer import ROMs to OpenEmu.  Whether I drag/drop or use the '+' button to add them, it goes through the motions (UI shows it trying to import), but doesn't import anything.

In the Console output, I get the following error for each:

`default	10:02:26.127681 +0100	OpenEmu	Error Domain=OEImportFatalDomain Code=-1 "(null)"
`

Same ROMs import fine into RetroArch.  If I copy ROMs already in OpenEMU to a temporary directory, then remove them in the UI, they don't re-import either.

**Comment by RobotLimeLtd** [comment]
I've managed to narrow this down - it's only Gameboy Advance ROMS that are not importing.

**Comment by clobber** [comment]
> or use the '+' button to add them

Sounds like you are using OpenEmu 1.x which is unsupported.

**Comment by clobber** [comment]
Whoops, I forgot the "Add to Library" functionality still exists there in 2.x too.

Anyway GBA games import just fine. Here's an example: [mapTest.gba](http://www.cavestory.org/downloads/mapTest.gba) (right click, save as) then drag and drop the file into your Library.

**Comment by RobotLimeLtd** [comment]
Ok - I've worked it out.  The ROMS are zipped using a compression format OpenEmu doesn't support.  Thanks for the test file.
