### ISSUE TITLE
Cannot launch ROMs compressed as ZIP files using built-in ZIP compresser

### ISSUE THREAD

**Issue by duckspike** [OpenEmu/OpenEmu#3282]
As the title suggests, I've recently encountered a difficulty launching Nintendo DS ROMs that I have compressed myself using the "Compress <file>" context menu item. Any ROM I've downloaded from the internet as a ZIP works perfectly fine, but trying to launched a ZIPed rom that I made myself tells me that the ROM can't be loaded.

Tested with 2.0.4 and 2.0.5 on a MacBook Air.

**Comment by clobber** [comment]
This is due to a different bug and nothing with Archive Utility.

Already fixed for next release. #3127
