### ISSUE TITLE
Compatibility with DualShock USB Wireless Adaptor on Mac

### ISSUE THREAD

**Issue by RobotLimeLtd** [OpenEmu/OpenEmu#3283]
Please could you add full compatibility with the DualShock 4 Wireless USB Adaptor?  Yes, I know you can connect the DualShock 4 directly over Bluetooth... but that doesn't work for the PS4 Remote app.

It almost works with OpenEmu, except that I cannot map L3, R3, R2 or the analogue sticks.  Also, when I try to set L2 as "Quick Save" it sets both Quick Save and Quick Load to "Rx+" and "Rx-" respectively.

**Comment by clobber** [comment]
Please search before opening a new issue.

#2788
