### ISSUE TITLE
Deleting the rom file and not selecting "I've moved it" causes app to crash

### ISSUE THREAD

**Issue by yangnw** [OpenEmu/OpenEmu#3285]
- delete rom file in finder
- "delete game" in openemu
- asks if it's moved, select no

I expected to see the game entry removed from openemu library, but instead, the game entry remains, and if I try to right click and "delete game" again, the app crashes. 

OpenEmu 2.0.5, experimental.

**Comment by robotoad** [comment]
> delete rom file in finder

OpenEmu manages the contents of the Game Library folder. To remove a game, you should delete it within OpenEmu. Manipulating library files via Finder can lead to corruption of the datastore and require starting over.
