### ISSUE TITLE
multiple discs with mednafen, saturn

### ISSUE THREAD

**Issue by Lunaticmango** [OpenEmu/OpenEmu#3289]
Hi guys, so sorry to bother you knowing that Mednafen for saturn is in experimental stage. I am having issues with importing saturn games with multiple discs. I am using open emu v.2.0.5 and mednafen 0.9.45.1.
I know another member online mentioned that he or she finally succeeded. Clobber said that with the new mednafen, it is now possible, altough completely in experimental stage and not official yet.
I followed the procedure online to the bones (using text edit for the m3u file), but with no luck. I also watch a procedure on youtube with a guy using texMate and pre importing the cue sheets before. I tried that too but no luck. I know the youtube video was for playstation. 
I will be very grateful if somebody could help me on this, thanks so much in advance.

**Comment by clobber** [comment]
>watch a procedure on youtube with a guy using texMate and pre importing the cue sheets before. 

Never do that. It doesn't work and is not how those files can be imported.

Unfortunately, I can't help you beyond what is in the import guide. Try searching the Issues to see if you find some info relevant to you.
