### ISSUE TITLE
Latest 8bitdo firmware breaks NES30 Pro automappings

### ISSUE THREAD

**Issue by vol24pl** [OpenEmu/OpenEmu#3293]
Hello. 

http://imgur.com/90bg3k2

As you can see on the picture for 8bitdo NES30 PRO: L2 is mapping to "Button 196 instead of 9 and R2 is mapping to Button 197 instead of 10.

App Controllers Lite is showing the proper mapping. 
This is an issue because when I click "right" it triggers both "right" and "L2".

I have updated my controller 2 months ago.

**Comment by vol24pl** [comment]
Same behavior when connected via Bluetooth and USB.

I happen to have 2 8bitdo NES30 PRO controllers and I reproduce this issue on every one of them.

macOS Sierra 10.12.6 (16G29)
OpenEmu v2.0.5 719-g369c3a2-Release

**Comment by clobber** [comment]
8bitdo changed something in their latest firmware (4.x) by switching Button numbers around, which breaks our automappings. Your workaround is to 'downgrade' back to the 2.x firmware for now. We cannot keep changing our automappings each time their firmware changes, as that would break automappings for users that haven't updated to the 4.x firmware yet. We will keep an eye on this though.

**Comment by vol24pl** [comment]
Thanks for the information!

Well – if I may – my suggestion would be to let the user choose which firmware compatibility he wants in the secret "konami code menu". 

Power users know about the menu and are expecting this kind of settings there.
Regular user wouldn't even see it and wouldn't be confused by it (while everything would stay the same for him).

Information about it could be placed in the git-hub wiki for controllers, so people would know where to find it and you would lay a responsibility for the proper config on user.

Just a suggestion on how to make everyone happy :)

**Comment by clobber** [comment]
Sorry, no, not going to go through the trouble of implementing something like that. Will eventually update the mappings to reflect the new firmware.
