### ISSUE TITLE
couldnt communicate with helper application

### ISSUE THREAD

**Issue by gavicii** [OpenEmu/OpenEmu#3294]
hola, i just have a problem with openemu 1.0 
everytime im trying to open a rom, ( any pokemon rom for gba, gbc and ds ) it says: Couldnt communicate with helper application.  I can`t open any rom, i already reinstalo the cores, and delete and re instalo openemu several times but nothing is working, im desperate. can somebody help me please?? i follow you back, if there is anyone who sepas spanish it will be awsome!
please help!

**Comment by clobber** [comment]
Sorry, OpenEmu 1.x is unsupported.
