### ISSUE TITLE
How to change PSP's system font on OpenEmu?

### ISSUE THREAD

**Issue by dropedrops** [OpenEmu/OpenEmu#3297]
Hi there! Here's the issue:

There're some games on PSP that uses the system's original font in character dialogues or message boxes, like Monster Hunter 3, Lunar: Silver Star Harmony, Jeanne Darc and others.

When you are playing these games on a emulator, you have to change the PPSSPP's font to PSP's hardware font, if you want the emulator displays it correctly. Otherwise, the default PPSSPP font end up displaying the dialogues improperly because of it. The result in Lunar, for example, is that text gets cutoff heavily in many lines. You can see exactly how it happens here:

https://github.com/hrydgard/ppsspp/issues/8262

Well, the fix is fairly simple on Windows and Android systems, cause you just have to replace some fonts files and it's done. But, how I change these files on Mac? Especially on OpenEmu, that doesn't show any folder, much less emulators files. I already have the PSP's hardware font files, just want to know how can I replace it when using OpenEmu. ;)

Thanks a lot! o/

**Comment by clobber** [comment]
`~/Library/Application Support/OpenEmu/PPSSPP/font ` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)

**Comment by dropedrops** [comment]
Nice! Thanks for the support, man!

**Comment by froggiepunch** [comment]
This doesn't actually work, at least not for Jeanne d'Arc. I've put the font files exactly where indicated, but the text is still a garbled mess as you can see https://imgur.com/vYJ1b7Q

The only solution I've found is to rebuild the core myself with the actual fonts, which is less than ideal because each update will break it.

**Comment by Scourgebane** [comment]
Is there something I am missing with this problem?  I placed my original PSP fonts in the ~/Library/Application Support/OpenEmu/PPSSPP/font folder but the text is still cut off in places as if PPSSPP is ignoring the files in that folder.  I read somewhere that you also have to disable display buffering to fix the font, but as far as I can tell there is no way to change display settings in OpenEmu.
