### ISSUE TITLE
Trouble Loading Multi Disc Games

### ISSUE THREAD

**Issue by tpfeeney** [OpenEmu/OpenEmu#3298]
Hello,

 I have read the instructions for loading multi disc games and have followed them to no avail. I am trying to load FF7 and MGS. I have made sure the cue files are not loaded in open emu (and not in the unsorted folder either). I have made a plain text *.m3u file (Final Fantasy VII (USA).m3u) file in a folder (Final Fantasy VII) folder on an external HDD. The folder also contains the cue and bin files for all three FF7 discs. From that folder I have attempted to drag and drop the *.m3u file into open emu with no success. I have also tried manually loading the *.m3u file too, and that also hasn't worked. 

Is anyone aware of this not working and what might be done to make it work?

**Comment by TempSpas** [comment]
What are the contents of the m3u file?

**Comment by tpfeeney** [comment]
Sorry I didnt include this before. The contents are:
Final Fantasy VII (USA) (Disc 1)
Final Fantasy VII (USA) (Disc 2)
Final Fantasy VII (USA) (Disc 3)

From what I understand from the instructions this should be all that is needed.

**Comment by TempSpas** [comment]
Change the contents to as follows:

`Final Fantasy VII (USA) (Disc 1).cue
Final Fantasy VII (USA) (Disc 2).cue
Final Fantasy VII (USA) (Disc 3).cue`

And see if that allows you to import the .m3u.

**Comment by tpfeeney** [comment]
Yes. I guess I didn't pay enough attention to the instructions. Thank you much for your patient help.
