### ISSUE TITLE
Dont open ps1 game

### ISSUE THREAD

**Issue by kek318** [OpenEmu/OpenEmu#3299]
Downloaded and installed experimental openemu 2.0.5
Added BIOS (md5 checked)

But the games (psx) is not added to the library (nothing is added to the scan)

Tried iso, bin + cue

Console
Error Domain = OEImportFatalDomain Code = 3 "(null)"

**Comment by kek318** [comment]
mac os sierra 10.12.6

**Comment by kek318** [comment]
![default](https://user-images.githubusercontent.com/30776364/29004903-4d2f739c-7ad8-11e7-969b-cf997b77114c.png)

**Comment by clobber** [comment]
Your cue sheet is what you want to import. Follow the CD guide https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games

Everything one needs to know is in there. Can't help you beyond that.

**Comment by kek318** [comment]
I do everything on the guide, I read it several times
But when I move these two files (cue and bin) into openemu window nothing happens

**Comment by clobber** [comment]
>I do everything on the guide, I read it several times

No, you haven't read the guide if you believe you need to move iso or bin into the window. The guide states just the cue sheet (with the bin being in the same folder alongside it). If nothing happens, you have a bad rip of the game which cannot be autodetected, or you've done something else wrong.

**Comment by kek318** [comment]
I tried and the way you wrote

**Comment by kek318** [comment]
I open this game in PCSX-Reloaded and I will use this program and not your sloppy program!

**Comment by clobber** [comment]
Thanks 4 the info, dope. Really sad to see an important and valuable user as yourself leave. Enjoy!
