### ISSUE TITLE
Black screen issues

### ISSUE THREAD

**Issue by Kenlimepie** [OpenEmu/OpenEmu#3301]
I was playing Pokemon HeartGold (on DS) which my friend gave the file to by Google Drive. It was going ok until I was getting a black screen, it happened when I was trying to load my save file. That was pretty weird since some of the files worked while others don't. Everything else works properly like the bottom half, the sound, and I can walk around in the game, but it is the black screen that is the problem (I can exit the game btw). I tried going into my newest file state that isn't black screened and did some progress, it just went black screen again after I saved it. I am playing this on a Mac computer with a 10.12.5 on my computer and 2.0.5 version, 719-g369c3a2-Release on the OpenEmu. Hopefully I can get this problem fixed soon, I am already at the first gym! 😛 
<img width="619" alt="screen shot 2017-08-09 at 7 40 08 pm" src="https://user-images.githubusercontent.com/30881622/29148338-a28318b2-7d3a-11e7-8183-82eb0edf3f12.png">

**Comment by clobber** [comment]
In general, Desmume doesn't support Pokemon games very well - this is sometimes AP patch related. You can try Desmume standalone version from their website, which has the JIT dynarec off by default which may improve compatibility, or you can read up on AP patches.

Also, please search before opening a new issue. This comes up from time to time.

**Comment by TheRealVinh** [comment]
WOAH
