### ISSUE TITLE
Playstation .cue extensions do not add games

### ISSUE THREAD

**Issue by Daplesco** [OpenEmu/OpenEmu#3303]
The first day I had downloaded Openemu, i was able to add 3 games- Ultimate Mortal Kombat 3, Driver, and Urban Chaos. It has been 3 days, and since then, I have not been able to add any Playstation One games. I can add GBA, DS, and anything else that doesn't need a .cue, but otherwise, I can't add games. I drag the .cue into the library , and it game scans, but nothing shows up. I made sure the .bin and .cue have the same names, and I followed the CD-based games guide to the letter, but it still does not work. Please help me.

**Comment by clobber** [comment]
You provided no details, so I'd just suggest searching our issues for possible solutions and also reading through the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games). Can't offer you any help beyond that.

**Comment by Daplesco** [comment]
@clobber Could you please help me? So far, you have just told me that there were no details. I provided all the details I can. I play water polo, I'm not a programmer

**Comment by clobber** [comment]
>I provided all the details I can

Is it that hard to figure out that you should probably give an example of a game that you cannot import, in great detail i.e. filename and contents of the cue sheet?

No one is entitled to special one-on-one support here, nor can anyone read your mind. There is a CD guide that covers all cases, including importing, and I do believe it says that you could possibly have a bad rip of a game or other issues. Importing cue sheets works correctly, every time, as long as everything is right on the user-end.

**Comment by Daplesco** [comment]
Medal of Honor for PSX. 
Files: MedalOfHonor.bin MedalOfHonor.cue

Cannot find contents of the cue sheet.

Thanks a lot,
@clobber

**Comment by clobber** [comment]
If there is nothing inside the .cue file, then there is no reason for the file to import.

**Comment by Daplesco** [comment]
@clobber I mean I do not know how to find the cue sheet contents

**Comment by Daplesco** [comment]
Please don't tell me "What kind of idiot are you? You can't open a cue sheet?"

I'm 14, I barely know how to find my application support for custom CounterStrikeSource skins, make it so I can understand

**Comment by clobber** [comment]
Sorry, I can't help you beyond this. I suggest tracking down other copies of the game and giving those a try.
