### ISSUE TITLE
Playstation .cue files do not work

### ISSUE THREAD

**Issue by Daplesco** [OpenEmu/OpenEmu#3304]
As I had previously mentioned, .cue files do not seem to add games to Openemu on my computer. They initiate the Game Scan sequence, but no game appears in the library. Manually inputting the game does not work either. Could you please help me find a solution? I am using OpenEmu's experimental build, latest update. I was able to add 3 games yesterday, but none today. Everything else works though, .gba, .nds, .n64, but not .cue . The .bin and .cue have the same name, and I made sure that I followed the guide to letter, dragging the .cue into the library and initiating the game scan.

**Comment by Daplesco** [comment]
@clobber I know you closed my previous case, do not close this one until we have found a solution.

**Comment by clobber** [comment]
Please don't open a new issue when you can reply in your previous. 

#3303
