### ISSUE TITLE
m3u files don't work with cue files that have other extension

### ISSUE THREAD

**Issue by vol24pl** [OpenEmu/OpenEmu#3306]
STR:

1. Take a 2 disk game.
2. name 1st cue file with extensions "CD1" : Oddworld - Abe's Exoddus (Europe) (Disc 1).CD1
3. name 2nd cue file with extension "CD2": Oddworld - Abe's Exoddus (Europe) (Disc 2).CD2
4. Create Oddworld - Abe's Exoddus (Europe).m3u
5. In m3u file write following:
> Oddworld - Abe's Exoddus (Europe) (Disc 1).CD1
> Oddworld - Abe's Exoddus (Europe) (Disc 2).CD2
6. Add m3u file to OpenEmu

Expected: Game is added to library
Result: Nothing happens

This is the way games are added to RetroPie. I don't see any reason it shouldn't be cross compatible as it's just about extension NAME and not the content itself

**Comment by clobber** [comment]
Files need to be named properly. Cue sheets are .cue.

Please don't needlessly open annoying issues like this when there is a guide.

I also don't give a damn about the stupid behavior of another piece of software compared to OpenEmu.
