### ISSUE TITLE
OpenEmu Mac cheats problem

### ISSUE THREAD

**Issue by jebediah2** [OpenEmu/OpenEmu#3308]
I'm doing the exact same thread as somebody else started in 2015 with successful solution because today the problem is back.

So basically this is for all my games, in the wheel icon in the hud, there is supposed to be a select cheat option, and I don't have it.

I downloaded the official version from openemu.org

**Comment by clobber** [comment]
Cheat code support is only available for the follow systems, as listed in the guide: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes

If they were supported for others, they'd be available as an option in the HUD bar menu.
