### ISSUE TITLE
Can't Fine EXEC.BIN and IVOICE.BIN files for Intellivision Retropie

### ISSUE THREAD

**Issue by safetychief8** [OpenEmu/OpenEmu#3309]
Can anyone tell me where to download the EXEC.BIN and IVOICE.BIN files for the Intellivision emulator in Retropie??? I can't find them anywhere.

**Comment by safetychief8** [comment]
...and ECS.BIN also

**Comment by clobber** [comment]
Ever heard of a search engine? Please don't open issues like this in our bug tracker.

Also read the [contributing guide](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) which states:
>Do not post links or refer to copyright infringing ROM download sites.
