### ISSUE TITLE
Wiimote as SNES controller does not recognize button hold controls

### ISSUE THREAD

**Issue by BenFeld** [OpenEmu/OpenEmu#3311]
I am having issues playing SNES games with my Wiimote. The emulation does not seem to recognize that a button (here Wiimote:2 or Wiimote:1) is held down. For example, in Super Mario RPG I cannot run, which makes the game at certain points unplayable. Likewise, in  DoReMi Fantasy I cannot increase the power of the bubbles.

**Comment by clobber** [comment]
I can't replicate this. Try both the guides first:

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing
