### ISSUE TITLE
OpenEmu won't open games, nothing happens!

### ISSUE THREAD

**Issue by donie333** [OpenEmu/OpenEmu#3314]
Help, suddenly my OpenEmu stopped working, I've tried deleting OpenEmu using AppZapper to delete system files, but am having no luck. When I attempt to open a game, nothing happens, the OpenEmu UI is unresponsive...

![20170831-openemu-issue](https://user-images.githubusercontent.com/31518700/29939583-9129c1fe-8e49-11e7-94ae-944af94e340d.gif)

**Comment by clobber** [comment]
You ignored the [contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) before opening a new issue, so you didn't post any required information. Nothing to go on in order to troubleshoot.

I suggest a computer restart.
