### ISSUE TITLE
Crash on launch - GenericObjError Error 0

### ISSUE THREAD

**Issue by projectk44** [OpenEmu/OpenEmu#3317]
![screen shot 2017-09-01 at 10 48 17 pm](https://user-images.githubusercontent.com/31540701/29970447-f5083e34-8f67-11e7-84f6-b0534c0932fc.png)

I get this particular error on launch, "The operation couldn't be completed."
(Foundation._GenericObjError error 0.) . 

OpenEmu was working fine for months until I started getting this error, which crashes the app on launch.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md

#3044
