### ISSUE TITLE
Nintendo Switch Pro Controller Causes Crashing

### ISSUE THREAD

**Issue by bionicpoke** [OpenEmu/OpenEmu#3320]
In Fire Emblem [E] for GBA through mGBA, switching the input type to "Switch Pro Controller" with the controller plugged in through a USB-> USB-C cable directly plugged into the controller causes the program to immediately crash. This is on the Mac version on the latest version of MacOS.

My Dualshock 4, directly plugged in, is not being recognized as an input device, so I'm really all around screwed in terms of controllers.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - Please search before opening a new issue.

#3272
