### ISSUE TITLE
Manual save state order

### ISSUE THREAD

**Issue by cvincent** [OpenEmu/OpenEmu#3321]
I'm trying to figure out how to re-order manual saves for a given game. Named save states are very useful when training for a speed run as you can quickly get back to trickier parts of a sequence to practice it. However, if I realize I needed a save state earlier in my sequence, it gets added to the top, and there doesn't seem to be a way to move it to the right position in either the library view or the context menu.

I've tried changing the order with the following methods:

1. Use the `touch` command to alter the created and modified dates on the save state files (including the `.oesavestate` bundle itself and all three files within the bundle).
2. Open the `Info.plist` file and change the `Timestamp` property.
3. Both of the above, all together (in reverse order so the `Info.plist` edit doesn't override the desired modified date).

I've also looked through the source code to see if I can figure out what to do. It feels like editing the `Info.plist` `Timestamp` property should be sufficient, but evidently it's not. Somewhere that I'm not looking, the old timestamp is being stored, as I can see it in the library view below the save state's screenshot.

Any advice? Appreciate it!

**Comment by clobber** [comment]
Yeah, just open each state file and re-save them in the order you want. Then delete the old ones you don't need anymore. That's a whole lot easier.

**Comment by cvincent** [comment]
@clobber Thanks for the pointer. That does work, but it is extremely tedious if you have a lot of save states to sort. I'd be happy to know a more direct way if at all possible (I'm technically savvy and have no problem modifying files and whatnot).

Ultimately the ability to do this directly in the GUI would be ideal. I haven't done Objective C in a while, but are there plans for such functionality in the future? Maybe I could contribute.

**Comment by clobber** [comment]
Sorry, no plans for anything like this and not interested in implementing a way to change the order. States are ordered by date and we want to keep UI clutter down to a minimum.
