### ISSUE TITLE
OpenEmu Crashes when using a plugged in Switch Pro Controller

### ISSUE THREAD

**Issue by thenbexperience** [OpenEmu/OpenEmu#3322]
It worked fine, until I did a restart.  Now OpenEmu crashes any time I have a Nintendo Switch Pro Controller even plugged into my system.  Works fine with PS4 controller.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - Please search before opening a new issue.

#3272
