### ISSUE TITLE
Hotkey for Restart System (⌘R)

### ISSUE THREAD

**Issue by maxforsyth** [OpenEmu/OpenEmu#3323]
I played a lot on Project64 for Windows, but then switched to Mac and starting playing in OpenEmu. P64 had a shortcut to restart the system, which was the F1 key. Since ⌘P pauses emulation here, could ⌘R be set to restart the system?

**Comment by azoreseuropa** [comment]
Yeah, I am agreeing with maxforsyth. It would be easier. Can you ?

**Comment by Wevah** [comment]
As a workaround, you should be able to customize the key command in Sytem Prefs -> Keyboard -> Shortcuts.

**Comment by maxforsyth** [comment]
> customize the key command in Sytem Prefs -> Keyboard -> Shortcuts

<img width="615" alt="screen shot 2017-11-19 at 8 24 44 pm" src="https://user-images.githubusercontent.com/529686/32998283-c6fd94e2-cd67-11e7-8a2c-a99af4439351.png">

So simple! Thanks, @Wevah
