### ISSUE TITLE
No longer able to add .cue files.

### ISSUE THREAD

**Issue by shinsukato** [OpenEmu/OpenEmu#3325]
Environment:
2017 Macbook Pro
Sierra 10.12.5
OpenEmu v2.0.5

To Reproduce:
1) Download OpenEmu drag to your Applications folder.
2) Attempt to import the .CUE file of disc one of a four-disc game.

<img width="726" alt="screenshot 2" src="https://user-images.githubusercontent.com/13015828/30239529-5ffcbe06-9556-11e7-9d64-280a270c2ae3.png">

3) Success! Final Fantasy 8 appears in library.
4) Attempt to create a .m3u file with the other three discs included (one .CUE file and three .CCD files)

<img width="726" alt="screenshot 2" src="https://user-images.githubusercontent.com/13015828/30239529-5ffcbe06-9556-11e7-9d64-280a270c2ae3.png">

<img width="1211" alt="screenshot 1" src="https://user-images.githubusercontent.com/13015828/30239528-5ff8c490-9556-11e7-8e64-41892f6e6881.png">

5) Delete the game from your openEmu library (leaving files untouched)
6) Drag the .m3u file into OpenEmu

Nothing.

8) Attempt to drag the original disc 1 .CUE file into OpenEmu

Nothing.

**Comment by shinsukato** [comment]
Okay, this seems to have been due to the files not being removed from Application Support folder, I can now import disc one just fine.

I still cannot import my .m3u file, is it not possible to mix .cue and .ccd?

**Comment by clobber** [comment]
The guides state the files you want to import cannot already exist in your Game Library or folder. As long as they don't, and there is also no orphaned files in 'unsorted', what you are doing should import. In your screenshot, the CCD file names don't match up with the M3U though. 

Beyond this, can't help you further.
