### ISSUE TITLE
.m3u files not importing

### ISSUE THREAD

**Issue by conchoecia** [OpenEmu/OpenEmu#3326]
Same problem as #3048, I followed the instructions for multi-discs to the T and OpenEmu isn't importing the discs. Everything is in the same directory, and this is after a fresh install after deleting `~/Library/Application Support/OpenEmu/`. I checked and each line on the `.m3u` file matches that of the `.cue` files.

**Comment by clobber** [comment]
Lacking details, sorry I can't help you with this. Follow the directions closely, make sure none of the files exist in the folders or provide more details.
