### ISSUE TITLE
m3u file not working, cue and bin files not importing

### ISSUE THREAD

**Issue by NegaScott128** [OpenEmu/OpenEmu#3327]
I have followed the directions for importing multi-disc PS1 games. I only imported the .m3u file, which is kept in the same folder as the .cue and .bin files for the game. Only the .m3u file shows up in the OpenEmu directory, not the .cue or .bin files. I even used the same text editor that the directions recommended. And yet, whenever I try to load the game, the screen stays black and I have to Force Quit the app. The only issue I can think of is that I encoded the .m3u file incorrectly, and in my defense, the directions make no mention of encoding settings. I just stuck with the default settings, which I will link below. I'll also include evidence that I followed the directions, since I've looked through some other posts and clobber always seems completely incredulous towards people who have this issue.

![screen shot 2017-09-10 at 9 58 55 am](https://user-images.githubusercontent.com/31823956/30250106-b49ab446-960e-11e7-8b83-860b2c3ffd8c.png)
<img width="592" alt="screen shot 2017-09-10 at 9 53 56 am" src="https://user-images.githubusercontent.com/31823956/30250131-0cbc7a10-960f-11e7-8ea8-93c5a3e9245f.png">
![screen shot 2017-09-10 at 9 54 07 am](https://user-images.githubusercontent.com/31823956/30250132-0cbcdadc-960f-11e7-9fa2-12e95fa8b4fe.png)
![screen shot 2017-09-10 at 9 54 17 am](https://user-images.githubusercontent.com/31823956/30250133-0cbcdfaa-960f-11e7-9839-e748978223ea.png)
![screen shot 2017-09-10 at 9 54 51 am](https://user-images.githubusercontent.com/31823956/30250130-0cbc7a74-960f-11e7-952a-60895d8e1099.png)

I have tried this with multiple games and haven't gotten any of them to work. What am I doing wrong?

**Comment by clobber** [comment]
> since I've looked through some other posts and clobber always seems completely incredulous towards people who have this issue.

Besides the few bugs I found and have fixed for next release, it's always because they did not read the directions fully and have something wrong. That's verifiable by looking at the previous issues when I troubleshot them. Sorry, I'm definitely not helping you now or others every time this "problem" comes up.
