### ISSUE TITLE
Analog stick range slider?

### ISSUE THREAD

**Issue by TheOpenWorld** [OpenEmu/OpenEmu#3330]
I need to make Mario in Super Mario 64 walk or tiptoe for machinmas, similar to what you can do with Project64.

**Comment by clobber** [comment]
Nope. Only way you can make Mario walk/tiptoe is with a proper analog gamepad.

**Comment by TheOpenWorld** [comment]
Already tried switch joycon

**Comment by clobber** [comment]
This is a problem with Nintendo gamepads (see #3102). You will have to use something else for now.
