### ISSUE TITLE
Dropping m3u file into openemu immediately crashes 

### ISSUE THREAD

**Issue by Tiaximus** [OpenEmu/OpenEmu#3331]
Attempting to load Dragon Warrior VII into openemu.

Created a folder, placed the Dragon Warrior VII (USA) Disc 1 and Disc 2 .cue and .bin files inside.

Created a simple text file (saved as .m3u) that has the following two lines inside:
Dragon Warrior VII (USA) Disc 1.cue
Dragon Warrior VII (USA) Disc 2.cue

Dragging the m3u file into openemu (or attempting to add to library via File -> Add to Library...) causes openemu to immediately crash.

I have no other files, no other games loaded into openemu.  This is a fresh download of openemu with a blank library.  Any thoughts?

**Comment by clobber** [comment]
>Any thoughts?

Post the crash log and the inside of your M3U file. This is probably a bug that is already fixed for next release.

**Comment by Tiaximus** [comment]
[Crash Log.txt](https://github.com/OpenEmu/OpenEmu/files/1294984/Crash.Log.txt)

Inside of m3u file:

Dragon Warrior VII Disc 1.cue
Dragon Warrior VII Disc 2.cue

**Comment by clobber** [comment]
Gotta use the search. Fixed for next release.

#3153
