### ISSUE TITLE
Blurry Text In-Game PSP

### ISSUE THREAD

**Issue by amannin** [OpenEmu/OpenEmu#3332]
This only started today (have been playing problem-free for weeks), to where all the in-game text for Tactics Ogre (PSP) has become blurry / unreadable. Some file somewhere must have been corrupted, or a hidden setting changed, but I can't figure out what it is or where.

[snapshot](https://imgur.com/p6NXAdZ)

I've tried re-importing the ROM and re-installing OpenEmu along with reinstalling the Cores. I've also tried experimenting with filters. None of these have worked. Also to note, when opening the game in the standalone PPSSPPDL app, it works just fine - PPSSPPDL and OpenEmu both use the same core (1.4.2).

When trying another PSP game, Final Fantasy Tactics, there are no issues. Just this game, starting today. I'm at a lost and would greatly appreciate some help and guidance.

**Comment by clobber** [comment]
We just updated our PPSSPP core plugin to 1.4.2, which is why you may now be seeing this glitch, but it is more likely a bug with PPSSPP (or our implementation) and *not* OpenEmu.

**Comment by clobber** [comment]
Not our bug. https://github.com/hrydgard/ppsspp/issues/9779

**Comment by danilobytes** [comment]
Not directly related to this game, but Final Fantasy Tactics looks a bit blurry as well. However that's because of some settings related to textures, which are discussed on the referenced issue and fixed the problem when I ran the game on PPSSPP standalone. So, will allowing edit for some options under an OpenEmu core be in consideration at some point?

**Comment by amannin** [comment]
OpenEmu so far has been an awesome experience and I am incredibly thankful for everyone's hard work, however, as **Danilobytes** mentioned, will we at some point be allowed to edit the display options for the cores, or are we locked in to the current method?

Also, as a work around, I rolled back the PPSSPP core to version 1.3, which seems to be working for now.

**Comment by dmayle1** [comment]
I am having the same issue with Tactics Ogre. How did you roll back the PPSSPP core to v 1.3?

**Comment by clobber** [comment]
https://github.com/OpenEmu/PPSSPP-Core/compare/8ded57e0802d...92f6d7a49edc

This is fixed now after merging a patch from upstream.

Restart the app and an updated PPSSPP core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for PPSSPP 1.4.2.1.
