### ISSUE TITLE
Hotkey on controller for "Special Keys" 

### ISSUE THREAD

**Issue by oskich** [OpenEmu/OpenEmu#3335]
It would be great if there was an option to set a hotkey on the controller, so that if pressed in combination with other buttons, one might for example activate "Save State" when pressing:
 Select +R    -    (Select used as hotkey)

I'm using a 8Bitdo SNES controller - which doesn't have enough keys to bind a special button. With older consoles it's fine, but with newer there are no free buttons for this...

This works perfectly in RetroArch/LibRetro: 
https://github.com/RetroPie/RetroPie-Setup/wiki/RetroArch-Configuration

**Comment by clobber** [comment]
Having combination keys would complicate the current input system and key mapping process, so not likely we will implement something like this.
