### ISSUE TITLE
Scrambled graphics on an opening screen in Ultima IV (Sega Master System) 

### ISSUE THREAD

**Issue by SRStwo** [OpenEmu/OpenEmu#3338]
This is a screen that appears following the initial animated screen. It shows a man in a robe. To see the screen you just have to wait for a while on the opening screen.

That screen renders correctly with the CrabEmu core but not the TwoMbit core. Changing the filters has no effect. I tried both CrabEmu and TwoMbit multiple times. The issue was reproduced each time with TwoMbit.

OS X El Capitan 10.11.6
Macbook Pro (Retina, 15-inch, Late 2013)
OpenEmu 2.0.5, 719-g369c3a2-Release

ROM file is UltimaIV.sms

I switched from the Intel Iris graphics to the Nvidia discreet GPU after quitting OpenEMU but the scrambling is still there. There is no difference. This suggests that it is not related to the system GPU driver.

![ultimaiv_scrambled](https://user-images.githubusercontent.com/32050132/30528744-ebb9658a-9c03-11e7-8dc8-bfd2cfa0e5c5.jpg)

![ultimaiv_correct](https://user-images.githubusercontent.com/32050132/30528902-549220b4-9c05-11e7-99b9-4638d26f2ef2.jpg)

**Comment by clobber** [comment]
Looks like a mapper bug with TwoMbit; not our bug. The only workaround, as you learned, is to just run it with the CrabEmu core plugin instead.

**Comment by SRStwo** [comment]
Unfortunately, when I tried Crab it froze shortly after I started a game. So, I'll have to test it more.

**Comment by clobber** [comment]
Genesis Plus GX will be the new (and only) SMS core in the next update, as it's still active and has the best compatibility/accuracy. This game seems to work fine with it.

**Comment by JustinAyers** [comment]
Just to let you know. The "frozen" issue was that the game was paused. I didn't realize that at the time. So, the only bug I know of so far is with that scrambled screen.
