### ISSUE TITLE
OpenEmu/ Can't open and play games os PPSSPP emulator

### ISSUE THREAD

**Issue by StarboyAsh** [OpenEmu/OpenEmu#3339]
I can't seem to play Brave Story New Traveler on my PSP emulator. I could earlier until one day when it suddenly started saying it can't communicate with helper application. I could only open my old save states and i couldn't save anymore. I tried deleting and reinstalling the cores, the application and now i can't even open my old save files and the game doesn't play. It opens into and stays on a black screen.

**Comment by clobber** [comment]
I don't have an issue loading this, so it's probably a PPSSPP regression that broke compatibility with that save state which happens. To work around this, load the game without restoring an autosave by:

* In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" when prompted to "Continue where you left off"
