### ISSUE TITLE
Input - multiple controllers, assigning which player

### ISSUE THREAD

**Issue by clobber** [OpenEmu/OpenEmu#334]
For when OE 'knows' about multiple controllers that you have mapped, we need a way to assign which controller belongs to which 'player'

Example: If you have two controllers mapped, the first will become Player 1 and the second Player 2. If you map a third controller, even if it's the only one plugged in it will still become Player 3 by default.

**Comment by fabswt** [comment]
How can we tell two identical controllers apart? I've gotten two PS4 controllers and they show up with the exact same reference in OpenEmu's options. i.e.: Sony PS4 DualShock 4 Wireless (CUH-ZCT2).

Would relying on the Bluetooth settings be an option? e.g.: one of them was renamed `PS4 Controller (White)` and the other `PS4 Controller (Blue)`. That seems likely the most convenient option in terms of UI.
