### ISSUE TITLE
SEGA SATURN - couldn't communicate with a helper application

### ISSUE THREAD

**Issue by littlecubba** [OpenEmu/OpenEmu#3341]
Doing a search for help on google did not find a thing unless the problem was with GBA or N64.

i was quite happy with YABUSE as it seemed to work a treat, but noticed that Sega Saturn side was no longer working, so wiped hdd completely and placed everything back with fresh clean files. Noticed the cores on Openemu were updated (YABUSE has gone and been replaced with Mednafen for running Sega Saturn files)

I am now getting the wonderful message

> Couldn't communicate with a helper application

Basic info (complete fresh hdd wipe so everything is back in place like new)
Running Mac Mini 2012, i5 16gb
Openemu v2.05 experimental (cores updated!!!)

Looking forward to playing Sega Saturn once more (**also looking forward to playing Panasonic 3DO**)

**Comment by clobber** [comment]
Sega Saturn support is still experimental and unsupported at this point.

**Comment by littlecubba** [comment]
Any chance of having the option of YABUSE as an option for Sega Saturn instead of Medfaden..?

**Comment by clobber** [comment]
No - there's no reason to still support Yabause. Your issue is probably user error but you provided no details as to what you are loading and how you got to that error.
