### ISSUE TITLE
OpenEmu on external HD

### ISSUE THREAD

**Issue by Aonaran** [OpenEmu/OpenEmu#3342]
Hi all.

I'm trying to have the folder "Game Library" located on my external hard disk: however, for some kind of unknown reason I'm unable to do so, as OpenEmu suddenly closes when I try to do it.

Here's all the steps I take after starting OpenEmu:

1) Preferences ----> Library
2) In "Location of the library folder", I click on "Change", select my external hard drive and then click on "Reset".

At first, OpenEmu starts doing some kind of copying: however, it crashes and closes after a few seconds. Although the "Game Library" folder is created, it's completely empty.

Suggestions on how this can be fixed?

FYI, I've a MacBook Air running Sierra.

Thanks a lot in advance for your help!

**Comment by clobber** [comment]
#3108
