### ISSUE TITLE
Problem in Zelda Majoras Mask

### ISSUE THREAD

**Issue by YiyoAhumada** [OpenEmu/OpenEmu#3344]
I got a few problems with this game. Maybe is the rom idk but i wanted to ask.  
Ive download a few roms for this game and always have a different problem. Like the cinematics dont display (For example, when i have to learn the first song that Princes zelda teaches me i see nothing so i have to do it with no vision or other example is that when I start the game, the mask that should apear at the beginning doesn't show)
But what i think is the main problem is that whenever I open the "Bombers Notebook" it NEVER shows, its black, with every rom that I have downloaded. And that, for me, is really important to complete the masks on the game. 
Can anybody give me an answer or help me. I really like OpenEmu and really want to play THIS game in particular. 

Thx in advance!

**Comment by clobber** [comment]
A Mupen64Plus GPU plugin bug.  Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)

N64 graphics will improve in a future update.
