### ISSUE TITLE
Kingdom hearts for playstation wont work

### ISSUE THREAD

**Issue by unknownacng34** [OpenEmu/OpenEmu#3345]
Hey guys. I have downloaded and followed all the steps for the BIOS folder, and other playstation games seem to be working.

But with the kingdom hearts rom, everytime I try to drop the playstation ones in - it says scanning game 1/1 then nothing happens afterwards. I cant find it in recent games or anywhere.

Anyone know why its this specific game? I've tried several roms for the same game wont work!!!

**Comment by clobber** [comment]
???

Kingdom Hearts is not a PlayStation 1 game. It is a PS2 game. We do not support PS2 games...
