### ISSUE TITLE
Dual Shock 4 Issues

### ISSUE THREAD

**Issue by Kevsousa95** [OpenEmu/OpenEmu#3346]
since the last update(2.0.5) dual shock 4 controller sometimes causes the app to crash. starting a game, opening preferences, and connecting the controller can all cause crashes. i tried both public and experimental builds with less issues on the experimental build

**Comment by clobber** [comment]
To fix your crash:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

**Comment by Kevsousa95** [comment]
working great now
