### ISSUE TITLE
OpenEmu and gun controllers

### ISSUE THREAD

**Issue by Aonaran** [OpenEmu/OpenEmu#3347]
Hi all (:

I've just downloaded Time Crisis on OpenEmu, and since it's impossible to play it with a keyboard I'm wondering whether OpenEmu supports the Namco Guncon or similar gun-controllers. Does it?

The second question is whether it's possible to play Time Crisis (and games like it) with a mouse. That said, using the mouse as pointer and to shoot as well (alternatively, and if possible, using the mouse as pointer and the keyboard to shoot). Is it possible? And if yes, how?

Thanks a lot in advance for your help and responses.

**Comment by clobber** [comment]
PS1 doesn't yet have lightgun support (via mouse). That will happen in a future update.

**Comment by Aonaran** [comment]
Hi clobber,

Thanks a lot for your response. What about lightgun support without via mouse? Is that available or not at all (I mean, is it possible to use a Namco Guncon or similar)?

**Comment by clobber** [comment]
No...that's not possible. Those only work on old CRT TV screens.

**Comment by acheronfail** [comment]
> PS1 doesn't yet have lightgun support (via mouse). That will happen in a future update.

Is there a tracking issue for this somewhere?

**Comment by clobber** [comment]
This update is available now.

Restart the app and an updated Mednafen core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for Mednafen 1.25.0

* Saturn [Stunner / Virtua Gun](https://github.com/OpenEmu/Mednafen-Core/blob/3fdb22a098f261150341f57e9302ee9329488b1e/MednafenGameCore.mm#L2885-L2912) and PS1 [Justifier](https://github.com/OpenEmu/Mednafen-Core/blob/3fdb22a098f261150341f57e9302ee9329488b1e/MednafenGameCore.mm#L2350-L2384) and [GunCon](https://github.com/OpenEmu/Mednafen-Core/blob/3fdb22a098f261150341f57e9302ee9329488b1e/MednafenGameCore.mm#L2386-L2437) supported games will automatically work via the mouse as "Player 1"
* You must restart emulation if loading your game from a previous autosave/save state for this to take effect.

Saturn Stunner / Virtua Gun games:
* Left mouse down is TRIGGER
* Right mouse down is Offscreen Shot aka RELOAD.

PS1 Justifier games:
* Left mouse down is TRIGGER
* Right mouse down is Offscreen Shot aka RELOAD
* Square/Circle is rear "auxiliary" button
* Cross/Triangle/Start is START button

PS1 GunCon games:
* Left mouse down is TRIGGER
* Right mouse down is Offscreen Shot aka RELOAD
* Square/Circle is "A" button
* Cross/Triangle/Start is "B" button
