### ISSUE TITLE
.iso

### ISSUE THREAD

**Issue by Nyehhhh** [OpenEmu/OpenEmu#3348]
So I have been trying to run .iso games on openemu.  Openemu simply doesn't seem to find the games inside of them. I am using a mac and got the emulators off [removed].

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - 

"Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."
