### ISSUE TITLE
Getting compile error when trying to build OpenEmu

### ISSUE THREAD

**Issue by heyitsjames** [OpenEmu/OpenEmu#3350]
Warning: Erlang and Elixir dev trying to play Mac app OSS contributor and failing hardcore!

Environment:
OpenEmu version: 2.0.5
Xcode Version: 8.2.11

Previous steps before attempting to build in Xcode:
`git clone --recursive https://github.com/OpenEmu/OpenEmu.git`
`Opened the project up in xcode`

I'm attempting to debug an controller mapping bug I'm getting while using the Raphnet 2-player N64 to USB adapter, v3. I'd love to contribute to this project and see if I can't get a solution PR up, but I'm having trouble compiling the application. Here's my error:

`check dependencies`
```
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

If I actually follow the directions by doing `[Edit > Convert > To Current Swift Syntax…]`, then I get 39 errors, all Swift compilation errors.

I guess what I'm asking is, are there docs on how to compile/build this thing for development? I have seen the compiling from source docs, but that seems to be for compiling a full `.app`, not building for development. I'd love to contribute, so if someone could point me in the right direction, that'd be great.

**Comment by robotoad** [comment]
As indicated in the compilation guide, you need to be using the latest version of Xcode to compile OpenEmu, which is version 9 as of this post. The guide is intended for developers and should be enough to get you started.

**Comment by clobber** [comment]
>I'm attempting to debug an controller mapping bug I'm getting while using the Raphnet 2-player N64 to USB adapter, v3

Just an FYI, the issues with adapters is happening with all multi-port adapters. You will likely be debugging code in [OpenEmu-SDK](https://github.com/OpenEmu/OpenEmu-SDK/) since that's where input code lives. You can read more about the general problem here: https://github.com/OpenEmu/OpenEmu/pull/3241#issuecomment-331573809
