### ISSUE TITLE
Final Fantasy VII (PSX) Aspect Ratio

### ISSUE THREAD

**Issue by ClayTheTurtle** [OpenEmu/OpenEmu#3353]
Hello again. It's me, that guy who (successfully) badgered the dev team about the appearance of pixels some time back (https://github.com/OpenEmu/OpenEmu/issues/732), and I've returned with more visual pedantry.

I've recently used the PlayStation emulation in Open Emu for the first time. In the past, I've preferred to play PS1-era games on my PSVita, but now that I own a proper MacBook, I was considering using the bigger, but still plenty portable, avenue for my RPG adventures.

However, for Final Fantasy VII specifically, I've noticed that everything seems squashed horizontally. I know Open Emu forces a 4:3 ratio for all its "home console" emulators—which is a move I applaud. I'm not suggesting that pixels should be 100% square or that Open Emu needs a "wide screen" mode. But I think it's pretty clear from looking at the menu that this is not how Cloud's portrait (or the text) should be displayed.

![screen shot 2017-09-29 at 7 12 13 pm](https://user-images.githubusercontent.com/5414296/31040327-bdd9f5de-a54b-11e7-82a9-881a36f717e6.png)

It's been a long time since I've played on the original PS1 hardware, but I have played it on PS2, PS3, and PS Vita, and every time Sony uses a much wider presentation. Something closer to this.

![ffvii_item_menu_1](https://user-images.githubusercontent.com/5414296/31040338-e1a1ed0a-a54b-11e7-9dd0-068f038ad957.png)

In addition, for the recent PC re-release, Square Enix has opted for a similar aspect ratio. To clarify, the new release is NOT widescreen in any way.

![maxresdefault](https://user-images.githubusercontent.com/5414296/31040340-e76f4520-a54b-11e7-9d12-6c05f4871937.jpg)

Now, I'm not sure if this is true of all PSX games, or if it's an issue unique to FFVII, but considering two separate companies (Sony with its official emulation and Square-Enix with its modern port) have opted for the wider ratio, I think it's not offbase to suggest that the ratio Open Emu defaults to is wrong for this game, if not all PSX games. Is this something that can be fixed, or at least commented upon by someone with more intimate knowledge of how the PS1 is SUPPOSED to output graphics?

**Comment by clobber** [comment]
We don't modify the output of the pixels in any way. We return the dimensions directly from the emulator core, whom the [author of Mednafen has calculated](https://forum.fobby.net/index.php?t=msg&goto=3778&) what should be the precise aspect ratio as scene on a real CRT based on the [dot clock rate](https://pineight.com/mw/index.php?title=Dot_clock_rates). I noticed you're not playing the game in an integer scale from the popout window, which could effect it a bit. Beyond that, I suggest you compare a screenshot of Mednafen standalone to a screenshot from OpenEmu, both at the exact integer scales, and see how they look. I did that in the past and saw no difference, i.e. they matched exactly.

**Comment by ClayTheTurtle** [comment]
Fair enough. It's not impossible that Sony gets it wrong™ with their own emulation, and maybe my eyes just see it as squished from years of seeing Sony's interpretation of how a PS1 game should look. I just thought it was worth mentioning how the "official" emulation handles it. I would've provided proper screenshots, but Sony, in all their wisdom, DISABLES SCREENSHOTS while emulating PS1 games.

I would defer to the guy who actually researched it.

**Comment by FenaPhoenix** [comment]
It's 100% squished, a quick google of an original psx screenshot can show you that

**Comment by FenaPhoenix** [comment]
(I know this is an old thread btw, before someone who thinks they're clever comments about it) <3
