### ISSUE TITLE
OpenEmu PSP emulator stuck during loading screen

### ISSUE THREAD

**Issue by JianDaGe** [OpenEmu/OpenEmu#3354]
Whenever I reach a loading screen in a game, the PSP emulator gets stuck on the screen, showing the loading screen but never progressing forward. Even when I fast forward it remains stuck on the screen.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..."

**Comment by JianDaGe** [comment]
I am using a Macbook Pro Os X El Capitan Version 10.11.16.

My OpenEmu is currently the 2.0.5 version.

The isos I have been attempting to utilise are the ones found in the following links:
https://www.emuparadise.me/PSP_ISOs/PhotoKano_(Japan)/158923
https://www.emuparadise.me/PSP_ISOs/Amagami_(Japan)/159048

While the emulator does not crash when I run both of these isos, they do get stuck when I reach a certain point early in the game in the case of the former, and on the very first screen in the case of the latter.

**Comment by clobber** [comment]
I can't replicate this. I tried Amagami and am able to get in-game, past the first screen:

<img width="942" alt="screen shot 2017-10-03 at 4 06 02 pm" src="https://user-images.githubusercontent.com/1303132/31149344-3b5abb54-a855-11e7-805f-37838dc2f348.png">

<img width="942" alt="screen shot 2017-10-03 at 4 07 46 pm" src="https://user-images.githubusercontent.com/1303132/31149352-42966652-a855-11e7-8587-46b71be7cbb2.png">

<img width="942" alt="screen shot 2017-10-03 at 4 07 57 pm" src="https://user-images.githubusercontent.com/1303132/31149358-4687d1ba-a855-11e7-8990-906d202ce454.png">

Make sure you are using the latest release of the PPSSPP core plugin (check OpenEmu > Preferences > Cores) which should be version 1.4.2. It's possible there is a bug/regression from PPSSPP upstream or that save state compatibility broke, so try loading the game without restoring an autosave by:

* In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" when prompted to "Continue where you left off"

**Comment by JianDaGe** [comment]
I've done everything exactly as you requested. The PSSPP core plugin is 1.4.2 and even after resetting the warnings and opening the game again I'm still stuck on the opening screen.

Is there any other data I can provide to help find a solution?
