### ISSUE TITLE
populous 2- trial of the olympian gods control problem

### ISSUE THREAD

**Issue by greengamerUSSR** [OpenEmu/OpenEmu#3355]
for some reason, when i play this game, it uses my mouse to control the game, but in all the other footage i saw of this game they are using the controller, is this normal? it's not really annoying to play with the mouse, it's just that the in-game cursor is not in sync with my mouse.

**Comment by clobber** [comment]
Using the Snes9x core plugin, that game is set to only use the 'SNES Mouse' and might not be perfect. To play that game with gamepad-only, switch the core plugin to Higan (while running the game, go to the HUD menu, click the cog wheel, select Higan).
