### ISSUE TITLE
SNES: Disable mouse control?

### ISSUE THREAD

**Issue by nebulousecho** [OpenEmu/OpenEmu#3356]
I tried playing _Civilization_ for the SNES in Open Emu and was surprised to find that my trackpad controlled the in-game cursor. I didn't realize that the game must have supported the SNES Mouse. Problem is, my system mouse cursor and the in-game cursor don't share the same position on screen, so it is very awkward to control.

I'm sure I'm not describing the problem very well, but ultimately what I'm trying to ask is if there's any way to disable SNES Mouse support so I can go back to using my keyboard or a game pad to play?

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/3355#issuecomment-333583617
