### ISSUE TITLE
Mayflash N64 Adapter Controller Problems

### ISSUE THREAD

**Issue by SoloKeita** [OpenEmu/OpenEmu#3357]
So I recently purchased a [Mayflash for PC USB adapter](http://www.mayflash.com/Products/N64SNESSS/PC043.html) for Nintendo 64 (N64) controllers but Port 1 doesn't work in OpenEmu.  However, both ports work in Sixtyforce on the same machine so I know it's not a hardware problem.  It looks like it was mentioned before [here](https://github.com/OpenEmu/OpenEmu/issues/2800) and [here](https://github.com/OpenEmu/OpenEmu/issues/2988) but never had a solution and the author said it doesn't work because it is a Mac but that can't be true since it works with Sixtyforce on Macs.

Does anyone have any insight on why this is happening?  Or maybe a short term fix?  Or who to talk to about fixing it long term?

Mac OS: 10.12.6
OpenEmu: v2.0.5

**Comment by clobber** [comment]
Please don't open duplicate issues for attention. The problem with multi port adapters is well-documented. 

#2988
