### ISSUE TITLE
PSX Game Issues

### ISSUE THREAD

**Issue by JanHeart01** [OpenEmu/OpenEmu#3358]
Hello. I wasn't sure if I should ask here, but I started using OpenEmu to play retro games, and I recently started playing Jersey Devil. What caught my attention is there's slight gameplay issues and subtle sound problems. When I started the game, it was normal but the character I control suddenly stops moving a few times. He jumps and does other things, but during those times he just stops running. These moments are very brief for I can quickly regain control, but I am concerned it could get worse if I continue playing. I thought it was my controller but the batteries weren't the issue. I adjusted the controls before playing, so I don't understand why he just stops.

As for the audio, it starts off fine but it stutters at some points, and I don't know what is causing the problem. It got more noticeable as I continued playing. I have yet to see if this affects other games.

My Mac OS X El Capitan, 10.11.6, and all the updates have been made. Is there any way to fix these problems? Is it the game itself? My computer? The PSX core? The BIOs?

**Comment by clobber** [comment]
I cannot replicate any of these issues on macOS 10.13.1 using my wireless PS4 DualShock 4. I ran around the hub world and first mission, testing both d-pad and analog control modes. It's worth noting that Mednafen's PS1 module is very CPU intensive, so if you are experiencing intermittent slowdown it could be attributed to your machine not being fast enough to run it at full speed.
