### ISSUE TITLE
Removal of Redrode Code

### ISSUE THREAD

**Issue by jphastings** [OpenEmu/OpenEmu#3364]
Hi folks, I see that [Retrode ROM support was removed](https://github.com/OpenEmu/OpenEmu/commit/08b91a80647292f8cf3993bef6aa63370d3c31ba) back in 2015. What was the reason for this? Is support for loading savestates directly from the Retrode still planned [as described in your notes](https://github.com/OpenEmu/OpenEmu/wiki/Next-Version#retrode-later)?

Thanks!

**Comment by clobber** [comment]
That was work in progress code that wasn't finished. Sorry, there's no plans for future Retrode support.

**Comment by jphastings** [comment]
That's a great shame, but so be it! Thanks for the prompt reply :)
