### ISSUE TITLE
Don't Know Where to find past save files

### ISSUE THREAD

**Issue by Kevin1327** [OpenEmu/OpenEmu#3366]
I was playing a game, and hadn't created any save states. I accidentally reset the game somehow. Then I loaded up the game again and then accidentally overwrote the save file by starting a new game, or it didn't save when I told it to. I was wondering if there was a way to get that past save back. I've looked for the file, but my Application Support Folder doesn't have an openemu folder in it.

**Comment by clobber** [comment]
No that isn’t possible. It’s already been overwritten.
