### ISSUE TITLE
PlayStation BIOS Files Deleted

### ISSUE THREAD

**Issue by Knight-Yoshi** [OpenEmu/OpenEmu#3367]
I added SCPH5501 (and 5502) bin file to the BIOS directory. However, when attempting to run the game after that the BIOS are deleted(?) and it throws an alert that says the aforementioned BIOS are required.

**Comment by Knight-Yoshi** [comment]
![bios-deleted](https://user-images.githubusercontent.com/6134576/31643999-987d0988-b2c1-11e7-878d-0b469479f6b7.gif)

**Comment by clobber** [comment]
It's obvious from the [BIOS guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files) that not only do you have the incorrect files but you are not importing them properly. Why not just read the guide first before opening a new issue?
