### ISSUE TITLE
UI enhancement : grid view to show two lines instead of "…" + region flag

### ISSUE THREAD

**Issue by Yohmi** [OpenEmu/OpenEmu#3368]
Hi,

Since I'm using OpenEmu, there's always been something off about the grid view.
It's quite simple, most games, unless you decide to have big artworks and in full screen, aren't fully displayed. They're truncated, with "…". I think it'd be great if there was basically a second line to continue (and finish) the name of the game.

The other idea is about flags. Roms can come in various editions, and when you see how, for example in the 16 bits era, it can impact gameplay (with 50 and 60 Hz depending on your region), I guess many people get different roms of the same game. It'd be great to have some sort of flag to distinguish U, E, J roms in the grid view (like, at the end of the name, or in the corner of the artwork…).

I hope these ideas will make sense 🙂 

Thanks for you hard work 😃

**Comment by clobber** [comment]
>They're truncated, with "…". I think it'd be great if there was basically a second line to continue (and finish) the name of the game.

That will end up looking worse than with the ellipsis.

>It'd be great to have some sort of flag to distinguish U, E, J roms in the grid view

That's what the different regional cover art is for. Otherwise, you can simply rename the games you want yourself or put them in various collections.

**Comment by clobber** [comment]
Also please search before opening a new issue. Dupe #1015
