### ISSUE TITLE
Build failed; check dependencies

### ISSUE THREAD

**Issue by scottdcrompton** [OpenEmu/OpenEmu#3370]
Attempting to compile experimental build; Build failed check dependencies

 /bin/sh -c \"/Users/scottcrompton/Library/Developer/Xcode/DerivedData/OpenEmu-hchsgglgoiictcfutfkggldohjmt/Build/Intermediates/MAME.build/Release/Build\ &\ Install\ MAME.build/Script-D0AADE2D1763815000759E26.sh\"

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
Scotts-MBP:openemu scottcrompton$

**Comment by clobber** [comment]
Issues regarding Arcade/MAME are unsupported since it's still experimental, but it looks like a script needs to be run manually first...I bet there's a hint in the repo.

**Comment by scottdcrompton** [comment]
I ran the Script inside the Scripts folder but I'm unsure as to what other script you are referring to.
