### ISSUE TITLE
Classic Controller not connecting

### ISSUE THREAD

**Issue by KirbyTheMemeMan** [OpenEmu/OpenEmu#3372]
So I updated my mac from 10.11 to 10.13 for this emulator and I want to play with a classic controller + wiimote but it doesn't connect and just uses the keyboard to control the game, I've tested this on ps1 snes and nes and it's the same result, the keyboard is the controller instead of the classic controller, please help!

**Comment by clobber** [comment]
[input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) and [wii remote pairing](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing) guides 

Classic Controller attachment is not supported. There is no fix for this as of now.
Similar enough to #2371
