### ISSUE TITLE
Swift Lanaguage Verison Error on Compile

### ISSUE THREAD

**Issue by scottcrompton** [OpenEmu/OpenEmu#3373]
Build fails with following:

“Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by clobber** [comment]
Mmm nope. OpenEmu compiles fine via the [guide](https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide) and using the latest Xcode (9.0.1 as of writing).
