### ISSUE TITLE
Why can't i clone the repo to my desktop?

### ISSUE THREAD

**Issue by Macsorzist67** [OpenEmu/OpenEmu#3375]
I always get a "permission denied" error. What can i do?

**Comment by PokeCaptain** [comment]
Read the wiki

https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide

**Comment by Macsorzist67** [comment]
I did and i have a ssh key signed to my account. but all i get is the same message:
![bildschirmfoto 2017-10-21 um 16 39 55](https://user-images.githubusercontent.com/32854648/31852810-deb0d36a-b67e-11e7-943d-53bb9b9247b6.png)

**Comment by clobber** [comment]
Not an OpenEmu issue. Reading the wiki and adding the ssh key is the right answer. Otherwise try the GitHub desktop app.
