### ISSUE TITLE
PS4 controller not properly working

### ISSUE THREAD

**Issue by AncientSongline** [OpenEmu/OpenEmu#3376]
Hi there. 
I'm using a PS4 controller and it works all fine when I'm playing, for example, on the GBA emulator, but even though I can map it in the settings, meaning that Openemu gets the inputs from the controller, it won't work on the PS1 (PSX) emulator. 
Any clue about it?

**Comment by clobber** [comment]
There isn't any reason why it'd work with one system in OpenEmu and not another. Which game?

**Comment by AncientSongline** [comment]
Castlevania Simphony of the Night.

Should I try with another game?

**Comment by clobber** [comment]
Works just fine here with that game and the DS4 controller. Try here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
