### ISSUE TITLE
Cant import my game into the psx emulator.

### ISSUE THREAD

**Issue by SkyMac35** [OpenEmu/OpenEmu#3379]
I have a .sub .ccd and a .img file for Spyro Year of the dragon and nothing I do works on importing the game. Is there somthing else I need?

**Comment by clobber** [comment]
As long as all the files are all named the same and the file extensions (.ccd/.img/.sub) are lowercase, you simply drag and drop in the .ccd file to import your game.

A few possible issues are:
* The files you want to import already exist in your Game Library folder.
* You have orphaned files in 'unsorted'.

There are a few CD import edge cases in 2.0.5 that are already fixed for next release.
