### ISSUE TITLE
trouble with spicific sega saturn games

### ISSUE THREAD

**Issue by Pixel0501** [OpenEmu/OpenEmu#3381]
I am trying to add the game "Gale Racer" for Sega Saturn. I have all the bios installed and I have a bin cue file with militple tracks, but it dosent reconize the rom. Help would be greatly appreasated!

**Comment by clobber** [comment]
Lacking details. Have you read the [CD guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) first? All one needs to do is import the cue sheet file.

**Comment by Pixel0501** [comment]
When I drag the cue file into openemu, it doesnt do anything.

**Comment by clobber** [comment]
List all the filenames including the contents of the cue sheet.

**Comment by clobber** [comment]
Closing for lack of info.
