### ISSUE TITLE
F310 OpenEmu issue

### ISSUE THREAD

**Issue by p1gBn1s** [OpenEmu/OpenEmu#3382]
Hi, I’ve been recently playing the Final Fantasy 7 on OpenEmu using a Logitech F310 controller without any issues whatsoever. During game play I selected the option at the bottom of the screen to “Edit Game Controls”. I was curious to see if there were any turbo button mapping options. While I was in game control options I remapped my controller successfully and after discovering no turbo button mapping options I returned to play the game. Now my controller does not respond. I did set he quick save to my square button since that button is not really used in the part the game I am in and I hit the button to test it out. It did register and quick saved my game. When I go back and open one of my very old save states the controller responds normally to the game, but when I reload my current session again no responsiveness from the game on that save. I have tried resetting the console resetting OpenEmu disconnecting and reconnecting the controller and remapping it several times with the same results. I can use it on other save files, but not the one I want to play. Any suggestions? Thanks

**Comment by clobber** [comment]
I'm not sure I'm following you:

First:
>Now my controller does not respond.

and then:
>  I did set he quick save to my square button since that button is not really used in the part the game I am in and I hit the button to test it out. It did register and quick saved my game.

So it doesn't work but it *does* work? Also I don't understand how one save state could respond to input but the other does not. The save state files hold no information about gamepad bindings from the frontend. What you're describing can't happen. All I can think of is maybe you pressed the 'Analog Mode' toggle that may effect input in certain games, or there is an emulator bug with your particular state file. Unfortunately, it doesn't really sound like an OpenEmu bug though.

Give this guide a try first to see if anything applies: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
