### ISSUE TITLE
Clearing a binding does not get saved in some cases

### ISSUE THREAD

**Issue by chasetopher** [OpenEmu/OpenEmu#3383]
Hello, I'm on the latest version of OpenEmu (2.0.5)

Steps to reproduce:
1. Open Preferences, go to Controls
1. "Clear" a binding by clicking it and pressing ESC
1. Close Preferences, quit OpenEmu
1. Reopen OpenEmu and go to Controls, the binding is still there

Expected result:
Upon reopening OpenEmu, the binding should still be cleared.

I was able to fix my problem by not only clearing a binding, but either adding or changing another binding. In that case, the bindings were saved, along with the cleared one. But it appears that if you do nothing but clear bindings and don't add or change any, the changes will not be saved upon closing OpenEmu.

Thanks, I really enjoy OpenEmu!

**Comment by clobber** [comment]
I can replicate this. Thank you very much for including steps.
