### ISSUE TITLE
It doesn't work with the new version of Mac

### ISSUE THREAD

**Issue by CR-Rojas14** [OpenEmu/OpenEmu#3384]
When I updated my macbook to MacOs High Sierra (10.13.1) it stopped working

**Comment by clobber** [comment]
Could you be less vague and more specific, please? Is there a crash log?

**Comment by Namouk** [comment]
@clobber Both versions (regular and experimental) work perfectly on 10.13.1

**Comment by clobber** [comment]
@Namouk Right. There is normally no problem but they may be experiencing a specific crash that happens under some circumstances.

**Comment by CR-Rojas14** [comment]
I Don't know if you could call it a crash log but it doesn't even open for me

**Comment by CR-Rojas14** [comment]
[Open Emu problems.txt](https://github.com/OpenEmu/OpenEmu/files/1443718/Open.Emu.problems.txt)

**Comment by CR-Rojas14** [comment]
That's what I could get from the report in my Mac

**Comment by clobber** [comment]
You need to be using OpenEmu 2.0.5, download it here: https://github.com/OpenEmu/OpenEmu/releases/download/v2.0.5/OpenEmu_2.0.5.zip

#2851
