### ISSUE TITLE
Will you support the nes/snes classic controllers proxied through a wiimote?

### ISSUE THREAD

**Issue by rjcarr** [OpenEmu/OpenEmu#3385]
I just plugged in an snes classic controller into a wiimote and expected it to "just work", as I'm fairly sure I've plugged in one of the wii classic controllers and it worked fine, but using the snes classic controller didn't register any button presses, but the wiimote itself was working fine.

Just curious if it is on the radar, or maybe even a hint where to look to add the support myself?

**Comment by clobber** [comment]
Classic Controller attachment is not supported. There is no fix for this as of now.

Similar enough to #2371
