### ISSUE TITLE
It crashed everytime I try to open a game

### ISSUE THREAD

**Issue by Clodmachine** [OpenEmu/OpenEmu#3386]
plz help title says it all

**Comment by clobber** [comment]
>plz help title says it all

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..." and "Include Console and crash logs, macOS and OpenEmu version, hardware information, ROM/game filenames, etc."

**Comment by Perm1990** [comment]
I have same problem - direct crash after start.
I tried to rename the OpenEmu directory in ApplicationSupport but without improvement.

[crashreport.txt](https://github.com/OpenEmu/OpenEmu/files/1445006/crashreport.txt)

Using latest 2.0.5 version of OpenEmu.

I installed yesterday the the Apple Security update for El Capitan.

**Comment by clobber** [comment]
@Perm1990 Your issue is #3108 and already fixed for next release.

**Comment by Perm1990** [comment]
Hi. When we may expect this next release? :)
