### ISSUE TITLE
Keyboard problems - OpenEmu is logging events, but not using them. Troubleshooting page exhausted

### ISSUE THREAD

**Issue by msikma** [OpenEmu/OpenEmu#3388]
First of all, I'm sorry to make a topic about keyboard problems. I know there are a lot of them. I don't seem to be able to figure out how to resolve this, though.

I've gone through the [troubleshooting page](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting%3A-Input-problems), but nothing seems to help. I've closed all the software listed, and although I used to have Karabiner Elements installed, I've uninstalled it completely. I'm running this off a Macbook Pro without external devices connected, and I have restarted before trying.

Here's [the log](https://gist.githubusercontent.com/msikma/611489516d8e1075271e86d1d983648d/raw/9a92856db21ad87421e924b89dca1d60a0c5540f/keyboard-log-openemu.txt) of me starting OpenEmu, running a game, pressing some buttons (you can see the keyboard events in the log) and then shutting down. The input has no effect in-game. There is no difference based on core or game. I can change the key configuration in the settings just fine.

Strangely enough, it used to work. But I haven't used it in a while because I've been busy, so I'm not 100% sure where I made a mistake and broke it.

System: MacBook Pro (Retina, 13-inch, Early 2015), Mac OS X 10.12.6

I'm hoping there's something I can still try or check. I've attempted to use other versions of OpenEmu, including the latest experimental and a few stable older versions, but none work.

**Comment by clobber** [comment]
Hrm well this isn't really an OpenEmu issue since it has to be some other app or process interfering. You said you restarted but I'd also make sure no other apps are running to see if any are the culprit. Also run `kextstat | grep -v com.apple` in Terminal to see if any non-Apple kernel extensions are installed. Some could be a problem.

**Comment by msikma** [comment]
Thanks for your help. It's weird that it's logging the events but not doing anything, though, e.g.:

    <OEHIDEvent 0x608000299f00 pad=0x0 type=Key number=80 state=On '←' cookie=0>

Running `kextstat | grep -v com.apple` yields the following:

https://gist.githubusercontent.com/msikma/23f556deac6d0a586c305b6e23495109/raw/d50f1ebebdb55b77660e411180be8ea311c79625/kexts.txt

The `com.logitech.driver.LogiGamingMouseFilter` and `com.driver.LogJoystick` looked suspicious, but unloading them doesn't change anything. Could be VirtualBox or VMWare, but then I have had those installed for much longer than OpenEmu and it did work in the past.

I was thinking maybe OpenEmu was somehow linked to a different keyboard (since normally I work with an external keyboard plugged in) but that doesn't seem to be the case either.

**Comment by clobber** [comment]
Try the following:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

**Comment by msikma** [comment]
Unfortunately, it's no go. That didn't change anything.

I'm sure it's my mistake somehow. There's something wrong with my settings. I'll have to do more research, maybe when I figure out what it is that's causing this I can make a new issue. Unless you have any other tricks I can try.

**Comment by msikma** [comment]
I've since formatted my PC (mostly for other reasons, I wanted to do a nice clean up). So as of right now I no longer have the ability to debug this. Still no idea what the problem was. I'll just close this for now. Maybe if it ever happens again I'll be able to retrace my steps more accurately.

**Comment by ttww** [comment]
Hi,
I have the same problem. After I had the problem with the pre compiled OpenEmu.app I downloaded the current git version and compiled it with Xcode under 10.15 Beta (19A536g) Catalina. Same behaviour.
I've also gone through the troubleshooting page, but nothing seems to help.

My kextstat
> kextstat | grep -v com.apple
> Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
>   154    0 0xffffff7f845b1000 0x4000     0x4000     com.intel.driver.EnergyDriver (3.5.5) 80256914-DED1-317B-9311-300A286F8072 <8 6 5 3>
>   179    0 0xffffff7f8484b000 0x184000   0x184000   at.obdev.nke.LittleSnitch (5422) 509CF51B-5610-3C03-A651-5FA527B6E52B <8 6 5 3 1>
>   188    0 0xffffff7f85ad1000 0x6000     0x6000     com.getdropbox.dropbox.kext (1.10.3) F29DD0CB-48D6-311A-9B69-E39CF775493C <8 6 5 2 1>

Should we reopen this error?
Any tips for bug hunting?
I'm new to this project and don't know where to start with logging/debugging :-)

Thanks for help :-)
