### ISSUE TITLE
macOS Sierra Keyboard Control not Working

### ISSUE THREAD

**Issue by Timbo11** [OpenEmu/OpenEmu#3390]
I am trying to play any game on my newer model of the macbook that was purchased this year (August, 2017). And I am not able to get my controls to work on my keyboard. I checked the bindings and they were correct, but i wasn't even able to change them. And they are still not responding. My touchpad is working fine.

**Comment by clobber** [comment]
Please read the [contributing guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems) and also use the search before opening a new issue. I counted and there are at least 60 duplicate issues of this.

**Comment by Timbo11** [comment]
Where do I find these
