### ISSUE TITLE
Rom Won't load error

### ISSUE THREAD

**Issue by CaseyDizzy** [OpenEmu/OpenEmu#3391]
Hello, 
you helped out pretty well with the m3u issue I had I forgot to put the .bin in the text file.

onto the new issue, I downloaded a rom from 2 places, both multi disk games, but I got the same one from different places, getting the same error "The emulator could not load the ROM"

console app shows two errors when this happens:

AEGetDescData of non-desc type 'reco' not a good idea

and

Scheduling the NSURLDownload loader is no longer supported.

I'm running High Sierra if that helps any.

Edit: games are wild arms 2 and xenogears.

**Comment by clobber** [comment]
>you helped out pretty well with the m3u issue I had I forgot to put the .bin in the text file.

Right, you said you [followed the guide](https://github.com/OpenEmu/OpenEmu/issues/3389#issue-271997218) before when you actually didn't, so I have no reason to believe you are this time.

>I downloaded a rom from 2 places, both multi disk games, but I got the same one from different places

Sounds like a bad dump of the game. Download them elsewhere.

**Comment by CaseyDizzy** [comment]
I made a mistake and let you know I appriciated your help. No reason to be
a dick about it either. I did try difference places. So that may not be it.
As I also just updated macOS and thought there may be a complication with
that.

I’m nit going to pretend I know everything. But I do know you don’t have to
be a condescending dick about it.
