### ISSUE TITLE
special key - fast forward - unpauses game (incompletely)

### ISSUE THREAD

**Issue by grimreaper** [OpenEmu/OpenEmu#3392]
# Steps to Reproduce:

1. Open game (core and game don't matter; reproduced on PSX game)
2. Press `pause`
3. Press `fast-forward`

# Expected Behavior

- Input is ignored.
- Game remains paused
- Play/Pause button in HUD functions as normal

# Observed behavior
- Game is unpaused
- Play/Pause button on HUD remains in "paused" mode (shows the 'play' button)
- Pressing `pause` changes the P/P button in the HUD to show as 'pause' but does not change game state
- Pressing `pause` twice fixes the HUD button and all else reacts as expected.

# Additional Information
macOS 10.13.2
OpenEmu 2.0.5

**Comment by shysaur** [comment]
I found this bug a while ago; it is fixed for the next release (see [pull request 17 on OpenEmu/OpenEmu-SDK](https://github.com/OpenEmu/OpenEmu-SDK/pull/17)).

**Comment by clobber** [comment]
Ah, yep. Thanks for pointing that out. This reminded me of other problems with global special keys, for example #1279, but that one can probably be fixed in OEGameDocument.

**Comment by grimreaper** [comment]
Thanks for pointing that out. I am looking forward to the next release.
