### ISSUE TITLE
Opening a PS1 game gives sound but no visuals.

### ISSUE THREAD

**Issue by TheSquishyMage** [OpenEmu/OpenEmu#3397]
Whenever i open a ps1 game i get no screen but i do get the audio. i used this video to set up the game bios https://www.youtube.com/watch?annotation_id=annotation_2626319765&feature=iv&src_vid=4ncTG2Vq8bQ&v=6z2Aa3lrDmM .

**Comment by clobber** [comment]
Which version of OpenEmu? Which game?

>i used this video

That video is incorrect. The official [BIOS guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files) should only be followed.
