### ISSUE TITLE
Pokemon games for GBA

### ISSUE THREAD

**Issue by mckmkdmk** [OpenEmu/OpenEmu#3399]
I try to put cheats with the "+" symbol and without it too and it doesn't work, I am trying to use modifier cheats and is not working, I try with gameshark, superheats and etc... and is not working, is there a way to make It work with every cheat?

**Comment by clobber** [comment]
Follow the guide to learn how to find working cheats, how to use them and specifically what works for GBA: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes
