### ISSUE TITLE
Error with OEImportFatalDomain Code=3??

### ISSUE THREAD

**Issue by aeolusluck** [OpenEmu/OpenEmu#3402]
I have three Sega Saturn games, when I import them into the openEmu, 2 of them are imported successfully, but only one can't be imported successfully. Here is the imported error log
**first one was error**
```
20:30:13.975466 +0800	OpenEmu	Claim 69C0EC52-B3EE-4A00-BFEB-47DB6299CC28 granted in client
20:30:13.975494 +0800	OpenEmu	Claim 69C0EC52-B3EE-4A00-BFEB-47DB6299CC28 invoked in client
20:30:13.980135 +0800	OpenEmu	Error Domain=OEImportFatalDomain Code=3 "(null)"
```
others succeed

```
20:30:31.725838 +0800	OpenEmu	Claim E940C2D0-BF43-4AE0-8425-40C99FC6F685 granted in client
20:30:31.725866 +0800	OpenEmu	Claim E940C2D0-BF43-4AE0-8425-40C99FC6F685 invoked in client
20:30:32.517228 +0800	OpenEmu	''
20:30:32.517329 +0800	OpenEmu	''
20:30:32.517383 +0800	OpenEmu	'SEGA SEGASATURN '
20:30:46.997462 +0800	OpenEmu	Claim BAE47FAD-AFDC-402F-9BE2-349E76C72487 granted in client
20:30:46.997493 +0800	OpenEmu	Claim BAE47FAD-AFDC-402F-9BE2-349E76C72487 invoked in client
20:30:49.226641 +0800	OpenEmu	''
20:30:49.226761 +0800	OpenEmu	''
20:30:49.226815 +0800	OpenEmu	'SEGA SEGASATURN '

```

what does mean about this error message??

**Comment by clobber** [comment]
No system was detected for it. That means either the cue sheet is wrong or it's missing its header and cannot be identified, making it a bad dump.

**Comment by alexeigladyshev** [comment]
How do I unsubscribe from e-mail like these about the OpenEmu?? I
unsubscribed from the page on Github, yet receive lots of these emails
every day!

Please tell me what I need to do to make it stop!

Thanks,

Alex
