### ISSUE TITLE
ROM file could not be found

### ISSUE THREAD

**Issue by owain63** [OpenEmu/OpenEmu#3403]
Hi,

When I try to run Jonah Lomu Rugby on Open Emu on Playstation emulator, I get the following error message...
<img width="832" alt="screen shot 2017-11-17 at 23 16 47" src="https://user-images.githubusercontent.com/33757010/32954445-15d0bdb8-cbee-11e7-9a57-b146736545fb.png">

Can anyone help with this please?

Thank you in advance!

**Comment by clobber** [comment]
That message is self explanatory. It cannot find the files in your Game Library; you either manually moved or deleted them from the folder.
