### ISSUE TITLE
Add in a preference to deactivate Bluetooth controller discovery

### ISSUE THREAD

**Issue by gauthieryannick** [OpenEmu/OpenEmu#3404]
I read a lot about Joy-Con compatibility with OpenEmu. Bottom line, it is said to be close to impossible to map 2 Joy-Cons as 1 controller. The only way to make it work would be to use a keyboard joypad mapper, however it does not work either.

It seems that Bluetooth discovery in OpenEmu has priority over keyboard mappers, which is a problem. So I think a new preference should be made available, which would **deactivate Bluetooth controller discovery completely**, letting us use keyboard mappers like "Controllers" or "Joystick Mapper" with OpenEmu.

I think that adding a preference should be quite easier to do than program specifically for Joy-Con support, which many are saying it will never happen.

Thanks!

**Comment by clobber** [comment]
There is no such discovery code to deactivate. Those gamepads simply aren't going to work with the way our input system is designed.

#3093
