### ISSUE TITLE
Emulation Recording/PlayBack

### ISSUE THREAD

**Issue by jnovack** [OpenEmu/OpenEmu#3406]
I see there's a lot of requests for recording gameplay (e.g. #2689), with the answering being outside the scope of the project.  I understand that, it is expected and warranted.

However, what I'm proposing is not audio/video playback/recording, it is emulation playback/recording.

We currently have the REW and FF keys, which means that we at least keep a cache of the previous emulation in the memory somewhere.  I'm suggesting saving THAT for playback (of the entire emulation later, most notably for recording later (e.g. a smooth play-through).

Understandably, emulation "saves" would probably not be scrubbable, but that's not my concern at this time.  I'd be more than content recording a "perfect run" (with my REW/FFs removed) after I've muscled through it.

**Comment by clobber** [comment]
Sorry, that is outside the scope of the project. Use external recording software for recording video instead. That’s their job and they do it well.

**Comment by jnovack** [comment]
Ok, so thanks for reading my request and processing it rather than just skimming over it and closing it.

**Comment by clobber** [comment]
I read it. You want what will ultimately be used for video recording. Just use video recording software. I don't need to explain why what you are suggesting is not a good idea.
