### ISSUE TITLE
Couldn’t communicate with a helper application.

### ISSUE THREAD

**Issue by saurabhm29** [OpenEmu/OpenEmu#3409]
All libraries are downloaded, but while opening the Pokemon Emerald ROM, I'm getting this error.

I've restarted the computer, uninstalled and reinstalled, deleted the "Cores" directory as redownloaded all the cores as well, but I'm still getting the same error.

**Comment by clobber** [comment]
Which version of OpenEmu and macOS?

**Comment by saurabhm29** [comment]
OpenEmu v1.0.4 554-gf588330-Release
OSX 10.10.5 Yosemite

**Comment by clobber** [comment]
Sorry, OpenEmu 1.x is unsupported. Only the [latest](https://github.com/OpenEmu/OpenEmu/releases/latest).
