### ISSUE TITLE
Games won't start at all

### ISSUE THREAD

**Issue by puderkat** [OpenEmu/OpenEmu#3410]
Every game that I double click to play doesn't even open at all and there's no error code. I've reset my computer and redownloaded the application and I don't know what to do anymore

**Comment by clobber** [comment]
>and I don't know what to do anymore

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..." and "Include Console and crash logs, macOS and OpenEmu version, hardware information, ROM/game filenames, etc."

Sounds like a good place to start.

**Comment by puderkat** [comment]
Thank you, I ended up having a .7z file instead of one that would actually work.

**Comment by clobber** [comment]
#3127
