### ISSUE TITLE
After "Compiling From Source", there's no sound in arcade games

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/OpenEmu#3411]
I tried to figure out what the problem might be, to no avail. I hope it's not too much of a problem..

(MacBook Air Mid '11, High Sierra 10.13.1, Xcode 9.1)

**Comment by clobber** [comment]
It broke after an API change in commit https://github.com/OpenEmu/OpenEmu-SDK/commit/62c7436015a4fa5e7bb5d434a2585adb5de94d8c.

In https://github.com/OpenEmu/UME-Core/blob/master/MAMEGameCore.mm#L504,
`NSUInteger bytesAvailableToWrite = ringBuffer.availableBytes;` needs to be changed  to 
`NSUInteger bytesAvailableToWrite = ringBuffer.freeBytes;`

I can't push a core plugin update with a fix for this until next OpenEmu release, so it will have to wait until then.

**Comment by clobber** [comment]
https://github.com/OpenEmu/UME-Core/commit/51f4bf588b3a6304a6a0a75fa82b203a56caa2a0

**Comment by PlutoX86** [comment]
Thank you!! :)
