### ISSUE TITLE
wii or wii u procontrollers not connecting 

### ISSUE THREAD

**Issue by Enangarcia** [OpenEmu/OpenEmu#3412]
I use to play with my Wii u Pro controller like a couple months ago, and it connected fine. However, now when I try to connect my pro controller all it does is freeze the control settings for a couple seconds and it doesn't connect. I tried connecting my Wiimotes as well but none were connecting. I tried resetting my laptop to try again, but it keeps doing the same thing. I've even checked my Bluetooth settings and it shows that it is connected But Open emu can’t find it.

**Comment by clobber** [comment]
Try here first: [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) and [wii remote pairing](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Wiimote-and-Wii-U-Pro-pairing) guides.
