### ISSUE TITLE
Not an issue. Minor design suggestion.. maybe ;)

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/OpenEmu#3413]
First, your work is phenomenal! Thank you so much for that!!.. :)

After work, i often play retro games with friends.. whenever i can (so i usually bring my mac with adapter-stuff and some PS3 controllers).

But.. i also liked your 1.0.4-aesthetics.. as you might know. ;) That's why i kinda recreated that look; And you absolutely inspired me to learn how to understand coding. :)

![bildschirmfoto 2017-11-29 um 10 07 58](https://user-images.githubusercontent.com/10595183/33367834-26634866-d4f0-11e7-8021-eb6aea717c98.png)

So,.. what i want to say is thank you! :)

**Comment by robotoad** [comment]
Thanks for the kind words. There are currently no plans to bring back the glossy cover art highlights.

**Comment by clobber** [comment]
@PlutoX86 We already told you a couple years ago that the cover art gloss isn't coming back.

#2186
