### ISSUE TITLE
Final Fantasy VIII (Multi-Disc Game) not importing on OpenEmu

### ISSUE THREAD

**Issue by dron8587** [OpenEmu/OpenEmu#3415]
After following, to the smallest detail, all available instructions and all similar topics on relevant forums, my downloaded ROM of Final Fantasy VIII will not import into OpenEmu.

I am on Mac OS 10.12.6 and running a fully updated version of OpenEmu. My Application Support/OpenEmu/Game Library/Sony Playstation folder was cleared of any previously installed game files before attempting to import the game again. I am attempting to import a folder containing all 4 discs' .bin, .cue, and .sbi files, along with the .m3u file I created as per instructions from Github's multi-disc game guide. 

All relevant BIOS files are installed and present in the library. 

When I drag the folder into OpenEmu, the Game Scanner scans 10 files but nothing comes up in the Sony Playstation caché window at all.
<img width="629" alt="screenshot 2017-11-30 01 58 20" src="https://user-images.githubusercontent.com/34121184/33418042-014b7062-d572-11e7-965c-393cc093a022.png">
What am I missing?

**Comment by clobber** [comment]
>After following, to the smallest detail

and

>When I drag the folder into OpenEmu, the Game Scanner scans 10 files but nothing comes up in the Sony Playstation caché window at all.

It seems you didn't follow the directions at all. Re-read the guide, because dragging an entire folder is not the way an m3u file gets imported. I'm really at a loss as to why some cannot follow our simple step-by-step guide, and yet swear they do.

**Comment by dron8587** [comment]
I have also tried to import the m3u file by itself; this also doesn't work.

**Comment by clobber** [comment]
Besides the few bugs I found and have fixed for next release, if an M3U file doesn't import, it's because you don't have something right so follow the guides closely. Sorry, I can't help you beyond that. I'd suggest actually reading the guide this time and also searching the previous issues for clues.
