### ISSUE TITLE
Crashes when deleting games

### ISSUE THREAD

**Issue by joshleaves** [OpenEmu/OpenEmu#3416]
Whenever I try to remove PSX games from my Library, the application crashes. The Console gave me the following error:

```
*** Assertion failure in -[NSWorkspace recycleURLs:completionHandler:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.83.101/AppKit.subproj/NSWorkspace.m:2607
```

Tested on another console (like the NDS) and it works perfectly.

May be of note:
- Latest version.
- OS X Sierra.
- Almost all of the PSX games in my OpenEmu Libary have been physically deleted from my hard drive.

**Comment by clobber** [comment]
#3285
