### ISSUE TITLE
Can't Click on DS Games (specifically Mario and Luigi: Bowser's Inside Story)

### ISSUE THREAD

**Issue by cwdickson** [OpenEmu/OpenEmu#3419]
When I click on my trackpad, it doesn't work. That simple. I'm on a Macbook Air, I think 2013. Any ideas?

P.S. This is not the "tap to click" thing. I can't even hard click it.

**Comment by clobber** [comment]
Describe this more clearly...can't click on *what*? The cover art in the Library?

**Comment by cwdickson** [comment]
No, when I click the screen in the game, nothing happens. This obviously prevents me from playing the game. I can play games without a touch screen perfectly fine, but DS games don't let me use the screen.

**Comment by clobber** [comment]
OpenEmu 2.0.5 - cannot replicate this. Works fine in all DS games, including Bowser's Inside Story. You are either having an AP patch issue with that particular game or something odd from here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
