### ISSUE TITLE
Help installing OpenEmu!

### ISSUE THREAD

**Issue by totallynotjoe** [OpenEmu/OpenEmu#3420]
I just downloaded the most recent version of it,(2.0.5)and got the zip file.But i have no idea what to do now.Help!

**Comment by clobber** [comment]
Well this is basic Mac 101 stuff and not an OpenEmu issue. You [uncompress](https://support.apple.com/kb/PH25411?locale=en_US) the zip file, move the OpenEmu app to your Applications folder and then [open](https://support.apple.com/kb/PH25088?locale=en_US) it.

**Comment by totallynotjoe** [comment]
But no app pos out.Just a cpzg.
