### ISSUE TITLE
Freese of gameboy game

### ISSUE THREAD

**Issue by SimonDelamarche** [OpenEmu/OpenEmu#3421]
When I play gameboy advance games freeze openemu after several minutes. I have already read that this is a common problem with macOS high sierra. my question is when will this problem be solved through an update. or when does the new general relay come out?

**Comment by SimonDelamarche** [comment]
realise*

**Comment by clobber** [comment]
When next release is ready. Please don't open issues for questions like this.

Duplicate #3365
