### ISSUE TITLE
N64 C-Pad can't handle diagonal

### ISSUE THREAD

**Issue by adamesq** [OpenEmu/OpenEmu#3422]
Directions on the C-pad don't seem to work properly when more than one button is activated. For example, the cpad is used for Robotron 64 for firing. I cannot shoot diagonally because only one direction at a time works.

**Comment by clobber** [comment]
Cannot replicate. Works fine with both keyboard (default C-Pad controls: I, K, J, L) and analog gamepad (PS4 Dualshock 4 with right analog stick mapped to C-Pad).
