### ISSUE TITLE
.m3u files not working for multi disc games.

### ISSUE THREAD

**Issue by Bleriott** [OpenEmu/OpenEmu#3423]
I'm having the same trouble as some of the previous (now closed) threads. I've tried deleting the game files from the library to start from scratch. I've added the .m3u file with the below code:
Final Fantasy VIII (USA) (Disc 1).cue
Final Fantasy VIII (USA) (Disc 2).cue
Final Fantasy VIII (USA) (Disc 3).cue
Final Fantasy VIII (USA) (Disc 4).cue

I noticed in the guide (that has been linked in various threads) though about a file which has this code:
Folder containing all Final Fantasy VIII files/
└╴Final Fantasy VIII (Disc 1).bin
└╴Final Fantasy VIII (Disc 1).cue
└╴Final Fantasy VIII (Disc 2).bin
└╴Final Fantasy VIII (Disc 2).cue
└╴Final Fantasy VIII (Disc 3).bin
└╴Final Fantasy VIII (Disc 3).cue
└╴Final Fantasy VIII (Disc 4).cue
└╴Final Fantasy VIII (Disc 4).bin
└╴Final Fantasy VIII.m3u <-- import this file

I just find the guide a bit misleading, am I meant to have one .m3u file in a folder containing the folders of each game disc (with their respective .bin and .cue files) or two .m3u files? Ive tried both but neither seems to work. When I add any of the above .m3u files nothing happens.

Any help would be greatly appreciated.

**Comment by clobber** [comment]
>I just find the guide a bit misleading, am I meant to have one .m3u file in a folder containing the folders of each game disc (with their respective .bin and .cue files) or two .m3u files? Ive tried both but neither seems to work.

I'm not sure why this is hard for you to understand. The guide is clearly showing a **single** folder with all of the required disc files **together in that folder** along with **one** m3u file created. This is exactly what the directions say.

Sorry, I cannot help you beyond what is in the guide. It's already step-by-step.
