### ISSUE TITLE
Nintendo Switch Pro Controller acting up

### ISSUE THREAD

**Issue by mikkelfosgrau** [OpenEmu/OpenEmu#3425]
I've read all the other tips, like not using chrome, restarting my MacBook Pro and deleting the library file (there was no OpenEmu folder in my Library folder), but my Nintendo Switch Pro Controller is still acting up. Sometimes I can't map the controls, sometimes I can, but they don't work, sometimes it seems like one button is pushed in all the time even though I'm not pushing it and so on. Any ideas on how to get it to work?

**Comment by clobber** [comment]
Deleting the Library is definitely not a tip. Input trouble will be related to known issues outlined in this guide: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by mikkelfosgrau** [comment]
I've done everything in the troubleshoot guide, but nothing seems to work. Any other tips?

**Comment by clobber** [comment]
No. It has to be something related, as other users are not have those problems. The only known issue is with the analog sticks which we will address in a future update.
