### ISSUE TITLE
Openemu crashes when launch game

### ISSUE THREAD

**Issue by BcseNt85** [OpenEmu/OpenEmu#3426]
when i launch a game, openemu crashes. I have this issue since I installed the corrective update (for root password) of Mac OS High Sierra

**Comment by BcseNt85** [comment]
Problem Resolved, it came from my Gamepad that have a problem with the right stick. It works with another gamepad

**Comment by clobber** [comment]
It's unlikely the security update caused your crash. You can try the following with your gamepad that you say causes it:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.
