### ISSUE TITLE
OpenEmu sits at black screen for SNES and NES games

### ISSUE THREAD

**Issue by storyid** [OpenEmu/OpenEmu#3427]
Hello,
I'm on macOS 10.12.6 on a MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports) with 16 GB of RAM, using OpenEmu 2.0.5 719-g369c3a2-Release.  When I try to launch either an SNES or NES game, OpenEmu goes full screen, to a black screen, and nothing happens from there.  I have tried multiple games on both SNES and NES, no luck.  Genesis games work fine.  Have tried the Secrets menu and tried running background thread instead of XPC as I've seen that suggested a few times, seems to be the same in both.  I've tried both the SNES9x (1.55) core and the Higan (0.95.1) core.  Am attaching a spindump from trying to run Super Ghouls 'N Ghosts using background thread and Higan...any suggestions greatly appreciated, glad to try to troubleshoot further.
[Spindump - 10.12.6 - OpenEmu 2.0.5 - SNES - Super Ghouls 'N Ghosts.txt](https://github.com/OpenEmu/OpenEmu/files/1545982/Spindump.-.10.12.6.-.OpenEmu.2.0.5.-.SNES.-.Super.Ghouls.N.Ghosts.txt)

**Comment by clobber** [comment]
What happens when you run (double click) “Classic Kong Complete” or “Super Bat Puncher” in the Homebrew tab?

**Comment by storyid** [comment]
Okay, they both work.  That doesn't make sense to me.  Seems unlikely that all my ROMS are corrupted, especially since they play in Snes9x (just tried Super Ghouls 'N Ghosts in Snes9x 1.55 (113) and it worked).  Are the particularities to be aware of with ROMS and OpenEmu?  I doubt it helps, but here's the info from Super Ghouls 'N Ghosts from Snes9x...

Snes9x version: 1.55
Mac port version: 113, Intel

            Cart Name: SUPER GHOULS'N GHOSTS
            Game Code: 
             Contents: ROM
                  Map: LoROM
                Speed: 0x20 (SlowROM)
                 Type: 0x00
    Size (calculated): 8Mbits
        Size (header): 8Mbits
            SRAM size: 0Kbits
Checksum (calculated): 0x648D
    Checksum (header): 0x648D
  Complement (header): 0x9B72
         Video Output: NTSC 60Hz
             Revision: 1.0
             Licensee: Capcom
               Region: USA and Canada
                CRC32: 0x6AABA901

**Comment by clobber** [comment]
I assume you are importing compressed ROMs, possibly gzipped. There is a bug right now with importing compressed ROMs (fixed for next version), so right now uncompress them first and import the .SFC/SMC files.

**Comment by storyid** [comment]
Oh man.  I'm an idiot.  Sure enough, I renamed it from .smc to .gz, ran it through my gzip program to decompress, it did, got another .smc file (1mb instead of 672kb) and gee, what do you know, it worked.  Thank you, I'm an idiot, am sorry to have taken your time from much more important things (like getting the next release out - exciting!!).  

The only thing I'll note is that it definitely puts OpenEmu in an unstable state if you are an idiot (like me), not that I'd expect you to fix that, but as noted, with the Higan core you can quit, with Snes9x you can't even quit, have to force quit.

Thank you so much, will stop bothering you now and go rock some Super Ghouls 'N Ghosts - I am going to get the rest of my games when I'm home for Christmas and dump them to ROMS - must be when I did this last time I compressed them and wasn't paying attention :)
