### ISSUE TITLE
Random crash when opening map/inventory in Silent Hill

### ISSUE THREAD

**Issue by MazterQyou** [OpenEmu/OpenEmu#3428]
When Playing Silent Hill (SLUS-00707), opening the map or inventory might result in OpenEmu crashing. Sometimes it does, sometimes it doesn't, and I wasn't able to find a case where it 100% reproduces, but it does happen often enough to catch the issue. As a side note, while testing I found that using Background Thread over XPC (yes, a bad idea, I know) reduces the chance for a crash significally. With XPC it can happen in minutes and playing becomes a nightmare for people who use map every 1-2 minutes like me. With Background Thread I can play for hours and it might not crash, but very sometimes it does as well (killing the hours of progress basically, because for some reason memory card is reset to where the last autosave state was).

I get that game-specific things are usually a problem of specific cores, but strangely enough, it's the OpenEmu that crashes, so I thought I should report this here. I'm not even entirely sure this is game-specific as I haven't tested it with other games.

My hardware configuration is: MacBook Pro Retina 15" Mid-2012, 2.3 GHz Core i7, 16 GB RAM, Intel HD4000 + NVIDIA GT650M. OS version: 10.13.3 Beta (17D20a) (used to happen on stable 10.13.2 too, so it's not the beta, see crashlogs). This happens in both stable and experimental OpenEmu 2.0.5.

Also attaching a few OpenEmu crashlogs.

[OpenEmu Crashlogs.zip](https://github.com/OpenEmu/OpenEmu/files/1554503/OpenEmu.Crashlogs.zip)

**Comment by clobber** [comment]
I believe you are experiencing the known High Sierra crash which is fixed for next release.

**Comment by MazterQyou** [comment]
@clobber I've seen you posting a test build with fix for this in another thread but the link is no more, can you post it once again so I can test and confirm please?

**Comment by clobber** [comment]
Also after looking at the logs, try using a different shader such as Pixellate or none at a all (Nearest Neighbor).

**Comment by MazterQyou** [comment]
I'm using NTSC (Blargg) since that filter makes it look a little like CRT and the game doesn't look so pixelated anymore. Never had problem with it but I'll give this a try, thanks.
