### ISSUE TITLE
Won't Import Games

### ISSUE THREAD

**Issue by zabotx** [OpenEmu/OpenEmu#3431]
Hey guys! I have been trying to figure this out for just over an hour with no avail. I download Legend of the dragoon disc 1 and loaded the .cue into OpenEmu. It worked fine and showed the box art, when I tried to launch it I was told that I needed to create an .m3u file. Which I did, naming it the same and placing all the .bin and .cue files into a folder with the same name as the files. 

Now when I try to load the .m3u file it will not import, and also now when I try to load just a regular .cue file it won't import. I've tried uninstalling and reinstalling OpenEmu, extracting it from a new .zip and more. It says "game scanner" at first but then just goes away and nothing happens.

Also now when I try to import a game with the same .cue it no longer even says scanning.

Any help would be appreciated.

Im running MacOS High Seirra 10.13.1

**Comment by clobber** [comment]
Follow both sets of directions.

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game

https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing

**Comment by zabotx** [comment]
Hey clobber! I appreciate the quick response. 

I have followed both these guides already and neither one fixed my problem. What I really need is to know how to remove OpenEmu from my mac completely and perform a fresh install. any insight as to how to do this?

**Comment by clobber** [comment]
You didn’t follow the guides, otherwise it would have worked. The fact that you wiped your install as a workaround proved that, because it means you had those files in your Game Library instead of properly deleting them.
