### ISSUE TITLE
Unable to Download Newest OpenEmu

### ISSUE THREAD

**Issue by finewinemama** [OpenEmu/OpenEmu#3433]
Hello,

I've been trying to download the newest OpenEmu and it has not been working whatoever. It crashes repeatedly. The only version of OpenEmu that works for me is 1.0.2. My computer is a Macbook and it is running on macOS Sierra version 10.12.6. I've tried everything from restarting my computer to redownloading several OpenEmu's. Please help! Thank you!

**Comment by robotoad** [comment]
Are you saying you can't download the application from the website or that the application crashes when you run it? If the application is crashing, we'll need to see a crash log to accurately diagnose it.

**Comment by finewinemama** [comment]
Robotoad,

I am able to download the application from the website and once I've installed it, it gives me a failure log. Since I don't think it exactly registers that an application has crashed I've attached the message it gives me when I try to download it. 

![screen shot 2017-12-13 at 2 41 31 pm](https://user-images.githubusercontent.com/34524568/33966265-d37560ba-e013-11e7-843b-73655cb49dd2.png)

**Comment by robotoad** [comment]
Looks like https://github.com/OpenEmu/OpenEmu/issues/3044.

If the Console log contains the same data store error, you'll need to delete your data store in `~/Library/Application Support/OpenEmu/Game Library`. This will require you to re-import any games you previously had.

**Comment by finewinemama** [comment]
Is there any way to save the data of all of my current games and back them up to re-import?

**Comment by robotoad** [comment]
Imported ROMs are stored in `~/Library/Application Support/OpenEmu/Game Library/roms`. You could move this folder to another location, such as your desktop, and re-use those files for reimporting.
