### ISSUE TITLE
Is there a way to back up ROM data?

### ISSUE THREAD

**Issue by finewinemama** [OpenEmu/OpenEmu#3434]
Hi!

Is there any way to back up games/ROMs that you have and transfer them to an updated OpenEmu version? I want to download the newest OpenEmu and keep the games I have now along with their data, however I'd have to end up deleting the data as there's a data error. Is there any way to keep what I still have without deleting everything?

**Comment by robotoad** [comment]
Please don't open a new issue for this. #3433
