### ISSUE TITLE
Openemu not opening games at ALL

### ISSUE THREAD

**Issue by MegaFire1121** [OpenEmu/OpenEmu#3435]
![screen shot 2017-12-16 at 8 19 51 am](https://user-images.githubusercontent.com/34600944/34070774-ffc72810-e239-11e7-90b9-2b63a6466daa.png)
![screen shot 2017-12-16 at 8 19 51 am](https://user-images.githubusercontent.com/34600944/34070775-0171ea60-e23a-11e7-8b47-1bc534cfaacb.png)
![screen shot 2017-12-16 at 8 20 01 am](https://user-images.githubusercontent.com/34600944/34070776-031578b4-e23a-11e7-802a-e8b8e809f228.png)
![screen shot 2017-12-16 at 8 20 14 am](https://user-images.githubusercontent.com/34600944/34070778-04276f82-e23a-11e7-8e8f-c24ab0cb26e9.png)

Macbook Air info:
1.6 Intel core I5
8gb ddr3 ram
Intel HD 6000 Graphics

Anyone help on why this is going on?

**Comment by robotoad** [comment]
Can you be more specific? I don't know what the screenshots are meant to convey. Are you getting a crash or error message when you launch a game?

**Comment by clobber** [comment]
Oh, I know why this is happening. See https://github.com/OpenEmu/OpenEmu/issues/3352#issuecomment-333324621 for a workaround.

**Comment by MegaFire1121** [comment]
No it doesn't give me a error message robotoad

**Comment by MegaFire1121** [comment]
And Clobber, it also doesn't work with ANY OTHER Games that are new

**Comment by MegaFire1121** [comment]
Clobber I tried to do what you said, it didn't work

**Comment by MegaFire1121** [comment]
Clobber I'm using emuparadise, since other ones won't work at all

**Comment by MegaFire1121** [comment]
![screen shot 2017-12-18 at 6 48 25 pm](https://user-images.githubusercontent.com/34600944/34181091-ea8ca75c-e4de-11e7-931f-c673ccc67d4c.png)

**Comment by clobber** [comment]
1. Download this file https://transfer.sh/XIQ05/touch_test.nds
2. Import it into your NDS library.
3. Open it.

What happens?

**Comment by MegaFire1121** [comment]
Clobber it works, but it didn't work I closed it and tried to play my game


Vincent Zhao
vincentz1116@aol.com




-----Original Message-----

**Comment by clobber** [comment]
> Clobber it works, but it didn't work I closed it and tried to play my game

Sorry, could you please clarify? That sentence seems to contradict itself.
