### ISSUE TITLE
Old save state for Genesis not running on 2.0.6

### ISSUE THREAD

**Issue by franklinyu** [OpenEmu/OpenEmu#3436]
I have a game running on Genesis (SEGA Mega Drive). After upgrading to 2.0.6 from 2.0.5 minutes ago, those saved states were moved to trash. Even if I recover them from trash, they won't load properly; the image freezes, and the control keys does not have effect. My saved states of GBA and NDS simulators works fine, so I'm wondering whether it's just Genesis, or even just my game; I cannot verify because I only have one single Genesis game. Since it didn't crash, I'm not sure how I can provide more information.

Note: I know some programming and CLI usage, so please tell me if there's any log or dump that I can provide/produce. I'm in EST.

**Comment by clobber** [comment]
Those old save states aren't coming back and were removed, as per the 2.0.6 release notes. Several of the emulator core plugins broke save state compatibility. Genesis Plus GX does it quite frequently and it is beyond our control.

**Comment by franklinyu** [comment]
Sorry, should have searched. Has been mentioned at ekeeke/Genesis-Plus-GX#194.
