### ISSUE TITLE
Doesn't work anymore on MacOS High Sierra 10.13.2

### ISSUE THREAD

**Issue by fymaster79** [OpenEmu/OpenEmu#3437]
Only a blank screen, and it can't exit to games list. 

Any solution for this?

**Comment by clobber** [comment]
>Any solution for this?

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..." and "Include Console and crash logs, macOS and OpenEmu version, hardware information, ROM/game filenames, etc."

Sounds like a good place to start.

**Comment by auni53** [comment]
Working fine on 10.12.6. Will try and report back if I can reproduce when I upgrade.

**Comment by YLSofsnow18** [comment]
I have Mac OS High Sierra version 10.13.6 but i seem to have the same issue...Will i have to update my mac or is this some sort of bug?

**Comment by takeshineale128** [comment]
I run a MacBook mid 2010 (White) on Mac OS 10.13.6 and the OpenEmu v2.0.9.1 but mine works just fine.

**Comment by YLSofsnow18** [comment]
odd my macbook air is from late 2010 yet whenever i try to run the game that i downloaded...a black screen with controls pops up.
