### ISSUE TITLE
Why PS1 in OpenEmu doesn't support cheat codes?

### ISSUE THREAD

**Issue by ifadardin** [OpenEmu/OpenEmu#3438]
I saw in my PS1 game there is no way to add cheat codes GameShark.

I checked this page:
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes
It seems like the core, Mednafen doesn't support cheat codes.

However here:
https://forum.fobby.net/index.php?t=msg&goto=5069&
It looks like Mednafen actually support cheat codes.

Did i miss something or?

**Comment by clobber** [comment]
>Did i miss something or?

Yep. Search before opening a new issue.

#2310
