### ISSUE TITLE
Sudden slow down on n64 emulation and loss of save states

### ISSUE THREAD

**Issue by bassfacedeez** [OpenEmu/OpenEmu#3440]
As the title says, I experienced a sudden slow down for n64. The computer was untouched between when it was last working and the problem occurred. I quit the program hoping this would solve the issue and when I opened it again, all the n64 save states were gone. 

No other save states or emulators were affected. I am completely baffled as to what happened so any help is appreciated.

Openemu version 2.0.6.1
macOS 10.11.6

**Comment by clobber** [comment]
Release notes says that save states were removed for deprecated core plugins. Nothing we can do about that. The graphics plugin update for Mupen64Plus meant that the old save states were no longer compatible. That is sometimes the price of progress and it is out of our hands.
