### ISSUE TITLE
OpenEmu v2.0.6.1 (OECoreUpdaterErrorDomain error -1.)

### ISSUE THREAD

**Issue by zeromtheimmortal** [OpenEmu/OpenEmu#3441]
I just updated to the latest OpenEmu and i have been playing final fantasy 2 with the most recent save file being 
Save-Game-318 2017-12-19 230521 -0500 2 copy 2.oesavestate alias

i believe i have to change my core and more sites suggest to click the cog and select core but i dont have that option. if there was to play my save or change my core so i can play this game again

**Comment by clobber** [comment]
What system?

**Comment by zeromtheimmortal** [comment]
Im running the openEmu on a mac and im playing final fantasy 2 on game boy advance. and ever since i downloaded the latest version i cant load my saves and i get that error code everytime. 

    On Wednesday, December 20, 2017 1:35 PM, clobber <notifications@github.com> wrote:
 

 What system?—

**Comment by clobber** [comment]
See https://github.com/OpenEmu/OpenEmu/issues/3436#issuecomment-352655253
