### ISSUE TITLE
MacOS High Sierra - does not function properly

### ISSUE THREAD

**Issue by KiraKuin** [OpenEmu/OpenEmu#3442]
The latest version of OpenEmu can open and add new games, but when emulating, will freeze after up to 10 minutes and be unable to exit to the games library. I am on the latest version of MacOS, no crash report occurs, and I use a 2-3 year old MacBook Pro that was recently fully repaired and wiped.

**Comment by clobber** [comment]
>The latest version

Which version? We fixed that freeze in 2.0.6.1

**Comment by KiraKuin** [comment]
It's 2.0.5, I thought I'd had the latest. Thanks.

**Comment by clobber** [comment]
Duplicate #3365
