### ISSUE TITLE
Save files deleted after update 12/20

### ISSUE THREAD

**Issue by 3KD** [OpenEmu/OpenEmu#3443]
I updated to the newest update.  Very excited about saturn's addition, btw.

Anyway, I went to look for my save files, and noticed that they weren't automatically populating under the floppy disk icon where they can normally be found.  I did a quick search through my library for the files and came up empty-handed.

Is it possible that the new update deleted all my save files?

**Comment by clobber** [comment]
Okay now we're starting to get several of these. You guys really need to search before opening a new issue, or at the very least read the release notes.

https://github.com/OpenEmu/OpenEmu/issues/3436#issuecomment-352655253
