### ISSUE TITLE
PS1/PSX controllers and keyboard not functioning

### ISSUE THREAD

**Issue by CluelessManchild** [OpenEmu/OpenEmu#3444]
So I downloaded the region specific stuff (scph 5500/5501/5502) for my PS1 and decided to play Burger Burger 2 (Burger Simulator). However my keyboard and controller (ps3) doesn't seem to work for no reason. However my game boy advance and nintendo DS work fine. What may be the problem.

**Comment by clobber** [comment]
Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by designbyadrian** [comment]
I'm also having issues. Dualshock 3 controller works with PSP, but not a PS1 game.

Updated OpenEmu just today. I'll see if a restart helps...

**Comment by clobber** [comment]
There's no reason for it to work with one system and not another.
