### ISSUE TITLE
Super Mario 64 Romhacks unplayable in version 2.0.6

### ISSUE THREAD

**Issue by mrdrprofpatrick** [OpenEmu/OpenEmu#3445]
Regular SM64 works just fine, but of the numerous romhacks I tried, all of them have severe issues, from either functioning, but with a black/glitchy screen rather than displaying the actual game (i.e. you can hear and move Mario in the background, but cannot see anything), to some that just do not play at all (e.g. just black/glitchy screens, unable to play the game in the background)

Version 2.0.6.1 of OpenEmu, running on macOS Sierra, v.10.12.6 (yeah, I know, I think there's an update for mac)

EDIT: Some other romhacks tested: SM64 Last Impact loads, but the sound effects and music are all wrong, seemingly random noises, and the level textures are all just solid black. Similarly for Super Mario Green Stars: game is visible, sound seems find, but screen is shrunk and level textures are all solid black. The incorrect sound effects are present on several other romhacks.

(I apologize if this is too much, I tried to provide as much detail as possible)

**Comment by clobber** [comment]
Most of the ROM hacks do things that cannot be done on real hardware. Them not working now is a result of more accurate emulation with the updated GPU plugin. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
