### ISSUE TITLE
N64 games slowing down with openemu 2.0.6.1

### ISSUE THREAD

**Issue by thibautq** [OpenEmu/OpenEmu#3447]
Hello,
After the last update, the N64 games are hugely slowing down. With the previous release of openemu, everything worked great. Is there anything to do, or can i replace the Mupen64 core with the previous release by my own ?
Thanks a lot,

I'm running macOS x high sierra 10.13.2, core I7 2,8 ghz, 8gb RAM, HD3000 512MB

**Comment by clobber** [comment]
There are going to be compatibility issues with some games and possibly an issue on some underpowered GPU's like the HD3000. There is nothing that can be done about that at the moment. We will just have to see how much the new GPU plugin improves over time. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
