### ISSUE TITLE
Buffalo Classic USB Game Pad recognized but not working

### ISSUE THREAD

**Issue by nickytonline** [OpenEmu/OpenEmu#3448]
Hi, first off, thanks for all the work you put into this project. Super cool stuff.

MacOS: High Sierra 10.13.2 on a MBA 13inch 2017
OpenEmu Version: v. 2.0.6 856-gebacd52-Release
Buffalo Game Pad: [Buffalo iBuffalo Classic USB Gamepad for PC BSGP815GY](https://www.amazon.ca/gp/product/B06XWD8QQJ/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1)

```
  ~: system_profiler SPUSBDataType
USB:

    USB 3.0 Bus:

      Host Controller Driver: AppleUSBXHCIWPT
      PCI Device ID: 0x9cb1
      PCI Revision ID: 0x0003
      PCI Vendor ID: 0x8086

        BRCM20702 Hub:

          Product ID: 0x4500
          Vendor ID: 0x0a5c  (Broadcom Corp.)
          Version: 1.00
          Speed: Up to 12 Mb/sec
          Manufacturer: Apple Inc.
          Location ID: 0x14300000 / 2
          Current Available (mA): 500
          Current Required (mA): 94
          Extra Operating Current (mA): 0
          Built-In: Yes

            Bluetooth USB Host Controller:

              Product ID: 0x828f
              Vendor ID: 0x05ac (Apple Inc.)
              Version: 1.43
              Speed: Up to 12 Mb/sec
              Manufacturer: Apple Inc.
              Location ID: 0x14330000 / 4
              Current Available (mA): 500
              Current Required (mA): 0
              Extra Operating Current (mA): 0
              Built-In: Yes

        USB,2-axis 8-button gamepad  :

          Product ID: 0x2060
          Vendor ID: 0x0583  (Padix Co., Ltd.)
          Version: 1.00
          Speed: Up to 1.5 Mb/sec
          Location ID: 0x14100000 / 5
          Current Available (mA): 500
          Current Required (mA): 100
          Extra Operating Current (mA): 0
```

I've gone through existing issues and the contributing and I think this is a unique issue. The game pad is recognized, but when I load a NES or SNES game with the input set to the game pad, the game pad does not work.

From other issues , I tried some suggestions like erasing the bindings in `~/Library/Application Support/OpenEmu/Bindings`.

I've also done a clean install and the issue still persists. I've never used a game pad on a Mac before so perhaps there is something obvious I'm missing. From what I read, there is no need to install any additional drivers.

Thanks in advance for any suggestions.

**Comment by nickytonline** [comment]
I should also mention that I've plugged the game pad directly into the machine, not in my USB hub.

**Comment by clobber** [comment]
I have that gamepad, and it works just fine. Also, you are misunderstanding the dropdown in the input preferences; both keyboard and gamepad work at the same time, so the dropdown is only for mapping controls, not selecting which input device to use. Try here first: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

Just an FYI: The latest version of OpenEmu is 2.0.6.1

**Comment by nickytonline** [comment]
@clobber, thanks for the info, for some reason this morning it wasn't updating to 2.0.6.1. I just updated. I also read through the wiki, but the problem still persists. I've closed all apps in the list and every other app I have running, but no dice. I'll read up some more through the docs to make sure I didn't miss anything. Thanks.

**Comment by clobber** [comment]
It has to be some other app or process interfering, or even a kernel extension installed.

**Comment by nickytonline** [comment]
K, cool. I'll keep digging until I find it then. Thanks!

**Comment by clobber** [comment]
Let us know what you find, so we can add it to the list. In Terminal you can try running `kextstat | grep -v com.apple` to see if any non-Apple kernel extensions are installed.

**Comment by nickytonline** [comment]
Cool. Will do.

**Comment by nickytonline** [comment]
A little update. I had some non-Apple kernel extensions running (VirtualBox related to Docker)

```
 ~  kextstat | grep -v com.apple
Index Refs Address Size Wired Name (Version) UUID <Linked Against>
158 3 0xffffff7f85da8000 0x62000 0x62000 org.virtualbox.kext.VBoxDrv (5.1.28) C0F0EDBE-F7FA-3189-8D24-48F02415C348 <7 5 4 3 1>
166 0 0xffffff7f85e0a000 0x8000 0x8000 org.virtualbox.kext.VBoxUSB (5.1.28) 93025612-D707-3185-AA16-5D987EA2F72E <165 158 55 7 5 4 3 1>
168 0 0xffffff7f85e12000 0x5000 0x5000 org.virtualbox.kext.VBoxNetFlt (5.1.28) F8FCB36B-980B-3823-BFCB-765E43593678 <158 7 5 4 3 1>
169 0 0xffffff7f85e17000 0x6000 0x6000 org.virtualbox.kext.VBoxNetAdp (5.1.28) 6AE4C456-BA43-328E-8464-1CAA4C6F7BB8 <158 5 4 1>
```

I ran

```
sudo kextunload -m org.virtualbox.kext.VBoxDrv
sudo kextunload -m org.virtualbox.kext.VBoxUSB
sudo kextunload -m org.virtualbox.kext.VBoxNetFlt
org.virtualbox.kext.VBoxNetAdp
```

to remove the extensions, but even after that, the game pad still doesn't work.

Still digging 😉

**Comment by nickytonline** [comment]
Good news it's all working. The bad news is, I'm a bonehead 😉. Being new to using a game pad on a laptop, I didn't realise that I needed to map the buttons. I assumed out of the box they would be mapped to defaults. So for each button or direction, focus on that input in the mapping form and click the physical button or direction on the controller.

**Comment by clobber** [comment]
We currently automap controls for the following gamepads: https://github.com/OpenEmu/OpenEmu/wiki#automap-supported-controllers
