### ISSUE TITLE
Glide64 is slow

### ISSUE THREAD

**Issue by zebHub** [OpenEmu/OpenEmu#3449]
Since upgrading to 2.0.6.1 I've noticed the N64 emulation to be choppy on Mario 64 and Zelda OOT

It is more accurate though. The text shows up correctly in Zelda cutscenes, the colours are better, first bowser has the correct Peach to Bowser painting transition.

Will the Glide 64 renderer improve? Can there be an option to set back to the old one?

**Comment by clobber** [comment]
1. It's GLideN64.

2. [Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3447
