### ISSUE TITLE
Issue #3450 NOT SOLVED - Can't open the program, get error: Foundation._GenericObjCError error 0. (#3450)

### ISSUE THREAD

**Issue by Magic1MrFox** [OpenEmu/OpenEmu#3451]
As per item raised in #3450, the issue was NOT the freeze. The issue was the inability to open the program.
Furthermore, I've also attempted what's been covered in #3044, and it also did not fix the problem.

Help would be appreciated.

**Comment by clobber** [comment]
Stop opening a new issue for this.

#3450
