### ISSUE TITLE
N64 games with choppy audio since update to 2.0.6 and 2.0.6.1

### ISSUE THREAD

**Issue by robbitobk** [OpenEmu/OpenEmu#3454]
Hello, I wanted to bring to your attention that ever since the update mentioned above that all of my n64 games which have for the most part worked extremely well with no type of audio lag or issue NOW since the last two updates have bad choppiness (i.e. in and out audio). I followed the instructions given when updating to 2.0.6 to not allow to continue a previously played n64 game and to start from beginning. From that point the n64 games I play have really bad audio issues that were not around before. I tried re-downloading the last version before this issue started (2.0.5) and the issue is still there with the audio choppiness. Do you have any info or assistance that could help fix this issue?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3447
