### ISSUE TITLE
2017 15" Macbook Pro choppy video SNES regardless of core or filter used

### ISSUE THREAD

**Issue by mario-64** [OpenEmu/OpenEmu#3455]
First of all let me say I absolutely love the interface and design of OpenEmu. Great job on that. I'm having an issue, however, with SNES emulation performance. Regardless of which core I use and which filter, video performance is just awful. It's very choppy. I verified that my dGPU is being used (Radeon 560 4GB) so I don't think video card is the problem. Using Retroarch which has a current Higan core, performance is flawless. Problem is, it doesn't have the great interface that OpenEMU has. I'm running 2.0.6.1 on High Sierra latest release. I'm happy to provide any troubleshooting assistance I can to get this working.

**Comment by clobber** [comment]
It's just not in sync with your display's refresh rate.

#967
