### ISSUE TITLE
Openemu Freezes on MAC Please help

### ISSUE THREAD

**Issue by Bucs4Life** [OpenEmu/OpenEmu#3458]
I usually have problems with the DS games but now it is happening to the GBA games as well. I have a MAC OS High Sierra. I have OpenEmu version 2.0.5. What should I do to fix this I had this problem for awhile now even before updating my mac and now it still lingers. I've read previous issues and I dont understand the lingo or language of the app itself so if you can explain what exactly I need to I would appreciate that. Thank you in advance

**Comment by clobber** [comment]
Update to the latest version. It's why we release updates.

Duplicate #3365
