### ISSUE TITLE
More then one Computer, but just one Human :-)

### ISSUE THREAD

**Issue by OurKitchen** [OpenEmu/OpenEmu#3459]
Greetings from Luxembourg,

we have a iMAC in the Kitchen and few laptops in our household.

Sometimes it is great just to start openEmu up and play for few minutes wherever you are...

I have the APP _and_! the Game library on my dropbox, so every new game that I drop into it will appear on all my devices, thats great :-)

BUT***  All the cores, _SAVE STATES_ (important) and the rest of the needed files are still saved on the Application Support folder that I cant configure to be somewhere else. (Screenshot attached)

Could you make an option/settings for that? That way the App would be truly mobile :-)

p.s. No I cant mess with the Unix filesystem as sometimes we are just in a Hotel with GUEST Access to e.g. a mac...

p.s.2 Yes that would more then qualify for a donation :-)

Thank you in advance
Our Kitchen in Luxembourg

![screen shot 2017-12-25 at 10 24 33](https://user-images.githubusercontent.com/34831956/34337317-a3d1179c-e95e-11e7-8352-8b9a4bfdd708.png)

**Comment by clobber** [comment]
Sorry, some files need to stay in Application Support where they belong and that won't change. Install OpenEmu to a "guest account" or use symbolic links or something.

**Comment by clobber** [comment]
Noting that the Saves States folder can be changed via the "Secrets" prefs menu. More info on finding and opening that in the wiki.
