### ISSUE TITLE
Sega Master System Black Screen after latest update

### ISSUE THREAD

**Issue by iwannanewname** [OpenEmu/OpenEmu#3460]
I updated my Openemu about 2 days ago, and ever since then, my Sega Master System roms all load black screen.  I had switched from Stable Openemu to Experimental months ago.  After this issue, I erased my Experimental Openemu, then tried reinstalling Openemu, but issue persists.

Thank you very much for your time and attention, and I apologize if I reposted already resolved/known/unsupported issue.

OpenEmu v2.0.6.1
858-gefc590e-Release

macOS High Sierra
version 10.13.2
MacBook Air (13-inch, Mid 2012)
Processor 2 GHz Intel Core i7
Memory 8 GB 1600 MHz DDR3
Startup Disk Macintosh HD
Graphics Intel HD Graphics 4000 1536 MB

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/3452#issuecomment-353645095
