### ISSUE TITLE
Sega CD: Cannot load BIOS_CD_J.bin

### ISSUE THREAD

**Issue by shadow-creator** [OpenEmu/OpenEmu#3461]
Hi! I'm trying to play Sonic CD on the Sega CD emulator. I found a rom with a cue sheet. Downloaded all the .bin files from different sources. However, no matter what I do, I cannot get BIOS_CD_J.bin to work. 

At first, I tried dragging and dropping the file into the emulator. No dice. Then, I went into Finder, looked for the BIOS folder in my computer, and dropped BIOS_CD_J.bin in there. It seemed to be fine, but, when I booted up Sonic CD, I got an error message saying that I didn't have the right BIOS file. When I looked at the BIOS folder, it's as if the file disappeared!

What happened? Help!

<img width="816" alt="screen shot 2017-12-25 at 4 53 30 pm" src="https://user-images.githubusercontent.com/19175997/34343207-53fe5036-e995-11e7-9ed0-c20638af329f.png">
<img width="581" alt="screen shot 2017-12-25 at 4 56 50 pm" src="https://user-images.githubusercontent.com/19175997/34343209-63fd1328-e995-11e7-983b-559e5422cf83.png">

**Comment by clobber** [comment]
You do not have the correct file. Read the guide, that's what it's there for.

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files
