### ISSUE TITLE
experimentals not so experimental

### ISSUE THREAD

**Issue by liamgrant** [OpenEmu/OpenEmu#3462]
Why experimentals are the same thing as standard builds?
Anyway, i'm using XCode (7.3.1) on 10.11.5 and the build using the git clone failed.
Anybody having the same issue?
"OpenEmu/OpenEmu-SDK/OpenEmuBase/TPCircularBuffer.h:54:14: Include of non-modular header inside framework module 'OpenEmuBase.TPCircularBuffer'"

**Comment by clobber** [comment]
To compile OpenEmu from source, the latest version of Xcode is required among other things. Read the guide. https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide
