### ISSUE TITLE
N64 Flying Dragon Life/Super meters swapped

### ISSUE THREAD

**Issue by TauzentBlitz** [OpenEmu/OpenEmu#3464]
For some reason the life bar is where the power bar is supposed to be and vise-versa.
<img width="2400" alt="flying dragon 2017-12-27 16 39 13" src="https://user-images.githubusercontent.com/20016772/34394012-9f885232-eb24-11e7-8d60-bbea97158d90.png">

At least the characters aren't invisible anymore. Version 2.6.0.1

**Comment by clobber** [comment]
GPU plugin bug. This will improve in a future version of GLideN64. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
