### ISSUE TITLE
Arcade game cannot save state or autosave

### ISSUE THREAD

**Issue by DolphinDream** [OpenEmu/OpenEmu#3467]
I can’t seem to be able to save the game state or have the state auto saved with some arcade roms. I’m using the experimental 2.0.6.1 858-gefc590e-Release on mac os x sierra 10.12.6 (16G1114).

The arcade game/rom I’m having problems with is “Head On” (Sidam bootleg, set 1)).. downloaded from: https://www.emuparadise.me/M.A.M.E._-_Multiple_Arcade_Machine_Emulator_ROMs/Head_On_(Sidam_bootleg,_set_1)/13554-download

Any ideas if this is a bug with OpenEmu’s arcade emulation or is it the rom itself?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/UME-Core/issues/7
