### ISSUE TITLE
OpenEmu dolphin core - pokemon xd - mac os x - keyboard config to adjust keyboard speed 

### ISSUE THREAD

**Issue by aliyahnicole** [OpenEmu/OpenEmu#3468]
PLZ HELP!! Playing Pokemon XD and am at the part where I need to slowly approach Bonsly, but cannot find controller/keyboard config in OpenEmu that adjusts controller/keyboard speed. I have came across numerous tutorials for the Dolphin emulator but not the Dolphin core with OpenEmu. I cannot proceed in the game w/o passing this part in the game. Plz help!!! :( 

-have tried tapping arrow keys, adjusting "key repeat" & "delay until repeat" in Mac keyboard settings, holding down modifier keys while pressing arrow keys

**Comment by clobber** [comment]
WIP ports are strictly unsupported. Go use Dolphin instead.
