### ISSUE TITLE
Daily Log feature similar to Wii U

### ISSUE THREAD

**Issue by ryanproud** [OpenEmu/OpenEmu#3471]
It would be nice to have a feature which tracked your time in each game.  Something similar to the Wii U Daily Log (http://en-americas-support.nintendo.com/app/answers/detail/a_id/1273/~/daily-log-overview).

**Comment by clobber** [comment]
Not useful enough or worth the effort. In list view you can see the total time a game has been played, but we won’t expand it beyond that.
