### ISSUE TITLE
Frame Rate low in fullscreen on MacBook Pro

### ISSUE THREAD

**Issue by jetbootjack** [OpenEmu/OpenEmu#3472]
Hi,

Using the latest release (v2.0.6.1) I see consistent frame-rate issues in many emulators when using fullscreen on a MacBook Pro:

     MacBookPro - 14,3 (15-inch, 2017) 
     Processor - 3.1 GHz Intel Core i7
     Memory - 16 GB 2133 MHz LPDDR3
     Graphics - Radeon Pro 560 (4GB)

I thought it was the new Saturn Core (perhaps my system spec is not good enough to get this running at frame-rate) as that is what I used first in full screen - seeing a lower frame-rate with audio stuttering as the game booted (the saturn logo formation juddered and the audio stuttered as the flying shards resolved in the Saturn logo). 

So I rebooted and the logo fly-in was fine but the sonic team logo had low frame-rate and audio stuttering in full screen.

I rebooted again and tried in windowed view the logos were great and the intro movie plays fine, as long as I am not in full screen. When the game plays again - frame seems fine in windowed view, but judders with stuttering audio in fullscreen mode.

So I tried the N64 core - same results very poor performance in full screen fine in windowed view - both audio and video quality affected by the fullscreen mode.

And then I tired the Atari 5200 core and it is exactly the same - scrolling jerky in full screen and fine in windowed mode, although audio seemed fine.

Likewise in Megadrive and SNES - fullscreen has frame-rate issues windowed is fine...

sTeVE

**Comment by clobber** [comment]
I cannot replicate this on a slightly older MBP with Intel Iris Pro+Radeon R9 M370X 2 GB. For me there is no performance difference in windowed vs fullscreen. OpenEmu is not using your discrete GPU anyway, but the integrated Intel HD Graphics 630 (unless you manually forced the discrete with something like gfxCardStatus). So there could be a driver bug problem, resource problem with other apps running, or an issue with a filter you may be using and/or the screen resolution.

Switch to the "Nearest Neighbor" filter and see if that makes a difference. Also want to make sure you are running 10.13 High Sierra if you're not already.

**Comment by robotoad** [comment]
I also can't replicate this on an early 2013 MBP with Intel HD Graphics 4000/GeForce GT 650M.

**Comment by jetbootjack** [comment]
Hi,

Thanks for the replies...

I am using nearest neighbor as my filter, the laptop is running 10.13.2. Screen resolution is default for the inbuilt retina panel on the MBP - I am not using an external display.

I can see no apps taking significant resources aside from OpenEmu - but I will disable spurious ones to see if there is any conflict.

I will also compare against my older launch model retina 2012 MBP which has a 650M gup...

I also looked around to see if any other apps were reporting similar issues and see a few reports like these:

https://illustrator.uservoice.com/forums/601447-illustrator-bugs/suggestions/20384572-high-sierra-macos-10-13-gpu-rendering-issues-i

And

https://discussions.apple.com/thread/8122451

Suggesting that disabling gpu switching may fix “known” slow down on new MBP...

sTeVE

**Comment by jetbootjack** [comment]
Okay - it’s an Apple thing :-)

Forcing the AMD GPU and disabling switching seems to have “cured” the issue...

Whatever the OS/driver issue is it is a feature of the latest MacOS 10.13.2 - and I’ve not seen any acknowledgement from Apple over the issue - so I will be chasing them as my MBP is only 4 months old and I expect it to work as designed!

sTeVE
