### ISSUE TITLE
All my N64 Game are SUPER slow ! 

### ISSUE THREAD

**Issue by thib5** [OpenEmu/OpenEmu#3473]
Hi ! On my Mac mini my N64 game run super slow. I don't understand it was working well like a month ago... I try to install openemu on my Macbook air and the game was running fine ...
here some info :
I tried to reinstall it or install an earlier version ...
I change my HDD for an SSD...
I tried to change the filter...
My playstation game for fine ??
My Mac mini is a mid 2011 2,3 Ghz i5 with 16gb of RAM with hight Sierra ( 10.13 ) running on a SSD
Thanks

p.s yes I post my issue on redit to but my kids are really sad and I'm really trying hard to find why it does that

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3447
