### ISSUE TITLE
N64 frame rate issues

### ISSUE THREAD

**Issue by DemonicGames** [OpenEmu/OpenEmu#3474]
after the latest update, all of my N64 games' frame rate dropped low enough to the point that I cannot play them anymore. I've closed out of everything so that only OpenEmu was open, but it still has problems. I don't know what the problem is, due to the fact that it worked fine before the update

**Comment by robotoad** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3447
