### ISSUE TITLE
Nintendo Switch Pro Controller analog range trouble

### ISSUE THREAD

**Issue by Marszene** [OpenEmu/OpenEmu#3475]
Hi, I've read a lot about this subject but I haven't found a real solution yet.

The analog sticks of my Switch Pro Controller doesn't have a proper response with the PSX emulator (I have tried 3 games and all of them has the same issue so it's an issue with the controller for sure; I haven't tried if the other consoles have the same issue because at the moment I'm only interested in PSX emulation).
I'm on a MacBook Pro 13" 2016 with Sierra.

It's like they can't reach the full range of motion (es. the character walks instead of running; the car doesn't turn enough etc.)

I know that Nintendo uses non-standard values for its analog sticks and it's difficult for you to set the proper range, but is there a solution to fix this issue? Please help, I would like to avoid having to buy another controller...

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3102

**Comment by clobber** [comment]
If this were fixed, the original issue would be closed and obviously you wouldn't be having trouble. It seems like you knew about this, so what is the point of opening a new issue?
