### ISSUE TITLE
'Stop Emulation' exits full screen but does not close emulator

### ISSUE THREAD

**Issue by spamguy** [OpenEmu/OpenEmu#3479]
I had been building OpenEmu from source for awhile, but for a variety of reasons I opted to do a clean install of the official 2.0.6.1 build.

Starting new emulators is still OK. Regardless of which emulation I'm running, though, the 'Stop Emulation' button in the HUD produces odd behavior. For years I've been used to the button minimizing and then closing the emulation window, leaving only the OpenEmu browser. As of this version, the app only minimizes the emulator and freezes action, but does not close it. There are no UI options to close it manually. Luckily command-W works and everything's fine from there.

Example outcome after stopping emulation:

![screen shot 2018-01-02 at 11 00 12 pm](https://user-images.githubusercontent.com/5761012/34509664-69e22ff2-f012-11e7-9244-6d9c273ce20f.jpg)

**Comment by clobber** [comment]
Minimizing? I'm not aware of stopping emulation ever doing that and don't know what your screenshot is supposed to demonstrate. Stopping emulation simply ends the helper app process and closes the window if you are playing in the popout window. Anyway, I cannot replicate what you are describing with OpenEmu 2.0.6.1 on macOS 10.13.2, so I guess you will have to provide more clear details with condition/steps to reproduce the issue.

**Comment by robotoad** [comment]
Your use of the term "minimize" is causing some confusion. On macOS, minimizing a window means shrinking the window (usually by clicking the yellow minus button) and having it appear on the Dock as a thumbnail. I'm assuming the problem you're describing here is that you play games in a popout window, and the popout window hosting the gameplay has disappeared yet the gameplay is still visible (this is what appears to be happening in your screenshot).

Just a guess: when you built the app in the past, did you also build cores? If you delete the cores in `~/Library/Application Support/OpenEmu/Cores/` and redownload them, does the issue resolve?

**Comment by spamguy** [comment]
Yeah, I agree 'minimize' was an inaccurate description. I don't think there really is a single word that describes it. The emulator exits full screen, shrinks a bit to the size you see in the screenshot, then action within the window freezes.

I did use manually built cores for awhile. The clean install I performed did involve me flushing the cores out of Application Support. At least, I think. I'll try another clean install in a bit to see what happens.

**Comment by clobber** [comment]
>The emulator exits full screen, shrinks a bit to the size you see in the screenshot, then action within the window freezes. 

Why didn't you describe that the first time? Important details matter. The bug, which I can now replicate, is as follows:
1. Open a game.
2. Select View > Undock Game Window (or have "Always use popout gameplay window" checked in Gameplay Prefs).
3. Click the "Toggle Fullscreen" button on the HUD bar.
4. Click the "Stop Emulation" button on the HUD bar.

Game will exit fullscreen and shut down, but the window will remain.

**Comment by spamguy** [comment]
> Why didn't you describe that the first time? Important details matter.

Sorry. I read and write bug tickets for a living, but this time I blew it. I guess I think of full screen emulation as a given.

**Comment by danilobytes** [comment]
Does this issue fix/address the related behavior shown on the following image?

<img width="701" alt="screen shot 2018-03-22 at 12 49 35" src="https://user-images.githubusercontent.com/7675806/37781578-b8a8a7e2-2dcf-11e8-929c-9197fb90dec2.png">

That occurs when stopping a game (full screen or not). Its actual window gets closed but that "invisible" one stays there. And it keeps adding more of them if I open and close other games (or the same one). If I close OpenEmu main window they won't go away, so I have to quit OpenEmu altogether to clear them up.

**Comment by robotoad** [comment]
@danilobytes That issue is fixed for next release.
