### ISSUE TITLE
Saturn (medafen): "Unsuitable Disc" with only some U.S. roms. Other U.S. roms work fine

### ISSUE THREAD

**Issue by glow162** [OpenEmu/OpenEmu#3480]
Using the Saturn (Medafen) emulator, for some U.S. roms (see ***update*** at the bottom), it tries to boot it using the Japanese bios, and therefor, just boots to the Saturn's menu and won't start, saying "unsuitable disc".

(i.e. just like a Japanese Saturn would if you put a U.S. game in there).

However, for other U.S. roms, it boots properly with the U.S. bios.

(for example, when I boot my U.S. version of Burning Rangers, it boots with the U.S. bios and works just fine.  But when I boot my U.S. version of NiGHTS, it tries to boot it with the Japanese bios, and obviously doesn't work).
[Both Games are proper CUE files]

How can I get it to boot with the correct bios?

Any help is greatly appreciated.

Thanks.

  ***update***

I'm fairly positive that the only roms that have this error are ones that have been converted from .mdf / .mds   into   .cue /.bin using mdf2iso

Just for this example, I've compared (in Text Editor) the cue sheets from the newly converted NiGHTS .cue file, with another NiGHTS .cue file that, let's say, has always been a .cue file

and there is no difference between the two whatsoever; their contents are actually exactly the same.

So somehow, the act of converting to .cue from .mdf seems to cause Mednafen (through OpenEMU) to try to boot these U.S. roms with the Japanese bios.

So this might also be worth investigating on the developers end as well.

Thanks

**Comment by clobber** [comment]
These are bad rips or conversions of the games. Download other copies.

**Comment by glow162** [comment]
The only thing is though that all of these .mdf roms worked when using the Yaba Sanshiro emulator (the new UoYabause).

So I'm just throwing this out there in case the developers wanted to look into this.

Otherwise, yes issue closed.

P.S.
I absolutely love Mednafen; it's a "god amongst men" in the world of emulation, especially for the Saturn.

Never thought I'd see a day of perfect Saturn emulation on a Mac..!

Cheers to all of you guys, your work is greatly appreciated.
