### ISSUE TITLE
8bitdo Controllers Crashes OpenEmu when plugged in by USB

### ISSUE THREAD

**Issue by felkeM** [OpenEmu/OpenEmu#3482]
I used NES30 Pro and SF30 Pro plugged into USB and when I open any game from OpenEmu, it unexpectedly quits.

macOS Serria 10.12.6

**Comment by clobber** [comment]
You must've updated your firmware which changed their HID profile around. To fix your crash:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

**Comment by felkeM** [comment]
Thanks
