### ISSUE TITLE
Import save files from Yabause to Mednafen?

### ISSUE THREAD

**Issue by glow162** [OpenEmu/OpenEmu#3483]
(I can't find anything on this anywhere else)

Is there anyway to transfer my Saturn game saves from Yabause (Which is on the internal.bram file) into Mednafen? 

Perhaps a way to convert that internal.bram file into a .bkr file that Mednafen would understand?

I've tried everything I could think of, but no luck.

Any information is greatly appreciated.

Thanks

**Comment by clobber** [comment]
No, not that I am aware of and I wouldn’t trust the backup and SRAM files created by Yabause.

**Comment by glow162** [comment]
Ah okay, thanks
