### ISSUE TITLE
Nintendo Switch Joy-con.

### ISSUE THREAD

**Issue by mrcheesecat** [OpenEmu/OpenEmu#3484]
Hello! I need help in mapping my Nintendo Switch Joy-con. For clarification, I am only using one joy-con, I am connected through Bluetooth, and I would like to play games from the SNES era and below. It seems as if the program maps the analog stick with no complications. However, if I try to map the (+) (-) Keys, the shoulder buttons, or the directional keys for A B X Y, the program simply does not recognize these buttons. I see others online using the Joy-con on mac yet I am confused on why mine does not work so smoothly? I am using OS X El Capitan version 10.11.6 and OpenEmu version 2.0.6.1. Thank you.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3093
