### ISSUE TITLE
Dropbox: Duplicate save games

### ISSUE THREAD

**Issue by Sootylad** [OpenEmu/OpenEmu#3487]
Hey folks, just posting a bug. Latest version of OpenEmu, latest version of OSX.

My saves are always duplicated. So for example playing Tomb Raider on PSX, made a manual save before the famous T-Rex fight and it made two saves with the same name and thumbnail.

Strangely, if I go view in finder on those saves, only one actually exists in the file system it would seem. 

Any more info needed?

**Comment by Sootylad** [comment]
A bit of extra info... In the save states area, there can be up to four maybe five auto saves or quick saves, different dates but all with the same thumbnail and the save save point if loaded. 

Although like I said, in the file system there's only one of each.

**Comment by clobber** [comment]
This doesn't normally happen and I cannot replicate it, so you will have to figure out exact steps or conditions to reproduce the issue. I just tested with Jumping Flash! for PS1 by creating a manual save state while there previously were none:

<img width="823" alt="screen shot 2018-01-10 at 11 25 36 pm" src="https://user-images.githubusercontent.com/1303132/34809912-c7544a84-f65d-11e7-9e35-4ba077888b83.png">

**Comment by Sootylad** [comment]
Right, got there in the end.

I had it set up so that my OpenEmu folder was actually stored in Dropbox, with a symbolic link sat in the Application Support folder acting as a pointer.

This meant that at any point I could pick up a game where I left off, regardless of which computer I was on (MacBook Pro or Mac Mini plugged into the telly).

Something in this process was tripping OpenEmu up, although it all worked, this one symptom of showing duplicate save files (even though there was only one file underlying in the file system) was presenting itself. Upon disabling dropbox it all works as intended with single save games.

So there we go, OpenEmu doesn't play nicely (well, not 100% nicely) with Dropbox. I can live with that no worries :)

Fantastic software matey.
