### ISSUE TITLE
N64 game sound choppy

### ISSUE THREAD

**Issue by hizic** [OpenEmu/OpenEmu#3489]
I’ve installed open emu on a Mac book pro 15 inch with touch bar. When it’s not plugged into hdmi projecting to a Samsung tv the sound is fine. However, as soon as I plug into tv the sound is choppy. Any suggestions?

**Comment by clobber** [comment]
I don't think this is an OpenEmu bug and I cannot replicate it on an older MBP while running N64 in fullscreen through HDMI. Your integrated GPU might be having trouble running the TV's display. Sounds sort of like #3472 - recommended to switch to the discrete AMD GPU instead.
