### ISSUE TITLE
option to increase openemu font size for highres displays.

### ISSUE THREAD

**Issue by jerkstore369** [OpenEmu/OpenEmu#3490]
I have a retina macbook (most people I think would have retinas by now) with a resolution of 2880x1800. The openemu UI font is so tiny. I can barely make them out. Add option to increase the size. This is mandatory. Thanks.

**Comment by robotoad** [comment]
OpenEmu uses standard font sizes. Consider using a scaled resolution in System Preferences->Displays.

**Comment by jerkstore369** [comment]
I do use a scaled resolution. I use "looks like 1920 x 1200". Anyways, using a scaled resolution makes things look smaller so I don't know why you would recommend that when the issue I have is the test looking smaller. In any case, you don't think people would like to be able to change the font size? Honestly, this answer is so lazy and perfectly demonstrates the attitude of this project.

**Comment by clobber** [comment]
>Waaa I got an answer I didn't like so I made a sweeping generalization about your software!

I can tell you're really new to using a Mac and a piece of shit living up to your username (perused your comment history on GitHub). Using "looks like 1920x1200" is much too high a resolution, and definitely not the default for your machine. Use either 1440x900 or 1680x1050. Apps don't change fonts or widget sizes, you idiot.

**Comment by robotoad** [comment]
<img width="361" alt="screen shot 2018-01-13 at 2 48 50 am" src="https://user-images.githubusercontent.com/238567/34904930-8016b372-f80c-11e7-967e-042fef723e3c.png">
