### ISSUE TITLE
Sega CD - try to open game, but it loads the 'play music CD' menu

### ISSUE THREAD

**Issue by CastleAlucard** [OpenEmu/OpenEmu#3492]
The three required SEGA CD BIOS are installed, and I imported a game via a plain text cue sheet. When I load the game the Sega CD screen appears (ver. 1.10), and says press start. Yet when I press start, it loads the 'Sega CD music player' instead of the game. I've tried this with multiple games, made new cue sheets according to the instructions, but I can't load any Sega CD games. Any suggestions?

**Comment by clobber** [comment]
>Any suggestions?

Sounds like a bad rip to me, so download another copy.

**Comment by digamejh** [comment]
This happens with me occasionally too.

In addition to clobber's advice above, if you are using a BIN/CUE pair make sure the .cue file is in the right format; even a stray character can cause it to not work.  See https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games
