### ISSUE TITLE
7z to nds file

### ISSUE THREAD

**Issue by mpfol** [OpenEmu/OpenEmu#3494]
I used the unarchiver to unzip the 7z file, but I can't seem to find a .nds file in the folder
Instead, the folder is named "LAYTON1 (A5FE by HF)" (Layton one referring to the game i'm trying to play). Inside the folder there are not any .nds files, but there is a .ovt and a .bin file along with several .txt files. Additionally, there is a folder called datafiles which has several other folders inside it
Running on OpenEmu v2.0.5 and macOS Sierra v10.12.6
I apologize if this is a silly question or if I did not provide enough information, I have next to no technical experience

**Comment by clobber** [comment]
Redownload the original file. You unzipped a .nds file that was renamed with the file extension .7z.
