### ISSUE TITLE
Games not showing up

### ISSUE THREAD

**Issue by aidanthegamer5** [OpenEmu/OpenEmu#3495]
Hi, I'm somewhat new to this emulator, so I'm a bit unsure about how things work. I tried to add a PSX game to my collection [removed], and when I went to add the files in, the game wouldn't show up. I made sure I had the BIOS files, and tried again. I even downloaded a different file altogether [removed], but that didn't work either. Can someone put me on the right path?

Oh, and for clarity's sake, I'm using a **_Mac_**, not a Windows computer.

**Comment by clobber** [comment]
Checked the second file and the contents of the cue sheet is incorrect. You will find information in the guide.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."
