### ISSUE TITLE
Old Xbox one controller mapping issues

### ISSUE THREAD

**Issue by JackStay** [OpenEmu/OpenEmu#3496]
When trying to map my xbox one controller it keeps changing from player 1 to player 2, leaving me unable to properly map the buttons. It also comes up with 2 options when choosing the controller. It shoes me 'Microsoft official wired' and 'xbox one wired controller'. This also keeps switching between the two. How can i fix this?

**Comment by Cruplezone** [comment]
this is definitely an issue with whatever driver you're using, not openemu. xbox one is not natively supported on macOS over usb. The Bluetooth version works great! Hook it up over BT if you can.

**Comment by clobber** [comment]
Yep sounds like a driver issue. You should only need to fiddle with the dropdown menus to first select "Player 1" and then the device you want to map for (bottom dropdown menu) and then set the mappings.
