### ISSUE TITLE
Suddenly Arcade games freeze after launch!

### ISSUE THREAD

**Issue by jeansebastienbg** [OpenEmu/OpenEmu#3497]
I had everything working for a god while and I remember playing arcade games fairly recently. I don't know if I updated the core or if I did something in particular, but today I tried to launch a game and all the arcade games freeze immediately after launching. I can't "power off" the emulation or quit OpenEmu. I need to force close OpenEmu to restart it. Here's an error message I can see in the console:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OERingBuffer freeBytes]: unrecognized selector sent to instance 0x7f817b79b170'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffc0f9f2cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffd5db948d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffc1020f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fffc0f11755 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fffc0f112a8 _CF_forwarding_prep_0 + 120
	5   MAME                                0x000000000dd1d1b9 -[MAMEGameCore osd_update_audio_stream:samples:] + 105
	6   MAME                                0x000000000fda5afa _ZN13sound_manager6updateEPvi + 682
	7   MAME                                0x000000000fd97bfc _ZN16device_scheduler14execute_timersEv + 364
	8   MAME                                <…>

Here are two error messages preceding this one that also seem unusual:
Refresh rate set to 59.185606 Hz
-[OERingBuffer freeBytes]: unrecognized selector sent to instance 0x7f817b79b170

**Comment by clobber** [comment]
Use OpenEmu 2.0.6.1 and he latest release of the MAME core plugin, which is 0.149.2.
