### ISSUE TITLE
Couldn't Find the /Application Support/OpenEmu

### ISSUE THREAD

**Issue by AntoineWeis** [OpenEmu/OpenEmu#3498]
## Hey There
I got issue locating the folder in my library here is a screen shot. ( "Blibliothèque" is french for Library by the way )

<img width="591" alt="capture d ecran 2018-01-23 a 19 04 04" src="https://user-images.githubusercontent.com/22632558/35292258-400bf5b4-0070-11e8-9011-d9ca9d595c41.png">

It's pretty weird so i decided to do the good old way with code !

<img width="567" alt="capture d ecran 2018-01-23 a 19 08 15" src="https://user-images.githubusercontent.com/22632558/35292456-d1f32e34-0070-11e8-8e5c-3be7964db534.png">

_I can see the good folders here, is it a problem around permissions ?_

How can i solve it ? In order to access to this folder with the Finder.
Is it an hidden folder ?

I do my best searching the issue with the old topics but i'm a bit new to unix prompt etc...

Thx for reading me

**Comment by robotoad** [comment]
In the first screenshot, you're browsing the system-wide Library folder instead of your personal Library folder, which you accessed in the second screenshot. To browse your personal Library folder in Finder, select the Go menu and hold the option key to reveal the "Library" menu item.
