### ISSUE TITLE
GBA Core issue; recently installed core gives "cannot communicate" error

### ISSUE THREAD

**Issue by MikeL224** [OpenEmu/OpenEmu#3499]
I just installed the cores for the GBA emulator on version 1.0.4, but upon trying to open a rom, I'm given the message "cannot communicate with helper application."  I tried to find a previous solution, but all threads link back to this comment: https://github.com/OpenEmu/OpenEmu/issues/1460#issuecomment-46348553

which has had its instructions deleted.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
