### ISSUE TITLE
OpenEmu not loading newer ROMs

### ISSUE THREAD

**Issue by bandsworth** [OpenEmu/OpenEmu#3500]
I have been able to download and play some older games like Mario 64 and older, but when I try to download games for something like the PSP, the files just download blank or something and when I try to open them in OpenEmu, it just says "game scanner" for a little bit and turns off. Just curious as to why this is happening. Thanks

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..." and "Include Console and crash logs, macOS and OpenEmu version, hardware information, ROM/game filenames, etc."

**Comment by clobber** [comment]
Closing for lack of info.
