### ISSUE TITLE
Unable to use in-game the second/third controllers.

### ISSUE THREAD

**Issue by timonoj** [OpenEmu/OpenEmu#3501]
Hi! I have the following issue:

I have 3 gamepads, 1 logitech F710 and 2 PS4 DualShock Controllers. I use Windows 10. I can map each of them individually in CEMU as 3 different Wii U Gamepads. Each of them gets their buttons assigned, corresponding to the real gamepads buttons. Everything looks good. But then in-game, only the first gamepad defined will work. Even though the other two are recognized in the input settings, they don't work at all in-game. If I remap a different controller as first controller, again, that first one will work, and the other two will be ignored in-game.

Please help!

**Comment by clobber** [comment]
>I can map each of them individually in CEMU as 3 different Wii U Gamepads

This is OpenEmu.
