### ISSUE TITLE
openEMU freezes after opening Rom

### ISSUE THREAD

**Issue by rubent8** [OpenEmu/OpenEmu#3502]
After my rom opened It froze and I can't close anything

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..." and "Include Console and crash logs, macOS and OpenEmu version, hardware information, ROM/game filenames, etc."

**Comment by clobber** [comment]
Closing for lack of info.
