### ISSUE TITLE
Something with Nintendo Switch Pro Controller repeatedly takes screenshots, overheating computer

### ISSUE THREAD

**Issue by Keebinz** [OpenEmu/OpenEmu#3503]
This is on the latest version of OpenEmu, 2.0.6.1, and I am using an early 2011 MacBook Pro, with MacOS High Sierra 10.13.2. 
With my Nintendo Switch Pro Controller, I was setting up my controls, and i was trying to set quick save to left stick click. For some reason, it immediately started to constantly inputting left analog down, therefore mapping everything below it to this. Since screenshot is the last one, it set that to left analog down, and started taking screenshots at an excruciatingly fast rate, and I didn't realize something was up until I noticed that my laptop started overheating, and saw a grey square repeatedly flashing in the top right corner of the screen. I was eventually able to resolve the issue, [pro tip: hold up on the left stick and enter the controls menu, go down to screenshot, let go and quickly press something else, like a button.] but I am concerned for anybody who accidentally triggers this and doesn't realize it, as the constant screenshots may quickly fill up computer storage, and it might overheat the computer. I'd suggest doing something about that, like setting something that wouldn't be as CPU-intensive as the last control. To replicate this, all I did was try to configure something as left stick click, using a Nintendo Switch Pro Controller. Actually, just now, I tried to replicate it. I just clicked on an option, and it immediately started putting in left analog down. I knew what was happening this time, so only 31 screenshots were taken, but when this first happened, it took me a minute or two to figure out what was going on and how to fix it, and I ended up with over 1,000, maybe 2,000 screenshots after everything was done! This could potentially be a big problem, so I thought I'd let you know. 
...I wish that I could type this well and this quickly on papers for school...

**Comment by clobber** [comment]
Many analog gamepads are constantly sending input events, despite being in 'rest' positions. Nothing we can do about that. For this reason, 'special' keys such as one set to take a screenshot should never be mapped to an analog direction.

**Comment by Keebinz** [comment]
Ok thanks
