### ISSUE TITLE
Can't open stuff.

### ISSUE THREAD

**Issue by Stevo1244** [OpenEmu/OpenEmu#3504]
Hey, I've looked at other people's problems, tried to apply that to the program, nothing worked.

My problem is that I can't open any games what so ever. DS games, n64 Games, all that good stuff. I double click it and if I'm lucky the blue outline vanishes or greys out.

This problem occured when I transferred my Mac to a storage device and rebooted it.
I'm super sorry if this problem was already resolved and I'm just being blind.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..." and "Include Console and crash logs, macOS and OpenEmu version, hardware information, ROM/game filenames, etc."

**Comment by Stevo1244** [comment]
I'm not really sure how to be more specific than 'I click it and nothing happens'. No error messages either.
This is what my Log looks like after I click:
default	20:33:15.321943 +0000	OpenEmu	TIC TCP Conn Cancel [19:0x6000003894b0]
default	20:33:15.322282 +0000	OpenEmu	TIC TCP Conn Cancel [22:0x60800038bef0]
default	20:33:15.322554 +0000	OpenEmu	TIC TCP Conn Cancel [20:0x60000039ab60]
default	20:33:15.322696 +0000	OpenEmu	TIC TCP Conn Cancel [23:0x60800038bd50]
default	20:33:15.322816 +0000	OpenEmu	TIC TCP Conn Cancel [24:0x60800038ca50]
default	20:33:15.322866 +0000	OpenEmu	TIC TCP Conn Cancel [21:0x60800038bfc0]
default	20:33:15.323164 +0000	OpenEmu	TIC TCP Conn Destroyed [19:0x6000003894b0]
default	20:33:15.323308 +0000	OpenEmu	TIC TCP Conn Destroyed [22:0x60800038bef0]
default	20:33:15.323360 +0000	OpenEmu	TIC TCP Conn Destroyed [20:0x60000039ab60]
default	20:33:15.323391 +0000	OpenEmu	TIC TCP Conn Destroyed [23:0x60800038bd50]
default	20:33:15.323428 +0000	OpenEmu	TIC TCP Conn Destroyed [24:0x60800038ca50]
and my Mac is a macOS Sierra Version 10.12.6, OpenEmu is at 2.0.6.1.
The games I have on there are Kirby 64, Kirby Mass Attack, Mario Party 3 and Super Mario 64 ds. Non of them are openable and there's no error messages.

**Comment by clobber** [comment]
I'm not sure that is the full log. Anyway, you said: "I transferred my Mac to a storage device" - what do you mean by this? It sounds like you made a file system change and OpenEmu cannot find your Library after manually moving it, and if that is the case you should have a warning about that.

**Comment by Stevo1244** [comment]
I've moved my entire home folder to a storage device so I could have a terrabyte's worth of memory rather than 120 gigabytes, and that's all there is to the log that's for the OpenEmu software.
I've tried reinstalling it but it remembers  it's previous state.

**Comment by clobber** [comment]
Okay, that should explain it. I'd recommend moving your OpenEmu folder back to its original location and then using OpenEmu > Preferences > Library to change the Game Library folder location. Otherwise, if you just want to start over you can run the following command in Terminal.app to delete OpenEmu's preferences: `defaults delete org.openemu.OpenEmu`

**Comment by Stevo1244** [comment]
Nothing is still happening, but thanks anyway.
