### ISSUE TITLE
font size

### ISSUE THREAD

**Issue by dyeinafyre** [OpenEmu/OpenEmu#3505]
@clobber 
> Waaa I got an answer I didn't like so I made a sweeping generalization about your software!
> 
> Feel free to generalize about me, though. I can tell you're really new to using a Mac and a piece of shit living up to your username (perused your comment history on GitHub). Using "looks like 1920x1200" is much too high a resolution, and definitely not the default for your machine. Use either 1440x900 or 1680x1050. Apps don't change fonts or widget sizes, you idiot.

Ironic, the guy claiming I made a generalization makes a generalization. I've been using Macs for years. I know plenty of apps that let you change the font size of the app.

Yes, I'm fully aware that my resolution isn't standard. Thanks for that. Guess what? I like it high. It's purely subjective. What in anything I wrote made you think I'm not aware of this? I'll be god damned if I spend $3k on a machine and not gain any screen real-estate. Besides, I need it for the work that I do.

My request was simple. To cater to those who chose to use high resolution settings. If you don't want to or believe not enough people do this to warrant the effort, I'd have tons more respect for you. And you telling me I'm using my mac wrong based on a purely subjective setting shows that I was right all along. You are a lazy, fat, cheetos eating pig sack of shit.

@robotoad 
Thanks for assuming I'm a moron like you.

**Comment by clobber** [comment]
Lol at registering a new account to try and get the last word. Psychotic.
