### ISSUE TITLE
Option to disable automatic core update

### ISSUE THREAD

**Issue by o-kniejski** [OpenEmu/OpenEmu#3508]
Since i can not find any way to disable automatic core updates, i am stuck with turning off my internet connection to enjoy a round of mupen64plus 2.5.3 with my older machine (since the latest update it stutters dramatically). And if i forget this step, additionaly copying the core again.

So, therefore i propose the addition of an enable-core-autoupdate-checkbox in the settings or at least the secret settings panel.

**Comment by clobber** [comment]
Not something we are going to add for a number of reasons. The issue with N64 is due to older GPU's, which may improve in the future. Just work around it by downloading the old core plugin that works for you and bumping the version number inside the plugin bundle.
