### ISSUE TITLE
How to create a Save File?

### ISSUE THREAD

**Issue by AnasShaikh24** [OpenEmu/OpenEmu#3509]
I tried to look in Library, Application Support, but then there wasnt a folder for openemu. Can somebody help me please?

**Comment by clobber** [comment]
>How to create a Save File?

In-game battery/mem card/save files are created automatically for games that have them. Bear in mind these are **not** the same thing as a Save State. Like most Mac apps, OpenEmu keeps its files in the user `~/Library/Application Support` folder, which is not the same as the root `/Library/Application Support`. There is very little reason to need to access this, so if you do, be careful not to break your OpenEmu installation. You can access it via:

`~/Library/Application Support/OpenEmu` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)

**Comment by AnasShaikh24** [comment]
Ya that's where I went. But there wasn't a OpenEmu folder. So where could have it gone?

**Comment by clobber** [comment]
Read my last sentence very closely and click the link.
