### ISSUE TITLE
OpenEmu Crahses Upon Either Opening Game or Preferences.

### ISSUE THREAD

**Issue by Yoshifan1219** [OpenEmu/OpenEmu#3510]
_This just happened today (as of this being posted), and I don't know why. I'm running this on Mac Mini. I downloaded the latest version and tired it out as well and that didn't change a thing either.
The games I was trying to load were Sonic 1, 2, 3K, & 3C. (Note I changed the Name & replaced them with #'s, because privacy reasons.)
I'm just gonna post the error code from the Terminal I got._

> Last login: Tue Jan 30 16:02:21 on console
> #####'s-Mac-mini:~ #####$ /Users/#####/Downloads/OpenEmu.app/Contents/MacOS/OpenEmu ; exit;
> defaults delete org.openemu.OpenEmu
> 2018-01-30 16:30:00.218 OpenEmu[915:67739] OELibraryDatabase loadFromURL: 'file:///Users/#####/Library/Application%20Support/OpenEmu/Game%20Library/'
> 2018-01-30 16:30:02.502 OpenEmu[915:67739] window did load
> 2018-01-30 16:30:03.098 OpenEmu[915:67739] Bluetooth keyboard
> defaults delete org.openemu.OpenEmu
> 
> 2018-01-30 16:30:11.160 OpenEmu[915:67739] SETUP DONE.
> 2018-01-30 16:30:11.229 OpenEmu[915:67739] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: OEGlobalButtonQuickLoad)'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fff3768e00b __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x00007fff5e319c76 objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff376cf514 _CFThrowFormattedException + 202
> 	3   CoreFoundation                      0x00007fff3759129c -[__NSDictionaryM setObject:forKey:] + 1020
> 	4   OpenEmuSystem                       0x000000010a072fed __60-[OESystemBindings OE_stringValuesForBindings:possibleKeys:]_block_invoke + 216
> 	5   CoreFoundation                      0x00007fff37606192 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 226
> 	6   OpenEmuSystem                       0x000000010a072ed3 -[OESystemBindings OE_stringValuesForBindings:possibleKeys:] + 203
> 	7   OpenEmuSystem                       0x000000010a0706ea __64-[OESystemBindings OE_setUpKeyboardBindingsWithRepresentations:]_block_invoke + 357
> 	8   CoreFoundation                      0x00007fff37627608 __NSArrayEnumerate + 536
> 	9   OpenEmuSystem                       0x000000010a070568 -[OESystemBindings OE_setUpKeyboardBindingsWithRepresentations:] + 211
> 	10  OpenEmuSystem                       0x000000010a0700fc -[OESystemBindings OE_initWithBindingsController:systemController:dictionaryRepresentation:] + 528
> 	11  OpenEmuSystem                       0x000000010a06ca48 -[OEBindingsController OE_registerSystemController:] + 233
> 	12  OpenEmuSystem                       0x000000010a06c61c -[OEBindingsController OE_setupBindingsController] + 245
> 	13  OpenEmuSystem                       0x000000010a06c0ee __50-[OEBindingsController initWithConfigurationName:]_block_invoke.54 + 281
> 	14  libdispatch.dylib                   0x00007fff5eecfd50 _dispatch_client_callout + 8
> 	15  libdispatch.dylib                   0x00007fff5eee31d6 _dispatch_queue_barrier_sync_invoke_and_complete + 60
> 	16  OpenEmuSystem                       0x000000010a06be84 -[OEBindingsController initWithConfigurationName:] + 417
> 	17  OpenEmuSystem                       0x000000010a06bb8b __49+[OEBindingsController defaultBindingsController]_block_invoke + 41
> 	18  libdispatch.dylib                   0x00007fff5eecfd50 _dispatch_client_callout + 8
> 	19  libdispatch.dylib                   0x00007fff5eecfd03 dispatch_once_f + 41
> 	20  OpenEmuSystem                       0x000000010a06bb5f +[OEBindingsController defaultBindingsController] + 45
> 	21  OpenEmu                             0x0000000109cfd7c5 __49-[OEGameDocument setupGameWithCompletionHandler:]_block_invoke_2 + 362
> 	22  libdispatch.dylib                   0x00007fff5eed7591 _dispatch_call_block_and_release + 12
> 	23  libdispatch.dylib                   0x00007fff5eecfd50 _dispatch_client_callout + 8
> 	24  libdispatch.dylib                   0x00007fff5eedb32d _dispatch_main_queue_callback_4CF + 1148
> 	25  CoreFoundation                      0x00007fff376467a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
> 	26  CoreFoundation                      0x00007fff376089ca __CFRunLoopRun + 2586
> 	27  CoreFoundation                      0x00007fff37607d23 CFRunLoopRunSpecific + 483
> 	28  HIToolbox                           0x00007fff3691fe26 RunCurrentEventLoopInMode + 286
> 	29  HIToolbox                           0x00007fff3691fb96 ReceiveNextEventCommon + 613
> 	30  HIToolbox                           0x00007fff3691f914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
> 	31  AppKit                              0x00007fff34beaf5f _DPSNextEvent + 2085
> 	32  AppKit                              0x00007fff35380b4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
> 	33  AppKit                              0x00007fff34bdfd6d -[NSApplication run] + 764
> 	34  AppKit                              0x00007fff34baef1a NSApplicationMain + 804
> 	35  OpenEmu                             0x0000000109dd9a39 main + 9
> 	36  libdyld.dylib                       0x00007fff5ef09115 start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> Abort trap: 6
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> Deleting expired sessions...7 completed.
> 
> [Process completed]
> 
>

**Comment by clobber** [comment]
To fix your crash:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.
