### ISSUE TITLE
Openemu monkey hero gameplay freeze

### ISSUE THREAD

**Issue by fabsalone** [OpenEmu/OpenEmu#3513]
Details of issue: the game monkey hero opens as per normal with PS1 start screen and goes onto monkey hero loading screen then plays fmv cutscene. Then it goes to a still screen which you have to press start and then it goes to a hub screen where you control the character. this hub screen is where the game freezes but the music continues to play as per normal. the game freezes as soon as you press any control buttons either on the keyboard or on a gamepad. it will also freeze if you dont press any button after about 3 seconds (player character stops flashing then freezes). 

please let me know if you can find a fix for this issue.

details of my computer and programs/files being used:
I have  mac os high sierra v 10.13.2. openemu v 2.0.6.1, the mednafen v 0.9.48 core for PS1 games, system files for mednafen are scph5500.bin, scph5501.bin, scph5502.bin, the game downlaod is a .7z file and then i use unarchiver to get the .cue file Which i drag into openemu. the file was downloded from coolroom.com. i have also tried with mutliple downloads from mutliple rom sites and same issue happens thats why i think it might be an issue with openemu. I tried looking for a crash report but it looks like this problem is not generating a crash report. unfortunately i cant attach the game file im using but you can just download from link here http://coolrom.com/roms/psx/38973/Monkey_Hero.php

**Comment by clobber** [comment]
This is a known bug with Mednafen. There is nothing you can do to fix it.

https://forum.fobby.net/index.php?t=msg&goto=1786&

**Comment by fabsalone** [comment]
I was just wondering if its possible for me to try this solution you wrote about on https://github.com/OpenEmu/Mednafen-Core/blob/master/mednafen/psx/notes/PSX-TODO  

 " It's straddling a framebuffer write command's parameters across two linked-list
	blocks(2 words at the end of the first block, and 1 word at the beginning of the next block).  AFAIK, this construct will only
	work on the real thing under *very* strict timing constraints.  Probably explains why it reportedly doesn't work on the PS2.
	It's as easy to fix as changing a certain 2 to a 3 in the GPU command table, and probably won't break anything,
	but I'm still reluctant to do it...

**Comment by clobber** [comment]
No. Those are just notes from Ryphecha, the author of Mednafen. Do not expect this game working any time soon.
