### ISSUE TITLE
How to access memory card saves from a 'different' game?

### ISSUE THREAD

**Issue by shinsukato** [OpenEmu/OpenEmu#3514]
I was playing Final Fantasy 7 (PSX), got part way through the game and then patched the .bin files with the retranslation project. In order to get openemu to recognise the new files, I had to 'delete' the game from the openemu library and drag the m3u file over again, but now all the save states and memory card files are gone.

Is there a way for me to get either those save states or those memory card files back?

**Comment by shinsukato** [comment]
I tried going through on the 'new' game, saving, and then replacing the .mcr files in the battery saves folder with the old ones, renamed, but somehow even after doing that only the 'new' saves are available.

**Comment by clobber** [comment]
All you would have originally needed to do is not restore your game from an autosave or save state file. Anyway, if you follow these steps exactly you can probably do it:
https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing#transfer-your-save-data
