### ISSUE TITLE
Trying to add cheat in XML-file

### ISSUE THREAD

**Issue by Kecki8472** [OpenEmu/OpenEmu#3516]
Hi everybody!

After reading about the cheats-DB-XML-file in another issue, I thought this might be a solution to save cheats. OK, not as comfortable as it were with an implemented function in OpenEmu itself, but at least A solution...
So I tried and added some cheats to the XML, but when I started the game, they were still not displayed. Here's what I entered into the XML:

		<game title="Teenage Mutant Ninja Turtles II - The Arcade Game (USA)">
			<hashes>
				<hash md5="e5f71b547f6a8c6166c55b1baa7d21c5" />
			</hashes>
			<cheats>
				<cheat code="AAEAULPA" type="Game Genie" description="Infinite Lives" />
				<cheat code="PEXTKZZE" type="Game Genie" description="More powerful Weapon" />
			</cheats>
		</game>

I have to admit that I never was a good programmer or script-writer.
So, am I totally wrong, and adding cheats is also this way not yet possible?
Or did I do something wrong in the XML?
The only line that made me worrying was the <hashes> line. May this value be wrong? But if so, were do I get the info that tells me which hashes-value is appropriate to which game??
The codes I tried here definitely work. Before editing the XML I tried them out via the "normal", not saving way via the options-menu inside the emu.

If that was a totally wrong idea by my side, please forgive. Then I guess I'll need to wait for an update-version that saves that stuff...
OK, looking forward to a reply.
All the best
Kecki

**Comment by clobber** [comment]
That XML file was only for testing UI functionality and API for the future cheats system and is unsupported. Do not use.
