### ISSUE TITLE
Snes/Superscope - Bazooka Blitzkrieg (USA) / Wrong crc

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/OpenEmu#3518]
Should be _49c187f3_ instead of 6810aa95 (SNESGameCore.mm)

**Comment by clobber** [comment]
No it's not wrong, you have a bad dump. Probably with a 512-byte SMC copier header.

http://datomatic.no-intro.org/?page=show_record&s=49&n=0211

**Comment by PlutoX86** [comment]
I see. It's just one of the most available dumps out there.. but hey.. who doesn't love blisters! Thx anyway
