### ISSUE TITLE
Suggestion: include region in game list in case there are two of them

### ISSUE THREAD

**Issue by msikma** [OpenEmu/OpenEmu#3520]
A fair number of games have the same title regardless of region. Currently, when importing the same game from two regions leads to ambiguity in the games list:

<img width="507" alt="screen shot 2018-02-09 at 01 09 20" src="https://user-images.githubusercontent.com/1507745/36005026-e2b27fc8-0d35-11e8-9e0e-e4ee1769ec2b.png">

To me personally it's not such a big problem since I always use the grid view, which displays the cover:

<img width="496" alt="screen shot 2018-02-09 at 01 08 09" src="https://user-images.githubusercontent.com/1507745/36005011-d293764c-0d35-11e8-990e-51ce94071b00.png">

It would be nice, though, to add (USA) or (Japan) after the title in cases like this. Personally I think it isn't necessary to do this for all games, just for the ones that appear in the list twice.

**Comment by clobber** [comment]
A long time ago we decided that cover art was good enough to distinguish between games. Since it's not worth the effort or useful enough to implement this, the follow solutions are available:

1. View > Show ROM Names

2. Right click game > Rename, to add a region suffix.
