### ISSUE TITLE
Xcode configuration when building from source code

### ISSUE THREAD

**Issue by MyopicVisage** [OpenEmu/OpenEmu#3521]
In attempting to compile the source with the experimental cores I experienced the error:
"
** BUILD FAILED **

The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal x86_64
(2 failures)
"
Is there a configuration file I can reference when building? Or arguments I should add to reference specific version of Swift or Swift Libraries? I am running Xcode version 8.1.

**Comment by clobber** [comment]
To compile OpenEmu from source, the latest version of Xcode is required among other things. Read the guide. https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide
