### ISSUE TITLE
open emu 1.0.4 couldn't communicate with helper application 

### ISSUE THREAD

**Issue by joedaghr** [OpenEmu/OpenEmu#3524]
want to start by saying that I'm not a computerry genius type guy, i just loves the emulators. dreamt of multi platform my whole life, then i found open emu. i fell in love. then i filled my computer with way too much "stuff"
      it all started when i tried to move openemu to an external hard drive. i pulled all roms from the app folder moved them to desktop; deleted open emu and reinstalled on hard drive thats when it started "couldn't communicate with helper application"
i have been able to play atari 2600, gameboy and nintendo but none of the other emus seem to "communicate with helper application"so i read other faqs on this and 
           -tried reinstalling on my computer once again "couldn't communicate with helper application"
           -tried deleting cores and emu folders. restart reinstall cores. "couldn't communicate with helper application"

then abandoned open emu and downloaded snes9x and it couldn't access open roms window for some reason. but i can right click roms and play them thru snes9x. i only mention this because i never had this problem with snes9x before and think it may be related. really just want openemu to work again. the memories. the walks on the beach. oh and how she let me use her; swoon.
running OS X yosemite 10.10.5
2ghz intel core 2 duo
2gb 1067 mhz ddr3
nvidia geforce 9400m 256mb

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
