### ISSUE TITLE
OpenEmu Is THE Business!

### ISSUE THREAD

**Issue by glitchyGhost** [OpenEmu/OpenEmu#3525]
Absolutely loving this software - finally something decent for Mac users.  I am a long time Raspberry Pi user and love having a 'work alternative' right on my Mac! Thanks guys.
Effortless setup, BIOS files and systems all work flawlessly - so cool.

A couple of improvement suggestions: 

I am funny about grouping Sega Mega Drive and Genesis together - I would much prefer a separate JAPAN Sega Mega Drive console, so I can have both JP and EU games together, and then fave Genesis separately.  I don't mind the mix on the Sega CD however.

Thanks again!

**Comment by clobber** [comment]
Just create your own collection if you want to group certain games. Click the + arrow at the bottom or right click on games to add them.
