### ISSUE TITLE
Import cover art doesn’t work

### ISSUE THREAD

**Issue by grandpixel** [OpenEmu/OpenEmu#3526]
So I don’t know how to reference other threads. But both were locked after my first reply so I can’t give much background info, other than to say that importing cover art isn’t working for my no-intro roms, and the solution given was to manually add the art myself. Unfortunately I don’t think this is a very good solution. It defeats the purpose of having the feature in the first place. I don’t have the artwork to add. It would be a ton of work for the end user to find, fetch, and normalize artwork for each game in their collection. There’s gotta be a better way.

**Comment by clobber** [comment]
Please try to understand the issue better in #3429 and stop posting about this.
