### ISSUE TITLE
My .nds file has loaded hundreds of times and now it won't load anymore!

### ISSUE THREAD

**Issue by mmkohl** [OpenEmu/OpenEmu#3529]
I had logged 100+ hours playing a game which I repeatedly saved.

As of a few minutes ago when I load the .nds file to continue playing the game it just loads a black screen that stays frozen. And if I hit "Reset Console" it just loads a white screen that stays frozen.

Can you help? I'd logged 100+ hours on this game and am horrified at the thought of losing the saved game I was working so hard on.

I'm using OpenEmu 2.0.6.1.

**Comment by clobber** [comment]
Which game?

**Comment by mmkohl** [comment]
Final Fantasy IV (DS). I was in the ending portion of the game collecting the secret items, which is one of those grinding endeavors that takes up MANY hours. :(

~~~~~~~~~~
Michael Kohl
Guitarist, Vocalist and Writer/Arranger
310.383.4241
mmkohl@gmail.com
~~~~~~~~~~

**Comment by clobber** [comment]
This sounds like another one of those JIT (dynarec) bugs where our port has JIT on by default and Desmume standalone has it off by default, in which the game may work properly there. Sorry, nothing we can do about this so I'd recommend just using the Desmume standalone app from their website when an issue like this arises. You can infer how to transfer out your in-game battery save file from here: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files

**Comment by mmkohl** [comment]
Uh oh. I really hope I can recover it. I just checked out the link you sent
and it only covers the GBA and SNES systems; this is a Nintendo DS game. I
looked for a similar article on your site re: transferring in-game battery
saves from Nintendo DS but couldn't find one - do you happen to have one
handy?

Michael


~~~~~~~~~~
Michael Kohl
Guitarist <https://soundcloud.com/mmkohl/sets/michael-kohl-guitar-demo>,
Vocalist <https://soundcloud.com/mmkohl/sets/michael-kohl-vocalist> and
Writer/Arranger
<https://soundcloud.com/mmkohl/sets/michael-kohl-writer-arranger>
310.383.4241
mmkohl@gmail.com
~~~~~~~~~~

**Comment by mmkohl** [comment]
Ah - you said "infer." Got it. I will try my best and hope I don't mess it
up!


~~~~~~~~~~
Michael Kohl
Guitarist <https://soundcloud.com/mmkohl/sets/michael-kohl-guitar-demo>,
Vocalist <https://soundcloud.com/mmkohl/sets/michael-kohl-vocalist> and
Writer/Arranger
<https://soundcloud.com/mmkohl/sets/michael-kohl-writer-arranger>
310.383.4241
mmkohl@gmail.com
~~~~~~~~~~

**Comment by mmkohl** [comment]
IT WORKED! I did lose ~3 hours of achievements on my save file but this is
WAY better than it being lost forever.

So, are you saying that now that I've migrated successfully to Desmume
standalone there's currently no way to safely migrate back to OpenEmu? I do
love OpenEmu, but obviously don't want a fright like this again...


~~~~~~~~~~
Michael Kohl
Guitarist <https://soundcloud.com/mmkohl/sets/michael-kohl-guitar-demo>,
Vocalist <https://soundcloud.com/mmkohl/sets/michael-kohl-vocalist> and
Writer/Arranger
<https://soundcloud.com/mmkohl/sets/michael-kohl-writer-arranger>
310.383.4241
mmkohl@gmail.com
~~~~~~~~~~

**Comment by clobber** [comment]
No, not saying that. I'm saying you need to play that game with Desmume standalone now that we have identified a problem when using it with the JIT dynarec. Maybe this gets fixed with the next Desmume release, in which you can import it back to OpenEmu.
