### ISSUE TITLE
Couldn't communicate with helper application

### ISSUE THREAD

**Issue by scottdcrompton** [OpenEmu/OpenEmu#3530]
First controller becomes unresponsive then core crashes.

Log file attached.
[OpenEmuHelperApp_2018-02-15-22023.txt](https://github.com/OpenEmu/OpenEmu/files/1730101/OpenEmuHelperApp_2018-02-15-22023.txt)

**Comment by clobber** [comment]
>Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Attempting to resolve device that is not yet ready.'

You need to provide very good details about your input device setup.
