### ISSUE TITLE
Couldn't Play Sega CD Game "Night Trap (USA)"

### ISSUE THREAD

**Issue by dpxcc** [OpenEmu/OpenEmu#3531]
I'm having trouble playing Sega CD game "Night Trap (USA)". It includes 2 CDs, and I managed to load either of them separately. As per documentation, I created a m3u file listing both cue files. Once i drag m3u file into OpenEmu nothing happens.

Console is showing following errors:
default	05:34:54.367111 -0500	OpenEmu	'#ø'
default	05:34:54.367201 -0500	OpenEmu	''
default	05:34:54.367287 -0500	OpenEmu	'SEGADISCSYSTEM  '
default	05:34:54.367569 -0500	OpenEmu	Error Domain=OEImportFatalDomain Code=3 "(null)"

Environment details:
OS X High Serra - Version 10.13.1
Core i7 16 GB RAM
OpenEmu 2.0.6.1
Core GenesisPlus 1.7.4.7

**Comment by clobber** [comment]
Sega CD (Genesis Plus GX) does not yet support multi-disc games.
