### ISSUE TITLE
[10.13.4 beta] OpenEmu's CPU usage is multiple times worse than standalone Snes9x

### ISSUE THREAD

**Issue by JeffreyATW** [OpenEmu/OpenEmu#3533]
When playing a game on the Snes9x core, my fans go on full blast and CPU jumps to about 60-70%:
<img width="815" alt="screenshot 2018-02-18 21 47 12" src="https://user-images.githubusercontent.com/266170/36363868-7839749a-14f5-11e8-9cf0-f76903a5dfca.png">

Comparing this to the same game on plain Snes9x 1.5.3:
![screenshot 2018-02-18 21 46 10](https://user-images.githubusercontent.com/266170/36363865-7270ab00-14f5-11e8-848b-2e039923f67b.png)

I remember this problem starting around the time I updated to a pre-release version of High Sierra. Things run more smoothly than they did then, but CPU usage is still rather high.
<img width="698" alt="screenshot 2018-02-18 21 49 23" src="https://user-images.githubusercontent.com/266170/36363907-b1e6742c-14f5-11e8-9b27-91898ae4e918.png">

Any thoughts? Happy to do some more diagnostics on my side. Thanks!

**Comment by clobber** [comment]
>I remember this problem starting around the time I updated to a pre-release version of High Sierra

I think you found your problem...don't use beta macOS. Cannot replicate this on 10.13.3. I'm sure the final release will be fine.

**Comment by JeffreyATW** [comment]
I'm now running 10.13.4, not a beta, and I'm still having the same CPU performance when running the Snes9x core

<img width="815" alt="screenshot 2018-05-20 10 46 37" src="https://user-images.githubusercontent.com/266170/40281868-42e568b8-5c1b-11e8-955a-aa91251bf166.png">

Surprisingly, Higan runs better at about 32% CPU.

Need any more info? Logs, etc.?
