### ISSUE TITLE
Accidentally dragged bin/cue files for multi game disc, now .m3u isn't loading

### ISSUE THREAD

**Issue by morelikeb** [OpenEmu/OpenEmu#3534]
Before reading the guide (sorry!) I imported the bin/cue files for FF IX. After reading the guide I created the .m3u file using textedit (followed guide to make plain text using format pulldown) typed in 4 lines:

Final Fantasy IX (USA) (Disc 1).cue
Final Fantasy IX (USA) (Disc 2).cue
Final Fantasy IX (USA) (Disc 3).cue
Final Fantasy IX (USA) (Disc 4).cue

saved as .m3u in the same folder as bin/cue files (folder name: FFIX)

the .m3u filename:

Final Fantasy IX (USA).m3u

When I drag this .m3u file to openemu nothing happens. Also tried using the add to library and launch game options in openemu. I have deleted the game from the openemu library (selecting the game and pressing delete) and there is nothing in the library that i can see. Is there a hidden library where the bin/cue files are that i need to delete? already tried deleting and reinstalling openemu, didnt work for me. please help! i'd like to better understand what exactly i did by adding the bin/cue to openemu

**Comment by clobber** [comment]
Cannot conclude that having previously imported the cue files is the cause.

* Which version of OpenEmu?
* Are all the cue files actually deleted from your Library?
* Is your m3u file actually correct?
* Is your m3u file in the same folder as all the cue/bin files?

**Comment by morelikeb** [comment]
Newest version of openemu from their website 2.0.6.1
not sure if the cue file are deleted from library - how do i make certain? when i have playstation selected as my console there are no games visible in library in openemu
when saving .m3u file i copied the file names of the .cue files directly to the editor, formatted from plain text, saved as Unicode (UTF-8) with extension .m3u
all files are in the same folder with no other files

**Comment by clobber** [comment]
Right click the m3u file > Get Info > uncheck "Hide extension" - what's the full filename?

**Comment by morelikeb** [comment]
<img width="1280" alt="screen shot 2018-02-20 at 5 30 38 am" src="https://user-images.githubusercontent.com/36653137/36419212-41fad5b2-15ff-11e8-93a2-29c48401bc69.png">
<img width="1280" alt="screen shot 2018-02-20 at 5 30 51 am" src="https://user-images.githubusercontent.com/36653137/36419213-42087096-15ff-11e8-8e4d-9b93ed528367.png">

**Comment by clobber** [comment]
What do your OpenEmu Library Preferences look like?

**Comment by morelikeb** [comment]
<img width="1280" alt="screen shot 2018-02-20 at 3 03 23 pm" src="https://user-images.githubusercontent.com/36653137/36446438-38967972-164f-11e8-8ab5-13d6cb8f99dc.png">
<img width="1280" alt="screen shot 2018-02-20 at 3 04 16 pm" src="https://user-images.githubusercontent.com/36653137/36446469-565e0330-164f-11e8-94a9-bbc4536d4750.png">

**Comment by clobber** [comment]
Cannot replicate this under the same settings while importing an m3u. Something else must be wrong. 
Open Console.app, go to the search filter box at the top and type openemu, then click Clear.
What output do you see in Console when you try to import the m3u file?

**Comment by morelikeb** [comment]
<img width="1280" alt="screen shot 2018-02-20 at 3 30 40 pm" src="https://user-images.githubusercontent.com/36653137/36447679-0d8cce94-1653-11e8-9dea-2d688ff0326d.png">

**Comment by clobber** [comment]
That's not the entire output. Expand the arrow, or better yet, just copy and paste it. A screenshot isn't needed here.

**Comment by morelikeb** [comment]
i see the problem (maybe) is it because i removed the (v1.0) from the file name?

**Comment by clobber** [comment]
Uhh yes, your filenames are definitely incorrect in some way. You cannot go renaming cue sheet files because they are referencing a specifically named .bin file...

**Comment by morelikeb** [comment]
that was the issue, game running finally. thank you for your patience
