### ISSUE TITLE
Mad Catz TE2+ L2 and R2 not registering

### ISSUE THREAD

**Issue by ultradeafaid** [OpenEmu/OpenEmu#3535]
after i updated to the new OpenEmu my mad catz TE2+ is not working properly for the playstation and super nintendo emulator when i go to preferences and controllers, i click on Mad Catz TE2+ and as i start to input every button, it registers fine. but as soon as i get to L2 and R2 the inputs show up as RY+ and RY-
after that i can no longer put any other inputs in. and my L2 and R2 do not work

**Comment by clobber** [comment]
I don't think there was anything in the latest update that affected input. Try here first: [Troubleshooting: Input problems](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems)
