### ISSUE TITLE
Not recognizing keyboard

### ISSUE THREAD

**Issue by cakethesnack** [OpenEmu/OpenEmu#3536]
I am on a MacBook, most recent software updates, most recent OpenEmu update. My only thought would be that something got deleted and messed it up. Is there any way to fully reset OpenEmu maybe?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."

**Comment by 1dancingthrulife** [comment]
I'm having the same issue. I read the input troubleshooting guidelines and the only potential interference was use of google chrome, but I was still having the same difficulty after closing google chrome and restarting OpenEmu. 

I am currently using MacOS High Sierra 10.13.4 and the most updated version of OpenEmu. I have been playing Pokémon Black on the Nintendo DS emulator for about a week now, but mid-game the keyboard stopped responding and I am unable to press any buttons on the screen (though I had been able to previously). If I open a new game, I am able to resume normal gameplay, but whenever I try to load the game from before, the issue continues. Do you have any suggestions for further analyzing and/or resolving this issue?

**Comment by clobber** [comment]
@1dancingthrulife That is a DeSmuME compatibility and/or AP patch issue, unrelated to this particular one here. You can search our issues or refer to the [Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) for a bit more information, but beyond that there is nothing more we can do.
