### ISSUE TITLE
N64 issue on Openemu Experimental 2.0.6 

### ISSUE THREAD

**Issue by danielevenanzi** [OpenEmu/OpenEmu#3538]
Hi guys, I'm experiencing lags and glitches (both audio and video) on N64 games in Openemu Experimental 2.0.6. N64 games were running fine on this version before I updated from OSX Sierra 10.12.5 to 10.12.6. All the other engines seem to run just fine, like they always did. My system specs: early 2011 "13 MacBook Pro, 2.3 ghz Intel Core i5, 8 GB ram, 500 GB SSD rom, Intel HD 3000 GPU. Any clues on what happened here? Thank you for your support, much appreciated.

Daniele

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3447
