### ISSUE TITLE
Unable to Install New Cores

### ISSUE THREAD

**Issue by D4v1n** [OpenEmu/OpenEmu#3539]
When I first installed the emulator, I only installed a few cores, expecting to only want to use those consoles. Unfortunately, now I want to try the rest of them. Now, if the emulator was functioning as intended, the cores I didn't have on my computer would be shown with an 'install' button. I don't know, am I missing something?

**Comment by clobber** [comment]
Cannot replicate; works for me. This mean it's a problem on your end - likely a firewall or application blocking outgoing connections to GitHub or their SSL certificate being rejected.

If you don't see "Install" listed for cores in Preferences > Cores and they are greyed out, then that is the case. If there are no warning icons next to the available libraries in Preferences > Library then you simply need to check the boxes.

**Comment by clobber** [comment]
Sounds like the case to me. If there are no additional cores listed with "Install" buttons then it is not able to connect to GitHub. Maybe you should provide a screenshot.

**Comment by D4v1n** [comment]
I just solved the issue. My computer was blocking connections to GitHub, as it does so with all websites that applications try to access. I had previously ignored those messages because other applications, such as Steam, try to access websites and those applications run fine without access to those websites; thus making me believe that those sorts of connections are unnecessary.
