### ISSUE TITLE
Transferring GBA .sav2 files

### ISSUE THREAD

**Issue by icedragon1095** [OpenEmu/OpenEmu#3540]
I followed the instructions to convert my GBA .sav2 files in [this guide](https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files), but it didn't work (I tried the method in the guide multiple times with different games to make sure I was doing it right) and I still can't use my old save files. Is there any other way to convert .sav2 files to .sav files or am I out of luck?
(my OS is macOS Sierra version 10.12.6 and my OpenEmu version is v2.0.6.1)

**Comment by clobber** [comment]
What didn't work? The guide is just copying a file to another folder and then renaming it. There is no conversion taking place. If it's not working for you, it's likely you have done something wrong.

**Comment by icedragon1095** [comment]
I copied and renamed my old save files exactly like the guide said, but when I run the games a new battery save is created instead of using the old save file I just copied and renamed.

**Comment by clobber** [comment]
What you're describing doesn't make sense. So the guide is for transferring a save file for an existing game in your collection over to the mGBA core plugin. You are doing either of the following wrong:
* Opening a different game than what your original save file was created with.
* Not actually renaming the save file correctly.

Show me a screenshot of your situation.

**Comment by icedragon1095** [comment]
I copied the file: 
![copied the file](https://user-images.githubusercontent.com/36802154/36636093-36c1a676-198d-11e8-80f4-ada0580bcdd5.png)
I renamed the file: 
![renamed the file](https://user-images.githubusercontent.com/36802154/36636095-4e8621c4-198d-11e8-99a4-1c0f525f74b7.png)
I ran the game and new save data was created: 
![ran the game](https://user-images.githubusercontent.com/36802154/36636098-5bc20f56-198d-11e8-94a4-5909713d743b.png)
I haven't downloaded a different version of the game since the last time I played it, and I haven't used save states or started the game from a save state.

**Comment by clobber** [comment]
Right click > Get Info of the other file, look under "Name & Extension", what do you see?

**Comment by icedragon1095** [comment]
The new one that was created when I ran the game
![screen shot 2018-02-24 at 6 17 33 pm](https://user-images.githubusercontent.com/36802154/36636209-a9642c9c-198f-11e8-96b3-8f9cec1a2c7d.png)

**Comment by clobber** [comment]
No, I need to see the one that you copied and renamed.

**Comment by icedragon1095** [comment]
Oh 
![screen shot 2018-02-24 at 6 24 58 pm](https://user-images.githubusercontent.com/36802154/36636223-2779b7fa-1990-11e8-8ec0-dc4c07274c68.png)
So I guess I just need to change the extension in the 'Get Info' window rather than just changing the file name

**Comment by clobber** [comment]
Often times, Finder works against you even though you have file extensions showing. One of the broken UX things I'll never understand on Mac. But yes, as you can see, the proper way is to use "Get Info" to rename a file extension. So all you need to do now is delete the one that mGBA generated, rename your copied one and then load it after you have reset warnings again.
