### ISSUE TITLE
Crash when deleting last game in a manual collection

### ISSUE THREAD

**Issue by gingerbeardman** [OpenEmu/OpenEmu#3541]
1. Create manual collection
2. Add some games
3. highlight last/bottom game
4. Press Cmd+Backspace
5. Hard crash

The game is also not actually deleted from the app.

https://pastebin.com/raw/7arVAnTf

video: https://youtu.be/-fnSBNtRM0o

**Comment by robotoad** [comment]
> The game is also not actually deleted from the app.

Note that deleting a game from a collection doesn't remove it from the library.
