### ISSUE TITLE
Attempting to sort titles by "Last Played" causes strange behavior in UI

### ISSUE THREAD

**Issue by shmoe** [OpenEmu/OpenEmu#3542]
Not included in these strange behaviors is actually sorting titles by "Last Played" so I initially thought it was just something that someone forgot to implement. But attempting to sort by "Last Played", even on lists of only a single item, causes severe lag in the sidebar when trying to switch collections.

**Comment by clobber** [comment]
I don't think I'm experiencing any lag. I can replicate sorting by "Last Played" not working though - probably broke after the 2.0 rewrite or a change in an SDK. What is your macOS and OpenEmu version?

**Comment by shmoe** [comment]
OpenEmu v2.0.6.1 and macOS 10.12.6

I can replicate the lag by sorting by last played in one playlist/Console then attempting to switch to another playlist/Console. Switching view mode will get it out of whatever loop it gets itself in.

**Comment by clobber** [comment]
Okay, I can replicate that too. I didn't know what you meant by lag.
