### ISSUE TITLE
PS2 controller reads but doesn't respond

### ISSUE THREAD

**Issue by SrednaH** [OpenEmu/OpenEmu#3543]
Hi, I really love this emulator. Now if I could only get my PS2 controller to work along with it..
I have a generic USB converter which the emulator reads fine, showing two twin USB joystick inputs under the Controls section of the Sony PlayStation. My impression is that mapping the buttons is an automatic function, however, there's no automatic response nor any response to a button being pressed or held. I don't know if I'm supposed to configure it somehow?

I have tried three controllers of which two were original and the third a fake.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."

>generic USB converter

OpenEmu oftens has issues with adapters.

>My impression is that mapping the buttons is an automatic function

No. You need to map your own controls. We only automap controls for the following: https://github.com/OpenEmu/OpenEmu/wiki#automap-supported-controllers

**Comment by SrednaH** [comment]
Sorry about not reading the guidelines first. This is my first experience with GitHub.

If I'm reading this correctly, there doesn't really seem to be a way at all to use an original PS2 controller since there's no way to plug it directly into the mac. So, might I ask, do you have any recommendations as to what would work in this situation? Any products that will fix it? Or should I just buy a new PS3 controller?

**Comment by clobber** [comment]
What I was saying was, there are reasons (often software related) why an input device may not work, with the guide having suggestions to fix it. Depending on use, I would probably recommend a PS4 controller at the moment.

**Comment by SrednaH** [comment]
I understand. I might still try out other adapters and notify you if I find one that works. Could be useful for others as well.
