### ISSUE TITLE
Any way to get Dreamcast core installed?

### ISSUE THREAD

**Issue by jamesalmeida** [OpenEmu/OpenEmu#3546]
Can't figure out how to run Dreamcast games in OpenEmu...

**Comment by clobber** [comment]
There is no official Dreamcast core port and there are no Dreamcast emulators available with nearly good enough compatibility. This will likely remain the case for a long time.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Usage of [experimental and WIP](https://github.com/OpenEmu/OpenEmu/wiki/Console---Core-Plugin-Status-&-Wishlist) core ports are strictly unsupported and have no ETA."
