### ISSUE TITLE
why no support old mac os?

### ISSUE THREAD

**Issue by eret1k** [OpenEmu/OpenEmu#3547]
I use os x 10.9 and wanna use your emulator.

**Comment by clobber** [comment]
>wanna use your emulator

Then upgrade your operating system. Apple left no hardware behind in updates all the way to 10.11. That means, if your Mac can run 10.9 Mavericks, it can also run 10.11 El Capitan which happens to be the last version we support. It's really that simple. Also, please don't waste our time opening issues like these. Our issues page is for bug reports.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
