### ISSUE TITLE
OpenEmu not importing multiple disc games properly

### ISSUE THREAD

**Issue by aliasingIsHard** [OpenEmu/OpenEmu#3548]
I put Metal Gear Solid Integral into my library. I followed the guide step by step, but it put two games into my library instead of one. I tried to open them but it said I needed an M3U file, which I already put in. I checked for any typos in the M3U or any incorrect files, but everything looked fine.

**Comment by clobber** [comment]
OpenEmu imports multi disc games just fine. You may have a misunderstanding or you did something wrong. If you are using an M3U, you cannot have those games already imported into your Library. That's not how it works. They must first be removed from your Library (like the guide says), then you create an M3U and import the discs for the game. It's also possible to have typos inside the cuesheet or .bin files that don't match up.
