### ISSUE TITLE
we need a mirror

### ISSUE THREAD

**Issue by juanmas07** [OpenEmu/OpenEmu#3549]
It's been several days already since I want to download the dist but I cannot complete it.

**Comment by clobber** [comment]
Uh I think you have the wrong repo. All of our releases are available through GitHub.

**Comment by juanmas07** [comment]
I know:

https://github.com/OpenEmu/OpenEmu/releases/download/v2.0.6.1/OpenEmu_2.0.6.1.zip

Impossible to download from several days now

**Comment by clobber** [comment]
Not our problem. Ask GitHub or your ISP. We won’t be deploying our software through any mirrors.

**Comment by juanmas07** [comment]
Ok thanks for answering

--
Juan Manuel Crescente
Eng. Software development and IT management
Bioinformatics - PhD Candidate @ INTA/CONICET
Please consider the environment before printing this email.
