### ISSUE TITLE
Can't Run Sega CD Games

### ISSUE THREAD

**Issue by Yoshifan1219** [OpenEmu/OpenEmu#3550]
I just want to play Sonic CD, but everytime I try to open the game, it says its missing "_BIO-CD-J.bin_".

I Know that's the regional code for the CD since it also asked for the E and U versions as well.
However I managed to recover those files and add them in, but I can't find a single one for the BIO-CD-J.bin.

**Comment by clobber** [comment]
Cannot link you to files. The [BIOS guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files) gives you hints for filenames to search for and their checksums. Start downloading and drag and dropping in files you find until one works.
