### ISSUE TITLE
Feature Request: PSX mouse support

### ISSUE THREAD

**Issue by LukeOrgana** [OpenEmu/OpenEmu#3552]
Unless I am mistaken, I believe that Mednafen already includes support for using the mouse in PS1 games. Is there a way to enable this in OpenEmu? If not, is there a chance it will be included in a future version? This would significantly improve the experience of some of the great classic Playstation Mouse compatible games, especially Discworld, Command & Conquer, etc.

**Comment by clobber** [comment]
This will happen in a future core plugin update, probably around the same time that lightgun support is added.

**Comment by LukeOrgana** [comment]
Thanks. Is there a rough idea of when this might happen?

**Comment by Stooovie** [comment]
still no PSX mouse support? it would be great for Policenauts
