### ISSUE TITLE
Cannot import FFVII m3u File

### ISSUE THREAD

**Issue by YungSinatra** [OpenEmu/OpenEmu#3563]
<img width="766" alt="screen shot 2018-03-20 at 1 05 14 pm" src="https://user-images.githubusercontent.com/37596842/37679830-600bf2ce-2c3f-11e8-8b79-09faa037b4da.png">
This is a quick picture of finder for me. I have all the files for FFVII. I am also attaching a screen shot of my m3u file. Please tell me what I am doing wrong. The m3u file just will not import. 
<img width="629" alt="screen shot 2018-03-20 at 1 07 21 pm" src="https://user-images.githubusercontent.com/37596842/37679939-a7f9a41e-2c3f-11e8-9993-567da680abe1.png">

**Comment by clobber** [comment]
Follow through issue #3534 or search the issues for others. We cannot continue to troubleshoot these as people are always doing something wrong.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."
