### ISSUE TITLE
The emulator could not run ROM - PSX

### ISSUE THREAD

**Issue by YunoDyva** [OpenEmu/OpenEmu#3567]
i have just download the openemu, but it's not the first time i have it. 
i have a new mabook and in the last one the emulator didnt load any N64 games and now its not running the PS and PSP games. just says "The emulator couldnt run ROM".

i download it again and it says that i need to install something and gives me the option, so i click on install but it doesnt load anything.

thanx

**Comment by clobber** [comment]
Sounds like #3539 to me.
