### ISSUE TITLE
Controle PS4 v2 (Slim) não funciona no Openemu... O devo fazer?

### ISSUE THREAD

**Issue by ribeiro072** [OpenEmu/OpenEmu#3568]
Olhei o post abaixo mas não consegui baixar o arquivo: controller-database.plist
O que faço para realizar o download do arquivo?

Estou utilizando o openemu 2.0.1v

"Clique na aba "Código" no topo desta página e depois clique na pasta OpenEmu. Olhe dentro dessa pasta para o arquivo "controller-database.plist". Baixe. Em seguida, vá para a pasta Aplicativos. Encontre o OpenEmu, clique com o botão direito e selecione show content. Vá para a pasta de recursos. Arraste o arquivo controller-database.plist que você baixou para esta pasta. Você será solicitado a substituir o arquivo antigo. Diga sim. Deve ser bom ir de lá."

**Comment by clobber** [comment]
Sorry, English only - you're on the Internet. From what I gather, you need to be using the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu - anything less is unsupported (as noted in our [Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md)). The official PS4 dualshock works fine over bluetooth (without using the adapter). Cannot help you more beyond this.

**Comment by ribeiro072** [comment]
I should install Mac OS Sierra to get openemu 2.0.6.
So with a new version of openemu I should be able to use dualshock 4 v2?

**Comment by mileyvirus** [comment]
Yes, that's exactly what clobber was saying. I can confirm successfully using a DS4 v2 with the latest version of OpenEmu both via Bluetooth and via USB.
