### ISSUE TITLE
OpenEmu crash on lauching games

### ISSUE THREAD

**Issue by Ryukhaan** [OpenEmu/OpenEmu#3569]
I've updated OpenEmu to 2.0.6_1 and i'm on masOS 10.12.6.
Very time I try to launch a game, OpenEmu crash. Even if i try to open settings.
I got this error (when opening settings): 

> Process:               OpenEmu [6355]
> Path:                  /Users/USER/Documents/*/OpenEmu.app/Contents/MacOS/OpenEmu
> Identifier:            org.openemu.OpenEmu
> Version:               2.0.6.1 (2.0.6.1)
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           OpenEmu [6355]
> User ID:               501
> 
> Date/Time:             2018-03-23 14:40:40.669 +0100
> OS Version:            Mac OS X 10.12.6 (16G29)
> Report Version:        12
> Anonymous UUID:        FAE87E92-3747-F1D3-D6E7-A000CE91A14D
> 
> Sleep/Wake UUID:       7CE04434-587C-4E86-925C-AC9795EF3E12
> 
> Time Awake Since Boot: 440000 seconds
> Time Since Wake:       21000 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0  Dispatch queue: org.openemu.system.OEBindingsController
> 
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Application Specific Information:
> Performing @selector(showPreferencesWindow:) from sender NSMenuItem 0x6080000a6fc0
> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: OEN64ButtonCDown)'
> terminating with uncaught exception of type NSException
> abort() called
> 

Moreover, when I updated to version 2.0.6_1, it told me to install something (mGBA core in my mind, sorry don't remember). I said OK, then during installation it crashed. Dunno if it could be useful to know.

Anyone know how to fix it ?

**Comment by clobber** [comment]
Follow https://github.com/OpenEmu/OpenEmu/issues/3532#issuecomment-366541371
