### ISSUE TITLE
emulating gta london

### ISSUE THREAD

**Issue by greengamerUSSR** [OpenEmu/OpenEmu#3570]
i'm trying to emulate gta london 1969 on the ps1, normally on a real playstation i would need to insert the gta '69 disc, then insert the gta 1 disc, then re-insert the gta '69 disc, how do i handle this in openemu?

**Comment by clobber** [comment]
You're talking about multiple discs, so you would need to create an M3U playlist file.

Follow the guide: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game

**Comment by greengamerUSSR** [comment]
i did as told, and the m3u playlist file won't be read by openemu. when i try to import it, nothing pops up.
