### ISSUE TITLE
Select and Start don't work

### ISSUE THREAD

**Issue by PokemonBlue** [OpenEmu/OpenEmu#3571]
The start and select buttons don't work when I tried to "Start A New Game" on my ROM (Pokemon Silver for GBC). I have tried to change the controls, but nothing seems to be working. How do I fix this?

**Comment by clobber** [comment]
Try here first: [Troubleshooting: Input problems](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems)
