### ISSUE TITLE
Unable to type any text on PSP games

### ISSUE THREAD

**Issue by Openemu25700** [OpenEmu/OpenEmu#3573]
Hello,
Today i wanted to play Monster Hunter Freedom United on PSP, but i am locked on the character creation screen, as the game asks me to type a name for the character, but **i can't type anything with my keyboard.**

Could it be possible to modify the PSP emulation core to have a sort of "virtual keyboard" appearing when i press a specific key ?

**Comment by clobber** [comment]
Probably not something that is possible to add. Use the in-game controls/menus for this.
