### ISSUE TITLE
System icons license

### ISSUE THREAD

**Issue by travisnewman** [OpenEmu/OpenEmu#3575]
I've already read #330 #541 #885 #1844, Credits.rtf, and the copyright disclaimer at the top of source files, as well as looking over openemu.org and the wiki here, but something that isn't readily obvious to me is the graphics license. Specifically for the system icons in the left sidebar. Is it possible to use these icons (with or without attribution) in other projects? Again, not talking about code at all, only the graphics themselves.

Thanks!

**Comment by clobber** [comment]
It seems that for now these are not licensed for use in other projects.

**Comment by travisnewman** [comment]
Understood, thanks clobber!
