### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by BOOGTOONS** [OpenEmu/OpenEmu#3576]
Every time I try to play a game, it crashes.

**Comment by clobber** [comment]
Uhhh okay?

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..." and "Include Console and crash logs, macOS and OpenEmu version, hardware information, ROM/game filenames, etc."

**Comment by BOOGTOONS** [comment]
Okay, uh... Every time I open any game, on any console, it crashes. I'm on the newest version, but a relatively old computer. I don't know what a log is. I'm not very good with computers.

**Comment by clobber** [comment]
> I don't know what a log is. I'm not very good with computers.

It's that message that pops up after an application crashes. C'mon man. How do you expect anybody to help you if you cannot post basic information.

**Comment by BOOGTOONS** [comment]
Then, I didn't get a log, I don't even think my computer recognized it crashed.

**Comment by clobber** [comment]
There is definitely a log. If this occurs "every time" then certainly you should see it. Post it back here in this issue next time. Until then, there is nothing I can do to help you.

**Comment by BOOGTOONS** [comment]
Okay.

**Comment by BOOGTOONS** [comment]
I got a thing but I don't know if it's a log. I clicked the "report" button.

**Comment by clobber** [comment]
Painful. So you posted a crash log but then deleted it...for reasons only you must understand.

To fix your crash:
1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.
