### ISSUE TITLE
Cannot run ROMs. Errors included.

### ISSUE THREAD

**Issue by taaronnicholson** [OpenEmu/OpenEmu#3578]
Running High Sierra 10.13.3, double clicking a title in the window or selecting 'Play Game' is not working to load games. Nothing happens at all. Cores and bios are installed.

The following errors come up in Console.app:
`error	20:46:19.458531 -0400	OpenEmu	        AEGetDescData of non-desc type 'reco' not a good idea
error	20:46:19.602805 -0400	OpenEmu	Scheduling the NSURLDownload loader is no longer supported.
`

**Comment by clobber** [comment]
Those are not errors and that is not nearly enough information to troubleshoot.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..." and "Include Console and crash logs, macOS and OpenEmu version, hardware information, ROM/game filenames, etc."

**Comment by taaronnicholson** [comment]
What other information do you need? I'll try again: 

1. Literally nothing happens when trying to load ROMs.

2. Console reports the following when loading the OpenEmu app:
`error 20:46:19.458531 -0400 OpenEmu AEGetDescData of non-desc type 'reco' not a good idea error 20:46:19.602805 -0400 OpenEmu Scheduling the NSURLDownload loader is no longer supported.`

3. MacOS 10.13.3.

4. OpenEmu 2.0.6.1 858-gefc590e-Release

5. My system specs: 
3.4 GHz Haswell i5 CPU
16GB DDR3 memory
GTX 760 2 GB GPU

6. ROMs affected: All.

**Comment by clobber** [comment]
>Literally nothing happens when trying to load ROMs.

There is likely more console output than the two irrelevant lines you are pasting. Until you provide more information and steps to replicate the problem (you know, like an example ROM/game and system) then I cannot help you. Try a good ol' fashion restart.

**Comment by taaronnicholson** [comment]
Here are two Console logs, filtered by OpenEmu events. One contains the events after opening OpenEmu, the other is the events of opening a ROM. This happens with every ROM, across all systems. I tried restarting before reporting.

[open openemu.txt](https://github.com/OpenEmu/OpenEmu/files/1854301/open.openemu.txt)
[open rom.txt](https://github.com/OpenEmu/OpenEmu/files/1854302/open.rom.txt)

**Comment by clobber** [comment]
> 3.4 GHz Haswell i5 CPU, GTX 760 2 GB

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "OpenEmu running on non-Apple hardware aka "Hackintosh" is strictly unsupported."
