### ISSUE TITLE
Mapping Sega Saturn Controls with NES30Pro stopped controller from mapping to any system.

### ISSUE THREAD

**Issue by Djarum0** [OpenEmu/OpenEmu#3579]
Attempting to map a NES30 Pro controller to the Sega Saturn fails after the first button (oddly says it is Button 7) then key inputs become unresponsive to any button mapping to any System. Controls still work in games/systems previously mapped. Only a restart of both the controller and OpenEmu allows mapping of other systems again.

**Comment by clobber** [comment]
Sounds like https://github.com/OpenEmu/OpenEmu/issues/3293#issuecomment-320040239. Just be on the latest firmware and then delete your bindings file.
