### ISSUE TITLE
Add "Go to Screenshot Folder" 

### ISSUE THREAD

**Issue by soegaard** [OpenEmu/OpenEmu#3583]
The "Controls" menu has a "Take Screenshot" menu item that makes it easy to take a screenshot.
There is unfortunately no way for a user to see where the screenshot is saved. I found the answer by looking at past Github issues. 

Proposal: Add a new menu item "Go to Screenshot Folder" that opens the folder where screenshots are stored in Finder/Explorer.

**Comment by shysaur** [comment]
This functionality already exists.If you right-click (or control+left click) on a screenshot in the screenshot library, and then select

**Comment by shysaur** [comment]
@soegaard If you received an incomplete response via e-mail, please open it on github to see the full response. Sorry for the inconvenience :(
