### ISSUE TITLE
Mana Khemia PSP button's crash

### ISSUE THREAD

**Issue by mathreinert** [OpenEmu/OpenEmu#3584]
Hi there. I'm having kind of a problem with the Mana Khemia's PSP version.

Everytime I win a boss fight, you're supposed to use the X button to skip it, but, for some reason, it doesn't work. Every other button it's fine, just the X button that I keep pressing and nothing happens. The game doesn't freeze, crashes or anything, it's just that issue with the button after boss fight.

I'm using the latest version of the OpenEmu app (2.0.6.1) on High Sierra 10.13.4 and I tried already downloading different roms from different websites, I'm only using in-game saving states and loading states and it keeps happening. I've tried the USA version, I've tried the Europe version, nothing works. I can't go on in the main story because of this :/ 

Is there a way to fix it? Thanks

**Comment by clobber** [comment]
Don't know anything about this game, but sounds like a PPSSPP or game bug to me. We can't do anything about that. Maybe something related here: https://forums.ppsspp.org/showthread.php?tid=13952
