### ISSUE TITLE
Does not support external keyboard or Bluetooth keyboard.

### ISSUE THREAD

**Issue by CoderSimonWong** [OpenEmu/OpenEmu#3586]
Does not support external keyboard or Bluetooth keyboard, so when using the Bluetooth keyboard can not play. Is there a solution or will it be added later?

**Comment by clobber** [comment]
Both keyboard types work fine.

Try here first: [Troubleshooting: Input problems](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems)
