### ISSUE TITLE
Cannot add new games

### ISSUE THREAD

**Issue by Jerrytheone** [OpenEmu/OpenEmu#3587]
So, I've only just begun to use OpenEmu, so please tell me if this is an old issue and already have been solved. I'm using OpenEmu 1.0.4, and I've added Contra, and that's it. When I try to add in a new game, say: Super Mario Bros. for the NES, it didn't show up when I dropped in the zip file. If you have any suggestions, I'm all ears.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

**Comment by Jerrytheone** [comment]
sorry
