### ISSUE TITLE
Issue recognising some HORIPAD mini4 button presses

### ISSUE THREAD

**Issue by sinfulnature** [OpenEmu/OpenEmu#3588]
Purchased a HORIPAD mini 4 to rectify problem of PS4 not being able to connect to Dualshock 4 following usage on OS X which led to not being able to use any of my controllers after accidentally using both with Mac. Hoped to use pad as a replacement emulator controller but OpenEmu will not recognise inputs from cross, circle, square, triangle, L1, R1 share or touchpad button. Presses from d-pad, options, L2 and r2 are fine. Have made sure no background apps are running.

**Comment by clobber** [comment]
If it's a standard HID device, then I don't think this is OpenEmu's problem. Also, you should be able to use a DualShock 4 on a PS4 again just fine after resetting it (pressing a paperclip in the hole on the back).

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
