### ISSUE TITLE
How to Import Downloaded PS1 Save Files to OpenEMU?

### ISSUE THREAD

**Issue by Octacle** [OpenEmu/OpenEmu#3590]
I downloaded a PS1 save file online and I hope to use it with OpenEMU. I traveled to the proper directory and then got stuck.
What do I do with the auto-generated mcr files from the game I got the save for? Do I get two copies of the save and then rename them to whatever the app named the auto-generated ones? Do I only have to replace one of the auto generated saves?

I tried it with two renamed copies of the save, and the emulator could not load the ROM.

Any help would be appreciated. Thanks!

UPDATE: Turned out to be a region issue - changed the region to US with Memcardrex. But the emulator still doesn't recognize the two new save files: the game says there are no save files, even though I replaced the files. Please help!!

**Comment by clobber** [comment]
You obviously must be using the same region mem card file as the game you are trying to play. You cannot just plunk any old save file you download in there. You are likely restoring an autosave at load which in turn overwrites the files you imported. You can infer what you are doing wrong (and how to fix it) by reading through this: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing#transfer-your-save-data

Note: Using tools to change mem card regions or convert save files types leaves room for error, so using such tools or methods is unsupported here.

**Comment by Octacle** [comment]
Sadly that is not the case. I clicked “no” when prompted to start from an auto save, and checked “don’t ask again”. If it’s not the auto save, what could it be? Those are the only 100% Croc 2 files I could find.

**Comment by Octacle** [comment]
I believe I am following the directions from the linked article correctly, but the issue persists. Please help!
