### ISSUE TITLE
MCR Files Downloaded From Internet Not Being Recognized by OpenEMU

### ISSUE THREAD

**Issue by Octacle** [OpenEmu/OpenEmu#3591]
I recently got my computer fixed, and all apps that didn't come with it were lost as a result. I redownloaded OpenEMU, and was able to get my progress restored on Croc: Legend of the Gobbos (PS1 version) via a level password. Croc 2 (also PS1 version), the only other game I completed, doesn't use passwords, so I downloaded an 100% complete GME file to restore my game progress. I converted it to an MCR, and replaced the MCR files automatically created in the Battery Saves folder with two copies of the new MCR (I made sure to rename them so they had the same names as the previous files). When I booted up the game and selected "Load Game" - there were no save files found. Did I do something wrong?
Any help would be appreciated. Thank you!

**Comment by clobber** [comment]
Transferring legitimate mem card files works, but you are likely not doing it correctly. You don't need to open a second issue for this (it's not an OpenEmu issue in the first place). I will add some information in a wiki guide later and update your original issue.

#3591
