### ISSUE TITLE
Still having problems with importing MCR files

### ISSUE THREAD

**Issue by Octacle** [OpenEmu/OpenEmu#3592]
The original issue is as follows.
"I recently got my computer fixed, and all apps that didn't come with it were lost as a result. I redownloaded OpenEMU, and was able to get my progress restored on Croc: Legend of the Gobbos (PS1 version) via a level password. Croc 2 (also PS1 version), the only other game I completed, doesn't use passwords, so I downloaded an 100% complete GME file to restore my game progress. I converted it to an MCR, and replaced the MCR files automatically created in the Battery Saves folder with two copies of the new MCR (I made sure to rename them so they had the same names as the previous files). When I booted up the game and selected "Load Game" - there were no save files found. Did I do something wrong?"

I was told that it may have been an autosave issue. Sadly that is not the case. I clicked “no” when prompted to start from an auto save, and checked “don’t ask again”. If it’s not the auto save, what could it be? Those are the only 100% Croc 2 files I could find.

**Comment by clobber** [comment]
Okay kiddo, you're officially done opening new Issues here.

#3590
