### ISSUE TITLE
Cannot add games to OpenEmu (Mac) - v2.0.6.1 (858-gefc590e-Release)

### ISSUE THREAD

**Issue by JasonNewton1** [OpenEmu/OpenEmu#3593]
Hi there,

My existing library is fine and I can open and play things just as I always have. The issue is I cannot add anything new. Whether I use 'Add to Library' or drag the .sfc file (I like SNES games) it will not add anything new.

My OpenEmu version is v2.0.6.1 (858-gefc590e-Release). 

I ought to reiterate, my existing library all play perfectly fine. No glitches or crashes. Saved States are fine. It's just adding new titles that is not working.

**Comment by clobber** [comment]
Cannot replicate anything like this. Need an example. Does it happen with all games? A certain one? Does the game already exist in your Library? Can you delete on that already exists in your Library and re-import it?

**Comment by JasonNewton1** [comment]
If I delete a game from my library and then try to re-add it again, it will not copy into my library. It happens with all games I try to add.

**Comment by clobber** [comment]
You will have to check Console.app (filter it for openemu) for output as you try to import a game.

**Comment by JasonNewton1** [comment]
When I try to add a game using 'Add to Library', I get this:

`default	21:01:05.553508 +0100	OpenEmu	Connection to sharingd became invalid
error	21:01:06.020601 +0100	OpenEmu	errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
default	21:01:06.077784 +0100	OpenEmu	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(ficl,askM handler=0x7fff5296e5e5 isSys=NO) err=0/noErr
default	21:01:06.491091 +0100	OpenEmu	open on /~/Library/Application Support/OpenEmu/Game Library/Super Nintendo (SNES)/Paperboy 2 (USA).sfc: No such file or directory
default	21:01:06.501788 +0100	OpenEmu	Error Domain=NSCocoaErrorDomain Code=4 "The file “Paperboy 2 (USA).sfc” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/jasonnewton/Desktop/Paperboy 2 (USA).sfc, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/~/Library/Application Support/OpenEmu/Game Library/Super Nintendo (SNES)/Paperboy 2 (USA).sfc, NSFilePath=/Users/jasonnewton/Desktop/Paperboy 2 (USA).sfc, NSUnderlyingError=0x604000840fc0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
`

**Comment by JasonNewton1** [comment]
When I launch OpenEmu, I notice there are two errors.

`error	21:09:41.893952 +0100	OpenEmu	Scheduling the NSURLDownload loader is no longer supported.
`
`error	21:09:41.893952 +0100	OpenEmu	Scheduling the NSURLDownload loader is no longer supported.
`

**Comment by JasonNewton1** [comment]
This is the error when trying to add new games.

`error	21:12:42.949044 +0100	OpenEmu	errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
`

**Comment by clobber** [comment]
You don't need to keep pinging with various log info. None of those are relevant except for your first batch:

```
OpenEmu	open on /~/Library/Application Support/OpenEmu/Game Library/Super Nintendo (SNES)/Paperboy 2 (USA).sfc: No such file or directory
OpenEmu	Error Domain=NSCocoaErrorDomain Code=4 "The file “Paperboy 2 (USA).sfc” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/jasonnewton/Desktop/Paperboy 2 (USA).sfc, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/~/Library/Application Support/OpenEmu/Game Library/Super Nintendo (SNES)/Paperboy 2 (USA).sfc, NSFilePath=/Users/jasonnewton/Desktop/Paperboy 2 (USA).sfc, NSUnderlyingError=0x604000840fc0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

The file system cannot see the file your are trying to copy or the folder it's trying to copy it to. Did you change a setting with your Game Library or try to manually migrate it somewhere?

**Comment by JasonNewton1** [comment]
Not that I remember. Where would that setting be? I did make a back up go the games to a NAS about five years ago, but the original files have always remained on the local MacBook drive.

**Comment by JasonNewton1** [comment]
clobber, I deleted OpenEmu, downloaded a fresh copy and imported my games fine. I don't know what was wrong but reinstalling seems to have fixed it.

Kind Regards

**Comment by clobber** [comment]
Your Game Library folder, at least where it wants to copy your ROM to, doesn't exist. Something must have been changed on your end. The destination path with the leading forward slash and then relative path seems suspicious, as I don't think it would normally be constructed that way.

Run the following command in Terminal.app and show me the output:
`defaults read org.openemu.OpenEmu databasePath`

**Comment by JasonNewton1** [comment]
`Last login: Tue Apr 10 19:16:05 on console
MacBook-Air:~ jasonnewton$ defaults read org.openemu.OpenEmu databasePath
~/Library/Application Support/OpenEmu/Game Library
MacBook-Air:~ jasonnewton$ `
