### ISSUE TITLE
Save file works in mGBA but not in OpenEmu (v2.0.6.1)

### ISSUE THREAD

**Issue by MrDemocracy** [OpenEmu/OpenEmu#3594]
I was playing Pokémon Prism on mGBA, before I decided I wanted to continue playing it on OpenEmu with the SABR filter. But when I added Prism to my OpenEmu library and copied the save file to the mGBA battery saves folder (the names are the same for both the rom and the save file) and tried to start up the game for the first time, I'm only given the options: `New Game` and `Options`
Not `Continue`.
Why does this happen??
If I load the battery save file in the OpenEmu folder with mGBA instead, the save loads without any problems.
Isn't OpenEmu also using mGBA?

**Comment by clobber** [comment]
Will work just fine if using the same ROM and same battery save file (named correctly) and that you are not restoring an autosave state on launch:

1. Copy your save file again since it's probably already overwritten.

2. Go to OpenEmu > Preferences > Library, click "Reset warnings"

3. Open your game and click "No" if prompted to "Continue where you left off"

**Comment by MrDemocracy** [comment]
It was first launch, there were no autosave. The save is not overwritten by a blank one. The .sav file contains my save data, OpenEmu just won't load it.

**Comment by clobber** [comment]
Sorry, but it's not our bug if everything was done correctly. The core is directly responsible for reading/writing the battery save file. We use mGBA 0.6.1 at the moment until I've had a chance to update the core plugin to 0.6.2.  Perhaps there is an incompatibility with 0.6.1 and whatever version yours was generated with.

**Comment by MrDemocracy** [comment]
The save was generated with v0.6.1. If everything's the same, why does it only work on mGBA (not the core)? Do you want me to send you the save file, so that you can check for yourself that it's not because I did something wrong? I have done this exact same thing many times before, and this is the first time I have encountered this problem.
