### ISSUE TITLE
Final Fantasy VII only intro

### ISSUE THREAD

**Issue by knightofjaffa** [OpenEmu/OpenEmu#3595]
i have downloaded Final Fantasy VII and followed the m3u instructions but when i open up final fantasy it is only the intro and then repeats

**Comment by clobber** [comment]
So the game successfully imported and loads to its intro movie? Well then press a button.

**Comment by knightofjaffa** [comment]
i did press a button nothing happens

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
