### ISSUE TITLE
PS4 Controller Not working with some buttons

### ISSUE THREAD

**Issue by tdepiera** [OpenEmu/OpenEmu#3597]
I've seen in the issues list that this issue happened with L2 and R2, but my issue is happening with X, Square, Triangle and Circle. When I go to edit the controls, when I press those buttons nothing happens. Im currently running version 2.0.6.1

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
