### ISSUE TITLE
Compiling BuildAll scheme in Xcode 9.3: Mednafen fails to link with missing symbols

### ISSUE THREAD

**Issue by orj** [OpenEmu/OpenEmu#3598]
```
Undefined symbols for architecture x86_64:
  "_memcpy_up", referenced from:
      _qlz_decompress_core in quicklz.o
  "_fast_read", referenced from:
      _qlz_compress_core in quicklz.o
      _qlz_decompress_core in quicklz.o
      _qlz_size_decompressed in quicklz.o
      _qlz_size_compressed in quicklz.o
  "_hash_func", referenced from:
      _qlz_compress_core in quicklz.o
      _qlz_decompress_core in quicklz.o
  "_fast_read_safe", referenced from:
      _qlz_decompress_core in quicklz.o
  "_fast_write", referenced from:
      _qlz_compress_core in quicklz.o
      _qlz_compress in quicklz.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It looks like the methods declared `__inline` are causing linker errors when linking Mednafen.

I'm going to see if I can figure out why.

**Comment by orj** [comment]
Adding `-D__inline=__attribute__((always_inline))` to `OTHER_CFLAGS` seems to solve compile/link issue.

**Comment by clobber** [comment]
Pretty sure those get triggered when you’re building for debug, which you should not be doing.

**Comment by orj** [comment]
@clobber I'm just building the default `Build All` scheme. I assume you guys only build in release for performance reasons.  Is there something I need to tweak to get the project to build in release by default?

**Comment by clobber** [comment]
Follow the [compile guide](https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide) if you want to correctly build the app + core plugins. Building in Xcode isn't as simple as just clicking the big iTunes-style play button. Most of the core plugins rely heavily on optimizations to run at full speed. Under zero circumstances should they be built in debug.
