### ISSUE TITLE
Mame Arcade Controller

### ISSUE THREAD

**Issue by JasonNewton1** [OpenEmu/OpenEmu#3599]
Hi there,

This isn't really an issue more a question. I realise that MAME arcade support is in the experimental build only but the games I have downloaded including Neo Geo titles run very well indeed. Could you recommend any USB controller for arcade titles rather than using the keyboard?

Kind Regards

**Comment by clobber** [comment]
Any of the [automap supported](https://github.com/OpenEmu/OpenEmu/wiki#automap-supported-controllers) controllers would probably do fine. Cannot speak to the ["Arcade style" gamepads](https://www.amazon.com/Neogeo-x-Arcade-Stick-Electronic-Games/dp/B0098F6PSY) as I've never used them.
