### ISSUE TITLE
Nestopia Dip Switches

### ISSUE THREAD

**Issue by cvn** [OpenEmu/OpenEmu#3600]
Hello,

I'm running a game called Super 42-in-1 (found online as "Super 42-in-1 [a1]"), and it supports two different operating modes. When opening the rom with the [macOS version of Nestopia](http://bannister.org/software/nestopia.htm), it shows me a Dip Switches dialog (pictured below) and allows me to choose a mode. With a real NES, I can switch modes by turning the system on and off. And using the FCEU core in OpenEmu, I can switch modes by resetting the console.

<p align="center"><img width="202" src="https://user-images.githubusercontent.com/774864/38804104-cdb937ae-41a3-11e8-99c3-1fcda4cbbfda.png"></p>

Is there any way to modify the dip switches when using the Nestopia core in OpenEmu? If not, I'd like to request support for this.

It appears that this is [supported by the Nestopia API](https://github.com/0ldsk00l/nestopia/blob/master/doc/details/api/Nes..Api..DipSwitches.html), so hopefully it's within the realm of possibility for OpenEmu.

Thank you,
Chad

**Comment by clobber** [comment]
Advanced core prefs/options. #1281
