### ISSUE TITLE
Open Emu 2.0.6.1 Won't Read PS1 Multi-Files 

### ISSUE THREAD

**Issue by Comando217** [OpenEmu/OpenEmu#3606]
Dear Supporter

Sorry didn't mean to press enter right away and it sent it off so thats my apologies for the last case file. But incase you didn't get the updated info.

For the last little bit I've been trying to get Final Fantasy VII or Metal Gear Solid to work on the Open Emu. However I've followed your guides and even video tutorials as to read them. I've put the .cue files into Open Emu, then open TextMate, made sure that the settings were correct

(exp.)
Final Fantasy VII Disc 1.cue
Final Fantasy VII Disc 2.cue
Final Fantasy VII Disc 3.cue

Deleteting all the other information as to only leaving the name of the actual file and replacing anything to .cue.

Saving the file as a m3u file and then exporting it.

I've dragged it in to Open Emu every time but it seems not to read it. Is this due to High Sierra?

**Comment by clobber** [comment]
You are not following the guide correctly, and video tutorials are incorrect. Read our official guide very carefully, word for word, including the opening paragraph taking note of the words in bold. Can't help you beyond this - problem is on your end.

#3605
