### ISSUE TITLE
Laserdisc support?

### ISSUE THREAD

**Issue by mcdado** [OpenEmu/OpenEmu#3608]
Hello! After years of disuse, I dusted OpenEmu again, and look for more stuff to run in it.
I realized you cannot run laserdisc games like the various Dragon's Lair, Time Warp, Space Ace, etc, and while looking around I found that there is an emulator that is [even distributed](http://www.daphne-emu.com/site3/index_hi.php) for macOS. Here are some options:

- [Daphne](http://www.daphne-emu.com/) - [an updated GitHub repo](https://github.com/DavidGriffith/daphne), there's [a port for RetroPie](https://github.com/Shmoopty/daphne-pi), see [RetroPie docs](https://github.com/retropie/retropie-setup/wiki/Daphne).
- [Hypseus](https://github.com/btolab/hypseus), by @btolab @h0tw1r3, a fork of Daphne with some updates.

Would it work to add it as an emulator in OpenEmu?
Cheers!

**Comment by clobber** [comment]
Not much interest in this now, but I've added it to our "[wish list](https://github.com/OpenEmu/OpenEmu/wiki/Console---Core-Plugin-Status-&-Wishlist#wish-list)" to check out in the future. It may or may not be a good fit.
