### ISSUE TITLE
N64 Games Stuttering Audio / Video

### ISSUE THREAD

**Issue by wardiz** [OpenEmu/OpenEmu#3609]
My System: Mac OSX 10.11.6; 2.8GHz Core i7; 16GB Ram; OpenEmu v2.0.6.1

After my last OE update, almost all my N64 games are stuttering, audio and video, from the title screen through gameplay. I'm thinking I need to update my OS, but don't want to do that unless I have to.

Thanks!

**Comment by clobber** [comment]
>I'm thinking I need to update my OS, but don't want to do that unless I have to

Yes, you should update your install of macOS. Apple releases updates (with important GPU driver bug fixes and improvements) for a reason.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3447
