### ISSUE TITLE
Darkstalkers Chronicle: The Chaos Tower MAC sprites not showing

### ISSUE THREAD

**Issue by birabiro** [OpenEmu/OpenEmu#3611]
so i've been trying to play the game on my macbook but the sprites are not showing up, i cant seem to find a solution
![darkstalkers chronicle the chaos tower 2018-04-24 1 17 18 pm](https://user-images.githubusercontent.com/38690230/39183925-f442639a-47c1-11e8-98fa-43a422c67b43.png)
![darkstalkers chronicle the chaos tower 2018-04-24 1 17 12 pm](https://user-images.githubusercontent.com/38690230/39183926-f467dbe8-47c1-11e8-9b02-4c83f52278c2.png)
![darkstalkers chronicle the chaos tower 2018-04-24 1 16 54 pm](https://user-images.githubusercontent.com/38690230/39183928-f48b7ee0-47c1-11e8-9405-b12cbf9ffffc.png)

**Comment by clobber** [comment]
PPSSPP bug, not ours. I'm sure it will be fixed eventually.

https://github.com/hrydgard/ppsspp/issues/6647
