### ISSUE TITLE
OpenEmu will not "unhide" when running emulation

### ISSUE THREAD

**Issue by danlei88** [OpenEmu/OpenEmu#3612]
OpenEmu version: v2.0.6.1
OS X version: 10.13.1

When running any emulation in OpenEmu and clicking the yellow round hide button in the emulation window to hide OpenEmu, I can't unhide the emulation in order to return to the emulation. The emulation window doesn't come back up no matter what I try.

OpenEmu needs to be quit and restarted instead. This issue started after the latest update if I recall correctly.

**Comment by danlei88** [comment]
Thank you for the reply!

Clicking the Dock icon does nothing, nor does right-clicking the icon and selecting "show". Though this only happens if you minimize using the yellow icon in the OS X windows, between the red and green ones. 

If I hide the window by right-clicking the dock icon and selecting "hide", then I can restore the window back up by left-clicking and selecting "show" or just left-clicking the dock icon.

So the issue is just when you use the yellow minimize-button in the window itself. Not an issue you can't work around of but thought you guys just might want to know about it.

**Comment by robotoad** [comment]
I'm not referring to the OpenEmu icon on the Dock. I mean the minimized window that appears on the right side of the Dock next to the trash can when you click the yellow button. What happens when you click that?

Hiding and showing windows are a different operation from minimizing, so that is behaving correctly.

**Comment by danlei88** [comment]
Oh.. it has a separate icon..

Clicking that icon does restore the emulation. So the issue was my idiocy and not a bug. Sorry to have taken your time with this and thank you ever so much for your assistance.

Keep up the good work, OpenEmu guys. This is by far the best emulator I've ever used.
