### ISSUE TITLE
Enable Mouse-Paddle in Stella

### ISSUE THREAD

**Issue by dragonfax** [OpenEmu/OpenEmu#3613]
This isn't about adding paddle controller support in OpenEmu. Rather its about enabling a feature that already exists in Stella.

Stella has a great feature to emulate a paddle controller using your mouse. It works great, and makes many paddle games on the 2600 playable without terrible joystick emulation or using some extra hardware and adapters.

OpenEmu doesn't support this option in Stella, though. So to use it you have to install and launch Stella directly. It would be nice to have this option available from within OpenEmu.

The one caveat is that Stella grabs your mouse when you play a game using this feature. So that would have to be dealt with.

**Comment by clobber** [comment]
Said feature in Stella is probably a frontend feature, meaning we would need to implement something equivalent in both OpenEmu and the Stella core plugin, so it's not as simple as just "enabling an  existing option." Anyway, this should be opened in https://github.com/OpenEmu/Stella-Core/ instead.
