### ISSUE TITLE
N64 ROMs start up with broken title screens; broken audio and video

### ISSUE THREAD

**Issue by Mousecopp** [OpenEmu/OpenEmu#3616]
I am currently using MacOS 10.13.4, High Sierra, on a Late 2013 Retina 13" MacBook Pro, running OpenEmu 2.0.6.1 (I also tried 2.0, but the same issue occurred).  I have additionally tried uninstalling and re-downloading OpenEmu multiple times, to no avail, as well as removing and re-downloading the ROMs themselves.  Attached is a video I took of exactly what happened, as it is hard to explain otherwise (.mov file, opens with quicktime player on my end at least).  The app and the rom both quit normally when told when using the red power button on the bottom, the red x in the window, and cmd+q.  But when looking in the console for a system log, I only found commands related to teamviewer?  I'm not sure if it's referring to the communications application (which I removed years ago and can't even find any remnants of), or something else entirely.  Below the video is what I copied and pasted, but considering I'm not very knowledgeable on this kind of stuff, I apologize if it isn't what you needed.  Thanks so much for your help!  

[OpenEmuCrash.MOV.zip](https://github.com/OpenEmu/OpenEmu/files/1962332/OpenEmuCrash.MOV.zip)

Apr 30 18:04:09 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.teamviewer[27575]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Applications/TeamViewer.app/Contents/MacOS: 17E199: xpcproxy + 11056 [1405][4ED93E24-75BD-3853-BE35-0C1F3B4A9AA9]: 0x2
Apr 30 18:04:09 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.teamviewer): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Apr 30 18:04:09 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.desktop[27576]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Applications/TeamViewer.app/Contents/Helpers: 17E199: xpcproxy + 11056 [1405][4ED93E24-75BD-3853-BE35-0C1F3B4A9AA9]: 0x2
Apr 30 18:04:09 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.desktop): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Apr 30 18:04:10 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100007.Aqua): Caller not allowed to perform action: plugin-containe.27579, action = pid-local registration, code = 1: Operation not permitted, uid = 501, euid = 501, gid = 20, egid = 20, asid = 100007
Apr 30 18:04:11 --- last message repeated 1 time ---
Apr 30 18:04:11 Drews-MacBook-Pro OpenEmu[27124]: OE_removeStateWatcher
Apr 30 18:04:11 Drews-MacBook-Pro systemstats[66]: assertion failed: 17E199: systemstats + 914800 [D1E75C38-62CE-3D77-9ED3-5F6D38EF0676]: 0x40
Apr 30 18:04:13 --- last message repeated 1 time ---
Apr 30 18:04:13 Drews-MacBook-Pro OpenEmu[27587]: system plugins not registered in database, because the db does not exist yet!
Apr 30 18:04:13 --- last message repeated 28 times ---
Apr 30 18:04:13 Drews-MacBook-Pro OpenEmu[27587]: Apple Internal Keyboard / Trackpad
Apr 30 18:04:13 Drews-MacBook-Pro OpenEmu[27587]: OELibraryDatabase loadFromURL: 'file:///Users/DrewTudor/Library/Application%20Support/OpenEmu/Game%20Library/'
Apr 30 18:04:14 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.service[27590]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Applications/TeamViewer.app/Contents/MacOS: 17E199: xpcproxy + 11056 [1405][4ED93E24-75BD-3853-BE35-0C1F3B4A9AA9]: 0x2
Apr 30 18:04:14 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.service): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Apr 30 18:04:15 Drews-MacBook-Pro OpenEmuHelperApp[27596]: parent application is: OpenEmu
Apr 30 18:04:15 Drews-MacBook-Pro OpenEmuHelperApp[27596]: Apple Internal Keyboard / Trackpad
Apr 30 18:04:15 Drews-MacBook-Pro OpenEmuHelperApp[27596]: Setting up emulation
Apr 30 18:04:15 Drews-MacBook-Pro OpenEmu[27587]: SETUP DONE.
Apr 30 18:04:16 Drews-MacBook-Pro OpenEmuHelperApp[27596]: Begin separate thread
Apr 30 18:04:16 Drews-MacBook-Pro OpenEmu[27587]: Display's nominal refresh rate is 59.97 Hz
Apr 30 18:04:19 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.teamviewer[27602]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Applications/TeamViewer.app/Contents/MacOS: 17E199: xpcproxy + 11056 [1405][4ED93E24-75BD-3853-BE35-0C1F3B4A9AA9]: 0x2
Apr 30 18:04:19 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.teamviewer): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Apr 30 18:04:19 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.desktop[27603]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Applications/TeamViewer.app/Contents/Helpers: 17E199: xpcproxy + 11056 [1405][4ED93E24-75BD-3853-BE35-0C1F3B4A9AA9]: 0x2
Apr 30 18:04:19 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.desktop): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Apr 30 18:04:24 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.service[27614]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Applications/TeamViewer.app/Contents/MacOS: 17E199: xpcproxy + 11056 [1405][4ED93E24-75BD-3853-BE35-0C1F3B4A9AA9]: 0x2
Apr 30 18:04:24 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.service): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Apr 30 18:04:26 Drews-MacBook-Pro OpenEmu[27587]: Helper Connection (0x604000482cb0) failed with error: Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 27596" UserInfo={NSDebugDescription=connection from pid 27596}
Apr 30 18:04:28 Drews-MacBook-Pro OpenEmu[27587]: Deallocating proxy: <OEThreadProxy 0x60400044cfc0, target: <OEGameDocument 0x604000193db0, ROM: 'Star Revenge 5.5 Destroyed Memories', System: 'openemu.system.n64', Core: 'org.openemu.Mupen64Plus'>>
Apr 30 18:04:29 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.teamviewer[27625]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Applications/TeamViewer.app/Contents/MacOS: 17E199: xpcproxy + 11056 [1405][4ED93E24-75BD-3853-BE35-0C1F3B4A9AA9]: 0x2
Apr 30 18:04:29 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.teamviewer): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Apr 30 18:04:29 Drews-MacBook-Pro com.apple.xpc.launchd[1] (com.teamviewer.desktop[27626]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Applications/TeamViewer.app/Contents/Helpers: 17E199: xpcproxy + 11056 [1405][4ED93E24-75BD-3853-BE35-0C1F3B4A9AA9]: 0x2

**Comment by clobber** [comment]
Mario 64 and other N64 ROM hacks are notorious for not working on real N64 hardware by taking advantage of old broken emulator behavior. As emulators are going in the direction of accuracy it will be up to the ROM hackers to fix their hacks.
