### ISSUE TITLE
Loading saves that have been used in other emulators

### ISSUE THREAD

**Issue by CobaltMan142** [OpenEmu/OpenEmu#3618]
I'm having trouble loading the saves for the games I have, on GBA in particular.  I already put the ROMs into OpenEmu, but i can't load my saved games on them. Help is most definitely appreciated.

**Comment by clobber** [comment]
There is a transfer guide that should help. That is the best we can do.

https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files
