### ISSUE TITLE
Arcade : player 2 controller doesn't work.

### ISSUE THREAD

**Issue by ladirection** [OpenEmu/OpenEmu#3619]
Hello,
I have the exact same issue reported here: https://github.com/OpenEmu/OpenEmu/issues/2770

 I plug two Logitech 310 on a Macbook pro (latest), I can "put in quarters" and press start but then nothing on player 2. Player 1 works fine. Both controllers are set to "D". Both work fine in SNES, Genesis or NES.

I tried X-Men 2 players, TMNT, Contra and Final Fight.

I'm running OpenEmu 2.0.6.1, Latest Mac OS and updates.

Thanks!

**Comment by clobber** [comment]
We don't need a duplicate issue opened for this.
