### ISSUE TITLE
mac 64-bit builds?

### ISSUE THREAD

**Issue by ShikiSuen** [OpenEmu/OpenEmu#3622]
Since macOS 10.14 all 32-bit macOS apps won't be supported to run on macOS anymore.
At this moment macOS 10.13.4 offers 64-bit-only mode to help developers prepare their apps for macOS 10.14 and later.

I also noticed that the 64-bit PPSSPPSDL runs smoother in graphics (regardless the unendurable sound glitches) and generates less heat to my laptop palmrests, wondering whether the implementation of 64-bit support could help OpenEMU runs faster with less system workload.

**Comment by clobber** [comment]
Did you check? Our app is 64-bit and has been since the start.
