### ISSUE TITLE
SNES - Cannot load ROM

### ISSUE THREAD

**Issue by SRQSTIG** [OpenEmu/OpenEmu#3623]
Just happened recently, was working not more than a week or 2 ago.  Ended up moving my computer from one location to another and when I tried to load up any SNES game, I keep running across the same error "The emulator could not load ROM."  The ROMs have not been moved from their folders or anything different than normal.  Not sure if anyone else is experiencing these problems or not?

**Comment by clobber** [comment]
>moving my computer from one location to another

Not enough details here to troubleshoot. Physically moved your computer? Something had to have changed in order for the ROM to no longer load. You can check Console.app for output.

**Comment by SRQSTIG** [comment]
Yes, I physically moved.  Had no problems before.  Loaded up OpenEmu on the computer and whenever I try to load any SNES game, it comes up with that error.  Where is console.app?  I will give you whatever readout you need to assist.

**Comment by clobber** [comment]
[Spotlight search](https://support.apple.com/en-us/HT204014) (magnifying glass in the upper right corner on your screen - it's how one finds files and apps on their Mac). You click it and type Console and press enter.

Filter Console for openemu, try to load a game, then copy and paste the output back here.

**Comment by SRQSTIG** [comment]
default	10:05:01.362026 -0400	OpenEmu	Task <E90F7427-E624-4664-806A-D32603670F14>.<0> received response, status 301 content K
default	10:05:01.362172 -0400	OpenEmu	Task <E90F7427-E624-4664-806A-D32603670F14>.<0> response ended
default	10:05:01.362550 -0400	OpenEmu	Task <E90F7427-E624-4664-806A-D32603670F14>.<0> now using Connection 8
default	10:05:01.362661 -0400	OpenEmu	Task <E90F7427-E624-4664-806A-D32603670F14>.<0> sent request, body N
default	10:05:01.375914 -0400	OpenEmu	Task <E90F7427-E624-4664-806A-D32603670F14>.<0> received response, status 200 content K
default	10:05:01.376069 -0400	OpenEmu	Task <E90F7427-E624-4664-806A-D32603670F14>.<0> response ended
default	10:05:06.269942 -0400	OpenEmu	Adding presenter 2ACD957C-6D79-4DC7-A45D-56E61961F749 for URL: <private>
default	10:05:06.270403 -0400	OpenEmu	Error loading /Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x:  dlopen(/Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x, 265): no suitable image found.  Did find:
	/Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x: truncated mach-o error: segment __TEXT extends to 2723840 which is past end of file 909312
	/Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x: truncated mach-o error: segment __TEXT extends to 2723840 which is past end of file 909312
default	10:05:06.408099 -0400	OpenEmuHelperApp	parent application is: OpenEmu
default	10:05:06.409948 -0400	OpenEmuHelperApp	IOHIDDeviceClass::start: elementCount=16 reportHandlerCount=4
default	10:05:06.409979 -0400	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=0 *buffer=7f9d48032630 *count=16 size=1536
default	10:05:06.410023 -0400	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=1 *buffer=7f9d46e19a90 *count=4 size=384
default	10:05:06.411627 -0400	OpenEmuHelperApp	Magic Keyboard
default	10:05:06.477456 -0400	OpenEmuHelperApp	Error loading /Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x:  dlopen(/Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x, 265): no suitable image found.  Did find:
	/Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x: truncated mach-o error: segment __TEXT extends to 2723840 which is past end of file 909312
	/Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x: truncated mach-o error: segment __TEXT extends to 2723840 which is past end of file 909312
default	10:05:06.482231 -0400	OpenEmuHelperApp	ROM did not load.
default	10:05:06.484463 -0400	OpenEmu	Removing presenter 2ACD957C-6D79-4DC7-A45D-56E61961F749
default	10:05:06.484585 -0400	OpenEmu	Removing presenter 2ACD957C-6D79-4DC7-A45D-56E61961F749
default	10:05:10.100108 -0400	OpenEmu	LSExceptions shared instance invalidated for timeout.

**Comment by SRQSTIG** [comment]
hope this is what you are looking for

**Comment by clobber** [comment]
> default 10:05:06.477456 -0400 OpenEmuHelperApp Error loading /Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x: dlopen(/Users/richardgilbert/Library/Application Support/OpenEmu/Cores/SNES9x.oecoreplugin/Contents/MacOS/SNES9x, 265): no suitable image found. Did find:

Something on your end changed, because the core plugins are either corrupt or missing. I don't know which version of OpenEmu you are using. I'd say go into your cores folder (appears to be /Users/richardgilbert/Library/Application Support/OpenEmu/Cores), delete them and then redownload them all from inside the app: OpenEmu > Preferences > Cores.
