### ISSUE TITLE
Unable to save in game for gba emulator

### ISSUE THREAD

**Issue by jeremypng99** [OpenEmu/OpenEmu#3624]
hi, I recently used openemu to play Zelda. however, as I finished the game and they prompted me to save the game, I said yes but as the game rebooted it did not have the save file and instead took me to my previous save file. may I know why this is happening? thanks for any feedback. and the save files are all within the game not the open emu save states.

**Comment by clobber** [comment]
I assume that is just how that particular game works. Likely not a bug with the emulator core.
