### ISSUE TITLE
Playstation 1 emulator won't work with controller

### ISSUE THREAD

**Issue by goobsten** [OpenEmu/OpenEmu#3627]
I have managed to set up the ps1 emulator and i can play games using the keyboard, but when i plug in  a controller none of the buttons register, i have tried this with 2 controllers (xbox one, nintendo switch wired controller) and both of these controllers work with other emulators (N64, NES)  Is there some file i need to download to make it work?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
