### ISSUE TITLE
An error occurred during persistent store migration.

### ISSUE THREAD

**Issue by wadijm** [OpenEmu/OpenEmu#3628]
Tried to open Dragon Ball Z - Shin Budokai (USA) for psp , got black screen, then reset the app and got 'An error occurred during persistent store migration.'
Using High Sierra 10.13.3

**Comment by clobber** [comment]
>An error occurred during persistent store migration

Don't know which version of OpenEmu you were upgrading from or which one you are using now but it's too late to fix any migration issue: #2649

As for your PSP game, PPSSPP has either a compatibility issue with the game or the old save state itself. Can't do anything about that. Try the following to get it to load:

* In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" when prompted to "Continue where you left off"
