### ISSUE TITLE
syscard3.pce doesn't work

### ISSUE THREAD

**Issue by greengamerUSSR** [OpenEmu/OpenEmu#3629]
After the last openemu update, most of my BIOS were gone for some reason, so i re-downloaded all of them from the same sites where i had got them originally, except for syscard3.pce. I did the exact same than before, but when i launch my game it tells me syscard3.pce is missing.

**Comment by clobber** [comment]
Only reason BIOS files can be removed is if they are invalid. Read the BIOS guide regarding syscard3 (it changed in a past Mednafen core plugin update)... it's why we wrote a guide.

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files
