### ISSUE TITLE
N64 core Mupen64Plus only compilation

### ISSUE THREAD

**Issue by StenApp** [OpenEmu/OpenEmu#3630]
I want to test gonetz' alpha version of GlideN64 https://www.indiegogo.com/projects/indiana-j-infernal-machine-high-level-emulation#/updates/all.
My only chance is use OpenEmu. How can I replace the GlideN64 file?

When I change the file in Mupen64Plus.oecoreplugin there is no graphics.....
Any hint how to succeed this task?

**Comment by StenApp** [comment]
@clobber  Is it possible to use the updated https://github.com/gonetz/GLideN64/tree/indi_naboo and compile OpenEmu on my own?

**Comment by StenApp** [comment]
Throws errors over errors and I don't know how to fix

**Comment by clobber** [comment]
Sorry, no. That is code from a Work In Progress branch and hasn't been merged in master yet. We will update our core port with the latest 'stable' branch code, which requires changes besides just plunking in some files and expecting it to compile, when we get around to it. Please stop pestering about this.
