### ISSUE TITLE
Genesis Sound Bugs

### ISSUE THREAD

**Issue by Davy6502** [OpenEmu/OpenEmu#3631]
I've recently been experiencing a few weird sound bugs, specifically for Genesis emulation. Is anyone else having this issue? And is there a possible fix?

**Comment by Davy6502** [comment]
@clobber Well, on my end, the game most effective to hear the bug is Shining Force's City Theme. It has a strange "echo" that you can hear with a high enough volume. Here's the City Theme from original hardware here: https://www.youtube.com/watch?v=4Rc2_6uWOhE, then compare it to what the emulator is playing.

**Comment by clobber** [comment]
Um, doesn't sound like a "bug" at all, but rather the particular revision of the Yamaha audio chip that Genesis Plus GX emulates and its default settings https://github.com/OpenEmu/GenesisPlus-Core/blob/master/GenPlusGameCore.m#L707-L721. Of course the discrete YM2612 sounds different than an ASIC YM3483 "MegaAmp" mod...

**Comment by Davy6502** [comment]
Ah, ok. Thank you. I wasn't aware of that. Lol
