### ISSUE TITLE
OpenEmu won't read keyboard input

### ISSUE THREAD

**Issue by bluebocat** [OpenEmu/OpenEmu#3633]
I previously set my input for all my games to be keyboard input, however when I try to change controls from, for example, "W" for UP on the analog stick to "T", OpenEmu won't register any keystrokes at all.

**Comment by clobber** [comment]
OpenEmu responds to both keyboard and gamepad input at the same time. So you are able to press a keyboard button (and use that) even while a gamepad is plugged in. The drop down menus in Controls Preferences are only for mapping controls, **not** "setting" which type of input works per-system.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
