### ISSUE TITLE
macOS 10.14 deprecates OpenGL/CL

### ISSUE THREAD

**Issue by gh0sti** [OpenEmu/OpenEmu#3634]
Looks like Openemu will need to be ported to Metal sadly with macOS 10.14
![image](https://user-images.githubusercontent.com/4202657/40940658-190de7c8-680e-11e8-993e-26d6c4d79c3f.png)

**Comment by clobber** [comment]
We read the news too - deprecated in 10.14 doesn't mean removed. OpenEmu will still run just fine on 10.14 pretty much as-is. We will eventually be removing support for 10.11 and having a Metal renderer, though. Future stuff. At the moment, the OpenGL renderer is here to stay for all the core plugins that currently need it (PPSSPP, Mupen64Plus, etc).
