### ISSUE TITLE
No Longer Able to Compile after Xcode Update

### ISSUE THREAD

**Issue by TRIFORCE89** [OpenEmu/OpenEmu#3637]
Following an update to Xcode v9.4 and Command Line Tools v10 I am no longer to compile OpenEmu.

Following the "Compiling From Source Guide" I get "no type or protocol named 'OEAudioBuffer'"

If I try through the Xcode GUI as I usually do (to update just those cores I have modified alone), I get similar behaviour to https://github.com/OpenEmu/OpenEmu/issues/3215 and https://github.com/OpenEmu/OpenEmu/issues/3073

I have deleted the application in full and my local repos, checking out the project fresh.

**Comment by clobber** [comment]
It sounds to me that you do not have OpenEmu-SDK checked out with the latest changes, as we cannot replicate your build error (you haven't really given good details on this though; Xcode is much more verbose). The app itself together with the SDK compile fine, using the OpenEmu build scheme.

>to update just those cores I have modified alone

I don't know which cores you modified or why, but perhaps the changes you made are related.
