### ISSUE TITLE
Banjo-Tooie N64 Crash during load/gameplay

### ISSUE THREAD

**Issue by erikmccomb** [OpenEmu/OpenEmu#3640]
When loading in to a new area, and occasionally during gameplay, emulation crashes but audio continues to play

**Comment by clobber** [comment]
Mupen64Plus and GPU plugin bug. This will improve in a future version of Mupen64Plus and GLideN64. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
