### ISSUE TITLE
4DO audio stutter in latest build (06-07-18)

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/OpenEmu#3641]
While i'm still trying to figure out what your latest SDL updates exactly do (regarding sound buffering, etc), i'd really appreciate it if you could/would tell me _why_ especially that core has problems with it, and where i'd have to look to fix it in the meantime. (I'd also understand if that's not your biggest concern at the moment, but thx anyway)

**Comment by clobber** [comment]
Sorry, like the guide says it’s alpha status (not to mention inactive) and unsupported.
