### ISSUE TITLE
Will the Dreamcast come to OpenEmu?

### ISSUE THREAD

**Issue by KayKuli99** [OpenEmu/OpenEmu#3642]
Hello,
I have used Open Emu a lot in the past few months, but this got me thinking, What about the Dreamcast? Not only is it one of the many classic consoles to come out the 90's but it had a great line up of games. I felt curious about why it's not on OpenEmu? I looked on GitHub for the answers but I saw that its confirmed unstable for the OpenEmu system. But the developer of the core (Riecast)
seems not interested in the computer interface but the development of the phone interface. This got to me, why not find a different Dreamcast core developer to help with the project and make it better on OpenEmu? I am not a tech-whiz, but I see true passion and amazing achievements by making the core work for OpenEmu. Getting the core of the Dreamcast to work would bring in more people who would bring in more gamers who want to play Dreamcast games on a stable emulator that does not kill their computer. I understand other people have requested this idea many times with other systems like the PlayStation 2, Gamecube and Atari Jaguar and other cores to be imported into OpenEmu. Dreamcast is just a simple core update to the system line up ahead of the PlayStation 1 and could benefit with the vast gaming experience being worthwhile for gamers who use Mac OSX for their everyday use. I am very hopeful in this project and hope to see it come along in the future. 
Thank You,
-Kay Kuli

**Comment by clobber** [comment]
All of the available Dreamcast emulators are still low compatibility and alpha status. So to answer your question: no, not any time soon.

**Comment by faridSoussi** [comment]
Dreamcast emulation is not "low compatibility and alpha status" on PC... Its working pretty well, actually.
