### ISSUE TITLE
pb with hori fighting commander

### ISSUE THREAD

**Issue by alexpiolho** [OpenEmu/OpenEmu#3645]
Hi, 
When I plugged in with my fighting commander OpenEmu recognized It (fighting commander in the little window) but I can't mapped any button. 
Sometimes I can mapped buttons but if I press the L1 I can't map anything.
How can I do ?

Thx,

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
