### ISSUE TITLE
Can't get the right pad on the steam controller to work

### ISSUE THREAD

**Issue by Muscarv2** [OpenEmu/OpenEmu#3647]
Hello, I've been able to get all buttons configured and working in OpenEmu with the steam controller except for the right pad. I've set the steam controller as an xbox 360 controller, but when I choose desktop configuration in the steam big picture mode and try to edit the controls there it doesn't show an image of a controller so I can select what buttons to map. So I made an xbox config for another game and imported it into the desktop configuration instead, and everything works fine except the right pad as said. Anyone know how to fix this? Here's what it looks like in big picture mode: http://u.cubeupload.com/Muscar/ScreenShot20180616at.png

And the controller settings window: http://u.cubeupload.com/Muscar/a48ScreenShot20180616at.png

I've tried setting the right pad as button pad, directional pad and right stick, nothing works. OpenEmu just doesn't recognise the clicks.

**Comment by clobber** [comment]
As far as I know, this isn't our problem but maybe this helps: https://github.com/OpenEmu/OpenEmu/issues/2855#issuecomment-289253332
