### ISSUE TITLE
using Rock candy controller for Metroid prime-C stick won't work

### ISSUE THREAD

**Issue by runupaway** [OpenEmu/OpenEmu#3648]
So Im playing metroid prime on openemu, and on getting the wave beam, your are supposed to use the c-stick to select it. Well, for some reason openemu will not recognize the analog stick that rock candy has as the c- stick.....and I cannot go any further in the game.
![screen shot 2018-06-16 at 9 40 00 pm](https://user-images.githubusercontent.com/40328041/41503923-d8ac61ba-71ad-11e8-8423-963481980aaf.png)

Does anybody know if I am doomed? or if there is a way around this? Keep in mind Im not a programmer so I am a novice in my understanding

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
