### ISSUE TITLE
Not importing new roms after changing game library location

### ISSUE THREAD

**Issue by hilfmirbitte** [OpenEmu/OpenEmu#3651]
I receive the following error in console when I try to add new SNES games.

Error Domain=OEImportFatalDomain Code=3 "(null)"

**Comment by clobber** [comment]
> OEImportErrorCodeNoSystem = 3

I doubt this has anything to do with changing library locations. Whatever you're trying to import, a valid system cannot be determined. Perhaps you don't have the SNES system enabled or the file you are trying to import is not .sfc/.smc (dunno, you didn't specify).

**Comment by hilfmirbitte** [comment]
It's an .smc and obviously I have the system enabled.

see below:

<img width="1269" alt="screen shot 2018-06-24 at 10 32 39" src="https://user-images.githubusercontent.com/16275197/41817367-08c75872-779a-11e8-873c-75cdf6ce6836.png">
<img width="108" alt="screen shot 2018-06-24 at 10 32 49" src="https://user-images.githubusercontent.com/16275197/41817368-08e0bb32-779a-11e8-8347-88218f0b53c9.png">

**Comment by clobber** [comment]
Download the following file and try to import: https://transfer.sh/IVyCs/bsnesdemo.sfc

What happens?
