### ISSUE TITLE
Can't Delete Saves

### ISSUE THREAD

**Issue by Sammiechu** [OpenEmu/OpenEmu#3652]
I try and right-click to delete my save files but all it does is highlight the save, when i double click it just brings up the game the save is from. Please help

**Comment by clobber** [comment]
Cannot replicate. Save States tab > right click on state > select Delete Save State, works here. If you have actual conditions in which this doesn't work with a way to replicate it, let us know.

**Comment by jetibbetts** [comment]
I'm having this problem as well. I click the Save State menu button in the floating task bar, the menu drops down, I right-click the save state that I want to delete, and it just loads the save state. I've also tried alt-clicking and ctrl-clicking a save state - same result. Version 2.2 (6096.40-g3b560b8c-Release).

![Screen Shot 2020-01-23 at 1 56 56 PM](https://user-images.githubusercontent.com/3586227/73019010-58381980-3de8-11ea-81b4-8a06346c0a07.png)

**Comment by clobber** [comment]
>I'm having this problem as well.

Uhh, no you're not. You're trying to delete them in the wrong place.

Actually read:

**Save States tab > right click on state > select Delete Save State, works here.**
