### ISSUE TITLE
Random freezing on macOS High Sierra

### ISSUE THREAD

**Issue by veronocle** [OpenEmu/OpenEmu#3657]
Heyo. I've been using OpenEmu successfully for two or three weeks, primarily for Mother 3 on GBA. It's been doing all right so far, but recently I've been encountering random instances of freezing anywhere from a minute to several hours into gameplay. I'm running on macOS High Sierra 10.13.15 with a Mid 2012 11-inch MacBook Air.

**Comment by clobber** [comment]
Which version of OpenEmu? Using the mGBA core plugin?

**Comment by veronocle** [comment]
Yep, that's the one. I was considering downloading mGBA on its own, but the ROM I'm using is from EmuParadise and works best with OpenEmu.

**Comment by clobber** [comment]
Closing for lack of info. Sounds like you are not using OpenEmu 2.0.6.1 which fixed this problem.

**Comment by devejonn** [comment]
I'm facing the same problem, been using Openmu for like a few hours to play PSP games. i was playing without any problems until the game started freezing suddenly, Relaunched the game few times but still.
I'm using the latest version of Openmu (2.0.6.1), Any solutions?
