### ISSUE TITLE
OpenEmu doesn't work

### ISSUE THREAD

**Issue by peacestory** [OpenEmu/OpenEmu#3663]
OpenEmu, latest v.2.0.6.1, doesnt work on my mac, OS X El Capitan 10.11.6. Before upgrading OS from previous OS this mac had, it run OpenEmu without any problems. I upgraded OS to the latest one in 2016, and OpenEmu started to shutdown when I try to play games on it, GameBoyAdvance, DS, any games. I couldnt find a solution and then gave up to fix this, but I have been curious how it works. I am here to ask you to figure this out. Ive tried the way deleting OpenEmu completely, downloading the latest OpenEmu, v2, and then opening it with unarchiver app. 
Please help me.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible, with exact steps to replicate a problem" and "Include Console and crash logs, macOS and OpenEmu version, hardware information, ROM/game filenames, etc."

**Comment by clobber** [comment]
Closing for lack of info.
