### ISSUE TITLE
Trouble connection bluetooth controller

### ISSUE THREAD

**Issue by luigi0301** [OpenEmu/OpenEmu#3665]
Now I'm having a hard time connecting to my controller. Every time I try, the application crashes. What is going on??!!

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/OpenEmu/issues/3532#issuecomment-366541371
