### ISSUE TITLE
Save States

### ISSUE THREAD

**Issue by luigi0301** [OpenEmu/OpenEmu#3666]
Ok, so I saw my issues were deleted because they were duplicates. Thank you, I found the way to fix my problem despite having tried it last night. I have transferred my data to the mGBA core but I am still confused and I dont know if this is a duplicate either because I couldn't quite find the answer. Is there a way to transfer save states between VBA and mGBA battery saves? I managed to get my save data back but I want to know if there is another guide to transferring save states in a similar way. If they are just completely unusable now then I guess that is it. I redownloaded an older version of open emu. 2.0.2 if this helps

**Comment by clobber** [comment]
>Ok, so I saw my issues were deleted because they were duplicates

Nope, not deleted. They were answered, linked to relevant information and then closed.

>Is there a way to transfer save states between VBA and mGBA battery saves

Save states are incompatible between emulators. What you are asking is not possible. The only thing you can do is transfer out the old battery saves, which sounds like you've done.

>I redownloaded an older version of open emu. 2.0.2 if this helps

Old versions of OpenEmu are unsupported. We cannot help you any more beyond this.
