### ISSUE TITLE
white frozen screen 

### ISSUE THREAD

**Issue by PLATINUM012** [OpenEmu/OpenEmu#3667]
I was playing pokemon platinum with the game and suddenly there were consecutive flashes of white light in the screen, I thought it was a regular, and ended the emulator. But when the game back on, it was just a white screen freezing. Please help me with this, I put so much effort and time into this game day and night!

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/3632#issuecomment-392822996
