### ISSUE TITLE
N64 games loading with black screen.

### ISSUE THREAD

**Issue by Tetrix64** [OpenEmu/OpenEmu#3669]
Greetings,

I've been playing N64 games on OpenEmu (v2.0.2) for some time now and have been having issues with some ROMs with the N64 emulator. Unfortunately, I don't really remember when the issues surfaced, but from my best recollection, it was after I updated to High Sierra.

SM64 USA and Japan works perfectly, as well as other ROMs based off the actual game (having the same courses and worlds, except with a change in Mario's controls/physics/actions). Other games, like Star Road and Last Impact, don't seem to display anything but a black screen. These games used to work just fine, but now they display nothing.

From a previous post on a similar issue, I have the answers to the questions needed:

Q: Is it loading the game but just a black screen and you still hear sound? 
A: Yes, I can also control Mario (I can tell by listening to game audio)

Q: Is it crashing? 
A: No.

Q: Is there any output in Console.app when this happens? 
A: I had a look and there doesn't seem to be any error messages, but there is the normal output (as expected).

Q: What about after a machine reboot?
A: I've tried this and nothing changes.

Q: What happens if you try to load the games without restoring an autosave state on first load?
A: Nothing changes.

If any other information is needed, don't hesitate to ask.

**Comment by clobber** [comment]
> OpenEmu (v2.0.2)

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

We release updates with bugfixes and improvements.

> other ROMs based off the actual game

Those are ROM hacks. Please search before opening a new issue. https://github.com/OpenEmu/OpenEmu/issues/3445
