### ISSUE TITLE
Recording/Viewing Controller Presses

### ISSUE THREAD

**Issue by amstrudy** [OpenEmu/OpenEmu#3670]
I'm trying to hit a frame-perfect trick and I would love to be able to see my controller presses per frame, either in real-time or recorded. Is there any way to do this?

**Comment by clobber** [comment]
The next release will have a Step Frame Forward and Step Frame Backward functions that can be bound to input presses, but beyond that there is not and will not be any way to "see" controller presses, unless using a specialized game ROM that shows them in-game.
