### ISSUE TITLE
Wii U Gamecube Adapter Support

### ISSUE THREAD

**Issue by Yungbossaowtt** [OpenEmu/OpenEmu#3674]
It's been about half a year since you guys closed issue #1773 and I thought i should bring this up again. With there now being a functioning dolphin core for OpenEmu, I think you guys should consider adding support for the Wii U (and mayflash) Gamecube controller adapters so we can get our authentic Gamecube experience. Thank you for reading my suggestion :]

**Comment by clobber** [comment]
>guys closed issue #1773

That issue is open. Are your eyes broken?

>I thought i should bring this up again

Please don't.
