### ISSUE TITLE
Any macosx apps that send keystrokes?

### ISSUE THREAD

**Issue by jeffreybox** [OpenEmu/OpenEmu#3675]
I'm just trying to send a simple left, right, action infinite loop for grinding purposes.  I've used AutoHotKey tons on PC, but I see AppleScript is no go (link below). 

Someone recommended http://www.osculator.net/. However, Osculator looks like it just has an applescript interface... no idea how that app works.

- https://github.com/OpenEmu/OpenEmu/issues/116

- my code
<img width="423" alt="screen shot 2018-07-12 at 10 50 35 pm" src="https://user-images.githubusercontent.com/14154735/42669903-03d349e4-8626-11e8-837f-7fa3b8d9d82c.png">

**Comment by clobber** [comment]
Sorry no, I don't believe anything will work due to the nature of our input system (noted here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems#input-keyboardgamepad-not-working).

**Comment by jeffreybox** [comment]
Fair enough.  Thanks for the quick response.
