### ISSUE TITLE
NES classic controler not working/detected

### ISSUE THREAD

**Issue by DrLuthor** [OpenEmu/OpenEmu#3676]
Hi,

I was really to finally get my hands on a NES classic controller to play my classics games on openemu with the original feeling (since it's compatible with the Wiimote). But then, the world fall appart when I discovered that my brand new controller was not working at all. I even suspect it's not even detected by the emulator.

Do you think this is something you can work on?

**Comment by tomek75** [comment]
just get nes classic usb converter
https://www.amazon.com/Mayflash-Wii-Classic-Controller-Adapter/dp/B07BN49ZFR

**Comment by DrLuthor** [comment]
Thanks @tomek75 
But the idea is to play with a real "cordless" NES controller, not being stuck 1 meter from a screen.

**Comment by clobber** [comment]
Classic Controller attachment is not supported. There is no fix for this as of now.

Similar enough to #2371
