### ISSUE TITLE
Laggg!

### ISSUE THREAD

**Issue by SlashedFall5** [OpenEmu/OpenEmu#3677]
A few days back I downloaded OpenEmu and it worked fine for the first week or so. But then today when I opened it  and went into fullscreen it was extremely laggy and I couldn't  play. I used to use fullscreen and never changed the filter.
P.s. My GPU is 1536mb

**Comment by clobber** [comment]
Come back when you're learned to post actual useful information to troubleshoot and not just your GPU's video RAM size.
