### ISSUE TITLE
Crashes, when click on cartridge of video-game.

### ISSUE THREAD

**Issue by DankakaTheCat** [OpenEmu/OpenEmu#3678]
Hey. I still have problems with my OpenEmu. When I double-click on the image of a video-game, crashes. When I click on settings, same. But, you have to fix it. Please, do it right now or I'll be very upset. (PS: Clobber, if you close this project. I'll kill you in midnight. NO JOKE!)

**Comment by clobber** [comment]
Too stupid to read the [Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) and to post a crash log means you get no help.
