### ISSUE TITLE
Transferring NDS file lead to deletion of ROM

### ISSUE THREAD

**Issue by glitterfox19** [OpenEmu/OpenEmu#3680]
I have been playing on an NDS Pokemon Diamond ROM. I wanted to fix the issue re: impossible evolution, so, using the Universal Randomizer, I created a new ROM. I wanted to transfer my old save file to this new game. I tried following the steps in this attached guide: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files but was unable to. I now no longer have the original Diamond ROM, and cannot load my previous autosave file or my battery save file. Is there a way to transfer the battery save file to the new ROM, or do I just have to give up and start over?

**Comment by clobber** [comment]
Sorry, it is impossible that transferring a save file could physically delete a ROM imported in your Game Library, if that is what you are trying to say. It seems somewhere along the way you messed up save files with save states or did not follow the directions. Note that your battery save file needs to match up with the name of your ROM. Either way, nothing can be done to help you.
