### ISSUE TITLE
Question: Sending Keyboard Events

### ISSUE THREAD

**Issue by murphycrosby** [OpenEmu/OpenEmu#3681]
I've seen this asked a couple of times and I've read the troubleshooting page about Input Problems. ( https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems#input-keyboardgamepad-not-working)

In that he says that OpenEmu uses IOKit, my question is, is it possible to write a program that uses IOKit to inject the keyboard events?  If no, it is possible to use the OpenEmu SDK to do something similar?

**Comment by clobber** [comment]
Sorry, no, not possible as answered before. #3675

**Comment by murphycrosby** [comment]
@clobber, Although I wished you would be more helpful and/or provide a possible solution to accomplish what I was asking, I was able to figure out a way on my own.  

I am just now getting back to this, so that others don't have to do the trial and error I went through to accomplish this.

For others asking this question, look at the Karabiner-VirtualHIDDevice (https://github.com/tekezo/Karabiner-VirtualHIDDevice).  Although Mr. clobber may not support this, I have used it to play over 25,000 games of MsPacman with no issue.

If you'd like to see an Objective-C implementation of this, feel free to checkout my project. 
 https://github.com/murphycrosby/MsPacman-NEAT

**Comment by clobber** [comment]
I already answered with the information I had, and knowing how our input system works, it is generally not possible. I’m not going to code you up a solution to something that is unsupported, I have no interest in and doesn’t work in the first place. I also don’t appreciate the passive aggressive nature of your reply and the README in your repo, but congrats for getting something working that has no use or interest to anyone besides yourself!
