### ISSUE TITLE
OpenEmu 2.0.6.1 doesn't load into MacOS Sierra 10.12.6

### ISSUE THREAD

**Issue by Ismakhil** [OpenEmu/OpenEmu#3682]
I recently updated OpenEmu and when i open it, it always leave me this message "The operation could not be completed Foundation._GenericObjectError 0". I wanted to know why the game crashes and i opened the OpenEmu file and the MacOS file into it to load it by Terminal. The same message was written when I opened OpenEmu but i looked up in Terminal and the message ""The model used to open the store is incompatible with the one used to create the store" and i don't understand why. Another message says that the application failed to load optimized model at path /Users/macbookpro/Desktop/OpenEmu.app/Contents/Resources/OEDatabase.momd/OEDatabase 1.3.omo. Please fix this bug, you're the best.

**Comment by clobber** [comment]
See https://github.com/OpenEmu/OpenEmu/issues/2838#issuecomment-253702730
