### ISSUE TITLE
(8Bitdo SN30 Pro) crash on opening Preferences

### ISSUE THREAD

**Issue by kowgawd** [OpenEmu/OpenEmu#3683]
Attached is the Crash log from opening OpenEmu, and attempting to open Preferences.

Previously tried removing all files and folders from OpenEmu and starting from a fresh instal

Application Specific Information:
Performing @selector(showPreferencesWindow:) from sender NSMenuItem 0x6080000bfc80
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unknown control value for identifier: 'OEControllerNintendoSwitchProControllerRightAnalogUp' associated with key name: 'OEN64ButtonCUp''
terminating with uncaught exception of type NSException
abort() called

[OpenEmu_2018-07-24-091019.txt](https://github.com/OpenEmu/OpenEmu/files/2224028/OpenEmu_2018-07-24-091019.txt)

**Comment by kowgawd** [comment]
Update - Had an 8BitDo SNES Gamepad with Analogue sticks plugged in USB and charging, unplugging it allowed OpenEMU to start, run a ROM and open Preferences. Reconnecting the controller at this point allowed editing the settings and caused no crashes so far.

**Comment by clobber** [comment]
>8BitDo SNES Gamepad with Analogue sticks

There is a problem with using this device right now. Probably something with the HID profile it presents while plugged in and/or paired via Bluetooth. Don't own one to be able to troubleshoot it right now. Somewhat related to #3620
