### ISSUE TITLE
8bitdo d-pad East and West not recognized, mapping as buttons 197/196 (R2/L2)

### ISSUE THREAD

**Issue by heroicbrickroad** [OpenEmu/OpenEmu#3685]
I have an 8bitdo NESPro30 and it has always worked great with OpenEmu. For some reason it's no longer recognizing the East and West buttons on the d-pad, instead mapping East as 197 (L2) and West as 196 (R2). 

This is with the controller plugged into USB with OpenEmu recognizing it as 8bitdo NESPro30. When I connect the controller wirelessly OpenEmu recognizes it as a Sony PS4 controller and doesn't have the same issue. However if I plug the controller in to charge, it stops working again. 

I've tested the controller on the same emulators outside of OpenEmu and on a Switch, and the controller doesn't have the same issue. 

I've tried deleting the default.oebindings file but that didn't resolve the issue either. 

I can't get around the issue by just leaving them mapped incorrectly, as when the 196/197 are set to left and right, North and South are automatically removed from up/down assignments. It's very frustrating.

**Comment by clobber** [comment]
>When I connect the controller wirelessly OpenEmu recognizes it as a Sony PS4 controller and doesn't have the same issue.

What? I'm not sure under what circumstance that can happen. Maybe your are starting that 8bitdo device in the wrong "mode" because I have the NES30 Pro and never experienced this. It has it's own HID profile for various modes and connection types. PS4 shouldn't be one of them.

**Comment by clobber** [comment]
As expected, I could not replicate any issue with my NES30 Pro on firmware 4.10 connecting via Bluetooth or USB. Simply press the "power" button on the bottom of the device and it pairs without issue, being recognized as "8Bitdo NES30 Pro" in Bluetooth Preferences. Closing the app, unpairing the device, connecting via USB and relaunching the app shows the mappings being preserved as well and still working. Perhaps you are having a problem outlined in our [Input Troubleshooting guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) or you are not on their [latest firmware](http://support.8bitdo.com/) or using the wrong mode to pair (simply press power).

![screen shot 2018-07-28 at 10 01 31 am](https://user-images.githubusercontent.com/1303132/43357873-cd3456c4-924d-11e8-8e5d-3e8758787591.png)

**Comment by heroicbrickroad** [comment]
Thanks for checking, I guess I’ll just live with it. The controller works if it pairs as PS4, if it pairs as NESpro it’s not working at all, and when USB has the same problem as before even after trouble shooting. My controller is firmware 4.10 and OpenEmu 2.0.6.1.

This issue wasn’t happening a week ago, and isn’t happening outside of OpenEmu. Maybe it’s an OSX thing.

**Comment by clobber** [comment]
You have something wrong as it works here. How do you even get it to pair as a PS3 device?

**Comment by heroicbrickroad** [comment]
If I sync to Bluetooth using the Start+A my computer syncs it as “wireless controller” and then its shows as Sony PS4 in OpenEmu and works correctly. If I just turn it on and pair normally the computer recognizes it as “8bitdo NESPro” properly, as does OpenEmu, but it doesn’t response to button prompts in OpenEmu. The button mapping stuff is only happening with USB. Before today I’ve always used USB and never had an issue. 

I’m on an old iMac and just updated Sierra to 10.12.6 recently. Maybe that has to do with it.

Anyway, thanks for trying to look into it. I appreciate the effort. OpenEmu is awesome.

**Comment by heroicbrickroad** [comment]
I just reset and reconnected the controller a few times, and its working properly via Bluetooth now. Still not USB. It must be something wrong with my controller. Thanks again.

**Comment by clobber** [comment]
The fact that when pairing in mode "Start+A" the device tries to present itself as a PS4 is wrong. You shouldn't do this despite what the manual says. I don't know 8Bitdo's reason for adding this mode in the 4.x firmware but its HID profile does not match up with that of a real DualShock 4 so there is no way it could work with OpenEmu's built-in presets. If you pair the way I stated above and redo your mappings, it will always work in Bluetooth and USB.
