### ISSUE TITLE
Automatically loading a ROM

### ISSUE THREAD

**Issue by ShaolinDave** [OpenEmu/OpenEmu#3687]
Can I have OpenEmu automatically load a specific ROM every time it starts?

I seem to recall that option but can't seem to find it now.

(I'm trying to build a dedicated arcade cabinet using OpenEmu/MAME on an old MacBook to replaced a broken JAMMA Board)

**Comment by clobber** [comment]
There is no such option in Prefs and not something we'd add. It could be possible to do it via a command line shortcut.

>dedicated arcade cabinet using OpenEmu/MAME

Not a good solution. Use standalone MAME instead.

**Comment by ShaolinDave** [comment]
It's a great solution when I have a MacBook with no screen laying in my closet.
But okay, I'll look at command line.
