### ISSUE TITLE
Arkanoid NES, controls issue

### ISSUE THREAD

**Issue by Nomzter** [OpenEmu/OpenEmu#3689]
Howdy!
I have control issues with Arkanoid on NES (using NEStopia core). It's the only game where configured gamepad (XO controller) doesn't work but the game works with touchpad. How can I switch it back to standard gamepad controls?

**Comment by clobber** [comment]
Arkanoid is set up to use the "Arkanoid Controller" which in this case is simply the mouse. No other way to switch it back.
