### ISSUE TITLE
Macbook gets warm when playing TG-16/PCE

### ISSUE THREAD

**Issue by Davy6502** [OpenEmu/OpenEmu#3690]
This isn't really an issue, but rather a question of some kind. Anytime I play TG-16/PCE games, my Macbook gets significantly warmer to the point where the fans get into full gear. And it doesn't do that with the other emulators on OpenEmu. 

Why is that? Is it the way the emulator is pulled off or is it something else?

**Comment by clobber** [comment]
Post actual [useful information](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) or nobody can help you.
