### ISSUE TITLE
The operation couldn’t be completed. (OSStatus error 99999.)

### ISSUE THREAD

**Issue by CopperBrown** [OpenEmu/OpenEmu#3693]
Hello, 

Sorry in advance as I am a total noob. I tried installing the openemu software and I bypassed the "untrusted developer" and opened anyway to get the message "The operation couldn’t be completed. (OSStatus error 99999.)"

I spent a while trying to figure it out last night without any success. Has anyone else experienced this?

HAREWARE: MacBook Pro (15-inch, 2017), 3.1 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3, Intel HD Graphics 630 1536 MB
OS: 10.13.6 (17G65)
OPEN EMU VERSION: 2.0.6.1

**Comment by clobber** [comment]
It's corrupted for whatever reason. Delete the app, download a new copy of the [latest release](https://github.com/OpenEmu/OpenEmu/releases/latest), extract the zip file with the built-in Archive Utility in macOS (right click > Open With > Archive Utility), then right click OpenEmu app bundle and select Open. That is how you bypass the [Gatekeeper](https://support.apple.com/kb/PH25088?locale=en_US) check.

**Comment by CopperBrown** [comment]
Hi clobber, I have done this a number of times and it hasn't worked. Controversial, but I googled "alternative to openemu" and downloaded 'retroarch'. I have the exact same message. I am now starting to think this might be something with my computer but it's only six months old and I have done everything from repair disk permissions, first aid utility, the ol classic 'off and on again' and nothing. :(

**Comment by clobber** [comment]
You need to google search the actual error message for a solution: "OSStatus error 99999.". The problem isn't our app, it's your machine/macOS install. Can't help you beyond that - it's not an OpenEmu problem.
