### ISSUE TITLE
Couldn't communicate with helper process

### ISSUE THREAD

**Issue by warrenmcquinn** [OpenEmu/OpenEmu#3694]
Tried to run the helper process in isolation, here's the terminal output:

![image](https://user-images.githubusercontent.com/1995151/43879827-a1e7523a-9b5a-11e8-8df0-1d1762919de2.png)

Crash logs:

[OpenEMU Crash Log.zip](https://github.com/OpenEmu/OpenEmu/files/2272887/OpenEMU.Crash.Log.zip)

Just logging in case it helps anyone else. High Sierra 10.13 beta

**Comment by clobber** [comment]
Umm this doesn't seem like a valid issue to me. You cannot simply launch OpenEmuHelperApp by itself. This is helpful to no one.
