### ISSUE TITLE
SNES Missing from Mac Version

### ISSUE THREAD

**Issue by Crashxx** [OpenEmu/OpenEmu#3695]
Hey guys, I just recently downloaded this and I can't seem to find the SNES system anywhere on the app, I've gone through everything trying to add it, here's some screen shots to show I can't check off SNES system or download it anywhere...
 <img src="https://i.imgur.com/lSlQRxT.png">
 <img src="https://i.imgur.com/Ipwdg4l.png">
 <img src="https://i.imgur.com/Kxl8DoZ.png">

**Comment by clobber** [comment]
It's not missing. You have your language set to "Japanese" so the system is called "Super Famicom" as you can see in your screenshots.
