### ISSUE TITLE
Games not adding

### ISSUE THREAD

**Issue by MonkeyPuyo** [OpenEmu/OpenEmu#3696]
I want to have Puyo Puyo n and Puyo Puyo Box (both on PS1) in my collection but they are not adding into my collection. I got all the BIOS roms and they both have bin and cue files. Plus I tried to add them by dragging and dropping and adding them into the PS1 rom folders but neither work...

**Comment by clobber** [comment]
Not an OpenEmu problem. If games don't import, you have something wrong or your files are bad.

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games
