### ISSUE TITLE
Unable to download cores

### ISSUE THREAD

**Issue by dylan1580** [OpenEmu/OpenEmu#3697]
When I load a game, it tells me to download the appropriate core, opens a download tab but never loads. I tried downloading from the preferences tab but couldn't click anything. Help would be very appreciated!

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#2449
