### ISSUE TITLE
OpenEmu 1.0.4 could not find a Core to launch the game

### ISSUE THREAD

**Issue by olesolo** [OpenEmu/OpenEmu#3700]
I'm trying to run OpenEmu 1.0.4 on OS 10.7.5 (iMac 2006 1.83/2Gb RAM/64VRAM). And cant download any cores :( Could you give me a hint how to fix it? Thanks

**Comment by olesolo** [comment]
Any chance to get old cores for 1.0.4 and a quick ref where to place them? thanks

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
