### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by GoldenPvE** [OpenEmu/OpenEmu#3703]
Hello i need help when i launch my game it start off a black screen i waiting for it to load for 30min and nothing happened Still the black Screen I use Mac osx el captian

**Comment by GoldenPvE** [comment]
it Version 2.0.6.1 and mac os El captian Console: psp

**Comment by GoldenPvE** [comment]
After I open naruto ninja hero 3 it start up the company name and then it black out forever I need help

**Comment by clobber** [comment]
Thank you for adding basic troubleshooting information that should have been in your original post.

Not our bug. https://github.com/hrydgard/ppsspp/issues/9591
