### ISSUE TITLE
Chrono Cross - m3u file not loading

### ISSUE THREAD

**Issue by firath** [OpenEmu/OpenEmu#3706]
Hello. I'm sorry, i re-opened a previous issue, but i saw afterwards that it was closed so... i thought  i should open a new one.

I'm trying to figure this thing out, but i stil can't make my Chrono Cross game works with Open Emu, even after following thoroughly the guide.
Here a screen :

<img width="959" alt="capture d ecran 2018-08-24 a 02 27 43" src="https://user-images.githubusercontent.com/42660548/44558773-54611d00-a746-11e8-96be-83477f37117c.png">

When i drop the M3U file on Open Emu, nothing happened... OpenEmu tried to load it and then nothing. I did saved the file as a Plain Text, names are matching so..... can't figure it out :( can you help me please?

Btw :
OpenEmu : v2.0.6.1
iOS : macOS High Sierra, version 10.13.6

Thank you...

**Comment by clobber** [comment]
Post the contents of the cue sheets, post the output from Console when you try to import the m3u, make sure the cue sheets don’t already exist as imported in your library...

**Comment by firath** [comment]
Oh thank you very much Clobber !! I thought that deleting the files on OpenEmu was enough to delete them from the library.. but actually it's not ! By looking outputs from Console i find out the reason : m3u file already existed because i tried to import it multiple time.. so i had to go directly on the folder Sony Playstation (Open Emu) and delete them myself. Now it works.. thank you gain :D

**Comment by clobber** [comment]
It is enough to delete them as of 2.0.6. Your guess is as good as mine as to why it would be in the folder. Maybe you manually copied it?

**Comment by clobber** [comment]
If you can produce steps to replicate this I’ll check it out. Otherwise I don’t think this can happen.

**Comment by firath** [comment]
I didn't :/ first time i go into this folder!

**Comment by firath** [comment]
I think the m3u need to be deleted manually when the import doesn't work. 
My guess is : first time i uploaded the m3u files, the content must had been incorrect, so OpenEmu couldn't load anything from it BUT it saved it anyway on the folder.

**Comment by firath** [comment]
After those first attempt, i started again from scratch to recreate a m3u, and this time i guess i didn't make mistake. But the previous m3u were still on the folder, so it didn't work

**Comment by clobber** [comment]
Then as I said, you’ll have to come up steps to replicate that behavior. With the import and game removal code, I don’t think this is possible. An m3u won’t get imported if there are no proper files associated with it. The importer doesn’t know where to send it, so it can’t go anywhere. Not worth speculating.
