### ISSUE TITLE
AirPods don't work

### ISSUE THREAD

**Issue by ferreirarq** [OpenEmu/OpenEmu#3707]
I don't know if it's a sound controller issue but AirPods don't work with any game. I need to disconnect them or use ordinary headphones with cable in order to play with sound.

If any other thing is playing ie a Podcast or music and I attempt to play a game, AirPods enter "telephone" call mode. Other sounds play. But games don't.

Hope this helps. Thanks!

**Comment by clobber** [comment]
Try this https://github.com/OpenEmu/OpenEmu/issues/2979#issuecomment-269884878

**Comment by ferreirarq** [comment]
Thanks! the terminal code didn't work. But _**selecting internal microphone as the source for sound input on my settings**_ did the trick.

Works like a charm now.

**Comment by clobber** [comment]
Weird, okay. Not sure what Sound Input would have to do with it.

**Comment by ferreirarq** [comment]
Don't know either but there was a link on the thread you just sent me with that solution

**Comment by tatundria** [comment]
Can this issue be fixed on OpenEmu? So we don't have to change the source of sound input from settings everytime we need to launch OpenEmu?
