### ISSUE TITLE
ROMs won't work on other emulators after being used in OpenEmu

### ISSUE THREAD

**Issue by ejj28** [OpenEmu/OpenEmu#3710]
ROMs gotten from OpenEmu's ROMs folder can't be loaded by other emulators, for example RetroArch on Android

**Comment by clobber** [comment]
You are likely trying some compressed ROMs that were affected by a bug in an older OpenEmu release where they would import decompressed but with the original compressed file extension. To avoid the bug moving forward, be using our [latest release](https://github.com/OpenEmu/OpenEmu/releases/latest).
