### ISSUE TITLE
PPSSPP Stuttering Audio

### ISSUE THREAD

**Issue by JanHeart01** [OpenEmu/OpenEmu#3713]
Hello! I was hoping to explain an issue that the PSP core contains involving audio issues. I started playing Crisis Core: Final Fantasy VII, and there are times when the audio stutters (usually for split seconds), but the rare cases include very distorted audio for a few seconds. Neither of them occur every minute, but they still happen. The filters have nothing to do with it, so that can't be it. My guess it's the core. Any chance that it will be fixed soon?

**Comment by clobber** [comment]
Have to use the search. This has been covered before: https://github.com/OpenEmu/OpenEmu/issues/1036#issuecomment-328298956

>Any chance that it will be fixed soon?

In the next update. There is an improvement to the core plugin that is tied to the next OpenEmu release that will fix it.
