### ISSUE TITLE
Updated openemu.org with modern code

### ISSUE THREAD

**Issue by craigerskine** [OpenEmu/OpenEmu#3714]
Hey, I created the original frontend markup for the openemu.org site way back in 2013. It's pretty old, so I recently updated it with function CSS and vue.js... now it's a little easier to edit and is fully responsive.

Here's the result: https://craigerskine.com/oe/

I have the source set up as a node/gulp build process. Let me know who to send the source to.

**Comment by clobber** [comment]
Ah, very nice! Thanks a lot for doing this. We have the website hosted in its own repo if you want to do a pull request that way: https://github.com/OpenEmu/openemu.github.io

Otherwise, if you prefer to just zip up the source and drop it here then go for it.

**Comment by craigerskine** [comment]
Ahhh... I completely missed that repo when searching. I'll do a proper pull request. Thanks so much @clobber.
