### ISSUE TITLE
WWF No Mercy Crashes

### ISSUE THREAD

**Issue by jonas303** [OpenEmu/OpenEmu#3715]
I'm not sure what exactly the issue is, but I know every time I go to quit a match in the WWF No Mercy rom, it crashes

**Comment by clobber** [comment]
Mupen64Plus and GPU plugin bug. This may improve in a future version of Mupen64Plus and GLideN64. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
