### ISSUE TITLE
PS1 DancePad

### ISSUE THREAD

**Issue by javihs97** [OpenEmu/OpenEmu#3716]
I've just downloaded DDR for PS1, and by playing (using the PS3 original dance pad) I noticed it doesn't recognize when pressing the two opposite arrows. I guess it's because they're opposite, so it wouldn't be necessary in other games. 

Is there a way I could fix this?

**Comment by clobber** [comment]
>Is there a way I could fix this?

No. The core plugin would need to have "dancepad" enabled and configured for the input. This is not something that can happen now but perhaps in the future with some sort of per-core configuration/options #1281.

In the near future, it is planned to add lightgun/mouse support for required PS1 games #3347.
