### ISSUE TITLE
N64 Rayman Issue

### ISSUE THREAD

**Issue by ecbrodie** [OpenEmu/OpenEmu#3717]
I am basically cross-posting this issue from Project 64 here, because I run into the same exact thing 100% of the time when playing Rayman 2 N64 on OpenEmu: https://github.com/project64/project64/issues/827

Is there any way that I can configure OpenEmu to work around this issue, so that I am no longer hard-stuck on the "Cave Of Bad Dreams" level?

**Comment by clobber** [comment]
Mupen64Plus and GPU plugin bug. This may improve in a future version of Mupen64Plus and GLideN64. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
