### ISSUE TITLE
Keyboard not being registered

### ISSUE THREAD

**Issue by LumpyKoala** [OpenEmu/OpenEmu#3718]
Any game I try to play doesn't register me pushing in the keyboard keys, therefore not being able to even start the game, but it does register my mouse and that's it.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
