### ISSUE TITLE
Background art for all games/systems will not download

### ISSUE THREAD

**Issue by Kbussler** [OpenEmu/OpenEmu#3719]
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2.3 GHz Intel Core i5
8 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 640 1536 MB
OS 10.13.4

OP Version 2.0.6.1

I have recently installed OP and started adding rom collections to it but none of the box art for any system or any game I have tried is giving me box art. I have tried right clicking and selecting download box art, I have the box checked for automatic download, I have checked application support to see if the openvgdb file is in there, I have restarted my computer multiple times I have also tried multiple rom sets from different downloaders and all are no-intro/.sfc sets. I originally installed experimental OP but have since reinstalled regular although I did not do a complete uninstall simply threw it away and reinstalled. however I also saw the tread about experimental not being a different build and that it would not affect this issue. My only conclusion is that it must have some kind of connection issue with openvgbd or something like that. Games play fine. I've also noticed that it takes quite a while when I drop a new game into OP for it to load and be added to the library. Maybe this is OP trying to connect to openvgdb and failing to establish a connection? really not sure what to do at this point? Is there a way to check on my connection or ability to access openvgdb?

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/3556#issuecomment-371863717

**Comment by clobber** [comment]
>Is there a way to check on my connection 

If you cannot access gamefaqs, you will not be able to download cover art.
