### ISSUE TITLE
OP support

### ISSUE THREAD

**Issue by Kbussler** [OpenEmu/OpenEmu#3720]
Ok now you locked the discussion about a problem that others have had and not resolved. there is an issue and I have seen other threads where it is not simply a bad rom set or a mame not supported issue. this is something that could help others and you seem to want to burry it. I have followed the guide and the support to the letter and there is something wrong. I have asked for help and not gotten it. 

As another troubleshooting attempt I have unchecked the box for automatic art download and the game loads instantly which is much faster than with it checked. this leads me to believe that it is an issue when trying to retrieve the metadata.

As one more thought, I am sure my romset is good as they are all no-intro and from different sources but is there anything I can do to confirm my set is compatible  with OP metadata retrieval process? I also tried unzipping the files and adding them in .sfc format for SNES and .nes format for NES

**Comment by clobber** [comment]
Please stop opening issues here because this is not an OpenEmu problem. Furthermore, "OP" is not an abbreviation for OpenEmu.
