### ISSUE TITLE
Download issue from GitHub Desktop

### ISSUE THREAD

**Issue by juppaluri** [OpenEmu/OpenEmu#3721]
While using version 1.34 of GitHub desktop to try to clone the repository, the cloning does not work.  I am on macOS High Sierra 10.13.6.  The message given is

"Error: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository."

In addition, when looking at the files that did download, I found out that there were no files in any of the folders for the cores, while there were files for openemu itself.  Therefore, Openemu could not be compiled.

I will attach screenshots if necessary.

**Comment by clobber** [comment]
Checking out the source code from GitHub is not an OpenEmu issue. You can learn more in our [compiling guide](https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide).

**Comment by juppaluri** [comment]
Sorry for the mistake
