### ISSUE TITLE
Crashing - PPSSPP Core, Persona 3 Portable

### ISSUE THREAD

**Issue by LastChalice** [OpenEmu/OpenEmu#3722]
Hello OpenEmu developers. 
I've been having a small problem with Persona 3 Portable. 
While the game usually runs fine, trying to "Check Requests/Compendium" in the [Velvet Room](http://megamitensei.wikia.com/wiki/Velvet_Room) often leads to the system freezing up, followed with the message that Openemu couldn't "communicate with the helper application". 
This only started happening near the endgame (Roughly 1/13, for those who know Persona), and already happened at least twice; saving the game temporarily stops this, but this is getting frustrating. 

Thanks in advance to whoever helps me solve this problem!
Best, 
Last Chalice

P.S. -- Sorry I couldn't find the log files; when I typed OpenEmu into the console, nothing popped up. 
Here's the information I have on hand. 
1. Macbook Air, 13 in. 2017, High Sierra
2. Openemu 2.0.6.1
3. Female Route
4. I lost count of all my save states a long time ago; would this be one cause of the issues?
I would delete the save states to clean my computer, but I can't find the "save state library".
5. Update: This happened again, but instead in the weapons store of the game. The game froze, I tried to save-state the game, and the "can't communicate with the helper application" error message popped up again

**Comment by clobber** [comment]
Doesn't appear to be our bug, but a PPSSPP compatibility bug. Can't do anything about this. Emulation compatibility improves slowly over time.

If it now always crashes on launch, try the following to get it to load:

* In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" when prompted to "Continue where you left off"

Beyond this, nothing else we can do here.
