### ISSUE TITLE
Compiling Cores Issue

### ISSUE THREAD

**Issue by juppaluri** [OpenEmu/OpenEmu#3724]
I am trying to compile the Mednafen Core individually.  I have downloaded and compiled the OpenEmu SDK, but whenever I try to compile the Core, it always tells me that I am missing a file in the OpenEmuBase framework (but I have compiled that).  To be more specific, here is the error message.

"Lexical or Preprocessor Issue: OpenEmuBase/OEGameCore.h file is not found"

I am on MacOS High Sierra, and using the latest version of Xcode.  I assume that my mistake is really stupid, so any help would be appreciated.  I can provide screenshots if necessary.

Thank you so much

**Comment by clobber** [comment]
I've stated before that issues compiling are not OpenEmu problems. You can either follow the [compiling guide](https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide) correctly or use the pre-compiled core plugin that is already provided. There is no reason to be compiling Mednafen yourself.
