### ISSUE TITLE
Filters not loading

### ISSUE THREAD

**Issue by sohojohn84** [OpenEmu/OpenEmu#3725]
Hello, 

I have downloaded a bunch of filters (.cg and .cgp). I dragged them all into Openemu and restarted the program. They all appear in my filter list after I restart Openemu, however, when I select them, either nothing happens (the filter doesn't apply) or the screen turns black.

Anyone can assist? Thanks much!

**Comment by clobber** [comment]
Most of those other multi-pass shaders rely on unimplemented features that we don't support, as the spec was ever-changing. Cg is deprecated and will be removed in a future release, replaced with GLSL and possibly Metal. Sorry, can't help you beyond that.
