### ISSUE TITLE
Denies the usage of Python script

### ISSUE THREAD

**Issue by Mkone32** [OpenEmu/OpenEmu#3726]
This sounds stupid, but I am using SerpentAI and it has a script that opens the application and leaves it running but all I get in return is a Permission denied error. 

I just want to know which file to modify so OpenEmu accepts this script as a valid player. 

(I am sorry if this sounds rude, but I don't know how else to put it)

**Comment by clobber** [comment]
This isn't an OpenEmu problem. It doesn't make sense that an application can deny opening it, that is something on your end at the operating system level. Sorry, can't help you beyond that.
