### ISSUE TITLE
Using the Wiimote as a Zapper for the NES

### ISSUE THREAD

**Issue by sohojohn84** [OpenEmu/OpenEmu#3730]
Hello,

not sure if this is wishful thinking...

Was wondering if there is a way to use a Wiimote as a zapper to play games like Gumshoe or the infamous Duck Hunt on the NES.

Anyone had success in pairing a wiimote to play zapper games? Thanks guys!

Jon

**Comment by clobber** [comment]
Can't just point a Wii remote at a screen and expect it to work. There is no support for that and there won't be. Those games can be played with the mouse where the mouse cursor acts as the zapper. It's already hooked up.
