### ISSUE TITLE
Eject One Memory Card?

### ISSUE THREAD

**Issue by ChristopherForrest** [OpenEmu/OpenEmu#3731]
Currently trying to play Codename: Tenka however when it starts it requires me to eject one of the memory cards.

So when a game is newly launched it creates two .mcr files and I have tried deleting one after launch to see if it will eject however it doesn't. Also tried to relaunch openEmu but another .mcr get created..

Not sure what to do.

**Comment by clobber** [comment]
There is no way to do this in OpenEmu. I would need to add some logic to our Mednafen core plugin to automatically do this - since to my knowledge Tenka is the only PS1 game having this requirement - but I want to be sure I have a complete list first.

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/Mednafen-Core/commit/b86f56c8d35be032a6fa1da5cf2e38fce2051e4a

When I've pushed out an updated core plugin with the fix I'll reply back here. No ETA

**Comment by clobber** [comment]
This update is available now.

Restart the app and an updated Mednafen core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for Mednafen 1.21.3.1
