### ISSUE TITLE
Unable to choose new Game Library Folder location

### ISSUE THREAD

**Issue by ryanjhaffner** [OpenEmu/OpenEmu#3733]
After downloading OpenEmu, it began saving added roms and application data in my downloads folder, so every time I clear that folder I have to avoid all my saved roms and files like "Library.storedata-shm". When I attempt to change it, OpenEmu says I don't have permission to access the folder I try to change it to. When I try to reset it, OpenEmu says I don't have permission to access OpenEmu. I have systematically gone through and allowed all folders to be accessed via Permissions, but was unable to resolve the issue. I have tried reinstalling twice, restarting the machine several times, and the app continues to choose downloads as the place to store data.

**Comment by clobber** [comment]
That is not the default folder location so you changed that yourself after install. You either changed the location or you unchecked the "Copy files to Game Library folder when adding to library" option in OpenEmu > Preferences > Library.
