### ISSUE TITLE
Nothing but save/load state works on playstation

### ISSUE THREAD

**Issue by luckyjazzt** [OpenEmu/OpenEmu#3735]
This happened while playing NCAA 01, and seems to be an issue in all football games for playstation. I've had this happen in NCAA 01, Madden 04, and Madden 05. I have not had any issues with these games on other systems, such as Madden 12 on psp. At some point during gameplay, I completely lose control of the entire system. Save/Load state still work, but nothing within the console itself works. It detects my controller, it lets me pair it and configure it just fine, but nothing works. And its completely random too, it happened in the middle of third quarter one game, during kickoff the other, during the coin toss in another, ect ect. Restarting the game seems to be the only thing that works, but I've always used saved states, so I'd lose all my progress doing this.

**Comment by clobber** [comment]
Without much more information, it sounds like two possibilities outside our control:

* Bad dump of the games(s).
* Emulator bug with Mednafen. Note: Sports games are known to be horribly programmed so there could be an edge case with some particular behavior.

I'd first verify you have a "good" dump of the game as cataloged by [redump](http://redump.org/) and if not, track one down.
