### ISSUE TITLE
Black Screen After Starting PSX Game in OpenEmu

### ISSUE THREAD

**Issue by aalhasani** [OpenEmu/OpenEmu#3737]
Guys,

Trying to play Tomb Raider 1 and 2 on Openemu on my MacBook pro. After unecmed the file and created the corresponding cue, I was able to launch the game. However, after selecting the start option, black screen popped up for both Tomb Raider. I do have all the Bios and OpenEmu is v.2.0.6.1

bty, i've played PSX games such Mega Man X4,5,6 before and they worked fine.

Suggestions?

This is an uploaded youtube video on my channel. 

https://www.youtube.com/watch?v=3Nnj59uBu5A&feature=youtu.be

**Comment by clobber** [comment]
I am not aware of any compatibility issues with Mednafen and certain Tomb Raider games. It sounds to me that you have a bad dump of the game and will just need to find other copies.
