### ISSUE TITLE
WOAH WOAH WOAH!!!

### ISSUE THREAD

**Issue by glitchyGhost** [OpenEmu/OpenEmu#3739]
Hey Guys, not sure what happened to this awesome software since last update or 2?
My system used to run so smoothly (last years build) - I could drop in my library on a fresh OS install and bam! it would all still be working and showing up. Now, I am greeted with a partial missing library, odd screen/artwork glitching whilst scrolling, games that used to import almost instantly without any hassle, are now all getting stuck or taking forever. Some games are now considered 'not available' even in my library - they have always worked just great.  I noticed the ~/Library location is now not valid as a location? and I have been forced to delete my entire library and start over since when I try to import it app gets jammed then says 37 errors need 'fixing' - various parts of some roms, bios' its also not happy with. Trying to reinstall library now but just so painfully slow.   Blimey.  Why even mess with such a beautifully created application? 
Cheers

**Comment by clobber** [comment]
Not sure if you opened this to gripe or what but we don't have these problems. Come back when you have an actual problem that you can replicate with full details.
