### ISSUE TITLE
Core/Console Specific Options?

### ISSUE THREAD

**Issue by Xx-Henry-xX** [OpenEmu/OpenEmu#3740]
Will there ever be a core/console specific options like expansion cart in Saturn (Mednafen supports this: https://mednafen.github.io/documentation/ss.html) or multiplayer in GBA?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Advanced core prefs/options. #1281
