### ISSUE TITLE
32X Games Looking Wrong

### ISSUE THREAD

**Issue by Davy6502** [OpenEmu/OpenEmu#3742]
It could just be me, but since the 2.0.7 update, I noticed that Sega 32X games look a bit squished in more than previous versions. I checked everything else (NES, and even Genesis) and they all look normal. Here's unaltered screenshots of the previous (2.0.6) and most current (2.0.7) versions of OpenEmu from MacOS Sierra 10.12.6, with the Sega logo from Knuckle's Chaotix to showcase the issue:

Version 2.0.6
![screen shot 2018-09-19 at 8 40 46 pm](https://user-images.githubusercontent.com/39528949/45790854-859d1200-bc4c-11e8-84bd-cdd28aa26a8b.png)

Version 2.0.7 (current)
![screen shot 2018-09-19 at 8 41 03 pm](https://user-images.githubusercontent.com/39528949/45790857-8f267a00-bc4c-11e8-96ac-91ebf6bd0998.png)

**Comment by geegeeman77** [comment]
This is happening to N64 games as well in version 2.0.7., such as Super Mario 64. It's squished from the sides. This did not occur in version 2.0.6.

**Comment by clobber** [comment]
https://github.com/OpenEmu/picodrive/commit/9e630e35b2a548dc855ab9d377a1152e6c564253

This is fixed now.

Restart the app and an updated Picodive core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for Picodrive 1.92.0.1
