### ISSUE TITLE
NES Keys can not be fired (rapid fire).

### ISSUE THREAD

**Issue by Scenx** [OpenEmu/OpenEmu#3746]
Hello, I don't think you understand what I mean. What I want to say is that there is no function, not how to set it. Please add this function. Many games on NES platform are very tired of fingers.

 Please make it like a handle with four buttons. The two buttons below provide a single launch, and the two buttons above push Key provides continuous transmission.

**Comment by clobber** [comment]
I don't think you know what I mean. This function is not available and would only be available through the "rapid fire" feature if we added it. Please do not open another issue for this.
