### ISSUE TITLE
n64 aspect ratio

### ISSUE THREAD

**Issue by PlutoX86** [OpenEmu/OpenEmu#3747]
Hey there! Nice work with the new release! :) (really)

High Sierra 10.13.6
OE 2.0.7 Exp.
Latest Mupen64 Core

https://imgur.com/a/VC6Lvtf

**Comment by clobber** [comment]
Hit scale 1x.

<img width="681" alt="screen shot 2018-09-20 at 1 03 54 am" src="https://user-images.githubusercontent.com/1303132/45798893-2e5d6880-bc71-11e8-933c-2f445bc476b9.png">

There is nothing wrong there.

**Comment by PlutoX86** [comment]
Well, you're right. The NTSC version looks is fine. I guess it's a PAL _problem_ then.

**Comment by clobber** [comment]
Hrm yes, that is a problem for PAL. I'll push a core plugin update later.

**Comment by clobber** [comment]
The Mupen64Plus core plugin 2.5.6 update brings it back to what it originally was: 5 pixels less wide. Barely noticeable, but I assume that is what you wanted.
