### ISSUE TITLE
playstaiton hacks won't load into library

### ISSUE THREAD

**Issue by pleasejust** [OpenEmu/OpenEmu#3748]
I drag and drop the vanilla symphony of the night cue file into the library window and it loads perfectly and auto loads the cover, everything's fine. I drag and cue of the hack, which worked in the previous version, and nothing happens. The cue file has the proper name of the bin file in FILE "..." BINARY. How did it work before but not now? I'm so sick of this crap... every version problem after problem.... I even copy the file into the folder where the playstation roms are stored. Doesn't show in library after a restart. Nothing. Really?

**Comment by clobber** [comment]
>I'm so sick of this crap... every version problem after problem....

Sorry, not interesting in helping you. Who knows what you've done wrong on your end.
