### ISSUE TITLE
Wii Classic Controller Triggers Don't Work

### ISSUE THREAD

**Issue by JayLeGee** [OpenEmu/OpenEmu#3751]
I've successfully hooked up and configured my Wiimote classic controller to OpenEmu, and most of the buttons work properly, except for the left and right triggers. Despite OpenEmu saying the triggers are mapped correctly (see image), when I attempt to use them in game, they don't do anything. I think what is actually happening is that the emulator is registering both the triggers as constantly pressed, because if I emulate closing the lid of the DS and then "reopen" it, I get the result of one press of the trigger immediately (specifically, I'm in Mario Kart DS, and upon "reopening" the DS, I hop once). I know for a fact it isn't a problem with my classic controller, as when it's hooked up to either my real Wii or the Dolphin emulator, it works fine, so I think it has to be an issue with OpenEmu or perhaps I can fix it somehow. Also worth noting is that in addition to testing this with the DS emulator, I also tried with the SNES emulator, and had about the same results. 
![screen shot 2018-09-21 at 11 10 19 pm](https://user-images.githubusercontent.com/43489323/45913649-9c319d80-bdf3-11e8-8e66-e0c4a1022b7a.png)

**Comment by clobber** [comment]
Classic Controller attachment is not properly supported. There is no fix for this as of now.
Similar enough to #2371
