### ISSUE TITLE
Cover Art Importing is Incomplete

### ISSUE THREAD

**Issue by diocpereira** [OpenEmu/OpenEmu#3752]
Hi everyone. I'm trying to import cover art for all my SNES games but some don't allow me to. It's strange since a lot of the unavailable cover art is for extremely popular games like Zelda and Super Mario World. Can someone look into this? Of course I can manually add the cover art myself, but it would be better if this process would be automated, perhaps by choosing a better (more complete) videogame database, like Moby Games (by the way, which one are you using?).

My apologies for taking up your time and keep up the good work.

<img width="1276" alt="openemu cover art" src="https://user-images.githubusercontent.com/20748524/45914210-98286e80-be39-11e8-8620-03710032c632.png">

**Comment by clobber** [comment]
With SNES games, it is likely you are importing ROMs with 512-byte copier headers. You need to import ones that do not contain them, usually their file extension is .sfc.

**Comment by diocpereira** [comment]
As opposed to .smc right?

**Comment by clobber** [comment]
Correct.

https://github.com/OpenEmu/OpenEmu/issues/1146#issuecomment-74404878

**Comment by diocpereira** [comment]
I just checked all of my ROMS (by using the Show in Finder command) and they're all .smc. It must be something other than the extension.

**Comment by clobber** [comment]
I think you misunderstood. .smc is usually a dead giveaway for containing the 512-byte copier header. You can check the comment I linked to for more information to perhaps figure out how to clean up your set.

**Comment by diocpereira** [comment]
Is it safe to use this? http://smc2sfc.herokuapp.com

**Comment by diocpereira** [comment]
Hey, I finally solved the problem thanks to a mix of downloading new ROMS + using the converter mentioned above to convert .smc to .sfc. It worked. I have artwork for all my ROMS. Thanks for the help and have a very nice day.
