### ISSUE TITLE
PS1 game freeze with DualShock Controller / Couldn’t communicate with a helper application

### ISSUE THREAD

**Issue by Matsuo3rd** [OpenEmu/OpenEmu#3754]
PS1 game freeze experienced on multiple PS1 games (Micro Machine 3 & Diablo). This is happening when clicking on genuine DualShock buttons gamepad connected through USB Gaming Controller ($3 blue box) onto Mac.

Controller works perfectly fine with Sega Genesis and MAME.

See OpenEmuHelperApp_2018-09-23-220405_macmini.crash extract:
Assertion failed: ((prevState.direction != OEHIDEventAxisDirectionNull) && "-axisMoved: invoked but axis didn't move"), function -[OESystemResponder axisMoved:], file /Users/clobber/Code/OpenEmu/OpenEmu-SDK/OpenEmuSystem/OESystemResponder.mm, line 550.

Tried multiple times to close OpenEmu / reboot Mac.
No success.

- OpenEmu Version: 2.0.7 experimental
- macOS Version: 10.13.6

[OpenEmuHelperApp_2018-09-23-220405_macmini.crash.txt](https://github.com/OpenEmu/OpenEmu/files/2409103/OpenEmuHelperApp_2018-09-23-220405_macmini.crash.txt)

**Comment by clobber** [comment]
Rebooting won’t save you. There is an assertion right there in the crash log that explains why. Your gamepad/adaptor is doing something unexpected. For now, it’s not going to work.

**Comment by clobber** [comment]
Also, you need to Force Quit “OpenEmuHelperApp” process via [Activity Monitor](https://support.apple.com/en-us/HT201464).

**Comment by shysaur** [comment]
We need a little more data to solve the problem you're experiencing. Please do the following steps:

1) Download a patched version of OpenEmu from the following link: https://transfer.sh/10ILEL/OpenEmu-2.0.7-nonullstickassert.zip

2) Open Terminal.app and copy-paste the following command, then press return:
``defaults write org.openemu.OpenEmu logsHIDEvents -bool true``

3) Open Console.app, and filter by OpenEmu

4) Unzip and open the patched version of OpenEmu downloaded earlier, then perform the same actions that caused the crash (this time OpenEmu should not crash) and close OpenEmu.

5) Copy-paste the filtered contents of the Console window to a text file and attach it to this issue.

6) Copy-paste the following command in Terminal.app and press return: 
``defaults delete org.openemu.OpenEmu logsHIDEvents``

**Comment by shysaur** [comment]
It seems from the data that we can fix this problem in the next release. Could you please download OpenEmu from this link (https://transfer.sh/hO2YI/OpenEmu-2.0.7-nonullstickassert2.zip) and check if it fixes your controller in-game?

**Comment by Matsuo3rd** [comment]
Hello.
Sorry for my late reply. I wanted to thoroughly test the patch over a week.
I confirm my issue was gone with the patched version @shysaur provided (OpenEmu-2.0.7-nonullstickassert2.zip).
Thanks again for your support guys.

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu-SDK/commit/d8cecdc367bd1e8093e0322fc11fcf0aa0323806

Thanks for confirming.
