### ISSUE TITLE
ask to remove saved files when deleting games from the library.. 

### ISSUE THREAD

**Issue by mortdeus** [OpenEmu/OpenEmu#3755]
Summary of issue

Deleting a game from the openemu library that has saved data, automatically removes saved data from "../openemu" and moves it to the trash bin without first notifying the user this will happen or asking if this is even desired behavior.  

# Steps to reproduce

1. Play a game and save either in game or using the built-in saved state feature and then delete the game from the library. 
2. Delete said game from the openemu library
3. After deleting the game, openemu will remove the game's saved data from "~/Library/Application Support/OpenEmu/Save States" folder and put it in the user's Trash bin. 

# Expected Behavior

1. When deleting a game from the library, I would like to be asked if I would also like my saved data to be removed as well. 

# Observed Behavior

The reason why I suggest this behavior is because I have been playing ff7 on playstation recently, and for some bizarre reason when I tried to load the game, I received a "emulator couldn't play rom" error. So suspecting data corruption or some other openemu specific error related to me having moved the directory containing the rom files from ~/Downloads/ to ~/Games/PSX/, I went ahead and tried to delete the game from the library so I could reload the .cue/.m3u from the new location and see if that fixed the issue. (which it didn't at first because I initially couldn't get the deleted game to rescan into the library, which i fixed and will address in another issue ticket).

After I got the game to reinstall, I tried to play it and realized that all my saved information was missing. Which fortunately, I was able to find in my Trash bin and was able to restore it back to it's location "../openemu/". However, considering that a trash bin can be configured to automatically empty itself at a future date, this could have resulted in a very unfortunate loss of valuable data; completely unbeknownst to the user. 

# Debugging Information

- OpenEmu Version: v2.0.7 (968-gf66035e-Release)
- macOS Version: High Sierra (10.13.6 (17G65))

**Comment by clobber** [comment]
Keeping the behavior we have now for several reasons, but the most important being that you should rely on in-game mem card saves instead of save states because save states can break compatibility at any time. Battery/mem card saves (those created in-game) will remain even after a game is removed.
