### ISSUE TITLE
Lost all saved data after openemu update

### ISSUE THREAD

**Issue by bbriessinck** [OpenEmu/OpenEmu#3756]
I updated OpenEmu and after the update I lost all saved data and the games start again from the very beginning. Are the save files somewhere to be found or is there no way to retrieve those?
<img width="482" alt="screen shot 2018-09-27 at 12 57 21" src="https://user-images.githubusercontent.com/43640190/46141677-e6cc7300-c254-11e8-830a-6df4c9ad8687.png">

**Comment by clobber** [comment]
If you were previously using a version of OpenEmu older than 2.0.6 then that could have happened. You can read why here: https://github.com/OpenEmu/OpenEmu/issues/3436
