### ISSUE TITLE
N64 game suddenly broken

### ISSUE THREAD

**Issue by mdjobst** [OpenEmu/OpenEmu#3757]
N64 game (Majora's Mask) has been running without a hitch on OSX High Sierra, but just tried to pull up an in-game save (using one of the owl statues) for the first time. All onscreen features (ie. the character and surroundings) are now gone, just the atmosphere and map is left onscreen. The revolving 'N' before 'Nintendo64' on the load screen is also missing. OpenEmu load states briefly show the full game before breaking. Can't seem to get the game to return to normal! 

Can I fix it/get the game and progress back?

- OpenEmu Version: 2.0.7
- OSX Version: 10.13.6

**Comment by clobber** [comment]
Yes, GLideN64 GPU plugin regression. It's under active development so changes are volatile and things can and will break. Nothing can be done about this until gonetz fixes this. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)

**Comment by clobber** [comment]
https://github.com/OpenEmu/Mupen64Plus-Core/commit/239ed5f1c470ea48e782a9ebf9709a7fa8c577ee

This is fixed now.

Restart the app and an updated Mupen64Plus core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for Mupen64Plus 2.5.7
