### ISSUE TITLE
Genesis: can't laught any game

### ISSUE THREAD

**Issue by jbdemonte** [OpenEmu/OpenEmu#3759]
Since the latest update (?), the genesis games no longer work
All others emulators works as well

# Steps to reproduce

I just try to run the game whose previously worked

# Observed Behavior

The screen stay black

# Debugging Information

- OpenEmu Version: 2.0.7     968-gf66035e-Release
- macOS Version: macOS Mojave version 10.14

Here are some log from the console
```
par défaut	01:58:01.160026 +0200	OpenEmu	Adding presenter E38E1A95-3440-495F-8E1B-139188CFB1FB for URL: <private>
par défaut	01:58:01.198431 +0200	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : OpenEmuHelperApp
par défaut	01:58:01.210331 +0200	OpenEmuHelperApp	Current system appearance, (HLTB: 2), (SLS: 1)
erreur	01:58:01.214338 +0200	OpenEmuHelperApp	Unable to load Info.plist exceptions (eGPUOverrides)
par défaut	01:58:01.214536 +0200	OpenEmuHelperApp	Post-registration system appearance: (HLTB: 2)
erreur	01:58:01.232163 +0200	tccd	Failed to copy signing info for 4754, responsible for file:///Applications/OpenEmu.app/Contents/MacOS/OpenEmu: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
par défaut	01:58:01.235133 +0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier org.openemu.OpenEmu, type: 0: 0x7f8d665293f0 at /Applications/OpenEmu.app
par défaut	01:58:01.246881 +0200	OpenEmuHelperApp	parent application is: OpenEmu
par défaut	01:58:01.248667 +0200	OpenEmuHelperApp	IOHIDDeviceClass::start: elementCount=16 reportHandlerCount=4
par défaut	01:58:01.248695 +0200	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=0 *buffer=7fce9d040c30 *count=16 size=1536
par défaut	01:58:01.248722 +0200	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=1 *buffer=7fce9be39940 *count=4 size=384
par défaut	01:58:01.248981 +0200	OpenEmuHelperApp	IOHIDDeviceClass::start: elementCount=9 reportHandlerCount=4
par défaut	01:58:01.249025 +0200	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=0 *buffer=7fce9be3a3c0 *count=9 size=864
par défaut	01:58:01.249060 +0200	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=1 *buffer=7fce9be3a760 *count=4 size=384
par défaut	01:58:01.249365 +0200	OpenEmuHelperApp	IOHIDDeviceClass::start: elementCount=18 reportHandlerCount=5
par défaut	01:58:01.249388 +0200	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=0 *buffer=7fce9d03d430 *count=18 size=1728
par défaut	01:58:01.249414 +0200	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=1 *buffer=7fce9be3b400 *count=5 size=480
par défaut	01:58:01.251766 +0200	OpenEmuHelperApp	Device 0x7fce9be3a2d0 does not have a location ID
par défaut	01:58:01.251810 +0200	OpenEmuHelperApp	Device 0x7fce9be3a2d0 does not have a product name.
par défaut	01:58:01.251950 +0200	OpenEmuHelperApp	Found Device 0x7fce9be3a2d0: Touchbar (probably)
par défaut	01:58:01.255446 +0200	OpenEmuHelperApp	Found Device 0x7fce9be3b310: Apple Internal Keyboard / Trackpad
par défaut	01:58:01.257918 +0200	OpenEmuHelperApp	Found Device 0x7fce9be39850: Magic Keyboard
par défaut	01:58:01.297476 +0200	kernel	AGC:: [OpenEmuHelperApp pid:4802 mux-aware] starting, non-mux-aware app count 0 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:1f power-state 0 3D idle HDA idle system-state 1 power-level 20:20 connect-change 0
par défaut	01:58:01.314285 +0200	OpenEmu	SETUP DONE.
par défaut	01:58:01.314623 +0200	powerd	Process OpenEmu.4754 Created PreventUserIdleDisplaySleep "OpenEmu playing game" age:00:00:00  id:21474871860 [System: PrevIdle PrevDisp DeclUser IntPrevDisp kDisp]
par défaut	01:58:01.327142 +0200	OpenEmuHelperApp	Rate change 0.000000 -> 1.000000
par défaut	01:58:01.352614 +0200	OpenEmuHelperApp	  saved enable noise cancellation setting is the same as the default (=1)
par défaut	01:58:01.389024 +0200	OpenEmu	Display's nominal refresh rate is 60.00 Hz
par défaut	01:58:03.413187 +0200	OpenEmu	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 624, 513, <private>
par défaut	01:58:03.428908 +0200	powerd	Process OpenEmu.4754 Released PreventUserIdleDisplaySleep "OpenEmu playing game" age:00:00:02  id:21474871860 [System: PrevIdle DeclUser IntPrevDisp kDisp]
par défaut	01:58:03.430135 +0200	OpenEmuHelperApp	Rate change 1.000000 -> 0.000000
```

**Comment by clobber** [comment]
Nothing changed in the last update to affect anything like this. What happens when you go to the Homebrew tab and run the game "Chase"?

**Comment by jbdemonte** [comment]
This one works as well.
In fact, if I remember right, in the interval, I switch from the experimental to the stable version

I dig this morning, I had 4 roms Sega Master System. All of them no longer works.
I remove two of them and download it again, the new one works.

Attached one which no longer works, it seems not being dragable on OpenEmu while, I copy it from `/Users/jbd/Library/Application\ Support/OpenEmu/Game\ Library/roms/Sega\ Master\ System`

[Alex Kidd in Miracle World (USA, Europe) (v1.1).zip](https://github.com/OpenEmu/OpenEmu/files/2430440/Alex.Kidd.in.Miracle.World.USA.Europe.v1.1.zip)

Do you think possible the file to have been modified by OpenEmu any way?
I did not have any problem with other consoles.

**Comment by jbdemonte** [comment]
When I try to drop some sms roms frehsly download, OpenEmu logs: `Error Domain=OEImportFatalDomain Code=-1 "(null)"` and it fails to add it
Example:
[Action Fighter (USA, Europe) (v1.2).zip](https://github.com/OpenEmu/OpenEmu/files/2430446/Action.Fighter.USA.Europe.v1.2.zip)

**Comment by jbdemonte** [comment]
In fact, he put it in the Arcade section :/ and they do not works there

**Comment by clobber** [comment]
Yeah, then this is not an OpenEmu problem since you can load the Homebrew ROMs.

The two files you attached here are definitely corrupt in some way -- they have the header of a zip file but they do not decompress. These have not been modified by OpenEmu. You will just need to delete, redownload and reimport all the affected ROMs that do not load.

Note: In an older version, there was a bug with compressed ROMs where they would import decompressed but with their compressed filenames. This would break loading on many of the core plugins, but this does not appear to be the problem you are experiencing here. Either way, files must be redownloaded.

**Comment by jbdemonte** [comment]
The strange thing is, those two files come directly from the OpenEmu library,
They used to work
