### ISSUE TITLE
Opening a .ips rom

### ISSUE THREAD

**Issue by jeffreybox** [OpenEmu/OpenEmu#3761]
Summary of issue:

- I want to play this rom hack of ffvii for NES.  https://www.romhacking.net/hacks/1657/
- Unzipping the download gives an .ips file (which i'm unfamiliar with)
- How do I play this on OpenEmu? Do I need a patch?

- OpenEmu Version: 2.0.7
- macOS Version: 10.13.6

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/OpenEmu/issues/3081
