### ISSUE TITLE
Mac OS Mojave rename game white text issue when dark theme enabled

### ISSUE THREAD

**Issue by JBSK8NC** [OpenEmu/OpenEmu#3762]
Summary of issue

When dark mode is enabled and the user tries to change the title of a game. The text input box makes the text invisible.

# Steps to reproduce

Switch between light and dark modes and change the name of a game. While in dark mode the cursor and the text are invisible.

# Expected Behavior

I expect to see the text and cursor

# Observed Behavior

When renaming a game with dark mode enabled the text box appears and the user inputs are invisible. You can highlight the text to see what is in the input but not when typing.

# Debugging Information

- OpenEmu Version: 2.0.7
- macOS Version: 10.14

**Comment by clobber** [comment]
Uh, why did you close what appears to be a valid issue?
