### ISSUE TITLE
Difficulties importing multi-disc PS game

### ISSUE THREAD

**Issue by 00rish00** [OpenEmu/OpenEmu#3763]
Hi there,

(first post ever on GitHub so newb apologies in advance!)

I've been following this guide:
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games

but am having trouble importing Final Fantasy 9 for PS. I managed to do FF7 & FF8 successfully and I've followed the same process with no luck. I know I've configured the CUE files correctly because I can import individual discs into OpenEMU (just can't run as it indicates it's a multi-disc game), however the M3U file refuses to read. Any help please?

See the images/attachments. I've zipped my CUE files and M3U.
[FF9 cues & m3us.zip](https://github.com/OpenEmu/OpenEmu/files/2456279/FF9.cues.m3us.zip)
<img width="133" alt="screen shot 2018-10-08 at 10 09 52" src="https://user-images.githubusercontent.com/43961682/46613894-68889000-cae2-11e8-9980-a66b1ac0e9c3.png">

Any guidance is greatly appreciated. I'm sure I'm doing something stupid, but pretty sure I did it all in plain text. It is CCD type.

**Comment by clobber** [comment]
You made cue sheets that point to CCD's which doesn't make any sense. CCD's are CloneCD Control Files, which are like cue sheets for CloneCD rips -- what you have right here. You do not need to make cue sheets for CloneCD rips. Instead, your M3U playlist file needs to contain just the CCD filenames.

**Comment by 00rish00** [comment]
thank you
