### ISSUE TITLE
SNES: it worked fine, now stopped completely

### ISSUE THREAD

**Issue by ingejanse** [OpenEmu/OpenEmu#3764]
I just installed the new version of OpenEmu (968-gf66035e-Release) to make it work with Mac Mojave. Works like a charm.

I played Zelda: A Link to the past without any problem yesterday evening. My 8bitdo also worked great.

I saved the game and tried restarting it this morning, but nothing works anymore. I only get a black screen, independent whether I try to start from the point where I quit, or if I try to start a new game.

Step by step:
open openemu
double click zelda rom from 'library' tab
choose 'yes' or 'no' from the 'do you want to continu where your stopped' from the popup
black screen
If I quit the game (via the red button on the navigation bar of openemu), I get a popup saying 'no communication possible with helper program' (see attached, in Dutch)
OpenEmu remains active, and I can return to the homescreen via 'window' -> 'openemu'

The same goes for all other supernes games. Other machines (megadrive, nes) work. 

Tried solutions
I use Snes9x core. I also tried Higan. Both give the same behaviour. 
I tried it with the 8bitdo connected and disconnected

Thanks in advance!

![schermafbeelding 2018-10-15 om 10 10 07](https://user-images.githubusercontent.com/31367673/46938072-17891680-d063-11e8-8055-4dd08160adf2.png)

**Comment by ingejanse** [comment]
I tried to find the crash report in Console when this happens.

fout	13:16:42.809538 +0200	OpenEmu	Unable to load Info.plist exceptions (eGPUOverrides)
fout	13:16:43.190469 +0200	tccd	Failed to copy signing info for 31391, responsible for file:///Applications/OpenEmu.app/Contents/MacOS/OpenEmu: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
fout	13:16:43.281889 +0200	OpenEmu	        AEGetDescData of non-desc type 'reco' not a good idea
fout	13:16:48.258675 +0200	OpenEmuHelperApp	Unable to load Info.plist exceptions (eGPUOverrides)
fout	13:16:48.316590 +0200	tccd	Failed to copy signing info for 31391, responsible for file:///Applications/OpenEmu.app/Contents/MacOS/OpenEmu: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"

**Comment by clobber** [comment]
Your game crashing both of the SNES emulator cores seems like a bad sign to me. Delete it and redownload one of the following ROMs, being sure to verify its MD5 checksum:

filename | MD5
:---: | ---
Legend of Zelda, The - A Link to the Past (Europe).sfc | ECFB3BD489A15CDDA12066100BDE0378
Legend of Zelda, The - A Link to the Past (USA).sfc  | 608C22B8FF930C62DC2DE54BCD6EBA72

**Comment by ingejanse** [comment]
Thanks! But the problems exists for all snes games. (see original message: 'The same goes for all other supernes games. Other machines (megadrive, nes) work.'). 

I reinstalled openemu, but that didn't change a thing. Is there a way to reinstall the supernes core, for instance?

**Comment by clobber** [comment]
Delete all the core plugins in `~/Library/Application Support/OpenEmu/Cores`  (~ meaning your Home folder where ~ is your username. Guide [here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) if you don't know this.), and then redownload them in the app (OpenEmu > Preferences > Cores).

**Comment by ingejanse** [comment]
Oh, that's great, thanks! I removed both cores, re-installed them, deleted the automatic save states, restarted openemu. And yes: it works again, and my manual save in the game still exists! I can continue! Thank you!

**Comment by ingejanse** [comment]
(thanks from Zelda to, she desperately needs the saving)
