### ISSUE TITLE
Autofill controls

### ISSUE THREAD

**Issue by polarbeared** [OpenEmu/OpenEmu#3766]
An incredibly annoying issue with a simple fix: a checkbox.
Currently I have two original PS 1 controllers plugged in by an adapter over USB. The PS 1 controllers emit a level of signal noise that is rejected by a real PS 1. Currently, I'm in the process of mapping these controllers. I want to throw my computer out the window.

Problem: after pressing the corresponding 'real' key on the controller, OpenEmu moves to the next field to map; this is especially annoying with the joysticks. The joysticks are not debounced. Therefore OpenEmu will often fill out the next field with the 'bounce' of the joystick. Sometimes, this will result in every field filling out with the same direction i.e. "Z-" or "X+".

A two-part problem:
- The field focus automatically moves to the next field when an input is registered
- The fields do not allow duplicates

Together, these two problems mean that: I may get one mapping finally correct, but through many, many 'bounces' I've lost other fields. Sometimes, a switch gets stuck and (if I'm mapping a field at the top of the list) I lose every subsequent field (which is sometimes 15 items) and I have to start over again.

Solution: a checkbox that says "automatically move onto the next field/don't allow duplicates"

# Steps to reproduce

Buy and connect a PS 1 or similar controller that is 'touchy' and attempt to map it via OpenEmu controller preferences. The behaviour can be observed with a regular keyboard. Type a key and you'll see it moves to the next field.

# Expected Behaviour

It doesn't move to the next field, because mapping controllers can be prone to switch bouncing.

# Observed Behaviour

It tries to be smart and moves to the next field automatically and does not allow duplicate control entries or copy pasting of controls.

# Debugging Information

- OpenEmu Version: 2.0.5
- macOS Version: 10.13.2

**Comment by clobber** [comment]
Aside from instead just using a DualShock 3 or DualShock 4 for the better experience, this can probably be mitigated by https://github.com/OpenEmu/OpenEmu/pull/3241
