### ISSUE TITLE
Pokemon Black 2  BLACK SCREEN near end game- OpenEMU 1.0.4

### ISSUE THREAD

**Issue by Zool123** [OpenEmu/OpenEmu#3767]
Summary of issue
So I'm nearly at the end of story mode and I'm playing Pokemon Black 2, I'm on the part after Giant Chasm, where I enter Team Plasmas ship for the second time. While on the ship I head towards the room leading to the bottom of the ship, right before the 2 V 2 Battle with the Team Plasma recruits. I go into the green Portal. Bang game goes completely black screen and there is nothing I can do. I'm pretty pissed as I am so close to end game and I want to complete it. Can I access the save file and open it into a different program? 

# Debugging Information

- OpenEmu Version: 1.0.4
- macOS Version: yes

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
