### ISSUE TITLE
Grey screen when opening any game, but sound is still playing

### ISSUE THREAD

**Issue by Supermanish13** [OpenEmu/OpenEmu#3768]
I was shocked to see that the game wouldn't load any video since OpenEmu was working fine just a couple of hours previously. However, there is still audio playing in the background, telling me that the game is still running. Unfortunately, I have no idea what happened to recreate this problem since in my eyes it happened spontaneously. I basically have no coding experience, by the way. I have already referenced comments #1190, #1681, #1688, and #1689 to no avail.

Hardware:
Early-2013 13-inch Retina MacBook Pro
2.6 GHz Intel Core-i5
8 GB 1600 MHz DDR3 RAM
Intel HD Graphics 4000 1536 MB
MacOS 10.14.1 Public Beta 4
OpenEmu Version 2.0.7

**Comment by clobber** [comment]
Issues from 2014 have nothing to do with your problem. Can't do anything for you without more information, try checking Console.

**Comment by Supermanish13** [comment]
I am very sorry but to be more specific mainly PSP games and DS games have this issue and I only say those games because those are the only ones I have. Also, lol I probably sound stupid (and I seriously am), but how do you find this "Console".

**Comment by clobber** [comment]
If you are having an issue with PSP games you should see here first: https://www.reddit.com/r/OpenEmu/comments/9hl9kp/cant_continue_last_game_on_psp/e6h2ap7/

**Comment by Supermanish13** [comment]
I'm sorry but I, in fact, do have PPSSPP version 1.6.3.2, so that Reddit doesn't apply to me I guess.

**Comment by clobber** [comment]
...read closer about the autosave states. You might need to do as suggested at the bottom.

**Comment by Supermanish13** [comment]
Okay, I'm thinking that it might be an issue with the new MacOS Mojave Public Beta 4 because OpenEmu worked fine on the Public Beta 3 about 7 hours ago. However, I updated to the Public Beta 4 about 3 and a half hours ago and it was only after that update that the games were like this:

<img width="1280" alt="screen shot 2018-10-18 at 9 36 20 pm" src="https://user-images.githubusercontent.com/44282034/47197876-e25c1d00-d31d-11e8-9460-49557d2ddbb6.png">

And I don't know if I'm tripping, but my reasoning tells me there is a compatibility issue or something between the new Public Beta and OpenEmu because the only variable between now and 7 hours ago is that update.

Let me know if you have any thoughts on the matter or if you found this as well with new beta.

**Comment by clobber** [comment]
Yeah... we don't run macOS betas on our daily drivers, and nor should anyone else. Those are meant for testing purposes. We also tend not to troubleshoot issues by those running OpenEmu on macOS betas because those issues normally work themselves out. Anyway, I think you may have found your variable. I guess we can revisit this after the next beta update or when 10.14.1 officially drops. For now I'll close.

**Comment by DomT4** [comment]
OpenEmu is working as expected again in the latest beta FWIW.
