### ISSUE TITLE
Controllers are permanently linked to Player #

### ISSUE THREAD

**Issue by maximbz** [OpenEmu/OpenEmu#3770]
When I set the buttons on my PS3 Six axis Wireless controller, inputting any button automatically switches the Player drop-down to Player 4. Using my XBox 360 controller to input buttons automatically switches it to Player 1.

Which Player is selected in the drop-down doesn't affect this. I can hold each controller in each hand and alternately press buttons, and the Player drop-down will switch rapidly between Player 1 and Player 4.

The USB port doesn't seem to affect this (I tried swapping which controller was in which port and got no change).

# Steps to reproduce

Connect PS3 to USB port.
Open Preferences window in OpenEmu and switch to the Controls pane.
Select Player 1 in the drop-down menu.
Click in field next to "Up:" -- OpenEmu waits for button input on controller.
Press Up on D-Pad of PS3 controller -- OpenEmu switches player to Player 4.

# Expected Behavior

Only the drop-down should be able to switch which player is being inputted for.

# Observed Behavior

Instead, there seems to be some sort of pre-set, where the XBox controller is permanently mapped ot Player 1, and the PS3 controller is permanently mapped to Player 4.

# Debugging Information

-OpenEmu version: 2.0.7
- macOS Version: 10.12.6

**Comment by clobber** [comment]
You need to select the Player # first and then the device from the bottom dropdown that you want to map controls for. If you'd like to start completely fresh by wiping out your existing changes, do the following:

1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.
