### ISSUE TITLE
[FR] Support Nestopia freeze saved files

### ISSUE THREAD

**Issue by utdrmac** [OpenEmu/OpenEmu#3775]
I'm switching to use OpenEMU and wanting to import my save states that were created using Nestopia. These cannot currently be imported by OpenEMU. When I drag/drop a .frz file onto OEMU, nothing happens.

# Steps to reproduce
Use Nestopia to save a game state. Attempt to import .frz file into OEMU

# Expected Behavior
For OEMU to import/accept the .frz state

# Observed Behavior
Nothing happens

# Debugging Information
- OpenEmu Version: 2.0.7 968-gf66035e-Release
- macOS Version: 10.13.6

**Comment by clobber** [comment]
Save states from a different version or fork of Nestopia may not be compatible with ours. You can try and fiddle with the .oesavestate bundle file and possible import over your freeze, but that is unsupported and I won't walk you through it. Instead, try importing over any in-game saves if the game has battery saves.

**Comment by utdrmac** [comment]
@clobber Instructions for importing in-game saves? I'm pretty sure my game had a battery when physically released.
