### ISSUE TITLE
Diagonal Controls

### ISSUE THREAD

**Issue by GRENSKIE** [OpenEmu/OpenEmu#3776]
Using a gamepad (USB clone of standard NES controller), I am unable to use diagonal controls, such as up and over in Contra to shoot at a diagonal angle.

Although this is happening with all games that support diagonal controls, I am referencing contra because, I have tested the controller with a copy of the same Contra.nes rom file on my sons computer with windows and a pc/windows based Nestopia emulator and it is capable of controlling it the way I want it to on there, so I know the controller and the rom file are good.

Is there something I am doing wrong or is there a way to enable simultaneous directional controls on OpenEmu?

- OpenEmu Version: 2.0.7
- macOS Version: 10.14 (Mojave)

**Comment by clobber** [comment]
It should already just work without issue and I cannot think of a reason it wouldn't with your device. See if anything applies here first:

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
