### ISSUE TITLE
UI doesn't respect accent color

### ISSUE THREAD

**Issue by MaddTheSane** [OpenEmu/OpenEmu#3777]
OpenEmu's UI does not respect the accent color of the system on Mojave and later.

There are some areas I can see implementing this being super-easy. Other areas would need to be tackled in a different way.

# Steps to reproduce

1. open System Preferences
1. Open General
1. Change Accent Color from Blue to something else
1. Look at UI

# Expected Behavior

1. Selections, etc… should match accent color

# Observed Behavior

1. Selections, etc… are blue

# Debugging Information

- OpenEmu Version: 2.0.7
- macOS Version: 10.14 (18A391)

**Comment by robotoad** [comment]
We've got improvements on this coming, specifically b906a82, 0423cab, and 112ae4c.
