### ISSUE TITLE
OpenEmu touch screen area not always responsive..

### ISSUE THREAD

**Issue by chinoponx** [OpenEmu/OpenEmu#3778]
Wondering if anybody else has encountered this problem, specifically with Lost In Blue NDS game. Sometimes the touch screen area will work, but sometimes, like with building beds/rafts whatever it wont register in that tiny box that they expect you to 'draw' in ... Any help welcome, even if anybody has any cheats would be helpful just to build things to skip this altogether... Thanks!

**Comment by clobber** [comment]
Game compatibility issues are not OpenEmu issues. This could be due to a bug in Desmume, a bug in the game, a bad dump of the game or even AP-patch related.
