### ISSUE TITLE
Updated Open-Emu to latest version only to find all of my save states wiped clean.

### ISSUE THREAD

**Issue by tylercoolidge** [OpenEmu/OpenEmu#3779]
I just updated OpenEmu to the newest version when I was prompted to (2.0.7), and restarted it after updating. I loaded my Game Boy Advance game of choice, went to load my latest save state, and found that all of my save states had been wiped with the update. I was just playing hours prior to updating, and had multiple save states. No save states for any game on any emulator remain. They aren't in OpenEmu's application support file either. They're gone. I am mad.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Open OpenEmu
2. Agree to update to latest version (2.0.7)
3. Open any game previously played with a save state
1. too much information is better than too little

# Expected Behavior

1. Update to latest version
1. Load game
1. Be able to load save states

# Debugging Information

- OpenEmu Version: 2.0.7
- macOS Version: OS X El Capitan 10.11.6

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3436
