### ISSUE TITLE
Problems on OSX Mavericks

### ISSUE THREAD

**Issue by ahab2000** [OpenEmu/OpenEmu#3784]
I have been running open emu on mavericks in Version 1.04 (latest Mavericks version) for a while now and everything worked fine.

Since I clean installed the whole system anew. It hast troubles opening Snes and N64 games. It always shows a status message that says: "Couldn`t communicate with a helper application" Anyone experiencing the same issues?

Is there something in need to install besides OpenEmu to make it work again. It must be possible since it was working fine before, I just cant figure it out.

Greetings, Simeon

**Comment by clobber** [comment]
Why are you thinking an old version of our software, released over 4 years ago, is still supported?

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
