### ISSUE TITLE
What is hash used for Artwork images

### ISSUE THREAD

**Issue by jkrauska** [OpenEmu/OpenEmu#3785]
I'm trying to reverse engineer how the artwork directory is maintained.

It seems that each ROM has a hash and that's how the artwork is stored and looked up.

eg. EFB1C72E-D4F4-4160-B53D-E257C6EA78EF comes from dkong.zip

It has the same number of digits as a md5sum hash, but with odd dashes, and it doesn't match the raw hash of the rom file.

I've found that manually removing a file and re-adding a file in the artwork directory re-applys the artwork in place.

Instead of manually clicking and dragging 100s of artworks I have each to an individual rom, I'd much rather script this.

Please advise?

**Comment by clobber** [comment]
Arcade ROMs do not yet have artwork, and won't any time soon. Those particular games are not identified via a hash either.

**Comment by jkrauska** [comment]
@clobber Please re-open.  When draging a jpg to an Arcade rom it sticks/works -- and it drops that file in the Artwork directory with a new name. So users are able to add their own artwork to Arcade roms.  

I'm asking HOW the name of that file dropped in Artwork is calculated.  
This is because I want to make it easier for ME to maintain my artwork.

It's a general purpose question about how ANY roms get artwork assigned.

**Comment by clobber** [comment]
Not a bug or OpenEmu issue. Sorry, I don’t have interest in this.
