### ISSUE TITLE
suggestion: automatically import local cover art file

### ISSUE THREAD

**Issue by solygen** [OpenEmu/OpenEmu#3786]
Would it be possible to easily add an automatic import of a local covert art file?

# Scenario

1. have a directory where two files are located (my-favorite.sfc, my-favorite.jpg).
2. drag the sfc file over to OpenEmu and drop into library
3. OpenEmu looks for an existing file, that matches the name and has a supported image file type
4. automatically add that that potentially found file as cover

---

by the way thanks for this amazing piece of software.

**Comment by PlutoX86** [comment]
Wait,.. don't you then have to download / rename every .jpg beforehand, put it in your downloads-whatever folder, just to avoid to drag&drop the cover art manually.. from a browser e.g.?! XD

**Comment by solygen** [comment]
More precisely i would like to add more than one rom in a row. Just drop a folder with a bunch of 'correctly' named files and go for it.

**Comment by clobber** [comment]
Glad you like the app, but sorry this would be outside the scope of the project and not worth the effort implementing.
