### ISSUE TITLE
Is there a way to have control schemes specific to different games? 

### ISSUE THREAD

**Issue by xFahrenheightx** [OpenEmu/OpenEmu#3788]
I have a need for separate control layouts for two different games on N64. One is tailored to FPS and the other is for a 3D platformer. Is there a way to have two separate control schemes and be able to switch between them?

**Comment by clobber** [comment]
No.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#206
