### ISSUE TITLE
PS1 - "Emulator could not load ROM" - CCD-IMG-SUB

### ISSUE THREAD

**Issue by Dolphiologist** [OpenEmu/OpenEmu#3789]
I have imported Ridge Racer Type 4 from a trusted and valid source. Upon opening the game, I get the error message "Emulator could not load ROM". I have carefully read and understood the CD-based games guide wiki. I am on experimental 3. Late 2011 MacBook Pro on High Sierra.
Can someone help me with this?

**Comment by clobber** [comment]
>Emulator could not load ROM

If your had done everything correctly then the game would load. You have something wrong.

>Can someone help me with this?

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Be as detailed and specific as possible..." and "Include Console and crash logs, macOS and OpenEmu version, hardware information, **ROM/game filenames, etc.**"
