### ISSUE TITLE
OpenEmu Crashing

### ISSUE THREAD

**Issue by Delta-Omega-Mu** [OpenEmu/OpenEmu#3792]
My OpenEmu won't open saying that 'An error occurred during persistent store migration.'
Originally, the emulator would crash as soon as I opened it, saying 'The operation couldn't be completed. (Foundation._GenericObjCError error 0.)'
When I reinstalled version 2.0.6.1., it then changed to 'An error occurred during...' etc.
I'm quite certain that this is an abnormality, as OpenEmu was working fine for the past 2 years. If it can only be fixed by deleting save states, I'm completely fine with that.
Any help is appreciated greatly.
Thanks.

OpenEmu Version 2.0.6.1.
MacOS High Sierra Version 10.13.3.

**Comment by clobber** [comment]
>An error occurred during persistent store migration

Don't know which version of OpenEmu you were upgrading from or which one you are using now but it's too late to fix any migration issue: #2649
