### ISSUE TITLE
improvements?

### ISSUE THREAD

**Issue by briannyeko** [OpenEmu/OpenEmu#3793]
When will you offer online(Bluetooth,NFC or Wi-Fi) capabilities to the emulators that you currently run? When will you offer Citra(3ds Emulator) to your platform?

**Comment by clobber** [comment]
* There will be no Wi-Fi support for NDS - that barely works on Desmume as it is.

* For other systems, there will be no "netplay" offered any time soon.

* There will be no Citra core port. 3DS is still sold in stores dude.
