### ISSUE TITLE
Importing an images folder into Nintendo DS 

### ISSUE THREAD

**Issue by Zaxploitation** [OpenEmu/OpenEmu#3796]
Hi guys, 

Thanks for the awesome work on OpenEmu.

I have downloaded and decompressed the Homebrew game: DS All Stars
(https://gamebrew.org/wiki/DS_All_Stars)

The game folder contains:
1.  The rom (DSAllStars.nds)
2. An images folder containing a collection of gif images (Gifallstars)

The developers installation guide suggests that you copy ‘DSAllStars.nds’ and ‘Gifallstars’ to the root directory of your micro SD card. Which is obviously not an option when using an emulator ;-).

Now I know that you can simply drag the .nds file into the OpenEmu window but I’m assuming that you cannot simply drag the images folder into: .../Game Library/roms/Nintendo DS?

Is there a way to get NDS games with image folders working on OpenEmu or is this a non-starter?
The question also applies to games with a ‘Gamedata’ folder which may alongside images also include music in the mp3 format.

Regards,

Paul

- OpenEmu Version: 2.0.7 (968-gf66035e-Release)
- macOS Version: 10.14.1 (Mojave)

**Comment by clobber** [comment]
The homebrew game was developed for use on a flash cart, so it will not be able to read external files like this through an emulator.

**Comment by Zaxploitation** [comment]
> The homebrew game was developed for use on a flash cart, so it will not be able to read external files like this through an emulator.

Perfectly clear, thanks Clobber.
