### ISSUE TITLE
m3u don`t work when convertet in textmate

### ISSUE THREAD

**Issue by dipdoplup** [OpenEmu/OpenEmu#3797]
when i want to make a cue file and save it as m3u the openemu wont read the the file.

i have downloadet driver to i put the game in texmate and change it to 

Driver 2 (Disc 1) (v1.1).cue
Driver 2 (Disc 2) (v1.1).cue

After that i save the file as driver2.m3u drag the file to openemu, noting 

i have followed the steps but nothing happens after i updatet openemu

i have openemu 2.0.7 and mac versj 10.14.1 mac os mojave

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."
