### ISSUE TITLE
Gravis Gamepad Pro stopped working

### ISSUE THREAD

**Issue by Yankeesboy** [OpenEmu/OpenEmu#3798]
Gravis Gamepad Pro joystick (usb cable) stopped working issue: 

I am using Gravis Gamepad Pro Joystick controller with OpenEmu on my iMac (21.5-inch, Late 2009) running on macOS High Sierra (10.13.4)

It was flawless until yesterday, the controller stopped working out of blue. I tried to fix the issue but it simply refused to connect/work. 

Then, I moved the Gravis Gamepad pro joystick to my another iMac (21.5-inch, Early 2011) running on macOS High Sierra (10.13.4). The controller works without any issue. The iMac recognizes the automap USB without any issue. 

Next, I formatted my iMac (21.5-inch, Late 2009) and restore time machine only my account excluding system folders for a fresh start. When I tried again to see if OpenEmu and the iMac recognizes the joystick controller - the answer is no. It simply refused to recognize the controller? 

Why is this happening? I tried to search online for troubleshooting/help but I couldn't find anything? All I know that this iMac USB ports are functions fine because the keyboard/mouse are working too so.. is this means there's a file sitting inside the iMac that is corrupted and needs to be fixed and connect to the controller? Any tips? I need this issue to resolve soon. 

Thank you!

**Comment by clobber** [comment]
>controller stopped working out of blue

>Then, I moved the Gravis Gamepad pro joystick to my another iMac (21.5-inch, Early 2011) running on macOS High Sierra (10.13.4). The controller works without any issue. 

Not going to be any bug related to OpenEmu.

>I tried to search online for troubleshooting/help but I couldn't find anything?

Try actually reading the [Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
