### ISSUE TITLE
Final Fantasy VII 

### ISSUE THREAD

**Issue by AlexGoldGaming** [OpenEmu/OpenEmu#3801]
I have been using OpenEmu for the past week to emulate games. I had previously downloaded a European version of the rom and dragged the cue files on to OpenEmu if that is a problem. But I am currently trying to import a multi-disc .m3u into OpenEmu. I did not preload them in and I believe followed the steps correctly. I had put all 3 discs into TextMate and added the .cue extension to the discs and titled the file as a .m3u.

![screen shot 2018-11-25 at 6 01 09 pm](https://user-images.githubusercontent.com/45342737/48986542-293af080-f0dc-11e8-8d8e-db911552a51d.png)

When I drag the .m3u file into OpenEmu it doesn't load it. I don't know if the files are still imported or sitting in the Game Library folder but I would like to know the issue.

Extra Info
OpenEmu Version: 2.0.7
OS X El Capitan Version: 10.11.6
I downloaded these from Romsmania

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."
