### ISSUE TITLE
Is it possible to run Game & Watch games on OpenEmu?

### ISSUE THREAD

**Issue by nossramo** [OpenEmu/OpenEmu#3802]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by irishmapping** [comment]
No, but there may be some homebrew recreations. But a dev can answer that for you.

**Comment by clobber** [comment]
>Is it possible to run Game & Watch games on OpenEmu

No. If there was a core port supporting that systems you would see it in the application.
