### ISSUE TITLE
Don´t know where to post this, but is it possible to support Game & Watch games?

### ISSUE THREAD

**Issue by nossramo** [OpenEmu/OpenEmu#3805]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
What exactly is your malfunction? You already opened an issue for this yesterday and I gave you an answer. Stop opening issues here.

#3802
