### ISSUE TITLE
Save States Keep Disappearing

### ISSUE THREAD

**Issue by turtleisaac** [OpenEmu/OpenEmu#3808]
It doesn't happen very often, but occasionally, all of my save states in almost every game will disappear. It's not much of a problem, considering that I don't usually load from the last autosave, but it is slightly annoying. I have checked in the OpenEmu folder in application support, in the save states folder, and have seen for myself that all of my save states are gone. They are also not there in the game (obviously.) Usually, these old save states going missing isn't that much of a problem, because I've already gotten past that point in the game, but it is slightly annoying, especially when I made them as backups for when I'm about to do a glitch in something like Pokémon Red. I'm not sure about what is causing it, but I do know that after closing a game sometimes, the "home screen" on OpenEmu (the game selection screen) won't reappear and I will have to quit or force quit the application. I say "in almost every game" because I checked the save states folder for a game I hadn't played in a while and saw that the save states for it were still there. (It was Legend Of Zelda Majora's Mask) (if that helps) But more recent stuff like Pokémon Red and Legend of Zelda Ocarina Of Time had lost all of their save states. (Battery saves were still intact.) I don't know how much this will help, but I have also noticed that trying to load a N64 game from the last autosave right after choosing to start the game in the "home screen" will result in some Mupen64 optimization message and it doing a full normal boot of the game (doesnt go to save state, does N64 boot screen and goes to title screen.) Obviously, I would like my save states to not disappear, and them to be accessible always. 

I am using macOS Mojave on a late 2015 iMac 27". My OpenEmu version is v2.0.7, and under the version, it says "968-gf66035e-Release"

**Comment by clobber** [comment]
What you're describe cannot happen, unless you removed them yourself. What I think you are experiencing is the removal of old save states created from deprecated core plugins that are no longer supported - or states that had to be removed due to compatibility being broken in a core plugin update. This would be observed after recently upgrading from an older version of OpenEmu.

This is described in #3436
