### ISSUE TITLE
Dr Kawashima's Brain Training on Nintendo DS 

### ISSUE THREAD

**Issue by Puma972** [OpenEmu/OpenEmu#3810]
The rom "Dr Kawashima's Brain Training: How Old Is Your Brain" on Nintendo DS needs to rotate 90°. I looked for a solution without success. Maybe it's necessary to implement an option?
Thanks.
Gianmarco.

- OpenEmu Version: 2.0.8
- macOS Version: 10.14.1

**Comment by clobber** [comment]
Already a feature request for this open. Although, it should probably be implemented core-side instead of front-end side.
