### ISSUE TITLE
cheats menu not able

### ISSUE THREAD

**Issue by alestormoody** [OpenEmu/OpenEmu#3815]
i use mac os, and i download the last version of openEmu from the site ( 2.0.8 ).
I've tried a game, but i don't see the chats option on the hud menu... can you help me?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3308
