### ISSUE TITLE
Super Mario 64 Romhacks unplayable in version 2.0.8

### ISSUE THREAD

**Issue by RobertLowe** [OpenEmu/OpenEmu#3817]
# Summary of issue

Re-opening of: https://github.com/OpenEmu/OpenEmu/issues/3445

# Steps to reproduce

1. With 2.0.8 try to open `Super Mario Star Road Final` romhack

---

1. Download `mupenplus-2.5` (latest as of posting) https://github.com/mupen64plus/mupen64plus-core/releases/download/2.5/mupen64plus-bundle-osx64-2.5.zip
2. Open `Super Mario Star Road Final` romhack with either `run_glide.sh <rom-path>` or `run_rice.sh <rom-path>`
3. Both work as expected

# Expected Behavior

1. Should work the same as the `mupen64plus-core`

# Observed Behavior

1. Black screen.

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.13.6

**Comment by clobber** [comment]
Um, this is OpenEmu.
