### ISSUE TITLE
How do I install extra unsupported cores?

### ISSUE THREAD

**Issue by Azync** [OpenEmu/OpenEmu#3818]
I am having difficulty understanding how to install Dolphin-Core. I cannot run Dolphin but I can run OpenEMU so I want to know how to open WII games through Open EMU. I have pressed OpenEMU>Preferences>cores but the page is empty and I do not see any option to install Dolphin.

**Comment by clobber** [comment]
>install extra unsupported cores

Wow it's almost like you already knew the answer you were going to get. Go use [Dolphin](https://dolphin-emu.org/).


[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Usage of [experimental and WIP](https://github.com/OpenEmu/OpenEmu/wiki/Console---Core-Plugin-Status-&-Wishlist) core ports are strictly unsupported and have no ETA."
