### ISSUE TITLE
bulk update paths of roms after moving rom folder by modifying Library.storedata.sqlite

### ISSUE THREAD

**Issue by vesper8** [OpenEmu/OpenEmu#3819]
I just had to move my entire rom collection to another volume on my mac and this caused me a lot of headaches. Following that none of my games were staring of course, each time I was asked to "locate" the rom and I had to manually point it to the new location

I tried the 'add to library' option but it crashed every time with a NSInternalInconsistencyException error. Drag'n'drop would also cause OpenEmu 2.0.8 to crash. I think if I had deleted all the old roms I would have been able to add them back, but then this would have also had the unwanted consequence of deleting all my save state data which I didn't want

I just wanted to be able to edit the paths manually and I knew there must be a way, but I couldn't find any solution in the issues or on reddit. So I tinkered and finally I found out how to do it, so here is the solution for anyone that wants to bulk change rom paths for whatever reason

Find the Library.storedata file inside your Game Library folder. Make a backup of this, then rename it to Library.storedata.sqlite

Then open it up with a database editor that supports sqlite. I suggest TablePlus because it's free and excellent

Then export the ZROM table to .csv format

Then open the .csv with a text editor such as Sublime Text and do a find/replace on the folder path
Save your modified .csv with the correct paths

Then back to TablePlus, truncate the ZROM table and commit your change. Then import the .csv

Finally rename the file back to Library.storedata and copy it back to its original location, overwriting the existing one. Do all of this while OpenEmu is not running

Voila.. not all roms load again as if the move had never happened.

Hope this helps someone else.

Wish there was a built-in way of doing this

Cheers

**Comment by clobber** [comment]
This seem weird and incredibly unnecessary. Paths stored in the datastore are already relative. One can simply move their Game Library folder from the option we have in Library preferences inside the app.

**Comment by vesper8** [comment]
Guess it was my fault for not doing it this way initially. I have a folder called _EMU in which I have the Game Library folder and the roms folder

I moved the entire _EMU parent folder to a new Volume and ended up in a mess. And the above solution was the only way I could fix it

**Comment by yoyoblake** [comment]
Thanks  - been looking for a good way to do this.  My issue is I setup a new Mac with OpenEmu and wanted to move my library over to an external drive to use - in that case you do need to edit the paths as import of an existing library is not supported.

**Comment by udance4ever** [comment]
> Paths stored in the datastore are already relative. 

relative to where?  could you provide a concrete example?

My understanding is ROMs are not stored inside the Game Library folder.

> One can simply move their Game Library folder from the option we have in Library preferences inside the app.

I moved my Game Library folder to a location that is not relative to where my ROMs are stored.

What would be really useful is a setting to redefine the root ROM folder.
