### ISSUE TITLE
There ain't a button to put in the cheat code

### ISSUE THREAD

**Issue by Sungminleekorean** [OpenEmu/OpenEmu#3820]
Summary of issue
I just download a new Openemu on my mac, and everything works alright but there ain't a button for the cheat code. I searched for a long time, including the grey bar while I am in the game...anyone like this too? Is there any solution for this? Thanks!

ps. I am using the PSP mode.

![2018-12-14 11 40 36](https://user-images.githubusercontent.com/45892559/50040511-b7c6d180-fff9-11e8-8cf5-3a726a17b1d3.png)

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3308
