### ISSUE TITLE
FFVII with Mednafen not responding to controller

### ISSUE THREAD

**Issue by Blackrush** [OpenEmu/OpenEmu#3825]
I have a Macbook Pro 2015 with an Xbox 360 controller and when running FFVII with Mednafen no input is working even with the keyboard so I get stuck on the credits. No problem with Crash Bandicoot: Warped though.

# Steps to reproduce

1. Import FFVII into OpenEmu
2. Play it

# Expected Behavior

The controller to be working

# Observed Behavior

Get stuck on the credits.

# Debugging Information

- OpenEmu Version: 2.0.8, 016-g31a4fbf-Release
- macOS Version: 10.13.6
- Xbox 360 Controller Driver Version: 0.16.5

**Comment by clobber** [comment]
There is no such thing as per-game input bugs. 

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
