### ISSUE TITLE
FFVII freeze issue

### ISSUE THREAD

**Issue by Blackrush** [OpenEmu/OpenEmu#3826]
Hello @clobber, I know it can be very tiring to sort other people's issues but I'm willing to help and I don't think I did anything wrong until now. Sorry for my previous bug-report which contained very poor information.

It appeared at first that the game had problem with the controller, which was obviously false since Crash Bandicoot worked just fine. What proved this to me is that I got to the next menu, but with great effort, and then everything just freezes. OpenEmu continue to have normal CPU usage.

It's just what appears to me because there is no debug information to be given back. Don't close this issue just yet, we'll edit this issue later if we need. If you don't have the time right now, leave the issue open because that's a real issue, don't throw this under the carpet you know?

# Steps to reproduce

1. Decode `.ecm` files into `.bin`
1. Generate `.cue` files using [CueMakerPy2](https://github.com/thorst/CueMaker/blob/master/CueMaker/CueMakerPy2/CueMakerPy2.py)
1. Import `.m3u` playlist of CD `.bin` files
1. Close every other running apps
1. Launch OpenEmu
1. Assign Controls to Xbox 360 inputs
1. Play the game

# Expected Behavior

To get past the credits or to be able to create a new game.

# Observed Behavior

Get stuck on never ending credits or just freezes on new game menu.

# Debugging Information

- OpenEmu Version: 2.0.8 `016-g31a4fbf-Release`
- macOS Version: 10.13.6
- Xbox 360 Controller Driver Version: 0.16.5

```
$ md5sum Final\ Fantasy\ VII\ \(E\)*
95daa58e45d71bfe6ce3c699c87652a0  Final Fantasy VII (E) (Disc 1) [SCES-00867].bin
05568d738344820d3549d4ac9e076669  Final Fantasy VII (E) (Disc 1) [SCES-00867].cue
b469faf7e80a1d4c8b51d61472fe9207  Final Fantasy VII (E) (Disc 2) [SCES-10867].bin
393296680fd35df62374c0e1b2c239a4  Final Fantasy VII (E) (Disc 2) [SCES-10867].cue
8538ff9ee95c9e2e029608c2ce787045  Final Fantasy VII (E) (Disc 3) [SCES-20867].bin
93d2b1bd4a52de093b2086a96a340926  Final Fantasy VII (E) (Disc 3) [SCES-20867].cue
```

```
% md5sum scph*
8dd7d5296a650fac7319bce665a6a53c  scph5500.bin
490f666e1afb15b7362b406ed1cea246  scph5501.bin
32736f17079d0b2b7024407c39bd3050  scph5502.bin
```

**Comment by clobber** [comment]
These are not OpenEmu problems. Sounds like you have a bad rip of the game to me. Google a bit and download a rip from “Redump”.

**Comment by Blackrush** [comment]
Actually I verified checksums of the files and they match the one provided by `redump.org`. Even after replacing the Cuesheets it still does the exact same thing again.

Hey man you need to chill, even if these are not OpenEmu (which I highly doubt at this point) stop being so butt-hurt about this and stay cool about it. I am not attacking you nor the quality of your project. Your behaviour is really unprofessional : is this what the kind of community you want to build here?
