### ISSUE TITLE
Static Noises on GBA Games

### ISSUE THREAD

**Issue by yeahokay12** [OpenEmu/OpenEmu#3834]
How to reproduce:

1. Install Pokemon FireRed 800.
2. Open the game up and press A all through the introduction, up until it goes to the help screen.

What I expect:

1. I need the game to...well...properly work. I have no idea why this doesn't work but there is another game called Pokemon Sweet that also doesn't work, and neither does the sequel.

What I observe:

1. I double click on the game to open it up, and it loads the normal intro for fire red but after the tutorial(?) it goes to a black screen and plays loud distorted/staticy sounds.

Debug Info:

- OpenEmu Version: Latest (2.0.8)
- macOS Version: Mojave; 10.14.1

**Comment by clobber** [comment]
Pokemon ROM hacks not working with the mGBA core plugin are not OpenEmu bugs.
