### ISSUE TITLE
Full screen / zoomed window performance on Intel GPUs

### ISSUE THREAD

**Issue by sxflynn** [OpenEmu/OpenEmu#3835]
When I set OpenEmu to full screen, the frame rate drops to below 60fps. 

# Steps to reproduce

1. Run any NES rom, for example, Super Mario 3
1. Set to display filter: nearest neighbor to make it run as easy as possible
1. Play in window mode, and notice the very fast frame rate.
1. Set to full screen mode, and notice how the frame rate is a little slower.

# Expected Behavior

When in full screen mode, the frame rate should stay a constant 60fps.

# Observed Behavior

When in full screen mode, the frame rate drops slightly. See this [Youtube video](https://www.youtube.com/watch?v=gYcZBouHOtg) for a demonstration of the reduced frame rate when in full screen.

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.14.2

Tested on a Macbook Pro Retina 13inch late 2013
2.4Ghz Intel Core i5
8 GB of RAM
Graphics: Intel Iris 1.5 GB

**Comment by clobber** [comment]
It appears we've reached our limit with the old Cg framework. I've experienced this now on 10.14.2 with an Intel Iris Pro (MBP 15'' Mid 2015), and oddly it's even worse after just restarting my machine. It's less bad when switching to Linear or Nearest Neighbor (to bypass the Cg shaders) but still not smooth. Switching to the discrete GPU seems to mitigate the problem but that's not a solution for most users.

@mrvacbob I think we need CARemoteLayer/CAOpenGLLayer or Metal for 2D now :P

#3472, #3677, #3783 are related.

**Comment by mrvacbob** [comment]
@sxflynn please file a bug about this to Apple at bugreporter.apple.com or with Feedback Assistant.

**Comment by mruxsaksriskul** [comment]
Same issue here for me for PSP core on a MacBook Air 2018 - Mojave - 8GB Ram. It's only occurring on built in Retina if I move OpenEmu window over to separate screen it runs fine. I did try the nearest neighbor and Linear @clobber those did help make it playable thanks for that. Think there will be a new wrapper coming any time soon?

**Comment by mruxsaksriskul** [comment]
@mrvacbob  I went ahead and opened a bug via feedback to Apple not sure it's visible but it's here https://feedbackassistant.apple.com/feedback/6132239. FYI @sxflynn

**Comment by mrvacbob** [comment]
Thanks. Metal is currently in development on a branch and is much faster. We're not ready to test it but I expect it will solve your problem.

**Comment by sxflynn** [comment]
Not reopening the issue, but I just wanted to say that this behavior is no longer being observed. I’m on the latest version of OpenEmu.
