### ISSUE TITLE
VBA to openemu

### ISSUE THREAD

**Issue by shakespeare1142** [OpenEmu/OpenEmu#3837]
Hey so I just upgraded from the virtual boy advance to OpenEMU and I was wondering if there was anyway i could import my save states

**Comment by clobber** [comment]
Not save states. You want to transfer in-game battery saves, which you can figure out how to do by reading here: https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files

The guide was written for when we still had a VBA core plugin in use, so you will have to find your folder where your battery saves are kept with the standalone VBA app and then transfer them over to mGBA for OpenEmu.

**Comment by shakespeare1142** [comment]
thanks my laptops being fussy but i'll figure it out
