### ISSUE TITLE
Link Cable support

### ISSUE THREAD

**Issue by zziggarot** [OpenEmu/OpenEmu#3838]
I'm wondering if there is any way to implement a link cable of sorts for game boy emulation

There is no link cable support on open emu that I have been able to find
(i.e. trading and battling in pokemon and TCG games)

could we maybe implement something over bluetooth?

I've seen this idea mostly getting brushed aside

**Comment by clobber** [comment]
Nope, sorry, Gambatte doesn't support that feature for Game Boy / Game Boy Color. Use cheat codes. 

>I've seen this idea

Please do not open duplicate issues.
