### ISSUE TITLE
8BitDo N30 Arcade Stick :: Pairing / Mapping Issues

### ISSUE THREAD

**Issue by sohojohn84** [OpenEmu/OpenEmu#3842]
Hello, 

I am trying to pair my 8bitdo joystick (N30 Arcade Stick) with Openemu and I am experiencing a weird issue.

Before I upgraded to the new firmware from 8Bitdo, I couldn't map the A button.

I have now updated to the new firmware and the controller appears as Nintendo Switch Pro Controller, and when I select it, it reverts back to "Keyboard".

Not sure if other members experienced the same issue. FYI I am running on Mojave 10.14.2

Thanks!

**Comment by clobber** [comment]
>I have now updated to the new firmware and the controller appears as Nintendo Switch Pro Controller

I have to mention this time and time again for people using 8Bitdo devices:

Stop using 8bitdo's incorrect "Mac mode" when you pair their devices. Power on with START, not START+A or any other modes.

**Comment by sohojohn84** [comment]
I do power it with Start, however, doesn't solve the issue.

**Comment by clobber** [comment]
You are not pairing in the right mode if the devices appears as a "Nintendo Switch Pro Controller". Sorry, can't help you beyond that.

**Comment by sohojohn84** [comment]
As a matter of fact, I am not looking to get it to work on bluetooth. USB would be just fine. However, I can't seem to get Openemu to recognize the stick
