### ISSUE TITLE
Persona 3 PPSSPP PC ISSUE

### ISSUE THREAD

**Issue by honeyraven** [OpenEmu/OpenEmu#3843]
I just recently downloaded persona 3 portable to my psp emulator. I have Windows. I set the keyboard controls and launched the game. I get the little intro song, and then the main screen. On the main screen it says New Game, Load Game, Config, etc. I try to hit New Game, but it won’t let me. In fact, it won’t let me click any of the options. Which is confusing considering I could use a button to skip the initial intro and was able to hit the “press any button to start” however that’s as far as it let’s me get. I’ve tried mapping my controls, changing them out. But NOTHING is working. I can use my arrow keys to go up and down from options, but no key works to hit any of them. Please help.

**Comment by clobber** [comment]
You’re lost. This is the repo for OpenEmu which is macOS software only.
