### ISSUE TITLE
Minor lag when computer plugged on Smart TV

### ISSUE THREAD

**Issue by sohojohn84** [OpenEmu/OpenEmu#3844]
This is most likely unrelated to Openemu itself.

I have 2 Macbook Pros. One from 2012 and I purchased a 2018 recently. I experience no lag when I play Openemu on my smart Tv using my mac from 2012. 

However, there is a minor lag when I use the 2018. Since we are all mac users has anyone experienced the same issue and know how to remove the lag? For reference, both machines are running on Mojave 10.14.2 and screen is on game mode.

Thx!

**Comment by clobber** [comment]
Sounds like #3835
