### ISSUE TITLE
Cheat codes not saving Gameboy Advanced. 

### ISSUE THREAD

**Issue by ethanbreck** [OpenEmu/OpenEmu#3847]
Summary of issue:
Add cheat codes for Gameboy Advanced game, (Pokemon Emerald), and save that state, yet the cheats need to be added every time., 

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
2. How to cause the problem
3. leaving nothing out
4. too much information is better than too little

Add cheats to game, and verify they work. (Work on my system.)
Play for some time.
Save game state, and close system. 
Quit app
Reopen app, and game. Cheats not there in the cheats menu. 

# Expected Behavior

1. Describe what
1. you want to
1. happen

I thought cheats get saved to the game, with the save state of the game. But according to issue #782, I need to find a Cheats-database.xml file in the program and manually add cheats.

I would like to either add cheats in the game, or have some way to add cheats and make sure they are saved for the game, so I don't need to save it every time I want to play.

 # Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

I add the cheats, but when the game is saved and closed, and the app is quit, the cheats seem to disappear from in game. 

# Debugging Information

- OpenEmu Version: V 2.0.8 (016-g31a4fbf-Release)
- macOS Version: 10.14.2 (18C54)

Additional Notes:

Maybe have an add on screen as a cheat manager to edit the file without needing to know the technical know-how, and needing to find the Cheats-database.xml file. 

Cheats-database is located at /Applications/OpenEmu.app/Contents/Resources/cheats-database.xml

**Comment by clobber** [comment]
Please don't open duplicate issues. I see you are aware of #782.
