### ISSUE TITLE
PSP massive control input lag

### ISSUE THREAD

**Issue by TeddyRocks** [OpenEmu/OpenEmu#3848]
Hello.. I have massive control input lag on ANY psp game. I was so excited to be able to play my PSP games as I have a huge library of UMD's and my PSP3000 died last year.
My mac is quad 2.8ghz i7 4980HQ
16GB ram
1TB Apple SSD
Nvidia 750M 2GB, intel Iris Pro disabled so discrete GPU always on

I have a few games for genesis and snes and saturn still in my collection, and those all work perfectly. Zero lag. They really feel amazing instant.

The issue with the PSP emulator is that the lag is there even when using the keyboard built in to the macbook.. so i know it's not an issue with the controller.

The controller I am using is the 8bitdo SN30 pro, both wired and bluetooth modes.

There are no framerate or performance problems with any  of the PSP games.. JUST control input lag.. I feels so sluggish it makes platformers and shmups more or less unplayable. I was really disappointed.

However, i feel it *may* be related to the mac os bluetooth being on at ALL, as when it is disabled completely, lag does seem to improve considerably. So possibly a conflict between ppsspp or openemu and sierra bluetooth service?

It also does NOT matter what screen filter is used. The lag happens in every game (tried all 65 i have legit UMD's of), both keyboard and controller, and every single screen filter choice. I have no idea what to do as ALL the other emus I happen to own original games for, just work with super fast controls. All the emus with public domain free roms downloadable from within Openemu itself also work without control lag. I have two legit PS1 games, Tempest X and Robotron X, so I'll also try those when i can, to see if it's a sony/open emu issue also.

I searched and searched and can find basically nothing about this issue from anyone else.. I will test on my imac pro and High sierra 10.13.6 as well if that is required (vega 64) but will only install it if admin really wants me to as that is my production machine.

Thank you kindly and please let me know any further  info i need to provide. This is my first post and I joined only to post this. 

On a side note, are we allowed to make threads with feature requests? Is there a feature request area?
# Debugging Information

- OpenEmu Version: 2.08
- macOS Version: 10.12.6

**Comment by clobber** [comment]
>However, i feel it may be related to the mac os bluetooth being on at ALL, as when it is disabled completely, lag does seem to improve considerably. 

Our PPSSPP core plugin implementation should not be adding any input latency, and I'm not sure this is an OpenEmu bug here. See if anything applies in: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

Side note: Whatever machine you use for OpenEmu should probably be using the latest macOS release.

**Comment by TeddyRocks** [comment]
Hi, I am using a supported config.. it's 10.11+.. if it requires 10.14 then please say so on requirements.
Nope, went through the entire list, nothing there applies here.

As i said the only thing that improves it is shutting down the bluetooth service entirely.

In any case, the reason I took many hours to reply is that I have reproduced the issue on my imac pro.

The imac pro was bought 6 months ago, 64gb ram, 8 core 3.2ghz xeon, 2TB Apple ssd, Vega 64 16gb. it shipped with OS 10.13.6 and I have never changed that.

I doubt putting on 10.14 would help in any way, or has there been specific code put into openemu TO take advantage for 10.14? 10.14 is in it's infancy and I truly believe 10.13.6 is still the absolute best Mac os around at present.. it's solid as a rock and fast. 

Anyway, the imac pro situation is a little bit different as it does not have a built in keyboard.. Also, I have used ONLY the keyboard to do the tests so far.
I have tried the included keyboard both ways.. via blue tooth, and connected via USB to the imac.

I also left the imac in it's raw state, as in, NO other peripherals connected..just keyboard, hardwired usb mouse (in case the bluetooth was causing the issues).. that's it.

Same problem as my macbook. Every time i press an arrow key to move or a button to fire or jump, there is a delay that makes the games unplayable.. it feels like about 500 - 700ms to me if I was to guess.

So, totally different computer, newer OS, much more powerful computer with very decent graphics.. same issue. All i did was install open emu and import a few of my roms to try. I have no  idea why this is happening but in 2.08 i am telling you there is something wrong with the PSP emulator. What else could it be?

Regards
Ted
