### ISSUE TITLE
Unable to Import M3U files when formatted correctly

### ISSUE THREAD

**Issue by Plasmabob1** [OpenEmu/OpenEmu#3849]
I'm on OpenEmu Version 2.0.5 and I'm trying to import Metal Gear Solid onto OpenEmu but I can't seem to get it to work, I've formatted the folder correctly and I'm only dragging and dropping the .m3u file.
This is the folder that I have made.
![screen shot 2019-01-20 at 9 33 53 pm](https://user-images.githubusercontent.com/46869371/51442116-4e726680-1cfb-11e9-94c1-b4c566967b50.png)
This is my .m3u file
![screen shot 2019-01-20 at 9 36 56 pm](https://user-images.githubusercontent.com/46869371/51442135-8d082100-1cfb-11e9-9bc5-125300992af0.png)
When I try to drag and drop my .m3u file the Game Scanner bar doesn't appear at all.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."
