### ISSUE TITLE
Impossible to connect more than 2 Wii U Pro controllers at once

### ISSUE THREAD

**Issue by aalarie** [OpenEmu/OpenEmu#3851]
# Steps to reproduce

1. Pair any 3 Wii U Pro Controllers to OpenEmu
*Note: You will not be able to pair all 3 at once due to the bug. Close the app to disconnect the already connected controllers and then pair the third one.
2. Starting with a new instance of OpenEmu where no controllers are connected, attempt to connect all 3 Wii U Pro controllers by pressing a button on each controller.

# Expected Behavior

1. All 3 controllers will pair with OpenEmu.

# Observed Behavior

1. Regardless of the permutation in which the controllers are paired, the first two will connect and the third one never will.

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.14.3

**Comment by clobber** [comment]
Does this issue still occur with OpenEmu 2.1.1? This will be difficult to test on our end.

**Comment by aalarie** [comment]
I can confirm that this is still reproducible with 2.1.1. If you tell me where this is handled in the code I could take a look and try to figure out what's going on.

**Comment by clobber** [comment]
Input code, and probably the Bluetooth stuff, lives in the OpenEmu-SDK repo. We may have already fixed this problem, but I need you to confirm, so in a few days I’ll provide you with a test build.

None of us have multiple Wii U Pro controllers so this may difficult for us to pin down.

**Comment by aalarie** [comment]
Sounds good.

**Comment by clobber** [comment]
@aalarie please test: https://send.firefox.com/download/5576844b5bc3daf5/#GN872buu222p2DU5z0UAig

**Comment by clobber** [comment]
Hopefully fixed as of OpenEmu 2.2. If not, please confirm.

**Comment by aalarie** [comment]
Just tested on 2.2. Unfortunately still happens.

**Comment by shysaur** [comment]
Please open Terminal.app and copy-paste the following command (note that it assumes that OpenEmu has been installed in the Applications folder):

`/Applications/OpenEmu.app/Contents/MacOS/OpenEmu -OELogCoreOutput 1 &> ~/Desktop/log-openemu.txt`

Press Enter in Terminal to launch OpenEmu, then reproduce the bug. Afterwards, close OpenEmu, and reply to this issue by attaching the `log-openemu.txt` file that appeared on the desktop. (avoid copy-pasting the contents of the file in the reply)

**Comment by aalarie** [comment]
[log-openemu.txt](https://github.com/OpenEmu/OpenEmu/files/4024053/log-openemu.txt)

Here's the log. As you'll see it detects the first two Nintendo RVL-CNT-01-UC, but then nothing for the third one. The OE_removeStateWatcher line makes it seem like it stops checking for devices after two are connected.

**Comment by shysaur** [comment]
Actually, the `OE_removeStateWatcher` line is unrelated to the input system. 

In fact, it seems that macOS itself is not even notifying OpenEmu that there are other controllers connected.

Is the third controller correctly paired to your Mac, and does it show up as "Connected" in  System Preferences > Bluetooth? If it does not show up there, then there is absolutely nothing we can do on our end.

**Comment by aalarie** [comment]
Yes it shows in Bluetooth preferences. If I connect the third one before the second one, then it will connect, but the second one won't. Only two can every be connected at the same time. Maybe the issue is with the driver itself? All of these controllers were paired through OpenEmu.

**Comment by shysaur** [comment]
It surely seems so... As a last check, could you please execute the following command in Terminal.app?

`hidutil list > ~/Desktop/hidutil-list.txt`

Then attach the "hidutil-list.txt" file that appeared on the desktop here. If only two controllers appear in the list output by `hidutil list`, then it is indeed a driver issue.

**Comment by aalarie** [comment]
[hidutil-list.txt](https://github.com/OpenEmu/OpenEmu/files/4024668/hidutil-list.txt)

Only two show up.

**Comment by shysaur** [comment]
There's really nothing we can do to fix this then.

**Comment by aalarie** [comment]
That’s a shame. Out of curiosity, what is the driver that you use?

**Comment by shysaur** [comment]
We do not use any special driver, just the standard Human Interface Device (HID) driver shipped by Apple with macOS. This same driver handles all USB and Bluetooth keyboard, mice, and game controllers. We have some custom code for handling Nintendo controllers such as yours which use the HID specification in a slightly non-standard way, but we still rely on the standard macOS HID driver to do so.

This is why OpenEmu is so finicky when people install specific drivers for these controllers. Those drivers replace the standard macOS one, and as a result OpenEmu cannot access the controllers properly.

**Comment by aalarie** [comment]
Just did a new test, I think this is in fact a bug in OpenEmu. If I try to connect all 3 controllers when OpenEmu is closed, then all 3 pair. But if I do the same when OpenEmu is opened, then only two will  connect as described in the bug.
