### ISSUE TITLE
Possible UI redesign

### ISSUE THREAD

**Issue by dotvhs** [OpenEmu/OpenEmu#3852]
I just wanted to say thanks for OpenEmu and all your hard work, I really appreciate that. Having this comfortable old-school gaming center is really awesome.

I wonder if design refreshment is in your future plans somewhere. If yes, perhaps something I was working on in my free time might be used:
![](https://user-images.githubusercontent.com/681416/51793074-12d41280-21bb-11e9-8f58-d46e331b6b58.png)
I can upload version 2x if it's needed.

I also recreated most of the console icons (200% zoomed in, originals are vectors):
![](https://user-images.githubusercontent.com/681416/51792923-a48e5080-21b8-11e9-8784-427831f2cdc7.png)

Any feedback is welcome, sorry if this is not the best place to share this.

**Comment by robotoad** [comment]
Eventually, we'd like to use native controls and move away from custom theming. Not only would that eliminate some maintenance costs, it would give the user a degree of control over how they want the app to look.

With regards to your design, I'm not a fan of stripping the color out of the sidebar icons. I think it takes away their charm and removes visual distinction. Consider how easy it is to tell at a glance the difference between the current Atari 2600, 5200, and 7800 icons compared to the monochrome versions.

Currently, there's no UI refresh planned beyond the use of native controls, so I'm going to close this issue, but feel free to visit our Discord and share more ideas.
