### ISSUE TITLE
No option to remove fast forward/rewind notifications

### ISSUE THREAD

**Issue by IronInfidel47** [OpenEmu/OpenEmu#3854]
I've been trying to record things like a no-coin run of old Mario games but the notification in the top left introduced for fast-forwards and rewinds will make the editing a major pain. Is there any way a feature can be added to make these notifications optional?

**Comment by clobber** [comment]
Run the following command in Terminal.app:
`defaults write org.openemu.OpenEmu OEShowNotifications -bool NO`
