### ISSUE TITLE
CXBX unresponsive to keyboard input

### ISSUE THREAD

**Issue by MirzaTaimoorBaig** [OpenEmu/OpenEmu#3855]
Summary of issue

So i am new to CXBX... Downloaded it today, and tried to run Read Dead Revolver.. Started emulation  and everything was going fine.. I watched the whole intro and then the games says "PRESS START".. I went to keymapping and mapped START to ENTER..... I applied the changes went back to game... Pressed enter but nothing happened..... The games was fine because the "PRESS START" was continuously blinking with some animation..... I tried mapping different keys but none of them responded.... PLEASE HELP.

I am running the latest release version...

And Windows 10 Home x64 Build 1809

**Comment by clobber** [comment]
Uhhh you are very lost, sonny. This is the repo for OpenEmu, an app for macOS.
