### ISSUE TITLE
Openemu wont open m3u file

### ISSUE THREAD

**Issue by zhuangcorp** [OpenEmu/OpenEmu#3856]
Openemu wont load m3u file

1. Created m3u file referencing cue files
2. cue files, m3u file, and iso files are in same folder
3. drag m3u file into openemu library
4. Game scanner says "done", but nothing is imported into the library

- OpenEmu Version: 2.08
- macOS Version: 10.12.4

<img width="791" alt="screen shot 2019-02-01 at 12 44 35" src="https://user-images.githubusercontent.com/47234983/52101589-a3797b00-261f-11e9-92d4-b0f13abbdeac.png">
<img width="889" alt="screen shot 2019-02-01 at 12 44 47" src="https://user-images.githubusercontent.com/47234983/52101598-aaa08900-261f-11e9-90dc-22df0f82a008.png">

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."

If I had to guess, the contents of your cue sheet are wrong or you have a bad rip of the game. Search for one from "Redump" instead.
