### ISSUE TITLE
Decode img.ecm

### ISSUE THREAD

**Issue by arstyo** [OpenEmu/OpenEmu#3857]
I downloaded PSX ROM for JoJo's Adventure, the files came as .ccd file but the .img file are encoded with .ecm . I tried look at the guide provided by OpenEmu but there are no guide for decode .img.ecm 

If you can please provide a detailed guide 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/28211817/52279321-e2932d80-298b-11e9-88ad-a2ac53209d00.png">

**Comment by clobber** [comment]
Actually follow the ECM guide. It doesn't matter which file extension is ECM'd.

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-an-ecm-or-ape-file
