### ISSUE TITLE
N64 multiplayer speed too fast Mario Kart (4 Players)

### ISSUE THREAD

**Issue by ikoelle** [OpenEmu/OpenEmu#3861]
Hello,

unfortunately I am experiencing problems while running open emu Mario Kart 64 (4 Players) on a MacBook Pro Late 2016 (Mac OS Mojave).

The game speed is way too fast. Playing 2 Players is not a problem.

Can you please help me to solve this issue?

Thank you.

BR

**Comment by clobber** [comment]
>Can you please help me to solve this issue?

Nope.

GLideN64 GPU plugin and/or Mupen64Plus bug. This will improve in a future version of GLideN64. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
