### ISSUE TITLE
SEGA CD The Emulator Could not Load ROM

### ISSUE THREAD

**Issue by Soldier-2Point0** [OpenEmu/OpenEmu#3863]
Summary of issue
SEGA CD games will not load on new Mac OS install
Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Install OpenEmu app
2. Import ROM
3. Import needed BIOS
4. Launch game

# Expected Behavior

1. Game should load

# Observed Behavior
1. Window pops up "The Emulator Could not Load ROM"
2. Only option is to select Ok

# Debugging Information

- OpenEmu Version: 2.0.0
- macOS Version: 10.14.3

Feb  7 17:18:54 Edgardos-MBP OpenEmu[910]: objc[910]: Class IKCGRenderer is implemented in both /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit (0x7fff957ab5f0) and /Applications/OpenEmu.app/Contents/MacOS/OpenEmu (0x10649e7e8). One of the two will be used. Which one is undefined.
Feb  7 17:18:54 Edgardos-MBP OpenEmu[910]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Feb  7 17:27:17 Edgardos-MBP OpenEmu[961]: objc[961]: Class IKCGRenderer is implemented in both /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit (0x7fff957ab5f0) and /Applications/OpenEmu.app/Contents/MacOS/OpenEmu (0x107e8c7e8). One of the two will be used. Which one is undefined.
Feb  7 17:27:17 Edgardos-MBP OpenEmu[961]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug

**Comment by clobber** [comment]
>OpenEmu Version: 2.0.0

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

**Comment by Soldier-2Point0** [comment]
Sorry. it was a typo. I'm fixing the version number now.

**Comment by clobber** [comment]
If your rip doesn't load, you have a bad copy. Download a "Redump" rip from somewhere online. Can't help you beyond that.

**Comment by Soldier-2Point0** [comment]
Does the log i included have any information as to what is going on? This is happening even with newly downloaded ROMs.

**Comment by clobber** [comment]
No, nothing useful in that random log output you copy and pasted. Trash the Genesis Plus GX core plugin file, redownload it in-app and use known "good" dumps of games from "Redump". That's all I can tell you.

**Comment by Soldier-2Point0** [comment]
Thank you for taking the time to help me.

**Comment by clobber** [comment]
They will be found on Archive.org, via google search or just searching their site. Deleting this message after posting but it will still makes it to your inbox.
