### ISSUE TITLE
Diddy Kong Racing crash

### ISSUE THREAD

**Issue by Seanesso** [OpenEmu/OpenEmu#3865]
Hello,

I have been able to play this game all the way to the final, final boss (Wizpig 2) in the Space World. If I try to go through the door to the boss, the screen goes dark and the sound stops. It stays this way permanently. If I close the emulation, I get a message that the game couldn't communicate with the helper. I have tried saving in OpenEmu right before walking through the door, and reloading the save to try to walk through again. I have also tried saving after I've walked through the door. It allows me to save until the music stops and the screen goes dark (it crashes) and then I can't do anything on OpenEmu but close the game. Here are some reports:

OpenEmu Version: 2.0.8
macOS Version: 10.14.3

**Console log:**
16:17:21.741353 -0800	contextstored	Duet: saveObjects async
16:17:22.248905 -0800	configd	processing network kernel events
16:17:22.686111 -0800	Console	trackMouse send action on mouseUp
16:17:23.353717 -0800	contextstored	Duet: saveObjects async
16:17:24.252470 -0800	locationd	CL: kCLConnectionMessageWatchdog
16:17:24.259018 -0800	locationd	CL: kCLConnectionMessageWatchdog
16:17:24.794820 -0800	locationd	CL: kCLConnectionMessageWatchdog
16:17:24.961706 -0800	locationd	CL: kCLConnectionMessageWatchdog
16:17:25.213299 -0800	locationd	CL: kCLConnectionMessageWatchdog
16:17:25.218509 -0800	configd	processing network kernel events
16:17:26.076698 -0800	locationd	CL: kCLConnectionMessageWatchdog
16:17:28.290758 -0800	configd	processing network kernel events
16:17:29.580727 -0800	locationd	CL: kCLConnectionMessageWatchdog
16:17:30.384105 -0800	fseventsd	Resolve user group list
16:17:31.260197 -0800	configd	processing network kernel events
16:17:34.080714 -0800	locationd	CL: kCLConnectionMessageWatchdog
16:17:34.229995 -0800	configd	processing network kernel events
16:17:34.314370 -0800	homed	SecItemCopyMatching
16:17:34.315782 -0800	homed	SecItemCopyMatching
16:17:34.317469 -0800	homed	SecItemCopyMatching
16:17:34.319423 -0800	homed	SecItemCopyMatching
16:17:36.638265 -0800	locationd	CL: kCLConnectionMessageWatchdog
16:17:37.302263 -0800	configd	processing network kernel events
16:17:37.568571 -0800	contextstored	CL: CLLocationManager
16:17:37.569081 -0800	contextstored	CL: CLLocationManager
16:17:40.271726 -0800	configd	processing network kernel events
16:17:41.904442 -0800	OpenEmu	trackMouse send action on mouseUp
16:17:43.241395 -0800	configd	processing network kernel events
16:17:46.211504 -0800	configd	processing network kernel events
16:17:46.954544 -0800	contextstored	Duet: saveObjects async

**Crash file (it won't let me upload it so I'm pasting the text):**
Process:               OpenEmuHelperApp [7621]
Path:                  /Applications/OpenEmu.app/Contents/Resources/OpenEmuHelperApp
Identifier:            OpenEmuHelperApp
Version:               2.0.8 (2.0.8)
Code Type:             X86-64 (Native)
Parent Process:        OpenEmu [7618]
Responsible:           OpenEmuHelperApp [7621]
User ID:               501

Date/Time:             2019-02-18 16:17:29.952 -0800
OS Version:            Mac OS X 10.14.3 (18D109)
Report Version:        12
Anonymous UUID:        8F798E53-898C-E79A-55E5-94FC9F0F4254

Sleep/Wake UUID:       177473A3-BFC1-4C48-AE73-F8CEB31FAEFC

Time Awake Since Boot: 280000 seconds
Time Since Wake:       8100 seconds

System Integrity Protection: enabled

Crashed Thread:        4

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (numVertex == 3), function renderTriangles, file /Users/clobber/Code/OpenEmu/Mupen64Plus/GLideN64/src/SoftwareRender.cpp, line 198.
 

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff7d82717a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff7d8276d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff504a0fde __CFRunLoopServiceMachPort + 337
3   com.apple.CoreFoundation      	0x00007fff504a052d __CFRunLoopRun + 1654
4   com.apple.CoreFoundation      	0x00007fff5049fc64 CFRunLoopRunSpecific + 463
5   com.apple.HIToolbox           	0x00007fff4f736ab5 RunCurrentEventLoopInMode + 293
6   com.apple.HIToolbox           	0x00007fff4f7367eb ReceiveNextEventCommon + 618
7   com.apple.HIToolbox           	0x00007fff4f736568 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff4d9f1363 _DPSNextEvent + 997
9   com.apple.AppKit              	0x00007fff4d9f0102 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1362
10  com.apple.AppKit              	0x00007fff4d9ea165 -[NSApplication run] + 699
11  OpenEmuHelperApp              	0x000000000f73aea0 -[OpenEmuXPCHelperApp launchApplication] + 77
12  OpenEmuHelperApp              	0x000000000f73a540 main + 126
13  libdyld.dylib                 	0x00007fff7d6eded9 start + 1

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff7d82717a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff7d8276d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff504a0fde __CFRunLoopServiceMachPort + 337
3   com.apple.CoreFoundation      	0x00007fff504a052d __CFRunLoopRun + 1654
4   com.apple.CoreFoundation      	0x00007fff5049fc64 CFRunLoopRunSpecific + 463
5   com.apple.AppKit              	0x00007fff4d9f9f89 _NSEventThread + 160
6   libsystem_pthread.dylib       	0x00007fff7d8e1305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff7d8e426f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff7d8e0415 thread_start + 13

Thread 2:: m64pwq
0   libsystem_kernel.dylib        	0x00007fff7d82a7de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7d8e4593 _pthread_cond_wait + 724
2   org.openemu.Mupen64Plus       	0x000000001379b3d9 workqueue_thread_handler + 89
3   org.openemu.Mupen64Plus       	0x000000001379b20e Fake_SDL_New_Thread + 30
4   libsystem_pthread.dylib       	0x00007fff7d8e1305 _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff7d8e426f _pthread_start + 70
6   libsystem_pthread.dylib       	0x00007fff7d8e0415 thread_start + 13

Thread 3:: org.openemu.core-thread
0   libsystem_kernel.dylib        	0x00007fff7d8272d6 mach_wait_until + 10
1   org.openemu.OpenEmuBase       	0x000000000f918ba3 -[OEGameCore runGameLoop:] + 1050
2   org.openemu.OpenEmuBase       	0x000000000f91847c -[OEGameCore _gameCoreThreadWithStartEmulationCompletionHandler:] + 104
3   com.apple.Foundation          	0x00007fff527fc104 __NSThread__start__ + 1218
4   libsystem_pthread.dylib       	0x00007fff7d8e1305 _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff7d8e426f _pthread_start + 70
6   libsystem_pthread.dylib       	0x00007fff7d8e0415 thread_start + 13

Thread 4 Crashed:
0   libsystem_kernel.dylib        	0x00007fff7d82d23e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff7d8e3c1c pthread_kill + 285
2   libsystem_c.dylib             	0x00007fff7d7961c9 abort + 127
3   libsystem_c.dylib             	0x00007fff7d75e868 __assert_rtn + 320
4   mupen64plus-video-GLideN64.so 	0x00000000154fd074 renderTriangles(SPVertex const*, unsigned short const*, unsigned int) + 6052
5   mupen64plus-video-GLideN64.so 	0x00000000154eb6b4 GraphicsDrawer::drawDMATriangles(unsigned int) + 340
6   mupen64plus-video-GLideN64.so 	0x000000001553ff60 F3DDKR_DMA_Tri(unsigned int, unsigned int) + 304
7   mupen64plus-video-GLideN64.so 	0x00000000154d56dc ProcessDList + 2012
8   mupen64plus-rsp-cxd4.so       	0x000000000fbab7e0 DoRspCycles + 128
9   org.openemu.Mupen64Plus       	0x0000000013695fa8 do_SP_Task + 2360
10  ???                           	0x00000000209c207b 0 + 547102843

**Comment by clobber** [comment]
GLideN64 GPU plugin and/or Mupen64Plus bug. This will improve in a future version of GLideN64 and/or Mupen64Plus. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
