### ISSUE TITLE
No cores

### ISSUE THREAD

**Issue by strafe** [OpenEmu/OpenEmu#3866]
Summary of issue

When installing OpenEmu the _"System Cores Installation"_ prompt consists of an empty list, in addition, the `Preferences > Cores` list is also empty. [I've uploaded a video of issue here.](https://streamable.com/hiy01)

It may be worth noting that I previously had OpenEmu installed on this machine when it was running macOS `10.13.6` and this issue was not present.

# Steps to reproduce

1. Install OpenEmu (either through Homebrew or from the GitHub releases page).
1. Run OpenEmu for the first time (through the right-click menu to avoid the codesign warning).
1. Go through the setup process as shown in the video above.

# Expected Behavior

1. Be prompted to install additional cores during setup and see all cores under `Preferences > Cores`.

# Observed Behavior

1. There are no cores listed during setup and the `Preferences > Cores` list is empty.

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.14.3

**Comment by clobber** [comment]
Not an OpenEmu issue. Your machine is blocking outgoing connectings to GitHub -- probably some sort of firewall software you have running.

**Comment by strafe** [comment]
@clobber forgive my ignorance, but how is that possible? I use GitHub.com and GitHub Desktop every day and have never experienced any problems accessing the GitHub domain. Not to mention I have no firewall software running and have the exact same configuration I did when I installed OpenEmu under `10.13.6`.

**Comment by strafe** [comment]
@clobber I have not restarted my machine or reinstalled OpenEmu since my previous post and now all cores are showing up under `Preferences > Cores`, I assure you this is an issue with OpenEmu and not with my system configuration (I now know this because I changed nothing).
![image](https://user-images.githubusercontent.com/15663890/53056496-4f85e780-34a3-11e9-902c-bc64ae0a210d.png)

**Comment by clobber** [comment]
> I assure you this is an issue with OpenEmu and not with my system configuration (I now know this because I changed nothing).

Sounds like you did some debugging and found the line of code that is the culprit? No? :)

Well, since nobody else can replicate this, and the few times that those having similar issues turned out to be network related on their end (GitHub's SSL cert being rejected by their machine, HandsOff/LittleSnitch blocking connections, etc), I'd say it's not conclusive that this is an OpenEmu bug. Glad it works for you now, though.

**Comment by strafe** [comment]
That's fine, I understand I haven't offered anything constructive towards the origin of this problem but I have not once had any certificate-related network issues with GitHub or other domains.

**Comment by clobber** [comment]
It's odd that you won't allow for the possibility of a momentary DNS hiccup or other network-related issue. Our software has been downloaded over 11 million times so if this was an OpenEmu bug, I'd hope it would have been widely documented by now!

**Comment by robotoad** [comment]
@strafe We can't replicate your issue. Nailing down an intermittent networking-related issue like this is practically impossible, but I doubt it's an OpenEmu issue. It could have been an arbitrary DNS hiccup that prevented fetching of the cores at that moment or countless other networking-related issues.
