### ISSUE TITLE
Game won't add

### ISSUE THREAD

**Issue by Ponmon64** [OpenEmu/OpenEmu#3867]
I have been using OpenEmu for about 6 months now, and have never run into any major issues until now. Whenever I try to add a game to Drag and Drop, or add to Library, nothing will happen at all. I first discovered this when trying to add Wipeout to my library. This has occurred with multiple games thus far, and I've seen no clear answer. I want to know if there is any solution other than just deleting OpenEmu and starting again from scratch

**Comment by clobber** [comment]
Read https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games
