### ISSUE TITLE
Resident Evil 2 Disc Problem (M3U Not Working)

### ISSUE THREAD

**Issue by KayKuli99** [OpenEmu/OpenEmu#3869]
I am having trouble getting the M3U to work on OpenEmu to play Resident Evil 2. I look at the instructions about the multi disc's and looked on different Reddit threads but I can't seem to fix the problem. Even when I create an m3u file it won't register on OpenEmu, am I doing something wrong? Do I have the right files? If it is possible, can someone use some screenshots to guide me through the process? 

<img width="882" alt="screen shot 2019-02-22 at 11 47 46 am" src="https://user-images.githubusercontent.com/40073529/53257257-b10ea780-3697-11e9-8ace-52a1d84010cd.png">

<img width="766" alt="screen shot 2019-02-22 at 11 47 06 am" src="https://user-images.githubusercontent.com/40073529/53257211-9b00e700-3697-11e9-9051-afe840fa4e46.png">

OpenEmu: V.2.0.8
Mac: Mojave 10.14

**Comment by clobber** [comment]
If it's not working, you've done something wrong so **read** the guide closely.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."

**Comment by zach933** [comment]
Anyone ever find an answer to this? Seems like a pretty valid question
