### ISSUE TITLE
Bluetooth connection Dualshock3 Sixaxis

### ISSUE THREAD

**Issue by raizzz35** [OpenEmu/OpenEmu#3871]
I am trying to connect PS3 controller in bluetooth with OPenEmu. My iMac recognize my controller in bluetooth but not OpenEmu. I have to plug the controller in USB to play. So I think there is something to configure in preference OpenEmu. I have already try this : User guide: "DualShock Controller Pairing" but no issue... I really like OpenEMu but I can't play with wired USB connection. Does antonyme know the magic way to fix that ? Thank you for your help :))))

**Comment by clobber** [comment]
The official PS3 DualShock 3 works and pairs just fine. Nothing needs to be “configured” with OpenEmu. Follow the guide — cannot help you beyond that.
