### ISSUE TITLE
Way to access previous versions

### ISSUE THREAD

**Issue by Dale-Pickle** [OpenEmu/OpenEmu#3872]
Hello, I was just wondering if there was a way I could revert back to an older version of OpenEmu. There are some files which I am trying to use to get certain games to work through the system which I have been told work on a previous version of OpenEmu, but not the current updated version that I have.
Thank you

**Comment by clobber** [comment]
Very vague here. There is no reason a game would work with an older version and not the latest. Sorry, you have been misinformed and we do not support older versions.
