### ISSUE TITLE
Cheat Codes on Pokemon White 2

### ISSUE THREAD

**Issue by OMEGAYAY** [OpenEmu/OpenEmu#3874]
I installed a cheat to get a pokemon  named bronzor. The cheat worked, then I deselected the cheat to stop the cheat from occuring. But when I went to find more pokemon the Bronzor cheat was stil in affect even though the cheat was deselected. I tried reseting my game four times and tried saving and getting out, but that didn't work. So my question is how I get the cheat to stop working?

Here is the cheat: 94000130 fffb0000
b2000024 00000000
c0000000 0000002f
10036b04 000001b4
dc000000 00000004
d2000000 00000000

And I am doing this on a macOS Mojave Version 10.14.2

**Comment by clobber** [comment]
DeSmuME has bugs with Action Replay cheat codes as well as issues handling the Pokemon games in the first place, which they note are unsupported. You can do nothing about this. Perhaps some of the cheat bugs will be resolved if their next version is ever released.

Also:

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) page is pretty clear on issues with NDS games.

**Comment by OMEGAYAY** [comment]
What is DeSmuMe?

**Comment by clobber** [comment]
>What is DeSmuMe?

...the reason you are able to play an NDS pokemon game in the first place: the emulator core plugin. OpenEmu is not the emulator.
