### ISSUE TITLE
High CPU usage with OpenEmuHelperApp

### ISSUE THREAD

**Issue by chrisdeeming** [OpenEmu/OpenEmu#3875]
Summary of issue

Sometimes after closing a game, OpenEmuHelperApp continues to use high CPU. On at least one occasion I've found OpenEmuHelperApp running several days after last using OpenEmu, causing performance issues.

# Steps to reproduce

Play a game, exit game, look at Activity Monitor.

# Expected Behavior

# Observed Behavior

The CPU usage of the helper app seems disproportionately high compared to other apps.

# Debugging Information

- OpenEmu Version: v2.0.8
- macOS Version: 10.14.3

![image](https://user-images.githubusercontent.com/2158514/53303041-99811b80-385d-11e9-8c90-f3cbcb294925.png)

I appreciate this report is slightly lacking in detail. I am happy to provide more information if the issue persists. The helper app seems to have shut down while typing this, but if you let me know what information is useful when the issue is occurring I'll report back when it happens again.

**Comment by clobber** [comment]
This would be happening from a crash playing an N64 game. We already have an issue open for this here: https://github.com/OpenEmu/Mupen64Plus-Core/issues/28
