### ISSUE TITLE
trouble with reloading save files

### ISSUE THREAD

**Issue by OMEGAYAY** [OpenEmu/OpenEmu#3880]
Okay so I was playing pokemon, so I clicked a wrong button and It brought me all the way back to near the begining, so I looked at my save progress but I couldn't find my recent saved one. I have been quick saving along the way, so IDK why it did that. Like i am so mad because I did a lot of progress and I really don't want to start over.

**Comment by clobber** [comment]
"Quick saves" do not persist between launches/restarts/loads of other save states. There is no way to get your progress back after having done any of those actions. Instead, you should either rely on in-game battery saves or "manual" save states alone.

**Comment by OMEGAYAY** [comment]
I am almost back to my original game data, but thanks for the info :)
