### ISSUE TITLE
Joystick on controllers not working in game on Open Emu

### ISSUE THREAD

**Issue by tushman** [OpenEmu/OpenEmu#3881]
I've tried multiple controllers now and am having the same issue with all of them (Ps3 and Ps4).  The joysticks work when I'm in edit game controls but once I try to play the game they don't do anything.  Every other button works and I've tried unplugging and switching out and redoing the game controls multiple times now with no luck.  I've been playing with my old ps3 controller for weeks with no issue until today.  Any help would be greatly appreciated as I'm halfway through FFIX and don't want to have to walk with the D-Pad the rest of the game.  Thank you.

**Comment by clobber** [comment]
Not an OpenEmu bug here. I have both of these devices and the analog sticks work just fine. With PS1 games, you need to be aware that not all games supported analog and for some you need to press the "analog mode" toggle in order to enable.

**Comment by tushman** [comment]
> Not an OpenEmu bug here. I have both of these devices and the analog sticks work just fine. With PS1 games, you need to be aware that not all games supported analog and for some you need to press the "analog mode" toggle in order to enable.

Wow, I am very stupid, thank you so much.
