### ISSUE TITLE
yeah why isn't it for windows?

### ISSUE THREAD

**Issue by rayconxe** [OpenEmu/OpenEmu#3882]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by MaddTheSane** [comment]
Because it uses Mac-specific APIs for the user interface.

**Comment by mrvacbob** [comment]
There's always Retroarch.
