### ISSUE TITLE
Couldn't Communicate With Helper Application

### ISSUE THREAD

**Issue by faza96** [OpenEmu/OpenEmu#3884]
Summary of issue

I just downloaded an old version of open emu downloaded a rom of super mario world for Snes watched a few videos to make sure i was doing it right. My setup is A wireless xbox one controller connected with a micro usb. I have already set up the drivers and config for the snes controller and now when i open super mario world form the snes tab it says "Couldn't Communicate with helper application

- OpenEmu Version: 1.0.4
- macOS Version: 10.10.5

**Comment by clobber** [comment]
Not sure why you think an old software release from 2014 would still be supported. Really strange.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
