### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by shakespeare1142** [OpenEmu/OpenEmu#3886]
i moved all my roms to the trash and now all my saves are gone accidentally what do i do

**Comment by shakespeare1142** [comment]
where can i find my battary saves and save states

**Comment by shakespeare1142** [comment]
I'm freaking out they have to be somewhere i just can't find there location, i have my roms a bios files though

**Comment by shakespeare1142** [comment]
oh my god now everything is just not functioning

**Comment by shakespeare1142** [comment]
i redownloaded it and now i don't have any cores i have no clue what is wrong

**Comment by clobber** [comment]
Deleting games through the UI also deletes any associated save states. As for the rest of your inane panic: sorry, I'm not going to troubleshoot whatever you broke or some misunderstanding you are having on your end.
