### ISSUE TITLE
No games will display. (White screen)

### ISSUE THREAD

**Issue by corsair** [OpenEmu/OpenEmu#3888]
Hello there,

When attempting to launch any Gameboy games, the emulator window will appear, but will remain as a white screen. I've attempted three different Gameboy Color games all to the same effect, in addition to a Game Boy Advance game.

Additionally, the emulation window appears to lock up and ignore further user actions including attempts to close it.

Thank you for your time.

![image](https://user-images.githubusercontent.com/1847891/54099381-38d20280-4376-11e9-8f12-2cd9164bfbfb.png)

These are some lines copied from Console.
``Mar 10 20:46:28 Anchor OpenEmu[82905]: objc[82905]: Class IKCGRenderer is implemented in both /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit (0x7fffac9dc5f0) and /Applications/OpenEmu.app/Contents/MacOS/OpenEmu (0x1007a57e8). One of the two will be used. Which one is undefined.
Mar 10 20:46:29 Anchor OpenEmu[82905]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
``
``27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 5041 vs 8202, 513, <private>``

# Steps to reproduce

1. Launch any game.

# Expected Behavior

Game launches properly and displays the expected output.

# Observed Behavior

Upon launching any game, the emulator display area will be completely white. Also attempting to relaunch the game will not have any effect.

After launching the game, I am also unable to close this window. Even clicking on Stop/Quit will be ignored. I am forced to force quit OpenEmu to get any windows to disappear.

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.14.3 (macOS Mojave)

**Comment by clobber** [comment]
Haven't given enough to go on (random copy and pasted Console output is useless -- could use the lines from as it actually happens), but sounds likes the core plugins crashed. **First** try games in the Homebrew tab, especially ones in the Game Boy Advance section and see if those work.

**Comment by corsair** [comment]
Sorry for the lack of logs or output. I wish it would crash fully as to provide a full log, but sadly that hasn't been the case. I just attempted to run "Spout" via the Homebrew tab and it resulted in the same issue.

![image](https://user-images.githubusercontent.com/1847891/54156631-e2130a00-4403-11e9-852d-4f3462804070.png)

Here is 100% of the Console logs from the moment of attempting to launch the game:
https://pastebin.com/VYESiMXX

**Comment by clobber** [comment]
There is nothing useful in that log -- it's just TCP traffic. You should filter Console.app for "openemu" and then retrieve output as you try to launch and close a game.

**Comment by corsair** [comment]
```default	13:55:49.748686 -0700	OpenEmuHelperApp	Current system appearance, (HLTB: 2), (SLS: 1)
default	13:55:49.752338 -0700	OpenEmuHelperApp	Post-registration system appearance: (HLTB: 2)
error	13:55:49.755207 -0700	OpenEmuHelperApp	Unable to load Info.plist exceptions (eGPUOverrides)
default	13:55:49.790976 -0700	OpenEmuHelperApp	parent application is: OpenEmu
default	13:55:49.793108 -0700	OpenEmuHelperApp	IOHIDDeviceClass::start: elementCount=16 reportHandlerCount=5
default	13:55:49.793134 -0700	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=0 *buffer=7f813d007430 *count=16 size=1536
default	13:55:49.793222 -0700	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=1 *buffer=7f813bf1cda0 *count=5 size=480
default	13:55:49.793656 -0700	OpenEmuHelperApp	IOHIDDeviceClass::start: elementCount=3 reportHandlerCount=1
default	13:55:49.793680 -0700	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=0 *buffer=7f813bd4f4e0 *count=3 size=288
default	13:55:49.793704 -0700	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=1 *buffer=7f813bd4f640 *count=1 size=96
default	13:55:49.794052 -0700	OpenEmuHelperApp	IOHIDDeviceClass::start: elementCount=17 reportHandlerCount=5
default	13:55:49.794078 -0700	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=0 *buffer=7f813c82be30 *count=17 size=1632
default	13:55:49.794180 -0700	OpenEmuHelperApp	IOHIDDeviceClass::buildElements: type=1 *buffer=7f813bd50320 *count=5 size=480
default	13:55:49.797307 -0700	OpenEmuHelperApp	Found Device 0x7f813bd4f730: Corsair Gaming MM800 RGB POLARIS
default	13:55:49.799088 -0700	OpenEmuHelperApp	Found Device 0x7f813bd50230: Corsair Gaming K95 RGB PLATINUM Keyboard
default	13:55:49.818166 -0700	OpenEmuHelperApp	Found Device 0x7f813bf1caf0: Corsair Gaming SCIMITAR PRO RGB Mouse
default	13:55:49.874988 -0700	OpenEmu	SETUP DONE.
default	13:55:49.917742 -0700	OpenEmuHelperApp	Rate change 0.000000 -> 1.000000
default	13:55:49.965767 -0700	OpenEmu	Display's nominal refresh rate is 59.94 Hz
default	13:55:50.844113 -0700	OpenEmu	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 5245 vs 8390, 513, <private>
```

**Comment by clobber** [comment]
Nothing there, that isn't surprising. Try switching filters if you're not using Nearest Neighbor or Pixellate. Also close down all other apps to try to narrow down if there is a conflict. Also try a machine restart. I've seen issues on Mojave with other apps running that are using GL that will cause video to not render in our app. As it stands now, we cannot replicate your problem.

**Comment by corsair** [comment]
I'll restart shortly and attempt to run it with no other applications running. I have three monitors attached, but not sure if that could be a potential issue.

If it continues to occur, I will get a video of it posted shortly. Sorry for the trouble thus far with this issue.

**Comment by clobber** [comment]
Yes, a restart at this point would be the best course of action. Narrowing down a problem with specific hardware (such as multiple monitors) or application is also recommended. A video of the app displaying a white screen isn't going to be useful to us, though.

**Comment by corsair** [comment]
Seems to be working well after a restart. The good ole' turn it off and back on. I'm going to self-close this issue, but may reopen it if the issue occurs again due to some kind of conflict with other applications.

Thanks for your time. @clobber

**Comment by oc329** [comment]
Also try pressing the delete button if this happens all of a sudden while playing. The delete button controls the lid button for OpenEmu and toggles the screen being white. I just fat fingered it myself.
