### ISSUE TITLE
OpenEmu adding GameGear games to Aracde list

### ISSUE THREAD

**Issue by Nassonadam** [OpenEmu/OpenEmu#3889]
I'm trying to add my games back into OpenEmu after moving back to High Sierra from Mojave(Mojave is a broken mess) so I pulled the files form HD->User->Library->Application Support->OpenEmu->Game Library->roms and when i try to add them to OpenEmu they add just fine but they get added to the wrong core(Arcade) thus not playable.

SYSTEM
MacOS High Sierra 10.13.6
Mac Mini (Late 2014)
2.6 i5

OPENEMU v2.0.8

Thanks in advance for the help

**Comment by clobber** [comment]
Games that are not detected to belong to any system *usually* correctly end up as "Arcade". This means that whatever you're trying to import (don't know, because you provided no details) is invalid and not actually a Game Gear ROM.

**Comment by Nassonadam** [comment]
It’s the entire library. It was already imported into game gear from which I too then.

**Comment by Nassonadam** [comment]
And why did you close it nothing has been resolved???

**Comment by Nassonadam** [comment]
And why did you close it nothing has been resolved???

**Comment by clobber** [comment]
Sorry, there's no import bug here. I won't be able to help you. Next time instead of wiping out your install and reimporting games, simply back it up and copy it over.
