### ISSUE TITLE
Steam will stop DS4 Controllers from working with OpenEMU

### ISSUE THREAD

**Issue by norahqueen** [OpenEmu/OpenEmu#3891]
The problem can be fixed by closing Steam, turning off the controller manually by holding down the PS button until the lightbar switches off and then pressing it again to turn on and reconnect. Suggest this be added to the "Troubleshooting: Input problems" page on the wiki. Controller appears within OpenEMU settings and can be set as the input device but won't work in game or when attempting to modify controls. Just closing Steam does not fix issue, must reconnect controller.

Edit: As well, the ability to dual-set an input would be nice. For example, when using the DS4 with PSP, it would be nice to have the ability to set the triggers (L2&R2) to repeat the action of one of the face buttons. 
Edit 2: I see on issue #1037 that double setting a control is intentionally left out as part of the 'it just works' philosophy, but is it possible to be added as a Secret setting for those of us who are a little more tech-minded and would like to use this feature.

**Comment by norahqueen** [comment]
As well, the ability to dual-set an input would be nice. For example, when using the DS4 with PSP, it would be nice to have the ability to set the triggers (L2&R2) to repeat the action of one of the face buttons.

**Comment by clobber** [comment]
Thank you, Steam has been added to the list of applications in the input troubleshoot wiki.
