### ISSUE TITLE
Quitting during full screen emulation leaves snapshot in front of everything

### ISSUE THREAD

**Issue by ActionPackedJack** [OpenEmu/OpenEmu#3893]
I was emulating Streets of Rage 2 on the Genesis on a Macbook Pro.  I pressed command-q with the emulator running in full-screen.  I was first asked to confirm I wanted to quit the application.  I said yes.  I was then asked if I wanted to stop emulation.  I said yes.  The Streets of Rage 2 image remained on my screen.  I tried to force quit OpenEmu but it was not on the list of open applications.  And my computer was not frozen, because I could tell by my touch bar that even though I couldn't see anything, I was able to tab between iTunes and Chrome.  I had to force shut down my computer to make the screen go away.

<img width="1680" alt="Screen Shot 2019-03-23 at 12 45 24 PM" src="https://user-images.githubusercontent.com/3644884/54869740-0e674880-4d6b-11e9-8447-53028f15ae63.png">

**Comment by clobber** [comment]
Version? We ask for this information for a reason.

**Comment by ActionPackedJack** [comment]
Ah, right, sorry.  2.0.8

**Comment by clobber** [comment]
Cannot replicate this while playing a Genesis game in fullscreen in either windows (popout or library'd). If there is a crash log, a way to replicate this problem or more details then you will have to provide them.

**Comment by clobber** [comment]
Cannot replicate with OpenEmu 2.1 on macOS 10.14.6
