### ISSUE TITLE
My keyboard is not working

### ISSUE THREAD

**Issue by TheYellowBacon** [OpenEmu/OpenEmu#3894]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
How about actually reading the guide as the issue template directed?

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
