### ISSUE TITLE
Cannot import multi-disc game

### ISSUE THREAD

**Issue by brando3733** [OpenEmu/OpenEmu#3896]
Cannot import final fantasy 8 if my life depended on it.I followed https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games to a T.Still to no avail.

1.Created folder in documents added all 4 disc .cues and .bin 

2.created .m3u plain text with textedit adding just .cue files.
![Screen Shot 2019-03-27 at 4 12 39 PM](https://user-images.githubusercontent.com/49003514/55109102-65428a00-50ab-11e9-80d2-80db9f53d3cf.png)

Adding the whole folder that all these files are in allows them to import but still prompts the m3u error in openemu.Does nothing dragging only m3u file.

![Screen Shot 2019-03-27 at 4 17 33 PM](https://user-images.githubusercontent.com/49003514/55109311-e4d05900-50ab-11e9-941c-8e1fe3486d10.png)
![Screen Shot 2019-03-27 at 4 18 19 PM](https://user-images.githubusercontent.com/49003514/55109339-02052780-50ac-11e9-95e4-218af61d84ef.png)

![Screen Shot 2019-03-27 at 4 19 47 PM](https://user-images.githubusercontent.com/49003514/55109415-34af2000-50ac-11e9-924a-7112cd1ad12f.png)

If anyone could think of any ideas on what I could be doing wrong please share,I've been at this for over an hr 1/2.

                                                                               Thank you.

**Comment by clobber** [comment]
>Adding the whole folder that all these files are in allows them to import but still prompts the m3u error in openemu.Does nothing dragging only m3u file.

Yeah...no, you didn't actually follow the guide. No where does it say to drag the whole folder. Without seeing the output log in Console, I'd guess you have files stuck in the Game Library folder or the games are already imported into your Library and should not be (as the guide states). Another possibility are bad cue sheet files. Beyond that, sorry, I'm not going to help troubleshoot this. It's always user error.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."
