### ISSUE TITLE
 douchebags on here huh?

### ISSUE THREAD

**Issue by brando3733** [OpenEmu/OpenEmu#3897]
No shit the https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games didnt tell me to add the whole folder while importing multi disc based games I tried it after trying the m3u file import and no its not in the game library directory douchbag clobber how about ask before being a prick?

sounds to me you cant answer the question so u lock it what an asshole.

**Comment by clobber** [comment]
Bye :)
