### ISSUE TITLE
Intellivision control overlays

### ISSUE THREAD

**Issue by Tomaskingsley** [OpenEmu/OpenEmu#3898]
Is there a future update which will allow saving individual control overlays for each game? Currently you have to remap all the keys for every game you want to play if you're playing with a standard game controller (as the keys on Intellivision are wildly different for each game). Even just the ability to save multiple configurations would be work. And also the ability to use both game controller and keyboard for a games controls (so that you can keep the numbers 1-9).

**Comment by clobber** [comment]
OpenEmu already respond to both keyboard and gamepad input at the same time. Did you even try?

To answer the rest of your questions:  no — no plans for that.
