### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by hecticfilo** [OpenEmu/OpenEmu#3899]
Hi there,

I've been playing Pokemon Heartgold on OpenEmu for a couple days now until when I saved the game (using the OpenEmu save option instead of the in game save) with OpenEmu's save file option. When opened after saving it has a black main screen. However, the screen does show image of the game where I'm at for a split second when opening the save file and then goes back to being black. I expect this to be resolved so I can actually play the game and have the ability to save games and come back to it. I have OpenEmu version 2.0.8 and my macOS is currently 10.14.3 Mojave. Hopefully this can be resolved quickly, whether it turns out that I can keep the save I currently have or starting over without the worry of receiving this black screen again.

Kind Regards.
![Screen Shot 2019-04-11 at 9 59 16 am](https://user-images.githubusercontent.com/49501297/55921516-7f01d680-5c40-11e9-898d-f5acda3d83fc.png)

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - 
* "Please search before opening a new issue."
* "NDS games (especially Pokemon) may have unsolvable problems related to AP patches or DeSmuME's JIT dynarec. Alternatively, try standalone DeSmuME that has the JIT dynarec off by default which may improve compatibility."
