### ISSUE TITLE
Save statements

### ISSUE THREAD

**Issue by IDKIMAFALURE** [OpenEmu/OpenEmu#3901]
Im using the latest version, and I'm using the ds emulator. Ive been playing Pokemon diamond and reached gym badge 5, until i accidentally loaded one of my save states and I'm now at gym badge 3. is there anyway to revert back to my original game. I even saved the game and hit restart and I'm still back at badge 3. Please help!!!

**Comment by clobber** [comment]
>until i accidentally loaded one of my save states and I'm now at gym badge 3

No. It's gone. You load a save state and that loads everything into memory at the time it was made. That's how save states work. What'd you think was going to happen here?
