### ISSUE TITLE
Max length of ar codes

### ISSUE THREAD

**Issue by karkus56** [OpenEmu/OpenEmu#3906]
Hello, what is the max length of an AR Code?
I have a code that does not fit into the cheat field. Can someone help me pls. 

Background information: 
- OpenEmu Version: 2.08
- macOS Version: 10.14.4
- Pokemon Platin
- All Item AR Code:
94000130 FCFF0000
B2101EE0 00000000
E0000644 00000294
03840044 03840045
03840046 03840047
03840048 03840049
0384004A 0384004B
0384004C 0384004D
0384004E 0384004F
03840050 03840051
03840052 03840053
03840054 03840055
03840056 03840057
03840058 03840059
0384005A 0384005B
0384005C 0384005D
0384005E 0384005F
03840060 03840061
03840062 03840063
03840064 03840065
03840066 03840067
03840068 03840069
0384006A 0384006B
0384006C 0384006D
0384006E 0384006F
03840070 03840087
03840088 038400D5
038400D6 038400D7
038400D8 038400D9
038400DA 038400DB
038400DC 038400DD
038400DE 038400DF
038400E0 038400E1
038400E2 038400E3
038400E4 038400E5
038400E6 038400E7
038400E8 038400E9
038400EA 038400EB
038400EC 038400ED
038400EE 038400EF
038400F0 038400F1
038400F2 038400F3
038400F4 038400F5
038400F6 038400F7
038400F8 038400F9
038400FA 038400FB
038400FC 038400FD
038400FE 038400FF
03840100 03840101
03840102 03840103
03840104 03840105
03840106 03840107
03840108 03840109
0384010A 0384010B
0384010C 0384010D
0384010E 0384010F
03840110 03840111
03840112 03840113
03840114 03840115
03840116 03840117
03840118 03840119
0384011A 0384011B
0384011C 0384011D
0384011E 0384011F
03840120 03840121
03840122 03840123
03840124 03840125
03840126 03840127
03840128 03840129
0384012A 0384012B
0384012C 0384012D
0384012E 0384012F
03840130 03840131
03840132 03840133
03840134 03840135
03840136 03840137
03840138 03840139
0384013A 0384013B
0384013C 0384013D
0384013E 0384013F
03840140 03840141
03840142 03840143
03840144 03840145
03840146 03840147
00000000 00000000
00000000 00000000
D2000000 00000000

**Comment by clobber** [comment]
I think you can have a max of 128 codes chained together. For this multi-line code, you may need to combine them all together with +'s to get it to fit in the field as the UI and our guide says. For example:

94000130 FCFF0000
B2101EE0 00000000
E0000644 00000294
...

Becomes 94000130 FCFF0000+B2101EE0 00000000+E0000644 00000294...

**Comment by karkus56** [comment]
Thx, but I have already tried it on this way, but unfortunately it still does not fit in.

**Comment by clobber** [comment]
Then it would seem you have discovered a hard character limit with the field. No workaround for that.

**Comment by karkus56** [comment]
Ok, Is there a way to split the code?
I've also tried that, but I do not know how the codes are structured and so it does not work well.
Always one half of the items will be deleted when I active one of the Code parts.
