### ISSUE TITLE
error building OpenEmu

### ISSUE THREAD

**Issue by mystuffhere** [OpenEmu/OpenEmu#3907]
Hi, I'm looking to try out the Dreamcast core so I tried to build OpenEmu from https://github.com/OpenEmu/OpenEmu without any luck. I'm not a programmer so don't know what I'm doing really. I'm following the instructions here https://github.com/OpenEmu/OpenEmu/wiki/Compiling-From-Source-Guide. I've downloaded xcode and github desktop, cloned the repository. I open OpenEmu.xcworkspace, make sure the scheme openemu > my mac is selected. Go to product > build for > profiling and when it finishes I get couple of errors. OpenEmu project > Localization > migrate "English.lproj" (Deprecated) and OpenEmu workspace > error > Unable to resolve build file: XCBCore.Buildfile. Anyone know how to resolve these or if it's possible to get it to build? I was using xcode 10.2.1 and I'm on macOS 10.14.4. Thanks.

**Comment by MDanihy** [comment]
Run it a couple of times.  I ran into errors the first time as well, and about the 3rd or 4th compile it went through all the way.  Not sure why, but I just kept re-running the job and it finally completed.

**Comment by clobber** [comment]
Sorry, anything pre-alpha or WIP is strictly unsupported.
