### ISSUE TITLE
error building OpenEmu #2

### ISSUE THREAD

**Issue by mystuffhere** [OpenEmu/OpenEmu#3908]
Please, I'm just looking to elaborate on some things. As, I said, i'm not a programmer, but I can't learn anything if my posts get taken down immediately for not meeting specific standards. Why can't it just be left or tagged and I can continue a conversation. I posted on reddit and it didn't even show. I feel like I'm struggling to step lightly around you're temperment just to find out something.

So pre-alpha is strictly unsupported. ok, fine, but someone in the community may be able to help, if you're unwilling, clobber.

Anyways, does anyone know how to get the Dreamcast core added into stable version of OpenEmu if building a pre-alpha won't work.

Thank you very much.

**Comment by clobber** [comment]
Let it go. It doesn't work yet. It's not ready yet. Please stop asking.

https://github.com/OpenEmu/OpenEmu/issues/3907#issuecomment-486795690
