### ISSUE TITLE
macOS: Using shared/split fullscreen doesn't work; OpenEmu reverts back by itself into a bugged mirrored mode

### ISSUE THREAD

**Issue by jatenk** [OpenEmu/OpenEmu#3911]
Summary of issue

# Steps to reproduce

1. Open a game in fullscreen or windowed (console doesn't matter as far as I can see)
2. Launch macOS' Mission Control (through keyboard shortcut or by dragging a window to the top of the screen)
3. Drag the game's window or screen next to another fullscreen app to create a shared (split) fullscreen
4. The system's expected animation happens

# Expected Behavior

1. OpenEmu's window resizes itself according to the space it is given (if the border between both fullscreen apps is dragged, OpenEmu needs to be able to resize again) - there will be big black bars above and below the game's content, more or less depending on the allocated screen space and the game's aspect ratio
2. If OpenEmu is the active app, the game can be played and controlled as usual while the other also visible app can be observed (in my case, a VLC video playing - can also be a YouTube video played in fullscreen, to name examples for potential uses)
3. If OpenEmu is the inactive app but still visible, the expected behaviour for OpenEmu being inactive happens
4. OpenEmu still recognizes that it is in fullscreen, so the fullscreen mode can be exited (and re-entered) as before

# Observed Behavior

1. Once the system's shared fullscreen setup animation is complete, OpenEmu drops out of the fullscreen to the desktop screen it came from, the other fullscreen app reverts to using up the entire fullscreen
2. ...but it is still in fullscreen mode, so without window borders or controls (since there's no "top of the fullscreen" the mouse can go to to reveal the window controls), and also no mouse-movement-controls appearing
2.b Sometimes, the game will take up the entire desktop screen (with only the dock and menu bar still visible) - but other times, it will be the size of half the fullscreen it was supposed to be in shared fullscreen. I can't reproduce what it turns out to be.
3. This mode can only be exited by quitting the game through the cmd+w (or cmd+q) keyboard shortcut.

! - If OpenEmu is in fullscreen and another app window/fullscreen is being dragged into it, the same behaviour occurs except for the windowed-mode frame and control (the x in the top left corner) being visible at the top of the window.

This is fully reproducible - shared fullscreen simply does not work with OpenEmu, which is quite a shame, because I'm on a 27'' screen which is large enough to allow for both a game and a video being played side to side without being too small to enjoy both.

# Debugging Information

- OpenEmu Version: 2.0.8 (016-g31a4fbf-Release)
- macOS Version: 10.13.6 (17G6030)
- iMac 2011 & MacBook Pro 2011 (same behaviour, same versions)

**Comment by shysaur** [comment]
I can still reproduce this issue in version 2.2.1 only if you use the popout gameplay window. As a workaround, do not use it.

This issue has been fixed for the next release in commit bc2c9d3d.
