### ISSUE TITLE
Issue with Keyboard Input for SOTN

### ISSUE THREAD

**Issue by megutron** [OpenEmu/OpenEmu#3912]
My keyboard input is suddenly not recognized when playing Castlevania SOTN. It was working perfectly fine with absolutely no issues before. I briefly tabbed out of the game to check something else, came back to it shortly after and could not do anything. I've tried restarting the emulation, restarting the application multiple times, closing applications in your troubleshooting guide, restarting my computer, and nothing is working. I have tried out some of the GBA games I have saved and there are no issues with keyboard input there and I can play those games just fine (Edit: I have now tried every other ROM I have installed in OpenEmu and they all work perfectly). As I am not tech savvy, I have no idea what to do right now to continue playing this game.

Edit2: I have just tried using my PS4 DualShock controller to see if changing the input would be recognized, but same result; can't get past the start screen now.

- OpenEmu Version: 2.0.8 
- macOS Version: 10.14.4

**Comment by clobber** [comment]
If "Always pause gameplay when in background" is ticked in OpenEmu > Preferences > Gameplay then I can see why switching focus would cause your game to pause, but this would only be for the duration of the OpenEmu gameplay window being in the background. The moment you switched back to it, the emulation would resume. I played through Castlevania SOTN (PS1 version) on OpenEmu and experienced no issue like this, even having made 170 save states -- so this is nothing I can replicate. If you restart emulation with the game open or launch the game without restoring from an autosave state, it should certainly run but I don't know how you'd been saving your progress. Beyond this, sorry, there isn't much more I can tell you.
