### ISSUE TITLE
Donkey Kong 64 : Banana Fairy unphotographable

### ISSUE THREAD

**Issue by OlivierLanglet** [OpenEmu/OpenEmu#3916]
Hello !

In DK64 there is a sidequest to photograph 20 banana fairies found all over the 
game.

In the level Gloomy Galleon, there is an underwater shipwreck that can be 
entered by Tiny, and a banana fairy is closed behind bars in a prison 
cell-style sealed room with no possibility of entering.

Normally you are able to photograph the fairy through the spacing between the 
bars(the bars themselves are one big flat texture with transparency between 
them where the spaces occur).

While it is possible to clearly see the fairy through the gaps, 
there is no detection of a 'clear view'. The photo camera has a "smiley" that 
stays red when the fairy is not in proper view, and turns green when the cam is 
centered on the fairy. That face never turns green and any attempts to take the photo fail.

As the room is designed to not be entered, there is no way to take the photo.

If anyone has a solution, I would be extremely grateful !

Thank you by advance !

Olivier

**Comment by clobber** [comment]
GLideN64 GPU plugin and/or Mupen64Plus bug. This may improve in a future version of GLideN64 and/or Mupen64Plus. Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
