### ISSUE TITLE
Playstation Analog mode problems

### ISSUE THREAD

**Issue by colson97** [OpenEmu/OpenEmu#3917]
When I was activate analog mode on, The analog sticks, the buttons, and the left/right trigger didn't responded to the gameplay! Will you fix this analog mode issue?

# Debugging Information

- OpenEmu Version: v2.0.8
- macOS Version: 10.14.4

**Comment by clobber** [comment]
Nothing to fix. You have a misunderstanding of what that button is for.

https://en.wikipedia.org/wiki/Dual_Analog_Controller

>If a PlayStation game is DualShock or Dual Analog compatible, the player may press the Analog button located between the two analog sticks to activate the analog mode. This is indicated by a red LED. If the Dual Analog controller is switched to analog mode while using a game which is not analog-compatible, the game will not register any button presses or, in some cases, the PlayStation will consider the controller to be detached.

**Comment by colson97** [comment]
I am using a PS4 Dualshock 4 controller and I pressed a PS button for activating analog mode.

**Comment by clobber** [comment]
For *which game*? Stop being vague, start clarifying your issue. This is a classic [XY Problem](http://xyproblem.info) here. You do not need to press that button for most games, and for others it will break the controls because the game doesn't support it. Understand?

**Comment by colson97** [comment]
Yes, sir. I understood.
