### ISSUE TITLE
How to reset joypad data

### ISSUE THREAD

**Issue by viniciusccarvalho** [OpenEmu/OpenEmu#3918]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

I use 3 joypads to play games, depending on the platform:

1. PS4 Dualshock
2. 8bitdo SF30 (SNES)
3. 8bitdo M30 (Genesis)

Due pairing to switch I had to reset the connection between my M30 and my mac. The computer unfortunatelly reset the name to the generic "Wireless controller" that was the same name of the Dualshock.

Now OpenEmu always associates the Dualshock mapping to the M30 controller, even after renaming it on bluetooth preferences.

Is there a way to remove any joypad association that is stored by openemu, that may help

Thanks

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.14.4

**Comment by clobber** [comment]
Well first off, the 8bitdo mode you use to pair with is wrong. Their "macOS mode" stupidly tries to mimic a PS4 HID profile for some weird reason. To pair: **Power on with START**, not START+A or any other modes.

To completely delete all current mappings:

1. Close the app
2. Navigate to the folder `~/Library/Application Support/OpenEmu/Bindings` (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Delete `Default.oebindings` in the "Bindings" folder.
4. Restart the app.

**Comment by viniciusccarvalho** [comment]
Thank you, only thing to note that indeed START+A bindings it to PS4, but using D-INPUT via START+B and Sync was the way to go.
