### ISSUE TITLE
Game files will not transfer into the "Drag & Drop Games Here" screen a second time

### ISSUE THREAD

**Issue by jd105** [OpenEmu/OpenEmu#3919]
Im on the mac os version of the system, I accidentally deleted one of my games and now it won't re-download back into the library, I've tried deleting the program, the game files and downloading both again, and even downloading a different version my experience with programs is limited

**Comment by clobber** [comment]
You possibly broke your Game Library in some way, and then you made it worse by deleting other files and changing versions of the software. This isn't exactly an OpenEmu problem, and I'm not too interested in troubleshooting this, especially when you have provided zero useful details and there is an older issue closed with the exact same title...

Here's what I'm going to tell you:

1. Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported. -- if you are using anything less than that, I'm not going to help you.
2. Delete or rename your entire Game Library folder.
Found in: `~/Library/Application Support/OpenEmu/Game Library` - (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/)
3. Try and import your game again.
4. Provide exact details on which game will not import.

**Comment by jd105** [comment]
1: I have the latest version of the system (being 2.0.8) 
2: I have deleted the entire game library of the open emu system in finder which has not worked 
3: I have imported all of the games again except the one that will not re-download
4: the game is Final Fantasy Tactics war of the lions on PSP which won't re-download onto the system

PS: I am aware that there was another chat that has resolved this issue, however the steps that I followed didn't work

**Comment by clobber** [comment]
I don't know what you mean by "re-download", perhaps you are using that to mean "re-import"?

>the game is Final Fantasy Tactics war of the lions on PSP

I need *exact* details. Copy and paste the whole filename. Is the file compressed/zipped? If so, you cannot import compressed files for disc-based games such as PSP.

**Comment by jd105** [comment]
After looking at through the website and finding some reviews, it turns out that the files have been corrupted recently by bugs and my Anti malware program identified the program a second time and made the file useless. I have found another website that works and is reliable. I apologise for wasting your time and I hope that this issue doesn't happen again.
