### ISSUE TITLE
Cannot open Sega Saturn  Game even if openemu accept the cue file drag

### ISSUE THREAD

**Issue by fredOnGitHub** [OpenEmu/OpenEmu#3921]
# Summary of issue
Cannot open Game even if openemu accept the cue file drag

# Steps to reproduce
1. at this @ http://www.gametronik.com/site/fiche/saturn/DoDonPachi%2520%2528J%2529/
2. unrar it
3. get XLD with preference option PCM (little indian)
4. convert the .ape to .pcm with XLD
5. change all filename extension .pcm to .wav according the cue file (from Track02.ape to Track13.ape).
I didn't touch Track01.iso

The cue file :

FILE "Track01.iso" BINARY
  TRACK 01 MODE1/2048
      INDEX 01 00:00:00
FILE "Track02.wav" WAVE
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 00:00:00
...
FILE "Track13.wav" WAVE
  TRACK 13 AUDIO
    INDEX 01 00:00:00

6. in final i have Track01.iso, Track02.wav ... Track13.wav
6. drop the cue file into openemu in Sega Saturn
7. see the game's logo added 
8. double click

# Expected Behavior
gaming

# Observed Behavior
"The emulator could not load ROM" message

# Debugging Information
That's ok with a game from emulparadise .mdf with .mds that i have converted with mdf2iso (https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-mdf-and-a-mds-file) and dropped 
 - Sega Saturn BIOS (v1.01 941228 Japan)
 - Sega Saturn BIOS (v1.01a 941115 NA/EU) (https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files)

- OpenEmu Version: 2.0.8 from dmg
- macOS Version: Mojave 10.14.5

**Comment by clobber** [comment]
1. Don't link to ROM download here.

2. You have a bad rip of the game and/or screwed up your conversion. Download a "good" rip of the game by Redump from Archive.org.
