### ISSUE TITLE
Cheats delete themselves upon closing and reopen

### ISSUE THREAD

**Issue by OGDigiRose** [OpenEmu/OpenEmu#3923]
Long Story Short. I have read https://github.com/OpenEmu/OpenEmu/issues/782 and as of today have run into this issue. That was mentioned 5 years ago or so. I am running version 2.0.8 which says it is current in the updater. Am I missing something? Is this project dead?

**Comment by clobber** [comment]
The last message in that thread explains it. No need to open a new one.
