### ISSUE TITLE
OpenEmu Can't Load Rom

### ISSUE THREAD

**Issue by ryost1981** [OpenEmu/OpenEmu#3926]
I've been playing Final Fantasy Tactics for awhile. Yesterday I went to play it and got this message:

![Screen Shot 2019-06-09 at 2 02 06 PM](https://user-images.githubusercontent.com/51538481/59162440-368b5b80-8abf-11e9-92e8-6bb3ec724e0d.png)

I am up to date with my version. 

I am also getting this with all the games I have been playing on every system. Does anyone know what could possibly be going on?

**Comment by clobber** [comment]
Lacking useful info to troubleshoot. Which version of macOS? What’s the output from Console.app as this happens? What does “every system” mean? Please elaborate.

**Comment by ryost1981** [comment]
Just updated to the latest MacOS Mojave.

Im not sure what the output from Console.app is?

I have roms for most of the emulators on OpenEmu. I was getting the same error on all emulators, however yesterday I re-tried and all emulators are working except PSX. I am still getting this error when I try to load Final Fantasy Tactics and Suikoden.

Thanks for any help.

**Comment by clobber** [comment]
Cannot replicate a problem using OpenEmu 2.0.9.1 with the Mednafen 1.22.2 core plugin for "Final Fantasy Tactics (USA)" using a known good dump cataloged by [Redump](http://redump.org/).

The game imports and loads, even after closing and relaunching.

Dump verification via Terminal:
```
cd ~/Downloads/test

test$ ls
Final Fantasy Tactics (USA).bin	Final Fantasy Tactics (USA).cue

test$ find . -name "[!.]*" -type f -print0 | sort -z | xargs -0 md5
MD5 (./Final Fantasy Tactics (USA).bin) = b156ba386436d20fd5ed8d37bab6b624
MD5 (./Final Fantasy Tactics (USA).cue) = d3376d215df27284306a0b13d0a76d2f

test$ curl http://redump.org/disc/55/md5/
b156ba386436d20fd5ed8d37bab6b624 *Final Fantasy Tactics (USA).bin
d3376d215df27284306a0b13d0a76d2f *Final Fantasy Tactics (USA).cue
```

<img width="942" alt="Screen Shot 2019-07-14 at 2 16 16 PM" src="https://user-images.githubusercontent.com/1303132/61188255-fed57d80-a641-11e9-8e5b-e5bfc87873dd.png">
<img width="942" alt="Screen Shot 2019-07-14 at 2 15 17 PM" src="https://user-images.githubusercontent.com/1303132/61188257-039a3180-a642-11e9-9bb3-4aaeaa1597b5.png">

Steps to follow:

* Ensure you have a known good dump of the game -- "Redump" on Archive.org.

* Re-download the Mednafen core plugin.
  1. Close the app
  2. Open `~/Library/Application Support/OpenEmu/Cores`  (Follow guide [here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) to access the hidden-by-default user Library folder.) and delete `Mednafen.oecoreplugin`
  3. Open the app
  4. Go to OpenEmu > Preferences > Cores and hit install for Mednafen.

* If that doesn't resolve it, try launching the game without restoring the autosave at launch. 
    1. In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
    2. Open your game and click "No" when prompted to "Continue where you left off"

* If still not working, get output from Console.app.
  1. [Spotlight search](https://support.apple.com/en-us/HT204014) (magnifying glass in the upper right corner on your screen - it's how one finds files and apps on their Mac). You click it and type Console and press enter.
  2. Filter the search for `OpenEmu` and press enter, click "Clear"
  3. Then try and launch your game and wait for output.
  4. Copy and paste all the console output back here.
