### ISSUE TITLE
Cannot change display mode with mapped key (NDS)

### ISSUE THREAD

**Issue by beachboy88** [OpenEmu/OpenEmu#3927]
When playing a NDS game, the display mode does not change if the mapped button is pressed. When I press the button, nothing happens. All other mapped buttons work, including Quick Save

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

"Next Display Mode" and "Last Display Mode" - the global hotkeys from the Controls menu *and* the mapped "special keys" from NDS Controls Preferences - work just fine here in OpenEmu 2.0.8 with our DeSmuME 0.9.11.1 core plugin. Update your OpenEmu install.
