### ISSUE TITLE
Multiple Controllers not working as input devices in macOS Catalina (10.15) Beta

### ISSUE THREAD

**Issue by sashblue** [OpenEmu/OpenEmu#3928]
Summary of issue

I've tried multiple external controllers with my Mac mini (Late 2018) after upgrading to the 10.15 beta. None of them are recognized by the OpenEmu app.

# Steps to reproduce

1. When opening OpenEmu and launching a game (with any console - I've tried Playstation, N64, GBA, and GBC), both of the external controllers I've paired are not recognized (Steel Series Nimbus and Dualshock 4).
2. When navigating to OpenEmu --> Preferences, under the Controls Tabs, only the Keyboard is listed under Inputs at the Bottom.
3. I have closed and re=opened OpenEMU, deleted and re-downloaded the app, restarted the computer, and reset the Saved Application state of the app itself. The issue persists.
4. Other Bluetooth devices are working, such as my Apple Wireless Keyboard and Mouse. Just no controllers are seen or recognized by the OpenEmu app.

# Expected Behavior

1. When launching OpenEmu and any game, the controllers should both be recognized and allow full control to play the games in my library.

# Observed Behavior

See above.

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.15 Beta (19A471t)
- Steel Series Nimbus Model GC-00004
- Dualshock 4 for PlayStation 4.

![Screen Shot 2019-06-09 at 5 16 22 PM](https://user-images.githubusercontent.com/51538291/59164497-80823a80-8adb-11e9-8fec-ea9dc8ec61c6.png)
![Screen Shot 2019-06-09 at 2 23 58 PM](https://user-images.githubusercontent.com/51538291/59164499-8415c180-8adb-11e9-81ae-7af6479b344e.png)

**Comment by clobber** [comment]
This is likely a 10.15 Beta bug and will go away in a new Beta release. You are beta testing Apple software so report this to Apple first.

https://feedbackassistant.apple.com/

Also a friendly reminder not to use beta releases on your daily driver if you care about stability.

**Comment by kuthair** [comment]
I am having this issue after upgrading to Catalina (final).

I'm using macOS Catalina 10.15.2.

I have two DualShock 4 controllers successfully paired with the OS. I can get 1 or the other to work with OpenEmu but not both at the same time.

I've tried restarting the OS, resetting and repairing both controllers, and reinstalling OpenEmu.

It was working flawlessly before the upgrade to Catalina.

thanks!
-Kuthair

**Comment by clobber** [comment]
@kuthair This issue is not relevant to your problem. Respond here instead: https://github.com/OpenEmu/OpenEmu/issues/4043#issuecomment-564133299
