### ISSUE TITLE
Cheats not working for GBA?

### ISSUE THREAD

**Issue by markuzzthe1** [OpenEmu/OpenEmu#3931]
Hello dudes, im running OpenEmu 2.0.8 on a Mac Mojave 10.14, and i can't find a way to make cheat codes work in pokemon fire red... Is this a common issue or is just me? Because i've looked online on tutorials, reproduced them step by step, and nothing seems to work

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes#gba-cheats
