### ISSUE TITLE
Is there a way to use Atari joysticks (w/USB adapter) to play Atari games?

### ISSUE THREAD

**Issue by mqttro** [OpenEmu/OpenEmu#3933]
# Summary of issue

I would like to use an actual Atari joystick, instead of PS4 controller etc., to play the Atari 2600 games, but unlike in the core Stella, I cannot figure out any way to simultaneously use the joystick while keeping the Select/Start/Difficulty etc. switches mapped to keyboard keys. 

# Steps to reproduce
Go into the controls preferences with an Atari joystick plugged in. It will show up and allow you to map the controls to Up/down/etc., but you cannot map the other switches to anything else.

![Screen Shot 2019-06-12 at 9 44 38 PM](https://user-images.githubusercontent.com/51768947/59397633-4fb03880-8d5b-11e9-9ec1-103736b87c11.png)

# Expected Behavior

I'd like to be able to run a hybrid, as with the core Stella, where I can use the joystick for the core functions while flicking switches via the keyboard.

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.14.4

**Comment by clobber** [comment]
>I'd like to be able to run a hybrid, as with the core Stella, where I can use the joystick for the core functions while flicking switches via the keyboard.

OpenEmu already responds to both keyboard and gamepad input at the same time.

Controls preferences is merely for mapping keys, not selecting which device is "in use" during gameplay.
