### ISSUE TITLE
Issue signing Cg.framework during debug build

### ISSUE THREAD

**Issue by RobertMenke** [OpenEmu/OpenEmu#3935]
## Summary of issue

I've upgraded to the Catalina beta (I completely understand that beta software is not supported by OpenEmu I'm just trying to take a deeper look into #3928). I've loaded the project into Xcode 11 Beta and attempted to build in debug mode. Release builds work as expected, but debug builds fail with the following error:

```
/Users/myuser/Library/Developer/Xcode/DerivedData/OpenEmu-hdchmphbqobawzakhvoxbobvtjvb/Build/Products/Debug/OpenEmu.app/Contents/Frameworks/Cg.framework/Versions/A: bundle format unrecognized, invalid, or unsuitable
Command CodeSign failed with a nonzero exit code
```

# Steps to reproduce

1. Describe step-by-step

- Follow the instructions on the "building from source" wiki (fresh clone + build)
- Open the workspace in Xcode 11 beta
- Attempt to build the project in debug

Brainstorm:

The [Xcode 11 changelog](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_release_notes) indicates the following updates:

CFBundleVersion is required (I verified that CFBundleVersion is present in `OpenEmu/Cg.framework/Versions/Current/Resources/Info.plist`)
> Bundles without a CFBundleVersion are invalid and can’t be properly installed on devices or simulators. CoreSimulator now checks and rejects such bundles earlier in the process with a clearer error message. (49892531)

I'm not entirely sure how to interpret the below issue and it may be entirely irrelevant. I made sure to delete DerivedData, clean the build folder, etc in order to ensure that none of the Xcode 10 output would be corrupting the Xcode 11 build.
> The format of result bundles changed in Xcode 11. A result bundle is an asset produced by Xcode 11 with the xcresult file extension that contains information about the build, tests, code coverage, and more. Any xcresult files produced with Xcode 10 or earlier cannot be read by Xcode 11. A result bundle can be produced by passing -resultBundlePath ./Example.xcresult to an xcodebuild invocation and the Example.xcresult can then be opened in Xcode. Xcode also creates result bundles in Derived Data. The current result bundle version number is 3, which can be specified by passing the xcodebuild flag -resultBundleVersion 3. Version 3 is the default in Xcode 11, but it is still recommended for automation to explicitly pass the flag, so that any potential future versions that become the default do not cause issues to existing tools. Result bundles can be inspected using xcresulttool. A JSON representation of the root object of the result bundle can be exported using xcrun xcresulttool get --format json --path ./Example.xcresult and any nested object, identified by its reference found in the JSON output, can be exported by adding the flag --id REF. xcresulttool also provides the description of its format using xcrun xcresulttool formatDescription. (41633595)

# Expected Behavior

Debug build succeeds from master branch

# Observed Behavior

Debug build fails from master branch due to an issue signing Cg.framework. Note this is only an Xcode 11/OSX Catalina issue. Xcode 10 will successfully compile a debug build.

# Debugging Information

- OpenEmu Version: 2.0.8
- macOS Version: 10.15 beta

**Comment by clobber** [comment]
You could have edited your last ticket instead of closing and opening a new one... let's keep issue/email chatter down to a minimum please.

Anyway, Cg framework is not used in our next release, so we're not going to go out of our way to troubleshoot this for those that don't know their way around Xcode.

As for input not working in 10.15 Beta, it is my understanding that you need to "approve/allow" Input Monitoring in the OS Privacy settings for OpenEmu. This is part of the new security changes coming in 10.15. If that doesn't work, we will have to check it out in some future 10.15 Betas.

**Comment by RobertMenke** [comment]
@clobber thanks for the input and good to know on the next release. I’ll leave this one alone.
