### ISSUE TITLE
Why is toggleable fast forward still not an option after 6 years?

### ISSUE THREAD

**Issue by snowe2010** [OpenEmu/OpenEmu#3937]
After 6 years and many closed issues, there is still no way to toggle fast forward. 

https://github.com/OpenEmu/OpenEmu/issues/2543
https://github.com/OpenEmu/OpenEmu/issues/832
https://github.com/OpenEmu/OpenEmu/issues/95

Instead of locking and closing issues it might be a good idea to explain why this might not be implemented or what needs to be changed for it to be implemented.

**Comment by clobber** [comment]
Outside of scope. Please don’t open issues like this. Surely you didn’t expect a good outcome.
