### ISSUE TITLE
GridView shows blank on launch

### ISSUE THREAD

**Issue by kimbara** [OpenEmu/OpenEmu#3938]
Summary of issue
GridView always shows blank on launch

# Steps to reproduce

1. Have a MacBookPro11,5, 16GB Memory, Intel Iris Pro 1536MB.
2. Install v2.0.8 on the MacBookPro.
3. Launch the app, and import many PlayStation Games.
4. Make sure Grid view is selected, and "Sony Playstation" is selected at the left sidebar.
5. Re-launch the app,

# Expected Behavior
Showing all imported games properly.

# Observed Behavior
The grid view is just the background color of the games view (so it looks like there are no games). Scrolling down a little bit (or resize the window, or change the thumbnail size, any triggers to be redraw the grid view)

, and all games appear properly.  Also, the highlighted item on the sidebar (whichever console I have selected) shows blank.

# Debugging Information
- OpenEmu Version: 2.0.8
- macOS Version: 10.14.5 (18F203)
- screenshot attached;
<img width="1079" alt="OpenEmu-BlankGridView" src="https://user-images.githubusercontent.com/6996761/59586829-c0ba6c00-911e-11e9-8ec5-52de4c5e1808.png">

**Comment by robotoad** [comment]
#3822

This issue should be fixed in the next release.

**Comment by kimbara** [comment]
Awesome, great!  Thanks.

**Comment by kimbara** [comment]
Can I download the latest dev app, to verify the fix?  or should I clone the master, and build the project on my Mac?

**Comment by robotoad** [comment]
Unless you're an experienced developer who can follow the build guide, I strongly recommend waiting for the next version, which is planned to be released this month.

**Comment by kimbara** [comment]
Nice, got it. 
I can't wait!
