### ISSUE TITLE
A new version

### ISSUE THREAD

**Issue by L1cardo** [OpenEmu/OpenEmu#3939]
Are you planning to release a new version since you added so many features? Because I failed building myself, need you to build one.

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by L1cardo** [comment]
I am expecting that the new version contains dolphin-emu.

**Comment by clobber** [comment]
Sorry, no ETA on releases and no new systems are currently planned. Also, please don’t open issues like these here. This is our bug tracker.
