### ISSUE TITLE
2.0.9 breaks controller support

### ISSUE THREAD

**Issue by 2600box** [OpenEmu/OpenEmu#3940]
tested MacOS 10.14.5 using xbox one s (bluetooth) and steam controller (dongle)

2.0.9 does not recognise controllers. showing "no controllers available" despite being connected and working in other games.

downgrading to 2.0.8 restores functionality and openemu works again.

**Comment by clobber** [comment]
Nah, I don’t believe this is possible. There are very few changes in 2.0.9 and none of them input related. Check again.

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by clobber** [comment]
This is fixed in the 2.0.9.1 release.
