### ISSUE TITLE
USB Controller not getting recognized after updating to 2.0.9

### ISSUE THREAD

**Issue by efdevelopersp** [OpenEmu/OpenEmu#3941]
I updated from 2.0.8 to 2.0.9 and after i relauched the OpenEmu my USB controller stopped working and don't get recognized anymore.

I'm on Mojave and the USB controller is from the link below:
https://novaknup.com.br/produtos/joypad-sem-fio-p-ps3-ref-kp-4123/

**Comment by clobber** [comment]
Second report now (#3940), and I **cannot** replicate this on two different machines running 10.14.5 and 10.11.6. OpenEmu 2.0.9 is a minor bugfix release and there were no changes to input code, see for yourself: https://github.com/OpenEmu/OpenEmu/compare/v2.0.8...v2.0.9

What OS are you running?

I'm wondering if this is an issue being compiled against the 10.14 SDK on macOS 10.14.5 with Xcode 10.2.1 - some kind of notarization issue. Does macOS prompt you with OpenEmu requesting access to "control your computer"? Check System Preferences > Security & Privacy > Accessibility.

Also be certain your problem is not actually related to something here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by clobber** [comment]
Update: Tested a fresh OpenEmu 2.0.9 install on a third machine with macOS 10.14.5 that has never had OpenEmu installed before and I still cannot replicate this.

Are you using Hackintosh/non-Apple hardware or old Mac hardware that does not officially support 10.14 Mojave? Any other details you can provide? Can you verify after a reboot?

**Comment by Gruv77** [comment]
My Mayflash f500 USB won't recognize... rolled back to 2.o.8 experimental.

**Comment by clobber** [comment]
@Gruv77 need more details than a "me too"

**Comment by Gruv77** [comment]
> @Gruv77 need more details than a "me too"

Sure.

**Comment by clobber** [comment]
@Gruv77 okay so you weren’t previously on 2.0.8 and not using Mojave either. I don’t think this is an OpenEmu bug in 2.0.9. Check the wiki guide I linked above.

**Comment by pavement714** [comment]
Hi there, I'm a huge fan of the app and really appreciate all your work and the new update. But multiple people (myself included)  are having USB controller issues with the update. I have a Xbox One controller plugged into USB port on Mojave. I tried the experimental build as well. Here is a link to others with issues and you will find more on the reddit group and twitter: https://www.reddit.com/r/OpenEmu/comments/c3lrlf/controller_now_not_recognized/

**Comment by MaddTheSane** [comment]
Can confirm: something broke in the 2.0.9 update: When side-to-side, 2.0.8 shows my Xbox One S controller, but 2.0.9 doesn't show it. I am running Mojave 10.14.5 (18F132).

The console for 2.0.9 says it "found" it, but it doesn't show up. Nor does a game respond to button presses.

Something that might be related: When I connect my BlueTooth controller while OpenEmu is running, then quit OpenEmu, the emulator crashes. Attached are two crash logs.
[Archive.zip](https://github.com/OpenEmu/OpenEmu/files/3316997/Archive.zip)

**Comment by clobber** [comment]
@MaddTheSane Okay... what broke then?
https://github.com/OpenEmu/OpenEmu/compare/v2.0.8...v2.0.9

**Comment by clobber** [comment]
Specifically, if you're checking, see if any of the OpenEmu-SDK changes affect it, although nothing looks suspect to me. Oddly enough, that GitHub compare range isn't showing all the commits. This should be the full list https://github.com/OpenEmu/OpenEmu-SDK/commits/a8d1f06df0d53309a96a05ca2348e3256415310e that 2.0.9 was compiled with.

**Comment by MaddTheSane** [comment]
Based solely on the tags, the changed file [here](https://github.com/OpenEmu/OpenEmu-SDK/compare/fab866fadb2c159a944faf0cebd95a260c4cba29...a8d1f06df0d53309a96a05ca2348e3256415310e#diff-cc06959ae6959f5b0864e8c712ced583) _might_ be causing issues. I'll investigate.

**Comment by Benjammin82** [comment]
Just updated and also having problems with joysticks and joy pads. Some work like PS4 others that previously did like my arcade stick that uses a zero delay usb encoder.

**Comment by pavement714** [comment]
> Just updated and also having problems with joysticks and joy pads. Some work like PS4 others that previously did like my arcade stick that uses a zero delay usb encoder can no longer been seen by openemu. Any ideas how I can go back to 2.0.8?

https://github.com/OpenEmu/OpenEmu/releases/download/v2.0.9/OpenEmu_2.0.8.zip

**Comment by clobber** [comment]
@MaddTheSane Thanks, I was hoping the modern syntax changes wouldn't be a problem but I guess there is a slight chance! Also here are 3 test builds - I'd appreciate if you could try all 3 and report any changes. Sorry if these download a bit slow.

https://transfer.sh/Ym8uq/TEST1.zip

https://transfer.sh/BhcyF/TEST2.zip

https://transfer.sh/GNlZT/TEST3.zip

**Comment by Benjammin82** [comment]
> > Just updated and also having problems with joysticks and joy pads. Some work like PS4 others that previously did like my arcade stick that uses a zero delay usb encoder can no longer been seen by openemu. Any ideas how I can go back to 2.0.8?
> 
> https://github.com/OpenEmu/OpenEmu/releases/download/v2.0.8/OpenEmu_2.0.8.zip

Thanks. I should have been more specific sorry I was using the experimental 2.0.8 as I got some arcade titles working with that version.

**Comment by clobber** [comment]
@pavement714 @Benjammin82 Test the 3 builds I posted above. Let's get this figured out instead of blindly "downgrading".

**Comment by Benjammin82** [comment]
No joy with the test builds sorry @clobber. I appreciate that you want to get it fixed.

**Comment by MaddTheSane** [comment]
Test 1: doesn't detect controller, crashes at quit if controller connected while running.
Test 2: doesn't detect controller, crashes at quit if controller connected while running.
Test 3: doesn't detect controller, crashes at quit if controller connected while running.

**Comment by jb242** [comment]
I'm seeing the same result as @MaddTheSane .

MacBook Pro 2015
macOS 10.14.5

**Comment by Wevah** [comment]
> I'm wondering if this is an issue being compiled with the 10.14 SDK on macOS 10.14.5 with Xcode 10.2.1

It could be; compiling with the 10.14 SDK/Xcode 10.x broke a few things (uncorrupt PDF export) in an app of mine. The OS does sometimes perform some behavior changes based on the SDK compiled against.

**Comment by MaddTheSane** [comment]
I'm opening a new issue with the crash on controller connect, as it is only tangentially related to this issue.

Also, I'm not experiencing the controller-not-found issue on my own build… but only on the computer it is built on.

**Comment by pavement714** [comment]
> @pavement714 @Benjammin82 Test the 3 builds I posted above. Let's get this figured out instead of blindly "downgrading". Be helpful beyond just trying to solve your immediate problem.

i posted my specs on the reddit thread. the guy asked a question so instead of the developer (you) spending time responding that could be used better, i thought i would help. 

btw, i installed all three test builds and they didn't work.

**Comment by clobber** [comment]
@MaddTheSane any change if you revert the modern syntax?

**Comment by clobber** [comment]
To test that theory, here is build TEST4 for everyone to try:

https://transfer.sh/xXlLe/TEST4.zip

**Comment by jb242** [comment]
Test4 restores controller availability for me.

8BitDo M30 over bluetooth.

**Comment by pavement714** [comment]
> To test that theory, here is build TEST4 for everyone to try:
> 
> https://transfer.sh/xXlLe/TEST4.zip

@clobber TEST4 worked for me on Mojave 10.14.6 Beta (18G48f) MBP (15-inch, 2018)

thanks to everyone who helped!

**Comment by clobber** [comment]
>Test4 restores controller availability for me.

>TEST4 worked for me on Mojave 10.14.6 Beta

Wow that's a bit incredible. Still not sure what's going on there, but once @MaddTheSane confirms TEST4 works for him, I will push out a 2.0.9.1 fix. Also, hopefully he gets back to us soon because my laptop has to go to an Apple Repair Center for 1-2 weeks in about 4 hours, hehehe :P

**Comment by Gruv77** [comment]
> @pavement714 @Benjammin82 Test the 3 builds I posted above. Let's get this figured out instead of blindly "downgrading". Be helpful beyond just trying to solve your immediate problem.

@ clobber - I do appreciate the work that's been done with OpenEmu... really, but I just wanted to play some Ms. Pac-Mac with my arcade stick... lol. The "downgrading" was just to get a game in this morning.

**Comment by MaddTheSane** [comment]
Test 4 works for me.

**Comment by clobber** [comment]
@Gruv77 Please, let's not needlessly post responses here... working on solving this now.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/commit/89778c7e78174fecfeec993955ba8bb52836906d

**Comment by clobber** [comment]
Last build for everyone to please try before I push this live: https://github.com/OpenEmu/OpenEmu/releases/download/v2.0.9.1/OpenEmu_2.0.9.1.zip

**Comment by MaddTheSane** [comment]
This fixes the issues on my end.

**Comment by clobber** [comment]
Excellent! Thanks to everyone for reporting and testing.

**Comment by Benjammin82** [comment]
Yep working for me. Much appreciated.

**Comment by clobber** [comment]
2.0.9.1 is available now.

**Comment by clobber** [comment]
Should be fixed for real in https://github.com/OpenEmu/OpenEmu-SDK/commit/63d7d87630a93bbe2a7b35f0c5293de2294a255a
