### ISSUE TITLE
Input doesn't work on macOS Catalina

### ISSUE THREAD

**Issue by vhawley** [OpenEmu/OpenEmu#3944]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Double check input monitoring is enabled (new option in the "Security & Privacy" pane in Catalina).
<img width="780" alt="Screen Shot 2019-06-23 at 4 44 32 PM" src="https://user-images.githubusercontent.com/2441451/59983592-60bc3d80-95d6-11e9-8d04-faeb651251d9.png">

2. Load any ROM from any system
3. Keyboard inputs don't work, and controllers are not recognized in the Controls options.

# Expected Behavior

1. Inputs should be recognized in games and perform actions

# Observed Behavior

1. Inputs are not recognized by any game

# Debugging Information

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.15 betas 1 and 2

**Comment by clobber** [comment]
Please report this to Apple. You are beta testing *their* OS. https://feedbackassistant.apple.com/

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3928, #3932

**Comment by L1cardo** [comment]
I don't think this is an Apple issue .
I can connect my PS4 controller via Bluetooth and I can perfectly use it on other apps.
APP store games work fine , steam works fine , but only OpenEmu is not working with the controller .
