### ISSUE TITLE
Please don't drop non-metal MacOS support :(

### ISSUE THREAD

**Issue by daniel-jozsef** [OpenEmu/OpenEmu#3945]
Apple decided to pull a planned obsolescence move on a lot of perfectly usable Macs.

Personally I see no reason whatsoever to upgrade from my early 2011 MBP with 16 gigs of RAM and then top of the line four core, eight thread mobile i7 CPU. And yet I'm already locked out of MacOS upgrades, and now it seems I'll be locked out of OpenEmu upgrades as well.

Please try to think a bit more like people think in the Linux world, and less like Apple does.

**Comment by robotoad** [comment]
Sorry, but we intend to keep reasonably up to date with the platform. The testing burden, technical debt, and performance issues are too great for us to target hardware nearly a decade old.
