### ISSUE TITLE
Wii classic controller L & R register as constantly pressed triggers most times

### ISSUE THREAD

**Issue by Diamondog36** [OpenEmu/OpenEmu#3947]
Before reading this, let me build some context.

I'm very well aware there have been others, who reported this long before I did and those issues have been closed with no fix possible. But there is a side on this issue that I haven't seen anyone mentioning in their reports, at least in those other issue reports, where the same issue was reported (#3751, #2371, #2556, #2857). Maybe others didn't encounter this, maybe they didn't notice this.
I did mention this on Reddit 2 years ago (AngelusGuy is my Reddit username), right here: https://www.reddit.com/r/OpenEmu/comments/54acf6/classic_controller_triggers_issue/
This post didn't get any replies, thus I don't know if developers know about this detail, so I believe I have to report it here as well.
(If you are a developer, skip to the next paragraph) First of all, it is already known that all mapping issues regarding the Wii Classic Controller come from the way Openemu recognizes the L and R buttons of the controller. Once the user maps those, they appear as "Classic Left Trigger" and "Classic Right Trigger". However, once pressed, Openemu will register them as constantly pressed and no other mappings will be possible after mapping either L, or R. It is unrelated to the system the user is trying to map for, thus these buttons mustn't be mapped anywhere at all if one wants to use the Classic Controller.

**HOWEVER**, at least in older versions that I had tested this more, sometimes these buttons would be mapped on Openemu as "**Classic L**" and "**Classic R**" instead. **If this happens, they work fine and Openemu doesn't register them as constantly pressed. They are perfectly usable in-game in that case**. I couldn't find any way to make them be recognized as buttons intentionally though, because it was a matter of pure luck. I could pull this off by repeatedly disconnecting and reconnecting the Wiimote with the Classic Controller and trying to map it again and again. I haven't been able to reproduce this "workaround" recently in 2.0.9.1, maybe because I didn't try enough times, maybe because I was just unlucky, or because some changes made this occur more rarely, or not occur at all. But I do have a screenshot that proves this can, or at least could happen.
<img width="1280" alt="Screenshot 2019-06-26, 13 27 19" src="https://user-images.githubusercontent.com/36894714/60175186-78383800-981b-11e9-89e4-f87bf0558bc6.png">
In the picture, I tried to remap N64. Openemu had already loaded the old mapping I had saved 2 years ago and I tried pressing L. It changed from "Classic L" to "Classic L Trigger". R works perfectly in-game, because it is mapped as "Classic R" and I confirmed it works even in 2.0.9.1.

Maybe my report is useless, maybe not. I'm not a developer and I can't tell if it indeed holds a key to fixing this or not. It's just a hunch, but I won't neglect to report it, because... who knows?

**My main question is: Is it possible to make Openemu always recognize these buttons as "Classic L" and "Classic R" and not as triggers?**

**Other information**
- OpenEmu Version: 2.0.9.1
- macOS Version: 10.14.5
- Model: Macbook Pro 13'' Late 2013
- CPU: Intel i5 2,6 GHz (Dual-Core)
- GPU: Intel Iris 5100
- RAM: 8 GB DDR3

**Comment by clobber** [comment]
>My main question is: Is it possible to make Openemu always recognize these buttons as "Classic L" and "Classic R" and not as triggers?

No. "L" and "R" on the Wii Classic Controller are analog, unlike the Wii Classic Controller Pro which are digital. Honestly, there are better gamepads out now which you should consider using instead.
