### ISSUE TITLE
Controllers are not working on macOS 10.15

### ISSUE THREAD

**Issue by L1cardo** [OpenEmu/OpenEmu#3948]
Controllers are not working on macOS 10.15 even keyboard.
This issue is the same as #3932 #3934 #3935 #3944
I have learned that you thought this is an Apple beta issue , but I think it is not.

Here are why :
   1. Not talking about controllers, even keyboard is not working .
   2. My PS4 controller works fine on other games, like steam games, retroarch , Mac APP store 
       games.

I know that this has something to do with beta, but I wish that you can figure out what is going on .

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.15

**Comment by clobber** [comment]
>This issue is the same as ...

**Do not** open duplicate issues. I don't know how to be more clear than that and don't appreciate you wasting our time like this.

> I have learned that you thought this is an Apple beta issue , but I think it is not. ...

Your opinion isn't helpful here. How one app functions compared to another is often irrelevant. The fact that ours may not be working compared to the others you list is *actually* a good indicator of an OS bug or change in behavior. As I hope you can understand, our code didn't change - something in the 10.15 beta did. Now I've told you before like I've told all the others: report this issue to Apple or stop installing their OS betas if you don't plan to actually provide them with feedback.

>I wish that you can figure out what is going on

Go ask Apple, or stop "pirating" their macOS beta builds intended for developers.

Hope this all makes sense!
