### ISSUE TITLE
Can't import .m3u files

### ISSUE THREAD

**Issue by firelad97** [OpenEmu/OpenEmu#3949]
## Summary of issue

I am unable to import .m3u files according to the guide. The very confusing thing is, I had checked most of existing (and locked) closed issues regarding the same problem I have. Someone who respond kept telling them that they didn't follow the guide correctly, and this just makes me upset.

Check this screenshot for the folder containing multi-disc Parasite Eve II with .m3u files:
https://i.imgur.com/YDZZTt4.png

As you can see above, I actually did followed the guide. When I dragged the .m3u file to OpenEmu, nothing happened. I have no idea why this is happening...

# Steps to reproduce

1. Move all multi-disc game files to a folder (CUE and BIN files)
2. Create .m3u file containing file names of CUE in plain text
3. Save it in the same folder as multi-disc game
4. Drag and drop .m3u file 

# Expected Behavior

OpenEmu correctly importing multi-disc game with a .m3u file.

# Debugging Information

- OpenEmu Version: 2.0.9.1
- macOS Version: Catalina (beta 19A501i)

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."

>Someone who respond kept telling them that they didn't follow the guide correctly

Yes, that is correct. In all cases people have not followed the guide correctly. Now it seems like it's your turn!

Possible issues:

* The files you want to import already exist in your Game Library folder.
* Your cuesheets are wrong.
* You have bad rips of the game, so they're not being autodetected as PS1 games.

If any of the above is true, you didn't follow the guide. Not an OpenEmu bug.

**Comment by firelad97** [comment]
Apologize, I don't have any issues of those. This is a fresh clean install, and I just happened to see the guide, and I followed it correctly. The library didn't have the game imported yet and it's not recognizing .m3u as it should. The cuesheets are correct, I've double-checked _everything_.

So I don't know what went wrong, so this is most definitely an OpenEmu bug. Or maybe it has to do with Catalina - macOS beta version. I will try downgrading and check everything again later.

**Comment by clobber** [comment]
>This is most definitely an OpenEmu bug

Okay, you get to show me what's wrong in the code then, because the m3u import process works fine with OpenEmu 2.0.9.1 and every stable macOS release it supports. Just because you're having a problem and *swear up and down that everything is "correct" on your end* doesn't mean it is.

**Comment by clobber** [comment]
And for the record:

```
~$ cd ~/Downloads/test
test$ ls
Parasite Eve II (USA) (Disc 1).bin	Parasite Eve II (USA) (Disc 2).bin
Parasite Eve II (USA) (Disc 1).cue	Parasite Eve II (USA) (Disc 2).cue
test$ cat "Parasite Eve II (USA) (Disc 1).cue"
FILE "Parasite Eve II (USA) (Disc 1).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
test$ cat "Parasite Eve II (USA) (Disc 2).cue"
FILE "Parasite Eve II (USA) (Disc 2).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
test$ md5 "Parasite Eve II (USA) (Disc 1).bin"
MD5 (Parasite Eve II (USA) (Disc 1).bin) = c2528bbcd164efad25c0aaccd8f6982b
test$ md5 "Parasite Eve II (USA) (Disc 2).bin"
MD5 (Parasite Eve II (USA) (Disc 2).bin) = 7bbe7164deabb5b88dcaca4bf7bf79e1
test$ curl http://redump.org/disc/1527/md5/
c2528bbcd164efad25c0aaccd8f6982b *Parasite Eve II (USA) (Disc 1).bin
f93a7e6dc96fd46138bf6142248bd64b *Parasite Eve II (USA) (Disc 1).cue
test$ curl http://redump.org/disc/1528/md5/
7bbe7164deabb5b88dcaca4bf7bf79e1 *Parasite Eve II (USA) (Disc 2).bin
97302a441323d17a75ea36c53e9d37ff *Parasite Eve II (USA) (Disc 2).cue
test$ echo -e "Parasite Eve II (USA) (Disc 1).cue"\\n"Parasite Eve II (USA) (Disc 2).cue" > "Parasite Eve II (USA).m3u"
test$ cat "Parasite Eve II (USA).m3u"
Parasite Eve II (USA) (Disc 1).cue
Parasite Eve II (USA) (Disc 2).cue
```

Drag and drop `Parasite Eve II (USA).m3u` into the Game Library window. As you can see, all my files are known good dumps, correct and the M3U imports just fine:

<img width="942" alt="Screen Shot 2019-07-07 at 6 08 53 PM" src="https://user-images.githubusercontent.com/1303132/60775242-b835cf80-a0e5-11e9-94c5-c7e6d58d9878.png">

If you cannot replicate the exact steps above, the problem is your end. Open Console.app, filter the search for `OpenEmu` and press enter, click "Clear", then drag and drop *your* M3U file and wait for output. Copy and paste all the console output back here.

**Comment by firelad97** [comment]
I apologize, I decided to not use OpenEmu as there are other applications out there that work better. Thank you for offering solutions though.
