### ISSUE TITLE
Load ROM Error - Multiple PSX Disc game

### ISSUE THREAD

**Issue by Perfectlous** [OpenEmu/OpenEmu#3950]
Hello, i do hope im not making some problems doing this, but i couldn't find an answer to my problem.

I recently downloaded Final Fantasy VIII, the game didn't came with a .cue file whatsoever and it was with a .ecm extension, i did what it must be done, using unecm to turn them into a .bin (because it was .bin.ecm), and i went to a page that makes the .cue files, hinting that it needs to be dropped in the order of the disc, which i did, and created the specific .cue for each disc, i then created the .m3u file and drop it on OpenEmu, it loaded perfectly, but i cant load it, saying "The Emulator could not load ROM". error.

All the .cue names are in order in the .m3u file, all the files are in a folder and the .cue files from each disc read like this.

- FOLDER
![Screen Shot 2019-07-07 at 12 03 40 PM](https://user-images.githubusercontent.com/52631406/60770992-4a6eb100-a0af-11e9-94be-87b5b39ecbfe.png)

- .m3u FILE
![Screen Shot 2019-07-07 at 12 04 46 PM](https://user-images.githubusercontent.com/52631406/60771004-75f19b80-a0af-11e9-802a-ec70385d0adc.png)

- INSIDE .cue FILE
![Screen Shot 2019-07-07 at 12 05 53 PM](https://user-images.githubusercontent.com/52631406/60771018-96215a80-a0af-11e9-8339-a4ce103a6b2e.png)

I really don't know what else i can inform with this error, because its not the only game i have an issue with, Mortal Kombat Trilogy present the same issue, saying the game cannot be loaded, i do hope i can get an answer about this and thank you very much for the help, keep up the good work.

Im using a Mac btw, here are the spec... thanks!

![Screen Shot 2019-07-07 at 12 06 43 PM](https://user-images.githubusercontent.com/52631406/60771043-ea2c3f00-a0af-11e9-8549-79c7680b7439.png)

Oh, i forgot! Here are the BIOS im using for the PSX emulator.

![Screen Shot 2019-07-07 at 12 09 08 PM](https://user-images.githubusercontent.com/52631406/60771059-1b0c7400-a0b0-11e9-8751-aec8059adefa.png)

**Comment by clobber** [comment]
>i did what it must be done, using unecm to turn them into a .bin (because it was .bin.ecm), and i went to a page that makes the .cue files

If you had to create your own cuesheets, then you already have bad dumps of the game. Don't bother with old ecm-compressed rips or other bad dumps. Just download good dumps from "Redump" on Archive.org.
