### ISSUE TITLE
Donate problem...

### ISSUE THREAD

**Issue by noxx09** [OpenEmu/OpenEmu#3951]
I think your soft is great and I would like donate some money but...
I'm not American,
I just want donate not subscribe to anything,
I don't want use gangster / pollutant money like bitcoin.

It's not the first time that I donate money (I make this for wikipedia a couple of time) but il's first time I can't find any satisfactory solution.
It's not possible to have a paypal solution or something like this ?

Regards.

**Comment by clobber** [comment]
Patreon has a one-time option. PayPal cannot be used with emulation projects. Sorry, beyond that I cannot help you.
