### ISSUE TITLE
Saturn ROMs Not Launching

### ISSUE THREAD

**Issue by Unboundclassic** [OpenEmu/OpenEmu#3953]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

Overall, the ROMs import and scrape artwork correctly, but don't launch. The only game that launches is NiGHTS into Dreams. That one plays great.

Not sure what's causing it exactly. Though NiGHTS into Dreams is a game with a .cue and a .bin files. Where the others are a .cue and a .iso files. As I understand it both "should" be supported. 

# Expected Behavior

I would like the games to launch and play.

# Observed Behavior

I double click and get this error:
<img width="432" alt="Screen Shot 2019-07-11 at 6 35 26 PM" src="https://user-images.githubusercontent.com/49640762/61094218-740b3d80-a40b-11e9-9d08-9ae47b5c1d68.png">

# Debugging Information

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.14.5 (18F203)

**Comment by clobber** [comment]
Sounds like a bad rip, so not worth investigating. Just follow the advice here: https://github.com/OpenEmu/OpenEmu/issues/3950#issuecomment-509015934
