### ISSUE TITLE
Cannot load the Games anymore.

### ISSUE THREAD

**Issue by BlackGamer000** [OpenEmu/OpenEmu#3954]
Describe step-by-step: 

Hello. 
I tried to edit the DeSmuME File with the <b>Hex Fiend</b> software, i wanted to change the default language as i downloaded EU Roms. 
I looked up to old issues opened on this Repository and i didn't got a useful response as i don't understand anything of Hex Code.  

# Expected Behaviour

Wanted to change the default game language.

# Observed Behaviour

When i open <b>OpenEMU</b>, i get the following error: <b>The emulator could not load ROM.</b>

# Debugging Information

- OpenEmu Version: v208
- macOS Version: macOS Mojave - 10.14.5

<i>Apologize if i did mistakes, i'm not English.</i>

**Comment by clobber** [comment]
>I tried to edit the DeSmuME File with the Hex Fiend software

Breaking your own game isn't an OpenEmu bug. What do you really want me to tell you? Delete your ROM, redownload the unedited one and don't try to edit it again.

**Comment by BlackGamer000** [comment]
The problem is, i can't load the games because i edited the file with the software mentioned above (Through the File Directory) and now i can't play games since i did mistakes in the Hex Code :c

**Comment by clobber** [comment]
>The problem is, i can't load the games because i edited the file with the software mentioned above (Through the File Directory) and now i can't play games since i did mistakes in the Hex Code :c

Yes, I understand that... Now please understand what I'm telling you:

Delete your ROM, redownload the unedited one, reimport the ROM and don't try to edit it again.

**Comment by BlackGamer000** [comment]
Okay, i will try, thank you for the fast response c:

**Comment by clobber** [comment]
Since I'm probably going to have to explain this anyway, here are the steps to follow:

1. Close the app
2. Open `~/Library/Application Support/OpenEmu/Cores` and delete `DeSmuME.oecoreplugin`
3. Open the app
4. Go to OpenEmu > Preferences > Cores and hit install for DeSmuME.

**Comment by BlackGamer000** [comment]
That solved it, thank you so much! c:
