### ISSUE TITLE
no sprites with Snes9x core

### ISSUE THREAD

**Issue by throva** [OpenEmu/OpenEmu#3956]
Hi! first of all, you guys rock and I'm probably stupid, who knows.

Until somewhat recently, OpenEmu was working fine. The other day, though (about a month ago), all the sprites just disappeared. I opened OpenEmu and... nothing, just the background. I've tried every key code combination I could think of to see if it came back but it (obviously) didn't work. On Higan it's fine, just SNES9x

I'm using OpenEmu 2.0.9.1, SNES9x 1.60.
I guess the BIOS is BS-X BIOS [English] [No DRM] [2016 v1.3] and/or Satellaview BS-BIOS (don't ask why there are 2, I have no idea).
My PC is MacBook Pro Mojave 10.14.5

I don't use it all that often, so I can't pinpoint to a specific MacOs update or anything, but that would be my guess since I couldn't find any sprite related commend in OpenEmu settings.

sorry for not having any more info, and thanks again!

**Comment by clobber** [comment]
Steps to follow:

* Re-download the Snes9x core plugin.
  1. Close the app
  2. Open `~/Library/Application Support/OpenEmu/Cores`  (Follow guide [here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) to access the hidden-by-default user Library folder.) and delete `SNES9x.oecoreplugin`
  3. Open the app
  4. Go to OpenEmu > Preferences > Cores and hit install for Snes9x.

* If that doesn't resolve it, try launching the game without restoring the autosave at launch. 
    1. In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
    2. Open your game and click "No" when prompted to "Continue where you left off"

* If still not working, get output from Console.app.
  1. [Spotlight search](https://support.apple.com/en-us/HT204014) (magnifying glass in the upper right corner on your screen - it's how one finds files and apps on their Mac). You click it and type Console and press enter.
  2. Filter the search for `OpenEmu` and press enter, click "Clear"
  3. Then try and launch your game and wait for output.
  4. Copy and paste all the console output back here.

**Comment by throva** [comment]
the first fix worked perfectly. thanks a lot!!
