### ISSUE TITLE
8bitdo Nes 30 Pro not working in macOS Catalina

### ISSUE THREAD

**Issue by atmb82** [OpenEmu/OpenEmu#3958]
Summary of issue

Openemu doesn't recognize 8bitdo Nes 30 Pro at all.

I followed the pairing instructions carefully, but as of now it doesn't work.
I tried pairing the controller both in Mac Mode (Start + A) and Normal mode (Start), confirmed by the led flashing the appropriate times for each mode.
Mac pairs and connects to the device, but Openemu doesn't recognize it at all.

# Steps to reproduce

1. Start up Nes 30 Pro both by pressing power or power + a (D-input/macOS modes)
2. Keep pairing button on the controller for 3 seconds until led flashes quickly (pairing mode enabled)
3. Open macOS bluetooth pane and connect the controller
4. Open Openemu, the controller is not recognized in either mode.

# Expected Behavior

4. Openemu should recognize the controller and let you configure it.

# Observed Behavior

1. Openemu doesn't show the paired controller at all in the controllers list.

# Debugging Information

- Openemu version: 2.0.9.1 058-g8850505-Release
- macOS version: Catalina Beta Beta 10.15 (19A512f)

**Comment by atmb82** [comment]
I saw that NO controllers work in Catalina Beta right now. Closing the issue until out of beta.

**Comment by clobber** [comment]
Please report this to Apple. You are beta testing *their* OS. https://feedbackassistant.apple.com/

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3928, #3932
