### ISSUE TITLE
House of the Dead Saturn cue issue

### ISSUE THREAD

**Issue by colson97** [OpenEmu/OpenEmu#3959]
I was downloading House of the Dead for the Saturn and then I tried using the Unarchiver see it's cued. I believe this can't be right for the Openemu. It cannot load rom either. 

<img width="947" alt="Screen Shot 2019-07-21 at 10 44 03 PM" src="https://user-images.githubusercontent.com/46289203/61604968-23fd5980-ac09-11e9-99fa-ac545b588e4e.png">
<img width="1052" alt="Screen Shot 2019-07-21 at 10 46 31 PM" src="https://user-images.githubusercontent.com/46289203/61605039-66269b00-ac09-11e9-80d0-26871bb46190.png">

**Comment by clobber** [comment]
Please actually read the the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games). It states: "MP3 is NOT supported."

You seem to be bothering with crap rips when you should be downloading known good dumps from "Redump" on Archive.org.
