### ISSUE TITLE
gameboy advance roms not working

### ISSUE THREAD

**Issue by dominicandrr** [OpenEmu/OpenEmu#3960]
Hello. All of the roms work just fine for all systems except for the gameboy advance. It used to work just fine, but one day I boot it up and now it wont play any roms.  I simply get the prompt "The emulator could not load rom"    Id like to somehow figure out why.  Im really not good with this kind of thing. All I could think of was update my emulator which I did, and still nothing.  The DS and Snes roms and etc all work just fine. Trying to figure out why only GBA doesn't work.  Any help would be greatly appreciated. Thank you for your time. 

- OpenEmu Version: 2.0.9.1 latest version
- macOS Version: Mac OS Sierra 10.12.6

**Comment by clobber** [comment]
Steps to follow:

* Re-download the mGBA core plugin.
  1. Close the app
  2. Open `~/Library/Application Support/OpenEmu/Cores`  (Follow guide [here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) to access the hidden-by-default user Library folder.) and delete `mGBA.oecoreplugin`
  3. Open the app
  4. Go to OpenEmu > Preferences > Cores and hit install for mGBA.

* If that doesn't resolve it, try launching the game without restoring the autosave at launch. 
    1. In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
    2. Open your game and click "No" when prompted to "Continue where you left off"

* If still not working, get output from Console.app.
  1. [Spotlight search](https://support.apple.com/en-us/HT204014) (magnifying glass in the upper right corner on your screen - it's how one finds files and apps on their Mac). You click it and type Console and press enter.
  2. Filter the search for `OpenEmu` and press enter, click "Clear"
  3. Then try and launch your game and wait for output.
  4. Copy and paste all the console output back here.

**Comment by Bucs4Life** [comment]
UPDATE: I redownloaded the core plug-in and it fixed thank you so much. Yes my issue was the same as his the ds games and other were working just fine! THANK YOU!!!
