### ISSUE TITLE
Rename game in List View not working

### ISSUE THREAD

**Issue by abuccilli** [OpenEmu/OpenEmu#3961]
Minor bug, at least on my end.

If I right-click an entry in "List View" and select "Rename Game" from the pop-up menu, I'm not presented with the option to enter any text. Instead, the entry name will just flash (almost as if I had changed the name, then hit enter to confirm my choice). I can, however, single-click an entry in "List View" to successfully change its name. In "Grid View," right-clicking to rename the game works fine.

- OpenEmu Version: v2.0.9.1
- macOS Version: 10.14.6

**Comment by shysaur** [comment]
Fixed for next release.
