### ISSUE TITLE
Handling multi-disc games with distinct discs

### ISSUE THREAD

**Issue by atb7** [OpenEmu/OpenEmu#3962]
How does OpenEmu handle multi-disc games where one or more of the discs are distinct (e.g., an extra bonus disc)?

For FF7, all 3 discs are linked and the handling of using one .m3u file in one folder works very well. However, for Lunar 2 there are 3 discs for the main game and a 4th "making of" disc. I assume the way to handle Lunar 2 is to create 1 folder/entry for the 3 discs and another for the 4th disc? This works but is slightly cumbersome. Could the UI be improved to better handle this down the line?

The same would apply for Final Fantasy Anthology, among many others. I could even foresee the feature being applied to a translation-patched game for a more pleasant grouping, assuming you wanted copies of both the original and patched games.

This is something of a feature request but also confirmation that this is the current correct way to handle these types of games.

**Comment by clobber** [comment]
Making Of / Bonus discs are generally not part of the game, so just import them separately. You'd import your M3U with the regular game discs and then if there is a bonus disc that isn't really part of the game, just import that on its own.
