### ISSUE TITLE
PlayStation 4 DualShock 4  Controller  mapping nes Controller

### ISSUE THREAD

**Issue by JackWchen2015** [OpenEmu/OpenEmu#3970]
the detail as bellow

**Comment by JackWchen2015** [comment]
when I connect to a PS 4 BLE Controller to play nes games, the controller cannot set the PS mode,auto switch to the NES controller. System version:10.14.4,OpenEmu Version:2.0.9.1

**Comment by clobber** [comment]
>when I connect to a PS 4 BLE Controller to play nes games, the controller cannot set the PS mode,auto switch to the NES controller

Sorry, I don't understand what you mean. You will have to be very clear.

**Comment by JackWchen2015** [comment]
> > when I connect to a PS 4 BLE Controller to play nes games, the controller cannot set the PS mode,auto switch to the NES controller
> 
> Sorry, I don't understand what you mean. You will have to be very clear.

when I first connect to my PS4 dualShock controller,it can mapping to sony plays station, but it auto mapping to nes controller last time

**Comment by JackWchen2015** [comment]
Can i play NES games with SNES Controller with Dualshork 4？
