### ISSUE TITLE
Artwork gone after update

### ISSUE THREAD

**Issue by tholsinger** [OpenEmu/OpenEmu#3972]
Summary of issue After updating OpenEmu all cover art is gone and all rooms appear to be attempting to download art without success.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce 1, open app that is it all the rooms have the rainbow background with the circling hash marks. no art anywhere 

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior find and apply art that was previously there

1. Describe what
1. you want to
1. happen

# Observed Behavior No art work associated with individual rooms

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information none that I know of

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.14.6
![Screen Shot 2019-08-20 at 12 03 40 PM](https://user-images.githubusercontent.com/54324008/63363949-96657480-c342-11e9-9e68-cbcdeeb35236.png)
![Screen Shot 2019-08-20 at 12 04 52 PM](https://user-images.githubusercontent.com/54324008/63364029-c3b22280-c342-11e9-9213-aa0ca3c849f7.png)

**Comment by clobber** [comment]
An OpenEmu update didn't remove your artwork. Sorry, cannot help you with this.
