### ISSUE TITLE
App crashes in macOS Catalina when exiting a game

### ISSUE THREAD

**Issue by shokuninstudio** [OpenEmu/OpenEmu#3974]
App crashes in macOS Catalina when exiting a game.

- OpenEmu Version: 2.0.9.1
- macOS Version: Catalina Dev Beta 7 build 19A546d

**Comment by clobber** [comment]
Please report to Apple through Feedback Assistant.

#3967

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."
