### ISSUE TITLE
Database Improvements and Using Alternate Sources

### ISSUE THREAD

**Issue by thekiefs** [OpenEmu/OpenEmu#3975]
I have over 10,000 game files that I run from Google Drive File Stream on my Mac. OpenEmu recognizes maybe 10% of all the ROMs and successfully matches them. [LaunchBox](https://www.launchbox-app.com), a multi-platform front-end, recognizes almost 90%, just through the filename alone. This is also true for [ArcBrowser](https://play.google.com/store/apps/details?id=net.floatingpoint.android.arcturus&hl=en_US).

This is because they both use (or at least give an option to use) a [constantly improving, community-maintained database](https://gamesdb.launchbox-app.com). 

I'm not sure what database OpenEmu uses but it appears to be severely lacking. Can we please be given the option to use the Launchbox Database, or another open source database? Manually matching games in OpenEmu is a non-starter for me considering the sheer volume that need to be matched.

**Comment by clobber** [comment]
Uses OpenVGDB which actually matches all *retail* releases of carts. Don’t have an example of what you cannot match, but we’re only going to use one data source: our own, which was custom made after a ton of work to fill our particular use case and library management style.

**Comment by thekiefs** [comment]
Here's a screenshot of an example N64 list: 

<img width="380" alt="Screen Shot 2019-08-31 at 14 34 58" src="https://user-images.githubusercontent.com/51860580/64067815-c5aa9a00-cbfc-11e9-95fb-b9b33cc817d3.png">
<img width="342" alt="Screen Shot 2019-08-31 at 14 35 10" src="https://user-images.githubusercontent.com/51860580/64067816-c5aa9a00-cbfc-11e9-833b-ca738cf51ac5.png">

None of them are matched, which is odd because (1) they are official retail versions (2) the filename is the official title of the game.

How do you manage your library? Outside of having some sort of embedded metadata (which perturbs the as-close-to-original intent of my ROMs as possible), officially named titles with an exact-name solution doesn't seem like a bad idea to me, or at least giving other users the option since every other game front-end does this.

**Comment by clobber** [comment]
XY problem here. Had you originally stated (and search for) your problem, we would have figured out that this is a known issue with the byte swapped N64 dumps. See #3429

>since every other game front-end does this.

That isn't true, so let's not generalize. Most frontends have no cover art. EmulationStation and other RetroPie derivatives/setups use the database we built. We're the source here.

Anyway, as stated we are not interested in fuzzy matching so you're not going to win anyone over here. When I feel like it, I will add in a wiki page with details on how matching works and the current known edge cases, but the short story is a mix of hash, serial and header matching depending on the system.

>since every other game front-end does this.

There you go again :P
