### ISSUE TITLE
Fast forward issue

### ISSUE THREAD

**Issue by Haruyen** [OpenEmu/OpenEmu#3976]
Hello,

I used OpenEmu for many years and it the first time that fast forward not working.

In the previous version of OpenEmu, it's working, but now, no.

I would use it for NDS and SNES and both of them don't working. I already use the fast forward with NDS before, and it was working. I would try on SNES, and it was never work. After, I try again on NDS and fast forward didn't work anymore.

I uninstall (manually first time) and install it again. But OpenEmu save my old preferences, so I uninstall it again with CCleaner and re-install it. My old preferences (and saves) were gone. However fast forward still doesn't work.

OpenEmu version : 2.0.9.1
Mac OS version : 10.14.6
proc : 2,3 GHz Intel Core I7
16 go 1600 MHz DDR3
NVIDIA Geforce GT 750M 2Go
Intel Iris Pro 1536 Mo

Thank you very much.

If I not very clear, excuse me, I'm French, so I could to express myself badly.

EDIT : I forgot some details : the game I want run with fast forward are : pokemon white on DS and Dragon quest III on SNES. And when I want use fast forward, I have the icone that appears like it worked. But the speed is the same as usual.

**Comment by clobber** [comment]
Cannot replicate this problem with OpenEmu 2.1. Fast forward works fine for both SNES and NDS systems.
