### ISSUE TITLE
GameCube + Wii Support (Dolphin Emulator)

### ISSUE THREAD

**Issue by Zrules** [OpenEmu/OpenEmu#3977]
I think that you should include Dolphin because the list kind of feels incomplete without it and you also support the Wiimote so it only make sense to include it with the other consoles. I'll provide a link to their website. Also it runs perfectly fine on my Mac which is over 5 years old at the time I'm typing this. If you have any questions, feel free to ask them and I'll answer them.

Link: https://dolphin-emu.org/

If your curious about my specs, here they are
Core i5 1.4 GHz
8 GB 1600 MHz DDR3 memory
Intel HD Graphics 5000 1536 MB GPU (which is equivalent to a low cost GPU)

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues?utf8=%E2%9C%93&q=dolphin

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."
