### ISSUE TITLE
Saturn Games Will Not Import

### ISSUE THREAD

**Issue by JoGo-DaMaster** [OpenEmu/OpenEmu#3979]
I have both Saturn Bomberman and Nights into Dreams. I looked on the Web and could only find mdf/mds file versions. I converted them to bin/cue with the official guide, but they won't import into OpenEmu anyway no matter what I do. Can anyone please help?

**Comment by clobber** [comment]
Sega Saturn games import just fine; I have a Library full of them. Instead of messing around with trying to convert files, which is error-prone, just download known good dumps from "Redump" on Archive.org which will be in the correct and supported format.
