### ISSUE TITLE
Why does NES controller have only 2 buttons(A & B)?

### ISSUE THREAD

**Issue by xiebruce** [OpenEmu/OpenEmu#3982]
This is an excellent emulator on macOS, but I just don't understand why two buttons missing? 

As you can see, this is a controller I found on Amazon ([link](https://www.amazon.com/Rechargeable-Wireless-Controller-Nintendo-Controller/dp/B077N8Y9VW/ref=sr_1_4?crid=7I3OY0Y8Z8ME&keywords=nes+controls+for+switch&qid=1568962182&sprefix=NES+controls%2Caps%2C379&sr=8-4)), obviously, it has four buttons.:
![image](https://user-images.githubusercontent.com/13575500/65306005-03c12b00-dbb7-11e9-9404-f37a6a0e397b.png)

And this is OpenEmu's controller, it has only 2 buttons, missing turbo button and the one on the right of turbo button(I don't know how to call it):
![image](https://user-images.githubusercontent.com/13575500/65306013-0754b200-dbb7-11e9-81a4-c83f4aa433dd.png)

please don't link to https://github.com/OpenEmu/OpenEmu/issues/2570, https://github.com/OpenEmu/OpenEmu/issues/933 or  [https://github.com/OpenEmu/OpenEmu/projects/1](https://github.com/OpenEmu/OpenEmu/projects/1), cause I don't see any progress on these links.

Anyone who needs these 2 buttons, please give this issue a thumbs up, we need to let the developers know we need these 2 buttons.

**Comment by craigerskine** [comment]
The original NES controllers did NOT have those buttons. OpenEmu controller prefs will always use the **original** controller designs and not some overseas knockoff kludgey design. If you want rapid fire button assignments, use [RetroArch](http://retroarch.com).
