### ISSUE TITLE
Genesis core crash on close

### ISSUE THREAD

**Issue by andypoo79** [OpenEmu/OpenEmu#3987]
Summary of issue

genesis core crashes openemu after clicking red power off button on.

open rom genesis core
emulation correct
click red button to stop emulation
os reports openemu quit unexpectedly

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.15 catalina

----- mac crash report ---

Process:               OpenEmu [18676]
Path:                  /Applications/OpenEmu.app/Contents/MacOS/OpenEmu
Identifier:            org.openemu.OpenEmu
Version:               2.0.9.1 (2.0.9.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           OpenEmu [18676]
User ID:               501

Date/Time:             2019-10-08 22:07:50.131 +0100
OS Version:            Mac OS X 10.15 (19A583)
Report Version:        12

Time Awake Since Boot: 42000 seconds
Time Since Wake:       27000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [18676]

Application Specific Information:
Over-release of NSResponder or subclass.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3967
