### ISSUE TITLE
OpenEmu crashing

### ISSUE THREAD

**Issue by onesyder** [OpenEmu/OpenEmu#3989]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Launch OpenEmu
2. Start any game on any system
3. Push "Stop Emulation" button to quit game
4. OpenEmu crashes and force quits

<img width="439" alt="Screen Shot 2019-10-12 at 9 55 41 AM" src="https://user-images.githubusercontent.com/56481278/66703278-816be880-ecd6-11e9-8927-260bc67a8804.png">

# Debugging Information

- OpenEmu Version: 2.0.9.1
- macOS Version: macOS Catalina version 10.15

**Comment by MaddTheSane** [comment]
This is a known issue, and the next release will fix the bug.

**Comment by clobber** [comment]
Good thing we have an issue pinned...

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3967
