### ISSUE TITLE
Old SNES .oesavestate (from 0.93.1) unable to load in 2.0.9.1

### ISSUE THREAD

**Issue by crackajack77** [OpenEmu/OpenEmu#3991]
Hey there,

On a Mac here, 10.12., OpenEmu 2.0.9.1
I still have some older SNES savestate bundles from 0.93.1 which I would happily be able to continue using in the current version.

OpenEmu recognizes the savestates, previews the included screenshot but cannot continue loading it with following error: 
![Bildschirmfoto 2019-10-14 um 21 40 46](https://user-images.githubusercontent.com/14182507/66778201-58607900-eecb-11e9-9091-23413233d96d.png)

info.plist from one the *.oesavestate's 
`<dict>
	<key>Core Identifier</key>
	<string>org.openemu.Higan</string>
	<key>Core Version</key>
	<string>0.93.1</string>
	<key>Name</key>
	<string>Spielstand 1 2014-10-19 19:36:18 +0000</string>
	<key>ROM MD5</key>
	<string>a2bc447961e52fd2227baed164f729dc</string>
	<key>Timestamp</key>
	<date>2014-10-19T19:36:18Z</date>
	<key>Version</key>
	<string>1.0</string>
</dict>
</plist>
`

The actual 'state' file only contains around 20.000 lines of hexadecimal code. 
![Bildschirmfoto 2019-10-14 um 21 37 25](https://user-images.githubusercontent.com/14182507/66778063-f0aa2e00-eeca-11e9-89f8-d4d5fef4a1a3.png)

Did the fileheader from those states change? How can i fix those states, don't want to loose all these older progress. Thanks!

![Bildschirmfoto 2019-10-14 um 21 39 51](https://user-images.githubusercontent.com/14182507/66778164-3535c980-eecb-11e9-8461-f94480d7e3fd.png)

**Comment by clobber** [comment]
Cannot help you with this -- this is not an OpenEmu issue. Higan save states are not compatible between releases. You should always rely on in-game battery saves instead of save states whenever possibly.
