### ISSUE TITLE
Suggestion: Show console or error on bad import

### ISSUE THREAD

**Issue by jackaperkins** [OpenEmu/OpenEmu#3992]
Many roms do not seem to import correctly, but as a user there's no indication why. I just see the small "Game Scanner" bar running for a few seconds, and then no game appears. Many other games work fine, but it's unclear why some fail.

Could that game scanner window stay open with a small error message, even if just something fairly generic?

Suggestions aside, OpenEmu is a fantastic piece of software ❤️  thanks!

- osx 10.14.5
- open emu 2.0.9.1

**Comment by clobber** [comment]
> Many roms

That’s vague. We include a guide here for expected file extensions: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing

If it’s a CD based game, use good dumps by “Redump” from Archive.org.

As for feedback, there is logging in Console but not adding anything additional to the UI.
