### ISSUE TITLE
N64 Crash at exact same point in a game. Couldn’t communicate with a helper application

### ISSUE THREAD

**Issue by Jatt96** [OpenEmu/OpenEmu#3997]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Open "WWF No Mercy" in the N64 emulator. 
2. After a regular 1 on 1 match, without fail, when pressing Quit, the game freezes.
3. Forced to close OpenEmu and then a "Couldn't communicate with helper application" occurs.

I've ensured OpenEmu is up to date. I downloaded 3 other wrestling games to replicate it (WM 2000, WCW World Tour, WCW Revenue) and after a 1 vs. 1 match, I was able to quit to get to the main menu without issue.

**Here's the error log:**

Process:               OpenEmuHelperApp [8453]
Path:                  /Applications/OpenEmu.app/Contents/Resources/OpenEmuHelperApp
Identifier:            OpenEmuHelperApp
Version:               2.0.9.1 (2.0.9.1)
Code Type:             X86-64 (Native)
Parent Process:        OpenEmu [8410]
Responsible:           OpenEmuHelperApp [8453]
User ID:               501

Date/Time:             2019-10-19 14:25:18.031 -0400
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Anonymous UUID:        30007944-31FD-0718-95C8-BE8941FF365B

Sleep/Wake UUID:       B2BE333C-C689-44C9-B95F-F3FDB284ED63

Time Awake Since Boot: 150000 seconds
Time Since Wake:       17000 seconds

System Integrity Protection: enabled

Crashed Thread:        4

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (numVertex == 3), function renderTriangles, file /Users/clobber/Code/OpenEmu/Mupen64Plus/GLideN64/src/SoftwareRender.cpp, line 198.
 

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff7d61c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff7d61c76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff5156c94e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff5156bebc __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff5156b61e CFRunLoopRunSpecific + 455
5   com.apple.HIToolbox           	0x00007fff507ca1ab RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           	0x00007fff507c9ee5 ReceiveNextEventCommon + 603
7   com.apple.HIToolbox           	0x00007fff507c9c76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff4eb6277d _DPSNextEvent + 1135
9   com.apple.AppKit              	0x00007fff4eb6146b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
10  com.apple.AppKit              	0x00007fff4eb5b588 -[NSApplication run] + 699
11  OpenEmuHelperApp              	0x000000000dbc0f4c -[OpenEmuXPCHelperApp launchApplication] + 77
12  OpenEmuHelperApp              	0x000000000dbc05f3 main + 126
13  libdyld.dylib                 	0x00007fff7d4e73d5 start + 1

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff7d61c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff7d61c76c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff5156c94e __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff5156bebc __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff5156b61e CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff4eb6a4a2 _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff7d6db2eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff7d6de249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff7d6da40d thread_start + 13

Thread 2:: m64pwq
0   libsystem_kernel.dylib        	0x00007fff7d61f86a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff7d6de56e _pthread_cond_wait + 722
2   org.openemu.Mupen64Plus       	0x000000001134b3c9 workqueue_thread_handler + 89
3   org.openemu.Mupen64Plus       	0x000000001134b1fe Fake_SDL_New_Thread + 30
4   libsystem_pthread.dylib       	0x00007fff7d6db2eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff7d6de249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff7d6da40d thread_start + 13

Thread 3:: org.openemu.core-thread
0   libsystem_kernel.dylib        	0x00007fff7d61c386 mach_wait_until + 10
1   org.openemu.OpenEmuBase       	0x000000000dd99188 -[OEGameCore runGameLoop:] + 1063
2   org.openemu.OpenEmuBase       	0x000000000dd98a54 -[OEGameCore _gameCoreThreadWithStartEmulationCompletionHandler:] + 104
3   com.apple.Foundation          	0x00007fff537c6112 __NSThread__start__ + 1194
4   libsystem_pthread.dylib       	0x00007fff7d6db2eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff7d6de249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff7d6da40d thread_start + 13

Thread 4 Crashed:
0   libsystem_kernel.dylib        	0x00007fff7d6222c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff7d6ddbf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff7d58c6a6 abort + 127
3   libsystem_c.dylib             	0x00007fff7d55520d __assert_rtn + 324
4   mupen64plus-video-GLideN64.so 	0x00000000130af254 renderTriangles(SPVertex const*, unsigned short const*, unsigned int) + 5940
5   mupen64plus-video-GLideN64.so 	0x000000001309b8fd GraphicsDrawer::drawTriangles() + 349
6   mupen64plus-video-GLideN64.so 	0x000000001308584c ProcessDList + 2028
7   mupen64plus-rsp-cxd4.so       	0x00000000104127e0 DoRspCycles + 128
8   org.openemu.Mupen64Plus       	0x0000000011249f3f do_SP_Task + 4351
9   ???                           	0x000000001e411940 0 + 507582784

Thread 5:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff7d61c22a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff7d61c76c mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff50fdbeda HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 122
3   com.apple.audio.CoreAudio     	0x00007fff50fdbe4f HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff50fd839f HALC_ProxyIOContext::IOWorkLoop() + 1017
5   com.apple.audio.CoreAudio     	0x00007fff50fd7df4 HALC_ProxyIOContext::IOThreadEntry(void*) + 122
6   com.apple.audio.CoreAudio     	0x00007fff50fd7956 HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff7d6db2eb _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff7d6de249 _pthread_start + 66
9   libsystem_pthread.dylib       	0x00007fff7d6da40d thread_start + 13

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff7d6da3f0 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff7d6da3f0 start_wqthread + 0

Thread 4 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000700007826000  rcx: 0x00007000077dcd38  rdx: 0x0000000000000000
  rdi: 0x000000000000b603  rsi: 0x0000000000000006  rbp: 0x00007000077dcd70  rsp: 0x00007000077dcd38
   r8: 0x00000000000000c6   r9: 0xcccccccccccccccd  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x000000000000b603  r13: 0x000000001c7ca000  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff7d6222c6  rfl: 0x0000000000000206  cr2: 0x00007fffb3d55188
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3715
