### ISSUE TITLE
A running game receives live input from Controls Preferences window

### ISSUE THREAD

**Issue by DarkDust** [OpenEmu/OpenEmu#3998]
My controls "suddenly" stopped working completely (joypad and keyboard) after having played for several days. It took me half an hour to figure out the issue and it might be worthwhile to mention this on the _Troubleshooting: Input problems_ page at: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

> With PSX, switching the controller to Analog Mode may cause a game to stop receiving inputs. The solution is to switch back to Digital Mode (e.g. via the `\` key in the default binding).

That I ran into this issue in the first place is maybe another bug: I wanted to map an (what I thought) unused button on my joypad to quicksave. So I opened the preferences, got to controls, Sony PlayStation, selected the joypad, clicked into the quick save field and then pressed the button I wanted to remap. It was previously mapped to Analog Mode and when I pressed it, it go reassigned to Quick Save… but first, the Analog Mode action was triggered, unbeknownst to me.

OpenEmu v2.0.9.1
macOS 10.14.6

**Comment by clobber** [comment]
>It was previously mapped to Analog Mode and when I pressed it, it go reassigned to Quick Save… but first, the Analog Mode action was triggered, unbeknownst to me.

Is it correct that you have "Always pause gameplay when in background" unchecked in Gameplay Preferences?

**Comment by DarkDust** [comment]
I had "Always pause gameplay when in background" checked but I can also reproduce the problem with the box unchecked (as you already found out).

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu/commit/0e7caf1eb9b67dd8756921feae87e1149dcab9f7
