### ISSUE TITLE
Mac Catalina Crash Issue. Update?

### ISSUE THREAD

**Issue by sohojohn84** [OpenEmu/OpenEmu#3999]
Hello Openemu team, 

thought I'd check to see if there was a solve for the crash experiencing with Catalina when stopping emulation.

Thanks much!

Jon

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

An update will be released when it's ready. It is unnecessary and not helpful to pester.

#3967
