### ISSUE TITLE
Cannot add CD-based games to library

### ISSUE THREAD

**Issue by kda49-github** [OpenEmu/OpenEmu#4002]
Summary of issue
Due to error whereby OpenEmu crashes when stop emulation button is pressed, I followed the instructions to build from source. This solves the crash problem but now I cannot add CD-based games (tried Playstation and Saturn) to the library. Drag and drop or using the Add to library menu does nothing. It works for cartridge based games (tried Nintendo). I am sure the built OpenEmu is the problem because I can add the same CD-based games while using the downloaded app.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Drag and drop or use Add to library a .cue or .ccd file

# Expected Behavior

1. Game scanner should appear and add game to library

# Observed Behavior

1. Game scanner does not appear and nothing happens

# Debugging Information
default	21:38:33.225809+0800	OpenEmu	''
default	21:38:33.225966+0800	OpenEmu	''
default	21:38:33.226089+0800	OpenEmu	''
default	21:38:33.232084+0800	OpenEmu	Error Domain=OEImportFatalDomain Code=3 "(null)"

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.15

**Comment by clobber** [comment]
>OpenEmu Error Domain=OEImportFatalDomain Code=3

Whatever you're trying to import, no system exists. Sounds like a bad dump of a game. Download known good dumps from "Redump" on Archive.org

**Comment by kda49-github** [comment]
But I was able to import the very same files using the official app

**Comment by clobber** [comment]
Then you’ve compiled incorrectly, perhaps missing system plugins or cores. Sorry, I don’t have time or interest to troubleshoot something you may have broken. Please wait until next OpenEmu release, which should be soon.
