### ISSUE TITLE
(macOS 10.15 Catalina) PPSSPP 1.9.3 crash

### ISSUE THREAD

**Issue by DarkenTVgaming** [OpenEmu/OpenEmu#4003]
I've played psp games for more days after macOS Catalina update, today the psp's emulator don't run and the pc show me a message of OpenEmuHelper crashing, what can i do? 

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.15

**Comment by clobber** [comment]
Steps to follow:

* Re-download the PPSSPP core plugin.
  1. Close the app
  2. Open `~/Library/Application Support/OpenEmu/Cores`  (Follow guide [here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) to access the hidden-by-default user Library folder.) and delete `PPSSPP.oecoreplugin`
  3. Open the app
  4. Go to OpenEmu > Preferences > Cores and hit install for mGBA.

* If that doesn't resolve it, try launching the game without restoring the autosave at launch. 
    1. In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
    2. Open your game and click "No" when prompted to "Continue where you left off"

* If still not working, get output from Console.app.
  1. [Spotlight search](https://support.apple.com/en-us/HT204014) (magnifying glass in the upper right corner on your screen - it's how one finds files and apps on their Mac). You click it and type Console and press enter.
  2. Filter the search for `OpenEmu` and press enter, click "Clear"
  3. Then try and launch your game and wait for output.
  4. Copy and paste all the console output back here.

**Comment by DarkenTVgaming** [comment]
I've tried with your all councils, but the issue continue...

**Comment by DarkenTVgaming** [comment]
> Steps to follow:
> 
> * Re-download the PPSSPP core plugin.
>   
>   1. Close the app
>   2. Open `~/Library/Application Support/OpenEmu/Cores`  (Follow guide [here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) to access the hidden-by-default user Library folder.) and delete `PPSSPP.oecoreplugin`
>   3. Open the app
>   4. Go to OpenEmu > Preferences > Cores and hit install for mGBA.
> * If that doesn't resolve it, try launching the game without restoring the autosave at launch.
>   
>   1. In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
>   2. Open your game and click "No" when prompted to "Continue where you left off"
> * If still not working, get output from Console.app.
>   
>   1. [Spotlight search](https://support.apple.com/en-us/HT204014) (magnifying glass in the upper right corner on your screen - it's how one finds files and apps on their Mac). You click it and type Console and press enter.
>   2. Filter the search for `OpenEmu` and press enter, click "Clear"
>   3. Then try and launch your game and wait for output.
>   4. Copy and paste all the console output back here.





I've tried with your all councils, but the issue continue...

**Comment by clobber** [comment]
>I've tried with your all councils, but the issue continue...

Clear you have not, because I asked you:
>If still not working, get output from Console.app.

**Comment by clobber** [comment]
This is fixed now.

Restart the app and an updated PPSSPP core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for PPSSPP 1.9.3.1.

**Comment by DarkenTVgaming** [comment]
> This is fixed now.
> 
> Restart the app and an updated PPSSPP core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu > Preferences > Cores and looking for PPSSPP 1.9.3.1.

Verified, It works perfectly now ;)
