### ISSUE TITLE
Cannot play sound on AirPods on Catalina

### ISSUE THREAD

**Issue by kidzrl** [OpenEmu/OpenEmu#4007]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce
1. Connect AirPods to Catalina.
2. Open a random game in game library.
3. Cannot hear game sounds from the game.
4. Play sound by other apps can hear sound from AirPods
5. Disconnect AirPods, can hear the game sound from built in speaker.

# Expected Behavior

1. Game sound output to AirPods normally.

# Observed Behavior

1. Cannot hear game sound from AirPods

# Debugging Information

- OpenEmu Version: 2.1
- macOS Version: 10.15
- AirPods 1

**Comment by iMojito** [comment]
Same on Mojave 10.14.6

**Comment by stuartcarnie** [comment]
We've identified the issue; a fix is coming
