### ISSUE TITLE
Can't Record OpenEmu audio

### ISSUE THREAD

**Issue by DarkenTVgaming** [OpenEmu/OpenEmu#4008]
Summary of issue

While I'm Recording my gameplay using OpenEmu I' can't recording audio with iShowU Capture (Using Quicktime), I can record the others app but no OpenEmu

# Steps to reproduce
1. Open OpenEmu.
2. Open Quicktime for recording audio with iShowU Capture.
3. click on device with multiple audio on my audio preferences.
4. start recording audio on quicktime.
5. starting emulation.

# Expected Behavior
1. Quicktime record OpenEmu's audio.

# Observed Behavior
1. OpenEmu is the only app that iShowU Capture (Using quicktime) can't recording.
2. Unlike i can see from Quicktime that it's recording OpenEmu's Audio if i choose only iShowU Capture from my audio preferences, but if i do that i can't ear OpenEmu's audio.

- OpenEmu Version: 2.1
- macOS Version: 10.15 Catalina

**Comment by clobber** [comment]
Issues with secondary audio output should be resolved in the next release. Please try this test build to see if it makes any difference: https://transfer.sh/eLy9J/OpenEmu_audiotest.zip

**Comment by DarkenTVgaming** [comment]
> Issues with secondary audio output should be resolved in the next release. Please try this test build to see if it makes any difference: https://transfer.sh/eLy9J/OpenEmu_audiotest.zip

Thank you so much, i've tried and it works perfectly, now i can record the audio with iShowU Capture using Quicktime

**Comment by clobber** [comment]
Great! Thanks for testing. Fix will be available in the next release.

https://github.com/OpenEmu/OpenEmu/commit/0ee0e738dce04e9910d09f45a3ed216f43b80562
