### ISSUE TITLE
Couldn't load games on OpenEmu 2.1 with MacOS Catalina

### ISSUE THREAD

**Issue by GianGus** [OpenEmu/OpenEmu#4009]
Steps to reproduce

1. Start OpenEmu Experimental 2.1 with MacOS Catalina 10.15 on iMac (Retina 4K, 21.5-inch, 2017);
2. Try to start a game (any, of different platforms)

# Expected Behavior

1. The games open normally and I can start to play them.

# Observed Behavior

1. No game starts. 
OpenEmu warns me differently depending on the platform I choose, for example:
with SNES, PlayStation, GameBoy, Virtual Boy games "The Emulator could not load rom"
with PlayStation games also "Unable to communicate with a support application"
with Nintendo (NES) games "corrupt file"
with Nintendo 64 games "The "xxx. Z64" file cannot be opened because you do not have the necessary privileges to view it." (but I have them)

# Debugging Information

- OpenEmu Version: 2.1 Experimental
- macOS Version: Catalina 10.15

**Comment by clobber** [comment]
Sounds like a whole lot of problems. Start first by trying to run games in the Homebrew tab.

**Comment by GianGus** [comment]
Games in the Homebrew tab work without problems. Is there a way to take crash logs with my games?

**Comment by clobber** [comment]
Then it may be safe to assume you have a lot of bad dumps of games. You should be using ROMs from a "No-Intro" set for cart-based systems and "Redump" for CD-based systems. All can be [obtained on Archive.org](https://hackmd.io/VhCKo5t5T3ubrSxN9DLJJA).

**Comment by GianGus** [comment]
But why in the past with other emulators and also with openemu older versions they work all well? 
Even with openemu 2.1 the first time I try to run some games they work well but suddently they stopped working (I think the only thing I did was to check again Catalina’s system control privacy settings  because I couldn't set the controller keys correctly)

**Comment by clobber** [comment]
The best way forward is to **test with known good dumps** of the games, so download one from the link I gave you and do that. While there could be another issue going on here, I'm not going to troubleshoot your files that you may have downloaded from Uncle Jimbob's Warez Emporium.

So, download a game, let me know which one and if it works or not.

**Comment by GianGus** [comment]
Ok here is how I solved (maybe this could be helpful to someone):

1. I tried, as you suggested, to download some games from Archive.org, all worked properly;
2. since I knew that my files were not bad dump games, I took them from the Finder, in the same position where they were already, and I inserted them again (drag and drop) in openemu.
The result?  everything is back to normal and everything is working properly.

I wonder just why it happened

**Comment by LuMario2013** [comment]
Yeah, that "Corrupt file." error reminds me of Golf Ball saying "Guys! The most important factor is whether the hotel has sufficient bedrooms for us to sleep in. So get off that chandelier and let's inspect them!" from "BFDIA 6: Well Rested", 
right?
<img width="372" alt="Screenshot 2023-10-22 at 8 13 00 PM" src="https://github.com/OpenEmu/OpenEmu/assets/155029317/3ecb5726-a351-4cf8-a233-3546c7b72c5e">
