### ISSUE TITLE
WWF No Mercy: Gray screen and then "Unable to communicate with the helper application"

### ISSUE THREAD

**Issue by jasonlightner** [OpenEmu/OpenEmu#4012]
# Summary of issue

WWF No Mercy for Nintendo 64 seems to be having issues with transitions between scenes.
I've had this happen in two locations—once when exiting from the Create a Wrestler mode, and then every time I attempt to do single-player story mode for the Light Heavyweight Championship.
The screen will go gray and then the game will not respond to any input.
Stopping emulation causes OpenEmu to display the message "Unable to communicate with the helper application".
Crash log:
[OpenEmuNoMercyCrashLog.txt](https://github.com/OpenEmu/OpenEmu/files/3784872/OpenEmuNoMercyCrashLog.txt)

# Steps to reproduce

1. Launch OpenEmu
2. Select Nintendo 64
3. Launch No Mercy
4. Go into Championship mode in Single Player
5. Select Light Heavyweight Title
6. When the game announces a 4-way match, observe it then going to a blank gray screen
7. Stop emulation with the red button on the toolbar
8. Observe Helper Application message from OpenEmu

# Expected behavior

1. The game plays normally.

# Observed behavior

1. The game freezes at a gray screen
2. OpenEmu displays a message about being unable to communicate with the helper application
3. The main OpenEmu window goes away, but you can bring it back via the Window menu

# Debugging information

- OpenEmu Version: 2.1
- macOS Version: 10.14.6

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3715
