### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by wagenet** [OpenEmu/OpenEmu#4016]
Summary of issue

Audio does not work at all. This is both for snes9x and Mupen64Plus. It worked on prior versions.

# Steps to reproduce

Play a game.

# Expected Behavior

I want audio to play.

# Observed Behavior

No audio is output.

# Debugging Information

- OpenEmu Version: v2.1 265-g9379477-Release
- macOS Version: 10.15 (19A602)

**Comment by clobber** [comment]
>Audio does not work at all.

Need to be a little more details than that.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4011
