### ISSUE TITLE
Screen tearing

### ISSUE THREAD

**Issue by Akylzhan** [OpenEmu/OpenEmu#4018]
Screen Tearing occurs while playing Kirby's adventure 1993 for NES
![kirby](https://user-images.githubusercontent.com/28390596/67918489-c775e700-fbc6-11e9-88c2-ab0e447f452b.png)
![kirby2](https://user-images.githubusercontent.com/28390596/67918495-c9d84100-fbc6-11e9-9e4c-1fc808a788d2.png)

- OpenEmu Version: v2.1
- macOS Version: 10.15

**Comment by clobber** [comment]
Heh. That is normal for games of this era. If you don't like it, go to the HUD bar > cog wheel > Display Modes > Overscan and tick both of the options to crop.

**Comment by Akylzhan** [comment]
This did not work for me :c, I have ticked both "Crop Vertical" and "Crop Horizontal"
