### ISSUE TITLE
The PSP Emulator on OpenEmu don't works!!

### ISSUE THREAD

**Issue by iramK** [OpenEmu/OpenEmu#4019]
I tried to use the PSP emulator, but after a black screen appears this message:

Could not communicate with the associated application

And the OpenEmu turns off.

The PPSSPP 1.9.3 Core its ok (may I think) there it's not error or something wrong apparently, I tried a few times more, but nothing, the black screen and the message again.

My version of OpenEmu is: 2.1 (recently updated for MAC OS Catalina)

What happen with Open Emu and PSP emulator. Can someone tell me how to fix it?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4003
