### ISSUE TITLE
Simultaneous, opposite-direction inputs from D-Pad not accepted.

### ISSUE THREAD

**Issue by HRayner** [OpenEmu/OpenEmu#4022]
# Summary

I'd like to be able to play Dance Dance Revolution, but there seems to be something preventing simultaneous inputs from opposite D-Pad directions.  (For example: if pressing East, cannot get a pressed West to register, even though this sort of input is common in DDR.)  Granted, this is uncommon for a REAL D-Pad, but it's common using a dance mat.

# Debugging Information

Running OpenEmu Version 2.1.1 on macOS 10.14.6.  Using a Mayflash GC Controller Adapter and a Konami-brand Wii dance pad.

# Steps to reproduce

- Plug the dance pad into the adapter, and the adapter into the USB hub.
- Open OpenEmu.
- Go to Preferences>Controls, select Player 1 and select the Mayflash adapter as the controller type.
- Select the desired gameplay buttons and press the corresponding areas on the dance pad.  You can map the arrow buttons on the dance pad to up-down-left-right (in which case, if you press one, the rest are auto-mapped, implying it's being detected as a D-pad input).
- Alternatively, you can map North, South, East, West to Triangle, X, O, Square.  Either mapping will work during gameplay.
- Open Dance Dance Revolution for PSX, select "Game Mode," Pick a character, select "Normal," and then pick a song.

# Expected Behavior

- When playing DDR, it is common to hit multiple directions simultaneously.  I might be standing on "West" and need to hit "East" for one example, or I might need to jump and hit "North" and "South" at the exact same time, for another example.  
- The expected behavior is that I would be able to do this with the dance pad and to get both inputs to register.  The simplest way to see if this is happening is took at the arrows at the top of the screen.  If you press a direction, then the corresponding arrow "bounces."  
- If you map the controls to a keyboard or the (NON-D-pad) buttons on a gamepad (including a gamecube controller plugged into the adapter), then these sorts of simultaneous presses work.  I could be holding the button for "West" or Square, and when I press "East" or Circle, the right arrow will bounce.  I can press "North" and "South" or Triangle and X simultaneously, and both arrows will bounce at the same time.

# Observed Behavior

- When I do the same thing using the dance pad arrow spots, it doesn't work.  If I'm standing on one direction (say, "West"), it won't register input from "East."  ("North" and "South" will still work, though.)
- This occurs whether I have the dance pad arrows mapped to up down left right OR triangle X square O.

**Comment by clobber** [comment]
Not a frontend feature. Must be implemented at the core level and it WILL break games. Open this issue in the applicable core plugin repo and we will consider making it a core option in the future.

**Comment by HRayner** [comment]
> Must be implemented at the core level and it WILL break games.

Please forgive my ignorance.  If I were hypothetically trying to get OpenEmu to JUST work for DDR, is there something I could conceivably tweak to make it work?  I'm certainly no expert programmer, but I have learned Python and Matlab and have faked things in other programming languages in the past.  My wife loved the old DDR games when she was growing up, and she's nostalgic now, so I'm trying to see if there's any way to fake this.

**Comment by HRayner** [comment]
Could you at least direct me to the core plugin repo?  I don't know where that is
