### ISSUE TITLE
Allow D-Pad Buttons to Function Like Keyboard Keys (keyboards don't break games)

### ISSUE THREAD

**Issue by HRayner** [OpenEmu/OpenEmu#4025]
Summary of issue

You can program keyboard keys (or non-D-pad controller buttons) to represent directional or other buttons.  These keys/buttons can then be pressed, even simultaneously, and the games work fine.  Nothing crashes, everything is cool.  Why, then, are auto-detected D-pads not allowed to give simultaneous inputs as well?

# Steps to reproduce

This procedure has been tried with the same result for the following PSX games: Alundra, Ape Escape, Silent Bomber, Spyro the Dragon, Dance Dance Revolution.

-Map keyboard arrows (or other keys) to represent the PSX D-pad, open a PSX game, and try pressing opposite directions at the same time.
-Map non-D-pad controller buttons to represent the PSX D-pad, open a game, press opposite directions at the same time.
-Map an auto-detected D-pad to represent PSX D-pad, open game, press opposite directions.

# Expected Behavior

When using the keyboard or the non-D-pad controller buttons, simultaneous presses of opposite directions are passed to the games (confirmed in DDR, which actually demands simultaneous presses).  Each game handles the simultaneous presses differently, but no game crashes, and everything keeps working.

# Observed Behavior

When using an input which OpenEmu has automatically detected as being a D-pad, opposite-direction inputs are not passed to the game (even though they can be passed via keyboard or other buttons and the games still work fine).
This occurs whether the D-pad is programmed to correspond to D-pad inputs (which, as we've already established, isn't be a problem) or the D-pad corresponds to other buttons entirely (in which case, it _definitely_ isn't a problem).

# Debugging Information

- OpenEmu Version: 2.1.1
- macOS Version: 10.14.6

**Comment by clobber** [comment]
We do NOT need a second issue opened regarding your feature request. Please stop pestering.
