### ISSUE TITLE
Sega Saturn trigger button reversed!

### ISSUE THREAD

**Issue by colson97** [OpenEmu/OpenEmu#4026]
While I played Duke Nukem 3D and Sonic R on the Saturn, the right trigger buttons went reversed! In the game, there's TR as TL and TL as TR. I did the right game controls edit but, can you fix this control issues?

**Comment by clobber** [comment]
https://github.com/OpenEmu/Mednafen-Core/commit/8c3211de0b98aa523042e5f49b6a8f249d8ad9d2

Fix available as of the Mednafen 1.24.1 core plugin. Thanks for reporting.
