### ISSUE TITLE
Intermittent Sound / No Sound with Steinberg UR-12 USB Audio Interface 

### ISSUE THREAD

**Issue by neosquid** [OpenEmu/OpenEmu#4027]
During OpenEmu emulation, game sound is heard with with long intervals of silence, or none at all. Tested with Arcade core and Mednafen PSX 1 emulation. During using OpenEmu, I'm unable to access System Preferences  ' Sound'  option, window appears blank, or freezes up. 

- OpenEmu Version: 2.21
- macOS Version: 10.14.6 Mojave

**Comment by mrvacbob** [comment]
Well, System Preferences definitely shouldn't freeze. Please report that to Apple using Feedback Assistant as I suspect this is an OS issue.

Can you try with Catalina?

**Comment by neosquid** [comment]
Problem seems to have resolved itself somehow.
