### ISSUE TITLE
Outrun 2019 Music slowdown

### ISSUE THREAD

**Issue by colson97** [OpenEmu/OpenEmu#4032]
When I was playing Outrun 2019 on the Genesis, the music slowdown on the emulation bad. Here's the real example: 

http://23.237.126.42/ost/outrun-2019/avboedfr/01%20hot%20fire.mp3

Can you fix this sound issue?

**Comment by clobber** [comment]
`OutRun 2019 (USA).md) = 402a6b80a138eefc426b27c24d4aa3f5`

Sounds just fine here. Perhaps you are playing the Europe/PAL version or using a Shader that your GPU cannot run at full speed.
