### ISSUE TITLE
Xbox Elite series 2 controller

### ISSUE THREAD

**Issue by newcontender** [OpenEmu/OpenEmu#4033]
Summary of issue

Hello everyone,

I am a big fan of this application as I have been using it for years and I am constantly pleased. Recently, I purchased a new Xbox Elite 2 controller. This is my first experience with an Elite controller and using it on OS X for the first time as well.

I understand drivers may be an issue with Open Emu not being able to detect this controller. I have installed the latest driver via this link which was provided on your Github: https://github.com/360Controller/360Controller
 
Although, it still is not showing up in Open Emu either via Bluetooth of USB. Forgive me I am a noob at all this but I believe Xbox controllers are supported via Bluetooth out of the box? I am able to use it via Bluetooth in Steam without any issues.

Has anyone been able to get this new Elite 2 controller working with Open Emu and if so, what steps were taken? I would appreciate any help and once again thanks to the developers of this fantastic application. If you require any further information please let me know.

System Info: 
OS X Catalina (latest version)
Mac Mini 2018

**Comment by MaddTheSane** [comment]
The TattieBogle wouldn't influence the Bluetooth part of the controller. And, IIRC, Elite Controller support wasn't working the last time I looked.

Your best bet with support would be Bluetooth mode.

**Comment by newcontender** [comment]
Ah, thanks for your response. Bluetooth is actually my preferred method of playing. How would I go about getting Open Emu to recognize the controller when it is paired via Bluetooth?

**Comment by newcontender** [comment]
There was a build of the TattleBogle driver posted on their github and now the Elite 2 works fine with OpenEmu. Not sure how frequent the devs post on here but I am willing to offer any testing, if necessary, for the Elite 2 Bluetooth support.
