### ISSUE TITLE
Why access to all keyboard strokes on OpenEmu

### ISSUE THREAD

**Issue by Solitarywolf64** [OpenEmu/OpenEmu#4034]
Why does OPenEmu want full access to all keyboard strokes in all programs?

**Comment by clobber** [comment]
This has already been covered before in other issues and in the [release notes](https://openemu.org/rnotes/2.1.1.html):

>IMPORTANT: Due to new security rules in macOS 10.15 Catalina, in order for keyboard input to work you MUST grant OpenEmu "Input Monitoring" access in the Privacy pane of Security & Privacy preferences.

**Comment by Solitarywolf64** [comment]
This still does not explain why it needs access to all of my keyboard strokes even when I am no using the program.  Is it grabbing sensitive data? Passwords, etc?

**Comment by clobber** [comment]
>when I am no using the program

You seem confused. OpenEmu is not "accessing" all of your keyboard strokes when you are not using it. Stop wasting our time and do the research on your own. It's amazing that you've given Google, Facebook, Twitter and yes, even Apple all of your data without question (they know what applications you have installed on your machine, what you download and what you search for) but then you come beating down our door over a non-issue. OpenEmu's input subsystem has not changed and still functions the same way it always has, whether you are using macOS 10.14 or the shiny new macOS 10.15. How else do you think the application can respond to both keyboard and gamepad inputs at the same time, especially for computer-based systems? Now, enough pestering already.
