### ISSUE TITLE
Arcade ROMS doesn't open 

### ISSUE THREAD

**Issue by ourcilleon** [OpenEmu/OpenEmu#4035]
Last week I can run all my roms, today I opened OpenEmu and almost all the roms shows an error related with required files missing, I reimported the roms but nothing happened, this are some errors in different roms. Nothing has changed in my computer since last week, what can I do to solve these issues?

Cadillacs and Dinosaurs 

Cadillacs and Dinosaurs (World 930201) (dino.zip) requires:
dino.zip  	- INCORRECT SET
qsound_hle.zip  	- INCORRECT SET
These ROMs must be from a MAME 0.215 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files.

KOF
The King of Fighters 2000 (NGM-2570 ~ NGH-2570) (kof2000.zip) requires:
neogeo.zip  	- INCORRECT SET
These ROMs must be from a MAME 0.215 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files._

- OpenEmu Version: 2.1.1
- macOS Version: Mojave 10.14.6

**Comment by clobber** [comment]
>what can I do to solve these issues?

Actually read the message and follow the directions, maybe? The OpenEmu MAME core plugin was updated to MAME 0.215 last week, so you are required to be using ROMs from a MAME 0.215 ROM set, just as the message tells you. Surely that message isn't too hard to understand?

It's not the job of us or OpenEmu to educate you on how MAME works. That's going to have to be on your own.
