### ISSUE TITLE
>when I am no using the program

### ISSUE THREAD

**Issue by Solitarywolf64** [OpenEmu/OpenEmu#4036]
>when I am no using the program

You seem confused. OpenEmu is not "accessing" all of your keyboard strokes when you are not using it. Stop wasting our time and do the research on your own. It's amazing that you've given Google, Facebook, Twitter and yes, even Apple all of your data without question (they know what applications you have installed on your machine, what you download and what you search for) but then you come beating down our door over a non-issue. OpenEmu's input subsystem has not changed and still functions the same way it always has, whether you are using macOS 10.14 or the shiny new macOS 10.15. How else do you think the application can respond to both keyboard and gamepad inputs at the same time, especially for computer-based systems? OpenEmu is free and open source software, so you are in return free to audit the code if you believe your data is somehow being slurped while you play Super Mario. Now, enough pestering already over Apple's latest security theatre. Go ask them about it.

_Originally posted by @clobber in https://github.com/OpenEmu/OpenEmu/issues/4034#issuecomment-555225194_

**Comment by Solitarywolf64** [comment]
Fuck YOU.

**Comment by clobber** [comment]
hue hue hue
