### ISSUE TITLE
Operation Wolf open emu 

### ISSUE THREAD

**Issue by theblackpig75** [OpenEmu/OpenEmu#4039]
I have Operation Wolf working on Open Emu set the control on my game pad however it only seems to have four way direction. 

Is it possible to use a light gun on open emu?

**Comment by clobber** [comment]
Um, that game was ported several systems. Which one are you talking about?

**Comment by theblackpig75** [comment]
Arcade

**Comment by clobber** [comment]
As noted before, Arcade is still “experimental” and unsupported. It does not have lightgun support yet.
