### ISSUE TITLE
Can't connect two controllers with OpenEmu (macOS Catalina)

### ISSUE THREAD

**Issue by pr1m0x** [OpenEmu/OpenEmu#4043]
Hey, as the heading says: I am not able to make a second controller (I have 2 ps4 controllers and connect via bluetooth) work. Single player games with just one controller are working fine.

I already changed and toogled the input-monotoring.

Thanks for help, and great work! 🔥

**Comment by clobber** [comment]
Need to know exactly which models. Screenshot the "Input:" dropdown menu in Controls Preferences if you have to.

**Comment by kuthair** [comment]
Hi,

Thanks for the link to this issue.

I am having this same issue after upgrading to Catalina (final).

I'm using macOS Catalina 10.15.2.

I have two DualShock 4 controllers successfully paired with the OS. I can get 1 or the other to work with OpenEmu but not both at the same time.

I've tried restarting the OS, resetting and repairing both controllers, and reinstalling OpenEmu.

It was working flawlessly before the upgrade to Catalina.

thanks!
-Kuthair

![openemu_controllers](https://user-images.githubusercontent.com/7365514/71049340-0547b400-2110-11ea-9e39-83bee2ccfe09.png)

**Comment by clobber** [comment]
@kuthair Right — two different PS4 Dualshock 4 models (one is the revised model) with slightly different HID profiles. This issue is fixed for next release. In a day or two, I will provide you with a test build so you can confirm.

**Comment by kuthair** [comment]
Awesome! Thank you!

**Comment by clobber** [comment]
@kuthair please test: https://send.firefox.com/download/5576844b5bc3daf5/#GN872buu222p2DU5z0UAig

**Comment by kuthair** [comment]
Yes! The 2 controllers are working again... thank you!

I will bang away at it for a few days and let you know if we come across any issues.

**Comment by clobber** [comment]
Officially fixed as of OpenEmu 2.2.
