### ISSUE TITLE
OpenEmu Gamecube Lag

### ISSUE THREAD

**Issue by xtailsdoll** [OpenEmu/OpenEmu#4045]
Recently I have gotten the dolphin cores for OpenEmu so I could play Gamecube games, but all the games I have installed for it tend to lag a lot. if anyone has any tips on how to stop the lag please let me know.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Usage of [experimental and WIP](https://github.com/OpenEmu/OpenEmu/wiki/Console---Core-Plugin-Status-&-Wishlist) core ports are strictly unsupported and have no ETA."

Your machine is probably too weak. Go use their standalone app.
