### ISSUE TITLE
Number of games

### ISSUE THREAD

**Issue by jazzybeat** [OpenEmu/OpenEmu#4046]
Summary of issue
It's not possible to know easily how many games there are in each console.
Can you please add an indicator on the left sidebar to show how many games are in each console.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
Been requested before somewhere but we have no interest in adding it. We want to keep UI clutter down. Check the Game Library folder if you really must know.
