### ISSUE TITLE
Have you read the guide?

### ISSUE THREAD

**Issue by jazzybeat** [OpenEmu/OpenEmu#4047]
Summary of issue
This annoying message shows up after opening 5 empty list views. 
"Disc-based games have special requirements. Please read the disc importing guide."

Since there is no indicator showing how many games there are it would be nice if perhaps this message stops appearing if you tap 2 times dismiss.

Thanks
 

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
Definitely not making that message suppressable - that will just lead to users hiding it the very first time and then never reading the Disc Import guide (we have enough experience to know this). It only appears for empty libraries that support discs, so if you don't like it then just hide the library itself from the sidebar (right click)... or add some games into it. A trivial matter.
