### ISSUE TITLE
Duplicated Consoles and Collections

### ISSUE THREAD

**Issue by atb7** [OpenEmu/OpenEmu#4048]
# Issue

I keep my OpenEmu Game Library on an external volume. Around the time I updated to v.2.1.1, I had issues with my library being detected and I apparently corrupted the DB files in the process. I can't recall the exact steps I did to cause this, but I used the "Change" and "Reset" library buttons a few times as the paths were jumping between my local and external drives.

Now my DB is a mashup of a clean library and my existing one. Below is how the UI looks. My existing library and collections appear to function normally; however, I'm left with one duplicate console for each entry and a duplicate "Recently Added" collection.

Any way to repair this or should I simply hide the duplicate consoles and live with it?

<img width="211" alt="duplicate_entries" src="https://user-images.githubusercontent.com/53662954/69921250-15d80900-1445-11ea-801b-cc3b5566d720.png">

<img width="418" alt="duplicate_libraries" src="https://user-images.githubusercontent.com/53662954/69921319-76674600-1445-11ea-931f-14ae317e19bd.png">

# Debugging Information

- OpenEmu Version: 2.1.1
- macOS Version: 10.15.1

**Comment by clobber** [comment]
Hmm would be interesting to know how to replicate that. Anyway, to resolve this what you really want to do is rename or delete your `Game Library` folder in `~/Library/Application Support/OpenEmu/`  (Follow guide [here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) to access the hidden-by-default user Library folder.), and then reimport all your games.

**Comment by atb7** [comment]
Sure, I can go this route. I was reluctant since I will have to manually import the games to a fresh library, re-add all (custom) artwork, and recreate my custom collections.

I regret not backing up my DB files before clicking the Change and Reset buttons. Part of the issue is that I was not sure what path to use for the library (e.g.., OpenEmu, OpenEmu/Game Library, or something else). And if I was in `~/Library/Application Support/OpenEmu/Game Library` and I changed it to an external location `/path/OpenEmu/Game Library`, then I was left with `/path/OpenEmu/Game Library/Game Library`. I caused corruption somewhere with all the button clicking.

I'll stick with manually recreating the library from a fresh instance, as mentioned above. Thanks for the feedback and support.

**Comment by cktse** [comment]
I am having exactly the same issue, trying to re-open an existing game library on an external volume after reinstalling OpenEmu on a new machine.

**Comment by julienbfabre** [comment]
Same issue here as well, just installed openemu on a new laptop, my lkibrary is on an external drive, pointed the library to the drive, all games show up but i have a duplicate list of consoles and i cant even turn them off, any ideas?
