### ISSUE TITLE
No-Intro NES set Headered vs Unhedeared

### ISSUE THREAD

**Issue by Diegus83** [OpenEmu/OpenEmu#4049]
I searched archive.org for a no-intro nes rom set and saw two different versions available, with the same date (20191022-042847) but one is market as headered and the other one as unheadered.
I haven't been able to find any info on the wiki as to whether one version is preferred over the other or it is indifferent which one I use. 

Update to add extra information:
I checked this website that I have seen quoted before
https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=0118

And got both versions of the game from archive.org. The crc32 and size correspond to the "unheadered" version but upon importing it, this rom gets no artwork and fails to launch with an Invalid File error message.
The headered version on the other hand gets the proper artwork and launches fine so I guess the "headered" set is the way to go but since the checksum for this version is not included on the cited website, is there another way to verify the integrity of the rom set?

**Comment by clobber** [comment]
Thanks for asking. You want the "headered" version of the ROM(s). The header tells the emulator important details about the ROM and it will not load without one. The checksum is the ROM *without* the 16 byte header, so don't worry about that. Besides NES/Famicom, other systems that also require headered ROMs are Atari 7800, Atari Lynx as well as Famicom Disk System ROMs. That's all.

**Comment by Diegus83** [comment]
Thanks so much for the clarification. I hope this information helps other people.
