### ISSUE TITLE
Couldn’t communicate with a helper application. 

### ISSUE THREAD

**Issue by Bucs4Life** [OpenEmu/OpenEmu#4051]
Summary of issue
I try to open a normal LeafGreen game for GBA and it gives me this message: "Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again." I've tried resetting my computer, the program, reinstalled the program, reinstalled the game and still nothing. I noticed this only affects my GBA games, as my DS games load up just fine. I was even playing the same GBA game a few days ago and it was working just fine which was the weird part. I didn't touch or delete anything and I can't find help from anywhere else. MY current mac version is macOS 10.13.6 My current OpenEmu is 2.0.6.1 please help!

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
