### ISSUE TITLE
Bluetooth Support for Elite 2

### ISSUE THREAD

**Issue by newcontender** [OpenEmu/OpenEmu#4053]
Hello,

What steps would have to be taken in order for OpenEmu to recognize this controller when it is paired with a Mac via bluetooth. 

Would it simply require a xbox wireless receiver or is there more to it than that?

I am uncertain whether to classify this as an issue or a feature support. Any clarification would be appreciated.

**Comment by clobber** [comment]
This is not our issue. Those Xbox devices are not going to work via Bluetooth on macOS, according to https://github.com/360Controller/360Controller/issues/966

Sorry, cannot help you. Use USB wired mode and the driver, or a better gamepad.

**Comment by jkr78** [comment]
According to the [360Controller FAQ](https://github.com/360Controller/360Controller#xbox-one-controllers-connected-with-bluetooth) 360Controller driver has nothing to do with it. If it is paired through Bluetooth correctly then this is app issue. 

In my case, I can pair the controller and HIDBrowser can see recognize it. But OpenEmu - not.

**Comment by newcontender** [comment]
It works via Bluetooth with Steam for me if that means anything.

**Comment by tyten** [comment]
Given that the OS has support for these devices now, can we expect support in OpenEmu?
