### ISSUE TITLE
Couldn’t communicate with a helper application.

### ISSUE THREAD

**Issue by Bucs4Life** [OpenEmu/OpenEmu#4054]
Summary of issue
I try to open a normal LeafGreen game for GBA and it gives me this message: "Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again." I've tried resetting my computer, the program, reinstalled the program, reinstalled the game and still nothing. I noticed this only affects my GBA games, as my DS games load up just fine. I was even playing the same GBA game a few days ago and it was working just fine which was the weird part. I didn't touch or delete anything and I can't find help from anywhere else. MY current mac version is macOS 10.15.1 My current OpenEmu is 2.1.1, both are which the most up to date for each respective software. please help! thank you in advance.

**Comment by clobber** [comment]
>MY current mac version is macOS 10.15.1 My current OpenEmu is 2.1.1

Are you *sure* you are running the latest? Your previous issue opened just 12 hours ago, which was verbatim for this one, stated macOS 10.13.6 and OpenEmu 2.0.6.1.

Try the following steps found here first: https://github.com/OpenEmu/OpenEmu/issues/3960#issuecomment-516665621

**Comment by Bucs4Life** [comment]
Yes, I spent yesterday updating both my computer and openemu to the latest update after you did reply to me yesterday

**Comment by Bucs4Life** [comment]
UPDATE: I redownloaded the core plug-in and it fixed thank you so much. Yes my issue was the same as his the ds games and other were working just fine! THANK YOU!!!
