### ISSUE TITLE
Games open to blank screen, when restarted or quit, error message flashes up 

### ISSUE THREAD

**Issue by mesaverda** [OpenEmu/OpenEmu#4056]
This is the error message that flashes up. Attempting to play Nintendo DS Games. Mac OS version is 10.15.1, OpenEMU is on latest version as well. Attached is both error message and the picture of the blank screen before it

Text of error message is
"Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again"

![Snip20191205_2](https://user-images.githubusercontent.com/58554396/70231466-4a540980-1752-11ea-8eea-14b23311edd3.png)

![Snip20191205_1](https://user-images.githubusercontent.com/58554396/70231291-f34e3480-1751-11ea-9c60-14533e79374a.png)

**Comment by clobber** [comment]
Lots of possible issues here, and probably ones that are outside of our control (bad dump or DeSmuME compatibility bug), but let's try the following first: 

Steps to follow:

* Re-download the DeSmuME core plugin.
  1. Close the app
  2. Open `~/Library/Application Support/OpenEmu/Cores`  (Follow guide [here](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) to access the hidden-by-default user Library folder.) and delete `DeSmuME.oecoreplugin`
  3. Open the app
  4. Go to OpenEmu > Preferences > Cores and hit install for DeSmuME.

* If that doesn't resolve it, try launching the game without restoring the autosave at launch. 
    1. In the app, go to OpenEmu > Preferences > Library, click "Reset warnings"
    2. Open your game and click "No" when prompted to "Continue where you left off"

* If still not working, get output from Console.app.
  1. [Spotlight search](https://support.apple.com/en-us/HT204014) (magnifying glass in the upper right corner on your screen - it's how one finds files and apps on their Mac). You click it and type Console and press enter.
  2. Filter the search for `OpenEmu` and press enter, click "Clear"
  3. Then try and launch your game and wait for output.
  4. Copy and paste all the console output back here.

**Comment by mesaverda** [comment]
None of those worked

These are the errors 
- Failed to copy signing info for 74389, responsible for file:///Applications/OpenEmu.app/Contents/MacOS/OpenEmu: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"

- internal_TCCCreateDesignatedRequirementIdentityFromMessage: Refusing TCCCreateDesignatedRequirementIdentityFromAuditToken (kTCCServiceAppleEvents) RESP:{ID: <ID of InvalidCode>, PID[74389], auid: 501, euid: 501, responsible path: '/Applications/OpenEmu.app/Contents/MacOS/OpenEmu', binary path: '/Applications/OpenEmu.app/Contents/MacOS/OpenEmu'}, ACC:{ID: <ID of InvalidCode>, PID[74392], auid: 501, euid: 501, binary path: '/Applications/OpenEmu.app/Contents/Resources/OpenEmuHelperApp'}, REQ:{ID: com.apple.appleeventsd, PID[332], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}: unable to compute designated requirement for: file:///Applications/OpenEmu.app/Contents/MacOS/OpenEmu.,

- AddInstanceForFactory: No factory registered for id <CFUUID 0x7fadb8d4ba90> F8BB1C28-BAE8-11D6-9C31-00039315CD46

**Comment by clobber** [comment]
Those are not the "errors" -- you need to post the entire log with "OpenEmu" filtered and NOT selectively copy and paste lines out of the log. There should also be a crash log that is being generated.

The fact that your game crashes is probably indicative of a bad dump or DeSmuME compatibility bug, so that would be out of our hands.
