### ISSUE TITLE
[Feature Request] DerKoun's "HD mode 7" / "bsnes-hd"

### ISSUE THREAD

**Issue by thekryz** [OpenEmu/OpenEmu#4058]
In spring 2019, DerKoun released a bsnes [mod to clean up Mode7](https://arstechnica.com/gaming/2019/04/hd-emulation-mod-makes-mode-7-snes-games-look-like-new/) and thereby enhance Mode7 visuals immensely. It's currently in its [9th](https://www.reddit.com/r/emulation/comments/cque6n/bsneshd_beta_9_bsnes_1073_hd_mode_7_and/) [beta](https://github.com/DerKoun/bsnes-hd/releases).
Byuu, the creator of bsnes, integrated the HD Mod into [bsnes in fall 2019](https://www.youtube.com/watch?v=H6u7Nk6_L50). 

I would love to see this feature in OpenEmu! Would that be possible?

Example pictures / videos:
- [Terranigma](http://www.framecompare.com/image-compare/screenshotcomparison/EBF1NNNU)
- [Super Mario Kart, Pilot Wings & F-Zero](http://www.framecompare.com/image-compare/screenshotcomparison/EB9MNNNU)
- [F-Zero in Widescreen](https://preview.redd.it/w82w2oeoj2x21.png?width=1538&format=png&auto=webp&s=b80e53631b96c2a063872fdfcd4aa3d67d792b6f)
- [Chrono Trigger (Ending)](https://www.youtube.com/watch?v=Ss49vVbULOQ)
- [Lock On](http://www.framecompare.com/image-compare/screenshotcomparison/EBFCNNNU)
- [Super Soccer](https://imgur.com/a/3E4mAER)
- [Zelda: A Link To The Past](https://i.imgur.com/LIAZBXg.png), ([2](http://www.framecompare.com/image-compare/screenshotcomparison/EB9CNNNU))
- [ActRaiser 2](https://www.youtube.com/watch?v=f5-37rvampo)

Edit: More examples

**Comment by clobber** [comment]
You're in luck. Our old [BSNES core](https://github.com/OpenEmu/BSNES-Core) has been updated (still some issues and functionality to resolve), but you should see this available in a future OpenEmu update as we recommend users to transition away from the old Higan core.
