### ISSUE TITLE
I can't Install MAME Core

### ISSUE THREAD

**Issue by gabrimax** [OpenEmu/OpenEmu#4064]
Hey, I have an iMac El Capitan 10.11.6 and used to play on OpenEmu Experimental, where MAME works fine.

But I formatted the Mac recently, and when I tried to install OpenEmu again (I used version 2.0.9.1, which is the last one that works on El Capitan, I think), the option to install MAME's core doesn't appear. The name "Mame" appears in the Core section, but the "Install" button doesn't appear. I tried to download other versions, tried to reinstall, and I still can't play MAME. Also, if I try to run a ROM in the Mame section, OpenEmu says I need to install the MAME core, and if I accept the installation there will only be a box saying it is being downloaded, but the download does not start.

![Screen Shot 2019-12-16 at 3 39 04 PM](https://user-images.githubusercontent.com/31581005/70941315-f20ee880-202a-11ea-9ddc-746575201871.png)

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

The latest MAME core plugin require macOS 10.14 at the minimum.
