### ISSUE TITLE
Scanlines dissapeared on version 2.1.1

### ISSUE THREAD

**Issue by frognum** [OpenEmu/OpenEmu#4065]
I updated to the current version (2.1.1), and noticed that the shader "Scanlines" from the previous ones have been removed.

Instead, it was added some weird looking shaders like VCR with a lot of noise ... 

I'm looking for a good and clean scanlines effect. Any suggestions?

**Comment by clobber** [comment]
>Any suggestions?

Actually check the shaders and explore the app a little bit... 

There are many great **configurable** CRT and NTSC shaders available to achieve your desired look.
