### ISSUE TITLE
Updates to the wish list on the wiki

### ISSUE THREAD

**Issue by shinra-electric** [OpenEmu/OpenEmu#4066]
These are some new(-ish?) emulators that are not mentioned in the wish list:

PlayStation 3 - [RPCS3](https://github.com/RPCS3/rpcs3)
Who doesn’t want this? Has a Vulcan backend, and preliminary support for MoltenVK and gfx-rs translation layers

Commodore Amiga - [vAmiga](https://github.com/dirkwhoffmann/vAmiga)
Supports Metal, by the same guy who made VirtualC64. Currently incomplete. 

Nintendo Switch - [Yuzu](https://github.com/yuzu-emu/yuzu)
Now has a Vulcan backend. 

PlayStation Vita - [Vita3K](https://github.com/Vita3K/Vita3K)
Has a Mac client, uses OpenGL

PlayStation 4 - [Orbital](https://github.com/AlexAltea/orbital)
This one is nowhere near functional, but it’s being developed by a respected member of the PS4 jailbreaking/homebrew community. Definitely one to watch in the future.

**Comment by clobber** [comment]
No... these are all pre-alpha and barely play games, so not something we're going to invest any time in porting and maintaining yet -- especially the systems with games still sold in stores.
