### ISSUE TITLE
GameCube Controller config missing

### ISSUE THREAD

**Issue by gingerbeardman** [OpenEmu/OpenEmu#4069]
GameCube Controller config missing

ps: I know you said this core is unsupported

# Steps to reproduce

1. Open Preferences
1. Try to configure buttons on a GameCube controller

# Expected Behavior

1. Should be listed

# Observed Behavior

1. Is not listed

# Debugging Information

- OpenEmu Version: 2.2 (6096.40-g3b560b8c-Release)
- macOS Version: 10.14.6 (18G2022)

ps: thanks for adding this core!

![Screen shot 2019-12-28 at 10 08 23](https://user-images.githubusercontent.com/49612/71542093-16879080-295a-11ea-8b64-5e84b8834193.png)

**Comment by gingerbeardman** [comment]
Oops, it's listed without the Nintendo prefix.

**Comment by gingerbeardman** [comment]
Given #4114 it seems GameCube is easy to miss when it's not listed alongside the other Nintendo platforms. IMHO

**Comment by clobber** [comment]
Thanks for the valuable feedback. We'd better move Famicom Disk System, Game Boy, Game Boy Advance, Super Nintendo AND Virtual Boy too, otherwise some idiot will never find those!
