### ISSUE TITLE
Arcade (MAME) not recognizing Player 1 Buttons 1-6

### ISSUE THREAD

**Issue by digamejh** [OpenEmu/OpenEmu#4070]
After upgrading to OpenEmu Experimental Version 2.2 and starting an Arcade (MAME) game, the directional, Insert Coin, Start, even Rewind buttons are working (thank you for that!), but the standard Player 1 Buttons 1-6 are not being recognized by any game I try.
I've tried re-mapping the buttons, and the Controls window recognizes my button presses, but still the problem persists once I return to the game.

Interestingly, this seems to only affect Player 1.  Player 2's inputs all seem to work fine in-game.

Steps to Reproduce:
* Start an arcade (MAME) game
* Press the Insert Coin and Start buttons to start the game as Player 1
* Notice how the Player 1 directional buttons work in-game (among others) but Player 1's action Buttons 1-6 do not.
* You can try re-mapping the Player 1 buttons in the "Controls" section of Preferences, but this will not fix the issue.

Debugging Information
OpemEmu version 2.2 Experimental
MacOS version 10.14.6

**Comment by clobber** [comment]
Cannot replicate. Player 1 controls work just fine here, both keyboard and gamepad. Perhaps your issue is with a particular gamepad (you did not clarify) or something else unrelated to OpenEmu.

**Comment by digamejh** [comment]
Update for anyone who has the same issue: I fixed the problem myself by launching my standalone MAME and re-mapping the Player 1 buttons there.

**Comment by clobber** [comment]
Huh? What would standalone MAME have to do with the OpenEmu core port?
