### ISSUE TITLE
Updated OpenEmu, GameCube console is missing

### ISSUE THREAD

**Issue by adwight0430** [OpenEmu/OpenEmu#4072]
I updated OpenEmu, and was able to see the GameCube console on the left hand side, but it crashed a second later. I tried to open OpenEmu again, but the GameCube was missing. I tried updating again, and I was told that I had the most recent form of OpenEmu, 2.2. I deleted and downloaded OpenEmu multiple times, to no avail. I shut down and restarted my computer, but the problem still persists. Is there any way I can fix this problem? I'm on MacOS 10.14.4.

**Comment by billkings95** [comment]
@adwight0430, I had that problem too. 

Solved it by uninstalling the app completely using [AppCleaner](https://freemacsoft.net/appcleaner/) and restarting the Mac. After that I installed OpenEmu again and it worked.

Another thing that may be happening is that the GameCube core is not installed. Check if in the app Preferences, the dolphin core is installed in the Cores tab.

Best.

**Comment by clobber** [comment]
Uh, you’d just need to right click on “Consoles” in the sidebar to enable the library or do it in Preferences.
