### ISSUE TITLE
OpenEmu is non-responsive when starting emulation, won't stop emulation or quit without a force quit.

### ISSUE THREAD

**Issue by GOKU643** [OpenEmu/OpenEmu#4077]
As of this morning, OpenEmu was working fine. I tried using it again just now and no matter what rom I attempt to run, it 

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Open the program.
2. Select any rom to start emulation.

# Expected Behavior

1. Open ROM and the game starts playing.
2. Emulation stops when I either turn off the emulation or quit the program.
3. When I quit the program, I expect it to stop running.

# Observed Behavior

1. Open the program.
2. Select any rom to start emulation.
3. Emulation screen is black, does not load.
4. When I attempt to stop emulation, the window stays up despite clicking on the option to confirm my choice in the popup window.
5. Program won't quit either. I wouldn't describe as frozen since I can click on options and such.

# Debugging Information

- OpenEmu Version: 2.2
- macOS Version: OS Mojave 10.14.6

**Comment by clobber** [comment]
>Program won't quit either.

Not enough details to go on here. Maybe `OpenEmuHelperApp` crashed and is stuck, also needing a Force Quit (check Activity Monitor). Restart your Mac to see if that fully resolves your issue.

**Comment by GOKU643** [comment]
No dice. The openemuhelperapp was quitting at the same time along with the OpenEmu application. I was able to resolve the matter by downgrading to version 2.1.

**Comment by clobber** [comment]
That’s not a resolution — there is nothing in v2.2 that could be a problem. Try a restart of your machine first to rule out your GPU drivers or something else on your machine being in a weird state.
