### ISSUE TITLE
Audio Device Crashing

### ISSUE THREAD

**Issue by bumpgoose** [OpenEmu/OpenEmu#4080]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

When I change my audio device to an aggregate device that picks up desktop audio, OpenEmu freezes and is unable to close. I have to go into activity monitor to force quit. This only ever happens when I use an aggregate audio device that picks up the desktop audio from OpenEmu. Once OpenEmu is closed and I reopen it, it will allow me to choose a game but upon opening it's frozen and won't close again. I've tried restarting my computer too but it doesn't do anything, it only comes back when I choose a different audio device. So I'm basically unable to record/stream OpenEmu with the desktop audio. Whenever I use any other audio device it works fine.
(btw openemu has been perfect and this is the only issue I've come across, thank you for making it possible to emulate on the mac!) 

# Observed Behavior

OpenEmu freezes, leaving me unable to put any controller input. Whenever I hit close, the screen remains.

# Debugging Information

- OpenEmu Version: Latest (2.2)
- macOS Version: 10.14.6

**Comment by SuperbFrog** [comment]
I'm on 10.15.2 and having this same issue when I try to start a game with _Multi-Output Device_ set as the audio device. My workaround for now has been to use version 2.1 and start the game with my normal audio device selected, and switch to the Multi-Output once the game starts.

**Comment by clobber** [comment]
This is pretty much the same as #4055 

Post details and crash logs in that issue instead.
