### ISSUE TITLE
MAME:Pac-Land: Can't make Pacman walk

### ISSUE THREAD

**Issue by fedekrum** [OpenEmu/OpenEmu#4081]
Mame : Pac-Land Issue.
I can't make pac-man walk forward nor backward, but I am able to insert coin, select the trip, and even jump.
I try with USB gamepad and with keyboard. None work.
I re downloaded the rom....same thing.
I have erased ALL prefs from OpenEmu....nothing !!
It use to work.
Same rom works on Retropie with no problem.
All other games work well.

# Steps to reproduce
1. Asign keybord keys or joystick to Arcade Controllers
2. insert coin
3. Try to make Pac-Man walk to the right (It would not)
4. Try to jump with trigger (it will)

# Expected Behavior
Pac-Man must walk right.

# Observed Behavior

1. Pac-Man can't walk

# Debugging Information
- OpenEmu Version: 2.2
- macOS Version: Catalina
- ROM: paclandm.zip . (md5: 5c01069416161b7c57fd8a2bb82189a0)

**Comment by clobber** [comment]
> It use to work.

This isn’t an issue with a specific game. There are some input bugs affecting some gamepads in OpenEmu 2.2. Switch back to 2.1.1 for now.

**Comment by fedekrum** [comment]
Hi clobber.
Does not work with 2.1.1.
And as I told, keyboard is not working.
I don't think is a specific issue of v.2.2
Have you try with that rom?

**Comment by clobber** [comment]
> Have you try with that rom?

Yes. Works just fine here.

I have no suggestions for you besides the [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) guide and whatever is going on in issue #4070

**Comment by fedekrum** [comment]
last.... is the md5 of your rom the same as mine?
Thanks

**Comment by clobber** [comment]
>last.... is the md5 of your rom the same as mine?

That's irrelevant. Different compression algorithms means the checksum will not be the same. Our MAME core port is based on MAME 0.215, so that means you should be using ROMs from that set or close to it, as long as our core port still loads them. Anyway, I don't believe your problem is game-specific.
