### ISSUE TITLE
**Unable to move the controller using the keyboard** !!!!

### ISSUE THREAD

**Issue by Pituercas** [OpenEmu/OpenEmu#4082]
Everytime I try to play any game on the OpeEmu emulator of my IMAC the keyboard doesn't works, I mean it works but not on the emulator 

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Open OpenEmu
2. Go to any game (Atari, SNES, ....)
1. Start the game and I can't move the character or do anything 

# Expected Behavior

I want the controller or keyboard controller to work, its simple just enough to can play the game as I used to do 

# Observed Behavior

That what I've written happens 

# Debugging Information

- OpenEmu Version: 2.2
- macOS Version: 10.15.2

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."

**Comment by Ashino3** [comment]
same thing happens for me. but whenever i close other apps and start emu. then keyboard works.
(especially when i close terminal)
