### ISSUE TITLE
[macOS] why does OpenEmu require keyboard monitoring?

### ISSUE THREAD

**Issue by novelistparty** [OpenEmu/OpenEmu#4085]
hello!

after I upgraded to macOS Catalina, OpenEmu requires me to give it permission to "monitor input from your keyboard even while using other apps"

That's a lot of trust to grant to a program, because the potential for keylogging.

Could the devs please explain the reason this is *required*?
Could they explain when/if it *isn't* required?
What plans are there to not require this in the future? 

thank you so much!

**Comment by clobber** [comment]
A good enough explanation https://github.com/OpenEmu/OpenEmu/issues/3988#issuecomment-555687089

It’s required while using OpenEmu — it MUST be granted permission so keyboard input can work. This is indefinite and has always been the case — nothing has changed now that you have upgraded your OS. It’s simply how using lower level input API works. The message from your OS deliberately sounds scary, so if you do not understand this then please by all means do not use OpenEmu.
