### ISSUE TITLE
Only black screenshots in 2.1.1 and 2.2 on Catalina

### ISSUE THREAD

**Issue by pagooedtv** [OpenEmu/OpenEmu#4086]
# Steps to reproduce
- Start i.e. game on Game Boy or SNES
- Press CMD + T or the menu entry for creating screenshot without using shortcut 

# Expected Behavior
- Expect a screenshot
- Last time when it worked was on December 27, 2019 on the same device

# Observed Behavior
- screenshot size is 25KB and 1660 x 1066
- you can still play the games (keyboard works very well)
- screenshot is black on OpenEmu screenshot gallery and when you open the "real file" with the help of finder

# Attached files
- two screenshots, same game, different dates of creation
![Super Mario Land 2019-12-27 16 04 10](https://user-images.githubusercontent.com/59545618/71817742-2ce2ca00-3087-11ea-8c44-080c78889b57.png)
![Super Mario Land 2020-01-06 13 08 16](https://user-images.githubusercontent.com/59545618/71817743-2ce2ca00-3087-11ea-9c0e-eb448e7cfbac.png)

# Debugging Information
- OpenEmu Version: 2.2 (also on 2.1.1)
- macOS Version: 10.15.2

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4023
