### ISSUE TITLE
Unable to load Auto Save states after latest security update

### ISSUE THREAD

**Issue by bdoctrow** [OpenEmu/OpenEmu#4087]
OpenEmu is unable to load AutoSave states. The issue seems to have begun after I installed macOS Security Update 2019-007. See details below

# Steps to reproduce

1. Launch OpenEmu
2. Double-click on the game I want to launch (in this case, The Legend of Zelda: Ocarina of Time)
3. Select 'Yes' when asked if I want to start from where I last left off.

# Expected Behavior

Normally it would load the Auto-save state, at the exact moment when I last switched off the emulator while playing.

# Observed Behavior

Instead, I receive an error message saying "the operation could not be completed. No other information is available about the problem." Then the game begins from the startup screen.

Note that this only happens when I quit and relaunch OpenEmu after exiting the game. If I exit the game and restart without quitting OpenEmu first, the autosave appears to load normally.

# Debugging Information

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.13.6

Here are all of the OpenEmu messages from Console from the last time this happened:

https://gist.github.com/bdoctrow/501de211e7d0e4c8c381dddb89b26d9d

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

**Comment by bhj** [comment]
Similar issue with the same game here, except both auto-save and normal save states do not work and give the "operation could not be completed" error. Battery saves do work. Any way to diagnose further?

- macOS 10.15.3
- OpenEmu 2.2.1

**Comment by timshutes** [comment]
I am having this exact problem for the exact same game - was a fix ever discovered?
