### ISSUE TITLE
Support other graphics API for GameCube?

### ISSUE THREAD

**Issue by Hoffy17** [OpenEmu/OpenEmu#4088]
Howdy. Thanks for adding GameCube support to OpenEmu, it's been a blast so far. I know it's been in the pipeline for a while so congrats and well done!

I'm wondering if we can expect support for other graphics backends for the Dolphin core, like Vulkan? I'm not sure which API that OpenEmu is using, I would assume OpenGL however as it runs similarly to Dolphin when I'm using OpenGL, i.e. some significant buffering and lag in heavy sequences like Metroid Prime's opening cutscene.

Vulkan however runs that cutscene much smoother when I use the Dolphin emulator outside of OpenEmu. I think support for Vulkan makes sense as Apple deprecated OpenGL and will probably remove support any day now (Vulkan uses the Metal API through a translation layer).

I'm no expert though and I could be completely wrong about all of this!

My specs:

OpenEmu v2.2
macOS v10.15.2
3.5GHz Quad Core Intel Core i7
NVIDIA GeForce GTX 780M

**Comment by MaddTheSane** [comment]
In order to use MoltenVK, the translation layer that uses Metal to emulate Vulkan, OpenEmu would have to support the Metal renderer. It currently does not support Metal, but support is planned. The API has a stub for emulators to request a Metal renderer.

**Comment by sxflynn** [comment]
Could we reopen this question/issue because OpenEmu does now in fact support Metal.

**Comment by mrvacbob** [comment]
There's nothing to here for OpenEmu; the work would be in the Dolphin core.
