### ISSUE TITLE
OGG support in Genesis Plus GX

### ISSUE THREAD

**Issue by Retropotenza** [OpenEmu/OpenEmu#4089]
# Summary of issue

CD rips in ogg format doesn't play in Mega-CD

# Steps to reproduce

1. Convert a CD in ogg format, ensuring completely that the .cue file is sane.
2. Try it.

# Expected Behavior

1. CD music play as for .wav CD rips.

# Observed Behavior

1. No CD audio is heard, only vanilla Megadrive audio.

# Debugging Information

- This was raised initially in https://github.com/OpenEmu/OpenEmu/issues/2146, but with a wrong report and a wrong .cue. The issue indeed exist, is a trivial one... the Tremor library is not included and linked in the Xcode project.
- Fix and pull request in https://github.com/OpenEmu/GenesisPlus-Core/pull/3

**Comment by clobber** [comment]
Yes, aware of the pull request. Thanks. Don’t worry — we will get to it. No need for an open issue.

**Comment by Retropotenza** [comment]
Thanks, sorry for the SPAM :-)...
