### ISSUE TITLE
Randomly the entirety of OpenEmu freezes.

### ISSUE THREAD

**Issue by pureboi** [OpenEmu/OpenEmu#4091]
Every so often, no matter what game I'm playing be it Pokemon White on the DS or Persona 2 on the PSP, the entirety of program just stops and the only way I can shut it down is using Force Quit. I can't really find what causes it or how to replicate it but sometimes touching on the game screen causes it but most of the time I'm just about to get into a boss fight and it freezes sending me back to the last time I booted up the game. I didn't see anyone else with this exact same problem but hopefully one of you guys know how to fix it. 
Thanks everyone.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - 
* "Please search before opening a new issue."
* "NDS games (especially Pokemon) may have unsolvable problems related to AP patches or DeSmuME's JIT dynarec. Alternatively, try standalone DeSmuME that has the JIT dynarec off by default which may improve compatibility."
