### ISSUE TITLE
Randomly the of OpenEmu freezes. (NOT A DS BUG)

### ISSUE THREAD

**Issue by pureboi** [OpenEmu/OpenEmu#4092]
Hello, I posted here earlier today explaining how the **Entirety** of OpenEmu crashes and that got deleted. I gave examples such as DS and PSP but it isn't limited to that with the original getting canned due to apparently me only talking about the DS emulator. It crashes on GBA, NES, and everything else resulting in me thinking the error is in the OpenEmu system and not the individual emulators. I've checked around this place and couldn't find anything like this (please excuse me if I just missed it and please link it to me). 
Some trends I've noticed before the freezes is sometimes speed up but that's entirely random and touching the game screen but not the black area surrounding it. 

Thanks for reading this again sorry if it violates some more rules, I did read them all and am trying to follow them to the best of my ability because I really want to get this fixed.

**Comment by clobber** [comment]
>and that got deleted

uh no, not deleted...

Required Information:

Please post very specific details in your original issue #4091 -- you're all over the place in this new one, without anything specific or steps to replicate a problem. If you can replicate a crash, then post steps to replicate it and a crash log. Your original issue sounds like an emulator compatibility problem, so I wouldn't be so quick to claim it's not. If something else is going on, then we will need a crash log and a known way to replicate it.
