### ISSUE TITLE
Controllers Set Up working in some games but not all (GameCube)

### ISSUE THREAD

**Issue by hjurin** [OpenEmu/OpenEmu#4095]
Setting up keyboard or PS3 controller works fine for most games (including GameCube) but not all.
I always use my PS3 controller with OpenEmu, on N64 games, NES, SNES, etc
I can always customise the controls, but here it does not work.
I don't think it is due to the game, I would say controls are on the emulator.

# Steps to reproduce
1. Download [Rayman 3 for GameCube](https://www.romsuniverse.com/download/gamecube/rayman-3-hoodlum-havoc-rom37675)
2. Set up controls in OpenEmu preferences (keyboard or PS3 controller in my case)
3. Launch the game

# Expected Behavior

1. I can select a language / navigate in the menu using my controller

# Observed Behavior

1. I just cannot use the PS3 controller.
2. The keyboard works, but not with the keys I mapped.

# Debugging Information

- OpenEmu Version: 2.2
- dolphin version: 5.0.1
- macOS Version: 10.14.6
- controller: Sony PS3 Sixaxis Wireless

**Comment by clobber** [comment]
You were likely experiencing an input bug in OpenEmu 2.2 that is now fixed in OpenEmu 2.2.1
