### ISSUE TITLE
Switch Pro Controller gets recognised as Horipad S

### ISSUE THREAD

**Issue by Fwoofito** [OpenEmu/OpenEmu#4096]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce
1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

Plug in a Switch Pro Controller and view the keybind mappings.

# Expected Behavior

1. Describe what
1. you want to
1. happen

For it to successfully detect a Switch Pro Controller

# Observed Behavior

 I am unable to actually map any buttons successfully other than pushing up on the left analog stick maps Y- and Y+ to the key you have selected and the one after it respectively

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: 6096.40-g3b560b8c-Release
- macOS Version: Catalina 0.15.2 (19C57)

**Comment by shysaur** [comment]
I cannot reproduce with my own genuine Nintendo Switch Pro Controller.

Hori manufactures and sells a wide range of licensed controllers for the Nintendo Switch, but they are not the same thing as the Nintendo Switch Pro Controller, even though they may look similar or have Nintendo Switch branding on it. Additionally, there are several online outlets which sell counterfeit Switch controllers.

Please make sure that your controller is in fact a genuine Nintendo-manufactured controlled, and not a Hori Switch-compatbile controller, or counterfeit masquerading as a Hori controller. The original Nintendo-manufactured Pro Controller is the only one explicitly supported and tested for use with OpenEmu.

Last note: if you have problems with mapping the analog sticks, rotate them in all directions before trying to map them.
