### ISSUE TITLE
Macbook Pro 13 2017 have no gamecube in emulation

### ISSUE THREAD

**Issue by tematkchv** [OpenEmu/OpenEmu#4097]
I have 2 computers, it's iMac and MacBook Pro, so i just updated emu version from github to 2.2 (normal not experimental) in imac and found out that it have gamecube simulation, but at the same time with same update to 2.2 in my laptop, openemu dosen't have gamecube emulation. How can i fix that?

**Comment by clobber** [comment]
> How can i fix that?

https://github.com/OpenEmu/OpenEmu/issues/4072#issuecomment-569552076
