### ISSUE TITLE
Intellivision Top Action Buttons

### ISSUE THREAD

**Issue by diebesgrab** [OpenEmu/OpenEmu#4098]
I'm new to Intellivision emulation (Intellivision anything, really), and I've noticed that in the control customization, there's only a binding for a single top action button—when all depictions of official Intellivision controllers that I've seen, including the one in OpenEmu itself, show two top action buttons. It seems like most games I've encountered so far seem to have identical functions for both top action buttons, but at least one does not (B-17 Bomber, which according to the manual maps the Jettison Fuel command to the top right action button, and Change Bomb Load to the top left action button, depending, I guess, on the part of the game you're currently playing).

I don't know if there are any other games that have different functions for these two buttons, but regardless it seems odd that there would be an entire input binding missing. Is this intentional or not?
<img width="654" alt="Screen Shot 2020-01-21 at 9 38 33 PM" src="https://user-images.githubusercontent.com/60165339/72860943-6c6c0180-3c96-11ea-9b07-87edc5e3cea4.png">

# Steps to reproduce

1. Open Preferences
2. Open Controls pane
3. Switch to Intellivision

# Expected Behavior

There to be two top action button bindings (left and right)

# Observed Behavior

There's only a single top action button binding

# Debugging Information

- OpenEmu Version: v2.2
- macOS Version: v10.15.2

**Comment by clobber** [comment]
Both "top" buttons are actually the same button on a real controller.

**Comment by clobber** [comment]
Looking at the [B-17 Bomber manual](https://www.gamesdatabase.org/Media/SYSTEM/Mattel_Intellivision//Manual/formated/B-17_Bomber_-_1982_-_Mattel_Electronics.pdf), it must be a typo or misunderstanding. The two top action buttons are electronically the same button.
