### ISSUE TITLE
Ability to copy the names of selected games to paste elsewhere

### ISSUE THREAD

**Issue by madhattermattic** [OpenEmu/OpenEmu#4101]
This is a feature request, to help out with the ease of collections, sorting, and other helpful data.

# Steps to reproduce

1. View a console's list of games
2. Select a group of games, or select all of them in that list

# Expected Behavior

1. Copy via the File menu or by hitting Command+C
2. Paste into a document to have a line-separated list of those games as they are named on the screen

# Observed Behavior

Paste does not work outside of OpenEmu, so the best you can do is copy the rom names in Finder to paste elsewhere, which doesn't provide proper names for most systems, only vague archive names

# Debugging Information

- OpenEmu Version: 2.2
- macOS Version: Catalina 10.15.2

Thanks for your consideration!

**Comment by clobber** [comment]
Not useful enough. You can select all of the items and drag and drop them all into a text area which will give you a full path to the ROMs, though.
