### ISSUE TITLE
Adding a "random game" button to the game library

### ISSUE THREAD

**Issue by madhattermattic** [OpenEmu/OpenEmu#4102]
This is a feature request, as a fun feature for folks with large collections and an exciting option for folks that stream gameplay or have live competitions.

# Expected Behavior

This doesn't exist yet, of course, but it would be awesome to add a button while looking at a console or collection's game list that will randomly pick and load a game from that list.

Another lowkey option would be to right click the console or collection from the lefthand menu and select a "random" option from a dropdown.

I could see this as being really useful for folks that stream or do live events that swear by OpenEmu as the best frontend. :)

Thanks for your consideration!

**Comment by clobber** [comment]
Sorry, no. Barely used niche features like these just amount to useless clutter.
