### ISSUE TITLE
Final Lap Twin (TurboGfx16) won't open

### ISSUE THREAD

**Issue by echolock** [OpenEmu/OpenEmu#4103]
Summary of issue
Tried multiple times with multiple versions of the rom. Opened fine in other emulators. 

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce
- Get a copy of Final Lap Twin
- Open it in OpenEmu (black screen)

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
Nope, cannot replicate. Both variants of the game import and load just fine. Mednafen (our core plugin) does not have compatibility bugs with TG16/PCE games.

<img width="942" alt="Screen Shot 2020-01-25 at 9 02 04 PM" src="https://user-images.githubusercontent.com/1303132/73130010-24125380-3fb6-11ea-8ab6-f6e1e01af6c9.png">
<img width="942" alt="Screen Shot 2020-01-25 at 9 02 23 PM" src="https://user-images.githubusercontent.com/1303132/73130011-2aa0cb00-3fb6-11ea-98de-bcd3c00fc0c9.png">
