### ISSUE TITLE
Keyboard no recognize on Mac OS Mojave

### ISSUE THREAD

**Issue by Tete53** [OpenEmu/OpenEmu#4105]
Keyboard no recognize on Mac OS Mojave, we can't play...

- OpenEmu Version: Open Emu 2.2.1
- macOS Version: mac OS Mojave

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
