### ISSUE TITLE
Is there a way to add borders and shaders?

### ISSUE THREAD

**Issue by sohojohn85** [OpenEmu/OpenEmu#4107]
Hello, 

I downloaded the latest version of Openemu and was amazed by the job the team has done. Phenomenal job.

I saw in the updates that it now supported third party shaders. I tried to add some in the metal format but somehow can't get them to appear on my filters menu.

Also, is there a mean to add borders instead of the 2 black borders due to the 4:3 format of TVs back then? I recently acquired a snes mini and loved the job they did with their borders.

Thanks much and again congrats.

**Comment by clobber** [comment]
Yes, there are [border shaders](https://github.com/libretro/slang-shaders/tree/master/border) available in our supported slang-shader format. We still need a wiki article to show people how to install their own via our [slang-shaders](https://github.com/OpenEmu/slang-shaders) repo. Sorry, cannot walk you through it now.

**Comment by craigerskine** [comment]
This is how I added custom shaders:
1. Download some slag-shaders. I used [these](https://github.com/libretro/slang-shaders).
2. Extract downloaded .zip into `~Library/Application Support/OpenEmu/Shaders`.
3. Enjoy.

You may have to create the Shaders folder if it does not exist.

**Comment by ron-wolf** [comment]
@craigerskine I’ve done so, where does one select the new shaders? I still just see the list of old shaders.

**Comment by craigerskine** [comment]
They show up in the Shader selector below the built-in defaults. In Prefs and in the Game HUD:
![Screen Shot 2020-02-06 at 8 33 38 AM](https://user-images.githubusercontent.com/56437/73946351-68a5c500-48bb-11ea-8d69-46e7f311c52c.png)

**Comment by sohojohn85** [comment]
Thank you, I got the shaders to work. Wondering if there are borders that cover the black bars that exist given the difference in screen size (4:3 in the past vs the 16:9 today). Thanks much!

**Comment by craigerskine** [comment]
@sohojohn85 That's called an [overlay](https://github.com/libretro/common-overlays). I don't think those are supported in OE.

**Comment by sohojohn85** [comment]
Oh ok, thanks much for clarifying
