### ISSUE TITLE
Quick save on N64 triggers Crash

### ISSUE THREAD

**Issue by piiantom** [OpenEmu/OpenEmu#4108]
Most of quick saves triggers a freeze on OpenEmu, and requires a 'force to quit'
This happened after the 2.2.1 update on Catalina

Problem also occurs when quitting the emulator (as the auto save is also performed)
Strange thing also: In quick save screenshots, some of them are vertically reversed, some are just blank

**Comment by clobber** [comment]
Cannot replicate and there is nothing in the OpenEmu 2.2.1 update that would affect Quick Saves. Post a crash log with replicable steps.

N64 emulation overall has compatibility bugs -- Mupen64Plus (the core plugin) and GLideN64 (the GPU plugin) are still in a volatile work-in-progress state which means it is not recommended to rely on save states as those can break between core plugin updates. Rely on in-game battery saves if available.

To get your N64 games in working order, load the games without restoring an autosave state on first load:

* Go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" if prompted to "Continue where you left off"
