### ISSUE TITLE
Dualshock 4 cant mapping

### ISSUE THREAD

**Issue by no-name089** [OpenEmu/OpenEmu#4110]
forgive my bad english. i work with the translator. at the bottom I write that again in German.

openemu: 2.09.1
macmini late 2012: hige sierra 10.13.6

issue:
- I connect my ds4 to the mac without problems and it is also recognized in openemu, but I cannot configure it. 
- I configured it a long time ago and don't know what has happened since then. 
- now i tried to configure my keyboard, but it doesn't work either. the esc key works with which i have now deleted the settings and can no longer get them.

in german:

ich verbinde meinen ds4 mit dem mac ohne probleme und er wird auch in openemu erkannt, aber ich kann ihn nicht konfigurieren. ich habe ihn einmal vor langer zeit konfiguriert und weiß nicht was seit dem passiert ist. jetzt habe ich versucht auch meine tastatur zu konfigurieren, was aber auch nicht funktioniert. die esc taste funktioniert mit dem ich jetzt die einstellungen gelöscht habe und sie nicht mehr herbekomme. 

![after esc](https://user-images.githubusercontent.com/34530662/73565711-6d551e00-4462-11ea-8792-3be66a3208ab.png)

**Comment by clobber** [comment]
>openemu: 2.09.1

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

**Comment by no-name089** [comment]
is not working with 10.13!

**Comment by clobber** [comment]
Upgrade your macOS.
