### ISSUE TITLE
2.1.1/mojave dualshock4 dont mapping

### ISSUE THREAD

**Issue by no-name089** [OpenEmu/OpenEmu#4111]
since someone said that it was due to highe sierra, I have now updated to mojave.

the problem persists on mojave !!!

issue:

ds4 is recognized and I can play with it, but I cannot change the keys.
I also can't change the keys on the keyboard.

what do I have to delete / edit for it to work?

![Bildschirmfoto 2020-01-31 um 23 59 08](https://user-images.githubusercontent.com/34530662/73580689-bdde7280-4486-11ea-9769-d7e60c5249e1.png)

**Comment by clobber** [comment]
>ds4 is recognized and I can play with it, but I cannot change the keys.

Works just fine here.

> I also can't change the keys on the keyboard.

Your problem is probably related to the following: 

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."

**Comment by no-name089** [comment]
"Works just fine here." doesn't get me anywhere. would be nice if someone who knew about it answered.

as already written and can be seen on the screenshot, it is recognized and I can play, but I can never re-assign keys. when i press esc on the keyboard it deletes the preconfigured one, but i cannot enter anything new. surely some plist is responsible for that, but which one?

I have also tried other ds4 and a ds3 is always the same problem.


![Bildschirmfoto 2020-02-01 um 00 21 50](https://user-images.githubusercontent.com/34530662/73581445-8a511780-4489-11ea-8672-18038ea7e12d.png)

**Comment by clobber** [comment]
I know about, I answered. I don't believe your problem is an OpenEmu issue.

Actually read the link I gave you.

**Comment by no-name089** [comment]
sorry for my post above .... but I've been trying to solve the problem for five hours now :(

yes I read it:

i have a Mac mini late 2012 withe a fresh Mojave osx on a new intern 256gb ssd.
the only "non osx" program is openemu 2.1.1.
the only program that run when I try open emu is open emu and the finder
idont have adapters, hubs or anything.
the only other bt devices ar the magic mous and the magic keyboard 

I have now tried retro arch on high sierra and it works wonderfully. but I want to continue using open emu.

**Comment by clobber** [comment]
>the only "non osx" program is openemu 2.1.1.

That is not the latest version.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

**Comment by clobber** [comment]
Sorry, I cannot help you. There is going to be something you have installed or running in the background that is interfering with input. This seems the likely case, as you said you tried multiple input devices using older versions of OpenEmu and on older versions of macOS.
