### ISSUE TITLE
Where is Gamecube?

### ISSUE THREAD

**Issue by SQUIDDYBeans** [OpenEmu/OpenEmu#4114]
There is no Gamecube input for games on Gamecube and I really wanna play smash bros melee

**Comment by SQUIDDYBeans** [comment]
I want to play smash bro's melee but there is nothing for game cube

**Comment by gingerbeardman** [comment]
It's listed on the input list as "GameCube" not "Nintendo GameCube" so it's not alongside the other Nintendo platforms.

**Comment by SQUIDDYBeans** [comment]
Thank you

**Comment by clobber** [comment]
Incredible - the most unnecessary ticket ever opened here. Use your eyes to look down the library sidebar.
