### ISSUE TITLE
How to use PyTorch as a player?

### ISSUE THREAD

**Issue by elcolie** [OpenEmu/OpenEmu#4115]
Thanks to everyone behind the project. This is great and fun software 👍 
I have seen the answer regarding `Python` script, but frankly I don't understand

I need SDK that 
1. Be able to get the entire screen to `Python`
2. `Python` be able to put key stroke to `OpenEmu`

Is it possible to do it?
If not would you mind give me your advice to work along with this?
Game engine be able to plug with `PyTorch, Keras, TensorFlow` will be awesome

**Comment by clobber** [comment]
Sorry not possible, whatever you're trying to do is outside the scope of this project. Cannot help you.
