### ISSUE TITLE
Titles of platforms should be consistent

### ISSUE THREAD

**Issue by gingerbeardman** [OpenEmu/OpenEmu#4116]
Titles of platforms should be consistent

Currently some platforms are qualified with the manufacturer name (Nintendo, Sega, Sony, etc) and others from the same manufacturer are not.

Examples
- SG-1000
- Sega Master System

One idea would be to remove the manufacturer name from listed platforms unless the manufacturer name is part of the product name (eg. Nintendo 64)

# Steps to reproduce

1. Looks at the list of platforms

![](https://user-images.githubusercontent.com/49612/71542093-16879080-295a-11ea-8b64-5e84b8834193.png)

# Expected Behavior

- Should be a predictable order

# Observed Behavior

- No predictable order

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6

# Further information

It might seem improbable but not finding items in the list happens for some of us that have to deal with dyslexia, blindness and other such disabilities. Such people are not “idiots”, they’re simply trying their best.   

#4069, #4114

**Comment by clobber** [comment]
We’re good. Next time you pester with this is a ban.
