### ISSUE TITLE
Problem with action replay codes for Yugioh games on DS. 

### ISSUE THREAD

**Issue by nygiantsfan1029** [OpenEmu/OpenEmu#4118]
None of the codes are working.  Im assuming it has to do with there being no master code for some of the games just a game ID.  For ex The game id WC 2008 is YG8E f5377a61.  IS there a way to put it in or something?

**Comment by clobber** [comment]
1. One has to be certain they are entering in the correct codes for the game and in the right format. More information on that in our [Cheat codes guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes).

2. DeSmuME (the NDS core plugin) has numerous cheat code bugs still (even as of our version 0.9.11.x), meaning if what you are entering is a valid code for your game, it might not work anyway. There is nothing you can do about this.

That's the best I can do for you.
