### ISSUE TITLE
Does OpenEmu support MAME audio Samples?

### ISSUE THREAD

**Issue by boriQA** [OpenEmu/OpenEmu#4122]
Does OpenEmu support Arcade MAME audio Samples?

If it does, where should I create a samples folder? Or on which existing folder should I place the samples?

Running OpenEmu v2.2.1 on Mac OS X Catalina

**Comment by clobber** [comment]
Yes: https://github.com/OpenEmu/OpenEmu/issues/1374#issuecomment-42960752

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."
