### ISSUE TITLE
Changing the Sensitivity of Nintendo DS D-Pad

### ISSUE THREAD

**Issue by dpearson2699** [OpenEmu/OpenEmu#4123]
When playing Super Mario 64 DS, it seems as if the D-pad isn't actually fully pressed down when pressing the corresponding key that it is mapped to (in this case I have the WSAD keys for the D-pad). I realized this because, in the game, you can also use the virtual touchpad to control the character. But when I use the virtual touchpad to control the character this way they actually run as they are supposed to, instead of just walking as they do when I use the keys for the d-pad. Is there a way to go into the DeSmuME core inside of `~Library/Application Support/OpenEmu/Cores` and edit the dead zones and/or change the percentage of how much the d-pad is "pressed down" (I'm forgetting the technical term for this). Also, I tried closing Google Chrome when using OpenEmu and it didn't change anything.

- OpenEmu Version: v2.2.1
- macOS Version: v10.15.3 (19D76)

**Comment by clobber** [comment]
No... there is no d-pad sensitivity; that isn't a thing. It's digital so it's either on/off with nothing in between. By default the character walks but you have to hold "Y" to "dash". If i remember correctly, the virtual touchpad in-game is meant to be for more precise movements. The game also has three different control modes you can play around with. Google the manual for this game if you need a better understanding.
