### ISSUE TITLE
Virtual Gamepad Feature

### ISSUE THREAD

**Issue by jcampbell05** [OpenEmu/OpenEmu#4125]
I noticed a while back there used to be an app called Joypad but it since has been removed, I am looking into if I can implement this feature into OpenEmu.

My idea is OpenEmu runs a web server which when loaded on a web browser shows the gamepad of the game currently playing.

Potentially down the line more native integrations can be added but this is my first building block.

I've already managed to modify the preferences pane as an early start but would love some pointers on how I can communicate with the currently running game.

<img width="867" alt="Screenshot 2020-02-16 at 12 37 17" src="https://user-images.githubusercontent.com/1484989/74604782-133a9680-50b9-11ea-99d5-bba238347e01.png">

At the moment I'm putting most of my modifications in the app delegate but this doesn't feel nice.

Any pointers ?

**Comment by clobber** [comment]
Sorry, no interest on this. Outside the scope of the project.
