### ISSUE TITLE
GameCube crashing

### ISSUE THREAD

**Issue by chasecott** [OpenEmu/OpenEmu#4131]
While playing games on dolphin in open emu games will randomly crash with a gray screen. Error message pops up that says cannot communicate with helper application. 

# Steps to reproduce

1. Playing any GC games 
1. Random crashes 

1. Wondering if there is a fix for this?

- OpenEmu Version: 2.2.1
- macOS Version: Catalina 10.15.3

**Comment by ibaileyc** [comment]
I have had this problem a few times as well (playing ds games). I think it happened once when I took my Airpod Pros out of my ear while a video or music is also playing in a different app. Though, I couldn't see if it crashed at that moment exactly and I've been unable to recreate this.

OpenEmu v2.2.1
macOS Catalina v10.15.3

**Comment by clobber** [comment]
If these are dolphin bugs and compatibility issues, we cannot help you. Without a crash log, there is no way to know.
