### ISSUE TITLE
Multi-disk not working with m3u on Catalina 10.15.2 and OpenEmu v2.2.1

### ISSUE THREAD

**Issue by Nicklaurence** [OpenEmu/OpenEmu#4132]
I have tried to follow the multi-disk instructions with two separate games on different platforms without success.

Case 1: PlayStation
Downloaded both discs for Chrono Cross. The following files are in a folder names "Chrono Cross":

- Chrono Cross CD1.img
- Chrono Cross CD2.img
- Chrono.Cross.NTSC.US.CD1.CCD
- Chrono.Cross.NTSC.US.CD1.sub
- Chrono.Cross.NTSC.US.CD2.CCD
- Chrono.Cross.NTSC.US.CD2.sub
- Chrono Cross.m3u

The m3u file was made using TextEdit and contains the following, formatted as plain text:
Chrono.Cross.NTSC.US.CD1.CCD
Chrono.Cross.NTSC.US.CD2.CCD

I expect that when I drag the m3u file into OpenEmu, that the game will load into the emulator, but unfortunately nothing happens.

Case 2: Sega Saturn
Downloaded all four discs for Panzer Dragoon Saga. The following files are in a folder named "Panzer":

- 042 Panzer Dragoon Saga Disc 1 of 4 (U).bin
- 042 Panzer Dragoon Saga Disc 1 of 4 (U).cue
- 043 Panzer Dragoon Saga Disc 2 of 4 (U).bin
- 043 Panzer Dragoon Saga Disc 2 of 4 (U).cue
- 044 Panzer Dragoon Saga Disc 3 of 4 (U).bin
- 044 Panzer Dragoon Saga Disc 3 of 4 (U).cue
- 045 Panzer Dragoon Saga Disc 4 of 4 (U).bin
- 045 Panzer Dragoon Saga Disc 4 of 4 (U).cue
- Panzer Dragoon Saga.m3u

The m3u file was made using TextEdit and contains the following, formatted as plain text:
042 Panzer Dragoon Saga Disc 1 of 4 (U).cue
043 Panzer Dragoon Saga Disc 2 of 4 (U).cue
044 Panzer Dragoon Saga Disc 3 of 4 (U).cue
045 Panzer Dragoon Saga Disc 4 of 4 (U).cue

As with case 1, I drag the m3u file into OpenEmu and nothing happens. I've also tried selecting it via File --> Add to Library both direct to the m3u file and at the folder level. Have also tried restarting the computer and restarting OpenEmu. The "Chrono Cross" and "Panzer" folders are both sitting in my downloads folder.

Any help would be much appreciated.

**Comment by clobber** [comment]
Case 1: The base filenames do not match up, so the problem is obvious there. Of course they won’t import.

Case 2: The cue sheets are probably bad, pointing to wrong files or a hard coded path. Common with junk rips.

The solution is to download known good dumps from “Redump” on Archive.org. You won’t have problems with CD rips after that.
