### ISSUE TITLE
games won't even scan after attempting to add them

### ISSUE THREAD

**Issue by hankada** [OpenEmu/OpenEmu#4133]
My issue just happened recently. I downloaded Openemu last night and put a few NDS games on there. Today, I tried to download PS1 games and the games didn't even scan. I then tried more NDS games, and again nothing. 
thanks.

MacBook Air 
iOS: 10.14.6
Openemu version: v 2.2.1

**Comment by clobber** [comment]
Unzip your NDS games. Presumably they are .zip or .7z with junk files in the compressed archived. Follow the import guide for anything else, especially CD games. Only use good dumps of the games from “Redump” on Archive.org. 

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing
