### ISSUE TITLE
Incorrect Set 0.217 MAME ERRoR 

### ISSUE THREAD

**Issue by Invasor12** [OpenEmu/OpenEmu#4134]
Hi my name is Angel and I have a problem with open emu experimental well the thing is was
playing with the open emu v.2.21 and there happen the Arcade version 0.217 but I don't wanna use this I wanna put back to MAME 0.149 version there have a error example I don't know what to do now please can do fix this 

Thanks!! 
- 
![Captura de Pantalla 2020-03-01 a la(s) 14 11 59](https://user-images.githubusercontent.com/61668032/75634939-deedcc80-5bc6-11ea-848d-2607cd718b45.png)

**Comment by clobber** [comment]
Sorry, only the latest core plugins are supported. If you don't like it, use MAME standalone.
