### ISSUE TITLE
Suggestion: Use more native macOS interface elements

### ISSUE THREAD

**Issue by dillonjohnbrown** [OpenEmu/OpenEmu#4137]
I would like to see OpenEmu updated to use macOS's native interface elements, in order to improve how the app fits in as a good Mac citizen. Don't get me wrong, I **love** the attention to detail and high level of polish you have put into this app, all out of the goodness of your hearts. I also love those same qualities in my Mac and the other apps I use. That is why I bring this up. 

A few examples. Sketch is a good macOS citizen superstar. Their interface is Mac through and through, while still being uniquely their own, and I believe that makes it feel even better to use.

Now with light and dark mode built into macOS, apps need to reflect a users interface theme. When I change from dark to light mode, all my apps, like Sketch, change too. You know which apps don't change? Junky apps built on Electron.

I do not want this to sound like a criticism. I'm not a coder, nor am I capable of making gorgeous illustrations like those in the Controls preferences (😍). I just hope to help where I can as both an OpenEmu and macOS fan.

**Comment by clobber** [comment]
We're already working on this...
