### ISSUE TITLE
Multi Disc Option or Change Disc Option 

### ISSUE THREAD

**Issue by littlerayy** [OpenEmu/OpenEmu#4139]
Greetings !

1. Some Games ask for us to Change Disc and there is not an option for it 
2. we need to have an option where we can change disc for the game to continue
3. Some people use another program called "Textmate" it helps them to switch discs

hope this issue is solved, we love open emu and dont forget to try your best adding Playstation2 console we cant wait

thank you , you guys the best !

- OpenEmu Version: v2.2.1
- macOS Version: Catalina 10.15.3

**Comment by clobber** [comment]
> ... and there is not an option for it 

Ummm, no... you must not understand how it’s supposed to work. 

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game
