### ISSUE TITLE
How do I update my Mupen64Plus core?

### ISSUE THREAD

**Issue by goleyeth** [OpenEmu/OpenEmu#4141]
In my never ending quest to get WWF No Mercy to work for emulation on my MacBook I have noticed that Mupen64Plus updated it's core package 2 days ago, I checked my OpenEmu for updates and it says I'm the most up to date, I am wondering if there is a way I can update the core myself or if there is going to be an OpenEmu update coming soon that will incorporate their updates as well?

**Comment by clobber** [comment]
> WWF No Mercy

This game does not work -- you cannot make it work.

>Mupen64Plus updated it's core package 2 days ago

That doesn't mean what you think it means. Any sort of activity on a repo can increment the "updated" counter and that does not mean they have a new release or code that benefits you. There is no "way" you can update OpenEmu's Mupen64Plus core plugin. There is no planned update for that plugin soon.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3715
