### ISSUE TITLE
PPSSPP Freezing - Ace Combat Join Assault 

### ISSUE THREAD

**Issue by RavenHwk** [OpenEmu/OpenEmu#4143]
I've seen similar problems proposed here, but haven't actually seen anything detailing a solution for the problem, so here goes:

While playing the game Ace Combat: Join Assault, the game will occasionally freeze after a transition (usually at the beginning or end of a mission), which will be followed by a repeating sound bug, like a broken record. If this occured only at the end of a mission, no big deal, AC:JA has autosaves so I can just restart the emulation. The issue that I have occurs right after the refueling minigame on Mission 7 (Adriatic Sea). Even if you skip the minigame, the screen goes black (as it normally does during the transition to a mission), but then it just stops. I've also experienced this following a cutscene after a mission of the game SOCOM US Navy Seals: Fireteam Bravo 3. In both games, this issue is prohibiting me from advancing any further. I am currently running MacOS Catalina, V.10.15.3, and I'm using the PPSSPP core for OpenEmu (OpenEmu is V2.2.1). Could this be caused by my not using the standalone PPSSPP Emulator? I apologize for any vagueness, but I'm not that skilled when it comes to tech, so I'm not really sure what to do here. It might just be a glitch on that one save file, but I doubt it, because a similar error occurred on a second save file, albeit after the mission had completed. On that save, I was still able to progress, but I haven't reached level 7 yet.

 Expected Behavior
Well, this one is a no brainer, I keep expecting that the Mission (or, in SOCOM's case, the post-mission cutscene) to continue, but it does not. After the fade to black, it just catches. The audio skips like the previously mentioned broken record, but the screen remains frozen.

**Comment by RavenHwk** [comment]
Edit: Operation Number 7 is not the issue, I took a different path and cleared Op.7 with no problem, but the Adriatic Sea mission (now Operation #8 thanks to the different campaign path) still has the issue. I don't know if it is an error with the Refueling minigame (takeoff and carrier takeoff minigames function fine) or with that specific mission, but any help would be welcome!

**Comment by clobber** [comment]
This is a PPSSPP emulator bug. Nothing we can do about it until they resolve it.
