### ISSUE TITLE
Riviera hangs when loading CG scenes

### ISSUE THREAD

**Issue by geraldeersteling** [OpenEmu/OpenEmu#4145]
# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.3

---

When playing Riviera The Promised Land, sometimes there are CG scenes. But during these scenes the emulator sometimes "freezes".

During such a freeze the sound is distorted and 'hangs', but weirdly I can still load a save state. OpenEmu _itself_ doesn't freeze, but the game will always freeze at the same spot.

I'm not sure what extra info I can include, but I'll gladly add any if needed.

**Comment by geraldeersteling** [comment]
I tried playing around with shaders...I have the feeling some shaders freeze at a different point, but  none seem to solve the issue (on a 2016 MBP).

**Comment by clobber** [comment]
This is a PPSSPP emulator bug. Nothing we can do about it until they resolve it.
