### ISSUE TITLE
Cannot import any games

### ISSUE THREAD

**Issue by thictacs** [OpenEmu/OpenEmu#4146]
I've tried searching for similar problems, but I was unable to find a solution, so sorry if this is a duplicate.
Also, I've only tried importing four games, so this may not be a problem for all games.

I've tried to import three Playstation games, or maybe they are Sega Saturn Games, and one that is a .iso (not sure which console it belongs to) but when I drag the .cue/.iso, or select open in OpenEmu, there was the "game scanner" message at the bottom, but after that nothing happened at all. I've dragged in the .7z file, opened it and dragged in the files that were compressed inside, yet nothing has happened at all.

I followed the CD guide and checked it matches the filename of the .bin/.img/.iso file and is in the correct case, has an extension does not contain a hardcoded path.

Thanks in advance for any help!

- OpenEmu Version: 2.21
- macOS Version: 10.14.6

**Comment by clobber** [comment]
Just download known good dumps from "Redump" on Archive.org which will be in the correct and supported format. Unzip, then import the .cue file to import your game.

>I've dragged in the .7z file

Also follow directions for [importing games](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing).
