### ISSUE TITLE
Old games doesen't work anymore

### ISSUE THREAD

**Issue by noisybox** [OpenEmu/OpenEmu#4147]
before christmas i was able to play all my roms, in the arcade section, in these days (before, and after the last upgrade) some games are not working anymore and with the following description :
neogeo.zip  	- INCORRECT SET

These ROMs must be from a MAME 0.217 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files.

Does anybody else have the same problem? what could it be?

- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/4035
