### ISSUE TITLE
Old version download for OS High Sierra 10.13.6

### ISSUE THREAD

**Issue by Jr0m** [OpenEmu/OpenEmu#4148]
My old hardware can't update to Mojave 10.14 or Catalina 10.15. 

Is there an old version of OpenEmu available for download? 

j

**Comment by ifonefox** [comment]
You can find all the old versions here: https://github.com/OpenEmu/OpenEmu/releases

**Comment by ifonefox** [comment]
2.0.9.1 was the last one to support 10.13. You can download it here: https://github.com/OpenEmu/OpenEmu/releases/tag/v2.0.9.1
