### ISSUE TITLE
Feature request: Memory Card manager for PlayStation (and other MC based systems)

### ISSUE THREAD

**Issue by ct2057** [OpenEmu/OpenEmu#4149]
It would be great to see functionality in OpenEmu that would either allow you to manage Memory Card data through the OpenEmu UI (best option), or through the emulated systems’ BIOS. 

Parsing/reading of .mcr/.psv files would be good too.

I currently have to do all my Memory Card management on a Windows machine using a bunch of other third-party apps, before copying them back to the Mac for use in OpenEmu. The process is quite tedious.

**Comment by clobber** [comment]
Mednafen, by default, creates memory cards per-game so they are never shared, making it needless to have to manage memory cards. Someone can make a standalone tool for macOS, but it's not going to be us. PCSX-R may already have one.
