### ISSUE TITLE
Master System not an option

### ISSUE THREAD

**Issue by theblackpig75** [OpenEmu/OpenEmu#4151]
I have downloaded an Master System ROM but when I drag and drop OpenEmu reports an issue, I try and resolve the issue by selecting Master System on the drop down menus but the only options I have are Arcade, Atari 26005200 Intellivision Vectrex and Videopac+.  Any ideas how to come up with more options because I haven't have been able to export lots of games.

Cheers
Paul

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing

**Comment by theblackpig75** [comment]
<img width="2560" alt="Screenshot 2020-03-21 at 14 12 59" src="https://user-images.githubusercontent.com/57136485/77231257-acb20800-6b91-11ea-8a5c-df72821b19ed.png">
I get this screen

**Comment by clobber** [comment]
Read the guide I linked. SMS games MUST be .sms and NOT .bin.
