### ISSUE TITLE
neogeo.zip - incorrect set

### ISSUE THREAD

**Issue by Stefano0712** [OpenEmu/OpenEmu#4152]
Summary of issue

Hi, i have some problem with MAME Roms. All of this Roms doesn't work and show me this message:

neogeo.zip - INCORRECT SET 
This ROMs must be from a MAME 0.217 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still request. Delete this files already imported and reimport with correct files.

I try to put this file (neogeo.zip) into library (some videos on youtube try this and work it).
I hope some people tell me a solution... 
Thanks

In the core preference of OPENEMU menu i have the MAME version 0.217
The operation system is OS X Catalina
The version of OPENEMU is V2.2.1

**Comment by clobber** [comment]
> neogeo.zip - INCORRECT SET
This ROMs must be from a MAME 0.217 ROM set.

The message is self-explanatory.
