### ISSUE TITLE
Blue Screen Crash during evolution in Pokemon Light Platinum (Ruby Hack)

### ISSUE THREAD

**Issue by rahulsurti97** [OpenEmu/OpenEmu#4153]
I'm playing Pokemon Light Platinum (Ruby Hack) and I get a blue srceen just as a pokemon is about to evolve.

## Steps to reproduce
1. Setup:
   1. Light Platinum: http://www.mediafire.com/file/198p6vc45dvh3q5/light-platinum-final.zip/file
   1. Save State: [Save-Game-3 2020-03-22 162126 -0500.oesavestate.zip](https://github.com/OpenEmu/OpenEmu/files/4366691/Save-Game-3.2020-03-22.162126.-0500.oesavestate.zip)
1. Save state includes Charmander that will evolve after 1 battle to reproduce easily

## Debugging Information
- OpenEmu Version: v2.2.1
- macOS Version: 10.14.6

**Comment by clobber** [comment]
Cannot help you with ROM hacks or possible emulator core bugs. Likely it doesn’t run on real hardware (mGBA is quite accurate compared to other GBA emulators such as VBA).
