### ISSUE TITLE
Setting controls not working for Sony PSP 

### ISSUE THREAD

**Issue by joker5bb** [OpenEmu/OpenEmu#4156]
I am unable to set controls for Sony PSP unless you visit other game device controls.
I opened Preferences > Controls and selected Sega Saturn and then Sony PSP 
Only then I can remap controls.  

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.4

**Comment by clobber** [comment]
I don’t think this is possible. Give us steps to replicate and a profile of your hardware and devices.
