### ISSUE TITLE
Control Re-mapping not working (GBA): keyboard

### ISSUE THREAD

**Issue by saads312** [OpenEmu/OpenEmu#4158]
I open the app and try to immediately change the controls from preferences, but all I can do is click on the controls, not re-map them. I try opening a game like Pokemon Emerald and then try to change the controls from the small panel at the bottom of the game, which doesn't work either. I tried closing chrome, as people said that it often interferes with it, but still to no avail.

I have used the emulator before and I used to be able to change the controls, but it is not working now. I've never used any external controller or anything like that, just keyboard. 

# Debugging Information

- OpenEmu Version: v2.2.1
- macOS Version: Mojave 10.14.1

Thanks

**Comment by clobber** [comment]
Sounds like an issue addressed in the [Input troubleshooting guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems). Also, you should update to 10.14.6 + latest Security Update.
