### ISSUE TITLE
couldn't communicate with a helper application

### ISSUE THREAD

**Issue by qllbee** [OpenEmu/OpenEmu#4161]
I got this error:
Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again.

I have an old imac 2009 27',I have updated the hardware and software.
I installed a new video card amd wx4170 (as same as radeon pro 555 or 560),full support metal.
Other games and software can run normally, but openemu can't.

I know openemu abandoned old mac with old osx system,so I updated the hardware to real support for metal.why can't I still play any game? This old imac has 32gb ram  and a metal card with 4gb,I think its performance is enough. I hope this bug can be solved  one day.

- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6

**Comment by qllbee** [comment]
I use macOS Mojave Patcher 1.3.7.dmg to creat a usb to install macos10.14.6.
I just installed this mojave system without any patch file.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "OpenEmu running on a 'patched' macOS version for obsolete Mac hardware is unsupported."
