### ISSUE TITLE
Marvel vs Capcom 2 OpenEmu

### ISSUE THREAD

**Issue by theblackpig75** [OpenEmu/OpenEmu#4162]
I am having problems getting MVSC2 running on OpenEmu. I have downloaded the latest ROM and Naomi. 

I get

"Marvel Vs. Capcom 2 New Age of Heroes (USA, Rev A)" (mvsc2u).

This machine does not work and the emulation is not yet complete. There is nothing you can do to fix this problem except wait for the MAME developers to improve the emulation.

**Comment by clobber** [comment]
Did you read it? I don’t see how we can make that message any more clear. Those games simply don’t run or are not fully playable with MAME.
