### ISSUE TITLE
Mac with user file location on External HD not initiating game window

### ISSUE THREAD

**Issue by tquicksell** [OpenEmu/OpenEmu#4166]
Summary of issue:

OpenEmu worked fin on the MacMini 2018 I am using until I transferred my user file to an external hard drive. All other application work well. While OpenEmu opens, when clicking on a rom to initialise a game, no window pops up. Does anyone have a fix? 

- OpenEmu Version: ???
- macOS Version: ???

**Comment by Sameto** [comment]
Same Issue here.

**Comment by adamdesoto** [comment]
Same here . Anybody find a workaround?  I moved my library and ROMs back to internal storage and still won't open.

**Comment by sonriks6** [comment]
Same here. Got this message in CMD:
/org.openemu.OEXPCCAgent.Agents/org.openemu.OEXPCCAgent.94F248BF-9518-49DF-88CC-FC1E1F640AA8.plist: Path had bad ownership/permissions

**Comment by sonriks6** [comment]
Hi! I've solved the issue in the "Get info" of the external drive, just uncheck the option at the bottom: "Ignore permissions in this drive" and should fix it.

**Comment by adamdesoto** [comment]
That worked!  Thanks so much!

**Comment by tquicksell** [comment]
You beautiful legend! That worked!
