### ISSUE TITLE
couldn't communicate with helper

### ISSUE THREAD

**Issue by graciejonti** [OpenEmu/OpenEmu#4167]
N64 games - Click on the game, black screen comes up and nothing happens...

deleted cores, restarted, re installed and still having same issue..

not any good at this stuff but looked at the logs and says crash every time...

any tips?

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

- OpenEmu Version: 1.0.4
- macOS Version: el capitain 
@clobber helpppp

**Comment by clobber** [comment]
> OpenEmu Version: 1.0.4

What's the matter with you?

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
