### ISSUE TITLE
Audio: Dual output doesn't work anymore

### ISSUE THREAD

**Issue by levengio** [OpenEmu/OpenEmu#4168]
I have a dual output audio configuration on my mac mini 2012, that combines both the analogue and the HDMI output. 
Up until the last version of OpenEmu which I had installed, (2 versions dated) My dual output worked as expected, with sound coming out from both ends, simultaneously, like with every other app. 
Since the update to v2.2.1 sound simply doesn't work on any emulated system, with my configuration anymore.

The only temporary workaround that I found, is to disable dual output, and select a single output device (eg HDMI) from the OS's "Audio devices.app".

# Steps to reproduce

1) Run OS's "Sound devices.app" and create a virtual dual output setting that combines 2 audio outputs.

2) Select them as default and save.

3) Run OpenEmu and launch any game from any system.

4) If The dual-out is default, no matter which single audio device you choose in OpenEmu during emulation (drop-down menu), sound is not going to work.

5) If You chose a single device out on Sound devices.app, sound works as expected and you can even change device while running, only the dual doesn't work in that case.

# Expected Behavior

The Dual output to work as it did on past versions.

# Observed Behavior

Described above.

# Debugging Information

- OpenEmu Version: 2.2.1 (latest as of 4/4/20)
- macOS Version: 10.14.6 Mojave

**Comment by clobber** [comment]
Try OpenEmu 2.3
