### ISSUE TITLE
Couldn't communicate with a helper application.

### ISSUE THREAD

**Issue by cjlambert85** [OpenEmu/OpenEmu#4171]
I realize similar or same issue is posted already, but I cannot add to the post, and suggestions did not solve my problem.  Please do not dismiss this post.
--

OpenEmu 2.2.1 was previously installed on my MacBook Air (13", mid 2013), and everything worked fine 3 days ago.

Today I updated MacOS to 10.15.4, and now when attempting to launch a rom in OpenEmu, I receive the following message:

"Couldn't communicate with a helper application.  Try your operation again.  If that fails, quit and relaunch the application and try again."

I found an article on this website from years ago:
https://github.com/OpenEmu/OpenEmu/issues/2114

I followed the instructions posted by 'clobber', which seemed to work for several people:

"Make sure you have the latest OpenEmu (in your case, version 1.0.4 'experimental' cores bundle)
Navigate to the folder ~/Library/Application Support/OpenEmu (~ meaning your Home folder where ~ is your username. Guide here if you don't know this: http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/)
Delete the "Systems" folder (if it exists)
Delete the "Cores" folder
Restart your computer
Reopen OpenEmu
Navigate to OpenEmu > Preferences > Cores, click download for all the cores so they redownload"

Issue persisted.  I then deleted all OpenEmu files (Main Application, User/Application Support folder and User/Preferences folder), and restarted the computer.

I then downloaded OpenEmu_2.2.1.zip from OpenEmu website.  Placed unzipped application into Applications folder.  Launched.  Installed appropriate cores at the fancy OpenEmu initial-launch screen.  Dragged Super Mario 64 (N64) rom and Super Mario World (SNES) rom (both of which I've had and used for over a decade) into the OpenEmu window.  Both load, and artwork is auto-downloaded and displayed for both roms.

Upon launching either rom file, issue persists.

"Couldn't communicate with a helper application.  Try your operation again.  If that fails, quit and relaunch the application and try again."

What now?  Thank you very much <3

**Comment by clobber** [comment]
An issue you dug up from years ago is not related to your problem at all. Post your crash log.

**Comment by clobber** [comment]
Assumed to be the same as #4165
