### ISSUE TITLE
save state won't work with gamecube

### ISSUE THREAD

**Issue by captnblood** [OpenEmu/OpenEmu#4174]
Summary:  saving and loading states won't work with gamecube.
---
this is probably a known problem already.
could someone tell me if this is planned, and if so, give a approximation of ETA ? (more than a year ?)
if there's some talk available about it on some faq or forum could you point me toward it ?
thanks.

# Steps to reproduce
1. load gamecube game. (i tried with resident evil 1 and 2)
2. try to save state (both quick save and normal save state aren't available (grayed out))

# Expected Behavior
i expected save states to work like with all the other cores

# Observed Behavior
saving state isn't allowed, menu entries are grayed out

# Debugging Information
- OpenEmu Version: 6136.54-g90714f36-Release
- macOS Version: 10.15.4 (19E287)

**Comment by captnblood** [comment]
i read here: https://github.com/OpenEmu/OpenEmu/issues/4119
that "Dolphin updates routinely break save state compatibility, where old saves are not compatible with the new version and won't load. "
could it be possible to have a frozen dolphin core that will not be updated, and as such enabling save states on this experimental core would pose the problem of dolphin updates breaking cmpatibility ?

**Comment by clobber** [comment]
No — and as you’ve read they are not supported at this time.
