### ISSUE TITLE
Beta App -False? Analytics 🦾 https://github.com/OpenEmu/OpenEmu/issues/4175#issue-597678661

### ISSUE THREAD

**Issue by tash777** [OpenEmu/OpenEmu#4175]
[https://github.com/OpenEmu/OpenEmu/issues/4175#issue-597678661]() Summary of issue

{"share_with_app_devs":true,"bug_type":"179","os_version":"iPhone OS 13.4 (17E255)"}
{
  "scheduled" : true,
  "machine_config" : "iPhone8,1",
  "log_version" : 2,
  "region_format" : "US",
  "os_version" : "iPhone OS 13.4 (17E255)",
  "language" : "en-AU",
  "sessions_data" : [
{
  "app_arch" : "arm-64bit",
  "app_build_version" : "3.7.1.0",
  "app_version" : "3.7.1",
  "app_adamid" : 874139669,
  "app_sessionreporter_key" : "DB77292D-6F16-44B6-ABCB-EF86346DCC1C",
  "app_storefront" : 143460,
  "app_bundleid" : "org.whispersystems.signal",
  "app_events" : [
    {
      "date" : "2020-04-08T03:05:38+1000",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 3
    }
  ],
  "app_is_beta" : false,
  "slice_uuid" : "ECA721F0-D0F6-3061-8FF7-5F2CB73ED05A",
  "app_cohort" : "7|date=1535065200000&sf=143460&rapp=com.google.GoogleMobile&pgtp=Software&pgid=874139669&prpg=Software_874139669&ctxt=Transient"
},
{
  "app_arch" : "arm-64bit",
  "app_build_version" : "57",
  "app_version" : "2.6.0",
  "app_adamid" : 899247664,
  "app_sessionreporter_key" : "2DC7CB3D-45AB-4FC4-B576-85A460586278",
  "app_storefront" : 143460,
  "app_bundleid" : "com.apple.TestFlight",
  "app_events" : [
    {
      "date" : "2020-04-08T02:59:33+1000",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 22
    },
    {
      "date" : "2020-04-08T03:00:39+1000",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 46
    },
    {
      "date" : "2020-04-08T03:05:43+1000",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 181
    },
    {
      "date" : "2020-04-08T03:08:52+1000",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 449
    },
    {
      "date" : "2020-04-08T03:16:26+1000",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 36
    },
    {
      "date" : "2020-04-08T03:17:17+1000",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 96
    }
  ],
  "app_is_beta" : false,
  "slice_uuid" : "80A092B1-B885-3033-A3C1-804A4B94A2CF",
  "app_cohort" : "7|date=1586165400000&sf=143460&pgtp=Search&pgid=6f41dd0b-f1d1-460a-bbf9-6995e4dab0a5&prpg=Genre_179183&ctxt=Search&issrch=1"
},
{
  "app_arch" : "arm-64bit",
  "app_build_version" : "3643",
  "app_version" : "3.643",
  "app_adamid" : 1050171910,
  "app_sessionreporter_key" : "28740DE4-F9D3-413A-B87F-53E7F27AD925",
  "app_storefront" : 143460,
  "app_bundleid" : "org.freevpn.vpn",
  "app_events" : [
    {
      "date" : "2020-04-08T02:42:25+1000",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 11
    },
    {
      "date" : "2020-04-08T07:35:33+1000",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 10
    }
  ],
  "app_is_beta" : false,
  "slice_uuid" : "9750EB28-2D75-3362-BA2A-24D982A3D79E",
  "app_cohort" : "7|date=1582804800000&sf=143460&pgtp=Search&pgid=078e1bc4-e44b-41ba-a86c-19acfa516b6b&prpg=Search_078e1bc4-e44b-41ba-a86c-19acfa516b6b&ctxt=Explore&issrch=1"
}
  ],
  "log_timestamp" : "2020-04-08T07:51:19+1000"
}

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
Posting spam earns you a ban.
