### ISSUE TITLE
WWF No Mercy Emulator/Game crashing "Could not communicate with helper application"

### ISSUE THREAD

**Issue by ThePrimeOfAllPrimes** [OpenEmu/OpenEmu#4176]
Summary of issue
Playing the game and transitioning between scenes causes the game to crash and when resetting the emulator, I get hit with "Could not communicate with helper application"

Game Played: WWF No Mercy

# Steps to reproduce

1. Open the game
2. Enter a fight.
3. Quit the game
4. Screen goes white (expected)
5. Game crashes

# Expected Behavior

1. Open game
2. Enter fight.
3. Quit fight. 
4. Screen goes white.
5. Back to main menu

# Observed Behavior

1. After quitting the fight, the game crashes and the emulator stops entirely.

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6 Mojave

I am unsure how to obtain crash reports as i could not find the function within the OpenEmu settings however, I did screencap the process leading up to the crash if that would help. It is a bit larger than I am allowed to post here so any help would be beneficial. (I don't use github much)

Thanks

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#3715
