### ISSUE TITLE
Syncing Save States Across Devices

### ISSUE THREAD

**Issue by atp10000** [OpenEmu/OpenEmu#4177]
Hello,

I store my OpenEmu library folder in iCloud drive, so it can be available across multiple devices. However, I recently noticed that the 'save states' are saved in the each Mac's Library, not the OpenEmu library folder. Thus, when I create a save state on one device, it does not sync to the other.

Any chance this can be possible? Perhaps this is possible and I am missing something?

Thanks!

# Steps to reproduce

1. Open OpenEmu and play a game.
2. Save a game. 
3. Close OpenEmu on this device.
4. Open OpenEmu on another device
5. Open the save state
6. Save state "cannot be found" (or something like that).

# Expected Behavior

1. I want to be able to pick up and resume my saved game on another device.

# Observed Behavior

1. See above.

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.4

**Comment by clobber** [comment]
Using a symbolic link is probably the best solution to accomplish what you want, but storing your save states and Game Library on a "cloud" drive is NOT recommended as syncing problems will negatively affect OpenEmu's behavior.
