### ISSUE TITLE
Soul Silver 

### ISSUE THREAD

**Issue by hca1334** [OpenEmu/OpenEmu#4179]
I downloaded a soul silver rom for the latest version of openemu but the rom will not extract or go into the openemu game slots in order for me to play i did not have this problem with pokemon white or crystal I havent tested with any other games yet other than heart gold. I already have platimuin downloaded. is this an openemu bug, gen IV bug, or a soul silver/heartgold bug? Also any idea on how to fix it?

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing
