### ISSUE TITLE
Support for Netplay

### ISSUE THREAD

**Issue by fab1o** [OpenEmu/OpenEmu#4180]
This is an awsome piece of software. Thanks for all the good work on this.

I see that the snes9x has the netplay support file. I wonder if we can active the option via OpenEmu or via command line.

Thank you.

https://github.com/OpenEmu/SNES9x-Core/blob/1f4dce126a938eed01d501aa9a95420d26ed01de/src/netplay.cpp

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/OpenEmu/issues/377
