### ISSUE TITLE
[MacOS 10.14.6] All ROMs on all Systems cause coreaudiod to crash, leaving no audio.

### ISSUE THREAD

**Issue by netverk** [OpenEmu/OpenEmu#4181]
I installed OpenEmu recently and tested SaGa Frontier for the PS1 in it.
At this time, I had iShowU installed, along with a multi-output device set up. However, as that does not allow volume control, I only use the multi-output device when streaming. Because of that, when I tried SaGa Frontier in it, the audio was being outputted to 'External Headphones'.

External Headphones in this case refers to a set of Logitech speakers with a small volume adjustment box, this box is what is connected to the Mac (Mac Mini 2018), with a set of headphones plugged into that box, which as a 3.5mm jack on it.

When I tried SaGa Frontier, the audio played just fine through my headphones, and there were no issues.

Upon using OpenEmu today, I found that upon starting a rom, this time for the SNES, all audio on the computer stopped, with the volume icon in the menu bar being greyed out and muted.

I investigated this further. The Sound panel in System Preferences will not open when OpenEmu is emulating. Upon enabling the Debug Menu and Audio Output Menu option, I found that when a rom is running, that option is greyed out.
Console.app shows that OpenEmuHelper returned a couple of messages which may help with determining what this error is.

- 21:19:50.341372 +0100	OpenEmuHelperApp	HALC_ProxySystem.cpp:143:GetObjectInfo:  HALC_ProxySystem::GetObjectInfo: got an error from the server, Error: 560947818 (!obj) default	
- 21:19:50.341954 +0100	OpenEmuHelperApp	AVAudioIONodeImpl.mm:569:_GetHWFormat: Unexpected iounit device ID: 0. Cannot get formats yet! error	
- 21:19:50.341984 +0100	OpenEmuHelperApp	AVAEInternal.h:82:_AVAE_CheckAndReturnErr: required condition is false: [AVAudioEngineGraph.mm:1295:Initialize: (IsFormatSampleRateAndChannelCountValid(outputHWFormat))] error	
- 21:19:50.343308 +0100	OpenEmuHelperApp	unable to start AVAudioEngine: The operation couldn’t be completed. (com.apple.coreaudio.avfaudio error -10875.)

I thought restarting coreaudiod could possibly fix this, however when this incident happens, coreaudiod seems to crash. If I open a rom with Audio MIDI Helper open, all audio devices immediately vanish from the app. It is as if the audio infrastructure of the Mac crashes when OpenEmu is emulating.

When emulation is stopped, and OpenEmu is returned to the library screen, audio immediately returns.

When the internal Mac Mini Speakers are set as the output device in System Preferences, OpenEmu experiences no issues with sound.

However, the Multi-Output Device and External Headphones always cause this issue. 

Please can you look into this? I note that there are various other issues regarding iShowU, however that is on Catalina and I'm still running Mojave.

**Comment by clobber** [comment]
Post the full crash log.

**Comment by clobber** [comment]
#4055
