### ISSUE TITLE
Controls froze, sound turned off, graphics still okay. Couldn't choose a single option in game. (Pokemon Black 2)

### ISSUE THREAD

**Issue by tessbesstess** [OpenEmu/OpenEmu#4186]
Hello, I came to this forum solely to get a solution to this issue I'm having. I'm in the middle of fighting a gym leader when all of a sudden, the music turned off by itself, I couldn't move around in-game at all, but the animations & graphics are still moving very smoothly. Please provide an answer for me in the simplest words possible! <3

Here's a link to a video that'll visually prove this situation https://drive.google.com/open?id=1H_4YN22MD4VUK3qxWipfkDCNBeQAVsR2

Some specs:
I'm using a 2017 13-inch MacBook Air.
macOS Catalina (Version 10.15.4)
Processor: 1.8 GHz Dual-Core Intel Core i5
Memory: 8GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB
My game of Pokemon Black 2 is being played with the DeSmuME emulator.

I've made quite a handful of progress so I don't wanna lose my cool achievements. I have a kickbutt Lucario at Level 21.

**Comment by tessbesstess** [comment]
Here's a link to a video that will visually prove my situation which I really hope works  [https://drive.google.com/open?id=1H_4YN22MD4VUK3qxWipfkDCNBeQAVsR2](url)

**Comment by tessbesstess** [comment]
Here's a link to a video that'll visually prove this situation https://drive.google.com/open?id=1H_4YN22MD4VUK3qxWipfkDCNBeQAVsR2

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) -
 
 * "Please search before opening a new issue."
 * "NDS games (especially Pokemon) may have unsolvable problems related to AP patches or DeSmuME's JIT dynarec. Alternatively, try standalone DeSmuME that has the JIT dynarec off by default which may improve compatibility."
