### ISSUE TITLE
Final Fantasy IX .sbi issue

### ISSUE THREAD

**Issue by robzii** [OpenEmu/OpenEmu#4187]
Hi ! I'm trying to play Final Fantasy IX (French version) on Playstation, but I get the error code saying "Required SBI files missing." even though I did downoad these from redump (I took the right ones, the FR ones) as explained on the tutorial (here :https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-sbi-file) and put them in the same folder as the .m3u I created and the .bin and the .cue files that were on the original download package, and drag/dropped the files on the game library.

I'm very confused as I found on this topic : https://github.com/OpenEmu/OpenEmu/issues/2510 someone saying they had this very issue and Clobber explained precisely what to do. I did what they said, multiple times, and it doesn't fix it, I still get the same "required sbi files missing" error message. I don't think the issue is coming from my game as I downloaded a package with all the Final Fantasy games on PS1, and I already played throught I, VII and VI without any issue on OpenEmu.

I'm on MacOS Mojave 10.14.6 and I already have the most updated verison of OpenEmu (2.2.1). Can someone help me ? 

Thank you for any help !

**Comment by clobber** [comment]
Things have changed in a recent OpenEmu release. Open the app, right click your game, click show files, paste your SBI files in that folder, making sure the file names match up.

**Comment by robzii** [comment]
Thank you ! Now it works prefectly :)
