### ISSUE TITLE
Mac OSX 10.15.4 Catalina stopped recognizing controllers

### ISSUE THREAD

**Issue by agrmsu** [OpenEmu/OpenEmu#4188]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce
1. Install Openemu
2. Toggle "input monitoring" in security pane
3. Use Openemu with multiple controllers for a week
4. Open Openemu, controllers not recognized
5.  Toggle input monitoring, both check box and with +/-
6. Disable input monitoring, restart computer
7. Reenable input monitoring,
8. Openemu still not recognizing controllers
9. Disable input monitoring multiple times both with check box, and +/-, with a restart between each try.
10.  Openemu still not recognizing controllers
11.  Uninstall openemu
12. Reinstall openemu
13. Try the above input monitoring steps above.
14. Openemu does not recognize controllers.

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
Not an OpenEmu bug. If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

**Comment by agrmsu** [comment]
How is that not a bug when it worked for a week, then stopped working foe as far as I can tell no reason. Then performed the toggling sequence I’m guessing 40-50 times with no result. I checked the troubleshooting guide and as far as I can tell I have no processes or programs to interfere with proper operation. And when installed on their own the emulator cores themselves work properly with multiple controllers.

**Comment by clobber** [comment]
> How is that not a bug when it worked for a week, then stopped working foe as far as I can tell no reason

I can assure you there’s nothing random about how OpenEmu works. If you can find a way to replicate your problem, I’ll take a look. Otherwise, sorry cannot help you beyond what I’ve already said.

**Comment by agrmsu** [comment]
I can’t replicate a problem if the only Mac I have access to has the problem. If it started working again, I might be able to try replication, but for now it’s not working. What does toggling the input monitoring setting do?  Either it has access or it doesn’t. It has been granted access multiple times in every way that I can see possible. Still no effect, but gamepads work fine with other programs, including some of the emulators found inside openemu. So either Catalina is not granting access or openemu is not recognizing that access is granted. I’m not being cute,  I genuinely don’t know what is needed. I’m willing to try anything short of wiping my drives and reinstalling OS X.
