### ISSUE TITLE
Clicking on ROM produces no result (no popup window, nothing happens)

### ISSUE THREAD

**Issue by ScottReinhard** [OpenEmu/OpenEmu#4189]
Summary of issue

**Pastebin of console while trying to open Rom:**
https://pastebin.com/DLrZH6cG

**# Steps to reproduce**
Bios and System files loaded correctly (have reproduced and worked on my iMac)

Double-click or right-click and select "play game" 
Expect that window will open with game running

Nothing happens, no popup window, no reaction from OpenEmu

Have tested on multiple gaming systems, no change in behavior

**# Expected Behavior**

Double-click or right-click and select "play game" 
Expect that window will open with game running

**# Observed Behavior**

Nothing happens, no popup window, no reaction from OpenEmu

**# Debugging Information**

- OpenEmu Version: 2.2.1

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,5
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	197.0.0.0.0
  SMC Version (system):	2.30f2
  Serial Number (system):	C02PTZJEG8WP
  Hardware UUID:	793C9B29-5F77-562F-957C-A4CFACDCAC4B

**Comment by clobber** [comment]
*What* ROM? What exactly are you trying to do? Try games in our Homebrew library and see if they run.

**Comment by ScottReinhard** [comment]
What am I trying to do? 
As noted in my post I'm trying to launch a ROM so that I can play it. As I noted, whenever I try to launch a ROM (either by double-clicking or right-clicking and selecting "play game"), regardless of gaming system, _nothing happens_. I have installed all the BIOS and System Files. I reproduced the installation on another machine and it works perfectly.

Every ROM I have tried, on any gaming system results in the same thing, nothing starts, nothing happens. Homebrew, NES, SNES, etc. etc. Would it help to list which ROMs in particular? It's all of them. On my other machine, I can open and play every ROM, homebrew games, etc.

Here's an updated pastebin filtered for openEmu:
https://gist.githubusercontent.com/ScottReinhard/fc09e26ef33513c7fb7a990c120ef4f3/raw/65afc6c831daa07d63aa3ef01a44c979896ce44d/gistfile1.txt

**Comment by ScottReinhard** [comment]
@clobber Did the new logs provide any details that may help diagnose the problem?

**Comment by ScottReinhard** [comment]
Gist where I try to open multiple games in SNES, NES, and Atari 2600 emulators in openEmu.
It isn't useful to list all of the ROMs, because _nothing_ has worked, nothing opens. Hopefully this console log is helpful:
https://gist.github.com/ScottReinhard/2e8f5174049185b5fcad0b845a006584

**Comment by marktassin** [comment]
I am having the same issue on my system. Any rom I try to open pops up with the screen and does not launch.

**Comment by ScottReinhard** [comment]
@clobber Did the new logs provide any details that may help diagnose the problem?

**Comment by clobber** [comment]
Nothing useful there. You should try the obvious restart and only launch OpenEmu with no other apps to narrow it down, if you haven't yet. Aside from that, I would make sure you are not using a Multi-Output audio device such as iShowU/Soundflower and ensure in System Preferences > Sounds > Output that "Internal Speakers" are selected.

**Comment by ScottReinhard** [comment]
Sounds good, will give it a try. Thanks.
