### ISSUE TITLE
Moga Rebel Support

### ISSUE THREAD

**Issue by masioka** [OpenEmu/OpenEmu#4191]
Just wondering if all MiFi controllers should work out of the box.

Thanks

**Comment by masioka** [comment]
Some additional information

MOGA REBEL:
  Address:	xx-xx-xx-xx-xx-xx
  Major Type:	Miscellaneous
  Minor Type:	Unknown
  Services:	DID, iAP2
  Paired:	Yes
  Configured:	Yes
  Connected:	Yes
  Manufacturer:	Cambridge Silicon Radio (0x4, 0x1737)
  Bluetooth Core Spec:	2.1
  Firmware Version:	0x0100
  Vendor ID:	0x20D6
  Product ID:	0x3729
  Class of Device:	0x00 0x00 0x0000
  AFH:	On
  AFH Map:	FFFF7F0000080F
  RSSI:	-61
  Role:	Master
  Connection Mode:	Active Mode
  Interval:	0 ms
  EDR Supported:	Yes
  eSCO Supported:	Yes
  SSP Supported:	Yes

**Comment by MaddTheSane** [comment]
If the controller has its HID table visible to IOKit, it should work with some mapping.
