### ISSUE TITLE
Save files won't open on updated version

### ISSUE THREAD

**Issue by kghoang** [OpenEmu/OpenEmu#4192]
Just updated to 2.0.8 version of Open Emu on Mac OS 10.13. Save files from previous OpenEmu app will not open. Get this error message: The operation couldn’t be completed. (org.openemu.GameCore.ErrorDomain error -6.)

**Comment by kghoang** [comment]
Just updated to 2.0.8 version of Open Emu on Mac OS 10.13. Save files from previous OpenEmu app will not open. Get this error message: The operation couldn’t be completed. (org.openemu.GameCore.ErrorDomain error -6.)

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
