### ISSUE TITLE
Install issues one Mac.

### ISSUE THREAD

**Issue by kennycason** [OpenEmu/OpenEmu#4193]
I'm unable to install OpenEmu. Unzipping the downloadable zip file causes Finder to hang and it must be force quit. I used standard Mac utility and have not tried anything via terminal yet. And as expected since I force quit Finder, the executable also does not open.

# Steps to reproduce

1. Download zip file
2. Right click and select "Open With > Archive Utility"

# Expected Behavior

1. To be able to unzip and open OpenEmu

# Observed Behavior

1. The OpenEmu unarchived file w/icon appear. However, the unarchive process will continue on (forever?) until you force kill Finder. 

# Debugging Information

- OpenEmu Version: v2.2.1
- macOS Version: Catalina, 10.15.2

**Comment by clobber** [comment]
Extracting a file is not an OpenEmu bug, and I cannot tell you why this would be happening on your machine. Some suggestions: restart your machine, update to the latest release of macOS Catalina, redownload OpenEmu from our website, try [The Unarchiver](https://apps.apple.com/us/app/the-unarchiver/id425424353?mt=12).

**Comment by kennycason** [comment]
fwiw, my intention with this issue was that there was possibly an issue with the uploaded OpenEmu zip file. However, I was able to get it working with command line tools. Mac still eats the dust when trying to extract OpenEmu, even with fresh download.

In process of updating computer, will restart and try again just for confirmation.

Result: It works now. Must be something strange with Mac or some combo or software installed. No idea.
