### ISSUE TITLE
harrpotter and the sorcerers stone freezing on a particular loading screen

### ISSUE THREAD

**Issue by jojo835** [OpenEmu/OpenEmu#4195]
hi all , ver new to this been playing through a pix rom of the Harry Potter game an noticed that one of the loading screens never seem to load , originally it was only on a side mission but now it seems to be stopping the main story line when you get to the transfiguration class it brings up the loading page but no loading bar appears  .... its seems its this loading screen 

<img width="795" alt="Screenshot 2020-04-25 at 15 28 08" src="https://user-images.githubusercontent.com/64317878/80282437-61979180-8709-11ea-8a91-8aa574e6d6d8.png">  

according to crash reports from my Macs console there is no issue with open emu as it doesn't crash or not respond in any way , it seem its the game itself ..... any Ideas how I could resolve ?

**Comment by clobber** [comment]
A *lot* of missing required information here that you simply ignored from the issue template:

* What version of macOS?
* What version of OpenEmu?
* What game *exactly* and for which system?

If this is an emulation core compatibility bug then there is nothing we can do for you.
