### ISSUE TITLE
A suggestion and a question :)

### ISSUE THREAD

**Issue by Racuevas39** [OpenEmu/OpenEmu#4196]
Hi. OpenEmu is an awesome and fine piece of software. I am very pleased with utilizing it. I wonder if there is a way to cycle from box art, to tittle and to screenshots, especially in the Arcade department, where I recall games/ROMs more from the gameplay rather than the game title. I understand there is mostly no (or lacking) amount of box art for Arcade, but the gameplay screenshots should be very helpful to navigate my ROMs collection.

And continuing with Arcade (and Sega Dreamcast), are you planning to include Redream and Flycast? They are an impressive pair of emulators that run great on macOS: Redream is extremely fast for Dreamcast, while Flycast emulated Dreamcast, Arcade Atomiswave, and Arcade Naomi!

Thanks!

**Comment by clobber** [comment]
> I wonder if there is a way to cycle from box art, to tittle and to screenshots, especially in the Arcade department

No -- it'd be obvious if a feature like that existed. Maybe in the future, but for now you can add your own but just drag and dropping images onto the games.

> are you planning to include Redream and Flycast?

No. These emulators are alpha quality and it will be a long time before they reach 99% game compatibility.
