### ISSUE TITLE
Enabling Input Monitoring disables controller mapping on mac

### ISSUE THREAD

**Issue by aliankarali** [OpenEmu/OpenEmu#4197]
Summary of issue

I have a USB Snes-like Controller (brand CSL). It is detected by the my Macbook and I can remap the buttons. OpenEmu warned me that I need to give OpenEmu the permission 'Input Monitoring' which is under Security & Privacy settings, Privacy section. After giving it and restarting the app, I cannot use Gamepad buttons to map inputs however existing mappings work. Revoking the permission and restarting the app solves the issue.

# Steps to reproduce

Give Input Monitoring permisson to OpenEmu.

# Expected Behavior

Inputs can be mapped to USB Gamepad buttons.

# Observed Behavior

Inputs cannot be mapped to USB Gamepad buttons. Existing mappings works. But button strokes on mapping screen are ignored.

# Debugging Information

- OpenEmu Version: 2.2.1 6136.54-g90714f36-Release
- macOS Version: 10.15.4

**Comment by clobber** [comment]
I don't think that's possible. Either way, input monitoring access *must* be granted in order for input to work. Other issues affecting input are listed in the [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) guide.

**Comment by aliankarali** [comment]
Please reopen the issue. It is exactly as I have described. I can provide more information if need be.

**Comment by aliankarali** [comment]
@clobber  can you give me more explanation then 'I don't think that's possible'?  Why are you closing it without even taking a look? Maybe someone else will take care of the issue. If you don't want to spend time leave it open.
