### ISSUE TITLE
Xbox Controller Mapping Isdsues

### ISSUE THREAD

**Issue by sparker01915** [OpenEmu/OpenEmu#4199]
I cannot edit controls for Xbox for any emulator.  It works and maps automatically however there are some controls I want to change to make it easier for me.  

MAC OS X Catalina

**Comment by clobber** [comment]
1. You must grant input monitoring access as the app instructs on launch, if you haven't already.

2. All other input problems will be in the [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) guide.

**Comment by sparker01915** [comment]
I've done all of this.  OpenEmu automatically maps the buttons.  You should develop a way for people to actually map the buttons to what they want to use.  Its so frustrating that I as a consumer cannot map the buttons to the way I want them forcing me to use several different emulators

**Comment by clobber** [comment]
>as a consumer

LOL you didn't pay for anything.

>cannot map the buttons to the way I want them

I have and use the Xbox One S Wireless Controller. Automapping and re-mapping controls works just fine. The setup works just fine on a stock install of macOS. Your problem appears to be unique to yourself, so you'll have to figure out what is wrong on your end. Sorry, cannot help you beyond that.
