### ISSUE TITLE
TG16/PC Engine emulation errors

### ISSUE THREAD

**Issue by coolman6** [OpenEmu/OpenEmu#4202]
I added two games to my TG16 emulator on OpenEmu in which both contained emulation errors. They are Coryoon and Wonder Momo. On Coryoon, stage 4 (Yellow Park) has glitchy visuals in the background. I watched a longplay of the game on YouTube and saw that the glitchy visuals are supposed to be stars and palm trees. On Wonder Momo, the title screen is glitchy and doesn't show the title image properly. Both games are still playable though, but it's disappointing to see these errors. I don't know if it's the emulator's problem or mine for finding possible broken roms. I would like to see both of these games fixed as they are very cool. If there is a site with fully working non-glitchy TG16/PC Engine roms can someone let me know please?
- OpenEmu Version: 2.2.1
- macOS Version: 10.15.3

**Comment by clobber** [comment]
Claims like these require evidence, otherwise we don't know what you're talking about. There could be the possibility of some bug with Mednafen's PCE module our in our own implementation. 

As for ROMs, you should be using known good dumps of the games from "No-Intro", downloaded on Archive.org.

**Comment by coolman6** [comment]
![IMG_5261](https://user-images.githubusercontent.com/64550686/80629573-09220600-8a21-11ea-81b0-6e4ba388e74a.jpeg)

**Comment by clobber** [comment]
<img width="942" alt="Screen Shot 2020-04-29 at 12 32 34 PM" src="https://user-images.githubusercontent.com/1303132/80633163-8cd5f580-8a15-11ea-9ceb-b6046c252dee.png">

Thanks for reporting. I can replicate this in Mednafen standalone as well as our core ports all the way back to version 0.9.32 -- this is a known issue with Mednafen's PCE module. Nothing you can do about it at this point, and it doesn't hurt gameplay.

From Mednafen's [changelog](https://mednafen.github.io/documentation/ChangeLog.txt):
> 0.8.0-beta:
> PCE:  Block memory transfer instructions are now emulated at 6 cycles per byte transfered(+extra if VDC is accessed) instead of 5, to match tests done by malducci.  This does break Wonder Momo, unfortunately...
>
> 0.3.5:
> PCE:  Block memory transfers now take 5 cycles(read, write, alter source, alter dest, decrement length?) per byte transferred instead of 6.  Fixes "Wonder Momo".

Also, please read this to learn how to [take screenshots on macOS](https://support.apple.com/en-us/HT201361).

Regarding **Coryoon**, please take a screenshot of the problem and then provide a link as to how you believe it ought to look so we can determine if there is a bug.

**Comment by coolman6** [comment]
By the way, for Coryoon, when I was downloading the rom, I found two versions of the zip file. A regular zip and an Alt 1 zip. I don't know what the difference is so I chose the Alt 1 zip file because it seemed like the better one to me. The error I found with Coryoon occured in the Alt 1 version and possibly the regular one as well. I'll try to get back to stage 4 again and take a screenshot so that you can see the issue regarding that game.

**Comment by coolman6** [comment]
Weirdly, I just checked the Coryoon roms again and I just noticed that the Alt 1 zip was removed. So I downloaded and re-added the regular rom and found no problems at all with sounds and graphics. Stage 4, as well as the other stages, had no graphical errors and I even managed to beat it till the end.

**Comment by coolman6** [comment]
Also, this isn't an issue and more of a personal request, will MSX and MSX2 support be coming in the future?
