### ISSUE TITLE
OpenEmu-OBS-SoundFlower Conflict, Probably Mojave-Related? 

### ISSUE THREAD

**Issue by ladyailuros** [OpenEmu/OpenEmu#4204]
I'm not sure if it's an OpenEMU issue or an OBS issue so I'm starting here. 

The Machine:  Mac Pro 5,1 20GB RAM, Quad-Core Xeon, RX580 8GB GPU, Mojave 

The Error and Steps To Reproduce  

When I am trying to capture the OpenEmu window in OBS, OBS is not pulling the audio in via Soundflower (Soundflower confirmed working in Sweet16 (AppleIIGS Emulator), Minecraft and PS4 Shareplay.) When I try to close OpenEmu, OE locks up and I have to Cmd-Alt-Esc out of it. OpenEmu then does not work until I reboot the Mac. Tried with the PSX, PSP and NES Cores. OpenEmu works fine otherwise, ditto OBS. I've tried opening each of them first (OpenEmu first then OBS and then OBS then OpenEmu) with no good results. 

Expected Behaviour: 

I know this worked under High Sierra, I have the stream VODs to prove it! I suspect a Mojave conflict but I have reached the end of my ability -- I'm a hardware girl, I'm not good at software! All I can think of is that there is a piece of the OS that they all want to use and it's not sharing? The fact that OpenEmu locks up hard when OBS is running is the weird part to me. 

If I need to go talk to the OBS guys I will do that too :D When I Googled for answers, this was the first site that came up! 

Thank you for your time, OpenEmu is a great piece of software and I use it all the time!

**Comment by clobber** [comment]
>Soundflower

It's already documented here that there is a problem using multi-output audio devices right now. It simply just isn't going to work.

https://github.com/OpenEmu/OpenEmu/issues?q=soundflower
