### ISSUE TITLE
Couldn’t communicate with a helper application. 

### ISSUE THREAD

**Issue by gowtherui** [OpenEmu/OpenEmu#4205]
It works perfectly fine on my laptop few months ago but now, it says couldn't communicate with a helper. i already uninstall the app then still not working. Also tried to delete the core in the library.Need help

my OpenEmu version is v1.0.4 experimental
Im using MacBook Pro (Retina, 13-inch, Late 2013) , OS X El Capitan 10.11.6

heres my log when i open the app

03/05/2020 11:28:55.627 PM WindowServer[169]: send_datagram_available_ping: pid 395 failed to act on a ping it dequeued before timing out.
03/05/2020 11:29:01.089 PM iconservicesagent[294]: -[ISGenerateImageOp generateImageWithCompletion:] Failed to composit image for descriptor <ISBindingImageDescriptor: 0x7fd4eb708720>.
03/05/2020 11:29:01.090 PM quicklookd[4191]: Error returned from iconservicesagent: (null)
03/05/2020 11:29:09.546 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:09.552 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:09.555 PM WindowServer[169]: send_datagram_available_ping: pid 395 failed to act on a ping it dequeued before timing out.
03/05/2020 11:29:09.744 PM sharedfilelistd[273]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:09.747 PM appleeventsd[52]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:09.802 PM OpenEmu[5246]: OELibraryDatabase loadFromURL: 'file:///Users/aykadvlqn/Library/Application%20Support/OpenEmu/Game%20Library/'
03/05/2020 11:29:09.804 PM OpenEmu[5246]: CoreData: Failed to load optimized model at path '/Applications/OpenEmu.app/Contents/Resources/OEDatabase.momd/OEDatabase 1.3.omo'
03/05/2020 11:29:10.356 PM OpenEmu[5246]: Apple Internal Keyboard / Trackpad
03/05/2020 11:29:12.068 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:12.073 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:12.077 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:12.082 PM appleeventsd[52]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:12.089 PM OpenEmuHelperApp[5252]: parent application is: OpenEmu
03/05/2020 11:29:12.104 PM OpenEmuHelperApp[5252]: Some shit about the game.
03/05/2020 11:29:12.335 PM OpenEmuHelperApp[5252]: Setting up emulation
03/05/2020 11:29:12.344 PM OpenEmuHelperApp[5252]: <NSXPCConnection: 0x7febb2443da0> connection from pid 5246: Warning: Exception caught during invocation of received message, dropping incoming message and invalidating the connection.
Exception: *** -videoBuffer cannot be sent to an abstract object of class NDSGameCore: Create a concrete instance!
03/05/2020 11:29:12.344 PM OpenEmu[5246]: Helper Connection (0x7fc75c39a3e0) failed with error: Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}
03/05/2020 11:29:13.732 PM OpenEmu[5246]: Deallocating proxy: <OEThreadProxy 0x7fc759d67da0, target: <OEGameDocument 0x7fc75e837c50, ROM: 'The Sims 2: Apartment Pets', System: 'openemu.system.nds', Core: 'org.openemu.desmume'>>
03/05/2020 11:29:14.607 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:14.608 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:16.606 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:16.610 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:16.612 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:16.618 PM appleeventsd[52]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:16.624 PM OpenEmuHelperApp[5264]: parent application is: OpenEmu
03/05/2020 11:29:16.638 PM OpenEmuHelperApp[5264]: Some shit about the game.
03/05/2020 11:29:16.820 PM OpenEmuHelperApp[5264]: Setting up emulation
03/05/2020 11:29:16.839 PM OpenEmuHelperApp[5264]: <NSXPCConnection: 0x7fda22f0b9e0> connection from pid 5246: Warning: Exception caught during invocation of received message, dropping incoming message and invalidating the connection.
Exception: *** -videoBuffer cannot be sent to an abstract object of class NDSGameCore: Create a concrete instance!
03/05/2020 11:29:16.839 PM OpenEmu[5246]: Helper Connection (0x7fc75e8955d0) failed with error: Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}
03/05/2020 11:29:17.881 PM OpenEmu[5246]: Deallocating proxy: <OEThreadProxy 0x7fc759d63610, target: <OEGameDocument 0x7fc75c33b3e0, ROM: 'Harvest Moon DS: The Tale of Two Towns', System: 'openemu.system.nds', Core: 'org.openemu.desmume'>>
03/05/2020 11:29:20.518 PM WindowServer[169]: send_datagram_available_ping: pid 395 failed to act on a ping it dequeued before timing out.
03/05/2020 11:29:20.558 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:20.562 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:20.564 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:20.569 PM appleeventsd[52]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:20.576 PM OpenEmuHelperApp[5273]: parent application is: OpenEmu
03/05/2020 11:29:20.590 PM OpenEmuHelperApp[5273]: Some shit about the game.
03/05/2020 11:29:20.641 PM OpenEmuHelperApp[5273]: [Nestopia] Ines: warning, unknown or invalid header data!
Ines: 16k PRG-ROM set
Ines: 8k CHR-ROM set
Ines: horizontal mirroring set
Ines: NTSC set
Ines: mapper 0 set
03/05/2020 11:29:20.643 PM OpenEmuHelperApp[5273]: [Nestopia] Board: NROM-128
Board: 16k PRG-ROM
Board: 8k CHR-ROM
03/05/2020 11:29:20.644 PM OpenEmuHelperApp[5273]: Setting up emulation
03/05/2020 11:29:20.653 PM OpenEmuHelperApp[5273]: <NSXPCConnection: 0x7ff692f05180> connection from pid 5246: Warning: Exception caught during invocation of received message, dropping incoming message and invalidating the connection.
Exception: *** -videoBuffer cannot be sent to an abstract object of class NESGameCore: Create a concrete instance!
03/05/2020 11:29:20.654 PM OpenEmu[5246]: Helper Connection (0x7fc759d73600) failed with error: Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}
03/05/2020 11:29:21.498 PM OpenEmu[5246]: Deallocating proxy: <OEThreadProxy 0x7fc75c3c1ab0, target: <OEGameDocument 0x7fc75e807c30, ROM: 'BATTLE CITY', System: 'openemu.system.nes', Core: 'org.openemu.Nestopia'>>
03/05/2020 11:29:22.089 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:22.096 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:22.098 PM launchservicesd[80]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:22.105 PM appleeventsd[52]: SecTaskLoadEntitlements failed error=22
03/05/2020 11:29:22.113 PM OpenEmuHelperApp[5276]: parent application is: OpenEmu
03/05/2020 11:29:22.125 PM OpenEmuHelperApp[5276]: Some shit about the game.
03/05/2020 11:29:22.175 PM OpenEmuHelperApp[5276]: [Nestopia] Ines: 128k PRG-ROM set
Ines: vertical mirroring set
Ines: NTSC set
Ines: mapper 2 set
03/05/2020 11:29:22.181 PM OpenEmuHelperApp[5276]: [Nestopia] Board: NES-UNROM
Board: 128k PRG-ROM
Board: 8k V-RAM
03/05/2020 11:29:22.182 PM OpenEmuHelperApp[5276]: Setting up emulation
03/05/2020 11:29:22.190 PM OpenEmuHelperApp[5276]: <NSXPCConnection: 0x7fa7f2706a70> connection from pid 5246: Warning: Exception caught during invocation of received message, dropping incoming message and invalidating the connection.
Exception: *** -videoBuffer cannot be sent to an abstract object of class NESGameCore: Create a concrete instance!
03/05/2020 11:29:22.190 PM OpenEmu[5246]: Helper Connection (0x7fc75e881b30) failed with error: Error Domain=NSCocoaErrorDomain Code=4097 "connection from pid 0" UserInfo={NSDebugDescription=connection from pid 0}
03/05/2020 11:29:23.681 PM OpenEmu[5246]: Deallocating proxy: <OEThreadProxy 0x7fc75e843040, target: <OEGameDocument 0x7fc75e878390, ROM: 'Contra', System: 'openemu.system.nes', Core: 'org.openemu.Nestopia'>>

**Comment by clobber** [comment]
>my OpenEmu version is v1.0.4 experimental

lol...

Stop ignoring the rules from the [Issues onboarding page](https://github.com/OpenEmu/OpenEmu/issues/new/choose).

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
