### ISSUE TITLE
Multi-output audio problem..

### ISSUE THREAD

**Issue by xRydan** [OpenEmu/OpenEmu#4206]
Hello Openemu! I wrote you guys on twitter about the problem who everybody has with Openemu but got no answer so I came here to know about the news over the output audio problem... multi-output or soundflower..
Like I really love your app, it was my favorite about all emulatores existante and I am quite sad that I can't use the app just because I can't record the sound of the games..
Can we finally get this issue solved please.. it has been a while that we reported that problem and I really hope to get Openemu back fast so I and everbody can enjoy ourselfs again playing those retro games ^^ Hope for an answer thank you

**Comment by clobber** [comment]
>Soundflower

It's already documented here that there is a problem using multi-output audio devices right now. It simply just isn't going to work.

https://github.com/OpenEmu/OpenEmu/issues?q=soundflower

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Search for duplicate issues before opening a new one and DO NOT pester about existing ones.
