### ISSUE TITLE
Couldn't connect to helper application

### ISSUE THREAD

**Issue by 69Joe69** [OpenEmu/OpenEmu#4207]
Ive been tryna play pokemon black 2 on openemu but it cant connect to helper application. All other console games work but any ds games like pokemon black 1, pokemon black 2, and new super mario bros wont work. I used to be able to play ds games but since i downloaded pokemon black 2, no ds games work. When clearing up storage on my mac i deleted some folders that looked like they had nothing in them but i dont know if thats what caused the problem. I have the desmume core and when i open the desmume plugin file it opens openemu and says a plugin of it is already downloaded.

**Comment by 69Joe69** [comment]
I just managed to connect to the game after restarting my mac. Ive tried the delete cores folder solution, it worked the first time i encountered this problem, but it didnt work this time. I also do not have a system folder.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) -
 
 * "Please search before opening a new issue."
 * "NDS games (especially Pokemon) may have unsolvable problems related to AP patches or DeSmuME's JIT dynarec. Alternatively, try standalone DeSmuME that has the JIT dynarec off by default which may improve compatibility."
