### ISSUE TITLE
Broken install after transferring

### ISSUE THREAD

**Issue by Arsalanbabar** [OpenEmu/OpenEmu#4210]
Hi, so I know you guys have been getting this problem a lot but I haven't found a solution for my issue yet. So I recently transferred my files to my new macbook pro and I try playing a game on the application and it just never loads. 

All my games are installed and the cores are there as well however whenever I try to play a game the screen changes to black but nothing happens. I cant even close the window and I need to force quit to get it off my screen. I tried deleting the application and redownloading but that did not work either

I tried downloading the homebrew games but those did not work either, same issue. 

Any advice would be great, also I don't know how to find the crash reporter so if you need that could you help me find it as well. 

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.3

**Comment by clobber** [comment]
>have been getting this problem a lot 

Nope.

>I recently transferred my files to my new macbook pro and I try playing a game on the application and it just never loads.

We have no idea what you did to break your install -- it's not our job to fix that. Read if anything here is helpful to you: https://github.com/OpenEmu/OpenEmu/issues/4189#issuecomment-621932852
