### ISSUE TITLE
Keyboard input not working??

### ISSUE THREAD

**Issue by khoss13** [OpenEmu/OpenEmu#4211]
Hello,

I just downloaded the most recent OpenEmu (and have a fully updated MacBook pro) to play some GBA games. My keyboard input is not working on the game loaded. Reading past questions on this topic, I have followed all procedures listed to no avail. I have granted input permissions in my system preferences, I have made sure that all other apps are closed (so no interference) and I have even tried restarting a few times. Any other suggestions on how to get the keyboard controls to work? I currently can't get any response on the game via keyboard (mouse click interaction works fine to access game settings). Thank you!

**Comment by clobber** [comment]
If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
