### ISSUE TITLE
MAME 

### ISSUE THREAD

**Issue by Crklz7** [OpenEmu/OpenEmu#4212]
Hi, sorry to bother but it's been like 5 hours that i'm driving crazy trying to solve a problem with Metal Slug 5 on OpenEmu with Mame. First i solved the core version problem, downloading an exact 0.219 version of the rom and then it says :

Metal Slug 5 Plus (bootleg) (ms5plus.zip) requires:
neogeo.zip  	- INCORRECT SET
These ROMs must be from a MAME 0.219 ROM set. 

(i tried other games on 0.219 to be sure, no one run)

I tried maybe all the versions of neogeo.zip i could find on the internet and no matter what, everytime the same problem. 

I tried first with the experimental v2.2.1 (actual)
and then with the experimental v2.0.8
and i'm on MBP OSX 10.14.6

Have a nice day

**Comment by clobber** [comment]
The message is clear. You need to use ROMs from the MAME version in use - in this case a MAME 0.219 set, or compatible. It’s not our job to locate these files for you. Try Archive.org
