### ISSUE TITLE
DeSmuMe

### ISSUE THREAD

**Issue by blublorb** [OpenEmu/OpenEmu#4214]
I have an issue with DeSmuMe core. When I play "Justice League Heroes" there is a Black bar that appears over the health and xp bars. I tried using DeSmuMe application and it did not experience the same issue. I have question as well which is Can install the DeSmuMe application into OpenEmu to replace the DeSmuMe Core.

-Screenshot:
![image](https://user-images.githubusercontent.com/65474371/82133784-e1bb8f00-97bd-11ea-8147-c6399c72671e.png)

- OpenEmu Version: 2.2.1
- macOS Catalina: Version 10.15.4

**Comment by clobber** [comment]
Actually **read** the [Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) regarding NDS games.

>I have question as well which is Can install the DeSmuMe application into OpenEmu to replace the DeSmuMe Core.

No, OpenEmu is not a launcher.
