### ISSUE TITLE
Invert X Axis for GameCube Controller mapping?

### ISSUE THREAD

**Issue by nohaycubetto** [OpenEmu/OpenEmu#4216]
I'm using OpenEmu 2.2.1 on macOS Catalina 10.15.4. I have an Xbox One controller via Bluetooth. On the Mupen64Plus core I can play fine. But on the dolphin core (v 5.0.2) / Gamcube controller mapping, the X axis for the analog stick is inverted, so when I turn left, the character goes right. I was wondering if there's any way to invert the mapping of the axis.

Thanks,
N

**Comment by dhkaneda** [comment]
@nohaycubetto If you "Edit Game Controls..." while are you are in the Gamecube game, you can edit the C-Stick options and instead of pushing your right analog stick left for left, push it right and vice versa. Ran into this recently when trying to play Wind Waker.

**Comment by robins1993** [comment]
I have a similar issue. I'm using the Playstation DS4 controller on Mac, the L&R won't calibrate to L1 and R1 on my controller. All other buttons work apart from the triggers. 
I even tried L3 and R3 for L&R but still no luck.

**Comment by nohaycubetto** [comment]
@dhkaneda thanks. I had tried that but it didn't work. Knowing it _should_ work I figured that the "Edit Game Controls..." menu behaves and doesn't get the gamepad's input. After several restarts of OpenEmu and re-pairs of the controller I was able to map it right, and now it works. Thanks! N.
