### ISSUE TITLE
Not reading inputs from my keyboard

### ISSUE THREAD

**Issue by nygiantsfan1029** [OpenEmu/OpenEmu#4217]
Not sure if this is actually a bug.  I opened up the emulator for the first time in a bout a month and none of the game are responding to my mac's keyboard inputs.  I tried going to your site and seeing if i needed an update but it is still not working.  Ok edit.  The games are reading my inputs but I can no longer edit my controls

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.4

**Comment by clobber** [comment]
I can assure you there’s nothing random about how OpenEmu works. If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here for possible problems: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
