### ISSUE TITLE
Some games glitch out and freeze when starting (mupen64 core)

### ISSUE THREAD

**Issue by binex-dsk** [OpenEmu/OpenEmu#4218]
(NOTE: this is a re-report of an issue I posted on an older account about a year back)

Summary of issue

When starting an N64 game after loading from a restore point (after quitting), certain games freeze with a weird visual glitch.

Tested games: SM64, Star Fox 64, Paper Mario, Kirby 64

# Steps to reproduce

1. Open up any of the previously mentioned games. (or something else--make sure to try at least one of those)
2. After the game starts, get into somewhere in the main game.
3. Quit and keep a save to restore from later.
4. Restart OpenEmu.
5. Open the same game up.
6. If no visual glitches occur, try multiple times. It's highly inconsistent.

# Expected Behavior

The game loads up properly.

# Observed Behavior

An odd visual glitch that looks like screen tearing occurs and the game doesn't start. No sound is played either, and the only way to get out is to restart the game.

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6

**Comment by clobber** [comment]
>NOTE: this is a re-report of an issue I posted on an older account about a year back

We do not want duplicate issues. We also don't want irrelevant issues about core plugins opened in the repo for the main application.

N64 emulation overall has compatibility bugs -- Mupen64Plus (the core plugin) and GLideN64 (the GPU plugin) are still in a volatile work-in-progress state which means it is not recommended to rely on save states as those can break between core plugin updates. Rely on in-game battery saves if available.

Also please keep in mind this notice is displayed for a reason:

![3b7d1862-13d2-11e5-8da7-3f1e90d7775c](https://cloud.githubusercontent.com/assets/1303132/12007091/554fbb6a-abb1-11e5-93b0-37e9d8d95149.png)
