### ISSUE TITLE
"Select Audio Output Device" doesn't seem to work

### ISSUE THREAD

**Issue by bakagaigin** [OpenEmu/OpenEmu#4220]
I use several output devices including HDMI, a USB audio interface, as well as Soundflower (and more recently, BlackHole, but it seems to have its own issues). For various purposes I use macOS's aggregate and multi-output devices as well. I love that OpenEmu introduced an output device switcher, but unfortunately, it doesn't seem to do anything.

I switch to another audio device, the audio goes silent for like a second, and then reverts to the previous device. None of the options have checkmarks (which tells me it doesn't seem to know what device it's using?).

Switching the system device from the menubar works fine however.

I've tried with everything unplugged from my laptop, so the only options are the built-in output and the virtual outputs, but to no avail.

the audio devices I have listed are:
- Built-in Output
- HDMI
- BlackHole 16ch
- Soundflower (2ch)
- Soundflower (64ch)
- Steinberg UR44
- Aggregate Device
- Multi-Output Device

System:
- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6

**Comment by shysaur** [comment]
Confirmed and fixed for next release.
