### ISSUE TITLE
The emulator could not load ROM

### ISSUE THREAD

**Issue by pierowidyastana** [OpenEmu/OpenEmu#4222]
Hello everyone,
I'm completely lost and have no idea what's happening. I just played a game (PS1) and it was working perfectly. I took a rest around 2 hours then tried to play a game but the emulator suddenly could not load ROM. I tried to launch the other games and it has the same result. I restarted my laptop but it didn't solve the issue. Can you please tell me how to resolve this issue? 
Thank you

- OpenEmu Version: 2.0.5
- macOS Version: 10.11.6

**Comment by clobber** [comment]
>OpenEmu Version: 2.0.5

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
