### ISSUE TITLE
OpenEmu Game problems.

### ISSUE THREAD

**Issue by MrDream101** [OpenEmu/OpenEmu#4223]
Hello, I recently downloaded OpenEmu. I have a MacBook Air and My Startup Disk is almost full. I downloaded most of the Kirby games, and couldn't download Kirby's Avalanche, Kirby 64, Kirby Squeak Squad, and a couple of others. Some of the ones I did download just had static as the art, but surprisingly still had the names. I played two of the working games easily. I left and later came back to try again. Some games did not download correctly as there was no art, and some didn't even download. There were some that didn't show up. I kept downloading them from different sites and places and they wouldn't download. Then I realized I couldn't play any games, working or not. I need help because the entire reason I got this application was to play Kirby Squeak Squad, and that was a very good game.

**Comment by clobber** [comment]
>My Startup Disk is almost full.

You need to resolve that problem.

A lot of missing required information here that you simply ignored from the [issue template](https://github.com/OpenEmu/OpenEmu/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
