### ISSUE TITLE
In need of extra meta

### ISSUE THREAD

**Issue by DrLuthor** [OpenEmu/OpenEmu#4224]
Hi guys !

Since I'm not allowed to post on [issue 664](https://github.com/OpenEmu/OpenEmu/issues/664#issue-15584276), I write here to underline that extra meta (region, release date/year, editor, developper, game serie and genre) would be very much appreciated.

Thanks for the app.

**Comment by clobber** [comment]
Do not open duplicates issues. Do not open issues to pester.
