### ISSUE TITLE
OpenEMU ...cheat codes?

### ISSUE THREAD

**Issue by snowhawk2001** [OpenEmu/OpenEmu#4226]
I am trying to use a cheat code (infinite lives) on Super Mario Brothers 2, but when I try to apply the cheat code, it won't work.

I am on OSX 10.11

How do I get this cheat code to work?

**Comment by clobber** [comment]
>I am on OSX 10.11

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

Also, please don't "cross post" - you already started a thread on the subreddit.
