### ISSUE TITLE
Error Domain=OEImportFatalDomain Code=-1 "(null)" When Importing most cartridge-based games

### ISSUE THREAD

**Issue by ameturpoet** [OpenEmu/OpenEmu#4227]
Rom importing fails with the error listed in the title when importing any cartridge-based game into most systems (So far tested with SMS, SNES, VB, Vectrex, GG, Lynx, GBA, but I suspect this is a broader issue), but doesn't seem to be an issue on CD-based systems (PC-FX, Saturn, PS1, PC-Engine CD tested). The listed error is returned in the console after every individual game's attempted import.

The file formats used are the native rom formats for each system (e.g .vb for Virtual Boy, .sfc for SNES, etc.), and these same roms had worked on a previous install of OpenEmu with the same version of the software (v2.2.1 experimental) on the same version of macOS (10.15.4) on the same machine with the same directory paths (I do not have OpenEmu copy my rom files to the Game Library folder, as I keep them on a network drive, though I have run all these same tests using local storage on the primary drive, with the same results).

I already have spent a fair bit of time organizing my library just how I like it, so I do hope that this doesn't require deleting all of my game library metadata, but hopefully there's a simpler solution.

----------------------

# Steps to reproduce
**1.** Drag-and-Drop any rom into the respective system (VB, SMS, SNES, Lynx, GBA, GG, Vectrex, etc.)
**2.** See console log output of:
> Error Domain=OEImportFatalDomain Code=-1 "(null)"

# Expected Behavior
**1.** Drag-and-Drop any rom into the respective system (VB, SMS, SNES, Lynx, GBA, GG, Vectrex, etc.)
**2.** Rom files are scanned and successfully added to library.

# Observed Behavior
**1.** [Observed behavior described in full within Steps To Reproduce section]

# Debugging Information

- OpenEmu Version: v2.2.1e
- macOS Version: 10.15.4

**Comment by clobber** [comment]
>Error Domain=OEImportFatalDomain Code=-1

`OEImportErrorCodeAlreadyInDatabase     = -1`

Doesn't sound like a problem here; duplicates cannot be imported. If the exact ROM already exists in your library, it will not be imported.

[Importing](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing) User Guide has useful information. You should also be using ROMs from a "No-Intro" set obtained from Archive.org. That's the best I can tell you.

**Comment by ameturpoet** [comment]
> > Error Domain=OEImportFatalDomain Code=-1
> 
> `OEImportErrorCodeAlreadyInDatabase = -1`
> 
> Doesn't sound like a problem here; duplicates cannot be imported. If the exact ROM already exists in your library, it will not be imported.
> 
> [Importing](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing) User Guide has useful information. You should also be using ROMs from a "No-Intro" set obtained from Archive.org. That's the best I can tell you.

They are not duplicates - I can confirm the libraries in question are empty.

**Comment by ameturpoet** [comment]
@clobber I was told to reply here with my clarification, but I had already posted a response, and you haven't responded to that even though you acknowledged it in the other thread. Where should I go to file bugs with OpenEmu if not here?

**Comment by clobber** [comment]
@ameturpoet Stop pestering. Continuing to do so will get you banned.

The correct thing to do is find precise conditions to replicate your problem, to determine if it's an actual bug or not.
