### ISSUE TITLE
Bluetooth audio not working

### ISSUE THREAD

**Issue by JasonInOttawa** [OpenEmu/OpenEmu#4228]
Summary of issue

I am running OpemEmu v2.2.1 build 6136.54-g90714f36-Release. I do not get sound through Airpods. 

# Steps to reproduce

Start OpenEmu.
Start a game.
Sound does not work.
(Sound does work with other applicaitons)

# Expected Behavior

Games with sound! :)

# Observed Behavior

Games without sound!

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.4

**Comment by clobber** [comment]
Works fine here. Disable or remove any multi-output audio device software.

**Comment by JasonInOttawa** [comment]
As far as I know, I am not running any multi-output device software. This is what I see in "Audio Devices"

![Screen Shot 2020-06-01 at 3 54 21 PM](https://user-images.githubusercontent.com/46451014/83448600-31d25c80-a420-11ea-91f4-322864dfe15d.png)

Is there anyplace I can check for audio errors?

Thanks,
Jason

**Comment by JasonInOttawa** [comment]
Please disregard - it's working
