### ISSUE TITLE
OpenEmu Mistakenly Thinking Duplicates Exist in Library

### ISSUE THREAD

**Issue by ameturpoet** [OpenEmu/OpenEmu#4229]
This is a follow-up to my bug report, but since there seemed to be some miscommunication and for some reason the bug was closed before I could clarify more information, I will continue here instead of filing a new bug report for the same persistent issue.

[Previous Bug Report In Question](https://github.com/OpenEmu/OpenEmu/issues/4227)

I am adding this gif as proof that there are in fact not duplicates in my library, and that this is an issue: https://imgur.com/40yLpV1

**Comment by clobber** [comment]
Do not open duplicate issues - you can comment with whatever you'd like in the previous, despite it being closed.
