### ISSUE TITLE
Having issues transferring .m3u file into open emu

### ISSUE THREAD

**Issue by YeezyTaughtMe-00** [OpenEmu/OpenEmu#4230]
Hello,

I've been researching this topic for quite some time now, and I'm not sure what else to do. For PS1 Roms that have multiple discs, I download the zip, extracted it, and I was left with 2 or 3 folders (depending on the game) that included a .bin file and a .cue file. I then created a separate folder and dragged and dropped each .bin/.cue coupling into the new folder. Next, I opened text mate and created the .m3u file by dragging the .cue files and cleaning them up so that they looked like the examples on the wiki. Once I saved it to the same folder as the rest of the .bin/.cue files, I dragged the .m3u file into OpenEmu - essentially following the exact steps the wiki provides. Unfortunately, the files were not read and nothing happened. I've been trying this with a couple of games, and the same issue persists.

The one thing that I notice is that the .cue files are 'Sega CD Games.' However, I'm not sure if there's a way to change the typing or if I just need to use a specific site that I can download roms which are compatible with this method. Any help on this matter would be greatly appreciated. Thank you.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Closely follow the [CD and M3U guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) for importing CD-based games &mdash; no additional help beyond the guides will be offered."

Your hints are to follow the guide and only use known good dumps of these games from "Redump" on Archive.org.
