### ISSUE TITLE
Sound Drops Intermittently

### ISSUE THREAD

**Issue by jasonguywvu** [OpenEmu/OpenEmu#4231]
So this happens occasionally on MAME, but regularly on SNES, no matter which of the cores I use. I'm playing, and everything is fine, and then the sound completely cuts out. When I check my status bar at the bottom of the OpenEmu screen, it is as if I muted it. I then turn the sound back on, it will work for a few minutes, then cut out again. I have even left the status bar up so I can watch it as I play, and I will watch the volume bar go from where I set it immediately to off. I tested every single SNES game I have and it happened with each one. I'm just using the stock speakers in my iMac, and this doesn't happen with anything else I use. In fact I'm playing music right now with no problem. This is a shame in that SNES is my favorite system.  I've searched for the last couple days and did not see where anyone else had a similar issue, so I'm wondering if I have a file somewhere in the bios or somewhere else in OpenEmu that could be throwing it off?  I am admittedly a novice (although been using OpenEmu for a long time) and when PSX/SegaCD/Saturn became available struggled with getting them to work, so I may have many more files than necessary.  Any help getting the sound to stay on would be greatly appreciated!  I literally just joined GitHub just for this, and this is my first ever post, so excuse me if I did something wrong or omitted something I was supposed to do.

OpenEmu 2.2.1
macOS Mojave 10.14.6

**Comment by clobber** [comment]
> it is as if I muted it.

That would be what you had done. You are either pressing the "Volume Down" hotkey or you have a key bound to "Mute" in Controls Preferences.
