### ISSUE TITLE
Loading a quick save state on DS sometimes freezes the game

### ISSUE THREAD

**Issue by NinjolasNJM** [OpenEmu/OpenEmu#4232]
OpenEmu version 2.2.1, OSX version 10.15.4

Occasionally, when restoring a quick save state on a DS game, the game will freeze. No inputs or buttons will function when it freezes like this, including quitting OpenEmu, forcing you to use alt+cmd+esc to close the application. The screen is stuck on the ScreenShot image for the state, and upon reloading OpenEmu the game will fail to load the auto save state as well and reboot the system to the battery save from the beginning of the last time the game was opened, erasing not only the progress from up to when you loaded the quick save, but the entire play session as well. Loading the quick save again will yield the same result as it did the first time.

Luckily, I did find a workaround for this in case it happens to anyone else. Right click on "Show package contents" in the quick save, and take out the file named State and add .dst to the end of it. Then open the game and this save state in standalone Desmume, and the save will load properly. Now in the game, save via the in game save functionality and go to File > Export ROM Save file, rename this file to the title of the game, and replace the Openemu battery save file with this file. Also be sure to delete the auto save state file or else the game will load to it instead of the one you just made. Upon opening the game, it should give you back your data.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues?q=Desmume
