### ISSUE TITLE
Misaligned tabs in the title bar

### ISSUE THREAD

**Issue by kerunaru** [OpenEmu/OpenEmu#4238]
The tabs in the title bar on main window seems to be misaligned.

# Steps to reproduce

1. Just open OpenEmu.

# Expected Behavior

1. Tabs being correctly visible on title bar.

# Observed Behavior

1. Tabs are cropped. I attached a screenshot.

<img width="942" alt="Captura de pantalla 2020-06-09 a las 20 14 15" src="https://user-images.githubusercontent.com/94023/84184520-cf1b3980-aa8d-11ea-9ca5-69fea5c8e169.png">

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.5

**Comment by J-rg** [comment]
That’s what happens if you don’t make sure your toolbar wears its retainer regularly. Will be fixed in the next update; until then you can work around this issue by running the following script in Script Editor:

```
set esStrings to "/Applications/OpenEmu.app/Contents/Resources/es.lproj/Localizable.strings"
set deStrings to "/Applications/OpenEmu.app/Contents/Resources/de.lproj/Localizable.strings"

tell application "TextEdit"
	activate
	open esStrings
	set text of front document to replace_chars(text of front document, "\"Capturas de pantalla\"", "\"Capturas\"") of me
	close the front document saving yes
	
	open deStrings
	set text of front document to replace_chars(text of front document, "\"Bildschirmfotos\"", "\"Screenshots\"") of me
	close the front document saving yes
end tell

on replace_chars(this_text, search_string, replacement_string)
	set AppleScript's text item delimiters to the search_string
	set the item_list to every text item of this_text
	set AppleScript's text item delimiters to the replacement_string
	set this_text to the item_list as string
	set AppleScript's text item delimiters to ""
	return this_text
end replace_chars
```
