### ISSUE TITLE
Feature Request: Windows Zoom Level "Maximum Integral"

### ISSUE THREAD

**Issue by CloseToNose** [OpenEmu/OpenEmu#4239]
I would like to suggest a new window zoom level for OpenEmu: "Maximum Integral".

As I understand it, OpenEmu only has a "Maximum" zoom level which fits the image to the screen size. So the zoom factor can any floating-point number between 1,0 and maybe 10,0 or 12,0 - depending on your screen size.

"Maximum Integral" only zooms with integer factors like 1, 2, 3, 4... and takes the maximum which suitable for your screen.

**Comment by clobber** [comment]
Use the "popout gameplay window" to achieve integral scaling - either View > Undock Game Window or OpenEmu > Preference > "Always use popout gameplay window" and set your scale from the HUD bar. Otherwise, it's not clear what you mean.

**Comment by CloseToNose** [comment]
Hello Clobber,

Thank you for your response. This is _almost_ what I meant: The scaling is exactly the way I wanted it, but I would prefer if you could do this not only in a window (with lots of apps and desktop stuff in the background), but also in fullscreen mode with a black frame around the game's display.

**Comment by clobber** [comment]
Yes, an option in fullscreen mode to toggle integer scales is desirable. We either have an issue already opened for this or it is something devs have discussed in chat. Either way, will happen at some point.
