### ISSUE TITLE
Multiplayer problems

### ISSUE THREAD

**Issue by patrickheeney** [OpenEmu/OpenEmu#424]
I am having some issues with the 2nd player controller and multiplayer.
## NES

Works as expected.
## Nintendo 64

The 2nd player or multiplayer options within the games are greyed out. It appears that the second controller can't be found. Tested on 3 multiplayer games.

The second controller works to control what I assume is the first player but only certain buttons. For example the A button worked all the time. Pressing the X was the same as pressing B on the first controller. Both controllers were mapped the same configurations. The first controller always works correctly.
## SNES

Works as expected.
## Sega Genesis

It lets me pick the 2 player options but when it comes time for the second player to use the controller it does not work. All the buttons have no effect. I tested this on 3 games. First controller works fine.

**Comment by chrisatge** [comment]
Playing on ps1 with 2 ( or 3) dualshocks 4 and at the beginning they work fine but after a few minutes they stop working and only one works, tried it with crash bash.

**Comment by ChaoticSquirrel** [comment]
having serious connection issues with SNES. The first controller connects but the second won't and it's saying I have three controllers connected when I only have two.
