### ISSUE TITLE
Bug report: Low-contrast display

### ISSUE THREAD

**Issue by CloseToNose** [OpenEmu/OpenEmu#4240]
First of all: Yes I know, MAME is unsupported, but I really love it and wanted to give some feedback.

I have noticed that the contrast of colors in MAME games is pretty low in OpenEmu compared to other MAME emulators. "MAME OS X" for example has much more vivid and brighter colors - you can see this very clearly in "R-Type II".

To verify this, I did not use any filters, shaders or zoom factor greater than 1 in both emulators.

**Comment by clobber** [comment]
That's probably going to be a difference of sRGB vs RGB colorspace. You should also definitely NOT be using ancient "MAME OS X" as any sort of baseline comparison -- it's OpenGL implementation is very old. You can assume it's incorrect.

Ours should be correct. https://github.com/OpenEmu/OpenEmu/commit/f1d163b6465518e55c0b67961ebfcdcb8442970c

**Comment by CloseToNose** [comment]
Hello Clobber,

Thank you for your reply. As I mentioned, I was referring to "other MAME emulators" in general, "MAME OS X" was just an example I had at hand.

Just look at various screenshots of the same game in different MAME emulators on Macs or PCs. You will notice the difference.

**Comment by clobber** [comment]
In emulators, colorspace in screenshots can also differ from their gameplay windows.
