### ISSUE TITLE
Downloading Core

### ISSUE THREAD

**Issue by Shelbopoly** [OpenEmu/OpenEmu#4241]
I've been trying to download and redownload, install and reinstall different versions of OpenEmu to play a Nintendo DS game; it lets me add the .nds file to the emulator which is the closest I've gotten to being able to play, but then it tells me I'm missing the DeSmuME core to be able to emulate it. I had already downloaded DeSmuME several times, and it still does not recognize it, and when I click to download what it wants me to, it gives an error (Foundation._GenericObjCError error 0.).

I have a 2014 Macbook Air, have updated it as far as it can go to 10.13.6 High Sierra, and have downloaded the most recent OpenEmu that works with that version. Currently have tried the 2.0.8 experimental .zip but that hasn't worked either. Not sure what else I can do to make this work.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
