### ISSUE TITLE
has a easy way to fix network error

### ISSUE THREAD

**Issue by lwangwangl** [OpenEmu/OpenEmu#4243]
after i install the app, it not show me the download core ui, and all are empy, when i turn to the homebrew ui, it tell me the cannot connet the internet, but i don't want to reset my digicert, and my network is ok, is there another way to fix this problem？

**Comment by lwangwangl** [comment]
i am not sure its about my mac github ssl cert, but i haven't found any expired cert, and i can access githhub by chrome

**Comment by clobber** [comment]
Sorry, no - network problems are going to be on your end.
