### ISSUE TITLE
OpenEmu 2.2.1 Experimental Random & Intermittent Freezes on macOS 10.15.5

### ISSUE THREAD

**Issue by Mr-Pitalo** [OpenEmu/OpenEmu#4247]
Hi All,

Just when playing games (on different cores and games - NES & MAME checked), I get random and Intermittent freezes every 5 minutes or so.

The freezes last for about 1 min more or less, and then the game continues normally on its own.

Unless someone shares the same issue, I'm wondering whether this could be my hardware not being enough? or maybe it's just the experimental version? But the NES core should still work fine, shouldn't it?

I run OpenEmu 2.2.1 Experimental on macOS 10.15.5, on a Mac mini (late 2012) Core i5 2.5GHz & 4GB RAM.

I'm thinking of upgrading the HDD to an SSD to see if It improves on the issue.

**Comment by clobber** [comment]
First time we've heard of this and we are not experiencing this issue. Without steps to replicate, there is not much we can do. It sounds like a problem on your end -- unknown what the cause is.
