### ISSUE TITLE
Catalina 10.15.5 PSP Bug

### ISSUE THREAD

**Issue by himekoarisu** [OpenEmu/OpenEmu#4248]
Hello! 
Now, when I'm trying to launch the psp game, it tries to start and then immediately crashes with the popup "Couldn’t communicate with a helper application." The game has never been run before, it just downloaded the app. I read a issue similar to this one and I made all the steps that the supporter indicated but it didn't work. I also reinstalled the core plugin for PSP and look for the "console" thing but it appears without anything, it has nothing. I suppose that is because I have never played anything before. 

I'm not sure if there is a solution. I've read that this problem is only with PSP. I haven't tried any other games but I suppose it works fine.

- OpenEmu Version: 2.2.1.
- macOS Version: Catalina 10.15.5

**Comment by clobber** [comment]
Uh. You didn’t think it’d be helpful to specify *which* game and include a crash log?

**Comment by himekoarisu** [comment]
> Uh. You didn’t think it’d be helpful to specify _which_ game and include a crash log?

I was trying to play Amnesia for SONY PSP. Sorry for my ignorance, what is a crash log?
