### ISSUE TITLE
Help with playstation roms

### ISSUE THREAD

**Issue by tlalokman** [OpenEmu/OpenEmu#4250]
Hi, I have tried all the tutorials for running playstation roms and already got the bios to play the ps roms, but openemu wont run the games, it doesnt even create a miniature in the library, any help? im using latest catalina update

**Comment by clobber** [comment]
Follow here: https://old.reddit.com/r/OpenEmu/comments/gv99fs/ff7_m3u_transferring_help/fstei4e/
