### ISSUE TITLE
Couldn't communicate with a helper application - macOS Big Sur

### ISSUE THREAD

**Issue by shokuninstudio** [OpenEmu/OpenEmu#4251]
OpenEmu's helper app doesn't like having the Powerbeats Pro or AirPods set as the sound output device in System Preferences. I can't launch any game unless my Mac's internal speakers are set to the output device.

A couple of times switching back and forth between audio devices has worked but in most cases I get the 'Couldn't communicate with a helper application' when a game tries to launch.

<img width="361" alt="Screenshot 2020-07-01 at 09 27 57" src="https://user-images.githubusercontent.com/54727267/86223968-29d11e00-bb80-11ea-9c19-429292ed9466.png">

**Comment by clobber** [comment]
You already mentioned this in two other issues. Don’t use Apple betas on your daily driver. These bugs often fix themselves in later releases.
