### ISSUE TITLE
Issue with virtual inputs

### ISSUE THREAD

**Issue by thefudgeishot** [OpenEmu/OpenEmu#4252]
I coded a python discord bot that receives commands and executes inputs with pynput although these keystrokes are recognized by macOS openEmu isn't recognizing them is an issue or intended? 

I'm sure this seems like a very peculiar question but yea...

**Comment by clobber** [comment]
It won't work. We receive inputs at a lower level.

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems#input-keyboardgamepad-not-working

**Comment by ddcouples** [comment]
> It won't work. We receive inputs at a lower level.
> 
> https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems#input-keyboardgamepad-not-working

Will it be supported in the future？
