### ISSUE TITLE
Support Folders in Game Library redux (Feature Request)

### ISSUE THREAD

**Issue by GryphonClaw** [OpenEmu/OpenEmu#4253]
**Ok I know the previous version of this request was closed but I think that was a misunderstanding and I didn't explain it very well... so I'll add the original question here and elaborate more:**
---
> Would it be possible to add Folders for the Games Library? for example in when SNES Library is selected, have the ability to add a Folder called: "Zelda Randos" and I could put all my Zelda Randomized Roms in said Folder

---

So what I was thinking was more of "Virtual Folders" It doesn't have to move ROMs around or anything physically. Much like how Xcode has the Yellow folders which are only in the project list for source code, blue folders would be actual folders on disk (not what this FR is about).

This would vastly improve the Icon view of the Library, I'm aware you can use a Collection (essentially a smart folder) but this does not meet the need that I'm asking for.

Thanks for considering this Feature Request.

**Comment by clobber** [comment]
Sorry, no. Create “Collections” in the application if you want to manage games.
