### ISSUE TITLE
feature request: map full and partial presses of triggers to seperate buttons in dolphin core

### ISSUE THREAD

**Issue by carsuki** [OpenEmu/OpenEmu#4255]
dolphin allows you to map seperate buttons to partial and full (analog) presses of the gamecube controller triggers: https://owo.headpat.services/i/jsnv.png

this feature would be useful in openemu for those who don't have true analog triggers on their controller (or for those with a keyboard), especially for games like mario sunshine which perform different functions depending on whether the trigger is fully pressed down or not

**Comment by clobber** [comment]
Sorry, no. OpenEmu isn't an ideal frontend to Dolphin and adding something like this is non-trivial in our UI. Instead use Dolphin standalone for such features or get a proper gamepad with true analog triggers (Xbox One or PS4 DualShock 4).
