### ISSUE TITLE
Modify emulator settings in OpenEmu

### ISSUE THREAD

**Issue by egorgam** [OpenEmu/OpenEmu#4258]
Hi! I cant find information about how I can edit dolphin config for using in OpenEmu. Pls how I can modify it? A most important point is resolution scaling - in MacOS and retina display native resolution looks ugly, but I how I see it can be configured in Dolphin or PPSSPPSDL apps. Thanks!

**Comment by clobber** [comment]
If such a thing existed, you would see it in the UI. Use Dolphin standalone if you need access to advanced preferences.
