### ISSUE TITLE
MAME Support?

### ISSUE THREAD

**Issue by maxoakland** [OpenEmu/OpenEmu#4259]
Are you planning to support MAME?

**Comment by digamejh** [comment]
The "Experimental" release already does. You can find the link below the "Download Now" button on the OpenEmu homepage

**Comment by maxoakland** [comment]
I noticed that but I didn’t see anything about whether this is planned to be officially supported or if it’ll remain experimental. I’m new to OSS so I’m not sure since it wasn’t explicit

**Comment by maxoakland** [comment]
Clobber, why didn't you answer my question?
