### ISSUE TITLE
OpenEmu games don't start with MacOS 10.15.6

### ISSUE THREAD

**Issue by GianGus** [OpenEmu/OpenEmu#4261]
I've just updated my iMac (Retina 4K, 21.5-inch, 2017) with the latest MacOS 10.15.6, re-give privacy settings authorizations but all my games don't start! No error messages, nothing!
I've restarted my Mac, nothing has changed

**Comment by sonriks6** [comment]
Same Here! Runned in cmd-line the app and shows a permissions issue. Can't load any ROM!! Please help!

**Comment by clobber** [comment]
No details, no steps to replicate, no output from Console -- not much we can do here. Am I to assume your issues in #4031 are resolves or is this a duplicate?

Given the lack of information, I'd say try: https://github.com/OpenEmu/OpenEmu/issues/4189#issuecomment-621932852

**Comment by sonriks6** [comment]
Hi! Just solved the issue. I've moved the Home Folder to an External HDD so only had to untick the "Ignore permissions in this drive" (Gef info pane). Now OpenEmu works smoothly.
