### ISSUE TITLE
I have a problem with staggeringly slow SS on my iMac

### ISSUE THREAD

**Issue by SamKoi1224** [OpenEmu/OpenEmu#4263]
I have a problem with staggeringly slow Sega Saturn on my recently modified iMac:

- iMac Late 2009 27" (iMac11,1)
- 2.93GHz Intel Core i7
- 32GB 1067MHz DDR3
- ATI Radeon HD 4850, 512MB
- 1TB SSD
- macOS High Sierra (10.13.6)

I tried to play Hideo Nomo World Series Baseball (Sega Saturn) on OpenEmu v2.0.9, but it was staggeringly slow and unplayable (as attached). The problem is, it worked just fine without any glitches on that iMac before I modified it.

- iMac Late 2009 27" (iMac10.1)
- 3.06GHz Intel Core 2 Duo
- 16GHz 1067MHz DDR3
- ATI Radeon HD 4850, 512MB 
- 1TB SSD
- macOS High Sierra (10.13.6)

The modified iMac looks faster and indeed any other apps (except SS on OpenEmu) do run much faster than before. Don't know why. Can anyone advise how to solve the problem?
 

[ss_hideo_nomo_wsb_slow.zip](https://github.com/OpenEmu/OpenEmu/files/4935825/ss_hideo_nomo_wsb_slow.zip)

_Originally posted by @SamKoi1224 in https://github.com/OpenEmu/OpenEmu/issues/4245#issuecomment-659857933_

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

You will be much happier running on a newer machine that can support our Metal renderer.
