### ISSUE TITLE
Switch Pro Controller won't map for PS1 Games

### ISSUE THREAD

**Issue by pjammy** [OpenEmu/OpenEmu#4265]
Hey y'all, been using OpenEmu fine for months now, haven't had any issues thus far except for this one I ran into when I started emulating PS1 games. My Switch Pro Controller won't let me map inputs for PS1 games. I go to the controller section, select Switch Pro Controller from the drop down, go to map a button, and it doesn't register any of the button presses for any button. My controller has never had any issues, it works perfectly fine on OpenEmu for DS, PSP, and Nintendo games as well as other emulators, I just can't get it to work with OpenEmu's PS1 games for some reason. I've tried resetting the controller and making sure OpenEmu was the only program running to mitigate interference but nothing's worked so far. Any help would be much appreciated. 

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.11.6

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
