### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by WillStern** [OpenEmu/OpenEmu#4267]
When playing either GB or GBA roms (these are the only roms i've tried), I am not getting any sound. I have started these roms up on the emulator core itself (mGBA) and they all work fine, sound included. I am running openemu on MacOS 10.14.6

**Comment by clobber** [comment]
Works fine on 10.14.6 here. Perhaps you have an issue related to multi-output audio devices, in which case you should check the other open issues.
