### ISSUE TITLE
Open emu pokemon platinum after beating champion auto save crash.

### ISSUE THREAD

**Issue by Anonymous20475** [OpenEmu/OpenEmu#4269]
Open emu pokemon platinum after beating champion auto save is impied and the saving stoppes part way. There is no way to keep playing the game after the saving crash. I have to go back to the last save state which i have done but still occours.
![Screen Shot 2020-07-29 at 1 45 42 PM](https://user-images.githubusercontent.com/68933176/88747492-f7c4d300-d1a2-11ea-9a90-80203d6a3325.png)
I am onthe latest mac software 2017 mac book air

**Comment by MaddTheSane** [comment]
> NDS games (especially Pokemon) may have unsolvable problems related to AP patches or DeSmuME's JIT dynarec. Alternatively, try standalone DeSmuME that has the JIT dynarec off by default which may improve compatibility.

[Troubleshooting: Reporting problems](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems).

This is a known bug.

**Comment by Anonymous20475** [comment]
So i download just Desmume
?
