### ISSUE TITLE
iShowU/Multiple Output Device for System Audio Output cuts audio from OpenEmu

### ISSUE THREAD

**Issue by remainmax** [OpenEmu/OpenEmu#4270]
Pretty much exactly as the title describes. I switch over to Multiple Output, which includes iShowU Audio Capture, and after a few minutes all audio output from OpenEmu is cut.

Using Version 2.2.1

I know this has already been addressed here, I saw the thread from Oct 2019, when in dev provided a download link for an audiotest version that was planned to be implemented in later full build, but sadly that link is now dead.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/OpenEmu/issues?q=iShowU
