### ISSUE TITLE
All games lead to gray or black screen when loaded; cannot quit app afterwards

### ISSUE THREAD

**Issue by thomaskresge** [OpenEmu/OpenEmu#4271]
Summary of issue

Every single ROM I attempt to run simply goes to a black or gray screen. This is for any game (zipped or unzipped), console, and core. After that, I cannot close the OpenEmu window and must force quit the app to return to the main screen.

I've tried giving OpenEmu additional permissions in system preferences. I've reinstalled the app multiple times. I've tried older versions of the app, as well as the experimental version, and the same issue persists for all versions.

Let me know if there's a way to provide more information, as that's all I've got at the moment.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Add a ROM to OpenEmu
2. Select game to play

# Expected Behavior

1. Game should run

# Observed Behavior

1. All black or gray screen when game is "loaded"
2. Can still change preferences, etc., but just won't load the game
3. There is also NO sound (I've read a similar issue as this, but people still seem to get audio; this is not the case for me)

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6

**Comment by clobber** [comment]
Try here: https://github.com/OpenEmu/OpenEmu/issues/4189#issuecomment-621932852
