### ISSUE TITLE
how to write a SegaMd game with my mac

### ISSUE THREAD

**Issue by ferried** [OpenEmu/OpenEmu#4273]
i want to write a Sega MD game ,but i have a mac only.
if i have a win so i can use SGDK.
but now i don't know how to start with my mac.

**Comment by clobber** [comment]
Not an OpenEmu issue.

Read: https://github.com/Stephane-D/SGDK/blob/79355ba0102d462cae6fd6b876d596c2f3d15a4c/readme.txt#L49
