### ISSUE TITLE
Weird alternating red and green color artifacts using CRT Royale Kurozumi

### ISSUE THREAD

**Issue by zanew** [OpenEmu/OpenEmu#4275]
You can see this pattern of red and green alternating sections using CRT Royale Kurozumi. I've uploaded an image comparing CRT Geom against Kurozumi for reference.
![b70b0d8](https://user-images.githubusercontent.com/478134/89689211-ec278980-d8d1-11ea-91e3-c4cfbf78b6e4.jpg)

1. Boot up any Super Nintendo ROM.
2. Set shader to CRT Royale Kurozumi.

Environment:
macOS: 10.15.5
OpenEMU: 2.2.1

**Comment by zanew** [comment]
After looking at some examples of this shader running on other emulators, I've determined that this artifact occurs on other systems as well and is most likely the way a PVM/BVM actually displays images.

**Comment by tiramisu222** [comment]
I think this is intentional. CRT screens sometimes have similar artifacts.

**Comment by dvessel** [comment]
This will happen with any shader with sharp contrasting scan lines that doesn't align with the pixel grid of your display resolution.

You can adjust the beam options to eliminate it or minimize it at least. Note the spot power. It's 0.38 by default. Max it out so the ugly pattern is exaggerated. Now raise Min Sigma slightly until it's barely visible then bring back Spot Power to its default.
