### ISSUE TITLE
Save File Multiplication/Duplication in Menu

### ISSUE THREAD

**Issue by ApricumMedia** [OpenEmu/OpenEmu#4277]
I'm playing EarthBound (USA ROM) for the SNES with the SNES9x core on version 2.2.1 of OpenEmu. A few hours in, I noticed the window would freeze whenever I opened the diskette icon "save" pop-up menu from the bottom bar while playing — when opening after some delay, a screen-spanning menu of identical save files appeared, with hundreds of entries with the same name.

# Steps to reproduce

1. Run EarthBound (USA) with SNES9x core on macOS
2. Allow game to auto-save or save manually
3. Continue playing for some time

# Observed Behavior

After playing for some time, opening any menu that shows save files to select and load freezes the window (while the menu is created synchronously on the same thread that draws the UI elements), the game keeps running in the background and can be controlled during this time, the cursor becomes a beachball during this. Once the menu loads, it shows hundreds of entries for the same save files (see attachment). The relevant save files can be checked in `~/Library/Application Support/OpenEmu/Save States/SuperNES/EarthBound (USA)`, no duplicates exist, each save file is present only once.

Somehow, the menu entries get multiplicated (or repeatedly duplicated) while playing. I remember that there were only 4 or maybe 6 duplicate entries for each a week ago, now there are so many that the menu barely opens on a less powerful machine. Opening the menu can take between 20 seconds and a minute. The actual number of files I do have is currently 10.

Any of the menus showing save files have this issue, for instance:

1. Being in-game and clicking the diskette icon
2. Right-clicking the game cover art in the library

# Expected Behavior

Only a single menu entry exists for each save file on disk, no freezing occurs.

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.6 or 10.15.5 (two systems used)

# Additional Information

I began playing on a desktop Mac and decided to move the entire `…/Application Support/OpenEmu` directory to into iCloud Drive and symlinked it back to `…/Application Support` to be keep everything in sync with my MacBook to play while traveling. *Sync issues* may have something to do with this, though the issue persists even when moving the folder back in proper and, as I've said, the files listed aren't actually on disk.

-----------

<img width="598" alt="Screenshot 2020-08-10 at 22 36 49" src="https://user-images.githubusercontent.com/7656669/89830744-ff01be80-db5c-11ea-8375-2abf94572419.png">
<img width="784" alt="Screenshot 2020-08-10 at 22 41 09" src="https://user-images.githubusercontent.com/7656669/89830766-04f79f80-db5d-11ea-8fdc-9aba8451c028.png">

**Comment by ApricumMedia** [comment]
As a second step to investigating this: While there aren't any actual duplicate `.savestate` files on disk that might've been accidentally copied during sync, I checked the SQLite database — as far as I can see, there are 43.180 records for EarthBound save files in there, these are definitely the ones showing up in menus throughout OpenEmu.

There seems to have been a catastrophic disconnect between the physical files and the entries in the database keeping track of them.

**Comment by clobber** [comment]
Usage of iCloud drive, Dropbox or any other "cloud" service to store your Game Library or Save States is unsupported. As you have discovered, you **will** encounter sync issues.

**Comment by adammck** [comment]
@ApricumMedia, I believe this is fixed by #4297. Please let me know if it works for you, if you happen to try it out. You'll need to back up the actual save state files (on disk), delete them from OpenEmu, and drop them back in. Caveat emptor.
