### ISSUE TITLE
OpenEmu is crashing when importing a game in the library

### ISSUE THREAD

**Issue by toxinu** [OpenEmu/OpenEmu#4279]
The first time I try to import a game in my library, OpenEmu is crashing.

# Steps to reproduce

1. Running OpenEmu for the first time on my MacOS Catalina (OpenEmu v2.2.1 6136.54-g90714f36-Release)
2. Import a game with drag-n-drop or "File -> Add to Library"
3. OpenEmu is crashing and exiting with the following error:

```
2020-08-14 23:56:24.664 OpenEmu[78848:8824082] *** Assertion failure in -[OEImportOperation OE_performImportStepCreateCoreDataObjects], /Users/clobber/Code/OpenEmu/OpenEmu/OEImportOperation.m:876
2020-08-14 23:56:24.665 OpenEmu[78848:8824082] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'System should have been detected at an earlier import stage'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3005cb57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff68d0a5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff30085d08 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff32777e9d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   OpenEmu                             0x0000000106e6c0f4 -[OEImportOperation OE_performImportStepCreateCoreDataObjects] + 2414
	5   CoreData                            0x00007fff2fa9d789 developerSubmittedBlockToNSManagedObjectContextPerform + 201
	6   libdispatch.dylib                   0x00007fff69e59658 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00007fff69e656ec _dispatch_lane_barrier_sync_invoke_and_complete + 60
	8   CoreData                            0x00007fff2fa9d675 -[NSManagedObjectContext performBlockAndWait:] + 277
	9   OpenEmu                             0x0000000106e69445 -[OEImportOperation main] + 145
	10  Foundation                          0x00007fff3265b981 __NSOPERATION_IS_INVOKING_MAIN__ + 17
	11  Foundation                          0x00007fff3265abb3 -[NSOperation start] + 722
	12  Foundation                          0x00007fff3265a8d9 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
	13  Foundation                          0x00007fff3265a7a9 __NSOQSchedule_f + 182
	14  libdispatch.dylib                   0x00007fff69e652b9 _dispatch_block_async_invoke2 + 83
	15  libdispatch.dylib                   0x00007fff69e59658 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x00007fff69e5b818 _dispatch_continuation_pop + 414
	17  libdispatch.dylib                   0x00007fff69e5af16 _dispatch_async_redirect_invoke + 703
	18  libdispatch.dylib                   0x00007fff69e67957 _dispatch_root_queue_drain + 326
	19  libdispatch.dylib                   0x00007fff69e68097 _dispatch_worker_thread2 + 92
	20  libsystem_pthread.dylib             0x00007fff6a0b39f7 _pthread_wqthread + 220
	21  libsystem_pthread.dylib             0x00007fff6a0b2b77 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    78848 abort      ./OpenEmu
```

And if I try to reimport it later, nothing is happening but the library remains empty.
I check the library folder and the game is here.

I can run the game without importing it into my library.

# Expected Behavior

1. Run OpenEmu
2. Drag-n-drop my game
3. Library showing my game

# Debugging Information

- OpenEmu Version: OpenEmu v2.2.1 6136.54-g90714f36-Release
- macOS Version: 10.15.6

**Comment by toxinu** [comment]
Got new information, this is happening when I am adding a game to the wrong console. The game is properly showing in the right console library but OpenEmu is still crashing when importing the game.

**Comment by clobber** [comment]
This is vague information. We need exact steps to replicate the crash, including the game you are importing (file name and all).

**Comment by toxinu** [comment]
@clobber Does it mean that you cannot replicate it with any file by following the steps I described?

> This is vague information. We need exact steps to replicate the crash, including the game you are importing (file name and all).

Except from sharing the exact file to you there are no missing steps. I can reproduce it with at least 4 different games btw.
You already have a complete stack trace, it should be a good start. 👍🏻

**Comment by clobber** [comment]
> You already have a complete stack trace, it should be a good start. 👍🏻

Erm, no. I can not replicate hitting that assert by importing games.

**Comment by toxinu** [comment]
I don't know if you read my comment above, which add a little more context:

> Got new information, this is happening when I am adding a game to the wrong console. The game is properly showing in the right console library but OpenEmu is still crashing when importing the game.

For example, click on "Famicom" and import the following SNES game: https://file.io/Lo798wM31t8d
Hope there is no piracy problem about that.

**Comment by clobber** [comment]
> when I am adding a game to the wrong console

That isn't possible to do. Dragging a file into a certain Library does not force it into that Library. That is not the way the importer works.

> https://file.io/Lo798wM31t8d

This link 404's.

Provide *exact* steps and settings to replicate it with a sample game included, or I cannot help you.

**Comment by clobber** [comment]
Duplicate of #3205
