### ISSUE TITLE
Controller Pak Not Working (N64 Emulation)

### ISSUE THREAD

**Issue by nesmaster64** [OpenEmu/OpenEmu#4280]
Very simple - I have an .mpk file for an N64 game - it isn't loading.

# Steps to reproduce

1. Open OpenEmu, play a game that uses the memory card (I'm running WWF No Mercy), and the memory card file (.mpk) is not detected. I have the filename exactly correct, and the file is in the ~/Library/Application Support/OpenEmu/ folder where the working .fla file is. I'm on an Apple laptop, if that helps.

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.5

**Comment by clobber** [comment]
1. Probably that game isn't going to work in the first place, see #3715
2. You are likely restoring an autosave state on launch which is overwriting everything in memory, hence not "seeing" the memory card file.
