### ISSUE TITLE
Mario Golf & Mario Tennis crash

### ISSUE THREAD

**Issue by Waluigi68** [OpenEmu/OpenEmu#4282]
I tried everything: I re-installed the game, I re-installed OpenEmu, nothing worked.

Two of my GBC games (Mario Golf & Mario Tennis) no longer works well, the emulator is crashing after a certain time when I open them and I get the following error message: "Couldn't communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again."

All of my other GBC games works perfectly, I only have a problem with these two games.

**Comment by clobber** [comment]
Post the complete crash log, not whatever that jumbled mess is, please.

**Comment by Waluigi68** [comment]
The crash log should be easier to read here: [https://cdn.discordapp.com/attachments/677929726156865537/744313142028533780/message.txt]

**Comment by shysaur** [comment]
From the crash log it seems that we have already fixed this bug recently in commit aeb0da48. Please check if the following test build resolves the issue: https://drive.google.com/file/d/1fiPscMy0AuTnh_J8VxhPRHY0ZzkZHqNx/view?usp=sharing

**Comment by Waluigi68** [comment]
I still have the same problem.

**Comment by Waluigi68** [comment]
There's also another thing I noticed:
OpenEmu immediately crashes when I'm saving my progress or when I attempt so edit data trough in-game means (ex.: I erase data trough the in-game menu).

**Comment by shysaur** [comment]
No, it's (probably) a bug in the code of our Gambatte core which is triggered by the specific game you are playing.

Try testing the following build of the Gambatte core plugin: https://drive.google.com/file/d/1ren7CKl3OZaOyT4FUUonYwz_QcplDpGX/view?usp=sharing

Steps to test:

0. Close OpenEmu
1. Download and unzip the file above
2. Open a Finder window, press Shift+Command+G, copy paste the following path: "~/Library/Application Support/OpenEmu/Cores", click Go
3. Copy the unzipped core plugin in the folder that just opened, replacing the existing one
4. Open OpenEmu again and test

**Comment by shysaur** [comment]
> OpenEmu immediately crashes when I'm saving my progress or when I attempt so edit data trough in-game means (ex.: I erase data trough the in-game menu).

Cannot reproduce. Please, file one issue per bug and do not try to piggyback multiple problems together.

**Comment by clobber** [comment]
Dupe: https://github.com/OpenEmu/Gambatte-Core/issues/6

**Comment by Waluigi68** [comment]
Your Gambatte build completely fixed my issue, thanks!

**Comment by shysaur** [comment]
Great! A fix will be made available to everybody else in a future core update.
