### ISSUE TITLE
Including Disc 2 and/or 3 cue file causes m3u to not import

### ISSUE THREAD

**Issue by slassen** [OpenEmu/OpenEmu#4285]
# Summary of issue

I've read the reporting guide and the CD and M3U guide. I did follow that guide as well as search open issues and Googled. I am checking for spelling errors, case sensitivity and miscellaneous suggestions found in Google. I am unable to import FF7 Disc 2, 3 and the m3u file. I've attached a screenshot of the `.cue` and `.m3u` files as well as the files in that folder at the bottom of this report in debugging information.

I believe this is not a problem with the `.m3u` and rather something to do with the disc 2/3 or bin or cue files. I have a QT video that I can upload and host somewhere if someone is interested.

Thanks for your time!

# Steps to reproduce

1. Compile from `master` commit hash `111db5b2e7758cc2461b03bcdb957a5cded2043f` using Xcode.
2. Drop PS BIOS files into library.
3. Source ff7 discs with cue and m3u files.
4. Drop m3u file into game library.

# Expected Behavior

- I should be able to drop the FF7 `.m3u` file into the game library.
- The library should recognize it and import the game.

# Observed Behavior

- When I drop the FF7 Disc 1 `.cue` file into the game library the game shows up as FF7 disc one. However, disc 2 and disc 3 do not work. Nothing happens. I retrieved these discs from the same reliable source.
- When I drop the FF7 `.m3u` file into the game library it does not work if I include any cue lines other than Disc 1

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.6

![Screen Shot 2020-08-17 at 6 10 29 PM](https://user-images.githubusercontent.com/6099499/90450160-070ab280-e0b7-11ea-9cac-bf03f8413627.png)

**Comment by clobber** [comment]
Please delete what you have imported of this game from your library and then download known good dumps of the games from a “Redump” set on Archive.org

**Comment by slassen** [comment]
Thank you. I have tried this set: https://archive.org/download/Sony-Playstation-USA-Redump.org-2019-05-27

Could it be that those discs are bad dumps? Or am I looking at the wrong thing?

**Comment by clobber** [comment]
Those are fine, as long as you have unzipped them and built your m3u correctly. You mentioned macOS 10.15, so you may be experiencing a permissions problem there. Follow all the steps outlined here and that should resolve your issue: https://old.reddit.com/r/OpenEmu/comments/gv99fs/ff7_m3u_transferring_help/fstei4e/?context=3

**Comment by slassen** [comment]
Yikes! That was it--I needed to give it full disk access permissions. Thanks again for your help.
