### ISSUE TITLE
Grey screen when opening any game

### ISSUE THREAD

**Issue by ryanmusicco** [OpenEmu/OpenEmu#4287]
Hi,

This has happened twice to me now and I can't remember how I fixed it, when I open a ROM there is just a grey screen and the only way of quitting Openemu is by force quitting. 

Has anyone else had this problem?

thanks
![Screenshot 2020-08-23 at 16 25 57](https://user-images.githubusercontent.com/70103796/90982177-593b5000-e55d-11ea-9681-31389559f0cb.png)

**Comment by clobber** [comment]
Missing version information, missing game information, missing steps to replicate your problem.

https://github.com/OpenEmu/OpenEmu/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by niccolomineo** [comment]
This happens to me when launching a game after I already quit one. Also, it doesn't always happen.
