### ISSUE TITLE
Attempted to install Dolphin through the "Cores Preferences" menu, but it didn't fully install and now it won't let me use it.

### ISSUE THREAD

**Issue by BadgerGoat89** [OpenEmu/OpenEmu#4288]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

Attempted to install Dolphin through the "Cores Preferences" menu, it seemed to install but now it won't let me use it. I can't re-install it, but it won't register on the side bar in any way. I have included a screenshot, notice that the option to install it is not there. 

![Screen Shot 2020-08-23 at 4 34 16 PM](https://user-images.githubusercontent.com/70117630/90992136-99510180-e562-11ea-9b9e-0d6067039fbc.png)

# Expected Behavior

I want to be able to use Dolphin after I install it.

# Observed Behavior

I have included a screenshot.

# Debugging Information

- OpenEmu Version: 2.0.5
- macOS Version: Sierra 10.12.6

**Comment by BadgerGoat89** [comment]
Note: I was able to go and delete the core dolphin file from Application support. I then reinstalled it, and had the same problem. It's letting me install dolphin, but then it isn't recognizing it, so I can't play it.

**Comment by duckey77** [comment]
@BadgerGoat89 , You are running an old version of OpenEmu.  It does not support GameCube.  You can tell by the Console column being blank.
