### ISSUE TITLE
High Sierra Support

### ISSUE THREAD

**Issue by metrofun** [OpenEmu/OpenEmu#4290]
macOS High Sierra is the last MacOS which supports Nvidia. There are still plenty of top-of-the-line MBP with GeForce GT 750M that can't be updated to macOS Mojave due to terrible performance in games. Not mentioning those with eGPUs.

Can OpenEmu be recompiled to support High Sierra? 🎮❤️

**Comment by clobber** [comment]
Sorry, no. We use API that requires a minimum of macOS 10.14. Your information is incorrect - Nvidia GPUs are  still supported on the latest macOS. For games to be performant on modern macOS, they should have a Metal renderer.
