### ISSUE TITLE
Can't play PSP games on OpenEmu with the PPSSPP core

### ISSUE THREAD

**Issue by Rocksaltz** [OpenEmu/OpenEmu#4292]
Everytime I try to play a PSP game it will open and show the developer name screen (Konami, Atlus, etc.) then go to a black screen and freeze. When I quit OpenEmu it gives me "couldn't communicate with helper application". I've tried resetting warnings and reinstalling OpenEmu but nothing seems to fix it. I'm using OpenEmu v2.0.9.1, macOS High Sierra ver. 10.13.6, and I have PPSSPP 1.10.3.1

**Comment by clobber** [comment]
Need an example game to replicate the problem. Also, only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported. Please do not open threads on reddit as well as issues on here at the same time.

**Comment by drpatchadams** [comment]
https://youtu.be/ip0FfkgT7j0


Hope it help

**Comment by clobber** [comment]
> Hope it help

No, it doesn't. I said give me a name of a game (exact file name) so I can try to replicate it.

**Comment by Rocksaltz** [comment]
Sorry about the multiple threads I was just kind of desperate for a
solution. Here's a link to the game I downloaded
https://cdromance.com/psp/shin-megami-tensei-persona-3-portable/.

**Comment by clobber** [comment]
<img width="942" alt="Screen Shot 2020-08-30 at 12 02 30 AM" src="https://user-images.githubusercontent.com/1303132/91651582-2826b800-ea54-11ea-9534-b80738bbece6.png">

It loads fine here on OpenEmu 2.2.1 with the PPSSPP 1.10.3.1 core plugin. Really cannot help you beyond that, as your issue may be attributed to a PPSSPP compatibility problem out of our hands. You should try loading the game "clean" without restoring an autosave state on first load:

* Go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" if prompted to "Continue where you left off"

If that resolves your issue, only rely on in-game memory card saving and not save states going forward.
