### ISSUE TITLE
How to solve invalid driver in openemu arcade mame?

### ISSUE THREAD

**Issue by drpatchadams** [OpenEmu/OpenEmu#4293]
How to update to the last version of mame 0.224 in arcade openemu ?

Thanks 

Before asking your question, please make sure you have searched for an existing similar question in the project Issues and Wiki.
-->

**Comment by clobber** [comment]
Your question is not clear. Sounds like you're asking how to "upgrade" a core plugin yourself to the latest version of MAME? It doesn't work that way. Our latest MAME core plugin is based on MAME 0.219.
