### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by IAmaBoomer** [OpenEmu/OpenEmu#4294]
Summary of issue
"Couldn’t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again."
Happens every time i try to play a game. For the N64 roms, When i try to play them, a black screen appears. and when i click the X button on the window? "Couldn't communicate with a helper application." Any way to fix this?

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Expected Behavior
I want it to play all my ROMS.

# Observed Behavior

- OpenEmu Version: 1.0.4 (experimental)
- macOS Version: 10.10.5.

**Comment by clobber** [comment]
>OpenEmu Version: 1.0.4 (experimental)

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
