### ISSUE TITLE
Cue file "does not seem to be a plain text file" when importing multi-disc game

### ISSUE THREAD

**Issue by drmathochist** [OpenEmu/OpenEmu#4296]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce
Create directory containing

Final Fantasy IX (Disc 1) (v1.0).bin
Final Fantasy IX (Disc 1) (v1.0).cue
Final Fantasy IX (Disc 2) (v1.0).bin
Final Fantasy IX (Disc 2) (v1.0).cue
Final Fantasy IX (Disc 3) (v1.0).bin
Final Fantasy IX (Disc 3) (v1.0).cue
Final Fantasy IX (Disc 4) (v1.0).bin
Final Fantasy IX (Disc 4) (v1.0).cue
Final Fantasy IX (v1.0).m3u

cue files contain
```
FILE "Final Fantasy IX (Disc 1) (v1.0).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
```
and respectively for Discs 2, 3, 4, exactly as downloaded along with corresponding .bin files.

m3u file contains
```
Final Fantasy IX (Disc 1) (v1.0).cue
Final Fantasy IX (Disc 2) (v1.0).cue
Final Fantasy IX (Disc 3) (v1.0).cue
Final Fantasy IX (Disc 4) (v1.0).cue
```

All files have permissions "-rw-r--r--".  All cue and m3u files are plain text (can cat them).

Drag m3u file onto library window of OpenEmu

# Expected Behavior

multi-disc game imports

# Observed Behavior

No import; in console, the following entry occurs in the OpenEmu process

default	19:22:07.848567-0700	OpenEmu	Error Domain=org.openemu.OEDiscDescriptor.ErrorDomain Code=-1 "File cannot be read" UserInfo={NSUnderlyingError=0x600001172df0 {Error Domain=NSCocoaErrorDomain Code=257 "The file “Final Fantasy IX (Disc 3) (v1.0).cue” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/johnarmstrong/Downloads/FF9 (1.0)/Final Fantasy IX (Disc 3) (v1.0).cue, NSUnderlyingError=0x600001173ae0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}}, NSLocalizedDescription=File cannot be read, NSLocalizedFailureReason=File Final Fantasy IX (Disc 3) (v1.0).cue does not seem to be a plain text file.}

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.6

**Comment by clobber** [comment]
Thanks for the detailed report. Hmm it cannot open the file -- sounds like another Catalina permissions issue -- so try granting OpenEmu "Full Disk Access":

Go into [Security & Privacy Preferences](https://support.apple.com/guide/mac-help/change-privacy-preferences-on-mac-mh32356/mac) and remove the existing File and Folder permissions for OpenEmu, if exists, and instead give Full Disk Access.

This is the advice I have given others with a similar problem and it seems to resolve it.

**Comment by drmathochist** [comment]
That seems to do the trick.  Thanks!
