### ISSUE TITLE
Playstation Cheats with Mednafen core version 1.25?

### ISSUE THREAD

**Issue by designbyadrian** [OpenEmu/OpenEmu#4300]
According to #2310, cheats were not available due to Mednafen not supporting it. 

The Mednafen wiki says cheats are supported, and it seems the latest version is the same as the core installed in OpenEmu, yet I cannot find a cheat option in the HUD.

What's the opinion on adding cheats to PSX emulation?

**Comment by clobber** [comment]
> due to Mednafen not supporting it.

Uh, that’s not what it says at all. You’re making that up. I’ll quote:

> No, not yet. In a future Mednafen core plugin update once it is easier to hook that up.

Key phrase: “** once it is easier to hook that up**”
