### ISSUE TITLE
Plans to move to flat design for buttons and preference icons?

### ISSUE THREAD

**Issue by niccolomineo** [OpenEmu/OpenEmu#4302]
Are there any plans to move to a flat design for buttons and preference icons? OpenEmu's skeuomorphism is cool, but feels kind of out of place in the current Mac Os.

**Comment by clobber** [comment]
> out of place in the current Mac Os.

I guess you haven’t seen Big Sur? Anyway, no. The icons for the Preferences tabs will remain. We are, however, continuing to remove the custom theming and replacing it with native controls. More of that in next release.
