### ISSUE TITLE
Auto Keyboard inputs ignored by game window

### ISSUE THREAD

**Issue by SuperTurn** [OpenEmu/OpenEmu#4306]
I have an auto key presser that I use with other apps that works great. I've mapped my PSX controller's X button to the letter K, and have told it to press K every 250 milliseconds. Problem is, the key press never make it to the game. If I open the Help menu, I can see that OpenEmu is getting the keystrokes, but nothing is passed to the emulated game.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Download and install the program Auto Keyboard by MurGaa.com. Give permissions to control computer in Security @ Privacy control panel.
2. Set Auto Keyboard to press a designated key every 250 milliseconds. Send Keystrokes to Focussed Window of Active Application. 
3. Bind OpenEmu's Keyboard input for the key specified in step 2. For example, bind the letter K to the X button for the Playstation, or bind the letter L to the start button on the Game Boy. 
4. Start the Auto Keyboard. 
5. Make OpenEmu's game window the active window. Confirm that keystrokes are being passed by opening OpenEmu's Help menu and watch keystrokes appear in the Search box. 
6. Start your emulated game. 
7. Observe that no keystrokes are being passed to the game. For example, in Pokemon Yellow, bind the Gameboy's Start button to the letter L. Set Auto Keyboard to press L every 250 milliseconds. The Menu does not open and close as it would if pressing the Start Button. 

# Expected Behavior

1. Keystrokes being generated by program Auto Keyboard would be interpreted by game window and processed accordingly. 

# Observed Behavior

1. The OpenEmu program is receiving the keystrokes from the Auto Keyboard application, but the game window is seemingly ignoring these as input. Manually typing the keys on the keyboard works as expected. The movie attached shows this behavior with Final Fantasy IX ignoring the Auto Keyboard press of K, which is bound to the X button of the PlayStation controller. 
[OpenEmu.mov.zip](https://github.com/OpenEmu/OpenEmu/files/5189984/OpenEmu.mov.zip)

# Debugging Information

- OpenEmu Version: 2.2.1 6136.54-g90714f36-Release
- macOS Version: macOS Mojave 10.14.6 (18G6020)

**Comment by clobber** [comment]
It won't work. We receive inputs at a lower level.

https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems#input-keyboardgamepad-not-working
