### ISSUE TITLE
Can't find original (first) CRT filter from years ago

### ISSUE THREAD

**Issue by mickeywilsonsfx** [OpenEmu/OpenEmu#4307]
Hello,

I've been trying to find the original CRT filter that was first used many years ago that came with OpenEMU, but now there's 3 new ones and I don't see the old one. The new CRT-Geom seems similar but it wiggles and hurts my eyes. Does anyone know where I can download the OG version?

**Comment by clobber** [comment]
Sorry, no. The older “filters” were actually Cg shaders and are not supported by the new shader system. Many of the new CRT shaders are customizable, so tweak them to your liking.
