### ISSUE TITLE
psp crashing

### ISSUE THREAD

**Issue by D3R3K9** [OpenEmu/OpenEmu#4308]
Summary of issue

recently the game I have in been playing (persona 3 portable) if i do almost  anything (any of my special attacs or use items) then the game either stops the animation, but the music still plays and camera moves or the whole thing turns grey, I've tried to clean load it multiple times i've checked to see if the save state was the thing that was off or if it was openemu by deleting the game and redownloading it on openemu it did the same thing I also redownloaded openemu and the samethng kept happening i restarted my laptop and still no fix this has happned to me once before and I was able to fix it, but unfortunatley I do not remember how I was able to fix it

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: mojave 10.14.6
-PPSSPP Core version: 1.10.3.1

**Comment by aaronliu0130** [comment]
Please be more specific with your issue by following the bug report. You need to tell the team what game you are playing on what core, else the team cannot reproduce this.

**Comment by D3R3K9** [comment]
> Please be more specific with your issue by following the bug report. You need to tell the team what game you are playing on what core, else the team cannot reproduce this.

I believe that I have fixed it
