### ISSUE TITLE
Keyboard inputs aren't working. Mac Book Air

### ISSUE THREAD

**Issue by TheToastJester** [OpenEmu/OpenEmu#4309]
On my old mac book os, I had bionic kraken open emu downloaded and it worked perfectly fine. I transported that file over to my new computer which is a macbook air, and the keyboard inputs aren't working for the game controls, and it won't let me change the game controls. It lets me open up the emulation so the open emu works on macbook air. I probably have somewhere where my keyboard settings are messed up but I can't find where to fix it. Help would be greatly appreciated, i searched issues and didn't see this asked before

**Comment by clobber** [comment]
> bionic kraken open emu

No idea what you’re talking about. 

> input

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."

**Comment by TheToastJester** [comment]
> > input
> 
> [Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
I read over that prior to posting this and have tried to close all applications and open it, and I don't own any of the interfering applications.

**Comment by clobber** [comment]
What version of macOS? What version of OpenEmu? Instead of deleting and ignoring the issue template, fill out the required information.

**Comment by TheToastJester** [comment]
> What version of macOS? What version of OpenEmu? Instead of deleting and ignoring the issue template, fill out the required information.

I apologize, I am not aware of the template you are referencing. I downloaded it on a Mac Os X Mojave (don't remember the version, and moved it to my MacBook Air Catalina 10.15.5. It is OpenEmu version 2.0.8. I'm going to probably try to redownload OpenEmu today.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

Sorry, cannot help you.
