### ISSUE TITLE
Cannot import m3u file

### ISSUE THREAD

**Issue by okla** [OpenEmu/OpenEmu#4313]
I am trying to add a multi-disc PS1 game (X-Files) represented by m3u file to the library to no avail. All bin/cue files are in the same directory, m3u is in plain text.

[Screen capture representing the issue](https://github.com/OpenEmu/OpenEmu/files/5244718/Screen.Recording.2020-09-17.at.22.20.52.mov.zip)

One clue that I have is that I've tried to add first disc to the library before, but it's not in the library anymore.

Hashes of the files:

MD5 (./X-Files, The (USA) (Disc 1).bin) = e3a7fc1a9b3a390ad709e75e9f79d786
MD5 (./X-Files, The (USA) (Disc 1).cue) = 05c8116e1d77ecace5d97ee1b609eece
MD5 (./X-Files, The (USA) (Disc 2).bin) = e542f4c340b521f07de4a0018044f5ba
MD5 (./X-Files, The (USA) (Disc 2).cue) = d6b91969547b0839024dbff90e9bc1f1
MD5 (./X-Files, The (USA) (Disc 3).bin) = 4c99e26f356b85ae8fa2ed95eecfc35f
MD5 (./X-Files, The (USA) (Disc 3).cue) = 65a1899f810476c7f82e2e588ef291ee
MD5 (./X-Files, The (USA) (Disc 4).bin) = 3724190d308e95b2d244f760b6b292f5
MD5 (./X-Files, The (USA) (Disc 4).cue) = 2e1ffad5a9935069c8f4c2708490f965

Hashes from redump.org:

e3a7fc1a9b3a390ad709e75e9f79d786 *X-Files, The (USA) (Disc 1).bin
05c8116e1d77ecace5d97ee1b609eece *X-Files, The (USA) (Disc 1).cue
e542f4c340b521f07de4a0018044f5ba *X-Files, The (USA) (Disc 2).bin
d6b91969547b0839024dbff90e9bc1f1 *X-Files, The (USA) (Disc 2).cue
4c99e26f356b85ae8fa2ed95eecfc35f *X-Files, The (USA) (Disc 3).bin
65a1899f810476c7f82e2e588ef291ee *X-Files, The (USA) (Disc 3).cue
3724190d308e95b2d244f760b6b292f5 *X-Files, The (USA) (Disc 4).bin
2e1ffad5a9935069c8f4c2708490f965 *X-Files, The (USA) (Disc 4).cue

# Steps to reproduce

1. Move all multi-disc game files to a folder (CUE and BIN files)
2. Create .m3u file containing file names of CUE in plain text
3. Save it in the same folder as multi-disc game
4. Drag and drop .m3u file

# Expected Behavior

Game is added to the library

# Observed Behavior

Game is not added to the library

# Debugging Information

- OpenEmu Version: 2.2.1 (6136.54-g90714f36-Release)
- macOS Version: 10.15.6 (19G2021)

**Comment by clobber** [comment]
See issue: #4296

**Comment by okla** [comment]
Solution worked, thanks. I think it's better to include a note about this Catalina "feature" to the [User guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-multi-disc-game) to prevent further duplicates of the issue.
