### ISSUE TITLE
keyboard not working 

### ISSUE THREAD

**Issue by cancoel** [OpenEmu/OpenEmu#4314]
Hi, I am trying to use the keyboard of my MacBook Pro for a GameBoy Advance Game but it doesn't respond.
In the settings, I am not able to map the keys. My input isn't recognized. I am using the built-in keyboard and I am on Big Sur Beta 7 with OpenEmu 2.2.1 (not experimental).

**Comment by clobber** [comment]
If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here for possible problems: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
