### ISSUE TITLE
Won't open on Mac OS 15.5

### ISSUE THREAD

**Issue by Sloodgelooce** [OpenEmu/OpenEmu#4315]
When I open the zip file for OpenEmu and click on the app, a notification comes up saying "'OpenEmu' cannot be opened because the developer cannot be verified. MacOS cannot verify that this app is free from malware." How do I fix this so I can open the App?

- OpenEmu Version: 2.2.1
- macOS Version: 15.5

**Comment by clobber** [comment]
From the [website](http://openemu.org/):

<img width="280" alt="Screen Shot 2020-09-24 at 8 59 14 AM" src="https://user-images.githubusercontent.com/1303132/94155260-5c6b7980-fe44-11ea-9639-b11fa3351d47.png">

> Please read special instructions for opening. 

Right click the app, open.

**Comment by rherrick** [comment]
I have OS X 10.15.7 and OpenEmu 2.2.1 (i.e. latest of everything) and I still get this message when opening the application by right-clicking it and selecting open. To get rid of it, run the following command:

`xattr -d com.apple.quarantine /Applications/OpenEmu.app`

**Comment by tealyt** [comment]
> I have OS X 10.15.7 and OpenEmu 2.2.1 (i.e. latest of everything) and I still get this message when opening the application by right-clicking it and selecting open. To get rid of it, run the following command:
> 
> `xattr -d com.apple.quarantine /Applications/OpenEmu.app`

if it says that click ok, go to settings, Security & Privacy, and then there will be a thing asking to run it

**Comment by tealyt** [comment]
> When I open the zip file for OpenEmu and click on the app, a notification comes up saying "'OpenEmu' cannot be opened because the developer cannot be verified. MacOS cannot verify that this app is free from malware." How do I fix this so I can open the App?
> 
> * OpenEmu Version: 2.2.1
> * macOS Version: 15.5

if it says that click ok, go to settings, Security & Privacy, and then there will be a thing asking to run it
