### ISSUE TITLE
In setup phase, System Cores Installation step shows no cores in the list and eventually no core is installed

### ISSUE THREAD

**Issue by deepnighttwo** [OpenEmu/OpenEmu#4318]
# Steps to reproduce

1. download and unzip OpenEmu 2.2.1 from http://openemu.org/
2. Got the OpenEmu.app
3. Move it to Application folder
4. Execute it
5. In the System Cores Installation step, it suppose to show lots of cores. But it shows no cores.

<img width="825" alt="Screen Shot 2020-10-01 at 1 28 43 PM" src="https://user-images.githubusercontent.com/631887/94775053-a7136580-03f1-11eb-980d-84f9743dad33.png">

# Expected Behavior

1. Show cores and install cores in setup phase

# Observed Behavior

1. No core shows and no core is installed

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6

**Comment by clobber** [comment]
Not an OpenEmu issue. GitHub had an outage during that time -- other high profile projects were also affected. If that is not the cause, your machine is blocking outgoing connectings to GitHub -- probably some sort of firewall software you have running.
