### ISSUE TITLE
Unable to start game

### ISSUE THREAD

**Issue by Yeetboy36** [OpenEmu/OpenEmu#4322]
I got OpenEmu yesterday for MacBook Air running 10.15.6 and have not been able to start any games (tried N64, GBA, and SNES) due to not being able to press the start or select button. I tried mapping the buttons but I cant change the keyboard controls either, any help?

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Expected Behavior

Play my game
# Observed Behavior

Games remain at title screen and no keyboard presses have any affect 

# Debugging Information

- OpenEmu Version: Not sure how to check
- macOS Version: 10.15.6

**Comment by clobber** [comment]
If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
