### ISSUE TITLE
atarisy1 BIOS suddenly no longer working for some MAME arcade games

### ISSUE THREAD

**Issue by GoldenGriffin93** [OpenEmu/OpenEmu#4323]
Curious if anyone has experienced the atarisy1 BIOS no longer being recognized by some games (my culprit is Indiana Jones and the Temple of Doom).

**Comment by clobber** [comment]
>suddenly

The MAME core plugin, as happens every so often, was recently updated to the latest version of MAME -- 0.225 as of writing. You need to be using an `atarisy1.zip` from a more recent MAME ROM set. You can read the error message as well as anybody else -- it's very clear on what is wrong and how to resolve.
