### ISSUE TITLE
Arcade/MAME "Error: Unable to load state due to an Invalid Header."

### ISSUE THREAD

**Issue by JuddaBudda** [OpenEmu/OpenEmu#4324]
Getting " Error: Unable to load state due to an Invalid Header. Make sure the save state is correct for this machine " when trying to load save states from Mame saves states.. Auto and Quick. Curious to know if this was due to a different Mame version from a previously release of OpenEmu? I'd like to open some high score save states. If this is only an issue in Mame.. I completely understand and apologize for bothering with a non OpenEmu related issue, but If you could help.... I would greatly appreciate it. 

Thank You

**Comment by clobber** [comment]
Yes, the MAME core plugin was updated to the latest version of MAME and those save states are often not compatible. Sorry, not an OpenEmu issue. Nothing you can do about it.
