### ISSUE TITLE
OpenEmu still not responding (v. 2.2.1) (OS 10.15.7)

### ISSUE THREAD

**Issue by coolman6** [OpenEmu/OpenEmu#4326]
Hey again. It's been a while since I've been here. I posted an issue a while back about how OpenEmu wasn't responding at all for me. Well unfortunately OpenEmu is still not working for me and I'm still just a bummed out as before. I just updated my Mac to version 10.15.7 in hopes that it would fix it. It didn't. I still get the "beach ball" cursor whenever I open it and I can only exit via force quitting. I tried doing the same actions as previously mentioned in my last post about deleting and reinstalling the applications but still didn't work. I truly just want to enjoy OpenEmu. Is there a way to fix this again?

**Comment by shysaur** [comment]
Did you delete the directory `~/Library/Application Support/org.openemu.OEXPCCAgent.Agents` as suggested in the other comments to your previous bug report?

Anyway, you can continue posting there instead of creating another issue report :)
