### ISSUE TITLE
How to use core plugins?

### ISSUE THREAD

**Issue by JoGoTheVO** [OpenEmu/OpenEmu#4327]
Hi! I have the Reicast core plugin that I wish to use for OpenEMU, but I have no idea how to import or use it. Any suggestions?
Also worth noting, will major Dreamcast support happen anytime soon? (Redream core is great, I'd recommend that too)
Feels weird we have the GameCube, but not the Dreamcast - or even the PS2!

**Comment by clobber** [comment]
Alpha status core plugins are not supported.
