### ISSUE TITLE
Xbox Elite Serie 2 Controller : No available controller

### ISSUE THREAD

**Issue by Thomasdvrd** [OpenEmu/OpenEmu#4328]
Hi , 

# Expected Behavior

Connecting my XBOX Elite Serie 2 Controller to my Mac via Bluetooth (or even usb-c cable) 
See the controller in the Input panel in Control setting

# Observed Behavior
When everything is connected, openEmu does not recognize my controller (for steam or other game it just works seamlessly. I want to be able to play with my controller. 

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: Catalina 10.15.7

**Comment by clobber** [comment]
Do not open duplicate issues. Pretty easy to read the guide before opening an issue here.
