### ISSUE TITLE
Keyboard not responsive to any input (macOS 11)

### ISSUE THREAD

**Issue by Gravydog-316** [OpenEmu/OpenEmu#4329]
Summary of issue
Keyboard not working as actual game controller in OpenEmu

# Steps to reproduce
Games are opening & loading properly, but OpenEmu is not responsive to any keyboard commands/keystrokes.

# Expected Behavior
Trying to use keyboard as a game controller, but nothing is happening.

# Observed Behavior
Game opens properly/loads properly, but the keyboard has no effect on any actual game controls.
Keyboard still works with Open Emu app commands (command-O to open, command-q to quit, etc.)

# Debugging Information
- OpenEmu Version: v2.2.1 (6136.54-g90714f36-Release)
- macOS Version: macOS 11

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."

**Comment by fishme** [comment]
@Gravydog-316 I had the same issue with 11.x - 
Open System Preferences -> Security & Privacy -> "Tab" Privacy -> Input Monitoring -> activate OpenEmu.

That should work.
