### ISSUE TITLE
After quitting OpenEmu app, the windows close, but app doesn't quit. No way to quit/close the OpenEmu app.

### ISSUE THREAD

**Issue by Gravydog-316** [OpenEmu/OpenEmu#4330]
Summary of issue
Trying to quit OpenEmu app, dialog appears asking if i want to close current game,
& after confirming, the OpenEmu itself closes the windows, but does not actually quit the app.
There is no way to quit the app.

# Steps to reproduce
1. Chose to quit the OpenEmu app;
2. dialog confirmation window appears, asking if i want to close currently open game;
3. After confirming that I want to close the currently open game, & quit the app,
the open windows close, but the actual OpenEmu app doesn't quit.
The command-q key command in the menu is greyed out, as well.

# Expected Behavior
When quitting the app, the app should quit.

# Observed Behavior
After quitting the app, & confirming that i want to close the open game, the open game window closes, but the actual app doesn't quit.

# Debugging Information
- OpenEmu Version: 2.2.1 (6136.54-g90714f36-Release)
- macOS Version: macOS 11
===
![image](https://user-images.githubusercontent.com/73397160/97086731-666ace80-15e2-11eb-94b3-d88b5e20931c.png)

**Comment by clobber** [comment]
>macOS Version: macOS 11

You are using a macOS 11 *beta*, not macOS 11. It is required to note which version of the beta. Anyway, macOS betas are unsupported and I do not believe this issue is happening with current development build of OpenEmu so we will close for now.
