### ISSUE TITLE
Request: Remember location of control bar

### ISSUE THREAD

**Issue by OPStellar** [OpenEmu/OpenEmu#4334]
When I am using OpenEmu and I move the control bar (the bar with the pause/play, save/load, etc. controls), it only remembers where it has been placed as long as I keep the window active. As soon as I switch to a different window and return to OpenEmu, the control bar is back in its default spot.
I would like to have the controls out of the way of the emulator, but they keep reappearing over the emulator screen if I switch windows, which I do often if I'm streaming on Discord. (I also think OpenEmu should get a Discord server, btw.)
I don't mind where the control bar starts, but if it could remember where I place it for at least as long as I have a game running, that would be better than this aggravating auto-placement-reset it does.
Is there already a solution to this? If not, can one be implemented?

**Comment by clobber** [comment]
I think your best bet is to just hide it. Controls > Always Hide HUD, or Shift+Command+H.
