### ISSUE TITLE
openemu bios

### ISSUE THREAD

**Issue by juanchi42** [OpenEmu/OpenEmu#4335]
buenas tardes, quisiera saber como y donde descargar bios para juegos mame ya que me tira un error y no puedo solucionarlo  ( Hat Trick Hero '95 (Ver 2.5J 1994/11/03) (hthero95.zip) requires:

pwrgoal.zip  	- NOT FOUND

These ROMs must be from a MAME 0.225 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files.)   ademas quisiera saber si se le pueden agregar creditos a los juegos ? ejemplo, el sunset rider, tiene 9 creditos y cuando se terminan, vuelve al inicio, quisiera agregarle mas para poder continuarlos.
desde ya, muchas gracias

**Comment by clobber** [comment]
* English only.

* Sorry, no, we cannot help you find and download games. Search Google and Archive.org for that.
