### ISSUE TITLE
controls not working on gameboy advanced

### ISSUE THREAD

**Issue by ToonSquirrel** [OpenEmu/OpenEmu#4336]
I have this on my MacBook Air,  and the controls worked really good until now, where non of the buttons work.  The game it doesn't work on is Pokemon Ruby,  but that's the only game I play

**Comment by ToonSquirrel** [comment]
I have tried restarting the console and it doesn't work

**Comment by clobber** [comment]
If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here for possible problems: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
