### ISSUE TITLE
*seeming* arbitrary refusal of certain snes roms (ver 2.2.1)... known issue?

### ISSUE THREAD

**Issue by splrb** [OpenEmu/OpenEmu#4337]
Summary: when trying to import SNES roms translated by Aeon Genesis (Metal Max, Assault Suits Valken, Bahamut Lagoon, etc.) they are *seemingly* universally unrecognized by the app. They will sometimes be scanned, but do not appear in the library, and do not produce any error message, or rejection notification, etc. That is literally all there is to it. As I only have my own machine, I can't know if this is a universal problem, or if it is intrinsic to the current version. I have loaded plenty of other SNES roms, and got Chrono Chross, and plenty of other multi disc games working fine. As such, there are no other apparent issues. If someone could address this, would be grateful. My retro-pi's screen died, and am trying to transfer roms from, to laptop. This issue... as well as getting the app to recognize battery saves are proving difficult. I have read the other posts about that secondary problem, and there doesn't seem to be a consensus on how to address it. Would be a bonus if someone can provide a helpful solution. Thanks.

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.14.6

**EDIT**: I realized that there is one game that HAS loaded from that website... the game Madara, but that is for the NES. Not sure why only the SNES games seem to be having trouble.

For those who don't know, you can find a list of the games to test it yourself at the link below:
https://agtp.romhack.net/projects.php

**I should note, I have only played at most ten titles that were translated by that team, and so I can't say which ones, if not all I would be having a problem with, if this is simply a local problem, and not general to the application's current version.""

**Comment by splrb** [comment]
For those who don't know, you can find a list of the games to test it yourself at the link below:
[](https://agtp.romhack.net/projects.php)

**Comment by clobber** [comment]
> known issue?

No. Drop a link to exactly what you're trying to import, otherwise I cannot help you.

**Comment by splrb** [comment]
https://cdromance.com/snes-rom/assault-suits-valken/
There's one. All of the titles can easily be found on cdromance. If you wish, I suppose I can provide links to each game... however, on my end, it seems to be a very general problem. As I said, when checking through which games were not loading, they were all from the website I linked to in the original post. That is just a list. Not download links. But it should provide a mostly complete list of titles that would fit this description, in case it is in actual fact a bug, or something.

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing

> Single ROM files per zip may be imported

That is why the archive you linked me does not import. Extract it first and then import the .smc file. Feedback regarding import failures will be added in the next release.

**Comment by splrb** [comment]
Thanks.
