### ISSUE TITLE
The games in my library won't load if you try to play them and won't close unless force quit

### ISSUE THREAD

**Issue by paralance** [OpenEmu/OpenEmu#4339]
When I try to boot any game, the screen stays blank and doesn't load. When trying to quit the application, nothing happens and it stays frozen, unless you force quit the application. Why could this be happening? Is this a bug in the software or a problem with my computer?

**Comment by shysaur** [comment]
This is a known issue (#4299). To fix, perform the following steps:

1. In Finder, type Shift+Command+G (or alternatively, from the "Go" menu select "Go to Folder...")
2. In the dialog that appears, copy-paste the following text (excluding the quotes): "~/Library/Application Support/", then click "Go"
3. Inside the folder that just opened, find the folder named "org.openemu.OEXPCCAgent.Agents" and drag it to the Trash. Authorize the operation with your password if required.

**Comment by paralance** [comment]
This did not work. Every time I delete it from Application Support it re-appears. What can I do?

**Comment by clobber** [comment]
@paralance Sounds like a permissions problem, but also try here: https://github.com/OpenEmu/OpenEmu/issues/4189#issuecomment-621932852

**Comment by paralance** [comment]
I just realized that I was using a multi-output audio device. I believe this is why I’m having the problem so I will switch it back to my Scarlet Solo audio output.
