### ISSUE TITLE
Issues with analog stick sensitivity: NDS, MAC, Xbox-360 wired controller

### ISSUE THREAD

**Issue by ColeWunderlich** [OpenEmu/OpenEmu#4342]
When playing with the NDS plugin on Mac 12.6 I am having an issue where the left analogue stick is overly sensitive.  Up, down, and right directions are all fine, but upon pushing it left it seems to continuously register left input, causing things to continue to move left until I input another direction.

I am wondering if there is any way to adjust this, specifically the controller deadzone.  Due to the fact I'm on MacOS 12.6 and openEMU 2.0.6.1 I know this is no longer supported.  I was still hoping I might be able to get some advice on a way to fix this myself, I have programming experience and am not afraid to dig into the files and tweak things.  So far I have found the plugin controller settings, but cannot figure out what would need to be changed to adjust the sensitivity or deadzone.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

All the analog fixes are in the latest version of OpenEmu. There is nothing we can do to help you.
