### ISSUE TITLE
Need help editing controller left stick sensitivity and/or deadzone

### ISSUE THREAD

**Issue by ColeWunderlich** [OpenEmu/OpenEmu#4343]
As I mentioned in issue #4342 I AM AWARE THAT ONLY THE LATEST VERSION IS SUPPORTED.  Despite that I was hoping to get some advice on how I might be able to address this issue **myself**.  Surely there must be a config file somewhere I could edit/hack to increase the deadzone/decrease the sensitivity.

**Comment by clobber** [comment]
As mentioned in your previous issue, "There is nothing we can do to help you." Accept the answer and move on.
