### ISSUE TITLE
Mac goes into call audio when any game is run

### ISSUE THREAD

**Issue by Rosquash** [OpenEmu/OpenEmu#4344]
When I run a gba game, the sound will go into the audio when a call is being made.
When running a DS game, the sound will go into call audio, however no sound from the ds game is made.
This happened once I updated to Big Sur
edit: this also only happens when my AirPods Pro are connected

**Comment by Suneski** [comment]
Just upgraded to Big Sur today, and having same issue. Can confirm similar behavior (going into call audio) when playing Game Boy Color games.

**Comment by jahio** [comment]
Just tried my SNES games after upgrading to Big Sur, and I have the same problem. No audio output, but the system seems to think I'm trying to use my Bluetooth speaker as a microphone.

**Comment by clobber** [comment]
Should not be a problem as of OpenEmu 2.3
