### ISSUE TITLE
Trying to use a mouse/trackpad

### ISSUE THREAD

**Issue by JCornford83** [OpenEmu/OpenEmu#4347]
I am trying to play Duckhunt, but I don't have any way to control/shoot, I have tried with a keyboard, a USB mouse, a bluetooth mouse and a magic track pad 2, but I am having no luck. Talking to people on Reddit they have said that they can use it and they don't have to do any setup, it just works, any suggestions?

I am running Mac Mini with High Sierra 10.13.6 and OpenEmu 2.0.9.1

Any help would be greatly appreciated.

**Comment by tiramisu222** [comment]
I made an account to respond and tell you to check permissions and remap, but it occurred to me that Duck Hunt is a NES Zapper title. The dev officially states that mouse is used for light gun on Reddit and it requires no config, but I haven't tried it out. Oh well, at least I have a GitHub account now.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
