### ISSUE TITLE
Does the Stadia controller is supported?

### ISSUE THREAD

**Issue by ChristoRibeiro** [OpenEmu/OpenEmu#4350]
Hi and big thanks for the work on this project 🙌

Recently I got a [Stadia controller](https://store.google.com/product/stadia_controller) and I was wondering if it's supported by OpenEmu? or it will be supported?

**Comment by shysaur** [comment]
The Stadia controller website specifies it is "HID Compatible", thus it should work without issues with OpenEmu -- at least via the USB interface.

If you encounter reproducible serious problems with it once you have it you can report them here, however we don't have one of these controllers to test, therefore our ability to help will be quite limited.
