### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by miaaaww** [OpenEmu/OpenEmu#4351]
Is a native M1 Mac release available or is Rosetta emulation the only way to install it?

**Comment by shysaur** [comment]
We are currently preparing a Universal release of OpenEmu for M1 Macs, but it's not ready yet because we are also busy with fixing bugs and adjusting the UI for Big Sur. In the meantime, you will indeed have to use Rosetta. We have tested OpenEmu under Rosetta and it already works quite well.

**Comment by ridicolos** [comment]
@shysaur Is there an issue or something else in which we can keep track of the current status of the development of the Apple Silicon version?
