### ISSUE TITLE
Couldn't communicate with a helper application

### ISSUE THREAD

**Issue by LeChatParle** [OpenEmu/OpenEmu#4352]
Anytime I try to open a GBA ROM, I get the "Couldn't communicate with a helper application" error and the app stops working. Below is my error log

[OpenEmuHelperApp_2020-11-27-074112_MBP.txt](https://github.com/OpenEmu/OpenEmu/files/5608115/OpenEmuHelperApp_2020-11-27-074112_MBP.txt)

**Comment by clobber** [comment]
Looks like the mGBA update broke save state compatibility for whichever game. Load the game without restoring an autosave state on first load:
* Go to OpenEmu > Preferences > Library, click "Reset warnings"
* Open your game and click "No" if prompted to "Continue where you left off"

**Comment by emieliason** [comment]
Hi – I don't think my issue was a duplicate. I tried resetting warnings and not continuing where left off and issue persists :(

**Comment by clobber** [comment]
@emieliason You wouldn't be getting the message that a save state crashed if you weren't loading a save state. What's the message after you choose not to? What game, exactly? It may not be compatible with mGBA. I noted that there appear to be issues with mGBA 0.8.4. If you can replicate the game not booting in the mGBA standalone app, it should be reported upstream.

**Comment by emieliason** [comment]
@clobber I saw somewhere else on the forum that you could delete the core from >Library and reinstall in Preferences, which fixed the issue. Sorry about that!! Basically I would be loading a save state and it would be a blank screen, when I exited it it would give me the "mGBA quit unexpectedly after loading a save state" message. Happened with all GBA roms (mostly Pokemon, but also Earthbound, Kirby, etc.).

**Comment by clobber** [comment]
@emieliason Okay good, sounds like previously the core download may have been corrupted. Not the first time I've heard of that.
