### ISSUE TITLE
Cheats sometimes don't turn off

### ISSUE THREAD

**Issue by Coaggly** [OpenEmu/OpenEmu#4354]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Turn on a cheat
2. Turn off cheat
3. Cheat sometimes is still active. Has only happened twice ever, once yesterday and once today.

# Expected Behavior

1. Cheats to always be off when turned off

# Observed Behavior

1. See above.

# Debugging Information

- OpenEmu Version: 2.2.1
- macOS Version: 10.15.7

**Comment by clobber** [comment]
Nothing specific to replicate here, and the issue you are describing is probably emulator and/or cheat engine specific where we can't do anything about it.
