### ISSUE TITLE
Fullscreen mode fills up background with red bars

### ISSUE THREAD

**Issue by schaarmax** [OpenEmu/OpenEmu#4355]
Hi I have a question, maybe someone here knows a fix for this issue.

A few hours ago I started seeing red bars next to my game in full screen mode. I'm using a mac and recently updated to Mac OS Big Sur. I'm running the newest OpenEMU version. This is unrelated to the game I play, but happens everytime I press fullscreen and play for a few seconds. Also happened when using desmume. Has anyone else who's using a mac run in to this issue?

![image](https://user-images.githubusercontent.com/75286524/100687717-17524f00-3381-11eb-9dbf-486331824587.png)
![image](https://user-images.githubusercontent.com/75286524/100687726-1c170300-3381-11eb-9743-41dc932e5f35.png)
![image](https://user-images.githubusercontent.com/75286524/100687740-1faa8a00-3381-11eb-9579-8aa7776f3e9e.png)

# Debugging Information

- OpenEmu Version: v2.2.1
- macOS Version: v11.0.1

**Comment by clobber** [comment]
Which shader?

**Comment by joecalfire** [comment]
YES! I'm having the exact same issue. 


OpenEmu Version: v2.2.1
macOS Version: v11.0.1

**Comment by schaarmax** [comment]
> Which shader?

All of them

**Comment by TotemG** [comment]
same here, I got nothing to do but rollback to Catalina :p

**Comment by J-rg** [comment]
On 2.3.1, does selecting a scale other than “Fill Screen” fix this? (controls bar → gear icon → Scale → _x)

**Comment by schaarmax** [comment]
Yes it does, but as soon as I change it back to “Fill Screen” the red lines reappear.

**Comment by ArcadeH0uze** [comment]
Is there any fix for this yet? It's kinda annoying, ESPECIALLY when playing DS games

**Comment by J-rg** [comment]
If upgrading to Monterey does not fix this, please [report the issue to Apple](https://feedbackassistant.apple.com/) in case you have not already done so, chances are they may not even be aware of it yet.

You can also enable „Always use popout gameplay window“ in the gameplay preferences, which hides the bars on any system but NDS.

**Comment by papillonsRevenge** [comment]
@schaarmax Do you know why you have the main screen a 2nd time on top of the touch screen in the 16:9 / 16:10 view? Any way to disable that? Is that supposed to be a "feature"?
