### ISSUE TITLE
Couldn't Communicate with a Helper application 

### ISSUE THREAD

**Issue by TheAlster** [OpenEmu/OpenEmu#4356]
i've tried everything even getting rid of openEmu but nothing seems to work. it just keeps popping up with "Couldn't Communicate with a Helper application"

i don't know anything about coding so I have no idea what to do :(, all ive done is updated to Big Sur and now it wont work.
Im also sorry if this has already been answered i just couldn't find if it had been.

Ive linked the logs here tho, hopes this helps, thanks guys
[OpenEmuHelperApp_2020-11-27-074112_MBP.txt](https://github.com/OpenEmu/OpenEmu/files/5627353/OpenEmuHelperApp_2020-11-27-074112_MBP.txt)

Oh and i have 
openemu 2.2.1 
mac OS 11.0.1

**Comment by auroricdragon** [comment]
I have this exact same problem

**Comment by shysaur** [comment]
See issue #4352. To fix:

- Go to OpenEmu > Preferences > Library, click "Reset warnings"
- Open your game and click "No" if prompted to "Continue where you left off"
