### ISSUE TITLE
No sound in PSP games.

### ISSUE THREAD

**Issue by Kadleth** [OpenEmu/OpenEmu#4357]
Loaded "Parodius Portable" & "Twinbee Portable". Neither game had any sound although the visuals seemed to be working fine.
Tried outputting audio to the computer speakers, to headphones (audio jack), to a TV (HDMI) & to AirPods (Bluetooth). Neither produced a sound. Turning the laptop on & off didn't solve the problem.
Checked with NES, SNES & Genesis games, sound isn't a problem.

Have latest OpenEmu & OS upgrades to date (December 3rd, 2020):

OpenEmu v2.2.1
6136.54-g90714f36-Release

PPSSPP 1.10.3.1

MacOS Catalina 10.15.7
MacBook Pro (Retina, 13-inch, Late 2013)
2.8 GHz Dual-Core Intel Core i7
8 GB 1600 MHz DDR3
Intel Iris 1536 MB

**Comment by clobber** [comment]
Cannot replicate this with Parodius Portable -- I hear sounds when I move up and down the menu in-game. I believe your underlying issue is resolved with OpenEmu 2.3, available now.
