### ISSUE TITLE
Nintendo DS Touch Screen - Swipes and Circles

### ISSUE THREAD

**Issue by Josh-I-Am** [OpenEmu/OpenEmu#4359]
Hi!
I'm playing Mario Party DS and it's practically impossible to win minigames like Cherry-Go-Round and Rail Riders because it's _also_ practically impossible to use the mouse to make quick strokes from the bottom of the screen to the top, or to spin the touch screen in rapid circles. I mean, you can't program any touch screen actions to your gamepad. Are there any ways to perform these actions in a way that's effective, easy on the carpal tunnel, and without expensive peripherals? And if not, would you guys consider developing a method of sorts?

**Comment by clobber** [comment]
No, and stop asking.
