### ISSUE TITLE
Stop harassing about accessibility

### ISSUE THREAD

**Issue by tenmilez** [OpenEmu/OpenEmu#4361]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

Open OpenEMU

# Expected Behavior

If I've already declined to grant accessibility to OpenEMU for keyboard access, then I should not get reprompted about it 

# Observed Behavior

Will always prompt about this

# Debugging Information

- OpenEmu Version: 2.2.1 6136.54-g90714f36-Release
- macOS Version: 10.15.7 (19H114)

**Comment by clobber** [comment]
Has been explained before -- this has nothing to do with OpenEmu. Toggle the setting. We read an Apple-provided API. Apparently this problem is resolved in macOS 10.11 Big Sur.
