### ISSUE TITLE
Hori Fighting Stick Mini, USB 3.0 on macOS 11.0 on a MacBook  2016 15.4"

### ISSUE THREAD

**Issue by inspiredlabs** [OpenEmu/OpenEmu#4363]
Summary of issue

# Debugging Information

- OpenEmu Version: `v2.2.1`
- macOS Version: `11.0 Beta` Big Sur (`20A5364e`)
- Version: `1.14`, `Hori Fighting Stick Mini, USB 3.0`
  - Product: `0x00ed`
  - Vendor: `0x0f0d  (HORI CO., LTD.)`

# Steps to reproduce

1. Plug in Hori Fighting Stick Mini, to USB-C to USB-A adapter
1. Choose `Input` from select drop-down in "controls" tab

# Observed Behavior

1. Plug in Hori Fighting Stick Mini, to USB-C to USB-A adapter appears in `Input` from select drop-down in "controls" tab
1. the adapter works on the SNES clone and a Madcatz Arcade device (so it does work).
1. I can connect the Hori device to my Windows 10 laptop (so it does work).
1. I have confirmed that it is up-to-date using: https://stores.horiusa.com/fighting-stick-mini-4-firmware-update/
1. Plugging in Hori Fighting Stick Mini, USB 3.0 on macOS 11.0 on a MacBook 2016 15.4" appears for a split second and disappears.

# Expected Behavior

1. Plug in Hori Fighting Stick Mini, to USB-C to USB-A adapter
1. Choose `Input` from select drop-down in "controls" tab
1. Gameplay Buttons are editable/playable

**Comment by vkedwardli** [comment]
It is HORI's problem, they are doing something special in the firmware which doesn't support macOS.

For software fix: (a bit hard for Big Sur, but many successful cases)
Install https://github.com/360Controller/360Controller

For hardware fix:
Buy a Mayflash Magic-NS / Magic-S Pro USB Stick

**Comment by ultranano** [comment]
Found a solution today for Hori Stick Mini PS4 version - Working and tested on Bis Sur 11.2.3

1 - Open OpenEmu
2 - Put Switch on Joystick to PS3
3 - Keep Pressed PS4+Options Buttons
4 - Connect to Mac using USB to USB C Adapter

Device remain connected and work properly!
Repeat process when you disconnect the joystick.

**Comment by vkedwardli** [comment]
@ultranano wow is this a hidden mode? What is the USB device name when you connect it like this?

**Comment by inspiredlabs** [comment]
> 2 - Put Switch on Joystick to PS3
> 3 - Keep Pressed PS4+Options Buttons
> 4 - Connect to Mac using USB to USB C Adapter

Confirmed it is working, thanks for posting your finding.

**Comment by inspiredlabs** [comment]
> @ultranano wow is this a hidden mode? What is the USB device name when you connect it like this?

The joystick doesn't change when I see how the device is enumerated on the USB controller: `About this Mac, System Report, Hardware, USB, Bus`.

**Comment by vkedwardli** [comment]
I have a player reported that, the Vendor ID + Product ID do change for DInput mode vs XInput mode

Default XInput mode:
![telegram-cloud-photo-size-5-6339285224415931429-y](https://user-images.githubusercontent.com/602245/127750926-60642b46-64bc-45b3-92ed-4929f9dc6a44.jpg)

DInput mode thru the 2 button press trick:
![telegram-cloud-photo-size-5-6339285224415931430-y](https://user-images.githubusercontent.com/602245/127750944-46f647e7-e26b-4ed8-b27f-03bee8bb2344.jpg)
