### ISSUE TITLE
N64 Games Crash on Start.

### ISSUE THREAD

**Issue by ikea48** [OpenEmu/OpenEmu#4364]
Info about Issue.

# Steps to reproduce  
When I open some N64 games like 95x (A Rom Hack) It will crash and say "Couldn't communicate with Helper Application"
<img width="372" alt="Screen Shot 2020-12-19 at 3 40 41 PM" src="https://user-images.githubusercontent.com/75869245/102699145-94e6dd80-4210-11eb-90f8-93c44ac2174b.png">
# Expected Behavior

It should Open the game and play it 

# Observed Behavior

1. The game will try to load but will show a gray screen, soon it will show the error "Couldn't communicate with Helper Application"

- OpenEmu Version: 2.2.1  6136.54-g90714f36-Release
- macOS Version: macOS Big Sur 11.1 for Apple M1 Macs
- Rom Link to test with: http://www.mediafire.com/file/c4f3i64r1lo6d9b/sm64.jp.z64/file

**Comment by ikea48** [comment]
*To see the error you have to power off the game after it shows the gray screen*

**Comment by clobber** [comment]
> Rom Hack

Mario 64 and other N64 ROM hacks are notorious for not working on real N64 hardware by taking advantage of old broken emulator behavior. As emulators are going in the direction of accuracy it will be up to the ROM hackers to fix their hacks.
