### ISSUE TITLE
How to change language setting or alternatively how to import a DeSmuMe save file

### ISSUE THREAD

**Issue by AtomicAllele** [OpenEmu/OpenEmu#4369]
Hello! I'm trying to play pokemon mystery dungeon explorers of sky in spanish. 
I've set my computer's language to spanish which didn't work. I've set my computer's region to spain and the Open Emu region to auto in hopes that the spain setting would transfer but it didn't work. I also set the Open Emu region to europe but that also didn't work.

I already had a save file in spanish on desmume which I've tried to import (because I've had audio and graphics issues playing it on desmume). I've tried placing it in Open Emu's Desmume Battery Saves folder and in Open Emu's save state folder but I could not load it, either through the UI or trying to open the file with Open Emu using "Open With". I've tried all of these methods using both the standard exported .dsv file and the exported raw save data file.

I'm doing this on macOS Mojave version 10.14.6 if this information helps.

**Comment by clobber** [comment]
Not possible yet.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#1110
