### ISSUE TITLE
OpenEmu Final Fantasy VII for PS not showing up

### ISSUE THREAD

**Issue by sheloves-e** [OpenEmu/OpenEmu#4370]
I have two files that I downloaded for OpenEmu, one .cue and .ecm. Ive seen guides on why it doesnt show up in my games library when I drag it there, but none have helped or Im just not good at programing to know what to do. Ill put a couple of pictures I can take of TextEdit and the files itself.
Im on MacOS, thanks!
![Screen Shot 2020-12-21 at 18 22 14](https://user-images.githubusercontent.com/67638818/102827709-75d77f80-43b9-11eb-84ce-8547cbeae5d2.png)
![Screen Shot 2020-12-21 at 18 22 43](https://user-images.githubusercontent.com/67638818/102827761-8687f580-43b9-11eb-923b-a8b75bb6670d.png)

**Comment by sheloves-e** [comment]
the data.bin.ecm in textedit was added, I forgot to delete that when I took the screenshot, sorry

**Comment by clobber** [comment]
You're not following directions. See the guide in the wiki and read carefully.
