### ISSUE TITLE
Pokemon Mini icon shows at an incorrect size

### ISSUE THREAD

**Issue by livid** [OpenEmu/OpenEmu#4371]
After upgrading to 2.3, Pokemon mini icon shows an incorrect size like this:

<img width="1086" alt="Screen Shot 2020-12-23 at 3 13 05 AM" src="https://user-images.githubusercontent.com/11427/102990867-f89d2f00-44cc-11eb-9710-2cd6f8f99d24.png">

OpenEmu version: 6190.646-g1aa76ae3-Release
macOS version: macOS Big Sur 11.1

**Comment by madhattermattic** [comment]
Just wanted to confirm that this is also the case in Catalina 10.15.7 (19H2).

**Comment by clobber** [comment]
Alpha system plugins (these do not have any supported cores) were included by mistake in the "experimental" app bundle. This has been fixed and reuploaded here: https://github.com/OpenEmu/OpenEmu/releases/download/v2.3/OpenEmu_2.3-experimental.zip
