### ISSUE TITLE
New consoles in list, but no option to download cores

### ISSUE THREAD

**Issue by madhattermattic** [OpenEmu/OpenEmu#4372]
Really excited to see the experimental cores active, and I'd love to test them out.

# Steps to reproduce

1. Downloaded the new experimental v2.3 release
2. See all the new available libraries (Jaguar, C64, Dreamcast, etc.). Awesome!
3. Add a game to one of those libraries, the cover art works, etc. Sweet so far
4. Load the game

# Expected Behavior

The new system should prompt for a missing core to install so the game is playable

# Observed Behavior

I get this error:

> The operation couldn’t be completed. OpenEmu could not find a Core to launch the game.
> Make sure your internet connection is active and download a suitable core.

However, there is no option like there was in the past to download / install the core, just the error. The new systems are not listed in the cores section in preferences, either.

# Debugging Information

- OpenEmu Version: v2.3 release (6190.646-g1aa76ae3-Release)
- macOS Version: Catalina 10.15.7 (19H2)

**Comment by madhattermattic** [comment]
Just to clarify, I've tested the new Dreamcast, Pokémon Mini, MSX, and PS2 systems out, I haven't tried the other new ones yet because this seemed linked.

**Comment by clobber** [comment]
Alpha system plugins (these do not have any supported cores) were included by mistake in the "experimental" app bundle. This has been fixed and reuploaded here: https://github.com/OpenEmu/OpenEmu/releases/download/v2.3/OpenEmu_2.3-experimental.zip
