### ISSUE TITLE
.gme files to .oesavestate for OpenEmu PS

### ISSUE THREAD

**Issue by sheloves-e** [OpenEmu/OpenEmu#4373]
So I downloaded a save state from a website for FF7 for PS, which I play on OpenEmu currently. The file has the .gme extension, any way I can make it a .oesavstate to play on OpenEmu?

**Comment by clobber** [comment]
.gme is not a "save state", that is a memory card save. Mednafen memory card saves are in the .mcr format, so you will possibly need to convert this and then copy it over. Sorry, not going to walk you through this. You can infer from the following wiki guides on where your .mcr file would need to go, though:

https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files

https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Required-m3u-file-missing#transfer-your-save-data
