### ISSUE TITLE
Bugged fullscreen with OpenEmu 2.3 (since BigSure update)

### ISSUE THREAD

**Issue by neosandsoen** [OpenEmu/OpenEmu#4374]
today, OpenEmu asked me to update the app with some upgrades about BigSure (like the new app icon) but since, I can't use the fullscreen for my games and the windows is very small, which I can't enlarge.

<img width="1280" alt="Capture d’écran 2020-12-23 à 19 33 12" src="https://user-images.githubusercontent.com/64285933/103027248-c4ba1c00-4555-11eb-9bdb-cd391d74c289.png">
<img width="1280" alt="Capture d’écran 2020-12-23 à 19 33 05" src="https://user-images.githubusercontent.com/64285933/103027252-c5eb4900-4555-11eb-9e42-4a3716098573.png">

**Comment by clobber** [comment]
From the [release notes](http://openemu.org/rnotes/2.3.html) that you should have read:

> Added integer scaling options to the HUD bar for fullscreen popout window.

In full screen mode, click the HUD bar > Cog wheel > Scale > "Fill Screen"

If you don't like this behavior, simply disable it in Preferences > Gameplay > Window Management > Uncheck "Always snap popout gameplay window to integer scale"
