### ISSUE TITLE
Cannot completely "fill screen" in fullscreen mode when "Always snap popout gameplay window to integer scale" is enabled

### ISSUE THREAD

**Issue by inekipelov** [OpenEmu/OpenEmu#4375]
During the update check, I noticed that if the subj is enabled, the "Screen Scale" setting is not applied when a value is Full Screen
Please, see attached screenshots. Is this correct behavior or a bug?

✅ Work correct
<img width="33%" alt="correct_x_1" src="https://user-images.githubusercontent.com/3010244/103029976-8c213f00-4563-11eb-9a07-16aeaf8b4f50.png"> <img width="33%" alt="correct_x_2" src="https://user-images.githubusercontent.com/3010244/103029982-8e839900-4563-11eb-9e70-0f2776c54fde.png"> <img width="33%" alt="correct_x_3" src="https://user-images.githubusercontent.com/3010244/103029983-8f1c2f80-4563-11eb-839b-09802af985bf.png">

❌ Conflict
<img width="100%" alt="bad_full_screen" src="https://user-images.githubusercontent.com/3010244/103029985-904d5c80-4563-11eb-963f-6284d45f0006.png">

**Comment by stuartcarnie** [comment]
This is a bug. As a temporary workaround, disabling _Always snap popout gameplay window to integer scale_ will fix _Fill Screen_ option:

![image](https://user-images.githubusercontent.com/52852/103035153-ccf87280-45ba-11eb-84c5-ad196aa5212a.png)

**Comment by npartlow** [comment]
i unchecked "Always snap popout gameplay window to integer scale" but it is still not working

**Comment by stuartcarnie** [comment]
We're working on a fix for the issue and improvements.

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu/commit/909b1941ee2fb5bcc02fb1dd684c8db0342c0247

**Comment by clobber** [comment]
Fixed in OpenEmu 2.3.1, available now.
