### ISSUE TITLE
Shader preferences are not being saved

### ISSUE THREAD

**Issue by mzenz** [OpenEmu/OpenEmu#4378]
# Summary

Latest stable OpenEmu release does not remember shader settings, going back to defaults after restarting a game. Confirmed on both experimental and stable releases.

## Steps to reproduce

1. Install OpenEmu v2.3.
2. Start any game.
3. On floating bar's wheel ⚙️ icon, go to "Shaders" -> "CRT Geom" (any shader should do).
4. Modify shader setting(s).
5. Restart game.

## Expected Behavior

Restarting a game should remember previously set shader preferences.

## Observed Behavior

Shader settings go back to default after restarting game.

## Debugging Information

- OpenEmu Version: 2.3
- macOS Version: 11.1 (Big Sur)
- Hardware: MacBook Air (Retina, 13-inch, 2018)

**Comment by clobber** [comment]
Fixed in OpenEmu 2.3.1, available now.
