### ISSUE TITLE
Full screen and gamecube

### ISSUE THREAD

**Issue by Jimmy-Dean2099** [OpenEmu/OpenEmu#4379]
Summary of issue (IM ON MAC BOOK LATEST BY THE WAY)My main problem is some of the games I have downloaded previously that worked fine before the update no longer go fullscreen when I click the full screen toggle and my other problem is that game cube games I downloaded previously no longer work they just say gamecube error go back to user manual or something like that and they don't start up any more just straight to error. I love open emu and I hate this awesome software to be like this, thank you for your software.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step I start the rom and I click full screen and its surrounded by black and still in small screen format in the center. Other problem is I click on game cube rom and they all say error please refer back to the gamecube manual and nothing else.
1. How to cause the problem For problem 1. Just click full screen but only some work and some dont go full screen. For problem 2. Just open game cube game and get error
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe whatPROB 1. game go full screen PROB 2. game work
1. you want to
1. happen

# Observed Behavior

1. Describe what you see BLACK SCREEN SURROUNDING SMALL FORMAT AND GAME CUBE GAME NO START 
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: NEWEST UPDATE
- macOS Version: Mac OS Big Sur 11.1

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4374
#4375
