### ISSUE TITLE
arcade_library@2x.png

### ISSUE THREAD

**Issue by livid** [OpenEmu/OpenEmu#4380]
I noticed that currently, there is no 2x image for [arcade_library.png](https://raw.githubusercontent.com/OpenEmu/OpenEmu/master/OpenEmu/SystemPlugins/Arcade/Images.xcassets/arcade_library.imageset/arcade_library.png) ![](https://raw.githubusercontent.com/OpenEmu/OpenEmu/master/OpenEmu/SystemPlugins/Arcade/Images.xcassets/arcade_library.imageset/arcade_library.png). So below is my attempt to create it based on the current 1x design.

![arcade_library@2x](https://user-images.githubusercontent.com/11427/103047539-adbcff00-4540-11eb-8c42-3b91192d298b.png)

If there is an art style standard or any guide, I would love to follow it and make the icon better.

Thanks for this wonderful project.

**Comment by clobber** [comment]
Thanks for the interest. There is already a designer on the team that we prefer to update the graphics once it is time.
