### ISSUE TITLE
Shader settings will not load.

### ISSUE THREAD

**Issue by dvessel** [OpenEmu/OpenEmu#4381]
Summary of issue

# Steps to reproduce

1. Run a game.
1. Configure a shader.
2. Close game.
3. Re-open game.

# Expected Behavior

Shader should be reloaded from last session.

# Observed Behavior

Default shader setting are used. The settings were saved but they will not load. Running `defaults read org.openemu.OpenEmu` lists the changed shader configuration but it's ignored.

Tried running as a background thread and they load. As XPC (default) they don't.

# Debugging Information

- OpenEmu Version: v2.3 - 6190.646-g1aa76ae3-Release
- macOS Version: 11.1 (20C69)

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4378
