### ISSUE TITLE
OpenEMU freezes upon starting a new game

### ISSUE THREAD

**Issue by sy2002** [OpenEmu/OpenEmu#4383]
Summary of issue

Stella Core and GameBoy core freeze upon starting a new game.

I am a new user, so I just installed OpenEMU today. I tried to use some of the games that I normally tend to use with the stand alone version of Stella and with MAME/MESS.

Happy to provide more debug info, if you want/need it and tell me where to obtain.

# Steps to reproduce

1. I am running the newest OpenEmu 2.3 on macOS 10.14.6
2. Try to start either Pac-Man or Pitfall or Space Invaders in Stella
3. OR: Try to start Super Mario Bros' in GameBoy Mode
4. Open Emu will freeze and the "spinning wheel of death" will be shown.

<img width="886" alt="grafik" src="https://user-images.githubusercontent.com/6825267/103086553-32f9ef80-45e5-11eb-81d3-7d1567f23fdf.png">

# Expected Behavior

No spinning wheel of death.

# Observed Behavior

Spinning wheel of death - see "steps to reproduce"

# Debugging Information

- OpenEmu Version: 2.3
- macOS Version: 10.14.6

**Comment by J-rg** [comment]
Does this still occur after restarting your Mac?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4376
