### ISSUE TITLE
As of version 2.3, scaling and shader configs are reset when quitting a game

### ISSUE THREAD

**Issue by Acetown** [OpenEmu/OpenEmu#4384]
Since updating to version 2.3 I'm finding that OpenEmu is no longer able to remember my shader settings. To be more specific, it does remember what shader I had selected, but any changes I've made to that shader's configuration will be discarded upon quitting a game and reverted back to it's default setting. 
Same applies to scaling, it's reverted back to it's default setting (usually 3x) whenever I quit a game.
This behaviour seems to carry across all cores.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4378
