### ISSUE TITLE
Can't scale the game window past certain point.

### ISSUE THREAD

**Issue by victor-tafro** [OpenEmu/OpenEmu#4386]
<p>Had to revert to 2.2.1, since on SNES I can't change the game window size to fill as much of the screen as i would like, it seems to max out at a specific size which may be 100%, prior to this updated you weren't capped and it just upscaled.</p>

**Comment by clobber** [comment]
You should read the [release notes](https://openemu.org/rnotes/2.3.html).

> Added integer scaling options to the HUD bar for fullscreen popout window, by default keeping the last used integer scale. Note: HUD bar > cog wheel > Scale > "Fill Screen" to fill the whole screen.

> Added "Always snap popout gameplay window to integer scale" when dragging. Note: Hold "shift" before dragging to disable snap resizing.

> Added "Always use popout gameplay window" as default.

If you are referring to not being able to completely fill the screen in *full screen* mode, that is a bug and there is already an open issue for that.
