### ISSUE TITLE
7z support? What happened? How to enable?

### ISSUE THREAD

**Issue by Japandave** [OpenEmu/OpenEmu#4390]
I know OpenEmu used to support zipping and 7zing our roms. I 7z'ed up many of my bigger roms to save space, and I played many of them this way. Flash forward a few months of not playing OpenEmu, I loaded it and none of my zipped of 7z'ed roms could be loaded. What..why?

On an unrelated issue, a few weeks later I did a clean reinstall of Catalina. Reinstalled OpenEmu, the new version, and... still it won't load any zipped or 7z'ed files. Is there some setting I need to enable or has support for compression been dropped?

**Comment by clobber** [comment]
Nothing happened to 7zip support. I just imported a 7zipped ROM and it imports and plays just fine. There's nothing random about the way OpenEmu works. Without actual details about your problem, there is nothing I can do to help you.
