### ISSUE TITLE
only screen 1x on nintendo64 emulator

### ISSUE THREAD

**Issue by StephaneGrull** [OpenEmu/OpenEmu#4391]
when i play with nintendo64 emulator the game screen is too small.
Only 1x is available

on the gameboy emulator there are more options x1, x2, x3 etc.

Is there an option to enlarge the screen area?

![image](https://user-images.githubusercontent.com/23403816/103249076-d2184180-496d-11eb-882b-fd728dce0836.png)

**Comment by clobber** [comment]
Contributing guidelines - "Please search before opening a new issue."

#4375
