### ISSUE TITLE
So I installed a bunch of games into my library and now it doesn't work

### ISSUE THREAD

**Issue by lemmyw** [OpenEmu/OpenEmu#4392]
Before when I only had a couple of games in the library it was working fine. After I had put more games into my library it stops responding when I click on a game to play it. Is there a limit to how many games/MB of data can be in the library???
Update - I've tried deleting the games and having only one game in the library but the same thing happens, it just doesn't work anymore

OpenEmu Version - 2.3
MacOS - 10.15.6

**Comment by clobber** [comment]
Without actual details of your problem, we cannot help you. If you mean a game won't import, OpenEmu will tell you why. If you mean a game will not open, there is a bug and you should see the other thread.
