### ISSUE TITLE
How do I go really full screen

### ISSUE THREAD

**Issue by hyposlasher** [OpenEmu/OpenEmu#4395]
When I go to full screen mode in PS1 emulation it has both horizontal and vertical black bars, while it should have only vertical ones. The problem appeared after I updated openEmu to the latest version 2.3. How do I fix this?
<img width="1440" alt="Screenshot 2021-01-02 at 19 31 41" src="https://user-images.githubusercontent.com/13961762/103459421-1e2e0200-4d31-11eb-9107-88fade78d8f3.png">

**Comment by clobber** [comment]
Contributing guidelines - "Please search before opening a new issue."

#4375
