### ISSUE TITLE
The MAME core has quit unexpectedly (persistent issue)

### ISSUE THREAD

**Issue by Racuevas39** [OpenEmu/OpenEmu#4398]
Hi. I started suffering the following issue: The MAME core quits after I click any rom imported in OpenEmu. And I am unable to run any rom whatsoever. The weird situation is my curated romset (0.225, just a few and worth roms) was working as expected, no issues at all. All of a sudden, the MAME core started crashing with every single rom or rom/chd combination (all the way from donkey kong to Metal Slug and even Street Fighter 3). All crash reports look identical and refer to the following lines (the full crash report is linked at the end to this post):

Crashed Thread:        2  Dispatch queue: com.apple.NSXPCConnection.user.562
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
**Termination Reason:    DYLD, [0x4] Symbol missing**
Dyld Error Message:
**Symbol not found: _objc_opt_new**
Referenced from: /Users/USER/Library/Application Support/OpenEmu/*/mamearcade_headless.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

I couldn't find any reference here or on Reddit about the error. And only happens on MAME; nes, snes, gba, nds, and others work great.

Info: MacBook Pro (15-inch, 2017), macOS Mojave 10.14.6, 2.9 GHz Intel Core i7, 16GB Ram, Radeon Pro 560 4 GB
OpenEmu: 2.3 Experimental (for MAME support). Feedback is submitted as OpenEmu indicated to do so (persistent issue)
[Crash Report log via Gist](https://gist.github.com/Racuevas39/f037eab0c31a9eabc83174006c3f8bae)

Thanks in advance. Suffice to say OpenEmu is by far the best solution for emulation on Mac.

**Comment by clobber** [comment]
#4397
