### ISSUE TITLE
Red bars in fullscreen mode

### ISSUE THREAD

**Issue by hyposlasher** [OpenEmu/OpenEmu#4400]
![image](https://user-images.githubusercontent.com/13961762/103564877-1ad97880-4ee1-11eb-973c-772500bc383f.png)

# Debugging Information

- OpenEmu Version: 2.3.1
- macOS Version: 11.1

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4355
