### ISSUE TITLE
GBA on OpenEmu has worse colors than standalone mGBA

### ISSUE THREAD

**Issue by tycooko** [OpenEmu/OpenEmu#4401]
I have the latest version of OpenEmu with the latest version of macOS Big Sur on a 2020 27'' iMac.
Final Fantasy VI Advance (patched with color restoration) looks less saturated and contrasted on OE than it does on the standalone version of mGBA.
The following images are from the same computer and the same ROM. mGBA is above and OpenEmu below.

<img width="2156" alt="Screen Shot 2021-01-05 at 00 00 50" src="https://user-images.githubusercontent.com/75950926/103591573-d524ac00-4ef0-11eb-975d-8eb355607534.png">
<img width="2156" alt="Screen Shot 2021-01-05 at 00 02 45" src="https://user-images.githubusercontent.com/75950926/103591581-db1a8d00-4ef0-11eb-9408-7f4e54f2c833.png">

Another example:
<img width="2155" alt="Screen Shot 2021-01-05 at 01 06 37" src="https://user-images.githubusercontent.com/75950926/103592120-74966e80-4ef2-11eb-841d-4f7b877c28a8.png">
<img width="2153" alt="Screen Shot 2021-01-05 at 01 06 58" src="https://user-images.githubusercontent.com/75950926/103592127-79f3b900-4ef2-11eb-8e5b-7303ed1583c3.png">

**Comment by clobber** [comment]
"Worse" being a subjective term here. What you are seeing is a difference in colorspace profiles. OpenEmu uses SRGB which is correct, while most emulators "get it wrong" by just using a generic RGB. Handheld emulation is especially notorious for having oversaturated colors with the gamma jacked up, which is what you are seeing here.

https://byuu.net/video/color-emulation/

**Comment by tycooko** [comment]
It's literally the level of saturation and contrast that the company that made the original console for the game shows in their official website when showing the original version of said game: https://www.nintendo.es/Juegos/Super-Nintendo/FINAL-FANTASY-III-277292.html#Galer_a .
I'm sure OpenEmu is the only one to really get it and Nintendo and Square Enix are wrong, but could I now or are there future plans to allow me to set my custom settings for the look of the games in OpenEmu or are there or will there be shaders that do that for me?
Thank you.

**Comment by clobber** [comment]
> It's literally the level of saturation and contrast that the company that made the original console for the game shows in their official website when showing the original version of said game

It's literally not.

> I'm sure OpenEmu is the only one that really gets it and Nintendo and Square Enix are wrong

LOL that doesn't sound like a snide remark at all! I'm sure you are well-versed on the technical details and definitely read the link I provided. You are also probably aware of the great track record Nintendo and other companies have at emulating and preserving their own games -- that was sarcasm, in case you couldn't tell.

Find another outlet for your autismo.
