### ISSUE TITLE
Crash when pressing language input keys on Japanese Keyboard

### ISSUE THREAD

**Issue by Jaybourne1** [OpenEmu/OpenEmu#4402]
Summary of issue
When either of the language input keys on a Japanese keyboard are pressed, OpenEmu will crash. 

# Steps to reproduce

1. Boot OpenEmu 
2. Press either of the language input keys on a Japanese keyboard (either "英数" key or "かな" key)
3. Observe crash

# Expected Behavior

1. OpenEmu would not crash when these keys are pressed, and only the text input mode would change. 

# Observed Behavior

1. Whether the OpenEmu has primary focus or not, when either input key is pressed OpenEmu will immediately close and the crash report screen will be displayed. 

# Debugging Information

- OpenEmu Version: 2.3.1 (crash report is from the experimental build, but same crash also happens in the standard 2.3.1 release version, as well as 2.3.)
- macOS Version: Big Sur 11.1

[Crashlog.txt](https://github.com/OpenEmu/OpenEmu/files/5767842/Crashlog.txt)

**Comment by cyco** [comment]
I looked at the problem yesterday and fixed a related crash with c987a00b0ef9c7e0346d7770c35f5c9825ee799d. I believe that fix will also keep OpenEmu from crashing with the keys you mentioned. With 6491b50ce86ba48da5ea2a1f6e8aace56edf959b OpenEmu should also label these keys correctly.

**Comment by Jaybourne1** [comment]
I can confirm the issue is no longer present in v2.3.3 (neither standard or experimental builds), and indeed the key labels show up correctly when mapping. 
Many thanks!
