### ISSUE TITLE
MSX

### ISSUE THREAD

**Issue by LeWolfYT** [OpenEmu/OpenEmu#4411]
I am running OpenEmu Experimental on my Big Sur MacBook Pro.
(Note: It is an Intel MacBook, not an M1 MacBook, and I have fMSX installed.)
I saw that files with the .dsk extension were being marked as MSX games but
when I open them I get a message saying "The document “Mappy (1984) (Namcot) (J).dsk” could not be opened."
I am aware of an experimental core for blueMSX but i do not have it installed.
Does anybody know why this is?
Extra info:
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
1.4 GHz Quad-Core Intel Core i5
8 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 645 1536 MB
My hard drive has 91.02 GB available out of 251GB, 
and my SD card has 1.02 GB out of 1.03 GB available.

**Comment by clobber** [comment]
Without going into too much detail, file types of alpha status system plugins are no longer associated with OpenEmu as of 2.3.3. You can safely ignore what you are seeing.
