### ISSUE TITLE
OpenEmu Clobber using "autism" as an insult and damaging OE's public image

### ISSUE THREAD

**Issue by Matfael** [OpenEmu/OpenEmu#4418]
https://github.com/OpenEmu/OpenEmu/issues/4401#issuecomment-754385164 : "read the link I provided"
I did.
This is the image that that article describes as "a technicolor nightmare" (https://byuu.net/video/color-emulation/):
![5](https://user-images.githubusercontent.com/75950926/103672704-f0d59400-4f7c-11eb-87e7-57d480d73474.png)
This is OpenEmu (the game is Golden Sun):
<img width="1882" alt="Screen Shot 2021-01-05 at 17 40 24" src="https://user-images.githubusercontent.com/75950926/103672883-35f9c600-4f7d-11eb-88c3-72a7cea96d07.png">
I rest my case.

Also: if Clobber is not 5 - and a crappy child of 5 I'd add - using "autism" as an insult really gives you the idea of the human quality of this person.

**Comment by clobber** [comment]
@Matfael LOL the fact that you keep creating new accounts just to post this shows the level of mindless obsession I was talking about. What's more is you don't even understand the information in the link provided: it's up to the emulator developer to correct the palette for sRGB. OpenEmu just uses a color-managed Metal surface. You probably thought this was a "big own" but instead you're the one making yourself look bad. I'd happily lose idiot users like you, so find something else.

https://developer.apple.com/library/archive/technotes/tn2313/_index.html
