### ISSUE TITLE
Bug: The file could not be imported (although it is still imported correctly)

### ISSUE THREAD

**Issue by Gioser90** [OpenEmu/OpenEmu#4419]
I wanted to point out that if I load the games (both **.bin+.cue** and **.img+.cue**) for **Playstation One**:

Up to version 2.2.1, they were loaded correctly without any anomalies.
Since version 2.3 (including 2.3.2) a notification overlay is shown that tells me the following:

> **_The file could not be imported.
> No valid system found._**

https://user-images.githubusercontent.com/16078125/104093584-a8271f00-528b-11eb-8145-5cc2e29fabf3.mov

The game still loads correctly and works flawlessly, so my report is only about the anomaly showing an incorrect notification popup which should absolutely not show.

I tried with a dozen games (for PS1), all the exact same problem (with 2.1.1 no problem, with version 2.3 and later the same apparent error).

# Debugging Information

- OpenEmu Version: 2.3.2
- macOS Version: macOS Big Sur 11.2

**Comment by clobber** [comment]
I can probably think of a way to replicate this, but would need to see what files you are actually working with in that folder. It is important to note that you are not supposed to drag the entire folder to import, only the cuesheet file. This is explained in the following guides:

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing
