### ISSUE TITLE
Audio issue

### ISSUE THREAD

**Issue by newdeal-999** [OpenEmu/OpenEmu#4420]
I am not sure exactly what the problem is, but when I go into a game (tried Tetris and Contra for NES) while listening on my Bose QC35 headphones over bluetooth it seems to activate the microphone (not sure if its the internal mic or the headphone mic) which really messes up the audio coming out of the headphones (especially if I am doing something else with audio on in the background also)

**Comment by clobber** [comment]
@newdeal-999 you're not exempt from filling out the [Issue Template](https://github.com/OpenEmu/OpenEmu/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
