### ISSUE TITLE
How to disable cores automatic upgrading?

### ISSUE THREAD

**Issue by qubing** [OpenEmu/OpenEmu#4423]
I am using OpenEmu with older version's MAME cores and it was working well. But because MAME just released new version of 0.227.0.1, all my relevant games can not startup now. Who knows where can I get correct version of neogeo.zip? Is is possible to disable the cores upgrading? Thanks.

**Comment by clobber** [comment]
> Who knows where can I get correct version of neogeo.zip?

Do not ask for that there. Use a search engine to find ROM sets for MAME.

>  Is is possible to disable the cores upgrading?

Sorry, no. We won't be supporting a feature like that. Use [MAME standalone](https://sdlmame.lngn.net/) and never update it, instead of OpenEmu, if you do not want to deal with updating your MAME ROM sets.
