### ISSUE TITLE
Advance Wars Dual Strike - Missing Cursor Issue (Fixed in full release for Desmume but not for OpenEmu core)

### ISSUE THREAD

**Issue by HiroiSekai** [OpenEmu/OpenEmu#4424]
Hi, just wanted to shoot an update for this because all issues regarding it seem to be closed. DeSmuMe has a Mac-specific stable release link for 0.9.12 on their Downloads page of their website here: http://desmume.org/download/ (If you download the app and click "About", the release version says 0.9.12)

I just downloaded the standalone app to my Mac and tested Advance Wars Dual Strike, and the cursor issue is resolved. Can this be implemented into a core update for OpenEmu? Thank you!

**Comment by clobber** [comment]
That is a snapshot build. That is not the final 0.9.12 release and we will not update our Desmume core port until then 0.9.12 is officially released.
