### ISSUE TITLE
include scraper for additional rom metadata?

### ISSUE THREAD

**Issue by adam226** [OpenEmu/OpenEmu#4428]
Any future plans to perhaps include additional metadata fields for roms besides cover art? I'm thinking of something similar to what EmulationStation does with it's metadata scraper and includes game information like the developer/publisher, date of release, genre, number of players, and a description of the game. I think they tie into TheGamesDB API to grab it.

Then maybe you could include some sort of "get info" panel on the right that expands out, or something similar, to give some more information about a game. Seems like it would be a nice add to the platform.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Falls under #664 and #811
