### ISSUE TITLE
Improvement suggestion - download from icloud on-demand

### ISSUE THREAD

**Issue by sibob** [OpenEmu/OpenEmu#4429]
I'm running openemu on a 256gb Macbook, with roms stored in an icloud folder. For space reasons, Macos frequently deletes the local copies of large games e.g. PS1 and Gamecube. So before playing a game, I go into finder and download the game. This way works, but I wonder if it might be possible to implement downloading via Openemu as and when it's required? 

Hope I'm not the only one wanting this, it'd be a really seamless way of handling large libraries on small drives.

**Comment by clobber** [comment]
Sorry, no. Quality space is inexpensive.

https://www.amazon.com/s?k=samsung+t5+ssd&ref=nb_sb_noss_1

https://www.amazon.com/SAMSUNG-Portable-SSD-1TB-MU-PC1T0H/dp/B0874YJP92
