### ISSUE TITLE
The Gambatte core has quit unexpectedly after loading a save state

### ISSUE THREAD

**Issue by blakeallard** [OpenEmu/OpenEmu#4431]
macOS Mojave 10.14.6
Pokemon Crystal Kaizo

**Comment by clobber** [comment]
I'm not surprised a Pokemon ROM hack is crashing the emulator. Sorry, nothing we can do about that. It's either a bug with the hack (it doesn't run on real hardware) or Gambatte has a bug. Either way, it's not an OpenEmu problem.
