### ISSUE TITLE
multi-key setting support?

### ISSUE THREAD

**Issue by tick5** [OpenEmu/OpenEmu#4432]
I use openemu to play arcade games. There are so many games need  to press multi-key. For example press A+B to escape from a dangerous situation, press A+B+C to collect energy.

But it's hard to press 2 or 3 keys at the same time precisely, misoperation happens all the time. So it's nice to set multi-key to a single key.

I didn't find this kind of setting in openemu, will this kind of function be supported some day?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#1671
