### ISSUE TITLE
Mario and Luigi Bowser Inside Story Glitch

### ISSUE THREAD

**Issue by ImTakenCunt** [OpenEmu/OpenEmu#4433]
when I start playing the game its fine nothing wrong but until I got to the first boss the game freezes I tried to change stuff in the settings and still nothing worked even with hacks I can skip the first boss but when I go to the second boss my game freezes I don't why it happens someone please help me.

can you please fix this glitch it works good on windows but not on mac why?

- OpenEmu Version: latest 
- macOS Version: macos catalina

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues?q=%22inside+story%22
