### ISSUE TITLE
cinematic bug

### ISSUE THREAD

**Issue by pablinho16** [OpenEmu/OpenEmu#4434]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1.  When I see a cinematic in the NDS emulator instead of going on with the game it crashes and the screen is totally black. (the game is inazuma eleven 3)

# Debugging Information

- OpenEmu Version:2.3.1
- macOS Version: Big Sur 11.1

**Comment by clobber** [comment]
Sorry, we are not responsible for bugs with Desmume.
