### ISSUE TITLE
No... input will not work without access.

### ISSUE THREAD

**Issue by theolen** [OpenEmu/OpenEmu#4436]
No... input will not work without access.

_Originally posted by @clobber in https://github.com/OpenEmu/OpenEmu/issues/4435#issuecomment-761600329_

Input monitoring permission is not needed to receive inputs from a controller (I have tested using a PS4 controller connected via bluetooth). Would you mind responding to my question again, in light of this new information?

**Comment by clobber** [comment]
It’s not happening. Stop asking.
