### ISSUE TITLE
HELP ME PLEASE! OpenEmu won't open

### ISSUE THREAD

**Issue by ozornaya** [OpenEmu/OpenEmu#4441]
MacBook Air with macOS Mojave 10.14.6 doesn't open OpenEmu 2.3.1 with this error (i'll leave a whole message, if it helps)

Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

[ошипка.docx](https://github.com/OpenEmu/OpenEmu/files/5860289/default.docx)

I've already tried reinstalling different versions of OpenEmu, but error is the samу every time.

If i'm trying to open it in Safe Mode, i can see next message:

![Снимок экрана 2021-01-23 в 16 30 49](https://user-images.githubusercontent.com/74509769/105580143-b309a580-5d9b-11eb-8ed0-0ff7555d937e.png)

BUT! The most amazing is that i've created a new user and there are no problems:

![Снимок экрана 2021-01-23 в 16 32 48](https://user-images.githubusercontent.com/74509769/105580174-d6345500-5d9b-11eb-8eb1-d583e6ebbf62.png)

How do I open OpenEmu in my profile(as admin)? :(

**Comment by clobber** [comment]
> If i'm trying to open it in Safe Mode, i can see next message:

You cannot run OpenEmu in safe mode.
