### ISSUE TITLE
Change the emulator Language

### ISSUE THREAD

**Issue by MoutonBinoclard** [OpenEmu/OpenEmu#4443]
Hello !
So that's my question :
Can I change the emulator language like put Desmume in French for play the game in French (Bcs the games know the console language) or is that impossible ? 

PS: I know w/ the desmume emulator we can change the language so I write this question here and not in there support

**Comment by clobber** [comment]
No way to do this through the UI at the moment.

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #1083
