### ISSUE TITLE
Automatically reloads last save on alt-tab

### ISSUE THREAD

**Issue by Gary-biocoiff** [OpenEmu/OpenEmu#4444]
Hello ! I noticed that each time I do alt-tab, the app automatically launches the latest save.
I attached a video here : https://www.loom.com/share/b449b88bf2bd49b1a550f99cfe70ecca

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

https://www.loom.com/share/b449b88bf2bd49b1a550f99cfe70ecca

# Expected Behavior

I think it shouldn't reload the last save. It didn't do that at first, it started doing it 10 days ago.

# Observed Behavior

Reloads the last save.

# Debugging Information

- OpenEmu Version: 2.0.9.1
- macOS Version: 10.13.6

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
