### ISSUE TITLE
Cursor does not appear in Advance Wars Dual Strike with DeSmuME core

### ISSUE THREAD

**Issue by maxrothman** [OpenEmu/OpenEmu#4445]
This is a known issue in DeSmuME, and [there's a workaround](https://sourceforge.net/p/desmume/bugs/1494/) that involves changing the 3D rendering engine settings. However, these settings cannot be altered in OpenEmu. The lack of ability to configure cores has also been [brought up before](https://github.com/OpenEmu/OpenEmu/issues/1281), but that issue is locked to collaborators so I'm unable to comment there.

Debugging Information

- OpenEmu Version: v2.3.3
- macOS Version: 10.15.7

**Comment by clobber** [comment]
And you will get the same response I've given others: we are aware of the need for core configuration settings, as you can clearly see, and we do not need duplicate issues (pestering, +1's, me too's, etc) open for them. Use Desmume standalone for the game that troubles you.

Duplicate of #1281
