### ISSUE TITLE
No GameCube quicksave

### ISSUE THREAD

**Issue by sims4so** [OpenEmu/OpenEmu#4446]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

no quicksave on gamecube

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: v2.3.3
- macOS Version: macOS Calintina 10.15.7 (19H114)

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4119
