### ISSUE TITLE
Sega Saturn Problem

### ISSUE THREAD

**Issue by tealyt** [OpenEmu/OpenEmu#4448]
I tried to run a Sega Saturn game and it lagged **_hard_**
- OpenEmu Version: Newest
- macOS Version: 10.15.6

**Comment by clobber** [comment]
Your Mac is too slow to run Mednafen’s Sega Saturn emulation at full speed. Nothing you can do besides getting a new machine.

**Comment by tealyt** [comment]
It ran fine before I updated it
