### ISSUE TITLE
OpenEmu stopped recognizing input and cannot be reset

### ISSUE THREAD

**Issue by eaglestrike98** [OpenEmu/OpenEmu#4450]
# Summary of issue:
OpenEmu was working normally for weeks. I left my computer running with OpenEmu on in the background, and then my computer went to sleep. Returned to my computer, put OpenEmu in the foreground, and inputs were not registering.

I first confirmed that my keyboard was working (it was). 

Then, I hard-closed the application and re-opened it and launched a game. Inputs were not recognized. 

Re-started the application and tried a different game. Inputs were still not recognized.

Closed the application, and toggled the input-settings in Privacy (turning it off, closing the app and restarting, turning it on, restarting again after being prompted to). Inputs were still not recognized.

Deleted OpenEmu from my computer and redownloaded it. Opened the application and started a game. Inputs still not recognized.

Again, OpenEmu was working normally without issue for weeks, and this issue suddenly occurred and can't be fixed, would welcome help.

# Expected Behavior

1. Keyboard inputs to be recognized

# Observed Behavior

1. Keyboard inputs not being recognized, despite undertaking numerous restarts, toggles, and redownload activities.

# Debugging Information
- OpenEmu Version: 2.3.3
- macOS Version: 11.1

**Comment by clobber** [comment]
If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here for possible problems: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
