### ISSUE TITLE
 Please give help!  openemu "could not download required data from the internet"

### ISSUE THREAD

**Issue by zhangyc310** [OpenEmu/OpenEmu#4452]
When I  start to run openEmu first time , It begin to downlaod data, and then show me the message "OpenEmu could not download required data from the internet".

My macos BigSur ,intel x86, OpenEmu v2.3.3 Experimental.
My internet is OK
![image](https://user-images.githubusercontent.com/8527838/106372451-b8be4700-63aa-11eb-9eea-ed581a112f68.png)

 How to solve it ? Please give some help! 
Thank u!

**Comment by watermelo** [comment]
me too...

**Comment by clobber** [comment]
Your machine or ISP is blocking outgoing connectings to GitHub -- probably some sort of firewall software you have running.

**Comment by EricRaw** [comment]
me too...

**Comment by EricRaw** [comment]
my Chinese friends , need to use Shadowsocks 梯子, to fix this issue

**Comment by Mohammed6155** [comment]
Hello and welcome! Got this error too!

My Internet is not working, I turned off "Setup Assistant has finished" and I quit OpenEmu. Then I got this error and if I press "Retry", it displays the error again!

**Comment by yuezijian** [comment]
This problem still existing, no firewall running and github accessing is fine.

**Comment by Shimmer2** [comment]
在中国用梯子也无法连接网络

**Comment by zhanghongzheng6** [comment]
在中国,用手机的联通4g网络可以可以

**Comment by sipdar** [comment]
I edit  my host file , mapping raw.githubusercontent.com to  185.199.110.133, it worked

**Comment by wxf0322** [comment]
> 在中国,用手机的联通4g网络可以

正解，连接手机热点就可以解决。

**Comment by saurabhbadhe123** [comment]
same issue
