### ISSUE TITLE
Not recognizing keyboard input MacOS Big Sur

### ISSUE THREAD

**Issue by jonlorusso** [OpenEmu/OpenEmu#4453]
- OpenEmu Version: 2.3.3
- macOS Version: Big Sur 11.1

Keyboard input not recognized.  Input Monitoring is enabled.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

See: https://github.com/OpenEmu/OpenEmu/issues/4450#issuecomment-769508394
