### ISSUE TITLE
I cannot get OpenEmu to work on Mac OS Big Sur Version 11.2.

### ISSUE THREAD

**Issue by Draco220** [OpenEmu/OpenEmu#4455]
Due to a wireless Internet problem, I had to update to Mac OS Big Sur, the newest version, 11.2.  I had to restore from a backup.  When it was done, I found that a number of my applications including OpenEmu did no work.

"The last time you opened OpenEmu, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?

If you choose not to reopen windows, you may have to open and position the windows yourself."

There are two choices: "Don't Reopen" and "Reopen."  Both choices result in the message "OpenEmu quit unexpectedly."

The version is 2.3.3.

**Comment by Draco220** [comment]
It also doesn't work with Big Sur Version 11.2.1.

**Comment by clobber** [comment]
Cannot do anything without a crash log. Try [redownloading](http://openemu.org/) the app.

**Comment by Draco220** [comment]
Clobber,

I've included additional information.  This is for the experimental version.

Thank you.

Thomas

**Comment by Draco220** [comment]
<img width="372" alt="Screen Shot 2021-02-13 at 1 46 37 AM" src="https://user-images.githubusercontent.com/78740130/108069021-bbaa7000-7017-11eb-83f7-b8693f0e9d7c.png">
<img width="1112" alt="Screen Shot 2021-02-13 at 1 56 39 AM" src="https://user-images.githubusercontent.com/78740130/108069047-c2d17e00-7017-11eb-8fd8-c6bac851fc9c.png">
The crash report is only partly visible.  To see more, I have a complete Microsoft Word document with all of the text.

**Comment by EhsanWaheed** [comment]
Works on big sur 11.2.1 just ran god of war using the psp core.

**Comment by clobber** [comment]
@Draco220 Read here: https://github.com/OpenEmu/OpenEmu/issues/4208#issuecomment-626454569
