### ISSUE TITLE
OpenEmu won't download cover arts

### ISSUE THREAD

**Issue by bengalamx** [OpenEmu/OpenEmu#4456]
Even the most popular games are just in pink noise

<img width="1464" alt="Captura de Pantalla 2021-02-09 a la(s) 9 30 17" src="https://user-images.githubusercontent.com/3253845/107386391-6de2b480-6ab9-11eb-972f-d9bbf02055ab.png">

**Comment by clobber** [comment]
Regarding N64: https://github.com/OpenEmu/OpenEmu/issues/3429#issuecomment-351484486

Regarding SNES: https://github.com/OpenEmu/OpenEmu/issues/3752#issuecomment-423721441
