### ISSUE TITLE
OpenEmu Controls Malfunction

### ISSUE THREAD

**Issue by zeroxena1** [OpenEmu/OpenEmu#4457]
I'm currently on the newest MacBook with Big Sur installed and I downloaded OE along with a Pokemon Platinum rom. Everything visually & audibly loaded just fine but when I use a key to move past the title screen nothing happens... I checked my settings and made sure that the controls are set to what I need them as but still nothing happens no matter what key I press. I also can't change the controls to something different either. It's as if OE isn't registering my built in keyboard...

**Comment by Gigasnow** [comment]
MBP 16 2019 with Big Sur 11.2.1 also failed to change the control keys.

**Comment by clobber** [comment]
If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here for possible problems: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
