### ISSUE TITLE
Paperboy MAME

### ISSUE THREAD

**Issue by ScrewThePVZ2Hackerz** [OpenEmu/OpenEmu#4460]
Unsure if this question exists already but let's give it a shot.
So I'm trying to play the arcade port of Paperboy but every ROM I gather, no matter where, results in this error message...

_Paperboy (rev 3) (paperboy.zip) requires:

paperboy.zip  	- INCORRECT SET

These ROMs must be from a MAME 0.227 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files._

I get the general gist but there doesn't seem to be any place to find a ROM that specifically states MAME 0.227. If there's a place I can get it for Paperboy, would you be kind enough to link it?

**Comment by clobber** [comment]
Sorry, no, check Archive.org for a more recent MAME ROM set.
