### ISSUE TITLE
HD Texture Packs

### ISSUE THREAD

**Issue by johngb2** [OpenEmu/OpenEmu#4465]
I am new here and have spent about 4 hours tonight trying to follow old posts about loading HD texture packs in OpenEmu. In particular I am working on Paper Mario. Here's what I have done (all from this old post https://github.com/OpenEmu/OpenEmu/issues/1394):

- Added the folders "cache" "hires_texture" and "texture_dump" to /Users/jay/.local/share/mupen64plus/
- Tried adding the .htc texture pack into the "hires_texture" folder and the "texture_dump" folder
- Added the [Video-Rice]... section to the mupen64plus.cfg file in Users/jay/Library/Application Support/OpenEmu/Mupen64Plus

Not sure if I need to do some renaming, add more to the .cfg file, or what. Thanks for your help!!!

**Comment by clobber** [comment]
Sorry, those guides are irrelevant to the latest Mupen64Plus core plugin that now uses GLideN64. Rice is long gone. Texture packs not supported. Nothing you can do.

**Comment by johngb2** [comment]
Ah, well that makes sense then. Is there a plan to add support for texture packs to OpenEmu? Having trouble finding an a Mac emulator that does. Thanks again!
