### ISSUE TITLE
A way to fix the Bronzor problem

### ISSUE THREAD

**Issue by NoobMaster-15** [OpenEmu/OpenEmu#4467]
So I enter the same cheat codes in my nds emulator and save when I caught a bronzor. So then it keep appearing in the wild now. You have to quit the rom and then delete. After deleting it, download again and it should work. (Also, don't disable the bronzor cheat, but delete it insted)

**Comment by brightredspacejoystick** [comment]
pokémon ds cheats are not supported. it's a known desmume issue.
