### ISSUE TITLE
How should I transfer my save states and game Library?

### ISSUE THREAD

**Issue by DevilSAM** [OpenEmu/OpenEmu#4469]
I had OpenEmu 2.0.6
And now I got a new macBook with Big Sur 11.2.2 and OpenEmu 2.0.6 crashes immediately after starting.
So I'd install OpenEmu 2.3.3
I transfer my ~/Library/Application Support/Open Emu/Game Library and .../SaveStates from old macBook to the new one.
Now, when I try load save state of any NES game (for example GUN-DEC) it says "can't load /Users/username/Library/Application Support/OpenEmu/Save States/N64/GUN-DEC.Quick Save State.oesavestates/State"

Genesis save states also does not loads (there is no file "State")

Arcade games save states also does not loads (troubles with headers (I think this is problem in  info.plist from .oesavestate))

**Now the questions: 
1. why it tries load NES-game save states from N64 folder?
2. is there a way to fix loading save states from nes, genesis, arcade?
3. may be there is a way to correct transfer save states from old version of OpenEmu to the new?**

**Comment by brightredspacejoystick** [comment]
so, the n64 core (mupen64plus) is still in development, and breaks save states even between internal updates on the same machine. there's a warning dialog (i'm guessing) most people dismiss warning about this: don't use save states (or, at least, don't trust them and be sure to sandwich them with battery saves).

i'm not 100% on this, but the fact you're going from 2.0.6 to 2.3.3, i'm 99% sure that the mupen64plus shipping core updated between those releases (a couple years apart)?

your best bet is to battery saves between transfers.

arcade is not supported.

nes and genesis should be fine.

**Comment by DevilSAM** [comment]
So that's who I made my save states work correctly:

1. Download new latest version OpenEmu.
2. Load one NES game to the game library (into openemu).
3. Run this game and made quick save.
4. At this point openemu makes ~/Library/Application Support/OpenEmu/Save States/NES/GAME_NAME folder with save states.
5. Copyall folders from ~/Library/Application Support/OpenEmu/Save States/NES from my first MacBook to the same folder on my new MacBook.
6. Now save states (quick saves and auto saves) works fine
7. Some of them has local language and some has english (Quick Save State VS Бастрое Сохранение). If so then I just rename it. 
8. No problem with NES now.

Other consoles not tested yet

**Comment by brightredspacejoystick** [comment]
perfect. yeah, for nes and genesis, you should be fine. mame will most likely get mixed results (but you might be pleasantly surprised). n64 you're going to have to do battery saves—but you've got the idea.

**Comment by DevilSAM** [comment]
About MAME... Early it required games from 0.149 and now games should be 0.227.
So 0.149 roms was easy to find [HERE](https://ia600703.us.archive.org/zipview.php?zip=/30/items/MAME_0.149_ROMs/MAME_0.149_ROMs.zip) for example. But I can't find 0.227 rooms anywhere :-/
Most of my games now doesn't work.

Any idea how can I fix it?
