### ISSUE TITLE
xbox controller not detected as controller

### ISSUE THREAD

**Issue by ramb6** [OpenEmu/OpenEmu#4470]
on 11.2.2 mac os

openemu 2.3.3

essentially the xbox controller is paired via bluetooth. shows paired and seems to have no issues. not detected in openemu however, if trying to map over keyboard, blank entries registered from the controller but doesn't solve anything

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
