### ISSUE TITLE
No audio with bluetooth     HELP!!!

### ISSUE THREAD

**Issue by Killercombo3** [OpenEmu/OpenEmu#4472]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

I'm on the most recent normal version of OpenEmu and whenever I use my Bluetooth headphones for audio, nothing comes out. The headphones aren't broken because it works on different things on and off the computer. OpenEmu is broken somehow and I have no clue how to fix it. I already redownloaded OpenEmu once. HELP!!!

**Comment by clobber** [comment]
> OpenEmu is broken somehow and I have no clue how to fix it

No it's not. There are macOS bugs with Bluetooth audio. The solution is to not use Bluetooth audio.

https://supermegaultragroovy.com/2021/01/26/it-s-over-avaudioengine/

https://supermegaultragroovy.com/2021/01/28/more-on-avaudioengine-airpods/
