### ISSUE TITLE
Micro Joistick not working

### ISSUE THREAD

**Issue by snslpa** [OpenEmu/OpenEmu#4474]
Hello, the app does not detect correctly the new generation micro joystick / micro gamepads.

MINI PLUS (3,5 $ micro gamepad, ideal for laptops and traveling)

http://www.aliexpress.com/item/4000693399973.html 

When I pair it through Bluetooth it is linked but not detected as a remote controller in OpenEmu preferences, when I try to set it up, it detects the movements but doest not work later. 

It would be great to have this micro joystick working with OpenEmu.

Thanks.

**Comment by clobber** [comment]
Sorry, without owning the device there is no way we can troubleshoot it and nobody is going to buy this. Use a [well-supported gamepad](https://github.com/OpenEmu/OpenEmu/wiki#automap-supported-controllers) instead. Also read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems).
