### ISSUE TITLE
will openemu’s metal dolphin core be supporting the nkit format?

### ISSUE THREAD

**Issue by brightredspacejoystick** [OpenEmu/OpenEmu#4475]

**Comment by clobber** [comment]
It does not use Metal. No, it will not be supporting "NKit"

**Comment by MaddTheSane** [comment]
Looks like nkit is a format used by Dolphin for compressing isos even more than what was used previously.
Adding support to nkit would be trivial.
And using nkit shouldn't be limited to the rendering front-ends.
