### ISSUE TITLE
Hot shots golf open tee 2 (Everybody's Golf 2) Heavy slowdown during swing 

### ISSUE THREAD

**Issue by Dann27** [OpenEmu/OpenEmu#4476]
# Steps to reproduce
Heavy slowdown during swing. The game works perfectly all the time except while you're charging the swing meter. FPS drop, making the game unplayable.
(I've tried every Hot Shots Golf title, same issue in every version.)

# Debugging Information

- OpenEmu Version: v2.3.3
- macOS Version: Big Sur v11.2.1

**Comment by clobber** [comment]
This is a PPSSPP emulator bug. Nothing we can do about it until they resolve it.
