### ISSUE TITLE
Pressing (-) button three times starts screen recording

### ISSUE THREAD

**Issue by therealppa** [OpenEmu/OpenEmu#4478]
Hi, maybe someone has an idea what's going on here. I have a Switch Pro controller connected via Bluetooth. I'm on macos version 11.2.3. When I quickly press the minus button (mapped to select) three times I get a pop up on wether I want to allow screen recording. This is quite annoying, but I have no idea how to get rid of it. When OpenEmu is not running, this dialog does not appear.

**Comment by MaddTheSane** [comment]
That seems to be a feature in Big Sur: if you're playing a game and press that button multiple times, it'll begin a recording. I have always denied it so I don't know what it exactly does.

**Comment by dvessel** [comment]
It'd be nice if there was a way to configure the behavior or disable it completely. It currently records at a low resolution in 23fps. Not very useful but it does confine the capture to a single app. There's no other way to record like this. It's either full screen or selection box.

**Comment by julienbfabre** [comment]
This also happens pressing twice the share button on the PS4 controller, very annoying indeed, anybody knows how to disable this?

**Comment by clobber** [comment]
Google search. This is not an OpenEmu issue.

https://apple.stackexchange.com/questions/415087/disable-screen-recording-prompt-from-bluetooth-game-controller-maybe-big-sur-on
