### ISSUE TITLE
Two Wiimote controllers - second controller wont function on some games (NHL 94/94, Madden)

### ISSUE THREAD

**Issue by nickraio** [OpenEmu/OpenEmu#4479]
Summary of issue: tried connecting two Wiimotes both through Bluetooth preferences in MacOS as well as through OpenEMU directly in controller settings in separate trials. Renamed one of the controllers to Nintendo RVL-CNT-02 to avoid duplicate names in Bluetooth settings. OpenEMU only recognizes both as Nintendo RVL-CNT-01. 

Both controllers are recognized when programming controller buttons. Both controllers work with games such as Golden Axe or Double Dragon (2 players function) and Tecmo Super Bowl, but in NHL 94, NHL 95 and Madden 95, can't get second player to work with controllers. 

I have tried deleting and reinstalling ROMs. I have tried uninstalling controllers and reinstalling through Bluetooth preferences and through OpenEMU. Have tried going into library/application support/OpenEMU/Bindings and deleting Default.oebindings and then reopening OpenEMU. 

Both players will work (able to slide controllers left and right in the in game selection menu) in NHL 94 on Super Nintendo Emulator core. Cannot get 2 players to work on these games in Sega Genesis Core. 

Could it be something with the ROMS? Curiously it will recognize buttons and dpad when trying to enter in controller setting for both controllers but then won't operate player 2. I can use either remote to make player 1 function.

Thanks

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

- OpenEmu Version: v2.3.3 experimental
- macOS Version: Catalina 10.15.7

**Comment by nickraio** [comment]
Also tried two 8bitdo controllers - same issue. Two-player won't work in NHL 94, 95, madden, in Genesis Plus core. Other titles work two-player. such as Double Dragon. NHL 94 SNES version works 2 players with wiimote or 8bitDo controller. MAME works 2 player. The issue seems only to be with certain titles in Genesis Core

**Comment by clobber** [comment]
Specific game issues would go here: https://github.com/OpenEmu/GenesisPlus-Core
