### ISSUE TITLE
Keyboard not responding on Big Sur 11.2.3

### ISSUE THREAD

**Issue by mbcz123** [OpenEmu/OpenEmu#4480]
# Expected Behavior

keyboard not responding

# Observed Behavior

keyboard not responding;
input monitoring ticked;
read all the https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
and have none of those mentioned;
I can press ESC in the controller interface to delete a pre-mapped key though, just can't input any new keys;

# Debugging Information

- OpenEmu Version: v2.3.3
- macOS Version: Big Sur 11.2.3

**Comment by clobber** [comment]
If you get the input permission dialog as you open the app, you must toggle the setting until it works. Also try restarting your machine to see if that has any effect. It sounds like you have some other application causing interference with OpenEmu receiving inputs.
