### ISSUE TITLE
How can we turn the analoug in psp contoller?

### ISSUE THREAD

**Issue by TheHandyUser** [OpenEmu/OpenEmu#4481]
Im playing god of war ghost of sparta and in it, it asks to rotate the analogue. I have mapped mine to the arrows key but pressing the arrow keys in the order it asks doesnt seem to work? 

![Screen Shot 1943-01-03 at 1 02 23 PM](https://user-images.githubusercontent.com/62173713/112271702-43337080-8ca1-11eb-866b-79c174046a62.png)

**Comment by clobber** [comment]
> I have mapped mine to the arrows key

You need to buy a [supported gamepad](https://github.com/OpenEmu/OpenEmu/wiki#automap-supported-controllers) with analog controls.
