### ISSUE TITLE
Mouse device is supported?

### ISSUE THREAD

**Issue by MiczyJack** [OpenEmu/OpenEmu#4482]
Some PSX games such as Arkanoid Returns, Shanghai - Matekibuyu, Clock Tower are supporting mouse device as a controller.  However the games cannot be played using attached mouse on OpenEmu, but only pad.  Not supported yet?

**Comment by clobber** [comment]
> Not supported yet?

Correct. https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Light-gun-and-Mouse

**Comment by MiczyJack** [comment]
Thanks!  Only SNES at this time.
