### ISSUE TITLE
Gameboy Advance Save Games Disappearing

### ISSUE THREAD

**Issue by BadgerGhostMan** [OpenEmu/OpenEmu#4483]
I'm having a strange issue with gameboy advance game save files. If I have not played a game for a while, the game files are deleted. If I resume play on the games when opening them, they simply boot up at the empty file select screen. This only happens on gameboy advance, and it only happens to games which I have not played for 4+ months. It has happened to several different games from several different sources, so it doesn't appear to be a problem with any individual roms.

**Comment by clobber** [comment]
You were using an old install with a GBA core plugin that is no longer supported.

#3436
