### ISSUE TITLE
How can I turn off automatic update

### ISSUE THREAD

**Issue by appoleo** [OpenEmu/OpenEmu#4484]
Mame core will be automatically updated after openemu is started. How can I turn off automatic update? I had search the relevant content, but nothing be find, and I didn't find the relevant settings in openemu, please help me

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4423
