### ISSUE TITLE
OpenEmu not opening on MacOS 11.3 beta 6

### ISSUE THREAD

**Issue by Flemming7** [OpenEmu/OpenEmu#4487]
1. Describe step-by-step
When I download the game and I want to open it I get a screen that says: App can't be opened cause the developer is no verified... after that is closes...

# Expected Behavior
It should just open and start

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 11.3 beta 6 (on the new Mac with Apple silicon)

**Comment by clobber** [comment]
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
