### ISSUE TITLE
Touchbar not working after running OpenEmu

### ISSUE THREAD

**Issue by NR0295** [OpenEmu/OpenEmu#4490]
Everytime i play games on openemu with NintendoDS (is the only core i use), i have problems with my touchbar, it goes full black and it won't work anymore until i restart the SMC of my macbook pro. 

Please fix this :)

**Comment by clobber** [comment]
Missing required information here that you simply ignored from the [issue template](https://github.com/OpenEmu/OpenEmu/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

Probably not an OpenEmu bug; report it to [Apple](https://developer.apple.com/bug-reporting/).

**Comment by NR0295** [comment]
Is def a OpenEmu bug, i’ve fixed it reseting the SMC and then everytime i use open emu with the nintendo ds emulator it fucks the touchbar again.


Nicolás Ruivo

📤  ***@***.***

🖥   http://www.nicolasruivo.com

**Comment by clobber** [comment]
> Is def a OpenEmu bug

That does not mean it is an OpenEmu bug.
