### ISSUE TITLE
Gamepad, driver or openemu issue? DPAD not recognized

### ISSUE THREAD

**Issue by zackdvd** [OpenEmu/OpenEmu#4491]
Hi, 
I'm now searching for a while and read a lot of guidelines on that. No help so far.

I've a PS3 USB alternative (Bigben BB4290) and it is working, unless the dpad buttons (digital up/down, left/right buttons). 
The same behavior as on retropie I must say. 

But:
The App "Controllers Light" does show all buttons (working)!
<img width="528" alt="image" src="https://user-images.githubusercontent.com/19238490/113615610-5dcbf900-9654-11eb-93dc-49e2b9476aee.png">

What I saw: Normally button-value is reported 0 not pressed, 1 pressed.
With the dpad, this is different. 8 is not pressed, any other value represent like up, down but also combinations of up and down.

So it is one input with different values. Does openemu handle that?

<img width="370" alt="image" src="https://user-images.githubusercontent.com/19238490/113615893-bbf8dc00-9654-11eb-8f06-670f403b7a36.png">

Thank you for any help on that!

**Comment by clobber** [comment]
Sounds like the device is pretending to be a OEM PS3 gamepad but has a different HID profile. Sorry, no, nothing we can do about that. I'd recommend using a [well-supported](https://github.com/OpenEmu/OpenEmu/wiki#automap-supported-controllers) gamepad instead.

**Comment by zackdvd** [comment]
OK, thanks for your answer anyway!
