### ISSUE TITLE
Can't find folder for screenshots on Mac OS X Sierra?

### ISSUE THREAD

**Issue by OctoAori20** [OpenEmu/OpenEmu#4492]
I've looked in almost every folder on this computer and yet... I can't find it at all. It just somehow doesn't exist? I'm the big confuse and need help figuring this out. D:

**Comment by clobber** [comment]
> Sierra

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/OpenEmu/issues?q=%22screenshots+folder%22
