### ISSUE TITLE
Bowser inside story freeze

### ISSUE THREAD

**Issue by Gelio2314** [OpenEmu/OpenEmu#4495]
The summary is in little words, the game works perfectly there no glitches and I had fun on the way, however when getting for the first time to bowser the game still works perfectly, the movement and all. Up to the point when I had to fight Midbus, when I enter into battle the bowser logo kinda freezes, and then I realize one part of the touch screen and the watch screen kinda switch about 1/3 of the screen change, when Fawful talks to Midbus then goes behind him the game actually freezes. The game doesn't crash, however, the music still continues, or whereas where it was playing at that point when it freezes the game plays that sound repeatedly forever and it still stays frozen and that's basically the story. If to help my model is macOS Big Sur 11.2.3.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4433
