### ISSUE TITLE
Problems with some mame games

### ISSUE THREAD

**Issue by erobles396010** [OpenEmu/OpenEmu#4496]
When i try to play certain mame games i get this message i tried looking for open cases for this problem but i found none im attaching a picture of the error message im getting can you tell me how to fix it thanks 
<img width="1280" alt="Screen Shot 2021-04-15 at 2 20 43 AM" src="https://user-images.githubusercontent.com/13433365/114838923-6b8b2800-9d92-11eb-994b-6e139ab36697.png">

**Comment by clobber** [comment]
Sorry, no, check Archive.org for a more recent MAME ROM set. The message is self-explanatory.
