### ISSUE TITLE
Bluetooth audio not working

### ISSUE THREAD

**Issue by beaver927** [OpenEmu/OpenEmu#4497]
Hi! When I use a rom, the audio does not work with my Bluetooth headphones. Although the audio works with my mac speakers, I often play in places where I need headphones. I am not very good w technology so if someone could please walk me through how to get my Bluetooth audio to work I would really appreciate it!

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues?q=bluetooth+audio
