### ISSUE TITLE
Potential core with DuckStation

### ISSUE THREAD

**Issue by RussDCA** [OpenEmu/OpenEmu#4498]
I guess this kind of question falls under 'feature request'. It's also possible that DuckStation is on someones radar, but just in case, I thought I'd drop this link here.

https://github.com/stenzek/duckstation

Seems like a pretty capable emu, there's a Mac build which (for me) is running really well, and has a host of great features.

Has anyone taking or taken a look at this as a potential new core?

**Comment by MaddTheSane** [comment]
I have created a DuckStation core: https://github.com/MaddTheSane/DuckStation-Core

**Comment by clobber** [comment]
@RussDCA You'd be on your own with any unsupported core plugins. We're not going to ship multiple PS1 plugins; Mednafen is way more than adequate.
