### ISSUE TITLE
Potential core with a newer PCSX2

### ISSUE THREAD

**Issue by RussDCA** [OpenEmu/OpenEmu#4499]
This question likely falls into the 'Feature Request' cat. There seems to have been some recent developments with PCSX2 on the Mac over the past year, so I thought I'd share just in case it's not common knowledge.

After doing a little search, I've seen a previously closed PCSX post dated back to 2011, and in the WIP list Play! is being worked on.

Thought it might be worth sharing the following thread, at the very least, to get it on peoples radar: https://forums.pcsx2.net/Thread-Native-Mac-Testing-Build

It's still a little cranky in places, so likely not quite where it needs to be for OpenEmu, but I thought it might be worth keeping an eye on.

Edit: Forgot to add the GitHub link: https://github.com/tellowkrinkle/pcsx2/tree/MacOS

**Comment by duckey77** [comment]
RusssDCA,  thank you for the info.  We have been  aware of this, and have played around with it a little already.  
It is in early stages and not a priority for porting right now.
