### ISSUE TITLE
Persona 3 Portable 

### ISSUE THREAD

**Issue by davidleibowitz** [OpenEmu/OpenEmu#4500]
I just downloaded OpenEmu and dragged in the ISO for Persona 3 Portable. I saw it in and thought it was good, but when I opened. It was a black screen. I am aware this was an issue for someone else with the same game, but it did not feel helpful. Is there something I have done wrong. I have not updated my Mac to the newest version, but it is a 2018 MacBook Air. version 10.14.6

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Expected Behavior. Persona 3 Portable to be playable.

1. Describe what
1. you want to
1. happen
Have someone help me fix the issue and have me play it. 

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 10.14.6

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues?q=persona+3

Cannot help you beyond what has already been discussed. We are not responsible for PPSSPP emulator bugs.
