### ISSUE TITLE
Adding Sega Saturn game

### ISSUE THREAD

**Issue by Teakay917** [OpenEmu/OpenEmu#4501]
I have tried to find an answer in previous posts, but cannot.  I am trying to add a Sega Saturn game to OpenEmu, but it will not scan after dragging and dropping.  Console reports it cannot find the file referenced in the .cue file "No such file or directory".  I have tried to edit the .cue file to ensure the file names match, but I continue to get the same error.  This game did load correctly in Yabause (without requiring any editing of .cue file), but I would prefer to use OpenEmu for save states and etc.  Why would it work in Yabause and not OpenEmu?

![Screen Shot 2021-04-19 at 10 54 06 AM](https://user-images.githubusercontent.com/82835504/115281287-b0e68700-a0fd-11eb-8421-9ba7e8a5ebe5.png)
![Screen Shot 2021-04-19 at 10 52 50 AM](https://user-images.githubusercontent.com/82835504/115281299-b3e17780-a0fd-11eb-90e5-3d27997fc18c.png)
![Screen Shot 2021-04-19 at 10 47 38 AM](https://user-images.githubusercontent.com/82835504/115281306-b643d180-a0fd-11eb-89bb-11714f885697.png)
![Screen Shot 2021-04-19 at 10 56 00 AM](https://user-images.githubusercontent.com/82835504/115281492-ebe8ba80-a0fd-11eb-9e5d-e48d204d539f.png)

**Comment by clobber** [comment]
The import error message tells you everything you need to know:
>  Console reports it cannot find the file referenced in the .cue file "No such file or directory".

The importer is looking for `SF3Track2.bin` and it does not exist. `SF3Track2.bin` is not the same as `Shining Force III - Scenario 1 Track2.bin`, now is it? From the messages, it is obvious that those file names need to match what is referenced in the cue sheet.
