### ISSUE TITLE
No Game allowed to add to the ps1 emulator

### ISSUE THREAD

**Issue by Diego97romero** [OpenEmu/OpenEmu#4503]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step

Download a ps1 game.
Uncompile the game with the unarchiver
add the .cue and .bin to the ps1 library
error message appear with any game:
Must not be compressed:
• .bin

1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what

add a game to the ps1 library
1. you want to
1. happen

# Observed Behavior

1. Describe what you see

The OpenEmu application is not allow the user to add and game to the ps1 library
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 11.2.3

**Comment by clobber** [comment]
> add the .cue and .bin to the ps1 library

That's not how importing a CD-based game works. Read the [import guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing).
