### ISSUE TITLE
Lost Auto Save

### ISSUE THREAD

**Issue by ellowex** [OpenEmu/OpenEmu#4507]
Hi, I’ve been using Open Emu to grind out Pokemon Red for the Gameboy for almost a month now. Last night I was on my way to catch the legendary birds and accidentally made Articuno faint - so I wanted to start the game over to try catching him again. Sadly I didn’t realize that I didn’t make an actual save file for this play-through. I had only been saving through Open Emu’s auto save function. I’ve since lost that play-through and all my hours put into it. Does anyone know if there’s a way I can find older auto saves and load them back up? 

Using OpenEmu on MacOSX / Pokemon Red
Thanks

**Comment by clobber** [comment]
Sorry, no, nothing you can do.
