### ISSUE TITLE
Cheat codes not persistent between game sessions

### ISSUE THREAD

**Issue by Son-Isaki** [OpenEmu/OpenEmu#4508]
Hey, I saw this issues is known since **2013**, but the posts are all closed since then...

Well, is this a bug ? if it is, will this bug be marked as corrected one day ? or is it just impossible to make it work ? (I don't really know how NDS games can be emulated on macos....) 

I'd like to understand why it is so complex to make the cheat codes persistent

Or, maybe I am using the cheatcodes in a wrong way and so, Is there any thing to activate or whatever to make them persistent

# Steps to reproduce

1. Open a game
2. Add cheat code
3. Close the game
4. Reopen the game

Now the code is gone

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: catalina 10.15.3
- Game: Pokemon SoulSilver

**Comment by clobber** [comment]
You are aware of issue #782. Do not open duplicates asking about this. Cheat codes will not persist until there is a full fledged cheat code manager UI.
