### ISSUE TITLE
OpenEmu NOT opening 

### ISSUE THREAD

**Issue by Carpemuo** [OpenEmu/OpenEmu#4509]
Summary of issue

When downloaded, after proceeding with the "special instructions for opening", it does not open. 

# Steps to reproduce

1. Downloaded
2. Unzipped
3. With ctrl pressed, click Open
4. Message: The application “OpenEmu” can't be opened' on Mac

# Expected Behavior

1. To open 

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 10.14.6
- MacBook Pro (Retina, 15" MID 2015)

**Comment by clobber** [comment]
1. Download [OpenEmu](http://openemu.org/)
2. Extract the zip file.
3. Right click on OpenEmu.app and click "Open", disregard the first message.
4. Again, right click on OpenEmu.app and click "Open"
