### ISSUE TITLE
GameShark cheat codes do not work in pokemon games

### ISSUE THREAD

**Issue by tocho29** [OpenEmu/OpenEmu#4512]
Hi guys, I have a problem and I don't know how to solve it.

I like OpenEmu and I'm using version 2.3.3 on MAC OS Sierra.

I am currently playing pokemon yellow edition but the cheat codes are not working, for example:

I want to capture Alakazam and I use this code: 0195d7cf but it doesn't work.

Is there something I'm doing wrong, do I need another version of the emulator, am I missing some plugin or program?

The game file has the extension .gb

I hope you can help me

Thank you very much.

**Comment by clobber** [comment]
It works. Add and enable the cheat code. Enter the forest and walk around until an encounter occurs.

Using your **GameShark** cheat code: `0195d7cf`

<img width="799" alt="Screen Shot 2021-05-10 at 2 06 08 PM" src="https://user-images.githubusercontent.com/1303132/117720108-7c656880-b19b-11eb-9220-15f926b3cfaa.png">

You will notice the sprite is corrupted. Instead, use **Game Genie** cheat codes for this game.

Using **Game Genie** cheat code: `368-AF8-F72+958-B08-E6A+2B8-B18-C4E`

<img width="869" alt="Screen Shot 2021-05-10 at 2 23 13 PM" src="https://user-images.githubusercontent.com/1303132/117720866-6d32ea80-b19c-11eb-8363-ecc747c76d4f.png">

As per our [Cheat Code guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes), the best resource for cheat codes is GameHacking.org.

Visit https://gamehacking.org/game/771, click "Name Modifier" > see "Always Encounter Modifier" > click "Info"
