### ISSUE TITLE
frozen

### ISSUE THREAD

**Issue by shorty7** [OpenEmu/OpenEmu#4513]
So I was playing earthbound and my game froze twice and shutting down my computer doesn’t work FYI I’m using snes9x v1.60
- OpenEmu Version: 1.3
- macOS Version: high sierra 10.13.6

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
