### ISSUE TITLE
How would I "Insert a CD"

### ISSUE THREAD

**Issue by ArcadeH0uze** [OpenEmu/OpenEmu#4516]
So I was playing Vib-Ribbon (A PS1 game) on the OpenEmu emulator, and beat the main course 4 times already. Now I was getting bored playing the same 3 courses over and over again (as one does), and a big feature of the game is playing your own CDs. However I am unsure how to "Play" these CDs. Do I insert them into my computer? Is there another way? Please help I have confuse

**Comment by clobber** [comment]
https://old.reddit.com/r/OpenEmu/comments/ccouuy/vib_ribbon_custom_songs/
