### ISSUE TITLE
Snes9x MSU-1 support?

### ISSUE THREAD

**Issue by sdellysse** [OpenEmu/OpenEmu#4518]
I found this question about Higan # 3507 but it's from a number of years ago

Is there any way to get MSU-1 support with the Snes9x core? I've tried the usual way that works with retroarch but I haven't had any luck. Any chance anyone knows how to get this working?

**Comment by clobber** [comment]
Use our BSNES core plugin to achieve this. For example:

1. Import `aladdin_msu1.sfc`
2. Right click on `aladdin_msu1.sfc` and click "Show in Finder"
3. Move the rest of the MSU-1 associated files there: `aladdin_msu1.msu` (a zero-byte file), `aladdin_msu1.xml` (memory mappings), `aladdin_msu1-1.pcm` ... `aladdin_msu1-41.pcm` (PCM tracks)
