### ISSUE TITLE
 MAME Romset Updater like ClrMAMEPro

### ISSUE THREAD

**Issue by ToniBahloni** [OpenEmu/OpenEmu#4519]
#Hello! Let me start by saying that I love OpenEmu. It's fantastic! I recently noticed that some of my rooms do not work. It looks as if the MAME core has been updated and so my romset needs to be updated. Is there a way to do this? There appears to be a ton of options for Windows machines, like ClrMAMEPro, but nothing for Mac OS. Thank you!

This issue was addressed by Clobber in this fashion:
_It's not up to us to teach you how to warez. Find a set and just download the zip files you want from the set_

I'm not asking for any illegal information, regarding the "warez" comment... As my question above stated, I was looking for an updater solution, like ClrMAMEPro, but for Mac. If there is a solution such as this, people wouldn't have to resort to warez and could just update their current romset without breaking the law.

**Comment by clobber** [comment]
> people wouldn't have to resort to warez and could just update their current romset without breaking the law.

That isn't true - and you are asking in the wrong place. This is for tracking bugs for OpenEmu.
