### ISSUE TITLE
Update the Wiki

### ISSUE THREAD

**Issue by matthewlilly** [OpenEmu/OpenEmu#4521]
I can't seem to find a way to initiate a pull request for the Wiki. I have also tried to clone it and push changes, using the link given on the Wiki page, but had no luck. Maybe it's a GitHub issue.

I was attempting to update the following section: [User guide: CD based games - I have a .CHD file from Archive.org](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#q-i-have-a-chd-file-from-archiveorg). 
To add another conversion method for .chd files. MAME rom-tools installed via homebrew makes using chdman a lot easier, and the script helps speed up multiple file conversions.

Proposed change below the line.

-----

### Q. I have a .CHD file from [Archive.org](https://archive.org/details/software)

Some CD dumps are stored in a MAME/MESS-specific format capable of multiple layers of compression (LZMA/zlib/FLAC/Huffman) called CHD (Compressed Hunks of Data or Compressed Hard Disk images), containing a `.cue` and `.bin` file. These files must be uncompressed with `chdman` before they can be used.
Two methods are listed below;

1. 1. Download and install the [SDL2](http://www.libsdl.org/download-2.0.php) framework for OS X.  
   2. Download a pre-compiled version of MAME or MESS 64-bit (x86_64) from [SDLMAME](http://sdlmame.lngn.net/)
   3. [Uncompress](https://itunes.apple.com/us/app/the-unarchiver/id425424353?mt=12) the `.zip` file and copy the `chdman` file found inside the "tools" folder to the same folder as your game with the `.chd` file
   4. Navigate to your game's folder in Terminal. Follow guides [here](http://apple.stackexchange.com/questions/11323/how-can-i-open-a-terminal-window-directly-from-my-current-finder-location) or [here](http://www.howtogeek.com/210147/how-to-open-terminal-in-the-current-os-x-finder-location/) to do this.
   5. Extract your `.chd`. In Terminal, enter the following command and press enter, making sure to add the correct filenames:

    `./chdman extractcd -i "sonic cd (usa).chd" -o "sonic cd (usa).cue" -ob "sonic cd (usa).bin"`
    

2. 1. Install [Tools for MAME](https://command-not-found.com/chdman) via homebrew.  
   2. Navigate to your game's folder in Terminal. Follow guides [here](http://apple.stackexchange.com/questions/11323/how-can-i-open-a-terminal-window-directly-from-my-current-finder-location) or [here](http://www.howtogeek.com/210147/how-to-open-terminal-in-the-current-os-x-finder-location/) to do this.
   3. Extract your `.chd` 
      1. **For single files**: In Terminal, enter the following command and press enter, making sure to add the correct filenames:
         
         `chdman extractcd -i "sonic cd (usa).chd" -o "sonic cd (usa).cue" -ob "sonic cd (usa).bin"`
      2. **For multiple files**: In Terminal, enter the following command and press enter: `touch convert.sh`
         
         Open `convert.sh` with an editor of your choice, enter the following and save:
   
         ```bash
         for file in *.chd; do
            chdman extractcd -i "${file%}" -o "${file%.chd}.cue" -ob "${file%.chd}.bin"
         done
         ```
         In Terminal, making sure you are still in the correct directory (with the .chd files), enter the following and press enter: `bash convert`

**Comment by clobber** [comment]
Added, thank you!
