### ISSUE TITLE
Hyperkin controller won't work in OpenEmu

### ISSUE THREAD

**Issue by WBPound5987** [OpenEmu/OpenEmu#4522]
Hello! I recently purchased a Hyperkin Scout BT controller and was able to connect it to my Mac via bluetooth. It shows up as connected on my mac and also shows up as connected in OpenEmu. The "hyperkin pad" shows up just fine on my OpenEmu system preferences. Yet, for some reason, the controller won't work. Nothing happens when I press the buttons or pad. It's connected just fine so why won't it work? Any help would be appreciated. Thank you.
-BP

**Comment by Hotdogs77a** [comment]
This issue could be related to mine: https://github.com/OpenEmu/OpenEmu/issues/4536
Maybe it is a bug due to changes in the bluetooth specifications in macOS 11.4?

**Comment by clobber** [comment]
If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
