### ISSUE TITLE
Keyboard input doesn't connect to Openemu

### ISSUE THREAD

**Issue by italianstal** [OpenEmu/OpenEmu#4523]
Lately I have been trying to play with Openemu some Nintendo DS games. However, every time I open Openemu a messages pops up saying: "To use the keyboard as an input device, you need to give OpenEmu the "Monitor input" permission.
If the keyboard controls stops working, disable and then re-enable this permission."

This is a permission found in 'Privacy and Security' of every macbook. 

Thing is, I have already granted this permission and have, several times, turned it off and on for the specific keyboard input. Nothing ever changed. I am still unable to play any games due to the keyboard not being connected for some reason to Openemu. 

I already had Openemu in past and I never had these type of issues so I was wondering if I am the only one to have these sorts of problems and if someone knew perhaps how to solve it. The versions of Openemu and of my mac I am currently running are:

- OpenEmu Version: v2.3.3
- macOS Version: Big Sur 11.3.1

**Comment by clobber** [comment]
We stickied [this issue](https://github.com/OpenEmu/OpenEmu/issues/3988#issuecomment-541127837) for a reason. Toggle the permission until it works.

Next time, use the search. https://github.com/OpenEmu/OpenEmu/issues?q=%22input+monitoring%22
