### ISSUE TITLE
Can't get wiimote to pair on iMac running high sierra, Openemu 2.0.9.1

### ISSUE THREAD

**Issue by cookaloris** [OpenEmu/OpenEmu#4525]
Hello,
I just put OpenEmu 2.0.9.1 onto my old iMac (mid 2011), which is running high sierra.
Everything looks good except I cannot get the wiimote to pair with OpenEmu. I followed the directions carefully. I select "add a wiimote" and then i press the red button or else press 1 and 2 on the controller, then I select "start scanning" and most of the time it doesn't find the wiimote. Occasionally it will prompt for a code, and the wiimote will buzz and if I go to the game, I can use the controller for about a minute. Then it just disconnects again. This is with one of my wiimotes. The other doesn't connect at all. I am at a loss. Has anyone had a similar problem or have any suggestions what to do? 
High Sierra is the highest OS i can run on this older iMac, and I believe Openemu 2.0.9.1 is the latest version I can have with high sierra. I have used the wiimotes with my late 2012 iMac and they work fine with that, so I don't believe there is anything wrong with the wiimotes.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
