### ISSUE TITLE
Update mGBA core

### ISSUE THREAD

**Issue by deroa163026** [OpenEmu/OpenEmu#4526]
Want to update to version 0.9.1 of mGBA from 0.8.4. How do I do this. No update button

**Comment by deroa163026** [comment]
Fire red colors are desaturated compared to native mGBA and visualboy. How do I fix?

**Comment by deroa163026** [comment]
Is there option to toggle fast forward without holding down the key or perhaps setting a different target fps?

**Comment by clobber** [comment]
> No update button

We haven't updated our core port to the latest mGBA yet. 

> colors are desaturated

Use mGBA standalone if the difference in palette colorspace bothers you.

> option to toggle fast forward without holding down the key

No. No plans to add this.

**Comment by deroa163026** [comment]
So is the difference in the palette intentional? I didn't change any settings in standalone mGBA colors, just default but the difference in saturation is there.
