### ISSUE TITLE
Just another guy who can't work out the keyboard

### ISSUE THREAD

**Issue by Breindahl12** [OpenEmu/OpenEmu#4533]
Summary of issue
It's the usual – I'm another one of the guys who can't seem to get their keyboard to work with OpenEmu. Sorry in advance for bothering with asking a question that's been asked a thousand times before, it's just that I'm about to give up and delete the platform. 

I've read all the guides and it seems it all comes down to the repeated advice: just keep toggling the keyboard permission until it works. I've been doing that for a few days now, and I feel like, if it hasn't worked so far I don't believe it will anytime soon. 

It seems a little weird and buggy that that would be the solution, but I tried it anyways and it got me nowhere. If toggling really is the only advice out there – I've tried all the others like closing applications and such – then this post might be more of a prayer to the developers that they try to change this. Keep in mind, I say this as someone who knows nothing of coding of programming, so that might be presumptuous of me to say, but it does just seem super weird. 

I also know of the contributing guidelines so, yea – sorry. 

# Steps to reproduce

All I'm doing is opening OpenEmu and a game, but the keyboard won't really cooperate with me. 

# Expected Behavior

I kind of just expect the platform to connect with the keyboard. 

# Observed Behavior

I press keys but nothing happens.

# Debugging Information

- OpenEmu Version: v2.3.3
- macOS Version: Big Sur 11.4 (MacBook Air)

**Comment by clobber** [comment]
If you get the input permission dialog as you open the app, you must toggle the setting until it works. Otherwise, see here: https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems

Also try restarting your machine to see if that has any effect. You may have some other application causing interference with OpenEmu receiving inputs.
