### ISSUE TITLE
JoyCons not working properly

### ISSUE THREAD

**Issue by Hotdogs77a** [OpenEmu/OpenEmu#4534]
Summary of issue
JoyCons only work when there is just ONE JoyCon connected. When BOTH are connected at the same time OpenEmu doesn't recognize any input from either controller.

# Steps to reproduce

1. Connect both Joycons in the mac settings
2. OpenEmu will show both controllers in the controls panel but doesn't recognize any input of the buttons/sticks.
3. Switching between Joycon L or R also doesn't make a difference
4. Any of the two Joycon will start working when you disconnect the other one

Both controllers are charged and work fine on my Switch console. Maybe this is an issue with the latest Mac 11.4 Update, as this issue wasn't there in 11.3. Also tried deleting controller bindings in the preferences folder.

- OpenEmu Version: 2.3.3
- macOS Version: 11.4

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/OpenEmu/issues?q=joycons
