### ISSUE TITLE
JoyCon input issues (two JoyCons for two players is not working)

### ISSUE THREAD

**Issue by Hotdogs77a** [OpenEmu/OpenEmu#4536]
# Summary of issue
First, for clarification: I AM NOT TRYING TO USE BOTH JOYCONS FOR ONE PLAYER. This is different. I want to use the left JoyCon for player one and the right JoyCon for player two. This is currently NOT working.

When both JoyCons are connected at the same time, OpenEmu is not recognizing any input from the JoyCons at all. HOWEVER: If I only connect ONE of the two JoyCons (L or R doesn't matter) everything works perfectly fine. The moment I connect the second JoyCon the first JoyCon stops working.

Both controllers are charged and work totally fine on my Switch console. They also do NOT disconnect or have any bluetooth connection problems. Maybe this is an issue with the latest macOS 11.4 Update, as this issue was not present in macOS 11.3. I also tried deleting the controller bindings file in the preferences folder.

# Steps to reproduce
1. Connect both JoyCons in the macOS settings
2. OpenEmu will show both controllers in the controls panel but doesn't recognize any input of the buttons/sticks at all.
3. Switching between JoyCon L or R also doesn't make a difference
4. Any of the two JoyCon will start working again when you disconnect the other one

OpenEmu Version: 2.3.3
macOS Version: 11.4

**Comment by Hotdogs77a** [comment]
@clobber 
Sry for the repost, couldn't reopen/comment on the first post anymore. Just wanted to say that this is a different issue. I am well aware of the problem, that both JoyCons can NOT act as a single controller for one person. I just want to use the left JoyCon for player one and the right JoyCon for player two. That should be possible, right?

**Comment by clobber** [comment]
> Maybe this is an issue with the latest macOS 11.4 Update, as this issue was not present in macOS 11.3.

Then you need to first [report this to Apple](https://developer.apple.com/bug-reporting/). Closing for now.
