### ISSUE TITLE
Shrek Super party and other games freeze when gameplay starts

### ISSUE THREAD

**Issue by jimdandy1234531** [OpenEmu/OpenEmu#4538]
so with Shrek super party and a couple others (but shrek is the only one that wont play period, the others will mostly play but wont always start up right) but as soon as i get thru the menus and at the first opportunity for a button input, the game freezes and becomes unresponsive and I have to force quit OpenEmu. Im on a 2015 macbook air and no other systems have this problem.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. OpenEmu
2. Choose Game (Shrek Super Party for main and 100% broken example)
3. Set up controller if not already
3. Either set up memory card or not by hitting A or B(neither setting works)
4. Pick any game setting (tournament or skirmish dont work, so pick either one, but I will be explaining the tournament setup from now on)
5. Pick Character (none work so pick Shrek, it's fastest)
6. Pick computer players (hit A twice)
7. Hit A to get passed explanations of mini games (bug catcher is first)
8. Wait for the Mirror to count down and disapear and watch the game freeze and crash 

# Expected Behavior

1. To play the game as intended
2. to play as if a gamecube has not been covered in AVGN shit and dog piss
3. to have the game to be read as if it were unscratched and not damaged in anyway.
4. To be able to interact with the first part of the game were character inputs are able to be triggered.

# Observed Behavior

1. I start the game like every other
2. the game starts as normal till i get passed the menus
3. the game crashes and i have to restart OpenEmu as soon as I can actually play the game once the menus have been gotten thru.

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 11.2.3

**Comment by clobber** [comment]
OpenEmu is not responsible for dolphin emulation bugs.

**Comment by Keremw70940** [comment]
I also got the same problem and I do not use OpenEmu, just Dolphin. The exact same problem emerges. Any change you found the solution? Really wanted to show my gf my childhood :(
