### ISSUE TITLE
OpenEmu won't take my keyboard inputs although i have given it the permission needed 

### ISSUE THREAD

**Issue by HorrorSpirit** [OpenEmu/OpenEmu#4540]
Whenever i open OpenEmu, it pops that little annoying message asking me to go give it input monitoring. I go there, and wouldn't ya know it, it already has that permission, yet i won't work.

# Steps to reproduce

I just open OpenEmu and it gives me that error message. I have no idea what is going on.

# Expected Behavior

That OpenEmu will actually take my inputs as intended since i have given it the permission it asked for.

# Observed Behavior

When i press my keyboard on the preferences section to change the controls, nothing happens. When i'm in a game and attempt to take an action, nothing happens.

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 11.4/Big Sur

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4535
