### ISSUE TITLE
Automap for xbox wireless controller (Xbox Series X|S)

### ISSUE THREAD

**Issue by jamiet83** [OpenEmu/OpenEmu#4542]
Hello, I can manually map controls to this device without issue but automap feature would be useful.

Manufacturer:	Unknown (0x8, 0x1702)
  Bluetooth Core Spec:	4.2
  Firmware Version:	5​.​1.2482.0
  Vendor ID:	0x045E
  Product ID:	0x0B13

A slight workaround was modify Controller-Database.plist and add this entry in as if it was a xbox360 controller under section starting with <key>OEControllerMicrosoftXbox360</key> (strangely it did not automap when I added it to the xbox one section <key>OEControllerMicrosoftXboxOne</key> )

But this workaround did not allow me to manually assign controls to the dpad and right analog stick.

<dict>
				<key>OEControllerDeviceName</key>
				<string>Xbox Wireless Controller</string>
				<key>OEControllerVendorID</key>
				<integer>1118</integer>
				<key>OEControllerProductID</key>
				<integer>2835</integer>
			</dict>

OS is big sur 11.4, openemu build is 2.3.3

kind regards, Jamie

**Comment by clobber** [comment]
Added in https://github.com/OpenEmu/OpenEmu/commit/a4a1f2f319de5aa5eed2f67935969bcdd0889b1c

**Comment by erikmartinessanches** [comment]
> Added in [a4a1f2f](https://github.com/OpenEmu/OpenEmu/commit/a4a1f2f319de5aa5eed2f67935969bcdd0889b1c)

Does this mean OpenEmu also supports series X controllers? I on't think series X is explicitly mentioned on the [controllers page](https://github.com/OpenEmu/OpenEmu/wiki#supported-controllers).
