### ISSUE TITLE
NDS microphone

### ISSUE THREAD

**Issue by StupidRepo** [OpenEmu/OpenEmu#4547]
# Summary of issue

So, I am stuck in the "Call your Dog's name" phase as the Microphone is just a buzzing noise instead of my voice. OpenEMU doesn't ask for microphone permissions and isn't seen in the Microphone Permissions page in System Preferences > Security and Privacy > Privacy > Microphone.

# Steps to reproduce

Get a Nintendog ROM and play it until you get up to the "Call your Dogs name". Hold the microphone button, and try your best to get it to play back what the dog hears, which would be a static buzzy noise.

# Expected Behaviour

Microphone doesn't produce some weird glitchy buzzy noise and instead picks up my voice.

# Observed Behaviour

Microphone producing some weird glitchy buzzy noise.

# Debugging Information

- OpenEmu Version: Latest
- macOS Version: macOS 12 Developer Beta

**Comment by StupidRepo** [comment]
*Also did a 5 year old compose this template because the numbered listings are all 1 and behaviour was spelt wrong.*

**Comment by clobber** [comment]
Not supported.

https://github.com/OpenEmu/OpenEmu/issues?q=nds+microphone
