### ISSUE TITLE
BigSur immediate crash

### ISSUE THREAD

**Issue by Will1297** [OpenEmu/OpenEmu#4550]
I have searched through and many people have issues with their keyboards when updating to the Big Sur OS, however I cannot even open the application. 
Originally I was running high sierra, and an older version of OpenEmu, my games kept crashing so I went to update the application but needed an updated OS to do so. So I updated my OS and now I can't even open the application at all. 
Upon deleting and re-downloading OpenEmu I get a pop up that says "OpenEmu cannot be opened because the developer cannot be verified". 
From there I can click cancel, and then go to the apple button top right and system preferences and then general and click "open anyway" for OpenEmu and I get "The operation couldn’t be completed. (Foundation._GenericObjCError error 0.) "

Is there anyone who can tell me how to fix this?

**Comment by clobber** [comment]
Download the application from our website. You have an old version that will crash on modern macOS.

**Comment by Will1297** [comment]
I have been downloading from the website.

**Comment by Will1297** [comment]
After looking through all mentions of #3044
I deleted my game files (after copying them to a separate folder) - no resolution
I have opened with the archive utility application
The zip file is from this website with the most up to date version of OpenEmu. 

Still says it can't be opened because the developer is unverified, and then I get that object error upon trying to open it anyway and it just doesn't open at all.

**Comment by Will1297** [comment]
@clobber I mean is there any fix that is known other than maybe reverting back to an old OS? 
I really like OpenEmu and I don't really want to use another emulator. I've been trying to get this to work for about 2 days now and I can't find a fix anywhere really.
