### ISSUE TITLE
(Feature Request) BSNES-HD and Sega Genesis GX Wide in OpenEmu for SNES and Genesis Widescreen Emulation

### ISSUE THREAD

**Issue by ItzGreenForever** [OpenEmu/OpenEmu#4551]
Will widescreen SNES and Genesis (via BSNES-HD and Sega Genesis GX Wide) be supported in OpenEmu? I can only use it in RetroArch and it's slow so I hope it gets added to OpenEmu.

**Comment by clobber** [comment]
Only if these features make their way to the upstream emulators and not forks.
