### ISSUE TITLE
Sega CD Contoller Input

### ISSUE THREAD

**Issue by pupliusscipio** [OpenEmu/OpenEmu#4552]
Greetings,

I have the Sega Saturn Wireless controller from retro-bit, and it works fine with Genesis games on Open Emu.  But I can't get it to come up for Sega CD games on the program.

What am I doing wrong?

**Comment by clobber** [comment]
Per-system input mapping issues are not possible with OpenEmu. Each system at the controller mapping stage uses the same input code.

> But I can't get it to come up

Unclear what this means.

> What am I doing wrong?

You have provided no details to troubleshoot your problem.
