### ISSUE TITLE
Wont let me insert controls

### ISSUE THREAD

**Issue by deh6cker** [OpenEmu/OpenEmu#4558]
Summary of issue
Openemu won't let me input my controls via the keyboard 
permission is on
Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
it will not let me change from arrow key controls to WASD, i pressed ESC to get rid of the arrow keys but it wont let me input the new controls
I did give input control permission
1. How to cause the problem
?
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen
I want to be able to play the game I am in the middle of.
# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: Big Sur 11.1

**Comment by clobber** [comment]
You already found issue #4535
