### ISSUE TITLE
Please help , OpenEmu can not connect to internet even with shadowsocks

### ISSUE THREAD

**Issue by Welogic** [OpenEmu/OpenEmu#4561]
![cache](https://user-images.githubusercontent.com/52484328/126273641-19ca370d-d7b7-4f01-853a-516fb880f8f6.png)

Can log on to Github successfully , but OpenEmu can not download any core from the internet .

revise the host or using shadowsocks could not work.

meet this problem for the first time since I started to use OpenEmu 4 years ago.

**Comment by clobber** [comment]
User connectivity issues are not OpenEmu issues. Your machine or ISP is blocking outgoing connectings to GitHub -- probably some sort of firewall software you have running (or your government!).
