### ISSUE TITLE
Can you provide a way to update cores independant of app?

### ISSUE THREAD

**Issue by pleasejustgo** [OpenEmu/OpenEmu#4562]
It's especially problematic with mame because when you update OpenEmu a mame rom may suddenly stop working becuaue it's the wrong set. I can't find the proper version of the rom I want to play, only the latest few versions are obtainable.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4423
