### ISSUE TITLE
Black Screen in Mame on Mac Os 10.13.6 Help Please

### ISSUE THREAD

**Issue by pinwil** [OpenEmu/OpenEmu#4563]
Hi I have a Macbook Pro 2010 15 inches, with High Sierra 10.13.6. And I have installed the version of open emu 2.0.6 was the only one that I installed the core of mame because the other previous and new versions did not install the core of mame.

When I enter the bios of neogeo.zip and a game the screen stays black, I tried with several versions of the bios and games and none works, I do not know if it is a problem of the version.

The core of mame I install it now is the 0.227.0.1 someone could help me where to get the neogeo.zip of this version as the games please.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."
