### ISSUE TITLE
Request: More donation options

### ISSUE THREAD

**Issue by noah-nuebling** [OpenEmu/OpenEmu#4564]
Hi there! First off, OpenEmu is some of the best software I've ever used. Thanks and kudos for making it.

In awe of the sheer quality of your product, I wanted to donate today, but I don't have BitCoin or CashApp or any of the other donation options on your website.

So I would like to request more donation options, ideally PayPal or Apple Pay.

**Comment by noah-nuebling** [comment]
Sidenote: I'd feel really good about paying 12.99 bucks for a one time donation or 1.99 for a monthly donation

**Comment by clobber** [comment]
> one time donation or 1.99 for a monthly donation

You are describing Patreon, which is one of the four options available on the website. Sorry, won't be others beyond that.
