### ISSUE TITLE
wind Waker mirror shield unable to aim correctly opened

### ISSUE THREAD

**Issue by Tonytheconqeror** [OpenEmu/OpenEmu#4566]
I was playing the legend of Zelda: the wind waker using opened on macOS Big Sur. I Had just obtain the mirror shield in the game. I need to aim the shield at a symbol on the wall to open the locked door, which I need to use only 50% pressed in the control stick, but my keyboard only detect: key pressed，key not pressed. Is there a way to have only 50% control stick tilted?

**Comment by clobber** [comment]
No. You need to buy a [supported gamepad](https://github.com/OpenEmu/OpenEmu/wiki#automap-supported-controllers) with analog controls.
