### ISSUE TITLE
Xbox One Elite Controller/Xbox One Controller Support

### ISSUE THREAD

**Issue by Senor-Hymie** [OpenEmu/OpenEmu#4580]
Will there be any Xbox One Controller support added?

As far as I know there are no drivers that support Xbox One controllers under the latest edition of Mac. The latest version of Mac also already natively supports Xbox controllers so I don't understand why Openemu doesn't.

**Comment by clobber** [comment]
> The latest version of Mac also already natively supports Xbox controllers 

No. Only certain ones.

Do not open new issues for this. Xbox One S already works with OpenEmu. Xbox Series X|S needs automap support. Xbox Elite is not supported: https://github.com/OpenEmu/OpenEmu/issues?q=xbox+elite
