### ISSUE TITLE
How to activate double/continuous jump for NES controller?

### ISSUE THREAD

**Issue by FEI-JIANG** [OpenEmu/OpenEmu#4581]
How to activate double/continuous jump for NES controller? Have to push jump-button every time when a jump.

**Comment by clobber** [comment]
If by "continuous" you mean without having to press/hold an actual button, no such feature exists. We have "rapid fire" which works in-game when pressing a button + the toggle key to enable. The toggle keys are found in Controls preferences and are called "Rapid Fire Toggle" and "Rapid Fire Clear".

**Comment by FEI-JIANG** [comment]
@clobber I didn't mean to get "continuous" jump without pressing/holding an actual button. What I want is to press the jump button and then hold the button to get continuous jump, rather than pressing the jump button again and again to get additional jump. Thanks

**Comment by clobber** [comment]
> What I want is to press the jump button and then hold the button to get continuous jump

I explained the Rapid Fire system so that will give you exactly what you want.

**Comment by FEI-JIANG** [comment]
Just figure it out. Thanks
