### ISSUE TITLE
Black screen from save state

### ISSUE THREAD

**Issue by jeskara** [OpenEmu/OpenEmu#4588]
Every time I open a save state of my Pokemon SoulSilver game for Nintendo DS on Open Emu, the player screen appears black although the menu on the lower half of the screen is still functional. No key or button seems to fix this issue. 

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Start a game in Pokemon SoulSilver 4781 (U)(Xenophobia)
2. Save using OpenEmu rather than the in-game menu
3. Open a save state game

# Expected Behavior

1. Open save state game
2. Screen is not black, but rather reflects what the thumbnail shows (where I last saved in the game)

# Debugging Information

- OpenEmu Version: v.2.3.3
- macOS Version: 10.14.6 Mojave

**Comment by clobber** [comment]
#1112
