### ISSUE TITLE
Import error 'Domain=NSCocoaErrorDomain Code=264' 

### ISSUE THREAD

**Issue by Douglasli** [OpenEmu/OpenEmu#4590]
I was trying to import _Suikoden-Tenmei no Chikai [Koei the Best]_ but got the following error.

```
Must not be compressed:
• "5004460.bin"

Unexpected error:
• "5004460.cue"

Error Domain=NSCocoaErrorDomain Code=264 "The file “5004460.cue” couldn’t be opened because the text encoding of its contents can’t be determined." 
```
What could be the problem?
Thanks in advance!

**Comment by clobber** [comment]
Read: 

* https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#importing

* https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Importing#import-failure-help
