### ISSUE TITLE
Is melonDS going to be supported?

### ISSUE THREAD

**Issue by patrickmetz** [OpenEmu/OpenEmu#4591]
Greetings,

I'd like to ask if there are any plans to integrate melonDS as a chooseable Nintendo DS core?
The emulator has come a long way and surely is a mature alternative to DeSmuME.

Bests,
Patrick

**Comment by clobber** [comment]
> melonDS

We are aware. It is possible, but unplanned.

**Comment by ayevtushenko** [comment]
I would be great to have this core in OpenEmu, the main reason is Wi-Fi support.
Just tested it in Digimon World DS and it works!
