### ISSUE TITLE
Dolphin Core Vulkan GFX configuration

### ISSUE THREAD

**Issue by heretic82** [OpenEmu/OpenEmu#4594]
Hi Dev Team !
with open emu I can not go at good performance with my MacBook with Iris Video Card 
in Dolphin emu I can select Vulkan as GFX core engine
<img width="605" alt="Schermata 2021-09-16 alle 20 47 10" src="https://user-images.githubusercontent.com/64310549/133670548-25ec212f-efee-4ec2-8914-8984c3412647.png">
as in the image attached, I tried tu "update" folders in the core plugin and config under application support folder with this version but no luck :(

**Comment by clobber** [comment]
> I tried tu "update" folders in the core plugin and config under application support folder with this version but no luck :(

It doesn't work that way. OpenEmu is not a "launcher"

Use Dolphin standalone. The OpenEmu core port does not have support for the Vulkan render yet.

**Comment by heretic82** [comment]
> > I tried tu "update" folders in the core plugin and config under application support folder with this version but no luck :(
> 
> It doesn't work that way. OpenEmu is not a "launcher"
> 
> Use Dolphin standalone. The OpenEmu core port does not have support for the Vulkan render yet.

Yes I know is not a launcher just a try to see if in the core the option "[Core]
GFXBackend = Vulkan" could be enabled in some way and a desperate try to copy the binaries.
i will wait the implementation ;) 

thanks
