### ISSUE TITLE
Can't add new games to the library

### ISSUE THREAD

**Issue by julienbfabre** [OpenEmu/OpenEmu#4596]
I am no longer able to add new games to the library, nothing happens, i tried drag n drop and also from the menu add to library, in both cases nothing happens, no errors, nothing.

I've checked the console.app and i see the following:

```
could not set attributes com.apple.macl on destination file descriptor: Attribute not found
error processing extended attributes: Attribute not found
```

Both thrown by the `OpenEmu (libcopyfile.dylib)`

I have given full disk access to open emu in the Mac Security Settings.

Any idea what's going on and how to solve it?

- OpenEmu Version: 2.3.3 (EX)
- macOS Version: 11.5.2 (Big Sur)

**Comment by julienbfabre** [comment]
The problem seems to be with a particular ROM file after all, i was able to add different ones on two systems so i am closing this for now.

**Comment by clobber** [comment]
> a particular ROM file

Which one? May need a download link to investigate.
