### ISSUE TITLE
Feature suggestion: Controller multiple bindings to one control

### ISSUE THREAD

**Issue by nolan4327** [OpenEmu/OpenEmu#4600]
I would like the ability to add multiple controller bindings to one function, mainly for consoles that only have a d-pad and/or one trigger button, such as the Gameboy and DS.

For example
- To use either both the d-pad and analog stick; to control movement, menus, etc.
- To use either trigger (for example, L1 and L2, and R1 and R2) for consoles that only have one trigger button.

**Comment by clobber** [comment]
Been asked before, not happening. Would complicate the input system. Instead, use a [proper gamepad](https://github.com/OpenEmu/OpenEmu/wiki#automap-supported-controllers) to play your games.
