### ISSUE TITLE
suggestion - universal cheat

### ISSUE THREAD

**Issue by literquart** [OpenEmu/OpenEmu#4604]
I suggest an enhancement - cheat logic that would work with everything.
Here's how it works:
1. run the game
2. see how many lives you have
3. tell OpenEmu to find all instances of that number in the game's ram
4. lose a life
5. search among previous hits for the new number
6. bingo, you've probably found where it stores number of lives.  Change to 255.

**Comment by clobber** [comment]
Modifications such as peek/poke and other hooks would have to be added to every core plugin, among lots of new API changes. This is not trivial and probably outside the scope of this project.
