### ISSUE TITLE
Dualsense doesn't work wirelessly with 2.3.3 (M1/Monterey Beta)

### ISSUE THREAD

**Issue by nonoche2** [OpenEmu/OpenEmu#4605]
My dualsense controller works normally when connected by USB, it is also seen by OpenEmu when connected by BlueTooth, however when I try to bind the buttons OpenEmu 2.3.3 registers no input whatsoever

**Comment by Masecoby** [comment]
Hi is this with a ps3 dual shock controller?

**Comment by nonoche2** [comment]
no this was with a PS5 dualsense, but I'm happy to report that it was an issue with the beta of Monterey that was fixed with the public release (sorry I forgot to update the report ^^)

**Comment by Masecoby** [comment]
Ok cool glad you solved your problem
