### ISSUE TITLE
Save states losing all progress when exiting full screen

### ISSUE THREAD

**Issue by andrewk666** [OpenEmu/OpenEmu#4610]
If you play a game in OpenEmu, go into full screen mode, then exit whatever way (say you get a notification), states won't autosave... and you lose all progress.

MAJOR BUG!

**Comment by clobber** [comment]
No response. It is assumed your are using OpenEmu 2.3.1 with the state save bug -- an older release -- instead of the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest). We push updates for a reason.

**Comment by andrewk666** [comment]
> No response. It is assumed your are using OpenEmu 2.3.1 with the state save bug -- an older release -- instead of the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest). We push updates for a reason.

2.3.3 actually

**Comment by clobber** [comment]
> 2.3.3 actually

Exact steps to replicate the problem, including example game and system, or nobody can help you.
