### ISSUE TITLE
A few questions, from a fellow user of OpenEmu

### ISSUE THREAD

**Issue by ninonook1** [OpenEmu/OpenEmu#4613]
I have a few questions about open emu

1. will you add multi-player connect to play games on GBA or DS.
2. will you add other cores that allow compatibility for multidisk on other consoles, that being Baten Kaitos (Gamecube) or Penn and teller smoke and mirrors (Sega CD)
3. is there something to show me how to add ports?
4. and most importantly, what are the next updates going to be like? (if there will be)

**Comment by clobber** [comment]
1. Not any time soon, and only if the core plugins have API to do so.
2. No -- multi-disc is already available where supported, with the exception of GameCube/Dolphin. There is no other Sega CD emulator available.
3. No, one does not simply "add" emulators. OpenEmu is not a launcher. Each core plugin is specifically ported with significant changes to "just work" as a core plugin for OpenEmu.
4. Sorry, no. Updates and features are never planned.
