### ISSUE TITLE
Rom identification process

### ISSUE THREAD

**Issue by viniciusccarvalho** [OpenEmu/OpenEmu#4614]
Hi folks, first thank you for this amazing software. OpenEmu is a blessing for mac users.

I have a question on how you guys identify roms if you don't mind sharing. I took a peak under the database and I could figure out how some systems like genesis/snes a file checksum/crc usually identifies the game.

For Sega CD/Saturn I figured you use the header information as described in here: https://plutiedev.com/rom-header

But I can't figure out the serial data for GCN/PSX/PSP/NDS, can you please share the sauce on how to read that data from those files?

Working on a personal rom organizer and could benefit a ton from this info.

Cheers

**Comment by viniciusccarvalho** [comment]
Oh, for future reference, found that I just need to figure out how to read a bin file from those systems. On Psx at least gotta read the System.cnf file and serial is there, still trying to figure out NGC :)

**Comment by clobber** [comment]
> still trying to figure out NGC 

https://github.com/OpenEmu/OpenEmu/blob/cf5606b006abed3f3ab085e046a826635aa0b7ab/OpenEmu/SystemPlugins/GameCube/OEGCSystemController.m#L54

`[Prefix]SystemController.m` files have the code for identification.
