### ISSUE TITLE
I know that there is already a fast forward function that I can use by pressing a button. Is there any way that you can make it faster like 5x or something like that? There are other emulators that are significantly faster.

### ISSUE THREAD

**Issue by MTieche** [OpenEmu/OpenEmu#4617]

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#803
#2632
https://github.com/OpenEmu/OpenEmu/issues?q=fast+forward+speed
