### ISSUE TITLE
Display scaling issue - 

### ISSUE THREAD

**Issue by ramb6** [OpenEmu/OpenEmu#4619]
When on fullscreen mode, the upper area of the game is out of the monitor's viewport. 
<img width="873" alt="Screen Shot 2021-11-06 at 4 42 52 PM" src="https://user-images.githubusercontent.com/49288167/140624699-56e17485-67cb-46f9-a741-dc2f12c85e5c.png">
<img width="696" alt="Screen Shot 2021-11-06 at 4 43 08 PM" src="https://user-images.githubusercontent.com/49288167/140624702-14d63533-83ce-4ce1-a655-20aa993ec6e0.png">

The difference is noticeable. Also maybe worth mentioning this is on a particular computer which recently introduced a notch...

**Comment by stuartcarnie** [comment]
Closed via:

* a711e34cc61881bab10503cb0d90dc29f003e1c6
* 9a94cfdfffa02883ac14daa7f48e86e6de48ebe8
