### ISSUE TITLE
Is the box art server down?

### ISSUE THREAD

**Issue by DestructoDisk** [OpenEmu/OpenEmu#4623]
I am having an issue getting box art. I had the game Lunar on Sega CD installed on OpenEmu, and OpenEmu had automatically installed the box art. 

My son deleted Lunar from OpenEmu by accident. I reinstalled it from the same file, and the game plays fine and even still has my save, but the box art is not there. Right clicking and choosing "download cover art" does nothing. 

So I then started installing new games to test it out, and nothing new I add will download box art. All of my older installed games however still have the box art.

I was wondering if perhaps the connection to wherever box art is downloaded from is broken. Or perhaps when my son deleted Lunar he also messed up some other kind of setting that messed with box art?

Please help, I miss having that beautiful box art :-)

**Comment by clobber** [comment]
This has been resolved. It will take your OpenEmu up to 24 hours to download the new cover art database -- it checks daily for updates on launch.
