### ISSUE TITLE
Super Danganronpa 2 display goes blank

### ISSUE THREAD

**Issue by KurapikaK** [OpenEmu/OpenEmu#4638]
Summary of issue

After a specific point in the game, I can't progress further because the screen goes blank. I exit a room, the scene changes, I encounter characters, and the screen goes black. I still have access to the controls, but I can't apply them to increase my progress in the game since I cannot see the scene, neither can I access in-game locations and talk to characters. All blank. This issue occurred at an earlier point as well, but the difference was that I did not have access to controls either and restarting openemu and loading saved data fixed the issue. 

# Steps to reproduce

1. Boot OpenEmu. 
2. Load saved data. 
3. Interact with characters. 
4. Change scene. 
5. Screen goes blank. 

# Expected Behavior

The expected scene to be displayed with access to in-game locations

# Observed Behavior

Black screen with access to controls but can't apply them to the game

<img width="1440" alt="Screenshot 2021-12-16 at 8 03 25 PM" src="https://user-images.githubusercontent.com/96247148/146391096-f7d3cab1-3f14-41d6-99a5-2a3a8c1955db.png">

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: Monterey 12.0.1

**Comment by clobber** [comment]
This is a PPSSPP emulator bug. Nothing we can do about it until they resolve it.
