### ISSUE TITLE
Wrong name and cover art

### ISSUE THREAD

**Issue by gugulibarata** [OpenEmu/OpenEmu#4639]
OpenEmu erroneously names the rom "Gym des Yeux - Exercer et Relaxer vos Yeux (France) (Demo) (DS Download Station).nds" crc32 25c33150 as "Mazes of Fate DS"

**Comment by GregoireLD** [comment]
There seems to be something special about "Mazes of Fate DS", because as I added an unlicensed demo of "Super Mario Galaxy DS" (which, being unlicensed, has no reason to be recognised at all, that's fine), it also was wrongly identified as "Mazes of Fate DS".

**Comment by J-rg** [comment]
This was fixed in f9ee8e8.
