### ISSUE TITLE
How to change the location of saves files?

### ISSUE THREAD

**Issue by cedricdelpoux** [OpenEmu/OpenEmu#4644]
I would like to change to location of saves files to keep it besides my Game Library on a USB stick.

How can I do that?

Thank you

**Comment by brightredspacejoystick** [comment]
go into 

openemu > preferences…

and on the first tab, you'll see the option to move your library's location.

**Comment by cedricdelpoux** [comment]
Yes I know I can change the library location but the saves files remain in `Library > Application Support > OpenEmu`

**Comment by nickd3000** [comment]
I would like to see this added as a feature, it is possible to create a symbolic link from where OpenEmu saves data in the Library folder to somewhere else, e.g. Dropbox by doing something like this on the command line:
ln -s "/Users/username/Dropbox/Emulaton/OpenEmu/Save States" "/Users/username/Library/Application Support/OpenEmu/Save States"

**Comment by clobber** [comment]
Beyond using symlinks for Save States, this will not be supported. We don't want the syncing problems. In the future, only the "roms" folder will be relocatable and not the entire "Game Library" folder which includes the database as well.
