### ISSUE TITLE
Stopped recognizing keyboard input on MacOS Big Sur 11.6

### ISSUE THREAD

**Issue by brpetrucci** [OpenEmu/OpenEmu#4645]
Hey all. I started using OpenEmu this past weekend and it was working well until a couple days ago. Not sure what exactly changed, but now whenever I open the game (Pokemon Fire Red), the keyboard input is not being recognized. I've tried toggling the input monitoring permission on and off. Quitting and reopening OpenEmu also does not work. The issue solves itself if I reboot, but nothing else seems to solve it and that's obviously not ideal. Any ideas of what could be? This is on OpenEmu v2.3.3.

**Comment by clobber** [comment]
> The issue solves itself if I reboot

Sounds like interference from another application then. We have an updated and detailed guide here: 

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."

**Comment by brpetrucci** [comment]
I tried following that guide and it didn't really work, but i haven't had the problem since the last reboot I guess
