### ISSUE TITLE
Sega Genesis Two players

### ISSUE THREAD

**Issue by jonathaninternet** [OpenEmu/OpenEmu#4648]
I've been trying to get 2 players to work and it just doesn't seem to read the player two input ever on Sega Genesis. Keyboard or controller doesn't matter. When I setup the controller in the settings it reads the controller or keyboard strokes but doesn't in the game. Any ideas? Using on Mac, Catalina OS. Tried on multiple systems give same result. Have tried NHL 94-96 for Genesis. I've got it to work on Street Fighter II on the Genesis but so far that is all, so wondering if this is a known issue or if there is something I could try to get the NHL games to work.

**Comment by clobber** [comment]
>  tried NHL 94-96 for Genesis

Need the MD5 checksums of the ROM files in question. Use this: https://emn178.github.io/online-tools/md5.html

**Comment by jonathaninternet** [comment]
Not sure if this is what you're looking for, I put the file into the input and it gave me:

48c90c1f4e8286d524e860024d4dd0fd

**Comment by jonathaninternet** [comment]
This is what that tool spit out: af8eef242c397cba0b2247bd1574a91f

**Comment by jonathaninternet** [comment]
NHL 94: acc6f6c7417f1af4ed4000bc67248610

NHL 96: 9d7b2fbf98e613a05b70d09cd50a6f99

**Comment by clobber** [comment]
Those three hashes do not match anything in the database. Are these compressed files? ROM hacks? Bad dumps? What are the filenames of the games you dragged and dropped onto that website? If the files are zipped, you should first unzip them and then drag the resulting file onto that website.

**Comment by jonathaninternet** [comment]
I've tried various versions of the ROMS, I don't know if they are compressed (they say .bin) but they won't extract on Mac or Windows. Not sure how to tell if they are hacks or bad dumps but like I said I've tried various versions of the same game. What is the file extension I should have? Seems like all the ones I acquire say .bin and they open fine in emulation but just can't get the 2 controllers to work.

**Comment by clobber** [comment]
To resolve, do yourself this quick favor:

* Delete the current NHL ROMs you have.
* Go to [Archive.org](https://archive.org/) and search for "no-intro genesis"
* Download your NHL games from a "No-Intro" set and use those instead.

You should be using ROMs from a "No-Intro" set for cart-based systems and "Redump" for CD-based systems. These sets are catalogs of known good dumps of the games.

**Comment by jonathaninternet** [comment]
Ok did that, it's a .md file now.
NHL 95: 75ac37d86dcc67a8d184c49f06bc4e0c

No change on the ability to control the 2nd player via keyboard or controller

**Comment by clobber** [comment]
No... `75ac37d86dcc67a8d184c49f06bc4e0c` is not the hash I have or see cataloged for NHL 95. The `.md` file (the uncompressed ROM file itself) should have the hash:

MD5 (NHL 95 (USA, Europe).md) = 94d3518a8e592563c78cf4da84d163c8

Use this site to verify the hash: https://emn178.github.io/online-tools/md5_checksum.html -- I may have linked you to the wrong one, originally.

**Comment by jonathaninternet** [comment]
94d3518a8e592563c78cf4da84d163c8 is what I got with the new site link.

**Comment by clobber** [comment]
Using the same ROM, I cannot get multiplayer to work either. This appears to be the same problem with all "EA 4-Way Play" supported games. I think this may have broken upstream in a previous release. Once I determine the problem, I'll push a fix and reply back here.

**Comment by jonathaninternet** [comment]
Great, thank you for your time and patience.

**Comment by bou5da** [comment]
Was there ever a fix for this? Trying to play Coach K basketball on genesis and nothing but 1 player controller is recognized. Thanks!

**Comment by jonathaninternet** [comment]
I haven't seen a fix unfortunately.

**Comment by clobber** [comment]
This has been fixed. I will notify this ticket when a core update has been released.

**Comment by bou5da** [comment]
Awesome. Thanks so much!

**Comment by bou5da** [comment]
Hello, just checking on a target date for this? Thanks!
