### ISSUE TITLE
nds top screen fail

### ISSUE THREAD

**Issue by nicko444** [OpenEmu/OpenEmu#4649]
Summary of issue
after playing heart gold on the nds the top screen blacked out and wouldnt go away. i downloaded a rom hack of heart gold and the same thing happened a little later in the game. this hasnt happened on any other nds game so far but im not sure if it will if i keep playing.
Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. download heart gold
2. continuously play
3. eventually will blackout

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
#1112

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - 
* "Please search before opening a new issue."
* "NDS games (especially Pokemon) may have unsolvable problems related to AP patches or DeSmuME's JIT dynarec. Alternatively, try standalone DeSmuME that has the JIT dynarec off by default which may improve compatibility."
