### ISSUE TITLE
Official Nintendo GameCube Controller Adapter for Wii U (WUP-028) support

### ISSUE THREAD

**Issue by Numberonekiwi** [OpenEmu/OpenEmu#4652]
I am wondering how to get open emu to recognize this device I have nintendo 64 controller plugged into this adapter. it is recognised in the system report as : 

 WUP-028:

  Product ID:	0x0337
  Vendor ID:	0x057e  (Nintendo Co., Ltd.)
  Version:	1.00
  Serial Number:	15/07/2014
  Speed:	Up to 12 Mb/sec
  Manufacturer:	Nintendo Co., Ltd.
  Location ID:	0x1a112000 / 6
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

**Comment by clobber** [comment]
The Official Nintendo GameCube Controller Adapter for Wii U (WUP-028) is not a HID-compliant device and will not work on macOS without a special driver, and therefore not compatible with OpenEmu. This has been mentioned in previous issues regarding GameCube adapters.

Also this used to be explicitly stated in the [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) guide and has just now been added back.

**Comment by articulatesnail** [comment]
How can I tell if my adapter is not HID-compliant? This is mine:

GameCube For Switch:

  Product ID:	0x0337
  Vendor ID:	0x057e  (Nintendo Co., Ltd.)
  Version:	1.00
  Serial Number:	GH-GC-001 T8
  Speed:	Up to 12 Mb/s
  Manufacturer:	Nintendo
  Location ID:	0x02110000 / 4
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0
