### ISSUE TITLE
PS DualShock4 Controller Color Setting

### ISSUE THREAD

**Issue by oscarguinane** [OpenEmu/OpenEmu#4656]
Is there a way to change the PS4 DualShock controllers' lightbar color setting from OpenEmu or another utility?

Steam allows dimming the bright PS4 controller lightbar but you can't use Steam to change the color and then use OpenEmu because Steam takes over the controller and prevents OpenEmu from using it.

I haven't found another utility that can do this either, not on the Mac AppStore or online, however I did find many controller testing apps.

The reason it's useful is that in low light, I see a bright reflection from the controller.

Of course, I can _totally_ use another controller, like an Xbox controller but I like the PS4 controller and wanted to change the color.

I've reposted this from Reddit [here](https://www.reddit.com/r/OpenEmu/comments/sepx42/ps_dualshock4_controller_color_setting/) because the question was closed by moderation...

**Comment by clobber** [comment]
No way to do this from within OpenEmu.

**Comment by oscarguinane** [comment]
Ok but wait, should there be a way?
