### ISSUE TITLE
OpenEmu MAME

### ISSUE THREAD

**Issue by ninonook1** [OpenEmu/OpenEmu#4658]
so I've been having some problems, some of them I have solved, but there has been one which has been killing me for a while.

"These ROMs must be from a MAME 0.235 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files."

I have the 0.235 name romset, but I'm still unsure of what to do. could I be clarified or explained what I'm supposed to do to fix this problem? thank you.

**Comment by clobber** [comment]
That message is clear. The game or some associated file is not from the correct ROM set. Cannot help you since you have not provided details as to which file(s) throw the error.

**Comment by ninonook1** [comment]
"Super Street Fighter II Turbo (USA 940323) (ssf2tu.zip) requires:


These ROMs must be from a MAME 0.235 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files."

does this help?

**Comment by clobber** [comment]
No. In that dialog should be a list of missing required files, possibly a parent ROM such as this:

<img width="372" alt="Screen Shot 2022-01-28 at 10 58 45 PM" src="https://user-images.githubusercontent.com/1303132/151649610-84933ca2-3baa-44e4-a5ae-0632ea22d9c0.png">

**Comment by ninonook1** [comment]
![Screen Shot 2022-01-29 at 9 08 36 AM](https://user-images.githubusercontent.com/50481076/151670232-88656861-489c-486d-aa3e-e6325ffdd60a.png)
well even if I get that romset, am I supposed to drag and drop it into openemu, or am I supposed to go into the application support folder and do something in there?

**Comment by clobber** [comment]
Send me a link to where I can download the exact file you trying. I need to know why it is not listing the required files.

**Comment by ninonook1** [comment]
[ssf2tu.zip](https://github.com/OpenEmu/OpenEmu/files/7964642/ssf2tu.zip)

**Comment by clobber** [comment]
I checked it out. That is not `ssf2tu`, that is a zip of `ssf2t` that somebody **renamed** to `ssf2tu` and also stuffed a `qsound.bin` in there. So no wonder MAME won't load it. If you want the USA version, then this is not the correct set.

Go to Archive.org and find a recent **NON-MERGED** MAME ROM set (0.224 will work fine). OpenEmu's core port of MAME does not yet fully support **MERGED** sets of MAME ROMs unless you want it to simply load the parent ROM of the set. You want to import the following files in OpenEmu:

* qsound_hle.zip (this is a required dependency for all Capcom CPS-2 arcade games)
* ssf2t.zip (this is the main "parent" ROM to "Super Street Fighter II Turbo" series)
* ssf2tu.zip (this is "clone" ROM required for the USA version)

Doing so will allow you to play the "USA" version of Super Street Fighter II Turbo if that is your intention.

**Comment by ninonook1** [comment]
there are no non-merged MAME versions of 0.224 that given, there are romsets over 100Gigs big, way over the limit of what my mac can hold if not handle, that given, as I've said, I have no idea where to put the romset, do I drag or drop it? do I go into the Openemu MAME file in application support and put it there?

with that aside, the sound I got, and I went and used just got the regular ssf2t instead of ssf2tu since for me, the end result will be the same. but the clone part... I have no idea what I'm supposed to do there, am I supposed to get a copy, if where do I put it, I can't put it in with the same folder since I can't have two items with the same name... so what am I suppose to do?

**Comment by clobber** [comment]
>there are no non-merged MAME versions of 0.224

A "split" set for version 0.224 is available. It is called "mame0.224". Forgot about "non-merged" for a moment.

> there are romsets over 100Gigs big

Yes, that is why it's called a "set". You do not need to download the entire ROM set. Read the webpage. Under "Download Options" you can select "Show all" and view the contents of the entire archive or folder, depending on how it was uploaded. Anyway, I'm not in the business of walking you through how to navigate Archive.org.

> do I drag or drop it?

Yes, that is what is meant by "...import the following files in OpenEmu"

### Anyway, to play "Super Street Fighter II Turbo", here are the options:

1. From a **SPLIT** set, import the following if you want the "USA" version:
* qsound_hle.zip
* ssf2t.zip
* ssf2tu.zip

2. From a **SPLIT** set, import the following if you want the "World" version:
* qsound_hle.zip
* ssf2t.zip

3. From a **NON-MERGED** set, you only need to import ssf2t.zip or ssf2tu.zip, depending if you care which region (World or USA).

I suggest reading this helpful [MAME ROMs tutorial](https://choccyhobnob.com/demystifying-mame-roms/) to better understand how the sets work.

**Comment by ninonook1** [comment]
alright i have gotten to the point of

"ssf2t.zip  	- INCORRECT SET

These ROMs must be from a MAME 0.235 ROM set. Some of these files can be parent/device/BIOS ROMs, which are not part of the game, but are still required. Delete files already imported and reimport with correct files."

and all of the romsets are way to big for my computer to handle, that's including the non-merged, I tried getting more experienced with this video https://www.youtube.com/watch?v=5OUR8VPVIHM and with what you sent me, both has only gotten me so far, that included my goal is to get the world version because it doesn't require me getting more than I need to. is there an option for where there romsets that are under almost 1 gigabyte

**Comment by clobber** [comment]
It's clear you're not reading what I've told you. I cannot help you beyond this.
