### ISSUE TITLE
Xbox Elite Wireless Controller - macOS Monterrey

### ISSUE THREAD

**Issue by oscarhgriffin** [OpenEmu/OpenEmu#4659]
Hello,

OpenEmu working beautifully on my M1 MBP, but it's not recognizing my Xbox Elite controller. Is there an available driver to make it compatible? I tried the existing xbox 360 driver but it wouldn't not install. Any help would be very much appreciated. 

Thank you,
Oscar

**Comment by CatGreen90** [comment]
Monterey has known issues with both Bluetooth and HID gamepads:
https://developer.apple.com/forums/thread/694146
https://github.com/libsdl-org/SDL/issues/4923

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/OpenEmu/issues?q=elite
