### ISSUE TITLE
Feature Request - Save State folder relocating

### ISSUE THREAD

**Issue by nickd3000** [OpenEmu/OpenEmu#4665]
Requesting the option to specify the Save State folder location via the settings panel.
This would allow users to store save states on the cloud to share between multiple computers.

**Comment by clobber** [comment]
We don't want the syncing issues, so doing this at one's own risk and will not be supported via OpenEmu. You can use symlinks, as you are aware. Further thoughts and discussion:

https://github.com/OpenEmu/OpenEmu/issues?q=symlink
