### ISSUE TITLE
Black Screen -Pokemon Heart Gold, Soul Silver

### ISSUE THREAD

**Issue by DelYanamme** [OpenEmu/OpenEmu#4671]
After playing for a while I decided to stop playing Pokemon Heart gold and i close out the tab, then i join back in to play some more and the upper screen is completely black i tried managing into going into another room and its still black i saved the game file and reset the game and the screen was back to normal then i load again the previous game and its black again i don't know if its a game issue as in the save file is already broken or if there even is a way to fix it

<img width="1280" alt="Screen Shot-Heart Gold" src="https://user-images.githubusercontent.com/100885621/156894719-f37a958e-c212-4a9c-a512-1f0e99e07807.png">

**Comment by jvondoom** [comment]
I can confirm this happening, using an Intel-based Mac Pro with osX v12.3 and OpenEmu v2.3.3

 A way to fix it is to save the game and restart it.

I have also got some errors with the sprites in the main map. After battle, they fail to load properly.
<img width="777" alt="Screenshot 2022-03-20 at 14 48 39" src="https://user-images.githubusercontent.com/14113078/159185422-3ab0a032-f4d1-4582-bee4-11a90783b09c.png">

**Comment by clobber** [comment]
#1112

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - 
* "Please search before opening a new issue."
* "NDS games (especially Pokemon) may have unsolvable problems related to AP patches or DeSmuME's JIT dynarec. Alternatively, try standalone DeSmuME that has the JIT dynarec off by default which may improve compatibility."
