### ISSUE TITLE
How to change Mednafen config?

### ISSUE THREAD

**Issue by cedricdelpoux** [OpenEmu/OpenEmu#4674]
I need to make some change to the **Mednafen** config.
I created a `mednafen.cfg` file juste under `Application Support/OpenEmu/Mednafen`.

```
;Format string for save games filename.
filesys.fname_sav %f
```
But the config file does not seems to be handled by **OpenEmu**.

I used [this gist](https://gist.github.com/iamgreaser/1478983) as inspiration for the file format.
The Mednafen config documentation is [here](https://mednafen.github.io/documentation/#Section_config_files).

**Mupen64Plus** has a `mupen64plus.cfg` config file,  **Dolphin** has a `Dolphin.ini` so why not **Mednafen**

Thanks

**Comment by clobber** [comment]
> But the config file does not seems to be handled by OpenEmu.

Correct, and it won't be. OpenEmu is not a launcher. Mednafen's config file as well as the others are best suited for the standalone emulators. You would have to recompile OpenEmu's Mednafen core port with the option you wanted. Sorry, will not walk you through this.

Settings here: https://github.com/OpenEmu/Mednafen-Core/blob/417cc0d01ed7f96957ce32462fee6d37eba35018/MednafenGameCore.mm#L105
