### ISSUE TITLE
Zip files on Apple Arm Big Sur

### ISSUE THREAD

**Issue by Elatarisi** [OpenEmu/OpenEmu#4676]
On my intel catalina macbook I can import roms in zip files but appearently I can't do that on m1 big sur. Is this a bug or is it this way from now on.

Both 2.3.3 versions

**Comment by digamejh** [comment]
What kind of roms?

I know MAME (arcade) games are traditionally distributed as zip files, but I imported all of mine to my M1 last week and they play without problems.  I'll try adding something new tonight.

**Comment by Elatarisi** [comment]
The rom's I was trying to add was broken sorry. Found a fresh pack and I'm good to go.
