### ISSUE TITLE
Current compiled version: no keyboard inputs possible?!

### ISSUE THREAD

**Issue by gktonic** [OpenEmu/OpenEmu#4685]
MacOS Monterey 12.3.1, MacBook Air M1, Xcode 13.3

I compiled with `xcodebuild -workspace OpenEmu.xcworkspace -scheme "OpenEmu + Cores (Experimental, Alpha)" -configuration Release` and moved "OpenEmu" (from DerivedData) to my Applications Folder. OpenEmu suggests the steps to do in order for my keyboard to work, but unlike the official experimental release from the website, the keyboard won't work with this version at all (Rosetta enabled) and the warning will pop up every time i open it. 

Anything i have to pay attention to before compiling? The new shaders/extra settings are just too good.. (thanks for the work on that!!)

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/issues/4632#issuecomment-1097290608

**Comment by gktonic** [comment]
Yes, this definitively works with the current official release (on my mac), but not with my compiled version. I just wanted to know if i missed something

**Comment by clobber** [comment]
This has nothing to do with us. "Security" in macOS will treat a new compiled build as an "untrusted" app therefore requiring you to run through all the steps again to allow input. Cannot help you beyond that.

**Comment by gktonic** [comment]
Alight. Thank you for your fast reply
