### ISSUE TITLE
Can we get cheats for the PSX integrated into the application?

### ISSUE THREAD

**Issue by rhartness** [OpenEmu/OpenEmu#4688]
Mednafen has allowed for PSX codes since 2019 (if I'm understanding the related Github changes to the project correctly.)  Can we get GameShark code integration into the application?

**Comment by clobber** [comment]
> if I'm understanding the related Github changes to the project correctly.

You're not. Our Mednafen core plugin has never had cheat support. It is not an easy matter and will be added when it is easier to do so.

https://github.com/OpenEmu/OpenEmu/issues/2310#issuecomment-168331976
