### ISSUE TITLE
Feature request: Add Phoenix core for 3DO

### ISSUE THREAD

**Issue by Laguna794** [OpenEmu/OpenEmu#4690]
http://www.arts-union.ru/node/23
It's considered the best 3DO core on Mac and it'd be cool to see it added to OpenEmu. 3DO has quite a few interesting titles like Doctor Hauzer and Lucienne's Quest, as well as the CD version of SSFFIIT. This core apparently supports all of the library.

**Comment by clobber** [comment]
- Yes, we are aware of this emulator.

- It's closed source. That means your request is impossible.
