### ISSUE TITLE
Keyboard input has stopped working (Mac)

### ISSUE THREAD

**Issue by jawdone** [OpenEmu/OpenEmu#4701]
Recently, after months of using OpenEmu, the keyboard input has ceased working. I've obviously allowed input monitoring while using other apps in security and privacy, have tried toggling that option on and off repeatedly, restarting my mac, deleting and redownloading openemu, opening the terminal and allowing input monitoring on that, downloading desmume, but nothing seems to work. This issue seems to have started after PRAM and SMC resetting my mac due to a mouse issue. Does anyone know if this is related/ if there's anything I can do to work around this issue? Many thanks in advance 
![Screenshot 2022-05-20 at 16 40 56](https://user-images.githubusercontent.com/105936135/169563662-dbd7288f-4046-4a90-9f1c-98506ebbb093.png)
!

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Read: https://github.com/OpenEmu/OpenEmu/issues/4632#issuecomment-1097290608
