### ISSUE TITLE
Wiimote won't pair to OpenEMU on MacOS Monterey

### ISSUE THREAD

**Issue by skooter407** [OpenEmu/OpenEmu#4705]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little2. 

Trying to open any NES game in the OpenEMU system causes it to crash when I have a wiimote paired to bluetooth. When I disconnect the wiimote  and open OpenEMU and load any NES game it loads fine. if I then pair my wiimote the software quits unexpectedly every time along with a very long vibration in my Wiimote. I am running MacOS Monterey latest version as well as latest version of Open EMU. 
# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4612
