### ISSUE TITLE
My screen after loading a existing saved file goes black?

### ISSUE THREAD

**Issue by davyjones14** [OpenEmu/OpenEmu#4706]
Playing soulsilver pokemon, I noticed my character was glitching out. I saved shortly after that and now when I load that saved file, my screen goes black. I got a Mac with macOS Monterey 12.3.1. Is there better software I can update or settings I need to change to avoid this?

**Comment by clobber** [comment]
#1112

[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - 
* "Please search before opening a new issue."
* "NDS games (especially Pokemon) may have unsolvable problems related to AP patches or DeSmuME's JIT dynarec. Alternatively, try standalone DeSmuME that has the JIT dynarec off by default which may improve compatibility."
