### ISSUE TITLE
Nimbus+: Two specific buttons cause OESystemBindings error

### ISSUE THREAD

**Issue by stevenjamescox** [OpenEmu/OpenEmu#4709]
### Summary
I added the Nimbus+ controller to my local Controller-Database.plist _and_ added the additional buttons.
Two of the four additional buttons work properly (L3 and R3)
**The other two cause an OESystemBindings error** -- buttons "Menu" and "Options"

### Controller Information

The Nimbus+ is an MFi controller that connects via Bluetooth.
It's essentially an upgraded version of the Nimbus. It has four additional buttons:

- Left analog stick button (L3)
- Right analog stick button (R3)
- "Menu" button (button 4 in picture)
- "Options" button (button 2 in picture)

Placement of Menu and Options buttons:

![Screen Shot 2022-06-01 at 1 08 45 PM](https://user-images.githubusercontent.com/17806659/171511320-22a2212b-c73d-4ae6-8670-c036c55884c5.png)

Here's how I have it set up in Controller-Database.plist:

![Screen Shot 2022-06-01 at 3 17 09 PM](https://user-images.githubusercontent.com/17806659/171511435-7a2ca3c3-8415-4c28-8977-7e9d6ae5f413.png)

In HID Browser, I tracked the events from the following four buttons

- A (Button 1 - `0x0001` decimal 1)
- Home (AC Home - `0x0223` decimal 547)
- Menu (AC Properties - `0x0209` decimal 521) and 
- Options (AC Exit - `0x0204` decimal 516)

To compare A & Home with Menu & Options, to see if the latter put out anything weird, and they didn't:

![Screen Shot 2022-06-01 at 2 18 34 AM](https://user-images.githubusercontent.com/17806659/171511371-82f9527f-221d-4b54-a5d7-e017eabff0cb.png)

Here's the full _device_ plist from HID Browser: 
[Nimbus+.plist.zip](https://github.com/OpenEmu/OpenEmu/files/8819887/Nimbus%2B.plist.zip)

## Scenario 1 -- **unaltered** plist

**Conditions:** Use original Controllers-Database.plist with no entry for this controller.

**Result:** ALL buttons are custom-mappable without any problem. Xcode console output when the Menu and Options buttons are pressed:
```
OpenEmu [hid] <OEHIDEvent 0x60000229a0d0 pad=0x600002fea300 type=Button number=521 state=On 'Button 521' cookie=19>
OpenEmu [hid] <OEHIDEvent 0x60000228c410 pad=0x600002fea300 type=Button number=521 state=Off 'Button 521' cookie=19>
OpenEmu [hid] <OEHIDEvent 0x6000022f15e0 pad=0x600002fea300 type=Button number=516 state=On 'Button 516' cookie=20>
OpenEmu [hid] <OEHIDEvent 0x6000022f3020 pad=0x600002fea300 type=Button number=516 state=Off 'Button 516' cookie=20>
```

## Scenario 2 -- controller and all four buttons in plist

**Conditions:** Used the way above pictured version of the Controllers-Database.plist with **ALL FOUR** additional buttons added.

**Result:** Xcode console just after application start:
```
OpenEmu Found Device 0x7f9ac471d2e0: Nimbus+
OpenEmu Could not find element for control of type: Button, cookie: (null), usage: 516
OpenEmu Could not find element for control of type: Button, cookie: (null), usage: 521
```
Then, when mapping the controller in Edit Control Options, all buttons work EXCEPT Menu (521) and Options (516). When either of those two buttons are pressed, the Xcode console outputs:

`*** Assertion failure in -[OESystemBindings OE_playerBindings:didSetDeviceEvent:forKey:], OESystemBindings.m:687`

The application doesn't crash, it just stops because I'm running with an attached Xcode console.
When I allow the application to continue running, the console puts out more:

```OpenEmu [General] Controller type 'OEControllerGCExtendedGamepadProfile' does not recognize the event '<OEHIDEvent 0x60000017e5d0 pad=0x600000c91e00 type=Button number=521 state=On 'Button 521' cookie=19>', when attempting to set the key with name: 'OENESButtonStart'```

and

```
OpenEmu [General] (
	0   CoreFoundation                      0x00007ff817f377b3 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff817c97bc3 objc_exception_throw + 48
	2   Foundation                          0x00007ff818de9d13 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 267
	3   OpenEmuSystem                       0x0000000109a3dde3 -[OESystemBindings OE_playerBindings:didSetDeviceEvent:forKey:] + 1267
	4   OpenEmuSystem                       0x0000000109a3c984 -[OESystemBindings OE_playerBindings:didAssignEvent:toKeyWithName:] + 420
	5   OpenEmuSystem                       0x0000000109a444d8 -[OEPlayerBindings assignEvent:toKeyWithName:] + 152
	6   OpenEmu                             0x0000000108df7e83 $s7OpenEmu22PrefControlsControllerC8register33_121800E00F8166A12BC04D22D058F873LLyySo10OEHIDEventCF + 803
	7   OpenEmu                             0x0000000108df2616 $s7OpenEmu22PrefControlsControllerC21registerEventIfNeeded33_121800E00F8166A12BC04D22D058F873LLyySo10OEHIDEventCF + 86
	8   OpenEmu                             0x0000000108df25b1 $s7OpenEmu22PrefControlsControllerC17setUpEventMonitor33_121800E00F8166A12BC04D22D058F873LLyyFSbSo15OEDeviceHandlerC_So10OEHIDEventCtcfU_ + 65
	9   OpenEmu                             0x0000000108df267c $sSo15OEDeviceHandlerCSo10OEHIDEventCSbIegggd_AbD10ObjectiveC8ObjCBoolVIeyByyd_TR + 76
	10  OpenEmuSystem                       0x0000000109a46687 -[OEDeviceManager deviceHandler:didReceiveEvent:] + 423
	11  OpenEmuSystem                       0x0000000109a4c2d2 -[OEHIDDeviceHandler dispatchEvent:] + 450
	12  OpenEmuSystem                       0x0000000109a4c40f -[OEHIDDeviceHandler dispatchEventWithHIDValue:] + 175
	13  OpenEmuSystem                       0x0000000109a4d45c OEHandle_InputValueCallback + 44
	14  IOKit                               0x00007ff81a7e51f8 __IOHIDDeviceInputElementValueCallback + 211
	15  CoreFoundation                      0x00007ff817ebd7ce __CFDictionaryApplyFunction_block_invoke + 22
	16  CoreFoundation                      0x00007ff817e865d3 CFBasicHashApply + 115
	17  CoreFoundation                      0x00007ff817e792fb CFDictionaryApplyFunction + 131
	18  IOKit                               0x00007ff81a7e9560 __IOHIDQueueValueAvailableCallback + 70
	19  IOHIDLib                            0x000000012ea66e2a _ZN13IOHIDIUnknown14genericReleaseEPv + 3466
	20  CoreFoundation                      0x00007ff817ee9566 __CFMachPortPerform + 288
	21  CoreFoundation                      0x00007ff817ebc944 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	22  CoreFoundation                      0x00007ff817ebc824 __CFRunLoopDoSource1 + 619
	23  CoreFoundation                      0x00007ff817ebae8b __CFRunLoopRun + 2415
	24  CoreFoundation                      0x00007ff817eb9e5c CFRunLoopRunSpecific + 562
	25  HIToolbox                           0x00007ff820b615e6 RunCurrentEventLoopInMode + 292
	26  HIToolbox                           0x00007ff820b6134a ReceiveNextEventCommon + 594
	27  HIToolbox                           0x00007ff820b610e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	28  AppKit                              0x00007ff81a8f91fd _DPSNextEvent + 927
	29  AppKit                              0x00007ff81a8f78ba -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	30  AppKit                              0x00007ff81a8e9f69 -[NSApplication run] + 586
	31  AppKit                              0x00007ff81a8bdee7 NSApplicationMain + 817
	32  OpenEmu                             0x0000000108e63f29 main + 9
	33  dyld                                0x000000011310d51e start + 462
)
```

At this point the application is running fine, but the Menu or Options button I've just tried to map isn't in the mapping list. I can keep mapping, and all buttons except for those two will work. The two problematic buttons will always give me the `Assertion failure` console error.

## Scenario 3 -- controller in plist, but NONE of the four new buttons in plist

**Conditions:** Controller is in the plist as in photo way above, but I've remove the four new button entries in the OEControllerMappings section.

**Result:** Xcode console just after application start:
```
OpenEmuHelperApp Found Device 0x7fa15ea05b20: Nimbus+
OpenEmuHelperApp WARNING: There are 2 button elements unaccounted for in MFi Extended Gamepad Profile.
```
**Only TWO button elements unaccounted for, not FOUR.** (Scenario 4 seems to reveal that the two detected and unaccounted button elements it was referring to were L3 and R3.)

And then when I attempt to custom map **any** of the **four** new buttons inside the application, I again get:
`*** Assertion failure in -[OESystemBindings OE_playerBindings:didSetDeviceEvent:forKey:], OESystemBindings.m:687`
All other buttons can be custom mapped, just not those four.

## Scenario 4 -- controller in plist, but only two new buttons in plist, L3 and R3

**Conditions:** Controller is in the plist as in photo way above, but I've remove the four new button entries in the OEControllerMappings section.

**Result:** Xcode console just after application start:
```
OpenEmuHelperApp Found Device 0x7fa15ea05b20: Nimbus+
```
**No mention of unaccounted for button elements** despite the lack of the Menu and Options buttons in this version of the plist.

And then when I attempt to custom map either the Menu or Options button inside the application, I get again get:
`*** Assertion failure in -[OESystemBindings OE_playerBindings:didSetDeviceEvent:forKey:], OESystemBindings.m:687` and the other console messages mentioned at the end of Scenario 2. All other buttons can be custom mapped, just not Menu or Options.
So overall identical result to Scenario 2.

## Other notes

- These scenarios had same results regardless of whether there was a file in ~/Library/Application Support/OpenEmu/Bindings/

- These scenarios had the same results when I tried giving the SteelSeries Nimbus+ its own separate profile in the Controllers-Database.plist rather than having it as one of several `OEControllerGCExtendedGamepadProfile` entries.

- These scenarios had the same results regardless of whether the `DisableCalibration` parameter for the `MFi Extended Gamepad Profile` set of controllers was set to 0, 1, or omitted entirely.

- Manually adding the two buttons' cookie numbers into the plist didn't change the results.

- Whether or not Input Permissions were enabled didn't change the results.

- The obvious solution, I know, is "Well then don't have this controller in your Controller-Database.plist, silly." Clearly that'll work just fine for me. But if it can be learned why this is happening, it may help prevent future controller issues for many users. Maybe the way this controller is interacting with the operating system is going to be become more common. Who knows.

- I dug though a bunch of binding-handling code in this project in Xcode but don't have anywhere near the expertise necessary to make sense of precisely what's going on.

- The only related issue I could find is #3994. Different scenario but same error message. @shysaur was able to update the application to handle the way Catalina was interacting with the N64 controller discussed.

## Theory 1
I'm adding them incorrectly. While I'm certain I have their `usage` numbers correct, maybe they're a special `type`.
HIDBrowser.app show them to be the same sort of button that the Home button is, with a `0x000c` prefix before the individual button code. Is the Home button currently handled in a particularly different way than other buttons?

## Theory 2
These two particular buttons are "new" or weird and are thus not able to be handled correctly by the application when configured in Controller-Database.plist. Maybe these buttons even deviate from HID standards/norms.

### Debugging Information
- OpenEmu Version: Same results with 2.3.3 and with a GitHub pull from about 24 hours ago.
- macOS Version: Tried both 2.3.3 and recent GitHub pull on Monterey 12.4, also tried just 2.3.3 on Big Sur 11.6.6 and Mojave 10.14.6. Same results.

**Comment by clobber** [comment]
I believe `AC Exit` and `AC Properties` need to be added to the input system in order for them to be recognized when using the database. See commit here for the general idea: https://github.com/OpenEmu/OpenEmu-SDK/commit/2531e9d7aa5493a5445d6f8a0dd957cf926d0eb3

**Comment by stevenjamescox** [comment]
Fantastic! Thank you for pointing me in the right direction. I'll study that commit of yours and its context and see if I can integrate `AC Exit` and `AC Properties` into the input system.

**Comment by stevenjamescox** [comment]
Holy crap. You rock, @clobber. Thank you for showing me right where to go.
I only had to add two lines to `OEHIDDDeviceParser.m`:
```
 case kHIDUsage_Csmr_ACExit :
 case kHIDUsage_Csmr_ACProperties :
```
And now it works perfectly.
