### ISSUE TITLE
GBA ROM WHITE SCREEN

### ISSUE THREAD

**Issue by Samucar07** [OpenEmu/OpenEmu#4710]
i try to start a rom but a white screen appear and nothing appen instead with another rom evrything work normally

- OpenEmu Version: 2.3.3
- macOS Version: Monterey 12.4

**Comment by clobber** [comment]
And you didn't think it'd be important to tell us which ROM?

**Comment by Samucar07** [comment]
sorry, i'm really sorry is pkmn perfect emerald (italian version) you can find with the name "pokemon smeraldo perfetto"
i found a "solution": options-----> emulator-----> save type--->flash 128K, but i don't know how to fix in open emu, again sorry clobber i hope u don't hate me

**Comment by clobber** [comment]
Use standalone [mGBA](https://mgba.io/) for this feature. We cannot accommodate for every badly coded pokemon ROM hack.
