### ISSUE TITLE
Use of undeclared identifier 'OEBIOSFile'

### ISSUE THREAD

**Issue by beeselmane** [OpenEmu/OpenEmu#4711]
When attempting to build from source on the latest commit (dff4666559f2ad6de44d29aeecc19448f0dbb3bb), I'm getting a compiler error on line 673 of the file `OEImportOperation.m`. Searching for this class, I can't seem to find it anywhere in the workspace. I've checked out submodules properly and all, so that shouldn't be the issue.

# Steps to reproduce

1. Clone recursive repository
2. Attempt to build either in Xcode or on the command line (default target, OpenEmu)

# Expected Behavior

1. The project builds successfully with no issues

# Observed Behavior

1. There is a build error

# Debugging Information

- OpenEmu Version: Latest commit
- macOS Version: 12.2 (M1 mbp)
- Note that I've tried this on a clean clone as well as my old version of the repo.

**Comment by stevenjamescox** [comment]
I was having the same issue. To get it to build for me, I reverted lines 38 through 43/45 of BIOSFIle.swift to how it is on the left side of this pull request code comparison: https://github.com/OpenEmu/OpenEmu/commit/db99c87e3dc153a80a0eac579bf49d13ae36fd0a

I attempted to fix it _properly_ by changing the `OEBIOSFile` reference on line 673 of `OEImportOperation.m` to refer to the `BIOSFile` enum on the _right_ side of the pull request comparison, but couldn't figure it out. I'm not familiar enough with how to refer to Swift objects in Objective-C.

**Comment by beeselmane** [comment]
@stevenjamescox Interesting, I'm not sure why this PR was merged without fixing it up. There's no way to interface with a Swift enum in Objective-C that doesn't have an underlying integer type, so I'm not sure these two places are compatible, or why the change was made. I suppose I'll simply partially revert the PR you linked on my end as well; hopefully someone with better knowledge of OpenEmu in specific sees this issues and decides how they want to implement a real fix (this is the only reference to `OEBIOSFile` left in the project, it seems.
