### ISSUE TITLE
How do I play with my old save

### ISSUE THREAD

**Issue by SheriffRabbit** [OpenEmu/OpenEmu#4721]
When I was young, I played GBC games on other devices, and saved the progress file with the built-in function of the game. The suffix is.sav. I want to continue my progress on the simulator, what should I do

**Comment by clobber** [comment]
You can pretty much use the guide below to infer out how to copy your in-game battery save files over to the folder that Gambatte needs to see them in:

https://github.com/OpenEmu/OpenEmu/wiki/User-Guide:-Transfer-Save-Files

They would obviously go in `‎⁨~/Library⁩/Application Support⁩/OpenEmu⁩/Gambatte⁩/Battery Saves⁩` and be named `Your_ROM_Filename.sav`
