### ISSUE TITLE
Files Failed to import

### ISSUE THREAD

**Issue by FlorenciaC204** [OpenEmu/OpenEmu#4727]
Hi, today I download OpenEmu and I spend like 2 hours trying to download Legend of Spyro a New Beginning in .iso format (by archive.org), I saw a lot of videos when the app give me the notification that something was wrong and no matter what I try nothing works. Thinking something was wrong I tried of download the game again but in another page (emuparadise.me) but I have no clue why the page didn't let me download the game although I try in two different lenguaje.

Now that I decided I need help I'm here. I need help to make the game work.

This are another facts you need to know:

- OpenEmu Version: 10.14.4
- macOS Version: Monterey 12.4

Thanks for the time, I wish this problem can be resolve.

**Comment by clobber** [comment]
Uh, where does it say that OpenEmu supports PlayStation 2 games?

It does not.
