### ISSUE TITLE
Change default core

### ISSUE THREAD

**Issue by BlankDolphin** [OpenEmu/OpenEmu#4729]
I have checked the forum and it says that I can just right-click the console on the console library section on the right to change the core but it doesn't come up all it comes up with is "Hide". (I am using a Wii plugin and I want to know how to select dolphin as the default core for the Wii console)
Thanks

**Comment by d-sparil** [comment]
If there's no choice of core, Default Core doesn't come up as an option when right clicking on the console name.

**Comment by clobber** [comment]
There is no supported Wii plugin available from us. Our Dolphin core plugin only supports GameCube.
