### ISSUE TITLE
bin files import

### ISSUE THREAD

**Issue by rafsimo** [OpenEmu/OpenEmu#4731]
Hi, I see that I'm supposed to use the Import Issue Resolver (bottom left corner of the Library window) to manually select the correct system to import .bin files, but I don't see anything like Import Issue Resolver in the bottom left. Where do I find it?
![image](https://user-images.githubusercontent.com/76566135/177216428-643ea35c-33ee-4876-9d6b-bd9e3b34dc4b.png)
Thanks a lot

**Comment by clobber** [comment]
From your screenshot it looks like you are wanting to import games for PlayStation. You are misunderstanding how CD-based games needed to be imported, so see the guide: https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games#importing
