### ISSUE TITLE
controller preferences not working

### ISSUE THREAD

**Issue by GEN-Z-RETRO** [OpenEmu/OpenEmu#4732]
I have been using openemu for quite a while now but for a few days now I have been facing issues regarding changing my controller layout for games, whether by keyboard or my ps4 controller. this issue is very prominent in GameCube games whose controls have become unresponsive. due to which it has become impossible for me to play retro games on openemu.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Read: https://github.com/OpenEmu/OpenEmu/issues/4632#issuecomment-1097290608

Also:
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "If keyboard and/or gamepad are not working, read the guide on [input troubleshooting](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for a solution."
