### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Agusum** [OpenEmu/OpenEmu#4734]
Hi, thank you for the amazing work you're doing with this frontend emulator. It's been a while since the last release but they've been many commits in the last year and a half so I was wondering if you could bundle them into a release so that we could get all the benefits, including the updated cores.

Thanks!

**Comment by clobber** [comment]
Core updates are automated and not tied to a release. There is a lot of work happening on the application and thus there are no plans for a new release at the moment. Your current version of OpenEmu hasn't stopped playing games.
