### ISSUE TITLE
Updating cores

### ISSUE THREAD

**Issue by Agusum** [OpenEmu/OpenEmu#4735]
Hi, sorry for opening a new question but the [previous one](https://github.com/OpenEmu/OpenEmu/issues/4734) got closed after the response so I didn't have the option to reply back there.

You mentioned that the cores are updated automatically and not tied to a release, however, when I check my cores I see that they are very outdated. For example, the latest release of mGBA is on v0.9.3 right now and OpenEmu only has 0.8.4.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/4369698/178252549-83e7a68a-dc6a-4480-88a2-8b22ced167d8.png">

**Comment by clobber** [comment]
Again, core updates are not tied to OpenEmu releases. The [mGBA core plugin](https://github.com/OpenEmu/mGBA-Core/commits/master) just hasn't had a new release pushed yet. I'm not sure what about that makes you think it's tied to OpenEmu releases. Stop asking about this and wasting peoples time.
