### ISSUE TITLE
No game sound

### ISSUE THREAD

**Issue by thaipokecard** [OpenEmu/OpenEmu#4738]
Summary of issue

When I first played the game (Pokemon Fire Red in Game Boy Advance), I can hear the game sound. I played for about 2 hours and closed openemu. The next day I opened the game again but there was no sound. I decided to try another game in another console. I opened Pokemon Yellow in Game Boy but there was no sound. I opened Pokemon Diamond in Nintendo DS and the sound comes back. I closed Pokemon Diamond and opened Pokemon Fire Red again. I could hear the game sound again. Today, I tried to open any games in any consoles but there were no sound. The game can still be played normally but there is no audio. I opened other apps or YouTube and can hear the sound without problem.

# Steps to reproduce

1. Open openemu.
2. Click the game under Game Boy Advance tab.

# Expected Behavior

I should be able to hear game sound while playing.

# Observed Behavior

The game can be played normally but no sound is heard.

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 12.4
- MacBook Pro M1 2020

**Comment by clobber** [comment]
You have not provided details about your audio configuration. Your problem is almost certainly something that has already been covered, so check here: 

https://github.com/OpenEmu/OpenEmu/issues?q=bluetooth+audio

https://github.com/OpenEmu/OpenEmu/issues?q=no+sound
