### ISSUE TITLE
Open bug, refuses to open

### ISSUE THREAD

**Issue by Lynx6666** [OpenEmu/OpenEmu#4744]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
2. I downloaded it 
3. download some games
4. play some of the games
5. close it for the day
6. get back on it the next day 
7. try to open openemu
8. nothing happens
9. try to click the reopen button
10. nothing happens again
11. Click the reopen button enough times, it refuses to open after that

# Expected Behavior

1. Openemu opens
1. I see my games
1. I can play the games that I have on there

# Observed Behavior

1. Openemu tries to open
1. doesn't open but says it "quit unexpectedly" 
1. I click reopen and the same thing pops up
<img width="467" alt="Screen Shot 2022-07-29 at 10 02 04 AM" src="https://user-images.githubusercontent.com/110202388/181778756-e66f64b3-aadf-490a-a2fd-ae2dae90a830.png">

# Debugging Information

- OpenEmu Version: ver 2.3.3
- macOS Version: 12.5

**Comment by clobber** [comment]
Stop opening multiple issues.

#4742
