### ISSUE TITLE
Reconsider #1280

### ISSUE THREAD

**Issue by mygizli04** [OpenEmu/OpenEmu#4745]
I would like to use a widescreen patch for Super Mario 64, however OpenEmu does not have an option for streching which makes widescreen games look squished. The original issue ( #1280 ) was closed because it "looks insanely horrible" but I'd rather play my games in 16:9 than 4:3. Surely there must be more games with 16:9 mods/options so why not give an option to enable widescreen for at least the N64 and the PS1?

For reference, this is how that mod looks like in OpenEmu right now:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/42012824/182001680-cdc5a42a-f3f4-46b6-99b6-d910d677c949.png">

**Comment by clobber** [comment]
You're conflating two different issues:

1. Muh screen. Super Stretchio Bros at 16:9 or even 21:9 (!) is never going to happen, as you've already learned.
2. Widescreen camera hacks on 3D systems. Support for these can maybe be handled automatically in the core plugins without user intervention. This is not the appropriate repo to request this.
