### ISSUE TITLE
Open Emu - No Cheat option for mac 

### ISSUE THREAD

**Issue by Davisgriffin94** [OpenEmu/OpenEmu#4757]
@clobber 

Hi Evreryone, 

Please can someone help me, I have recently downloaded Openemu on my MacBook, and il loving getting to re-live my childhood. however, it doesn't appear to have the option to select cheats. 

Is there a way to solve this?

**Comment by ghostonfriday** [comment]
yes, i got the same issue here.

OpenEmu v2.3.3 o Macbook Air M2 OS Monterey v12.6
<img width="307" alt="Screen Shot 2022-10-13 at 22 43 30" src="https://user-images.githubusercontent.com/115726859/195643152-c527a258-1d10-4789-a1df-50d248dbe396.png">

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Cheat-codes#supported-cheats

You'll notice for the system you're trying, there is no cheat option available because at the moment cheats are not supported for that system. Search the issues before opening a new one.

#2138
