### ISSUE TITLE
I can't open the program

### ISSUE THREAD

**Issue by alicesdream** [OpenEmu/OpenEmu#4762]
I just bought iMac and play some emulator games but my mac doesn't allow me to open the program what can ı do about it? 
<img width="328" alt="Screen Shot 2022-09-28 at 9 48 33 PM" src="https://user-images.githubusercontent.com/114613584/192864239-770ae206-249f-4285-8869-fd21843aabe3.png">

**Comment by BlitheBrandon** [comment]
This is typical MacOS behavior. This document will hopefully help you out. It's linked from the OpenEmu site.
https://support.apple.com/lt-lt/guide/mac-help/mh40616/mac
