### ISSUE TITLE
Xcode 14 support?

### ISSUE THREAD

**Issue by hstriepe** [OpenEmu/OpenEmu#4768]
I was able to build OpenEmu with Xcode 13 on Monterey, but ran into multiple failures on Ventura requiring Xcode 14.
What are the plans of supporting it?

**Comment by J-rg** [comment]
Xcode 14.1, which should be released later this month, is supported. In the meantime, please use the [current beta](https://developer.apple.com/services-account/download?path=/Developer_Tools/Xcode_14.1_beta_3/Xcode_14.1_beta_3.xip) or remove the offending lines of code.

**Comment by hstriepe** [comment]
Ok, will try again. Some of the experimental cores have a lot of issues - UME, PPSSPP, and Dolphin.

Dolphin standalone works great with Universal support.
