### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Simboiss** [OpenEmu/OpenEmu#4770]
What is the exact logic behind screenshot formats?
When I take a screenshot of a NES game, I end up with a PNG with size 1550 x 1274.
I use the Pixellate shader.

1550 / 256 (the original X resolution of the NES) = 6,0546875
1274 / 240 (the original Y resolution of the NES) = 5,308333333333333

Where do these dimensions come from?
Why can't we have original dimensions?

**Comment by clobber** [comment]
> 256 (the original X resolution of the NES)

No, not quite. The video is aspect ratio corrected and appears as it would on an actual TV of the era.

>  Why can't we have original dimensions?

Then your screenshot would not match what you see on screen, now would it?

To change this:

https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-Preferences:-Secrets
