### ISSUE TITLE
Input monitoring rights macOS security 

### ISSUE THREAD

**Issue by Raiden1982** [OpenEmu/OpenEmu#4773]
Hello,
I'm new to macOS and have a technical question regarding OpenEmu.
After launching, a message will appear stating that OpenEmu wants to receive keystrokes from all apps. 
It is not clear to me why the _input monitoring rights_ are required.
Other programs don't need them either. After all, this is a potential security risk. 
I wonder what is the technical reason for this?

**Comment by clobber** [comment]
Search before opening new issues.
