### ISSUE TITLE
ESC key to close, in OpenEmu

### ISSUE THREAD

**Issue by valiantdj** [OpenEmu/OpenEmu#4777]
Hello! 

Is there a way to make OpenEmu close by pressing the Escape key only? (like Dolphin and PCSX2 can). 

Also is there any way to remove the "are you sure you would like to quit this game" text too when closing a game?

You can by using Command Q, I'm just trying to make the experience smoother :)

**Comment by clobber** [comment]
> make OpenEmu close by pressing the Escape key only?

No.

> way to remove the "are you sure you would like to quit this game" text too when closing a game?

You read the screen and then check the box:
<img width="532" alt="Screen Shot 2022-10-19 at 8 27 51 PM" src="https://user-images.githubusercontent.com/1303132/196842267-4ebe28e3-1952-4e4b-94dd-ab8fdf553fa7.png">
