### ISSUE TITLE
OpenEmu repeatedly crashes and will not open

### ISSUE THREAD

**Issue by TyTheTromboneGuy** [OpenEmu/OpenEmu#4779]
I have been using OpenEmu since January of 2021 on a MacBook Pro running release version High Sierra. Later that year, July if I am not mistaken, I migrated my data from the old MacBook to a brand new MacBook Pro (latest model of that year) that is currently running release version Monterey. OpenEmu had been working fine the rest of the year, but I believe around February or March of 2022 it began to crash, so at that point I stopped using it and came back once the new semester began, and it still crashes like it did then.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

I've tried to open the program several times and the same error report shows up. I've even tried uninstalling the program 3 or 4 times to no avail. I've even tried to open it using the Terminal..

# Expected Behavior

I guess all I can say that I expect it to do is what it is supposed to do: open the menu screen containing all my ROMs.

# Observed Behavior

When I attempt to open it, it crashes immediately (let me know if you would like to see the full crash report).

# Debugging Information

OpenEmu Version 2.3.3
macOS Monterey Version 12.4

**Comment by jaririeke** [comment]
same here

**Comment by clobber** [comment]
@TyTheTromboneGuy and @jaririeke: Post crash logs.
