### ISSUE TITLE
Fast Forward not working

### ISSUE THREAD

**Issue by itsnotworkin** [OpenEmu/OpenEmu#4785]
Summary of issue

I recently downloaded OpenEmu, but the fast-forward is not working. I doubt it is an issue with the input since the game indicates that fast-forwards is on when I press the fast-forward button. However, the game remains the speed. I tried changing the input, and restarting the emulator, mac and game but no change. I have a 13 inch 2020 mac with the latest macOS update Ventura 13.0.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4780
