### ISSUE TITLE
I import .cue  but show No valid system detected: • "Digimon Rumble Arena 2 (USA).cue" 

### ISSUE THREAD

**Issue by fxy591** [OpenEmu/OpenEmu#4791]
I convert .iso to .cue/.bin and import the .cue, but there is a problem
 No valid system detected:
• "Digimon Rumble Arena 2 (USA).cue"

macOS 13.0

**Comment by clobber** [comment]
The error is correct. No where do we state you must "convert" an .iso to .bin/cue. If the game is for GameCube, you simply import the iso. If the game is for PS2 or Xbox, that is not currently supported by OpenEmu.
