### ISSUE TITLE
fast forward does not working

### ISSUE THREAD

**Issue by YamElgabsi** [OpenEmu/OpenEmu#4800]
hay guys! I am new on Mac and this is a superb emulator but the only thing (and important one) that the fast forward doesn't working. I added the controls and its seen like it try to do it but its doesn't effect at all.
If I can get a guide hot to fix it or wait for next update to dix it it will be great.

- OpenEmu Version: 2.3.3
- macOS Version: Ventura 13.0.1

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Duplicate of #4780
