### ISSUE TITLE
Fast-forward key

### ISSUE THREAD

**Issue by Vlay6** [OpenEmu/OpenEmu#4801]
I am using a 2021 Mac M1, I downloaded OpenEmu from the official website. I ran the games in NDS on the first day and everything was normal. However, after I quit the application and shut off my laptop, the next day, the fast-forward key is not working anymore. Upon pressing/holding it, the fast-forward icon pops up on the top left of the screen, but the game/screen isn't in fast-forward and at normal speed. I have tried binding to other keys, opening new games in NDS, exiting the application and reopening, but the result are still not working

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#4780
