### ISSUE TITLE
macOS 13: The MAME core has quit unexpectedly

### ISSUE THREAD

**Issue by whok1llkennyd1** [OpenEmu/OpenEmu#4804]
OpenEmu 2.3.3 Experimental
OLD mame_appcast.xml [Update MAME to 0.235] WORK
LAST UPDATE mame_appcast.xml [Update MAME to 0.250] NOT WORK! CRASH

Ventura 13.0.1 (22A400)

**Comment by clobber** [comment]
>NOT WORK! CRASH

POST THE CRASH LOG

**Comment by whok1llkennyd1** [comment]
[OpenEmuHelperApp-2022-12-12-181604.ips.zip](https://github.com/OpenEmu/OpenEmu/files/10211527/OpenEmuHelperApp-2022-12-12-181604.ips.zip)

**Comment by clobber** [comment]
@whok1llkennyd1 See if this fixes your crash:

* Finder → Go → Go to Folder… → `~/Library/Application Support/OpenEmu/Cores`
* Right click `MAME.oecoreplugin` → Move to Trash
* Launch OpenEmu → Preferences... → Cores → Download "MAME" 0.250.0 again.

**Comment by jschrab** [comment]
I am noticing a similar problem out of the blue. Removing the MAME core and reinstalling (0.250.0) it did not help.

The specs of my iMac are...

- Retina 5K, 27-inch, 2020
- 3.8 GHz 8-Core Intel Core i7
- AMD Radeon Pro 5700 XT 16 GB
- 32 GB 2667 MHz DDR4
- macOS 13.0.1 (22A400)

Here's the crash report
[OpenEmuHelperApp-2022-12-12-180226.ips.zip](https://github.com/OpenEmu/OpenEmu/files/10213030/OpenEmuHelperApp-2022-12-12-180226.ips.zip)

**Comment by clobber** [comment]
@jschrab @whok1llkennyd1 Just wondering, does this happen with all games? Certain ones? Have an example?

**Comment by carlos-biker** [comment]
I have exactly the same problem that @whok1llkennyd1.

**Comment by whok1llkennyd1** [comment]
> @whok1llkennyd1 See if this fixes your crash:
> 
> * Finder → Go → Go to Folder… → `~/Library/Application Support/OpenEmu/Cores`
> * Right click `MAME.oecoreplugin` → Move to Trash
> * Launch OpenEmu → Preferences... → Cores → Download "MAME" 0.250.0 again.
Try. **Not work**

> * Just wondering, does this happen with all games? Certain ones? Have an example?
Not work only ARCADE. Others cores good launch
I'm forcibly changing a new kernel (250) to an old kernel (235) and everything works. it's about the new kernel

**Comment by jschrab** [comment]
Let me know if there is anything more I can provide @clobber - thank you for looking into this!

**Comment by dson32** [comment]
I'm having a similar issue.  OpenEmu Arcade Mame worked well yesterday on my Mac Studio M1 but won't open on my 2019 Mac Pro Xeon.  If changing the new kernel (250) to an old kernel (235) is recommended, can someone provide a step by step process on how to do so?  Is there another way or should we wait for some update?  thanks

**Comment by ew4syu** [comment]
i tried the test version, it still can't work.
[OpenEmu error 20221214.txt](https://github.com/OpenEmu/OpenEmu/files/10224476/OpenEmu.error.20221214.txt)

**Comment by whok1llkennyd1** [comment]
> Oddly enough, the crash is for users running macOS 13.0.1 with Intel Macs. Cannot replicate it on Intel Macs running macOS 12.6.1 or Apple Silicon Macs.
> 
> Test the following build to see if the crash is fixed:
> 
> * Close OpenEmu
> * Delete your current MAME.oecoreplugin in the Cores folder
> * [Download this test version](https://transfer.sh/ibP756/MAME_0250-test1.zip), extract and copy to Cores folder
> * Relaunch OpenEmu and test Arcade.

Cry. MAME_0250-test1 CRASH

**Comment by dvessel** [comment]
@clobber I’ve been compiling a personal copy and got the exact same error but it only happens when running natively on ARM. Running it in Rosetta will prevent the crash. This is on 13.1.

Been trying to debug it but I don’t know Swift or Objective C. If this holds any clues, Xcode stopped right here:

```
OpenEmuKit/Source/OECorePlugin.swift:

    typealias Controller = OEGameCoreController
    
    private var _controller: Controller?
    public var controller: OEGameCoreController! {
        if _controller == nil,
           let principalClass = bundle.principalClass {  << Thread 2: EXC_BAD_ACCESS (code=2, address=0x16fe03660)
            _controller = newPluginController(with: principalClass)
        }
        return _controller
    }

variables on crash:

self  OpenEmuKit.OECorePlugin 0x000060000261c480
  OpenEmuKit.OEPlugin OpenEmuKit.OEPlugin 
    ObjectiveC.NSObject NSObject  
    url Foundation.URL  "file:///Users/foo/Library/Application%20Support/OpenEmu/Cores/MAME.oecoreplugin/" 
    name  String  "MAME"  
    bundle  NSBundle  0x0000600002128730
    infoDictionary  [String : Any]  28 key/value pairs  
    version String  "0.250.0" 
    displayName String  
    _controller OEGameCoreController? nil
```

**Comment by stuartcarnie** [comment]
> @clobber I’ve been compiling a personal copy and got the exact same error but it only happens when running natively on ARM. Running it in Rosetta will prevent the crash which is really odd. This is on 13.1.

This happens because the MAME core is only built for x86_64 architecture, so it fails to load. I have built a version for aarch64 and it works fine natively.

We should implement logic to inspect the available architectures and report an error if one can't be found.

**Comment by dvessel** [comment]
> Different error in this case.

Browsing through some of these crash logs, it looks very similar but I’m no expert.

```
Crashed Thread:        1  Dispatch queue: com.apple.NSXPCConnection.user.anonymous.23451

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x000000016f2bffd0
Exception Codes:       0x0000000000000002, 0x000000016f2bffd0
```

> This happens because the MAME core is only built for x86_64 architecture, so it fails to load. I have built a version for aarch64 and it works fine natively.

For Ventura? Might be some changes no pushed to Github or some configuration I’m not aware of.

> We should implement logic to inspect the available architectures and report an error if one can't be found.

It actually does report mismatch architectures when running an ARM build of OpenEmu with an x86 only build of MAME. I ran into it once due to the recent commit. [5b9f56f7](https://github.com/OpenEmu/UME-Core/commit/5b9f56f70806a36fe8b6e7106c856f48c11dbed5)

Before Ventura, I had an ARM build of MAME working just fine.

**Comment by clobber** [comment]
> Browsing through some of these crash logs, it looks very similar but I’m no expert.

Yes... one will see that same exception for any core crash. The differences are in the fine details of the logs. Diagnosing a crash with MAME is particularly more difficult, as we really need to be able to replicate it with OpenEmu in debug mode with the core process attached.

> Before Ventura, I had an ARM build of MAME working just fine.

Not only is that not yet fully supported in MAME, their developers have said some games don't run correctly in the ARM native build. I wouldn't be trying for this yet. If you are hoping for a significant performance increase, that will not be noticeable.

**Comment by dvessel** [comment]
> Yes... one will see that same exception for any core crash. The differences are in the fine details of the logs. Diagnosing a crash with MAME is particularly more difficult, as we really need to be able to replicate it with OpenEmu in debug mode with the core process attached.

Okay, there’s a very good chance that the bug I’m running into is off topic. Sorry if that’s the case but I my local copy of MAME 0250 runs fine in Rosetta. OpenEmu itself is much newer though.

> Not only is that not yet fully supported in MAME, their developers have said some games don't run correctly in the ARM native build. I wouldn't be trying for this yet. If you are hoping for a significant performance increase, that will not be noticeable.

Performance has always been fine through Rosetta. Building for ARM was just for my personal curiosity and some hope that expensive shaders consume less GPU time.

**Comment by clobber** [comment]
> Okay, there’s a very good chance that the bug I’m running into is off topic.

Yeah I don't believe it's the same as the main crash in this thread.

> some hope that expensive shaders consume less GPU time

No, that would not be core-related. Note that the shaders are GLSlang and use SPIRV to transform into Metal Shader Language -- executed on the GPU from OpenEmu and not the core plugin process. Shader performance, beyond your own GPU, are tied to OpenEmu-Shaders and OpenEmuKit frameworks.

**Comment by dson32** [comment]
Since my Intel Mac has been running Mame on OpenEmu for years now and suddenly stopped working with a possible MacOS update, do you think MAME will start working in a future MacOS update or are we looking at the end of easy compatibility?  OpenEmu may offer an update at some point, but doesn't seem like it gets updated frequently.

**Comment by r-frett** [comment]
This same error appeared for me about two days ago on OpenEmu 2.3.3 for all mame roms. Reloading mame core 0.250.0 hasn't fixed it. I've now upgraded from OSX 13.0.1 to 13.1 and the error still persists. 

I wonder if OSX 13.1 being released two days ago (December 13, 2022) is somehow related? 

Retina 5K, 27-inch, 2017
3.8 GHz quad-core Intel Core i5
Radeon Pro 580 8 GB
64 GB 2400 MHz DDR4
macOS 13.1 (error also in 13.0.1) 

[OpenEmu_Crash_2022-12-15.zip](https://github.com/OpenEmu/OpenEmu/files/10235392/OpenEmu_Crash_2022-12-15.zip)

**Comment by whok1llkennyd1** [comment]
Temporary solution: I manually del the core 0.250 (/Users/***/Library/Application Support/OpenEmu/Cores)
Copied the [old kernel 0.235](https://github.com/OpenEmu/UME-Core/releases) to the directory OpenEmu/Cores.
Denied the OpenEmu access to the Internet (so that the program does not update the kernel)

**Comment by clobber** [comment]
**TEST 2**

There will likely be many more test builds as I attempt to narrow down the problem -- this will take some time, so please test and report back.

Known so far: Crash running MAME 0250 core plugin with Intel Macs on macOS 13.x+

Test the following build to see if the crash is fixed:
* Close OpenEmu
* Delete your current `MAME.oecoreplugin` in the `Cores` folder
* [Download **TEST 2** here](https://transfer.sh/gOIsAk/MAME_0250-test2.zip), extract and copy to `Cores` folder
* Relaunch OpenEmu and test Arcade.

**Comment by jschrab** [comment]
For **MAME_0250-test2.zip** from @clobber
Similar crash behavior - crash report attached.

[OpenEmuHelperApp-2022-12-15-140555.ips.zip](https://github.com/OpenEmu/OpenEmu/files/10240271/OpenEmuHelperApp-2022-12-15-140555.ips.zip)

**Comment by r-frett** [comment]
MAME.oecoreplugin crash report for TEST 2

[OpenEmu_Crash_2022-12-15 for TEST 2.zip](https://github.com/OpenEmu/OpenEmu/files/10240365/OpenEmu_Crash_2022-12-15.for.TEST.2.zip)

**Comment by clobber** [comment]
Thanks for testing. Here is **TEST 3**

Test the following build to see if the crash is fixed:
1. Close OpenEmu
2. Delete your current `MAME.oecoreplugin` in the `Cores` folder
    - Finder → Go → Go to Folder… → `~/Library/Application Support/OpenEmu/Cores`
    - Right click `MAME.oecoreplugin` → Move to Trash
3. [Download **TEST 3** here](https://transfer.sh/B627rp/MAME_0250-test3.zip), extract and copy to `Cores` folder
4. Relaunch OpenEmu and test Arcade.

**Comment by carlos-biker** [comment]
Still the same error... here is the crash report :-)

[crash.txt](https://github.com/OpenEmu/OpenEmu/files/10241426/crash.txt)

**Comment by r-frett** [comment]
MAME.oecoreplugin crash report for TEST 3

[OpenEmu_Crash_2022-12-16 for TEST 3.zip](https://github.com/OpenEmu/OpenEmu/files/10241935/OpenEmu_Crash_2022-12-16.for.TEST.3.zip)

**Comment by clobber** [comment]
Here is **TEST 4**

Test the following build to see if the crash is fixed:
1. Close OpenEmu
2. Delete your current `MAME.oecoreplugin` in the `Cores` folder
    - Finder → Go → Go to Folder… → `~/Library/Application Support/OpenEmu/Cores`
    - Right click `MAME.oecoreplugin` → Move to Trash
3. [Download **TEST 4** here](https://transfer.sh/Klt0k0/MAME_0250-test4.zip), extract and copy to `Cores` folder
4. Relaunch OpenEmu and test Arcade.

**Comment by MScoutsDCI** [comment]
TEST 4 resolved the issue for me

**Comment by ew4syu** [comment]
TEST 4 is ok for me！

**Comment by clobber** [comment]
> TEST 4 resolved the issue for me



> TEST 4 is ok for me！

Great. The problem appears to be with macOS 12.4 used as the deployment target. I've switched it to 10.15 which seems to work. I will push a MAME core plugin update as version 0.250.1 to resolve this for everyone.

**Comment by clobber** [comment]
This is fixed now.

Restart the app and an updated MAME core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu → Preferences → Cores and looking for MAME 0.250.0.1.

**Comment by r-frett** [comment]
Amazing! Just loaded in the new core and it works a treat!
Thanks clobber for the expert bug bashing!

**Comment by carlos-biker** [comment]
Thank you very much, great job!

**Comment by whok1llkennyd1** [comment]
> This is fixed now.
> 
> Restart the app and an updated MAME core plugin will automatically download and install. You can verify you have the new version by going to OpenEmu → Preferences → Cores and looking for MAME 0.250.0.1.

You my hero! Now I can play the Undercover Cops again
