### ISSUE TITLE
Save states supposedly load, but no sound & controls don't work

### ISSUE THREAD

**Issue by svoge52** [OpenEmu/OpenEmu#4806]
If I open up the game (a PokemonROM - Radical Red), and click any of my saved states (that were working on the Open Emu app just yesteday), it will now act is if the saved state was loaded and shows the image properly, but that's it. No sounds, and the controls don't work.

I've tried redownloading OpenEmu, restarting my computer, etc. but no luck. I have OpenEmu v. 2.3.3 for macbook.

**Comment by clobber** [comment]
Sounds like mGBA broke save state compatibility for some games again. Sorry, there is nothing we can do about this. You'll have to start the game without loading a save state. Please rely on in-game saves and not save states going forward.

**Comment by svoge52** [comment]
Thank you for the reply. How would in game saves even work if you have to
start the app, which relies on out of game save states? Also what is mGBA?
