### ISSUE TITLE
Cannot play SNES games on OpenEmu v2.0.6.1 once the new SNES9x Core 1.61 installed (iMac Late 2009 macOS 10.13.6)

### ISSUE THREAD

**Issue by pwongputorn** [OpenEmu/OpenEmu#4811]
Cannot play SNES games once the new SNES9x Core version 1.61 installed
OpenEmu v2.0.6.1 
iMac Late 2009 macOS 10.13.6

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Only the [latest version](https://github.com/OpenEmu/OpenEmu/releases/latest) of OpenEmu is supported."

**Comment by clobber** [comment]
Oddly enough, the SNES9x core update runs fine on 10.11 for me, so I don't know what their problem on 10.13 could be without a crash log. It may not be a deployment target problem.

**Comment by pwongputorn** [comment]
I've updated to 2.0.9.1 and it works just fine. Thank you for your support.
