### ISSUE TITLE
fast forward not working

### ISSUE THREAD

**Issue by Bcap32** [OpenEmu/OpenEmu#4814]
I play pokemon on openemu a lot. The fast forward function does not work anymore. just fast forward is not working. 

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

- OpenEmu Version: v2.3.3
- macOS Version: 13.1

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

This is fixed for next release.

Duplicate of #4780
