### ISSUE TITLE
KeyBoard Input not working for Updated MAC

### ISSUE THREAD

**Issue by TheBzrkGamer** [OpenEmu/OpenEmu#4825]
I haven't played OpenEmu in a while so I got back on to play some old Pokemon RomHacks, when getting on I couldn't move at all. This is when I got on here and saw how many people had the same issue, I think gave OpenEmu permission to monitor my input and restarted my computer. It still isn't working and the app still has my permission. I have tried everything from the FAQ section and I still can't use my keyboard. If anybody has any suggestions or alternatives please let me know so I can start playing again!

P.S: It won't work for any of the games, new or old.

# Steps to reproduce

1. I am unaware how I caused this problem, I am assuming it is just me updating my Mac.

# Expected Behavior

1. I want to be able to use my keyboard while playing OpenEmu

# Observed Behavior

1. The only keys working while running OpenEmu are the top keys that exit the app (like escape) and my brightness icons. I can use my keyboard while in the Library but not the game itself.

# Debugging Information

- OpenEmu Version: v2.3.3
- macOS Version: 13.0.1

**Comment by obchodniuspech** [comment]
same here, ventura, trying to play gameboy color silver and its not working :)

**Comment by isyrota** [comment]
Venture keyboard not working :(

**Comment by hyfjjjj** [comment]
same

**Comment by Ragnar-04** [comment]
I have the same problem, except my sound for the emulator completely cut out. I know it's not my computer because if I get on something like Youtube then my sound is fine.

**Comment by nghtstr** [comment]
I am having the same problem as well. Mac, Intel i9 2.0 GHz, Monterey 12.6.4. I updated yesterday to 12.6.4, and today it is not responding to any key presses. Yesterday, it was not a problem at all.

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Read: https://github.com/OpenEmu/OpenEmu/issues/4632#issuecomment-1097290608
