### ISSUE TITLE
Can't add games

### ISSUE THREAD

**Issue by nikitaosx** [OpenEmu/OpenEmu#4828]
I am trying to add my Sonic Simon Wai ROM hack to OpenEmu but it says it already exists in the library while in reality it's not.

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Save the ROM to Downloads.
2. Try to drag and drop it into the Library.
3. The error appears.

# Expected Behavior

1. I thought that it will import.

# Observed Behavior

1. The error appears instead of it importing.

# Debugging Information

- OpenEmu Version: v2.3.3
- macOS Version: macOS Ventura 13.0

**Comment by clobber** [comment]
It's there.
