### ISSUE TITLE
Pokemon Argent Soulsilver Black Screen

### ISSUE THREAD

**Issue by Josanssouci** [OpenEmu/OpenEmu#4831]
When I play on the this rom, for the first it's working well, but when I quite the game et re play just after I have directly a black screen on all my saves, I have the sound of the game and te tactil part who is working and that's it :/
Do we have any solutions ?

# Steps to reproduce

1. strat the game and play few minutes and save
2. Quite OpenEmu
3. Open OpenEmu and launch the game
4. Now I have blackscreen

# Debugging Information

- OpenEmu Version: 2.3.3
- macOS Version: 12.6 / Apple Puce M1

**Comment by Jawa006** [comment]
Pokemon Soul Silver has a anti piracy that turns your screen black, and the solution to fixing the 'blackscreen' bug is by first saving your game in the in game save feature.
- Save your Pokemon game 
- press the restart button 
- open your save file via in game rom
- viola, your screen should be fixed

**Comment by Josanssouci** [comment]
Thank you ! I will try, I just have to save one time in the game or everytime ?

**Comment by Josanssouci** [comment]
I tried by recording on the game directly, it worked for a while, more than usual but for a while I save after 2 hours of play and the black screen :'(
