### ISSUE TITLE
Fast forwarding and rewinding is broken on several cores in v2.3.3 on Mac m1 OS Ventura 

### ISSUE THREAD

**Issue by AlexanderKeny10** [OpenEmu/OpenEmu#4833]
Summary of issue

The fast forwarding and rewinding feature is not working on cores for Gameboy Advanced and Nintendo DS. There my be more but I don't have roms of other software to test them all. 
The 'Fast forward' and 'rewind' feature do show imagine of left '>>' and right arrows '<<' on the upper left hand screen but but do not fast forward or rewind as intended. Simply nothing happens. 

Macbook Air m1 with the latest update of Ventura 13.2 
OpenEmu v2.3.3

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

This is fixed for next release.

Duplicate of #4780
