### ISSUE TITLE
OpenEmu Complete MAME ROM Sets

### ISSUE THREAD

**Issue by dson32** [OpenEmu/OpenEmu#4838]
Hi, 
Was wondering what the best complete Arcade MAME ROM Set that is compatible with OpenEmu at this time.
Last thread I saw I believe recommended mame0.224, but wondering if there are newer Rom sets that are better.
If there are any suggestions, please list what the file name is on Internet archive.
Thanks in advance.

**Comment by dvessel** [comment]
The version will be shown in the cores tab within the settings. The rom set must match the MAME version. Newer sets will fail to load if a particular rom was updated. And don’t ask where to get roms.

**Comment by Princelo** [comment]
https://github.com/Abdess/retroarch_system/blob/libretro/Arcade/neogeo.zip

**Comment by gerardvanschip** [comment]
Curent core for OpenMemu 2.4.1 is 0.250.0.1 while mame itself is at 0.261 so you will need to find a rom download site that lists 0.250 roms.

You can grab the latest (updated Dec 16, 2022) mame core here:
https://github.com/OpenEmu/UME-Core/releases
