### ISSUE TITLE
Are there any plans to update the Dolphin core on OpenEmu? 

### ISSUE THREAD

**Issue by FiniusFrog** [OpenEmu/OpenEmu#4841]
Hi there, 

I’ve just updated to Mac OS Ventura and stupidly forgot to check compatibility with Open Emu before I did. Found out the hard way that GameCube games currently don’t work via Open Emu’s Dolphin core. ☹️ The new standalone version of Dolphin is working on Ventura. Are there any plans to update the Dolphin Core on Open Emu? Or is it a bigger/more difficult issue than that?  Thanks to everybody involved in making Open Emu it’s an amazing platform and I love using it. 😃

**Comment by nromjr** [comment]
I am facing the same issue, and rather surprised that not a lot of people have given a conscise answer to this... I'd love to keep playing on the OpenEmu platform, and for some reason I can't find the save files that I had so that I can continue playing on Dolphin... so I'd love to see this issue resolved.

**Comment by EckerbergAndrew** [comment]
They say to contact Dolphin as it's not an OpenEmu issue, but with 38% of games working perfectly and another 59% working with only minor issues as reported on Dolphin's site, whilst OpenEMU's Dolphin just crashes when trying to open games...it's completely an OpenEmu issue...

**Comment by Minimistro32** [comment]
#4846 #4845 #4756 #4782 
All of these appear to be about this issue.

**Comment by cedbeu** [comment]
Maybe OpenEmu team should either contact Dolphin team, or remove the core from the list. Dolphin doesn't work at all on OpenEmu anymore on M1/M2 under Ventura, it systematically crashes, while the standalone Dolphin works perfectly; so it's little easy to say "see with Dolphin team"… Maybe you should either collaborate with them or remove the core from OpenEmu…

**Comment by cacaosteve** [comment]
I have an M1 Mac so I compiled OpenEmu-metal, Mupen64Plus, and dolphin-core (they seem to use the old revision a444fa1 of dolphin). It would still be interesting to see if I could get a newer release of dolphin working, but this should suffice for now.

https://mega.nz/file/vJZU1LYZ#v9E6t30uVaBXA6M-Ot71UIo79ao7-va-bK9k2BmJceY

If you use my OpenEmu.app you need to codesign --force --deep --sign - /Applications/OpenEmu.app.

I've only tested this in macOS Sonoma on an M1 Max MacBook Pro.

The Cores go in ~/Library/Application Support/OpenEmu/Cores.

For dolphin I changed "mach_msg_header_t* send_msg = nullptr;" to "mach_msg_header_t* send_msg = &msg_out.Head;" in MemTools.cpp and set bSupportsGPUTextureDecoding = false in VulkanContext.cpp and OGLMain.cpp.

For Mupen I had to put this for the _getWSPath function in CommonAPIImpl_mupenplus.cpp.static void _getWSPath(const char * _path, wchar_t * _strPath) {if (!_path || !_strPath) {return; // Avoid NULL dereference}std::setlocale(LC_ALL, "C"); // Set locale to the C default localesize_t converted = ::mbstowcs(_strPath, _path, PLUGIN_PATH_SIZE);if (converted == (size_t)-1) {// Handle the conversion error, e.g. by setting _strPath to an empty string_strPath[0] = L'\0';return;}_strPath[PLUGIN_PATH_SIZE - 1] = L'\0'; // Ensure null termination_cutLastPathSeparator(_strPath);}
