### ISSUE TITLE
Why aren't there any new releases?

### ISSUE THREAD

**Issue by davidseegert** [OpenEmu/OpenEmu#4848]
Hey, fist of all, thank you for all the time and effort you are putting into this project! 

I just wanted to asked why there aren't any new releases? It seems like there where multiple releases each year until 2021 when things suddenly stopped. However this project doesn't look inactive to me otherwise. As it looks, there is a relatively constant stream of contributions.

For example I am waiting for this [fast forward bugfix](https://github.com/OpenEmu/OpenEmu/issues/4780) to get published, but it seems this gets raised [over](https://github.com/OpenEmu/OpenEmu/issues/3976) and [over](https://github.com/OpenEmu/OpenEmu/issues/4833) again as there is no publication. 

Is there any underlying problem or things we can do, to help building a new release?

**Comment by karlingen** [comment]
+1
