### ISSUE TITLE
What is the milestone for a new release? It's been 2 years....

### ISSUE THREAD

**Issue by pleasejustgo** [OpenEmu/OpenEmu#4852]
Surely enough has been fixed to warrant a new release. Please consider making a new release. Thanks.

**Comment by diamondsw** [comment]
The lack of an answer in six weeks... is an answer in and of itself.

**Comment by malfroid** [comment]
Now over 1000 days since the last release 2.3.3. Is this project dead?

**Comment by clobber** [comment]
Do you see new commits? Did you even look?
