### ISSUE TITLE
Add 3DS Emulation

### ISSUE THREAD

**Issue by Crashenterminate** [OpenEmu/OpenEmu#4853]
It will be cool to have 3ds emulation in OpenEmu using citra

Also for games that need the 3ds gyroscope feature (e.x.: WarioWare Gold's Twist League) also add something to simulate the gyroscope movement

That's all, thanks for reading my feature request, and if this gets added, thanks for adding my request to OpenEmu

Bye ;D

**Comment by MaddTheSane** [comment]
As it is, recent Citra build require OpenGL 4.3, which is not provided by Apple's OpenGL framework.
Good news is that Citra is working on a Vulkan back-end.
Bad news is that OpenEmu doesn't have hooks yet for Vulkan/MoltenVK yet.

**Comment by Crashenterminate** [comment]
> As it is, recent Citra build require OpenGL 4.3, which is not provided by Apple's OpenGL framework. Good news is that Citra is working on a Vulkan back-end. Bad news is that OpenEmu doesn't have hooks yet for Vulkan/MoltenVK yet.

So... also hook vulkan. No?
