### ISSUE TITLE
Integrate DOSBox on OpenEmu (to extend to MS-DOS-based games)

### ISSUE THREAD

**Issue by Gioser90** [OpenEmu/OpenEmu#4866]
DOSBox is the emulator that allows emulation of MS-DOS-based games.
It works well, but has no GUI (all terminal-based).

If a way could be found to collaborate with the staff and integrate the DOSBox engine directly into OpenEmu?
First and foremost, "DOSBox" would finally get a GUI, but more importantly, OpenEmu would be enriched with a world of MS-DOS PC games that is absolutely no small feat.

Website: https://www.dosbox.com
OpenSource: https://github.com/blackberry/DosBox

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue." 

https://github.com/OpenEmu/OpenEmu/issues?q=boxer
