### ISSUE TITLE
keyboard input monitoring - Ventura 13.5 not working 

### ISSUE THREAD

**Issue by quantum-fusion** [OpenEmu/OpenEmu#4893]
Summary of issue

The keyboard does not work when permissions are enabled.  

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

Launch OpenEmu on Ventura 13.5 
Open System Preferences from pop up "OpenEmu requires additional permissions"
Unlock System Preferences
Toggle off Input Monitoring for OpenEmu
Click Quit & Reopen popup
Close OpenEmu
Lock System Preferences and close it
Relaunch OpenEmu
Open System Preferences from pop up "OpenEmu requires additional permissions"
Unlock System Preferences
Toggle on Input Monitoring
Click Quit & Reopen popup

# Expected Behavior

I am expecting to be able to play a game with keyboard controls. 

# Observed Behavior

The keyboard controls do not work. 

<img width="515" alt="Screenshot 2023-06-01 at 12 09 29 PM" src="https://github.com/OpenEmu/OpenEmu/assets/10088099/ff693694-68a4-45e0-9b96-bc5b032eeeb9">

<img width="364" alt="Screenshot 2023-06-01 at 12 09 50 PM" src="https://github.com/OpenEmu/OpenEmu/assets/10088099/c6b2b871-0181-43de-a8cd-b9388bb59202">

- OpenEmu Version: ???
- macOS Version: ???

**Comment by atarigamer** [comment]
Same issue on Ventura 13.4 and OpenEmu 2.3.3.
Removing OpenEmu from the Input Monitoring settings and adding back in does not help.

**Comment by hangxingfu** [comment]
me too,  help me, please

**Comment by quantum-fusion** [comment]
someone please help us!!!

**Comment by dvessel** [comment]
Try this: https://github.com/OpenEmu/OpenEmu/issues/4632#issuecomment-1442136713

It’s only 2 steps, follow it exactly in the order listed.

**Comment by atarigamer** [comment]
> Try this: [#4632 (comment)](https://github.com/OpenEmu/OpenEmu/issues/4632#issuecomment-1442136713)
> 
> It’s only 2 steps, follow it exactly in the order listed.

Perfect, thanks, that fixed it for me!

**Comment by hangxingfu** [comment]
> 

nice bro, very thanks, Step six is very useful 😊

**Comment by hangxingfu** [comment]
> Try this: [#4632 (comment)](https://github.com/OpenEmu/OpenEmu/issues/4632#issuecomment-1442136713)↳
> 
> It’s only 2 steps, follow it exactly in the order listed.↳
nice bro, very thanks, Step six is very useful 😊

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."
