### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by TauaRian** [OpenEmu/OpenEmu#4910]
do you have a version for windows 10?

**Comment by MaddTheSane** [comment]
This is a macOS-only application.
The closest you'll find on Windows is RetroArch.

**Comment by SleepDaemon** [comment]
I mean swift coded apps can be run on windows. People behind Arc are doing it, so why not do the same? Is it because you don't have the people to achieve it?

**Comment by MaddTheSane** [comment]
Partly that, but mostly because the APIs used are still Cocoa/Mac-specific. It doesn't matter if the source code is Objective-C or Swift: The APIs don't (publicly) exist for Windows.

Porting to Windows would require a complete re-write of the codebase.
