### ISSUE TITLE
Street Fighter EX3 keeps crashing PCSX2 (NTSC SLUS-20130)

### ISSUE THREAD

**Issue by gktonic** [OpenEmu/OpenEmu#4911]
After opening the game, PCSX2 crashes/quits after a short while

The crash appears to be rather randomly (after the capcm logo, after character selection, etc.), and did not occur in older builds (or the latest/last version of AetherSX2)

PCSX & game settings are on default

- OpenEmu Version: MacBook Air / Apple M1 / 16 GB
- macOS Version: Ventura 13.4.1

**Comment by clobber** [comment]
Alpha status core plugins are not supported.

**Comment by gktonic** [comment]
I am sorry, my bad. This bug report went to the wrong git

It was actually meant for the latest nightly build of PCSX2
