### ISSUE TITLE
Building from source: UniversalDetector can't link to libarclite_macosx.a, MACOSX_DEPLOYMENT_TARGET is too low

### ISSUE THREAD

**Issue by ghyatzo** [OpenEmu/OpenEmu#4914]
Hello,

I've tried to build from source, but It would always error out when looking for libarclite_macosx.a at linktime.
Along with a warning: 
> The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 13.3.99.

all needed to make the build succeed was to change the deployment target of UniversalDetector to 10.13 instead of 10.9.

Is this just a leftover setting from older times? Can you reproduce this? Is the deployment to 10.9 needed for any particular reason?

**Comment by dvessel** [comment]
I ran into the same thing. From what I’ve found, it’s some legacy library that was dropped in Xcode. I ended up creating a custom branch that splits off right before f14da62 then cherry picking after that. It can be brought back inline with its resolved.

**Comment by Jenavieve-Rose** [comment]
yeah I am getting this same error while a few weeks ago had no issues building.

**Comment by Jenavieve-Rose** [comment]
Even after changing the UniversalDetector I still get the errors 
"File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a"

and 

"Linker command failed with exit code 1 (use -v to see invocation)"

Since libarclite is depreciating it shouldn't still be looking for it but apparently it is even after changing the universal.

**Comment by dvessel** [comment]
@Jenavieve-Rose set the deployment target for XADMaster as well. Make sure you select the proper targets.

![SCR-20230811-khqx](https://github.com/OpenEmu/OpenEmu/assets/126473/085c6686-20e6-4251-88ed-190fcd098669)

**Comment by ghyatzo** [comment]
From what I could gather since newer versions of Mac OS that library was baked into the system so it got removed from the Xcode tool chain.

**Comment by ultratiem** [comment]
@dvessel thanks a ton for forking and fixing the build! Compiled without issue 👍 

Did you manage to get the cores built? I got an error on Mupen. Would be nice to bump up some of the core versions

**Comment by dvessel** [comment]
I did nothing. The commit was recently reverted by J-rg so this can be closed.
