### ISSUE TITLE
mario and luigi bowser's inside story openEMU keeps crashing on blooper statue boss

### ISSUE THREAD

**Issue by KB12naeb** [OpenEmu/OpenEmu#4919]
shortly before i had an issue where the game would crash on the first midbus fight but i had to skip over it with a walk through walls cheat and now im having an even worse issue with the next boss also crashing the game when you start the fight and i tried using the walk through walls cheat but didnt work bc when you enter the loading zone your put into a cutscene and the game crashes so if anyone could tell me a way to fix this it would be very nice being able to progress, also is this a common issue with every boss in this game with the emulator?

**Comment by clobber** [comment]
Yes, this is a bug common with the DeSmuME emulator. Not an issue for OpenEmu to solve.

#4433
