### ISSUE TITLE
Retroachievements support.

### ISSUE THREAD

**Issue by Menelkir** [OpenEmu/OpenEmu#4921]
I've searched around (even on the code) to see if this isn't an issue that was already addressed.
I'm not sure if you guys are aware of this site: https://retroachievements.org
Many emulators and frontends supports it, isn't a really necessary feature, but is a nice to have (with a toggle if some people feels like is bad for some reason).
The API is here: https://github.com/RetroAchievements/rcheevos

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

https://github.com/OpenEmu/OpenEmu/issues?q=Retroachievements
