### ISSUE TITLE
OpeEmu Update Needed for Sonoma 14.0

### ISSUE THREAD

**Issue by Gerbo20** [OpenEmu/OpenEmu#4928]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce
Every time that I try to run a Gamecube game after I have updated my Mac to Sonoma 14.0, I get the following message:
   "The dolphin core has compatibility issues and some games may contain glitches or not play at all."

# Expected Behavior

It would usually run games without any problem... (I think there might be a new dolphin update available to fix this issue)

# Observed Behavior

After showing the message, It opens the windows for a fraction of a second and then stops running and gets the message that Dolphin Core having compatibility issues...

# Debugging Information

- OpenEmu Version: 2.3.3 
- macOS Version: 14.0

**Comment by clobber** [comment]
> "The dolphin core has compatibility issues and some games may contain glitches or not play at all."

This has nothing to do with OpenEmu or Sonoma. The dolphin core plugin purposely displays that message on load in order to manage user expectations.
