### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by michaelheiml** [OpenEmu/OpenEmu#4930]
Hi, since the latest official release is back from 2021 - is there a plan to create a new build anytime or is there another way how users should get a more recent version of OpenEmu including all the latest developments/commits? What would be recommended? Everyone pulling/building their own app?

**Comment by vesper8** [comment]
Yea.. I was wondering the same. There are usually some ~10 commits between releases.. but there are over 500 commits since the last release some ~22 months ago.

**Comment by middelpi** [comment]
I would appreciate a new release, too. It is not difficult to build it by cloning the repository, but for some unknown reason, t would not load cores.

**Comment by sonic2kk** [comment]
This has been asked a lot in the past, a quick search of the issue tracker shows this:
- #4852
- #4734

**Comment by clobber** [comment]
New release this year.
