### ISSUE TITLE
Using existing ROM folders instead of creating new ones

### ISSUE THREAD

**Issue by Bent3ndo** [OpenEmu/OpenEmu#4946]
Is there a way of telling OpenEmu to use existing folders for ROMS instead of it needing to create duplicate sets elsewhere?

Perhaps a new feature could be added where under each console in settings you can tell it to detect froms from specific folders like other emulation suites allow?

**Comment by GregoireLD** [comment]
Not sure if that's what you mean, but In the OpenEmu preferences, In the first tab "Library", you can uncheck "Copy files to Game Library folder when adding to library". Next time you add a game, OpenEmu will simply use the original file instead of duplicating it.
