### ISSUE TITLE
2.4 is damaged and cannot be opened

### ISSUE THREAD

**Issue by MysticalOS** [OpenEmu/OpenEmu#4949]
Doesn't open no matter what on macOS 14.2.1 on M3 Max. Right clicking and opening to get past gatekeeper doesn't matter. Trying to force it with xattr -cr doesn't matter. It's just damaged and cannot be opened by macOS, something is just missing/built wrong in it.

**Comment by MaddTheSane** [comment]
We are aware of it.
In the meantime, you can get it to run by using the following command line in the Terminal: `codesign --force --deep --sign - /path/to/OpenEmu.app`

**Comment by gongmin00** [comment]
I have the same issue any way to download other stable versions?

**Comment by MysticalOS** [comment]
> I have the same issue any way to download other stable versions?

Command above works fine. gets it working

**Comment by clobber** [comment]
Should now be resolved with the release of OpenEmu 2.4.1. Get it from the [website](http://openemu.org/ ) or in the [releases](https://github.com/OpenEmu/OpenEmu/releases/tag/v2.4.1).
