### ISSUE TITLE
[Feature] Ability to easily add external slang shaders without modifying application bundle

### ISSUE THREAD

**Issue by MysticalOS** [OpenEmu/OpenEmu#4950]
I've actually been adding custom slang shaders to 2.3.3 for ages by opening app bundle and adding them in there since it populates based on what's in there. Some really good ones I like to pull from other public repos and projects.

Got me thinking, maybe there should be an easier way like a folder in application support that will also load from as well, cause my stupid butt got so excited by 2.4 I totally replaced my modified 2.3.3 before thinking about it and now I'll have to locate those again, oops.

**Comment by clobber** [comment]
Yeah, this is possible. Here's the last time I wrote about it which should get you started:

https://github.com/OpenEmu/OpenEmu/issues/4529#issuecomment-848057299

They will end up in `~/Library/Application Support/OpenEmu/Shaders`

**Comment by MysticalOS** [comment]
Ah so I don't actually hav to add my slang shaders into the app bundlde itself, if i put them in ~/Library/Application Support/OpenEmu/Shaders they will populate in list?

**Comment by clobber** [comment]
Yes. I'd recommend first checking out the ones we have converted to work with OpenEmu if you want to see how the folder structure works or package up new ones. The ones you want to move over should probably work fine if they were already working via the app bundle.

https://github.com/OpenEmu/slang-shaders/releases

**Comment by MysticalOS** [comment]
Got it all working. even remembered i had a recent backup, well recent as in 6 months old, but perk of being on 2.3.3 so long is 6 months ago, 2.3.3 was still latest, so it had my modded slang shaders. recovered them and put them in the app support folder and all good

I just didn't know emulator already supported that cause shaders folder doesn't exist until you create it yourself or app creates it by dragging and dropping your plugins. lesson learned :D
