### ISSUE TITLE
Updated to OpenEmu 2.4.1 and keyboard doesn't work

### ISSUE THREAD

**Issue by KKPD90** [OpenEmu/OpenEmu#4952]
Hi,

Have updated to 2.4.1 today and now my Mac's keyboard input is not read during games or when configuring via Controls in Settings. Input Monitoring is set to "ON". Whenever OpenEmu is booted it displays the error message "ALERT_INPUT_MONITORING_HEADLINE ALERT_INPUT_MONITORING_PART1 ALERT_INPUT_MONITORING_PART2_MONTEREY". Have shut down and rebooted Mac.

- OpenEmu Version: 2.4.1
- macOS Version: Sonoma 14.1.2

**Comment by FleXoft** [comment]
Based on this: https://github.com/OpenEmu/OpenEmu/issues/4535

> I solved this problem.
> 
> Firstly I saw the openemu sign with a check box in the input monitoring session in the privacy.
> Then there is a "+" and "-" sign. I selected openemu and click "-" sign to erase openemu.
> After that I reopened Openemu, it showed that it requested input permission.
> Go to privacy and see the openemu sign again in the input monitoring session.
> Tick the check box and the problem is solved.

**Comment by KKPD90** [comment]
> Based on this: #4535
> 
> > I solved this problem.
> > Firstly I saw the openemu sign with a check box in the input monitoring session in the privacy.
> > Then there is a "+" and "-" sign. I selected openemu and click "-" sign to erase openemu.
> > After that I reopened Openemu, it showed that it requested input permission.
> > Go to privacy and see the openemu sign again in the input monitoring session.
> > Tick the check box and the problem is solved.

I'm not sure I follow, could I get an exact process of events? I can uncheck and check OpenEmu in Input Monitoring in my System Preferences, but the keyboard still does not work when I relaunch OpenEmu.

**Comment by NguyenQuangMinh0504** [comment]
@KKPD90  you have to remove open emu and add it again, not by clicking the toggle button.

**Comment by FleXoft** [comment]
> I'm not sure I follow, could I get an exact process of events? I can uncheck and check OpenEmu in Input Monitoring in my System Preferences, but the keyboard still does not work when I relaunch OpenEmu.

/* Don't toggle the checkbox! That way won't work... */

<img width="780" alt="image" src="https://github.com/OpenEmu/OpenEmu/assets/1357569/4e851f59-3813-4225-8290-f41ff10f2b15">

1. select OpenEmu
2. press '-'
3. press '+'
4. and find the OpenEmu application, it will probably be in the Applications folder.

**Comment by KKPD90** [comment]
> > I'm not sure I follow, could I get an exact process of events? I can uncheck and check OpenEmu in Input Monitoring in my System Preferences, but the keyboard still does not work when I relaunch OpenEmu.
> 
> /* Don't toggle the checkbox! That way won't work... */
> 
> <img alt="image" width="780" src="https://private-user-images.githubusercontent.com/1357569/293501777-4e851f59-3813-4225-8290-f41ff10f2b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNDM2NzUsIm5iZiI6MTcwNDE0MzM3NSwicGF0aCI6Ii8xMzU3NTY5LzI5MzUwMTc3Ny00ZTg1MWY1OS0zODEzLTQyMjUtODI5MC1mNDFmZjEwZjJiMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDFUMjEwOTM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVlOWEyYTZhZGExYzEyOTk0NzhhZjA0MjViZTI1Y2QyMDMxMWNiMzU4Zjg5ODk5YzA2OGFiNGQ4MzlhOGZhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1unM4uUyIeUJ4ARakPAQ_vzvxL0tPYnbmGIW2d3SNjY">
> 1. select OpenEmu
> 2. press '-'
> 3. press '+'
> 4. and find the OpenEmu application, it will probably be in the Applications folder.

Thanks!

**Comment by pensez-agile** [comment]
Hi, did not find this issue because my search was too specific, ended up opening a duplicate (#4963), sorry!
Anyway this fixes the issue, thanks a lot!

**Comment by james-york** [comment]
This happened to me today on an update, and I solved it the same way.

> Based on this: #4535
> 
> > I solved this problem.
> > Firstly I saw the openemu sign with a check box in the input monitoring session in the privacy.
> > Then there is a "+" and "-" sign. I selected openemu and click "-" sign to erase openemu.
> > After that I reopened Openemu, it showed that it requested input permission.
> > Go to privacy and see the openemu sign again in the input monitoring session.
> > Tick the check box and the problem is solved.

**Comment by lewis504-g** [comment]
Thank you FleXoft

**Comment by hombreimaginario** [comment]
Using 2.4.1 on Monterrey. Keyboard won't work, no matter how many times I activate or deacticate input monitoring.

**Comment by LiamPalmqvist** [comment]
Same here. Error given as well. 
<img width="532" alt="Screenshot 2024-05-14 at 16 58 11" src="https://github.com/OpenEmu/OpenEmu/assets/38404738/02167efa-4fa4-4d6e-806e-e38533a8bb82">

**Comment by LiamPalmqvist** [comment]
Solved for Monterray:

The following worked to get input monitoring working for me again:

1. Shut down OpenEmu
2. Remove OpenEmu entirely from "Privacy & Security --> Input Monitoring" (use the minus button)
3. Start OpenEmu. It will re-appear in "Input Monitoring"
4. Turn the OpenEmu switch in "Input Monitoring" to on
5. Restart OpenEmu

**Comment by Rozzemak** [comment]
> Solved for Monterray:
> 
> The following worked to get input monitoring working for me again:
.....

Worked also for Sonoma

**Comment by FreezaSama** [comment]
This is still not solved the PS4/5 controller when wirelessly with OpenEmu on Mac. While OpenEmu detects the controller, selecting it doesn’t allow key assignments or input. However, the controller works as expected in all other apps when connected wirelessly and only functions properly in OpenEmu when plugged in via USB.
