### ISSUE TITLE
doesn't detect my input device (macOS issue)

### ISSUE THREAD

**Issue by ghost** [OpenEmu/OpenEmu#4957]
Before I write my issue, my 1st language isn't english (it's spanish) so idk if I will explain myself well about this topic so pls take that in mind while reading my issue 😬

Since the latest update, I cannot play any ROM due to OpenEmu not detecting my keyboard... Everytime I open it there's this window(? that pops up: 

<img width="479" alt="Captura de pantalla 2024-01-02 a las 1 35 36" src="https://github.com/OpenEmu/OpenEmu/assets/155402282/6472dce5-69fe-4fdd-9a7e-c9df0bb90b42">

The thing is that I've read the guide on this web about the issue and I have granted the permission on both the Bluetooth and the Input Device privacy/security thing yet it doesn't work...

<img width="569" alt="Captura de pantalla 2024-01-02 a las 1 43 31" src="https://github.com/OpenEmu/OpenEmu/assets/155402282/97014549-62c8-42bc-b6c9-3d255597516c">

Whenever I put and quit the permission it would tell me to reopen the app so the change would happen and it still won't work... I tried deleting the app and redownloading it just in case it would work but it didn't 🙃

Maybe the solution is easy af but I prefer to ask in here than feel like a dumbo while trying random things :)

**Comment by FleXoft** [comment]
Here is the solution: https://github.com/OpenEmu/OpenEmu/issues/4952#issuecomment-1872921160
