### ISSUE TITLE
Keyboard Input Monitoring

### ISSUE THREAD

**Issue by Scimitaria** [OpenEmu/OpenEmu#4959]
After the latest update, OpenEmu started giving me this message:
OpenEmu must be granted the Input Monitoring permission in order to use the keyboard as an input device.

Removing and re-granting the permission may also resolve keyboard input issues.

and stopped receiving input from my keyboard. I have had that permission on for OpenEmu since I downloaded it a year ago, so I removed and regranted it twice, restarted the computer, then removed and regranted it again. Nothing worked.

I'm using an M1 MacBook Air, if that helps.

- OpenEmu Version: 2.4.1
- macOS Version: 13.6.1

**Comment by clobber** [comment]
Read here: #4952
