### ISSUE TITLE
How to downgrade Arcade Core MAME0.250.0.1？

### ISSUE THREAD

**Issue by maglolok** [OpenEmu/OpenEmu#4961]
The Arcade core for openemu 2.4.1 is MAME0.250.0.1,
I tried downgrading to MAME149, but every time I replace it and start openemu, it automatically upgrades to MAME0.250.0.1.
Is there any way to stop the automatic upgrade? Please advise everyone. Thanks!

（PS: There are too few games that support MAME0.250.0.1, many of them are very old games.🤣）

Thanks again!

**Comment by clobber** [comment]
No. Search Archive.org for a more recent MAME set.
