### ISSUE TITLE
Implement cheat for PlayStation or change your core to support cheats

### ISSUE THREAD

**Issue by deilsoncso** [OpenEmu/OpenEmu#4962]
Is it possible to change the PlayStation core or implement cheats on this core? because several emulators have cheats, and PlayStation games were the ones that most revolutionized cheats (GameShark) at the time. psxfin.exe, ePSXe.exe among others have these native features. Is it complicated to add this feature or does it require changes to the entire PSX emulation project?

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

#2310
