### ISSUE TITLE
Input monitoring does not work on MacOS Sonoma

### ISSUE THREAD

**Issue by pensez-agile** [OpenEmu/OpenEmu#4963]
I used OpenEmu on several MacOS versions with success and pleasure, but I didn't manage to have input working after Sonoma upgrade.

# Steps to reproduce

1. Launch OpenEmu 2.4.1
2. Popup appears asking to enable Input Monitoring for OpenEmu
3. Open system configuration and enable Input Monitoring
4. Relaunch OpenEmu 2.4.1
5. Popup appears again regardless of the status for Input Monitoring (either enabled or disabled)
6. Input does not work, either keyboard or any gamepad that were working before with OpenEmu

# Expected Behavior

1. Popup should not appear if Input Monitoring is enabled
2. OpenEmu does react on keyboard or gamepad input

# Observed Behavior

1. Popup still appears regardless of the status for Input Monitoring
2. Tried to disable then enable did not work either
3. Games (cores) are launching as expected but don't react to input
4. Dialog to change input keys does not react as well

# Debugging Information

- OpenEmu Version: 2.4.1
- macOS Version: Sonoma 14.3

**Comment by clobber** [comment]
Search before opening a new issue.

https://github.com/OpenEmu/OpenEmu/issues/4952#issuecomment-1872921160
