### ISSUE TITLE
Can't use keyboard commands after the last update

### ISSUE THREAD

**Issue by thiagobgtome** [OpenEmu/OpenEmu#4964]
Hi,

After the last update (2.4.1) I can't use the keyboard commands. 

Everytime I try to game the app asks me to enable the permission to use keyboard, but it is already enabled and still doesn't work.

My computer is a MacBook Air M1 (Sonoma 14.2.1).

Anyone with this problem can help me?

thanks.

**Comment by clobber** [comment]
Search before opening a new issue.

https://github.com/OpenEmu/OpenEmu/issues/4952#issuecomment-1872921160
