### ISSUE TITLE
OpenEmu v2.4.1 / MacOS 14.3. Controller mapping with Switch Pro controller doesn't work.

### ISSUE THREAD

**Issue by andrewostrin** [OpenEmu/OpenEmu#4971]
Switch Pro controller is visible and selectable in controller settings, but all buttons are unresponsive.

[x] Input monitoring is enabled for OpenEmu in MacOS security settings.
[x] Controller works as expected in other applications.

# Steps to reproduce:

1) Clean install OpenEmu 2.4.1.
2) Allow input monitoring in MacOS settings on startup.
3) Open controller settings in OpenEmu.
4) Connect Switch Pro controller to Bluetooth, so that it becomes selectable in controller settings for any system.
5) Start mapping buttons - all Switch Pro Controller buttons are unresponsive.

OpenEmu Version: 2.4.1
macOS Version: 14.3

**Comment by dvessel** [comment]
Switch Pro support is included. Make sure you don’t have Steam or any other game that handles game inputs open.

**Comment by andrewostrin** [comment]
> Switch Pro support is included. Make sure you don’t have Steam or any other game that handles game inputs open.

The problem persists on MacOS 14.4.1

Weirdly it's the other way around - when launching OpenEmu after a fresh boot, the controller is unresponsive.

But after launching any other application that utilises the controller (Steam, PCSX2), while OpenEmu is running - it starts working in OpenEmu as well, until disconnected.

**Comment by dvessel** [comment]
I don’t own a Switch Pro controller but I know support is in there. 09b721bf7f Is this an official controller or third-party?

Not sure if this will work since it’s for controllers that are not recognized at all but try going into _**System Settings > Game Controllers**_. Select your controller and add OpenEmu override. There will be a controller compatibility mode which mimics an xbox 360 controller.

**Comment by andrewostrin** [comment]
> I don’t own a Switch Pro controller but I know support is in there. 09b721bf7f Is this an official controller or third-party?
> 
> 
> 
> Not sure if this will work since it’s for controllers that are not recognized at all but try going into _**System Settings > Game Controllers**_. Select your controller and add OpenEmu override. There will be a controller compatibility mode which mimics an xbox 360 controller.

It's an official Nintendo Switch Pro controller.

Not seeing any compatibility settings on Sonoma under Game Controllers and changing user profiles doesn't resolve the issue.
 
Launching another app as described above restores functionality in OpenEmu, until the controller is disconnected.

It seems like some controller initialisation step is failing.

Similar report on Reddit:
https://www.reddit.com/r/OpenEmu/comments/180hzzh/switch_controller_not_working/?rdt=35168

![image](https://github.com/OpenEmu/OpenEmu/assets/8829269/0cb6bbe5-8897-4466-b9a5-f47aade2f6cb)

**Comment by dvessel** [comment]
It’s only visible when you add an app. It can’t be enabled globally. Make sure you undo it if it doesn’t work.

<img width="699" alt="SCR-20240401-ohyr-2" src="https://github.com/OpenEmu/OpenEmu/assets/126473/f02ab7cd-15b1-4164-a5d0-51d31511bf37">


And it looks like you modified the default profile for the Pro controller. Try resetting it to the default. The controller framework might be interfering with OpenEmu.

**Comment by andrewostrin** [comment]
No effect both with the default profile and the 360 override.

**Comment by J-rg** [comment]
The name of the controller must be [“Pro Controller”](https://github.com/OpenEmu/OpenEmu-SDK/blob/3d2214e328668697ce771d657a05076455ddc899/OpenEmuSystem/OESwitchProControllerHIDDeviceHandler.m#L342) for it to be recognized as a Switch Pro Controller.

**Comment by andrewostrin** [comment]
> The name of the controller must be [“Pro Controller”](https://github.com/OpenEmu/OpenEmu-SDK/blob/3d2214e328668697ce771d657a05076455ddc899/OpenEmuSystem/OESwitchProControllerHIDDeviceHandler.m#L342) for it to be recognized as a Switch Pro Controller.

That solved it, thanks! 
Renamed controller to "Pro Controller" in MacOS settings, mapping now works without additional steps.
