### ISSUE TITLE
Open emu wont register the keyboard input

### ISSUE THREAD

**Issue by Paiineapple** [OpenEmu/OpenEmu#4973]
Hi, i just download the latest version of openemu, and it told me that I had to allow the app in the keyboard input, I went to the configurations and it was already allow.

i tried to eliminate the app and re install it again, and it still is allow, but whenever I start the app, it wont register,

- OpenEmu Version: 2.4.1
- macOS Version: MacOs sonoma version 14.2.1

**Comment by taylorling** [comment]
Confirm same issue here using same OS. Controller works fine, but not keyboard.

Upon startup, there is also a dialog that seems incomplete, text seems like placeholder to me.
<img width="433" alt="Screenshot 2024-01-28 at 9 49 50 AM" src="https://github.com/OpenEmu/OpenEmu/assets/7766387/2d38559e-d26a-4381-b973-c300dd0b049a">

**Comment by clobber** [comment]
[Contributing guidelines](https://github.com/OpenEmu/OpenEmu/blob/master/CONTRIBUTING.md) - "Please search before opening a new issue."

Solution: https://github.com/OpenEmu/OpenEmu/issues/4952#issuecomment-1872921160
