### ISSUE TITLE
Input Monitoring issue with Mac

### ISSUE THREAD

**Issue by Haydencook30** [OpenEmu/OpenEmu#4974]
Summary of issue

Opening OpenEmu brings me to saved states but will have a pop up telling me to turn on Input Monitoring

When turning on Input Monitoring it does save and shows that its on for OpenEmu (and off for Minecraft and other apps) yet popup still displays and I cannot move in any games.

- OpenEmu Version: 2.4.1
- macOS Version: Ventura 13.6.3

**Comment by clobber** [comment]
Search before opening a new issue.

https://github.com/OpenEmu/OpenEmu/issues/4952#issuecomment-1872921160
