### ISSUE TITLE
Input stopped working after update.

### ISSUE THREAD

**Issue by mazeto** [OpenEmu/OpenEmu#4997]
![image](https://github.com/OpenEmu/OpenEmu/assets/7754903/a452fb12-8455-4d12-a6e0-29c8d62a7ff0)

It was working normally, but after the update, it stopped to work.

I already gave it Input Monitoring privileges on System Preferences, but it still doesn't work. I reinstalled the program, and nothing.

I did read the troubleshooting page, https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems, and the input troubleshooting page linked there, and nothing.

# Steps to reproduce

1. Open openemu, open game. Boom, no input.

Expected Behavior

1. Keyboard button pressed, Mario smashes Goomba.

# Observed Behavior

1. When I start the program, a pop up window says "ALERT_INPUT_MONITORING_HEADLINE", "ALERT_INPUT_MONITORING_PART1", and "ALERT_INPUT_MONITORING_PART2_MONTEREY".

# Debugging Information

- OpenEmu Version: 2.4.1.
- macOS Version: 12.7.3, not patched, official hardware.

**Comment by yokoboko** [comment]
I'm experiencing the same issue.

**Comment by Kirb-tech** [comment]
I am also having the same problem:   When I open the preferences and give it the permissions, it still does not work, and it still gives this pop up. I did not have any problems like this before, but when I just recently updated it I started to have this problem and nothing will work.
<img width="592" alt="Screenshot 2024-03-29 at 3 21 47 PM" src="https://github.com/OpenEmu/OpenEmu/assets/156863928/7b1fcc26-db47-40db-a62e-41c2b9196ea4">

I have removed and regranted the permissions, but it has still not worked
I also was on MacOS Ventura when this started and when I updated it to Sonoma, I have still had the same issue

**Comment by Kirb-tech** [comment]
They've had this problem before, Here's a fix that helped me. 
https://github.com/OpenEmu/OpenEmu/issues/4535#issuecomment-862861728

**Comment by mazeto** [comment]
Solved. You gotta open Preferences, Security & Privacy, Privacy tab, Input Monitoring, Select OpenEmu.app, minus icon "-", reopen Open Emu, and give it Input Monitoring permission again.
