### ISSUE TITLE
Add further Jolly Good Emu Cores

### ISSUE THREAD

**Issue by WingofaGriffin** [OpenEmu/OpenEmu#5001]
Taking a look at the repo, it seems that the jgemu project is a good source of emulation cores for this project: https://jgemu.gitlab.io/

It seems that there are a few not currently integrated, most notably:
- Geolith for NeoGeo
- SameBoy as an alternative to Gambatte (more updated and Metal compatible)
- melonDS as an alternative to DesMuMe
- Cega

I still need to teach myself Swift to see if I would be able to help add these cores (and others not in the jgemu project), though wanted to ask about the current state of things. Small ones like Pico-8, Tic80, Fbneo, and MSX seem simple as well.

**Comment by MaddTheSane** [comment]
Most of the cores (at least the parts that interact with OpenEmu. What underlying emulators are actually written in is usually C++, but pure C is not uncommon) are actually written in Objective-C. Still, that shouldn't prevent a Swift core from being written.

**Comment by clobber** [comment]
@WingofaGriffin We don't need a bunch of core update requests opened or similar threads. We will add or update on our own time.
