### ISSUE TITLE
Games run ok but sound cuts of after a few mins of usage!!!! WHY

### ISSUE THREAD

**Issue by C0deName007** [OpenEmu/OpenEmu#5010]
Summary of issue

Read https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Reporting-problems

# Steps to reproduce

1. Describe step-by-step
1. How to cause the problem
1. leaving nothing out
1. too much information is better than too little

# Expected Behavior

1. Describe what
1. you want to
1. happen

# Observed Behavior

1. Describe what you see
1. Actually happen
1. when you follow the steps above

# Debugging Information

- OpenEmu Version: ???
- macOS Version: ???

**Comment by MaddTheSane** [comment]
Unless you provide more information (Your computer, the game you're trying to play, the system you're trying to play it on), we can't help you.
