### ISSUE TITLE
change NES aspect ratio

### ISSUE THREAD

**Issue by BaronAWC** [OpenEmu/OpenEmu#5018]
I'm playing NES Tetris and the blocks appear to be squished down more than they should. it's small but should be pretty easy to notice.

![Screenshot 2024-05-11 at 3 37 16 PM](https://github.com/OpenEmu/OpenEmu/assets/43506286/0271b732-c380-41bf-ae2a-386a222c1e70)

from what i know, the emulator does this because it's how it would look on actual hardware. while i understand that, i hope you can also understand that i don't really want to play tetris, a game with squares, with not-quite-square pieces.

i've tried to figure out where to change the aspect ratio but i have been unable to do so. by counting the number of blocks in the game's background, i think i'm looking for a 16:15 ratio.

**Comment by robotoad** [comment]
There are currently no plans to change this behavior. OpenEmu displays graphics as they originally appeared on televisions.
