### ISSUE TITLE
Is it possible to manually install FInalBurn Neo (Arcade) core?

### ISSUE THREAD

**Issue by Azzhoe** [OpenEmu/OpenEmu#5036]
I would like to install and use this core for some of my arcade roms. I've seen a few people were able to install it manually but can't find any instructions on how to do this. Would the devs please consider including this in the main package and also give us the option to specify which core the game will load with during launch if they both belong to the same categorie, such as Arcade. Because under that categorie you can have many cores such as MAME 2003, MAME 0.250, FBNeo, etc. You're able to do this on Retroarch and I would love to see something like this being added to OpenEmu.

**Comment by clobber** [comment]
No. We're not going to maintain multiple Arcade core plugins. MAME is more than enough.
