### ISSUE TITLE
How to contribute cover art for games? especially room hacks

### ISSUE THREAD

**Issue by stephane-archer** [OpenEmu/OpenEmu#5040]

**Comment by digamejh** [comment]
Just drag the image* on to the placeholder in the OpenEmu interface

* You used to be able to just drag the image itself (from, say, a browser window) but now you have to save the image to your hard drive first...

**Comment by stephane-archer** [comment]
Is there a way to add it to same kind of database for others ? I imagine you get the artwork from somewhere when we import a ROM?

**Comment by clobber** [comment]
> Is there a way to add it to same kind of database for others ? I imagine you get the artwork from somewhere when we import a ROM?

It's better to state which game(s) you're having issue with so we can understand what isn't displaying cover art. There are situations where some ROMs may not.

**Comment by stephane-archer** [comment]
Most Pokémon ROM hack, they are unofficial ROM so I don't expect you to be up to date on this, but if I can update my cover art while benefiting others, it is cool if I can contribute. Any way to add cover art for others ?

**Comment by clobber** [comment]
> Most Pokémon ROM hack, they are unofficial ROM so I don't expect you to be up to date on this, but if I can update my cover art while benefiting others, it is cool if I can contribute. Any way to add cover art for others ?

We don't add cover art for unofficial games or hacks. As suggested, add your own by drag and dropping an image.
