### ISSUE TITLE
iCade Support

### ISSUE THREAD

**Issue by rosskimes** [OpenEmu/OpenEmu#514]
It would be really cool to have support for some of the different flavors of the [ThinkGeek iCade](http://www.ionaudio.com/products/gaming/mobile-device-gaming). They are essentially Bluetooth keyboards that send particular keys when buttons are pressed and released. For example, when you press the up arrow it sends a pulse of a single W key and then sends an E when you let up.

The main difference between this and a normal keyboard is the fact that it only sends a single pulse when you press and hold instead of continuously sending the key over and over again.

[Documentation can be found here](http://www.ionaudio.com/products/details/icade).

**Comment by arenita510** [comment]
Hola, buenas tardes, tengo una mac del 2017 con High Sierra, y al intentar conectar mi 8bitdo Zero, me pide que coloque una numero como si fuera un teclado, el problema es que solo me da 2 seg para hacerlo, y es por eso que no puedo enlazar un control
