### ISSUE TITLE
Select Audio Output Device

### ISSUE THREAD

**Issue by rjungemann** [OpenEmu/OpenEmu#546]
It would be useful to me if the audio output device [could be chosen](http://stackoverflow.com/questions/2075989/how-can-i-change-the-audio-output-device-in-objective-c_) either in Preferences or in the floating toolbar while a game is running. That way I can route the audio using Soundflower or similar applications.

Right now, OpenEmu lets you route its video using Syphon, but it would be nice to be able to route the audio as well.

The intent is to run music ROMs and be able to post-process them live using other applications such as Max, and also to process audio and video from OpenEmu in tandem.

**Comment by pencilcheck** [comment]
How do I enable this feature in the latest openemu build? It seems like the DS doesn't output sound to bluetooth. https://github.com/OpenEmu/OpenEmu/issues/2979
