### ISSUE TITLE
Confusion regarding Mupen64Plus

### ISSUE THREAD

**Issue by michaelratner** [OpenEmu/OpenEmu#560]
Beta tester here, so pardon me for not knowing much about the development process.

I see in the source code that there is a folder for Mupen64Plus that is regularly updated. However, in the latest beta, there is no trace of an N64 core. Is this intentional? I see that there are people discussing bugs in Mupen64Plus here, and I was wondering how if I'd be able to add the N64 core to OpenEmu.

Again, sorry for my cluelessness.

**Comment by Emuguy473** [comment]
Is it possible we can have another update of OpenEmu with the Glide64 plugin inserted into Mupen64Plus? Or can we just do it manually ourselves on OpenEmu? Someone please help me!!
