### ISSUE TITLE
Import option for saves/freezes

### ISSUE THREAD

**Issue by bensowden** [OpenEmu/OpenEmu#580]
It would be great to be able to import saves/freezes. I have been using SNES9x for a while and have a number of saves/freezes for the games already (quite a few games I am part way through). Looking at the saves/freezes folders it seems openemu uses its own format so it would be great to be able to import my old saves to this format so I don't have to go back to the indiviual emulator to play my old saves.

**Comment by clobber** [comment]
Nah
