### ISSUE TITLE
Control UI with controller

### ISSUE THREAD

**Issue by bahamas10** [OpenEmu/OpenEmu#581]
First of all, this project is awesome!

I would love to be able to control the UI with my controller. I envision a mac mini hooked up to my tv, dedicated to OpenEmu, controlled fully by my NES and N64 controllers.  I'll take a look at the source later tonight to see if it's something I could implement myself.

**Comment by GeoffreyPlitt** [comment]
Another year without this essential feature.

**Comment by mrvacbob** [comment]
#401
