### ISSUE TITLE
Can't compile in ML 10.8.3 - OpenEmuBase.h not found.

### ISSUE THREAD

**Issue by squiter** [OpenEmu/OpenEmu#583]
Hey guys, I'm trying to compile OpenEmu in my MacMini with Montain Lion 10.8.3 but when I click to Build for profiling the Xcode show me an error:

```
'OpenEmuBase/OpenEmuBase.h' file not found
```

This error was appeared in file OpenEmu_Prefix.pch

**Comment by ih2502mk** [comment]
if you're cloning using terminal do 
```
git clone --recursive git@github.com:OpenEmu/OpenEmu.git
```
or if you already have cloned it "incorrectly" run this to pull in the submodules
```
git submodule update --init --recursive
```
