### ISSUE TITLE
Nintendo64 controller screen hides set buttons, maps controls strangely.

### ISSUE THREAD

**Issue by jackmcconnell** [OpenEmu/OpenEmu#589]
After compiling the source code and running OpenEMU I tried mapping the controls using a USB - N64 adapter and an original N64 controller for Player 1 to USB Device 1 and Player 2 to USB Device 2.

On clicking on the first box in the Preferences to map a button on the controller to, pressing a button on the controller would jump through the selections a bit too quickly. It would also not show the button that the control has been assigned to. I had to go back and, very slowly and carefully, press the controls and get them to set. After a lot of trial and error I was able to set the controls for both controllers and save them by closing the Preferences window. 

The problem is, when playing a game, pressing and holding a button does not work as expected. Take Super Mario 64 for example: pressing and holding Z should make Mario crouch but instead, it just makes him crouch once and then stand up again immediately. Moving the analogue stick around also makes him 'judder' about, often in an incorrect direction.  

I had no crashes whilst performing any of the above snd have successfully used this adapter and controller with previous versions of OpenEmu. 
My first thought is that it appears the controller is set too sensitive.

**Comment by clobber** [comment]
Issues using adapters should be resolved as of OpenEmu 2.2.
