### ISSUE TITLE
Feature Request: Alternate action for mouseover menu when playing DS games

### ISSUE THREAD

**Issue by Project538** [OpenEmu/OpenEmu#592]
Was trying out the Nintendo DS emulation, and realized that the small menu overlay appears at the bottom while mousing over the screen. While playing in most console emulators, this is a nice feature, since I wouldn't normally be using the mouse. However, the mouse is how you interact with the touch screen when emulating DS games. OE's mini-menu could potentially get in the way of gameplay functions and would be a nuisance if playing a game that requires frequent touchscreen interaction. If possible, it'd be nice to have that pop-up menu be activated in a different way when playing DS games

**Comment by FluffyCode** [comment]
Alternative suggestion - what about an option (somewhere in the settings) to orient the screens side-by-side? This way, when mousing over the emulator window, the cursor can be used to interact with the touchscreen window or the options bar, but the bar won't be in a position to interfere with the touchscreen.
