### ISSUE TITLE
Rom's languages

### ISSUE THREAD

**Issue by ghost** [OpenEmu/OpenEmu#603]
It would be a good thing to add, into preferences, a setting about the default language due some roms (likes European roms) contains more than 1 language (Deutsch, Italian, French, English). I'm italian and in some games i can't select my default language. 
ps. Sorry for my bad english. :)

**Comment by angel7777zzz** [comment]
clobber r ur brain fking damaged?
We support u to find bugs and promote ur fking app, for repay, u must fking help us to build good using experience. 
U just fking say that's impossibe
