### ISSUE TITLE
Application will not build (OpenEmuBase.h not found) 

### ISSUE THREAD

**Issue by tc728** [OpenEmu/OpenEmu#656]
Latest version. Attempted with (git clone and .zip) + following instructions. It starts to build all and then gets an error stating that OpenEmuBase.h is not found.

How do I get github to give me a working version of OpenEMU? I forgot to save it when I reformatted everything. 

This is the issue.
http://i.imgur.com/38IZ2Gh.png

**Comment by Avelez1998** [comment]
I don't get this. This is my first time doing something like this. Clobber, I'm trying to update my Mednafen core. But this keeps on happening.
