### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by scottsmedley** [OpenEmu/OpenEmu#659]
Using Mountain Lion 10.8.4 and just compiled the latest source code today (4th June at 11pm GMT). Keyboard is not working at all as a controller, meaning I am unable to play any games or even change the default controls.

**Comment by zachfedor** [comment]
Can reproduce as well. Running OpenEmu v. 1.0.4 on OS X Yosemite v. 10.10.3 with Chrome v. 43. Occasionally OpenEmu will not register any keyboard input, not even to change the button layout in the preferences. Plugging in a control is a workaround, but the keyboard doesn't work after unplugging it. Restarting both OpenEmu and Chrome solves the problem.
