### ISSUE TITLE
Image freezes when connecting to TV through HDMI.

### ISSUE THREAD

**Issue by PackAttack91** [OpenEmu/OpenEmu#714]
When I mirror the image between my TV and Macbook Pro I am able to start the emulator up just fine, but when I attempt to play a game the image freezes.  The sound continues fine and I can hear the game making sounds as if I am putting in the correct inputs, it just doesn't show.

I am able to do things like go fullscreen and then back out of fullscreen and it will advance the image, but stay frozen there.

**Comment by clobber** [comment]
Ancient
