### ISSUE TITLE
Build Fails Using xCode 5.0

### ISSUE THREAD

**Issue by retrog** [OpenEmu/OpenEmu#749]
I'm using xCode 5.0 on OSX 10.8.5 and the build fails saying xCode can't find OpenEmuSystem.h.  I've searched via finder and can't find this file either.  Below is a screenshot of the errors.
![screen shot 2013-10-26 at 9 53 17 am](https://f.cloud.github.com/assets/5249740/1412122/6b699618-3dc8-11e3-98c7-654b9026cea6.png)
I'm guessing this is a PEBKAC error but I'm a total novice at this.
Any help appreciated.  =)

**Comment by Avelez1998** [comment]
How can you fix an "Apple Mach-O Linker (ID) Error"?
