### ISSUE TITLE
Opening roms from the command line does not work

### ISSUE THREAD

**Issue by jacktourist** [OpenEmu/OpenEmu#755]
Using terminal command
```
open romname.ext
```
does nothing. It just opens OpenEmu, but I must manually double-click the game.
Bonus Issue: When I first open a game not in the library, it imports correctly from the command line, and there's a dialog box asking if I want to start playing now. Clicking Yes does nothing. I suspect these failures are related.

**Comment by cyco** [comment]
Fixed! Not sure when…
