### ISSUE TITLE
NES Zapper or SNES Mouse compatibility.

### ISSUE THREAD

**Issue by drewbyhk** [OpenEmu/OpenEmu#761]
Could we add NES Zapper and SNES Mouse compatibility by any chance? I mean a bunch of my games have to use the zapper and mouse to play it. Could we add it?Thanks!

**Comment by jurassicjordan** [comment]
when will this post be available? and how can I get the mouse to work for SNES for games like mario paint?

**Comment by jurassicjordan** [comment]
also, can you add a R.O.B. ai for the NES?
