### ISSUE TITLE
Retrolink N64 Gamepad support

### ISSUE THREAD

**Issue by beber666** [OpenEmu/OpenEmu#793]
Hello,

Same asking for my new Retrolink N64 Gamepad
http://www.aliexpress.com/item/Free-shipping-new-arrival-high-quality-N64-Controller-Wired-USB-Controller-for-PC-poly-bag-brand/686492262.html

The Game Pad is recognized well by Open Emu, but I can't map any control, and the pad doesn't work in game

![3](https://f.cloud.github.com/assets/6094638/1782930/72a534fc-68b9-11e3-89d6-d78c7c3c280e.jpg)

Here are some informations of it:

![1](https://f.cloud.github.com/assets/6094638/1782922/59cf6218-68b9-11e3-8813-c1bf37de6bc0.jpg)

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>device type</key>
    <string>gaming</string>
    <key>hid descriptor</key>
    <data>
    BQEJBKEBoQJ1CJUFFQAm/wA1AEb/AAkwCTEJMgkyCTWBAnUElQElB0Y7AWUUCTmBQmUA
    dQGVDCUBRQEFCRkBKQyBAgYA/3UBlQglAUUBCQGBAsChAnUIlQdG/wAm/wAJApECwMA=
    </data>
    <key>hid usage</key>
    <integer>4</integer>
    <key>hid usage page</key>
    <integer>1</integer>
    <key>interface number</key>
    <integer>0</integer>
    <key>location id</key>
    <integer>337641472</integer>
    <key>product id</key>
    <integer>6</integer>
    <key>product name</key>
    <string>Generic   USB  Joystick  </string>
    <key>product version</key>
    <integer>265</integer>
    <key>readable inputs</key>
    <integer>18</integer>
    <key>transport</key>
    <integer>1</integer>
    <key>vendor id</key>
    <integer>121</integer>
    <key>vendor id source</key>
    <integer>1</integer>
    <key>vendor name</key>
    <string></string>
</dict>
</plist>

Thanks for your help

**Comment by mvmckinnon** [comment]
I am having the same problem... was this ever solved?
