### ISSUE TITLE
Keyboard completely refuses to work

### ISSUE THREAD

**Issue by megaminxwin** [OpenEmu/OpenEmu#798]
I've tried fixing it using [659](https://github.com/OpenEmu/OpenEmu/issues/659) and [772](https://github.com/OpenEmu/OpenEmu/issues/772). I've recompiled it twice both using the GUI and the CLI. I've deleted all preferences that I'm aware of, but the keyboard just _will not work_. Ever. No matter what I do, it won't pick up the controls, it won't let me change the controls, it just absolutely refuses to work. I'm completely at a loss now.

I'm running OS X Mavericks 10.9.1 on a mid-2010 13" MacBook Pro, compiling using the very latest versions, downloaded straight from the source.

**Comment by davidssmith** [comment]
DOSBox can steal the keyboard from OpenEmu also. I had this same problem with a game in DOSBox open before I started OpenEmu.  Stopping DOSBox fixed it.

**Comment by lukejr** [comment]
I quit Parallels 11 on the keyboard was recognised.

**Comment by Ghostavio** [comment]
I have no application opened and the keyboard still doesn't work :/

**Comment by Austin299792** [comment]
Ghostavio - Do you have any anti-virus software running, or any application that starts in the background when you log into your computer?

**Comment by clobber** [comment]
https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems
