### ISSUE TITLE
Enhance Network Share Support

### ISSUE THREAD

**Issue by MikeMayer** [OpenEmu/OpenEmu#804]
It would be nice if there was a way to support a network share that is the super set of a collection of games and the OpenEmu library proper lived there.

Perhaps the library could be shared across a couple computers on the same network.

I was thinking it would be nice if on-demand games could be loaded to a local OpenEmu library for mobile systems.

I know this is a non-trivial feature request but it would be useful for at least me.

**Comment by cyco** [comment]
Closing for #898.
