### ISSUE TITLE
'System' column hidden but selected in list view

### ISSUE THREAD

**Issue by okdana** [OpenEmu/OpenEmu#809]
Probably related to issue #262 (?):

When you right-click on the column headers in the list view (with the default configuration), the column 'System' is selected, even though it's not actually shown in the list.

Disabling and re-enabling it makes it re-appear.

Not sure if the goal was to eliminate this column for non-collection views entirely or just to make it unticked by default, but it seems like incorrect behaviour either way.

**Comment by J-rg** [comment]
Fixed in b9bd8b1 / 2.3.2.
