### ISSUE TITLE
linux port

### ISSUE THREAD

**Issue by monotek** [OpenEmu/OpenEmu#822]
would be nice you would also port to linux...

**Comment by Forgen** [comment]
Has anyone forked this with the intent of re-implementing it for cross platform (Windows/Linux)?

**Comment by robotoad** [comment]
See clobber's comment.

**Comment by Forgen** [comment]
@robotoad I understand @clobber's comment, but it means he is not interested in pursuing it.  It doesn't mean it cant be done :).  Of course, it means starting the implementation-side from scratch, but it looks like just the high-level UI and architecture is worth keeping.  So I forked it with the intent of starting to poke around the code.

**Comment by mrvacbob** [comment]
The equivalent project is called Retroarch.
