### ISSUE TITLE
Changing core without pausing causes unrecoverable non-responsiveness

### ISSUE THREAD

**Issue by okdana** [OpenEmu/OpenEmu#824]
When a game is running, if i try to change the core via the cog icon > Select Core, the application will become non-responsive unless i first pause the emulation.

By non-responsive i don't mean that it beach-balls or anything — it responds to button presses, i can still access the menu and the Preferences dialogue, it still pops up the little 'are you sure' message when i try to quit. I just can't get out of the game.

If i press the red power button, the pause/unpause button, or the restart button, or even if i try to do Close Window from the menu, it *acts* like it's accepted my input, but it just doesn't do anything. I have to exit the application and restart in order to play the game or view the library again.

I have had this happen with both SNES and Game Boy games. The obvious correlation there is Higan, although the problem occurs whether i'm switching to Higan or from it.

If i first pause the game by pressing the little pause button on the HUD, this lock-up doesn't seem to occur (or at least it must be much less likely).

OpenEmu 1.0 / OS X 10.9 / MacBookAir4,1

**Comment by lloeki** [comment]
I have the same issue when trying to switch (from FCEU to Higan or Nestopia) in 1.0.4. Didn't think about pausing before reading this either (which works as a workaround).
