### ISSUE TITLE
Missing covers

### ISSUE THREAD

**Issue by franciscolourenco** [OpenEmu/OpenEmu#827]
There seem to be some major covers missing..
_snip_

![http://i.imgur.com/ZYXD7iQ.png](http://i.imgur.com/ZYXD7iQ.png)

Who maintains the database? Is it possible to contribute?

**Comment by grandpixel** [comment]
Using No-Intro roms, only loaded 3 N64 games so far, Super Mario 64, Mario Kart 64, and Super Smash Bros. None are downloading cover art.

**Comment by clobber** [comment]
@grandpixel See #3429
