### ISSUE TITLE
Game-pad control bindings not editable after Preferences window closed

### ISSUE THREAD

**Issue by okdana** [OpenEmu/OpenEmu#835]
Not sure if this is specific to my controller/adaptor, but i've noticed an issue with controls:

I am only able to modify the game-pad control bindings the first time i open the Preferences window. After it's closed that first time, the controls are no longer editable until i restart the application.

Steps to replicate:
1. Shut down and restart OpenEmu
2. Immediately go to OpenEmu > Preferences > Controls
3. Select the controller from the Input menu
4. Modify bindings as desired — everything works as expected
5. Close the Preferences window
6. Immediately re-open Preferences and go to Controls again
7. Select the controller again
8. Try to modify bindings again — the controls are highlighted, but there is no response to input from the pad

Throughout this, the controller continues to work fine with all cores. I just can't change the bindings (for any system).

I don't have any of the supported controllers listed on the wiki, so i can't verify if this is controller/adaptor-specific. I am using a [Trio Linker Plus II](http://www.hkems.com/product/ps2/TrioLinkerPlus2.htm), which does work great otherwise.
- OpenEmu 1.0
- OS X 10.9
- MacBookAir4,1

**Comment by CalebeNP** [comment]
I'm using the v2.0.4 and it is still a problem... =/

**Comment by clobber** [comment]
@CalebeNP Mmm no I can't replicate that here. Are you having a different issue? See the [input guide here](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems).

If so, open a new ticket with exact steps to replicate the problem. This one would be unrelated.
