### ISSUE TITLE
CRASHES Everytime.

### ISSUE THREAD

**Issue by johndupras** [OpenEmu/OpenEmu#854]
Hello,

I believe I have a bad rom file. HOW and WHERE are the rom files stored?!?! 

For example iTunes saves the files in a Music folder. I know. Sound crazy right. Way to simple.

Where is this application storing anything. I've gone through my system looking through the library and found NOTHING. I've tried downloading it again and same problem happens, it looks for this magical mythical library, which I cannot find on my machine.

And then it crashes.

This is not user friendly at all.

Thanks,
John

**Comment by krakoukass77** [comment]
I tried to follow the steps to finally solve my issue (crash when launching any rom) but I noticed something while trying to do so : there is NO Openemu folder in the ApplicationSupport. Is there a reason for that ? It might be linked to the crash issue no ?
I tried to create an OpenEmu folder by myself and to relaunch openemu but it still crashes the same way...
Any clue ?

It just seems very odd (and frustrating) that some of us aren't able to solve this crash issue.

**Comment by clobber** [comment]
@krakoukass77 Please stop posting in two-year old issues completely unrelated to your own. Go back to yours and actually read what was posted to you.
