### ISSUE TITLE
Missing localised PC Engine controller graphic

### ISSUE THREAD

**Issue by okdana** [OpenEmu/OpenEmu#862]
I noticed that all of the systems currently available in 1.0 have localised controller images, except for the PC Engine — there is only the (US) Turbografx-16 controller.

A high-resolution image of the PC Engine controller is available here:

http://upload.wikimedia.org/wikipedia/commons/b/b6/PC-Engine-Console-Set.jpg

Note that the image shows the _original_ PC Engine controller, which lacked turbo switches. Later versions looked exactly the same but added the switches like the ones shown in the Turbografx-16 image ([like this](http://farm3.staticflickr.com/2658/5703369060_345082f3a1_o.jpg)).

**Comment by clobber** [comment]
83505e57bbc4055f952a50bbf997f5bc7887514d
