### ISSUE TITLE
Doesn't respond to PS4 DualShock 4 after assigning L2 or R2 as an input.

### ISSUE THREAD

**Issue by ReaLgoesWronG** [OpenEmu/OpenEmu#867]
When using the Dualshock 4 over Bluetooth, assigning either L2/R2 triggers will cause OpenEmu to not respond to the controller anymore. Every other button works fine but OpenEmu need to be restarted for the DS4 to work if R2/L2 was assigned.

**Comment by MScoutsDCI** [comment]
This doesn't seem to be entirely fixed.  I'm running version 1.0.4 and I just got a ps4 controller and I'm having the same issue.  I checked the plist file just in case and it looks correct but the issue still persists.  I can map the controls fine until I get to the triggers and then it becomes unresponsive.

**Comment by christopherowen** [comment]
I cannot map the L2 or R2 buttons on my DS4 either in 1.0.4 dev.  I have confirmed that Controller-Database.plist has been set as in c648d0a.

**Comment by christopherowen** [comment]
to get the l2 and r2 buttons working again, I 

1) Reverted the change in c648d0a
2) Stopped OpenEmu
3) Deleted ~/Application Support/OpenEmu/Bindings Configurations/Default.oebindings 
4) Started OpenEmu

**Comment by MScoutsDCI** [comment]
Tried those steps, that made no difference for me.  Sometimes if I just sit and press L2 or R2 over and over again I'll get lucky and it will register one time.  Once it's set, it works flawlessly in games, but getting it set is extremely difficult and entirely dependent on luck it seems.

**Comment by zachcoyle** [comment]
Could you try replacing your plist at `OpenEmu.app/Contents/Resources/Controller-Database.plist`
with this one http://cl.ly/0l1Z3B3s2J1u/Controller-Database.plist and then try mapping L2 and R2?

**Comment by MScoutsDCI** [comment]
That did it!  I see you added a second section for L2 and R2 in the plist file. I guess that did it. Thanks!

**Comment by paulsobrien** [comment]
Hi, I was having the same problem with the PS4 dualshock L2/R2 buttons running OpenEmu 1.04
those two buttons were not being recognised wired or wireless.

I followed zachcoyle's suggestion & now they work, thanks for posting the .plist
