### ISSUE TITLE
PC Engine CD loading

### ISSUE THREAD

**Issue by z00p** [OpenEmu/OpenEmu#869]
I'm having trouble loading PC Engine CD ROM image files into OpenEmu (experimental build). The files are cue and iso format. I can get the image to appear in the library if I change the file extension iso to bin but then launching a title will either show to error messages "The operation could not be completed" and "Couldn't communicate with a helper application" or occasionally crash the emulator. I'm guessing this is probably an issue with the format of the images files I'm using. I can post an example cue file if that helps.

Thanks
John

**Comment by kevinw** [comment]
I'm having this problem trying to play Rondo of Blood. The CUE file *looks* accurate. Does OpenEMU log errors importing the CUE file somewhere?

**Comment by clobber** [comment]
@kevinw That's vague. Please describe what the problem actually *is* and copy and paste the contents of your cue sheet. Also, the currently shipped version of Mednafen alongside of OpenEmu cannot yet read WAV files for playing. The new, but not yet shipped, version can.

**Comment by jedijon** [comment]
Hopefully this is the right place for this question, seems to fit with the general .cue file discussion. 

I'm new to this whole emulation thing and have been having trouble getting a pc engine .cue file set up properly to be read by the emulator. I am attempting to use either ISO/MP3 or ISO/WAV (I've tried both) with no success. When I strip the audio out of the .cue the emulator fires up and runs the ISO (after starting from the system 3.0 boot screen). Of course this works with sound effects and gameplay, but no music. 

If I leave the audio references in the .cue the emulator fails to load the game... With nothing put into the log file. Can anyone point me to an example of a "working" cue file? I've scoured the web and haven't been able to find any info on the correct syntax for these files.

Thanks in advance for any help. I'm not at home at the moment, but if it's helpful I can post an exempt from my non-functioning .cue later on.

**Comment by clobber** [comment]
@jedijon The [CD Guide](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-CD-based-games) states that "MP3 is NOT supported" so that is your first hint. The best advice to you would be to find another dump of the game; one where you do not need to fiddle around with a broken cuesheet or that contains MP3 audio tracks.

**Comment by jedijon** [comment]
Thanks clobber. I assumed that would be the case, but hadn't come across the guide you pointed me too. As I mentioned, I also tried converting the MP3 files to WAV, but that didn't work. I don't think the .cue sheet should need to be modified if the formatting is all WAV (it references the rest of the files as WAV and ISO (which I should now have after converting the MP3 files). 

Per your understanding the ISO/WAV combo should work, correct? I'm not completely off in the weeds? I understand you point w.r.t. the simplest solution is to get ahold of another dump with WAV audio, but the copy of the disk I've got is scratched and produces errors when I attempt to dump it. So I'm trying to work with what I've gotten access too. 

Thanks again for your help.

**Comment by jedijon** [comment]
By the way, the syntax in my .cue sheet matches this from the CD guide (different game, but same syntax):

Single binary track with WAVE audio track file

FILE "Castlevania - Symphony of the Night (USA) (Track 1).iso" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "Castlevania - Symphony of the Night (USA) (Track 2).wav" WAVE
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00

**Comment by clobber** [comment]
If using OpenEmu 2.x (the only version we support) then the guide is really hard to miss (we keep it in your face until a CD-supported library has a game in it). In fact, if you aren't using OpenEmu 2.x, then you definitely won't be able to get WAV audio tracks working with the Mednafen core plugin.

Anyway, the simplest solution is to get ahold of another dump that doesn't have MP3 *or* WAV audio tracks and I promise if you just google enough you will find it.

It's a futile effort to play guessing games with the cuesheet if you don't have the original one that came with your rip -- or if something else is wrong. The example you posted above is wrong for PCE CD games. They often include audio as the very first track and can have their binaries split up, for example:

```
FILE "01 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 01 AUDIO
    INDEX 01 00:00:00
FILE "02 Akumajou Dracula X - Chi no Rondo (J).iso" BINARY
  TRACK 02 MODE1/2048
    PREGAP 00:03:00
    INDEX 01 00:00:00
FILE "03 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 03 AUDIO
    PREGAP 00:02:00
    INDEX 01 00:00:00
FILE "04 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 04 AUDIO
    INDEX 01 00:00:00
FILE "05 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 05 AUDIO
    INDEX 01 00:00:00
FILE "06 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 06 AUDIO
    INDEX 01 00:00:00
FILE "07 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 07 AUDIO
    INDEX 01 00:00:00
FILE "08 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 08 AUDIO
    INDEX 01 00:00:00
FILE "09 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 09 AUDIO
    INDEX 01 00:00:00
FILE "10 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 10 AUDIO
    INDEX 01 00:00:00
FILE "11 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 11 AUDIO
    INDEX 01 00:00:00
FILE "12 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 12 AUDIO
    INDEX 01 00:00:00
FILE "13 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 13 AUDIO
    INDEX 01 00:00:00
FILE "14 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 14 AUDIO
    INDEX 01 00:00:00
FILE "15 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 15 AUDIO
    INDEX 01 00:00:00
FILE "16 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 16 AUDIO
    INDEX 01 00:00:00
FILE "17 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 17 AUDIO
    INDEX 01 00:00:00
FILE "18 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 18 AUDIO
    INDEX 01 00:00:00
FILE "19 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 19 AUDIO
    INDEX 01 00:00:00
FILE "20 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 20 AUDIO
    INDEX 01 00:00:00
FILE "21 Akumajou Dracula X - Chi no Rondo (J).wav" WAVE
  TRACK 21 AUDIO
    INDEX 01 00:00:00
FILE "22 Akumajou Dracula X - Chi no Rondo (J).iso" BINARY
  TRACK 22 MODE1/2048
    PREGAP 00:03:00
    INDEX 01 00:00:00
```

So again, sorry, the best advice is to find another rip of the game. You should really do that.

**Comment by jedijon** [comment]
This is excellent. I really do appreciate the insight. At this point, I'm mostly trying to learn about how everything pulls together. I'll take your advice and look for a "better" copy of the game.

Thanks again!

**Comment by viniciusccarvalho** [comment]
I'm also having issues with loading Rondo of Blood TG 16 on openemu. I have the latest 2.0.5 version, I can load SegaCD games with cue files with no issue, but no luck with rondo of blood:
```
FILE "Akumajou_Dracula_X_-_Chi_no_Rinne_(NTSC-J)_[KMCD3005]_[T+Eng].bin" BINARY
  TRACK 01 AUDIO
    INDEX 01 00:00:00
  TRACK 02 MODE1/2352
    PREGAP 00:02:00
    INDEX 00 00:48:65
    INDEX 01 00:49:65
  TRACK 03 AUDIO
    PREGAP 00:02:00
    INDEX 01 03:05:14
  TRACK 04 AUDIO
    INDEX 01 04:51:48
  TRACK 05 AUDIO
    INDEX 01 05:54:67
  TRACK 06 AUDIO
    INDEX 01 07:31:09
  TRACK 07 AUDIO
    INDEX 01 08:54:61
  TRACK 08 AUDIO
    INDEX 01 09:59:35
  TRACK 09 AUDIO
    INDEX 01 12:57:60
  TRACK 10 AUDIO
    INDEX 01 14:41:28
  TRACK 11 AUDIO
    INDEX 01 17:22:05
  TRACK 12 AUDIO
    INDEX 01 19:03:58
  TRACK 13 AUDIO
    INDEX 01 21:34:18
  TRACK 14 AUDIO
    INDEX 01 24:01:69
  TRACK 15 AUDIO
    INDEX 01 27:41:51
  TRACK 16 AUDIO
    INDEX 01 30:07:10
  TRACK 17 AUDIO
    INDEX 01 33:22:56
  TRACK 18 AUDIO
    INDEX 01 34:52:29
  TRACK 19 AUDIO
    INDEX 01 36:34:49
  TRACK 20 AUDIO
    INDEX 01 38:34:50
  TRACK 21 AUDIO
    INDEX 01 42:36:12
  TRACK 22 MODE1/2352
    PREGAP 00:02:00
    INDEX 00 46:49:62
    INDEX 01 46:50:62

```

There's no feedback from the emulator as if there's any error importing. That would be nice to see what's wrong with the ROM. I've checked my Library folder and I don't have any roms with that name,.just in case someone wonders if deleting files would work.

Any ideas?

**Comment by clobber** [comment]
@viniciusccarvalho I believe I've acquired that same dump+romhack and it imports just fine.

MD5 hash of the binary:
`MD5 (/Akumajou_Dracula_X_-_English_Patched_BINCUE/Akumajou_Dracula_X_-_Chi_no_Rinne_(NTSC-J)_[KMCD3005]_[T+Eng].bin) = cd17d191fad41cb5e5a91e0960b43970`

Simply drag and drop in the `Akumajou_Dracula_X_-_Chi_no_Rinne_(NTSC-J)_[KMCD3005]_[T+Eng].cue` cue sheet file to import the game.

The only way the game could not import, is if your Game Library already contains that binary with the exact same hash.

**Comment by viniciusccarvalho** [comment]
@clobber Gosh, same MD5 here, still can't import. I removed all the entries from TG-16 library but still nothing happens when I drag the cue file into the TG-16 games panel.

Any other ideas?

Thank you

**Comment by viniciusccarvalho** [comment]
Ah, never mind. So stupid on my end, did not realize there was a separate entry for TG16-CD
