### ISSUE TITLE
'Native resolution' screenshots are not native resolution

### ISSUE THREAD

**Issue by okdana** [OpenEmu/OpenEmu#874]
Presumably related to #204 and/or #845:

Using the debug option to take screenshots at native size, i am not actually getting the screenshots at native size. Rather, i am getting them at native size plus/minus OpenEmu's aspect ratio corrections.

Example:

When i take a screenshot of a PC Engine game using stand-alone mednafen at 1x scale, i get an image with resolution 256x232.

When i take a screenshot of the same game using OpenEmu's mednafen core (and the native resolution option turned on), i get an image with resolution 310x232.

I get similar non-native resolutions with Mega Drive, SFC, and Famicom screen captures.

In addition to the incorrect resolution, there is also (for most cores) an unattractive 'feathering' effect on one edge of the image. I'm guessing that's probably an artefact of the scaling method used.

Anyway i assume all of this difference is due to the aspect ratio junk in `OEGameView`'s `nativeScreenshot`.

**Comment by ChampionReed** [comment]
Help me: I took a screenshot. Nothing happened. Do you know where it is saved, and if anything should have came on screen when it did?

**Comment by livid** [comment]
For the same NES game ROM, the native resolution screenshot from RetroArch is 256x224, but 256x240 from OpenEmu?
