### ISSUE TITLE
USB OverDrive compatibility with OpenEmu

### ISSUE THREAD

**Issue by ionull** [OpenEmu/OpenEmu#876]
I can bind betop controller key to keyboard system wide on OS X 10.9.
But it is not working in OpenEmu.
Please optimize this, thanks for your hard working :)

**Comment by Monomeeth** [comment]
There does seem to be a conflict issue with USB Overdrive and OpenEmu. Sure you don't need USB Overdrive to use many controllers etc with OpenEmu, but if you DO need it for some other reason then it still needs to be installed. Seems just having it installed is causing problems.

In my case I have a Gravis GamePad Pro that I've used successfully with USB Overdrive for playing games on the Mac. However, no matter what I did, I couldn't get it to work with OpenEmu while USB Overdrive was installed. 

OpenEmu could recognise and list it, but whenever I tried using it for a game it just wouldn't work. The only way to get it to work was to full uninstall USB Overdrive AND restart the Mac. Just disabling it wouldn't do it. Anyway, after that the Gravis GamePad Pro worked perfectly with OpenEmu. Only problem is that I need USB Overdrive to use the gamepad for other games.

One thing I didn't try was restarting the Mac after disabling the gamepad in USB Overdrive, so I will reinstall USB Overdrive and see whether disabling the device while using OpenEmu will work if I restart the computer. Hopefully that works, although it's still inconvenient if you need to do a restart every time you want to switch between using the controller in OpenEmu or another game.
