### ISSUE TITLE
Game Library location change does not work as expected.

### ISSUE THREAD

**Issue by Thinkscape** [OpenEmu/OpenEmu#916]
### Reproduce steps
1. Install OpenEmu
2. Go to preferences
3. Change Game Library path (i.e. `/foo/bar`).
4. (optionally) close and relaunch app
5. Import games.
### Expected

The newly selected path (i.e. `/foo/bar`) contains `Library.storedata`, `Artwork` and `roms` with respective files inside.
### What happens instead

Roms are copied to new path (`/foo/bar`) but Artwork and the main database stays in `~/Library/Application Data/OpenEmu/Game Library`

I've tried closing the app and manually moving db, but this does not work and it still re-creates fresh db in the default "Application Data" folder. Is this a bug? Is there a way to change game library location ?

**Comment by mprintz** [comment]
I am also having this issue. I want to also move my game library to my dropbox folder and not the default location. My app freezes when I select change library. Also freezes when I hold alt when opening the application and selecting choose library.

Still love the application! It's great. Just want to change location to be able to use same share on two computers.

thanks
