### ISSUE TITLE
Multiple DualShock 4 controllers not working

### ISSUE THREAD

**Issue by macboy6** [OpenEmu/OpenEmu#922]
When using one DualShock 4 controller for Player 1 and another for Player 2, the D-Pad will not function for Player 2.  Restarting OE or Mac does not fix this issue.  Unsure whether this issue is specific the using multiple DualShock 4 controllers, or if it's due to identical controllers being used in OE.

**Comment by davidedwardclark** [comment]
No, this issue has not been resolved. I have two DS4 controllers and the second one does not work. I am using the latest version of OpenEmu Experimental.

**Comment by tedostrem** [comment]
+1
