### ISSUE TITLE
Roms won't load after Mac restart

### ISSUE THREAD

**Issue by extracampine** [OpenEmu/OpenEmu#925]
I have just downloaded the latest version of OpenEmu and have the following problem: after I restart my Mac and try and run a rom, I get the following 2 error messages;
1. The operation could not be completed. No other information is available about the problem.

Then, when I click OK, I get:
1. Couldn't communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again.

Quitting and relaunching doesn't fix the problem.

If I add roms before restarting, these roms work fine. But after a restart, they won't work.

The roms are stored on a network drive (NAS) which connects automatically via wifi on logon to the mac. I don't know if this has anything to do with it, but I wonder. In OpenEmu there does not appear to be any way to see the ROM path. There is an option to "open in finder" - when I click this when the problem is occurring, nothing happens.

Paste from console:

30/12/2013 00:15:26.372 OpenEmuHelperApp[340]: parent application is: OpenEmu
30/12/2013 00:15:26.377 OpenEmuHelperApp[340]: bad ROM path or filename
30/12/2013 00:15:26.378 OpenEmu[294]: Warning: Exception caught during decoding of received reply to message 'loadROMAtPath:usingCorePluginAtPath:systemPluginPath:completionHandler:', dropping incoming message and calling failure block.

Exception: **\* -[NSXPCConnection initWithListenerEndpoint:]: Endpoint argument is NULL.
30/12/2013 00:15:26.378 OpenEmu[294]: -[NSAlert alertWithError:] called with nil NSError. A generic error message will be displayed, but the user deserves better.
30/12/2013 00:15:26.378 OpenEmu[294]: Helper Connection (0x608000669d80) failed with error: Error Domain=NSCocoaErrorDomain Code=4101 "Couldn’t communicate with a helper application."
30/12/2013 00:15:27.762 OpenEmu[294]: Deallocating proxy: <OEThreadProxy 0x6080004589f0, target: <OEGameDocument 0x6080001b73e0, ROM: '8 Eyes (USA)', System: 'openemu.system.nes', Core: 'org.openemu.Higan'>>

Any help appreciated!!

**Comment by beeksiwaais** [comment]
Hi,

Sorry to reopen this issue but does OpenEmu support AFP or CIFS and NFS ?
