### ISSUE TITLE
Feature Request: Rapid Fire buttons

### ISSUE THREAD

**Issue by xthenkx** [OpenEmu/OpenEmu#933]
A nice feature to add would be the ability to have a Turbo Controller or the ability to add turbo buttons to the keyboard or gamepad for the NES emulator. In games that require serious button mashing (Gun Smoke) this feature would only require the button to be pressed and held down to get the desired effect. This is not to be confused with Turbo mode or Fast Forward.

**Comment by clobber** [comment]
We've worked out an acceptable UI-less solution for rapid fire button toggling, that can be used by any system and is modeled after classic gamepads with rapid fire/turbo/auto toggle buttons. This will leverage our global "special keys" system and require no UI work. The full specs are listed at the project link below. Pull requests welcome on this one.

https://github.com/OpenEmu/OpenEmu/projects/1

**Comment by superarts** [comment]
Excuse me but the "Rapid Fire Toggle" feature mentioned above is not merged yet?

**Comment by clobber** [comment]
Open issue = not implemented. There is nothing to "merge" - that is just a project page with details.

**Comment by Scenx** [comment]
I am very sorry to have just seen this page. I am very happy that so many people need this feature. I hope that the author can add the "Rapid Fire" function as soon as possible.

**Comment by hoangnh228** [comment]
I wish the turbo buttons added :(

**Comment by Hegde-Sandesh** [comment]
still waiting for the turbo button, I don't want to build biceps by mashing on buttons

**Comment by daxeshpatel7224** [comment]
> Open issue = not implemented. There is nothing to "merge" - that is just a project page with details.

Hello, 

Can you please implement this feature? or at least this "Rapid Fire Toggle" workaround?

**Comment by Thornchg** [comment]
So, how long does this feature take to achieve?

**Comment by shysaur** [comment]
Implemented in db5f63ac.

**Comment by daxeshpatel7224** [comment]
Wow great. Excited to download the latest version of OpenEmu. 
Please release the new version with this feature.

**Comment by michaelahlers** [comment]
Whoot! Been watching this ticket for years. Dreams _do_ come true! 😁
