### ISSUE TITLE
bug: OE forces pop-out window after OpenEmuHelperApp has crashed in non-pop-out mode

### ISSUE THREAD

**Issue by okdana** [OpenEmu/OpenEmu#935]
Normally, i use the non-pop-out mode when i play games. Several times, the game (i.e., OpenEmuHelperApp) has crashed. When this happens, the window goes with it, and an error pops up saying that it can't communicate with OpenEmuHelperApp. To get the window back, i have to go to Window > OpenEmu.*

After doing this, everything works fine, except for one thing — OE forces me into the pop-out mode for the remainder of the session. The option in Preferences remains unticked, so there is apparently nothing i can do to go back to non-pop-out mode except restart the application.

\* Actually, this should probably not even happen, it should bring the window back for me

**Comment by shysaur** [comment]
Fixed in f5f9e3be.
