### ISSUE TITLE
Too many cores show in the list on start

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/OpenEmu#944]
Running the experimental build shows a whole bunch of consoles in the left side, even if you have no games for them.

It's nice we got so many and all, but maybe a cleaner presentation wouldn't show them until you add games? I'm just not going to play any FDS ROMs that I know of.

**Comment by tonylukasavage** [comment]
I definitely agree with @SuperCritic here. An option to only show emulators with ROMs would be ideal. It's the first option I went looking for once I installed ROMs on more than one emulator.

**Comment by clobber** [comment]
> Last post was 2013, better bump it

Yeesh. Not adding a needless pref here. You have two great options:

* Right click on "Consoles" in the sidebar and deselect the ones you don't want.
* Go to  OpenEmu > Preferences > Library and deselect the ones you don't want under "Available Libraries"
