### ISSUE TITLE
Turbo mode

### ISSUE THREAD

**Issue by Winzor** [OpenEmu/OpenEmu#95]
In the Original VBA, users were able to speed up the playback of the emulation (usually to about 300-400%), by pressing a key (which by default was spacebar, but was configurable). I was incredibly disappointed not to see this in OpenEmu, as I hate sitting through long boring cutscenes as much as the next guy. I'd love seeing this functionality implemented at some point, either as it was in VBA or as a - + configuration which could increase or decrease playback by a set interval.

**Comment by ArmyBox1** [comment]
I am having a lot of problems with the speed button. When I press the key, the game with surge in and out of FF/Turbo mode. It makes it mush harder to play, especially when I need to fast forward through things. Please send help
