### ISSUE TITLE
Reduce input lag (pre-rendering and post-rendering issues)

### ISSUE THREAD

**Issue by mrvacbob** [OpenEmu/OpenEmu#953]
Currently we read input in the app and send it to the cores.
- DO uses .001s (less than 1/60 sec) which is okay I guess.
- XPC uses about 1/60 sec latency which is a loss of 1 frame :(

It looks like XPC receives the message on a secondary thread in a core, then OEThreadProxy sends it to another thread, which wastes some scheduler quantums.

Rather than optimizing that, why don't we just read input in the core process?

The video-output side latency is likely a worse problem, have not measured yet.

**Comment by astrange** [comment]
Basically the core should be hosting the whole window itself.

**Comment by clobber** [comment]
Notes from previous discussions:

How we currently share IOSurfaces (with each step having 1 screen update between them):
1. Core writes to surface
2. App reads surface, applies shader, writes window
3. WindowServer reads window, updates screen


Optimizations (output):
- 2D Cores: no reason to use GL when we can just write to an IOSurface.
- CVDisplayLink for app and Cores adding 1 frame delay?
- Drop Cg support so we're not restricted to GL2. This means converting all the shaders in-use back to GLSL.
- Core/HelperApp: switch to GL3 core profile, possibly front end too
- GL: remove immediate mode and move to buffers

Optimizations (input):
- Remove OEThreadProxy system and set XPC's target queue to be the one the game core runs in?
- XPC communication has increased latency when it shouldn't. Usually suggested to move input to the Core process.

**Comment by astrange** [comment]
To be clear, "immediate mode" just means GL2.

Since IOSurfaces have cpu-writable buffers when locked, just drawing the game straight into it should be faster, but it all depends on the GPU driver. So benchmarking a few different ways is best.

**Comment by franktinsley** [comment]
Wish I could contribute to a fund so you guys could quit your days jobs and work on this. :)

**Comment by clobber** [comment]
Optimizations (output):
✓ 2D cores write direct to IOSurface (though not yet enabled)

Optimizations (input):
✓ Input events are now handled in the core process! 6eeda41cec0f1c8fdd37f3e5486496154a9d9160 

Note: OEThreadProxy is still used but it doesn't go through the XPC connection.That could still be improved.

**Comment by clobber** [comment]
OpenEmu 2.1.
