### ISSUE TITLE
OpenEmu keeps slowing down/lagging.

### ISSUE THREAD

**Issue by whatproblems** [OpenEmu/OpenEmu#963]
OSX Version 10.9.1
2GB RAM, 2.26 Dual Core Intel.

First off, great program. It ran fine for a few days, recently though, it's just been lagging extremely bad and running very slow. I've mainly been using it to play old GameBoy Color and NES games.

It ran flawlessly but now is just giving me a ton of problems, to the point where I just can't play it at all. Any ideas on how to fix it on my end?
- Thanks

**Comment by ArmyBox1** [comment]
I am having a lot of problems with the speed button. When I press the key, the game with surge in and out of FF/Turbo mode. It makes it mush harder to play, especially when I need to fast forward through things. Please send help
