### ISSUE TITLE
Logitech f310 problems

### ISSUE THREAD

**Issue by animalrap** [OpenEmu/OpenEmu#964]
It recognizes the gamepad, but it won't take any input. The same gamepad has worked with other emulators on my mac in the past.

**Comment by MillerBoss** [comment]
For anyone searching Google and come here what @ghost said above works. 
macOS 10.14.2 Beta OpenEmu 2.0.7
Confirmed working with a Logitech Gamepad F710.
Switch to D. Unplug from Mac and plug back in. 
OpenEmu > Preferences > Controls > Input will show the device
