### ISSUE TITLE
Snes drops fps sometimes

### ISSUE THREAD

**Issue by aronkihui** [OpenEmu/OpenEmu#967]
Only snes9x, and visual boy advance have a fps drop sometimes.

**Comment by LordHDL** [comment]
Just want to point out this issue still happens, and not just for SNES.  Here's an example video with flickering every frame (makes it easy to see the drops): https://www.dropbox.com/s/wqwgod51utpj00r/OpenEmu%20FPS.mp4.zip?dl=0

My GPU is AMD Radeon 6750M.  I use Nearest Neighbor.

**Comment by clobber** [comment]
Hi @LordHDL and @aronkihui (if you're still around). Could you run this small app so I can get the refresh rate of your display? Just unzip and then right click and select open to run http://cl.ly/3M3L1F1D0y41 -- then paste the result back here please.

**Comment by LordHDL** [comment]
That's a nifty piece of software, thanks.  Here's my rate:

![screen shot 2015-03-21 at 8 40 44 am](https://cloud.githubusercontent.com/assets/5182602/6765129/1404462e-cfa9-11e4-8f6e-51825c453d74.png)

**Comment by aronkihui** [comment]
The point is that on Snes9x standalone everything go smoothly and without random frame drops. Something is wrong in Snes9x/Higan cores, all other system work very smooth, even the more expensive ones like PSX or DS.

**Comment by mrvacbob** [comment]
If it's due to pixel formats, the remote-layer branch will help. That will get done when it's done.

Different cores have slightly different FPS also, and a mismatch with the screen FPS could cause a drift.

**Comment by Scapetti** [comment]
Any progress on this? Syncing the refresh rate to the monitor?
