### ISSUE TITLE
Rewind cores

### ISSUE THREAD

**Issue by punkhop** [OpenEmu/OpenEmu#974]
One of my favorite features of Retroarch is the rewind function - I'd love to assign this to one of the trigger buttons on my controller. Is this possible in OpenEmu, and if not, pleeeease add it!

**Comment by cyco** [comment]
It's coming :)

**Comment by clobber** [comment]
Rewind will be available in the next release.

**Comment by Njordy** [comment]
Can you list cores what support this feature?
