### ISSUE TITLE
No Cores

### ISSUE THREAD

**Issue by JRMN1** [OpenEmu/OpenEmu#998]
I tried using running the app on my MacBook and my iMac, but I can’t get it to work. When I try to drop ROMs in the app window it doesn’t do anything. I’ve also tried changing the library location and when I go to preferences under available libraries I see exclamation points next to all and cores.  Also in the cores tab, I don’t see any cores listed. I tried deleting the app but it seems to remember my preferences.  What am I doing wrong?

**Comment by Bmorr1123** [comment]
@jmragin How did you get your network monitor to stop blocking OpenEmu? I am having the exact same issue.

**Comment by jmragin** [comment]
My network monitor prompts me whnever app tries to phone home
(incoming/outgoing traffic).  It was just a matter of creating a global
rule to allow OpenEmu to connect to its proper services.
